### ISSUE TITLE
Homepage -- implement on Janis

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#100]
This task was completed as https://github.com/cityofaustin/janis/issues/33

Noting that some homepage components that need update will be addressed as separate issues:
- 311
- header footer styling/colors 
- Choose Language Banner #148 
- Global Navigation #106

**Comment by mateoclarke** [comment]
@cthibaultatx, will you make sure that we get a new issue created in the backlog to update the 311 component and header footer styling/colors based on new mocks? Other than that, the remaining tasks to update the homepage have been logged in separate issues afaik.
