### ISSUE TITLE
Performance review OPO form & microsite

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1000]
- [ ] Microsite
- [ ] Form

**Comment by amenity** [comment]
Basically page-load-speed. You can use [this Google tool](https://developers.google.com/speed/pagespeed/insights/) to assess. More context on all of these in the [Testing and QA folder](https://drive.google.com/drive/folders/1KqmfEe7_WWwcVjY2HFm0nx-xzR_1_HyO).

**Comment by easherma** [comment]
Testing on slow 3G is...not great: 
https://www.webpagetest.org/result/190326_QG_2302e7a4c5c424b014906ac6ec67b3ff/

**Comment by easherma** [comment]
![google_audit](https://user-images.githubusercontent.com/10539855/55037734-af186b00-4fec-11e9-8b1e-dcedf1681caf.png)
Google audit simulating 3g

**Comment by oliver2g** [comment]
closing this issue since testing is complete and new issues have been created
