### ISSUE TITLE
Police Oversight form: Implement Hotjar on form

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1002]
https://www.hotjar.com/

[Installation instructions](https://help.hotjar.com/hc/en-us/articles/115009336727).

**Comment by amenity** [comment]
Slacked credentials to @easherma...they'll be in the [ODD-ops wiki](https://github.com/cityofaustin/odd-ops/wiki) soon, too.

**Comment by easherma** [comment]
Our current build means we have index.html in the public folder, but also in the travis folder @sergiogcx uses for builds. For now, that probably means making the same changes to two places at once, but we'll want to streamline that for the future.

**Comment by amenity** [comment]
See https://github.com/cityofaustin/techstack/issues/1214
