### ISSUE TITLE
Police Oversight Form: Implement name changes for subdirectories

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1006]
Right now the URLs will read `forms.austin.gov/police-oversight-complaint` and `forms.austin.gov/police-oversight-compliment`.

**Comment by sergiogcx** [comment]
This issue has now been completed and it is ready for review:


Code (now we can specify a name for the directory):

```
{
	"forms": [
		{"url": "https://github.com/cityofaustin/officer-thank-form", "directory": "police-oversight-compliment"},
		{"url": "https://github.com/cityofaustin/officer-complaint-form", "directory": "police-oversight-complaint"}
	]
}
```

The magic happens here:
https://github.com/cityofaustin/forms-service-deploy/blob/849375ab2452effb4239a4971bdaab3b0b354e6b/.travis/aws-helper.sh#L147


Production:
https://d1tox4tz6kpvtt.cloudfront.net/police-oversight-compliment/
https://d1tox4tz6kpvtt.cloudfront.net/police-oversight-complaint/

Staging:
http://police-monitor-website-staging.s3-website-us-east-1.amazonaws.com/police-oversight-compliment/
http://police-monitor-website-staging.s3-website-us-east-1.amazonaws.com/police-oversight-complaint/

**Comment by sergiogcx** [comment]
Ready for review @amenity @briaguya ! :)
