### ISSUE TITLE
Police Oversight Form: Obtain and apply SSL certificate for Forms.austin.gov

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1007]
Aha! Link: https://desi1.aha.io/features/RT-116

**Comment by sergiogcx** [comment]
SSL Set up for both domains:

Production:
https://forms.austin.gov/

For production I created a temporary SSL certificate that will be working for up to 2 years whilewe wait for Amazon to issue theirs (which is better). That process can take a while, but I will be keeping track.

Staging: (uses an existing certificate)
https://forms.austintexas.io/

**Comment by amenity** [comment]
Closing this, but learned we need to update our account vendor. https://github.com/cityofaustin/techstack/issues/1205

**Comment by sergiogcx** [comment]
It's live now! :)

![Screen Shot 2019-02-20 at 1.34.34 PM.jpg](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/e4fb3fe7-8287-466c-9cd2-af136b63307b)

**Comment by amenity** [comment]
🙌
