### ISSUE TITLE
Police Oversight Form: Implement map/location component design refinements

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1012]
![b2 what happened 2x](https://user-images.githubusercontent.com/1463708/50858594-71ddfe80-1356-11e9-8b35-7dc4486071fd.png)

- Text box in map
- Empty location box
- 5-7 predictive suggestions (can cover map)
- Zoomed to ~extent of Austin
- No pin until typing begins

@toribr will ask test familiarity of the use-my-location icon

**Comment by easherma** [comment]
component is located in https://github.com/cityofaustin/usfs-components/

**Comment by amenity** [comment]
PR: https://github.com/cityofaustin/usfs-components/pull/3

**Comment by amenity** [comment]
Will close when it's deployed to Storybook or the live form.
