### ISSUE TITLE
Police Oversight form: Design "Thank you" form

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1020]
Set of mocks for the "Thanks" form. 

[Here's the copy](https://docs.google.com/document/d/1dwY2kacSrGaP0Up-Y0PtLI_u7BX75sQk_14XlX9sH5Y/edit).

**Comment by chasechenevert** [comment]
Checking in on this, I could create this quickly, but given that the pages of the form are identical (excluding landing and confirmation pages) should I still put this into mocks for the Devs? I'm happy to, just wanted to see what's preferable/helpful.

**Comment by amenity** [comment]
@chasechenevert - I don't think you need to. @easherma - thoughts?

**Comment by toribr** [comment]
@chasechenevert Let's go ahead and make a mock, removing the sharing files and witnesses chapters. If you'll upload your latest I could also do it.

**Comment by chasechenevert** [comment]
## OPO Thank you form

- [Design: OPO Form and email dev spec](https://xd.adobe.com/spec/bf7944c2-69b2-444f-6f10-e3e27f0f47a3-c948/) (single file with compliment, complaint, and email).
- Original Content doc that I worked from: [Office of Police Oversight > Thank you form](https://docs.google.com/document/d/1dwY2kacSrGaP0Up-Y0PtLI_u7BX75sQk_14XlX9sH5Y/edit)

![screen shot 2019-02-05 at 8 54 02 am](https://user-images.githubusercontent.com/7027270/52281369-9f9d6f80-2923-11e9-8962-b2eaebc775e5.png)
