### ISSUE TITLE
Police Oversight form: Implement MVP urls

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1024]
URLs will read
forms.austin.gov/police-oversight/complaint
and
forms.austin.gov/police-oversight/thanks

**Comment by sergiogcx** [comment]
I like the idea, I will have the forms' urls renamed today.

**Comment by sergiogcx** [comment]
This is ready for review:

Staging URLs:
http://police-monitor-website-staging.s3-website-us-east-1.amazonaws.com/police-oversight/complaint
http://police-monitor-website-staging.s3-website-us-east-1.amazonaws.com/police-oversight/thanks

Production URLs (as of this moment):

**Comment by amenity** [comment]
Looks good to me. @easherma @briaguya ?

**Comment by briaguya** [comment]
Looks good to me!

**Comment by sergiogcx** [comment]
This issue can be closed! :)
