### ISSUE TITLE
Identify content for Information Page MVP mocks

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1027]
Choose a page of OPO content for Chase to use in his Information Page MVP mocks. The content does not need to be finalized! It should just be representative, structurally, of the Information Page content type. 

(The Permitting content [we chose](https://github.com/cityofaustin/techstack/issues/909) in November for the Information Page content type is much more complex than the basic content we need for OPO pages.)

**Comment by srigdon** [comment]
@chasechenevert Here's a page of OPO web content that fits the Information page type: https://docs.google.com/document/d/1UFLOvMU75FIhLdHdu2qJl4n7QqaFnQb5-lVj1S0AJHM/edit 

Warning: it's a wall of text. Let me know if you need any more information or content.
