### ISSUE TITLE
Global Nav -- Content Review

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#104]
Thursday, 3/8, 1.5 hours
Review design mocks with content team

**Comment by courtneyjacinic** [comment]
@toribr @cthibaultatx what is the purpose of this task? To review content? For the content team to review design mocks? Does this require a meeting or do we just need design to send mocks? Do we need a task for Design to send us the mocks?

**Comment by cthibaultatx** [comment]
@courtneyjacinic @ifsimicoded @toribr global navigation is part of the homepage update @mateoclarke has been working on
