### ISSUE TITLE
Police Oversight form: Update content and components

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#1040]
- [x] [aboutYouChapter.js](https://github.com/cityofaustin/officer-form-chapters/blob/master/src/aboutYouChapter.js)
- [ ] [howYouFoundUsChapter.js](https://github.com/cityofaustin/officer-form-chapters/blob/master/src/howYouFoundUsChapter.js)
- [x] [officerDetailsChapter.js](https://github.com/cityofaustin/officer-form-chapters/blob/master/src/officerDetailsChapter.js)
- [x] [shareEvidenceChapter.js](https://github.com/cityofaustin/officer-form-chapters/blob/master/src/shareEvidenceChapter.js)
- [x] [whatHappenedChapter.js](https://github.com/cityofaustin/officer-form-chapters/blob/master/src/whatHappenedChapter.js)
- [x] [witnessDetailsChapter.js](https://github.com/cityofaustin/officer-form-chapters/blob/master/src/witnessDetailsChapter.js)

**Comment by easherma** [comment]
Noting for later: look into modifications to the us-form-system/JSON schema flow such as updating copy for buttons, adding supplementary explanation forms.

**Comment by easherma** [comment]
@amenity @toribr the 'how you found us' section seems to not be in the mock anymore. Should I just nix it?

**Comment by toribr** [comment]
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
