### ISSUE TITLE
Police Oversight form: update intro & chapter order

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#1041]
- [ ] [Complaint form intro](https://github.com/cityofaustin/officer-complaint-form/blob/master/js/components/Introduction.jsx)
- [ ] [Complaint form chapters](https://github.com/cityofaustin/officer-complaint-form/blob/6dc0c95a67b38be0f21fa9a276d78d33ba29d2ca/js/config/form.js)
- [ ] [Thanks form intro](https://github.com/cityofaustin/officer-thank-form/blob/master/js/components/Introduction.jsx)
- [ ] [Thanks form chapters](https://github.com/cityofaustin/officer-thank-form/blob/master/js/config/form.js)

**Comment by easherma** [comment]
1. Landing page
2. Tell us what happened
3. Share your photos or videos
4. Tell us about the officer(s)
5. Tell us about the witnesses
6. Tell us about you (optional)
7. Review your answers before submitting
8. Success (edited)

**Comment by amenity** [comment]
(turned out we already had them in the right order, the mocks were off.)
