### ISSUE TITLE
Police Oversight form: Add calendar icon to date/time field

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1057]
CTX Floods has this done already.

Aha! Link: https://desi1.aha.io/features/RT-105

**Comment by amenity** [comment]
@Niicck - can you point us to the code/assets y'all have adding a calendar icon to a date/time field?

**Comment by Niicck** [comment]
Here's my source code for adding a little calendar emoji:
https://github.com/cityofaustin/ctxfloods/blob/dev/src/components/Shared/Emoji/index.js
And its used like this:
```
<Emoji symbol="📅" label="calendar"/>
```

Is that what you were looking for?
