### ISSUE TITLE
Police Oversight form: Style tweaks pre- Sprint Review

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1058]
In order of priority:
- [ ] ~Intro page~ #1051 
- [ ] ~Review page~ #1013 
- [x] Reduce spacing between fields and field labels, e.g. "Location, if known" is right next to the description field. Should be 20px. 
- [x] Add 40px bottom-margin after the field/form component
- [x] Debug location component not displaying correctly outside usfs-components repo

**Comment by easherma** [comment]
https://github.com/cityofaustin/techstack/issues/1051 for intro
