### ISSUE TITLE
Look into better multi-repo organization

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1068]
While it's really cool to think we'll just have everything published on NPM so we can pull it into any new project, it seems to be making development at this stage overcomplicated.

It'd be cool to look into reorganization using submodules like how OpenEmu uses them for the emulator cores (https://github.com/OpenEmu/OpenEmu)

**Comment by easherma** [comment]
Just FYI, it might also be worth considering subtrees or a monorepo. There are a couple articles that do decent overviews of some common gotchas:

https://andrey.nering.com.br/2016/git-submodules-vs-subtrees/

https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/

I’ve used submodules before and also gone with a monorepo structure.
