### ISSUE TITLE
Identify information pages for resource recovery

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1070]
https://airtable.com/tblZogjLILtjQQuaJ/viwEr4exYRsg7mfr0

**Comment by annieszot** [comment]
1/29/19 AS completed #1070
https://airtable.com/tblZogjLILtjQQuaJ/viwEr4exYRsg7mfr0

**Comment by annieszot** [comment]
Adding Laura Trujillo back on to ask if I close or she closes and if need to check on how pages were identified.
