### ISSUE TITLE
Screener in 4 languages for alpha usability participants

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1077]
Laura knows where some previous surveys are - just need to find them, and make sure they contain all the questions that we need.

Aha! Link: https://desi1.aha.io/features/RT-98

**Comment by LauraTrujillo** [comment]
@toribr https://drive.google.com/drive/folders/1w6PAEDRQCyswYNACBQwNsTNIXn5xkVIt
Does this help?

**Comment by kriskristin** [comment]
@LauraTrujillo @toribr 

How have been translating in the past? Is there someone I can reach out to for Vietnamese and Arabic translations?

**Comment by LauraTrujillo** [comment]
@kriskristin We have a company we've worked with: Language and Content
Our contacts are: Adriana Urgelles (aurgelles@languageandcontent.com) and Addy Miro (addymiro@languageandcontent.com). 
I send them a Word doc of what we need translated (highlighting anything that does NOT need to be translated) and let them know the languages and a little note about how great it would be to have the translations back by whatever date.
