### ISSUE TITLE
OPO form: sharing evidence

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1079]
Please remove the red "*required" text from Evidence, Officers and Witness chapters. All info in those chapters is optional.

**Comment by easherma** [comment]
@briaguya I think this brings us back to the issue with usds, no? We need to mark the Yes/No as required, which is not the same as evidence _being_ required. However, us forms system automagically adds that 'Required' text, right?

**Comment by toribr** [comment]
I never really liked this YES/NO interaction but since it was the default, and happened while I was gone,  It got designed that way. We could set a default for the pages where it's optional. Ie, evidence and witnesses and officers set to no. However, this may unintentionally set bias.
