### ISSUE TITLE
Police Oversight form: Investigate non-local storage for confirmation page.

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/techstack#1083]
Currently the officer complaint form uses localstorage to pass the confirmation case number from the form configuration to the confirmation page.

I spent some time trying to think of better ways to pass that number (ie. React props, or even through the USDS formConfig object; however, there isn't a lot of documentation is provided and cannot spend too much time on this.

For now localStorage will suffice.

Aha! Link: https://desi1.aha.io/features/RT-95

**Comment by sergiogcx** [comment]
This may no longer be necessary, we are now using localStorage to store the form submission to allow the user to enter the email at the confirmation page.

So there are now at least two uses for localStorage.

**Comment by easherma** [comment]
+ 1, don't see the downside to localStorage for this? Eventually we may even want the ability for someone to come back to a form to finish filling it out later

**Comment by sergiogcx** [comment]
At first I was not comfortable using localStorage, but now we also use it for storing form data for 2nd submission at the confirmation page, making this issue irrelevant.

Best if closed in my opinion,
