### ISSUE TITLE
Redirect http to https 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1085]
**Describe the bug**
When I navigate to `http://alpha.austin.gov` — or to`austin.texas.gov` without explicitly prepending `https://` — the page hangs indefinitely. 

**Device**
Macbook Pro, MacOS Mojave

**Browser**
Chrome, Firefox, Safari

Hopefully just updating the .htaccess file? 😬

**Comment by amenity** [comment]
One hour later and I can't reproduce. 🤷‍♂️

**Comment by sergiogcx** [comment]
Oh, I just saw it is closed. Well Let me know if I can help at any time.

**Comment by amenity** [comment]
@briaguya happening again today.

**Comment by amenity** [comment]
@sergiogcx  - would you add a size & estimate to this, please? 🙏 👕 
_XS --->1, S--->2, M--->3, L--->5, XL --->8_

**Comment by amenity** [comment]
Might just be npm package

**Comment by sergiogcx** [comment]
Accomplished yesterday by moving DNS records to cloudfront:

```
$ curl -IL http://alpha.austin.gov
HTTP/1.1 301 Moved Permanently
Server: CloudFront
Date: Thu, 28 Feb 2019 10:55:45 GMT
Content-Type: text/html
Content-Length: 183
Connection: keep-alive
Location: https://alpha.austin.gov/
X-Cache: Redirect from cloudfront
Via: 1.1 966f5fd0c86bd4e9f829fca8c1e569b8.cloudfront.net (CloudFront)
X-Amz-Cf-Id: sLArLWlsmyhEdDcAVQ4QXw76yeVYD1xQvkfd9n13ku7BUWsQWAljQQ==

HTTP/2 200
content-type: text/html
content-length: 90097
date: Wed, 27 Feb 2019 19:17:10 GMT
last-modified: Wed, 27 Feb 2019 15:38:08 GMT
etag: "d085c3a3241f35fb2a580b561a8719a0"
server: AmazonS3
age: 56317
x-cache: Hit from cloudfront
via: 1.1 12b95f4a8620bcfb6c85511fae926d57.cloudfront.net (CloudFront)
x-amz-cf-id: uHNK88AYqptjrF9WqcZS1r1Xt2s2HzRo8A06LlcBBwgYWpuLWiXPVg==
```

**Comment by amenity** [comment]
Splendid!! 👌
