### ISSUE TITLE
Police Oversight Forms: Implement USFS Components pipeline with NPM publish

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/techstack#1088]
Create a pipeline that whenever there is an update on the components, it builds, refreshes and publishes the library to npm.

https://github.com/cityofaustin/usfs-components
https://www.npmjs.com/package/@cityofaustin/usfs-components

Aha! Link: https://desi1.aha.io/features/RT-92

**Comment by amenity** [comment]
Not MVP and should be done in conjunction with group discussion on architectural approach.

**Comment by sergiogcx** [comment]
This is being done by @Niicck and @easherma
