### ISSUE TITLE
Police Oversight form: Implement general styles on the review page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1091]
![opo_b7 review_draft 9 2x](https://user-images.githubusercontent.com/7027270/50912425-bd94b480-13f7-11e9-8734-b2b96a1a78bd.png)

**Comment by amenity** [comment]
@chasechenevert @toribr - can be reviewed at https://opo-form.netlify.com/. Comment here if you see issues or have questions.

**Comment by toribr** [comment]
![screen shot 2019-02-01 at 3 44 22 pm](https://user-images.githubusercontent.com/3790067/52151314-4b9b3e00-2638-11e9-9c08-0db28412dc0c.png)
 This page title is missing from the review chapter

**Comment by toribr** [comment]
Submit button label is "Submit" not "Submit Application"
![screen shot 2019-02-01 at 3 45 52 pm](https://user-images.githubusercontent.com/3790067/52151380-87360800-2638-11e9-8617-ef7e25169af0.png)

**Comment by amenity** [comment]
Oh good, because 
![img_cd5478f4275d-1](https://user-images.githubusercontent.com/1463708/52151647-73d76c80-2639-11e9-8d36-e3c198479756.jpeg)

**Comment by amenity** [comment]
Looks good to me! Made https://github.com/cityofaustin/techstack/issues/1102

**Comment by amenity** [comment]
@easherma - are you going to open a PR forthat branch? ☝️

**Comment by amenity** [comment]
It's...complicated. But this is essentially merged.
