### ISSUE TITLE
Police Oversight form: Fix on-focus bug with map location field on mobile

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1093]
**To Reproduce**

1. Go to the "What Happened" page
2. Click on location text field 

**Current behavior**
The page zooms in slightly. This crops the text. Exiting the field input doesn't zoom back out. 

**Screenshots**

<img width="250" alt="img_1172" src="https://user-images.githubusercontent.com/1463708/52091535-57282f80-257a-11e9-8a6c-82f6f448421e.PNG">
<img width="250" alt="img_1172" src="https://user-images.githubusercontent.com/1463708/52091536-57282f80-257a-11e9-960c-dcf387311200.jpeg">

**Device**
iPhone 6S

**Browser**
Safari, Firefox

**Comment by easherma** [comment]
This zoom appears to happen whenever user focuses on any field of the form, but it's particularly noticed with the map

**Comment by amenity** [comment]
While this is [default iOS behavior](https://blog.osmosys.asia/2017/01/05/prevent-ios-from-zooming-in-on-input-fields/), it's not triggered by any of the other fields unless you zoom in/out first. 

What if we just increase the font size to 16px, @easherma ?

**Comment by easherma** [comment]
fixed in https://github.com/cityofaustin/officer-complaint-form/pull/17/commits/0d76ae38692130a34000b35f2c6f07ef96877486
