### ISSUE TITLE
Police Oversight form: Placeholder text for officers and witnesses

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1094]
Problem: When you click 'add officer' in the police complaint form, the minimized section for the already added officer has no text to identify what it is. This also happens when adding multiple witnesses.

It should say, "Officer 1, Officer 2, ..." "Witness 1, Witness 2, ..."

**URL tested:** https://forms.austintexas.io/police-oversight/complaint/officer-details

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/3c5e929b7afb75e526dd08c6ec229547b0e5a2d7/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/3c5e929b7afb75e526dd08c6ec229547b0e5a2d7/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Fofficer-details&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/officer-details) to reproduce the issue on Browserstack**

**Comment by briaguya** [comment]
After investigating this a bit I found that our OfficerDetailsDisplayWidget gets these props passed in:
<img width="359" alt="screen shot 2019-01-31 at 6 24 34 pm" src="https://user-images.githubusercontent.com/6384156/52094646-885a2d00-2585-11e9-9dec-d9aff4ff0eba.png">

I tried messing around with adding a hidden index field but that seems to be a bit overcomplicated and would make our schema pretty messy.

Another option would be to build out something within the review component using local storage, for example:
- Add a constructor that generates a unique ID for each component
- Store that unique ID in local storage and set an index based on how many others are in there

Not quite sure how well either solution would end up being.

Overall, this is a non-trivial change, so I'm estimating it as an L.

**Comment by easherma** [comment]
Also potentially relevant: https://github.com/usds/us-forms-system/blob/master/src/js/widgets/ArrayCountWidget.jsx

https://github.com/usds/us-forms-system/blob/master/docs/building-a-form/available-widgets.md#arraycountwidget

Looks like something we might be able to leverage at first glance.

**Comment by amenity** [comment]
Yeah, I was looking at the array count thing too - @briaguya - do you think that changes the size on this?

**Comment by easherma** [comment]
Should we close this for now? Seems like we've opted for 'blank' descriptions

**Comment by easherma** [comment]
I think this could tie into a redesign of the review page, but I'm going to close it for now.
