### ISSUE TITLE
Janis 2.0: Finalize Department Page MVP design

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1096]
Attach final department page comp and viz assets here.

**Comment by chasechenevert** [comment]
The most current version lives in the [Janis 2 stickersheet](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/9055635c-de21-497d-b8fb-631c3e39c802/Department-MVP-web-23/). This will be updated once we have the page content.
