### ISSUE TITLE
Janis 2.0: Home page visual design update

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1097]
Attach final comp for homepage and assets here.

**Comment by chasechenevert** [comment]
## Homepage MVP
- Not a real redesign, simply restyling existing data
- We will do a much bigger redesign of the homepage once we know what users want and need, and we have more information across the site

### Dev spec:
- [Desktop](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/9489fed6-9eac-42a2-8516-af855c6e9042/Homepage-MVP-Desktop/)
- [Mobile](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/ef2bb79c-50a2-4cfa-a016-6ee9cd61dd54/Homepage-MVP-Mobile-1/)

<img width="793" alt="Screen Shot 2019-04-04 at 11 06 49 AM" src="https://user-images.githubusercontent.com/7027270/55570830-de546980-56c9-11e9-8cf5-6f82d36ecc6a.png">
