### ISSUE TITLE
Write new form questions

### ISSUE THREAD

**Issue by juliazbyron** [cityofaustin/techstack#11]
- [x] Schedule review meeting with AAC (Julia)
- [x] [Determine/organize questions](https://docs.google.com/document/d/1JQgBdLGXkEF9sRGwI0Qad70EbSuyLkVcCUrpk5VtBXQ/edit?usp=sharing) (Julia)
- [x] Review organization @courtneyjacinic 
- [x] Draft questions copy (Julia)
- [x] Meet with AAC to review (Julia)
- [x] Incorporate AAC feedback (Julia)
- [ ] Refine copy @courtneyjacinic

**Comment by juliazbyron** [comment]
[Foster form questions for concept one](https://docs.google.com/document/d/1JQgBdLGXkEF9sRGwI0Qad70EbSuyLkVcCUrpk5VtBXQ/edit?usp=sharing)

**Comment by juliazbyron** [comment]
@courtneyjacinic The questions are ready for you to refine. There's a couple sections where I need extra help from you, which I noted (process and availability).

**Comment by juliazbyron** [comment]
@courtneyjacinic Also if you could make your changes as suggestions, I'm putting the copy into the prototype and it'll let me know where I need to edit it.

**Comment by courtneyjacinic** [comment]
@juliazbyron Working on this now! Will post when completed!

**Comment by courtneyjacinic** [comment]
@juliazbyron Comments in!
