### ISSUE TITLE
Police Oversight form: Add header to confirmation email mocks

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1101]
@sergiogcx is good to start on #993, but we need to add a simple OPO header to the mocks: https://xd.adobe.com/spec/6a786d16-7606-4b9d-7c98-0202c57a13eb-1c49/

Add to #1137 when complete - along with any other changes you'd like.

**Comment by chasechenevert** [comment]
## OPO Email draft: header

- Updated [spec is here](https://xd.adobe.com/spec/bf7944c2-69b2-444f-6f10-e3e27f0f47a3-c948/) with email template on the last row of the doc. 
- City seal has been marked for export, you'll find it in the "Assets" section of the info panel

![screen shot 2019-02-07 at 8 52 53 am](https://user-images.githubusercontent.com/7027270/52419879-998bc800-2ab6-11e9-988d-45fa9d9e081e.png)

### Design notes
- Mostly trying to make sure that this doesn't visually register as spam to users while trying to keep the formatting to a minimum.
- Want it to feel official but I didn't want to labor over this too much for a v1 (it can be really easy to over-design deceptively simple components).

**Few changes**
- 1px rule line between the intro and body text with gray: #DBDEE1
- Header text "Your complaint was..." to blue: #0050D8

**Comment by sergiogcx** [comment]
It's looking good! Thanks @chasechenevert
