### ISSUE TITLE
Police Oversight form: Received a ticket question needs True/False answers

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1104]
**Describe the bug**
If the user does not respond, no "False" answer shows and it reads like a positive.

/Review-and-submit

**Expected behavior**

![screen_shot_2019-02-04_at_7_41_59_am](https://user-images.githubusercontent.com/3790067/52212425-0e11fd00-2852-11e9-8d26-d0fb02a7bc72.png)

**Comment by easherma** [comment]
Would this fall under https://github.com/cityofaustin/techstack/issues/1013 ?

Put another way, if it said 'no answer' instead of blank, would that resolve this issue?

**Comment by toribr** [comment]
Yeah, that's ok.

**Comment by easherma** [comment]
Actually this question just wasn't conforming to the rest of the form. I've adjusted it so a blank answer means the answer won't show on the review page.
