### ISSUE TITLE
Police Oversight - Editing previous answers for officers and witnesses

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1105]
**Describe the bug**
Resident is allowed to change answer on officer and witness chapter from no to yes, but fields for "yes" don't show when answer is changed.
**URL**

**To Reproduce**

1. Go through form and select no for witness and officer
2. On review, change your answer from no to yes
3. Where is the detail for the officer? The only way to add detail is "Add Another"

**Expected behavior**
Presumably, if answer is changed to "yes" then corresponding fields for this chapter should show. (Share your evidence works correctly)
![screen shot 2019-02-04 at 1 57 04 pm](https://user-images.githubusercontent.com/3790067/52233484-d2dcf180-2884-11e9-95af-f8b03d7568e9.png)

**Comment by easherma** [comment]
I've poked around in us-forms a bit, but I think we should discuss this with them on their next call as far as a good way to go about implementing it.

**Comment by easherma** [comment]
@toribr this also might be related to redesign of the review page?

**Comment by easherma** [comment]
@toribr is this issue still relevant in light of the changes made in #1674 ? if not I think we can close it.

**Comment by toribr** [comment]
Yep, closing it.
