### ISSUE TITLE
Police Oversight form: Add placeholder for race

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1107]
**Describe the bug**
[ ] Race selection should look like this (add "select race"):
![screen shot 2019-02-04 at 2 21 26 pm](https://user-images.githubusercontent.com/3790067/52234868-446a6f00-2888-11e9-8378-0ae9c2de2aa2.png)

Aha! Link: https://desi1.aha.io/features/RT-85

**Comment by easherma** [comment]
@briaguya I implemented this in https://github.com/cityofaustin/usfs-schema-blocks/blob/4d54757a56df1b8bbbb818c3f41a2dd2afba10dc/src/blocks/raceBlocks.js#L34 , but am having trouble having the build for that carry through to the officer form

**Comment by amenity** [comment]
See #1213

**Comment by easherma** [comment]
Should be live at https://forms.austintexas.io/police-oversight/complaint
