### ISSUE TITLE
Draft Commercial Collection Services Information page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1109]
original link: http://www.austintexas.gov/department/commercial-collection-services

Jeff's Draft lives here: https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Resource Recovery > Information Pages

**Comment by LauraTrujillo** [comment]
@JeffCopy @desigonz I made my comments and suggestions. Back to you, Jeff!

**Comment by JeffCopy** [comment]
Revisions incorporated, onward!
