### ISSUE TITLE
Translation -- translation stored in CMS

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#111]
translations stored in CMS as JSON (manually input) as determined by content team

**Comment by ashleecoa** [comment]
Content can be accessed here: https://drive.google.com/drive/folders/1rgRRytxDq6KD14kce8I6BdXGJkN87TJA?usp=sharing

**Comment by ashleecoa** [comment]
Devs will have to input the translated content into the site using JSON. 

The content exists here: https://drive.google.com/open?id=1rgRRytxDq6KD14kce8I6BdXGJkN87TJA
It is 5 services and 1 department page for Austin Resource Recovery for the three languages.

- [ ]     Add Spanish translation content to alpha
- [ ]     Add Vietnamese translation content to alpha
- [ ]     Add Arabic translation content to alpha

**Comment by benweatherman** [comment]
We're not going to store this in the CMS because
1. We don't know what the translation workflow is
2. It's hard to translate streamfields
