### ISSUE TITLE
Draft Haul it the right way information page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1110]
original link: (PDF) http://austintexas.gov/sites/default/files/files/Haul_It_The_Right_Way_Flyer_Eng_Span.pdf

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Resource Recovery > Information Pages

Draft link https://docs.google.com/document/d/1VhdiJLg0Ee5EFRDAGwk6DctxECQjKHuAUmT4-xj3JK8/edit

**Comment by JeffCopy** [comment]
@annieszot here's the current draft:

https://docs.google.com/document/d/1nNsb254FWWZISMHfhn_Xc4OYTaT9viNz862jl7-WjKQ/edit

**Comment by annieszot** [comment]
- [ ] IA linked (draft)
- [ ] Governance/Workflow #1971
- [ ] Draft

**Comment by annieszot** [comment]
Draft https://docs.google.com/document/d/1VhdiJLg0Ee5EFRDAGwk6DctxECQjKHuAUmT4-xj3JK8/edit
