### ISSUE TITLE
Draft Street Sweeping Information Page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1111]
original link: http://austintexas.gov/department/street-sweeping

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Resource Recovery > Information Pages

*For now, I think we have to link to the non-interactive street sweeping schedule PDF

**Comment by JeffCopy** [comment]
My draft here:
https://docs.google.com/document/d/1hvbinxIUqAsYeY8OlTHnG9dyN6rT9xGPg0csKfkXYxI/edit

**Comment by LauraTrujillo** [comment]
@JeffCopy can you give us access when you get a chance? Thanks!

**Comment by LauraTrujillo** [comment]
@JeffCopy reviewed!

**Comment by desigonz** [comment]
happy to take a pass too if you give me edit access
