### ISSUE TITLE
Draft Brownfields Information page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1112]
original link: http://www.austintexas.gov/brownfields

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Resource Recovery > Information Pages

Aha! Link: https://desi1.aha.io/features/RT-82

**Comment by JeffCopy** [comment]
@annieszot here is the updated draft
https://docs.google.com/document/d/1nNsb254FWWZISMHfhn_Xc4OYTaT9viNz862jl7-WjKQ/edit#

**Comment by LauraTrujillo** [comment]
Draft lives here: https://docs.google.com/document/d/1nNsb254FWWZISMHfhn_Xc4OYTaT9viNz862jl7-WjKQ/edit?usp=sharing
@JeffCopy It can use your eyes one more time. It was at a 10th grade reading level, so I simplified it and removed the info about Austin Brownfields Revitalization Office.

**Comment by JeffCopy** [comment]
looks good, imo.

**Comment by annieszot** [comment]
@LauraTrujillo Good to close? Whom should do the final round of edits when you drafted? :) Or shall we skip the final edit round?

**Comment by LauraTrujillo** [comment]
@annieszot thanks, good to close!
