### ISSUE TITLE
Draft Brush Information page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1113]
original link: http://austintexas.gov/brush

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Resource Recovery > Information Pages

Aha! Link: https://desi1.aha.io/features/RT-81

**Comment by JeffCopy** [comment]
My draft here: https://docs.google.com/document/d/1iNiH5CdGfzbPVqZAULUVSIvPtvAteGJCgoCV_N2aMfs/edit?usp=sharing

**Comment by LauraTrujillo** [comment]
reviewed!

**Comment by JeffCopy** [comment]
Modified title to align with change in how we do info pages, now ready to advance.
