### ISSUE TITLE
Break Austin Economic Development Program into different pages

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1114]
original link: http://austintexas.gov/recyclingecodev

Save in:
Austin.gov > Content > Content Transitions > Resource Recovery > Information Pages

It may be that this page doesn't need to be split up into as many pages as we originally thought. Use your best judgment. I'm happy to talk this through with you!

**Comment by annieszot** [comment]
Pages drafted, incorporating with issues in #2133. Closing
