### ISSUE TITLE
Draft Enterprise Resource Guide Information page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1115]
original link: http://austintexas.gov/recyclingecodev

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Resource Recovery > Information Pages

Aha! Link: https://desi1.aha.io/features/RT-79

**Comment by annieszot** [comment]
- [x] Information page draft started
https://docs.google.com/document/d/1If7Z-pVNm3XfZoqUybM11dWBZylI-RxS_bMiLDWYS3o/edit

**Comment by annieszot** [comment]
- [x] draft started Feb. 6
- [x] first draft finished Feb. 22
https://docs.google.com/document/d/1iowTyNLlytwy8KnOIqg69NtZQDqh3vGsiY8mlq_pfhA/edit#
-Assigned to @srigdon and @desigonz for first-round reviews due Thurs. 2/28
-Notes: University of Texas at Austin Social Innovation Initiative's link is broken
  - I excluded laws/ordinances - thoughts on including that info under Government + Business topic?
  - The Bond financing program - don't know what it means or how to include it in this information page
  - Flag - last page, vanity url (austinrecycle.com)
  - Decided not to link the Small Business Incentive Guide

**Comment by desigonz** [comment]
@annieszot Finally finished my review of this page. As we discussed, though, I think we should sync up with design re: a solution for lists of links!

**Comment by annieszot** [comment]
Removing @srigdon and @desigonz from assignees. Thanks for the edits!
After catch-all workshop, I need to restrategize pages

**Comment by annieszot** [comment]
Re-assigning to @LauraTrujillo This is a catch-all page so really appreciating your capacity to help with deciding what to do with this. Let me know if you have questions :)

**Comment by LauraTrujillo** [comment]
catch all doc: https://docs.google.com/document/d/1-k60yWKNyvv9C9a-ZyZv0g2G5gl9uFi6zXAMqGkDkfw/edit?ts=5ca3e114#

**Comment by LauraTrujillo** [comment]
@JeffCopy can you take a look at this page?
@annieszot and @desigonz Let me know your thoughts on this as well. My thinking was that getting entrepreneurs to the classes was important, and until we have an answer to "what replaces the PDF?" we could just link to the resource instead of pulling out the links.

**Comment by desigonz** [comment]
Hey @LauraTrujillo! Awesome work. I think this is getting closer to what @annieszot and I were discussing—a page on how businesses can reduce waste. Eventually, I wonder if, instead of using inline links, we could use the "Top services" buttons that Chase and Tori are working on in their designs. (Maybe this would be approaching a "fancy topic" page.) For now, though, it looks like you're linking to pages on austintexas.gov. Do we have plans/a workflow for how to link across the two sites, and how we'll address these as we transition other departments?

We'd also want to link out to Austin Materials Marketplace with a nice call to action—communicating what AMM is, who it's for, and that it's taking you off of Alpha. I'm wondering if/how this link should behave differently from links to city services.

**Comment by annieszot** [comment]
Thanks so much for consolidating @LauraTrujillo! I challenge the linking to the resource guide and say it's up to ARR to promote it through their marketing/communication plans/channels. By the time we publish this page live on Alpha, the guide will be over a year old. 

Here are drafts I'm turning this catch-all page into:
https://docs.google.com/document/d/1JvGfOPZvQldi3k97bBopyYizwzNqQwYX581bPrbwcBY/edit#
https://docs.google.com/document/d/122Ql-r9fMon2SeqBEBnd5WXcf-_bqjyeuSEtMzelLfc/edit

**Comment by annieszot** [comment]
*Throws hands up*
Okay, I propose scratching the enterprise resource guide info page and instead turn fresh content from that page, specifically "there are 5 basic parts to starting a new business in Austin", into a service page.
https://docs.google.com/document/d/122Ql-r9fMon2SeqBEBnd5WXcf-_bqjyeuSEtMzelLfc/edit#

**Comment by annieszot** [comment]
whoa whoa whoa @LauraTrujillo -->ARR must have updated their guide "Spring 2019"
http://austintexas.gov/sites/default/files/files/Resource_Recovery/Recycling_and_Reuse_Enterprise_Resource_Guide-Spring-2018.pdf *face palm*

**Comment by annieszot** [comment]
Feel free to close when ready @LauraTrujillo
