### ISSUE TITLE
Draft Austin Materials Marketplace Information Page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1116]
original link: http://austintexas.gov/recyclingecodev

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Resource Recovery > Information Pages

Aha! Link: https://desi1.aha.io/features/RT-78

**Comment by annieszot** [comment]
Will Austin Resource Marketplace keep their website (platform) and have an information page? 
https://austinmaterialsmarketplace.org/
-[x] Information page started

**Comment by LauraTrujillo** [comment]
@annieszot That's a great question about the marketplace site. We can ask Keri when we see her next.

**Comment by annieszot** [comment]
AMM information page ready for review 
https://docs.google.com/document/d/1AQm8D_MnurNA4ryuXF_FZCpGbaKVBlten7ZvuH00z_Q/edit#
Assigned to @srigdon @desigonz for first review. Edits due Monday, 3/4/19

**Comment by desigonz** [comment]
@annieszot @LauraTrujillo Starting to review this page, but I have an overarching question: what's the goal of this page vs. austinmaterialsmarketplace.org? This page duplicates a lot of the same information and links, which seems like not a great practice content governance-wise—if something is out-of-date, content managers would have to update in two places. (Also wondering what having similar content on both places would do SEO-wise, maybe @srigdon has thoughts?) Maybe a better solution would be to link out to Austin Materials Marketplace from a different page.

Maybe I'm asking a bigger question: how do we treat microsites with their own domains and branding? Is there a consistent way we can link out to these (maybe through some new content type/feature) across alpha?

**Comment by LauraTrujillo** [comment]
@desigonz Your intuition and bigger question are right on- let's dig into that and do some research about how and why microsites pop up. What need are they filling for departments? This could be an issue in our backlog.

**Comment by srigdon** [comment]
@desigonz @LauraTrujillo I concur, and it looks like 
http://austintexas.gov/recyclingecodev already links out to https://austinmaterialsmarketplace.org/ with a big yellow button, so no need to restate any content that's available there. Where could we help the resident complete an action on learn how to? I made a comment in the doc suggested a way to reshape this, but I think it depends on what other content there. I think the need for this page can be met elsewhere, though.

**Comment by annieszot** [comment]
Removing @srigdon and @desigonz from assignees
After catch-all workshop, I need to restrategize pages

**Comment by annieszot** [comment]
I've decided to scratch this from ARR's content umbrella per Desi's notes https://docs.google.com/document/d/12SNG6-ErlmEBoug3j5VsuOjkdCb6Uj8r4x_pJGwtm4w/edit?usp=sharing
Will remove sprint and move to backlog: medium term

**Comment by annieszot** [comment]
Per meeting with Desi on 4/5, will develop content that links out to AMM.

**Comment by annieszot** [comment]
Incorporating AMM into Waste + Businesses info page 
https://docs.google.com/document/d/1JvGfOPZvQldi3k97bBopyYizwzNqQwYX581bPrbwcBY/edit#
