### ISSUE TITLE
Draft Shop Zero Waste Information Page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1117]
original link: http://austintexas.gov/recyclingecodev

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Resource Recovery > Information Pages

Aha! Link: https://desi1.aha.io/features/RT-77

**Comment by annieszot** [comment]
Moved to "In Progress" 
Ready for QA Review 
https://docs.google.com/document/d/1uSJI1oF4l0vD2KKy09wTA0V_yDN_tJWue6NQ7aT3aM4/edit

**Comment by JeffCopy** [comment]
I added a few suggestions.

**Comment by annieszot** [comment]
Thanks @JeffCopy! 

@desigonz I incorporated some of Jeff's edits and volleying the content to your court for review. Thanks! https://docs.google.com/document/d/1uSJI1oF4l0vD2KKy09wTA0V_yDN_tJWue6NQ7aT3aM4/edit

**Comment by desigonz** [comment]
I added some edits and comments!

**Comment by annieszot** [comment]
Thanks for the edits @desigonz ! 
@LauraTrujillo @srigdon How do we standardize external links lists?

**Comment by annieszot** [comment]
Adding @LauraTrujillo for review (soft due 2/26) 
*Specific asks on icons and standardized external links (see Desi's comments) 
https://docs.google.com/document/d/1uSJI1oF4l0vD2KKy09wTA0V_yDN_tJWue6NQ7aT3aM4/edit

**Comment by LauraTrujillo** [comment]
Great job! Good to close!

**Comment by annieszot** [comment]
Thank you @LauraTrujillo for your helpful, polished edits!

**Comment by annieszot** [comment]
Dropped into Joplin, information page draft 
- [x] delete service page draft (duplicate pre information page deployed contenty type deployed]
- Preview, mobile preview clunky/non-existent yet 
- [x] Test once preview/mobile preview ready

**Comment by annieszot** [comment]
Reopened to edit and incorporate structures decided on title, etc.

**Comment by annieszot** [comment]
Reassigning to @LauraTrujillo Draft should be ready for Joplin again. I dropped the draft in Joplin then deleted it. Let me know if edits need to be made before testing/publishing on Joplin.

**Comment by LauraTrujillo** [comment]
catch all page doc: https://docs.google.com/document/d/1-k60yWKNyvv9C9a-ZyZv0g2G5gl9uFi6zXAMqGkDkfw/edit?ts=5ca3e114#

**Comment by LauraTrujillo** [comment]
@JeffCopy can you review the tiny changes I made?
@annieszot when Jeff's done, it's ready for you!

**Comment by JeffCopy** [comment]
Couple of minor suggestions; looks good!

**Comment by annieszot** [comment]
@LauraTrujillo My suggested edits are added. Thanks!

**Comment by LauraTrujillo** [comment]
Reviewed by ODD, now to ARR's team to review. Removing milestone.

**Comment by oliver2g** [comment]
@LauraTrujillo any word from ARR about reviewing this? Any blockers?

**Comment by LauraTrujillo** [comment]
@oliver2g No word, I'll nudge Keri today, thanks!
