### ISSUE TITLE
Police Oversight form: Validate correct number of digits for zip and phone

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1118]
The form should validate these fields if the user enters text: zip code ( for 5 digits and legit US zip); email for valid construction; and phone number (for 10 digits).

**Comment by easherma** [comment]
changing to Medium because us-forms system has validation happening in a few places, as does the json form schema it's based off of, and its taking some time to look at all of this and figure out the cleanest implementation.

**Comment by easherma** [comment]
we could/should add email validation to this list

**Comment by easherma** [comment]
@Niicck I forget if this came up for you at all, have you played with the validations inside us-forms-system? I remember trying to use them awhile back and they didn't seem to apply, and I seem to remember you having a similar issue. If not no worries.

**Comment by easherma** [comment]
https://github.com/cityofaustin/officer-form-chapters/commit/05b4a38c8c6da9e7dbeba1fe728f0f442a5191c7 should fix!
