### ISSUE TITLE
Police Oversight form: Implement Spanish confirmation emails

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1120]
Content here: https://docs.google.com/document/d/1O9qGMVBOotlbNe5V2j2kF1RoymGclLFIRmiwXCya4w0/edit

**Comment by LauraTrujillo** [comment]
@sergiogcx: https://drive.google.com/drive/folders/1fXreM4c2GxZNW4-BSVf5ZBcPshHaZsy3

**Comment by sergiogcx** [comment]
I could not access the link @LauraTrujillo I asked @amenity and she gave me these links:

https://drive.google.com/drive/folders/107A1pBCEvKTQjE_eYHQCncmOEwzUFTjU

https://drive.google.com/drive/folders/17zYpknrL-kWaX4AIwpKPD8oEUWVnhgiN <-- Form and email content (edited)

**Comment by sergiogcx** [comment]
This branch addresses both stylesheet fixes for #1137 and the translations for #1120 (this issue)

https://github.com/cityofaustin/form-service-api/pull/6

You can see the emails here:

Complaint form email in English: 
https://6jm8rnjkxf.execute-api.us-east-1.amazonaws.com/staging/email-template

Complaint form email in Spanish:
https://6jm8rnjkxf.execute-api.us-east-1.amazonaws.com/staging/email-template?lang=es


Thank you form email English:
https://6jm8rnjkxf.execute-api.us-east-1.amazonaws.com/staging/email-template?type=thanks

Thank you form email Spanish:
https://6jm8rnjkxf.execute-api.us-east-1.amazonaws.com/staging/email-template?type=thanks&lang=es
