### ISSUE TITLE
Determine standards for Alpha IA and URLs

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1121]
We'll soon have forms, Information Pages, and Department Pages. How should our page hierarchy and URLs work?

@srigdon has done some preliminary research and will put together a draft. Then we'll want content and @toribr to review.

Aha! Link: https://desi1.aha.io/features/RT-75

**Comment by amenity** [comment]
These URL domain/standards for Gov.UK are pretty solid:
[Central government: naming and registering websites](https://www.gov.uk/government/publications/naming-and-registering-government-websites/central-government-naming-and-registering-websites). 

I wonder if we could pull some of this out as a starting place and work from there?

**Comment by srigdon** [comment]
Draft: https://docs.google.com/document/d/1pI2vdbAC4gpupVU02GLo6qGr6nsEJGuEORnVHJqs6JM/edit#

**Comment by amenity** [comment]
Awesome, thanks @srigdon !! Assigning to content team + Tori for review & sign-off.

- [ ] Annie
- [ ] Desi
- [ ] Jeff
- [ ] Laura
- [ ] Tori

**Comment by desigonz** [comment]
awesome work @srigdon!

**Comment by srigdon** [comment]
Updating with OPO dept and information page URLs.

**Comment by annieszot** [comment]
Terrific @srigdon Top notch work. My review is in progress but will conclude by COA today

**Comment by amenity** [comment]
👌 ✨
