### ISSUE TITLE
Janis/Joplin - Implement Department Page API endpoint/Janis 1.0 page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1124]
Once the Department Page model is implemented, #664, we need to expose it via the API in Joplin, as well as extend Janis to consume and create Department Pages.

The end result of this should be Janis building Department Pages from the Joplin API, and having them appear at the correct URLs.

This does not include any of the styling around the Department Pages in Janis, so they will probably look incredibly barebones.

**Comment by briaguya** [comment]
![Image](https://i.imgur.com/I2t240K.jpg)
