### ISSUE TITLE
Draft HIV Planning Council Information page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1132]
original link: http://austintexas.gov/department/hiv-planning-council

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Public Health > Information Pages

**Comment by annieszot** [comment]
Created and saved in Austin.gov > Content > Content Transitions > Public Health > Public Health Content > Information Pages (new folder)

**Comment by annieszot** [comment]
[] First draft
https://docs.google.com/document/d/1QT4C8gqoZLs0LscziLnKrauQ8gs7yLBwJi7-jym27Pk/edit?usp=sharing
Top Link?

**Comment by annieszot** [comment]
Draft ready for QA/Review 
https://docs.google.com/document/d/1QT4C8gqoZLs0LscziLnKrauQ8gs7yLBwJi7-jym27Pk/edit

**Comment by desigonz** [comment]
I added a few comments!

**Comment by annieszot** [comment]
Thank you @desigonz !  Very helpful :) Edits incorporated and assigning to @srigdon 
https://docs.google.com/document/d/1QT4C8gqoZLs0LscziLnKrauQ8gs7yLBwJi7-jym27Pk/edit

**Comment by srigdon** [comment]
I made some small direct edits and suggested a bigger one in comments. Take a look and let me know what you think. Great job, @annieszot @desigonz! This concise page is a huge improvement over the current one. 👏🏻👏🏻👏🏻

**Comment by annieszot** [comment]
Thanks so much @desigonz and @srigdon! Assigning to @LauraTrujillo for review due Thursday 2/21. 
https://docs.google.com/document/d/1QT4C8gqoZLs0LscziLnKrauQ8gs7yLBwJi7-jym27Pk/edit

**Comment by LauraTrujillo** [comment]
Great work, y'all! Ready to go!

**Comment by annieszot** [comment]
@LauraTrujillo Thanks for encouraging the WagTail test! 
First go-around - Information Page not listed in Content Types
![screen shot 2019-02-19 at 4 51 03 pm](https://user-images.githubusercontent.com/46934140/53053497-221b4880-3467-11e9-94a1-190261141346.png)
So I copy and pasted the content in a Service Page template
When attempting to add a contact
![screen shot 2019-02-19 at 4 45 33 pm](https://user-images.githubusercontent.com/46934140/53053566-5a228b80-3467-11e9-9744-6ae27d2d06f7.png)
I could not manually input the contact
![screen shot 2019-02-19 at 4 45 21 pm](https://user-images.githubusercontent.com/46934140/53053598-78888700-3467-11e9-9cd0-fd7e2cc0d418.png)
Any advice before I create an issue bug?

**Comment by annieszot** [comment]
Dropped in Joplin Information Page (content model deployed today) 
Draft features bold text, but bold not available in Joplin, just H1, H2. Incorporated H2, but may need H3. 
![screen shot 2019-02-20 at 7 48 58 pm](https://user-images.githubusercontent.com/46934140/53137718-55360880-3549-11e9-924a-cc541445e134.png)

- [ ] figure out how to delete old, irrelevant drafts (like the service page mentioned above)

**Comment by annieszot** [comment]
Reopened to edit and incorporate structures decided on title, etc.

**Comment by annieszot** [comment]
Rewrote title to "HIV Planning Council" and generalized contact information to the email address. Will post to Joplin after deleting older drafts.
