### ISSUE TITLE
Draft Child Care Information Page 

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1134]
original link: http://austintexas.gov/childcare

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Public Health > Information Pages

Aha! Link: https://desi1.aha.io/features/RT-70

**Comment by JeffCopy** [comment]
My draft here:
https://docs.google.com/document/d/1dRL-GW08EEKMMP2kzOxly2Eu2_Rbuov73xBf7BKWs3s/edit

**Comment by LauraTrujillo** [comment]
reviewed!

**Comment by desigonz** [comment]
@JeffCopy Just finished my review!

**Comment by LauraTrujillo** [comment]
@jeffcopy is this done or should we move it to Sprint 28?

**Comment by JeffCopy** [comment]
It’s going to carry over. I had questions about Desi’s suggested edits, better done as a conversation than as in google doc comments and need to make time to follow up with her on that.

**Comment by LauraTrujillo** [comment]
Great! I'll move it to 28.

**Comment by JeffCopy** [comment]
This one was long-stuck, but I've incorporated some revisions from Desi's long-ago edit, resolved an issue or two, and am tagging @srigdon as the next pair of eyes and saying so long to this particular issue . . .

**Comment by desigonz** [comment]
@LauraTrujillo Tagging you for second review on this one—in Jeff's absence, want to incorporate the edits directly?

**Comment by LauraTrujillo** [comment]
reviewed and made edits. closing for now!
