### ISSUE TITLE
Draft Crypto (waterborne disease) Information page 

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1136]
original link: http://austintexas.gov/department/cryptosporidiosis

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Public Health > Information Pages

**Comment by desigonz** [comment]
Link to my draft: https://docs.google.com/document/d/1t1LP2L6M62zDIuYAcViY4rfJ8WKX3arTobuaapLk3gs/edit?usp=sharing

**Comment by LauraTrujillo** [comment]
@desigonz reviewed!

**Comment by JeffCopy** [comment]
Back to you!
