### ISSUE TITLE
Draft flu information page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1138]
original link: http://austintexas.gov/department/flu-austin-influenza
include information from flu report: http://austintexas.gov/sites/default/files/files/Health/Epidemiology/Flu/Flu_Report_-_February1-2019_week_4.pdf

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit
*Include link to austin.gov content for getting a flu vaccine: https://docs.google.com/document/d/11wKjhYakpjhIFqz67G7m2IqyQ5EB6C8Or90zYvdvsUQ/edit

Save in:
Austin.gov > Content > Content Transitions > Public Health > Information Pages

**Comment by desigonz** [comment]
Draft here: https://docs.google.com/document/d/1qJxR_bx6cRj9To3L5ehGZt0LTAUtiLrlKvrdB7ciasI/edit?usp=sharing

**Comment by LauraTrujillo** [comment]
@desigonz: I reviewed it!

**Comment by JeffCopy** [comment]
@LauraTrujillo @desigonz I added a couple of cents as well.

**Comment by desigonz** [comment]
incorporated revision!
