### ISSUE TITLE
Draft Measles Information Page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1139]
original link: http://austintexas.gov/sites/default/files/files/Health/Info_to_Post/Measles_Information_02_11_2015.pdf

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Public Health > Information Pages

**Comment by desigonz** [comment]
Link to my draft: https://docs.google.com/document/d/1dsXP5ZCSxk1V5peLn1sWwZr2gafW1kJY_d4fVpFUG1E/edit?usp=sharing

**Comment by LauraTrujillo** [comment]
@desigonz - reviewed and didn't have anything to add outside of Jeff's suggestions.

**Comment by desigonz** [comment]
Reopening this for review because Linda from APH had some great feedback. @annieszot, sending it over to you for one last review!
