### ISSUE TITLE
Acceptance Criteria -- Preflight checklists

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#114]
Work with each team to create a checklist they will use for content, code, design, and functionality before moving work to production. 

- [X] [Content](https://docs.google.com/document/d/1uztCmkvBnb5HT93Mn6Yg6L-LPKrrVquWkjLbA31vbpU/edit#heading=h.3e8podqp7bl8)
- [x] Dev: Evaluate each item in [The a11y checklist](https://a11yproject.com/checklist) and file an issue for anything we can’t check off. For the backlog, [Extended code preflight checklist ](https://github.com/cityofaustin/techstack/issues/188).
- [ ] ~Design~ Premature given our resources. For the backlog, [Design preflight process](https://github.com/cityofaustin/techstack/issues/187).
- [x] Product - Acceptance criteria tested by PO based on user story

**Comment by mateoclarke** [comment]
For devs, see cityofaustin/janis#50
