### ISSUE TITLE
Alpha: Define how residents navigate and traverse Austin alpha via landing pages and navigational elements

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1140]
How can we sidestep breadcrumbs and provide something more valuable to users - surfacing information they need in the right place?
Tags? "Related" content/services?

Relationship indicators 🤓

**Comment by toribr** [comment]
Documentation & conversations about persona/situational framework is here: https://docs.google.com/document/d/1pI2vdbAC4gpupVU02GLo6qGr6nsEJGuEORnVHJqs6JM/edit?usp=sharing

**Comment by chasechenevert** [comment]
Visual design of this issue: #1203
