### ISSUE TITLE
Create wireframe set from Janis 2.0 sticker sheet

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1142]

**Comment by toribr** [comment]
Just a note that we've decided against a separate sticker sheet for now, since there's little styling and it'll be easier to keep up with one version.

**Comment by amenity** [comment]
Gotcha. Should we close this or move it to the backlog?

**Comment by toribr** [comment]
It's still in progress.

**Comment by chasechenevert** [comment]
- I lost some info across this sprint due to a save/override issue
- I'll be going back in and adding all of that back by tomorrow
