### ISSUE TITLE
Police Oversight form: Create working master branch 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1144]

**Comment by sergiogcx** [comment]
The master branch is now working!

https://github.com/cityofaustin/officer-complaint-form

It looks like the only issues were related to the `yarn.lock` file where an old version of one the dependencies was being cached.

You can see the master branch run here:
http://police-monitor-website-staging.s3-website-us-east-1.amazonaws.com/police-oversight/complaint/
