### ISSUE TITLE
Police Oversight Form - change all instances of "translator" to "interpreter"

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1147]
Several instances in the options in this chapter: https://opo-form.netlify.com/introduction
*Online*
Your contact information for us to follow up with you (translators available)
CHANGE TO:
Your contact information for us to follow up with you (interpreters available)
*Over the phone*
If you need language translation, you can call with a friend to translate for you or ask for a translator. Just tell us the language you prefer.
CHANGE TO:
If you need an interpreter, you can call with a friend to interpret for you or ask for an interpreter. Just tell us the language you prefer.
*In Person*
If you need language translation, you can call with a friend to translate for you or ask for a translator. Just tell us the language you prefer.
CHANGE TO:
If you need an interpreter, you can call with a friend to interpret for you or ask for an interpreter. Just tell us the language you prefer.

https://opo-form.netlify.com/about-you

I would like a translator for all my future interactions.
CHANGE TO:
I would like an interpreter for all my future interactions.

Aha! Link: https://desi1.aha.io/features/RT-64

**Comment by easherma** [comment]
https://github.com/cityofaustin/officer-complaint-form/pull/29
