### ISSUE TITLE
Draft homeless assistance information page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1152]
original link: http://www.austintexas.gov/department/homeless-assistance

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Public Health > Information Pages

Aha! Link: https://desi1.aha.io/features/RT-63

**Comment by desigonz** [comment]
added @srigdon for first review

**Comment by desigonz** [comment]
also doc lives here: https://docs.google.com/document/d/1ffA7cWBJNM_nSix3RTju6cLWuFZ4l61NTtak8VoM4aY/edit?usp=sharing

**Comment by srigdon** [comment]
First pass finished, assigning to @LauraTrujillo for second pass.

**Comment by LauraTrujillo** [comment]
@srigdon @desigonz - reviewed!
