### ISSUE TITLE
Draft Mosquito-borne illness information page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1153]
*Use a more accessible name than mosquito-borne
original link: http://www.austintexas.gov/westnile AND http://www.austintexas.gov/zika

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Public Health > Information Pages

**Comment by desigonz** [comment]
Link to my draft: https://docs.google.com/document/d/1JIssBsLRoBYkIr-LhzbWTAUTlgonOELvvIc3PrzaFC8/edit?usp=sharing

**Comment by LauraTrujillo** [comment]
@desigonz reviewed!

**Comment by desigonz** [comment]
assigned @annieszot as 2nd reviewer but no rush :)

**Comment by annieszot** [comment]
@desigonz  reviewed!
