### ISSUE TITLE
Draft info page for Signing up for a diabetes course

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1154]
original link: http://austintexas.gov/department/diabetes-education

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Public Health > Service Pages

Aha! Link: https://desi1.aha.io/features/RT-62

**Comment by desigonz** [comment]
Hey @LauraTrujillo—it looks like there's already a draft of this content: https://docs.google.com/document/d/1trSHZt3qXFT9VFVPny1CTT-T_yfSJXjMIFGFjDmLBQc/edit?usp=sharing

Should I just work from there?

**Comment by LauraTrujillo** [comment]
good catch, @desigonz. Yes- go ahead and work from there (and feel free to make any and all edits!)

**Comment by desigonz** [comment]
I took a stab at rewriting this one as an information page, using the same heading sections as I do for illness pages (measles, mosquito-borne, etc); the service page really just seemed to be serving as a link out to where you sign up for the class. Interested to hear your thoughts. Assigning to @srigdon for first review. New doc lives here: https://docs.google.com/document/d/14GNobdf1nlWMVI5YSnXU5JZSn9TYfXZQ57L2qrlEs94/edit?usp=sharing

**Comment by LauraTrujillo** [comment]
reviewed!

**Comment by desigonz** [comment]
Thanks, @LauraTrujillo! Did you have an opinion re: whether this should be a service or an info page?

**Comment by LauraTrujillo** [comment]
@desigonz oops- I think you did a great job turning it into an info page. Let's see how it performs!

**Comment by desigonz** [comment]
Thanks @LauraTrujillo! @srigdon, want to take the second pass on this doc: https://docs.google.com/document/d/14GNobdf1nlWMVI5YSnXU5JZSn9TYfXZQ57L2qrlEs94/edit?usp=sharing

**Comment by srigdon** [comment]
Second pass finished!

**Comment by desigonz** [comment]
Incorporated edits and closed.
