### ISSUE TITLE
Draft Healthy Adolescent Information page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1159]
original link: http://austintexas.gov/department/healthy-adolescent

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Public Health > Information Pages

**Comment by desigonz** [comment]
This is the paper application they use for the Peer Educator program

**Comment by desigonz** [comment]
My draft is here: https://docs.google.com/document/d/1Y1isYhlE3fSHSOkMfYO3DlGnSaCLmSlfRp-q_utt7QM/edit?usp=sharing

Assigning @JeffCopy to first review!

**Comment by JeffCopy** [comment]
look great! My suggestions now added.

**Comment by desigonz** [comment]
Thanks @JeffCopy! Assigning to @LauraTrujillo for second review.

**Comment by LauraTrujillo** [comment]
@desigonz Reviewed and left my 2 cents. Great job!
