### ISSUE TITLE
Draft Chronic Disease and Injury Prevention information page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1160]
original link: http://austintexas.gov/department/chronic-disease-prevention-and-control

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Public Health > Information Pages

Aha! Link: https://desi1.aha.io/features/RT-57

**Comment by desigonz** [comment]
Draft lives here:
https://docs.google.com/document/d/1849RUiCzTDN_JLHUfBe7xyZzmPNDNDsdNHe4tG1eWTc/edit?usp=sharing

@JeffCopy, assigning you to first review!

**Comment by JeffCopy** [comment]
suggestions added, onward!

**Comment by desigonz** [comment]
thanks for your great edits, @JeffCopy! Assigning to @LauraTrujillo for second review.

**Comment by LauraTrujillo** [comment]
@desigonz reviewed!
