### ISSUE TITLE
Maternal Infant Outreach Program service page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1161]
original link: http://www.austintexas.gov/department/maternal-infant-outreach-program

~~copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit~~

Save in:
Austin.gov > Content > Content Transitions > Public Health > ~~Information Pages~~ Service Pages

**Comment by desigonz** [comment]
I think this is better as a service page! My draft lives here: https://docs.google.com/document/d/1N6y1lJv4HfyfOcc_l6kxZXBnda3v3gGQLg7zFDWQgPU/edit?usp=sharing

I have to fact check a few things and plan to do so when I'm back from vacation.

**Comment by desigonz** [comment]
Waiting to hear from Cynthia Washington to set up a fact-checking call.

**Comment by desigonz** [comment]
Followed up with Cynthia on 4/8/2019 but still haven't heard back. @LauraTrujillo, any recommendations on next steps?

**Comment by desigonz** [comment]
Sending to @annieszot for first review. [Draft lives here](https://docs.google.com/document/d/1N6y1lJv4HfyfOcc_l6kxZXBnda3v3gGQLg7zFDWQgPU/edit?usp=sharing). Disregard the fact check notes—will get those covered when we send to APH for the revision/approval cycle.

**Comment by annieszot** [comment]
Great! Will review Sunday or Monday at the latest @desigonz !

**Comment by annieszot** [comment]
Suggested edits incorporated @desigonz ! Let me know if you have questions.

**Comment by desigonz** [comment]
Thanks @annieszot! Onto @LauraTrujillo for second review.

**Comment by LauraTrujillo** [comment]
Reviewed! commented on bulleted list
