### ISSUE TITLE
Draft Public Health Regulations content

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1175]
Major catchall page

original link: http://austintexas.gov/department/public-health-regulations
add Travis County's regulations: http://austintexas.gov/department/public-health-regulations-unincorporated-areas-travis-county

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Public Health > Information Pages

**Comment by annieszot** [comment]
@LauraTrujillo I'll assign myself, and take steps forward after we discuss catch-all pages at our inaugural content pin-up on Tuesday :)

**Comment by desigonz** [comment]
@annieszot Are you still working on this page? It seems to me like this is a page that we could archive, or at least put into the backlog for when we have a solution for codes and ordinances. At the moment, the page doesn't seem terribly useful to residents)

**Comment by annieszot** [comment]
@desigonz Haven't touched this page since it was assigned, so we could archive or backlog for codes and ordinances. Bringing in @LauraTrujillo to double check.

**Comment by LauraTrujillo** [comment]
@annieszot @desigonz Let's backlog it until we figure out codes and ordinances... and also how best to organize that content :)

**Comment by desigonz** [comment]
@LauraTrujillo @annieszot perfect!
