### ISSUE TITLE
Draft Smoking in Public Places Information page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1176]
original link: http://austintexas.gov/department/smoking-public-places
(include information from the other pages it links out to)

copy this template (disregard OPO content): https://docs.google.com/document/d/1DAcBVOsWZ0F0nFEIjOFX_-9RxG1jCzMUf4jTzg1O6rI/edit

Save in:
Austin.gov > Content > Content Transitions > Public Health > Information Pages

Aha! Link: https://desi1.aha.io/features/RT-42

**Comment by desigonz** [comment]
[Draft lives here](https://docs.google.com/document/d/1lvQczE59avNNcrL0VX_idMrA21OY0l4cq3_rXXpqgFw/edit?usp=sharing). Next step is to reach out re: fact checking.

**Comment by desigonz** [comment]
Karina Moore in APH responded to my fact checking queries and I've incorporated my edits into the draft. 

Assigning to @JeffCopy for first review: https://docs.google.com/document/d/1lvQczE59avNNcrL0VX_idMrA21OY0l4cq3_rXXpqgFw/edit?usp=sharing

**Comment by oliver2g** [comment]
@JeffCopy @desigonz any blockers on this?

**Comment by JeffCopy** [comment]
No, it's to me for review; I started on it, got pulled into something else, need to circle back.

**Comment by oliver2g** [comment]
ok cool @JeffCopy. if you have bandwidth to get to it this sprint, pls add it to the milestone. thanks!

**Comment by JeffCopy** [comment]
My suggestions added, tag you're it @desigonz.

**Comment by desigonz** [comment]
Passing off to @LauraTrujillo for 2nd review.

**Comment by LauraTrujillo** [comment]
Reviewed! Great work!
