### ISSUE TITLE
Top 10 Media requests

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1179]
- [x] Get report from Amenity (or anyone else who receives the digest
- [ ] Ask Sarah R. about her availability to help me find patterns in the requests

**Comment by amenity** [comment]
@LauraTrujillo - David Green added you to the digest! You might circle back with him to see if there's a database/spreadsheet of some sort?

**Comment by LauraTrujillo** [comment]
@amenity Yes! I received it this morning. Thank you! That's a great idea- will do.

**Comment by easherma** [comment]
Just fyi if y’all want we can write a script that goes through them all and
counts most common words, etc.

**Comment by LauraTrujillo** [comment]
@easherma That would be super cool! Low priority, but I'm intrigued!
