### ISSUE TITLE
Police Oversight form: Got multiple emails when I submitted a single complaint 

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#1185]
**Describe the bug**
I got three emails when I only submitted one complaint??

**Comment by sergiogcx** [comment]
I have been looking into this, and I have not been able to replicate; however, I did make some changes that I thought could be causing this problem.

**The changes have been deployed to staging, feel free to test the form (or the endpoint)**
https://6jm8rnjkxf.execute-api.us-east-1.amazonaws.com/staging/form/submit

Originally, the backend would iterate through a list of recipients (a total of three: the user, opo, and apd) and send an email for each.

That has now changed to submitting three separate emails through thee separate function calls, to make sure the variables do not share memory values.

Here is the code, the function that submits an email:
https://github.com/cityofaustin/form-service-api/blob/84cc4fab8bcb99fdb4a52ffe7e6d1f54b6ad2c85/main.py#L524

And the three separate instances where the email will be sent:
https://github.com/cityofaustin/form-service-api/blob/84cc4fab8bcb99fdb4a52ffe7e6d1f54b6ad2c85/main.py#L749

** More testing will be needed, let's sit down and take an hour or two for testing **

**Comment by amenity** [comment]
https://github.com/cityofaustin/techstack/issues/1212 continues
