### ISSUE TITLE
Police Oversight form: Clean up email design for Outlook Windows desktop client

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1190]
Initially Outlook was not even showing the header at all, then in no colors (all gray); then, after some effort, I managed to make Outlook look like this:

![Screen Shot 2019-02-11 at 9.18.55 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/98954db5-5b92-423a-84fe-881c6ef851ab)

This is the "responsive" version:

![Screen_Shot_2019-02-11_at_9_19_29_PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/fb9449cb-f346-4786-a5ba-724de76c9f42)

Aha! Link: https://desi1.aha.io/features/RT-35

**Comment by sergiogcx** [comment]
![Screen Shot 2019-03-19 at 12.33.23 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/8b6d2bb7-43db-4a97-aee5-5720c191e4e4)

![Screen_Shot_2019-03-19_at_12_34_34_PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/84965cad-4c25-47fc-b40f-8558b2fa4056)

![Screen_Shot_2019-03-19_at_12_35_53_PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/2c5e5a6d-530d-499b-91c3-696a559bfbbd)

![Screen_Shot_2019-03-19_at_12_39_26_PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/6881ae34-b07b-4dbc-9969-0a3b7b18e3bb)

**Comment by oliver2g** [comment]
Verified that this fix looks good on Friday 3/22 on a windows machine in the Outlook client
