### ISSUE TITLE
Police Oversight form: Search and replace Python script for translation

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1191]
Contingency plan for translation - search and replace in JSON file.

**Comment by amenity** [comment]
@sergiogcx - for today:

**Comment by amenity** [comment]
@sergiogcx -add link here when it's in repo

**Comment by sergiogcx** [comment]
Ah, here it is. I created it earlier and sent the link to Eric, forgot to post it here.

https://github.com/cityofaustin/officer-complaint-form/pull/28
