### ISSUE TITLE
Police Oversight form: Further work with Python translation script

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1192]
- [ ] Incorporate into Travis build script
- [ ] Syntax checker (since theoretically content team could be editing string file)
- [ ] Training for the content team

**Comment by easherma** [comment]
@amenity I'm sure if it makes sense for me to write more issues beyond the checklist we have here?

**Comment by sergiogcx** [comment]
The pipeline is ready & tested, ready to be merged:
https://github.com/cityofaustin/officer-complaint-form/pull/28

This still contains the "street" spanish (my own translation) as opposed to the official translation. That will take half a day or about that long, so I think a separate task needs to be created for it.

Thank you @briaguya for your review, I will merge Friday evening. In the mean time, I will spend time with the official translation and the pipeline for the Thank you form.
