### ISSUE TITLE
Police Oversight form: Implement redirects and final URLS for forms

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1193]
[Austin.gov Standards for IA and URLs](https://docs.google.com/document/d/1pI2vdbAC4gpupVU02GLo6qGr6nsEJGuEORnVHJqs6JM/edit#):
> With forms.austin.gov as the single subdomain used for our forms infrastructure across departments, forms will use a path such as forms.austin.gov/police-thank and forms.austin.gov/police-complain. This allows us to support the needs of additional departments as we scale, and keeps our infrastructure centralized so that it can be updated, improved, and audited in one place.

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [x] Redirect `forms.austin.gov` to Austin.gov

- [x] `forms.austin.gov/police-complain` for English complaint

- [x] `forms.austin.gov/policia-queja` for Spanish complaint

- [x] `forms.austin.gov/police-thank` for English thank you

- [x] `forms.austin.gov/policia-agradezca` for Spanish thank you

**Comment by sergiogcx** [comment]
It's done, this issue can now be closed.
