### ISSUE TITLE
Revise immunizations service page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1195]
http://alpha.austin.gov/services/get-immunized and https://www.austintexas.gov/immunizations

Note from content inventory: 
- Sidebars have important information that could be incorporated into the information. 
- Page needs to be reprioritized

Additional notes from me: 
- Surface clinic hours 
- Rethink lists of vaccines
- Where's the flu shot?
- Add a map.
- Review payment--aren't they free for some groups? 
- Make sure important content from current immunizations page has a home

**Comment by desigonz** [comment]
My edits using the new service page template saved here: https://docs.google.com/document/d/1CdHeFbMTTUabOuf7qeg6wZh_Zaw8YK52ACuPn-B0M8M/edit?usp=sharing

This page already [exists on alpha](http://alpha.austin.gov/services/get-immunized) but I noticed discrepancies and missing content as I was working on information pages that link to this one.

**Comment by desigonz** [comment]
Sending to @JeffCopy for first review

**Comment by JeffCopy** [comment]
A few proposed revisions, back to you!

**Comment by desigonz** [comment]
Thanks @JeffCopy! Assigning @LauraTrujillo for 2nd review.
