### ISSUE TITLE
Police Oversight form: Send CTM final form fields

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1196]
Send David Gottlieb a list of the final fields for the OPO complaint and compliment form. He will update the Sharepoint site he built for OPO accordingly.

**Comment by easherma** [comment]
@oliver2g I saw this issue and noticed amenity was still assigned, we should probably check if this has been done/needs to be confirmed?

**Comment by amenity** [comment]
Very much done. ✅
