### ISSUE TITLE
Visual design: Topic landing page

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1202]
Aha! Link: https://desi1.aha.io/features/RT-27

**Comment by toribr** [comment]
Look at #1203 for reference.

**Comment by chasechenevert** [comment]
## Visual design: Topic Landing
- Without service collection [please see the sub-topic page](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/ba8a7770-c654-4128-a42a-b4f7b5e8f64d/Sub-topic-Landing-MVP-Desktop-1/) for how this is styled
- With service collection

### Dev specs
- [Desktop](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/6808c014-dbbe-4e50-94d4-b086604d3265/Topic-Landing-MVP-Desktop/)
- [Mobile](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/c38c2796-e87a-4a74-bb2d-2bf485f25c05/Topic-landing-MVP-Mobile-Closed/)

<img width="1062" alt="Screen Shot 2019-04-04 at 10 00 07 AM" src="https://user-images.githubusercontent.com/7027270/55566152-b90f2d80-56c0-11e9-9d7d-2edcba9f7003.png">

### Service collections
Based on mass.gov's model [view example](https://www.mass.gov/topics/licenses-ids)
> Service collections bundle relevant information about a page and surface relevant links and services so that the user can take action immediately if they see what information they need, without needing to click into another topic or sub-topic page. Users are provided with more contextual information that helps them determine
