### ISSUE TITLE
Visual design: Navigational component for end node page

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1203]
Visual design from wireframe

**Comment by toribr** [comment]
I'm closing this issue, because topic and any sub-topic landing pages have the exact same structure.

**Comment by toribr** [comment]
Look at #1201 for reference.

**Comment by chasechenevert** [comment]
## Navigational Elements MVP
### Dev Specs
- Component: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/ddc6cb4a-1e5b-4f53-b7f7-ac8626f720ce/Navigation-Footer-Mobile-1/

<img width="1456" alt="Screen Shot 2019-03-27 at 2 04 49 PM" src="https://user-images.githubusercontent.com/7027270/55121157-2b7f7c80-50c7-11e9-8415-d4df578c88e1.png">

**Example of navigational elements within an end node such as a service page.**
Note that "offered by" and "related to" tags drop off on tablet and mobile, leaving on the return link to the node's parent page.
- Web: 
- Mobile: 
<img width="1883" alt="Screen Shot 2019-03-27 at 2 10 18 PM" src="https://user-images.githubusercontent.com/7027270/55121149-1b679d00-50c7-11e9-9218-6959ea3cfb5a.png">

**Comment by toribr** [comment]
1) Far left: parent topic title: travels up to immediate parent node (topic or dept) 
2) Middle: related to: shows sister topics, if any (probably rare for a while)
3) Last: Offered by: department name goes here
