### ISSUE TITLE
Visual design: Service collection

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1204]
Visual design of service collection wireframe

**Comment by chasechenevert** [comment]
## Service collection visual design
### Dev specs
- Desktop: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/6808c014-dbbe-4e50-94d4-b086604d3265/Topic-Landing-MVP-Desktop/
- Mobile: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/c38c2796-e87a-4a74-bb2d-2bf485f25c05/Topic-landing-MVP-Mobile-Closed/

### Notes
Mobile
- service collection turns to an accordion
- disable hyperlink (title) and suppress arrow icon

**Reference**: [mass.gov](https://www.mass.gov/topics/early-childhood-education-care)
