### ISSUE TITLE
Police Oversight: Complaint Form: Document translation format

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/techstack#1207]
The translation format should be documented for further translations.

**Comment by sergiogcx** [comment]
I took a couple hours to document the format of the translation files:

https://github.com/cityofaustin/officer-complaint-form/blob/07e1daa28d6bddd0583f6cc0e5703a8600f670ed/locale/README.md

Let me know your thoughts,

**Comment by amenity** [comment]
❤️
