### ISSUE TITLE
Police Oversight Form: Prototype/mocks of OPO "microsite"

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1208]
When we launch the form, it will link to the OPO department and information pages in Janis 2.0 as if it's a mini standalone site. We would like to show our partners at CPIO & CTM what this will look like. It will also serve as specs for the dev team and any contractors we bring on.

It would be wonderful if it could be a clickable prototype, but straight up mocks are also fine.

It should contain
- _Complaint investigation process_ information page with [final content](https://docs.google.com/document/d/1UFLOvMU75FIhLdHdu2qJl4n7QqaFnQb5-lVj1S0AJHM/edit)
- _How we store and use your data_ information page with [final content](https://drive.google.com/open?id=1wrbujcoozIwzwjSHGGKZIPNJclrGXBdNxtjHG5zosdU)
It will need the following changes
- _Office of Police Oversight_ department page with [final content](https://drive.google.com/open?id=1aNMVFzTNvsijo4rbzBk5jYpQOs5NquHVSWlqzV3wO50)

Changes/updates

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [x] "Alpha" removed from header

- [x] Global menu removed or updated to be a "microsite" menu between the three pages

- [x] Add thank you button

- [x] "Alpha.austin.gov is a new website and a work in progress." where the lorem ipsum is in the footer.

- [x] (Maybe, up to y'all) Remove "Related Services" section

- [x] Remove Vietnamese and Arabic buttons

- [x] Remove sitemap in the footer; just disclaimer with link to project site and Austintexas.gov
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://desi1.aha.io/features/RT-23

**Comment by toribr** [comment]
Yes, let's def remove "related services"

**Comment by chasechenevert** [comment]
Thank you @amenity--this is helpful!

**Re: Footer and "Alpha.austin.gov is a new website and a work in progress."**
Tori wanted to get Content to write us something a little more descriptive since "new website" doesn't really help the user understand what "Alpha" is. It may totally be out-of-scope for right now so I can put back the original text, but just to flag it for us.

**Comment by amenity** [comment]
@chasechenevert @toribr - I was thinking the same thing. I think @LauraTrujillo was involved with the current sentence for the homepage and I wouldn't be surprised if it was arrived at after much discussion/negotiation with stakeholders. I'm okay with whatever design+content decides.

**Comment by LauraTrujillo** [comment]
@chasechenevert  @toribr @amenity I'm not crazy about the "new website" part. At the time it fit our needs, but needs change! Happy to re-work something that explains Alpha and could also grow with the project.

**Comment by annieszot** [comment]
@amenity @LauraTrujillo @chasechenevert @toribr Footer suggestion: Alpha.Austin.gov is the people of Austin’s toolbox to design a website that’s built to hear and deliver their needs and wants.

**Comment by amenity** [comment]
@chasechenevert - would you add a size & estimate to this, please? 🙏 👕
