### ISSUE TITLE
Police Oversight: Complaint Form: Issues with Internet Explorer

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/techstack#1210]
So it does appear that the form does not work in Internet Explorer, I have run a quick view from BrowserStack and this is one of the outputs:

![pic1.png](https://s3.amazonaws.com/police-monitor-website-pr/pic1.png)

![pic2.png](https://s3.amazonaws.com/police-monitor-website-pr/pic2.png)

Aha! Link: https://desi1.aha.io/features/RT-21

**Comment by easherma** [comment]
https://github.com/pqina/filepond/issues/82

https://github.com/pqina/filepond-polyfill

**Comment by easherma** [comment]
related https://github.com/cityofaustin/techstack/issues/1281

**Comment by wilhitem** [comment]
verified, works in IE 11 now!
