### ISSUE TITLE
Police Oversight form: Check on Spanish master build

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1213]
Build seems inconsistent between English and Spanish: 
- placeholder for race
- arrows on back and continue buttons

**Comment by easherma** [comment]
https://forms.austintexas.io/fiscalizacion-de-policia/queja

**Comment by easherma** [comment]
no hay bronca!  ( LGTM)

**Comment by easherma** [comment]
Should be live at https://forms.austintexas.io/police-oversight/complaint
