### ISSUE TITLE
Police Oversight form: Index.html file

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1214]
<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] HotJar #369

- [ ] Google analytics #1108 

- [x] Document language #1150
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

**Comment by easherma** [comment]
I've also added the site header for launch to the index.html.

**Comment by easherma** [comment]
For now I'm just making updates in two places :-/

**Comment by amenity** [comment]
@briaguya @sergiogcx - can we reduce the redundancy here and just pull the same index.html file into both forms? Note that the `lang` parameter will need to change for the Spanish forms.
