### ISSUE TITLE
Police Oversight form: Migrate translated content for complaint form

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1219]

**Comment by amenity** [comment]
@sergiogcx - Eric is going to start on this, picking up where your #1199 leaves off. Thinking that we should have all the strings for both forms in one file since it's safer for longer-term maintenance - e.g. someone from the content team needs to go in and change the wording of a question that's used in both places.

**Comment by desigonz** [comment]
Finished migrating the official translations from the current translation doc. I noticed a few inconsistencies or places where we are missing a new translated—made [#1220](https://app.zenhub.com/workspaces/5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/1220) to track those
