### ISSUE TITLE
Write materials for usability testing screening process 

### ISSUE THREAD

**Issue by aineeathar** [cityofaustin/techstack#122]

**Comment by LauraTrujillo** [comment]
@aineeathar are you using this to help? Do you need anything else? https://docs.google.com/document/d/1xnWcRkUo7cIjPmZafm3HGpYA1Val3R_VPux8AOCVVc8/edit#heading=h.cc9wsfrak10q

**Comment by aineeathar** [comment]
I’m a bit behind here but will organize my tasks today and ping you if I need help! Thanks for checking in.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
