### ISSUE TITLE
Police Oversight form: Compile list of additional/updated translations

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1220]
## Global
- [ ] ["Back"](https://github.com/cityofaustin/officer-complaint-form/blob/77a88ce2c29efcfa20089381cc436f2c01f9b798/locale/translations.json#L372) and ["continue"](https://github.com/cityofaustin/officer-complaint-form/blob/77a88ce2c29efcfa20089381cc436f2c01f9b798/locale/translations.json#L384) buttons
- [ ] ["Edit"](https://github.com/cityofaustin/officer-complaint-form/blob/77a88ce2c29efcfa20089381cc436f2c01f9b798/locale/translations.json#L460) button
- [ ] ["Remove"](https://github.com/cityofaustin/officer-complaint-form/blob/77a88ce2c29efcfa20089381cc436f2c01f9b798/locale/translations.json#L436) button
- [ ] ["Select race"](https://github.com/cityofaustin/officer-complaint-form/blob/77a88ce2c29efcfa20089381cc436f2c01f9b798/locale/translations.json#L360)
- [ ] ["Sending"](https://github.com/cityofaustin/officer-complaint-form/blob/77a88ce2c29efcfa20089381cc436f2c01f9b798/locale/translations.json#L380) button
- [ ] ["Browse"](https://github.com/cityofaustin/officer-complaint-form/blob/6b726c7757477890085c0042bd2d88146bca48ce/locale/translations.json#L391)

*Note: for our "add another" button, the translator split into two: "Añadir un oficial" and "Añadir un testigo." I changed to "Añadir otro"—differentiating them would mean we need two different English phrasings

## "Tell us what happened" page
- [ ] ["Please provide a response"](https://github.com/cityofaustin/officer-complaint-form/blob/6b726c7757477890085c0042bd2d88146bca48ce/locale/translations.json#L279) error message
- [ ] ["Date and time, if known?"](https://github.com/cityofaustin/officer-complaint-form/blob/6b726c7757477890085c0042bd2d88146bca48ce/locale/translations.json#L68) re-do—it's translating to "¿Qué día sucedió?" (time only)
- [ ] ["I received a ticket during this interaction."](https://github.com/cityofaustin/officer-complaint-form/blob/77a88ce2c29efcfa20089381cc436f2c01f9b798/locale/translations.json#L73) currently translates to "¿Recibió una multa?"—change to first person?
- [ ] ["Skip this if you prefer to remain anonymous."](https://github.com/cityofaustin/officer-complaint-form/blob/6b726c7757477890085c0042bd2d88146bca48ce/locale/translations.json#L80) (To be added to [line 80](We'll need your name in order to find the ticket you’re referencing.) 
- [ ] ["Location"](https://github.com/cityofaustin/officer-complaint-form/blob/77a88ce2c29efcfa20089381cc436f2c01f9b798/locale/translations.json#L476)
- [ ] ["Type in the location or drag the map to the location."](https://github.com/cityofaustin/officer-complaint-form/blob/77a88ce2c29efcfa20089381cc436f2c01f9b798/locale/translations.json#L364)
- [ ] ["Enter a location here"](https://github.com/cityofaustin/officer-complaint-form/blob/77a88ce2c29efcfa20089381cc436f2c01f9b798/locale/translations.json#L81)
 
## "Share your photos or videos" page
- [ ] ["Upload any evidence that you have (video files, audio files, photos, police report, hospital record, etc)"](https://github.com/cityofaustin/officer-complaint-form/blob/77a88ce2c29efcfa20089381cc436f2c01f9b798/locale/translations.json#L97)
- [ ] ["Drag and drop your files or "](https://github.com/cityofaustin/officer-complaint-form/blob/77a88ce2c29efcfa20089381cc436f2c01f9b798/locale/translations.json#L101)
- [ ] ["Uploading", "Upload complete", "Upload canceled"](https://github.com/cityofaustin/officer-complaint-form/blob/77a88ce2c29efcfa20089381cc436f2c01f9b798/locale/translations.json#L408)
- [ ] ["tap to cancel", "tap to retry", "tap to undo"](https://github.com/cityofaustin/officer-complaint-form/blob/77a88ce2c29efcfa20089381cc436f2c01f9b798/locale/translations.json#L408)
- [ ] ["Error during upload"](https://github.com/cityofaustin/officer-complaint-form/blob/bd78052c99ca75a085b3c1ddf92ff858d2b8b8ed/locale/translations.json#L420)

## "Tell us about you" page
- [ ] ["I would like an interpreter for all my future interactions."](https://github.com/cityofaustin/officer-complaint-form/blob/bd78052c99ca75a085b3c1ddf92ff858d2b8b8ed/locale/translations.json#L173) currently translates to "¿Le gustaría que buscáramos...?"—should we change to first person to match?

## "Review your answers before submitting" page
- [ ] ["Submit"](https://github.com/cityofaustin/officer-complaint-form/blob/bd78052c99ca75a085b3c1ddf92ff858d2b8b8ed/locale/translations.json#L376)

**Comment by amenity** [comment]
Thanks for the super-organized compilation, @desigonz! I removed the "Placeholder Officer Details" items, per #1094. 
@LauraTrujillo - I'm assigning this to you to send to the translators. 🙏

**Comment by amenity** [comment]
Re: "I received a ticket...", @toribr @chasechenevert - Do we want this first person even though the rest of the form is second person?

**Comment by toribr** [comment]
Good point. It should probably be: Did you receive a ticket during this interaction?

And also, while we're there: "We'll need your name in order to find the ticket you’re referencing. Skip this if you prefer to remain anonymous."

**Comment by desigonz** [comment]
My guess is that the first person happened when the interaction became a checkbox (rather than yes/no radio buttons). I think it would be strange to have a checkbox with a second-person question like "Did you receive a ticket during this interaction?"

@amenity & @LauraTrujillo — I haven't done the thank you form translation migration yet; you might want to wait to see if anything is missing there to send them as a batch. Planning to get to that today/tomorrow.

**Comment by amenity** [comment]
@desigonz - yup, Tori just pointed that out in a convo. And good call on waiting for the thank you form translation.

**Comment by amenity** [comment]
@desigonz - please add a list of the translations as a Word doc [here](https://drive.google.com/drive/folders/1uhVFQsOoET9vfzjIgOc2abvDUba6scQy) and ping @LauraTrujillo as soon as it's done. 🙏

**Comment by amenity** [comment]
@desigonz @LauraTrujillo - cleaning up issues, I think it makes sense to have this as Desi's task to compile the content, and #1181 as the send off.

**Comment by LauraTrujillo** [comment]
@desigonz @amenity Sent to translators!
