### ISSUE TITLE
Police Oversight form: Add sentence to ticket text

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1222]
Add "Skip this if you prefer to remain anonymous." to the italic helper text under the ticket number field.
<img width="426" alt="screen shot 2019-02-18 at 12 48 41 pm" src="https://user-images.githubusercontent.com/1463708/52971643-d9d42b80-337d-11e9-860b-06ccc0b5bff6.png">

Aha! Link: https://desi1.aha.io/features/RT-14

**Comment by easherma** [comment]
Just pointing out this this will also need to go through translation and be added to the spanish pipeline

**Comment by amenity** [comment]
Yup, #1220.

**Comment by easherma** [comment]
@amenity it was easy enough that I added it on my way to doing something else. However, we may want to workshop it a bit once we go through all the content, as its just a big ol block of text atm. :-/

**Comment by easherma** [comment]
https://github.com/cityofaustin/officer-form-chapters/commit/74fc0434de53ade4a26e331b54970e74bcb3df6d

**Comment by easherma** [comment]
@desigonz just a ping to make sure we have "Skip this if you prefer to remain anonymous." as a phrase to translate

**Comment by easherma** [comment]
https://github.com/cityofaustin/officer-complaint-form/commit/775028dca7794d67a83f6c9c845e30b0c7e311fd commit to master

**Comment by desigonz** [comment]
yep, "Skip this" in on our list!
