### ISSUE TITLE
Police Oversight form: Update translations.json file 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1226]
Once the translators send @LauraTrujillo our final batch of OPO translations we will need to make updates to the `translations.json` file.

**Comment by LauraTrujillo** [comment]
@desigonz @amenity translation is attached!
[OPO Dept page and global text_Spanish[1].docx](https://github.com/cityofaustin/techstack/files/2902661/OPO.Dept.page.and.global.text_Spanish.1.docx)

**Comment by amenity** [comment]
Yayyyy! 🙌 🇲🇽 🇪🇸 🇵🇷 🇬🇹 🇭🇳 🇪🇨 🇳🇮 ...
