### ISSUE TITLE
Austin.gov project site update

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1228]
Aha! Link: https://desi1.aha.io/features/RT-9

**Comment by JeffCopy** [comment]
I've implemented a bunch of suggested edits and questions to consider in the odd website doc, here:
https://docs.google.com/document/d/1vnpChbachE_kUy9o4GdKVhd10La9RAaRoSAcF84sxFw/edit

**Comment by LauraTrujillo** [comment]
Thanks! Sending to Ben to build now!

**Comment by JeffCopy** [comment]
Great!
