### ISSUE TITLE
Police Oversight form: Update translations.json files with additional translations

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1229]
https://github.com/cityofaustin/officer-complaint-form/blob/77a88ce2c29efcfa20089381cc436f2c01f9b798/locale/translations.json

Final translations here: https://docs.google.com/document/d/1fogJT1_rMylbBmcTf62sX6H6Z1Rlh6R779IYB8q0asY/edit

**Comment by desigonz** [comment]
![Unknown.jpeg](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/3ae5306e-8911-437e-a6f0-b6fbc5db2e9f)
![Unknown-1.jpeg](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/2e464d4c-0784-4278-8f6b-340f7219c5d8)
![Unknown-2.jpeg](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/79397374-71c7-416e-b554-b3846c43bdcf)

**Comment by desigonz** [comment]
#Fix—currently showing up in English#
- [ ] Required information
- [ ] Call the Office of...
- [ ] Optional information
- [ ] Officers involved
- [ ] Phone

#Global—mostly buttons#
- [ ] Atrás
- [ ] Continuar
- [ ] Editar
- [ ] Eliminar
- [ ] Seleccionar raza
- [ ] Enviando
- [ ] Explorar

#“Tell us what happened” page#

- [ ] Por favor provea una respuesta 
- [ ] Fecha y hora, si las sabe 
- [ ] Recibí una multa durante esta interacción. 
- [ ] Pase a la siguiente si desea permanecer anónimo
- [ ] Ubicación
- [ ] Escriba el lugar o arrastre el mapa hasta la ubicación.
- [ ] Introduzca una ubicación aquí

#“Share your photos or videos” page#

- [ ] Cargue cualquier evidencia que tenga (archivos de video, audio, reportes de policía, reportes de hospital, etc.)
- [ ] Arrastre y suelte sus archivos o
- [ ] Cargando
- [ ] Archivo cargado
- [ ] Archivo cancelado
- [ ] Oprima para cancelar
- [ ] Oprima para intentar otra vez
- [ ] Oprima para deshacer
- [ ] Error al cargar el archivo

#“Tell us about you” page#

- [ ] Me gustaría tener un intérprete en las próximas comunicaciones

#“Review your answers before submitting” page#

- [ ] Enviar

**Comment by desigonz** [comment]
@amenity Made all of the changes to above expect "phone"—it's in this pull request: https://github.com/cityofaustin/officer-complaint-form/pull/54

Re: "phone," it looks the field label used to be "Phone number," which is what's in translations.json, but maybe @easherma abstracted this field out? See screenshot below.

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/9c995382-cea9-41a8-809d-82cf60d77a8f)

**Comment by amenity** [comment]
@easherma - can you advise?

**Comment by easherma** [comment]
Oi, yeah I did in order to get the correct mobile number context to pop up.
I can tweak this though, my bad.

**Comment by amenity** [comment]
Do we need to create another issue for this phone business, @easherma ?

**Comment by desigonz** [comment]
@easherma @amenity Wanted to surface this content edit above again re: "phone" field that should read "phone number" but I don't know where I would make that update :/

**Comment by easherma** [comment]
![Screenshot from 2019-03-27 14-23-59](https://user-images.githubusercontent.com/10539855/55106048-f9a4f080-509b-11e9-89db-b2e2f04c1541.png)
looks addressed, I remember doing this, sorry for not noting on the issue.

**Comment by desigonz** [comment]
@easherma The issue is actually in English—should read "Phone number" on the witness details page, not "Phone," but I wasn't able to find where that label lives.
