### ISSUE TITLE
Refactor access tokens to come from .env file or other kinds of variables

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#1235]
Whenever we get around to updating the HERE geocoder, we should refactor the code to hide our access tokens. Ditto for Mapbox (and we're actually using my personal token there, so add that to the devops list).

**Comment by easherma** [comment]
ATM reverse geocoding is broken because we were sharing the token with ctx floods and @Niicck did the right thing.

We need to: 
* set up a new HERE account under an ODD email address
* ideally refactor the map component to accept access token via .env file or some other hidden variable, but more than likely just paste in the new token for now

**Comment by easherma** [comment]
We can't hide anything on the front end!

**Comment by amenity** [comment]
Would be better to load in separate file, but not a priority.
