### ISSUE TITLE
Police Oversight form: Browserstack testing

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1241]
Devices & browsers to test based on [Austintexas.gov analytics](https://github.com/cityofaustin/techstack/issues/1240).

Mobile:
- [x] iPhone: Safari 12.0
- [x] Android: Chrome 71.0

Desktop:
- [x] Windows 10: Chrome 71.0
- [x] Windows 7: Chrome 71.0
- [x] MacOS 10.14: Chrome 71.0
- [x] Windows 10: Edge 17.17

**Comment by amenity** [comment]
@desigonz - making this a large and assuming it will go into Sprint 25. Adjust as necessary!

**Comment by desigonz** [comment]
@amenity Tested these browsers and reported bugs. I also used the WAVE tool and submitted one a11y bug!

There are still some content and translation changes to be incorporated (#1284, #1223)—we should watch them in case those break translations and Spanish form functionality

**Comment by easherma** [comment]
fyi I merged those in, if anything I think that fixed problems instead of
causing them ;-)

**Comment by amenity** [comment]
@desigonz @easherma y'all turned up and blew out those bugs like superheros!! Thank you.
