### ISSUE TITLE
Police Oversight form: Social media blurb to recruit user testers

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1247]
Write up something and work with OPO to refine and post to their social media channels.

**Comment by toribr** [comment]
This should include a link to this screener: https://goo.gl/forms/R5dOSFclfPz5GzBs2

So, something like: Help us improve our form for reporting complaints and thanks for the Austin Police Department! Interested parties fill out this survey (link above) and we will reach out if you are a good fit for the next study.

**Comment by amenity** [comment]
@LauraTrujillo - assigning to you b/c I know you'd do such an impeccable job, but feel free to delegate!

**Comment by LauraTrujillo** [comment]
One option: Do you want to help improve the form for sending complaints or thanks to the Austin Police Department? Fill out this survey (link to: 
https://goo.gl/forms/R5dOSFclfPz5GzBs2) and we will follow up with you. 

What do you think, @sarafperalta
