### ISSUE TITLE
Police Oversight form: Carver 2/25 testing - sign to recruit library visitors

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1252]

**Comment by amenity** [comment]
@desigonz - will you size this please? 🙏

**Comment by desigonz** [comment]
@toribr Here's the sign I came up with, to print onto tabloid size: https://docs.google.com/presentation/d/1ritLngdBjOfN0nIeEHOUa7dxE4FgcmReGjUnjgmcxgg/edit?usp=sharing

- Thoughts on adding ODD logo or City of Austin seal to communicate who we are? Or is it better to stay anonymous?
- I used vague language re: what we're testing ("our new website"); I figured we can better explain in person and get more specific about what OPO is and does.

Let me know what you think!

**Comment by desigonz** [comment]
@toribr @chasechenevert I'm not getting an option to print onto the tabloid-sized paper—could one of y'all help me print this on Monday morning?
