### ISSUE TITLE
Police Oversight form: Carver 2/25 testing -photograph tests

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1256]
take photos of the test and clean a few good ones for presentation decks/digest/etc.

**Comment by chasechenevert** [comment]
Here's a link to 2 pics within the project folder in Drive: https://drive.google.com/drive/u/0/folders/18ybxZgybNQrNP5K9FDwdpw5IKnSB3dAX

Austin.gov > 02 Public Interface / Janis > Alpha pages > [Page_Office of Police Oversight](https://drive.google.com/drive/u/0/folders/1XBM1c5Ba5-_Gzbj8Z3PpspCEDvtSt9X-)
