### ISSUE TITLE
Police Oversight: Fix Language Links

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/techstack#1258]
The English/Spanish links do not work for the OPO form. Will hard code them for now until we can figure out a better way.

**Comment by sergiogcx** [comment]
I created a PR branch, with minimal changes. It has been merged to master and it has been tested to work:  https://github.com/cityofaustin/officer-complaint-form/tree/1258-sg-ocf-urlinks

**Comment by easherma** [comment]
@sergiogcx we are good to close then, no?
