### ISSUE TITLE
Bug: Date and time field is grayed out

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1259]
**Describe the bug**
Date and time field displays as a filled in gray box out in Android—none of the other fields look like this

**URL**
https://forms.austintexas.io/police-oversight/complaint/what-happened

**Additional context**
Doesn't prevent user from completing a task, it's just inconsistent design-wise. Super low priority

**URL tested:** https://dxun9n0idyi09.cloudfront.net/police-oversight/complaint/what-happened

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=9.0&device=Google+Pixel+2&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fdxun9n0idyi09.cloudfront.net%2Fpolice-oversight%2Fcomplaint%2Fwhat-happened&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dxun9n0idyi09.cloudfront.net/police-oversight/complaint/what-happened) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Google Pixel 2 |
| Browser | Mobile_chrome |
| Operating System | Android 9.0 |
| Resolution | 1080 x 1920 px |
| Screen size | 5.74 in - 2.74 x 5.0 in |
| Viewport | 411 x 731 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/b41ae9903a63e2250721065f26efc61596580a99/realdroid_Google_Pixel_2.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/b41ae9903a63e2250721065f26efc61596580a99/realdroid_Google_Pixel_2.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=android&os_version=9.0&device=Google+Pixel+2&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fdxun9n0idyi09.cloudfront.net%2Fpolice-oversight%2Fcomplaint%2Fwhat-happened&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dxun9n0idyi09.cloudfront.net/police-oversight/complaint/what-happened) to reproduce the issue on Browserstack**

**Comment by sergiogcx** [comment]
Using my android phone it looks grayed-out, but when I tap on it shows the date-time picker just fine.

![Screenshot_20190220-201837.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/b956f675-8cee-4ad5-b1fb-903495332887)

![Screenshot_20190220-201900.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/49ca1c09-a844-4fb9-81d0-29af4bb9bc11)

**Comment by desigonz** [comment]
@sergiogcx — yep, functionality-wise it works just fine. I was wondering if this is the kind of thing that's _too_  fine-grained to report

**Comment by amenity** [comment]
@desigonz @sergiogcx - I'd rather err on the side of overreporting bugs. I'll assign priority, and they'll be dropped in On deck/Short term/Medium-Long term accordingly. Saying something like y'all did, "Super low priority," or "it looks grayed-out, but when I tap on it shows the date-time picker just fine." really helps.

**Comment by sergiogcx** [comment]
@amenity Totally agreed, I am glad @desigonz caught it I would have never found out. I also agree the color needs to change. Will be looking into this.
