### ISSUE TITLE
Bug: add phone number keyboard for witness page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1260]
Regular keyboard showing up for witness phone number field, but phone keyboard for “Tell us about you” phone number field. 

**URL tested:** https://dxun9n0idyi09.cloudfront.net/police-oversight/complaint/officer-details

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=9.0&device=Google+Pixel+2&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fdxun9n0idyi09.cloudfront.net%2Fpolice-oversight%2Fcomplaint%2Fofficer-details&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dxun9n0idyi09.cloudfront.net/police-oversight/complaint/officer-details) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Google Pixel 2 |
| Browser | Mobile_chrome |
| Operating System | Android 9.0 |
| Resolution | 1080 x 1920 px |
| Screen size | 5.74 in - 2.74 x 5.0 in |
| Viewport | 411 x 731 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/4d4ba0a351c55f64da59f8c7b8ba4b39b38ff11a/realdroid_Google_Pixel_2.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/4d4ba0a351c55f64da59f8c7b8ba4b39b38ff11a/realdroid_Google_Pixel_2.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=android&os_version=9.0&device=Google+Pixel+2&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fdxun9n0idyi09.cloudfront.net%2Fpolice-oversight%2Fcomplaint%2Fofficer-details&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dxun9n0idyi09.cloudfront.net/police-oversight/complaint/officer-details) to reproduce the issue on Browserstack**

**Comment by sergiogcx** [comment]
Yep, it does not work on my phone.

**Comment by easherma** [comment]
This is hopefully a quick JSON schema fix, the fact that it affects experience on mobile makes me want to bump it up in priority.

**Comment by wilhitem** [comment]
verified on browserstack on same device/os/app info
