### ISSUE TITLE
Bug: have to tap "Continue" button twice

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1262]
**Describe the bug**
On the "What happened" page when using Safari on iOS (in both Browserstack and on my phone), have to tap "Continue" button twice to submit

**URL**

**To Reproduce**

1. Go to 'What happened' page and fill out description
2. Scroll down and tap on 'Continue'

**Expected behavior**
Expect to submit and continue to next page

**Current behavior**
On Safari, browser chrome appears. If I tap "continue" again, it will submit.

**URL tested:** https://dxun9n0idyi09.cloudfront.net/police-oversight/complaint/

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device=iPhone+XS&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fdxun9n0idyi09.cloudfront.net%2Fpolice-oversight%2Fcomplaint%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dxun9n0idyi09.cloudfront.net/police-oversight/complaint/) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone XS |
| Browser | Mobile_safari |
| Operating System | iOS 12.0 |
| Resolution | 1125 x 2436 px |
| Screen size | 5.8 in - 2.79 x 5.65 in |
| Viewport | 375 x 812 dp |
| Aspect Ratio | 19.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/bdb9924e488016e0e0a0503285d48be30d061c77/realios_iPhone_XS.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/bdb9924e488016e0e0a0503285d48be30d061c77/realios_iPhone_XS.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device=iPhone+XS&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fdxun9n0idyi09.cloudfront.net%2Fpolice-oversight%2Fcomplaint%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dxun9n0idyi09.cloudfront.net/police-oversight/complaint/) to reproduce the issue on Browserstack**

**Comment by sergiogcx** [comment]
@desi @amenity I was able to reproduce this "issue" but only when going directly from the keyboard to the Continue button.

If I get rid of the keyboard first, then I press the Continue button, the form works as expected.

**Comment by amenity** [comment]
Thanks, @sergiogcx - assigned a P5 and moved it to medium-term backlog.
