### ISSUE TITLE
Bug: Map pin icon not appearing in IE

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1268]
**Describe the bug**
Map pin icon not appearing when I'm moving around map; just see a shadow of where the pin would drop. You see the pin when the map first loads but not once you start interacting

**To Reproduce**

1. Go to 'What happened' page
2. Scroll down to map
3. Drag map around to change pin location

**Current behavior**
Pin to appear at new location

**Expected behavior**
Shadow of where pin should be but no actual pin

**URL tested:** https://dxun9n0idyi09.cloudfront.net/police-oversight/complaint/introduction

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdxun9n0idyi09.cloudfront.net%2Fpolice-oversight%2Fcomplaint%2Fintroduction&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dxun9n0idyi09.cloudfront.net/police-oversight/complaint/introduction) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1126x766 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/3736b2e37f041133bd0996514b2f5639ec2b2c34/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/3736b2e37f041133bd0996514b2f5639ec2b2c34/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdxun9n0idyi09.cloudfront.net%2Fpolice-oversight%2Fcomplaint%2Fintroduction&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dxun9n0idyi09.cloudfront.net/police-oversight/complaint/introduction) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
![yikes](https://media.giphy.com/media/80TEu4wOBdPLG/giphy.gif)

**Comment by easherma** [comment]
was not able to replicate...?

**Comment by easherma** [comment]
https://github.com/cityofaustin/officer-complaint-form/pull/43 appears to fix this

**Comment by desigonz** [comment]
we've got a map pin! Closing this issue.
