### ISSUE TITLE
Bug: uneven borders on buttons in IE

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1269]
Uneven border thickness in IE. Another low priority display issue; doesn't affect functionality.

**URL tested:** file:///C:/Users/hello/Desktop/images/cartoon-animation.gif

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=file%3A%2F%2F%2FC%3A%2FUsers%2Fhello%2FDesktop%2Fimages%2Fcartoon-animation.gif&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=file:///C:/Users/hello/Desktop/images/cartoon-animation.gif) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1024x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/8d4e95b0a5c9f414bb3dec40a8f23e4faf7991da/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/8d4e95b0a5c9f414bb3dec40a8f23e4faf7991da/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=file%3A%2F%2F%2FC%3A%2FUsers%2Fhello%2FDesktop%2Fimages%2Fcartoon-animation.gif&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=file:///C:/Users/hello/Desktop/images/cartoon-animation.gif) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
hm, there may not be anything we can do about this/may actually be an artifact from browserstack

**Comment by desigonz** [comment]
@easherma yeah resolution is pretty low on browserstack—sometimes it's hard to tell what's what!

**Comment by sergiogcx** [comment]
Well, this is what I am seeing in a virtual machine:

Internet Explorer 11 (Windows 10):

<img width="1440" alt="ie_1" src="https://user-images.githubusercontent.com/5282430/53290562-62324200-376b-11e9-9ae9-a00282285e23.png">

<img width="1440" alt="ie_2" src="https://user-images.githubusercontent.com/5282430/53290571-8ee65980-376b-11e9-8d0a-ecd147c6beb2.png">



With Edge (Windows 10):

<img width="1440" alt="edge_1" src="https://user-images.githubusercontent.com/5282430/53290578-a9203780-376b-11e9-9cab-daa5ee5a82e2.png">
<img width="1440" alt="edge_2" src="https://user-images.githubusercontent.com/5282430/53290579-a9203780-376b-11e9-80c7-e99665a4cba9.png">


I also checked in Chrome and FireFox in Windows 10, all looking good. So it's not any kind of weird DPI or monitor resolution issue.
