### ISSUE TITLE
Bug: email address too long on "review" page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1270]
On the "review your answers" page, the email address is too long to fit and breaks the right justification.

**URL tested:** file:///C:/Users/hello/Desktop/images/cartoon-animation.gif

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=file%3A%2F%2F%2FC%3A%2FUsers%2Fhello%2FDesktop%2Fimages%2Fcartoon-animation.gif&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=file:///C:/Users/hello/Desktop/images/cartoon-animation.gif) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1024x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/762d9c2430d16f4ffab0c5ce5d34192c1eeb1ba2/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/762d9c2430d16f4ffab0c5ce5d34192c1eeb1ba2/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=file%3A%2F%2F%2FC%3A%2FUsers%2Fhello%2FDesktop%2Fimages%2Fcartoon-animation.gif&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=file:///C:/Users/hello/Desktop/images/cartoon-animation.gif) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
gonna mark this p5: 
It will likely involve some fiddling with css in our review page/with us forms system. This may be a responsive issue as well, I'm curious if this happens on any other browsers. Either way, it doesn't break functionality, and users will get email confirmation anyways so I don't see it as a big deal for launch.
