### ISSUE TITLE
Microsite MVP micro Issues

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1271]
- [x] Make COA title not link to home page
- [x] Replace Farah's image with her actual picture (and make an issue to not have it hardcoded)
- [x] Make the top service links to the forms work
- [x] [Find the hardcoded strings we have and make them translated](https://github.com/cityofaustin/techstack/issues/1307) 
- [x] Breadcrumb link
- [x] Thank you link
- [x] Links on alpha footer
- [x] remove link to home on header 
- [x] arrows for service buttons
- [x] Update URLs: 
   - [x] `forms.austin.gov/police-complain` for English complaint
   - [x] `forms.austin.gov/policia-queja` for Spanish complaint
   - [x] `forms.austin.gov/police-thank` for English thank you
   - [x] `forms.austin.gov/policia-agradezca` for Spanish thank you

![Space Jam](https://media.giphy.com/media/8CSflsMG1IFos/giphy.gif)

**Comment by easherma** [comment]
TODO: 

- [ ] Breadcrumb link
- [ ] Thank you link
- [ ] Links on alpha footer
- [ ] remove link to home on header 
- [ ] arrows for service buttons

**Comment by easherma** [comment]
Reminder: breadcrumb link for forms.gov should link back to dept page on janis now

**Comment by amenity** [comment]
Hardcoded strings: 
- For the full City of Austin website (footer)
