### ISSUE TITLE
Bug: map freezes

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1272]
Not sure if this is a problem with the Browserstack emulator or with Windows 10 Chrome, but the map froze when I tried to use my current location.

**To Reproduce**

1. Go to 'What happened' page
2. Scroll to the map
3. Click the location/bulls-eye icon
4. Allow Chrome to use your current location

**Current behavior**
Zoomed out and located me somewhere north of Oklahoma City. Wouldn't let me manipulate the map again (although I could enter an address in the search bar)

**Expected behavior**
Expect to see map focus on my current location

**URL tested:** https://forms.austintexas.io/police-oversight/complaint/what-happened

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Chrome&browser_version=71.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Fwhat-happened&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/what-happened) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 71.0 |
| Operating System | Windows 10 |
| Resolution | 1202x946 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/a7095aa8bd0ec29e0f50d9fa020387a8ec361259/win10_chrome_71.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/a7095aa8bd0ec29e0f50d9fa020387a8ec361259/win10_chrome_71.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Chrome&browser_version=71.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Fwhat-happened&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/what-happened) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
I wasn't able to reproduce this.

**Comment by easherma** [comment]
Gonna close, we can reopen if it seems to happen more.
