### ISSUE TITLE
Bug: Uploaded evidence doesn't persist

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1275]
When you upload evidence on "Share your photos or videos," navigate to another page, then navigate back, you don't see the uploaded evidence (even though other data you enter persists). However, it does show up on the review page.

Seems low priority—not ideal user experience but functionality is working.

**To Reproduce**

1. Go to 'Share your photos or videos'
2. Click on 'Browse'
3. Select an image to upload
4. Wait for image to upload
5. Click 'Back'

**Current behavior**
Drag/drop/browse field is empty

**Expected behavior**
Expected to see the image I had uploaded earlier.

**URL tested:** https://forms.austintexas.io/police-oversight/complaint/share-evidence

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Chrome&browser_version=71.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Fshare-evidence&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/share-evidence) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 71.0 |
| Operating System | Windows 10 |
| Resolution | 1202x946 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/677898c1398a386a191c07313171f69e705e6f19/win10_chrome_71.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/677898c1398a386a191c07313171f69e705e6f19/win10_chrome_71.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Chrome&browser_version=71.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Fshare-evidence&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/share-evidence) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
ehh, that is not good at all, but we may better be able to tackle this once we refactor the form, unless @sergiogcx has an immediate idea of how to fix ( could be a simple setState but then we start digging into how us-forms systems handles state). I'd put this as a P3.5 if I could.

**Comment by sergiogcx** [comment]
If it is working, it means it is part of the state. I don't think the files are recovered from the state every time FilePond is initialized, I think that to fix this issue we simply have to implement that access, parse the files data structure, and load the thumbnails again.

I haven't looked at this, but for now I have enough on my plate. Probably best for next sprint.
