### ISSUE TITLE
Bug: number picker for phone number field

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1276]
Number UI picker on "Tell us about you" allows you to scroll + and - a digit—doesn't seem appropriate for phone number. The phone number field on witnesses page doesn't use this behavior.

**To Reproduce**

1. Go to 'Tell us about you'
2. Select "I am willing to be contacted..."
3. Click on 'phone number field'
4. Use up and down arrows to increase/decrease

**URL tested:** https://forms.austintexas.io/police-oversight/complaint/about-you

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Chrome&browser_version=71.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Fabout-you&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/about-you) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 71.0 |
| Operating System | Windows 10 |
| Resolution | 1202x946 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/c41e7b4f62ada0ed018b65e888057dedd953291e/win10_chrome_71.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/c41e7b4f62ada0ed018b65e888057dedd953291e/win10_chrome_71.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Chrome&browser_version=71.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Fabout-you&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/about-you) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
gonna call this p3: 
I can look into this, may be related to https://github.com/cityofaustin/techstack/issues/1118 and/or a simple JSON Schema fix...unfortunatley its a bit time intensive to test changes, and since we can trust most users in good faith to be typing in a phone number, I think it would be ideal to have this fixed before or shortly after launch. Dosen't block current functioning of the form, though.

**Comment by wilhitem** [comment]
verified in chome and in IE11.
