### ISSUE TITLE
Bug: visited link styling

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1277]
Visited link for "Learn more about who we are..." shouldn't style as purple

**URL tested:** https://forms.austintexas.io/police-oversight/complaint/introduction

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Chrome&browser_version=71.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Fintroduction&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/introduction) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 71.0 |
| Operating System | Windows 10 |
| Resolution | 1202x946 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/756ff93d12cac0e75f2f9db2c8d67e603af4d0f5/win10_chrome_71.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/756ff93d12cac0e75f2f9db2c8d67e603af4d0f5/win10_chrome_71.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Chrome&browser_version=71.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Fintroduction&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/introduction) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
Quick enough fix, but not super high priority IMO. Most people will visit the form for the first time.
