### ISSUE TITLE
Persist data when switching from English to Spanish

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1279]
When a user switches languages at any point in the form, they are sent to the introduction page for the new language. All data they have submitted is lost. 

Preferred experience is that the data persists when user switches languages.

**Comment by easherma** [comment]
Good call, I don't think it's feasible not feasible to fix this before launch, but once we refactor everything we can probably tackle this.

**Comment by easherma** [comment]
@toribr brought up that this is pretty terrible UX. However, in the meantime we could add an alert that at least lets a user know from data is lost if they switch languages.

**Comment by amenity** [comment]
@toribr @easherma @sergiogcx @oliver2g - probably good to discuss this in the 3/19 dev/design sync! If a fix is not in scope for the OPO media push, what makes sense for an alert in the meantime?

**Comment by desigonz** [comment]
consolidated this into #1722
