### ISSUE TITLE
Bug: can't edit Spanish "review" page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1280]
This is a fun one! Was also able to reproduce it on my own browser (aka not Browserstack)

**To Reproduce**

1. Select "Español"
2. Fill out form through review page
3. Click any "edit" button

**Current behavior**
Doesn't allow me to edit fields the way I can with the form when it's in English. Seems like page refocuses on the edit button I just clicked.

**Expected behavior**
Ability to edit the field

**URL tested:** https://forms.austintexas.io/fiscalizacion-de-policia/queja/revisar-y-enviar

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=71.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Ffiscalizacion-de-policia%2Fqueja%2Frevisar-y-enviar&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/fiscalizacion-de-policia/queja/revisar-y-enviar) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 71.0 |
| Operating System | OS X Mojave |
| Resolution | 1548x946 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/bf151a25a3746f0b63a9e3d904969614e980841b/macmo_chrome_71.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/bf151a25a3746f0b63a9e3d904969614e980841b/macmo_chrome_71.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=71.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Ffiscalizacion-de-policia%2Fqueja%2Frevisar-y-enviar&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/fiscalizacion-de-policia/queja/revisar-y-enviar) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
@sergiogcx wanna take a look at this when you can?

**Comment by easherma** [comment]
appears to be fixed by https://github.com/cityofaustin/officer-complaint-form/commit/f159d4bd84cb81d1998cec499a810551de089c27 or something close to it
