### ISSUE TITLE
Bug: upload loading forever (on IE)

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1281]
Tried uploaded an image on IE, but it just said "uploading" indefinitely. Also couldn't click to cancel.

**URL tested:** https://forms.austintexas.io/police-oversight/complaint/introduction

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=7&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Fintroduction&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/introduction) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 7 |
| Resolution | 1548x946 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/1cfa219624d8adb016e5c600ef271f6ad0371a80/win7_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/1cfa219624d8adb016e5c600ef271f6ad0371a80/win7_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=7&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Fintroduction&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/introduction) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
![screenshot from 2019-02-22 14-23-33](https://user-images.githubusercontent.com/10539855/53269068-80d20380-36ad-11e9-9686-a6b578d0d5be.png)

**Comment by easherma** [comment]
appears to be fixed with https://github.com/cityofaustin/officer-complaint-form/pull/43

**Comment by desigonz** [comment]
Also confirmed that this one's working.
