### ISSUE TITLE
Bug: can't open closed accordions in Spanish

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1282]
Might be related to [#1280](https://app.zenhub.com/workspaces/5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/1280)
Only happens if you've clicked "editar", and doesn't happen in the English version of the form

**To Reproduce**

1. Select "Español"
2. Fill out form through "review" page
3. Click "-" to close "Díganos lo que sucedió" accordion
4. Click "+" open it up—it should work like normal
5. Click "editar" button
6. Repeat step 3
7. Repeat step 4

**Current behavior**
Accordion doesn't open

**Expected behavior**
Expect accordion to open back up

**URL tested:** https://forms.austintexas.io/fiscalizacion-de-policia/queja/revisar-y-enviar

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=71.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Ffiscalizacion-de-policia%2Fqueja%2Frevisar-y-enviar&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/fiscalizacion-de-policia/queja/revisar-y-enviar) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 71.0 |
| Operating System | OS X Mojave |
| Resolution | 1548x946 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/55151b17dd7fd12e3c73986eb8b2f68deb6b2419/macmo_chrome_71.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/55151b17dd7fd12e3c73986eb8b2f68deb6b2419/macmo_chrome_71.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=71.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Ffiscalizacion-de-policia%2Fqueja%2Frevisar-y-enviar&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/fiscalizacion-de-policia/queja/revisar-y-enviar) to reproduce the issue on Browserstack**

**Comment by sergiogcx** [comment]
Ah, darn it. it looks like a translation is breaking stuff in the code:

@desigonz do you have any PRs you might be merging in soon to translations.json?

Missing '%' characters in translation:

<img width="318" alt="screen shot 2019-02-22 at 2 30 55 pm" src="https://user-images.githubusercontent.com/5282430/53269443-7d8b4780-36ae-11e9-8bfe-85928a1e3dd3.png">

Line Link:
https://github.com/cityofaustin/officer-complaint-form/blob/45b3a03d67fae724a9465efc3021ef54293c3cb1/locale/translations.json#L360

**Comment by easherma** [comment]
appears to be fixed by https://github.com/cityofaustin/officer-complaint-form/commit/f159d4bd84cb81d1998cec499a810551de089c27 or something close to it
