### ISSUE TITLE
small updates to translations.json

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1284]
Opening up a new PR for these small translations.json fixes.

- [x] add % to the bug @sergiogcx found in [#1282](https://app.zenhub.com/workspaces/5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/1282)
- [x] change "Su grupo etnico" to "Su raza" per official translations
- [x] update English string for "If you need an interpreter, you can call with a friend to interpret for you or ask for an interpreter. Just tell us the language you prefer."
- [x] update English string for "Office hours are Monday through Friday, 9 am to 5 pm."
- [x] update English string for "If you need an interpreter, you can come with a friend to interpret for you or ask for an interpreter. Just tell us the language you prefer."
- [ ] update English string for "How we store and use your information"
- [x] update English string for "Badge Number"

**Comment by desigonz** [comment]
@sergiogcx Made these updates in [pull request #44](https://github.com/cityofaustin/officer-complaint-form/pull/44)

**Comment by easherma** [comment]
merged

**Comment by amenity** [comment]
@desigonz - would you add a size & estimate to this, please? 🙏 👕 
(Also, is that second to last unchecked task something we should make an issue for?)
