### ISSUE TITLE
Bug: upload widget on "review" page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1285]
Blue box appears in lieu of the progress bar/close button on upload widget in the review screen.

**URL tested:** https://forms.austintexas.io/police-oversight/complaint/review-and-submit

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Edge&browser_version=17.0&zoom_to_fit=true&full_screen=true&resolution=1280x800&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Freview-and-submit&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/review-and-submit) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Edge 17.0 |
| Operating System | Windows 10 |
| Resolution | 1280x800 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/fb619e385aa25cbf37392658ce522414e6dab0fe/win10_edge_17.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/fb619e385aa25cbf37392658ce522414e6dab0fe/win10_edge_17.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Edge&browser_version=17.0&zoom_to_fit=true&full_screen=true&resolution=1280x800&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Freview-and-submit&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/review-and-submit) to reproduce the issue on Browserstack**

**Comment by benguhin** [comment]
@easherma try adding this to remove padding from file upload "X" button

.form-review-panel button:not(.usa-button-unstyled) {
padding: 0;
}

**Comment by sergiogcx** [comment]
As a quick comment, this is the code that fixes the File Upload widget:

```
.filepond--file-action-button.filepond--file-action-button {
  font-size: 1em !important;
  width: 1.625em !important;
  height: 1.625em !important;
  font-family: inherit !important;
  line-height: inherit !important;
  margin: 0 !important;
  padding: 0 !important;
  border: none !important;
  outline: none !important;
  will-change: transform,opacity !important;
}

.filepond--file-action-button {
  cursor: auto !important;
  color: #fff !important;
  border-radius: 50% !important;
  background-color: rgba(0,0,0,.5) !important;
  background-image: none !important;
  box-shadow: 0 0 0 0 hsla(0,0%,100%,0) !important;
  transition: box-shadow .25s ease-in !important;
}
```
