### ISSUE TITLE
Police Oversight form: Blue box around upload icon

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1288]
![screen shot 2019-02-23 at 10 41 18 am](https://user-images.githubusercontent.com/1463708/53289160-04e0c580-3758-11e9-9968-b492d88e45b7.png)

**Comment by easherma** [comment]
This is already an issue

**Comment by easherma** [comment]
https://github.com/cityofaustin/techstack/issues/1285

**Comment by amenity** [comment]
Oops, my bad! Thanks.
