### ISSUE TITLE
Police Oversight form: Browserstack testing round two

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1290]
Mobile:
- [x] iPhone: Safari 12.0
- [ ] Android: Chrome 71.0

Desktop:
- [x] Windows 10: Chrome 71.0
- [x] Windows 7: Chrome 71.0
- [x] MacOS 10.14: Chrome 71.0
- [x] Windows 10: Edge 17.17

**Comment by amenity** [comment]
@LauraTrujillo @oliver2g @wilhitem - It would be great to get someone from the content team to do another round of browser testing next week.

**Comment by LauraTrujillo** [comment]
We could assign it to Jeff- He'd have fresh eyes for it.

**Comment by oliver2g** [comment]
Thanks Annie!
