### ISSUE TITLE
Police Oversight form: Validate email address

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1291]
Right now we are not confirming that the email address is in a valid form. We should do this on both the "About you" page and the confirmation page.  

 ![Screenshot URL](https://live.browserstack.com/issue-tracker/16e4e4660eb3e9b804a9aa2a1b0942176c4eb8b9/win10_ie_11.0.jpg)

**Comment by easherma** [comment]
Form validation would be nice for email, phone, zip, and maybe others.

**Comment by easherma** [comment]
https://github.com/cityofaustin/officer-form-chapters/commit/05b4a38c8c6da9e7dbeba1fe728f0f442a5191c7 should fix!
