### ISSUE TITLE
Bug: linked text actions

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1295]
Problem: 
When you submit your complaint, the links on the "We have received your complaint" page do not do anything.

Steps to recreate:
1. Go to https://forms.austintexas.io/police-oversight/complaint/
2. Walk through form and click submit
3. click on 
* what happens next
* email: policeoversight@austintexas.gov
* 512-972-2676

expected results:
what happens next: links to an information page
email: whatever normally happens
phone number: I have no idea what its supposed to do in desktop browser. 

I tested this on IE 11 and chrome on my mac. 
When i tested on my samsung galaxy using chrome the links interacted correctly. 

**URL tested:** https://forms.austintexas.io/police-oversight/complaint/introduction

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Fintroduction&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/introduction) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1024x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/19bda4eeb04f2f41d49f747e3c00fe0d47038f6b/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/19bda4eeb04f2f41d49f747e3c00fe0d47038f6b/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Fintroduction&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/introduction) to reproduce the issue on Browserstack**

**Comment by wilhitem** [comment]
found out this is a dupe. :O
