### ISSUE TITLE
Expand limit of files uploaded in form to 100

### ISSUE THREAD

**Issue by wilhitem** [cityofaustin/techstack#1297]
Right now, when filing a police complaint the file limit for upload is 10. We want to expand this to 100 as an interaction could take place over a long span of time and we want to make sure we can receive all evidence.

Steps to recreate:
1. go to https://forms.austintexas.io/police-oversight/complaint/introduction
2. go through form to files
3. attempt to upload more than 10 files

Expected results:
allowed to upload 100 files

**Comment by sergiogcx** [comment]
It's implemented, I did test it locally (and yes after 2-3 songs in my playlist I was finished picking files manually):

Note: It says 101, but I am sure I missed one or two along the way. 

![Screen Shot 2019-02-24 at 7.25.25 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/4e7dfa4a-cbc9-480d-a4b7-31d575924911)

This is in the same pr as #1298
https://github.com/cityofaustin/usfs-components/pull/7

**Comment by amenity** [comment]
@sergiogcx - would you add a size & estimate to this, please? 🙏 👕 
_XS --->1, S--->2, M--->3, L--->5, XL --->8_
