### ISSUE TITLE
Limit file upload to 20 GB

### ISSUE THREAD

**Issue by wilhitem** [cityofaustin/techstack#1298]
Problem:
Without some kind of limit on file size in the police complaint form, files uploaded could be abused and end up costing a ton of money. We discussed based on video sizes, etc that we should limit files uploaded to 20GB

**Comment by sergiogcx** [comment]
** READY FOR REVIEW **

This functionality has been implemented in the following PR: https://github.com/cityofaustin/usfs-components/pull/7

`https://github.com/cityofaustin/usfs-components/pull/7`

Here is a screenshot with some testing:

![screen shot 2019-02-24 at 6 23 58 pm](https://user-images.githubusercontent.com/5282430/53307925-a8b69800-3862-11e9-895c-0cec84d46e33.png)

### Testing Procedure

In mac, I generated a large empty file with the following command:

For a file just under 20gb:
```
mkfile -n 18gb ~/Desktop/18gbFileJustUnder20
```

For a file just over 20gb:
```
mkfile -n 20gb ~/Desktop/20gbFileJustOver
```

This is now ready for review and implementation.
