### ISSUE TITLE
Bug: Unable to see address text for location

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1299]
Problem:
On the police complaint form, when I type in an address location, you can't see the text that you have typed in so its hard to know if you mistyped.

Steps to recreate:
1. go to https://forms.austintexas.io/police-oversight/complaint/
2. start online form
3. go to the location section on 'what-happened' page and start typing in a location: "800 Guadalupe"

expected result:
I can see the text i have typed in

actual result:
the text i added is not visible.

Seen in IE11, Mac Chrome, iOS Firefox, iOS Safari

**URL tested:** https://forms.austintexas.io/police-oversight/complaint/what-happened

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Fwhat-happened&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/what-happened) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1024x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/4934157f1840d024c7ee9e148c9cfa195f8cbfaf/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/4934157f1840d024c7ee9e148c9cfa195f8cbfaf/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=1024x768&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Fwhat-happened&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/what-happened) to reproduce the issue on Browserstack**

**Comment by amenity** [comment]
![img_3daa09f93f53-1](https://user-images.githubusercontent.com/1463708/53294963-93842f80-37b6-11e9-8f32-4bde253466d7.jpeg)
On iOS.

**Comment by amenity** [comment]
Also maybe relates to or should be fixed with #1296.

**Comment by easherma** [comment]
https://github.com/cityofaustin/officer-complaint-form/commit/d93ea4839cb984d4daa8dea1948340b0a1e56ba0 should have fixed this
