### ISSUE TITLE
Police Oversight form: Reveal to search engine indices 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1306]

**Comment by sergiogcx** [comment]
A PR has been created:
https://github.com/cityofaustin/officer-complaint-form/pull/82

**Comment by sergiogcx** [comment]
Robots updated, HTTP headers removed.

**Comment by sergiogcx** [comment]
To clarify, this has been done to the complaint form. Also removed from thank you form.

**Comment by oliver2g** [comment]
@sergiogcx how do i test this, so that i can close the issue?
