### ISSUE TITLE
Police Oversight microsite: Translations for hardcoded strings

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1307]
Hardcoded strings: 

### Header
- [x] Gov site header 
> Un sitio oficial _de la_ Ciudad de Austin.   Así es como usted puede verificarlo. 
> 
> Dot gov
> El dominio .gov significa que es oficial. 
> Los sitios del gobierno frecuentemente terminan en dominios .gov. Antes de compartir información confidencial, asegúrese de que está en un sitio del gobierno.
> 
> SSL
> Este sitio es seguro. 
> El protocolo https:// le asegura que se está conectando al sitio web oficial y que cualquier información que usted proporcione está encriptada y será transmitida de forma segura.
- [x] Change "Un sitio oficial del Ciudad de Austin." to "Un sitio oficial de la Ciudad de Austin."
- [x] Remove "o .mil". 
- [x] Menu --> Menú 

### Footer
- [x] For the full City of Austin website, visit -->  Para el sitio web completo de la Ciudad de Austin, visita

### Department Page
- [x] Contact Information --> Información de contacto
- [x] File a complaint against an Austin police officer --> Presente una queja contra un oficial de policía de Austin
- [x] Thank the Austin Police Department --> Agradezca al Departamento de Policía de Austin
- [x] What we do --> Lo que hacemos
- [x] Our mission --> Nuestra misión
- [x] Meet our director --> Conozca a nuestra directora
- [x] Director, Office of Police Oversight --> Directora, Oficina de Fiscalización de la Policía
- [x] City of Austin --> Ciudad de Austin
- [x] Top services --> Servicios principales 

### Contact information sidebar
- [x] Closed --> Cerrado

### Bonus: English hardcoded string updates
- [x] Remove "federal" from "Government websites often end in .gov. Before sharing sensitive information, make sure you’re on a _federal_ government site."
- [x] Change "File a complaint against an Austin Police Officer" to "File a complaint against an Austin police officer" (with "police officer" lower case)
- [x] Change "Thanks Austin Police Department" to "Thank an Austin police officer"

**Comment by briaguya** [comment]
Need a full one for this, we currently have:
File a complaint against an Austin Police Officer -> Presente Una Queja

**Comment by briaguya** [comment]
<img width="471" alt="screen shot 2019-02-25 at 7 02 15 pm" src="https://user-images.githubusercontent.com/6384156/53379613-eaf9db00-392f-11e9-847f-d5bfaf951dc0.png">
how much of this should we translate?

**Comment by briaguya** [comment]
Do we translate anything in
<img width="319" alt="screen shot 2019-02-25 at 7 03 40 pm" src="https://user-images.githubusercontent.com/6384156/53379660-15e42f00-3930-11e9-9167-5b7236342562.png">
 contact info?

**Comment by briaguya** [comment]
this do the trick?
<img width="558" alt="screen shot 2019-02-25 at 7 26 37 pm" src="https://user-images.githubusercontent.com/6384156/53380558-6610c080-3933-11e9-9aca-26e467f6e192.png">

**Comment by amenity** [comment]
@desigonz @sergio - if you could take a look at my translations that would be great. 

As far as the contact information sidebar, @briaguya I think those days of the week and the header "Información de contacto" are enough.

**Comment by sergiogcx** [comment]
I read through them, they look very good to me! 100/100

Probably best to wait for @desigonz 's opinion too.

**Comment by desigonz** [comment]
Un sitio oficial *de la* Ciudad de Austin. (ciudad is feminine)

We took out the bit about .mil for our website, so the first sentence of .gov should be:
*Los sitios del gobierno frecuentemente terminan en el dominio .gov.*

I believe "Conoce a nuestra directora" should be *Conozca*, since we're using usted and not tú ([conjugations here](http://www.wordreference.com/conj/ESverbs.aspx?v=conocer))

re: @briaguya's question about translating in the contact info, we need to translate "Closed" as "Cerrado"

**Comment by amenity** [comment]
Thanks, y'all!

**Comment by amenity** [comment]
@briaguya - ready to go!
