### ISSUE TITLE
Bug: double "example" on witness page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1309]
**Describe the bug**
Need to delete an "example" from "Examples: Examples: were they injured, were they harassed, how were they involved, etc."

Not sure why this is happening...I had fixed this one a few days ago:
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/70cfe31c-ba19-412a-a245-3e99f1dab4f4)

@easherma, any thoughts?

**URL**
https://forms.austintexas.io/police-oversight/complaint/witness-details

**To Reproduce**

1. Go to https://forms.austintexas.io/police-oversight/complaint/witness-details
2. Scroll down to 'Is there anything we should know about this witness?'

**Comment by easherma** [comment]
I don't see this recurring.
