### ISSUE TITLE
Return of the on-focus map location bug 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1321]
**Describe the bug**
Same as https://github.com/cityofaustin/techstack/issues/1093, which we fixed way back when by upping the font size. 😞 

**URL**
https://forms.austintexas.io/police-oversight/complaint/what-happened

**To Reproduce**

1. Go to the "What Happened" page
2. Click on location text field 

**Current behavior**
The page zooms in slightly. This crops the text. Exiting the field input doesn't zoom back out. 

**Expected behavior**
🙅‍♂️ zoom!

**Screenshots**
![img_14976e23152c-1](https://user-images.githubusercontent.com/1463708/53443774-0c130800-39d2-11e9-8e72-5b580a54b02d.jpeg)

**Device**
iPhone 6

**Browser**
Safari, Firefox

**Comment by easherma** [comment]
fixed https://github.com/cityofaustin/officer-complaint-form/commit/cb3fdcac83f70cb4f4a9cca088a4bc340c12ba1a
