### ISSUE TITLE
Medium post: How Style Communicates Substance

### ISSUE THREAD

**Issue by JeffCopy** [cityofaustin/techstack#1322]

**Comment by JeffCopy** [comment]
@LauraTrujillo 
My draft for the blog article we discussed:
https://docs.google.com/document/d/1mYG9sFQ3P-TwomB1-yN2IleReCGnkbAeiHmUjs70YW4/edit?usp=sharing

**Comment by JeffCopy** [comment]
@LauraTrujillo 
New draft, with much of the same language but largely rethought based on yesterday's discussion.

**Comment by JeffCopy** [comment]
@LauraTrujillo minor tweaks implementicized, ready for your eyes.

**Comment by LauraTrujillo** [comment]
@JeffCopy reviewed! Suggested some headings to increase "scanability." I suggest having Sara P. review it again just to make sure all is well w/ OPO content. Great job!

**Comment by JeffCopy** [comment]
Thanks much, and I will send on for Sara P to give it a read.
