### ISSUE TITLE
Police Oversight microsite: Browserstack testing

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1323]
Devices & browsers to test based on [Austintexas.gov analytics](https://github.com/cityofaustin/techstack/issues/1240).

Mobile:
- [x] iPhone: Safari 12.0
- [x] Android: Chrome 71.0

Desktop:
- [x] Windows 10: Chrome 71.0
- [x] Windows 7: Chrome 71.0
- [x] MacOS 10.14: Chrome 71.0
- [x] Windows 10: Edge 17.17

Pages:
- http://alpha.austin.gov/police-oversight
- https://alpha.austin.gov/police-oversight/complaint-investigation-process
- http://alpha.austin.gov/en/police-oversight/how-we-store-and-use-your-data

**Comment by desigonz** [comment]
@amenity Completed Browserstack testing—closing this issue!

**Comment by amenity** [comment]
![awesome](https://media.giphy.com/media/vCKC987OpQAco/giphy.gif)
