### ISSUE TITLE
First heading is not an H1

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1327]
**Describe the bug**
First heading of the page is an h2, not the h1 title.
`<h2><a href="https://alpha.austin.gov/police-oversight">Office of Police Oversight</a></h2>`

**URL**
https://alpha.austin.gov/police-oversight and https://alpha.austin.gov/es/police-oversight
https://alpha.austin.gov/es/police-oversight/complaint-investigation-process
http://alpha.austin.gov/en/police-oversight/how-we-store-and-use-your-data

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/06e79b7a-1d00-4534-afb9-a37f2f5e8932)

**Comment by amenity** [comment]
Page title is an H1, which is what we want. ✔️
