### ISSUE TITLE
Make time dumber (Override/turn off time zone translations)

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1331]
Hours appearing incorrectly in Browserstack — must be because they change hours to be in a user's time zone. Can we turn this off? If someone in NYC looks at the OPO page, they should be able to see the correct hours. 

**URL tested:** https://alpha.austin.gov/police-oversight

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=10.0&device=iPhone+7&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Falpha.austin.gov%2Fpolice-oversight&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://alpha.austin.gov/police-oversight) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 7 |
| Browser | Mobile_safari |
| Operating System | iOS 10.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.64 x 5.44 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/cb7aa4731a847a0e359853aa6d3b4eaabe512c7d/realios_iPhone_7.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/cb7aa4731a847a0e359853aa6d3b4eaabe512c7d/realios_iPhone_7.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=10.0&device=iPhone+7&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Falpha.austin.gov%2Fpolice-oversight&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://alpha.austin.gov/police-oversight) to reproduce the issue on Browserstack** 
\

**Comment by easherma** [comment]
I think this is mainly because we're using FormattedTime from react-intl

https://github.com/cityofaustin/janis/blob/master/src/components/Contact/Hours.js

More info on the react-intl side here:

https://github.com/yahoo/react-intl/issues/1135

At first glance the simplest solution seems like it may just be to stop using FormattedTime, since it isn't really needed for translation.
