### ISSUE TITLE
OPO microsite content edits to make it Joplin

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1333]
Please check against Spanish as well, especially for sentences and line breaks

![alpha-opo-1.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/be5729e7-d44e-4833-8519-8118c7286b2e)
- [x] remove colon in "Top services" and sentence case (I'm guessing it's hard-coded, so I reported it as a bug in [#1329](https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/1329)
- [x] (512) style for phone number 
- [x] Space needed (or paragraph break?) before "We do this by..."
- [x] Spell out "Rutherford Lane"? We do so on the form, although haven't determined this for our style guide

[alpha-opo-2.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/61bb423b-2a70-4205-a56e-8b78961ea61a)
- [x] replace double hyphens with [em dashes](https://www.chicagomanualofstyle.org/book/ed17/part2/ch06/psec085.html)
- [ ] too many spaces before "Farah studied..." in bio—maybe it was supposed to be a paragraph break?!

![alpha-opo-3.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/013563a0-7583-400c-a52d-f4618d59610c)
- [x] sentence case title ("Complaint investigation process")

![alpha-opo-4.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/e9eb96d5-bbfd-44f3-a381-582ed2c76a34)
- [ ] should "administrative inquiries," "supervisor referrals," "citizen concerns," and "administratively closed" need to be capitalized or lowercase? (I'm inclined to lowercase them)
- [x] space or sentence break before "This category is..."

![alpha-opo-5.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/381c8a0c-ea4d-4f23-9995-e6d340903755)
- [x] space or sentence break before "We will also offer..."

**Comment by amenity** [comment]
Just updated these in Joplin:
- [x] (512) style for phone number - https://joplin.herokuapp.com/admin/snippets/base/contact/2/ and https://joplin.herokuapp.com/admin/pages/27/edit/ 
- [x] Space needed (or paragraph break?) before "We do this by..."
- [x] Spell out "Rutherford Lane"? We do so on the form, although haven't determined this for our style guide - https://joplin.herokuapp.com/admin/snippets/base/location/4/

**Comment by amenity** [comment]
Updated in Joplin:
- [x] replace double hyphens with [em dashes](https://www.chicagomanualofstyle.org/book/ed17/part2/ch06/psec085.html)
- [x] too many spaces before "Farah studied..." in bio—maybe it was supposed to be a paragraph break?! - _looked like there were some extra spaces and an extra paragraph break._

**Comment by amenity** [comment]
Updated in Joplin
- [x] sentence case title ("Complaint investigation process")
- [x] space or sentence break before "This category is..."
- [x] space or sentence break before "We will also offer..."

Not updating. I agree they look weird title case, but will defer to @sarafperalta and @srigdon 
- [ ] should "administrative inquiries," "supervisor referrals," "citizen concerns," and "administratively closed" need to be capitalized or lowercase? (I'm inclined to lowercase them)

**Comment by amenity** [comment]
Not updating these ones. I agree they look weird title case, but will defer to @sarafperalta and @srigdon 
- [ ] should "administrative inquiries," "supervisor referrals," "citizen concerns," and "administratively closed" need to be capitalized or lowercase? (I'm inclined to lowercase them)
