### ISSUE TITLE
Center align director's name and title for mobile

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1334]
Per design mocks, director name & title block should be center aligned in mobile view https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/

**URL tested:** https://alpha.austin.gov/police-oversight

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=10.0&device=iPhone+7&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Falpha.austin.gov%2Fpolice-oversight&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://alpha.austin.gov/police-oversight) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 7 |
| Browser | Mobile_safari |
| Operating System | iOS 10.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.64 x 5.44 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/0999e34223b58d290dc5ef73a400a8d70d386cec/realios_iPhone_7.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/0999e34223b58d290dc5ef73a400a8d70d386cec/realios_iPhone_7.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=10.0&device=iPhone+7&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Falpha.austin.gov%2Fpolice-oversight&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://alpha.austin.gov/police-oversight) to reproduce the issue on Browserstack**

**Comment by pibemillo** [comment]
https://github.com/cityofaustin/janis/pull/344
https://janis-staging-pr-344.herokuapp.com/police-oversight
