### ISSUE TITLE
Redo forms.austin.gov redirect

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1336]
Gah, sorry @sergiogcx - I messed up my request in #1193. 😬 

I meant redirect forms.austin.gov to **Alpha**.austin.gov. Austin.gov directs to Austintexas.gov, so now Forms.austin.gov is effectively redirecting to Austintexas.gov. 

This can wait if it's a lot of work.

**Comment by sergiogcx** [comment]
No problem at all, a 2 min fix underway!

**Comment by sergiogcx** [comment]
This should be working now, could you test? and close if good to go

**Comment by amenity** [comment]
It is working, but it's going to http:// not https://.

**Comment by sergiogcx** [comment]
ah, let me change that
