### ISSUE TITLE
Develop topic pages content

### ISSUE THREAD

**Issue by courtneyjacinic** [cityofaustin/techstack#134]
Tuesday, 3/6, 1.5 hours

**Comment by LauraTrujillo** [comment]
https://docs.google.com/document/d/1pUXDJPkAT-qRy66AeIAHt90LRGH6onE-Iie0B-fmpeY/edit?ts=5a9efc80#

**Comment by LauraTrujillo** [comment]
Reopening so we can refine content

**Comment by LauraTrujillo** [comment]
Need review from:

- [ ] @courtneyjacinic 
- [ ] @cthibaultatx 
- [ ] @toribr

**Comment by ashleecoa** [comment]
@courtneyjacinic replied
