### ISSUE TITLE
OPO form and microsite: complete content review for media push

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1342]
It is too late to make major content changes, like #1340, for the MVP release. 

Before the media release, we need to fully review all content in the form, microsite, and confirmation emails for accuracy and consistency. 

Let's talk about the best way to document them before we get started.

**Comment by LauraTrujillo** [comment]
## File a complaint
*In person*
- [ ] Remove "You will need to check in with building security at the front desk."

**Comment by LauraTrujillo** [comment]
## File a complaint- form
*Tell us what happened*
- [ ] Remove ", if known?"
- [ ] Add a period after date and time
- [ ] Add helper text under Date and time: Getting as close to the date and time as you can helps us with our investigation.

**Comment by LauraTrujillo** [comment]
## File a complaint- form
*Share your photos or videos*
- [ ] Link to "How we use your info" - nothing happens when I click on it
- [ ] Add a period at the end of etc. :"Upload any evidence that you have (video files, audio files, photos, police report, hospital record, etc)"

**Comment by LauraTrujillo** [comment]
## File a complaint- form
*Tell us about the officer(s)*
- What was the officer wearing
- [ ] Remove "in" "In uniform"
- [ ] Capitalize "uniform
- [ ] Capitalize "Regular"

**Comment by LauraTrujillo** [comment]
## File a complaint- form
*Tell us about you*
- Contact preferences
- [ ] Use numerals for two to four: 2 to 4

**Comment by LauraTrujillo** [comment]
## File a complaint- form
*We have received your complaint*
- [ ] Your case number should read "Your confirmation number"
- [ ] Add parentheticals to phone number per our style: (512)...
- [ ] Use numerals (aka digits) for two to four: 2 to 4
- [ ] Update confirmation paragraph to read: 
- You can email us at policeoversight@austintexas.gov or call us at (512) 972-2676 with your confirmation number to find where your complaint is in this process.

If you provided your contact information, a staff person from the Office of Police Oversight will contact you within 2 to 4 business days, and you will receive an email with a copy of your complaint and a confirmation number.

**Comment by LauraTrujillo** [comment]
## Thank an Austin police officer
*Online*
- Required information
- [ ] Move "Time" to Optional info
- [ ] Time should be Date and time
*In person*
- [ ] Remove "You will need to check in with building security at the front desk."

**Comment by LauraTrujillo** [comment]
## Thanks- form
*Tell us what happened*
- [ ] Remove ", if known?"
- [ ] Add a period after date and time
- [ ] Add helper text under Date and time: Getting as close to the date and time as you can helps us thank the right officer(s).

**Comment by LauraTrujillo** [comment]
## Thanks- form
*Tell us about the officer(s)*
- What was the officer wearing
- [ ] Remove "in" "In uniform"
- [ ] Capitalize "uniform
- [ ] Capitalize "Regular"

**Comment by LauraTrujillo** [comment]
## Thanks- form
*Tell us about you*
- Contact preferences
- [ ] Use numerals (aka digits) for two to four: 2 to 4
- Your email address
- [ ] Should read "Required if you want the confirmation number sent to your email."

**Comment by LauraTrujillo** [comment]
## Thanks- form
*We're glad to hear...*
- [ ] Remove "You’ll also receive an email with a copy of your thank-you note."

If you provided your contact information, a staff person from the Office of Police Oversight will contact you within 2 to 4 business days, and you will receive an email with a copy of your complaint and a confirmation number.

**Comment by LauraTrujillo** [comment]
## Confirmation email- Complaint
- [ ] Add parentheticals to phone number per our style: (512)...
- [ ] Use numerals (aka digits) for two to four: 2 to 4
- [ ] "Complaint investigative process" should be in sentence case

**Comment by LauraTrujillo** [comment]
## Complaint investigation process
- [ ] Expand acronym: Learn about the Office of Police Oversight's complaint investigation process.
- Timeframe
- [ ] User numerals (aka digits) "Investigations could take up to 6 months to complete and may require 1 to 4 hours of your time over the course of those months."
- [ ] Revise next sentence to read: Our office will contact you with a monthly update.
- [ ] Expand acronyms in each step of complaint process:
- - [ ] 1. The Office of Police Oversight ...
- [ ] A complaint specialist in the Office of Police Oversight reviews your complaint, including any available video, audio, or other evidence. Then we send the information to Internal Affairs.

**Comment by LauraTrujillo** [comment]
## How we store and use your data
- [ ] Remove "department" in the first line, to read: "When you file a complaint against an Austin Police officer..."

**Comment by LauraTrujillo** [comment]
## File a complaint- PDF/printed form
- Office hours
- [ ] Space between Monday and 8
- [ ] Make am and pm lowercase
- [ ] Move Sunday's "closed" over to align with Saturday
- Phone number
- [ ] Use complaint number? If so, change to (512) 972-2676
- Physical Address
- [ ] Add suite: 1520 Rutherford Ln., Suite 211
- Required information
- [ ] Change "time" to Date and time
- *Tell us what happened*
- [ ] Remove ", if known?"
- [ ] Add a period after date and time
- [ ] Add helper text under Date and time: Getting as close to the date and time as you can helps us with our investigation.
- *Contact preferences*
- [ ] Use numerals (aka digits) for two to four: ... 2 to 4 business days.
- Your email address
- [ ] Should read "Required if you want the confirmation number sent to your email."

**Comment by LauraTrujillo** [comment]
## File a complaint- PDF/printed form
*(https://forms.austin.gov/files/OPO_complaint-form_print_English.pdf)*
- Office hours
- [ ] Add space between Monday and 8 AM
- [ ] Make AM and PM lowercase
- [ ] Move Sunday's Closed over to align with Saturday's
- Phone number
- [ ] If we want to use the complaint phone number, change to: (512) 972-2676
- Physical address:
- [ ] Add suite: 1520 Rutherford Ln., Suite 211
- Required information
- [ ] Change Time to "Date and time"
- Tell us what happened
- [ ] Add a period after date and time
- [ ] Add helper text under Date and time: Getting as close to the date and time as you can helps us with our investigation.
- Contact preferences
- [ ] Use numerals (aka digits) for two to four: 2 to 4
- Your email address
- [ ] Should read "Required if you want the confirmation number sent to your email."

**Comment by LauraTrujillo** [comment]
Thank you @easherma and @sergiogcx for helping me figure this out!!! 🙏
