### ISSUE TITLE
Change color for visited link to blue

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1343]
**URL tested:** https://alpha.austin.gov/police-oversight

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Falpha.austin.gov%2Fpolice-oversight&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://alpha.austin.gov/police-oversight) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Samsung Galaxy S9 Plus |
| Browser | Mobile_chrome |
| Operating System | Android 8.0 |
| Resolution | 1440 x 2960 px |
| Screen size | 6.2 in - 6.2 x 2.9 in |
| Viewport | 360 x 740 dp |
| Aspect Ratio | 18.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/41f8fa287439ff8b8217569cde8e7b5f0eddad93/realdroid_Samsung_Galaxy_S9_Plus.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/41f8fa287439ff8b8217569cde8e7b5f0eddad93/realdroid_Samsung_Galaxy_S9_Plus.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Falpha.austin.gov%2Fpolice-oversight&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://alpha.austin.gov/police-oversight) to reproduce the issue on Browserstack**

**Comment by amenity** [comment]
@chasechenevert @toribr - what do you want to spec for this?

**Comment by amenity** [comment]
@chasechenevert what would you like here?

**Comment by annieszot** [comment]
@chasechenevert ?

**Comment by annieszot** [comment]
![Screen Shot 2019-03-23 at 12 48 30 PM](https://user-images.githubusercontent.com/46934140/54869665-ffcc6180-4d69-11e9-8b7a-9aebc6fe1969.png)
- Visited link is purple

**Comment by oliver2g** [comment]
@chasechenevert can you verify this looks right?
@easherma can you put an estimate on this issue?

**Comment by chasechenevert** [comment]
Late seeing this, my bad. Purple is the default in the USWDS and I don't have any strong opinion to change it at the moment.
