### ISSUE TITLE
External link icon breaks to new line

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1344]
Minor design thing: Maybe not actually something we need to fix, but on this device size, the project site external link icon breaks onto a new line, thus separating from "project site."

**URL tested:** https://projects.austintexas.io/projects/austin-digital-services-discovery/about/what-we-are-doing/

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fprojects.austintexas.io%2Fprojects%2Faustin-digital-services-discovery%2Fabout%2Fwhat-we-are-doing%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://projects.austintexas.io/projects/austin-digital-services-discovery/about/what-we-are-doing/) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Samsung Galaxy S9 Plus |
| Browser | Mobile_chrome |
| Operating System | Android 8.0 |
| Resolution | 1440 x 2960 px |
| Screen size | 6.2 in - 6.2 x 2.9 in |
| Viewport | 360 x 740 dp |
| Aspect Ratio | 18.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/0f13462ec078d4a19d59d91c131e750e499d958a/realdroid_Samsung_Galaxy_S9_Plus.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/0f13462ec078d4a19d59d91c131e750e499d958a/realdroid_Samsung_Galaxy_S9_Plus.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fprojects.austintexas.io%2Fprojects%2Faustin-digital-services-discovery%2Fabout%2Fwhat-we-are-doing%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://projects.austintexas.io/projects/austin-digital-services-discovery/about/what-we-are-doing/) to reproduce the issue on Browserstack**

**Comment by annieszot** [comment]
Bug fixed on Samsung Galaxy S9 and all preferred IOS and Android platforms (Phone: Safari 12.0; Android: Chrome 71.0)
![Screen Shot 2019-03-24 at 1 20 38 PM](https://user-images.githubusercontent.com/46934140/54883845-25c03780-4e38-11e9-8cd3-56e61331efe4.png)
![Screen Shot 2019-03-24 at 1 21 13 PM](https://user-images.githubusercontent.com/46934140/54883846-2658ce00-4e38-11e9-8b16-fa8b7881bfc9.png)
![Screen Shot 2019-03-24 at 1 23 00 PM](https://user-images.githubusercontent.com/46934140/54883847-2658ce00-4e38-11e9-8494-b450f32e9a57.png)
Closing
