### ISSUE TITLE
Breakpoint specifications for righthand column on Department Page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1346]
At narrower browser sizes (across browsers and platforms), the right rail on the Department Page gets cut off: 
 ![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/6980a727-f47e-4778-ae05-b77ca7b800af)

**URL tested:** https://alpha.austin.gov/police-oversight

We need to write specifications so the developers can implement a fix.

**Comment by pibemillo** [comment]
I believe this issue was addressed by @Niicck when fixing contact hours table. If so, I think we can close this one.

**Comment by Niicck** [comment]
Yep. This got cleaned up by https://github.com/cityofaustin/techstack/issues/1461
