### ISSUE TITLE
Develop "You're now leaving austintexas.gov" message content

### ISSUE THREAD

**Issue by courtneyjacinic** [cityofaustin/techstack#135]
Tuesday, 3/6, 1 hour
- [x] Develop content
- [x] Determine how and where this will live on atx.gov

**Comment by LauraTrujillo** [comment]
https://docs.google.com/document/d/1Av45ZlZ8uJlCXLRCsfLeGVNh6YdV47bHaP1gtbRyfFA/edit

**Comment by LauraTrujillo** [comment]
Need review from:
- [ ] @ashleecoa 
- [ ] @courtneyjacinic 
- [ ] @cthibaultatx 
- [ ] @toribr

**Comment by courtneyjacinic** [comment]
How and where this will live on atx.gov: 
This message will pop up when a user clicks a banner (banner has yet to be complete: #83 ) on the service pages that will be linking to austin.gov. 

Message will pop up whenever we link to austin.gov from atx.gov

**Comment by courtneyjacinic** [comment]
@LauraTrujillo @ashleecoa I added another option in there for consideration
