### ISSUE TITLE
Remove extra period from thank you form intro page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1350]
**Describe the bug**
Under "in person" section, there is an extra period after the last sentence.

**URL**
https://forms.austintexas.io/police-thank/introduction

**Screenshots**
![opo-thanks-intro.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/c713bdf4-b02d-4eee-ac41-1d276e020774)

**Comment by amenity** [comment]
Spanish has the same problem: 
<img width="1002" alt="screen shot 2019-03-06 at 5 22 38 pm" src="https://user-images.githubusercontent.com/1463708/53921009-9e4f8780-4034-11e9-8340-5714e156be5a.png">

**Comment by amenity** [comment]
Captured in #1431.
