### ISSUE TITLE
Make disciplinary memo page for OPO

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1353]
Currently: 
http://www.austintexas.gov/department/disciplinary-memos

**Comment by amenity** [comment]
@briaguya - wondering if we can do this w/o #595?

**Comment by chasechenevert** [comment]
Capturing some water cooler discussion @amenity and I had about this so I don't forget it: 
- Tables are _really_ hard to do well on mobile, do we need to have this information structured within a table?
- With 205 disciplinary memos at count, how might we make it easier for users to parse this data? Local search, pagination, filters? 
- Are PDFs necessary for any reason (protocol/mandate, etc.)? 
- What does this look like on the backend?

**Comment by easherma** [comment]
Backend wise, we can probably use the existing links where the PDFs are
stored, at least in the meantime.

Tables can be hard on mobile, but this table only has three columns. But
there is little info besides name, date, and pdf link. Being able to
filter/search/sort by officer or date would be nice.

A really great longer term project would be opening this information up
into more if a dashboard and doing some work with the contents of each
complaint. If our clients/stakeholders are interested in something like
that I’d love to help flesh that out.
