### ISSUE TITLE
Spanish translation on introduction

### ISSUE THREAD

**Issue by wilhitem** [cityofaustin/techstack#1356]
Problem: 
On https://forms.austin.gov/policia-queja/introduccion the 'required information' section has 'what happened' in english![Screen Shot 2019-02-27 at 10.09.36 AM.png](https://images.zenhubusercontent.com/5a971d9c4b5806bc2bc8db22/388545de-b30d-4185-817a-9d8b4e1442d5)

**Comment by desigonz** [comment]
Not sure why this is happening—it's in translations.json [thank you](https://github.com/cityofaustin/officer-thank-form/blob/f7a841e817a86975668632a33e59513477f9b4b7/locale/translations.json#L417) and [complaint](https://github.com/cityofaustin/officer-thank-form/blob/f7a841e817a86975668632a33e59513477f9b4b7/locale/translations.json#L417)
