### ISSUE TITLE
Links on spanish OPO forms should link to spanish info pages on alpha, not English

### ISSUE THREAD

**Issue by wilhitem** [cityofaustin/techstack#1358]
Right now for the introduction and completion pages, the links to 'the investigation process' and 'what happens next' go to the english translations.

Is it possible to link to the spanish pages? Is that a bad idea based on future work and how we plan to handle translated pages?

See screenshots, I hovered over the links and you can see the english url's in the bottom footer showing that it leads to the english versions.
![Screen Shot 2019-02-27 at 10.20.11 AM.png](https://images.zenhubusercontent.com/5a971d9c4b5806bc2bc8db22/eccfb44f-997d-47ea-8bbe-4a7a50cdded6)![Screen Shot 2019-02-27 at 10.23.02 AM.png](https://images.zenhubusercontent.com/5a971d9c4b5806bc2bc8db22/0d411407-57c8-4ebe-a848-d8842652f4aa)

**Comment by amenity** [comment]
Currently, these links go to the English pages. 

- [ ] On https://forms.austintexas.io/policia-queja/compartir-evidencia, "Cómo almacenamos y usamos su información" should link to https://alpha.austin.gov/es/police-oversight/how-we-store-and-use-your-data on 
- [ ] On https://forms.austintexas.io/policia-queja/confirmation, "Qué sucederá ahora" should link to https://alpha.austin.gov/es/police-oversight/complaint-investigation-process/

**Comment by easherma** [comment]
@sergiogcx can you check this/verify that it's addressed?

**Comment by sergiogcx** [comment]
Thanks @easherma, I will get working on this immediately.

**Comment by sergiogcx** [comment]
Oy, addressed in this PR:

https://alpha.austin.gov/es/police-oversight/how-we-store-and-use-your-data

Merged to master.

**Comment by oliver2g** [comment]
Eric's doing QA on this.

Mobile:
- [ ] iPhone: Safari 12.0
- [ ] Android: Chrome 71.0

Desktop:
- [ ] Windows 10: Chrome 71.0
- [ ] Windows 7: Chrome 71.0; 
  - [ ] Internet Explorer 11
- [ ] MacOS 10.14: Chrome 71.0
- [ ] Windows 10: Edge 17.17; 
  - [ ] Internet Explorer 11

**Comment by sergiogcx** [comment]
Ah, my bad about the PR. It was merged and this is the commit that fixed it:

https://github.com/cityofaustin/officer-complaint-form/commit/e54bde4498489dbbb551606f688a1dd9d556cfef#diff-4e91ba43e81e8bd966fb3b26900e1fde

**Comment by easherma** [comment]
Checked IE 11 and its good as well as Chrome on my browser; given that this change is just a link and nothing else I think this is sufficient QA.
