### ISSUE TITLE
Sentence case on OPO form email

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1361]
**Describe the bug**
Our editorial style is to use sentence case for headings, titles, and buttons, which means capitalizing the first word and proper nouns only. Need to update to sentence case throughout the form emails. Very low priority :)

**Screenshots**
![unknown-3](https://user-images.githubusercontent.com/5839508/53509305-28ba4900-3a81-11e9-89f2-9624d1ed825e.jpeg)

**Comment by easherma** [comment]
@sergiogcx i think this may be done already? and/or is related to another issue we had in QA

**Comment by sergiogcx** [comment]
This is done, closing.
