### ISSUE TITLE
Special characters not rendering in form emails

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1362]
**Describe the bug**
Accents and tildes aren't rendering in Spanish OPO form emails.

![unknown-4](https://user-images.githubusercontent.com/5839508/53509835-450ab580-3a82-11e9-99e8-768d02798208.jpeg)
Should be: "Díganos", "Descripción", "Número", etc

**Comment by sergiogcx** [comment]
A PR has been created, feel free to review @desigonz  (or change)

https://github.com/cityofaustin/form-service-api/pull/10

**Comment by desigonz** [comment]
I tested from https://forms.austin.gov/policia-agradezca, not sure if the URL I test from matters at this point...

I'm seeing special characters appear in some of the content but not others—see screenshot below!

<img width="912" alt="opo-form-confirmation-email" src="https://user-images.githubusercontent.com/5839508/53751672-6f89b380-3e72-11e9-8f5d-d45e257d43b3.png">

**Comment by amenity** [comment]
I am seeing all the special characters coming through now.
