### ISSUE TITLE
Hours editorial style

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1366]
**Describe the bug**
Our editorial style is to not use ":00" in dates and lowercase am and pm (so should read 8 am – 5 pm). Low priority. Apologies if I've already reported this one.

**Screenshots**
![image](https://user-images.githubusercontent.com/5839508/53514090-843e0400-3a8c-11e9-9f79-8cef3d9a03b5.png)

**Comment by annieszot** [comment]
@Niicck Requires browser testing referenced in #340 before closing?
