### ISSUE TITLE
Solidify user-testing process sync with dev

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#1377]
Stubbing this out for later discussion and there may be related issues already, but we ought to have a agreed on process/workflow/chain of communication before conducting user tests. 

Perhaps something like an issue created for the test, then tagging the dev team as well to verify the URLs used for the test and what builds they correspond to.

**Comment by easherma** [comment]
@toribr wants to bring this up for next sprint review

**Comment by toribr** [comment]
Also - this needs to happen well ahead of testing, so that the test scripts can reflect what will actually be available for testing. :)

**Comment by oliver2g** [comment]
adding @kriskristin

**Comment by kriskristin** [comment]
@toribr @easherma When should we work on this? Should we wait until we begin the next round of usability testing? Or would it be best to tackle it sooner?

I want to understand what the dev needs are when we run user tests. Let's document requirements. 

- URLs being tested
- Build being tested
- Dates of testing

I had a convo with @sergiogcx about developing/standardizing a release chain. I think this will help out dev/testing/QA. 

Check this out: https://wiki.mozilla.org/Release_Management/Release_Process

**Comment by desigonz** [comment]
Gonna close this, we can reopen a new issues with specifics if necessary.
