### ISSUE TITLE
Police Oversight complaint form: confirmation page enhancements

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1378]
Two separate confirmation pages, depending on whether or not the user has submitted an email address already. 

### If the user has not submitted an email address 
<img width="1261" alt="confirmation" src="https://user-images.githubusercontent.com/1463708/54054525-04144e80-41b0-11e9-8902-6dd86501c483.png">

 - Text can be copied from the XD Spec: [Screen 1](https://xd.adobe.com/spec/bf7944c2-69b2-444f-6f10-e3e27f0f47a3-c948/screen/cae43686-7f53-4dc1-a27a-316624d65347/Complaint-8-Success-1/) | [Screen 2](https://xd.adobe.com/spec/bf7944c2-69b2-444f-6f10-e3e27f0f47a3-c948/screen/7e6d3e3e-0982-4654-88c3-8bb8dcfb989c/Complaint-8-Success-1-2/) | [Screen 3](https://xd.adobe.com/spec/bf7944c2-69b2-444f-6f10-e3e27f0f47a3-c948/screen/a98316cb-1cff-481b-85ca-54a5d4e4a6db/Complaint-8-Success-1-3/)  _Note that the phone number format in the spec is incorrect, should be (512) 972-2676._
 - For the loading indication (if there is going to be a perceptible lag when user presses the "submit" button), @chasechenevert likes [this CSS indicator](https://codepen.io/chrisnager/pen/yfwgE). The circle is 6px by 6px. If there is an easier way to have a loading indicator or you need an icon, ping Chase to discuss. 
 - We can do error state for email validation later when we do it on the other field, see #1291 
 - For success state (user's email address is validated and submitted):
    - Background-color: #0CA900;
    - Icon from Google's Material DS in : "Check" https://material.io/tools/icons/? search=check&icon=check&style=baseline
    - Position: centered
<img width="84" alt="screen shot 2019-03-06 at 2 40 00 pm" src="https://user-images.githubusercontent.com/7027270/53912088-c2539e80-401d-11e9-9c5a-ce303a18e00e.png">

### If the user already submitted an email address
<img width="277" alt="Screen Shot 2019-03-08 at 3 25 03 PM" src="https://user-images.githubusercontent.com/1463708/54056690-72f4a600-41b6-11e9-813f-6382b377e0d9.png">

Same, but instead of the form field, have the text "You will receive an email with a copy of your complaint and confirmation number at [email address]." with the email address `<strong>`.

### Issues addressed
 - The current text is misleading since it assumes the user submitted an email address. #1340 
 - The phone number should be in the format (512) 972-2676 (see #1375)
 - A recommendation from[ user testing](https://docs.google.com/document/d/1-6Wmb5JkGF16HkEzb-lN-r7SxHB9teoCwmviJwCgMYk/edit?ts=5c798b95): Having an email field display on this page if the user has not submitted an email address would likely result in more submissions, as this is the most obvious spot as to the benefit of an email record.
- "Case number" needs to change to "confirmation number" #1341 
- Order of text blocks on page needs to change #1340

**Comment by amenity** [comment]
@chasechenevert @toribr @LauraTrujillo @desigonz 
Can I get your eyes on this content and design? I just edited in the HTML directly and copy-🍝ed the email field from earlier in the form. Lmk what you'd like changed and I'll update the mocks in the issue before passing it over to Sergio.

**Comment by desigonz** [comment]
Content thoughts:

- Phone number should be styled (512) 972-2676 (see [#1375](https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/1375))
- In the second mock, need a period at the end of the second paragraph (starting "If you provided your phone number...")
- In that same paragraph, instead of "a person at the Office," maybe "someone at the Office"??

**Comment by toribr** [comment]
The copy is different - one says "person" at the Office and one says "staff person". Which is correct?

**Comment by LauraTrujillo** [comment]
> The copy is different - one says "person" at the Office and one says "staff person". Which is correct?

It should be "staff person."

**Comment by sergiogcx** [comment]
A PR has been created (originally based from issue #1388):
https://github.com/cityofaustin/officer-complaint-form/pull/62/files

** Note: It's still a WIP, but the functionality is now there:

![UfL5KV9rRk.gif](http://g.recordit.co/UfL5KV9rRk.gif)

To do:
- Fine tune styles (button, font sizes, checkmark size, etc).
- Incorporate content & content changes
- Change translations and incorporate new translations.

**Comment by sergiogcx** [comment]
Full size screenshot:

![Screen Shot 2019-03-10 at 4.52.27 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/f99ba28c-6109-48f8-9c09-22a5b2cc965c)

**Comment by sergiogcx** [comment]
Updates:

![Screen Shot 2019-03-11 at 11.15.17 AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/c256b280-250b-4b7b-9e60-d188eeac8780)

![Screen Shot 2019-03-11 at 11.13.52 AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/10160b0f-0d8c-49a9-9981-4f8e1bea7ef4)

**Comment by desigonz** [comment]
content thing—no period at the end of the heading "We have received your complaint"
