### ISSUE TITLE
Police Oversight form: Close intro page accordions by default on complaint form

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1382]

**Comment by easherma** [comment]
I’ve wondered about this. Do we think it’l be a discoverability problem to
have the online form ‘hidden’ by default? It wont be immediately obvious
how to get to the form...

**Comment by toribr** [comment]
If I anticipated it being a problem, I wouldn't recommend it. I think it may actually enhance discoverability in that the "start" button sometimes fell below the fold. When the user clicks the option, then the movement asserts itself as a content bit and encourages scrolling, where otherwise the button may not be seen.

In the end, it's a guess, and HotJar is our friend.

**Comment by easherma** [comment]
https://github.com/cityofaustin/officer-complaint-form/tree/1382-close-intro-accordians

**Comment by easherma** [comment]
live on staging: https://forms.austintexas.io/police-complain/introduction
