### ISSUE TITLE
Correct <title> attributes in OPO form

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1383]
Noticing that the browser bar title (aka `<title>`) style is inconsistent on the complaint and thanks forms. Also, we're not translating into Spanish currently.

- @amenity  /devs, is it technically feasible to translate?  
- @LauraTrujillo @srigdon Are there best practices for this field when it comes to translation? Also, my hunch is to match the browser bar title to the H1—thoughts? (So "File a complaint" instead of "Officer Complaint Form")

![2.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/7674db3b-8841-46ec-ba27-868f6feaec6e)
![1.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/a2c79ada-8d5d-4422-b917-25a5080bff03)
![4.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/452e5263-9c0b-4da8-b796-8dbf948bcb04)
![3.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/96c06f17-fd4e-497f-bc94-c347a5c75fe1)

**Comment by easherma** [comment]
Good catch! We should be able to translate that.

**Comment by easherma** [comment]
@amenity et al, can we confirm with the powers that be what @desigonz asked:
>my hunch is to match the browser bar title to the H1—thoughts? (So "File a complaint" instead of "Officer Complaint Form")

**Comment by amenity** [comment]
Yup @easherma, @desigonz ! 
So:
Presente una queja
Agradezca a un oficial de policía de Austin

**Comment by easherma** [comment]
@amenity but just to clarify, the title in the browser tab will read 'File a complaint' and not 'Officer Complaint Form'?

**Comment by amenity** [comment]
@easherma - yes!

**Comment by easherma** [comment]
changed at https://github.com/cityofaustin/officer-complaint-form/pull/63 & https://github.com/cityofaustin/officer-thank-form/pull/13

@desigonz may be best just to check in w/you in the next couple days to make sure the translations get updated correctly

**Comment by amenity** [comment]
👌
