### ISSUE TITLE
Police Oversight form: Design new confirmation page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1388]
Design new confirmation pages for the thanks and complaint forms, see #1378.

**Comment by toribr** [comment]
Do we really need to send an email for a thank you?

**Comment by toribr** [comment]
@chasechenevert and I reviewed below, he'll be working from this.
![confirmation](https://user-images.githubusercontent.com/3790067/53824551-cc9c6c80-3f39-11e9-8b54-9d552d166ab5.png)

**Comment by chasechenevert** [comment]
### Loading indication
Not sure if this is out-of-scope, but I like this simple CSS loading indicator: 
- https://codepen.io/chrisnager/pen/yfwgE

### Error state for email validation
- Are we able to pull in USWDS error state for this field if the user attempts to submit an inauthentic email address? If so, that's what I'd go with. In terms of the error text I'm not sure if Content would need to vet that.

**Comment by chasechenevert** [comment]
## Add
- Desktop variation. Mostly I just don't want the "Submit" button to extend too long, but I'll create a mock so I can deliver specific sizing

**Comment by amenity** [comment]
@chasechenevert - per #1378 and #1375, the

**Comment by amenity** [comment]
@chasechenevert great! No need to redo the mocks, but note per #1378 and #1375, the phone number should be in the format (512) 972-2676. ☎️

**Comment by amenity** [comment]
@chasechenevert Will you also include a mock of the confirmation page as you would like it to look if the user has already submitted their email address? @toribr recommended including the email they supplied in the confirmation message, e.g. "You will receive an email with a copy of your complaint and confirmation number at [email address]."

**Comment by toribr** [comment]
@amenity You think they need something more precise than my version above?

**Comment by amenity** [comment]
Oh no! I skipped straight to Chase's. Thanks, @toribr
