### ISSUE TITLE
OPO form and microsite QA 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1390]
First focus on these:
- [x] Nick's new date/time picker
- [x] The new map-only page
- [x] That surly review page
- [x] The new email submission sitch on the confirmation page

Mobile:
- [x] iPhone: Safari 12.0
- [x] Android: Chrome 71.0

Desktop:
- [x] Windows 10: Chrome 71.0
- [x] Windows 7: Chrome 71.0
- [x] MacOS 10.14: Chrome 71.0
- [x] Windows 10: Edge 17.17

also see QA issues:
#1290 #1244 (Both closed 3/26/19)

**Comment by Niicck** [comment]
Additional things to look for in the datepicker:

- [ ] WCAG Compatiable https://github.com/cityofaustin/techstack/issues/1446
  - I took this to mean tabable input fields. I'm not sure what else goes into WCAG Compatibility
- [ ] Add Calendar Icon https://github.com/cityofaustin/techstack/issues/1057
- [ ] Date/Time should not be grayed out https://github.com/cityofaustin/techstack/issues/1259

**Comment by desigonz** [comment]
I began to do QA in Chrome 72 on MacOS 10.14 and submitted issues for them. I did the whole complaint form in English + Spanish with a particular focus on the new date/time fields, map-only page, surly review page, and email submission on confirmation page.

**Comment by desigonz** [comment]
@oliver2g, do you need me to work on more OPO QA, or is this one taken care of?

**Comment by oliver2g** [comment]
I believe so, but I'm going to also ask @Niicck and @annieszot to glance at the checklists in this issue before closing. They did the lions share of QA earlier this week.

**Comment by desigonz** [comment]
@oliver2g @Niicck @annieszot Great, happy to pitch in for any last-minute QA. I also noticed a few things yesterday/this morning and added new issues.

**Comment by annieszot** [comment]
@oliver2g, @desigonz pointed out a sweet feature "Report on Github" in browser stack. Yay, automation! Instead of taking note of each bug, taking manual screenshots and creating a new issue, check this out: 
![Screen Shot 2019-03-27 at 12 16 22 PM](https://user-images.githubusercontent.com/46934140/55097710-657e5d80-508a-11e9-9e2d-bf35ad47b9c5.png)
![Screen Shot 2019-03-27 at 12 16 50 PM](https://user-images.githubusercontent.com/46934140/55097711-657e5d80-508a-11e9-801d-20d7fcaaa1b0.png)
![Screen Shot 2019-03-27 at 12 16 56 PM](https://user-images.githubusercontent.com/46934140/55097712-657e5d80-508a-11e9-8d10-43beffa254c3.png)

**Comment by annieszot** [comment]
@Niicck I'll work on this QA this afternoon

**Comment by annieszot** [comment]
Screenshots for "The new email submission sitch on the confirmation page" 
![Screen Shot 2019-03-27 at 12 40 28 PM](https://user-images.githubusercontent.com/46934140/55099588-f3a81300-508d-11e9-9b52-7933e946468e.png)
![Screen Shot 2019-03-27 at 12 41 38 PM](https://user-images.githubusercontent.com/46934140/55099589-f3a81300-508d-11e9-828f-fdca293abad3.png)
![Uploading Screen Shot 2019-03-27 at 12.41.49 PM.png…]()
![Uploading Screen Shot 2019-03-27 at 12.41.59 PM.png…]()

**Comment by annieszot** [comment]
Screenshots calendar icon for #1057 
![Screen Shot 2019-03-27 at 12 47 21 PM](https://user-images.githubusercontent.com/46934140/55099869-821c9480-508e-11e9-9b3c-8baea2b3b66e.png)
![Screen Shot 2019-03-27 at 12 47 24 PM](https://user-images.githubusercontent.com/46934140/55099870-821c9480-508e-11e9-9c30-1399fd215386.png)

**Comment by annieszot** [comment]
Closing
