### ISSUE TITLE
Identify depts. with microsites and their points of contact

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1392]

**Comment by desigonz** [comment]
- [ ] @desigonz: dig up email addresses
- [ ] @desigonz: draft up intro email

**Comment by desigonz** [comment]
@kriskristin here's my first stab at an intro email...all feedback welcome! I'm wondering if we're hitting the right tone?


Hi ____,

I work in the Office of Design and Delivery. I work on a team that is imagining the future of the City of Austin’s websites. We’re in the process of building the City of Austin’s future website, with the goal of improving resident access to municipal services.

One of the things we’re thinking about is how to integrate and connect users to City of Austin microsites like <name of microsite>. We’d would love to set up a time to talk to you about the <name of microsite> website and learn more about your process, audience, and goals. Do you have availability to meet during the week of <April 1 through 4>?

**Comment by desigonz** [comment]
@kriskristin made some more edits, the latest version is edited here on github :)

**Comment by desigonz** [comment]
- Healthy Places Healthy People: ask Linda Cox for contact; if not, HPHP@austintexas.gov
- Austin Animal Center: @LauraTrujillo, do you have a good AAC contact? 
- Austin Materials Marketplace: Daniel Kietzer

**Comment by LauraTrujillo** [comment]
@desigonz I'll do some digging to find out who we've worked with in the past at AAC.

**Comment by kriskristin** [comment]
@desigonz Sorry, I haven't seen this until now. My GitHub notifications are not working, I need to get that figured out.

Email looks great. I am assuming that you are going to link them to the exact site that we are going to be talking to them about. That way they have more context, they might not know that what they have is called a microsite.
