### ISSUE TITLE
Implement new Process Page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1400]
Delete current Process Page
Duplicate Service Page
Rename it Process Page

**Comment by amenity** [comment]
@briaguya - discussed this during planning on Thursday and decided we should cross-flock discuss first. See #1445

**Comment by easherma** [comment]
@briaguya can you update on this? If it still needs to be done or if we can point to a PR/commit where we took care of it? I see Service and Process pages on Joplin prod, but I'm clear on the specific differences.

**Comment by easherma** [comment]
May be related: https://github.com/cityofaustin/techstack/issues/777
