### ISSUE TITLE
Make "Contacts" have social media urls - Joplin 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1403]
Ideally just a list of URLs, Janis will parse and assign appropriate icon

QA Notes:
In joplin, if you navigate to a page with contacts, you can click the "edit contact" button and there should be a place to enter URLs for social media accounts.

**Comment by briaguya** [comment]
Looks like FB is embracing the @ now, might as well put it in our links there too (like we're doing for twitter)

![Screen Shot 2019-03-21 at 2.50.34 AM.png](https://images.zenhubusercontent.com/5afb42ab4b5806bc2bd34c32/0046b5b5-180e-4b69-b806-e90f077ec6c1)
