### ISSUE TITLE
Hard code OPO social media in contact information 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1404]
https://www.facebook.com/atxpoliceoversight/
https://twitter.com/ATX_OPO

Display with material icons as shown in https://xd.adobe.com/spec/9770982d-46fa-472c-7726-37597101c397-e141/screen/308ded90-fef1-4900-9be3-48daaf1f747b/OPO-Department-MVP-Desktop/

**Comment by pibemillo** [comment]
This is being addressed by #1421, see PR https://github.com/cityofaustin/janis/pull/322. 

FB SVG needs to be updated to filled-in/boxed version
