### ISSUE TITLE
Decide on days of the week order stuff

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1405]
Janis automatically shows current day at the top of a list of times. Do we want to keep it this way? 

(https://live.browserstack.com/issue-tracker/cb7aa4731a847a0e359853aa6d3b4eaabe512c7d/realios_iPhone_7.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/cb7aa4731a847a0e359853aa6d3b4eaabe512c7d/realios_iPhone_7.jpg)

**Comment by oliver2g** [comment]
Will be decided at design pin-up on 4/2

**Comment by oliver2g** [comment]
The decision is to leave the day of week order as it is unless production or user testing proves otherwise
