### ISSUE TITLE
Incorporate Central Texas Diabetes Coalition content into diabetes info page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1414]
Central Texas Diabetes Coalition: http://www.austintexas.gov/department/central-texas-diabetes-coalition

Google doc for diabetes prevention: https://docs.google.com/document/d/14GNobdf1nlWMVI5YSnXU5JZSn9TYfXZQ57L2qrlEs94/edit?usp=sharing

**Comment by desigonz** [comment]
Draft lives here: https://docs.google.com/document/d/14GNobdf1nlWMVI5YSnXU5JZSn9TYfXZQ57L2qrlEs94/edit?usp=sharing

I just incorporated info on the Central Texas Diabetes Coalition onto a page I had drafted earlier. @srigdon, want to take first pass at the updated page?

**Comment by desigonz** [comment]
Hey @srigdon, are you done reviewing this one?

**Comment by srigdon** [comment]
@desigonz Finished! See edits in the document.

**Comment by desigonz** [comment]
Passing to @LauraTrujillo for 2nd review.

**Comment by desigonz** [comment]
@LauraTrujillo you've seen an early version of this draft (before incorporating Central Texas Diabetes Coalition) so should be a quick pass!

**Comment by LauraTrujillo** [comment]
good to go, @desigonz! 
Adding a note about email aliases to our pinup board for next week!

**Comment by desigonz** [comment]
Great, closing this one.
