### ISSUE TITLE
Recruit Spanish-speaking participants for OPO form testing

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1416]

**Comment by kriskristin** [comment]
I translated the participant recruitment form into Spanish. Sergio reviewed it for errors and  @desigonz will shortly. 

https://docs.google.com/document/d/1gJ1pk5O1vIPxZyQW4eCTILaqgMj8537dFpvpRyONW1Q/edit?usp=sharing

**Comment by kriskristin** [comment]
Spanish recruitment survey is done. Spanish social media blurb was sent to Sara Peralta. 
I will touch base with Sara again and see if there are other outreach groups that we can access for usability testing.
