### ISSUE TITLE
Create "Locations for Testing and Outreach" Resource

### ISSUE THREAD

**Issue by aineeathar** [cityofaustin/techstack#142]
[Locations for Testing and Outreach](https://airtable.com/tblT3P9DXAzFRcqgj/viweBjRwtFOqcLpYE)

Document locations and organizations to connect with for resident outreach and usability testing:
- Types of residents who visit each location, e.g. 65+, ESL, visually-impaired, etc. 
- Peak traffic hours or schedules for meetings/childcare/classes that draw particular crowds
- Contact person 
- ...

**Comment by juliazbyron** [comment]
Duplicate issue. Julia already doing this task.

**Comment by juliazbyron** [comment]
Reopening. Context from Amenity:

This effort is separate from the test plan. 

"Marni and I talked about how it would be useful to have information from more than just a couple libraries about the types of residents who visit each location, peak traffic hours, schedules for any meetings/childcare/classes that draw particular crowds, who to contact there for setting something up, etc. The idea was that Ainee can compile that type of information as a resource for everyone. 

So while it would help us identify optimal locations and times for this round of Foster Application testing, that's not the entire purpose."

**Comment by juliazbyron** [comment]
@amenity Can you update the name and description for clarity?

**Comment by aineeathar** [comment]
- Added central library contact to Julia's test plan! 
- Sent Airtable to equity office and language access
