### ISSUE TITLE
Use material icons for contact information component

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1421]
Make them look like: https://xd.adobe.com/spec/9770982d-46fa-472c-7726-37597101c397-e141/screen/308ded90-fef1-4900-9be3-48daaf1f747b/OPO-Department-MVP-Desktop/

**Comment by easherma** [comment]
currently we're importing material icons as a font set: 
https://github.com/cityofaustin/janis/blob/db904e59bed52fa729bb6456a3331c563145740e/src/css/base/_variables.scss
example usage: 
https://github.com/cityofaustin/janis/blob/20b89d0224bba1ee9da40b618ebd9594e8d9ace2/src/components/Pages/Information.js#L37

**Comment by pibemillo** [comment]
PR for review/discussion here:
https://github.com/cityofaustin/janis/pull/322
