### ISSUE TITLE
Update content on OPO Complaint Investigation page process pages to match mocks

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1423]
https://alpha.austin.gov/en/police-oversight/complaint-investigation-process should look like

https://xd.adobe.com/spec/9770982d-46fa-472c-7726-37597101c397-e141/screen/2dab58ac-cec6-487f-9ea2-831954213943/OPO-Information-Investigation-Process-1/ 

- [ ] H4 should be same size as body copy
- [ ] H4 should be bold - right now it's not showing as bold on all browsers; need to look into which IBM Plex Sans https://fonts.google.com/specimen/IBM+Plex+Sans

**Comment by easherma** [comment]
Is this a dupe/related #1348 ?

**Comment by amenity** [comment]
@easherma sure is.
