### ISSUE TITLE
Follow up with CTTC on usability testing w/ Digital Inclusion subcom 

### ISSUE THREAD

**Issue by aineeathar** [cityofaustin/techstack#143]

**Comment by amenity** [comment]
@ashleecoa, @courtneyjacinic, @cthibaultatx  - do y'all know where this stands?

**Comment by amenity** [comment]
We are due in April to follow up with the Community Technology and Telecommunications Commission, specifically the Digital Inclusion Subcommittee, about usability testing. There was also talk about inviting them to Sprint Reviews or the like. 

Need to email:  
- William (Dave) Floyd, bc-William.Floyd@austintexas.gov (chair)
- Nehemiah Pitts III, bc-Nehemiah.Pitts@austintexas.gov (committee subchair for digital inclusion working group)

Discuss: 
- Update/progress report - especially pain-points and success with translation and diverse user testing participants
- Their particular interests, concerns, and aspirations for the project
- Their preferred way to stay in the loop — Project Site? Sprint Reviews? Weekly Digest? Short-stack morning meetings?

**Comment by amenity** [comment]
@mateoclarke offered to liaison with CTTC.
