### ISSUE TITLE
OPO media push: Map form component 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1432]
Map is moving to its own page, see #1433 ... 

Additionally:
- [x] Remove "find me" icon from map text field
- [x] Address-entry text field should expand across width of map on desktop, ie, 90% so that users can see entire address when on desktop
- [x] Add plus/minus controls (zoom) to lower right of map
- [x] Disable 3D view on map

**Comment by easherma** [comment]
https://github.com/cityofaustin/usfs-components/pull/8 
![done](https://media.giphy.com/media/8JW82ndaYfmNoYAekM/giphy.gif)

**Comment by amenity** [comment]
I am not seeing the 90% width for the address bar in desktop.

<img width="989" alt="Screen Shot 2019-03-12 at 11 18 33 PM" src="https://user-images.githubusercontent.com/1463708/54253489-52fa1500-451d-11e9-8d59-bb0bf612821e.png">

Want me to make this into a new issue?

**Comment by amenity** [comment]
Looked awkward at 90%, but extended the search bar on desktop.
