### ISSUE TITLE
Police Oversight form: Design map-only page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1434]
Per our [discussion with Gay](https://docs.google.com/document/d/1QGIv0tQh_Pa5sM0gTOTdY7xORMBVIOdKQF5dne5Jyt8/edit), location information is extremely important for OPO in identifying what officers might be the subject of a complaint.  

As such, having it on its own page would be an improvement - gives the map more room, and focus.

**Comment by toribr** [comment]
![complaint - 2 1 - what happened - yes 1](https://user-images.githubusercontent.com/3790067/53979320-19677b00-40d3-11e9-8c45-fbbccf7c67e0.png)
