### ISSUE TITLE
"An official website" header should be visible on mobile

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1437]
@briaguya - [specs here](https://github.com/cityofaustin/techstack/issues/1443#issuecomment-470616800).

**Comment by briaguya** [comment]
bug
<img width="446" alt="Screen Shot 2019-03-12 at 2 52 11 PM" src="https://user-images.githubusercontent.com/6384156/54231440-8796ae00-44d6-11e9-90ce-6b5bf08d2c92.png">

**Comment by amenity** [comment]
@briaguya - is there a PR out for this guy?
