### ISSUE TITLE
OPO media push: Change "Date and time?" to "When did it happen?"

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1438]
### English
_https://forms.austin.gov/police-thank/what-happened_
- [x] Change "Date and time, if known" to "When did it happen?"

https://forms.austintexas.io/police-complain/what-happened
- [x] Change "Date and time, if known" to "When did it happen?"

### Spanish
_https://forms.austin.gov/policia-agradezca/que-sucedio_
- [x] Change "Fecha y hora, si las sabe" to "¿Cuándo sucedió?"

_https://forms.austintexas.io/policia-queja/que-sucedio_
- [x] Change "Fecha y hora, si las sabe" to "¿Cuándo sucedió?"

### Translations.json
- [x] Update [Line 65-66](https://github.com/cityofaustin/officer-complaint-form/blob/77a88ce2c29efcfa20089381cc436f2c01f9b798/locale/translations.json#L65):
```
"When did it happen?": {
    "es": "¿Cuándo sucedió?"
```

**Comment by amenity** [comment]
@LauraTrujillo You had "Add a period after date and time" - do you mean on the date and time label?

**Comment by LauraTrujillo** [comment]
@amenity scratch that! No period needed- I was looking at the helper text. The label doesn't need punctuation

**Comment by amenity** [comment]
Thanks, @LauraTrujillo!

Also, @toribr would like to hold off on: 
- [ ] Add helper text under _Date and time_: Getting as close to the date and time as you can helps us thank the right officer(s).
until we validate the need for such verbiage in user testing. Is that cool w you?

**Comment by LauraTrujillo** [comment]
@amenity Yep, that's very cool with me.

**Comment by amenity** [comment]
@desigonz - was this in a PR? I am not seeing it reflected on the staging sites... 🤔

**Comment by desigonz** [comment]
@amenity pull request here: https://github.com/cityofaustin/officer-thank-form/pull/16

**Comment by desigonz** [comment]
@amenity Made a pull request to update line 65-66: https://github.com/cityofaustin/officer-complaint-form/pull/68
