### ISSUE TITLE
Police Oversight form: Remove yes/no conditional before officer info on thank you form

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1439]
@toribr points out that it doesn't make sense to nest the officer information behind a yes/no on the officer details page. We should just have "Tell us about the officer(s)" and go straight to the Name, Physical description, etc. fieldset. 

- [ ] English form
- [ ] Spanish form

**Comment by amenity** [comment]
@easherma - this should be pretty easy, yeah?

**Comment by toribr** [comment]
This is on the "thank you" form, if that's not obvious.

**Comment by amenity** [comment]
@easherma - could you size, please?

**Comment by easherma** [comment]
I'm not convinced this is an easy fix or even a good idea, I think it came up on another issue as well. 

Either way it's a pretty big deviation from current spec and has implications across both forms. I'd call it out of spec/scope for this version.

**Comment by toribr** [comment]
This will be tracked in #1369
