### ISSUE TITLE
Mock up Arabic-translated content in alpha.austin.gov

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#144]
@ashleecoa @courtneyjacinic @LauraTrujillo please share alpha Arabic content with me so I can mock it up

**Comment by ashleecoa** [comment]
@cthibaultatx https://drive.google.com/open?id=1rgRRytxDq6KD14kce8I6BdXGJkN87TJA

**Comment by cthibaultatx** [comment]
mocked up and reviewed with content team. @ashleecoa is checking with translators whether or not Arabic can be read centered vs. right-aligned.
