### ISSUE TITLE
<title> should match page title

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1450]
<img width="913" alt="Screen Shot 2019-03-08 at 5 33 11 PM" src="https://user-images.githubusercontent.com/1463708/54061836-4a75a780-41c8-11e9-994d-6f84f49510ea.png">

**Comment by pibemillo** [comment]
I can take this one. Looks like we need to import Head from React-Static into each content-type so we can set <title>{title}<title>. Will push up a branch to review and discuss

**Comment by amenity** [comment]
@pibemillo - is this in a PR or deployed somewhere?

**Comment by pibemillo** [comment]
Both! 
https://github.com/cityofaustin/janis/pull/327
https://janis-staging-pr-327.herokuapp.com/

**Comment by amenity** [comment]
Beautiful. ✨

**Comment by pibemillo** [comment]
@briaguya merge party took care of this, now in master
