### ISSUE TITLE
Microsite interview protocol

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1453]
- [x] develop questions
- [ ] write intro script
- [ ] write closing script
- [ ] get edits/feedback

**Comment by kriskristin** [comment]
@desigonz  
Beginning of some questions: 

What is the primary goal of this [microsite] webpage?
Can you describe the type of person that this [microsite] is intended for?
Tell me about why [department] chose to make this [microsite] website? 
Do you think this [microsite] is successful? Why or why not?

**Comment by desigonz** [comment]
@kriskristin Started an [interview protocol doc](https://docs.google.com/document/d/1BLWEm_1pTye9Lec0dDL1ef9huSXbsKV1lI3MFlh-Q-0/edit?usp=sharing)

**Comment by kriskristin** [comment]
interview protocol looks great @desigonz.
