### ISSUE TITLE
Police Oversight form: Upload revised PDFs

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1456]
- [x] [OPO_2019_complaint-form-print_English.pdf](https://github.com/cityofaustin/techstack/files/2973062/OPO_2019_complaint-form-print_English.pdf)
- [x] [OPO_2019_complaint-form-print_Spanish.pdf](https://github.com/cityofaustin/techstack/files/2973063/OPO_2019_complaint-form-print_Spanish.pdf)
- [x] [OPO_2019_thanks-form-print_English.pdf](https://github.com/cityofaustin/techstack/files/2973064/OPO_2019_thanks-form-print_English.pdf)
- [x] [OPO_2019_thanks-form-print_Spanish.pdf](https://github.com/cityofaustin/techstack/files/2973065/OPO_2019_thanks-form-print_Spanish.pdf)

**Comment by srigdon** [comment]
[OPO_2019_complaint-form-print_English.pdf](https://github.com/cityofaustin/techstack/files/2973062/OPO_2019_complaint-form-print_English.pdf)
[OPO_2019_complaint-form-print_Spanish.pdf](https://github.com/cityofaustin/techstack/files/2973063/OPO_2019_complaint-form-print_Spanish.pdf)
[OPO_2019_thanks-form-print_English.pdf](https://github.com/cityofaustin/techstack/files/2973064/OPO_2019_thanks-form-print_English.pdf)
[OPO_2019_thanks-form-print_Spanish.pdf](https://github.com/cityofaustin/techstack/files/2973065/OPO_2019_thanks-form-print_Spanish.pdf)

**Comment by amenity** [comment]
@sergiogcx - ready when you are!

**Comment by sergiogcx** [comment]
The files have been updated.

**Comment by sergiogcx** [comment]
These are the links:
https://forms.austin.gov/files/OPO_complaint-form_print_English.pdf
https://forms.austin.gov/files/OPO_complaint-form_print_Spanish.pdf
https://forms.austin.gov/files/OPO_thanks-form_print_English.pdf
https://forms.austin.gov/files/OPO_thanks-form_print_Spanish.pdf

Staging(master):
https://forms.austintexas.io/files/OPO_complaint-form_print_English.pdf
https://forms.austintexas.io/files/OPO_complaint-form_print_Spanish.pdf
https://forms.austintexas.io/files/OPO_thanks-form_print_English.pdf
https://forms.austintexas.io/files/OPO_thanks-form_print_Spanish.pdf

**Comment by srigdon** [comment]
As of 3/18, the English and Spanish print/by mail complaint forms need to be updated to these links: 

[Abbreviated Complaint Form-Span.pdf](https://github.com/cityofaustin/techstack/files/2984907/Abbreviated.Complaint.Form-Span.pdf)
[Abbreviated Complaint Form-Eng.pdf](https://github.com/cityofaustin/techstack/files/2984908/Abbreviated.Complaint.Form-Eng.pdf)

**Comment by sergiogcx** [comment]
So the links will remain like these:

https://forms.austintexas.io/files/OPO_complaint-form_print_English.pdf
https://forms.austintexas.io/files/OPO_complaint-form_print_Spanish.pdf
https://forms.austintexas.io/files/OPO_thanks-form_print_English.pdf
https://forms.austintexas.io/files/OPO_thanks-form_print_Spanish.pdf

Our forms for the complaint form were simply deleted, and the files `Abbreviated Complaint Form-Span.pdf, Abbreviated Complaint Form-Eng.pdf` were renamed to `OPO_complaint-form_print_Spanish.pdf & OPO_complaint-form_print_English.pdf` respectively.

**Comment by srigdon** [comment]
@sergiogcx Thank you! Here are the thank-you forms, and I kept the file name format you spelled out above (good call on those, much better). Can you put them up? 

[OPO_thank-you-form_print_English.pdf](https://github.com/cityofaustin/techstack/files/2990182/OPO_thank-you-form_print_English.pdf)
[OPO_thank-you-form_print_Spanish.pdf](https://github.com/cityofaustin/techstack/files/2990183/OPO_thank-you-form_print_Spanish.pdf)
