### ISSUE TITLE
Janis 2.0: Implement Service Page phase 2

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1458]
#876 covered some ground, but need to discuss what's next with @chasechenevert and @toribr at the 3/19 design/dev sync.

**Comment by toribr** [comment]
So there's a couple of inconsistencies between janis and joplin that I'm noticing.
joplin: https://joplin.herokuapp.com/admin/pages/4/edit/
Janis: https://janis-staging.herokuapp.com/health-safety/records-and-certificates/birth-and-death-certificates

1) Looks like the steps should be rendering as options(accordions), but aren't.
2) Additional content component is rendering weirdly (at the very least it's rendering centered text which is out of spec.

**Comment by pibemillo** [comment]
Refactor `StepsWithOptions` to match designs
- accordions

**Comment by pibemillo** [comment]
@briaguya what is this url `https://janis-staging.herokuapp.com/health-safety/records-and-certificates/birth-and-death-certificates` when working in local? I can't access the page..

**Comment by briaguya** [comment]
@pibemillo lots of links will be broken because we restructured urls for topic collections, right now this is working for me: http://localhost:3000/health-safety/health-records-certificates-2/birth-death-certificates/birth-and-death-certificates
