### ISSUE TITLE
Joplin 2.0: Initial CMS research

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1459]
- [x] Review [previous comparison work](https://drive.google.com/drive/folders/1n39E35SW9d7PYUeNOxQJnjE-95qVuZmO)
- [ ] Document Wagtail pain points with @briaguya 
- [x] Review Gov.uk CMS with content and UX [content-publisher](https://docs.publishing.service.gov.uk/apps/content-publisher.html) #1460 and document features/patterns we want to use
- [x] Set up requirements for comparison in upcoming sprint

**Comment by easherma** [comment]
@briaguya it would still be good to get together sometime and document the specific pain points with joplin, but I'm going to close this for now
