### ISSUE TITLE
Review GOV.UK content-publisher 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1460]
**Objective** 
Whether or not we can reuse the Gov.uk CMS, let's document what features/patterns we would want in Joplin 2.0. 

[Video](https://drive.google.com/file/d/1u1FxA2t8VPEeUSy3V470TKIfdHk2Fvh9/view):

**Comment by oliver2g** [comment]
@LauraTrujillo at content backlog grooming, the team decided that this should be a meeting between dev and content. Can you help schedule

**Comment by oliver2g** [comment]
@LauraTrujillo this meeting is scheduled for Thursday 4/18. @toribr will be out of office. can you please reschedule?

**Comment by LauraTrujillo** [comment]
@oliver2g sure thing! Rescheduled for the following week.

**Comment by LauraTrujillo** [comment]
Per our meeting, we're shelving this conversation right now. We're going to get another dev on Joplin to build out what we need. Can't rely entirely on Gov.uk's cms "as is" 
![IMG_6137](https://user-images.githubusercontent.com/30263897/56611248-f1769d00-65d6-11e9-9a1b-eaa1f74b9a63.jpeg)
