### ISSUE TITLE
OPO media push: Upload (Share your photos or videos) page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1466]
- [x] Link to "How we use your info" - nothing happens when I click on it
- [x] Add a period at the end of etc. :"Upload any evidence that you have (video files, audio files, photos, police report, hospital record, etc)"

**Comment by easherma** [comment]
This is all fixed in staging(forms.austintexas.gov), not pushed to
production.

**Comment by desigonz** [comment]
@amenity Added the missing period. As for the link, not sure what's going on—the right link is in the code.

**Comment by amenity** [comment]
@desigonz - the link is working!

**Comment by desigonz** [comment]
yep, just seeing it on staging! thanks!
