### ISSUE TITLE
Police Oversight form: Review and submit page officers/witnesses sections

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1475]
- [x] Make Add button for witness and officer label "Add officer" and "Add witness"
- [x] Remove/hide bold "Tell us about the officer(s)" text
- [x] Remove/hide bold "Tell us about any witnesses"

See also #1105.

**Comment by amenity** [comment]
@toribr - I broke this out from another issue with some simpler tasks. Attaching a screenshot of the officer section of the review page. Which of the "Tell us about the officer(s)" do you want removed/hidden? 
![screencapture-forms-austintexas-io-police-complain-review-and-submit-2019-03-13-17_44_17](https://user-images.githubusercontent.com/1463708/54319711-78882c80-45b8-11e9-8b5b-c497e93863b6.png)

**Comment by toribr** [comment]
This one.
![Screen Shot 2019-03-14 at 8 58 17 AM](https://user-images.githubusercontent.com/3790067/54362669-5c77a000-4637-11e9-833d-9f562c423673.png)

**Comment by easherma** [comment]
https://github.com/cityofaustin/us-forms-system/commit/0f6ed7e823688e0af230b9c0d9160ec31d5e05e6
 donezo

**Comment by amenity** [comment]
@easherma - I am still seeing the bold "Tell us..." on https://forms.austintexas.io/police-complain/review-and-submit
<img width="880" alt="Screen Shot 2019-03-15 at 5 33 15 PM" src="https://user-images.githubusercontent.com/1463708/54465342-a7cda380-4748-11e9-9bf4-6b6c00e9d3fa.png">

**Comment by easherma** [comment]
donezo

**Comment by annieszot** [comment]
![Screen Shot 2019-03-23 at 12 53 03 PM](https://user-images.githubusercontent.com/46934140/54869704-a1ec4980-4d6a-11e9-86fa-1f2843db47bb.png)
Done and closing
