### ISSUE TITLE
Police oversight form: Fix capitalization on file upload

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1476]
This text should be 
_"Drag and drop your files or upload"_ [with upload linked]
<img width="841" alt="Screen Shot 2019-03-13 at 6 05 52 PM" src="https://user-images.githubusercontent.com/1463708/54320346-aff7d880-45ba-11e9-9094-ca504ff11a1b.png">

This is part of the Filepond widget.

**Comment by amenity** [comment]
@sergiogcx - revisiting @easherma's [question](https://github.com/cityofaustin/techstack/issues/1182#issuecomment-467679106): Do you think this is something that could be fixed with translations.json?

**Comment by sergiogcx** [comment]
I just saw this, I will be fixing this ASAP.

**Comment by sergiogcx** [comment]
Na, it's done through the FilePond component, the translation will have to be adjusted.

**Comment by sergiogcx** [comment]
Ok, after discussing with content the capitalization needs to match editorial style.

https://github.com/cityofaustin/us-forms-system/pull/26

**Comment by sergiogcx** [comment]
It looks like the translations are already there:

Complaint:

https://github.com/cityofaustin/coa-forms/blob/709e49535957ef60a7a65cb9dbcec1b1887c7e78/forms/officer-complaint-form/locale/translations.json#L148

Thank you:

https://github.com/cityofaustin/coa-forms/blob/709e49535957ef60a7a65cb9dbcec1b1887c7e78/forms/officer-thank-form/locale/translations.json#L137


All there is to do is to test and merge.

**Comment by easherma** [comment]
tested, merged to staging!
