### ISSUE TITLE
Thank you form "Learn more about who we are" link

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1477]
"Learn more about who we are and what we do." is linking to the same page rather than [OPO microsite](https://alpha.austin.gov/police-oversight/)
- [x] fix English link
- [ ] fix Spanish link

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/302af2a1-42e3-45cd-804b-8daa2681b8c4)

**Comment by amenity** [comment]
English fixed in https://github.com/cityofaustin/officer-thank-form/pull/18. That should take care of the Spanish link as well, right, @easherma?

**Comment by easherma** [comment]
Yes, this is fixed.

**Comment by desigonz** [comment]
It's linking to the English page from both the English and Spanish thank you forms. Shouldn't the Spanish thank you form link to https://alpha.austin.gov/es/police-oversight?
