### ISSUE TITLE
Update Choose Language Bar based on new designs

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#148]
##mobile/sm mocks:
![default-english](https://user-images.githubusercontent.com/20911665/37229793-d3ddf898-23aa-11e8-87de-96126801827a.png)
![spanish](https://user-images.githubusercontent.com/20911665/37229799-d6985074-23aa-11e8-9c89-6f74ca9a0d1a.png)
![vietnamese](https://user-images.githubusercontent.com/20911665/37229804-d94d7218-23aa-11e8-93d2-d478cf929409.png)
![arabic](https://user-images.githubusercontent.com/20911665/37229807-dafefda2-23aa-11e8-9b60-b7306d2ef8db.png)

##tablet/med and desktop/lge behave and styled the same
![default-english lge](https://user-images.githubusercontent.com/20911665/37230118-ee4f6ba2-23ab-11e8-813e-5d7b9a428afc.png)
![spanish lge](https://user-images.githubusercontent.com/20911665/37230128-f138a022-23ab-11e8-90fa-17645312c896.png)
![vietnamese lge](https://user-images.githubusercontent.com/20911665/37230133-f3bead8c-23ab-11e8-9ad3-5f9b1796b5fa.png)
![arabic lge](https://user-images.githubusercontent.com/20911665/37230137-f5a2446a-23ab-11e8-823b-18f846f6a357.png)

- sketch file: https://drive.google.com/open?id=1wtiU9LqpvU2KTu362bCPMfS7tfYgjyuf

TODO:
- [x] UX Review/handoff
- [x] Paste mocks here and/or reference Sketch version to work from cc/ @cthibaultatx    
- [ ] Get translated words (tablet and desktop) and abbreviations (mobile) from content team - we have words, still waiting on abbreviations.

**Comment by cthibaultatx** [comment]
Please review

- [ ] @LauraTrujillo 
- [ ] @courtneyjacinic 
- [ ] @ashleecoa 
- [ ] @toribr

**Comment by ashleecoa** [comment]
@cthibaultatx We did not. Could we add them into the table? If so, I can just let the translators know that we have more in there.

**Comment by ifsimicoded** [comment]
@cthibaultatx this task is now tagged with dev, so I'm reopening, since dev has not implemented design v2 on janis yet.

**Comment by cthibaultatx** [comment]
@ifsimicoded it's in issue #180

**Comment by ashleecoa** [comment]
Abbreviations are in here: 
Spanish: https://drive.google.com/open?id=1F-MInnVSWD-U_YJNeDthLxC-2GWwuuy3
Arabic: https://drive.google.com/file/d/1A2Ssy8OT6EKiGSLYhTFHYbAq6maAKt0x/view?usp=sharing
Vietnamese: https://drive.google.com/file/d/1wobtUirII4fJWzta0-dHm_pT7DTXA_YW/view?usp=sharing
