### ISSUE TITLE
Police Oversight form: Update Spanish thanks paper form translations

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1480]
[OPO_thanks-form_print_Spanish_needs-translation_3-14-19.docx](https://github.com/cityofaustin/techstack/files/2967641/OPO_thanks-form_print_Spanish_needs-translation_3-14-19.docx)

**Comment by amenity** [comment]
@desigonz - please add to #1481 for @srigdon when you are done! Thanks.

**Comment by desigonz** [comment]
uploaded new doc to [#1481](https://app.zenhub.com/workspace/o/cityofaustin/techstack/issues/1481)
