### ISSUE TITLE
Police Oversight confirmation emails: proofread and compile typos

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1482]
Was able to close #1362 , but looks like there are some lingering capitalization/standards typos in the OPO confirmation emails. 

Check:
- [ ] Complaint confirmation - English
- [ ] Complaint confirmation - Spanish
- [ ] Thanks confirmation - English
- [x] [Thanks confirmation - Spanish corrections.pdf](https://github.com/cityofaustin/techstack/files/2968108/Thanks.Confirmation.-.Spanish.corrections.pdf) - capitalizations and "Ln." goes to "Lane"

Then, 
- [ ] Create one issue for Sergio with all the corrections.

**Comment by amenity** [comment]
- [ ] [Thanks Confirmation - Spanish corrections.pdf](https://github.com/cityofaustin/techstack/files/2968108/Thanks.Confirmation.-.Spanish.corrections.pdf) - capitalization and "Ln." goes to "Lane"

**Comment by desigonz** [comment]
@amenity Also realizing we're using some wrong translations here (I don't believe we ever checked this against the official translations). Might be easiest if I go into the code and try to update as much as possible first, then do a review.

**Comment by desigonz** [comment]
@amenity Created a [pull request](https://github.com/cityofaustin/form-service-api/pull/14) with my first pass of edits—once it's merged I'll give it a second pass.

**Comment by desigonz** [comment]
@amenity I reviewed the English and Spanish confirmation emails and started issue [#1515](https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/1515) for the edits—they're looking slightly more programmatic than copy changes.

**Comment by desigonz** [comment]
Also, might be nice to have another set of eyes on these confirmation emails 😵

**Comment by LauraTrujillo** [comment]
Handled!
