### ISSUE TITLE
Fix translation on complaint form "sobre usted" page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1484]
On https://forms.austintexas.io/policia-queja/acerca-de-usted, "I am willing to be...2 to 4 business days" needs to be translated

![opo-queja-sobre-usted.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/d5556b89-7c67-4681-b749-d918c97f7cb9)

**Comment by desigonz** [comment]
@amenity [PR #71](https://github.com/cityofaustin/officer-complaint-form/pull/71)

**Comment by annieszot** [comment]
Translated https://forms.austintexas.io/policia-queja/acerca-de-usted
![Screen Shot 2019-03-22 at 1 28 25 PM](https://user-images.githubusercontent.com/46934140/54845088-79028080-4ca6-11e9-9d18-8c61965734aa.png)
Closing issue
