### ISSUE TITLE
Create a confirmation modal for language switching during OPO form completion

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1485]
Draft copy for @chasechenevert 

Title: Start over in Spanish?

Body: Switching to Spanish will erase all the information you have previously entered.

Are you sure you want to switch?

SECONDARY button label: Yes, start over.  PRIMARY: No, proceed in English.

**Comment by toribr** [comment]
https://developer.paciellogroup.com/blog/2018/06/the-current-state-of-modal-dialog-accessibility/

**Comment by easherma** [comment]
@toribr read that article and yikes. so did we maybe rush into the idea of trying to implement this before press push?

**Comment by sergiogcx** [comment]
I have a PR open, in case anyone would like to take a look:

https://github.com/cityofaustin/officer-complaint-form/pull/75

I only spent 2.5 hrs on this, so no big deal if we don't want to implement it after all.

**Comment by sergiogcx** [comment]
Here is a good animation clicking through the options:

![fgWKTVTpDK.gif](http://g.recordit.co/fgWKTVTpDK.gif)

**Comment by sergiogcx** [comment]
Here is a screenshot for desktop version (max-width: 600px)

![Screen Shot 2019-03-20 at 12.55.16 AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/a7bb8fb9-fab9-43ba-9408-c349c82f7db0)

Screenshot Mobile:

![Screen Shot 2019-03-20 at 12.56.24 AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/4c9d7062-4ca0-43c5-91df-b265ef4316ae)

**Comment by toribr** [comment]
@easherma @sergiogcx One thing that we also didn't discuss is *where* the form is invoked. It doesn't make sense to invoke it from the page where @sergiogcx is showing it - it should only be invoked *after* the user is within the form, ie, at the point at which the user has already entered info.

**Comment by chasechenevert** [comment]
## Vis Design: modal for switching languages

Dev spec: https://xd.adobe.com/spec/b48d6db0-a7ad-4604-4ca6-7565eafd4758-c2bc/

Here's the MVP for the translation modal. Going to need to refine this later, but for MVP it works.

<img width="1734" alt="Screen Shot 2019-03-20 at 12 07 04 PM" src="https://user-images.githubusercontent.com/7027270/54704428-b4674880-4b08-11e9-8b64-255fb4e094f8.png">

**Comment by easherma** [comment]
@toribr et al: doing some board cleaning and is this issue supposed to refer to the design of the modal only or also implementation? It appears both, and I want to re-size it to a L/XL accordingly (since it has taken a couple days with a couple people working on it). Ya'll ok with me re-sizing this?

**Comment by toribr** [comment]
I'm not sure - there may or may not be an additional issue somewhere? Size accordingly.

**Comment by desigonz** [comment]
Hey team—found some grammatical errors in the Spanish version of this and planning to create a new issue with edits. Is there a content point person on the modal language that I can direct questions to?

**Comment by desigonz** [comment]
Submitted [#1602](https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/1602) with translation edits. Are we planning to send these new texts out to a professional translator?

**Comment by easherma** [comment]
@sergiogcx @desigonz @toribr This has been in QA for a minute. There were some changes over made time, but we do have a working version in production right now that appears to implement this feature. Are we holding it open for additional QA or any other reason or should we mark it as resolved?

**Comment by desigonz** [comment]
from my perspective it's cool to close it, but I'd wait for @toribr to chime in. I believe @sergiogcx is working on #1602

**Comment by toribr** [comment]
How about we wait for the results of usability testing, which will happen on Wed?

**Comment by easherma** [comment]
Up to ya'll and @oliver2g . My two cents would be that if our board is crowded it would be good to close this (as the modal is 'created') and just open a  new issue for making improvements based on testing if those come up.

**Comment by toribr** [comment]
That'd be ok, too.

**Comment by desigonz** [comment]
+1 @easherma—anything new will need its own issue(s)
