### ISSUE TITLE
Police Oversight form: Phone numbers should be link

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1488]
`Call the Office of Police Oversight at (512) 972-2676.`

should be 

```
Call the Office of Police Oversight at <a href="tel:+1-512-972-2676">(512) 972-2676</a>.
```

- [x] English thanks
- [x] Spanish thanks
- [x] English complaint
- [x] Spanish complaint

**Comment by easherma** [comment]
https://github.com/cityofaustin/officer-complaint-form/commit/81d886b368416af7b94998121396980276f9ec86

not 100% sure how translations will handle this
