### ISSUE TITLE
Link which opens new tab needs icon to indicate that

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1489]
The link for "How my info is used" on the media page needs this icon immediately after the text.

https://material.io/tools/icons/?search=open%20in%20new%20&icon=open_in_new&style=baseline

**Comment by annieszot** [comment]
Looks complete

**Comment by annieszot** [comment]
Looks complete 
![Screen Shot 2019-03-23 at 12 40 14 PM](https://user-images.githubusercontent.com/46934140/54869591-ebd43000-4d68-11e9-97d0-14e8a6ce5c40.png)
Closing
