### ISSUE TITLE
Bug: zoom buttons not centered

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1493]
Zoom + and - buttons should be centered within the frame

**URL tested:** https://forms.austintexas.io/police-complain/where-happened

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-complain%2Fwhere-happened&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-complain/where-happened) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 72.0 |
| Operating System | OS X Mojave |
| Resolution | 1512x946 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/5a49c5132af29c2f16105604aa007ce1a02cc152/macmo_chrome_72.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/5a49c5132af29c2f16105604aa007ce1a02cc152/macmo_chrome_72.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-complain%2Fwhere-happened&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-complain/where-happened) to reproduce the issue on Browserstack**

**Comment by annieszot** [comment]
I'm doing QA 
Mobile:
- [ ] iPhone: Safari 12.0
  - [ ] English
  - [ ] Spanish 
- [ ] Android: Chrome 71.0
  - [ ] English
  - [ ] Spanish 

Desktop:
- [ ] Windows 10: Chrome 71.0
  - [ ] English
  - [ ] Spanish
- [ ] Windows 7: Chrome 71.0;
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 7: Internet Explorer 11
  - [ ] English
  - [ ] Spanish 
- [ ] MacOS 10.14: Chrome 71.0
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Edge 17.17; 
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Internet Explorer 11
  - [ ] English
  - [ ] Spanish

**Comment by annieszot** [comment]
All maps on "Where were you" vertical + and -. Still presented same as @desigonz's comment. 
All maps on "review" Where you were have horizontal + and -

**Comment by annieszot** [comment]
@easherma Any concerns if "+" and "-" not centered or vertical vs horizontal?

**Comment by annieszot** [comment]
Retested on all - "+" and "-" centered on map "Where were you?" 
-iPhone and Android slow to load 
Closing
