### ISSUE TITLE
Bug: map zoom buttons look different on review page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1495]
On the review page, the zoom + and - buttons are side-by-side rather than one on top of the other. I expected them to be consistent to the screenshot in [#1493](https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/1493) 

**URL tested:** https://forms.austintexas.io/police-complain/review-and-submit

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-complain%2Freview-and-submit&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-complain/review-and-submit) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 72.0 |
| Operating System | OS X Mojave |
| Resolution | 1512x946 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/5345a091df0b0ef0a84bea6c3d17ad707b0dad40/macmo_chrome_72.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/5345a091df0b0ef0a84bea6c3d17ad707b0dad40/macmo_chrome_72.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-complain%2Freview-and-submit&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-complain/review-and-submit) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
Styling for buttons on review page is kinda hairy, probs needs refactoring in us-forms-system
