### ISSUE TITLE
Translate alpha.austin.gov's privacy page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1496]
Privacy page lives here: https://joplin.herokuapp.com/admin/pages/37/edit/

**Comment by ablangworthy27** [comment]
Sent for translation!

**Comment by ablangworthy27** [comment]
Just received this back from translators and requested invoice

**Comment by desigonz** [comment]
@ablangworthy27 Wow that was fast! Let me know if you need help with the review process or publishing on Joplin.

**Comment by ablangworthy27** [comment]
This is done
