### ISSUE TITLE
Bug: map on review page X button

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1497]
On the review page map, the X button to clear the address field is misaligned (too far to the left).

**URL tested:** https://forms.austintexas.io/police-complain/review-and-submit

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-complain%2Freview-and-submit&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-complain/review-and-submit) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 72.0 |
| Operating System | OS X Mojave |
| Resolution | 1512x946 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/ce97d7e8fa270bec0835441c5c9d775cfdd3fd65/macmo_chrome_72.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/ce97d7e8fa270bec0835441c5c9d775cfdd3fd65/macmo_chrome_72.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-complain%2Freview-and-submit&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-complain/review-and-submit) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
This is def related to the frustrating way buttons are currently handled on the review page.
