### ISSUE TITLE
Police Oversight review button tweaks

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1499]
Sentence case capitalization on the following buttons:
- [x] Add Another (button) → Add another (lowercase) (on [Tell us about the officer(s)](https://forms.austintexas.io/police-thank/officer-details)
- [x] Add another (button) -> Add another (lowercase) [Tell us about any witnesses](https://forms.austintexas.io/police-oversight/complaint/witness-details))
- [x] Update Page (button) → Update page (lowercase) 4x (on [Review your answers before submitting](https://forms.austintexas.io/police-thank/review-and-submit))

<img width="400" alt="Screen Shot 2019-03-15 at 3 57 20 PM" src="https://user-images.githubusercontent.com/1463708/54462232-faa15e00-473c-11e9-9922-711b0d3ef1f0.png">

![screencapture-forms-austintexas-io-police-thank-review-and-submit-2019-03-15-16_01_13](https://user-images.githubusercontent.com/1463708/54462248-0a20a700-473d-11e9-8e43-c3271a7647b9.png)

**Comment by annieszot** [comment]
I'm doing QA 
Mobile:
- [ ] iPhone: Safari 12.0
  - [ ] English
  - [ ] Spanish 
- [ ] Android: Chrome 71.0
  - [ ] English
  - [ ] Spanish 

Desktop:
- [ ] Windows 10: Chrome 71.0
  - [ ] English
  - [ ] Spanish
- [ ] Windows 7: Chrome 71.0;
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 7: Internet Explorer 11
  - [ ] English
  - [ ] Spanish 
- [ ] MacOS 10.14: Chrome 71.0
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Edge 17.17; 
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Internet Explorer 11
  - [ ] English
  - [ ] Spanish

**Comment by annieszot** [comment]
@easherma Does "Update" need to be translated into Spanish?

**Comment by easherma** [comment]
Ahh good catch, I do think the translations needs to be tweaked.

**Comment by annieszot** [comment]
@easherma Thanks! Nevermind on adding a button for "Add another witness". It's there :) I'll update the comment with a screenshot.

**Comment by annieszot** [comment]
Checks out except for #1589 
Closing issue
