### ISSUE TITLE
Police Oversight form: Review new date time picker!

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1501]
Before @Niicck implements the new WCAG-compliant date & time picker on the thanks form, we need design eyes on it:

https://forms.austintexas.io/police-complain/what-happened

![Screen Shot 2019-03-15 at 4.44.47 PM.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/c9397756-2ec1-4139-91a9-c8a62328927e)

**Comment by toribr** [comment]
Need to research how screen reader handle am/pm but good for now.
