### ISSUE TITLE
Complaint form translation fixes

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1502]
*Intro page*
"Call the Office of Police Oversight at (512) 972-2676. We’d be happy to speak with you." needs to be split into two entries on translations.json:
- [x] Call the Office of Police Oversight at 
- [x] We’d be happy to speak with you.

*Share your photos page*
- [x] Upload any evidence that you have (video files, audio files, photos, police report, hospital record, etc.).

*Witnesses page*
- [x] Phone
- [x] Witness

*Confirmation page*
- [x] "Your email" --> "Su dirección de correo electrónico"

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/6af44b6d-5473-43ba-bcc7-5105a43cacf6)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/7b3cee46-e61a-42f9-aab2-825e5dd2067d)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/977bfcf2-a9d7-49cc-8b6c-9701967f9f4c)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/3079f785-ce36-42bb-82d4-afd40b99849c)

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/1c7cd14e-7d17-4529-b619-481327c51780)

**Comment by desigonz** [comment]
@amenity [PR #72](https://github.com/cityofaustin/officer-complaint-form/pull/72) with a handful of complaint form translation fixes 
https://github.com/cityofaustin/officer-complaint-form/pull/72

**Comment by oliver2g** [comment]
Done for complaint form. Needs to be done for thank-you form (new issue).
