### ISSUE TITLE
Police Oversight form: Translate <title> on both forms

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1504]
Browser tab text should match page title.
<img width="790" alt="Screen Shot 2019-03-15 at 5 05 50 PM" src="https://user-images.githubusercontent.com/1463708/54464961-e2364100-4746-11e9-9450-106e3dc01981.png">

**Comment by oliver2g** [comment]
@Niicck and @easherma any idea on who this should be assigned to?

**Comment by easherma** [comment]
@sergiogcx shouldn't translations.json translate these titles already? Maybe it's an issue with being case sensitive?
https://github.com/cityofaustin/officer-complaint-form/blob/16cdee9308b1d3fdeeb595cdc758bbe2bf68899d/locale/translations.json#L224

https://github.com/cityofaustin/officer-complaint-form/blob/16cdee9308b1d3fdeeb595cdc758bbe2bf68899d/js/config/form.js#L17

**Comment by sergiogcx** [comment]
Well, the index.html file does not get translated at all. I will have to create a translations file for the index file and make index.html translation part of the pipeline in travis.

**Comment by sergiogcx** [comment]
I will take care of this, I will need 2-3 hours to make this happen for the two forms.

![Screen Shot 2019-03-25 at 3.42.14 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/9490923a-ace2-4b3f-9589-39742af1308c)

**Comment by sergiogcx** [comment]
This has now been addressed in these PRs:

Complaint:
https://github.com/cityofaustin/officer-complaint-form/pull/95
https://github.com/cityofaustin/officer-thank-form/pull/30

Working models:
https://opo.austintexas.io/policia-queja/
https://opo.austintexas.io/policia-agradezca/

**Comment by sergiogcx** [comment]
Both have been tested and merged to master.

**Comment by desigonz** [comment]
@sergiogcx This looks great, closing it.
