### ISSUE TITLE
Padding on body text

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1506]
See the paragraph starting "Do you have additional information" in the screenshot below. I expect this text to span across the whole width. 

**URL tested:** https://forms.austintexas.io/police-complain/share-evidence

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-complain%2Fshare-evidence&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-complain/share-evidence) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 72.0 |
| Operating System | OS X Mojave |
| Resolution | 1438x946 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/1d5e578f3c91112ef88c2188e3799a28368fa14f/macmo_chrome_72.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/1d5e578f3c91112ef88c2188e3799a28368fa14f/macmo_chrome_72.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-complain%2Fshare-evidence&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-complain/share-evidence) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
I think this might be handled by other commits but I'll need to check.

**Comment by sergiogcx** [comment]
Ah, yes I fixed this issue a few days back.

**Comment by sergiogcx** [comment]
Fixed in commit:

https://github.com/cityofaustin/officer-complaint-form/commit/e54bde4498489dbbb551606f688a1dd9d556cfef#diff-4e91ba43e81e8bd966fb3b26900e1fde

**Comment by desigonz** [comment]
Looks beautiful! Closing this one.
