### ISSUE TITLE
New copy for new date and time fields

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1508]
Looks like we have placeholder copy for the new date and time fields. (This might be multiple issues.)

- [x] Content point person to review language, and then...
- [x] Translate to Spanish
- [x] Update in date/time field code
- [x] Update in translations.json

**URL tested:** https://forms.austintexas.io/policia-queja/introduccion

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Fintroduccion&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/introduccion) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 72.0 |
| Operating System | OS X Mojave |
| Resolution | 1438x946 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/4f7dbffac58abaa67c39bb976aa5a36a78a3d379/macmo_chrome_72.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/4f7dbffac58abaa67c39bb976aa5a36a78a3d379/macmo_chrome_72.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Fintroduccion&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/introduccion) to reproduce the issue on Browserstack**

**Comment by sergiogcx** [comment]
All translated, pushed to master. Ready for review or QA

**Comment by oliver2g** [comment]
I'm doing QA on this.

Mobile:
- [ ] iPhone: Safari 12.0
- [ ] Android: Chrome 71.0

Desktop:
- [ ] Windows 10: Chrome 71.0
- [ ] Windows 7: Chrome 71.0; 
  - [ ] Internet Explorer 11
- [ ] MacOS 10.14: Chrome 71.0
- [ ] Windows 10: Edge 17.17; 
  - [ ] Internet Explorer 11

**Comment by Niicck** [comment]
Copy looks good. Closing.
