### ISSUE TITLE
Date field format for Spanish

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1509]
Dates in Spanish are formatted date, month, year (not month, date, year). 😬

**URL tested:** https://forms.austintexas.io/policia-queja/que-sucedio

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Fque-sucedio&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/que-sucedio) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 72.0 |
| Operating System | OS X Mojave |
| Resolution | 1438x946 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/224e0d1139fb5402ab463bc4968f2f3e6164f1af/macmo_chrome_72.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/224e0d1139fb5402ab463bc4968f2f3e6164f1af/macmo_chrome_72.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Fque-sucedio&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/que-sucedio) to reproduce the issue on Browserstack**

**Comment by sergiogcx** [comment]
Could we research more into this? Date format is not based on language, it is based by country. 

"Two U.S. standards mandate the use of year-month-day formats: ANSI INCITS 30-1997 (R2008); and NIST FIPS PUB 4-2 (FIPS PUB 4-2 withdrawn in United States 2008-09-02[9]),"

https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_United_States

Also, currently the backend does not parse dates, if we implement this, we also have to change the way emails are formatted, which means I have to write the parsing method so it can interpret english dates and spanish dates. 

Also the email templates have to be modified for the two separate cases, one for english and another for spanish emails.

Also, if the backend is going to parse dates, then I would prefer if the form provides the standard ISO format (yyyy-mm-dd).

**Comment by desigonz** [comment]
@sergiogcx @Niicck @kriskristin This is something we could test for in Spanish user testing. Spanish uses date-month-year format, but our user base might be accustomed to using month-date-year in online contexts.

Nielsen Norman Group on the matter: "If your site caters to international users, your date format should be clear and understandable. Date-entry fields are culture dependent, and can cause major problems for those users who are accustomed to a different format" ([source](https://www.nngroup.com/articles/date-input/)). Adding labels for month and date are super helpful in differentiating, which we've already done.

**Comment by desigonz** [comment]
Another best practice: spelling out months (January, February; enero, febrero, etc.) rather than just using numbers ([long interesting thread here](https://ux.stackexchange.com/questions/16095/how-to-display-date-and-time)).

**Comment by oliver2g** [comment]
Echoing a slack post from @Niicck  
"According to Sergio’s comment on the issue, best practice is to have date format is specified by county, not by language. Desi’s quote from the Nielsen Norman Group says the same thing: “If your site caters to international users, your date format should be clear and understandable.” Our form does not cater to international users, our form caters to users in Austin TX. I’m not sure if our Spanish speaking users living in Austin are more familiar with dd-mm-yyyy over mm-dd-yyyy format. I wouldn’t assume that our users require a different format without evidence from them. That’s my 2 cents, if any of this is my call, which it maybe isn’t.

From a development standpoint it would actually be kind of a big change. We currently don’t have the ability to change form functionality based on language. It’s a tradeoff between development time vs. benefit to users."

I don't think we should make this change unless we get issues with it in production or user testing. Moving to the backlog for now.
