### ISSUE TITLE
Lowercase AM and PM in date/time field

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1511]
Our editorial style is to lowercase AM and PM.

**URL tested:** https://forms.austintexas.io/policia-queja/que-sucedio

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Fque-sucedio&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/que-sucedio) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 72.0 |
| Operating System | OS X Mojave |
| Resolution | 1438x946 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/5d792ede0863226da45e53a571cbf6e7b026c828/macmo_chrome_72.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/5d792ede0863226da45e53a571cbf6e7b026c828/macmo_chrome_72.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Fque-sucedio&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/que-sucedio) to reproduce the issue on Browserstack**

**Comment by amenity** [comment]
LGTM
