### ISSUE TITLE
Bug: Date field lets me enter date in the future

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1512]
While the calendar picker doesn't let me choose a date in the future, I can write in a date in the future. (Not sure if that's actually a problem.) 

**URL tested:** https://forms.austintexas.io/policia-queja/que-sucedio

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Fque-sucedio&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/que-sucedio) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 72.0 |
| Operating System | OS X Mojave |
| Resolution | 1438x946 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/8a61a6dee3b1ba95036eb2758bc7fb965765aa8c/macmo_chrome_72.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/8a61a6dee3b1ba95036eb2758bc7fb965765aa8c/macmo_chrome_72.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Fque-sucedio&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/que-sucedio) to reproduce the issue on Browserstack**

**Comment by Niicck** [comment]
Duplicated by https://github.com/cityofaustin/techstack/issues/1086
