### ISSUE TITLE
Complaint confirmation email edits

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1515]
- [x] capitalization thing happening despite copy edits in [language.yaml](https://github.com/cityofaustin/form-service-api/blob/master/templates/email/officepoliceoversight/language.yaml)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/c8cc4fe7-00e2-48d8-9480-35b60c60b965)

- [x] Change "Witness(es)" heading to "[Tell us about any witnesses](https://github.com/cityofaustin/form-service-api/blob/d9d498314cfcc7ec606e2d8d20fd4c7c6c8ec906/templates/email/officepoliceoversight/language.yaml#L117)"
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/90f19e1f-788c-4bd4-a477-6a489cbfb345)

- [x] Change "Demographic information" heading to "Tell us about you"
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/d302238d-7393-41a2-8d6e-bb0d5bebcc27)

- [x] Spanish email subject should be "Hemos recibido su queja." to be consistent with English emails
![opo-email-subject-spanish.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/10cf0ee9-a6bc-46b1-a9e8-bcdb0cca6edb)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/11de35d5-55b7-4634-a81d-00f43f121ddc)

**Comment by sergiogcx** [comment]
This is the PR:
https://github.com/cityofaustin/form-service-api/pull/21

**THIS ISSUE CAN BE TESTED THROUGH THE STAGING FORM**

This can also be seen here:
English:
https://6jm8rnjkxf.execute-api.us-east-1.amazonaws.com/staging/email-template
Spanish:
https://6jm8rnjkxf.execute-api.us-east-1.amazonaws.com/staging/email-template?lang=es

**Comment by easherma** [comment]
I'm doing QA: 
Mobile:
- [ ] iPhone: Safari 12 (Or test on 11 for greater device compatibility?)
  - [ ] English
  - [ ] Spanish 
- [ ] Android: Chrome 71.0
  - [ ] English
  - [ ] Spanish 

Desktop:
- [ ] Windows 10: Chrome 71.0
  - [ ] English
  - [ ] Spanish
- [ ] Windows 7: Chrome 71.0;
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 7: Internet Explorer 11
  - [ ] English
  - [ ] Spanish 
- [ ] MacOS 10.14: Chrome 71.0
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Edge 17.17; 
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Internet Explorer 11
  - [ ] English
  - [ ] Spanish

**Comment by easherma** [comment]
Tested IE 11 and mobile, sent myself an email...it all looks good. This is a very minor change, so I don't see a need for further QA. LGTM!
