### ISSUE TITLE
Add workflow and governance to Digital Services Style Guide 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1520]
Per https://gathercontent.com/blog/a-four-step-road-map-for-good-content-governance

**Comment by annieszot** [comment]
@LauraTrujillo How do I edit the Digital Services Style Guide?

**Comment by LauraTrujillo** [comment]
@annieszot, unfortunately, we can't have an account for everyone (based on the basic account we have) So I can either make the edits for you, or swap writer accounts with @srigdon. Let me know what works best for you!

**Comment by annieszot** [comment]
@LauraTrujillo Thanks and no problem! I'll prep the content and pass it off as we do in our review editorial process, then you can choose what to publish?

**Comment by annieszot** [comment]
@LauraTrujillo Draft additions: 
In the Digital Styles Guide under "Create quality content": 
Who's your content crew? 
Documenting content governance clarifies accountability and responsibility but may involve a wide net of writers. Along with content owners and content managers, pinpoint someone who provides strategy, or who charts the course, for the content, someone who makes sure implementation happens, and someone who strengthens the content by keeping users' needs and behaviors clear and addressed. 

Workflows
How is content planned, produced, published and governed? 
Design workflows to show how your content "flows" through your organization while highlighting research, content creation, testing, evaluation, and training. Define and gain agreement on content ownership and roles. 
Example flow outline:
Plan -> Create -> Revise -> Approve -> Test -> Publish 
Follow these stages while considering:
What tasks are required at each stage?
Who should be responsible or be involved in each stage including residents?
How long does each stage take?
What tools will support each stage? 
----
Revisions welcome, and I'm happy to test this with our content team before we finalize.

**Comment by LauraTrujillo** [comment]
@annieszot I added your suggestions to the Style Guide. We can continue to refine them as we go along. Thanks!
