### ISSUE TITLE
Change numbers in copy to be digits not spelled out

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1524]
## File a complaint- digital form
*We have received your complaint*
- [x] Your case number should read "Your confirmation number"
- [x] Add parentheticals to phone number per our style: (512)...
- [x] Use numerals (aka digits) for two to four: 2 to 4
- [x] Update confirmation paragraph to read: 
- You can email us at policeoversight@austintexas.gov or call us at (512) 972-2676 with your confirmation number to find where your complaint is in this process.

If you provided your contact information, a staff person from the Office of Police Oversight will contact you within 2 to 4 business days, and you will receive an email with a copy of your complaint and a confirmation number.

**Comment by easherma** [comment]
should be done, pushed to master

**Comment by annieszot** [comment]
![Screen Shot 2019-03-23 at 12 43 56 PM](https://user-images.githubusercontent.com/46934140/54869627-6604b480-4d69-11e9-8365-87e1026a9d04.png)

**Comment by annieszot** [comment]
- [x] Your case number should read "Your confirmation number"
 - [x] Add parentheticals to phone number per our style: (512)...
 - [x] Use numerals (aka digits) for two to four: 2 to 4
 - [x] Update confirmation paragraph to read:

You can email us at policeoversight@austintexas.gov or call us at (512) 972-2676 with your confirmation number to find where your complaint is in this process.
If you provided your contact information, a staff person from the Office of Police Oversight will contact you within 2 to 4 business days, and you will receive an email with a copy of your complaint and a confirmation number.
