### ISSUE TITLE
## Confirmation email- Complaint

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1525]
## Confirmation email- Complaint
- [x] Add parentheticals to phone number per our style: (512)...
- [x] Use numerals (aka digits) for two to four: 2 to 4
- [x] "Complaint investigative process" should be in sentence case
- [x] "Complaint investigative process" should be "Complaint investigation process"

_Originally posted by @LauraTrujillo in https://github.com/cityofaustin/techstack/issues/1342#issuecomment-470259248_

**Comment by sergiogcx** [comment]
This is the PR:
https://github.com/cityofaustin/form-service-api/pull/21

**THIS ISSUE CAN BE TESTED THROUGH THE STAGING FORM**

This can also be seen here:
English:
https://6jm8rnjkxf.execute-api.us-east-1.amazonaws.com/staging/email-template
Spanish:
https://6jm8rnjkxf.execute-api.us-east-1.amazonaws.com/staging/email-template?lang=es

**Comment by LauraTrujillo** [comment]
Looks good!
