### ISSUE TITLE
Medium Post one pager 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1527]
So, you wanna write a Medium Post? 
https://docs.google.com/document/d/1KMFASGEiuEkWKdo4jeOmHZOfc02LKVsPiapxvD3IpkU/edit

- [x] drafted
- [x] shared with Laura 
- [x] organized in folder
- [x] Link to folder location

**Comment by annieszot** [comment]
@LauraTrujillo Medium Post one pager 
https://docs.google.com/document/d/1KMFASGEiuEkWKdo4jeOmHZOfc02LKVsPiapxvD3IpkU/edit
Low priority - requested deadline for feedback April 1

**Comment by LauraTrujillo** [comment]
@annieszot- reviewed! Great work!

**Comment by annieszot** [comment]
@LauraTrujillo Thanks so much! 
Here's the folder link https://drive.google.com/open?id=15hyuOVj6zjcF1F2TzHh0XtQ7oJsNhaxe
Closing

**Comment by desigonz** [comment]
I'm late to the game on this, but I love it. Added some edits.

Thoughts: 
- Do we have a target reading level we'd like to achieve on Civiqueso? 
- What kind of image guidelines can we provide to help authors select relevant and quality images?

**Comment by annieszot** [comment]
Excellent thoughts @desigonz 
I copy and pasted the community gardens and opo medium posts into the Hemingway app. Articles resulted in a grade 12 reading level. :/ @LauraTrujillo's latest civiqueso post was at a grade 8 reading level. Thanks for the reminder @desigonz to keep our reading level content creation consistent 👍 

Let's aim for grade 8 reading level? 

Image guidelines 
Preferably inhouse, project photos.
Tips from Medium, how to add, delete, position, and caption a photo
https://help.medium.com/hc/en-us/articles/215679797-Images
Adding these things now

**Comment by desigonz** [comment]
Ahhh caption styles! So important! Might also want to think about attribution and copyright (use public domain image, etc). Could be nice to try to go for active photos—things where people are interacting, etc. No stock imagery lol.

Reading level-wise—we could probably raise it to grade 9 or 10, considering our audience, but the more readable the better!

**Comment by annieszot** [comment]
Gotchya! Captions, attributions, and copyright added to draft. Revisions welcomed

**Comment by desigonz** [comment]
Ohh oh another thing! We should make sure to author and add alt text for all images. (Haven't used Medium in a while so not sure if they support this. But it's a11y best practices.)

**Comment by annieszot** [comment]
Yes yes! Thank you! Will need a little more time to investigate/integrate. 
Will re-open issue and unassign Laura.

**Comment by annieszot** [comment]
@desigonz At your convenience, can you please take a look at my additions (re: alt text) before I close this? 
@srigdon At your convenience, finish the section on publicizing? 

Requested due date Friday, April 5.

**Comment by desigonz** [comment]
Hey @annieszot! Thanks for revising. Looks like you added instructions on how to add alt text to Google docs, but ultimately that won't end up on Medium. Just did some quick research and it looks like Medium doesn't have the capability (which is a huge huge shame! shaking my head about their shoddy accessibility efforts). They do have a caption field, however; I'd recommend adding something to the effect of "write a short, snappy, and descriptive caption" instead.

**Comment by srigdon** [comment]
@annieszot, I finished the section on publicizing. Thanks for creating this document!

**Comment by annieszot** [comment]
@srigdon Woohoo! Thanks so much for your contributions. Closing!
