### ISSUE TITLE
Fix whatever is causing department page to not be bigger than full width on mobile

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1531]
<img width="487" alt="Screen Shot 2019-03-20 at 1 14 47 AM" src="https://user-images.githubusercontent.com/6384156/54662911-97e9f280-4aad-11e9-94ab-9476a3164a82.png">

**Comment by annieszot** [comment]
Browser tested. All devices pass with department page full width of the screen
iPhone XR, XS max, XS: Safari 12.0
Android Samsung Galaxy A8, Samsung Galaxy Note 8, Pixel XL and Pixel: Chrome 71.0
![Screen Shot 2019-03-23 at 11 35 41 AM](https://user-images.githubusercontent.com/46934140/54868970-63ea2800-4d60-11e9-879c-0edba06d055d.png)
![Screen Shot 2019-03-23 at 11 36 53 AM](https://user-images.githubusercontent.com/46934140/54868971-6482be80-4d60-11e9-8b19-62a32d3b0678.png)
Closing
