### ISSUE TITLE
Make hours on contacts look better

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1532]
<img width="421" alt="Screen Shot 2019-03-20 at 1 16 09 AM" src="https://user-images.githubusercontent.com/6384156/54662970-cbc51800-4aad-11e9-8097-fb57185cafa3.png">
<img width="722" alt="Screen Shot 2019-03-20 at 1 16 58 AM" src="https://user-images.githubusercontent.com/6384156/54663008-eac3aa00-4aad-11e9-9bed-b413c9bd8f79.png">
<img width="1152" alt="Screen Shot 2019-03-20 at 1 17 13 AM" src="https://user-images.githubusercontent.com/6384156/54663017-ed260400-4aad-11e9-8fc7-1a3f75a72b95.png">

**Comment by annieszot** [comment]
Besides different hours listed (#1580) all contact hours "look better" 
Browser testing complete
- [ ] iPhone XR, XS max, XS: Safari 12.0
- [ ] Android Samsung Galaxy A8, Samsung Galaxy Note 8, Pixel XL, and Pixel: Chrome 71.0

Desktop:
- [ ] Windows 10: Chrome 71.0
- [ ] Windows 7: Chrome 71.0
- [ ] MacOS 10.14: Chrome 71.0
- [ ] Windows 10: Edge 17.17
![Screen Shot 2019-03-23 at 12 12 53 PM](https://user-images.githubusercontent.com/46934140/54869440-4fa92980-4d66-11e9-9dff-da1e9ec04b94.png)
![Screen Shot 2019-03-23 at 12 13 41 PM](https://user-images.githubusercontent.com/46934140/54869441-4fa92980-4d66-11e9-9924-a3500629cc82.png)
![Screen Shot 2019-03-23 at 12 17 52 PM](https://user-images.githubusercontent.com/46934140/54869442-4fa92980-4d66-11e9-8795-b9fbd1264e4a.png)
