### ISSUE TITLE
Fix overlapping heading text on department page in Spanish on mobile

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1533]
<img width="518" alt="Screen Shot 2019-03-20 at 1 19 14 AM" src="https://user-images.githubusercontent.com/6384156/54663187-632a6b00-4aae-11e9-99f8-c1a1beb4df88.png">

**Comment by briaguya** [comment]
it appears as if a previous heading fix took care of this

**Comment by annieszot** [comment]
Browser tested and good to go for all the following mobile platforms/devices: 
iPhone XR, XS max, XS: Safari 12.0 
Android Samsung Galaxy A8, Samsung Galaxy Note 8, Pixel XL and Pixel Chrome 71.0
![Screen Shot 2019-03-23 at 11 21 40 AM](https://user-images.githubusercontent.com/46934140/54868839-f4c00400-4d5e-11e9-95bf-dd866bd8bd86.png)
![Screen Shot 2019-03-23 at 11 24 19 AM](https://user-images.githubusercontent.com/46934140/54868840-f4c00400-4d5e-11e9-97a8-808877b95b02.png)
Closing 
@briaguya more browser testing needed on additional devices? If so, which ones?
