### ISSUE TITLE
Make mobile footer look better

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1535]
<img width="510" alt="Screen Shot 2019-03-20 at 1 32 31 AM" src="https://user-images.githubusercontent.com/6384156/54663684-1c3d7500-4ab0-11e9-8821-46cbdc438d70.png">

**Comment by annieszot** [comment]
Mobile footer "looks better" 
Browser testing complete on mobile: 
- [ ] iPhone XR, XS Max, XS: Safari 12.0
- [ ] Android Samsung Galaxy A8, Samsung Galaxy Note 8, Picel XL, and Pixel: Chrome 71.0
![Screen Shot 2019-03-23 at 12 26 25 PM](https://user-images.githubusercontent.com/46934140/54869512-7fa4fc80-4d67-11e9-8344-c007538ce333.png)
Closing
