### ISSUE TITLE
Make information page heading match designs

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1536]
On mobile it seems to have a ton of padding:
<img width="478" alt="Screen Shot 2019-03-20 at 1 33 56 AM" src="https://user-images.githubusercontent.com/6384156/54663744-4e4ed700-4ab0-11e9-8512-12cdb7117465.png">

On desktop it seems to be really far to the left:
<img width="1264" alt="Screen Shot 2019-03-20 at 1 35 28 AM" src="https://user-images.githubusercontent.com/6384156/54663808-763e3a80-4ab0-11e9-818d-2ae4ba4c868d.png">

**Comment by annieszot** [comment]
Browser tested, progress made @briaguya 
iPhone XR, XS max, XS: Safari 12.0
Android Samsung Galaxy A8, Samsung Galaxy Note 8, Pixel XL, Pixel: Chrome 71.0
![Screen Shot 2019-03-23 at 11 47 17 AM](https://user-images.githubusercontent.com/46934140/54869172-ed025e80-4d62-11e9-8c9e-747f8ed0df0e.png)
Desktop testing - all reformatted but bug in Windows 10 
Tested/approved for Windows 7: Chrome 71.0, MacOS 10.14: Chrome 71.0 and Windows 10: Edge 17.17 
![Screen Shot 2019-03-23 at 11 53 42 AM](https://user-images.githubusercontent.com/46934140/54869197-479bba80-4d63-11e9-80e1-9488918179a2.png)
Bug on Windows 10 
![Screen Shot 2019-03-23 at 11 52 45 AM](https://user-images.githubusercontent.com/46934140/54869210-68fca680-4d63-11e9-98be-27ac2f4e40b0.png)

**Comment by annieszot** [comment]
Closing --> new bug #1581
