### ISSUE TITLE
Fix OPO breadcrumb in Spanish, it's giant on mobile

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1537]
<img width="361" alt="Screen Shot 2019-03-20 at 5 16 05 AM" src="https://user-images.githubusercontent.com/6384156/54676706-481c2300-4acf-11e9-966b-a643479e1b19.png">

**Comment by pibemillo** [comment]
https://github.com/cityofaustin/janis/pull/343

URL for PR to QA: https://janis-staging-pr-343.herokuapp.com/police-oversight/complaint-investigation-process

**Comment by chasechenevert** [comment]
See #1203 for the larger sub-navigational elements that will apply to this as we merge OPO into Alpha. We can discuss this during design/dev sync or sooner--just let us know.

Differences between OPO banner and Janis 2 sub-nav:
- Title case
- Light-blue background

CC: @toribr
