### ISSUE TITLE
Service page to guide the user through the garden permit process (get a garden permit)

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1549]
Deliverable in Community Garden project scope doc 
https://docs.google.com/document/d/1NVNrS0FIfef1G5dxM8-u7Bvs7F_j3S5gQJjkcavpmWI/edit#
 - [x] IA linked (draft) (Plan)
 - [x] Governance/Workflow established including weigh-in from Design,Dev (Plan)
 - [x] Draft (Create)
 - [ ] Editors assigned (round 1) (Revise)
 - [ ] Feedback received, incorporated
 - [ ] Editors assigned final round
 - [ ] Final revisions, approval from Service Design Lab PM (Approve)
 - [ ] Stakeholders informed, approved (Approve)
 ~-[ ] Users defined (Test)~
 - [ ] User testing scheduled
 - [ ] User testing conducted
 - [ ] User testing changes incorporated
 - [ ] Draft on joplin
~- [ ] Authors trained (Funshop) - also for service pages?~ 
 - [ ] Content owners identified, commited
 - [ ] Published on joplin, live on alpha.austin.gov

**Comment by annieszot** [comment]
Draft https://docs.google.com/document/d/15eMRnayTCVNS4qr3_MUVhK9nMJhS79C7cQMkLAD4O1A/edit

**Comment by oliver2g** [comment]
@annieszot there are a lot of tasks in this issue's checklist--probably spanning across multiple sprints. it might be a good idea to turn this issue into an epic and add spread out individual issues across sprints. same for #1545

**Comment by annieszot** [comment]
@oliver2g Issue converted into epic #1986
