### ISSUE TITLE
Austin.gov progress page

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#155]
Currently, we point site vistors to projects.austintexas.io for more info. We've talked about having some type of this information visible on a page within austin.gov itself. This might be a different content type, maybe not.

cc/ @cthibaultatx

Aha! Link: https://desi1.aha.io/features/RT-343

**Comment by cthibaultatx** [comment]
My only note here is that, as much as I'd like all of our projects site information to live on alpha, it may get in the way of residents getting straight to what they need and discovering related services. Vote to keep it on projects site until we have a separate but related url from alpha.

**Comment by mateoclarke** [comment]
I thought we wanted a timeline or view of progress similar to Indy. Are you saving we should stand up a separate subdomain for that? ex: https://shift.indy.gov/

**Comment by cthibaultatx** [comment]
Yes @mateoclarke related but separate
