### ISSUE TITLE
Increase size of address field in LocationPicker

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1554]
We want a longer address field. The styling should be simple: `.mapboxgl-ctrl-top-left` needs `min-width:75%`.

**Comment by annieszot** [comment]
I'm doing QA
Mobile:
- [ ] iPhone: Safari 12.0
  - [ ] English
  - [ ] Spanish 
- [ ] Android: Chrome 71.0
  - [ ] English
  - [ ] Spanish 

Desktop:
- [ ] Windows 10: Chrome 71.0
  - [ ] English
  - [ ] Spanish
- [ ] Windows 7: Chrome 71.0;
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 7: Internet Explorer 11
  - [ ] English
  - [ ] Spanish 
- [ ] MacOS 10.14: Chrome 71.0
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Edge 17.17; 
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Internet Explorer 11
  - [ ] English
  - [ ] Spanish

**Comment by Niicck** [comment]
@easherma Pushing back to Review; this design feature is still not implemented. You can see how it's supposed to work if you go into the inspector and manually enter `min-width: 75%` in the `mapboxgl-ctrl-top-left` class.

So working with mapbox is tricky. Adding `.mapboxgl-ctrl-top-left { min-width: 75%;}` explicitly to the usfs-components styling wouldn't resolve it. Because this class gets written later on by the mapbox instance itself. So the challenge of this issue is declaring the style in usfs-components (ideally), but having it propagate by the time it makes it to the form itself.

**Comment by easherma** [comment]
@Niicck hey this should be good to QA!

**Comment by Niicck** [comment]
QA'd. Approved. Looks good.
