### ISSUE TITLE
Review Page: improve styling on "Describe your Experience"

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1556]
"Describe your Experience" should be a header, and the description should be fullwidth and not right-justified.

**Comment by easherma** [comment]
Might be related to the redesign of the review page

**Comment by Niicck** [comment]
Before:
<img width="721" alt="Screen Shot 2019-03-24 at 8 12 55 PM" src="https://user-images.githubusercontent.com/14187277/54890076-a3eeff00-4e75-11e9-9f55-a764f0072d45.png">

After:
<img width="662" alt="Screen Shot 2019-03-24 at 8 12 43 PM" src="https://user-images.githubusercontent.com/14187277/54890081-ab160d00-4e75-11e9-978e-27f0f639c5cc.png">

Ooo, ahh.

This requires changes in 4 repos.

**Comment by easherma** [comment]
yaaayyy

I like this, but any chance you could make it require changes in more than 5 repos? ;-p

**Comment by easherma** [comment]
Moving this to Sprint 30, perhaps this and some content/translation updates will form the next OPO release.

**Comment by easherma** [comment]
@toribr at some point we should get some input from ya'll if this is worthwhile to ship

**Comment by toribr** [comment]
The styling for all of it needs to be improved, not just this one section. Meaning, right-justified text should not be used at all. Ever. Anywhere. (Unless numbers are involved and then it's correct) :) Does this change include only this section or all sections?

**Comment by oliver2g** [comment]
@Niicck was this ever pushed to master or prod? if not, i'll put it in the next small release and then close this issue. @toribr has another issue for redesigning the review page. #1540

**Comment by Niicck** [comment]
It has not been merged into prod. There was still a little more work that needed to be done on it. Maybe we can leave it alone for now until we decide to redo the review page.

**Comment by oliver2g** [comment]
Agreed. If there's still work, then it's going in the backlog for now. Thx!
