### ISSUE TITLE
Design variation of "this is a test site" for pages other than the homepage

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#156]
Some options:

- add a variation of the banner that is on the homepage
- a new type of notification banner
- dismissable modal or popup 
- dismissable sticky footer

cc/ @cthibaultatx

**Comment by amenity** [comment]
Will icebox until usability testing surfaces the need.

**Comment by cthibaultatx** [comment]
updated navigation and not needed any longer
