### ISSUE TITLE
Police Oversight: Spanish forms issues

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/techstack#1561]
Both forms in Spanish present translation issues, and broken functionality.

**Comment by sergiogcx** [comment]
I tested a way to make the form work by passing properties to the component specifically for the label. Webpack provides a clear pattern that can be safely altered.

![Screen Shot 2019-03-21 at 5.37.40 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/b765b074-5aa7-437a-acdc-67bdcfd9c64e)

![Screen Shot 2019-03-21 at 5.39.02 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/2b19da3e-f385-43ab-ae4c-cd813f029bba)

![Screen Shot 2019-03-21 at 6.14.29 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/cbe60f90-7802-4828-ab82-171193ecd105)

![Screen Shot 2019-03-21 at 6.16.47 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/8de523f2-4788-49d8-b0de-0964a80e6def)

**Comment by sergiogcx** [comment]
This has been fixed and addressed in both forms now.

**Comment by Niicck** [comment]
Cool, I'm glad that the label method worked! The only comment I have is that we should remember to update the lastest usfs-components version in its package.json

**Comment by oliver2g** [comment]
I'm doing QA on this.

Mobile:
- [ ] iPhone: Safari 12.0
- [ ] Android: Chrome 71.0

Desktop:
- [ ] Windows 10: Chrome 71.0
- [ ] Windows 7: Chrome 71.0; 
  - [ ] Internet Explorer 11
- [ ] MacOS 10.14: Chrome 71.0
- [ ] Windows 10: Edge 17.17; 
  - [ ] Internet Explorer 11

**Comment by easherma** [comment]
hey we checked this and it looks like a tasty tasty snack
