### ISSUE TITLE
Spanish Language Testing of OPO Form

### ISSUE THREAD

**Issue by kriskristin** [cityofaustin/techstack#1562]
Looking for 5-8 user tests

Let's focus on getting mobile tests if possible.

Be sure to take pictures!

We want to be sure we determine if a user starts the test in English, and then wants to switch to Spanish, should the warning be in English or Spanish. 

@toribr We can gather notes here

**Comment by oliver2g** [comment]
Testing is done. @desigonz and @kriskristin are doing synthesis.
