### ISSUE TITLE
Short term nav 

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1563]
How does it work?

https://github.com/cityofaustin/techstack/issues/1528

**Comment by toribr** [comment]
![image](https://user-images.githubusercontent.com/3790067/55341052-8caea380-546b-11e9-9861-37e34c7fa5c3.png)

Need to resolve:
-[ ] search
-[ ] department names
-[ ] Use "Healthcare & Prevention" as topic name for PH
-[ ] Change "Police reports & records" to "Police & law enforcement"?
-[ ] Some pages aren't directly parented by topics; discuss with dev if new UI is required for Joplin and/or how pages are connected to parent pages but won't show in topics (OPO supporting pages are good example)

**Comment by toribr** [comment]
![megaM](https://user-images.githubusercontent.com/3790067/55491917-f2ca3080-55fb-11e9-90bf-5118205db914.png)

**Comment by toribr** [comment]
![megaMenu](https://user-images.githubusercontent.com/3790067/55492546-ff9b5400-55fc-11e9-9397-28c00f1735b7.png)

**Comment by toribr** [comment]
![megaMenu](https://user-images.githubusercontent.com/3790067/55497857-d7fdb900-5607-11e9-9e2a-ed652f57842f.png)
Updated version which includes topic for OPO forms.

**Comment by chasechenevert** [comment]
Adding this in here to round out deliverables.

## Visual design: Short-term global navigation (MVP)
- We'll eventually have to reevaluate this once Alpha is populated with more content,.

### Dev specs: 
- Desktop: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/617c2999-53bd-43b6-baa8-28938737f83c/Navigation-Global-desktop/
- Mobile: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/d6c960cc-186e-421e-aace-ccdf356014ab/Navigation-Global-mobile/

<img width="1155" alt="Screen Shot 2019-04-10 at 12 39 52 PM" src="https://user-images.githubusercontent.com/7027270/55900901-d5faa380-5b8d-11e9-8364-06af3d19816c.png">
<img width="1367" alt="Screen Shot 2019-04-10 at 12 35 20 PM" src="https://user-images.githubusercontent.com/7027270/55900903-d6933a00-5b8d-11e9-884d-58d76f89b055.png">
