### ISSUE TITLE
OPO form current structure evaluation/improvements

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#1567]
Lets look at webpack, performance stats, see what sort of redundancies we can address
Also: 
refactor css
clean stuff up
update docs as needed
consolidate repos

**Comment by easherma** [comment]
We might split this up into individual issues l8R

**Comment by sergiogcx** [comment]
We made some great progress with performance, we have reduced the size of the payload to 1/3rd of the original size.

Production Test:
https://www.webpagetest.org/result/190326_RC_0298c6cfba14c5ac6078a6c513c7c2f7/

Staging: 
https://www.webpagetest.org/result/190326_26_f748ae067327b264414a1a9038ba5694/



Worst Performance:
https://www.webpagetest.org/result/190326_QG_2302e7a4c5c424b014906ac6ec67b3ff/

**Comment by easherma** [comment]
@sergiogcx lets keep performance notes in this issue: 
https://github.com/cityofaustin/techstack/issues/1000

**Comment by easherma** [comment]
We are shortly going to merge in some changes that get us down this path a bit; 

- [ ] moving usfs-components into appropriate folders in the us-forms-project:
  - [ ] proposed, tests pass
  - [ ] merged to staging 
  - [ ] pushed to prod
- [ ] merged schema blocks repo with chapters repo 
  - [ ] proposed, tests pass
  - [ ] merged to staging 
  - [ ] pushed to prod
- [ ] publish this version of us-forms-system to npm
- [ ] update docs

Did some initial exploring of a single repo for all forms, ran into some tweaks with the babel compile process that we'd need to address.

**Comment by oliver2g** [comment]
@easherma are you and @sergiogcx still working on this for Sprint 28?

**Comment by easherma** [comment]
Going to close this, as it's covered by two other issues: #1646 & #1632
