### ISSUE TITLE
Police Oversight: Change modal box to all English all spanish

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/techstack#1570]
Currently the modal box will show a message in English if the user clicks the English link, or Spanish if the user clicks the Spanish link.

- [x] The user should see both dialogs in English if the user is in the English version of the form.
- [x] The user should see both dialogs in Spanish if the user is in the Spanish version of the form.
- [x] Both Complaint and Thank-you forms.
ALSO:
- [x] Implement translations.
- [x] Remove buggy logic or fix (does not seem to work in the thank you form):

```
 // If the language is the same, then ignore the click...
    if (
        (linkRedirect + '/') == '/police-complain/' &&
        this.currentFormLanguage == 'opo_current_language_english'
    ) {
      console.log('Click ignored, same language');
      return;
    }
```

**Comment by sergiogcx** [comment]
Hmm, it doesn't work in the thank you form because of the string `'/police-complain/'`:

https://github.com/cityofaustin/officer-thank-form/blob/12a8f0a05bc570f100027bd327ed1cbb609e4dbb/app.js#L87


```
if (
        (linkRedirect + '/') == '/police-complain/' &&
        this.currentFormLanguage == 'opo_current_language_english'
    ) 
```

**Comment by sergiogcx** [comment]
Thank-you form, PR open:
https://github.com/cityofaustin/officer-thank-form/pull/24

**Comment by sergiogcx** [comment]
Complaint form, PR:
https://github.com/cityofaustin/officer-complaint-form/pull/83

**Comment by oliver2g** [comment]
I'm doing QA on this.

Mobile:
- [ ] iPhone: Safari 12.0
- [ ] Android: Chrome 71.0

Desktop:
- [ ] Windows 10: Chrome 71.0
- [ ] Windows 7: Chrome 71.0; 
  - [ ] Internet Explorer 11
- [ ] MacOS 10.14: Chrome 71.0
- [ ] Windows 10: Edge 17.17; 
  - [ ] Internet Explorer 11

**Comment by Niicck** [comment]
Verified. Closing.
