### ISSUE TITLE
Police Oversight: Create Modalbox

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/techstack#1571]
Create a modal box to prevent the user from loosing his/her data.

**Comment by sergiogcx** [comment]
Created this issue to keep track of QA and/or other requests.

**Comment by Niicck** [comment]
I'm doing QA on this.

**Comment by Niicck** [comment]
Also checking the thank you form.

Mobile:
- [ ] iPhone: Safari 11
  - [ ] English
  - [ ] Spanish 
- [ ] Android: Chrome 71.0
  - [ ] English
  - [ ] Spanish 

Desktop:
- [ ] Windows 10: Chrome 71.0
  - [ ] English
  - [ ] Spanish
- [ ] Windows 7: Chrome 71.0;
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 7: Internet Explorer 11
  - [ ] English
  - [ ] Spanish 
- [ ] MacOS 10.14: Chrome 71.0
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Edge 17.17; 
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Internet Explorer 11
  - [ ] English
  - [ ] Spanish

**Comment by Niicck** [comment]
Looks good.

**Comment by Niicck** [comment]
The Modal is good. Closing QA.
