### ISSUE TITLE
Remove all uses of "evidence" in labels and copy within form and email, English issue

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1573]
Form Review page header use : "Share your media" as header

Secondary copy under "yes": 
Upload any evidence that you have (video files, audio files, photos, police report, hospital record, etc.).
Change to:
"Upload any media that you have..."

**Comment by srigdon** [comment]
![Screen Shot 2019-03-22 at 2 23 02 PM](https://user-images.githubusercontent.com/5445796/54848403-31342700-4caf-11e9-924e-f9b66be7a4d6.png)

**Comment by easherma** [comment]
@sergiogcx we also use the word evidence in chapters and in the URL file path. should we also change those to 'media' instead of 'evidence'? I'd say yes to be consistent. LMK if we should have that as a separate issue

**Comment by annieszot** [comment]
I'm doing QA 
Mobile:
- [ ] iPhone: Safari 12 (Or test on 11 for greater device compatibility?)
  - [ ] English
  - [ ] Spanish 
- [ ] Android: Chrome 71.0
  - [ ] English
  - [ ] Spanish 

Desktop:
- [ ] Windows 10: Chrome 71.0
  - [ ] English
  - [ ] Spanish
- [ ] Windows 7: Chrome 71.0;
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 7: Internet Explorer 11
  - [ ] English
  - [ ] Spanish 
- [ ] MacOS 10.14: Chrome 71.0
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Edge 17.17; 
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Internet Explorer 11
  - [ ] English
  - [ ] Spanish

**Comment by annieszot** [comment]
Screenshots for iPhone
![Screen Shot 2019-03-25 at 5 47 38 PM](https://user-images.githubusercontent.com/46934140/54959431-12d86080-4f27-11e9-826a-fcae98e32193.png)
![Screen Shot 2019-03-25 at 5 48 58 PM](https://user-images.githubusercontent.com/46934140/54959432-1370f700-4f27-11e9-8b9f-16bec0af41c5.png)
![Screen Shot 2019-03-25 at 5 49 09 PM](https://user-images.githubusercontent.com/46934140/54959433-1370f700-4f27-11e9-9385-0520959e93b2.png)

**Comment by annieszot** [comment]
Good job! Closing
