### ISSUE TITLE
Location needs to be made required within form, and added to list of requirements on landing page

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1574]
![Screen Shot 2019-03-22 at 1.18.48 PM.png](https://images.zenhubusercontent.com/5a81e99a4b5806bc2bc6a146/b66c2393-b338-4e6f-8c98-5871417094a0)

• What happened
• Date and time
• Location

**Comment by srigdon** [comment]
For the Spanish form, Location = Ubicación

**Comment by easherma** [comment]
Should be fixed by
https://github.com/cityofaustin/officer-complaint-form/commit/9bf611f09c1cd92c4aa169ead45c1736135a13dc
in staging

**Comment by annieszot** [comment]
I'm doing QA 
Mobile:
- [ ] iPhone: Safari 12 (Or test on 11 for greater device compatibility?)
  - [ ] English
  - [ ] Spanish 
- [ ] Android: Chrome 71.0
  - [ ] English
  - [ ] Spanish 

Desktop:
- [ ] Windows 10: Chrome 71.0
  - [ ] English
  - [ ] Spanish
- [ ] Windows 7: Chrome 71.0;
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 7: Internet Explorer 11
  - [ ] English
  - [ ] Spanish 
- [ ] MacOS 10.14: Chrome 71.0
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Edge 17.17; 
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Internet Explorer 11
  - [ ] English
  - [ ] Spanish

**Comment by annieszot** [comment]
Screenshots for iPhone
![Screen Shot 2019-03-25 at 5 33 09 PM](https://user-images.githubusercontent.com/46934140/54959383-ea506680-4f26-11e9-9f9e-2bcdd6057935.png)
![Screen Shot 2019-03-25 at 5 33 24 PM](https://user-images.githubusercontent.com/46934140/54959384-ea506680-4f26-11e9-96b2-e8cb7647ddbb.png)
![Screen Shot 2019-03-25 at 5 36 07 PM](https://user-images.githubusercontent.com/46934140/54959385-ea506680-4f26-11e9-9fa9-9750d675decd.png)
![Screen Shot 2019-03-25 at 5 37 03 PM](https://user-images.githubusercontent.com/46934140/54959386-ea506680-4f26-11e9-8de6-441874730d4d.png)

**Comment by annieszot** [comment]
Good job! Closing
