### ISSUE TITLE
Improvements to Review - placeholder

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1575]
![Screen Shot 2019-03-22 at 2.00.14 PM.png](https://images.zenhubusercontent.com/5a81e99a4b5806bc2bc6a146/83649f27-364b-4d85-9787-7b720745d76a)

-[ ] where is title coming from?

**Comment by easherma** [comment]
Odd, we had a previous issue for this and I thought it was addressed.

**Comment by toribr** [comment]
It's for my reference, only!

**Comment by toribr** [comment]
Duplicate.
