### ISSUE TITLE
Remove all uses of "evidence" in labels and copy within form and email, Spanish issue 

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1576]
Form Review page header use TRANSLATION FOR: "Share your media" as header

Secondary copy under "yes":
Upload any evidence that you have (video files, audio files, photos, police report, hospital record, etc.).
TRANSLATE to:
"Upload any media that you have..."

**Comment by easherma** [comment]
Should be fixed by
https://github.com/cityofaustin/officer-complaint-form/commit/9bf611f09c1cd92c4aa169ead45c1736135a13dc,
in staging

**Comment by annieszot** [comment]
I'm doing QA: 
Mobile:
- [ ] iPhone: Safari 12 (Or test on 11 for greater device compatibility?)
  - [ ] English
  - [ ] Spanish 
- [ ] Android: Chrome 71.0
  - [ ] English
  - [ ] Spanish 

Desktop:
- [ ] Windows 10: Chrome 71.0
  - [ ] English
  - [ ] Spanish
- [ ] Windows 7: Chrome 71.0;
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 7: Internet Explorer 11
  - [ ] English
  - [ ] Spanish 
- [ ] MacOS 10.14: Chrome 71.0
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Edge 17.17; 
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Internet Explorer 11
  - [ ] English
  - [ ] Spanish

**Comment by annieszot** [comment]
Screenshots for iPhone: 
![Screen Shot 2019-03-25 at 5 42 42 PM](https://user-images.githubusercontent.com/46934140/54959281-875ecf80-4f26-11e9-822d-7b3e03c8ac31.png)
for Android:

**Comment by annieszot** [comment]
Good job! Closing
