### ISSUE TITLE
OPO complaint form: "Where were you" page lets you continue if you clear the location, even though location is required

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#1579]
![location-required-bug.gif](https://images.zenhubusercontent.com/5be0b7bea977220c77bd229b/c3c35f20-104c-495e-b09c-e58a1a06746c)

**Comment by easherma** [comment]
We should try to get #1644 to fix this as well

**Comment by annieszot** [comment]
Resolved on #1751 Will not let you proceed after clearing the address field.
