### ISSUE TITLE
Hours off when in different browsers

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1580]
QA in Browser Stack, discovered time zones off. And why list Friday first? 
I found this while investigating #1366

Browser Stack testing for https://janis-staging.herokuapp.com/police-oversight

For Mobile:
iPhone: Safari 12.0
Time zone bug for iPhone XS and XS Max. Not XR (fine) 
![Screen Shot 2019-03-22 at 4.46.19 PM.png](https://images.zenhubusercontent.com/5c4b52abd709c56fe9edad32/264c0d6a-a4d3-44d6-af6f-be6558373bbc)
Android: Chrome 71.0
Time zone bug for Android Samsung Galaxy A8, Google Pixel XL and Pixel 
![Screen Shot 2019-03-22 at 4.51.36 PM.png](https://images.zenhubusercontent.com/5c4b52abd709c56fe9edad32/2309af1b-3c99-4d00-af98-b0ca7ac8cb8e)
Time zone bug for Desktop: Windows 10: Chrome 71.0, Windows 10: Edge 17.17, and MacOS 10.14 Chrome 71.0
![Screen Shot 2019-03-22 at 4.57.36 PM.png](https://images.zenhubusercontent.com/5c4b52abd709c56fe9edad32/d16da624-1119-474e-8902-776014505a09)

**Expected behavior**
<Currect timezone>

**Screenshots**
<See above>

**Device**
<See above>

**Browser**
<See above>

**Comment by easherma** [comment]
So the Friday is first cause it shows whatever day of the week it is.

The time zone may be off because the virtual machine is running in a
different time zone, though I thought we had discussed not having the time
zone change

**Comment by Niicck** [comment]
Related to last issue: https://github.com/cityofaustin/techstack/issues/1331

**Comment by oliver2g** [comment]
@Niicck 1331 is closed, so is this something you're working on? what is the nature of the fix?

**Comment by Niicck** [comment]
1331 is closed, but it was not entirely fixed. I thought I fixed it, but I was wrong. There are additional code changes I need to make. This ticket is in progress.

**Comment by briaguya** [comment]
I'm very happy to know that whatever XR BrowserStack had on hand is in the central time zone somewhere.
