### ISSUE TITLE
Information Page centered, not left-indent while in Windows 10 Chrome 71.0

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1581]
**Formatting inconsistent with other design formats (left vs centered)**
<Browser tests showed windows 10 desktop (chrome 71.0)->

**https://janis-staging.herokuapp.com/police-oversight/how-we-store-and-use-your-data**

**To Reproduce**
<I found this while testing #1536>

![Screen Shot 2019-03-23 at 11.52.45 AM.png](https://images.zenhubusercontent.com/5c4b52abd709c56fe9edad32/2b5dbb58-212c-45d5-9caa-83eadb7d9723)

**Comment by briaguya** [comment]
![May-14-2019 22-20-17](https://user-images.githubusercontent.com/6384156/57746357-7ca6f800-7696-11e9-8e54-2004dc4ab18e.gif)

This is the behavior I'm seeing in Chrome on my mac, it's the same as I found in chrome on my windows machine.

**Comment by annieszot** [comment]
Ah! Good to close?
