### ISSUE TITLE
Spanish language typo in modal

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1587]
"No, proceda en Inglés" debe ser "No, proceda en Español."
Estás de acuerdo, @sergiogcx?

![Screen Shot 2019-03-25 at 1.07.45 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/ec32c9d6-ca34-43da-9eeb-eacca7b4ed38)

**Comment by sergiogcx** [comment]
This has been addressed in commit:
https://github.com/cityofaustin/officer-complaint-form/commit/76ab68d319111bc4483c6e56d6c9d11a9de096a3

Give a few minutes to build, also be sure to clear your browser's cache.

**Comment by sergiogcx** [comment]
![Screen Shot 2019-03-25 at 4.43.04 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/4ad3c9eb-705b-459b-aac8-9615791b333a)

**Comment by Niicck** [comment]
QA'd. It looks good.
