### ISSUE TITLE
Modal gets cut off in IE

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1588]
Modal should be centered instead of positioned off to the right.

|Property | Value|
|------------ | -------------|
| Browser | IE 11 |
| Operating System | Windows 10 |
| Resolution | 1078x734 |

![Screen Shot 2019-03-25 at 1.55.48 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/ffac81d4-1cc1-4a9b-ab94-9b37e1bb178f)

**Comment by sergiogcx** [comment]
Alright, it looks like I have found a solution:

Complaint form:
https://github.com/cityofaustin/officer-complaint-form/pull/84

Thank form:
https://github.com/cityofaustin/officer-thank-form/pull/26


Windows 10, IE 11, Full width:

![Screen Shot 2019-03-25 at 6.12.31 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/cf7bcd7a-d890-4f98-8135-d39b6ed36c8f)



Windows 10, IE 11, mobile-width:

![Screen Shot 2019-03-25 at 6.12.53 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/defee5b3-4240-43e6-8983-f3b129f096e1)




Windows 10, EDGE, full-width: (UNAFFECTED)

![Screen Shot 2019-03-25 at 6.14.47 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/705fba96-8d35-4c7e-8156-8ca8dcf7101e)

**Comment by sergiogcx** [comment]
I am going to go ahead and merge the changes, it is a harmless change.

**Comment by oliver2g** [comment]
Confirmed with @Niicck that this fix is verified.
