### ISSUE TITLE
Police Oversight: Complaint Form: Adjust translations for review page buttons.

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#1589]
@easherma Does "Update" need to be translated into Spanish?

_Originally posted by @annieszot in https://github.com/cityofaustin/techstack/issues/1499#issuecomment-476349303_

**Comment by annieszot** [comment]
Also "Add officer"

**Comment by sergiogcx** [comment]
Webpack should be renamed to web-wack:

![Screen Shot 2019-03-25 at 6.48.57 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/c7f8726f-73f5-4267-8a77-1ea4da6af9cb)

**Comment by sergiogcx** [comment]
I've got it:

![Screen Shot 2019-03-25 at 8.05.13 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/278a4e44-1881-4484-91f0-b7a54ce1b078)

![Screen Shot 2019-03-25 at 8.05.18 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/a9ffbba2-bc63-460a-bda6-88abff643f1f)

![Screen Shot 2019-03-25 at 8.05.28 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/006aef72-621d-43ef-ab31-9ec4274465bf)

![Screen Shot 2019-03-25 at 8.05.31 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/cbb26f2a-f403-40b5-a9d4-6ce29d9c6959)

**Comment by easherma** [comment]
@sergiogcx can you size this when you have a moment? also do you need a dev to review or should we move it to QA?
