### ISSUE TITLE
Update service page hours

### ISSUE THREAD

**Issue by COA-Matthews** [cityofaustin/techstack#159]
Correct hours for Recycle and Reuse Center:
![screen shot 2018-03-15 at 1 08 23 pm](https://user-images.githubusercontent.com/20911665/37482507-532829ec-2852-11e8-8fb4-1def41e27c9c.png)

Notes from Doug:
We don’t have correct facility hours on the service pages. I’m assuming that will be input on the CMS and not a dynamic piece of content…so something to add to the punchlist.

Day | Open - Close Hours
12:00 AM - 11:00 PM
12:00 AM - 11:00 PM
12:00 AM - 11:00 PM
12:00 AM - 11:00 PM
12:00 AM - 11:00 PM
12:00 AM - 11:00 PM
12:00 AM - 11:00 PM

**Comment by amenity** [comment]
@cthibaultatx
