### ISSUE TITLE
Review Form Update Button not translated

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1590]
"Update" is not translated into Spanish.

|Property | Value|
|------------ | -------------|
| Browser | Chrome 71 |
| Operating System | Windows 10 |
| Resolution | 1365x734 |

![Screen Shot 2019-03-25 at 3.12.10 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/301bd653-b2c2-4724-838d-34f155f3753c)

**Comment by easherma** [comment]
I already made an issue for this

**Comment by Niicck** [comment]
Duplicated by #1589
