### ISSUE TITLE
Focus flatpicker zooms to fit entire screen on Iphone

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#1591]
**Describe the bug**
When you tap on the calendar icon on mobile, it zooms to fit the whole screen, bad UX bad

**Device**
Iphone running Safari 12

**Comment by oliver2g** [comment]
@easherma is this an issue of it being ugly or an issue of the user getting blocked from continuing the process? If it's the latter, then I think this bug should be a P3.

**Comment by easherma** [comment]
Sorry I forgot about this one! I'd actually put it in even higher, it's pretty annoying on mobile.

**Comment by easherma** [comment]
I will take the case!

**Comment by easherma** [comment]
https://github.com/cityofaustin/us-forms-system/pull/17 fixed, tested android and iphone on browserstack

**Comment by annieszot** [comment]
I can help with QA on this tomorrow afternoon (Thursday 4/25).
@easherma "Flatpicker" is the calendar icon?
