### ISSUE TITLE
Police Oversight: Thank-you form: Update button not translating

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/techstack#1594]
Same issues from ticket #1589 but for thank you form.

**Comment by sergiogcx** [comment]
PR (merged): 
  https://github.com/cityofaustin/officer-thank-form/tree/1589-sg-otf-fixbuttontranslations

**Comment by sergiogcx** [comment]
PR (merged): 
  https://github.com/cityofaustin/officer-thank-form/tree/1589-sg-otf-fixbuttontranslations

**Comment by sergiogcx** [comment]
PR (merged): 
  https://github.com/cityofaustin/officer-thank-form/tree/1589-sg-otf-fixbuttontranslations

**Comment by easherma** [comment]
Verified + screenshots
