### ISSUE TITLE
Numbers scroll up and down in the Badge Number and other numeric fields

### ISSUE THREAD

**Issue by oliver2g** [cityofaustin/techstack#1597]
On the "Tell us about the officer(s)" page, the badge number field scrolls up or down when two finger swiping or rolling the mouse wheel. This could cause users to mistakenly change the badge number when trying to scroll down the page.

To re-create, enter any number. Then scroll down by two-finger swiping or rolling the mouse wheel while the cursor is still in the field. The numbers go up or down. The only way to avoid this is to tab or click out of the field first.

The scrolling behavior should be limited to date/time picker fields. It shouldn't apply to other numeric fields. All other numeric fields should be checked as well (e.g. Zip Code) across all forms.

NOTE: I was using Chrome on Mac OS (High Sierra) for this bug

**Comment by Niicck** [comment]
@oliver2g Can you let us know which browsers you came across this issue?

**Comment by oliver2g** [comment]
@Niicck Chrome browser on Mac OS High Sierra
