### ISSUE TITLE
Draft General 404 page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1598]
We'll draft more specific 404 pages (for depts, global, etc...) at a later date. Chase has research if you want to read up on it.

**Comment by JeffCopy** [comment]
@srigdon will you be the first pair of eyes on this one?
btw, I WAY overthought this in an effort to be more clever than is called for. Opted for a more  straightforward specimen of the 404 genus.
Draft is here:
https://docs.google.com/document/d/1lqvXYh_Cfa1UtJtVShVBm2Ozl6eWbYfdqJ75VMQYu7M/edit

**Comment by srigdon** [comment]
Looks good and I put a few questions in the doc. Want to weigh in @LauraTrujillo?

**Comment by LauraTrujillo** [comment]
@jeffcopy looks good! Entered my questions and comments below Sarah's.

**Comment by JeffCopy** [comment]
Thanks!
