### ISSUE TITLE
Spanish translation edits for language switch modal

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1602]
Note: In Spanish, names of languages are lowercased (so "ingles" and "español")

I'm not entirely sure about all of the translations, especially "Está seguro(a) que..."—getting a professional would be better. But in lieu of that I believe I've spruced some things up.

------

**¿Comenzar de nuevo en inglés?**

Cambiar a inglés borrará toda la información que ha ingresado.

¿Está seguro(a) que quiere cambiar de idioma?

[No, proceder en español] [Si, comenzar en inglés]

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/3e9d7624-863e-43bf-9c5c-fc0769c1a792)

**Comment by desigonz** [comment]
Hi @sergiogcx— @kriskristin and I are doing Spanish OPO user testing on Spanish and would love to have this pushed to live by then. Do you think that's doable? Thank you thank you!

**Comment by sergiogcx** [comment]
Merged to master.
