### ISSUE TITLE
Content for Senior persona prototype

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1604]
Please rewrite this page to reflect our current standards (it's for use in a prototype, so doesn't have to be perfect - this won't be pushed to production)
http://www.austintexas.gov/department/architectural-barrier-removal-program

**Comment by JeffCopy** [comment]
https://docs.google.com/document/d/1pafkV4I05wvBJ8RDykFzqwrYpTjiWMhJn33jj6E4iZQ/edit

**Comment by JeffCopy** [comment]
This is a rewrite of a page Tori wants to use for testing.  @desigonz can you take the first pass?

**Comment by desigonz** [comment]
@JeffCopy Just made some edits!

**Comment by JeffCopy** [comment]
@desigonz gracias!

**Comment by toribr** [comment]
Thanks, y'all.

**Comment by JeffCopy** [comment]
@LauraTrujillo per note above, this won't be pushed into production; it's for testing. This is my rewrite of the page with Desi's edits, and it may be good to go for these purposes, but if you want to take a look, it is here. Thanks!

**Comment by LauraTrujillo** [comment]
@JeffCopy looks great! I don't have anything to add.

**Comment by JeffCopy** [comment]
@toribr 
closing issue, next persona piece will go into review today.
