### ISSUE TITLE
Vertically center language switch modal

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1605]
On desktop, language switch modal floats to the bottom of the page; on mobile, it's buried beneath the fold.

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/08c77ba5-810e-4c33-b071-a5852ed2f048)

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/b5ce77ce-3113-4c77-b816-f703457ba3f5)

**Comment by Niicck** [comment]
This is actually pretty serious if you can't reach the modal on mobile.

**Comment by oliver2g** [comment]
@Niicck pls estimate this bug

**Comment by oliver2g** [comment]
@Niicck pls estimate this

**Comment by sergiogcx** [comment]
Is this a bug? I cannot replicate:

Chrome, mobile mode:

![Screen Shot 2019-04-15 at 3.27.38 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/ac45b91e-1af1-4abb-a95d-6c6cc2cd518a)

From my phone:
![Screenshot_20190415-152552.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/36991f24-c720-4a5d-8bf7-e4b8493faab6)

**Comment by easherma** [comment]
I think it would be best practice to have the modal be towards the top of the page, no? Since that is where the user taps? We can ask at design/dev sync.

**Comment by Niicck** [comment]
On staging, browserstack with iphone 6:

![Screen Shot 2019-04-15 at 3.33.38 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/06861cb7-95bd-4ee3-b891-34c82bf7296f)

**Comment by sergiogcx** [comment]
It seems to be a platform problem, not a screen size problem:

![Screen Shot 2019-04-15 at 3.55.20 PM.jpg](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/07b78f48-ca5c-4d67-bbd3-ba6282d26038)

**Comment by sergiogcx** [comment]
I set up a PR:

https://github.com/cityofaustin/officer-complaint-form/pull/100

Running demo:

https://opo.austintexas.io/police-complain-pr-100/introduction


I will need additional Browser-Stack testing on iPhone 6S

**Comment by sergiogcx** [comment]
The PR fixed it, now it is just matter of testing the same PR in other devices:

iPhone 6s:
![Screen Shot 2019-04-15 at 5.57.48 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/5a86b48c-be77-49d9-a1cb-5461c56b975e)

**Comment by sergiogcx** [comment]
Bug-fix tested on multiple Android iPhone devices, looking better. 

Link:

https://opo.austintexas.io/police-complain-pr-100/what-happened

**Comment by sergiogcx** [comment]
As far as vertically centering the modal, a new issue will have to be made.
