### ISSUE TITLE
Content for Unemployed persona prototype

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1606]
http://www.austintexas.gov/department/career-center

Rewrite this according to new style guide for prototype. (doesn't have to be perfect.
This is also for the testing of persona prototypes.

**Comment by JeffCopy** [comment]
Here's the first draft page. This content is for persona testing. 
https://docs.google.com/document/d/1lP8yScepwDpN3k71dsLsYYA1kLsvVP7IzsHXJ2kfDnc/edit#

@annieszot you're first reviewer on this one, thanks!

**Comment by annieszot** [comment]
@JeffCopy Edits in! Feel free to kick back to me for another round of revision

**Comment by JeffCopy** [comment]
Thanks!

**Comment by JeffCopy** [comment]
@annieszot thanks for the edits, very helpful! I took almost all of them. Moving on to Laura for a second read so we can move it on to Tori. 

@LauraTrujillo, on to you.

**Comment by LauraTrujillo** [comment]
@JeffCopy reviewed!

**Comment by JeffCopy** [comment]
@LauraTrujillo thanks! Further revisions implemented. Wanna take another look? On the do-we-or-don't-we-include-indeed/monster? issue, I propose we leave them for now, and see if there's any feedback on it from testing.

**Comment by LauraTrujillo** [comment]
@JeffCopy looks good!

**Comment by JeffCopy** [comment]
@toribr ready to roll
