### ISSUE TITLE
Community Youth Development Program content

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1607]
http://www.austintexas.gov/department/community-youth-development-program-dove-springs-78744

**Comment by LauraTrujillo** [comment]
Neat- 2 word doc forms, one of which is at least 2 years old :) 
[CCC_Application_-_FY18 (1).docx](https://github.com/cityofaustin/techstack/files/3302794/CCC_Application_-_FY18.1.docx)
[CSNA_survey__Eng-Span__2017__FY18_ (1).docx](https://github.com/cityofaustin/techstack/files/3302797/CSNA_survey__Eng-Span__2017__FY18_.1.docx)

**Comment by LauraTrujillo** [comment]
Draft lives here: https://docs.google.com/document/d/1GszVjEyfSDxP8VTSzfgLArLi7Q8aij9XI6UlMMSlGmA/edit?usp=sharing
@JeffCopy ready for your eyes!

**Comment by JeffCopy** [comment]
My suggested edits are now there; tag, you're it!

**Comment by LauraTrujillo** [comment]
@annieszot on to you! Can you give it a look-see by Tuesday, June 25th?

**Comment by annieszot** [comment]
Yes @LauraTrujillo ! And before I continue suggesting edits, radical suggestion - reframe this info page to be "Community development in Dove Springs" instead of just highlighting a program/committee?

**Comment by LauraTrujillo** [comment]
@annieszot yes! I love it- thank you!!
