### ISSUE TITLE
Draft HIV content

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1613]
Your mission: make sure all of the HIV content that should be transitioned has been drafted; draft whatever haven't been, and review existing HIV-related drafts. You might want to start by checking against the notes in the content audit, and then review the drafts we have so far. A lot of these drafts are old and weren't written using our current templates, so please update the templates and make sure everything is taken care of.

http://www.austintexas.gov/department/austinhiv
And
http://www.austintexas.gov/department/hiv-resources-administration-unit-hrau

These alpha drafts already exist in the drive:
- [HIV Planning Council Information Page](https://docs.google.com/document/d/1QT4C8gqoZLs0LscziLnKrauQ8gs7yLBwJi7-jym27Pk/edit?usp=sharing)
- [Get free HIV testing](https://docs.google.com/document/d/1WYxl7K2xZoDHc52a1olKIPWJpP5d_mFgH39TS1nuCuo/edit?usp=sharing)
- [Find medical and support service providers if you are HIV positive](https://docs.google.com/document/d/1snQ-9nxiyq-jbbZS_ot5FRjoksn43EMUjiCppcvYbys/edit?usp=sharing)

and this one is published:
- [Find free condoms and learn other ways to prevent HIV](https://alpha.austin.gov/en/health-safety/healthcare-prevention/disease-prevention/find-free-condoms)

Analytics info for Austin HIV branded site (2018 calendar year)
- [Where to get tested](http://www.austintexas.gov/department/where-get-tested) is the most viewed page (12,447)
- [Service providers](http://www.austintexas.gov/department/service-providers) (962)
- [About HIV and prevention](http://www.austintexas.gov/department/about-hiv-prevention) views are tiny (507)—let's add to the most-viewed service page and make that service page a top link
- [If you are positive](http://www.austintexas.gov/department/if-you-are-positive) (711)
- [Contractor resources](http://www.austintexas.gov/department/contractor-resources) is tiny (349)
- [HIV Planning Council](http://www.austintexas.gov/department/hiv-planning-council) (1,101)

**Comment by annieszot** [comment]
@LauraTrujillo Since I drafted the HIV planning council content, I'll assign myself to this content

**Comment by desigonz** [comment]
- [ ] rewrote [HIV Planning Council as a service page](https://docs.google.com/document/d/1ntLyj-EMf54rvGKxm4P6z8cfE7DUwEme1zvwK4ng4Y8/edit?usp=sharing)—it's more consistent with how we treated [joining the Central TX Diabetes Coalition](https://docs.google.com/document/d/1llvtWtb2JSuAA6D8GDdBOsZW5JfZeq01C1XtpF3dVxI/edit?usp=sharing), and it's an action folks can take!

**Comment by JeffCopy** [comment]
Reviewed pages, offered a few editorial suggestions and raised one question. I think it's NOT weird to currently have some fyi prevention/healthy practices language in both those places, since anybody who winds up on either page might benefit, but do agree that the best eventual answer is something more like the homelessness topic collection, where it's all together in a more systematic way.

**Comment by desigonz** [comment]
Thanks @JeffCopy! Onto @LauraTrujillo for second review.

**Comment by LauraTrujillo** [comment]
@desigonz left my comments. I agree with Jeff about having prevention/information in both places AND about backlogging the "Find services if you are HIV positive" content until we get to something like the homelessness topic collection.
