### ISSUE TITLE
Draft refugee services content

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1622]
http://www.austintexas.gov/department/refugee-services

It's interesting how Boston organized their content- especially when it's not just city services available to new residents: https://www.boston.gov/departments/immigrant-advancement/immigrant-advancement-resources

Might all be covered in this draft—please review: https://docs.google.com/document/d/1HbA2qNf6X9XIjWOhP_kH1dpKy6epvvCG-fpdCnpypuU/edit?usp=sharing

**Comment by desigonz** [comment]
Hi Laura—I'm reviewing the refugee services content and from the looks of [this draft](https://docs.google.com/document/d/1HbA2qNf6X9XIjWOhP_kH1dpKy6epvvCG-fpdCnpypuU/edit?usp=sharing), seems to be that the City of Austin no longer provides these services. Can you confirm? (Should I ask Sarah Rodriguez to confirm?) If that's true, I'll throw the draft into an archived folder and close this issue for now.

**Comment by LauraTrujillo** [comment]
Yeah, let's archive and close it for now.
