### ISSUE TITLE
Draft STD content

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1623]
Should it be STI?

http://www.austintexas.gov/department/sexually-transmitted-diseases-stds

We have a draft of a service page for STD testing: https://docs.google.com/document/d/1IGhEBxFOXxWam7ghcmcP9bTvn-YXZF-mVyCEnwAr6gQ/edit?usp=sharing

Do we need anything else?

**Comment by desigonz** [comment]
Assigning [this draft](https://docs.google.com/document/d/1IGhEBxFOXxWam7ghcmcP9bTvn-YXZF-mVyCEnwAr6gQ/edit?usp=sharing) to @JeffCopy for first review.

**Comment by JeffCopy** [comment]
My suggested edits are there. Onward!

**Comment by desigonz** [comment]
Thanks a million @JeffCopy! Onto @LauraTrujillo for review round 2.

**Comment by LauraTrujillo** [comment]
Good to go, @desigonz!
