### ISSUE TITLE
Draft Women, Infants and Children (WIC) content

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1625]
http://www.austintexas.gov/wic

draft: https://docs.google.com/document/d/1Cl7PHJ-jCDPX_ScoFxbweTEqrQ5JkG5MOsFJV7mIYcE/edit

**Comment by LauraTrujillo** [comment]
@desigonz can you take first review of this page? Draft lives here: https://docs.google.com/document/d/1Cl7PHJ-jCDPX_ScoFxbweTEqrQ5JkG5MOsFJV7mIYcE/edit#

I didn't include any of the links to breastfeeding support, but I'm wondering if you think I should. Trying to avoid a catch-all page and wanted to start with less on the page then build as we need to. I'm just not sure if these are partners that need to be linked to for funding. For reference, those links live in an old draft here: https://docs.google.com/document/d/1cEY9T2fW_X953UPcqpliu8N6_CWAgUvLuXD4KJLBx-g/edit#)

**Comment by desigonz** [comment]
I think your intuition to exclude links is spot-on! Some are broken and others have super low analytics. Also, they link to a bunch of PDFs (looks like CoA made them) presented with no context around them (like when to use them) and have abysmal click rates.

Draft looks good! I think this is perfect for MVP and if they have pushback about the links and PDFs, we can work with them post-MVP to look at analytics, determine what's useful, and flesh out deeper (and meaningful) content.

**Comment by LauraTrujillo** [comment]
@desigonz Thanks!
@annieszot On to you for a second set of eyes, please!

**Comment by annieszot** [comment]
Great @LauraTrujillo ! Love the cross-promotion links. I agree the copy "as-is" is ready for MVP, and my suggested edits are included or can get tacked on for post-MVP :)
