### ISSUE TITLE
Draft service page for smoke-free events toolkit

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1630]
http://austintexas.gov/sites/default/files/files/Health/Chronic_Disease/FINAL_Smokefree_Toolkit__003_.pdf

Use service page template

**Comment by desigonz** [comment]
Draft lives here: https://docs.google.com/document/d/1kCU9JHW3R1PqEpH0wzj7Q0eeFQO6_EE0tF9mU2NrFaA/edit?usp=sharing

Will be meeting Ashley LeMaitre, the program coordinator, on April 12 and will run this content by her then!

**Comment by desigonz** [comment]
Waiting until after Sprint 29 review to loop back to Ashley LeMaistre.

**Comment by oliver2g** [comment]
@desigonz depending on what you hear back from Ashley, pls add the Sprint milestone as necessary.

**Comment by desigonz** [comment]
@srigdon, would you mind taking the first review?

**Comment by desigonz** [comment]
@JeffCopy can you take a pass on this draft? https://docs.google.com/document/d/1kCU9JHW3R1PqEpH0wzj7Q0eeFQO6_EE0tF9mU2NrFaA/edit?usp=sharing

**Comment by JeffCopy** [comment]
suggested edits are there now, back to you.

**Comment by desigonz** [comment]
Thanks! Onto @LauraTrujillo for second review.

**Comment by LauraTrujillo** [comment]
@desigonz reviewed with one suggestion!
