### ISSUE TITLE
Make linting pass for FileUploadWidget

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#1634]
Related: https://github.com/cityofaustin/techstack/issues/1632
This is currently being ignore by eslint in order to make the build pass. Following some linting would be good for us to avoid tech debt/better future maintainability.

**Comment by sergiogcx** [comment]
Didn't implement the review widget; I do not know what is causing the problems with eslint. Also I spoke with @Niicck today and the component is being re-worked to avoid using environment variables. Not sure how this is going to affect the review widget.

**Comment by sergiogcx** [comment]
Closing #1632 should be the frame of reference for these issues.
