### ISSUE TITLE
"City of Austin" doesn't link to the home page from department, information, and service pages

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#1637]
On all department, information, and service pages, the City of Austin title is clickable but linked to https://alpha.austin.gov/# and goes nowhere. 

For the OPO department page, there's no way to click back to the home page other than the link in the footer: https://alpha.austin.gov/police-oversight/

**Comment by briaguya** [comment]
This was intentional as per #1425

When we move away from the OPO microsite to the full site this should be addressed
