### ISSUE TITLE
Resolve navigation to info pages from OPO

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1642]
Short term solution

**Comment by chasechenevert** [comment]
## Visual design: OPO information page links on Department pages

### Dev specs
- Desktop: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/dc01779e-7f91-4cc9-a216-9d6714ec8a40/Navigation-Page-links-MVP/

### Context
- Desktop: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/9055635c-de21-497d-b8fb-631c3e39c802/Department-MVP-Desktop/
- Mobile: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/060634eb-a0ac-48d3-9784-d1b5770ef714/Department-MVP-Mobile/

<img width="1001" alt="Screen Shot 2019-04-10 at 2 02 37 PM" src="https://user-images.githubusercontent.com/7027270/55907007-38a66c00-5b9b-11e9-8c6e-a2b9426c0e95.png">


CC: @toribr + @pibemillo
