### ISSUE TITLE
Refactor forms build process/scripts

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#1647]
**Objective** 
Now that we have a version deployed to production and have more forms in the pipeline, it's a good idea to revisit our build process to make sure we can be flexible. 

**Participants**
@sergiogcx 
@easherma 
Anyone else who wants to help

**Agenda**

------
- [ ] Schedule meeting
- [ ] Meet
- [ ] Create resulting issues

**Comment by easherma** [comment]
https://brettdewoody.com/secure-environment-variables-with-travis/

**Comment by sergiogcx** [comment]
We used to have secure environment variables (https://github.com/cityofaustin/joplin/blob/3f023106603a682f13d3a9676bc57a2fac603e0e/.travis.yml#L36) I shortly found them to be a pain to work with and retracted to using environment variables in settings instead so they can be changed without having to change code.

**Comment by sergiogcx** [comment]
Also, @Niicck is re-writing the deployment pipeline. Closing this issue.
