### ISSUE TITLE
Janis - Service page links are broken when navigating from /en/ or /es/ instead of not having a language specifier

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1649]
There are some issues with how we're handling internationalized links in Janis. The links work fine on reload, but don't work when navigating.
http://g.recordit.co/FgDZc0UdkF.gif

I did a bit of investigating, and found that switching away from using internationalized links will still keep the language selection, while the address bar will lose it.

I did some investigating as to more comprehensive solutions, and investigated upgrading from react-static 5 to react-static 7. It seems as though there have been quite a few improvements there (https://github.com/nozzle/react-static/blob/master/CHANGELOG.md) but also quite a few breaking changes.

Upgrading to react static 7 comes with quite a few benefits, for one, builds run on multiple threads by default (faster!), and there is a plugin that supports incremental builds (looks like setting that up might be decently complicated with our setup). Given those improvements, I'd like to migrate to react-static 7 and deal with the breaking changes.

**Comment by sergiogcx** [comment]
It looks like this happens at the local level too:

```
yarn start-prod
```

<img width="1368" alt="Screen Shot 2019-04-02 at 8 02 00 PM" src="https://user-images.githubusercontent.com/5282430/55445698-354f2700-5582-11e9-9c0f-ae9c70c4792e.png">
