### ISSUE TITLE
Upgrade to react-static 7

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1650]
PR: https://github.com/cityofaustin/janis/pull/585

## testing notes:
https://joplin-pr-brians-janis-testing.herokuapp.com/ is set up to build/preview with https://janis-1650-react-static-7.netlify.com/

## Bonus
I did some investigating as to more comprehensive solutions, and investigated upgrading from react-static 5 to react-static 7. It seems as though there have been quite a few improvements there (https://github.com/nozzle/react-static/blob/master/CHANGELOG.md) but also quite a few breaking changes.

Upgrading to react static 7 comes with quite a few benefits, for one, builds run on multiple threads by default (faster!), and there is a plugin that supports incremental builds (looks like setting that up might be decently complicated with our setup). Given those improvements, I'd like to migrate to react-static 7 and deal with the breaking changes.

**Comment by easherma** [comment]
5.9.7 <--- current version we use

**Comment by easherma** [comment]
6 and 7 both have significant breaking changes. 
First glance notable stuff from 6: 
* All render and component props are now deprecated in favor of using child-as-a-function rendering. Anywhere you are using these props must be migrated to use a child as a function.
* React-Static no longer ships with any routing-related functionality. It functions independently of your routing paradigm. Thus, it no longer exports anything from react-router.
* Router has been deprecated and replaced by the Root component. The Root component implements the HashScroller component, an ErrorBoundary and a very simple and non-invasive route context using @reach/router (the recommended router). The base router is customizable or replaceable if the user wishes to use a different router.

From 7: 
* Upgraded to React 16.8.x
* Internally, all state is now being tracked and stored in a single global state variable. This global state is passed around everywhere, including getRoutes, most plugin hooks, and just about anywhere React Static calls into your own user code.
* Though still available, the start, bundle and export commands are being deprecated and have been removed from the documentation.

**Comment by easherma** [comment]
active in https://github.com/cityofaustin/janis/pull/395

**Comment by briaguya** [comment]
@desigonz this is once again just a "click around and make sure things aren't broken" test. Mostly on the Janis side but feel free to use the joplin PR app for testing previews/changes.

**Comment by desigonz** [comment]
- [ ] feedback not submitting
![1650-feedback](https://user-images.githubusercontent.com/5839508/67891892-84156d00-fb21-11e9-9274-7867c80dd976.gif)

**Comment by desigonz** [comment]
Submit bug is still happening in staging :( :(

**Comment by desigonz** [comment]
Feedback submission now works in staging! QA done.
