### ISSUE TITLE
Can't add additional officer or witness

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1652]
This is happening on staging for both the English and Spanish complaint forms. Not happening on the live site right now.

To replicate: 
1. Fill out form
2. Add officer or witness details
3. Click "add another officer" or "add another witness"

What I expected: First officer details collapsed, with new blank section to enter 2nd officer details 
What happened: The answers I had written were highlighted in gray, with no blank section

**URL tested:** https://forms.austintexas.io/policia-queja/detalles-oficial

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Firefox&browser_version=63.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Fdetalles-oficial&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/detalles-oficial) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Firefox 63.0 |
| Operating System | OS X Mojave |
| Resolution | 1326x766 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/8d1e5021a7294f9831d01e0680bdc835d4e2449b/macmo_firefox_63.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/8d1e5021a7294f9831d01e0680bdc835d4e2449b/macmo_firefox_63.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Firefox&browser_version=63.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Fdetalles-oficial&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/detalles-oficial) to reproduce the issue on Browserstack**

**Comment by sergiogcx** [comment]
Production does not have the problem, it affects both English and Spanish, it affects only the complaint form.

**Comment by sergiogcx** [comment]
Console output:

![Screen Shot 2019-04-03 at 4.08.06 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/ebf7dce0-b99b-4b06-8b9c-57dedefed247)

**Comment by easherma** [comment]
https://github.com/cityofaustin/officer-form-chapters/commit/80cb8117598df6423f94560494abc739ee33d68e should fix it

**Comment by desigonz** [comment]
thanks @easherma! confirmed this is working now. Closing this issue.
