### ISSUE TITLE
Changes made in Joplin aren't publishing out

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1656]
Laura made a number of changes (one or two weeks ago!) to the OPO pages in Joplin but they haven't published out. Sharing some screenshots that point out the content discrepancies.

During testing today, someone clicked through to the "Complaint investigation process" and said "What's OPO?" 

![complaint-process-frontend.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/37549268-e2de-4a8a-8fba-4ac9c0bffc5c)![complaint-process-back2.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/939c19d4-624f-4842-8410-08d1fe52b814)![complaint-process-back1.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/94bf2ca7-daa7-4d1b-a710-80aef1b2e4fa)

**Comment by sergiogcx** [comment]
Janis now has a Travis build that can be triggered at any time.

**Comment by easherma** [comment]
Hmm, its true we have a manual trigger for builds but given the meeting we had a few days ago, I don't think thats good enough. 

@briaguya could you reference the issues you made after that discussion here? I think what probably makes sense is to reference those here as ongoing work and close this specific issue, unless you want to leave it open?
