### ISSUE TITLE
Write up date/time picker bugs

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1657]
Hey @kriskristin—making us an issue to review user testing data and flesh out all of the problems we see with the date and time picker. 

As I doing QA on another thing, I noticed this discrepancy below, among all the other things we saw today 🙃

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/4e1fc7c8-e731-4145-8113-5d3e4048e3d6)

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/f77c0f0f-1a08-4d99-82be-39e64fd198ad)

**Comment by kriskristin** [comment]
I think the date & time issues have been resolved. @toribr @sergiogcx @easherma can you confirm?

**Comment by toribr** [comment]
I think this is a dupe of the resolved #1676
