### ISSUE TITLE
Update Joplin so that content publishes without having to rebuild manually

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1658]
The content team is getting to the point where we need to update content on the fly. 

Make it so that we don't have to manually rebuild every time we make a content change? Or at least update the site once a day?

**Comment by sergiogcx** [comment]
I am working on this, this is going to be finished before the sprint is finished. In fact, it is already working in the master/staging branch:

`https://joplin-staging.herokuapp.com/`

More thorough testing is happening today and in the next few days, before I can make it available to production (where it is most needed).

Namely, I need to make sure that react-router is not a problem and add a cache-clearing method to the container routines.

**Comment by sergiogcx** [comment]
Merged to master, all there is left is to switch the master bucket.

**Comment by sergiogcx** [comment]
Also, currently master/staging gets built with production data. We need to decide if we want staging to build on staging data, or if we need to trigger builds on staging from production.

**Comment by desigonz** [comment]
@sergiogcx Not sure the answer on your question there—my hunch is keep production tied to everything so we don't have to update in multiple places (which I believe is what @briaguya said yesterday). 

Is this ready for me to test? I tried updating in Joplin prod but didn't see changes reflected in Janis. Let me know how/when I can test.

**Comment by sergiogcx** [comment]
Sorry for the lack of clarity, Joplin isn't publishing to Janis yet.  I have resolved this with the developers, we have deployed this to production but it appears production builds are breaking, so I can't further test this on janis.

**Comment by sergiogcx** [comment]
I have resolved the subject of the different environments with the devs, we have deployed a temporary solution to production but it appears production builds are breaking due to another smaller issue with phones. Until that gets resolved we won't be able to further test this issue.

**Comment by desigonz** [comment]
No worries, let me know when you're ready for me to test.
