### ISSUE TITLE
Investigate content-publisher (gov.uk)

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1660]
# Brain dump
## Getting it running
working on it: https://github.com/alphagov/content-publisher

**Comment by oliver2g** [comment]
![20190423_145004](https://user-images.githubusercontent.com/35782646/56673259-8c29b700-667d-11e9-9270-212c1675f706.jpg)
FYI. @briaguya if this issue means evaluating gov.uk as a potential new content editor, then I think we can close this issue. If it means looking at features that we might be able to replicate in the current Joplin, then we can assign it to someone. Let me know what you had in mind.
