### ISSUE TITLE
Change OPO thanks form title to H1

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1661]
Take a look at the screenshot below—the titles for the OPO complaint and thanks pages (in English & Spanish) are styling differently. The thank you form should be h1, not h2. 

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/63af032c-81ae-4dec-b8db-fbbd3f1859b6)

**Comment by easherma** [comment]
Lets wait to do this as we're in the middle of consolidating form repos.

**Comment by easherma** [comment]
https://github.com/cityofaustin/coa-forms/pull/15, live at https://opo.austintexas.io/police-thank/1661-update-thanks-title-h1/introduction

**Comment by desigonz** [comment]
@easherma I'm still seeing this as an h2!

**Comment by desigonz** [comment]
@easherma Here's the screenshot: 
![image](https://user-images.githubusercontent.com/5839508/56770400-7e595c00-6779-11e9-8ac5-2f2776c32ab5.png)

**Comment by easherma** [comment]
@desigonz give it another try; should be live now

**Comment by desigonz** [comment]
@easherma Beautiful! Closing this issue.
