### ISSUE TITLE
Police Oversight: Automate PR server deployment

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/techstack#1673]
Currently the OPO pr viewer does not build automatically. That needs to be implemented.

https://github.com/cityofaustin/opo-pr-viewer

**Comment by sergiogcx** [comment]
Done! Merged to master:
https://github.com/cityofaustin/opo-pr-viewer/pull/1

**Comment by easherma** [comment]
@sergiogcx do we have this documented anywhere? Maybe we can add it to the README on the soon to be consolidated forms repo

Would you consider this closed issue or is there some sort of QA process you'd envision?
