### ISSUE TITLE
User can unwittingly delete information via multiple "edit" buttons on Review, Officer and Witness sections

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1674]
video here: https://austininnovation.slack.com/archives/C8T4YD23T/p1554748563005400

The two 'edit' buttons on Review makes for a lousy UX experience, and also can remove any data if the user selects "no>update" from the top edit button. 

1) there shouldn't be 2 "edit" buttons for the same section 

2) if a user selects the top edit button, then selects "no> update" then any data present about an officer is deleted. It might be weirdly logical, but horrible nonetheless, as the data destroyed does not share proximity with the edit button, and does not make clear that any pre-existing officer info is about to be deleted.

Review needs a need interaction flow and design altogether, but in the meantime can we hide the first, and unnecessary edit button? I don't see the point of it even being there. I'll write a bug, but it would be good to know if we can get this fixed pretty quick as it's really shoddy and potentially destructive.

**Comment by easherma** [comment]
related to https://github.com/cityofaustin/techstack/issues/1094

**Comment by easherma** [comment]
@oliver2g we should talk about this, I think P3 may be a bit too high

**Comment by easherma** [comment]
Also related to https://github.com/cityofaustin/techstack/issues/1275

**Comment by easherma** [comment]
@toribr should we talk about this at the design/dev sync?

**Comment by easherma** [comment]
@toribr we didn't really get to this one; lets talk about it soon!

**Comment by oliver2g** [comment]
taking this out of Sprint 28 for now. let's discuss it during Sprint planning for 29.

**Comment by easherma** [comment]
We discussed different ways to address this. What might be most feasible is some sort of error or warning (similar to the routing modal) letting people know their submissions will be removed for that section.

**Comment by oliver2g** [comment]
Also, @toribr will analyze the analytics on hotjar to see if there's any data that will help bump this up as a priority that needs to be worked on now. Priority set to P4 for now.

**Comment by easherma** [comment]
Also related: https://github.com/cityofaustin/techstack/issues/1105

**Comment by easherma** [comment]
@briaguya has a PR: https://github.com/cityofaustin/coa-forms/pull/22/files
@Niicck is working on having Yes/No only on the /officer-info page but not on the review page. With the ability to add/remove officers on the review page

We discussed modifying this behavior vs having a modal or other notification for the user, but decided the former is the ideal solution for now.

**Comment by Niicck** [comment]
<img width="767" alt="Screen Shot 2019-05-01 at 2 38 54 PM" src="https://user-images.githubusercontent.com/14187277/57038352-58233880-6c1f-11e9-9afe-eb9d29ff401a.png">

I've got a working solution here:
https://opo.austintexas.io/police-complain/1674-edit-officers/

Or if you want to cut to the chase:
https://opo.austintexas.io/police-complain/1674-edit-officers/review-and-submit

We now have the option to add 'ui:removeFieldFromReview' on the uiSchemas of our chapters.
You can check out the code changes and documentation here: https://github.com/cityofaustin/us-forms-system/pull/24

**Comment by Niicck** [comment]
QA Plan:
Do 3 trials of the complaint form. It doesn't matter which browser.
Use this link: https://opo.austintexas.io/police-complain/1674-edit-officers/

1. 
  - On /officer-details, enter info for 2 officers.
  - On /witness-details, enter info for 2 witnesses
  - Check that its still there on /review-and-submit. 
  - Submit form. 
  - Check email. Make sure the officer and witness info is in your email.
2. 
  - On /officer-details, enter info for 2 officers.
  - On /witness-details, enter info for 2 witnesses
  - Check that its still there on /review-and-submit.
  - BUT THIS TIME edit the info in the review page. Delete 1 officer and delete 1 witness. Then add 1 new officer and 1 new witness.
  - Submit. Check email. Make sure data matches.
3. 
  - Enter NO officer info on /officer-details. Select "No" I don't want to enter officer info
  - Enter NO witness info on /witness-details. Select "No I don't want to enter witness info
  - THIS TIME enter info for 2 officers and 2 witness only on the review page.
  - Submit. Check email. Make sure data matches.

**Comment by annieszot** [comment]
I'll do QA. 
Mobile:
- [ ] iPhone 6: Safari 11 (Previously Safari 12)
  - [ ] English
  - [ ] Spanish 
- [ ] Android (Galaxy 8): Chrome 7
  - [ ] English
  - [ ] Spanish 

Desktop:
- [ ] Windows 10: Chrome 71.0
  - [ ] English
  - [ ] Spanish
- [ ] Windows 7: Chrome 71.0;
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 7: Internet Explorer 11
  - [ ] English
  - [ ] Spanish 
- [ ] MacOS 10.14: Chrome 71.0
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Edge 17.17; 
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Internet Explorer 11
  - [ ] English
  - [ ] Spanish

**Comment by annieszot** [comment]
Need screenshots?

**Comment by annieszot** [comment]
Closing! Good work :)
