### ISSUE TITLE
Police Oversight: Notes for Monorepo

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/techstack#1675]
Notes:

- I have been thinking about the comments I heard in DevSync. It wouldn't hurt to have a production replica branch. It would be treated like staging, but shares the code of prod.

- We will have to address deployments in the monorepo, the pipeline script will have to identify the environment (master, prod-replica, prod, or pr), then determine if all forms need to be deployed, or just one where the changes happened, then deploy both english and spanish versions for each form, or that single form.

- Localizations will have to be arranged for, or merged together.

- If bash gets very difficult to maintain, we can go with something else like Python.

- Routing should not be an issue, if the patches are made correctly. I think the deployment will require some work and thorough testing, but I do see the monorepo simplifying the development process.

- I also don't drink the S3/CloudFront koolaid, I am fine using anything else: Netlify, Heroku, you name it. Whatever simplifies the development process. (edited) 

- Let's make a new repo for this purpose though, just in case we collectively change our minds and need to go back.

- This should also allow us to use something else other than Travis (CircleCI, Microsoft, GitLab, etc). We need to prevent deployments in the wrong buckets. (edited)

**Comment by easherma** [comment]
@Niicck many of these points are addressed in your repo consolidation, no? Should we update this issue, or close it?

**Comment by Niicck** [comment]
Yep, these points have been accounted for. I think we can close it out.
