### ISSUE TITLE
OPO form: Date reporting and handling of date and minutes acting funny: STAGING

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1676]
Date is reporting incorrectly on review page; additionally user can enter more than two digits on minutes field; may also be similar problem with date field.

STAGING only, but needs to be fixed for reliable user testing.

**Comment by Niicck** [comment]
Deployed into staging, should be good to test.

**Comment by toribr** [comment]
Looks good.

**Comment by oliver2g** [comment]
@Niicck can you add an estimate and then close this issue. Tori gave it the go ahead. Thanks!
