### ISSUE TITLE
Strange 404 Page on staging form

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1680]
**Describe the bug**
404 page for staging forms looks weird.

https://forms.austintexas.io/officer-thank/review-and-submit

**To Reproduce**

1. Go to https://forms.austintexas.io/officer-thank/review-and-submit
2. Behold

**Current behavior**

We're taken to a strange purgatory of broken links.

**Expected behavior**

Reroute to an appropriate 404 page that isn't isolated from the rest of the site.

**Screenshots**

![Screen Shot 2019-04-09 at 2.56.45 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/bff06fea-009e-463a-bcd7-aead4dfb032c)

**Device**

Desktop

**Additional context**

@sergiogcx would probably know best what this means or if its a problem

**Comment by Niicck** [comment]
In prod:
<img width="741" alt="Screen Shot 2019-04-09 at 3 01 05 PM" src="https://user-images.githubusercontent.com/14187277/55831274-56f76380-5ad8-11e9-9b8e-6ee8d6c6fd17.png">

**Comment by sergiogcx** [comment]
Not really a bug, since it does not pertain to the forms. Also, master is our dev environment.

**Comment by sergiogcx** [comment]
Created a 404 page anyway: https://forms.austintexas.io/404.html

Perhaps the real discussion be: what should the expected behavior be for a development environment?

Cheers,

**Comment by sergiogcx** [comment]
It seems to work: https://forms.austintexas.io/have-you-checked-me?

**Comment by Niicck** [comment]
The production form is still acting weird. https://forms.austin.gov/officer-thank/review-and-submit

> Perhaps the real discussion be: what should the expected behavior be for a development environment?

That is the question I'm asking. Should this issue be transformed into a feature request for a formal 404 page for our form microsite?

**Comment by sergiogcx** [comment]
I think so, my understanding is that all non-form links need to be redirected to the microsite.

The reason the redirect does not work is because of the relative paths of the javascript files. I can update that shortly.

**Comment by sergiogcx** [comment]
The redirect has been fixed. Once we determine the course of action, we can then create a ticket which I would be happy to take.
