### ISSUE TITLE
Review page headings cut off in mobile

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1686]
See screenshots—review page headings get cut off in mobile when they extend to 2 lines. 

this first screenshot is on an iPhone 6

![IMG_2173.PNG](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/46bd2ae9-91ba-4cd7-b872-e2e5a5f6fa8d)

**URL tested:** https://forms.austintexas.io/policia-queja/revisar-y-enviar

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=7.1&device=Samsung+Galaxy+A8&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Frevisar-y-enviar&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/revisar-y-enviar) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Samsung Galaxy A8 |
| Browser | Mobile_chrome |
| Operating System | Android 7.1 |
| Resolution | 1080 x 2220 px |
| Screen size | 5.8 in - 5.6 x 2.7 in |
| Viewport | 360 x 612 dp |
| Aspect Ratio | 18.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/64e91514297f9be0c745e5a8dab80a786da453d5/realdroid_Samsung_Galaxy_A8.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/64e91514297f9be0c745e5a8dab80a786da453d5/realdroid_Samsung_Galaxy_A8.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=android&os_version=7.1&device=Samsung+Galaxy+A8&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Frevisar-y-enviar&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/revisar-y-enviar) to reproduce the issue on Browserstack**

**Comment by sergiogcx** [comment]
We could definitely use the guidance from @toribr but I can think of a few options:

1. Make each component a bit taller so that the text will provide enough space.
2. We could hide the text overflow.
3. Make the text size smaller (or come up with some kind of automatic size adjustment)

Anyhow, just my two cents.

**Comment by toribr** [comment]
Since this is an ongoing problem we will have with Spanish, I want to discuss which options we can use that will give us the most robust and flexible code going forward, and also include @chasechenevert and @pibemillo in this conversation. @pibemillo @chasechenevert opinions?

**Comment by sergiogcx** [comment]
@chasechenevert it appears we only need two lines of CSS code to make it work (notice the box at the bottom):

![Screen Shot 2019-04-16 at 11.37.57 AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/a77221b8-0b56-40f5-9c21-5f99a44a269f)

I've assigned @pibemillo to work on the task, he has a ton of interest in getting familiar with the forms too.

To start with, we only needed these two lines plus whatever Gonzalo determines needs fixing.

```
    min-height: 7rem !important;
    height: auto !important;
```

**Comment by pibemillo** [comment]
https://github.com/cityofaustin/officer-complaint-form/pull/101

**Comment by Niicck** [comment]
UI bug on Chrome Google Pixel 2:
https://opo.austintexas.io/policia-queja-pr-100/revisar-y-enviar

The titles are no longer cut off, but we lose our bottom margins. I'll merge in the code changes for officer-complaint-form because its better than what we had before, and we'll maintain parity with officer-thank-form. But I'm going to move the ticket back into "In Progress"

<img width="319" alt="Screen Shot 2019-04-17 at 12 17 44 PM" src="https://user-images.githubusercontent.com/14187277/56307653-f89b3800-610a-11e9-907d-889f62ac5465.png">

**Comment by sergiogcx** [comment]
@Niicck PR 100 is for another issue, @pibemillo is working on PR 101:

https://opo.austintexas.io/policia-queja-pr-101/revisar-y-enviar

![Screen Shot 2019-04-17 at 4.09.33 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/0af48ed4-a39f-4115-8db0-4ee3ad925e42)

**Comment by sergiogcx** [comment]
Looking good on master both forms, closing this issue.

![Screen Shot 2019-04-17 at 4.16.01 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/baf455e9-4106-4fe1-8ba5-c51a2bdd07cd)

![Screen Shot 2019-04-17 at 4.19.18 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/ee7fdcd7-3034-4f46-b2fe-e169ca66a40b)

![Screen Shot 2019-04-17 at 4.20.05 PM.png]
(https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/160e168c-b8bb-44a3-907e-12d493b06974)

![Screen Shot 2019-04-17 at 4.20.11 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/7c6248f3-8c23-42a2-83c6-530d0d8d82f0)
