### ISSUE TITLE
Bug: 404 page not loading in deployed environments

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1690]
Looks like there's something broken with our 404 handling and the template isn't loading.

**Comment by sergiogcx** [comment]
Not sure what may be causing it at first impressions. 

I have checked the settings in CloudFront and S3, they seem to be set up correctly:

CloudFront:

![Screen Shot 2019-04-14 at 5 53 58 PM](https://user-images.githubusercontent.com/5282430/56100445-5434ae00-5ede-11e9-90b2-9747863e7c3f.png)

S3:

![Screen Shot 2019-04-14 at 5 51 03 PM](https://user-images.githubusercontent.com/5282430/56100452-5991f880-5ede-11e9-8909-83b29bdfded4.png)

**Comment by sergiogcx** [comment]
I see that the 404 page works locally:



![Screen Shot 2019-04-14 at 6 09 19 PM](https://user-images.githubusercontent.com/5282430/56100597-72031280-5ee0-11e9-8416-f01bb3c293db.png)

S3 does not: http://janis-austin-gov-production.s3-website-us-east-1.amazonaws.com/this-should-cause-an-error

I will take a good look, and see if I can make it work on the cloud.

**Comment by sergiogcx** [comment]
Strange, it looks like your deployment also doesn't show the 404 page

http://janis.s3-website.us-east-2.amazonaws.com/show-me-error-page

**Comment by sergiogcx** [comment]
Oh, in our Nginx config it shows like this:

![Screen Shot 2019-04-14 at 6 20 39 PM](https://user-images.githubusercontent.com/5282430/56100734-08840380-5ee2-11e9-911f-4b7ff98bac18.png)


Not sure if this is going to work in S3, but in your s3 bucket (http://janis.s3-website.us-east-2.amazonaws.com/show-me-error-page) the 404 page is now showing.

Making the same change in master:

![Screen Shot 2019-04-14 at 6 20 08 PM](https://user-images.githubusercontent.com/5282430/56100725-f5713380-5ee1-11e9-91cf-e57d8d4bd1cf.png)

**Comment by sergiogcx** [comment]
It looks like it is working now:

https://janis.austintexas.io/show-me-404

Will have to implement this in prod and PRs

**Comment by sergiogcx** [comment]
Ok, prod is now showing the 404 error:

https://alpha.austin.gov/show-me-404-here

You may not see the latest version, because it is set up with an origin group, which includes your old janis build. 

Once we have a finished deployment pipeline, the origin group will be updated automatically.

**Comment by sergiogcx** [comment]
PRs are a routing problem, they are going to show the bucket's error message.

**Comment by easherma** [comment]
@sergiogcx should this be moved to QA?
