### ISSUE TITLE
Add clarifying language to OPO form confirmation page about storing email addresses

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#1696]
Related to #1688, add to the confirmation page language explaining that we do not store your email address, but you can get a copy of your complaint and the confirmation number emailed to you if you want.

**Comment by srigdon** [comment]
![OPO_conf-page-complaint_copy-change.png](https://images.zenhubusercontent.com/5be0b7bea977220c77bd229b/970e0407-bef5-425a-8956-0a9269709101)

I talked to @sergiogcx and clarified that the user can't really submit their email address and remain totally anonymous, even if just on the confirmation page. They can copy down the confirmation number and track their complaint that way, or ask someone to call the office and track it for them, but we do store logs of the email addresses entered on that page on AWS. We don't share these logs with other offices, but even just a few people at the ODD having the ability to view that info breaks the privacy of the user. 

To really make sure someone can get a copy of their complaint _and_ remain anonymous, we'd have to do something like offer the the ability to save a copy of it in some file format after submission or on the review page. Dare I say PDF download? But this is a future feature, so I'll create a separate issue. 

Here are my copy changes to this page: 

- Instead of: "For a copy of your complaint and confirmation number, enter your email address below." Change to: "To receive a copy of your complaint and confirmation number, enter your email address below. Email addresses entered on this page are not shared with the Office of Police Oversight, but they are stored on an AWS server maintained by City of Austin staff. To remain completely anonymous, do not enter your email address here." 
- Leave the rest of the page as is. 

@LauraTrujillo @desigonz Can you be my two pairs of eyes? Does this make sense? Also, same question as #1688 re: Spanish translation.

**Comment by oliver2g** [comment]
@srigdon i don't know that we can make this change without OPO eyes on it. My instinct is to put it in the backlog for now and then include it with all other insights we have from @toribr, user testing, etc. If there are any improvements we highly recommend doing right now, then we can put them all together in a proposed release to OPO. Lemme know if yall have any other thoughts @LauraTrujillo @desigonz

**Comment by LauraTrujillo** [comment]
I agree with batching it with the other insights, @oliver2g

**Comment by desigonz** [comment]
Agreed with @oliver2g and @LauraTrujillo.

Also, @srigdon, FWIW, my initial reaction to your copy was that it's very thorough, but perhaps overwhelming for a user.

**Comment by srigdon** [comment]
We're recommending changes to the complaint form that override the need for this update.
