### ISSUE TITLE
Hide search UI

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#170]
Instead of [adding explanatory text to the search results page](https://github.com/cityofaustin/techstack/issues/118#issuecomment-371217981), we decided to hide the search UI until the search feature is tackled. 

It should be hidden from the top navigation and homepage hero image overlay. 

Since this requires design and dev resources, it may be moved to the backlog if it is too big to be incorporated in #102 and #103. This will be determined in 3/12 dev review of design v2 meeting.

**Comment by mateoclarke** [comment]
Done in this commit: https://github.com/cityofaustin/janis/pull/160/commits/56379c3a8478238c596e5d1b224bf10c974c58d3
