### ISSUE TITLE
Survey of best practices and how other civic tech website are handling linking offsite. 

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1715]
Check the usual suspects, (mass.gov, uk.gov, etc) plus any *recent* research or thinking.

Distinguish between the use of an icon (if used) that merely represents a link to offsite (wikipedia) and an icon that opens a new browser tab.

**Comment by chasechenevert** [comment]
Prepare for pin-up for next Tuesday, April 18

**Comment by chasechenevert** [comment]
Here are some resources I came across: 
[Opening external links: same tab or new?](https://www.caktusgroup.com/blog/2017/03/01/opening-external-links-same-tab-or-new/) This article contains a number of other links to further research. 
> The qualitative results of my inquiry suggest a split of preferences among users between the “same tab” and “new tab” behaviors. From the user experience perspective, the strongest (in my opinion) arguments in favor of opening outbound links in the same tab lie in accessibility and mobile use considerations. For most stakeholders, I suspect, the SEO argument outweighs any reasoning that stems from user experience. However, as the push for building accessible websites increases as does the rate at which users access content on mobile devices, stakeholders may find themselves between a rock and a hard place searching to strike a balance between attracting new audience through SEO efforts and retaining existing users by tending to their accessibility and mobile browsing needs.

[Should links open in new windows?](https://www.smashingmagazine.com/2008/07/should-links-open-in-new-windows/)
> No, they shouldn’t. At first glance the decision to open links in new windows or not depends on the given site and the preferences of its visitors.
