### ISSUE TITLE
Representing guides on topic & other pages

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1718]
### Residents should be able to distinguish and view when guides are available for the content that they are viewing, so the can navigate to it.

Guides are comprised of many pages, and may also be represented on one or more topics, and possibly topic collections. How do users distinguish a guide from other topic content? What form visually does a link to a guide take?

This issue covers how residents can see when guide are available when they are looking at related content on TOPIC COLLECTIONS.

Use "Get a mobile food vendor permit" as your example. Low fidelity is fine.

**Comment by toribr** [comment]
Edited to story format.

**Comment by chasechenevert** [comment]
### Near-term design solution
We'll utilize the current tile design to display the guide content without any icons or labels other than "Part of:" placed just below the page subtitle within the blue page banner block. 

**Dev spec**: [mobile](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/51aa2fb9-cba8-4f59-a726-f8be07fb39ff/Service-MVP-Mobile/), [web](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/ce9e7492-b75b-472c-9dab-98d7bd1843ba/Service-MVP-Web/)

<img width="1026" alt="Screen Shot 2019-06-05 at 10 34 55 AM" src="https://user-images.githubusercontent.com/7027270/58969693-be9af980-877d-11e9-9fcd-e56bca9ae963.png">
