### ISSUE TITLE
Write tests coverage for forms! 

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#1721]
**Objective** 
We ought to have some decent unit test coverage of all the new functionality we've introduced into us-forms-system

I'll be frank, I'm pretty light on writing unit tests in real-world apps, especially in Javascript. There is some testing infrastructure we can utilize in the us-forms-system repo but it would be good to collaborate on some of this and plan out some tests to write. 

**Participants**
@sergiogcx 
@briaguya 
@Niicck 

**Agenda**

- Look at the current tests and libraries used in us-forms-system, decide if we want to tweak anything for our benefit (I've done this a little already)
- Look at our existing components without tests and evaluate what we should write some tests for
- Make an issue for writing each test
----- 
- [ ] File Upload
- [ ] Location picker
- [ ] Calendar/DateTIme

------
- [ ] Schedule meeting
- [ ] Meet
- [ ] Create resulting issues
-----

**Comment by desigonz** [comment]
Gonna close this because it's specific to OPO and by the time we get to this, we'll probably be refactoring or switching the form to formstack.
