### ISSUE TITLE
ARR Waste + Businesses info page

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1725]
Pieced out from enterprise resource guide, original Austin Materials Marketplace info page. 

Draft https://docs.google.com/document/d/1JvGfOPZvQldi3k97bBopyYizwzNqQwYX581bPrbwcBY/edit#

@LauraTrujillo FYI on issue creation. Moving to Backlog Medium

**Comment by gabrielaperezdelaosa** [comment]
I don't understand this page and don't really see the user story for it. It seems like just a linkout to https://austinmaterialsmarketplace.org/.
