### ISSUE TITLE
Janis/Joplin - Figure out preview cache/routing that doesn't break redundancy

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1726]
We need to find a way to work with react-static/router and cloudfront so that we can have redundancy for our statically generated pages and also not break our previews when we make model changes.

**Comment by sergiogcx** [comment]
To solve this problem, all we need is to have a fine-grained policy to not resolve for 404 errors.

Redundancy should be there only as a backup in case the website is not working. In terms of content (new routes, old routes) that should be handled by the newly built site. If the site is indeed broken, then we have the option to use a backup from the origin group.

Also, the backup serves the purpose of being available in case there are configuration errors in the bucket, 403 (permission errors), 5xx (some kind of server, code error). Then those requests should he handled by the backup.

Simply by turning off the 404 flag, we can let the primary site deal with the routes:

![AWS_CloudFront_Management_Console.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/dc4940df-b2ab-429a-a267-6b6a7268c289)
