### ISSUE TITLE
Implement react-intl for coa-forms repo

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1727]
Use the react-intl library to handle our translations.

This could streamline our deployment process and eliminate the risk of difficult bugs in the future (like when translating to Spanish broke the timePicker that one time).

This might help our implementation of #1279

**Comment by Niicck** [comment]
Icebox for now. The future translation workflow should look similar to Janis- we should allow content to make translation changes from within Joplin.

**Comment by Niicck** [comment]
Another Issue that was made much more complicated by not having this feature: https://github.com/cityofaustin/techstack/issues/1601

**Comment by desigonz** [comment]
consolidated this into #1722
