### ISSUE TITLE
Add Mobile/Tablet Placeholder RelatedTo and OfferedBy to Service Page

### ISSUE THREAD

**Issue by pibemillo** [cityofaustin/techstack#1730]
https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/51aa2fb9-cba8-4f59-a726-f8be07fb39ff/Service-MVP-Mobile/

<img width="432" alt="Screen Shot 2019-05-10 at 3 55 44 PM" src="https://user-images.githubusercontent.com/6384156/57556285-366f3300-733c-11e9-83fe-4a35d3ad83dc.png">
just so we know the part we're talking about

**Comment by easherma** [comment]
Offered by is pending model updates
