### ISSUE TITLE
Design general error page

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#174]
Residents may encounter an error page if a link is broken or a page is not working. Need to design content and layout.
##Initial mocks:
![alpha_L_404.png](https://images.zenhubusercontent.com/5a96f9e34b5806bc2bc8d56d/93885e1b-92c1-4e07-ada5-661aefee0a85)![alpha_M_404.png](https://images.zenhubusercontent.com/5a96f9e34b5806bc2bc8d56d/8dbd6026-934e-4fbe-afba-9cfda5960ef2)![alpha_S_404.png](https://images.zenhubusercontent.com/5a96f9e34b5806bc2bc8d56d/ae114f4c-bf80-4ef4-bffb-57a7ad94f1a7)

##Notes from slack conversation
– Capitalize "We"
– It feels like a total dead end that would reduce their trust in the site, but they'll probably face it a lot during alpha. Add something like "Because "alpha" means we're still working on the site, we're probably working on this page right now, it should be back up shortly. Feel free to leave a note alerting us to this by submitting an online request"
– if you want to say "our system will notify us that you hit this error" instead of "you can let us know if you want", that could satisfy that part. It's just letting them know this isn't going into a black hole, something will actually be done about it and they'll be able to use this page in the future

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] Refine language
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://desi1.aha.io/features/RT-341

**Comment by amenity** [comment]
This may connect to #251 and or the error page- same content type?

**Comment by chasechenevert** [comment]
See issue: #1100
