### ISSUE TITLE
Draft "help people experiencing homelessness" service page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1741]
Draft lives here: https://docs.google.com/document/d/1i_luJEQskZk5XjH_4Vyhhv97aD_E9D-pjC9b5dFJRK4/edit?usp=sharing

**Comment by desigonz** [comment]
Will be reviewing with Taylor and Sarah Rodriguez on Monday, 5/13

**Comment by desigonz** [comment]
Assigning [this draft](https://docs.google.com/document/d/1i_luJEQskZk5XjH_4Vyhhv97aD_E9D-pjC9b5dFJRK4/edit?usp=sharing) to @JeffCopy for first review.

**Comment by JeffCopy** [comment]
my suggestions included in the google doc, thanks!

**Comment by desigonz** [comment]
Thanks @JeffCopy! Assigning to @LauraTrujillo for second review.

**Comment by LauraTrujillo** [comment]
@desigonz looks great!! Wondering about moving the "Practice Safety" content to be a numbered step instead of supporting content, but I'll defer to you.

**Comment by desigonz** [comment]
Thanks @LauraTrujillo!
