### ISSUE TITLE
Incorporate catch-all guidelines into style guide or workshops

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1742]
https://docs.google.com/document/d/1-k60yWKNyvv9C9a-ZyZv0g2G5gl9uFi6zXAMqGkDkfw/edit?usp=sharing

**Comment by srigdon** [comment]
We touch on this a bit in Funshop I: Writing for residents, but the deck could use a review and refresh for more recent examples and any project communication needs. 

But this looks like a mostly finished Style Guide entry already, with good info for city content authors. @Jo-Dwyer and @ablangworthy27, what do you think about adding it in?

**Comment by desigonz** [comment]
"Catch-all page" is our term—y'all might want to think about titling it something more meaningful. I'll put this on next sprint candidates for now.

**Comment by ablangworthy27** [comment]
I just edited this draft and incorporated into the style guide
