### ISSUE TITLE
Police Oversight: Change CloudFront Origins to new stack (master/staging)

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/techstack#1746]
Switch CloudFront origins to new stack, from current master bucket to new master bucket (coa platform)

**Comment by sergiogcx** [comment]
This has been done in the past two days, ready for review.

Details:
The origins had to be added for all four forms; also, each form needed to be tested.

**Comment by easherma** [comment]
@sergiogcx can we indicate the best way to test this for QA? Any particular routes to check or do we just sign off if it all is working normally?

**Comment by sergiogcx** [comment]
For master, sign off if all works correctly. For prod, Nick and I will sign off if all is nominal.
