### ISSUE TITLE
RT on iPhone 6: Safari 11

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1751]
Here are them features to test:
- [x] /introduction
  - [x] Do the accordion buttons work?
- [x] /what-happened
  - [x] Are "Required" fields required? (Can you not proceed until you've filled out an answer?)
  - [x] DatePicker
    - [x] Can you enter a date?
    - [x] Does it autocorrect if you try to enter a future date?
    - [x] Does it autocorrect if you try to enter a date that doesn't exist (like February 31st)?
    - [ ] Is the date entered reflected in the calendar?
    - [ ] Is the date selected in the calendar reflected in the input boxes?
  - [x] TimePicker
    - [x] Can you enter a time?
    - [x] Are you prevented from entering a fake time?
  - [x] Received a Ticket
    - [x] Enter the name of your device+Browser as the name of ticket. That way we can trace the email response back to you if there was a problem.
- [x] /where-happened
  - [x] Are "Required" fields required? (Can you not proceed until you've filled out an answer?)
  - [x] LocationPicker
    - [x] Can you set a location by entering the "Four Seasons"?
    - [x] Can you set a location by entering "800 Guadalupe"?
    - [x] Can you set a location by dragging the icon somewhere?
    - [x] If you clear/x out the location, does the page prevent you from going forward?
- [x] /share-evidence
  - [x] Gosh darn it, its still called /share-evidence, didn't we change that already?
  - [x] Can you upload a picture?
  - [x] Can you upload a *second* picture?
- [x] /officer-details
  - [x] Can you enter all information about 2 officers?
- [x] /witness-details
  - [x] Can you enter all information about 2 witnesses?
- [x] /about-you
  - [x] Can you enter all information about 1 yourself?
  - [x] Maybe do like 1 or 2 runs (out of the 4 forms) where you don't enter your information here, but wait until the final email submission form to see if that works.
- [x] /review-and-submit
  - [x] Is all your information there?
- [x] /confirmation
  - [x] See if that email input thing works for the runs where you didn't enter personal information.
- [x] Check your email
  - [x] Did you get an email with your confirmation number?
  - [x] Does the copy of your report have all the stuff you entered in it?
  - [ ] If not, double check with Sergio, because I think he's still getting all of our staging emails.
- [x] Modal
  - [x] Does the modal pop up when you try to switch languages when you've entered data?
  - [x] Does it let you switch to another language if you say "Yes"?
- [x] Spanish Form Considerations
  - [x] Is it in Spanish? (Did all of our text translations work?)

Sprint-specific considerations to kinda watch out for:
- [x] https://github.com/cityofaustin/techstack/issues/1644
  - Covered by regression testing. Basically make sure the map on /where-happened works when you enter an address.
- [x] https://github.com/cityofaustin/techstack/issues/1743
  - Covered by regression testing. Basically make sure the file uploader on /share-evidence works.
- [x] https://github.com/cityofaustin/techstack/issues/1086
  - Covered by regression testing. Basically make sure the datepicker on /what-happened works.
- [x] https://github.com/cityofaustin/techstack/issues/1591
  - Covered by regression testing. Basically make sure the calender icon selector thing still works on /what-happened.
- [x] https://github.com/cityofaustin/techstack/issues/1579
  - Covered by regression testing. Basically make sure that location is still required on /where-happened even if you clear out your location.

**Comment by annieszot** [comment]
I'm doing RT

**Comment by annieszot** [comment]
all 4 forms (complaint, thanks, queja, agradezca)
- [ ] complaint
- [ ] thanks
- [ ] queja
- [ ] agradezca

**Comment by annieszot** [comment]
![Screen Shot 2019-04-24 at 4 10 32 PM](https://user-images.githubusercontent.com/46934140/56701466-fd408d00-66c4-11e9-9b98-10194d2cfaf0.png)
![Screen Shot 2019-04-24 at 4 38 51 PM](https://user-images.githubusercontent.com/46934140/56701467-fd408d00-66c4-11e9-836b-c2d277ca1af7.png)
![Screen Shot 2019-04-24 at 4 43 19 PM](https://user-images.githubusercontent.com/46934140/56701468-fd408d00-66c4-11e9-83f1-2b116245f8a9.png)
![Screen Shot 2019-04-24 at 4 46 15 PM](https://user-images.githubusercontent.com/46934140/56701470-fd408d00-66c4-11e9-9c26-dfebd2eeba7b.png)
![Screen Shot 2019-04-24 at 4 47 31 PM](https://user-images.githubusercontent.com/46934140/56701471-fd408d00-66c4-11e9-8e9c-7a4b0af5835a.png)
![Screen Shot 2019-04-24 at 5 14 15 PM](https://user-images.githubusercontent.com/46934140/56701472-fd408d00-66c4-11e9-85a9-298bf3256f7b.png)
![Screen Shot 2019-04-24 at 5 17 16 PM](https://user-images.githubusercontent.com/46934140/56701473-fd408d00-66c4-11e9-9860-3c153f10f4c3.png)
![Screen Shot 2019-04-24 at 5 18 28 PM](https://user-images.githubusercontent.com/46934140/56701474-fdd92380-66c4-11e9-8422-f03ec64ccf38.png)
![Screen Shot 2019-04-24 at 5 20 14 PM](https://user-images.githubusercontent.com/46934140/56701475-fdd92380-66c4-11e9-9b0d-e453ea173161.png)
![Screen Shot 2019-04-24 at 5 22 02 PM](https://user-images.githubusercontent.com/46934140/56701476-fdd92380-66c4-11e9-959a-1df6783d258c.png)
![Screen Shot 2019-04-24 at 5 25 37 PM](https://user-images.githubusercontent.com/46934140/56701478-fdd92380-66c4-11e9-8623-2d45e68d9709.png)
![Screen Shot 2019-04-24 at 5 25 49 PM](https://user-images.githubusercontent.com/46934140/56701479-fdd92380-66c4-11e9-9c95-cbdf466a4c53.png)
![Screen Shot 2019-04-24 at 5 26 09 PM](https://user-images.githubusercontent.com/46934140/56701480-fdd92380-66c4-11e9-9699-1b85287beed7.png)
![Screen Shot 2019-04-24 at 5 27 08 PM](https://user-images.githubusercontent.com/46934140/56701481-fe71ba00-66c4-11e9-8f29-ee441aa9e129.png)
![Screen Shot 2019-04-24 at 5 27 25 PM](https://user-images.githubusercontent.com/46934140/56701482-fe71ba00-66c4-11e9-8b9e-fb25df011647.png)
![Screen Shot 2019-04-24 at 5 33 27 PM](https://user-images.githubusercontent.com/46934140/56701483-fe71ba00-66c4-11e9-90ce-e35f71d26c0e.png)
![Screen Shot 2019-04-24 at 5 42 29 PM](https://user-images.githubusercontent.com/46934140/56701484-fe71ba00-66c4-11e9-8095-aa4b8428bcf1.png)
![Screen Shot 2019-04-24 at 5 43 36 PM](https://user-images.githubusercontent.com/46934140/56701485-fe71ba00-66c4-11e9-810d-a9e9d8f3c0cd.png)
![Screen Shot 2019-04-24 at 5 45 07 PM](https://user-images.githubusercontent.com/46934140/56701486-fe71ba00-66c4-11e9-92c3-91525266d18b.png)
![Screen Shot 2019-04-24 at 5 46 59 PM](https://user-images.githubusercontent.com/46934140/56701487-fe71ba00-66c4-11e9-8144-458825fe9f1b.png)
![Screen Shot 2019-04-24 at 5 53 28 PM](https://user-images.githubusercontent.com/46934140/56701488-ff0a5080-66c4-11e9-84c1-c9c6a57539b1.png)
![Screen Shot 2019-04-24 at 5 56 40 PM](https://user-images.githubusercontent.com/46934140/56701489-ff0a5080-66c4-11e9-8a64-e769e31b9cff.png)
![Screen Shot 2019-04-24 at 5 57 14 PM](https://user-images.githubusercontent.com/46934140/56701491-ff0a5080-66c4-11e9-9261-52201aebe368.png)
![Screen Shot 2019-04-24 at 5 58 06 PM](https://user-images.githubusercontent.com/46934140/56701492-ff0a5080-66c4-11e9-91fc-07c6b043a0ce.png)
![Screen Shot 2019-04-24 at 6 06 18 PM](https://user-images.githubusercontent.com/46934140/56701493-ff0a5080-66c4-11e9-81d2-eb5b886bd6e6.png)
![Screen Shot 2019-04-24 at 6 07 09 PM](https://user-images.githubusercontent.com/46934140/56701494-ff0a5080-66c4-11e9-8f04-c3ee57e281e2.png)
![Screen Shot 2019-04-24 at 6 07 36 PM](https://user-images.githubusercontent.com/46934140/56701496-ffa2e700-66c4-11e9-9507-d5220f9e7e9c.png)
![Screen Shot 2019-04-24 at 6 14 37 PM](https://user-images.githubusercontent.com/46934140/56701497-ffa2e700-66c4-11e9-98e8-12ceea05fde4.png)
![Screen Shot 2019-04-24 at 6 16 57 PM](https://user-images.githubusercontent.com/46934140/56701498-ffa2e700-66c4-11e9-838d-9e9c53e46084.png)
![Screen Shot 2019-04-24 at 6 17 15 PM](https://user-images.githubusercontent.com/46934140/56701499-ffa2e700-66c4-11e9-83a6-0b9f37e7f0c7.png)
![Screen Shot 2019-04-24 at 6 18 20 PM](https://user-images.githubusercontent.com/46934140/56701500-ffa2e700-66c4-11e9-81fd-c698c8b531b1.png)
![Screen Shot 2019-04-24 at 6 23 12 PM](https://user-images.githubusercontent.com/46934140/56701501-003b7d80-66c5-11e9-8739-572b2df07377.png)
![Screen Shot 2019-04-24 at 6 30 47 PM](https://user-images.githubusercontent.com/46934140/56701502-003b7d80-66c5-11e9-8cac-a5df32de4ce8.png)
![Screen Shot 2019-04-24 at 6 31 42 PM](https://user-images.githubusercontent.com/46934140/56701503-003b7d80-66c5-11e9-9c04-c9521412b138.png)

**Comment by annieszot** [comment]
Bugs reported 
#1791 
#1792
~~#1793~~ Datepicker works and automatically prevents future dates/fixes fake dates (ex. 2/29/2019 to 3/01/2019 etc)
