### ISSUE TITLE
RT MacOS 10.14: Chrome 71.0

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1756]
Here are them features to test:
- [x] /introduction
  - [x] Do the accordion buttons work?
- [x] /what-happened
  - [x] Are "Required" fields required? (Can you not proceed until you've filled out an answer?)
  - [x] DatePicker
    - [x] Can you enter a date?
    - [x] Does it autocorrect if you try to enter a future date?
    - [x] Does it autocorrect if you try to enter a date that doesn't exist (like February 31st)?
    - [x] Is the date entered reflected in the calendar?
    - [x] Is the date selected in the calendar reflected in the input boxes?
  - [x] TimePicker
    - [x] Can you enter a time?
    - [x] Are you prevented from entering a fake time?
  - [x] Received a Ticket
    - [x] Enter the name of your device+Browser as the name of ticket. That way we can trace the email response back to you if there was a problem.
- [x] /where-happened
  - [x] Are "Required" fields required? (Can you not proceed until you've filled out an answer?)
  - [x] LocationPicker
    - [x] Can you set a location by entering the "Four Seasons"?
    - [x] Can you set a location by entering "800 Guadalupe"?
    - [x] Can you set a location by dragging the icon somewhere?
    - [x] If you clear/x out the location, does the page prevent you from going forward?
- [x] /share-evidence
  - [x] Gosh darn it, its still called /share-evidence, didn't we change that already?
  - [x] Can you upload a picture?
  - [x] Can you upload a *second* picture?
- [x] /officer-details
  - [x] Can you enter all information about 2 officers?
- [x] /witness-details
  - [x] Can you enter all information about 2 witnesses?
- [x] /about-you
  - [x] Can you enter all information about 1 yourself?
  - [x] Maybe do like 1 or 2 runs (out of the 4 forms) where you don't enter your information here, but wait until the final email submission form to see if that works.
- [x] /review-and-submit
  - [x] Is all your information there?
- [x] /confirmation
  - [x] See if that email input thing works for the runs where you didn't enter personal information.
- [x] Check your email
  - [x] Did you get an email with your confirmation number?
  - [x] Does the copy of your report have all the stuff you entered in it?
  - [x] If not, double check with Sergio, because I think he's still getting all of our staging emails.
- [x] Modal
  - [x] Does the modal pop up when you try to switch languages when you've entered data?
  - [x] Does it let you switch to another language if you say "Yes"?
- [x] Spanish Form Considerations
  - [x] Is it in Spanish? (Did all of our text translations work?)

Sprint-specific considerations to kinda watch out for:
- [x] https://github.com/cityofaustin/techstack/issues/1644
  - Covered by regression testing. Basically make sure the map on /where-happened works when you enter an address.
- [x] https://github.com/cityofaustin/techstack/issues/1743
  - Covered by regression testing. Basically make sure the file uploader on /share-evidence works.
- [x] https://github.com/cityofaustin/techstack/issues/1086
  - Covered by regression testing. Basically make sure the datepicker on /what-happened works.
- [x] https://github.com/cityofaustin/techstack/issues/1591
  - Covered by regression testing. Basically make sure the calender icon selector thing still works on /what-happened.
- [x] https://github.com/cityofaustin/techstack/issues/1579
  - Covered by regression testing. Basically make sure that location is still required on /where-happened even if you clear out your location.

**Comment by annieszot** [comment]
Links:
https://forms.austintexas.io/police-complain/introduction
https://forms.austintexas.io/policia-queja/introduccion
https://forms.austintexas.io/police-thank/introduction
https://forms.austintexas.io/policia-agradezca/introduccion

On each, make sure to:

  Fill out form with a police badge number and a zip code in the about you page.
  Check that those numbers show up on the review page.
  Make sure you can edit those numbers on the review page.
  Send a confirmation email to yourself.
  Make sure the confirmation email contains the numbers you entered.
Forms:

- [ ] complaint
- [ ] thanks
- [ ] queja
- [ ] agradezca

**Comment by annieszot** [comment]
Bugs reported: 
#1813

**Comment by annieszot** [comment]
Closing Issue

**Comment by annieszot** [comment]
Screenshots 
![Screen Shot 2019-04-25 at 9 08 50 PM](https://user-images.githubusercontent.com/46934140/56781318-6baa4b80-67a8-11e9-8b83-dc8d5ded5c68.png)
![Screen Shot 2019-04-25 at 9 09 43 PM](https://user-images.githubusercontent.com/46934140/56781320-6c42e200-67a8-11e9-98a9-66f1e97e3400.png)
![Screen Shot 2019-04-25 at 9 12 50 PM](https://user-images.githubusercontent.com/46934140/56781321-6c42e200-67a8-11e9-886d-106387cb5e9f.png)
![Screen Shot 2019-04-25 at 9 22 11 PM](https://user-images.githubusercontent.com/46934140/56781322-6c42e200-67a8-11e9-8025-fcbbafe07199.png)
![Screen Shot 2019-04-25 at 9 22 33 PM](https://user-images.githubusercontent.com/46934140/56781323-6c42e200-67a8-11e9-89d4-953598ced749.png)
![Screen Shot 2019-04-25 at 9 26 24 PM](https://user-images.githubusercontent.com/46934140/56781324-6cdb7880-67a8-11e9-8964-e44a75c3b086.png)
![Screen Shot 2019-04-25 at 9 27 43 PM](https://user-images.githubusercontent.com/46934140/56781325-6cdb7880-67a8-11e9-9875-ca663a5ab2ab.png)
![Screen Shot 2019-04-25 at 9 28 53 PM](https://user-images.githubusercontent.com/46934140/56781327-6cdb7880-67a8-11e9-9724-1364b5b111af.png)
![Screen Shot 2019-04-25 at 9 29 57 PM](https://user-images.githubusercontent.com/46934140/56781328-6cdb7880-67a8-11e9-9c44-03b414edecf6.png)
![Screen Shot 2019-04-25 at 9 36 47 PM](https://user-images.githubusercontent.com/46934140/56781329-6cdb7880-67a8-11e9-886d-28c5ca68a1be.png)
![Screen Shot 2019-04-25 at 9 37 00 PM](https://user-images.githubusercontent.com/46934140/56781330-6d740f00-67a8-11e9-8ed5-211b744beeda.png)
![Screen Shot 2019-04-25 at 9 39 10 PM](https://user-images.githubusercontent.com/46934140/56781331-6d740f00-67a8-11e9-9a53-4e9d22d86ab3.png)
![Screen Shot 2019-04-25 at 9 54 49 PM](https://user-images.githubusercontent.com/46934140/56781332-6d740f00-67a8-11e9-9a1e-f0642f707031.png)
![Uploading Screen Shot 2019-04-25 at 10.01.51 PM.png…]()
![Uploading Screen Shot 2019-04-25 at 10.02.08 PM.png…]()
![Uploading Screen Shot 2019-04-25 at 10.14.37 PM.png…]()
![Uploading Screen Shot 2019-04-25 at 10.14.40 PM.png…]()
