### ISSUE TITLE
RT MacOS 10.14: Safari

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1757]
Here are them features to test:
- [ ] /introduction
  - [x] Do the accordion buttons work?
- [ ] /what-happened
  - [x] Are "Required" fields required? (Can you not proceed until you've filled out an answer?)
  - [ ] DatePicker
    - [x] Can you enter a date?
    - [x] Does it autocorrect if you try to enter a future date?
    - [x] Does it autocorrect if you try to enter a date that doesn't exist (like February 31st)?
    - [x] Is the date entered reflected in the calendar?
    - [x] Is the date selected in the calendar reflected in the input boxes?
  - [ ] TimePicker
    - [x] Can you enter a time?
    - [x] Are you prevented from entering a fake time?
  - [ ] Received a Ticket
    - [x] Enter the name of your device+Browser as the name of ticket. That way we can trace the email response back to you if there was a problem.
- [ ] /where-happened
  - [x] Are "Required" fields required? (Can you not proceed until you've filled out an answer?)
  - [ ] LocationPicker
    - [x] Can you set a location by entering the "Four Seasons"?
    - [x] Can you set a location by entering "800 Guadalupe"?
    - [x] Can you set a location by dragging the icon somewhere?
    - [x] If you clear/x out the location, does the page prevent you from going forward?
- [ ] /share-evidence
  - [x] Gosh darn it, its still called /share-evidence, didn't we change that already?
  - [x] Can you upload a picture?
  - [x] Can you upload a *second* picture?
- [ ] /officer-details
  - [x] Can you enter all information about 2 officers?
- [ ] /witness-details
  - [x] Can you enter all information about 2 witnesses?
- [ ] /about-you
  - [x] Can you enter all information about 1 yourself?
  - [x] Maybe do like 1 or 2 runs (out of the 4 forms) where you don't enter your information here, but wait until the final email submission form to see if that works.
- [ ] /review-and-submit
  - [x] Is all your information there?
- [ ] /confirmation
  - [x] See if that email input thing works for the runs where you didn't enter personal information.
- [ ] Check your email
  - [x] Did you get an email with your confirmation number?
  - [x] Does the copy of your report have all the stuff you entered in it?
  - [ ] If not, double check with Sergio, because I think he's still getting all of our staging emails.
- [ ] Modal
  - [x] Does the modal pop up when you try to switch languages when you've entered data?
  - [x] Does it let you switch to another language if you say "Yes"?
- [ ] Spanish Form Considerations
  - [x] Is it in Spanish? (Did all of our text translations work?)

Sprint-specific considerations to kinda watch out for:
- [ ] https://github.com/cityofaustin/techstack/issues/1644
  - Covered by regression testing. Basically make sure the map on /where-happened works when you enter an address.
- [ ] https://github.com/cityofaustin/techstack/issues/1743
  - Covered by regression testing. Basically make sure the file uploader on /share-evidence works.
- [ ] https://github.com/cityofaustin/techstack/issues/1086
  - Covered by regression testing. Basically make sure the datepicker on /what-happened works.
- [ ] https://github.com/cityofaustin/techstack/issues/1591
  - Covered by regression testing. Basically make sure the calender icon selector thing still works on /what-happened.
- [ ] https://github.com/cityofaustin/techstack/issues/1579
  - Covered by regression testing. Basically make sure that location is still required on /where-happened even if you clear out your location.

**Comment by oliver2g** [comment]
@desigonz quick follow-up on this. do we still need to do run this test in this OS/browser?

**Comment by desigonz** [comment]
Here's what @easherma said when I asked about it: "it would be nice, but I was thinking we could just save it to be the test for this release overall. we arent making big changes so I think a single round on a single browser is fine."

@Niicck might have different thoughts on whether we should do one or multiple browsers. Either way, we could rename this issue to "OPO 2.1.1 QA/regression test" or something similar.

**Comment by Niicck** [comment]
I'm with Eric. It'd be nice to do testing on Safari. But in general, it would be overkill to do multi browser regression testing for small releases

**Comment by oliver2g** [comment]
@easherma looks good, let's push to prod
