### ISSUE TITLE
Mock up service pages with map "app"/module

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#176]
![alpha_S_4.0_Service_dropoff.png](https://images.zenhubusercontent.com/5a96f9e34b5806bc2bc8d56d/efad4a78-0416-44fc-b73b-c7c837f67695)![alpha_S_4.0_Service_pickup.png](https://images.zenhubusercontent.com/5a96f9e34b5806bc2bc8d56d/35355d66-ba10-4145-b647-869a6692239b)

**Comment by cthibaultatx** [comment]
@LauraTrujillo @courtneyjacinic @ashleecoa ready to review the UX for these two service pages with map module

**Comment by LauraTrujillo** [comment]
@cthibaultatx Looks good to me!

**Comment by courtneyjacinic** [comment]
@cthibaultatx lookin' good. Thanks for incorporating our feedback from the last review!

**Comment by cthibaultatx** [comment]
@ashleecoa didn't get your review but moving task to "closed"
