### ISSUE TITLE
Police Oversight: Fix translation thank you form

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/techstack#1760]
It appears there is a problem with one of the translations in the Thank you form:

![Screen Shot 2019-04-24 at 2.00.51 AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/0f005128-d08e-471b-9eb8-e8feb4185492)

**Comment by sergiogcx** [comment]
Fixed in PR:
https://github.com/cityofaustin/coa-forms/pull/12

Fix in action:
https://opo.austintexas.io/policia-agradezca/1760-sg-coaf-thankyoutranslation/introduccion

Screenshot:
![Screen Shot 2019-04-24 at 2.08.28 AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/56da8317-ef39-46ea-933f-0d2121653ad0)

**Comment by annieszot** [comment]
I'm doing QA 
Mobile:
- [ ] iPhone 6: Safari 11 (Previously Safari 12)
  - [ ] English
  - [ ] Spanish 
- [ ] Android (Galaxy 8): Chrome 7
  - [ ] English
  - [ ] Spanish 

Desktop:
- [ ] Windows 10: Chrome 71.0
  - [ ] English
  - [ ] Spanish
- [ ] Windows 7: Chrome 71.0;
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 7: Internet Explorer 11
  - [ ] English
  - [ ] Spanish 
- [ ] MacOS 10.14: Chrome 71.0
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Edge 17.17; 
  - [ ] English
  - [ ] Spanish 
- [ ] Windows 10: Internet Explorer 11
  - [ ] English
  - [ ] Spanish

**Comment by annieszot** [comment]
Good job! 
![Screen Shot 2019-04-24 at 11 27 30 PM](https://user-images.githubusercontent.com/46934140/56709951-8a95d880-66e9-11e9-8753-99ee45f06f9c.png)
![Screen Shot 2019-04-24 at 11 28 27 PM](https://user-images.githubusercontent.com/46934140/56709952-8b2e6f00-66e9-11e9-873b-a1b9761bdcf7.png)
![Screen Shot 2019-04-24 at 11 29 13 PM](https://user-images.githubusercontent.com/46934140/56709953-8bc70580-66e9-11e9-95d2-aa80249db4a8.png)
![Screen Shot 2019-04-24 at 11 30 31 PM](https://user-images.githubusercontent.com/46934140/56709954-8bc70580-66e9-11e9-80bb-a602f56264c7.png)
![Screen Shot 2019-04-24 at 11 31 10 PM](https://user-images.githubusercontent.com/46934140/56709955-8bc70580-66e9-11e9-867e-f7ab0005a111.png)
![Screen Shot 2019-04-24 at 11 32 19 PM](https://user-images.githubusercontent.com/46934140/56709956-8bc70580-66e9-11e9-86a3-4ee8d976b998.png)
![Screen Shot 2019-04-24 at 11 33 12 PM](https://user-images.githubusercontent.com/46934140/56709957-8cf83280-66e9-11e9-8343-4268342c9746.png)
![Screen Shot 2019-04-24 at 11 33 57 PM](https://user-images.githubusercontent.com/46934140/56709958-8cf83280-66e9-11e9-96aa-83b3715d35de.png)
Closing
