### ISSUE TITLE
Map Component Location clearing breaks on Windows/IE 11

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1762]
**Describe the bug**

There are 2 "x" boxes when you enter some locations into the LocationSelector. 

There was one moment when I cleared the inner x, and the map broke. I couldn't enter a new location and I couldn't proceed with the form. I have been unable to recreate this issue, so it might be rare. Still, the 2nd inner "x" should be gotten rid of.

**URL**
https://forms.austintexas.io/police-complain/where-happened

**To Reproduce**

1. Go to /where-happened

**Current behavior**

Clearing 

**Expected behavior**

There should only be one "x" box to clear a location. And you should be able to enter another location after clearing it.

**Screenshots**

![Screen Shot 2019-04-24 at 3.34.27 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/02b0a8e3-cb7d-4d82-95c0-57cf7844870b)

**Device**

Windows 10, IE 11

**Additional context**

This (sometimes, rarely, exceptionally) prevents users from continuing the form.

**Comment by easherma** [comment]
Addressed in https://github.com/cityofaustin/us-forms-system/tree/IE-11-fix
https://stackoverflow.com/questions/41900431/disable-ie-11-input-clear-x-button

**Comment by Niicck** [comment]
Already merged in, but I'm QAing it now.
