### ISSUE TITLE
Confirmation email is not correct for some fields

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1763]
**Describe the bug**

+ The heading `Ticket number:` should be `Your name as it appears on the ticket`
+ Should `Race: Other` display the actual race entered?

**To Reproduce**
Fill out a form with a ticket name on /what-happened and add a badge number to an officer. Then check your confirmation email.

**Current behavior**

**Expected behavior**

It should show your information on the confirmation email.

**Screenshots**

![Screen Shot 2019-04-24 at 4.00.39 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/47176ca6-0f90-4307-aced-a95417b28579)

![Screen Shot 2019-04-24 at 4.01.13 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/67b8e2c0-f5bd-4284-b6bb-7ac222518ab4)

![Screen Shot 2019-04-24 at 4.20.19 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/43abf4cd-f5da-4652-b418-5aaf6aa18426)

**Device**

Windows 10, IE 11

**Additional context**

**Comment by Niicck** [comment]
I think the badge number display is a different issue unrelated to the backend service parsing: https://github.com/cityofaustin/techstack/issues/1771

**Comment by desigonz** [comment]
Ticket number label happening in Spanish too. It should read `Nombre como aparece en la infracción`

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/ac86c5ba-1e8e-42b1-afef-17e3c5c64293)
