### ISSUE TITLE
Our form validations aren't in Spanish

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1764]
**Describe the bug**

Our form validations aren't in Spanish

**URL**
https://forms.austintexas.io/policia-queja/detalles-testigos
**To Reproduce**

Make a validation error on the /detalles-testigos

**Current behavior**

Error messages are in English.

**Expected behavior**

Show error messages in Spanish.

**Screenshots**

![Screen Shot 2019-04-24 at 4.15.21 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/e4324284-7e42-4152-b6c3-ebc53eb45f8c)

**Device**

Windows 10, IE 11

**Comment by easherma** [comment]
Related: #1727 
https://github.com/usds/us-forms-system/issues/170

**Comment by easherma** [comment]
@desigonz 
For 'This field should be at least x characters(s)', we need a translation. Want to whip something up?

**Comment by easherma** [comment]
https://github.com/cityofaustin/coa-forms/pull/20 <--- adds in a fix for email. We'll need translations for other error messages, like the 'field should be at least x' example above

**Comment by desigonz** [comment]
`Por favor ingrese una dirección de correo electrónico válida`

`This field should be at least 10 characters` (<---- get rid of the parentheticals around "s" on "characters")

`Este campo debe tener por lo menos diez caracteres`

**Comment by oliver2g** [comment]
Still broken @easherma 
1. Correo electronico: wording doesn't match what @desigonz translated above:
Desi's: "Por favor ingrese una dirección de correo electrónico válida"
Staging: "Por favor provea una dirección válida

2. Numero de telefono:
"10 character(s)" should be "diez caracteres"

![Screen Shot 2019-05-09 at 2 20 10 PM](https://user-images.githubusercontent.com/35782646/57480552-b4acd600-7265-11e9-97f3-334c845076e1.png)

**Comment by easherma** [comment]
Should be fixed in staging now:
![form](https://user-images.githubusercontent.com/10539855/57555016-a7145080-7338-11e9-8ad6-b34991f44bd3.png)

**Comment by desigonz** [comment]
Verified that it's fixed on staging, closing this issue.
