### ISSUE TITLE
Error message on map

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1765]
**Describe the bug**
Error message reads "is not of a type(s) string"

**To Reproduce**

1. Go to 'Where were you?' page
2. Move map to a location
3. Click X to remove location

**Current behavior**
See error message

**Expected behavior**
No error message until you try submitting the page.

**URL tested:** https://forms.austintexas.io/police-complain/where-happened

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=7.0&device=Samsung+Galaxy+S8&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-complain%2Fwhere-happened&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-complain/where-happened) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Samsung Galaxy S8 |
| Browser | Mobile_chrome |
| Operating System | Android 7.0 |
| Resolution | 1440 x 2960 px |
| Screen size | 5.8 in - 2.5 x 5.2 in |
| Viewport | 360 x 740 dp |
| Aspect Ratio | 18.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/bcc93a1b191381b094639c647ea5ed5bd55a857c/realdroid_Samsung_Galaxy_S8.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/bcc93a1b191381b094639c647ea5ed5bd55a857c/realdroid_Samsung_Galaxy_S8.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=android&os_version=7.0&device=Samsung+Galaxy+S8&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-complain%2Fwhere-happened&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-complain/where-happened) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
This one could be a pain but hopefully we can just set a more custom error. We should check if this happens on any other devices and get more clarity on a precise definition of the problem.

**Comment by desigonz** [comment]
I was able to only reproduce it twice...would love if you gave it a shot.

**Comment by desigonz** [comment]
Also, I think just changing the messaging might be a good solution @easherma

**Comment by desigonz** [comment]
This happened again on Windows 7 IE 11

To reproduce:
1. go to where page
2. type four seasons and press enter (will fill in address)
3. X out the address field

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/85724b04-c16a-4d95-9bf9-69a1b18c7377)
