### ISSUE TITLE
Map zoom buttons are inconsistent on review page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1767]
The review page + and - zoom buttons are styled differently than "Where were you?" page

**URL tested:** https://forms.austintexas.io/police-complain/review-and-submit

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=7.0&device=Samsung+Galaxy+S8&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-complain%2Freview-and-submit&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-complain/review-and-submit) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Samsung Galaxy S8 |
| Browser | Mobile_chrome |
| Operating System | Android 7.0 |
| Resolution | 1440 x 2960 px |
| Screen size | 5.8 in - 2.5 x 5.2 in |
| Viewport | 360 x 740 dp |
| Aspect Ratio | 18.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/797988faf45dfdf1d7475212439425f97d562f3c/realdroid_Samsung_Galaxy_S8.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/797988faf45dfdf1d7475212439425f97d562f3c/realdroid_Samsung_Galaxy_S8.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=android&os_version=7.0&device=Samsung+Galaxy+S8&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-complain%2Freview-and-submit&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-complain/review-and-submit) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
This is a dupe
