### ISSUE TITLE
Police Badge Number is not being Saved

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1771]
**Describe the bug**

Something is going wrong with the police badge number.

1. Police number is not persisted on the confirmation email or the review page.
2. It gets cleared out if you select a "uniformed" status from focusing on the badge number box.

**URL**

**To Reproduce**

1. Fill out form with a police badge number. Check confirmation email - N/A badge number
Also:
1. Try to enter a badge number on the review page
Also:
1. Select a "uniformed" status while your cursor is focused on the badge number input. The number you entered will disappear.

**Screenshots**

Review Page Bug:
![review page badge.gif](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/3e0056bc-d4a2-4c9a-86a3-b7c3557a1981)

"Uniformed" Selection Bug:
![uniformed breaks badge.gif](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/d853d41a-5ebc-49d0-8f31-3891970eb593)

**Device**

Windows 10, IE 11

**Comment by easherma** [comment]
@Niicck your example is Spanish, do we know if this problem happens on both English and Spanish versions of the form?

**Comment by Niicck** [comment]
Yes, it's a problem on both versions of the form.

**Comment by Niicck** [comment]
Same issue for zip code too. Not saving when you enter it in /about-you, getting cleared out when you jump to fill out the next part, not being able to enter it at all on the review page.

![codigo postal.gif](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/cfaebcfd-6cac-40b3-be20-a5188f07e631)

**Comment by Niicck** [comment]
QA Process:

cityofaustin/techstack#1771

Primarily concerning
- badge numbers for officers
- zip code for about-you

Browser:
Windows 10, IE 11

Link to pr deployment:
https://opo.austintexas.io/police-complain/1771-badge/

QA Test Criteria:
1. Fill out form with a police badge number and a zip code in the about you page.
2. Check that those numbers show up on the review page.
3. Make sure you can edit those numbers on the review page.
4. Send a confirmation email to yourself.
5. Make sure the confirmation email contains the numbers you entered.

Once this Review/QA is confirmed, then we'll merge it into master and close this issue.

**Comment by desigonz** [comment]
Approved! @Niicck I already merged the PR request but I'll let you close this one when you're ready :)
