### ISSUE TITLE
Dotted lines in IE 11

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1773]
We get weird dotted outlines whenever we click on any part of a page in IE 11.
Noticed on https://forms.austintexas.io/police-thank/what-happened

![Screen Shot 2019-04-24 at 5.16.37 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/53a57f7b-9705-4899-926c-c08b53d37a3c)

Might need to make a change to the outline css property. Make sure it doesn't break other boundaries that we have.
Ref: https://stackoverflow.com/questions/8911906/css-ie-remove-the-dotted-lines-when-select-something-in-ie

**Device**
Windows 10, IE 11

**Comment by desigonz** [comment]
Happening in Windows 7 IE 11 too.
