### ISSUE TITLE
"Optional" translation

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1774]
"Optional" should translate to "opcional" on review page

**URL tested:** https://forms.austintexas.io/policia-queja/revisar-y-enviar

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=7.0&device=Samsung+Galaxy+S8&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Frevisar-y-enviar&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/revisar-y-enviar) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Samsung Galaxy S8 |
| Browser | Mobile_chrome |
| Operating System | Android 7.0 |
| Resolution | 1440 x 2960 px |
| Screen size | 5.8 in - 2.5 x 5.2 in |
| Viewport | 360 x 740 dp |
| Aspect Ratio | 18.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/e3671410754d87ffe0180311ceb76fcec22a23a4/realdroid_Samsung_Galaxy_S8.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/e3671410754d87ffe0180311ceb76fcec22a23a4/realdroid_Samsung_Galaxy_S8.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=android&os_version=7.0&device=Samsung+Galaxy+S8&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Frevisar-y-enviar&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/revisar-y-enviar) to reproduce the issue on Browserstack**

**Comment by desigonz** [comment]
Maybe @sergiogcx or @easherma can help me with this one. Adding the following to both thanks and complaint translations.json in [branch 1822-copy-updates](https://github.com/cityofaustin/coa-forms/tree/1822-copy-updates) didn't fix this issue:

`  "%optional%": {
    "es": "%opcional%"
  },
  
  "%Optional%": {
    "es": "%Opcional%"
  },`

Any thoughts on what's happening?

**Comment by easherma** [comment]
I'll take a look, thinking the parenthesis would have something to do with it.

**Comment by easherma** [comment]
Looks to be fixed with my tweak: https://opo.austintexas.io/policia-queja/1822-copy-updates/revisar-y-enviar

**Comment by desigonz** [comment]
Beautiful—approved and ready for you to merge!
