### ISSUE TITLE
Spanish date copy styling on review page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1775]
"Abril 8th, 2019" is incorrect in Spanish ("th" definitely doesn't exist in Spanish, and dates are formatted day/month/year). I expected to see "8 abril 2019." 

**URL tested:** https://forms.austintexas.io/policia-queja/revisar-y-enviar

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=7.0&device=Samsung+Galaxy+S8&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Frevisar-y-enviar&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/revisar-y-enviar) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Samsung Galaxy S8 |
| Browser | Mobile_chrome |
| Operating System | Android 7.0 |
| Resolution | 1440 x 2960 px |
| Screen size | 5.8 in - 2.5 x 5.2 in |
| Viewport | 360 x 740 dp |
| Aspect Ratio | 18.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/900f7853166b4db463c04e5b472134b7d32dd755/realdroid_Samsung_Galaxy_S8.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/900f7853166b4db463c04e5b472134b7d32dd755/realdroid_Samsung_Galaxy_S8.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=android&os_version=7.0&device=Samsung+Galaxy+S8&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Frevisar-y-enviar&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/revisar-y-enviar) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
Def could be addressed as part of #1727

**Comment by easherma** [comment]
Also related: #1509
