### ISSUE TITLE
Review page error icon overlaps with text on Samsung S8

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1776]
Style on error message review page—icon overlaps text. 

**URL tested:** https://forms.austintexas.io/policia-queja/revisar-y-enviar

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=7.0&device=Samsung+Galaxy+S8&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Frevisar-y-enviar&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/revisar-y-enviar) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Samsung Galaxy S8 |
| Browser | Mobile_chrome |
| Operating System | Android 7.0 |
| Resolution | 1440 x 2960 px |
| Screen size | 5.8 in - 2.5 x 5.2 in |
| Viewport | 360 x 740 dp |
| Aspect Ratio | 18.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/6270c727c3e87bd332cb89a2837bc1fbf6eef597/realdroid_Samsung_Galaxy_S8.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/6270c727c3e87bd332cb89a2837bc1fbf6eef597/realdroid_Samsung_Galaxy_S8.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=android&os_version=7.0&device=Samsung+Galaxy+S8&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Frevisar-y-enviar&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/revisar-y-enviar) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
@desigonz good catch! Also the error text is in English, but I think we have another bug report covering that already.
