### ISSUE TITLE
Modal does not work on IE 11

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1778]
The Spanish Modal gets stuck to the bottom of the screen and the bottom half gets cut out. The bottom half is the half that actually contains the navigation buttons, so this is a problem.

**Device**
Windows 10, IE 11

![ie modal small.gif](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/f68daed2-d099-4013-866c-64827744be37)

**Comment by desigonz** [comment]
Also happening in Windows 7 IE 11.
