### ISSUE TITLE
"share your media" v. "share photos and videos"

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1780]
We're using inconsistent headings for the "share" page and the corresponding accordion on the review page. Not sure if this was intentional. cc @srigdon 

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/9bfec6e4-f1f2-4a3c-b015-8624599f9cfe)

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/de96a06d-5c0e-4267-9b74-bb663a5a429d)

**Comment by easherma** [comment]
Hmm, IIRC we went back and forth a little bit with the copy, but I think the review page copy is correct.

**Comment by srigdon** [comment]
The consensus at the time was “Share your photos or video” seemed more approachable or easier to understand than “share your media,” but I’m liking media more 1) because it’s more accurate and 2) the helper text is there to explain it. Let’s change the header to “Share your media” in all instances.
