### ISSUE TITLE
Spanish thanks email headings/subjects

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1783]
The headings and subject lines in English and Spanish are consistent, and look like they haven't been edited by content.

I recommend the same subject and heading for each:
- [ ] English: Your thank you was submitted successfully!
- [ ] Spanish: ¡Su nota de agradecimiento fue enviada!

@srigdon thoughts?

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/e76d483c-3164-4a10-a5d4-99d568a79ecf)

**Comment by srigdon** [comment]
I agree with your recommendation. Not sure, but this might’ve been an instance of copy written on the fly and not reviewed until...now. Great catch!

**Comment by desigonz** [comment]
Removing from Copy-not-code epic because I believe this lives in a different repo— @Niicck, can you confirm? Looks like this copy lives in https://github.com/cityofaustin/form-service-api.

**Comment by desigonz** [comment]
Review criteria: 
- [ ] On Thank You confirmation email, English subject and heading should be `Your thank you was submitted successfully!` [#1783](https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/1783)
- [ ] On Thank You confirmation email, Spanish subject and heading should be `¡Su nota de agradecimiento fue enviada!` [#1783](https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/1783)

**Comment by desigonz** [comment]
Closed, see #1825
