### ISSUE TITLE
Language switch modal on confirmation page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1785]
If you try to switch languages on the confirmation page, you get the "Start over in Spanish?" modal. I don't expect this here because I've submitted the form already.

**URL tested:** https://forms.austintexas.io/police-complain/introduction

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=7&browser=IE&browser_version=11.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-complain%2Fintroduction&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-complain/introduction) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 7 |
| Resolution | 986x766 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/adf349e7355bf072497d2b211b8684fa324b8429/win7_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/adf349e7355bf072497d2b211b8684fa324b8429/win7_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=7&browser=IE&browser_version=11.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-complain%2Fintroduction&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-complain/introduction) to reproduce the issue on Browserstack**

**Comment by Niicck** [comment]
Duplicate Closing
