### ISSUE TITLE
Fix "new officer" and "new witness" translations

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1789]
On thank you form in Spanish: "New oficial" and "New testigo" are appearing. Expected "Nuevo oficial" and "Nuevo testigo." 

These were supposed to have been fixed in #1659 (it's not happening in complaint forms), but I think we missed the thank you forms.

**URL tested:** https://forms.austintexas.io/policia-agradezca/introduccion

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=7&browser=IE&browser_version=11.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-agradezca%2Fintroduccion&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-agradezca/introduccion) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 7 |
| Resolution | 986x766 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/f6bb69cce4409de19d483a568991946cefcc4952/win7_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/f6bb69cce4409de19d483a568991946cefcc4952/win7_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=7&browser=IE&browser_version=11.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-agradezca%2Fintroduccion&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-agradezca/introduccion) to reproduce the issue on Browserstack**

**Comment by desigonz** [comment]
This seems to be fixed now—maybe it was a caching thing? Closing

**Comment by easherma** [comment]
https://github.com/cityofaustin/coa-forms/pull/24
