### ISSUE TITLE
Map doesn't load in iPhone 6/safari 11 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1791]
**Describe the bug**
When performing regression testing #1751, map doesn't always load (English complaint form, Spanish thank you form)

**https://forms.austintexas.io/police-complain/introduction**
**https://forms.austintexas.io/policia-agradezca/introduccion**

**To Reproduce**
1. Go to '/what-happened' 
2. Wait for map to load (tick-tock) 
3. See error?

**Current behavior**
Map will not load

**Expected behavior**
Map ought to load

**Screenshots**
<![Screen Shot 2019-04-24 at 6.06.18 PM.png](https://images.zenhubusercontent.com/5c4b52abd709c56fe9edad32/33237b1d-844d-4161-821b-a0c601be8d64)>
<

**Device**
iPhone 6

**Browser**
Safari 11

**Comment by annieszot** [comment]
Related #1644

**Comment by Niicck** [comment]
Backlog for now. We need to redesign the LocationPicker page.
