### ISSUE TITLE
Calendar icon not working when clicked on in mobile browser test (iPhone 6; Safari 11) 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1794]
Describe the bug
While regression testing for #1751, in reference to #1591, unfortunately, the calendar icon did not work for mobile while testing in browser stack.

URL
All
https://forms.austintexas.io/police-complain/introduction
https://forms.austintexas.io/policia-queja/introduccion
https://forms.austintexas.io/police-thank/introduction
https://forms.austintexas.io/policia-agradezca/introduccion

To Reproduce

Go to '/what-happened.'
Click on the calendar icon
Wait- no calendar pops up
Error unseen?

Current behavior
When move cursor (arrow) to the calendar icon and click on each form in /what-happened, calendar does not pop up.

Expected behavior
After clicking the icon (date picker), the calendar ought to pop up allowing the user to select the date that populates the date fields.

Screenshots
No screenshots

Device
iPhone 6

Browser
Safari

**Comment by Niicck** [comment]
Known issue. Closing.
