### ISSUE TITLE
Janis - fix background color on homepage

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1796]
I've changed the background on the WorkInProgress component to be white as I was running into issues getting the left/right sides of the TopServices component to use the gray background color.

This should be addressed to match designs, it seems like there's come wonky css in there.

![Screen Shot 2019-04-25 at 1.56.42 AM.png](https://images.zenhubusercontent.com/5afb42ab4b5806bc2bd34c32/0995d1b0-a58e-4a5b-bbe9-38087b8a3b6f)

**Comment by sergiogcx** [comment]
This is a non issue, the text has been removed as per issue #2084


Now in prod:
https://alpha.austin.gov/

**Comment by sergiogcx** [comment]
@oliver2g would you mind closing this issue?
