### ISSUE TITLE
<title> tag not translated

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1797]
Spanish complaint and thank you forms have untranslated `<title>` tags. This was supposed to have been fixed in #1504.

**URL tested:** https://forms.austintexas.io/policia-agradezca/confirmation

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Chrome&browser_version=71.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-agradezca%2Fconfirmation&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-agradezca/confirmation) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 71.0 |
| Operating System | Windows 10 |
| Resolution | 1028x766 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/a2b14d352f9ea79505c733c9dab5a1846d69fe06/win10_chrome_71.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/a2b14d352f9ea79505c733c9dab5a1846d69fe06/win10_chrome_71.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Chrome&browser_version=71.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-agradezca%2Fconfirmation&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-agradezca/confirmation) to reproduce the issue on Browserstack**

**Comment by sergiogcx** [comment]
Done:

Complaint Form:
https://opo.austintexas.io/policia-queja/1797-sg-coaf-translatetitle/introduccion

Thank you form:
https://opo.austintexas.io/policia-agradezca/1797-sg-coaf-translatetitle/introduccion
