### ISSUE TITLE
'Please provide a response' error message not showing up for Spanish form

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1799]
We have error message text for the English complaint and thank for maps, but not for the English ones. I expect to see error messages on both. 

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/3e3573f0-da99-4e71-953a-c18bfadece9a)

**Comment by easherma** [comment]
Good catch @desigonz ! It actually appears that we are missing error messages for all 'required' entries in Spanish.

**Comment by easherma** [comment]
I've pretty much narrowed this down to this:
The error message does not show up on any build where webpack mode is 'production'
The error messages WILL show up when webpack mode is 'development'

This problem does not occur on the English version of the form, regardless of the webpack mode.

**Comment by easherma** [comment]
Fixed in https://github.com/cityofaustin/coa-forms/pull/20

**Comment by desigonz** [comment]
Got it. So there's nothing to change? Should we close this one?
