### ISSUE TITLE
Map content in relation to information architecture

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#18]
Map content in relation to information architecture

**Comment by LauraTrujillo** [comment]
@amenity This is an old Asana task we migrated over, and I think we've already completed it. However, if we want to keep it in the backlog for future releases we can. What we want to accomplish here is making sure the services we are transitioning are mapped into the global nav and have a place within the themes and topics.

**Comment by amenity** [comment]
@LauraTrujillo Hmm. It sounds like this is really an ongoing thing. I'd like to see it handled either of these ways: 
 - Create a version system for the site navigation and tackle one at a time concurrent with any content model work. 
 - Add it as a subtask or specific issue when it needs to happen. 

If it's really that you want this here as a reminder, add it to y'all's beautiful preflight checklist.

**Comment by LauraTrujillo** [comment]
@amenity Thanks! Added to our preflight checklist. Good to close this one out.
