### ISSUE TITLE
Thanks form zip code validation

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1800]
Related to #1787. Zip code field validation currently:
- you can arrow down to negative numbers
- form gives you an error message if you try to submit a number less than 5 (this is not 5 digits; literally, the number can be 6 and you're good) 

I expected to not be able to arrow down to negative numbers or have to submit at least a five digit number.

**URL tested:** https://forms.austintexas.io/police-thank/about-you

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Chrome&browser_version=71.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-thank%2Fabout-you&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-thank/about-you) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 71.0 |
| Operating System | Windows 10 |
| Resolution | 792x766 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/52f1b0f4ad7171f52d2a9c1f4448ad5000d60060/win10_chrome_71.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/52f1b0f4ad7171f52d2a9c1f4448ad5000d60060/win10_chrome_71.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Chrome&browser_version=71.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-thank%2Fabout-you&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-thank/about-you) to reproduce the issue on Browserstack**

**Comment by Niicck** [comment]
Can I tack something else on? The previous validation config for zip code in the /about-you page did not work.
```
          zipCode: {
            type: 'number',
            minimum: 5,
          },
```
means a minimum value of the number 5, not a minimum number of digits. This resulted in us enforcing the wrong rule for validation
