### ISSUE TITLE
Witness field in thanks confirmation email

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1802]
In the thank you form confirmation email (both English and Spanish), there is a field for witness information. There shouldn't be!

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/ced1b77d-8c3c-4710-8a4b-eaef43340efd)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/cb2523da-b124-465a-9eb6-7e92cc371e77)

**Comment by Niicck** [comment]
Duplicate
