### ISSUE TITLE
Janis - Header and "how you know" menu z-index isssues

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1805]
**Describe the bug**
<img width="1622" alt="Screen Shot 2019-04-25 at 1 01 51 PM" src="https://user-images.githubusercontent.com/6384156/56757723-80f88900-675a-11e9-9e3b-3fd40f7f0179.png">

**URL**
https://janis.austintexas.io/

**To Reproduce**
1. Click on the + on the official website thing

**Comment by pibemillo** [comment]
@easherma hope you don't mind i snagged this issue from you, noticed it was a quick css property fix:
https://github.com/cityofaustin/janis/pull/384
