### ISSUE TITLE
Component update for design v2: Service Page Components

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#181]
Link to mock - https://drive.google.com/open?id=1wtiU9LqpvU2KTu362bCPMfS7tfYgjyuf
(cut the images out in favor of the sketch link to shorten the description)

For all:
  - [x] Rename components

Update each:
  - [x] `<PageBanner />`
  - [x] `<Breadcrumbs />` 
    - each is a link
    - gray breadcrumbs for inactive link, orange for active/current page
  - [x] `<PageHeader />`
    - h1
    - optional description (for theme & topic pages)
    - optional page break below (for theme & topic pages)
  - [x] `<Steps />`
    - discussion need about how this data gets created in Joplin and what structure it gets sent to Janis
  - [x] `<ApplicationBlock />`
    - custom style updates for Recollect (all view variations)
    - hide tabs on Recollect- makes app specific to service/resident task
  - [x] `<HtmlFromAdmin/>`
    - ol, ul - no nesting
    - h1, h2, p, a
    - check those constraints are ok with content team
  - [x] `<ContactDetails />`
    - [x] `<Phone />`
    - [x] `<TTY/TTD Phone />`
    - [x] `<Email />`
    - [x] `<Address />`
    - [x] `<Hours />`
  - [ ] `<ContactDetailsWithMap />`
  - [x] `<SectionHeader />`

**Comment by cthibaultatx** [comment]
@mateoclarke I have a few notes and questions:
- I don't think the service banner is a link but I may not be understanding the implementation.
- What does the 'a' stand for in WYSIWYG editor UI?

**Comment by mateoclarke** [comment]
@cthibaultatx: My bad. The bullet point about links was supposed to be under the breadcomb section. Now updated. a stands for anchor tag, or link. `<a href="">`

**Comment by ifsimicoded** [comment]
@cthibaultatx 
- "each is a link" should have been a part of breadcrumbs. So I've updated the description. 
- the 'a' stands for anchor which is the html name for links.
- let's sit down at some point and just style the different recollect views up -- I can teach you some stuff and you can make a branch or we can pair on it after user testing.

## Recollect schedule view 1
![screen shot 2018-03-19 at 6 15 28 pm](https://user-images.githubusercontent.com/3039125/37627351-fd06e7c6-2ba1-11e8-903c-2e6fed1f4ea2.png)

## Recollect schedule view 2
![screen shot 2018-03-19 at 6 19 55 pm](https://user-images.githubusercontent.com/3039125/37627409-388c84cc-2ba2-11e8-88c9-5f249b5e8175.png)

And then there's the Recollect recycle guidelines view

**Comment by cthibaultatx** [comment]
@ifsimicoded sounds great re: recollect. I already worked out the breadcrumbs styling issues and updated the mocks prior to you and Mateo beginning to implement.

**Comment by ifsimicoded** [comment]
closing and logging new issue for remaining component here #225
