### ISSUE TITLE
"Ticket Number" Confirmation Email OPO complaint form - "Ticket Reference" instead? 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1811]
Describe the bug
When performing regression testing for #1750, the confirmation email in #1754 showed "Ticket number" for "I received a ticket during my interaction". Change language to "Ticket reference" instead of "Ticket number" in confirmation email since user doesn't insert a number? 

URL
Confirmation email

To Reproduce

Complete OPO complaint form including checking the box "I received a ticket during my interaction" on /what-happened. 

Screenshots
![Screen Shot 2019-04-25 at 8.06.39 PM.png](https://images.zenhubusercontent.com/5c4b52abd709c56fe9edad32/528bef68-f2c8-4ac2-852f-fabb02c96373)
![Screen Shot 2019-04-25 at 7.10.43 PM.png](https://images.zenhubusercontent.com/5c4b52abd709c56fe9edad32/282533ab-909f-4fad-be32-cd81601d5148)

Device
Windows 7
Browser
Chrome 71.0

**Comment by Niicck** [comment]
Fixed
