### ISSUE TITLE
Ticket info listed on thank you confirmation email

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1812]
Describe the bug
OPO thank you form - ticket info appears in confirmation email but not in /what-happened page
URL
https://forms.austintexas.io/police-thank/what-happened
and 
confirmation email

To Reproduce

Go to https://forms.austintexas.io/police-thank/introduction
Complete thank you form, share email to receive a confirmation email
See "Has Ticket" N/A 
See "Ticket Number" N/A
Maybe it's not an error, but perhaps there's a preferred experience? 

Current behavior
See above
Expected behavior
Not have "has ticket" or "ticket number" shown in confirmation email? 

Screenshots
![Screen Shot 2019-04-25 at 8.31.19 PM.png](https://images.zenhubusercontent.com/5c4b52abd709c56fe9edad32/57d5a615-ac13-40ee-a415-974c9e12efac)
![Screen Shot 2019-04-25 at 8.30.27 PM.png](https://images.zenhubusercontent.com/5c4b52abd709c56fe9edad32/acb3140f-d9f5-4194-b05c-a3613234e7ea)
Device
Windows 7 

Browser
Chrome 71

**Comment by Niicck** [comment]
Fixed
