### ISSUE TITLE
Sex/Gender: Inconsistent "sexo" on agradezca review/confirmation email

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1813]
Describe the bug
While conducting regression testing #1750 for #1756, noticed "sexo" on the confirmation email is "Masculino" and "Femenino", and not "Mujer" and "Hombre" as noted on the form when you fill it out. 
URL
Confirmation email

To Reproduce

Go to https://forms.austintexas.io/policia-agradezca/introduccion
Complete form and submit 
When you receive the confirmation thanks email, review "sexo" and compare with your review page in browserstack 
See error

Current behavior
The form asks to specify "Sexo" as "Mujer" and "Hombre" but on the confirmation email it's listed as gender "feminino" and "masculino" 

Expected behavior
Have consistent sex or gender indications on form and confirmation email. 

Screenshots
![Screen Shot 2019-04-25 at 10.01.51 PM.png](https://images.zenhubusercontent.com/5c4b52abd709c56fe9edad32/0ae564f4-8dd2-44b3-839e-a0bb9e23fb37)
![Screen Shot 2019-04-25 at 10.02.08 PM.png](https://images.zenhubusercontent.com/5c4b52abd709c56fe9edad32/1aa66071-f155-45da-abef-7af67ebbaa5d)
![Screen Shot 2019-04-25 at 10.14.37 PM.png](https://images.zenhubusercontent.com/5c4b52abd709c56fe9edad32/e9618b15-dfa0-450b-801c-4cea8fb1bb17)
![Screen Shot 2019-04-25 at 10.14.40 PM.png](https://images.zenhubusercontent.com/5c4b52abd709c56fe9edad32/26e0581c-39cb-4d18-a935-8ded5072e290)
Device
Mac 10.14 

Browser
chrome 71.0

**Comment by desigonz** [comment]
Closed, see #1825
