### ISSUE TITLE
Form Service Updates Sprint 29

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1816]
form-service-api code: https://github.com/cityofaustin/form-service-api/pull/23
coa-forms code: https://github.com/cityofaustin/coa-forms/pull/17

Merged into master, you can now test it on the staging deployment:
https://forms.austintexas.io/police-complain/introduction

We had to merge it into master to test because it required changes on the backend. And the backend form-service-api does not have the ability to do PR builds.

---
**QA Test Plan:**
You can use any browser, no need to use browserstack.
staging link: https://forms.austintexas.io/police-complain/introduction
Test the 3 issues below.

---
To test: https://github.com/cityofaustin/techstack/issues/1766
   - /share-evidence should now be /share-media for English
   - and it should be /compartir-archivos for Spanish

---

To test: https://github.com/cityofaustin/techstack/issues/1782
  - Thank you form confirmation email should no longer have ticket or witness info

---

To test: https://github.com/cityofaustin/techstack/issues/1763
  1. Fill out a complain form, but enter a name into ticket
  2. Check that the email template no longer says "Ticket Number" but rather "Name as is appears on ticket"

This test (1763) needs to be done for both English + Spanish for both outlook and non-outlook email clients. 4 tests total, the browser doesn't matter.
  1. English + Outlook
  2. English + Not outlook
  3. Spanish + Outlook
  4. Spanish + Not outlook

**Comment by Niicck** [comment]
Important Deployment Note: both form-service-api and coa-forms will have to be pushed into production.

**Comment by desigonz** [comment]
All of your changes look good! 

I created issue #1838  to change confirmation email text "share your photos and videos" to "share media" for both English and Spanish, assigned myself to it.

**Comment by Niicck** [comment]
Awesomesauce! Thanks @desigonz!
