### ISSUE TITLE
Component update for design v2: Feedback Form

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#182]
- [x] Add to Storybooks
- [x] Add translation
- [x] add browser, device, page url info to Github Issues (https://github.com/cityofaustin/alpha-
- [ ] determine text representations of emojis for screen readers
- [x] do we need backfills for emoji? images instead?
- [x] log emoji value with Google Analytics event handler
- [x] save emoji to state
- [x] submit emoji w/ feedback textarea to Github Issues (https://github.com/cityofaustin/alpha-feedback/issues)
feedback/issues)
- [x] 'Give more feedback' in 3rd screen resets the form back to the emoji page.

Backlog considerations:
- CSRF, API throttling 

![screen shot 2018-03-15 at 11 06 23 am](https://user-images.githubusercontent.com/20911665/37475531-ef9bc44e-2840-11e8-8885-4557b976270c.png)

Mobile flow:
![screen shot 2018-03-15 at 11 08 49 am](https://user-images.githubusercontent.com/20911665/37475728-58a80272-2841-11e8-9dcc-35646d8b2ed7.png)

**Comment by ifsimicoded** [comment]
@benweatherman having some issues with creating github issues here:
https://github.com/cityofaustin/alpha-feedback/issues
I'm using the same form post code that I was using with the previous form which was operable --
```
export const postFeedback = (data) => {

  const { title, description, email } = data;

  return axios
    .create({
      headers: { 'Content-Type': 'application/json' }
    })
    .post(`${process.env.FEEDBACK_API}`, {
      destination: 'githubIssue',
      repository: 'alpha-public-feedback',
      title: title,
      description: description
    })
}
```
which submits to https://coa-test-form-api.herokuapp.com/process/ and returns a 200 -- but I'm not seeing a new issue created here: https://github.com/cityofaustin/alpha-feedback/issues.

any 💡's?  
Maybe an environment thing since I'm posting locally?

**Comment by benweatherman** [comment]
I _believe_ the user account we were using got deleted so we need to create a new one. There might be something fishy going on locally, but that user thing will definitely get in our way at some point. Do you want me to look into that or do you want to run with it?

**Comment by ifsimicoded** [comment]
Thanks for investigating -- also looks like I have some access control issues from janis heroku branches. Not sure how important it is to resolve this. 

![screen shot 2018-04-05 at 6 41 43 pm](https://user-images.githubusercontent.com/3039125/38397053-1e8339b0-3901-11e8-940f-4fc70f2981e7.png)

**Comment by ifsimicoded** [comment]
thanks @benweatherman and @mateoclarke! 🌻 Got both of these issues (CORS whitelist and ☠️  user) resolved.

**Comment by ifsimicoded** [comment]
@cthibaultatx @courtneyjacinic We should talk about the text representation of the emojis for accessibility/screen readers and varying cultures.

**Comment by cthibaultatx** [comment]
I think @toribr may have created some definition for them already for CMS design. I'll ask.

**Comment by ifsimicoded** [comment]
Closing this issue as all dev tasks are complete or in review. 
The remaining emoji to text task is logged in issue #327
