### ISSUE TITLE
Hotjar code needs to be removed from opo.austintexas.io 

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1827]
Currently Hotjar code is on .io and .gov sites, which means that it's gathering data from both, which is a hotmess. (see what i did there?)

The hotjar code should be removed from .io so we get clean data. let me know if you need access.

**Comment by sergiogcx** [comment]
Please don't mind the commit history, I am still figuring out the pipeline.

This is now accomplished here:
https://github.com/cityofaustin/coa-forms/pull/26

All there is left is to change the environment to production (currently on dev).

Look at the source code of these PRs:
https://opo.austintexas.io/police-complain/1827-sg-coaf-removehotjar/introduction
https://opo.austintexas.io/police-thank/1827-sg-coaf-removehotjar/introduction

Thanks!
