### ISSUE TITLE
Janis: Fix Production Deployment Routes

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/techstack#1834]
### 1. Try this first:

https://d1ksscekic4tim.cloudfront.net/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup

Notice the redirect in your browser, the subfolder is noticeable in the url bar, the page should look broken.

Now try this link (the same, with a trailing forward-slash)

https://d1ksscekic4tim.cloudfront.net/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup/

No errors, no redirect, can refresh fine.

Now look at this site, same code, deployed at the root level:

http://janis-lab.s3-website-us-east-1.amazonaws.com/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup

No errors, no redirect, can refresh fine.

 
 
 
  
### 2. The Problem (details):

When deployed to a subfolder, Janis tends to redirect (when behind a proxy, such as CloudFront or Nginx).

For example, imagine Janis is deployed in a bucket and subfolder as follows (you can click on the following link):

http://janis-lab.s3-website-us-east-1.amazonaws.com/janis-prod-2019-05-02--6-13-01-ff847ecd

Where the bucket is `janis-lab` and the subfolder is `janis-prod-2019-05-02--6-13-01-ff847ecd`

When behind a proxy (in this case CloudFront, `https://d1ksscekic4tim.cloudfront.net`) there is a redirect:

Command:

```bash
$ curl -IL https://d1ksscekic4tim.cloudfront.net/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup

```

Result:

```bash
HTTP/2 302
x-amz-error-code: Found
x-amz-error-message: Resource Found
location: /janis-prod-2019-05-02--6-13-01-ff847ecd/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup/
date: Thu, 02 May 2019 06:16:42 GMT
server: AmazonS3
x-cache: Miss from cloudfront
via: 1.1 410f438fadc9dbf015df89f81a951152.cloudfront.net (CloudFront)
x-amz-cf-id: OCVAVyUcVTu5b0VgoFxNkNF2_NwsFJJiwFXTm_wNKIMyDUpL2dZVww==

HTTP/2 200
content-type: text/html
content-length: 117391
date: Thu, 02 May 2019 06:16:43 GMT
last-modified: Thu, 02 May 2019 06:13:35 GMT
x-amz-version-id: H_KAoLsUAD6L8QpDjOJzxl74IQ4CaqU9
etag: "7e5c217073155dff823bfbe063e392d3"
server: AmazonS3
x-cache: Error from cloudfront
via: 1.1 410f438fadc9dbf015df89f81a951152.cloudfront.net (CloudFront)
x-amz-cf-id: 874UqVaVh6r0D9vMoBAt0HaZaStI1YTt6htPbxv81E6R86v9gcNepQ==
```

**Notice the 302 is issued and adds the subfolder to the url**: `/janis-prod-2019-05-02--6-13-01-ff847ecd/`

This behavior can be seen in the browser:
https://d1ksscekic4tim.cloudfront.net/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup

1. Try refreshing that page in the browser.
2. Click on Household waste (top-left).

Strangely this same error happens behind an Nginx proxy, so it is not exclusive to CloudFront. The weird part: S3 is not set up to handle redirects, meaning it has to be something at the application level (react router).

### 3. The Challenge:

Find a way to access `http://janis-lab.s3-website-us-east-1.amazonaws.com/janis-prod-2019-05-02--6-13-01-ff847ecd/` through a proxy and without redirects. 

1. You are welcome to put your janis build in that same bucket (or any other)
2. You are welcome to put your build in that same subfolder (or any other)
3. It has to be through a subfolder, and through a proxy (CloudFront or Nginx,... nginx preferrably)

**Comment by sergiogcx** [comment]
My observations:

1. The exact same code does not present any redirection when located in the root folder. But when placed in a subfolder, the redirect happens.
2. Not all paths redirect, for instance https://d1ksscekic4tim.cloudfront.net/departments redirects, but https://d1ksscekic4tim.cloudfront.net/departments/ does not (notice trailing slash `/`).
3. Pages refresh without a problem with a trailing slash:  (https://d1ksscekic4tim.cloudfront.net/departments/
4. Nginx presents the same problem, so it is not just CloudFront.
5. The S3 is not set up to handle redirects, so it has to be the application (react router).


I've tried:
1. Different proxies, different buckets, different subfolders. Same code.
2. Adding "homepage" to package.json (according to react-static documentation, https://facebook.github.io/create-react-app/docs/deployment)
3. Setting up an environment variable `PUBLIC_URL` (according to docs)
4. Tried messing with `basePath` in static.config.js, tried `/janis-prod-2019-05-02--6-13-01-ff847ecd `,  forward slash `/`,  and `https://d1ksscekic4tim.cloudfront.net` neither worked.
5. Tried messing with `siteRoot` in static.config.js, tried `/` and `https://d1ksscekic4tim.cloudfront.net` neither worked.
6. Combinations of 4 and 5.

I may have missed something, just really tired. From the docs (https://facebook.github.io/create-react-app/docs/deployment), homepage is the way to go, but I had no success. 

What I have not tried:
1. Using basename in react-router
2. Dig in more into the docs
3. Maybe I missed something in any of the steps above. Every deployment was slow.

**Comment by sergiogcx** [comment]
To test on the cloud I just deploy to a bucket called janis-lab (which is behind a cloudfront distro). 

To test locally, I use a modified version of the opo proxy (a dockerized nginx proxy):
https://github.com/cityofaustin/opo-pr-viewer/tree/1834-sg-opo-nginxproxy

**Comment by easherma** [comment]
Taking this off Janis 2.0 as it isn't really needed for the micro-site transition.

**Comment by sergiogcx** [comment]
@easherma I will finish this task off today, I will be running additional tests. If these tests fail we know we need to upgrade to rs7 to make the routes work.

**Comment by easherma** [comment]
FWIW I set up a netlify deployment, which we could leverage to troubleshoot whether a particular routing issue is being caused by deployment or by the app itself.

**Comment by sergiogcx** [comment]
I performed one more test using our current version of react-static, it appears we still get the redirects depending on whether there is a trailing slash character.

So for now versioning is a problem, we are going to have to wait to get rs7 working.

**Comment by sergiogcx** [comment]
I noticed the same problem happens in rs7, so there is something else causing the problem:

https://dyj1z3uej60oo.cloudfront.net/en/departments

```
λΞ curl -IL https://dyj1z3uej60oo.cloudfront.net/en/departments
HTTP/2 302
x-amz-error-code: Found
x-amz-error-message: Resource Found
location: /rs7/en/departments/
date: Wed, 15 May 2019 21:13:06 GMT
server: AmazonS3
x-cache: Miss from cloudfront
via: 1.1 b6893337c0deb629a088dde9414834dd.cloudfront.net (CloudFront)
x-amz-cf-id: YtIeRWk3nPA5CJgvW9G6B0-FZQFx7Mtt0ItYxDOgWs37nwIfL07D9A==

HTTP/2 404
content-length: 0
x-amz-error-code: NoSuchKey
x-amz-error-message: The specified key does not exist.
x-amz-error-detail-key: rs7/rs7/en/departments/index.html
date: Wed, 15 May 2019 21:12:58 GMT
server: AmazonS3
age: 9
x-cache: Error from cloudfront
via: 1.1 b6893337c0deb629a088dde9414834dd.cloudfront.net (CloudFront)
x-amz-cf-id: imjgqRtlYzTdUyWQj7DprtFuIYcU1f9TFXiUIqeE0pIM5gl1BqUBLQ==

```

I will create a new issue for next sprint and see if we can make this happen next.
