### ISSUE TITLE
Witness info not captured in Spanish complaint confirmation email 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1835]
Describe the bug
While doing QA for #1674, when submitting the complaint form (Spanish), witness information does not appear on Spanish confirmation email. 

URL
https://opo.austintexas.io/policia-queja/1674-edit-officers/introduccion

To Reproduce

Go to https://opo.austintexas.io/policia-queja/1674-edit-officers/introduccion
1. 
On /officer-details, enter info for 2 officers.
On /witness-details, enter info for 2 witnesses
Check that its still there on /review-and-submit.
Submit form.
Check email. Make sure the officer and witness info is in your email.
See error 

OR

On /officer-details, enter info for 2 officers.
On /witness-details, enter info for 2 witnesses
Check that its still there on /review-and-submit.
BUT THIS TIME edit the info in the review page. Delete 1 officer and delete 1 witness. Then add 1 new officer and 1 new witness.
Submit. Check email. Make sure data matches.
See error 

OR

Enter NO officer info on /officer-details. Select "No" I don't want to enter officer info
Enter NO witness info on /witness-details. Select "No I don't want to enter witness info
THIS TIME enter info for 2 officers and 2 witness only on the review page.
Submit. Check email. Make sure data matches.
See error

Current behavior
See above

Expected behavior
Witness information included on Spanish confirmation email 

Screenshots
Ping @annieszot for screenshots

Device
Mac OS Mojave

Browser
Chrome 

Additional context

**Comment by Niicck** [comment]
Fixed by https://github.com/cityofaustin/techstack/issues/1821
