### ISSUE TITLE
Create Script to Test New Migrations

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1836]
As a Joplin Developer, I want to test new migrations faster.

The "Managing Local DB" section of the Joplin README.md outlines the several manual steps that developers need to take in order to test new migrations. I want to create a script to automate as much of it as possible.

**Comment by oliver2g** [comment]
@Niicck can i update the milestone to Sprint 31?

**Comment by Niicck** [comment]
Yes!
