### ISSUE TITLE
Change to "share media" on English and Spanish confirmation emails

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1838]
Submitted PR here: https://github.com/cityofaustin/form-service-api/pull/25

Testing criteria:
- [x] When you submit a complaint form in English uploaded materials, does the email say "Share your media"?
- [x] When you submit a complaint form in English uploaded materials, does the email say "Comparta archivos"?

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/508ed0b7-1499-405e-b006-82cec68ccf91)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/22140c50-5ddc-4485-b7f4-a2b1b4257d0f)

**Comment by sergiogcx** [comment]
![Screen Shot 2019-05-02 at 3.37.43 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/f548cfd9-1a2f-460a-8e38-91d97c354c8c)

![Screen Shot 2019-05-02 at 3.34.07 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/0d27aca1-9804-4444-b3da-7339ebbb5ffd)

**Comment by sergiogcx** [comment]
I think this is ready for prod
