### ISSUE TITLE
Need a way to translate the word 'witness'

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1839]
Translating "witness" breaks the form submission for form-api-service. This translation was fixed by https://github.com/cityofaustin/techstack/issues/1821 but we still need to translate the word "witness" sometimes.

![Screen Shot 2019-05-02 at 1.20.43 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/27a79a2c-2cb5-4bab-ae2f-0b586d1c8066)

**Comment by sergiogcx** [comment]
We will need to re-instate the witness word in the translations file. The form will need to have the schema renamed to anything that does not have the witness keyword.

**Comment by sergiogcx** [comment]
As it turns out, all it needed was some love:

https://github.com/cityofaustin/coa-forms/pull/27

Demo:

https://opo.austintexas.io/policia-queja/1839-sg-ocf-witnesstranslation
