### ISSUE TITLE
Feedback component into Janis 2

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#1840]
We need to re-introduce the ability for users to submit feedback about alpha. 

### Resources
- [Feedback component](http://janis-staging.herokuapp.com/storybook/?selectedKind=Forms&selectedStory=Feedback%20Form&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) rendered in Storybook
- XD spec: [desktop](https://xd.adobe.com/spec/a1e17b2e-1b43-40ea-6041-eaf6ba807ea8-d7d0/), [mobile](https://xd.adobe.com/spec/a1e17b2e-1b43-40ea-6041-eaf6ba807ea8-d7d0/screen/959f2dfa-e058-4db7-875b-6b4f6b73c528/Feedback-mobile-default-1), [flow view](https://xd.adobe.com/spec/a1e17b2e-1b43-40ea-6041-eaf6ba807ea8-d7d0/grid/)

## Acceptance criteria

**As a resident**
- [ ] I can **submit text feedback** about a page on Alpha
- [ ] So that **I can inform the Alpha team of my feedback**

**Criteria**
- [ ] Just before the global footer, users can see a feedback question [Did you find what you're looking for on this page?] with yes/no buttons set in the secondary styling (fill: `#F0F0F0`, border: `#C6CACE`, `box-shadow: 0px 3px 6px #00000014;`
- [ ]  **User makes yes/no selection**
    - [ ] selected button turns dark blue `#2F4668`, remove drop-shadow; non-selected button fill changes to `#F0F0F0`
    - [ ] component expands downwards to reveal text, "Tell us more..." text, and an `open text field (not required)`with a primary "submit" button below the open text field. 
    - [ ]  User can see character limit countdown [specify character limit]
- [ ]  **Submit**: when user selects "submit" the button label changes to the "sending" state (as we have it in forms where the 3 dots animate), and their response should turn gray `#ADADAD`
    - [ ]  When submitted successfully, button turns green with white checkmark, indicating the feedback was successfully recorded. 
    - [ ] success display, "Feedback received. Thank you for helping improve this website!" with a green success badge below
- [ ] **Success**: resident feedback is recorded on the backend [not sure how], and a Slack issues is created (based on how the previous feedback component worked)

**Comment by chasechenevert** [comment]
- [ ] Develop acceptance criteria for dev

**Comment by chasechenevert** [comment]
## Mockups
- Mobile ([spec](https://xd.adobe.com/view/39c67b3c-10fe-4226-6e8a-0dfd7b1cb47d-4ff7/screen/7c8bbf35-e76d-4a6f-963a-33e912a2e8dc/Feedback-mobile-))
- Desktop ([spec](https://xd.adobe.com/view/39c67b3c-10fe-4226-6e8a-0dfd7b1cb47d-4ff7/))

## Question
It's hard to know how this should be designed without knowing the type of feedback we want/need? I've seen feedback phrased and displayed a few different ways, and they all try to encourage particular feedback from the user. 

Examples of feedback prompts I've seen: 
- "Did you find what you were looking for on this webpage? (yes/no)
- "Is this page useful" (yes/no)
- "Is there anything wrong with this page? (link)
- Emoji scale 1-5
- "Send feedback about our Help Center"

## Notes
**Content - label/question phrasing**
Should we keep the label/question open-ended and general, such as “Give feedback", or be more prescriptive like the examples before? 

**Design**
- Depending on the way we phrase the question we could eliminate the need for yes/no buttons.
- Going back and forth about whether the feedback component should visually be related to the page body, or the footer. In the mockup I’ve made the feedback component relate more to the page body as opposed to the footer with the idea to encourage users (via proximity and styling) to give feedback based on the page they are on currently.
- The leading icon is just an idea to call more attention to this component but not making it appear as a primary action (bright blue)
- Dev thinking about how we record this feedback. My understanding is that a Github issue is created once the feedback is recorded. Beyond that, I’m not sure how we’d want to interact with this feedback as a team.

**Comment by desigonz** [comment]
- Include browser/device info

**Comment by chasechenevert** [comment]
# Pin-up notes and next steps
Looking at options of 1. an open text field, or 2. a yes/no question and then an open text field, we've decided that we want to **make it as easy as possible for residents to submit any kind of feedback** and we think that a yes/no answer is more useful than none at all. If residents want to provide a more detailed response they'll have the ability to do so, but it won't be required.

## Next steps
- [ ] Use the visual design of the light gray bar, but incorporate the yes/no buttons across mobile and desktop
- [ ] Update criteria to match the design
  - [ ] Specify button states

**Comment by chasechenevert** [comment]
I think this is ready for Dev now, but please review and let me know @desigonz 
- Mocks for desktop and mobile show the full flow with both answers 
- Dev criteria has been updated, but since this flow has a few different states I want to be sure dev has everything they need

**Comment by desigonz** [comment]
Thanks! New issue for dev implementation is #3147.
