### ISSUE TITLE
Janis/Joplin - Translated service page steps

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1843]
We need to update them to have translations, from what I can tell it should be decently straightforward on the Joplin side of things: https://github.com/cityofaustin/joplin/pull/225

**Comment by oliver2g** [comment]
@briaguya should this be assigned to you?

**Comment by easherma** [comment]
Acceptance:

- [ ] Steps are in the editor
- [ ] Steps can be added for any language
- [ ] Steps data can be entered neiher joplin nor janis break
- [ ] make sure we can at least still build the english steps correctly
