### ISSUE TITLE
Janis - "City of Austin" in desktop header has centering issues

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1844]
It appears as if we're centering "City of Austin" in the header in a way that depends on the width of the containers on the sides, we should rethink this if we want to have it be in the actual center

<img width="1604" alt="Screen Shot 2019-05-03 at 7 38 10 AM" src="https://user-images.githubusercontent.com/6384156/57137807-8bc4a680-6d76-11e9-92cc-a05ad6899d1f.png">
<img width="1594" alt="Screen Shot 2019-05-03 at 7 38 21 AM" src="https://user-images.githubusercontent.com/6384156/57137812-8f582d80-6d76-11e9-8e50-5aa6a33bff46.png">

![together](https://user-images.githubusercontent.com/6384156/57137919-e0682180-6d76-11e9-8574-3763c3db599b.png)

**Comment by easherma** [comment]
@oliver2g I played around with this a bit, but I'm not sure whether it should be much of a priority? It isn't really needed for MVP/microsite transition. Could be better for a Janis 2.1 or 2.1.1

**Comment by oliver2g** [comment]
@easherma let's talk at Sprint Planning

**Comment by briaguya** [comment]
something fixed this, it's working properly on alpha.austin.gov rn
