### ISSUE TITLE
Finalize test plan for tree testing alpha navigation 

### ISSUE THREAD

**Issue by kriskristin** [cityofaustin/techstack#1848]
##### A super thorough guide on tree testing
https://treetesting.atlassian.net/wiki/spaces/TTFW/overview

##### Alpha navigation testing plan
https://docs.google.com/document/d/1kCkMKce5MSXxYzxgF7sEAQBWPqz78XWes2NTHapnyJs/edit?usp=sharing

##### Next steps
* Develop a schedule and find someone else who would have time for some tasks. Another idea is to determine what we need specifically and ask for help on smaller specific tasks. (Analytics, organizing a new map)
* Build out the tree of austintexas.gov
* Determine tree test tasks, including:
(Most common tasks, critical tasks and tasks that exercise problem areas)

**Comment by oliver2g** [comment]
@kriskristin is this issue still in progress for this Sprint? If so, would you mind updating the milestone?

**Comment by kriskristin** [comment]
@srigdon 

###### Here are the nav tests for you to review. 
[Austintexas.gov navigation tree test] (https://s36pu5zk.optimalworkshop.com/treejack/s2u1r038)
[Alpha navigation tree test] (https://s36pu5zk.optimalworkshop.com/treejack/vu1u50k1)

These tests are from the POV of the test taker. Some questions I have are:
* Does the test flow well? Is there something that can be improved?
* Are the intro/outro sections working? 
* Are there any confusing parts?

###### I would also like you to review where things map to on the trimmed Alpha nav
Here are screenshots from the admin side of the test. (You should have access to that through out office Optimal Workshop account in 1password.)

![Screen Shot 2019-06-25 at 10.19.13 PM.png](https://images.zenhubusercontent.com/5c7d9d4fd74bd07972c5327e/c834f8fb-2806-45c0-9edb-166f2d4c5195) 
![Screen Shot 2019-06-25 at 10.19.30 PM.png](https://images.zenhubusercontent.com/5c7d9d4fd74bd07972c5327e/1310f4c1-0c64-493a-88e1-98e6fda0cd28)
![Screen Shot 2019-06-25 at 10.19.39 PM.png](https://images.zenhubusercontent.com/5c7d9d4fd74bd07972c5327e/5ce49ab3-7c2c-47c4-b494-7f8f5b6b9676)

Question:
* Are there any qusetions that we should add in their polyhierarchy structure?
* Do the end nodes look correct to you? 
* Is there something else we can add to the test that would get the content team clarity on the IA? Basically, are there general questions about our IA that content has? How can we leverage this time to get insight into those questions?
