### ISSUE TITLE
Make sure analytics tracking code for alpha.austin.gov is correctly implemented

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1850]
When @toribr checked site speed, it seems to say that the URL getting tracked is staging. Let's look into this and make sure production is set up.

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/9a5c7f0a-770f-4dce-8a70-322d19627f74)

**Comment by easherma** [comment]
@desigonz FYI best staging url now is janis.austintexas.io , but yes this is important

**Comment by sergiogcx** [comment]
Using Google's Tag Assistant plugin for Chrome (https://get.google.com/tagassistant/), the tracking code seems to be enabled for both Prod and Staging (they both share the same tracking code):

Production:

![Screen_Shot_2019-05-10_at_5_57_27_AM.jpg](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/897b11d2-0e6a-4f14-a857-ba8f3a8dbbe3)

Staging:

![City_of_Austin.jpg](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/b5207979-1827-45b5-82ea-f59bd42ce33a)

**Comment by desigonz** [comment]
@sergiogcx Thanks for taking this on! I'm not sure on best practices re: implementing tracking codes for staging versus prod, but my gut tells me we don't want to muddy up prod data with all of the work we do on staging. Thoughts?

**Comment by sergiogcx** [comment]
You are right, I am going to have it removed from the staging site. For some reason I assumed it needed to be there for the build process.

That will be taken care of today, if not tomorrow. It only takes 5 minutes.

**Comment by sergiogcx** [comment]
This is taken care of through this PR:
https://github.com/cityofaustin/janis/pull/402

**Comment by sergiogcx** [comment]
Merged to master, please review.

![Screen Shot 2019-05-14 at 8.32.59 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/d8cf2c5a-311e-4280-805f-e0848b587bb6)

**Comment by desigonz** [comment]
Excellent! I verified using Google Tag Assistant as well. So when the next release gets pushed to prod, the analytics tag will still be on Alpha prod but not on staging, correct?

![image](https://user-images.githubusercontent.com/5839508/57790307-18208300-7700-11e9-83c7-3d83a3472f3b.png)
