### ISSUE TITLE
Content template review and revise 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1858]
To-do item in Content governance doc 
https://docs.google.com/document/d/1RTj0nrl5xufueC8fjoktPy_GwBKdICYD4ecI04CBaMQ/edit

Content templates
- [x] Information page 
- [ ] Service page (needs updating)
- [ ] Guide (formerly process page) (under development) 
- [ ] Topic page
- [ ] Topic collection page
- [ ] Department page (tweak, currently going off of Office of Police Oversight’s dept page)
- [ ] To do: Audit templates in Joplin to verify if templates will best serve workflow for us and future content owners

**Comment by LauraTrujillo** [comment]
Closing this because it's so similar to #1859
