### ISSUE TITLE
Parity with google doc templates and Joplin templates

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1859]
Per comment in Content Governance doc 
https://docs.google.com/document/d/1RTj0nrl5xufueC8fjoktPy_GwBKdICYD4ecI04CBaMQ/edit

![Screen Shot 2019-05-06 at 2.20.03 PM.png](https://images.zenhubusercontent.com/5c4b52abd709c56fe9edad32/8f35fb7c-ad8f-4551-b4a3-0b3b372f5158)

**Comment by easherma** [comment]
This seems like something dev and content should sync on. Maybe a meeting with 1-3 people.

**Comment by annieszot** [comment]
Want to set up the meeting @easherma with you, Desi and Laura? 
Here is the meeting invite and agenda template: 
Meeting Purpose: Dev and Content team sync on google doc templates and Joplin templates 
Date, Time: 
Facilitator: 
Time/Agenda Item | Next Steps

**Comment by easherma** [comment]
Are google doc templates still relevant if we can get everything into joplin? Were very close to that being a reality.

**Comment by desigonz** [comment]
@easherma At least while content editors across City departments aren't on Joplin, drafting and editing on a Google doc first will likely always be our reality—we need to draft and get their feedback (via in-line edits and comments) before inputting. And my guess is that, even when users have a great authoring interface, they might still be inclined to drafting and reviewing in word processing tools.

**Comment by LauraTrujillo** [comment]
@desigonz, @easherma yep! Plus it'll help us with translations until we figure out that workflow. (woo!)

**Comment by LauraTrujillo** [comment]
Per #1858 comment:

To-do item in Content governance doc 
https://docs.google.com/document/d/1RTj0nrl5xufueC8fjoktPy_GwBKdICYD4ecI04CBaMQ/edit

Content templates
- [x] Information page 
- [ ] Service page (needs updating)
- [ ] Guide (formerly process page) (under development) 
- [ ] Topic page
- [ ] Topic collection page
- [ ] Department page (tweak, currently going off of Office of Police Oversight’s dept page)
- [ ] To do: Audit templates in Joplin to verify if templates will best serve workflow for us and future content owners
