### ISSUE TITLE
Missing title for Spanish share page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1863]
This is only happening on staging right now: https://forms.austintexas.io/policia-queja/compartir-archivos

What I expect: to see the title "Comparta archivos"
What I got: missing title!!

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/b38db77c-8e04-4816-bd3b-c2dbabc7ac9c)

**Comment by sergiogcx** [comment]
The title seems missing in english too "https://forms.austintexas.io/police-complain/share-media"

**Comment by oliver2g** [comment]
The title isn't missing in Prod, so let's definitely include it in this release

**Comment by easherma** [comment]
Available shortly to QA at: https://opo.austintexas.io/police-complain/1863-share-media-title/

**Comment by desigonz** [comment]
@easherma Approved—looks great in both English and Spanish. Ready for you to merge the branch and close this issue!

**Comment by oliver2g** [comment]
looks like the title is still missing on the English form. https://forms.austintexas.io/police-complain/share-media
<img width="987" alt="Screen Shot 2019-05-10 at 4 28 11 PM" src="https://user-images.githubusercontent.com/35782646/57557699-abdd0280-7340-11e9-8439-90786d1989e3.png">

**Comment by easherma** [comment]
Its there. It was previously visible at the QA link above and is now in staging (master).
