### ISSUE TITLE
Configure analytics for tracking languages 

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1864]
Set up a way to track and analyze how Alpha is used for translated pages/different languages. This could be implemented via views.

**Comment by desigonz** [comment]
Various best practices recommend setting up views that filter out traffic based on language:
- https://moz.com/community/q/google-analytics-best-practices-for-multilingual-website
- https://www.jeffalytics.com/multilingual-tracking-google-analytics/

I've set up two new views on Google Analytics:
- English external traffic (filters out CoA and Faulk IP addresses, and only shows data for alpha.austin.gov URLs in the `/en/` subdirectory)
- Spanish external traffic (filters out CoA and Faulk IP addresses, and only shows data for alpha.austin.gov URLs in the `/es/` subdirectory)

One thing I'm noticing, though, is that a lot of our page views aren't actually at URLs with `/en/` or `/es`. Let's talk to the dev team about what might be going on here.

![image](https://user-images.githubusercontent.com/5839508/70166155-d77f5b80-1689-11ea-9a7b-e41632154586.png)

**Comment by desigonz** [comment]
Per dev sync conversation:
- [ ] research how Google Analytics handles redirects

**Comment by desigonz** [comment]
Are there helpful? 
- http://www.chriscasarez.com/google-analytics-how-to-tutorial/analytics-redirect-tracking
- https://moz.com/community/q/tracking-301-redirect-traffic-in-google-analytics
- http://www.atlantaanalytics.com/practicing-web-analytics/how-does-google-analytics-handle-301-and-302-redirects/

**Comment by InaraFernandez** [comment]
I closed this issue since it's been implemented but will make a few notes: 
- Since implementation, ODD has gone remote, making it very difficult to capture strictly "external" traffic since we are working remotely. I am creating a new issue calling for a revision of our property views.
