### ISSUE TITLE
Clean up janis layout/make easier to start

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#1869]
Janis seems to rely on Docker for no particularly good reason. Perhaps we can clean up it's layout and allow for easier adoption by others by not requiring Docker to run react-static. As is, running react-static by itself does not happen without errors either, which is kinda silly.

**Comment by sergiogcx** [comment]
There are plenty of important reasons Janis is built on docker, in the beginning it was used to imitate the environment where is to be deployed (first Heroku, now on AWS).

Feel free to work around docker for local development, but be advised there can be a number of implications of getting rid of docker entirely.

**Comment by sergiogcx** [comment]
Docker makes sense to me to have other services containerized, it facilitates getting rid of existing databases without compromising local resources. Seems to me like an easier pipeline and easier management of code and environment variables.

That being said, I do like the idea of being able to run Janis without docker but not getting rid of docker entirely.

**Comment by easherma** [comment]
Being addressed in tandem with a dependency upgrade: 
https://github.com/cityofaustin/janis/pull/395
