### ISSUE TITLE
Design preflight process

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#187]
A process for checking design work to ensure that it produces an acceptable user experience. This could be a metric like _90% of users can complete task_.

Aha! Link: https://desi1.aha.io/features/RT-340

**Comment by amenity** [comment]
This is going to stay in backlog for the time being, but we want to have a process like this to ensure we're testing every feature. Having a remote testing tool would support this by allowing it to be done expediently on a regular basis.

**Comment by cthibaultatx** [comment]
@amenity this could come from a draft and then meeting to review draft by me/Tori/Julia

**Comment by toribr** [comment]
Sunsetting.
