### ISSUE TITLE
Lets look at wagtail updates

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#1870]
While we are looking at react-static updates, we should also be mindful of wagtail updates. 

There has been almost a full year of updates on the wagtail end we haven't included. 

Just glancing through the changelog and things popped out at me, such as: 
* validators for StreamFields
* markdown style formatting in rich text fields
* localization fixes for dates
* more informative error messages
* better color contrast
* functions to prevent indexing admin pages
* refactoring of admin stuff

Nothing earth shattering, but it might not hurt to take a look at an upgrade

**Comment by briaguya** [comment]
We also might be able to clean up our API and not do so many things manually if we use something like this: https://github.com/tr11/wagtail-graphql

**Comment by easherma** [comment]
https://github.com/cityofaustin/joplin/pull/228 seems pretty groovy and good to go
@briaguya I'll make a seperate issue for wagtail-graphql

**Comment by easherma** [comment]
added @briaguya  for QA
