### ISSUE TITLE
love chicken logo in menu

### ISSUE THREAD

**Issue by oliver2g** [cityofaustin/techstack#1872]
Do we want to keep the love chicken logo next to the "more about the alpha.austin.gov project." link? I think this is an internal ODD logo that is acting as a competing brand with the COA seal. What kind of icon (if any) should we use?

**URL tested:** https://janis.austintexas.io/

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Chrome&browser_version=73.0&zoom_to_fit=true&full_screen=true&url=http%3A%2F%2F311.austintexas.gov%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=http://311.austintexas.gov/) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 73.0 |
| Operating System | OS X High Sierra |
| Resolution | 1920x968 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/31dc81f3ce44458e1fffaa6caeb063341813da9b/machs_chrome_73.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/31dc81f3ce44458e1fffaa6caeb063341813da9b/machs_chrome_73.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Chrome&browser_version=73.0&zoom_to_fit=true&full_screen=true&url=http%3A%2F%2F311.austintexas.gov%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=http://311.austintexas.gov/) to reproduce the issue on Browserstack**

**Comment by oliver2g** [comment]
@chasechenevert any ideas on this issue before we demo next week?

**Comment by chasechenevert** [comment]
Definitely! 

### Proposed design changes
- [ ] Replace our Love Chicken™ with the "info" icon from the Google Material icon font and size it to match the city seal (I have 36px on my end)
- [ ] Change the menu footer background color to `#F8F9FA`
- [ ] Include a 1 px stroke to the top of the menu footer (serves as a divider) with the bright blue color `#0049C7`
- [ ] Include a 1px stroke with the bright blue color `#0049C7`

<img width="1349" alt="Screen Shot 2019-05-23 at 2 52 02 PM" src="https://user-images.githubusercontent.com/7027270/58282082-5a823980-7d6a-11e9-9fa3-16c843174a67.png">

**Comment by sergiogcx** [comment]
Taken care of through this PR:
https://github.com/cityofaustin/janis/pull/425

https://janis-pr.austintexas.io/425/
