### ISSUE TITLE
Menu doesn't close after clicking a Service tile

### ISSUE THREAD

**Issue by oliver2g** [cityofaustin/techstack#1874]
Current:
1. Click on a menu item to open the menu (e.g. Permits & Tickets.
2. Click on a tile under "Check out City of Austin Services" (e.g. Get ready for curbside bulk item pickup). The menu remains open and blocks the top half of the page, including the page title.
3. The menu won't close unless I close it manually.

Expected:
1. When clicking on a tile, the menu closes automatically.
2. When clicking anywhere outside the menu, the menu closes automatically

**URL tested:** https://janis.austintexas.io/

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Chrome&browser_version=73.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fjanis.austintexas.io%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://janis.austintexas.io/) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 73.0 |
| Operating System | OS X High Sierra |
| Resolution | 1920x968 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/26198c1c8eacfad465f2a02aa7ffe0fc288b16fe/machs_chrome_73.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/26198c1c8eacfad465f2a02aa7ffe0fc288b16fe/machs_chrome_73.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Chrome&browser_version=73.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fjanis.austintexas.io%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://janis.austintexas.io/) to reproduce the issue on Browserstack**

**Comment by sergiogcx** [comment]
This issue is fixed through PR (late commit)
https://janis-pr.austintexas.io/397/

Code:
https://github.com/cityofaustin/janis/pull/397

**Comment by briaguya** [comment]
resolved by #1790
