### ISSUE TITLE
Discuss joplin testings/PR /deployment process

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#1876]
**Objective** 
We're all jumping back into joplin, @sergiogcx and @Niicck have ongoing changes that affect deployment, and it would be good to get on the same page and discuss testability/criteria for future PRS. 

Also related https://github.com/cityofaustin/techstack/issues/897

------
- [ ] Schedule meeting
- [ ] Meet
- [ ] Create resulting issues

**Comment by Niicck** [comment]
A fine idea. I'm not quite ready for a meeting yet. I think after another week I will be. I need more time reading the code on my own.
