### ISSUE TITLE
Review pre-OPO content

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1880]
@LauraTrujillo, can you take a look at the following pages, and then for each page that you think needs some reworking before translating and Janis 2.1 launch (a.k.a. anything that is bigger than just a copy/style edit), make a new issue for them? We can then divvy up these issues among team members. Feel free to add comments about what needs revising! 

(I am going to make a separate issue for copy editing/checking for style.)

If/when English copy is approved, please indicate so on the [Janis 2.1 translation spreadsheet](https://docs.google.com/spreadsheets/d/1HnKT-FnLAeLc9YT__pUAk2UdMEI1opwfPuzVFxct8NI/edit?usp=sharing).

- [x] Get immunizations for you and your family
- [x] Drop off household hazardous waste and other recyclables
- [x] Get a birth or death certificate
- [x] Get ready for curbside bulk item pickup
- [x] Get ready for curbside compost pickup
- [x] Set out your leaves, grass, and branches for pickup
- [x] Pick up free paint and other household items
- [x] Prepare for public health emergencies
- [x] Find free condoms and learn other ways to prevent HIV
- [x] Look up your trash, recycling, and compost pickup days

Unsure of this one:
- [x] "Interior remodel" is live on Joplin backend but I don't think it's supposed to be?

**Comment by desigonz** [comment]
Note: make sure to look at "Get ready for curbside bulk item pickup" and "Get ready for curbside compost pickup"—per the mellifluous words of @easherma:
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/40c8d1ad-7b47-4730-88a5-a6d8a876fe7d)

**Comment by LauraTrujillo** [comment]
I'm going to create an issue to get approval for the English copy missing per the Janis 2.1 translation spreadsheet. (Looking at you, immunizations)
- Made a few edits to "Interior remodel" but putting that on the backburner for now, since that may be part of the guide??
