### ISSUE TITLE
Research and decide whether to write descriptions for topic pages

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#1881]
Do topic pages need descriptions? We might need this for SEO later, but for now, is it OK to ship content without this? 

We want to know: 

- [ ] How to people find topic pages? 
- [ ] What does Google do with the topic pages when you search for key phrases that land you there? 

Example topic page: https://janis.austintexas.io/health-safety/disaster-safety-relief/disaster-preparedness/

**Comment by LauraTrujillo** [comment]
From my copy editing spree, the following drafted topic pages would need descriptions if we choose to go that route:  
- [ ]  Recycling & reuse
-- Need description
- [ ] Compost & food waste
-- Need description
- [ ] Household waste
-- needs description
- [ ] Recycling, trash, and compost
-- needs description
- [ ] Birth & death certificates
--  needs description
- [ ] Disaster & safety relief
-- needs description
- [ ] Healthcare & prevention
-- needs description
- [ ] Health records & certificates
-- needs description

**Comment by LauraTrujillo** [comment]
We decided this is not MVP, but more P2 based on Desi's MVP doc.
