### ISSUE TITLE
Copy edit all existing content

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1882]
- [x] First review: @LauraTrujillo 
- [ ] Second review: @JeffCopy 

Let's make sure our copy is clean. Make sure to review all pages: 
- home page
- topic collection pages
- topic pages, service/information/department pages
- any and all UI elements, including nav. 

With nav items: themes are not using sentence case; should they? Additionally, for nav items, we sometimes use `&` while other times use `and`. Need to make a decision on this (and make an issue to codify in our style guide). Also, what implication would `&` have on translations?

For anything that isn't content manageable, write a new issue and assign to `Team: Dev`, and set release to `Janis 2.1`. If it is content manageable, update in Joplin.

Please keep it to a copy edit—no substantial rewording unless something is egregious.
- title conventions (service page = start with verb, information page = noun—for now.)
- spelling
- grammar
- [style](https://docs.google.com/document/d/1yL3afGS_72aFYBoF7ZH90yUCNeqAgYx1RuRxc_JbZAw/edit#heading=h.4dkllygu82ul)—make sure that:
  - headings and buttons are all sentence case
  - phone number format is (512) 972-5520
  - [street names are spelled out in addresses](https://docs.google.com/document/d/1yL3afGS_72aFYBoF7ZH90yUCNeqAgYx1RuRxc_JbZAw/edit#heading=h.v0kb4hzegeov)
  - [times follow this convention](https://docs.google.com/document/d/1yL3afGS_72aFYBoF7ZH90yUCNeqAgYx1RuRxc_JbZAw/edit#heading=h.v2926m4hzgf3)

**Comment by LauraTrujillo** [comment]
- [ ] [Flu prevention](http://joplin.herokuapp.com/admin/pages/32/edit/) 
-- Currently tied to Austin Resource Recovery, can't select Public Health as department
- [ ] [Disease prevention](http://joplin.herokuapp.com/admin/pages/53/edit/)
-- Needs description of topic page
- [ ] [Drop off household hazardous waste and other recyclables](http://joplin.herokuapp.com/admin/pages/11/edit/)
- [ ]  [Recycling & reuse](http://joplin.herokuapp.com/admin/pages/59/edit/)
-- Need description
- [ ] [Compost & food waste](http://joplin.herokuapp.com/admin/pages/58/edit/)
-- Need description
- [ ] [Measles in Austin](http://joplin.herokuapp.com/admin/pages/33/edit/)
-- Need to add Public Health Department
- [ ] [Interior remodel](http://joplin.herokuapp.com/admin/pages/16/edit/)
-- Need Development Services Department
- [ ] [Get immunizations for you and your family](http://joplin.herokuapp.com/admin/pages/9/edit/)
-- Need table for shots :) 
-- Need Public Health Dept.
- [ ] [Get a birth or death certificate](http://joplin.herokuapp.com/admin/pages/65/edit/)
-- Need Public Health Dept
-- Has an author note, FYI
- [ ] Set out your leaves, grass, and branches for pickup
- [ ] Look up your trash, recycling, and compost pickup days
- [ ] Prepare for public health emergencies
- [ ] Pick up free paint and other household items
- [ ] Get ready for curbside compost
-- Update name. Still not easy to differentiate between this and bulk (the "get ready" should be changed)
- [ ] Get ready for bulk item pickup
-- Update name. Still not easy to differentiate between this and bulk (the "get ready" should be changed)
- [ ] Find free condoms and learn other ways to prevent HIV
- [ ] Austin Resource Recovery
- [ ] File a complaint against an Austin Police Officer
- [ ] Office of Police Oversight
- [ ] Household waste
- [ ] Get a mobile food vendor permit (I feel like this is one that doesn't need review, as it's moving to the guide template??)
- [ ] Recycling, trash, and compost
- [ ] Birth & death certificates
- [ ] Disaster & safety relief
- [ ] Healthcare & prevention
- [ ] Health records & certificates
- [ ] Grow a community garden
- [ ] Learn how to prevent crypto and other waterborne diseases
- [ ] Privacy policy for Alpha.Austin.Gov
- [ ] Community gardens
- [ ] Get a community garden permit
- [ ] Complaint investigation process
- [ ] Parks and Recreation
- [ ] How we store and use your data
- [ ] Get in line at Qless
- [ ] Become an animal foster care provider (can probably scrap this page as well)

**Comment by LauraTrujillo** [comment]
I didn't make any changes to nav items regarding the "&" question because I wanted to discuss with y'all. 
However, I do think themes should be in sentence cases. Let's discuss!

**Comment by desigonz** [comment]
Make the decision to replace ampersands with "and." Opened #2384 to address outstanding hard-coded edits. Closing!
