### ISSUE TITLE
Submit Janis 2.0 content for translation

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1886]
All existing ARR and APH content, as well as UI features and current homepage.

Refer to this [Google spreadsheet](https://docs.google.com/spreadsheets/d/1HnKT-FnLAeLc9YT__pUAk2UdMEI1opwfPuzVFxct8NI/edit?usp=sharing).

**Comment by LauraTrujillo** [comment]
@desigonz does this refer to the translations we just received?

**Comment by desigonz** [comment]
yep, closing this one
