### ISSUE TITLE
SXSW learnings deck

### ISSUE THREAD

**Issue by juliazbyron** [cityofaustin/techstack#189]
Spend 1 hour creating deck, 1 hour presenting over lunch. Send a meeting invite to DTI listserv.

**Comment by amenity** [comment]
@juliazbyron - you did this, right?

**Comment by amenity** [comment]
https://docs.google.com/presentation/d/1G_NKv4c7-URkPq72lZy4BVTRDmaaIhLeKBWIY3g7n6M/edit?usp=sharing
