### ISSUE TITLE
"stuck": errors prevent continuing or going back (complaint staging)

### ISSUE THREAD

**Issue by oliver2g** [cityofaustin/techstack#1898]
When trying to navigate between "What Happened?" and "Where were you?" pages using the "Continue" and "Back" buttons, the browser gets stuck. The buttons essentially stopped working. The only thing that changed was the page title.

Note in the screen shot that the title is "Where were You?" but the fields from the "What Happened?" page. Also note "where-happened" in the url. Maybe that's the problem.

**URL tested:** https://forms.austintexas.io/police-complain/where-happened

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-complain%2Fwhere-happened&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-complain/where-happened) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1920x920 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/c243446e9ad95841bd46b44424cddb6cab56e19a/machs_safari_11.1.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/c243446e9ad95841bd46b44424cddb6cab56e19a/machs_safari_11.1.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-complain%2Fwhere-happened&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-complain/where-happened) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
I haven't been able to replicate this on the same browserstack, lets close for now but re-open if we spot it again.
