### ISSUE TITLE
Requirements and research on CMS sustainability

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#190]
Was thinking last night about your CMS concerns. It feels like something we should address sooner rather than later. There are obviously a lot of things to think about:
- Would doing a decoupled Drupal, Wordpress, etc. allow us to reuse the components Simi and Mateo are about to start rebuilding? 
- Would we want to use a form builder that comes with that CMS? Drupal 8 has a well-maintained tool that I think is very accessible very their API we might want to consider, especially as we evaluate what our "in-house" open source form tool and avoid the option of building that from scratch. 
- How can we continue to apply the testing we're doing on Alpha so that it isn't held up by the time it takes to build? 
- How can we enable continued content transitioning while we are unsure of a CMS we want for a longer period of time? We don't want to interfere with momentum of Funshops and department engagement.
- As we hire fellows (or fill the CTM postings) would we want someone familiar with a specific CMS? Most can be implemented well or badly - so imho it helps to have someone who knows their best practices. This would be from a site-building/maintenance perspective, e.g. a non-dev specializing in IA, content models, participation in open source community, user roles, etc. to work in close collaboration with the team.
- How can we work with the content team to ensure they don't invest too specifically in a Funshop curriculum that centers around the current CMS UI. 

BW: Many of these answers need to account for CTM, which we haven’t done a good job of doing. They also can’t be done without good vision/leadership from our visionaries/leaders :slightly_smiling_face:

**Comment by amenity** [comment]
Just discussed using [GatherContent](https://gathercontent.com/)[[API]](https://docs.gathercontent.com/reference) as a tool to facilitate ongoing department transitions while we worked on this. 

Marni also suggested [OpenCities](http://www.opencities.com/Home).

**Comment by amenity** [comment]
As far as the process — in my mind this would be one dev looking at options. The last "CMS evaluation exercise was arduous, so let's do this in a way that's not. 🙂We know a lot more about what to look for now!

Anything from checking out the API (b/c we would want to stay decoupled), to talking to other cities using different tools*, to standing something up locally. 

_* Orlando is using OpenCities, Philadelphia is using Wordpress, and San Francisco is using Drupal. When we spoke to Bryan at Mass.gov last time, we had already decided not to use Drupal 8 for round one, so our [discussion centered more around design systems](https://docs.google.com/document/d/1hJ4FI85XmavaESLy4B7qBZXWKS299ZeBS8qP6JulDqE/edit#heading=h.4jcinetsex1r). Could circle back with him, Harlan, & Jesse for info on how D8 is working for them.

**Comment by amenity** [comment]
[Material Admin](https://github.com/briancwald/material_admin) is a Drupal Admin theme "geared to being a theme used for decoupled Drupal where Drupal is the backend administration tool." 
![Date](https://www.drupal.org/files/material-admin-date.png) ![Dashboard](https://www.drupal.org/files/material-admin-content.png). [More screenshots on Drupal.org](https://www.drupal.org/files/material-admin-content.png).

**Comment by amenity** [comment]
@toribr - @Ben and I discussed initiating this research after you handed over the synthesis from your first round of CMS testing. Does that sound right to you, and if so - when do you think that will be?

**Comment by amenity** [comment]
@courtneyjacinic @ashleecoa @LauraTrujillo - wanted to pull you into this convo. :) 

_Impact on Funshops?_
Do you expect to incorporate any CMS-specific material into the Funshop? I understand if you feel you need to — you know your audience. I just don't want to invest too specifically in that aspect of the curriculum since we expect the CMS functionality and UI to evolve. 

_Impact on content transition_
- Do you think we need a staff-friendly CMS to transition EMS and DSD content? Or will we be able to handle it the same way as we did with ARR, with someone from the core team entering it into the CMS themselves?
- Do you have a general sense of we'll begin transitioning content at scale and bring in more content strategy & copywriting resources?
- At what point, if ever, would you like to see a CMS solution (look & feel, functionality) that we'll commit to using for a while? If so, how long a while?

**Comment by LauraTrujillo** [comment]
@amenity Thanks!

- There is not any CMS-specific material in any of the Funshops because we want to focus on the content itself, not the (wonderful) bucket that will be holding it. 
- Preferably whatever CMS we end up with will be staff-friendly, but yes- initially someone from the core team will enter EMS & DSD's content themselves.
- We will have more of a general sense of when we'll begin transitioning content after Adam organizes the departments into "buckets" (re: dept. prioritization).
- I would love to see a CMS solution as soon as possible so that we can begin training ARR (and then the world! I mean, the rest of City of Austin employees) on it. I understand that we may not have a CMS forever, but I don't want to define "a while" right now. Just long enough that employees aren't constantly having to re-learn how to use a system.

**Comment by toribr** [comment]
@amenity @ben I wouldn't expect the outcome of this round - or any round of testing, for that matter - to have an impact on CMS choice. If the CMS discussion needs to be had, then I would vote for making that decision as soon as possible, regardless of the author UI, testing, etc.

**Comment by toribr** [comment]
Sooo... previously I have stated that I was platform agnostic. After testing with a few City staff, however, that view has completely changed. I'm totally against us using Drupal, all in on Wagtail. I just can't see us making the usability leaps we need to make with Drupal. We've got huge wins ahead of us with this redesign, but we need a platform we can keep light and streamline and make what we need, instead of wrangling all the stuff we don't need.

**Comment by amenity** [comment]
This needs to be broken up into actionable issues.

**Comment by amenity** [comment]
So, for anyone who hasn't heard, the dev team has chosen our for-the-next-few-years CMS. 
@Tori Breitling - you'll be relieved to know that its Wagtail! :person_doing_cartwheel: :bird: :tada: :woman-cartwheeling:

Factors
======
   - The concern about continuing Wagtail was about the organizational readiness to sustain it, e.g. more devs and training for existing staff to join in supporting it.  We believe strongly that this is the direction that will take the city's digital services further long-term.
   - Python (on which Wagtail is built) is a good language to adopt
           - It's applicable to a wide range of applications integral to municipal digital services, e.g. maps & data analysis
           - It has a large open source community
           - It is attractive for developers coming from the private sector
    - The author experience we're working towards will be cleaner and we can implement Tori's design with higher fidelity if we build it ourselves
   - We want to get away from the notion that only devs can write code, e.g.
           - Adding 311 services to Wagtail looks like this:  https://github.com/cityofaustin/joplin/pull/113. It's a pretty easy pattern to follow and modify
           - Similarly, the [Mozilla JSON Form schema](https://mozilla-services.github.io/react-jsonschema-form/) | [Playground](https://mozilla-services.github.io/react-jsonschema-form/) which is just a hierarchy of field types and help text. 

Shout out to @benweatherman and @toribr for weighing in with ux and dev perspectives!
