### ISSUE TITLE
techy error message on location (staging complaint)

### ISSUE THREAD

**Issue by oliver2g** [cityofaustin/techstack#1900]
techy error message displays after entering an address / moving the map, clearing the address field, then trying to continue. Can this be hidden?

**URL tested:** https://forms.austintexas.io/policia-queja/donde-sucedio

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Fdonde-sucedio&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/donde-sucedio) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1920x920 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/52ba15b500bd6060e0c9b3de5a7c8c432c823852/machs_safari_11.1.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/52ba15b500bd6060e0c9b3de5a7c8c432c823852/machs_safari_11.1.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Fdonde-sucedio&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/donde-sucedio) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
This bug did surface earlier; I believe we have another issue for this in the backlog or closed somewhere.
