### ISSUE TITLE
Visual design for legalese pages

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1902]
How does the privacy policy page look? Legal notices? Contact us? Can the info page be used, or do we need to make it look different?

**Comment by chasechenevert** [comment]
Current idea for these pages is to use the Information Page content type. I haven't looked at any of the legal information to understand whether it breaks the content model, but I can check in with Content to see if they have any updates.

**Comment by desigonz** [comment]
Here's a preview of the privacy policy as an info page: https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxMzcx

Closing this issue because it seems pretty settled!
