### ISSUE TITLE
Janis - nav footer

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1903]
**Acceptance criteria**
desktop view
- [x] Themes and topic collections displayed
- [x] As in meganav, if there is no topic collection under a theme, "Coming soon" appears
- [x] clicking topic collection takes you to topic collection page

mobile view
- [x] by default, theme accordions are collapsed
- [x] if you click on a theme, the accordion expands and displays topic collections
- [x] (@chasechenevert, can you check that items in accordions are displaying as expected? should there be those bullet points?)

https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/b3294341-554f-4f83-a6db-bd4eb014d91e/Navigation-Footer-Desktop-/

We don't have this implemented, we probably should change that

If there are things blocking this from being "done done" I'll make them

**Comment by oliver2g** [comment]
@briaguya can you estimate this and add it to either Sprint 30 or 31? Thx

**Comment by briaguya** [comment]
Made a PR with my progress so far. https://github.com/cityofaustin/janis/pull/409

**Comment by desigonz** [comment]
assigning @chasechenevert for QA. Use this: https://deploy-preview-409--janis.netlify.com/

Let's check against what we have now (are the themes and topic collections working, and are they styling correctly?). I'm also going to make another issue for the seal/contact/links/social part and redoing the blue bottom to remove the white seal and make it skinnier (@chasechenevert, let's touch base next week about that)

**Comment by chasechenevert** [comment]
This looks good to me! Just two things
- [ ] mobile view: "theme" color from `#0049c7` to `#162e51`
- [ ] link hover to `#1a4480`
- [ ] remove bullets if it's not too much to do 

I'll make a separate issue to remove the bullets from the global/primary nav

**Comment by desigonz** [comment]
@briaguya to incorporate updates based on Chase's review. We want to get this in production!

**Comment by briaguya** [comment]
@desigonz this is merged into staging now, put it back in QA

**Comment by desigonz** [comment]
@briaguya Looks great per @chasechenevert's acceptance criteria above.

The one thing I noticed is that visited links turn purple only in mobile. I made #2799 to cover this, and we can deal with it later. Your nav is ready for prod :)
