### ISSUE TITLE
Write "Prepare your mobile food vendor permit application" page

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#1918]
Draft: https://docs.google.com/document/d/1BNWbpuTwmx9zUds4eLVFaLdrqSluJ4lef3bobu9DIK8/edit

**Comment by sergiogcx** [comment]
Not important or anything, but this is the year captain 'merica was born:

![Screen Shot 2019-05-16 at 1.17.48 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/3b6a5525-979e-4dd0-80d6-3e70dc15f993)
