### ISSUE TITLE
Content debt documentation workflow

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1923]
### As an Alpha content strategist and editor, I want a workflow for documenting content debt so that we can efficiently fix it when we have the needed functionality.

**Is your request related to a problem? Please describe.**
Content debt: We're publishing content on Joplin (yay!!) but don't always have the full functionality we'd like for the longterm, which causes us to do things like link to a PDF or form on austintexas.gov. How might we have a workflow that allows us to efficiently document content debt for later use?

**This could look like...**
1. Create an issue in Github. Label it "content debt." Maybe make a template for content debt documentation that asks:
  - What is the URL?
  - Describe the content debt. (What do we need to remember to do in the future?)
  - What is the long-term, ideal solution for the content debt? 
  - Is this related to a feature request issue? (Add the number below and add the issue as a dependency.)
  - What approvals will be needed to publish this content change?
2. Have a notes field in Joplin per page, and on that page, write in the Github issues number.

**Other thoughts**
- Should we do one issue per page, or one issue per content debt item? For example, a page might need a PDF hosted on Joplin and a new email alias. My vote is a separate issue for each; it will make it easier to sort through and close in the future.
- What would be super super amazing is some sort of Joplin-Github integration! Can we associate an issue with a page, and when we close it on Github, it no longer appears in Joplin? (I'm dreaming big.)
- Filter Joplin pages by things that have open issues.

**Comment by annieszot** [comment]
@desigonz Voila, content debt issue template! I also added 'What type of content debt is it'? 
https://github.com/cityofaustin/techstack/blob/master/.github/ISSUE_TEMPLATE/content_debt.md

**Comment by desigonz** [comment]
@annieszot @LauraTrujillo @srigdon @JeffCopy 

**Here's where we are with the content debt workflow**
When you input content into Joplin, if there are temporary solutions we're using that we need to fix once we have future functionality, do the following:
- Make note of it using the "author notes" feature in Joplin
- Make an issue for each bit of content debt using the [content debt](https://github.com/cityofaustin/techstack/blob/master/.github/ISSUE_TEMPLATE/content_debt.md) template
  - Fill out the template to the best of your ability
  - Add the "content debt" label, as well as the label for the particular feature this issue requires. (If the feature label doesn't exist, ask the product manager/team about it and tag "future feature.")
