### ISSUE TITLE
Rethink page titling convention

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1924]
As guides are forming, we're realizing that our conventions for titling pages will be crucial. Also, we've have an instance of service-oriented language with similar structure/verbiage is confusing. Let's get on the same page about how we use titles. This might require a meeting.

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/e6082db2-5517-47a5-bc47-b9f41dc6d75e)

**Comment by easherma** [comment]
This was partially inspired by me thinking two tiles were dupes when they weren't. It seems pretty clear that scanning these tiles could use some design refinements. 

@desigonz @annieszot and I were talking about how this might play into tweaks to the way titles are modeled. If we had verbs/actions associated with content type, we could break the title into some distinct chunks that would help make the page easier to scan. This could also help enforce/encourage service-oriented language as _part_ of the content writing by making it _actually_ part of the data model. 

![tile](https://user-images.githubusercontent.com/10539855/57661102-172c0c00-75af-11e9-8b2e-e2f02bd823e4.jpg)

**Comment by desigonz** [comment]
@srigdon Assigned this to you per our conversation at design pin-up today. Let me know if you have the bandwidth for it this sprint or if we should push it out, or if you'd like someone else to take it on.

**Comment by desigonz** [comment]
Title conventions are in the style guide so closing this issue!
