### ISSUE TITLE
Joplin - Functionality - Manage Contacts

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1929]
As a content manager, I want to see and manage contacts in one place that I can navigate to

Add the ability within Wagtail to create new and/or manage the contacts. (apparently you need to know the URL to do this currently)

**Comment by easherma** [comment]
So it looks like there is a section on each page for adding contacts from a given list, but you also want the ability to create new contacts presented in that same section? Or at least linked to.

**Comment by briaguya** [comment]
Split this in 2, the functionality (we now have a button to get to contacts) is covered by https://github.com/cityofaustin/joplin/pull/230, and we now have an issue to update this to match a fully fleshed out design for how we want to handle this (https://github.com/cityofaustin/techstack/issues/1942).
