### ISSUE TITLE
Joplin - Functionality - Add author notes to pages

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1932]
As a content editor, I need to add notes to a page about things I need to fix in the future

Bonus if it links directly to Github

This is essentially adding a text field for content authors to add notes about a page they are working on.
May need the ability to see if a note has been added from the page list. Naturally this note does not display on Janis.

**Comment by easherma** [comment]
Ooooeee at least from a dev perspective this would be a real big one but sounds kinda fun!

**Comment by briaguya** [comment]
@easherma could also be SUPER small if we just want to add a text box for now.

The displaying notes on the page list would be a bit more complex, but just adding the box is like 2 lines of code.

**Comment by sergiogcx** [comment]
I was thinking the same thing, have it styled a bit differently. I only wanted to consult with Tori first and gather more requirements.

**Comment by briaguya** [comment]
split this in 2 and made #2065
