### ISSUE TITLE
Joplin - Functionality - Assign pages to departments

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1934]
As a content editor, I need to be able to assign a info or service page to a department, so that when it is published it is associated on janis with the correct department.

Not quite sure how pages are currently assigned to a dept - some invisible mechanism on the backend?

**Comment by easherma** [comment]
Good question, I will check with @briaguya as this is impacting some other issues as well.

**Comment by briaguya** [comment]
@toribr I've updated this issue to be split in two: once we have a desired design for this we can use https://github.com/cityofaustin/techstack/issues/1943 to manage that, but for now, the functionality is intact:

<img width="1620" alt="Screen Shot 2019-05-15 at 3 39 11 AM" src="https://user-images.githubusercontent.com/6384156/57761513-4a5fbf80-76c3-11e9-9f9f-4214fe0ab5e3.png">

@easherma - Service pages, on the other hand, have not been set up as capable of belonging to departments as per: https://github.com/cityofaustin/techstack/issues/1413, we had:

* Service Pages can:
  * Belong to a topic only:
    * alpha.austin.gov/theme/topic/service_page_title

**Comment by toribr** [comment]
I don't recall the context of that decision, but a service pages should be able to display the department it belongs to in the light blue banner (to the right of where related and TCs are displayed).
![Screen Shot 2019-05-15 at 7 54 52 AM](https://user-images.githubusercontent.com/3790067/57777150-c0c1e900-76e6-11e9-9df6-fbf3d6d3824b.png)

**Comment by easherma** [comment]
@toribr can a single service page can belong to multiple departments?

**Comment by toribr** [comment]
@LauraTrujillo @desigonz 
Probably y'all are better equipped to answer this?

**Comment by briaguya** [comment]
@easherma a single Info page cannot

**Comment by LauraTrujillo** [comment]
@toribr @easherma @briaguya We prioritized that functionality as a nice to have in a later release. Not quite icebox later, but not a need just yet.

**Comment by easherma** [comment]
@LauraTrujillo FWIW on the dev end this is less of a functionality problem and more of 'clarity of the model' problem

**Comment by toribr** [comment]
@briaguya Was your intention for #1943 for this issue or for a longer term solution? Since you already have a way to assign depts to service pages, my thought was you'd use the same solution for info pages, at least for now. Am i missing something?

**Comment by briaguya** [comment]
@toribr the intention was for a longer term solution with #1943, the "functionality" part of this issue means "it's possible to assign service pages to departments" in the same way that we can with info pages right now

**Comment by toribr** [comment]
Ok, then if I am understanding correctly, this would become part of the yet-to-come epic we discussed yesterday that deals with managing meta things for pages.

**Comment by briaguya** [comment]
@toribr #1943 would, this one would be implemented more immediately so we can get rolling with the Janis ui and have "offered by" in place

**Comment by briaguya** [comment]
Closing this. Getting this to show up in Janis is now a part of https://github.com/cityofaustin/techstack/issues/2304
