### ISSUE TITLE
As a content editor, I need to see which language I am editing in

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1938]
Based on design for #1937

**Comment by easherma** [comment]
@toribr looks like this is pending design, but we could in the short term just make the active language filled in the same way it does when you hover over it at the top with your mouse to switch languages.

**Comment by toribr** [comment]
Yes, that would totally suffice for now.

**Comment by easherma** [comment]
addressed in https://github.com/cityofaustin/joplin/pull/235

**Comment by toribr** [comment]
![Screen Shot 2019-05-23 at 8 24 33 AM](https://user-images.githubusercontent.com/3790067/58256262-4f141b80-7d34-11e9-963c-c712276417f5.png)
We need a little tweak to this so there's a line between languages(boxes). In that way these will look like individual buttons and not one big button.
