### ISSUE TITLE
Analyze language access usability test data

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#194]
Synthesize Spanish, Vietnamese, and Arabic translation usability test results

**Comment by cthibaultatx** [comment]
@LauraTrujillo @ashleecoa @courtneyjacinic when do we want a deadline for wrapping this up and who should lead the documentation?

**Comment by cthibaultatx** [comment]
@LauraTrujillo can you post learnings doc link here?

**Comment by LauraTrujillo** [comment]
@cthibaultatx https://docs.google.com/document/d/17dj-r45EANoFiTemLE5bCa2ls5xgLrAe_sdmr5lSdiU/edit#
