### ISSUE TITLE
Joplin - Implementation Matches Design - Log out button

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1944]
**Acceptance criteria**
- [ ] Name is included within drop-down menu
- [ ] Left align menu items
[Link to mock; don't worry about the colors](https://github.com/cityofaustin/techstack/issues/1944#issuecomment-496570306)

Copied from: https://github.com/cityofaustin/techstack/issues/926

I'm not able to log out of Joplin. When I try to go to https://joplin.herokuapp.com/admin it redirects to https://joplin.herokuapp.com/admin/pages/3/, which has me already logged in. This is in Version 70.0.3538.110 of Chrome. When I went to the same page in Firefox, where I wasn't already logged in, I got redirected to the login page, which works, but now I also can't log out there.

https://joplin.herokuapp.com/admin/pages/3/

**To Reproduce**
1. Go to https://joplin.herokuapp.com/admin
2. See if it redirects to https://joplin.herokuapp.com/admin/pages/3/
3. See if you can find a way to log out.

**Screenshots**
https://drive.google.com/file/d/1em9btlbIvySXOo_ur6M0U35ern0W1KWd/view?usp=sharing

**Comment by briaguya** [comment]
UI/UX changes:
* Switch from having the email address to using First? name

**Comment by toribr** [comment]
Yes, use first name, please. Here's the final UI look.
![Screen Shot 2019-05-22 at 7 31 11 AM](https://user-images.githubusercontent.com/3790067/58183259-a5218a00-7c74-11e9-8f9a-3debfb80af6d.png)

**Comment by toribr** [comment]
There are a couple of visual issues here which aren't ideal. We need the menu to be part of the name (left-aligned) rather than the way it looks now. 
![Screen Shot 2019-05-28 at 10 34 54 AM](https://user-images.githubusercontent.com/3790067/58491311-612afb00-8134-11e9-84e4-92b5ebdfdac9.png)

**Comment by easherma** [comment]
Mainly concerned with the alignment with the latter example, not the colors
