### ISSUE TITLE
Joplin - Implementation matches design - Service pages under departments

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1945]
We should update the Joplin content editor UX to allow editors to manage what pages are under departments.

We probably need a decent design of how we'd like to handle this, might balloon past an 8.

**Comment by oliver2g** [comment]
@briaguya pls estimate and add a milestone

**Comment by Niicck** [comment]
class ServicePage needs
```
    department = models.ForeignKey(
        'base.DepartmentPage',
        on_delete=models.PROTECT,
        verbose_name='Select a Department',
        blank=True,
        null=True,
    )
```
like in InfromationPage

in base/models.py

**Comment by Niicck** [comment]
Make sure that still works with CreateContentModal

**Comment by Niicck** [comment]
extra credit: make CreateContentModal nicer

**Comment by Niicck** [comment]
Make sure it gets built at URLs in Janis and the links are in the right places

**Comment by Niicck** [comment]
Ask Chase/Tori where service page (links/buttons) should go on a department page in Janis.

**Comment by chasechenevert** [comment]
We list links two ways on service pages (so far). Let me know if this isn't what you need.

**Top services**
Max of 4 services that are marked for listing in the top services block

**Related content**
List of links specific to a department.

Dev spec: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/

<img width="1458" alt="Screen Shot 2019-05-23 at 10 06 45 AM" src="https://user-images.githubusercontent.com/7027270/58264386-64dd0d00-7d43-11e9-865b-2ca4867010e2.png">

**Comment by oliver2g** [comment]
@Niicck or @briaguya what's the estimate on this? also are we aiming to close the issue in this sprint?

**Comment by briaguya** [comment]
@oliver2g I'll put an estimate on it. I think we're waiting on the prod push to worry about it.

**Comment by briaguya** [comment]
Put an 8 on this, looks like there's some design stuff in the mix here so we can probably do some splitting as we make progress on it.

**Comment by chasechenevert** [comment]
Just FYI to the above in terms of design: from what I can see, the "related content" section has already been implemented on the OPO department page https://janis.austintexas.io/en/police-oversight, so unless there shouldn't be anything you'd need to change there.

**Comment by briaguya** [comment]
@chasechenevert my concern is more around the content editor experience. What does it look like for a content editor to manage the related and top links on the page?

It's possible those changes would require some data model changes in Joplin, and maybe some API changes to accommodate those in Janis.

**Comment by desigonz** [comment]
Made #2256 to cover the design of the user flow for assigning a department to a page, and assigned @toribr to that one. This issue focuses on the basic functionality to assign a department to a **service** page.

**Comment by easherma** [comment]
Closing, functionality is implemented, design is covered by future stuff.
