### ISSUE TITLE
Janis: Fix redirects

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/techstack#1949]
I've created this issue in relation to issue #1834 Janis routes redirect regardless of being built in our current version 5.x or version 7.x. I don't have the time to troubleshoot this problem right now, and it does not block master/production from being built.

React-Static 7:

```
$ curl -IL https://dyj1z3uej60oo.cloudfront.net/en/departments
HTTP/2 302
x-amz-error-code: Found
x-amz-error-message: Resource Found
location: /rs7/en/departments/
date: Wed, 15 May 2019 21:13:06 GMT
server: AmazonS3
x-cache: Miss from cloudfront
via: 1.1 b6893337c0deb629a088dde9414834dd.cloudfront.net (CloudFront)
x-amz-cf-id: YtIeRWk3nPA5CJgvW9G6B0-FZQFx7Mtt0ItYxDOgWs37nwIfL07D9A==

HTTP/2 404
content-length: 0
x-amz-error-code: NoSuchKey
x-amz-error-message: The specified key does not exist.
x-amz-error-detail-key: rs7/rs7/en/departments/index.html
date: Wed, 15 May 2019 21:12:58 GMT
server: AmazonS3
age: 9
x-cache: Error from cloudfront
via: 1.1 b6893337c0deb629a088dde9414834dd.cloudfront.net (CloudFront)
x-amz-cf-id: imjgqRtlYzTdUyWQj7DprtFuIYcU1f9TFXiUIqeE0pIM5gl1BqUBLQ==
```

The same happens on react-static 5.x While this is not necessary, it is the only issue blocking us from having versioning through CloudFront and S3. Feel free to take this issue, or to close it.

**Comment by chiaberry** [comment]
We, the devs, no longer know what this is referring to. So it is closed. If it reappears, we will reopen.
