### ISSUE TITLE
Train Joan and Dee Dee to be content coaches

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#195]
Train on:
- [x] Funshops
- [x] Style guide
- [x] Invite them to our work sessions.

**Comment by ashleecoa** [comment]
Content Coach Onboarding doc: https://docs.google.com/document/d/1KkDLSuY53X6v2-2dhwXx5pgoO1Bp-1Rnh8wfPuB1Uzs/edit
