### ISSUE TITLE
Janis - Clicking off the menus closes them but tapping off doesn't

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1954]
Tried it out on my phone and it doesn't close things. Worth investigating.

**Comment by sergiogcx** [comment]
Taking a look, maybe use the `click` event as opposed to `mousedown`:

`document.removeEventListener('mousedown', this.handleClickOutside); `

https://github.com/cityofaustin/janis/blob/9179d6248788ff1aff9b477b4ef172d727db29cb/src/components/PageSections/Header/index.js#L32

https://github.com/cityofaustin/janis/blob/9179d6248788ff1aff9b477b4ef172d727db29cb/src/components/PageSections/Header/index.js#L36
