### ISSUE TITLE
Save title changes on Joplin

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1958]
**Describe the bug**
When I change a title on an information page in Joplin, the change doesn't save. (I was able to save a department page title with no problem.)

**URL**
https://joplin.herokuapp.com/admin/pages/3/

**To Reproduce**

1. Go to the "Content" page on Joplin.
2. Under "Learn how to prevent the flu" page, click "edit."
3. Change title to "Flu prevention."
4. Either "save draft" or "publish."

**Current behavior**
Title change does not save—is still the old title.

**Expected behavior**
Title change saves.

**Screenshots**
![image](https://user-images.githubusercontent.com/5839508/57891226-45545a80-7800-11e9-89c4-8c21a3fd1e54.png)
![image](https://user-images.githubusercontent.com/5839508/57891236-4be2d200-7800-11e9-8ed8-3296cf47e2a3.png)

**Comment by desigonz** [comment]
On service pages, there are two title fields (see #1953); editing the second field updates the first. Information pages only have the first field.

**Comment by briaguya** [comment]
I think the best course of action here is to move the translated titles to the top and then remove (maybe just hide) the non translated title.

Anyone have a problem with this approach?

**Comment by sergiogcx** [comment]
Sounds good, I think it's reasonable to just hide the unused title for now.

**Comment by desigonz** [comment]
Sounds good!
