### ISSUE TITLE
Janis/Joplin - Better translation support in previews

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1959]
Original Title: Open preview in translated language

**Describe the bug**
Preview always opens in English, even when you're editing in a different language.

**URL**
https://joplin.herokuapp.com/admin/pages/3/

**To Reproduce**

1. Select a page to edit in Joplin.
2. Click "es" to edit the Spanish version.
3. Make some edits.
4. Click "preview" and wait for new window to open.

**Current behavior**
Preview opens with the page in English. Back in Joplin, the page reloads back to the English editor.

**Expected behavior**
To see the preview page in Spanish.

**Comment by briaguya** [comment]
When investigating this, I also noticed that using the Language Select Bar within the Janis preview only works once, then the link stops responding.

To consider this fixed, we should:
* Appropriately append language to our preview urls based on the content editor's currently selected language (new feature)
* Make sure the language toggle in the Janis preview works fully (so shared preview links don't act broken)
* For extra credit: In the mobile preview, make sure it always matches the content editor's current selected language
  * If a content editor switches languages, update the preview URL language on the spot
  * If a content editor switches languages in the Janis mobile preview, be aware of it!
    * Not sure what the best UX around this would be, seems like a question for @toribr and @chasechenevert, but for now just hitting a debugger in Chrome when it happens would be a good start to a branch.

**Comment by toribr** [comment]
One thing I want to ask content about  - it always seemed a little funny to me to allow the user to take actions within the preview window. It's a preview window, not a little browser (according to it's use within the author interface). I'm pretty sure there's an issue out there somewhere in which I propose stripping the header (menu and language picker) from the preview UI. In this way the mobile preview would show more content (not the header which the author has seen plenty). I can't think of in what instance an author would want to navigate to where ever using the preview window–but i want to confer with the content team.

**Comment by desigonz** [comment]
@toribr That's interesting and valid; I get your point about not taking actions within the preview window. (Of course, I would want to be able to check that the hyperlinks in the body of a page I just edited are working, etc.) Some thoughts:
- What's standard practice for preview on other authoring interfaces? 
- What would CoA web content managers expect? Would not having the header be jarring/a blocker?

**Comment by toribr** [comment]
Preview in all the other authoring interfaces (that i can think of) happens in a full browser, so I'm not sure that there's anything there we can leverage. But for sure we could test it. It might not be a good idea to remove it simply because it does take up so much room, thus somewhat defeating the purpose of preview. (Which didn't occur to me until just now)

**Comment by desigonz** [comment]
@Niicck looks beautiful! feel free to push to prod.
