### ISSUE TITLE
No translation title field on information page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1960]
**Describe the bug**
There is currently one title field on information pages, unlike other pages, which have two redundant title fields (#1953). Because of this, we can't enter translated titles, nor can I update the title (#1958). 

**URL**
https://joplin.herokuapp.com/admin/pages/33/edit/

**To Reproduce**

1. Go to Joplin and try editing "Prevent measles in Austin"
2. Click "es" to edit in Spanish

**Current behavior**
A field for the Spanish title

**Expected behavior**
No field for the Spanish title

**Screenshots**
![image](https://user-images.githubusercontent.com/5839508/57892863-4ab4a380-7806-11e9-8ce1-c698915f70f4.png)

**Comment by briaguya** [comment]
@desigonz it's there, it's just hiding
<img width="893" alt="Screen Shot 2019-05-16 at 8 48 17 PM" src="https://user-images.githubusercontent.com/6384156/57897761-fa484080-781b-11e9-9fba-bca1f422b6eb.png">
