### ISSUE TITLE
Joplin - Service Page - Add translated descriptions

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1962]
**Describe the bug**
When I updated the "description" field in Spanish on service pages, the Spanish description gets saved in the English version.

**URL**
http://joplin.herokuapp.com/admin/pages/12/edit/

**To Reproduce**

1. Edit a service page
2. Click "es" to switch to Spanish.
3. Paste in a Spanish description. 
4. Publish the page. 
5. Go back to edit the page

**Current behavior**
Spanish description saved in the EN version
![image](https://user-images.githubusercontent.com/5839508/57956754-b7d83f80-78bf-11e9-93af-9aecd2a52f9d.png)

**Expected behavior**
English description in the English version and Spanish description in the Spanish version.

**Comment by briaguya** [comment]
Updated the title of this to represent the issue completely. Should be able to fix this by editing https://github.com/cityofaustin/joplin/blob/master/joplin/base/translation.py
