### ISSUE TITLE
Draft "hire a day laborer" service page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1979]
Draft here: https://docs.google.com/document/d/16siLTqjO5klJpgUt5P4UABnFR2k4ed6NUtyMqkm61Vs/edit?usp=sharing

**Comment by desigonz** [comment]
@kriskristin Same with this one, would be great to have your thoughts. [draft lives here](https://docs.google.com/document/d/16siLTqjO5klJpgUt5P4UABnFR2k4ed6NUtyMqkm61Vs/edit?usp=sharing)

**Comment by desigonz** [comment]
Assigning to @JeffCopy for first review. This is related to #1890.

**Comment by JeffCopy** [comment]
My suggested edits are added, tag you're it.

**Comment by desigonz** [comment]
Assigning to @LauraTrujillo for second review. [draft lives here](https://docs.google.com/document/d/16siLTqjO5klJpgUt5P4UABnFR2k4ed6NUtyMqkm61Vs/edit?usp=sharing)

**Comment by LauraTrujillo** [comment]
Reviewed w/ comments

**Comment by desigonz** [comment]
@LauraTrujillo thanks!
