### ISSUE TITLE
Draft "find work as a day laborer" service page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1980]
Draft lives here: https://docs.google.com/document/d/150w3_ohVmHMt1I_xDSLZos8JdvL3_Y-Pxl5ToKFQrY8/edit?usp=sharing

**Comment by desigonz** [comment]
@kriskristin No rush, but would love to have your eyes on this content! [draft lives here](https://docs.google.com/document/d/150w3_ohVmHMt1I_xDSLZos8JdvL3_Y-Pxl5ToKFQrY8/edit?usp=sharing)

**Comment by desigonz** [comment]
Assigning to @JeffCopy for first review

**Comment by JeffCopy** [comment]
My suggested edits are there, it's ready to roll.

**Comment by desigonz** [comment]
Thanks @JeffCopy! Onto @LauraTrujillo for second review.
