### ISSUE TITLE
Revise Service Page 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1982]

**Comment by annieszot** [comment]
For https://docs.google.com/document/d/15eMRnayTCVNS4qr3_MUVhK9nMJhS79C7cQMkLAD4O1A/edit

- [ ] Editors assigned (round 1)
- [ ] Feedback received, incorporated
- [ ] Editors assigned final round

**Comment by annieszot** [comment]
Requesting @srigdon to review garden permit service page by Friday, May 31.

**Comment by annieszot** [comment]
@JeffCopy Are you able to revise this service page by end of the day tomorrow *(Tuesday, June 4)? Thank you! 
https://docs.google.com/document/d/15eMRnayTCVNS4qr3_MUVhK9nMJhS79C7cQMkLAD4O1A/edit

**Comment by JeffCopy** [comment]
affirmative!

**Comment by annieszot** [comment]
Excellent! Thanks and much appreciated!

**Comment by JeffCopy** [comment]
Just a couple of suggestions/questions; this is a lot of information beautifully boiled down. Back to you!

**Comment by annieszot** [comment]
Adding @LauraTrujillo for 2nd round review. Requesting edits by end of the day Monday, June 10. https://docs.google.com/document/d/15eMRnayTCVNS4qr3_MUVhK9nMJhS79C7cQMkLAD4O1A/edit?ts=5cf57db8

**Comment by LauraTrujillo** [comment]
@annieszot looks good! It may help to use a step w/ options format in Joplin. Especially with steps 2, 3, and 6.

**Comment by annieszot** [comment]
Excellent! I'll ask more about step w/ options format in Joplin tomorrow :) Closing
