### ISSUE TITLE
Revise Information Page

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1988]

**Comment by annieszot** [comment]
For https://docs.google.com/document/d/1FX_1-WOWyWltL4twhSg6q2tZmabR0cNuds5xIc48m8Q/edit#
- [ ] Editors assigned (round 1)
- [ ] Feedback received, incorporated
- [ ] Editors assigned final round

**Comment by annieszot** [comment]
Requesting @srigdon to provide feedback by Friday, May 31.

**Comment by annieszot** [comment]
@JeffCopy Are you able to edit this information page by end of the day tomorrow (Tuesday, June 4)? Thank you! 
https://docs.google.com/document/d/1FX_1-WOWyWltL4twhSg6q2tZmabR0cNuds5xIc48m8Q/edit#

**Comment by JeffCopy** [comment]
Yep, I shall!

**Comment by annieszot** [comment]
Thanks so much @JeffCopy !

**Comment by JeffCopy** [comment]
Back to you with my suggestions; onward!

**Comment by annieszot** [comment]
Thanks so much, Jeff! Your edits really polished the copy. Much appreciated. 
Adding @LauraTrujillo for 2nd round review. Requesting edits by end of the day Monday, June 10. 
https://docs.google.com/document/d/1FX_1-WOWyWltL4twhSg6q2tZmabR0cNuds5xIc48m8Q/edit#

**Comment by JeffCopy** [comment]
De nada!

**Comment by LauraTrujillo** [comment]
Reviewed with comments!

**Comment by annieszot** [comment]
Wonderful! Closing :)
