### ISSUE TITLE
Revise pard dept page

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1995]

**Comment by annieszot** [comment]
For https://docs.google.com/document/d/1l1cn8-DnTju7oK4hOM_10cNe0dE9eEH30Lf_xDNAdpU/edit
- [ ] Editors assigned (round 1)
- [ ] Feedback received, incorporated
- [ ] Editors assigned final round

**Comment by annieszot** [comment]
Assigning/requesting edits from @srigdon by end of day Thursday, June 6
https://docs.google.com/document/d/1l1cn8-DnTju7oK4hOM_10cNe0dE9eEH30Lf_xDNAdpU/edit

**Comment by annieszot** [comment]
Moving milestone to sprint 33

**Comment by srigdon** [comment]
Edits made in line, see comments.

**Comment by annieszot** [comment]
Thank you @srigdon ! @LauraTrujillo ready for your final review :) Requesting edits by Wednesday, June 26, There are gaps in the information I'll gather when meeting with PARD during the "approval" phase in our editorial process.

**Comment by LauraTrujillo** [comment]
@annieszot looks great! Left some comments

**Comment by annieszot** [comment]
Awesome! Closing
