### ISSUE TITLE
Parks and Rec department page 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1999]
draft started
https://docs.google.com/document/d/1l1cn8-DnTju7oK4hOM_10cNe0dE9eEH30Lf_xDNAdpU/edit

**Comment by desigonz** [comment]
This page is pretty good to go, will need a quick review before sending off for approval with Community Gardens guide.

**Comment by sammodabber** [comment]
Have a meeting with web SPOC and Cindy next week

**Comment by gabrielaperezdelaosa** [comment]
not getting a response from SPOC
hoping to get a better picture
otherwise drafted
