### ISSUE TITLE
Revise interest form

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2001]

**Comment by annieszot** [comment]
For https://docs.google.com/document/d/1W1wZFz-9ok8_3Wd2d0SoYyU9r2Pth8HoWqhEOhy_hZM/edit

- [ ] Editors assigned (round 1)
- [ ] Feedback received, incorporated
- [ ] Editors assigned final round

**Comment by desigonz** [comment]
@annieszot This might be easier to review in context of the guide—can you point me to relevant drafts?

**Comment by annieszot** [comment]
Sure thing @desigonz! Here's the guide draft https://docs.google.com/document/d/1xeOpvSl8FS9uWifSzjuRh9TnBt0hg7o2vysFDkVm20E/edit#heading=h.f1e7qdicvq5o

Requesting feedback by Friday, May 31. Also thanks for your patience as this editorial process is ironed out!

**Comment by desigonz** [comment]
@annieszot I did a quick pass—I had a few questions and recommendations for where to add more language.

**Comment by annieszot** [comment]
Thanks so much @desigonz! Very helpful comments and recommendations. Draft is updated and assigned to @LauraTrujillo. @LauraTrujillo, requesting edits by end of the day Tuesday, June 4. 

-I also welcome your feedback on parsing out/asking questions on "how" the proposed functionality. Will love your guidance on how to best work with design/dev to produce the functionality. Also welcome edits on overall content. 

Here's the draft again: https://docs.google.com/document/d/1W1wZFz-9ok8_3Wd2d0SoYyU9r2Pth8HoWqhEOhy_hZM/edit

And the user story: #2070 , #2071 and #2072 *content on acceptance criteria to be edited once this content is finalized/approved by PARD.

**Comment by LauraTrujillo** [comment]
Reviewed and left some comments!

**Comment by annieszot** [comment]
Assessed/accepted comments. Resolved questions. Closing.
