### ISSUE TITLE
Community Garden Interest Form 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2007]
See #2070 for additional context.

-----

1 of 3 design options for residents who want to start a community garden reach the website on the community gardens information page or community garden guide and click the link "Start the conversation"

### As a prospective gardener, I want to sign up for a community garden so that I can get information for what the process is.

Building a sign-up form (feature) that sends an automatic email upon submission will decrease the amount of time to express interest in building a community garden and inform the resident of what the process entails. 

The goal is to increase efficiency for the resident (prospective gardener) and documentation (for supportive city staff) 

Alternative solutions considered include a pop-up "Sign-up for a community garden" #2071 where users share their email address or phone number (for texts) (user story issue # ) or link directly to the guide Epic #2028  

Acceptance criteria
Content draft https://docs.google.com/document/d/1W1wZFz-9ok8_3Wd2d0SoYyU9r2Pth8HoWqhEOhy_hZM/edit
1. Form is one page (scroll) and toggles translations fluidly
2. Open fields capture correct information for: 

Name:

Phone number: (required)

Email: (required) 

Neighborhood: (optional)  

Location of potential community garden (map pin drop) 

Have you reviewed the “How to get a garden permit for your community garden” guide? 
-Yes
-No 

If yes, then great! You’re steps closer to starting a community garden.
If no, please take a look at the guide.

How ready are you to start a community garden? [radio buttons]
-I’m curious and want to learn more about the process
-I’m almost ready. I have my steering committee, but I need to find a sponsor. 
-I’m ready and have a steering committee, a sponsor, and money for the garden. I just need help submitting the community garden permit application and next steps.

Submit (button) 

Confirmation page after submission with a confirmation number 

9. Automatic email
Copy of answers submitted in interest form 
Link to the guide
Link to the service page "Get a community garden permit" 
Condensed outline of building a community garden process. 

Definition of Done
Form edited according to changes needed during user testing
Form QA bugs fixed and form passes regression testing 

-------

Deliverable in Community Garden project scope doc 
https://docs.google.com/document/d/1NVNrS0FIfef1G5dxM8-u7Bvs7F_j3S5gQJjkcavpmWI/edit#

-form - involve all teams? 
Live on Community Gardens information page 
-process for development tbd

**Comment by gabrielaperezdelaosa** [comment]
https://cityofaustin.formstack.com/forms/community_garden_interest_form
