### ISSUE TITLE
Typesetting: Remove rule line between headings and body copy, change H2 color 

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#2008]
## Visual design changes
- [x] Remove blue rule line between headings and body copy
- [x] Change the H2 color from blue to `#212121`

**Rationale**
- So far the relationship between a section's heading and body copy are very clear, so there's no need to try to reinforce this. 
- I've got to reduce the reliance on this primary blue and reserve it only for links and other important actions/information.

### USWDS 2.0 typesetting resources
- [Using type
](https://v2.designsystem.digital.gov/design-tokens/typesetting/overview/)
- [Typesetting example](https://v2.designsystem.digital.gov/components/typography/#prose)

### Current
![Screen Shot 2019-05-20 at 12 16 52 PM](https://user-images.githubusercontent.com/7027270/58039877-9d89a600-7af9-11e9-81dc-ccbed23e6051.png)

### With change
![Screen Shot 2019-05-20 at 12 20 45 PM](https://user-images.githubusercontent.com/7027270/58040030-08d37800-7afa-11e9-8d19-7a1ab4e5e077.png)

**Comment by chasechenevert** [comment]
Duplicate of #2011.

**Comment by sergiogcx** [comment]
This is addressed in issue 418

Demo:
https://janis-pr.austintexas.io/418

Code:
https://github.com/cityofaustin/janis/pull/418

**Comment by sergiogcx** [comment]
Tested on IE11:

![Screen Shot 2019-05-24 at 5.54.55 AM.jpg](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/8a48d021-a404-40d0-890c-e6273be352f5)
