### ISSUE TITLE
Specify build args during deployment

### ISSUE THREAD

**Issue by benweatherman** [cityofaustin/techstack#201]
Currently we use build args when building the static version of the site because the HTML is generated during the docker build phase (environment variables are using during the docker run phase).

https://github.com/cityofaustin/janis/blob/7b1e46ddad8a58fc749ada43f4d804e719980d83/scripts/build.sh#L12-L15

Unfortunately, there's no way to have heroku pass those commandline args. We only have the ability to set environment variables.

We need to figure out how to set build-time variables in heroku.

**Comment by easherma** [comment]
@Niicck is this still relevant given the changes being made to the build process?
