### ISSUE TITLE
Official site banner: remove icon, center text and plus icon

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#2013]
## Visual design change
- [x] Remove capitol icon. It's too small to be intelligible 
- [x] Center text and plus icon
- [x] Insure that the entire banner is clickable (not just the plus icon)

### Resources
- Janis 2 dev spec: [Official site banner mock](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/ef38d15b-e291-4af7-b88b-5a947cf60c56/Banner-Global-Official/)

### Current

![Screen Shot 2019-05-20 at 12 04 09 PM](https://user-images.githubusercontent.com/7027270/58039239-c90b9100-7af7-11e9-9b58-dddfef43ee8d.png)

### With changes

![Screen Shot 2019-05-20 at 12 05 56 PM](https://user-images.githubusercontent.com/7027270/58039249-d0329f00-7af7-11e9-8057-031b1c382dae.png)

**Comment by sergiogcx** [comment]
Hi @chasechenevert question for you as far as the width of the menu.

In the specs it looks like you are going by a max width of 1440, while working on this I initially set it up to 1080 as the smaller menu below as shown in the image:

![Fullscreen_5_23_19__12_24_PM.jpg](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/b5eb8578-50c7-4999-8a1f-4cc7062b7b76)

I am working on getting the PR ready for you

**Comment by sergiogcx** [comment]
This is the PR:

https://janis-pr.austintexas.io/417/

**Comment by chasechenevert** [comment]
That looks right to me!

**Comment by sergiogcx** [comment]
After speaking with Chase the width was changed to 1160px, good testing will be needed in order to ensure the menu behaves as expected in every device.

**Comment by sergiogcx** [comment]
Tested on IE11:

![Screen Shot 2019-05-24 at 5.51.00 AM.jpg](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/355a0d01-d2e2-4df4-b27d-0bf19c6ecdcb)

![Screen_Shot_2019-05-24_at_3_26_37_AM.jpg](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/ab6126b7-da17-4615-9d4d-48f56b10b20d)
