### ISSUE TITLE
Joplin - PR apps can't find the correct CSS

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#2066]
If we make changes to the CSS in Joplin, when we make a PR app it fails to find the bundle with the updated styles.

This might also be a problem with our JS, but I haven't tested it out yet.

**Comment by sergiogcx** [comment]
Yea, something’s messed up. I think it has something to do with where the CSS files get uploaded when they get built

I suspect they might get overwritten or outright deleted.
