### ISSUE TITLE
Get approval for English content

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2069]
Per Desi's Joplin MVP translation spreadsheet: https://docs.google.com/spreadsheets/d/1HnKT-FnLAeLc9YT__pUAk2UdMEI1opwfPuzVFxct8NI/edit#gid=0

*APH*
- [ ] Get immunizations for you and your family
- [ ] Crypto and other waterborne diseases
- [ ] Flu prevention

*General*
- [ ] Privacy policy for Alpha.Austin.gov

**Comment by desigonz** [comment]
Will be batching APH pages in with [#2186](https://github.com/cityofaustin/techstack/issues/2186).
