### ISSUE TITLE
Community garden permit payment 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2075]
### As a resident completing my application for a community garden permit and the community garden building process, I want to pay my garden application fee ($50) and license agreement fee ($100) online so that the process is streamlined.

Building a payment feature will provide quick, convenient, and faster processing ways to pay application fees while improving cash flow for city departments requiring those payments. 

Inviting discussion/consultation when deciding what kind of payment feature to design/develop:
-Payment gateway 
-Payment processor
-Payment provider
-Payment service or payment system
-Merchant account 
Source Reference: https://www.wildapricot.com/articles/online-payment-services

No alternatives considered yet for streamlining application fees and payments. 

-------

Relates to deliverable in community garden scope https://docs.google.com/document/d/1NVNrS0FIfef1G5dxM8-u7Bvs7F_j3S5gQJjkcavpmWI/edit# and other pertinent projects in SDL-->alpha.austin.gov.

**Comment by srigdon** [comment]
Payments will likely be handled once this is transitioned.
