### ISSUE TITLE
User story- community garden event content type 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2079]
As a content creator for the Parks Department, I want to publish community garden wellness events and training events so that residents are aware of community building opportunities.

Building an event content type in Joplin will increase awareness of affordable education opportunities for Austin residents while highlighting service access entry points. 

Ideally, event types will include date, location, time, how to get to the event, if childcare is provided (educational courses and trainings), contact information/rsvp, if food is provided and options to specify dietary restrictions. (Teams will sync to decide on these requirements). 

No alternative solutions considered yet. 

Acceptance criteria
To be determined 

Definition of Done
To be determined

**Comment by desigonz** [comment]
Closing this, will be looped into #2077
