### ISSUE TITLE
Can't select topic collection when making a topic page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2080]
**Describe the bug**
When I was creating a new topic page, I wasn't able to select a topic collection page to associate it with via the explorer.

**URL**
https://joplin.herokuapp.com/admin/pages/66/edit/#56

**To Reproduce**

1. Go to https://joplin.herokuapp.com/admin/pages/66/edit/#56
2. Scroll down to 'TOPIC COLLECTIONS THIS PAGE BELONGS TO'
3. Click "+ ADD TOPIC COLLECTIONS THIS PAGE BELONGS TO"
4. Click "Select a Topic Collection"
5. Modal explorer will appear. Select a topic.

**Current behavior**
Nothing happens. If you close the modal, the topic page editing UI doesn't indicate that anything has been selected.

**Expected behavior**
Some sort of indication that a page was selected—maybe select a page and "save," or modal closes and the topic page editing UI indicates the page you just selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/5839508/58210825-f8fd9480-7caf-11e9-87e7-58f574d3bc17.png)

![image](https://user-images.githubusercontent.com/5839508/58210814-f438e080-7caf-11e9-8e92-99e3a22cb907.png)

**Browser**
Chrome 73 on macOS (Mojave)

**Additional context**

**Comment by briaguya** [comment]
@desigonz I'm having trouble reproducing this. Could you try again when you get a chance?

**Comment by toribr** [comment]
Added myself so I can track this issue, along with working on this flow.

**Comment by desigonz** [comment]
@briaguya It's working for me now! 🎉

**Comment by desigonz** [comment]
@briaguya Ok to close this issue? Or @toribr do you want to repurpose/rewrite for UX needs?

**Comment by toribr** [comment]
Ok to close.
