### ISSUE TITLE
Background image on home page doesn't appear in IE11

### ISSUE THREAD

**Issue by oliver2g** [cityofaustin/techstack#2082]
The image of lady bird lake doesn't display on the home page (janis.austintexas.io)

**URL tested:** https://janis.austintexas.io/

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fjanis.austintexas.io%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://janis.austintexas.io/) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1440x788 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/17e29b7f155f509d863efb198d11c1245b2bc40e/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/17e29b7f155f509d863efb198d11c1245b2bc40e/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fjanis.austintexas.io%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://janis.austintexas.io/) to reproduce the issue on Browserstack**

**Comment by sergiogcx** [comment]
It looks like the url is missing the DOT in `.jpg`, AWS can't find the file so it returns a 403

![Screen Shot 2019-05-23 at 1.57.12 PM.jpg](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/4521e6ee-4900-4284-9162-6e474a70321b)


![Screen Shot 2019-05-23 at 1.56.52 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/ec5a147d-0889-4a14-a97e-03ca9b909607)

**Comment by sergiogcx** [comment]
It looks like the dot is missing in one of the links

![Screen_Shot_2019-05-23_at_2_05_45_PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/e85d063e-45ce-42cd-8e04-99d442b8862e)

**Comment by sergiogcx** [comment]
Brian beat me to fixing the issue:

https://github.com/cityofaustin/janis/pull/419/files

**Comment by briaguya** [comment]
But of course, IE11 doesn't support `object-fit: cover`

<img width="1544" alt="Screen Shot 2019-05-23 at 2 18 34 PM" src="https://user-images.githubusercontent.com/6384156/58280211-b1d1db00-7d65-11e9-8b9e-d59171a002d4.png">
