### ISSUE TITLE
alpha.austin.gov link in footer doesn't work

### ISSUE THREAD

**Issue by oliver2g** [cityofaustin/techstack#2085]
When I click on the link, nothing happens.

**URL tested:** https://projects.austintexas.io/projects/austin-digital-services-discovery/about/what-we-are-doing/

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fprojects.austintexas.io%2Fprojects%2Faustin-digital-services-discovery%2Fabout%2Fwhat-we-are-doing%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://projects.austintexas.io/projects/austin-digital-services-discovery/about/what-we-are-doing/) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1440x788 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/e77aead75589a6e32e12d38e0759f6ff40577763/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/e77aead75589a6e32e12d38e0759f6ff40577763/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fprojects.austintexas.io%2Fprojects%2Faustin-digital-services-discovery%2Fabout%2Fwhat-we-are-doing%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://projects.austintexas.io/projects/austin-digital-services-discovery/about/what-we-are-doing/) to reproduce the issue on Browserstack**

**Comment by briaguya** [comment]
@oliver2g I think it's working as intended, on staging it goes to the staging URL and on prod it goes to the prod URL.

If you click it from another page it should just bring you to the homepage, does that happen?

**Comment by oliver2g** [comment]
Just looked at it again in light of your comment. Makes sense. Closing.
