### ISSUE TITLE
Sync on content releases 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2086]
Goal from "content goals for this sprint (31)" at content pin-up 5.21.19
https://docs.google.com/document/d/1PDDhXEXuowUeKZximIjR1ZZL26jZK1RzKLt4g0hn16M/edit

@annieszot and @desigonz to sync 
- [x] Look at roadmap and decide (big buckets) what content to release and when
- [ ] Identify workflows and tools we need to efficiently push out content
- [ ] What to call content releases
- [ ] Create content releases in Github

Meeting scheduled for Wednesday, May 29. 
Roadmap https://docs.google.com/spreadsheets/d/1ytu5-cCd7hXrq6cMOwiPvgSYKPPmcnoEUTd99ZuD67U/edit#gid=1709744959

**Comment by desigonz** [comment]
@annieszot Adding "Identify workflows and tools we need to efficiently push out content" based on a short convo Marni and I had today. I think you alluded to something similar. Looking forward to tomorrow!

**Comment by annieszot** [comment]
Desi and I synced on May 29. 
Will make a new issue on determining content releases 2.0 
Big takeways from sync: determine MVP workflow, add to workflow doc, finish defining content debt, create gantt or another timeline to bring to sprint planning tomorrow.
