### ISSUE TITLE
overlapping text on topic collection tiles (IE11)

### ISSUE THREAD

**Issue by oliver2g** [cityofaustin/techstack#2087]
The "Learn More" links and Topic Page tiles are all overlapping on the Topic Collection page.

**URL tested:** https://janis.austintexas.io/en/housing-utilities/recycling-trash-and-compost/

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fjanis.austintexas.io%2Fen%2Fhousing-utilities%2Frecycling-trash-and-compost%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://janis.austintexas.io/en/housing-utilities/recycling-trash-and-compost/) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1440x788 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/599840f70e2275c58b98bb4bd01022f5d2a71bab/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/599840f70e2275c58b98bb4bd01022f5d2a71bab/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fjanis.austintexas.io%2Fen%2Fhousing-utilities%2Frecycling-trash-and-compost%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://janis.austintexas.io/en/housing-utilities/recycling-trash-and-compost/) to reproduce the issue on Browserstack**

**Comment by briaguya** [comment]
@oliver2g in my testing this is now working on https://janis.austintexas.io/en/housing-utilities/recycling-trash-and-compost/

Any chance you'd like to confirm so we can close this out?

**Comment by oliver2g** [comment]
Looks good now
