### ISSUE TITLE
Joplin - Listing page shows notes when there aren't any

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#2090]
It appears as though sometimes blank notes are showing up as `<p></p>` instead of a pure blank string.

I have no idea how to reproduce this. There must be something about @desigonz 's environment that's making it happen.

Anyways, a blank p block should still count as no notes. We need to fix this.

**Comment by sergiogcx** [comment]
Hmm, I wonder if this is something we could use in react:

https://developer.mozilla.org/en-US/docs/Web/API/DOMParser

```
function cleanNoteString(htmlCode){
   var domObject = new DOMParser().parseFromString(htmlCode, 'text/html');
   return domObject.body.textContent.trim() || "";
}
```

I haven't tested, but I put the `.trim()` there and if it works it would take care of double spaces, single space, anything like that, or if null then return an empty string. The function itself should return the text only and not the html tags.

**Comment by briaguya** [comment]
@sergiogcx only issue is we're doing this part in python:
https://github.com/cityofaustin/joplin/blob/78142e66b34538688c1c5c017498808108d0a873/joplin/base/wagtail_hooks.py#L75

**Comment by briaguya** [comment]
fixed by https://github.com/cityofaustin/joplin/pull/244
