### ISSUE TITLE
Joplin: Don't trigger builds on new article

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/techstack#2091]
When creating a new article, Joplin triggers an un-publish event. 

Ideally we should not see any actions taken by the builder, so we need to find a way to avoid these unnecessary builds.

**Comment by briaguya** [comment]
if we do a bit of digging here: https://github.com/cityofaustin/joplin/blob/34fdd3a677d8d350696900e2c700a89419c44dd5/joplin/base/views/joplin_views.py#L78

we might be able to get it to just save a draft and not go live with it.

**Comment by sergiogcx** [comment]
Unassigned myself, I don't have the bandwidth. Maybe a good exercise for anyone interested in learning how the builds currently happen.

Regardless of whether we stay with our current idea of docker containers building on-demand, or if you want to use CircleCI or even Netlify, someone will need to address this issue.
