### ISSUE TITLE
Revision history author

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2094]
### As a content editor I want to see an author associated with a revision in the revision history, so that I am able to identify the person I should go to if I have a content question.

**Is your feature request related to a problem? Please describe.**
Authors associated with the revision history. I saw a change was made on a page and I wanted to know who made the change so I could ask them about that edit.

**Describe the solution you'd like**
Could list author at the list-view of the revision history as well as in the diff view
![image](https://user-images.githubusercontent.com/5839508/58271928-e1c3b300-7d52-11e9-897b-e697a8dac22a.png)
![image](https://user-images.githubusercontent.com/5839508/58271969-f99b3700-7d52-11e9-985d-b32a85cafb48.png)

**Comment by toribr** [comment]
In order for any design solution to be effective, then everyone that is using the admin log-in for Joplin should be kicked off and given their own email/pass.

**Comment by toribr** [comment]
![2094](https://user-images.githubusercontent.com/3790067/58566289-f641f880-81f5-11e9-8dca-ab511e07e619.png)

Each revision should have the first and last name of the person who last revised.

**Comment by easherma** [comment]
![revise](https://user-images.githubusercontent.com/10539855/58669063-95ebad80-8300-11e9-9888-5a74a7cf0dcd.png)

@toribr this is ready to go, but I wanted to run this by you:
do you see any value in listing the original author of the draft as well as the author of the last revision?

**Comment by toribr** [comment]
I'm not aware of any need for that functionality at this time.

**Comment by easherma** [comment]
I want to confirm because the user story @desigonz wrote talks about the author of the revision and the comp has the person who last edited that revision. Since those can easily be two different people it could get confusing.

**Comment by desigonz** [comment]
To me, the person who authored a revision = the person who edited the page. 

It's pretty easy to see who is the original author of the page—you can see that in the [listing page](https://joplin.herokuapp.com/admin/pages/3/), and once we have this implemented, you can scroll down to the bottom and see who made the very first save.

Maybe a clearer user story would be:
As a content editor I want to see **who made each revision on the revision history page**, so that I am able to identify the person I should go to if I have a content question.
