### ISSUE TITLE
Saving on Joplin when I haven't made changes

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2099]
**Describe the bug**
Joplin allows me to save a draft when I haven't changed anything. If I do that to a page that's live, then what happens is that, if I go back to the listing of pages, it's status is "live + draft"—even though the live version is exactly the same as the draft. This leads to confusion about whether the page is actually up-to-date.

Relatedly, if I open a page to edit but don't make a change, and then a click the nav to go somewhere else, I get the "Changes you made may not be saved" modal.

**URL**
Joplin 

**To Reproduce**

1. Go to edit a live page, for example https://joplin.herokuapp.com/admin/pages/11/edit/
2. Don't edit anything, but instead click "Save draft"
3. Go back to the [content list view page](https://joplin.herokuapp.com/admin/pages/3/)

**Current behavior**
The page you just edited is now listed as "live + draft," not just "live"

**Expected behavior**
The page just says "live." Or maybe, on the edit page, I shouldn't be able to "save draft" until I've made a change. Not totally sure.

**Browser**
Chrome 73 on macOS (Mojave)

![image](https://user-images.githubusercontent.com/5839508/58281733-72a58900-7d69-11e9-8564-058868004a01.png)

**Comment by toribr** [comment]
I think this comes down to user roles, as well as a change needed in functionality. In the case of a published page for the "publisher" role, that user should only get an "update" button which publishes the updates.

In the case of an author without publishing permissions, then that user would get the "save draft" button. In the case where no changes were made to the page: if the user clicks to the list view and no changes were made, then no draft is saved. If the user clicks save draft to exit (and this is likely) then if no changes were made then the system should not create a draft state. If changes were made, then the draft state is saved and the status is "draft + live"

**Comment by desigonz** [comment]
Created #2285, #2286, and #2287 to address this issue, based on our conversation today. Closing this one for now.
