### ISSUE TITLE
Author note icon

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2100]
**Describe the bug**
Related to #1932. Clicking author note icon in Joplin makes the page jump to the top.

**URL**
https://joplin.herokuapp.com/admin/pages/3/#

**To Reproduce**
1. Go to https://joplin.herokuapp.com/admin/pages/3/#
2. Scroll down to a page under the fold that has the author notes icon next to it
3. Click the icon

**Current behavior**
Page jumps back to the top.

**Expected behavior**
I guess I expected to go straight to the author notes, or not be able to interact with the icon at all

**Device**

**Browser**
Chrome 73 on macOS (Mojave)

**Comment by briaguya** [comment]
I went ahead and changed it to be less confusing but still very obviously placeholder:
![Screen Shot 2019-05-23 at 6.30.09 PM.png](https://images.zenhubusercontent.com/5afb42ab4b5806bc2bd34c32/c3f6085c-3123-4f20-a5a4-97f3fc67cdb9)

We have this issue: https://github.com/cityofaustin/techstack/issues/2065 which I think is a good place for more ideas about notes.
