### ISSUE TITLE
Draft hepatitis page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2102]
http://www.austintexas.gov/department/hepatitis-0 and http://www.austintexas.gov/department/hepatitis

**Comment by LauraTrujillo** [comment]
@JeffCopy can you please work your magic/review this page?

**Comment by JeffCopy** [comment]
My suggested edits are in the doc; onward!

**Comment by LauraTrujillo** [comment]
@annieszot can you review, please? Would be great to have edits by the end of the week- Friday, June 21st. Thank you!

**Comment by annieszot** [comment]
Of course @LauraTrujillo ! I'm on it!

**Comment by LauraTrujillo** [comment]
Thanks, @annieszot!
