### ISSUE TITLE
Refine Follow Universal Recycling Ordinance

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2106]
Google: https://docs.google.com/document/d/18GzFa1tBEZhKft5RffpoKez7KggICPBhIjE3cFuB2qE/edit

Austintexas.gov link: http://austintexas.gov/uro

- Should it stay a service page?
- Add it to template

**Comment by LauraTrujillo** [comment]
Moving this to follow ARR's Funshop on 7/3

**Comment by LauraTrujillo** [comment]
Meeting with Chase from ARR to white board this content.

**Comment by LauraTrujillo** [comment]
@annieszot and I met with Kerri G., Katie, and Chase Norris today to discuss URO content. They have an internal deadline and we advised them on how to make current content more user-friendly. Moving this to backlog since we won't need to draft content until after drupal 8 launch.

**Comment by annieszot** [comment]
@LauraTrujillo Sent follow-up email 8.5.19. Okay to turn this issue into an epic and close? 
Epic will include 
- Universal recycling ordinance information page 
-1 form that combines/braids recycling and organics diversion plan
- Service page - "Do I meet requirements for the universal recycling ordinance?"

**Comment by annieszot** [comment]
Closing -> turned into new epic #2685
