### ISSUE TITLE
Draft a communications plan for Joplin

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#2113]
As we continue working on Joplin with a small group of content creators at the City, we should draft a plan for how and when we'll communicate about it. 

Draft: https://docs.google.com/document/d/1x4M_QO0OE-KUk9x1F8KyZyo-djZF08oUAiw_sijiBlk/edit#

**Comment by annieszot** [comment]
@srigdon Want to add this to Sprint planning tomorrow? Probably be good to get started since it's JUNE starting Saturday. Cray
