### ISSUE TITLE
Chicken keeping content 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2138]

**Comment by annieszot** [comment]
Per #2244 
For potential chicken keeping form and chicken keeping rebate application 
Original form links: http://www.austintexas.gov/online-form/chicken-keeping-application; http://www.austintexas.gov/sites/default/files/files/Trash_and_Recycling/chicken-keeping-rebate-FINAL.pdf
How a scale of 1-3 (1 being the easiest and 3 being the most complex), how complex would this form be to implement? **1**

On a scale of 1-3 (1 being the least and 3 being the most), what kind of impact will this form have?
Based on page views (~1550) **1**

**Comment by desigonz** [comment]
Covered in #2496
