### ISSUE TITLE
Alpha Production and Staging Environments

### ISSUE THREAD

**Issue by benweatherman** [cityofaustin/techstack#215]
Currently we automatically deploy to alpha.austin.gov when code is merged into cityofaustin/janis master branch. We should be more deliberate before updating alpha.

- [x] deploy joplin (the production heroku app)
- [x] add new janis project (`austindotgov` in heroku), hook up to GitHub, deploy
- add/change DNS entries
    - [x] alpha.austin.gov => alpha.austin.gov.herokudns.com
    - [x] staging.austin.gov => jstaging.austin.gov.herokudns.com

There are a few weird things going on here that would be nice to address:
1. **Heroku Build**
    1. **Don't rebuild at each stage** Normally a Docker workflow would have us build once and then move the built image to additional stages. This ensures that what we're seeing in staging is what we'll get in production. Heroku doesn't support this and requires a rebuild for each stage.
    2. **Build-time variables per stage** It would be nice to set different CMS URLs for review apps, for times when we want to test changing the CMS and the frontend at the same time. This would allow us to use a CMS review app URL to build the frontend without having to change code. Heroku doesn't support this.
2. **DNS** Currently we have to ping another team to change DNS entries. They have to update a zone file and redeploy. That group often has a lot going on, so would be nice to relieve them of this burden. Can we own the DNS records?
3. **Images** Eventually we'll want to put static assets on a CDN. In the meantime, we're serving images from joplin. This stinks because we have to keep joplin up and running, even though we're serving static content from janis. If we distribute the images with janis, we can remove the need to keep joplin running & scaled.

**Comment by ifsimicoded** [comment]
This will also assist us in dev's QA process with content and design teams.

**Comment by benweatherman** [comment]
Submitted a ticket to get the DNS changed

> Thank you for contacting the Service Desk.
> Service Desk Ticket # 1828096 has been opened for your request.
> 
> Open Date: 4/9/2018 3:50:42 PM
> 
> Problem Description: NAME                    TYPE   VALUE
> --------------------------------------------------
> alpha.austin.gov.       CNAME  austindotgov.herokuapp.com.
> staging.austin.gov.     CNAME  janis-staging.herokuapp.com.
> 
> Thanks in advance for making these changes!
> 
> 
> If you need to call for status on this request or to add additional information, please contact the appropriate Service Desk and refer to ticket # 1828096.

**Comment by benweatherman** [comment]
Whoops, looks like I used the wrong DNS names for Heroku. Gonna submit a new help desk ticket to update those entries.

**Comment by benweatherman** [comment]
```
$ dig staging.austin.gov

; <<>> DiG 9.9.7-P3 <<>> staging.austin.gov
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11983
;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;staging.austin.gov.		IN	A

;; ANSWER SECTION:
staging.austin.gov.	19336	IN	CNAME	staging.austin.gov.herokudns.com.
staging.austin.gov.herokudns.com. 59 IN	A	50.16.227.190
staging.austin.gov.herokudns.com. 59 IN	A	50.19.121.155
staging.austin.gov.herokudns.com. 59 IN	A	50.16.237.173
staging.austin.gov.herokudns.com. 59 IN	A	54.225.179.161
staging.austin.gov.herokudns.com. 59 IN	A	23.21.92.233
staging.austin.gov.herokudns.com. 59 IN	A	54.221.212.171
staging.austin.gov.herokudns.com. 59 IN	A	54.225.154.108
staging.austin.gov.herokudns.com. 59 IN	A	23.21.213.192

;; Query time: 47 msec
;; SERVER: 192.168.175.1#53(192.168.175.1)
;; WHEN: Mon Apr 23 10:49:11 CDT 2018
;; MSG SIZE  rcvd: 221
```

```
$ dig alpha.austin.gov

; <<>> DiG 9.9.7-P3 <<>> alpha.austin.gov
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7777
;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;alpha.austin.gov.		IN	A

;; ANSWER SECTION:
alpha.austin.gov.	21599	IN	CNAME	alpha.austin.gov.herokudns.com.
alpha.austin.gov.herokudns.com.	59 IN	A	54.225.179.161
alpha.austin.gov.herokudns.com.	59 IN	A	54.235.157.232
alpha.austin.gov.herokudns.com.	59 IN	A	54.243.149.76
alpha.austin.gov.herokudns.com.	59 IN	A	54.225.154.108
alpha.austin.gov.herokudns.com.	59 IN	A	54.225.185.38
alpha.austin.gov.herokudns.com.	59 IN	A	54.225.64.197
alpha.austin.gov.herokudns.com.	59 IN	A	54.221.212.171
alpha.austin.gov.herokudns.com.	59 IN	A	54.243.154.12

;; Query time: 73 msec
;; SERVER: 192.168.175.1#53(192.168.175.1)
;; WHEN: Mon Apr 23 10:49:16 CDT 2018
;; MSG SIZE  rcvd: 217
```
