### ISSUE TITLE
Revise soil kitchen information page

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2153]
Draft https://docs.google.com/document/d/16HS-toTwr9Y_IIkdy-O4Bhnrhw112wBcokz_DDhQvqM/edit#

**Comment by annieszot** [comment]
- [ ] Editors assigned (round 1)
- [ ] Feedback received, incorporated
- [ ] Editors assigned final round

**Comment by annieszot** [comment]
Assigning @srigdon for first-round review. Requesting edits by Wednesday, June 19 along with edits for #1995 and #2168.

**Comment by annieszot** [comment]
Thanks for the question @srigdon in the doc, and I'll unassign you and assign @LauraTrujillo to get a second opinion on "info" or "service page" :)

**Comment by srigdon** [comment]
@annieszot First round complete!

**Comment by annieszot** [comment]
Shazam! Thanks, @srigdon ! @LauraTrujillo final round assigned, edits requested by end of day Wednesday, June 26 with #1995, #2147, and #2168 please :)

**Comment by LauraTrujillo** [comment]
@annieszot The page looks fantastic! and I left my 2 cents for a service page :)

**Comment by annieszot** [comment]
Great! Thank you 👍 Will rework and format to a service page. Closing
