### ISSUE TITLE
Implement translation notification page component

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#216]
@cthibaultatx has designed a component to notify users when the page they are looking at has not yet been translated into their language.

general notification component that can be page-specific or applied sitewide. It can be dismissed. If a user dismisses it, the block should stay dismissed for the remainder of the session.

PS In the design library, there is a notification for emergencies.

On the technical side, do we have awareness at a page level of the state of translations? How do we know if they are missing?

![screen shot 2018-06-08 at 8 43 49 am](https://user-images.githubusercontent.com/20911665/41161357-3386f8a0-6af8-11e8-9515-f2f95fec6124.png)

**Comment by amenity** [comment]
Cleaning out ancient, probably-no-longer-applicable, issues.
