### ISSUE TITLE
Add editorial style decisions to style guide

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2165]
We have a number of editorial style decisions we've made (how to format times! how to format phone numbers! etc) that currently only live in the [grammar/usage/style/editing guide](https://docs.google.com/document/d/1yL3afGS_72aFYBoF7ZH90yUCNeqAgYx1RuRxc_JbZAw/edit?usp=sharing). We should review to see what is relevant for City of Austin content editors (specifically thinking about those who will be maintaining content on the Joplin MVP) and add to our Gitbooks style guide.

**Comment by ablangworthy27** [comment]
The specific examples listed in this issue (times and phone numbers) are actually already included in gitbook style guide.

However, I did create a new issue to update the Usage section in the grammer doc and add to the style guide. This is a different and bigger task. 

Also,  I think ultimately this grammar doc should be archived. The information on should/will ultimately be split up into the style guide and the Content Field Guide.
