### ISSUE TITLE
Revise tree recycling information page 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2168]
Draft: https://docs.google.com/document/d/1ndA1r5ecc_CpzNKzMZEDmbJC96zrC5mGA2r0JpUt8lE/edit#

**Comment by annieszot** [comment]
- [ ] Editors assigned (round 1)
- [ ] Feedback received, incorporated
- [ ] Editors assigned final round

**Comment by annieszot** [comment]
![Screen Shot 2019-06-13 at 5 03 05 PM](https://user-images.githubusercontent.com/46934140/59470473-614a1c80-8dfd-11e9-830b-517d4634106d.png)

**Comment by annieszot** [comment]
Considering turning this into a table. Adding @chasechenevert to check-in and make sure content align with his recommendations/mock designs.

**Comment by annieszot** [comment]
Assigning @srigdon for first-round review. Requesting edits by Wednesday, June 19 along with edits for #1995.

**Comment by srigdon** [comment]
First review finished! See edits and comments in line.

**Comment by annieszot** [comment]
Thanks @srigdon ! Unassigning :)

**Comment by annieszot** [comment]
Adding @LauraTrujillo to put on your radar for final revisions bundle by Wednesday, June 26. Warning there's a lot of comments and structure items to suss out here, but asking for final review on agreement with first-round suggestions. Goal is to work out tables with @chasechenevert by early next week. Thank you!

**Comment by chasechenevert** [comment]
## Visual design: fee table mockup
I had a moment to mockup that fee table and i think this works fine. I’ve used bolding here for the location name but i’m not sure what we’ll allow in joplin. we will want to constrain styling within tables, but i’m not sure what other use cases might challenge the current thinking.


<img width="485" alt="Screen Shot 2019-06-21 at 2 49 56 PM" src="https://user-images.githubusercontent.com/7027270/59948305-3c752b00-9435-11e9-96b8-59ee2b2728f9.png">

**Comment by LauraTrujillo** [comment]
reviewed! Let's say "Christmas trees" instead of "holiday trees" because it shows up higher in searches :)

**Comment by annieszot** [comment]
Thanks, y'all! Closing :)
