### ISSUE TITLE
enlarge submenu item hit area

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#218]
![screen shot 2018-03-27 at 10 23 34 am](https://user-images.githubusercontent.com/20911665/37977233-f8d703c2-31a8-11e8-9d5b-7acbef6a4543.png)

When I try to click "Recycling, trash, & compost" I usually have to click more for the link to work. @ifsimicoded I figured out (thanks to @luqmaan) that the reason I have to click so many times to get the submenu item to work is because I'm clicking outside the click area.

**Comment by mateoclarke** [comment]
This will be fixed once Simi's Pull Request get merged: https://github.com/cityofaustin/janis/pull/203
