### ISSUE TITLE
Revise street sweep information page 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2188]
Draft https://docs.google.com/document/d/15UINZ4xEZgOaW3sU1oMypoQZ124Z-_2hKwCdok4KPbI/edit#

**Comment by annieszot** [comment]
- [x] Editors assigned (round 1)
- [ ] Feedback received, incorporated
- [ ] Editors assigned final round

**Comment by annieszot** [comment]
Assigning @JeffCopy for first round edits. Requesting edits by Tuesday, June 11.

**Comment by JeffCopy** [comment]
my suggested edits in place, ready for next steps.

**Comment by annieszot** [comment]
Adding @LauraTrujillo for second round review. Edits requested by Friday, June 14. 
https://docs.google.com/document/d/15UINZ4xEZgOaW3sU1oMypoQZ124Z-_2hKwCdok4KPbI/edit?ts=5cfaa276

**Comment by LauraTrujillo** [comment]
@annieszot reviewed!

**Comment by annieszot** [comment]
Thank you! Closing :)
