### ISSUE TITLE
Translated page descriptions need longer character limits

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2193]
English: The City of Austin offers curbside compost pickup for residents as part of our goal to keep 90% of materials out of landfills. Use our tool to find out what you can compost in Austin.

Spanish: La Ciudad de Austin ofrece servicio de recolección de compost al borde de la acera para los residentes como parte de nuestra meta de mantener 90% de los materiales fuera de los vertederos. Utilice nuestra herramienta para ver lo que puede convertir en compost en Austin.

![Screen Shot 2019-05-29 at 3.18.54 PM.png](https://images.zenhubusercontent.com/5a81e9804b5806bc2bc6a13b/1f15fdbb-3804-49d4-93c7-216c5127a0ea)

**Comment by easherma** [comment]
@LauraTrujillo @toribr  Eventually we should be able to define separate limits by language. For now, given that this is just a little over the default limit of 255 (at 270), how bout we just increase the character limit for this section on service pages only?

**Comment by LauraTrujillo** [comment]
Works for me, @easherma. If it's not too difficult, can we increase it for info pages too?

**Comment by toribr** [comment]
Yep. @LauraTrujillo will you create an issue that defines it properly, ie, limit by language?
