### ISSUE TITLE
User story-request a composting class form

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2202]
### As a resident who wants to request a compost class to get a home composting rebate, I want to notify someone at the City about my interest and get a class scheduled. 

More context see #2273 

**Is your feature request related to a problem? Please describe.**
Nope. Austintexas.gov simple form transition ARR 

**Describe the solution you'd like**
A simple form that can be filled out quickly and ARR is notified by email.

**Describe alternatives you've considered**
No alternatives considered. Would be awesome if the date requested populated into a future calendar feature (long-term future). 

**Additional context**

**Acceptance criteria**
See content draft https://docs.google.com/document/d/1MD2Ioqgbn4_C27ruYes1AK_o-8H-mfexxy7vc50-x48/edit?ts=5d1e9f0f
Simple form is a transfer of info captured from the form on austintexas.gov
Form passes QA testing 
All information is captured when submitted 
Email sent to Austin Resource Recovery (email address tbd) upon form submission and to resident who submitted. 

**Definition of done**
Form can fluidly toggle between English and Spanish and all information is captured

**Comment by annieszot** [comment]
Content draft
https://docs.google.com/document/d/1MD2Ioqgbn4_C27ruYes1AK_o-8H-mfexxy7vc50-x48/edit

**Comment by annieszot** [comment]
Adding @desigonz for comms on implementing simple form for ARR

**Comment by desigonz** [comment]
Yay requesting compost classes! I did a first round of edits.

**Comment by annieszot** [comment]
Thanks so much @desigonz ! Before passing it on to @LauraTrujillo I'll bring it to content pin-up Tuesday.

**Comment by annieszot** [comment]
Moving milestone to Sprint 35. Will  strategize and establish a goal for sprint 35 7.12.19

**Comment by annieszot** [comment]
https://docs.google.com/document/d/1MD2Ioqgbn4_C27ruYes1AK_o-8H-mfexxy7vc50-x48/edit?ts=5d1e9f0f 
Got the greenlight/content approval from ARR. Ready to move forward @desigonz
