### ISSUE TITLE
Publish + Translations compost class form 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2206]
**Revise process for forms (markdown next comment)
Refer to https://docs.google.com/document/d/1vGsq17-a1Ho9gjkVBUiTNnPLsrGPkLfWKP7gPv5kpJ8/edit#heading=h.xbik72h24d7a

**Comment by annieszot** [comment]
- [ ] forms.austintexas.io?  
- [ ] Share page with stakeholders to interact with, provide feedback
- [ ] User testing determined (Y/N)
If yes
- [ ]  User testing conducted
- [ ] User testing changes incorporated
Process for translations
- [ ] Audit Alpha for all missing translations, including pages, UI elements, and error messages
- [ ] Submit to translators
- [ ] Review translations and approve them
- [ ]  Input new translations into Alpha

**Comment by annieszot** [comment]
See #2574

**Comment by annieszot** [comment]
Translations doc to send https://docs.google.com/document/d/1vH6eQN5f3VIpB4QBzATwcQSV-AR_7Q2Ci4y7LdAaAl8/edit

**Comment by desigonz** [comment]
Duplicate of #2574
