### ISSUE TITLE
Helper text location is wonky in Joplin

### ISSUE THREAD

**Issue by oliver2g** [cityofaustin/techstack#2212]
Helper text doesn't display correctly. This could cause confusion for city staff content managers

**Comment by easherma** [comment]
Related: https://github.com/wagtail/wagtail/issues/4473

**Comment by easherma** [comment]
May also be related: 
https://github.com/wagtail/wagtail/issues/4430
https://github.com/wagtail/wagtail/pull/4374

**Comment by easherma** [comment]
It looks like we've made some css changes over time that effect this. (ex: https://github.com/cityofaustin/joplin/blame/1abdb7880394940cc6f2624e9ecf1309bca42fca/joplin/css/editor.scss#L20)
We should reconsider these changes, and the value they bring vs using wagtail as intended. 
We should sync with design so we have consistent mocks and can think about these elements authoritatively. 
Therefore, this may be a better thing to revisit post MVP vs another quick change now.

**Comment by easherma** [comment]
Also HelpPanels are cool, maybe we can use those more:
https://docs.wagtail.io/en/v2.5.1/reference/pages/panels.html?highlight=HelpPanel
Also this video goes over some various uses of help text:
https://www.youtube.com/watch?v=ciYNMcv3lE0

**Comment by easherma** [comment]
Related: 
https://github.com/wagtail/wagtail/issues/4471

FieldPanels don't have headings assignable atm. We could potentially fix/add this and contrib back to wagtail.
