### ISSUE TITLE
Mobile and desktop previews are broken with Janis 2.0 build

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#2215]
**Describe the bug**
Preview links and mobile preview show a blank screen and several errors

**Expected behavior**
Using a pasted link, clicking 'Preview', or viewing the Mobile Preview should all show a version of the page with the latest saved changes running on the current production version of Janis.

**Comment by briaguya** [comment]
Fixed previews in prod with: https://github.com/cityofaustin/janis/commit/e789a6d44097228d9be4d70a0f7272cdfffc9c77

Fixed previews in staging with:
https://github.com/cityofaustin/janis/commit/7d109b4e6b6c70aab784585f37d1a9539edad7cf

**Comment by briaguya** [comment]
There is placeholder data for some things due to discrepancies in how revisions are pulled from the DB vs how published pages are built.

You may see "Sample Text" in a few places.
