### ISSUE TITLE
Janis - Airport/311 links in wrong position at certain screen widths

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#2220]
The airport/311 links show up on the left at certain in-between widths, this shouldn't happen.

We should probably just switch to the mobile header style earlier, but it's worth looking into keeping the full size header at smaller widths.

<img width="225" alt="Screen Shot 2019-05-30 at 12 22 31 AM" src="https://user-images.githubusercontent.com/6384156/58610480-2da1bb00-8271-11e9-89de-dbeadaec0f4f.png">

**Comment by easherma** [comment]
closing, dupe of https://github.com/cityofaustin/techstack/issues/2238
