### ISSUE TITLE
Joplin - moving data between envs is borked

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#2221]
Smuggler is being weird, we should get better at moving data between Joplin environments so we can have:
## Top Priority
* Joplin prod data in local dev envs
## Bonus Priority
* Joplin prod data in staging
* Joplin prod data in Joplin PR apps

Original:
```
The sanitize data script in joplin is currently just replacing every instance of a user emails with 'admin@austintexas.io'.

This works well for making sure we can load pages, but fails to load in with smuggler because of duplicate `wagtailusers.userprofile` entries.

We should update our script (which uses [jq](https://stedolan.github.io/jq/)) to remove these entries automatically
```

**Comment by easherma** [comment]
So to test this: 

- go to joplin prod
- download a dump using django datadump
- try to load this dump in a local joplin env (ideally using vanilla django)
- watch for errors; make it so there are no errors

**Comment by easherma** [comment]
Not quite related, but maybe steal some of these utilities: https://cfpb.github.io/cfgov-refresh/migrations/

**Comment by easherma** [comment]
Ok I got this working by dumping through heroku CLI: 
`heroku run -a joplin python ./joplin/manage.py dumpdata --natural-foreign --natural-primary -- > data.json`

**Comment by easherma** [comment]
@Niicck lets discuss how to best integrate the above command into our build pipelines/where to expose it?

The way I tested it:
* go to joplin prod
* download a dump using the heroku CLI to call dumpdata as above
* I loaded this into my local env using smuggler (django-admin/load) for convenience, but that can surely be optional

**Comment by briaguya** [comment]
@easherma @Niicck made a quick PR with some interim fixes, hoping to get it into staging

**Comment by briaguya** [comment]
So it looks like with my latest changes the data loads in, and we can save drafts of any existing pages, we can also make new pages and publish them, but if we try publishing an existing page we get a ton of errors.

This happens both locally and on staging now.

**Comment by Niicck** [comment]
Issued addressed more specifically in https://github.com/cityofaustin/techstack/issues/2311
