### ISSUE TITLE
Revise chicken keeping information page 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2225]
Draft https://docs.google.com/document/d/18ybLb6Wo6YUqLZXAC_LgxLk9P9ffyNxiZyiFi8gIF7w/edit#

Hemingway App reading level: Grade 5

**Comment by annieszot** [comment]
- [ ] Editors assigned (round 1)
- [ ] Feedback received, incorporated
- [ ] Editors assigned final round

**Comment by annieszot** [comment]
Assigning @JeffCopy for first round edits. Requesting feedback by Thursday, June 20.

**Comment by JeffCopy** [comment]
My suggested edits there for your perusal; onward!

**Comment by annieszot** [comment]
Thanks @JeffCopy ! Assigning @LauraTrujillo for final round revisions. Requesting edits by Monday, June 24. Thanks!

**Comment by LauraTrujillo** [comment]
@annieszot good to go!

**Comment by annieszot** [comment]
Thank you much @LauraTrujillo ! Closing!
