### ISSUE TITLE
Search within wagtail throws error

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#2230]
**Describe the bug**
If you try to search the page list the system throws an error

![Screen Shot 2019-05-30 at 8.44.54 AM.png](https://images.zenhubusercontent.com/5a81e99a4b5806bc2bc6a146/282dc204-9c86-4ac7-8baf-301ff67f0a76)

**Comment by briaguya** [comment]
While investigating fixes for this, I started getting ideas. Instead of jumping in and spending a lot of time on things without any prioritization or design work, I made an issue https://github.com/cityofaustin/techstack/issues/2253
