### ISSUE TITLE
Department pages that aren't OPO

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2237]
**Describe the bug**
We published the ARR department page without an image and it's doing some wonky things! Probably due to the OPO department page customizations. See image below—no title, but button that goes to Google. Lol.
![image](https://user-images.githubusercontent.com/5839508/58645122-54d7a700-82c8-11e9-8346-c6726fb9748a.png)

I'm going to unpublish this page for now...but it should also be viewable in preview.

**URL**
https://joplin.herokuapp.com/admin/pages/3/

**To Reproduce**

1. Go to 'Austin Resource Recovery and view draft

**Comment by briaguya** [comment]
@desigonz I think we should rename this:
"department pages won't display a header without a banner image.

I need to get some stuff merged into prod janis but right now (after I removed the link to google and added an image in joplin) it looks like this: https://deploy-preview-436--janis.netlify.com/en/preview/department/UGFnZVJldmlzaW9uTm9kZTo3NTc=
