### ISSUE TITLE
Janis nav at ~900px width breakpoint

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2238]
**Describe the bug**
Nav is acting funny at certain breakpoints. In the screenshot below, I'm at about 900 px width. The full theme nav is collapsed, but the links for "Airport" and "311" have shifted to under the menu icon (I expect them to be on the right.)

![image](https://user-images.githubusercontent.com/5839508/58645784-9fa5ee80-82c9-11e9-822b-88811592b08f.png)

**URL**
https://alpha.austin.gov/

**Comment by briaguya** [comment]
i think this is the same as this: https://github.com/cityofaustin/techstack/issues/2220

**Comment by easherma** [comment]
related/dupe: https://github.com/cityofaustin/techstack/issues/2220

**Comment by briaguya** [comment]
@easherma lol timing

**Comment by desigonz** [comment]
Also this happens when nav is open
![image](https://user-images.githubusercontent.com/5839508/58657698-76df2280-82e4-11e9-8831-35c35c738938.png)

**Comment by desigonz** [comment]
Related: #2272
