### ISSUE TITLE
Get 311 links translated and implemented in code

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#224]
continued from https://github.com/cityofaustin/techstack/issues/185

@ifsimicoded updated the 311 components to the new design but we're missing translations. Adding this issue to make sure there is a handoff from content to dev once we get those from the 311 dept

**Comment by LauraTrujillo** [comment]
311 services (English): https://docs.google.com/document/d/1ms8iDsrm28gSFK8B0n1KgxrwJRKastkx80zwMJNQm4E/edit?usp=sharing 

@mateoclarke @ifsimicoded: translations are below:

- [ ] [311 prioritized services_Arabic.docx](https://github.com/cityofaustin/techstack/files/1891570/311.prioritized.services_Arabic.docx)
- [ ] [311 prioritized services_spanish.docx](https://github.com/cityofaustin/techstack/files/1891571/311.prioritized.services_spanish.docx)
- [ ] [311 prioritized services_Vietnamese.docx](https://github.com/cityofaustin/techstack/files/1891579/311.prioritized.services_Vietnamese.docx)

**Comment by LauraTrujillo** [comment]
@ifsimicoded @mateoclarke Here is the spreadsheet: https://docs.google.com/spreadsheets/d/1lNjU0moOXBUAKpdInm-R5auWljnB3_5F6cUt30UuSxw/edit?usp=sharing

I greyed the services that fell after the top 9, since our design only allows for the top 9. I went ahead and moved "Other" to the 9th spot on the list, with an example of what an "other" 311 service request looks like underneath it.

Holler if you have any questions!

**Comment by ifsimicoded** [comment]
Thank you! Just FYI, I think we're only using 8 links and the last link will be All 311 services based on @cthibaultatx comments here: https://github.com/cityofaustin/techstack/issues/236
So I think we have one more translation need for 311 -- 'All 311 services'

**Comment by LauraTrujillo** [comment]
@ifsimicoded Here is "All 311 services"
[All 311 Services.docx](https://github.com/cityofaustin/techstack/files/1928355/All.311.Services.docx)

**Comment by ifsimicoded** [comment]
Hey @LauraTrujillo, sorry to ask in so many pieces. I'm having trouble finding the appropriate urls for each of the 311 services in the translated content [google drive document](https://docs.google.com/spreadsheets/d/1lNjU0moOXBUAKpdInm-R5auWljnB3_5F6cUt30UuSxw/edit?pli=1#gid=0). I filled in the best I could using the list provided here: http://311.austintexas.gov/reports/list_services. Could you fill in the gaps? or help me figure out where else I can go to find this info. THANKSSSSS

**Comment by LauraTrujillo** [comment]
@ifsimicoded Ask away!! I filled in the urls where I could- thanks for reaching out! There are two that I'm missing, but because they fall well after the top 9, I don't think they will block you. Holler if you need anything else. Thank YOUUUUUUUUU!!!

**Comment by ifsimicoded** [comment]
Dearest @LauraTrujillo, 
Thank you much for this! In many cases the landing page language doesn't mate up with the link language. For example, 'Request Environmental Services' lands on 'Submit Food Complaint Request
' -- which doesn't mean close to the same thing to me. Will these landing pages be updated? I'm thinking if I get confused, our users will too.
Many ♥️ and I still have your charger. 
Fondly yours,
Simi
