### ISSUE TITLE
Document instances of ARR forms

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2244]
Create an issue per existing form on austintexas.gov that would need to be transitioned. Label it "Feature: forms" and "Site content."

**How a scale of 1-3 (1 being the easiest and 3 being the most complex), how complex would this form be to implement?**

**On a scale of 1-3 (1 being the least and 3 being the most), what kind of impact will this form have?**

**Comment by annieszot** [comment]
- [ ] Create user stories for forms

**Comment by annieszot** [comment]
Shout-out to @LauraTrujillo ! Thanks for your work on the content inventory!
