### ISSUE TITLE
Figure out workflow for requesting mailboxes

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2246]

**Comment by desigonz** [comment]
Here's what I've learned:
- We can request a mailbox with permissions through CTM. Multiple people can have access to one mailbox, which is great! I wonder what that will mean for some folks' workflows—this might have to be a new/another mailbox they have to check, which could be confusing,.
- Nameir is requesting a mailbox for some of the process workflow stuff he's doing. I asked him to keep me posted on what the experience is like—I'd like to be able to tell department contacts what to expect if they are switching to mailboxes

Other thoughts:
- As we have conversations with ARR and APH with about approval workflows, I'd love to get them on board to switching any existing individual's email addresses (aka "For more contact desi.gonzalez@austintexas.gov") with mailboxes ("For more contact reallygreatprogram@austintexas.gov"). We can probably help come up with names for the mailboxes and streamline requests to CTM. 
- Should we start documenting instances of new mailboxes we create, so they don't get unwieldy? How should we do so?

@LauraTrujillo and @annieszot, would love y'all's thoughts on this!

**Comment by annieszot** [comment]
Thanks so much for getting this rolling @desigonz ! 

So, the purpose of the mailboxes--will we consult departments to set up a specific mailbox through CTM for their program or department? Instead of tying "contact information" to a person or 311 or having their own IT departments do so? What's the purpose of setting up mailboxes? 

If so, how can Wagtail support this as we circulate our editorial process? See https://github.com/wagtail/wagtail/blob/87bbc31d88ca747584a47836985ec20677a2de82/docs/advanced_topics/settings.rst#email-notifications
![Screen Shot 2019-06-02 at 8 33 26 PM](https://user-images.githubusercontent.com/46934140/58770632-ba03f480-8575-11e9-90de-4ea120dfe2aa.png)

**Comment by desigonz** [comment]
Hi @annieszot! All good questions. The mailboxes are what I previously called "aliases" but I learned that's not the term CTM uses :) So these are end-user-facing email addresses that a resident would use to get in touch with a question about a program or a service, and it's not related to the draft/approval/translation process. 

Re: contact information—We can always privilege tying contact info to 311 if that's what a program/service prefers and makes the most sense. The goal of using generic/program-related email addresses is to make them more evergreen. Here are examples of drafts where a generic email address (rather than individual's names) would be a big benefit:
- [Sign up for a free diabetes prevention and education class](https://docs.google.com/document/d/1trSHZt3qXFT9VFVPny1CTT-T_yfSJXjMIFGFjDmLBQc/edit?usp=sharing)
- [Support for pregnant women and moms](https://docs.google.com/document/d/1N6y1lJv4HfyfOcc_l6kxZXBnda3v3gGQLg7zFDWQgPU/edit?usp=sharing)

Re: their own IT departments, great question, didn't even think about that. I assumed that CTM sets up all network (aka @austintexas.gov) accounts, but maybe @LauraTrujillo could clarify?

**Comment by LauraTrujillo** [comment]
@desigonz @annieszot This is exciting! Yes, let's document new mailboxes and who would be responsible for them (thinking this would be our primary contacts). It could be as simple as a google sheet in the Dept. Transition folder?

**Comment by desigonz** [comment]
@LauraTrujillo Do you mean document mailboxes we propose in a Google doc, or as they get created?

Also, thoughts on next steps for mailboxes after our meetings with APH and ARR contacts? It sounds like Jen in APH likes the idea of mailboxes but needs to socialize the concept with her team.

**Comment by LauraTrujillo** [comment]
@desigonz I meant as they get created.
I think we could start with APH's mailboxes so they're ready when Jen wins them over :)

**Comment by desigonz** [comment]
As we draft, log instances and recommendations for mailboxes here: https://docs.google.com/spreadsheets/d/1Nq9QexwfREUHyjaycdg8d-hUaTUWbvH1hbn4Z0d1qCc/edit?usp=sharing

**Comment by annieszot** [comment]
Workflow for setting up writinglab@austintexas.gov
Submit a help desk ticket through Service Now (type in service now in Sharepoint)
Mention requesting assistance setting up an email address for x purpose. 
Copy ticket number when submitted 
You'll be notified by email when the Service Now ticket is closed. 
To check emails in that account, click on your profile photo/placeholder in Outlook "My account". Select "Open another mailbox". Input the email address created via Service Now. 
To forward emails to you or another colleague, go to settings and search for "forwarding". Input email address to forward to.
