### ISSUE TITLE
Joplin links components to appropriate section in ODD style guide

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2254]
### As a content editor I want the style guide panel in Joplin to display information on the specific component/content type I am editing so that I can more efficiently find relevant guidance.

**Is your feature request related to a problem? Please describe.**
We used to have this functionality before we switched to Gitbooks

**Describe the solution you'd like**
As designed, each component should have a help icon, which when clicked, present the correct section of the style guide (using anchor tags). (@toribr, do you have any additional documentation for this?)

**Comment by easherma** [comment]
https://gitbook.canny.io/feature-requests/p/embed-a-gitbook-into-an-app-or-website

This appears to be broken/not possible with the new version of gitbook

**Comment by easherma** [comment]
So we fixed the above issue by syncing Gitbook with our old repo. This means we just need to do some style tweak to make everything look nice. 

_However_ syncing anchors between the repo is not as sustainability as I might have hoped. I've tried some template stuff with django but it is hard passing values between scope. The javascript used before is pretty janky too, but we could go through and update it to match. But as soon as we change/tweak things we'll run into the same problem again. 

We might need to take a step back and have a better approach.

**Comment by desigonz** [comment]
@easherma Sounds good, let's take a step back!

**Comment by desigonz** [comment]
Just reviewed how this is working in staging. 

On service pages, it anchors to "Creating service pages"! Yay!
Currently, all other content types are anchoring to "Writing process pages." Process pages are no longer a thing. I made issue #2578 for content team to add the missing content types.

**Comment by easherma** [comment]
@desigonz FYI I had already migrated the content from the old style guide to the new, it just isn't linking properly atm.

**Comment by desigonz** [comment]
During sprint 39, we'll work with content team to devise a strategy and answer bigger-picture style guide questions; after that, we will revise acceptance criteria.

**Comment by desigonz** [comment]
Got intel on how all this is actually working and am documenting here:

- [Gitbooks sync](https://cityofaustin.gitbook.io/digital-style-guide/make-content-accessible) to the [Github repo](https://github.com/cityofaustin/digital-services-style-guide). It's one way, so updating on the Github repo won't change anything in Gitbooks.
- Joplin pulls from the [Github repo](https://github.com/cityofaustin/digital-services-style-guide). 
- We haven't yet implemented it so that the menu syncs with Gitbooks. That's been confusing because when we navigate the style guide in Joplin, we see old content that doesn't match with Gitbooks.
![image](https://user-images.githubusercontent.com/5839508/65189208-f4ff3a80-da35-11e9-98e8-b85888346368.png)
- Since the Gitbook to Github sync is set up, we don't need to migrate info and department pages (#2985), we just need to fix the menu thing.
- Style guide content in Joplin
  - Currently, you see the correct style guide content on Joplin for information and service pages. 
  - Department page style content isn't appearing in Joplin—it 404s (see screenshot)
  - We don't have entries for the following content types; content team will be working on those in coming sprints; the first two are prioritized, second two are lower priority)
    - Guide
    - Official documents
    - Topic pages
    - Topic collections
![image](https://user-images.githubusercontent.com/5839508/65189478-b28a2d80-da36-11e9-8e11-dc4fba0708ee.png)
- Gitbooks would be nice to use because it's a nice, searchable interface to point people to outside the context of Joplin.
- The current Gitbook is *not* the link that we shared around the City a long time ago (so things like Sara P's bookmark and the Forms Style Guide point to something that's broken). Some options:
  - Communicate a new link to folks.
  - Set up a redirect, if possible?
  - Set up our old Gitbook to say "We've moved!" with a link.

@easherma I'm guessing every time we have a new content type entry in the style guide, it will require dev work to make sure it appears in the style guide pane in Joplin. What would you size that effort?

**Next steps**
- Content team will be working on new entries for content types. It sounds like we should be updating them in Gitbooks (#2578).
  - And actually, let's make sure folks have Gitbook accounts.
- @desigonz to work with team to develop acceptance criteria for getting the menu to sync properly (#3012). But this will be for later sprints (not a priority for sprint 40).
- Think about redirect strategy (#3013)
- Once #3012 and #2578, make issues so that Joplin links to those appropriate sections per content type.

**Comment by easherma** [comment]
"@easherma I'm guessing every time we have a new content type entry in the style guide, it will require dev work to make sure it appears in the style guide pane in Joplin. What would you size that effort?"
Very minor, 1 at most.

**Comment by desigonz** [comment]
I made issues #3180 and #3181 for next steps on dev implementation. Closing this doozy.
