### ISSUE TITLE
Joplin confirmation banner behavior

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2255]
### As a content editor I want the Joplin confirmation banner to appear and persist in a way that makes it easy for me to understand what actions were just saved/taken.

**Is your feature request related to a problem? Please describe.**
#1957 fixed a banner bug, but the banner still isn't working the way we'd like. The time out is pretty short, making it difficult to read at times. Do different banner messages (for different actions) need to persist for different amount of times?

**Describe the solution you'd like**
*A clear and concise description of what you want to happen.*

**Describe alternatives you've considered**
*A clear and concise description of any alternative solutions or features you've considered.*

**Additional context**
*Add any other context or screenshots about the feature request here.*

**Comment by easherma** [comment]
@desigonz you can qa this here: https://joplin-pr-2255-banner-behavior.herokuapp.com/admin/pages/3/

**Comment by desigonz** [comment]
@easherma Looking good! The acceptance criteria I'm using (per the conversation I had with @toribr this AM) is:
- [x] the banner time out duration is doubled

The banner is now at the top—is that part of this issue or a different one?
