### ISSUE TITLE
Joplin user flow for assigning page to a department

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2256]
### As a content editor I want to be able to associate a service or information page to one department so that end users can see which department that information is offered by.

Note: we already have the ability to add one department to a page, but it's not the ideal UX flow; however, we are holding off on the ideal flow until after Joplin MVP.

**Is your feature request related to a problem? Please describe.**
Information and service pages are "offered by" a department. A content editor should be able to assign that.

**Describe the solution you'd like**
The ideal UX flow for a content editor to select and edit which department a page is associated with.

**Describe alternatives you've considered**

**Additional context**
#1945

**Comment by easherma** [comment]
Isn't this superseded by https://github.com/cityofaustin/techstack/issues/2271?

https://joplin-pr-2271-simple-ugly-fix.herokuapp.com/ has implementation using wagtail's page choose for selecting related departments. 

Wagtail has several 'chooser' patterns built in. I'd recommend us checking those out and seeing if we consider them sufficient before trying to create an ideal user flow from scratch while also trying to implement that in this MVP product.

**Comment by desigonz** [comment]
This is the ideal, long-term user flow, not just the functionality.
