### ISSUE TITLE
DIscuss janis build pipeline, worker, AWS stuff

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#2265]
**Objective** 

Have clear knowledge of current build processes and interfacing with AWS so that knowledge can be easily transferred/shared between team members. 

**Agenda**
With Sergio leaving, we need to walk through in detail:
* where we got with a janis build pipeline, including testing/troubleshooting builds and how to roll back/view previous builds
* what is relevant in AWS, for janis and also for other projects, and what can be archived or deleted to browsing AWS is less confusing

**Comment by sergiogcx** [comment]
@Niicck and I have already discussed this issue. @easherma was also present for the greater part of the discussion. Will leave documentation.
