### ISSUE TITLE
Auto-log out

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2266]
### As a content editor I want to be automatically logged out of Joplin after a certain period of time so that I can feel that the website is secure.

Acceptance criteria:
- [ ] A user gets logged out of their account after 4 hours.

Note: this is fairly arbitrary, and should be revised according to author feedback.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by desigonz** [comment]
@toribr Can you update the acceptance criteria above with the appropriate amount of time for auto-log out? Thanks!

**Comment by easherma** [comment]
We can also set Django to log out the user if they close the browser window, should we also do that?

**Comment by easherma** [comment]
https://joplin-pr-2266-auto-logout.herokuapp.com/ to QA

**Comment by desigonz** [comment]
It works! 

![image](https://user-images.githubusercontent.com/5839508/60685739-69c8cc80-9e6a-11e9-822f-a42371148f50.png)

Is that message Wagtail's?
