### ISSUE TITLE
Filter content listing page on Joplin

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2269]
### As a content editor I want filter pages by multiple dimensions so that I can easily find what I need in a sea of content.

**Acceptance criteria**
On the [content listing page](https://joplin.herokuapp.com/admin/pages/3/), a user can filter by:
- [ ] Users can show or hide filter section
- [ ] User can filter by page type
- [ ] User can filter by page status
- [ ] User can filter by last updated date range (as indicated in [this mock](https://github.com/cityofaustin/techstack/issues/2269#issuecomment-501344639))
- [ ] When filter section is collapsed/hidden and filters have been applied, 
  - number of results for the currently applied filters are displayed (as indicated in [this mock](https://github.com/cityofaustin/techstack/issues/2269#issuecomment-501344639))
 - and filters selected are displayed and separated by commas, also as indicated in the mocks.

**Comment by desigonz** [comment]
@toribr, I believe you identified dimensions for the filters when we workshop Joplin UI stuff last week—can you update the above acceptance criteria?

**Comment by toribr** [comment]
Initial comps:
![#2269](https://user-images.githubusercontent.com/3790067/59199729-4907a280-8b5c-11e9-9c31-ab61308906a8.png)
![Content List with Filter](https://user-images.githubusercontent.com/3790067/59199730-49a03900-8b5c-11e9-978e-721617dcfd9a.png)
![Content List, filter closed](https://user-images.githubusercontent.com/3790067/59199731-49a03900-8b5c-11e9-9582-02eb8048bdd5.png)

**Comment by toribr** [comment]
![Content List Filter #2269-MVP](https://user-images.githubusercontent.com/3790067/59367916-bbb28280-8d02-11e9-9aba-aa0b5b18e116.png)
