### ISSUE TITLE
Prep for CMS test

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#227]
## Preparation
- [x] Storyboard and write test plan, share with all team - Laura
- Team reviews test plan
     - [x] @cthibaultatx 
     - [ ] @toribr 
     - [ ] @courtneyjacinic 
     - [x] @ashleecoa 

## Prepare prototype
- [x] Design prototype and develop content, review with test team

## Recruiting & Scheduling
- [x] Recruit 5 participants (Jorge from ARR should be one of those users)
- [x] Review test approach and etiquette with team and participating partners
- [x] Ashlee sends email with testing dates and times to Drupal users (testing week of April 9th)

## Test prep
- [x] Build test kits: consent form, video camera, audio recorder, moderator's script, copy of talk-aloud preamble, copies of CMS "fake" content, green m&ms, jump drive with test (backup)
- [x] pre-test the prototype before April 7th

**Comment by cthibaultatx** [comment]
@LauraTrujillo where's the test plan? Could you add a link here?

**Comment by cthibaultatx** [comment]
@LauraTrujillo @courtneyjacinic @ashleecoa @toribr here's the github template for creating new usability test issues: https://github.com/cityofaustin/techstack/blob/master/usability_test_template.md

**Comment by LauraTrujillo** [comment]
@cthibaultatx test plan here: https://docs.google.com/document/d/1TNzjJqR8MtvzTnpyGlLsvgEledDMd7kT1ApgZHHbNxE/edit?usp=sharing

**Comment by cthibaultatx** [comment]
@LauraTrujillo @ashleecoa @toribr thinking about CMS test participants, I imagine they should be author-publishers who've haven't tested a content management prototype with us prior. Have y'all talked about this?

**Comment by ashleecoa** [comment]
@cthibaultatx We've talked about it. We could do that, but we were thinking 5 participants. Would it be OK to have at least one that we've tested with before. We wanted to get Jorge (ARR) input. @LauraTrujillo

**Comment by toribr** [comment]
Yes, it's ok to test with Jorge - might be good to have one previous. We can expand the test if we don't think we've gotten what we need.

**Comment by cthibaultatx** [comment]
That impacts the test data @toribr @ashleecoa I recommend reviewing it with Jorge but not evaluating that review with the rest of the test data.

**Comment by cthibaultatx** [comment]
Here's Tori's note taker airtable: https://airtable.com/shr7yL8t4ZdAVm48o
