### ISSUE TITLE
Associate one page with multiple departments

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2271]
### As a content editor I want to be able to assign more than one department to an information or service page so that I can properly reflect the services that are related to more than one department.

Acceptance criteria:
- [ ] On Joplin, a user can add more than one department to a page

~~*Note: we know this will be a need in the future. Should we hold off until we have content ready to publish that is offered by multiple departments, or implement now for Joplin MVP? Review with content team to check if any ARR or APH content needs to be co-presented.*~~ 
Found it! [The smoke-free event service page](https://docs.google.com/document/d/1kCU9JHW3R1PqEpH0wzj7Q0eeFQO6_EE0tF9mU2NrFaA/edit?usp=sharing) is something that is offered by two departments.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by briaguya** [comment]
Made this an 8 because we need it to work with both Janis and Joplin

**Comment by briaguya** [comment]
We should also make sure we have all our bases covered when it comes to the design of this:
* How do we want offered by to look? Should we have multiple departments there?
  * If we don't want multiple departments in offered by, how do we decide which one shows up?

@toribr @chasechenevert any thoughts?

**Comment by desigonz** [comment]
> Made this an 8 because we need it to work with both Janis and Joplin

@briaguya Should we split into multiple issues?

**Comment by briaguya** [comment]
@desigonz I think high level we're looking at:
* Joplin - Update data model/api to support multiple departments for pages
  * Make sure we update Janis so this doesn't break the build
* Janis - Make sure we build the pages at all correct urls (under every department)
* Janis - Make sure we display department information correctly for each page
  * In xd we have multiple department lines in mobile (https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/51aa2fb9-cba8-4f59-a726-f8be07fb39ff/Service-MVP-Mobile/), not sure what it should look like on desktop

**Comment by chasechenevert** [comment]
For Janis we decided not to deal with multiple departments for the MVP of the contextual nav since it would involve more interaction, but if it sounds like we have a need now we can make it happen. 

The model we are using for the contextual nav is mass.gov's: https://www.mass.gov/how-to/apply-for-the-women-infants-children-wic-nutrition-program. It would be something similar to that, but we'd need to work through some drafts to see if we want to change anything about the interaction or styling.

<img width="1439" alt="Screen Shot 2019-07-03 at 11 11 08 AM" src="https://user-images.githubusercontent.com/7027270/60607716-6dcdef00-9d83-11e9-824e-634c91bf6a3f.png">


CC: @toribr

**Comment by desigonz** [comment]
@chasechenevert With guides coming soon and the example above, we're seeing a need for multiple departments now. Can you mock up what that would look like on Janis?

**Comment by desigonz** [comment]
@briaguya and @easherma 

**Additional acceptance criteria**
- [ ] When "offered by" multiple departments, list all the departments separated by comma
- [ ] parent page is always where you came from
- [ ] if navigated from a department, keep the "related" blank

**Comment by easherma** [comment]
https://github.com/cityofaustin/joplin/pull/295 is a fix that just adds the functionality for service pages but im not going to copy paste code for all the other page types since we don't have any other examples and I really don't like the approach we're currently using in the codebase

**Comment by easherma** [comment]
https://github.com/cityofaustin/janis/pull/456 janis side of this is here
