### ISSUE TITLE
Review Chronic Disease Prevention and Control pages

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2278]
- [x] [Join the Central TX Diabetes Coalition](https://docs.google.com/document/d/1llvtWtb2JSuAA6D8GDdBOsZW5JfZeq01C1XtpF3dVxI/edit?usp=sharing)
- [x] [Sign up for a diabetes prevention and education class](https://docs.google.com/document/d/1trSHZt3qXFT9VFVPny1CTT-T_yfSJXjMIFGFjDmLBQc/edit?usp=sharing)
- [x] ~~Chronic disease prevention info page~~ **ARCHIVE** and make a [chronic disease prevention](https://docs.google.com/document/d/1gwQnZf_rbIAi0lgqhBLz16x62G8lJgS_BrTWQfo1IxU/edit?usp=sharing) topic page instead
- [x] ~~Diabetes prevention info page?~~ **ARCHIVE**—merged with "sign up for a diabetes class"
- [x] [Start your Walk TX! 10 week challenge](https://docs.google.com/document/d/1_7GiFicELWsiEAt8P8ug8NIV_bOAXND2P-sd89uUYgQ/edit?usp=sharing)
- [x] [Free help to quit tobacco](https://docs.google.com/document/d/1TIZi3sZW_Wee9wHdcZS6b_gOFdGEdnVmjdUTkj9djgU/edit?usp=sharing) info page

**Comment by desigonz** [comment]
@srigdon Would you mind reviewing the following pages? All of them have gone through some sort of editing before but they've been revised to reduce redundancy. Hoping they'll be a quick pass.

- [ ] [Chronic disease prevention](https://docs.google.com/document/d/1gwQnZf_rbIAi0lgqhBLz16x62G8lJgS_BrTWQfo1IxU/edit?usp=sharing) topic page
- [ ] [Join the Central TX Diabetes Coalition](https://docs.google.com/document/d/1llvtWtb2JSuAA6D8GDdBOsZW5JfZeq01C1XtpF3dVxI/edit?usp=sharing) service page
- [ ] [Sign up for a diabetes prevention and education class](https://docs.google.com/document/d/1trSHZt3qXFT9VFVPny1CTT-T_yfSJXjMIFGFjDmLBQc/edit?usp=sharing) service page
- [ ] [Free help to quit tobacco](https://docs.google.com/document/d/1TIZi3sZW_Wee9wHdcZS6b_gOFdGEdnVmjdUTkj9djgU/edit?usp=sharing) info page

**Comment by desigonz** [comment]
@JeffCopy can you take a quick pass on the following? 

- [ ] [Chronic disease prevention](https://docs.google.com/document/d/1gwQnZf_rbIAi0lgqhBLz16x62G8lJgS_BrTWQfo1IxU/edit?usp=sharing) topic page
- [ ] [Join the Central TX Diabetes Coalition](https://docs.google.com/document/d/1llvtWtb2JSuAA6D8GDdBOsZW5JfZeq01C1XtpF3dVxI/edit?usp=sharing) service page
- [ ] [Sign up for a diabetes prevention and education class](https://docs.google.com/document/d/1trSHZt3qXFT9VFVPny1CTT-T_yfSJXjMIFGFjDmLBQc/edit?usp=sharing) service page
- [ ] [Free help to quit tobacco](https://docs.google.com/document/d/1TIZi3sZW_Wee9wHdcZS6b_gOFdGEdnVmjdUTkj9djgU/edit?usp=sharing) info page

**Comment by JeffCopy** [comment]
Just a few options and suggestions; these look good.

**Comment by desigonz** [comment]
Thanks for your amazing edits as usual, @JeffCopy!

Now to @LauraTrujillo for second review :)

**Comment by LauraTrujillo** [comment]
Reviewed with a few comments/suggestions
