### ISSUE TITLE
ARR Engagement Plan 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2279]
To reference June-August 2019
https://docs.google.com/document/d/1HuPflGdAb9mBz2AMJ7qxkjeDGbYvE0DB24_m1O2QZso/edit#

**Comment by annieszot** [comment]
All right @LauraTrujillo the plan is ready for you! Call to check-in on it tomorrow if necessary? Thanks!

**Comment by LauraTrujillo** [comment]
Good to go! I sent a meeting invite for next week, which was as soon as I could set it. Fingers crossed we can all attend!

**Comment by annieszot** [comment]
AWESOME @LauraTrujillo ! Thanks so much and sending good meeting vibes!
