### ISSUE TITLE
Primary "update/save" actions on editing page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2285]
### As a content moderator editing a live page, I want the primary action on an editing page to be "update" and a secondary action to be "save draft."

Acceptance criteria: 
- [x] This happens only once a page is live, not on pages that have not yet been published
- [x] This happens for the moderator and admin roles
- [ ] Primary action label is "Update" (but functions as the publish button has been—should request a build)
- [x] the next option in the dropdown is "Save draft"

Current:
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/ee6e74fc-154b-49f9-ba68-eedd9c8bb590)

Future:
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/b9d1f0ae-5eab-42bf-bcf3-086de2b3a59a)

**Is your feature request related to a problem? Please describe.**
Content moderators want to be able to quickly publish out a change. This is also related to the problem in #2099 (saving drafts when there hasn't been a change).

**Describe the solution you'd like**
See diagram above. (Also keep the other buttons—"unpublish" and "delete")

**Comment by easherma** [comment]
@desigonz I think this is a good case where we ought to define some acceptance criteria. 
Are we asking for different behavior here? My read is the following, so please confirm:

Apply the following to _live_ pages only:
- change 'publish' to read 'update'. **the functionality of this button does not change**
- swap the publish/update button & 'save draft' in position on the button's dropdown menu

Draft pages (or unpublished pages) would not be changed at all?

**Comment by desigonz** [comment]
@easherma thanks for the feedback! You interpreted correctly, and I've added acceptance criteria above.

**Comment by desigonz** [comment]
@Niicck 
I made a change in Joplin, clicked "update," and got this error.
![image](https://user-images.githubusercontent.com/5839508/59222783-e9c38580-8b8f-11e9-99e5-ebb1f9cabe08.png)
To reproduce: 
1. go to https://joplin-staging.herokuapp.com/admin/pages/9/edit/
2. make a change
3. click update
What I expect: Same behavior as "publish" on other pages—exit out to listing view 
What happened: that error above :(

All the other acceptance criteria looks good.

**Comment by Niicck** [comment]
Thanks, Desi. That publish issue is a known bug. I'll look into it now.
