### ISSUE TITLE
Draft Stepping On fall prevention service page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2294]
https://www.healthyplaceshealthypeople.org/mycommunity/
http://www.austintexas.gov/department/injury-prevention

related to #1615

**Comment by desigonz** [comment]
[Draft here](https://docs.google.com/document/d/1tem6nHHmi1TzzuuUn3ROnf6g0JBPezrkKPCDppvc_wA/edit?usp=sharing)

@LauraTrujillo, I know this is going out of order, but would you mind reviewing it first? In a nutshell: information on this program is super vague, and it's unclear who the target audience is—seniors who want to participate in the class, or community orgs who want to host the class. I've written content that would work for either.

**Comment by LauraTrujillo** [comment]
@desigonz it looks great! What if we break out the pages into 2 service pages- one for seniors who want to participate, and another for people/orgs who want to host the class?

**Comment by desigonz** [comment]
@LauraTrujillo Let's recommend that to APH if that's actually the case!
