### ISSUE TITLE
Draft Injury Prevention topic page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2295]
see #1615 for more info

Group injury prevention services and info pages into a topic page

**Comment by desigonz** [comment]
[Draft lives here](https://docs.google.com/document/d/1ZOyDgCdkniYDcwieivbN4UZXjc46bYEiTMxzx7eRQgA/edit?usp=sharing)

@JeffCopy, do you mind taking a quick first review on this? For more on the back story for this topic page, see the comments in #1615.

**Comment by JeffCopy** [comment]
Headed there soon!

**Comment by desigonz** [comment]
Thanks @JeffCopy!

On to @LauraTrujillo for second review:
[Draft lives here](https://docs.google.com/document/d/1ZOyDgCdkniYDcwieivbN4UZXjc46bYEiTMxzx7eRQgA/edit?usp=sharing)

**Comment by LauraTrujillo** [comment]
@desigonz good to go!
