### ISSUE TITLE
Test using Gather Content as translation tool with mock screenshot

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#230]
To solve issue around translators not translating correctly - seems like they are copy pasting text and not looking at the mocks

**Comment by cthibaultatx** [comment]
ok @amenity @courtneyjacinic I'll close this issue but where's the issue re: "talking to them first"?

**Comment by amenity** [comment]
@cthibaultatx - thanks for catching that! Guessing I said I would make it and didn't. 
Here: https://github.com/cityofaustin/techstack/issues/240
