### ISSUE TITLE
Joplin navigation labels

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2315]
### As a content editor, I want to be able to easily navigate between different sections on Joplin (Content, Images, Contacts, Locations, Users) so that I can efficiently edit content.

**Is your feature request related to a problem? Please describe.**
Currently, the Joplin left nav only uses icons with no labels. It can be confusing to know where to edit something, especially in the instance of "Contacts" vs "Locations," which uses the same icon.

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/f25a9874-2332-4ac1-94e8-a7853182f2ab)

**Describe the solution you'd like**
Possibly adding labels and swapping out icons. Would later be great to test how users understand these labels/icons.

**Describe alternatives you've considered**

**Additional context**

**Comment by chasechenevert** [comment]
- [ ] Maps
- [ ] locations
- [ ] contacts

**Comment by chasechenevert** [comment]
Here are the names for the icons within the [Material icon font set](https://material.io/tools/icons/?icon=text_fields&style=baseline) that we have in Janis: 

- Map: "map"
- Locations: "location_on"
- Content: "text_fields"
- Images: "photo"
- Contacts: "contact_phone"
- Users: "account_circle"
