### ISSUE TITLE
Compile ARR batch 1 (information pages) 

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2321]

**Comment by annieszot** [comment]
Documenting batch and justification 
Information page (epics)
Street sweep #2192 
Holiday tree recycling #2172 
Brownfields #2153 
Soil kitchen #2157 
Haul it the right way #2151 
Zero Waste content #2133

**Comment by annieszot** [comment]
Street sweep #2192
Holiday tree recycling #2172
Brownfields #2153
Soil kitchen #2157
Haul it the right way #2151
Zero Waste content #2133
