### ISSUE TITLE
Take a TB test service page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2324]
[Draft here](https://docs.google.com/document/d/1Fi0AumyVMuGhnLB_9_vtnOcTJJK74NjezgbROohGu70/edit?usp=sharing)

**Comment by desigonz** [comment]
@JeffCopy Do you mind taking first review on this one?

**Comment by JeffCopy** [comment]
Just a few suggestions/options to consider; onward!

**Comment by desigonz** [comment]
Thanks! Onto @LauraTrujillo for second review.

**Comment by LauraTrujillo** [comment]
@desigonz reviewed with comments!
