### ISSUE TITLE
APH department page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2325]
We have a very old draft: https://drive.google.com/open?id=1LNk5SsdbxvvW_f38lux2Chg49tjrm6NZUhUtNxrDb3M
The draft needs to be revised and make sure it fits with our current content model/conventions.

**Comment by LauraTrujillo** [comment]
Updated draft: https://docs.google.com/document/d/1S7LjUH_K1CdJacZTHAR6YRMOC7tfSLjz0cl-wTb_t6U/edit

**Comment by LauraTrujillo** [comment]
@desigonz Can you do a first review of this page, please?

**Comment by desigonz** [comment]
@LauraTrujillo I did a first pass and added a bunch of comments!

**Comment by LauraTrujillo** [comment]
@desigonz Thank you for those great comments- very helpful!!
@annieszot can I get a second review from you by Monday, July 1st?

**Comment by annieszot** [comment]
Reviewed @LauraTrujillo ! Good to go! May want to work with APH's PIO to work on the wording for the intro paragraph, which mirrors the original copy, but it's really vague. This is good to go for MVP :)

**Comment by LauraTrujillo** [comment]
@annieszot Yes, this will definitely need to have APH review again. Previously, it got Linda Cox's seal of approval, but I'd like to get Jen's approval now.
