### ISSUE TITLE
Evaluate simple forms — USFS

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2328]
We want to stand up two fairly simple forms: #1904 (Day Labor) and #2210 (request a composting class). We'd like to evaluate which option—our existing forms based on USFS, or Wagtail forms—is the best option for us.

Using the [simple forms requirements](https://docs.google.com/document/d/1Na_3bpwkO6XIg0w9DOMFudXYELQeW24ZYdWfERnjw6k/edit?usp=sharing) we're compiling, let's evaluate how far along each option is for each.

Maybe: give each bullet point a rating of 1 to 5, with 1 being doesn't fulfill requirement at all and 5 being it does the best job ever and we don't have to do anything for it.

Afterward, we'll have a meeting to discuss!

**Comment by Niicck** [comment]
I'll implement the day labor form in usfs

**Comment by Niicck** [comment]
Frontend PR: https://github.com/cityofaustin/coa-forms/pull/43
Backend PR: https://github.com/cityofaustin/form-service-api/pull/28
