### ISSUE TITLE
Draft official document content model

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2330]
- [ ] Content model [in this doc](https://docs.google.com/spreadsheets/d/1ZkH93F4tJ0_Zjx4t8k6k6TgwSlOh8u8ejWmegE6WqH0/edit?usp=sharing) ready to go to devs

**Comment by desigonz** [comment]
![image](https://user-images.githubusercontent.com/5839508/59879109-9c090300-936f-11e9-92bc-b3236d05fd09.png)

**Comment by srigdon** [comment]
Drafted the content model, will have more complete version ready for devs by next sprint.
