### ISSUE TITLE
Fee table style conventions

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2331]
### As a content contributor, I want to know the conventions and best practices for tables, so that I can author a table that is consistent with others on austin.gov.

**Acceptance criteria**
- [ ] a content team member to think through the considerations below, make decisions, and add to the style guide

We now have the ability to add tables via Joplin using markdown (see #2333 for details on how to do so), as well as have them styling beautifully on Janis!

I've added the fee table to the [Get immunizations for you and your family](https://alpha.austin.gov/en/health-safety/healthcare-prevention/disease-prevention/get-immunized/) service page (in English and in Spanish) as an example. 

We need to develop style conventions for tables. @chasechenevert presented on tables for displaying prices during a pinup and pointed out various content considerations, including but not limited to:
- [x] heading language (price vs. fee vs. cost? How do y'all feel about "services" above? Should we have a default word for the first columb?)
- [x] cost annotations (ex. how I added "per dose")
- [x] when to use tables vs. when to not
- [x] governance things, always using a table for a fee, even if there is only one fee

When doing so, you might want to consider #2674—fee table for "Get a birth or death certificate."

![image](https://user-images.githubusercontent.com/5839508/62328504-f3bf8180-b478-11e9-8d78-0b4dd26e8aeb.png)

--------

**Additional context**
#1936

**Comment by Jo-Dwyer** [comment]
@chasechenevert when you get a chance, I'd love to know more about what was learned re: when to use a table vs when not to.

**Comment by Jo-Dwyer** [comment]
## Price vs fee
* a price is the amount as of money or goods, asked for or given in exchange for something else. 
* a fee is a fixed sum charged, as by an institution or by law, for a privilege

### Charges for services offered by the City of Austin will be referred to as fees.

**Comment by Jo-Dwyer** [comment]
## When to use tables

When there are three or more services with an associated fee, they should be displayed in a table.

For one or two services, is there another visual way to set the service and fee information apart from content?

**Comment by Jo-Dwyer** [comment]
Text has been added but I cannot for the life of me figure out how to add markdown in order to include the table.
