### ISSUE TITLE
Synthesis alpha navigation test data 

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2337]

**Comment by kriskristin** [comment]
Synthesis planned: https://drive.google.com/open?id=1UDH71O1Cof8k9EnKTluWwlgVaxeQAg7c

**Comment by srigdon** [comment]
- [ ] Logged the tasks with high failure percentages, the ones on the fence, and one that succeeded but took a long time for people to complete. 
- [ ] Need to add think-aloud observations to all of the above.

**Comment by desigonz** [comment]
Per sprint planning conversation, synthesis is complete! Closing this one.
