### ISSUE TITLE
ARR batch info pages "WHY" justification 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2353]
Street sweep #2192
Holiday tree recycling #2172
Brownfields #2153
Soil kitchen #2157
Haul it the right way #2151
Zero Waste content #2133
Batteries #2017

**Comment by annieszot** [comment]
See #2321

**Comment by annieszot** [comment]
@LauraTrujillo When you get back, any advice on where to look to get stats on justifying these info pages? Besides the content inventory? Maybe a quick walkthrough on Google Analytics? :)

**Comment by LauraTrujillo** [comment]
I'd suggest using research with residents, content inventory, and Google analytics to help justify these pages.
For analytics go to: https://analytics.google.com/analytics/web/#/report-home/a27761834w53193846p54026649
For page data:
- Behavior
- - Site content
- - - all pages
For PDFs:
- Events
- - Top events
- - - Downloads
- - - - PDFs

**Comment by annieszot** [comment]
Justification for (screenshots below; all analytics from 01/2018-01/2019): 
Street sweep #2192- 1894 unique page views 
Holiday tree recycling #2172 - 12,708 unique page views
Brownfields #2153 - 1192 unique page views 
Soil kitchen #2157 - 2342 unique page views 
Batteries #2017- 9183 unique page views 
@LauraTrujillo tagging you before I close. Take a gander at these numbers! Looks like we got a good batch of second round ARR content :)

**Comment by LauraTrujillo** [comment]
@annieszot 100%!
