### ISSUE TITLE
Joplin mobile preview message

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2354]
### As a CoA staff member who is editing content on Joplin, I want the "Loading" message to look professional so that I feel like I can trust the new authoring interface.

Make "Loading..." more professional (aka not funny caps)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/a4208d58-3130-4995-9e8b-0c6ddaf60046)

**Acceptance criteria**
- [x] Message says "Loading..." without funny caps and without the emoji (sorry)

**Comment by briaguya** [comment]
This is actually Janis.

**Comment by desigonz** [comment]
Assigning @chasechenevert to QA

**Comment by chasechenevert** [comment]
Where can I find this change, would it be in staging?

**Comment by desigonz** [comment]
@briaguya This is still happening in Joplin staging—where/how can we preview this?

**Comment by briaguya** [comment]
@desigonz this is fixed on staging now

**Comment by desigonz** [comment]
@briaguya Looks great on staging, ready to merge to prod!
