### ISSUE TITLE
Implement tile group

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#2356]
We **won't** use this style on `desktop` with: 
- top services 
- topic pages

We will use this on `desktop`: 
- topic collections

We will use this on `mobile` (everywhere): 
- topic pages
- topic collections
- top services

![Cards_responsive spec@2x@2x](https://user-images.githubusercontent.com/7027270/62474598-da645100-b768-11e9-8ae7-6d241fc119fe.png)

![Tile group@2x](https://user-images.githubusercontent.com/7027270/63378876-c0c22c80-c358-11e9-9a0f-2bc3b2503648.png)

------

Refer to design notes: https://github.com/cityofaustin/techstack/issues/2299

**Acceptance criteria**

Homepage  breakpoints:
- [x] > 1440 use regular tiles
- [x] 929 - 1440 use regular tiles
- [x] 768 - 929 use regular tiles
- [x] < 768 use compact tiles

Topic pages breakpoints:
- [x] > 1440 use regular tiles
- [x] 929 - 1440 use regular tiles
- [x] 768 - 929 use regular tiles
- [x] < 768 use compact tiles

Topic collection breakpoints:
- [x] > 1440 use compact tiles
- [x] 929 - 1440 use compact tiles
- [x] 768 - 929 use compact tiles
- [x] < 768 use compact tiles

Top services on department pages:
- [x] > 1440 use regular tiles
- [x] 929 - 1440 use regular tiles
- [x] 768 - 929 use regular tiles
- [x] < 768 use compact tiles

**Comment by chasechenevert** [comment]
So far:
![Cards_responsive spec@2x@2x](https://user-images.githubusercontent.com/7027270/62474598-da645100-b768-11e9-8ae7-6d241fc119fe.png)

**Comment by desigonz** [comment]
@desigonz to develop acceptance criteria

**Comment by desigonz** [comment]
- [ ] @chasechenevert to update master mock files (replace implemented tile with compact)
- [ ] then ready to go to dev

**Comment by chasechenevert** [comment]
I'm probably not understanding how we'll need to implement this, but the hope was that this could be as minor as changing margin and padding values depending on the breakpoint. What I heard yesterday during sprint planning sounded like it has bigger data model implications, is that right?

**Comment by briaguya** [comment]
@chasechenevert assigning you because I've got this pretty much done in a PR here: https://github.com/cityofaustin/janis/pull/498

I've screenshotted and linked a bunch of stuff there.

Leaving this as in-progress because I know I need to do a bit more testing around links working (I messed with that logic a bit), but I figure the sooner we get on the QA side of this the faster I'll be able to implement fixes/suggestions/changes.

**Comment by chasechenevert** [comment]
@briaguya woo! This is awesome! The only notes I have here are for the hover and active state to match the styling to the regular tile instance:

```
hover { 
background-color: #D9E8F6;
text-color: #0049c7;
}

active { 
background-color: #D9E8F6;
text-color: #0049c7;
}
```

**Comment by chasechenevert** [comment]
@briaguya and I connected directly about the above notes. Brian made changes to the CSS, and I made changes to the spec for parity and consistency. Good to go from me.

**Comment by desigonz** [comment]
Just went through QA and found one thing: the "learn more" is missing on topic collection pages. See screenshot.

**Acceptance criteria**
- [ ] "Learn more" appears on topic collection pages


(ignore the arrows)
![image](https://user-images.githubusercontent.com/5839508/64736371-1600e200-d4b0-11e9-9425-8895b7a1269a.png)
