### ISSUE TITLE
Feedback from product acceptance - design v2

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#236]
### Homepage
Welcomes residents to the site and encourages them to dive into topics that might help them meet their goals.
- [x] 'Welcome to' in Lora italic does not match mock-up

### Theme Page
Residents can use the theme page to discover groups of related services or products they need or are interested in.
- [x] missing edge-to-edge line break between header and beginning of page content, look to navigation on other page templates
- [x] remove line break below theme description
- [x] body inside tile group should be centered (this is confusing in mocks as it's shown both ways 😢)
- [x] when breaking from desktop and tablet to mobile, the arrow on the tile group header does not scale down

### Topic Page
Residents can locate all related services or products and navigate to the one they need or want.

### Navigation
Residents can move intuitively across alpha.austin.gov and still know where they are in the hierarchy.
- [x] 'English' in language bar should be highlighted when someone first arrives to the site showing them the active language
- [x] 'Alpha.austin.gov', airport link, and 311 link should align horizontally at center
- [x] After opening menu item 'Permits & Tickets', user is unable to close it. All other menu items will close.
- [x] On all page templates- when sizing screen down from desktop to tablet and mobile, the menu appears automatically/is open in the smaller screens.

### 311
Familiarizes residents with 311 as a customer service center and gives residents a quick pathway for requesting help or reporting problems.
- [x] In desktop, there should be 9 links showing (prioritized order), and the last link of the 9 should be "All 311 services" and link to  #http://311.austintexas.gov/reports/list_services
- [x] In tablet, there should be 6 links showing (prioritized order), and the last of the links should be "All 311 services" and link to http://311.austintexas.gov/reports/list_services
- [x] In mobile, there should be 4 links showing in prioritized order, and last link as above

### Service Page
Residents can use service pages to accomplish a goal and to discover related services.
- [x] remove share link from recollect app in all instances
- [x] days of week in contact module should be interactive- revealing current day only with drop-down option to see rest of days and hours

**Comment by ifsimicoded** [comment]
missing edge-to-edge line break between header and beginning of page content, look to navigation on other page templates --> addressed in https://github.com/cityofaustin/janis/pull/215

**Comment by ifsimicoded** [comment]
For 311 updates, @cthibaultatx do you think it's strange for users to see a different set of links depending on what device they're on?

**Comment by cthibaultatx** [comment]
@ifsimicoded not so long as the order is always the same

**Comment by ifsimicoded** [comment]
@cthibaultatx --> "remove line break below theme description"
### Do you mean on the theme page the dashed line?

![screen shot 2018-04-11 at 11 22 27 pm](https://user-images.githubusercontent.com/3039125/38656320-547b3dfa-3ddf-11e8-9152-45dae9dd4a18.png)

### Do you also want it removed from the Topic pages?

![screen shot 2018-04-11 at 11 22 53 pm](https://user-images.githubusercontent.com/3039125/38656325-5dd20d3e-3ddf-11e8-9f1f-c053125fba47.png)

These dashed lines are shown in the mocks, so I want to be sure we're talking about the same thing.

**Comment by ifsimicoded** [comment]
-  'Welcome to' in Lora italic does not match mock-up
- After opening menu item 'Permits & Tickets', user is unable to close it. All other menu items will close.
- when breaking from desktop and tablet to mobile, the arrow on the tile group header does not scale down
- 'English' in language bar should be highlighted when someone first arrives to the site showing them the active language
Addressed in PR
https://github.com/cityofaustin/janis/pull/217

On all page templates- when sizing screen down from desktop to tablet and mobile, the menu appears automatically/is open in the smaller screens.
Addressed in PR
https://github.com/cityofaustin/janis/pull/217

**Comment by cthibaultatx** [comment]
@ifsimicoded yes, please remove the dashed line just below the header and description on the theme templates only, *not topic*

**Comment by ifsimicoded** [comment]
"remove line break below theme description" handled in PR https://github.com/cityofaustin/janis/pull/221
