### ISSUE TITLE
Preview doesn't show contact information

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2362]
**Describe the bug**
Neither the mobile preview nor the preview page that opens in a new page is showing contact information.

**URL**
Live page: https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/recycling-reuse/pickup-free-paint/
Edit page in Joplin: https://joplin.herokuapp.com/admin/pages/12/edit/
Preview page: https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZTo3Nzg=

**To Reproduce**

1. Go to https://joplin.herokuapp.com/admin/pages/12/edit/
2. Look at the mobile preview and/or click "preview"
4. See error; compare with live page https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/recycling-reuse/pickup-free-paint/

**Current behavior**
No contact info appearing in mobile and full-page preview

**Expected behavior**
Since the live page shows contact info and we've entered contact info in Joplin, I expect to see the contact info in the mobile and full-page preview

**Screenshots**

Live page: ![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/8e236cf2-df6a-4395-8c62-0e0364e3dabb)
vs. preview link: ![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/71acfe99-396b-4884-bc05-7026c55547ab)
and mobile preview: ![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/e4934e12-4468-498b-80fa-39b9ddfbd5bb)

**Browser**
Chrome 73 on macOS (Mojave)

**Additional context**

**Comment by briaguya** [comment]
This appears to be happening due to a problem with how we're "cleaning" contacts with preview data. This PR (https://github.com/cityofaustin/janis/pull/448) fixes it for service pages, but we should test to make sure this works on all of our page types.

**Comment by briaguya** [comment]
This is part of a bigger issue with redundant code in our cleanData methods, I've created a techdebt issue to address it in a greater sense (https://github.com/cityofaustin/techstack/issues/2414)

**Comment by briaguya** [comment]
Working in prod now:
Dept page: https://alpha.austin.gov/en/preview/department/UGFnZVJldmlzaW9uTm9kZTo3MzU=
Info page: https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZTo2NTk=
Service page: https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZTo3ODM=

**Comment by desigonz** [comment]
@briaguya  Looks great!!
