### ISSUE TITLE
Spooky contact info on map block

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2363]
**Describe the bug**
On the [Pick up free paint](https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/recycling-reuse/pickup-free-paint/) page, the map block is pulling in contact info—even though we've just selected a location in Joplin for this block, not contact info. 

(You'll see there are two instances of contact info on this page—we expect to see the contact info at the bottom, but not under the map.)

**URL**
Edit page: https://joplin.herokuapp.com/admin/pages/12/edit/
Edit location: https://joplin.herokuapp.com/admin/snippets/base/location/1/ (you'll notice there's no contact info here!)
Live page: https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/recycling-reuse/pickup-free-paint/

**Screenshots**
![image](https://user-images.githubusercontent.com/5839508/59620119-af0e9f80-90f1-11e9-836e-e08f69c5a702.png)

**Device**

**Browser**

**Additional context**

**Comment by briaguya** [comment]
dev note: This is happening because we are using the [ContactMap](https://github.com/cityofaustin/janis/blob/master/src/components/Contact/ContactMap.js) component. It should be decently easy to just remove the contact info from this block, but we should make sure that doesn't break anything else

**Comment by briaguya** [comment]
@desigonz if you want to check this out in https://deploy-preview-451--janis.netlify.com/ that'd be cool!

**Comment by desigonz** [comment]
looks great!
