### ISSUE TITLE
Foster Prototype 0.2 Coordinate/schedule usability testing with Knowbility

### ISSUE THREAD

**Issue by juliazbyron** [cityofaustin/techstack#237]
We haven't gotten any people using screen readers from intercepts so we need to target recruiting  for them.

**Comment by cthibaultatx** [comment]
Julia connecting Celine to Martin who can help schedule sessions. 
Here are some details about the tests:
•    The tests would take 30-40 minutes
•    We would like to do three of them between April 10th-13th, preferably on Wednesday. 
•    We will travel to participants
•    Celine needs to make sure compensation is good to go with @atx-adam $25/session for 3 residents

**Comment by cthibaultatx** [comment]
Emailed Martin to try to set up a call for today or tomorrow

**Comment by juliazbyron** [comment]
Got the update from Celine and reached out to the person we were referred to this morning (Glenda). No word back yet.
