### ISSUE TITLE
Step option block icon overlaps helper text

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2371]
**Acceptance criteria**
- [ ] step option expand/collapse icons (+ and x) is below helper text, should appear just as the expand/collapse icon for "Add any maps..." section

**Describe the bug**
On service pages, the step options expand/collapse icons (+ and x) overlap with the helper text.

**URL**
example: http://joplin-staging.herokuapp.com/admin/pages/82/edit/

**To Reproduce**

1. Go to Joplin
2. Open a service page
3. Scroll down to "Write out the steps a resident needs to take to use the service"

**Current behavior**
x or + icon overlaps the step option box

**Expected behavior**
*A clear and concise description of what you expected to happen*

**Screenshots**
collapsed:
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/4a827888-d081-4f4f-a95e-260daa31a526)

expanded:
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/1c46adce-cf20-4ac6-8369-13bac6de868f)

**Device and browser**
Chrome 73 on macOS (Mojave)

**Additional context**

**Comment by briaguya** [comment]
Our Joplin css is wonky. The 3 is for a quick fix, we should really look into how to best build the Joplin UI we want instead of adding hacks on hacks on hacks.

**Comment by desigonz** [comment]
> Our Joplin css is wonky. The 3 is for a quick fix, we should really look into how to best build the Joplin UI we want instead of adding hacks on hacks on hacks.

Got it. Will deprioritize for now.

**Comment by desigonz** [comment]
Fixed with new streamfields
