### ISSUE TITLE
Janis design - multiple phone numbers for contacts

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2373]
### As a resident, I want to be able to see the multiple phone numbers available for a contact and be able to know what each number is for, so that I know which is the right number to call.

**Acceptance criteria**
- [ ] Both phone numbers appear on Janis
- [ ] *need mocks*

**Is your feature request related to a problem? Please describe.**
Some programs or services have multiple phone numbers associated with them (see, for example, [breastfeeding support](https://docs.google.com/document/d/1khKjxBj5J8bmHz4828VthHol5NgeujYUFXzqKGDOuoY/edit?usp=sharing)). We need the design in Janis to accommodate for multiple phone numbers.

**Additional context**
See also #2039, which focuses on Joplin implementation.

**Comment by chasechenevert** [comment]
## Visual design
- Debating whether we should bold the labels on phone numbers, but this should work for now.

<img width="793" alt="Screen Shot 2019-06-19 at 12 37 07 PM" src="https://user-images.githubusercontent.com/7027270/59787516-3fceb200-928f-11e9-86e6-5928e2139e31.png">

**Comment by desigonz** [comment]
thanks for the speedy mock @chasechenevert! I've added acceptance criteria to #2374 and I'm closing this one.
