### ISSUE TITLE
Decide on platform for style guide tab

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2380]
**Objective** 
Discuss what a longer-term solution for the style guide tab should be.

**Problem**
Gitbook.io does not allow us to use an iframe and embed into style guide tab. It appears to be a gitbook policy. 

**Background**
We moved the style guide from github.io to gitbook.io so that we could have multiple people who had edit and publish access (aka on the new free City account). But now that means we can't embed in Joplin preview. There is a feature request out for this functionality: https://gitbook.canny.io/feature-requests/p/embed-a-gitbook-into-an-app-or-website

@easherma on Slack: for instance, potentially instead of linking to a style guide as a seperate doc, why dont we define detailed help text for each part of the page _in_ joplin that we display on the side

**Participants**

**Agenda**

------
- [ ] Schedule meeting
- [ ] Meet
- [ ] Create resulting issues

**Comment by Jo-Dwyer** [comment]
@easherma how difficult is it to migrate style guide content between GitHub and GitBook? I want to know if it's worth beginning work on the guide content before we've settled on a single, long-term platform for the guide.

**Comment by desigonz** [comment]
We've discussed using Gitbooks as the source of truth for editing the style guide, which syncs to the Github repo that feeds the style guide tab. Closing this issue for now.
