### ISSUE TITLE
Gitbook Hackathon Sync

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2381]
**Objective** 
Figure out Gitbooks 
Slack link https://austininnovation.slack.com/archives/C5PHTQRPD/p1560970317059200

**Participants**

FYI @desigonz 
Assignees/Participants: @annieszot @LauraTrujillo @srigdon and @easherma 

**Agenda**
TBD 
------
- [ ] Schedule meeting
- [ ] Meet
- [ ] Create resulting issues

**Comment by desigonz** [comment]
Eric figured out the style guide stuff, yay! So closing this one.
