### ISSUE TITLE
Janis copy edits for hardcoded things

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2384]
**Acceptance criteria**
- [ ] change "&" to "and" in theme names
- [ ] all themes should be sentence case
- [ ] change "Check out City of Austin Services" to "Check out City of Austin services" (service lowercased)

**Comment by desigonz** [comment]
Edits made in [Janis PR #445](https://github.com/cityofaustin/janis/pull/445)

**Comment by desigonz** [comment]
Submitted a PR for these edits, but I couldn't figure out where to edit the theme names that are *within* the meganav. Compare "Housing and utilities"(correct) on blue background on the top versus "Housing & Utilities" (incorrect) on white background within meganav
https://deploy-preview-445--janis.netlify.com/

![image](https://user-images.githubusercontent.com/5839508/60054638-b65d1c80-96a0-11e9-959d-e2c5b2b8f266.png)
![image](https://user-images.githubusercontent.com/5839508/60054703-e1e00700-96a0-11e9-9caa-6c1c9ef67aed.png)

**Comment by briaguya** [comment]
So within the meganav we're actually using https://joplin.herokuapp.com/admin/snippets/base/theme/ to get the theme info. I've updated them in joplin.
