### ISSUE TITLE
Data model prototype

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2386]
Use Airtable/Google form? What other tools might work?

**Comment by srigdon** [comment]
- [ ] Review questions to OPO (so far) and email the doc to them. Also ask for a workshop time next week during which we'll go through all the states a complaint can be in and all of the possible outcomes. FYI @desigonz

**Comment by desigonz** [comment]
@srigdon If you'd like, when I send the OPO official doc mock (probably tomorrow), I can ask about scheduling a time for a workshop next week.

**Comment by desigonz** [comment]
Also @srigdon and @toribr: do y'all think we need to define user stories for objectives 2 and 3 further? Or do you feel confident about what we have?

Here's what came out of the first user story workshop: https://docs.google.com/document/d/1nE7RbKvhZrwBu7sOXUSyO826XP-qvI4wzaMErkSCIZo/edit?usp=sharing

We were focusing on objective 1 at that point, but I think many apply to objectives 2 and 3.

**Comment by toribr** [comment]
@desigonz If anything thing, I think that may over define. For MVP, anyway. It still does somewhat depend on what meta data we are able to capture and how it is abstracted.

**Comment by srigdon** [comment]
Moving this to Sprint 36 for now, as it's in the works. OPO is doing an internal workshop to identify all of the data types in all of the document types they want to publish, and then having legal review and sign off on using them. FYI @desigonz @toribr
