### ISSUE TITLE
Official document list page — Joplin interface wireframe

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2388]
### As a content editor, I want to choose which publish official documents to one page so that users can see all of one type of official document on a page. 

- [ ] Wireframe — how an author builds an official doc list page page ready to deliver to devs

See also #2389 and #2390

**Is your feature request related to a problem? Please describe.**
We want to display cases w/ disciplinary outcomes on one Janis page. 

**Describe the solution you'd like**
We're thinking of allowing a content editor to build a landing page of official docs rather than directly feed them in. This is because:
- our MVP content model for officials docs won't allow for tags or similar metadata to allow it to sort
- this way, OPO can also build a page for things like policy recommendations

MVP will _not_ include pagination, but eventually we'll need to add it

**Describe alternatives you've considered**
We could alternatively auto-populate via something like tags.

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by toribr** [comment]
MVP, where added entries work like steps (only with multiple fields). Because of this, check for issue on collapsing past entries, which would make the page more usable.
![#2387 Official doc list](https://user-images.githubusercontent.com/3790067/60987295-eb0ade00-a306-11e9-885d-cb7a013dc34e.png)
