### ISSUE TITLE
Content type/model: official document list page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2389]
### As a resident, I want to be to access all official documents of one type on a page.

See also #2388 (Joplin interface).

**Is your feature request related to a problem? Please describe.**
We want to display cases w/ disciplinary outcomes on one Janis page. 

**Describe the solution you'd like**
We're thinking of allowing a content editor to build a landing page of official docs rather than directly feed them in. This is because:
- our MVP content model for officials docs won't allow for tags or similar metadata to allow it to sort
- this way, OPO can also build a page for things like policy recommendations

Does this page need a description field at the top? Does it need the ability to add some contextual information?

**Comment by srigdon** [comment]
Draft version complete, will write a more complete version next sprint.
