### ISSUE TITLE
Official document list page — Janis mocks

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2390]
### As a resident, I want to be to access all official documents of one type on a page.

**Acceptance criteria**
- [ ] mock for the Janis display of aggregate official documents for OPO cases with disciplinary outcomes

See also #2388 (Joplin interface) and #2389.

**Is your feature request related to a problem? Please describe.**
We want to display cases w/ disciplinary outcomes on one Janis page. 

**Describe the solution you'd like**
We're thinking of allowing a content editor to build a landing page of official docs rather than directly feed them in. This is because:
- our MVP content model for officials docs won't allow for tags or similar metadata to allow it to sort
- this way, OPO can also build a page for things like policy recommendations

Does this page need a description field at the top? Does it need the ability to add some contextual information?

Pagination is out of scope for MVP

**Comment by toribr** [comment]
Examples here: https://docs.google.com/document/d/1-sZ61G5nuUCtuZfKb5io2KBOMuvUt9ABUUSbzsLF5tM/edit#

**Comment by chasechenevert** [comment]
# Janis Visual Design draft 1
### Option 1
- All metadata is clustered below the summary
- Depending on what information the user is scanning for, the distance of the metadata from the document title could make scanning more difficult, despite the information being grouped
![Official Document content type – 4@2x](https://user-images.githubusercontent.com/7027270/60356833-ae9ac200-9997-11e9-861c-9d816e521176.png)

### Option 2
- Distributing the metadata with the author label below the heading
- This example does not show the document type. This is an opportunity to ask what information needs to be presented to the user
![Official Document content type – 3@2x](https://user-images.githubusercontent.com/7027270/60356855-b8242a00-9997-11e9-803c-e897bc23903f.png)

### Option 3
- This example is modeled off of CFPB's search listing 
- Depending on what the user is looking for, this more distributed approach could help scanning by placing key metadata above the document title (in this case: document type and publish date, but it could be any meta data). 
- This example excludes "document type:" label
![Official Document content type – 2@2x](https://user-images.githubusercontent.com/7027270/60356866-bf4b3800-9997-11e9-8596-2e3dccaac7bc.png)
