### ISSUE TITLE
Send for approval (APH health equity, environmental health, & epidemiology P1 content)

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2392]
Once all of the Health Equity (epic: #), Environmental Health (epic: #), and Epidemiology (epic: #) content has been drafted and undergone Alpha team revisions, 
- [ ] Gather up all of the content relevant to this division
- [ ] Send batch content to APH contacts for approval (via Sharepoint)

**Comment by desigonz** [comment]
@LauraTrujillo Done, correct?

**Comment by LauraTrujillo** [comment]
@desigonz I'm pretty sure yes, but let me just go through and make sure. I'll close this issue when I'm done.
