### ISSUE TITLE
Find out what's causing issues in the translator <> Content Team workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#240]
The translations we are getting look like they are being translated without the context of the page. It might be that they are disregarding the mocks and just copy-pasting text into their word docs for translation.

**Comment by ashleecoa** [comment]
@cthibaultatx @amenity Was the plan to pull out our specific examples from this during the synthesis? Like I know of "Steps" and "Stairs" 

And then setting up a meeting with them?

**Comment by cthibaultatx** [comment]
Yes @ashleecoa that's the best approach. awe could set up time to connect with them next week once we've evaluated test data.

**Comment by ashleecoa** [comment]
Review the workflow and dev items https://docs.google.com/document/d/1kLn7QK3kqMtj6sVGPvf0GhVvugswbLbgO_EGcYERhFw/edit?usp=sharing

- [ ]  @benweatherman 

- [ ]  @ifsimicoded 

- [ ] @mateoclarke

**Comment by ifsimicoded** [comment]
@ashleecoa I added the workflow for static content -- and it definitely needs to be improved upon. The current method is definitely not scale-able and prone to errors.
