### ISSUE TITLE
Architect OPO department page w/ official documents

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2404]
MVP for the new official documents—how a user navigates from department page to official documents.

**Comment by chasechenevert** [comment]
## MVP changes (no visual design tweaks)
- [ ] Add "Official Documents" to "Related content" ul

<img width="1290" alt="Screen Shot 2019-07-08 at 12 24 40 PM" src="https://user-images.githubusercontent.com/7027270/60830322-8cb1f400-a17c-11e9-82d3-55da2a321469.png">

## Visual design changes for Related content
XD Spec: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/9055635c-de21-497d-b8fb-631c3e39c802/Department-MVP-Desktop/
- [ ] Remove background color
- [ ] Bottom border: `2px`, `#F0F0F0`, width of body content (not 100%)
- [ ] Remove bullets, link text flush left with "Related content" section label
- [ ] Link text to H4

<img width="1299" alt="Screen Shot 2019-07-08 at 12 24 53 PM" src="https://user-images.githubusercontent.com/7027270/60830350-9cc9d380-a17c-11e9-9496-3e9abc820224.png">
