### ISSUE TITLE
Tab focus for "official website" menu

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2407]
**Describe the bug**
When using just a keyboard to navigate alpha.austin.gov, I can't focus on the "An official website of the City of Austin" and therefore can't open/access the content there.

**URL**
https://alpha.austin.gov/

**To Reproduce**

1. Go to https://alpha.austin.gov/
2. Use the tab key to go through the interactive elements on a page

**Current behavior**
Focus goes from "Skip to main content" to "English," never lets me choose "An official website of the City of Austin"

**Expected behavior**
Focus goes from "Skip to main content" to "An official website of the City of Austin" and then continues to English

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by briaguya** [comment]
After getting a bit of a start on this it looks like it might get a little wonky, put a 3 on it.

**Comment by chiaberry** [comment]
@desigonz ready to be QA'd here: https://deploy-preview-571--janis.netlify.com

**Comment by desigonz** [comment]
Looks great, QA complete! No need to QA in staging, just dev test.
