### ISSUE TITLE
OPO updated copy for anonymous vs. identified complaint

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2409]
### As an OPO complaint form user, I want to know what information OPO will need from me to be able to give me details about my case when I call to follow-up in the future, so that I am able to weigh whether I submit my complaint anonymously or not.

In order for OPO to be able to tell a complainant the status of the case and more particular details about the investigations, OPO needs the following information from a user:
- [ ] First name
- [ ] Last name
- [ ] Phone number
- [ ] The user needs to be able to identify *some* part of their complaint (for example, when it happened, officer description, etc)

Users who submit complaints anonymously can only learn if a case is open or closed—no other information.

We need to update copy on the [Tell us about you](https://forms.austintexas.io/police-complain/about-you) and [confirmation](https://forms.austintexas.io/police-complain/confirmation) pages. The message should:
- [ ] on [Tell us about you](https://forms.austintexas.io/police-complain/about-you), let a user know that by choosing to not share contact information, they're making a decision to opt out of being able to learn details about the case
  - [ ] similar copy on intro page to set expectations?
- [ ] On the [confirmation](https://forms.austintexas.io/police-complain/confirmation) page, set an accurate expectations of what an anonymous user can learn by following up
  - [ ] do we want to add similar copy on the confirmation email?

Do we also remove the confirmation number for anonymous users?

**Comment by srigdon** [comment]
Proposed changes: 

- [ ] Create a service page that acts as the landing page for the complaint form and succinctly explains who the OPO is, how the complaint process works, and the process for submitting a complaint anonymously vs giving your contact information. 

- Edit the following pages of the form: 
- [ ] Page 1/front page/introduction 
- [ ] Tell us about you 
- [ ] Confirmation

- [ ] Edit the confirmation email copy

**Comment by desigonz** [comment]
Sent proposed copy to OPO; closing this issue.
