### ISSUE TITLE
Joplin - Refactor previews to not need a janis build

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#2415]
At the moment, our previews for Joplin are made in Janis. This is causing some issues with managing complexity in Janis (https://github.com/cityofaustin/techstack/issues/2414) as well as issues with maintaining multiple Joplin environments such as PR apps (https://github.com/cityofaustin/techstack/issues/2296).

It'd be great to be able to make some Django templates for previews that import our Janis components and manage the data that way instead.

**Comment by desigonz** [comment]
Let's redo this when we redo data model.

**Comment by Niicck** [comment]
Replaced by https://github.com/cityofaustin/techstack/issues/2296
