### ISSUE TITLE
Approve new copy and flow for OPO anonymous complaint

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2421]
We'll need Mia to sign off on the new flow and copy.

**Comment by toribr** [comment]
Included updated changes from Sara and sprint review

![6 1 Demo](https://user-images.githubusercontent.com/3790067/61077213-8c676200-a3e3-11e9-9a48-1b8145b58f0b.png)
![6 2 Follow UP](https://user-images.githubusercontent.com/3790067/61077214-8cfff880-a3e3-11e9-8834-152934626fdd.png)
![6 2 1 Follow UP](https://user-images.githubusercontent.com/3790067/61077215-8cfff880-a3e3-11e9-9633-3a0e2172954d.png)
![6 3 Review](https://user-images.githubusercontent.com/3790067/61077216-8cfff880-a3e3-11e9-82de-7bb220b3dc46.png)
![6 4 Universal confirmation](https://user-images.githubusercontent.com/3790067/61077217-8cfff880-a3e3-11e9-8cbe-2e1377bced36.png)
