### ISSUE TITLE
URL and title conventions for simple forms

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2422]
We will be implementing two simple forms (#2498 and #2499) using USFS. After that, we'll likely be moving simple form creation to Joplin.

- [x] What should the URL conventions be for these two simple forms? (For OPO, we're using https://forms.austintexas.io/police-complain/)
- [x] What title conventions should we use for forms: Verb/service-oriented language ("File a complaint", "Request a day laborer," "Request a composting class"?) 
- [x] We should probably document this somewhere—maybe the style guide? Discuss! (And then we'll create an issue to do it.)

![image](https://user-images.githubusercontent.com/5839508/60777938-73686380-a0fa-11e9-9537-390301de9fee.png)

**Comment by LauraTrujillo** [comment]
Per content pin-up: Request-day-labor and request-compost-class

**Comment by srigdon** [comment]
Documented in the [URL standards doc](https://docs.google.com/document/d/1pI2vdbAC4gpupVU02GLo6qGr6nsEJGuEORnVHJqs6JM/edit#heading=h.7o0rznke1lox).  

Created #2563 so's I don't forget to update the style guide.
