### ISSUE TITLE
Blast the QA engineer job post

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2426]
Job description link: https://odd.austintexas.io/join/positions/Full-Stack-Developer/

- [ ] various agile meetup groups
- [x] Women Who Code Austin
- [x] Austin Digital Jobs fb group
- [ ] PiLadies
- [x] Lesbians Who Tech
- [ ] Built in Austin
- [x] Data for Democracy
- [x] Women in Tech
- [x] Ladies Get Paid
- [x] HexagonUX Houston
- [x] Coding Club
- [x] Open Austin
- [x] Civic Union
- [x] Tech Lady Mafia
- [x] Austin Automation Professionals meetup
- [x] Austin Software QA testing meetup
- [x] Austin Quality Software Dev meetup

other places: https://airtable.com/tblFaebgRgET7jvsQ/viwiVpluCBTbunxpL?blocks=hide

**Comment by srigdon** [comment]
- [ ] Code for America's #jobs-for-america channel
