### ISSUE TITLE
Blast fullstack dev job post

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2427]
- [ ] various agile meetup groups
- [x] Women Who Code Austin
- [x] Austin Digital Jobs fb group
- [x] PyLadies
- [x] Lesbians Who Tech
- [ ] Built in Austin
- [x] Data for Democracy
- [x] Women in Tech
- [x] Ladies Get Paid
- [x] HexagonUX Houston
- [x] Coding Club
- [x] Open Austin
- [x] Civic Union
- [x] Tech Lady Mafia
- [x] Austin Hispanic Hackers meetup
- [x] Feminist Hack ATX

other places: https://airtable.com/tblFaebgRgET7jvsQ/viwiVpluCBTbunxpL?blocks=hide

**Comment by srigdon** [comment]
- [ ] Code for America's #jobs-for-america channel

**Comment by srigdon** [comment]
Built in Austin charges per job listing.

**Comment by desigonz** [comment]
thanks @srigdon! closing this one and considering it blasted.
