### ISSUE TITLE
Revise chicken rebate service page 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2432]
Draft: https://docs.google.com/document/d/1f1_59RZuqkA28bK6a_iYvSTEuV11ou2ZLVbcHEaO_KE/edit

**Comment by annieszot** [comment]
- [ ] Editors assigned (round 1)
- [ ] Feedback received, incorporated
- [ ] Editors assigned final round

**Comment by annieszot** [comment]
Assigning @desigonz rd 1 edits. Requesting edits by Wednesday, July 10.

**Comment by desigonz** [comment]
Comments added! 🥚🐣🐥🐔🐓🍗

**Comment by annieszot** [comment]
Thanks @desigonz ! Assigning @LauraTrujillo for final round review. Requesting edits by Wednesday, July 10. Will document content debt within doc by this evening.

**Comment by LauraTrujillo** [comment]
good to go, @annieszot!

**Comment by annieszot** [comment]
Thanks @LauraTrujillo ! Closing
