### ISSUE TITLE
Mock of OPO official document list page with wrapper

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2437]
- [ ] comp showing the entire official document listing page, showing 3-5 instances of memos with wrapper

**Comment by chasechenevert** [comment]
I've added this to the XD Janis dev spec: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/9055635c-de21-497d-b8fb-631c3e39c802/Department-MVP-Desktop/
