### ISSUE TITLE
Revise zero waste business rebate service page

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2439]
Draft: https://docs.google.com/document/d/1Kqy96_JaXfBS6XLlh0PjJth8Un3B5NWjrXhmz1tsPds/edit

**Comment by annieszot** [comment]
- [ ] Editors assigned (round 1)
- [ ] Feedback received, incorporated
- [ ] Editors assigned final round

**Comment by annieszot** [comment]
Assigning @srigdon Requesting edits by Wednesday, July 10

**Comment by srigdon** [comment]
Drafted reviewed, lookin' good! Put a question in there about content debt, let me know what you think.

**Comment by srigdon** [comment]
@annieszot Reviewed, lookin' good. Sending to @LauraTrujillo for next review.

**Comment by annieszot** [comment]
Awesome! Thanks @srigdon !

**Comment by LauraTrujillo** [comment]
reviewed with comments and a suggestion or two.

**Comment by annieszot** [comment]
Thank you! Comments assessed, suggestions incorporated and closing.
