### ISSUE TITLE
Refactor data cleaning to share and execute where data is fetched not in React components

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#244]
Move data transformations from React Components to where data is fetched.
impacts all page components, navigation components
share code between cleaning functions where possible

https://github.com/cityofaustin/janis/pull/205/files/8abb4d90240853d44dd0642674a9e9f571d8fabe#r178574619

**Comment by ifsimicoded** [comment]
Completed in Sprint 6 via https://github.com/cityofaustin/janis/pull/239 and https://github.com/cityofaustin/janis/pull/242
