### ISSUE TITLE
Revise dead animal pick-up service page 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2451]
Draft: https://docs.google.com/document/d/1hCpK5XLs9XldNomztCXRZMcO9rtNIjjQkz11KAgPREo/edit

**Comment by annieszot** [comment]
- [ ] Editors assigned (round 1)
- [ ] Feedback received, incorporated
- [ ] Editors assigned final round

**Comment by annieszot** [comment]
Assigning @desigonz for rd 1 review. Requesting edits by Wednesday, July 10.

**Comment by desigonz** [comment]
Nice work! Added comments and edits to the doc!

**Comment by annieszot** [comment]
Fantastic edits @desigonz ! So much cleaner! Assigning @LauraTrujillo for final round. Requesting edits by Wednesday, July 10.

**Comment by LauraTrujillo** [comment]
Awesome, @annieszot. Made some suggestions and comments.

**Comment by annieszot** [comment]
Thanks @LauraTrujillo ! Made not in "approval" issue to resolve comments. Closing
