### ISSUE TITLE
Revise home composting rebate service page 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2457]
- [x] Editors assigned (round 1)
- [x] Feedback received, incorporated
- [x] Editors assigned final round

**Comment by annieszot** [comment]
Draft: https://docs.google.com/document/d/1-MGHNqCIh4HnjhU3qSJt_lLk08GxoUsX93Z_QDWFBnY/edit

**Comment by annieszot** [comment]
Assigning @desigonz for rd 1 review. Edits requested by Wednesday, July 10.

**Comment by desigonz** [comment]
@annieszot Looking good! Adding comments and edits to the doc.

**Comment by annieszot** [comment]
Thanks @desigonz ! Assigning @LauraTrujillo for final round. Requesting edits by Wednesday, July 10.

**Comment by LauraTrujillo** [comment]
@annieszot reviewed with suggestions. Great work!

**Comment by annieszot** [comment]
Thanks @LauraTrujillo ! Closing
