### ISSUE TITLE
Departments vs. topic/topic collection page heading weight

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2464]
The H1 headings for the "Departments" listing page vs. topic collection pages are displaying at different font-weights.
- [Departments](https://alpha.austin.gov/en/departments/) is `font-weight=600`
- Topic and topic collection pages, such as [Recycling, trash, and compost](https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/) is `font-weight=500`

@chasechenevert Can you clarify which is correct?

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/5847e883-6519-4b35-b81d-b24cd20f5603)

**Comment by chasechenevert** [comment]
In the spec I've got all page titles at `font-weight=500` (medium weight)

**Comment by desigonz** [comment]
Thanks @chasechenevert—I've updated the accepted criteria and reassigned to dev team.
