### ISSUE TITLE
Service pages "step with options" style questions

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2465]
[Get a birth or death certificate](https://alpha.austin.gov/en/health-safety/health-records-certificates-2/birth-death-certificates/birth-and-death-certificates-test) service page uses the step-with-options feature, and it's brought up some design and editorial style questions for steps with options:
- Should the copy preceding the options be unbolded, to match the other (non-option) steps? (cc @chasechenevert)
- Should the sentence before the accordions end in a period, to match the other (non-option) steps? (cc @LauraTrujillo @srigdon)

Comment here with your thoughts and I'll create issues as needed!

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/45362958-e007-4735-951d-576a84491673)

**Comment by chasechenevert** [comment]
Ideally we would allow for heading styles here, which we don't currently. Back when Steps were designed and implemented we only allowed one heading value in Joplin -- I'm not sure if it was a decision to not allow headings for Steps or an oversight but it would be great to have them I think.

<img width="1203" alt="Screen Shot 2019-07-03 at 11 27 09 AM" src="https://user-images.githubusercontent.com/7027270/60608680-a4a50480-9d85-11e9-9dfd-20a8874b1db6.png">

Went ahead and mocked up what that would look with H2 headings. 
<img width="521" alt="Screen Shot 2019-07-03 at 11 31 37 AM" src="https://user-images.githubusercontent.com/7027270/60608921-24cb6a00-9d86-11e9-9db8-f3e7c54ac03e.png">

**Comment by srigdon** [comment]
@LauraTrujillo @desigonz Any imperative statement should end in a period, yes. Unless it's a particularly urgent or important imperative, then maybe an exclamation point. What do you think?

**Comment by desigonz** [comment]
@srigdon  Great, let's use periods! (Or exclamations or question marks, when needed.)

Also, @LauraTrujillo and @srigdon , can y'all review @chasechenevert's design above that all steps would include a bolded first sentence (that's actually a heading)? I'm not sure we've been writing service page steps with this in mind. Some considerations:
- We'd have to separate the first sentence out as a heading separate from the rest of the text within that step. For example, in step 1 of [bulk item collection](https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup), *Use the “What do I do with” tool below to see what bulk items can be picked up.* would be a heading and then we'd need a line break before *Bulk items are items that are too large for your trash cart, such as appliances, furniture, and carpet.*
- In [get free paint](https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/recycling-reuse/pickup-free-paint), all of the step text would be headings, I guess?
- we hyperlink in #3 on the [get immunizations page](https://alpha.austin.gov/en/health-safety/healthcare-prevention/disease-prevention/get-immunized). Would we hyperlink in a heading? 
- Also, if these are heading, then I don't know how I feel about a heading ending in a semicolon...she steps 1 and 2 in the screenshot above.

@chasechenevert  Is the heading design something we could move to post-MVP?

**Comment by LauraTrujillo** [comment]
@desigonz excellent points. I'm on board for making the first sentence into a heading and hyperlinking if necessary.
I'm also not sure about the semicolon. Let's have them end in a period.

**Comment by desigonz** [comment]
- [ ] @desigonz to synthesize conversations we've had about this and create acceptance criteria for dev.

**Comment by desigonz** [comment]
Acceptance criteria logged in #2662. Will review at a future design/dev sync!
