### ISSUE TITLE
"Create new content" modal icons

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2467]
### As a content editor, I want consistency icon-wise on the "create new content" modal so that I can trust the authoring interface I'm using.

**Is your feature request related to a problem? Please describe.**
Some of the content types that you can create via the "create new content" modal have representative icons; others don't. 

To get to the modal, go to https://joplin.herokuapp.com/admin/pages/3/ and click the "create new content" button.

Note: per #2466 we'll be removing "process pages," but we will need a solution for guides.

**Describe the solution you'd like**
Let's either get rid of icons all together, or select icons that are meaningful (and consistent with other Joplin icons per #2267). 

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/5839508/60468760-4a3e6380-9c20-11e9-9ccf-b4474d588367.png)

**Comment by toribr** [comment]
First round:
![dept_page_s](https://user-images.githubusercontent.com/3790067/61160154-1ab31500-a4c4-11e9-88d4-279125e236a3.png)
![dept_page](https://user-images.githubusercontent.com/3790067/61160155-1ab31500-a4c4-11e9-887f-a226cb4b4e4d.png)
![guide_page_s](https://user-images.githubusercontent.com/3790067/61160156-1b4bab80-a4c4-11e9-8de0-b317b0f7cf10.png)
![guide_page](https://user-images.githubusercontent.com/3790067/61160157-1b4bab80-a4c4-11e9-9eb5-01285b740a8b.png)
![info_page_s](https://user-images.githubusercontent.com/3790067/61160158-1b4bab80-a4c4-11e9-8622-9a6d4b95961f.png)
![info_page](https://user-images.githubusercontent.com/3790067/61160159-1b4bab80-a4c4-11e9-81c5-0ec20727e10c.png)
![official_doc_s](https://user-images.githubusercontent.com/3790067/61160160-1b4bab80-a4c4-11e9-9f39-380de58c4c9d.png)
![official_doc](https://user-images.githubusercontent.com/3790067/61160161-1b4bab80-a4c4-11e9-9e54-30ff279d16b4.png)
![service_page_s](https://user-images.githubusercontent.com/3790067/61160162-1b4bab80-a4c4-11e9-8d04-6010458f4d28.png)
![service_page](https://user-images.githubusercontent.com/3790067/61160163-1b4bab80-a4c4-11e9-8bbe-11e879ef3667.png)
![simple_form_s](https://user-images.githubusercontent.com/3790067/61160164-1be44200-a4c4-11e9-978f-f6bc571cb5ef.png)
![simple_form](https://user-images.githubusercontent.com/3790067/61160165-1be44200-a4c4-11e9-99e5-3b10f30c3f88.png)

**Comment by toribr** [comment]
Dept
![dept_page_s](https://user-images.githubusercontent.com/3790067/61160317-a036c500-a4c4-11e9-9105-d1659b84826e.png)
![dept_page](https://user-images.githubusercontent.com/3790067/61160318-a0cf5b80-a4c4-11e9-9a61-60b14f8e4d3d.png)

Guide
![guide_page_s](https://user-images.githubusercontent.com/3790067/61160332-a9279680-a4c4-11e9-9df9-6d4424b143a3.png)
![guide_page](https://user-images.githubusercontent.com/3790067/61160333-a9279680-a4c4-11e9-8672-e2ccd35d29a7.png)

info
![info_page_s](https://user-images.githubusercontent.com/3790067/61160337-b17fd180-a4c4-11e9-81b6-817545e69969.png)
![info_page](https://user-images.githubusercontent.com/3790067/61160338-b17fd180-a4c4-11e9-937d-7f0309df0b8d.png)

official doc
![official_doc_s](https://user-images.githubusercontent.com/3790067/61160348-bba1d000-a4c4-11e9-995b-9bf33d110c2e.png)
![official_doc](https://user-images.githubusercontent.com/3790067/61160350-bc3a6680-a4c4-11e9-8f8e-e93a13e5867f.png)

service 





![service_page_s](https://user-images.githubusercontent.com/3790067/61160368-d2e0bd80-a4c4-11e9-94f0-0ccc219281b3.png)
![service_page](https://user-images.githubusercontent.com/3790067/61160369-d2e0bd80-a4c4-11e9-9b6c-b9f3cbf1df80.png)

simple form
![simple_form_s](https://user-images.githubusercontent.com/3790067/61160380-dd9b5280-a4c4-11e9-9238-b434a063090b.png)
![simple_form](https://user-images.githubusercontent.com/3790067/61160381-de33e900-a4c4-11e9-93f2-0fef3185f748.png)

**Comment by toribr** [comment]
Note that these icons should be used within the content creation flow (forthcoming) and in the style guide as well.

**Comment by easherma** [comment]
@toribr will we have icons for topics & topic collections or are we potentially removing those from the modal?

**Comment by toribr** [comment]
Good question - I'm not sure yet. I'd like to position topic and TCs differently (not as pages, per se), which does mean removing them, but at the same time need to determine how they are managed and that part is a bit trickier, as it has ramifications into other aspects.

**Comment by toribr** [comment]
I'm not sure what's happening with topics and topic collections insofar as moving them out of the create modal, but in the short term if we aren't doing that, here's an intermediate solution. 

![content types](https://user-images.githubusercontent.com/3790067/62247257-15eace00-b3ab-11e9-9550-4bdf5620a9b5.png)
![content types_landing](https://user-images.githubusercontent.com/3790067/62247258-16836480-b3ab-11e9-983b-a5b24b0222b0.png)

**Comment by toribr** [comment]
@srigdon This is related to #2610 - the descriptions on the above screens should be reviewed and synced with that issue.

**Comment by LauraTrujillo** [comment]
@toribr I'm unassigning myself here. The content model doc has been updated (and #2610 is ready for you). I'll let you decided when to close this one and 2610.

**Comment by desigonz** [comment]
Thanks @LauraTrujillo! @toribr, Laura's descriptions can be found on the first sheet of the content model doc.

**Comment by toribr** [comment]
![select topic](https://user-images.githubusercontent.com/3790067/62569128-e711a380-b853-11e9-9eb7-af7ede261466.png)
![Select content type](https://user-images.githubusercontent.com/3790067/62569130-e711a380-b853-11e9-8619-9ffc17469179.png)

Updated.

**Comment by desigonz** [comment]
Great! Made this into acceptance criteria here: https://github.com/cityofaustin/techstack/issues/2692
