### ISSUE TITLE
Review copy and flow for "create new content" modal

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2468]
### As a content editor using Joplin, I want the "create a page" modal to match our content strategy and editorial style, so that I can independently make a page that is consistent with austin.gov content standards.

**Is your feature request related to a problem? Please describe.**
We've made a lot of content decisions about various page types that aren't reflected in the "create new content" modal.

To get to the modal, go to https://joplin.herokuapp.com/admin/pages/3/ and click the "create new content" button.

Some things to look for:
- [x] Can we add slightly more descriptive text to help a user decide when to use a page? (Ex: Information page is described as "a page with information." See [content model](https://docs.google.com/spreadsheets/d/1ZkH93F4tJ0_Zjx4t8k6k6TgwSlOh8u8ejWmegE6WqH0/edit#gid=1131885431)
- [x] When do you need "back" and "close" buttons in the modals? "Back" button makes sense if you click the wrong page type. We can click outside of the page type selection if the author decides not to create a page, but including a "close" button allows them to get out of the flow without having to delete a page they didn't want to create at that point, or having to click "back" and then click out of the page selection modal.
- [x] Need to write copy for the title modal for basically all page types except service pages (see screenshot—we're currently using service page language for things like topic collections, eek!)
- [x] Include guidelines for information page titling (subject keywords—not verbs like an info page)
- [x] Copy edit to match our editorial style guide (for example, use sentence case for everything, not headline case!) (@desigonz can up update the hardcoded content here?)
- [ ] [What else am I missing? Add here]

*NOTE:* Topic and topic collections might be covered by new UX flows per #2223 

![image](https://user-images.githubusercontent.com/5839508/60470514-4ad9f880-9c26-11e9-9fa7-82809b461edf.png)

**Describe the solution you'd like**
Someone on the content team should review the modals for: 
- [x] Service pages
- [x] Information pages
- [x] Department pages
- [x] Guides 

These will later need to go to design.

**Describe alternatives you've considered**
*A clear and concise description of any alternative solutions or features you've considered.*

**Additional context**
*Add any other context or screenshots about the feature request here.*

**Comment by desigonz** [comment]
Found some relevant issues:
#619
#745

**Comment by toribr** [comment]
![Select content type a](https://user-images.githubusercontent.com/3790067/61330870-3b41de80-a7e6-11e9-9708-39eb71b48a45.png)

**Comment by LauraTrujillo** [comment]
Unassigned myself. @desigonz There's a comment for you up at the top.

**Comment by desigonz** [comment]
@LauraTrujillo It's hardcoded but not sure if I'll be able to update it. If there are copy edits beyond what you wrote for #2610, can you add below, and then I'll work with dev to implement them?

**Comment by LauraTrujillo** [comment]
@desigonz sure can!
- Select content type modal
- Make everything sentence case
- [ ] Select the content type
- [ ] Service page
- [ ] Information page
- [ ] Department page
- [ ] Topic page
- [ ] Topic collection pages
- Topic collection or theme modal
- Make everything sentence case:
- [ ] Topic collection or theme?
- [ ] Topic collection

**Comment by toribr** [comment]
Approved updates! 
https://xd.adobe.com/spec/6728765d-1f27-4732-4e6d-b3d6726ca4ec-1119/

![Basic form](https://user-images.githubusercontent.com/3790067/62568616-3e634400-b853-11e9-8717-08264a91e9a2.png)
![Dept modal](https://user-images.githubusercontent.com/3790067/62568618-3efbda80-b853-11e9-851a-157adb6e5871.png)
![Uploading Guide modal.png…]()
![Uploading Information modal.png…]()
![Uploading Official document.png…]()
![Uploading Service modal.png…]()

**Comment by desigonz** [comment]
Incorporated into acceptance criteria in #2692
