### ISSUE TITLE
Topic name not appearing in preview

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2473]
**Describe the bug**
When you add a topic to a page in Joplin and then preview the page, the topic collection on the Janis preview appears as "Sample text" rather than the topic name.

**Acceptance criteria**
- [ ] When a user previews a page they are editing, the topic name appears in the preview
- [ ] If no topic is selected, nothing appears in the preview

**URL**
Joplin

**To reproduce**

1. Go to Joplin
2. Choose a service or information page to edit
3. Select a topic
4. Click "preview"

**Current behavior**
Preview opens in new window; "Sample text" appears where topic name should be. "Sample text" also appears in mobile preview.

**Expected behavior**
Preview opens in new window; topic name appears at top of page. Topic name should also appear in mobile preview.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/7ecf9379-4b5c-46c0-bbde-0e6bced31ab1)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/af92663f-4575-4197-b7e2-56ae4cd47e53)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/6980912d-75ba-4294-bf6f-03cc959a1364)

**Comment by briaguya** [comment]
@desigonz I have this working in my guide previews PR app: https://deploy-preview-553--janis.netlify.com/en/preview/guide/UGFnZVJldmlzaW9uTm9kZToxNjgw

I figure the QA checklist for this is something like:
- [ ] Make sure it looks ok in above link
- [ ] once on staging: test preview for service, info, guide, and official document pages (topic pages haven't been included, that can be addressed with https://github.com/cityofaustin/techstack/issues/3066, department pages don't apply)
- [ ] merge to prod and enjoy previews!

**Comment by desigonz** [comment]
Hey @briaguya, this looks great. PR app QA complete.

**Comment by briaguya** [comment]
@desigonz this is live on staging
