### ISSUE TITLE
Copy edit footer

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2474]
We've got some inconsistent capitalization in our footer. 
- [x] Should "project site" be lowercased?
- [x] The URLs: ".gov", right, not ".Gov"? And should we capitalize "Alpha" and "Austintexas" in the URLs, or lowercase? 
- [x] Once a decision is made on URL capitalization conventions, add to the style guide.

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/e916ee2c-b717-4fdc-8c65-fb730d2ea3ad)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/71e26f71-0dee-4837-aac4-65b5bcbdae14)

**Comment by LauraTrujillo** [comment]
@desigonz 
Yes, "Project site" should be lowercase. That is a sentence and capitalization should reflect that :)
URLs should also be lowercase, unless they start the sentence. In this instance, Alpha is capitalized, but "Austintexas" is not.
Is this hard coded on the site or something I can change?

**Comment by desigonz** [comment]
It's hardcoded—assigning to myself to develop acceptance criteria for dev

**Comment by desigonz** [comment]
Made issue #2634 for dev team. Closing this!
