### ISSUE TITLE
Austin.gov Mission & Vision

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#248]
We need to solidify a mission and vision to guide our tech stack work!
[Here is our working document](https://docs.google.com/document/d/1xEmINTKwojw0frTjGt9vHE1g5fQBLakui0dqpbg6Ufg/edit?ts=5aba8bc2#).

**Comment by courtneyjacinic** [comment]
@wilhitem 
@amenity and I reworked the mission a bit to make it better support the mission stated in the document sent day before last by @benguhin . We are holding on the Vision until we know what the vision of Government That Works, so we can make sure our vision supports that of our parent. @wilhitem, could you provide these when you have them/or let us know where to find them?

Thank you!!

**Comment by amenity** [comment]
Austintexas.gov Mission:

_Make the City of Austin’s services easily and equitably accessible to residents through digital solutions that adapt and grow according to their needs. _
✨📱💻👭👭👭💻📱✨

As Courtney explained above, holding on vision.
