### ISSUE TITLE
Revise organics service page 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2482]
- [x] Editors assigned (round 1)
- [x] Feedback received, incorporated
- [x] Editors assigned final round

**Comment by annieszot** [comment]
draft: https://docs.google.com/document/d/1MD2Ioqgbn4_C27ruYes1AK_o-8H-mfexxy7vc50-x48/edit

**Comment by annieszot** [comment]
Assigning @srigdon as part of "zero waste content revision bundle." Requesting edits by Wednesday, July 10.

**Comment by srigdon** [comment]
Drafted reviewed, lookin' good! Put a question in there about content debt, let me know what you think.

**Comment by annieszot** [comment]
Great revisions @srigdon and much appreciated! My two cents to your question are in the doc, and I welcome Laura's take. Perhaps an item to decide at content pin-up Tuesday. 

@LauraTrujillo The draft is ready for your final review! Edits requested by Wednesday, July 10 :)

**Comment by LauraTrujillo** [comment]
Made a few suggestions, but it's good to go!

**Comment by annieszot** [comment]
Thank you! Edits incorporated. Closing
