### ISSUE TITLE
<title> for topics & topic collections

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2497]
**Describe the bug**
Topic collections and topic pages don't have meaningful `<title>` tags, just the page URL. Let's change that!

**Acceptance criteria**
- [x] On a topic or topic collection page, the `<title>` (that appears in the browser tab) is the same at the title of the topic/topic collection. 

**URL**
https://alpha.austin.gov/en/health-safety/healthcare-prevention/

**Screenshots**
![image](https://user-images.githubusercontent.com/5839508/60776623-3482df80-a0f3-11e9-8eb3-e381e2c209f4.png)

**Comment by briaguya** [comment]
Could be a 1 but gave it a 2 in case we hit some css wonkyness

**Comment by briaguya** [comment]
working here: https://deploy-preview-467--janis.netlify.com/en/housing-utilities/recycling-trash-and-compost

**Comment by desigonz** [comment]
@briaguya QA complete—looks beautiful!
