### ISSUE TITLE
Implement compost class form

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2499]
**Acceptance criteria**
- [ ] draft content: https://docs.google.com/document/d/1MD2Ioqgbn4_C27ruYes1AK_o-8H-mfexxy7vc50-x48/edit?usp=sharing
- [ ] URL structure: /request-composting-class/ (per #2422)
- [x] No progress bar (please remove for all simple forms)
- [ ] Form entries get sent to [email address TBD]

**Comment by desigonz** [comment]
Actions to take after our 7/31 meeting:
- [ ] @annieszot will review copy, thinking about one level of hierarchy within form + helper text.
- [ ] @desigonz will then review
- [ ] @easherma to update form so that we can compare across forms during the next content pinup
- [ ] Left align helper text for date/time pickers

**Comment by easherma** [comment]
Original: 
https://opo.austintexas.io/request-compost-class/2499-compost-class/form
Alternate: 
https://opo.austintexas.io/request-compost-class/2499-compost-class-alternate/form

**Comment by desigonz** [comment]
Per conversation with @annieszot, we're looping back with ARR. Backlogging this for now.
