### ISSUE TITLE
Drafting EMS Communications Medic 1 Process Page content

### ISSUE THREAD

**Issue by courtneyjacinic** [cityofaustin/techstack#25]
[Original content in new layout here](https://docs.google.com/document/d/1TRSXZ97S7Jyh3YCdjopzfZDugDToV9VA-28-5r500Lo/edit#heading=h.bqn28tjekhcr)

**Comment by amenity** [comment]
No public safety contract; blocked by this. 

Need to find out if contract timeline is soon enough to make this happen. Likely need to jump forward
