### ISSUE TITLE
UX requirements for translation notification page component

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#250]
In order to implement #216 dev needs more requirements. 

Are there other situations where this should appear?

**Comment by amenity** [comment]
@mateo, broke this out from #216 - will you add any other requirements you need here?

**Comment by cthibaultatx** [comment]
Yes, this is a general notification component that can be page-specific or applied sitewide. It can be dismissed. If a user dismisses it, the block should stay dismissed for the remainder of the session.

PS In the design library, there is a notification for emergencies.

Any other questions? @mateoclarke @amenity 

![screen shot 2018-06-08 at 8 43 49 am](https://user-images.githubusercontent.com/20911665/41161414-758f31fe-6af8-11e8-90d5-271046468326.png)
