### ISSUE TITLE
Add OPO complaint and thank you to information architecture

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2503]
- [x] Deciding what topic collections/topics they fit under
- [x] Creating new topic/topic collection pages

**Comment by desigonz** [comment]
@kriskristin, sarah's never created a new topic or topic collection; this would be a great moment to observe how she uses Joplin as a content editor

**Comment by kriskristin** [comment]
@srigdon Can I observe you while you do this? Just let me know when you plan on doing it.

**Comment by srigdon** [comment]
Did the above. Got bugs! See #2636
