### ISSUE TITLE
Audit 311's pages

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2504]
Audit: https://docs.google.com/spreadsheets/d/1-XYSYXQwMEGq7AqaVXINlYBXplhrqemI3rxw46-FKQc/edit#gid=0

When you're done, leave high level (tl;dr) notes in a comment here.

**Comment by mark-swanson** [comment]
https://docs.google.com/spreadsheets/d/1-XYSYXQwMEGq7AqaVXINlYBXplhrqemI3rxw46-FKQc/edit#gid=0

**Comment by mark-swanson** [comment]
Broad overview: It's in good shape. There was some significant work done on this recently, and it shows.
