### ISSUE TITLE
Simple forms—Update style guide & content model spreadsheet

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2506]
- [ ] In style guide: 
  - [ ] Title convention (service-oriented language)
  - [ ] When to use second/first person?
  - [ ] anything else from content pin-up? 
- [ ] Update content model spreadsheet

**Comment by srigdon** [comment]
- [ ] Turn notes from (content pinup agenda)[https://docs.google.com/document/d/1IHENUdTEK9lCS0Lrf9aLIGjTJvao6Nit_FeFh7NHjn4/edit] into style guide entries.

**Comment by desigonz** [comment]
Moving this back to sprint 38.
