### ISSUE TITLE
Plan for privacy link and content

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#251]

**Comment by cthibaultatx** [comment]
Once this is figured out, we'll also add the Read about privacy link to the footer or somewhere else to make it accessible on desktop.

**Comment by ashleecoa** [comment]
@cthibaultatx  I thought I remember some discussion on this a while ago, and the idea was to use the current City's privacy policy? http://austintexas.gov/page/privacy-policy

**Comment by amenity** [comment]
See also #252. 

> @ashleecoa commented on Fri Feb 09 2018
> We need to write and add a privacy policy to alpha. Here's the austintexas.gov one: http://austintexas.gov/page/privacy-policy
> 
> Should we consult with Law Department?

**Comment by cthibaultatx** [comment]
@ashleecoa you and I connected on this over slack last week (I think). Yes, we could use the same privacy content. Up to you and content team :)

**Comment by LauraTrujillo** [comment]
@ashleecoa Closing this issue per our conversation in backlog grooming. Created issue #311
