### ISSUE TITLE
Implement Joplin navigation labels & icons

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2510]
### As a content editor, I want to be able to easily navigate between different sections on Joplin (Content, Images, Contacts, Locations, Users) so that I can efficiently edit content.

**Acceptance criteria** 
- [x] Each item in the nav has icons. Here are the names for the icons within the [Material icon font set](https://material.io/tools/icons/?icon=text_fields&style=baseline) that we have in Joplin:
- Content: "text_fields"
- Maps: "map"
- Locations: "location_on"
- Images: "photo"
- Contacts: "contact_phone"
- Users: "account_circle"
- [ ] icons are centered
- [ ] text is centered
- [ ] active text labels same color as active icon 
- [ ] Each item in the nav has a text label per [mock](https://github.com/cityofaustin/techstack/issues/2510#issuecomment-516558985) in the following order
- Pages
- Images 
- Locations
- Contacts
- Maps
- Users

**Is your feature request related to a problem? Please describe.**
Currently, the Joplin left nav only uses icons with no labels. It can be confusing to know where to edit something, especially in the instance of "Contacts" vs "Locations," which uses the same icon.

**Comment by chasechenevert** [comment]
We decided to keep the icon+label stacked (as implemented) for now (image is just to show positioning and not color)
<img width="215" alt="Screen Shot 2019-07-10 at 10 22 50 AM" src="https://user-images.githubusercontent.com/7027270/60981853-b7c35180-a2fc-11e9-8bdb-0c21d4b925b3.png">

**Comment by chasechenevert** [comment]
Just wanted to check before I upload, is this the correct order of the menu items? @toribr

**Comment by toribr** [comment]
No. Probably:

Content: "text_fields"
Map: "map"
Locations: "location_on"
Images: "photo"
Contacts: "contact_phone"
Users: "account_circle"

We need to combine map & location soon, as the difference betwixt them is not at all obvious. See #2364

**Comment by desigonz** [comment]
Something I hadn't noticed before today—you select a location for a contact. Not sure that that would change anything, but I guess the location data is being used two ways in two different locations.

**Comment by toribr** [comment]
Remind me... location is used within contact and where else?

**Comment by desigonz** [comment]
> Remind me... location is used within contact and where else?

@toribr Maps! https://joplin.herokuapp.com/admin/snippets/base/map/add/

**Comment by briaguya** [comment]
@toribr @desigonz I think it would make sense to keep locations and remove maps.

Instead of having the "map block" in our "add maps and apps" section be a chooser for a snippet called "map," we could update it to be a chooser for locations.

The only reasons I can think that would complicate this are maps with multiple locations, but I'm sure we'll address that concern as a part of https://github.com/cityofaustin/techstack/issues/2364

**Comment by desigonz** [comment]
Thanks @briaguya! Added your note to #2364 . For now let's surface all, and when we decide on the maps/location/contact solution, we'll remove maps if we need to.

**Comment by desigonz** [comment]
@easherma Hi! Taking a look at this and noticing one of the acceptance criteria hasn't been completed—"Each item in the nav has a text label." Moving this back to on deck.

**Comment by desigonz** [comment]
![image](https://user-images.githubusercontent.com/5839508/62158787-e0c07c00-b2d5-11e9-8d62-e9523f96fd62.png)

**Comment by desigonz** [comment]
@toribr, can you review this on staging?

**Comment by toribr** [comment]
I'm ok with the left aligned text, but "home" needs to change to "pages". Eventually, we'll want a "dashboard" selection, and we don't want to have to retrain authors how to find pages.

**Comment by desigonz** [comment]
back to @easherma!

Acceptance criteria 
- [ ] change "Home" to "Pages"

**Comment by easherma** [comment]
Done, should we make a future issue for moving labels to under each icon?

**Comment by desigonz** [comment]
@easherma Design reviewed and says it looks ok as is.
