### ISSUE TITLE
Talk through and plan: Cleaning up Joplin Models/API - refactor so it's not a pain

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#2513]
- [x] Identify any small cleanup we can be working on right now.
- [x] Document ideas for bigger data model changes that will happen with J3.

Audit existing code in Joplin, get rid of stuff we don't need anymore (like department snippets, for example)
Also, we may be able to simplify the code a bit by having some more generic methods to inherit from when they are required by a many if not all content types.

**Comment by easherma** [comment]
https://github.com/cityofaustin/joplin/pull/314 moved some stuff around but there is still more work to do, those changes doesn't really follow typical django or wagtail layout conventions which are pretty common:
https://medium.com/my-new-roots/django-project-layout-494d2ed89b74
https://www.revsys.com/tidbits/recommended-django-project-layout/
https://github.com/torchbox/wagtail-torchbox/tree/master/tbx

**Comment by easherma** [comment]
Assigning all devs since a) Brian started doing some of this already and b) Ideally it can be as collaborative as possible

**Comment by easherma** [comment]
Would love to set up an in person meeting or two to go through some of this while I'm back in town.

**Comment by easherma** [comment]
Need to update notes here with the whiteboarding and further plans

**Comment by easherma** [comment]
This came up some more in terms of the new top services stuff. Our API structure is making it hard on Janis

**Comment by briaguya** [comment]
Let's talk about building tests for this, I'm thinking:
* Tests around API specifically, when building out the API, we'll be able to define requests and expected responses, then write failing tests for those and make them pass (tdd ftw)
* Full end to end test, we should probably come up with a good dataset for a test db, then spin up joplin with that db and run a janis build against it, and make sure we run tests to see everything renders as expected. This could be quite big, and probably will take a bit of research.
