### ISSUE TITLE
Review the "Complaint investigation process" page with the OPO for consistency

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#2514]
https://alpha.austin.gov/police-oversight/complaint-investigation-process/ 

Based on copy updates regarding anonymous complaints, is all of this still true?

**Comment by srigdon** [comment]
- [ ] Schedule a meeting at Rutherford to do an editing session about this page.

**Comment by desigonz** [comment]
- [ ] @srigdon will send a draft with edits by ______

**Comment by desigonz** [comment]
@srigdon to see if Sara Peralta can take this on.

**Comment by desigonz** [comment]
@srigdon is emailing Sara Peralta to check in on this. Sara P in OPO now has Joplin access and can update this whenever, so this is in their court.
