### ISSUE TITLE
Capital Contracting content audit

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2517]
Home page: http://www.austintexas.gov/department/capital-contracting

**Comment by mark-swanson** [comment]
Alrighty, at a stopping point! https://docs.google.com/spreadsheets/d/17f8c7j-KDGmr09z9LTNnWtIm9Mpw21vbX4k-4Wa704I/edit#gid=0

C/P my comments: Overall thoughts: Very fractured navigation. Nothing seems to flow from one thing to another. Good example of the design driving content, not the other way around. Based on my (fairly substantial) experience working with government contracting, there are a lot of parts of this are standard operating procedure, which is fine. There is a great opportunity to digitize a lot of these forms. Businesses will jump through the hoops necessary to get a city contract, but I'd pitch this as an opportunity to ease staff burden through a digital solution.

**Comment by desigonz** [comment]
assigned to @Jo-Dwyer for review

**Comment by Jo-Dwyer** [comment]
It would be helpful to get more insight into objective issues based on the heuristics. It also seems that this audit isn't complete: Columns for "Trivial/non-trivial" and "Next steps" are undefined for majority of the links.

**Comment by Jo-Dwyer** [comment]
What else does this need? I think we can close this @desigonz

**Comment by desigonz** [comment]
@Jo-Dwyer If you don't think there's anything that needs to be updated, then yes!
