### ISSUE TITLE
City Boards and Commissions content audit

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2519]
https://www.austintexas.gov/department/boards-and-commissions

**Comment by desigonz** [comment]
@matthewbarron When you're done with this issue, please move to "Review" and assign to @srigdon

**Comment by Jo-Dwyer** [comment]
@matthewbarron this audit needs readability scores. [City boards and commissions audit](https://docs.google.com/spreadsheets/d/1eTY0mzV0HE4RpAhQW4kDKkKRq2UFJsQkkfuooss9SIU/edit#gid=0)

When they're update, can you move this issue to "Review" and assign to @srigdon?

**Comment by matthewbarron** [comment]
Hello!

Sure thing, Jo. I’ll take care of it.

MB

**Comment by srigdon** [comment]
@matthewbarron wrapped up readability scores, now ready for review.

**Comment by gabrielaperezdelaosa** [comment]
I was a little confused on what I'm supposed to do here.

I understand that @srigdon and Mathew have already done the audit: https://docs.google.com/spreadsheets/d/1eTY0mzV0HE4RpAhQW4kDKkKRq2UFJsQkkfuooss9SIU/edit#gid=0

What does review entail? Filling out the empty columns to the right or making sure that the information is still current?

**Comment by gabrielaperezdelaosa** [comment]
@srigdon what's exit criteria? Here's what I've done
- [x] overviewed the audit to make sure it still matches what's on austintexas.gov
- [x] made sure reading level columns and such are filled
- [x] redigested the take-aways and organized them in a manner I would know how to tackle
- [x] created an issue for the feature I think we would need to transition Boards and Comm's (#4580)
