### ISSUE TITLE
CPIO content audit

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2520]
home page: https://www.austintexas.gov/department/communications

**Comment by mark-swanson** [comment]
At a stopping point: https://docs.google.com/spreadsheets/d/1H2m_wF27oME3SH2qa0p0_M6ngXbj8KxnPtRTGMoDgcQ/edit#gid=0

**Comment by LauraTrujillo** [comment]
@LauraTrujillo ready!
