### ISSUE TITLE
City Clerk's office content audit

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2523]
Home page: http://austintexas.gov/department/city-clerk
Inventory sheet: https://docs.google.com/spreadsheets/d/1-we8vC0_qHwGcGQRXfCOIuwxawPGLFB50QFBTdVIz4w/edit#gid=1748134111

**Comment by matthewbarron** [comment]
Not sure how to resize this... However, this issue, on the last side nav tab, bassically doubled in size ): 

But I'm working through it. Seems to mostly cross link to information pages.  Nothing too crazy but super interested when looking at it from this new perspective

**Comment by Jo-Dwyer** [comment]
@srigdon @annieszot @ablangworthy27 Do any of you have time for an inventory review?

**Comment by ablangworthy27** [comment]
I can do it

**Comment by ablangworthy27** [comment]
This is done. Feedback is in the comments of the doc.
