### ISSUE TITLE
Community Court content audit

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2524]
home page: https://www.austintexas.gov/department/community-court

**Comment by anukandimalla** [comment]
@desigonz done content inventory and analysis and link for the inventory and analysis 
https://docs.google.com/spreadsheets/d/1xAGQjkqeywcH_7gYKREammjoWq8tkt2PK7t47XJ2yJE/edit?usp=sharing

**Comment by anukandimalla** [comment]
@desigonz Ready for Review
