### ISSUE TITLE
City Council content audit

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2525]
home page: https://www.austintexas.gov/department/city-council/council-meetings
Completed Inventory sheet: https://docs.google.com/spreadsheets/d/15TuOZwTiDbUz8BvKkBMykViIjL9E9m0XJaxhw65Oxps/edit#gid=0

**Comment by matthewbarron** [comment]
This audit is already half-done as its side-menu hierarchy was reshuffled from City Clerk department, which has been audited already. There isn't much left to audit here. Only a few main nav tabs.

**Comment by desigonz** [comment]
Is this audit done? If so, add the link here and assign a content strategist to review.

**Comment by ablangworthy27** [comment]
@matthewbarron I have finished reviewing this but wasn't able to include comments in the spreadsheet. I can share at the next meeting.
