### ISSUE TITLE
Development Services content audit

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2527]
home page: https://www.austintexas.gov/department/development-services

**Comment by desigonz** [comment]
@matthewbarron When you're done with this issue, please move to "Review" and assign to @Jo-Dwyer

**Comment by Jo-Dwyer** [comment]
[DSD Content audit](https://docs.google.com/spreadsheets/d/1mFgf7sV1Y9IQr2TO0bWVPb6IoVf6140Yr7Eq_xkQja4/edit#gid=1533383286)
