### ISSUE TITLE
Equity office content audit

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2529]
home page: https://www.austintexas.gov/department/equity-office

**Comment by anukandimalla** [comment]
@desigonz Ready for the review and here is the link for the [Equity office inventory](https://docs.google.com/spreadsheets/d/1VqlBOxBvvQRf9Ah-YxiBigBNRLdnAqR9-s-wE4xDdvs/edit?usp=sharing)

**Comment by anukandimalla** [comment]
[Here is the link for Forms Service Access Framework](https://docs.google.com/spreadsheets/d/1IVO5yy_yMSyMp0i0S4rIoyal1VRFUB3COqZqdarvBbU/edit?usp=sharing)

**Comment by desigonz** [comment]
Thanks @anukandimalla! We'll talk about this at the content audit sync tomorrow, but moving forward, can you ping @Jo-Dwyer when an audit is complete and she'll divvy it up with the content team?

**Comment by anukandimalla** [comment]
Thanks @desigonz 👍

**Comment by Jo-Dwyer** [comment]
Looks good! I had to stop myself before I ended up starting a transition strategy... Thanks @anukandimalla
