### ISSUE TITLE
Draft description text for OPO official document page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2531]
In the [OPO official document listing page mocks](https://xd.adobe.com/view/a6e88427-d7e7-413b-6d85-f18144f0687c-d0d9/), we have a description field. The text is currently lorem ipsum. We need some content hear that introduces context for these documents.

**Comment by srigdon** [comment]
@desigonz Let's go with this rough draft version of a description for now: "Complaints filed against Austin police officers can result in legal documents. OPO publishes many of these documents in full respect of the law and toward our mission to inform the public and increase transparency." 

Updated draft doc: https://docs.google.com/document/d/1-sZ61G5nuUCtuZfKb5io2KBOMuvUt9ABUUSbzsLF5tM/edit#

**Comment by desigonz** [comment]
Thank you @srigdon! @chasechenevert, can you add that copy to the mocks? Then it'll good to go to OPO.

**Comment by chasechenevert** [comment]
Here's the update: https://xd.adobe.com/view/a6e88427-d7e7-413b-6d85-f18144f0687c-d0d9/
