### ISSUE TITLE
Homeland Security & Emergency Management content audit

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2533]
home page: https://www.austintexas.gov/hsem

**Comment by anukandimalla** [comment]
@Jo-Dwyer Ready to Review and find the [link](https://docs.google.com/spreadsheets/d/14fTkGlbgA0fPb0XDl56A3-hMQYhz-VZGp3XOm6aRtaM/edit?usp=sharing) in here to review

**Comment by Jo-Dwyer** [comment]
Looks good. Good insights. I see good cause for an alert content type and a clear sense of priorities here. Thank you @anukandimalla!
