### ISSUE TITLE
Innovation content audit

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2535]
home page: https://www.austintexas.gov/innovation

**Comment by anukandimalla** [comment]
Found 2nd website for Innovation Lab https://cityofaustin.github.io/innovation/

**Comment by anukandimalla** [comment]
@LauraTrujillo Ready for Review.

**Comment by LauraTrujillo** [comment]
content audit: https://docs.google.com/spreadsheets/d/1D-uX4QOQa3NGBi4MFMTPQ-v_Q6TViwgDxxySGJxHfiI/edit
