### ISSUE TITLE
Office of Medical Director content audit

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2541]
home page: https://www.austintexas.gov/omd

**Comment by anukandimalla** [comment]
Found 1 microsite: http://www.austintexas.gov/atxn(austintexas.gov official Media Channel) and 1 Related OMD website : https://atcomd.wordpress.com/about/

**Comment by anukandimalla** [comment]
@LauraTrujillo Ready for the review and link for the doc 
https://docs.google.com/spreadsheets/d/1RgGKYY4EUGSED_OWYFdbfuQJVv47IuFeJ7imZxfNBRg/edit?usp=sharing
