### ISSUE TITLE
Real Estate Services content audit

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2542]
home page: https://www.austintexas.gov/department/real-estate-services

**Comment by anukandimalla** [comment]
@desigonz Read for review and Link for the office of Real estate Audit 
https://docs.google.com/spreadsheets/d/1TIKAFB_DfQt8Dh-oA_2AwQOIQMHZ0KQtpNCTNYBSer4/edit?usp=sharing

**Comment by anukandimalla** [comment]
Link for Office Real estate Audit with Forms service access framework
https://docs.google.com/spreadsheets/d/1IWhC-1SrG8abcXFhINVEZsXUzSEFlbkMNzfXdCV1Gzs/edit?usp=sharing

**Comment by desigonz** [comment]
assigned to @annieszot for review

**Comment by annieszot** [comment]
Looks good! Thanks @anukandimalla!
