### ISSUE TITLE
Parks and Rec content audit

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2544]
home page: https://www.austintexas.gov/department/parks-and-recreation

**Comment by Jo-Dwyer** [comment]
@matthewbarron when you're finished, please move this to 'Review' and assign @Jo-Dwyer to review

**Comment by ablangworthy27** [comment]
@matthewbarron can you provide the link to the audit?

**Comment by ablangworthy27** [comment]
This is done. Comments in the doc.
https://docs.google.com/spreadsheets/d/1rm9qJSpfm1uT_nqMUfVy41YW8EuI9dnsnr4-8KkLvxE/edit#gid=1748134111
