### ISSUE TITLE
Wagtail questions

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2553]
Using this epic to identify all of the questions we'd like to investigate at Wagtail Space.

**Comment by desigonz** [comment]
@easherma @briaguya I'm being very generous about what I threw in here. Feel free to add or take things out of this epic!

**Comment by briaguya** [comment]
Not sure if this is already somewhere else but:
"Is it possible to make a field required for publish but not for saving a draft?"

**Comment by desigonz** [comment]
A more helpful revision history—can you see when something was published or unpublished?

**Comment by briaguya** [comment]
place with notes https://docs.google.com/document/d/1RGWCd66fHoh7qvOvtkk7t69kcqAYwgN0LX7BhpBPu7Q/edit?usp=sharing

**Comment by briaguya** [comment]
Apparently our modeltranslation method of doing internationalization is less than ideal, and we have been told about https://wagtailtrans.readthedocs.io/en/latest/getting_started.html as a cool option that may be better

**Comment by easherma** [comment]
Suggesting we leave this open but maybe edit the title/context to be a running list of 'things we want to ask other wagtail users'
