### ISSUE TITLE
Make author notes icon not a link

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2558]
**Describe the bug**
Currently, when you click the author notes icon from the [content list page](https://joplin.herokuapp.com/admin/pages/3/), you get a modal alert as seen in the screenshot below.

**Acceptance criteria**
- [ ] The author notes icon is not a link; if you click the icon, nothing happens

**URL**
https://joplin.herokuapp.com/admin/pages/3/

**To Reproduce**

1. Go to https://joplin.herokuapp.com/admin/pages/3/
2. Click on author notes icons
3. See error

**Current behavior**
That modal in screenshot below 

**Expected behavior**
When you click the button, it should take you to author notes. However, let's wait to make this happen for when author notes are in a new tab (#2559). 

For now, let's make it not a link.

**Screenshots**
![image](https://user-images.githubusercontent.com/5839508/60924494-fc041280-a266-11e9-849a-f33aa89fdc98.png)

**Device**

**Browser**

**Additional context**

**Comment by desigonz** [comment]
@briaguya Now when I hover over the icon, the cursor looks like 🚫(not rendering in screenshot but circled where it does show on my browser) and code is `javascript:null;`. Would prefer not to have this at all but not a huge deal; let me know what you think.

PS I'm on Chrome.

![image](https://user-images.githubusercontent.com/5839508/62626334-c0ec1200-b8ec-11e9-984b-4e72d883bc96.png)

**Comment by briaguya** [comment]
@desigonz

The way we're adding the icon here is as a "button" in wagtail, so it's going to be a link no matter what. I used javascript:null to make sure nothing happens when you click it (if it's blank it'll reload the page which gets messy).

I updated it so the cursor doesn't change to a 🚫
