### ISSUE TITLE
View author notes from content list page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2559]
### As a content editor I want click the author notes icon from the content list page and go directly to the author notes so that I can easily see how a page needs to be improved..

**Is your feature request related to a problem? Please describe.**
Currently, nothing happens.

**Describe the solution you'd like**
When you click the button, it takes you to author notes tab.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/5839508/60924494-fc041280-a266-11e9-849a-f33aa89fdc98.png)

**Comment by chiaberry** [comment]
We no longer have the author notes icon on the content listing page.
