### ISSUE TITLE
Collapse content blocks on official doc pages

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2568]
- [ ] @toribr to deliver Joplin mocks for dev

### As a content editor, I want to be able to collapse entries when editing page types like service pages and official documents, so that it's a seamless experience to enter content on pages with lots of blocks.

**Is your feature request related to a problem? Please describe.**
From @toribr: "implementing this as steps is pretty painful from a usability standpoint."

**Describe the solution you'd like**
Ability to collapse content blocks on pages where you can add a lot of blocks.

**Describe alternatives you've considered**

**Additional context**

**Comment by desigonz** [comment]
At Wagtail Space learned there's a solution for that

**Comment by toribr** [comment]
@desigonz Sort of confused about the user story - i understand the case for official docs, but not sure about service pages. Is there a particular service page which is a good illustration of the problem?

**Comment by desigonz** [comment]
@toribr That's a good question—we wrote this user story a while ago. I defer to you on whether we want to collapse in service pages, but here are some you might want to look at:

- [Get a birth or death certificate](http://joplin-staging.herokuapp.com/admin/pages/65/edit/) (example of a page with options)
- [Get a central preparation facility](http://joplin-staging.herokuapp.com/admin/pages/135/edit/) (example of a page with more steps)

Although quickly looking at these, it doesn't seem like we need to collapse on service pages.

**Comment by toribr** [comment]
@desigonz Agree.

**Comment by desigonz** [comment]
Duplicate of #2668, closing this one.
