### ISSUE TITLE
Install Google Analytics for Austintexas.gov admin

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#257]
From the Drupal admin, we can see how often users login. [Here](https://docs.google.com/spreadsheets/d/1oDa7zpNIT0JPazq8swRav8uUgLfqEyoleR00pF_maMw/edit#gid=0) is a table showing users active withing the past 6 months (~200) — ~100 of which have logged in during the past two weeks. This is helpful, but it doesn't give us the level of detail we would like to understand current usage.

Implementing GA on the current Drupal author interface will give us quantitative data to inform #190.

If there are any questions about nuances of usage patterns, @ashleecoa has a wealth of knowledge in this area. 💁

Aha! Link: https://desi1.aha.io/features/RT-329

**Comment by amenity** [comment]
@benweatherman, you said this would be pretty easy? @toribr wanted to make you aware of this issue in case it informs or can inform your work.

**Comment by amenity** [comment]
@toribr - would this be useful for you? Came up in a "which-CMS?" talk with @ben as something that would inform his evaluations. Would analytics on the admin side of the current site be useful to you?

**Comment by toribr** [comment]
It's always a good idea. Will be a while before it's useful, but it should be installed. More importantly, HotJar or similar (I can't recall the name right now) should also be installed.

**Comment by amenity** [comment]
@benweatherman - sticking this back on your horizon. If it's a S, maybe we can get it in as filler in a future sprint?

**Comment by amenity** [comment]
Also sticking in this guy, @toribr https://github.com/cityofaustin/techstack/issues/369.
