### ISSUE TITLE
Review contact snippet user experience

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2571]
Adding a contact user experience needs some help.
- Review which fields are required
- "Social media url" block is weirdly left aligned
- In social media block, why is there "copy content from" other languages? 
- Do we need helper text for any of the fields?
- What else?
- (tori) We've talked about the usefulness of being able to display only some fields within a snippet. Presumably, these controls would surface after the snippet was placed on a page (like local overrides). In the meantime, duplicate pared-down contacts could be made to use per instance, but in the case of a changing phone number, for example, all instances would need to be changed.

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/0c954966-45f1-44e3-be99-343761534b22)

**Comment by toribr** [comment]
Requirements here need to be discussed:

The current configuration wrt required fields is ok, I think.

Acceptance requirements:
- [ ] center social media block
- [ ] remove or hide "copy content from" social media
- [ ] discuss moving "save" button to top in bar to match content pages

**Comment by desigonz** [comment]
Thanks @toribr! For the things you outlined above, do you want to discuss with the content team, dev team, or both?

**Comment by toribr** [comment]
Neither - let's get #2607 and #2606 fixed and leave moving the save button to a later fix when we know what we're doing with snippets and translations, and the relationship between maps/location/contacts.
