### ISSUE TITLE
Implement official document content type

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2572]
### As a resident, I want to be to access all official documents that OPO is allowed to publish so that I can be better informed about policing in Austin.

**Acceptance criteria**
- [ ] Janis implementation ([dev spec](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/895949b5-49ac-45bc-9114-2f5b3183573e/Official-Document-MVP-web-1/))
- [x] Joplin implementation (mock below)
  - [x] Title, description, topic, and department fields should behave as they do on information and service pages 
  - [x] Ability to add as unlimited "official document" blocks
  - [x] Adding these blocks should behave similarly to steps on service pages—can reorder and delete (see design). 
  - [x] For MVP, we will *not* be uploading and hosting files on Wagtail—instead, content editors can add a name and URL for the document.
  - [x] All of the fields within the official document block are required

**MVP mocks**
Janis dev spec
https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/895949b5-49ac-45bc-9114-2f5b3183573e/Official-Document-MVP-web-1/

Joplin interface
![#2387 Official doc list](https://user-images.githubusercontent.com/3790067/60987295-eb0ade00-a306-11e9-885d-cb7a013dc34e.png)

**Comment by Niicck** [comment]
I'm not seeing the official document type within the Janis dev specs.

**Comment by desigonz** [comment]
Pinged @chasechenevert about this in Slack https://austininnovation.slack.com/archives/CKEJP1XQV/p1564156504001200
Chase, is it possible they've moved?

**Comment by desigonz** [comment]
Here is the link to the mocks: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/895949b5-49ac-45bc-9114-2f5b3183573e/Template-Official-Document-desktop/ cc @Niicck

**Comment by desigonz** [comment]
- [ ] "Authoring office of document" field should be translatable

**Comment by Niicck** [comment]
Check it out: 
Janis: https://deploy-preview-463--janis.netlify.com/en/health-safety/health-records-certificates-2/birth-death-certificates/official-documents/
Joplin: https://joplin-pr-2572-official-doc.herokuapp.com/admin/pages/108/edit/
