### ISSUE TITLE
Translate compost class form

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2574]

**Comment by annieszot** [comment]
See #2206

**Comment by annieszot** [comment]
Translation doc to send https://docs.google.com/document/d/1vH6eQN5f3VIpB4QBzATwcQSV-AR_7Q2Ci4y7LdAaAl8/edit @LauraTrujillo

**Comment by LauraTrujillo** [comment]
Sent to translators!

**Comment by annieszot** [comment]
Currently with translators. Will change milestone to sprint 37. Will close if translations returned before or on 8/8/19.

**Comment by LauraTrujillo** [comment]
@desigonz @annieszot also closing this one since Desi G has the translations now and the form is hardcoded. holler if you need anything!
