### ISSUE TITLE
IA rules

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2575]
We've got themes, topic collections, topic pages, and department pages. We also have rules for how these are related, but they haven't been documented consistently, which makes it hard for developers to implement the rules. Let's make sure it's all documented in one place.

Some things might live in the [Standards for IA and URLs doc](https://github.com/cityofaustin/techstack/issues/2271).

**Comment by desigonz** [comment]
- [ ] @desigonz to jot down IA rules
- [ ] review with content and design team
- [ ] document in [Standards for IA and URLs doc](https://github.com/cityofaustin/techstack/issues/2271)

**Comment by desigonz** [comment]
### IA pages
- Themes (top-level nav; aggregates topic collections)
- Topic collections (aggregates topic collections and topics)
- Topics (aggregates guides, service, and information pages)


### Content pages
- Service page
- Information page
- Guides


### Hybrid 
- Department page


### Rules
- **Content pages under topics** 
  - All guides and service pages must be assigned to at least one topic.
  - Guides, information, and service pages can live in multiple topics.
  - Information pages do not have to be assigned to a topic page, especially when an information page is meant to be viewed in the context of a service or a department. Example: [How we store and use your data](https://alpha.austin.gov/police-oversight/how-we-store-and-use-your-data) and [Complaint investigation process](https://alpha.austin.gov/police-oversight/complaint-investigation-process) are very specific to the OPO complaint process and therefore are only assigned to a department, not a topic. 
- **Content pages under departments**
  - All guides and service pages must be "offered by" at least one department.
  - Guides, information, and service pages can be "offered by" multiple **departments**.
  - In rare cases, an information page may not be "offered by" a department. Example: the privacy policy is an information page that is globally available; it doesn't make sense to tie it to departments. 
- *? Can topics live in more than one topic collection ?*

**Comment by toribr** [comment]
@toribr, we've talked about how these multiple topics should be within different themes (although we're not currently following that rule on alpha.austin.gov. Thoughts?

I think that's "could", not "should". In rare cases, a guide, information page, or service page may make sense under a different topic. This may be in a different theme or the same thing - the essential thing to think of is locating the page where a resident might look for it, regardless of it's parents. (Need to be able to make a good case for this, however.)

These pages which have multiple parents should have a primary department, contact, and single editor within that department responsible for the page.

? Can topics live in more than one topic collection ?
Again - I don't think we yet know if there is a viable use case for this, but it may be possible. However, it seems unlikely because that's presuming a resident is looking for a group of content, rather than a single page.

**Comment by desigonz** [comment]
Thanks @toribr! Agreed that a guide, info page, or service page could live under multiple topics in rare cases. My question is: we currently have the same page living in two sibling topics. See "Get your compost ready for curbside pickup" in both columns below. Should that be allowed, or no?

![image](https://user-images.githubusercontent.com/5839508/61322577-9cac8200-a7d3-11e9-93e1-eb9a8a535ccc.png)

**Comment by toribr** [comment]
My thought right now, is yes. It makes sense.

**Comment by desigonz** [comment]
@toribr Okay cool, so for now, allowing pages to be assigned to sibling topics, but we'll revisit later.

**Comment by briaguya** [comment]
## On the theme/topic side
- Themes - Statically defined in code, hard to change.
- Topic Collections - associated with one and only one theme.
- Topics - associated with one or more topic collections
- Pages (service/info/document) - associated with one or more topics

## On the department side

- Departments - not associated with themes/topics in any way
- Pages (service/info/document) - associated with one or more departments

## URLs

- /department_slug/page_slug
- /theme_slug/topic_collection_slug/topic_slug/page_slug

## Guides (for the future)

This is where things will get wonky, I figure this will make more sense after dev/design sync next week

**Comment by srigdon** [comment]
@briaguya re: 
> On the department side
> Departments - not associated with themes/topics in any way
I thought Departments were being coded as a Topic Collection? At least for now, right?

**Comment by briaguya** [comment]
@srigdon the "Departments" page is more or less a topic collection page. I think that may be what you're remembering.

**Comment by desigonz** [comment]
Yep, to summarize (and correct me if I've gotten anything wrong):
- [the page that aggregates all departments](https://alpha.austin.gov/en/departments/) functions similarly to a topic collection page (but is it's own thing and not currently content manageable in Joplin)
- pages that use the department page content type (ex. [OPO](https://alpha.austin.gov/en/police-oversight)) cannot be assigned to a theme, topic collection, or topic. A user can navigate to it in the IA via the [the page that aggregates all departments](https://alpha.austin.gov/en/departments/).

@briaguya's done some brilliance to make it so that the URL of a page reflects how you navigated to it. So if a page titled "Find free ice cream" is assigned to a department and you navigate to it from the Dessert Opportunity Department page, the URL ends in `/dessert-opportunity/free-ice-cream`, but if you navigate to it from the "Staying cool" topic within the "Summers in Austin" topic collection, the URL is `/health-and-safety/summers-in-austin/staying-cool/free-ice-cream`.

**Comment by desigonz** [comment]
@briaguya, one thing you didn't mention above is that we can currently assign a topic collection to another topic collection (which makes things like #2638 happen).

**Comment by desigonz** [comment]
I made #2745 for adding the IA rules (although I actually think its more like "how to assign a page to topics/departments") to the style guide, so closing this.
