### ISSUE TITLE
Add content types to style guide

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2578]
Right now, we only have guidelines for service pages on the style guide. Let's add:
- [ ] Guides (see #2561)
- [x] Information pages
- [x] Department pages
- [ ] official documents

Longer-term, let's add:
- [ ] Topic pages
- [ ] Topic collection pages

Then, we can finish #2254

**Comment by easherma** [comment]
FYI I did migrate info pages and department pages back into the old style guide. 
But either way this might be worth discussing for a better approach. For instance, when I last chatted with content about it, the content in this style guide isn't actually intended to be used anywhere besides Joplin...so it might be potentially better to manage it directly in Joplin.

**Comment by desigonz** [comment]
@Jo-Dwyer  When publishing the APH department page, we checked against OPO and noticed that Farah's title on the OPO department page included her department so I went ahead and did the same for APH. But that's something we should either add to the style guide or in microcopy in Joplin. Or decide to omit it for any department.

![image](https://user-images.githubusercontent.com/5839508/64429826-7f31c100-d07c-11e9-82de-933cdd3b7f8f.png)

I'll also add this note in the style guide issue.

**Comment by desigonz** [comment]
@easherma re: "the content in this style guide isn't actually intended to be used anywhere besides Joplin"—that's not actually true. Different departments have been referring/linking to the style guide in their documents (like the forms guide; Sara Peralta also said she refers to it in her work). So we do need a platform where it's visible outside of Joplin.
