### ISSUE TITLE
Save as draft button

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2579]
**Describe the bug**
We made "save as draft" the primary action for pages in draft state. And now, the "Save as draft" button gets cut off for pages that are in draft state. Let's make it look good.
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/2ea35c37-5e06-47f7-b9fe-f77768a2dc2d)

**URL**
Joplin

**To Reproduce**

1. Go to https://joplin.herokuapp.com/admin/pages/3/
2. Find a page that is in a draft state
3. Click "edit"

**Current behavior**

**Expected behavior**

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by Niicck** [comment]
The button gets cut off for pages that are in the "draft" state.

**Comment by desigonz** [comment]
@Niicck good call! I updated my (admittedly weak) bug reporting above.

**Comment by desigonz** [comment]
Assigning to @chasechenevert to QA

**Comment by chasechenevert** [comment]
Good to go 👍
