### ISSUE TITLE
"View live" and "live + draft" when editing a page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2580]
There is a "view live" button on the content listing page (Figure A), but none when you're actually editing a page (Figure B); in the latter, you can only "preview." I've had times when I wanted to view live once I clicked into the edit page (also, could help reduce our pesky save-revisions-with-no-changes problem in #2286). Is this something we should consider?

Additionally, when you're editing a page, there's no indication whether that page is live, live + draft, or draft. Is this something we can include?

By comparison, in vanilla Wagtail you can click to open the live version, and know if it's live/live + draft/draft, from the edit page.

Figure A
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/f933a5ac-b5cf-4b8b-bed7-e01d9c7f9a7d)

Figure B
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/c76024ba-ceba-4c87-8a6a-7133c62f8bcf)

**Comment by desigonz** [comment]
@toribr will show new header design at dev-design sync, then we'll break down into acceptance criteria (and MVP vs. Joplin 3)

**Comment by toribr** [comment]
![Screen Shot 2019-08-21 at 9 39 26 AM](https://user-images.githubusercontent.com/3790067/63441817-a0957a80-c3f7-11e9-912a-ff6ba8e9ac4f.png)
This header also addresses other issues, some of which are issues, and some which aren't.

**Comment by desigonz** [comment]
I'll review during sprint 38!

**Comment by desigonz** [comment]
Made acceptance criteria in #2827. Closing this issue.
