### ISSUE TITLE
Joplin content main page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2581]
**Acceptance criteria**
- [x] Search page as the main "edit" page
- [x] "Pages" heading
- [x] Hide "other searches" section
- [x] Hide "parent" column
- [x] Includes "create new content" button

### tori's mock for our new pages page!
![image](https://user-images.githubusercontent.com/5839508/64054024-c2ef6c80-cb4a-11e9-9358-c5b6703d1a42.png)

### current search page
![image](https://user-images.githubusercontent.com/5839508/64054091-1a8dd800-cb4b-11e9-99d1-bf7dd3044d67.png)

### how the page reloads when you sort a column
![image](https://user-images.githubusercontent.com/5839508/64054267-dc44e880-cb4b-11e9-8e2d-64d0e748015e.png)

-------
### background

@briaguya recommends using the content search page as our primary listing page for Joplin content. This will help us implement things like filters (#2349). Let's evaluate if/how this will serve our needs.

http://joplin-staging.herokuapp.com/admin/pages/search/?q=a

**Comment by easherma** [comment]
FYI, the default wagtail dashboard can be customized to show some stuff (probably could feed it lists), and also populates with the users most recently edited pages.

**Comment by easherma** [comment]
We’ve run into some scaling and performance issues that we’ll definitely want to consider along the way

**Comment by desigonz** [comment]
@toribr I wrote up acceptance criteria, can you please review? There are a few questions for you above.

**Comment by toribr** [comment]
@toribr, check out how the search page currently paginates—the number of results per page is a lot less than our current Pages listing. What should we set as the number of results on this page?
@desigonz Probably depends a bit on performance - it's currently paginating at 20. I think that's fine unless we hear otherwise.

  for @toribr: when you sort a column (ex. click "author"), the page reloads to what we're using at the Pages listing page. Wanted to give you an FYI—is that what you would expect?

Def not. I expect the same UI as the previous page, but with the filter selected, and the results matching the filter.

**Comment by desigonz** [comment]
Thanks @toribr for your responses! Let's review the following at dev-design sync.

> DG: when you sort a column (ex. click "author"), the page reloads to what we're using at the Pages listing page. Wanted to give you an FYI—is that what you would expect?
> 
> TB: Def not. I expect the same UI as the previous page, but with the filter selected, and the results matching the filter.

**Comment by easherma** [comment]
I think the estimate for this should be higher. We're introducing some non-standard behavior that could mess with Wagtail's routing a bit, and we'll want to make sure we can override parts of the search template without also affecting searches that happen elsewhere, and stuff like the issue Desi mentions above.

**Comment by easherma** [comment]
Unfortunately, in the case of the admin search view, it looks like content_type is hard-coded as the only available URL parameter: https://github.com/wagtail/wagtail/blob/master/wagtail/admin/views/pages.py#L953

**Comment by robbobfrh84** [comment]
@desigonz and @toribr, Quick question on our "orderable" column here.... 👇

![Screen Shot 2019-10-28 at 12.04.09 PM.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/00f7118f-61dc-4f65-b38c-840ec26fd6c6) 

We currently don't that build into our UI yet. Should I remove it?
...like so... 

![Screen Shot 2019-10-28 at 11.59.34 AM.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/f8da04fb-60bf-425b-8fb7-348525b42b19)

Keep ✅  /  Remove ❌

**Comment by robbobfrh84** [comment]
Ok, after chattin' with desi, Looks like we'll just keep it for now! ✅

**Comment by robbobfrh84** [comment]
READY FOR QA: 
- https://joplin-pr-2581-content-main-pa.herokuapp.com/admin/pages/search/

**Comment by desigonz** [comment]
Hi @robbobfrh84! You've met acceptance criteria but there are some regressions that were introduced that we'll have to fix before passing QA. Let me know if you have any questions or want to talk this over.

- [ ] Edit page header bug (see screengrab 1)—I expect it to function as the header currently functions on Joplin staging.
- [ ] The "Pages" header has been applied across Joplin, but it should only be applied on Pages. Let's fix the following so they revert back to existing headers:
  - [ ] Users (screengrab 4)
  - [ ] Images (screengrab 5)
  - [ ] Documents (screengrab 6)
  - [ ] Snippets (the aggregate snippet pages are fine, but the "Pages" header is applied when you create a new snippet or edit an existing one)
    - [ ] Maps (see screengrab 2)
    - [ ] Locations (screengrab 9)
    - [ ] Contacts (screengrab 3)
- [ ] Style for headings in create content modal and create content modal loading message has changed to all caps. I expect it to style in sentence case as it currently styles on Joplin staging. (screengrabs 7 and 8)

### screengrab 1
![2581-edit-page](https://user-images.githubusercontent.com/5839508/67776705-b003f600-fa2e-11e9-9d7d-8b7d81ec4381.gif)

### screengrab 2
![2581-maps](https://user-images.githubusercontent.com/5839508/67776753-c5792000-fa2e-11e9-8ac0-abc74c5e2078.gif)

### screengrab 3
![image](https://user-images.githubusercontent.com/5839508/67777270-7da6c880-fa2f-11e9-9ad1-1d9d603a3c16.png)

### screengrab 4
![image](https://user-images.githubusercontent.com/5839508/67777316-8c8d7b00-fa2f-11e9-927f-34a60293e653.png)

### screengrab 5
![image](https://user-images.githubusercontent.com/5839508/67777347-98793d00-fa2f-11e9-9872-6c628af984c9.png)

### screengrab 6
![image](https://user-images.githubusercontent.com/5839508/67777389-a929b300-fa2f-11e9-9f1d-7f545e5203ea.png)

### screengrab 7
![image](https://user-images.githubusercontent.com/5839508/67777543-e1c98c80-fa2f-11e9-98d7-2a6275f0423b.png)

### screengrab 8
![image](https://user-images.githubusercontent.com/5839508/67777567-e9893100-fa2f-11e9-8534-106415c61200.png)

### screengrab 9
![image](https://user-images.githubusercontent.com/5839508/67777698-1a696600-fa30-11e9-99ae-d3dcc1104526.png)

**Comment by robbobfrh84** [comment]
Thanks @desigonz ! I think i know what to do to fix this. 

I did noticed this tough... Is it a known issue ?
- Couldn't find anything related to it in any issues. 
- Trying to figure out if it might be related or not...
- If there is no issue I'll prob. just make one as it's replicated currently in joplin: http://joplin.herokuapp.com/admin/users/add/

![add users bug.gif](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/d24fe2ed-9b50-46e1-b520-6473653d03ed)

**Comment by desigonz** [comment]
@robbobfrh84 oooh yes please make an issue for that user bug!

Ahhh something else I'm noticing:
- [ ] The edit button is gone
![image](https://user-images.githubusercontent.com/5839508/67800004-7cd45d80-fa54-11e9-8e6b-0dc2ae1528d6.png)


compare with:

![image](https://user-images.githubusercontent.com/5839508/67800065-a3929400-fa54-11e9-9e03-c0ccf2013401.png)

**Comment by desigonz** [comment]
Oops too quick on the last one. There are a few things missing:
- [ ] Edit button per content entry
- [ ] Clicking title links to the edit page
- [ ] Dropdown includes
  - [ ] Unpublish
  - [ ] Revisions

![2581-no-edit](https://user-images.githubusercontent.com/5839508/67800864-0fc1c780-fa56-11e9-938f-d116b0eb228b.gif)

compare with staging:
![image](https://user-images.githubusercontent.com/5839508/67800760-dab57500-fa55-11e9-855d-01d75393bfe8.png)

**Comment by desigonz** [comment]
@robbobfrh84 Waaaaait maybe ignore all those. I logged in and then saw all of the edit buttons. What witchcraft!

**Comment by desigonz** [comment]
Okay QA passed!
