### ISSUE TITLE
Delete page from content list view

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2582]
**Acceptance criteria**
- [x] "Delete" is on the menu from the content list view (Figure B)

-----
### previous notes

You can delete a page when you're editing the page itself (Figure A) but not when you're on the content list view (Figure B). Should you be able to do it on the latter?

For comparison, vanilla Wagtail allows you to do it from both.

Figure A
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/d225ca50-bf37-4fc9-948b-c62542aa6687)

Figure B
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/22d42108-0eb5-4ebb-b52d-15d3d7cce48b)

**Comment by toribr** [comment]
Yes, we should put delete back to this menu!

**Comment by desigonz** [comment]
thanks @toribr! added acceptance criteria for dev

**Comment by desigonz** [comment]
@briaguya This one looks good, QA complete!
