### ISSUE TITLE
Behavior of "leave site" alert

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2583]
### As a Joplin user, I want to be alerted when I might accidentally lose content I've worked on but don't want to be annoyed by the messaging when I haven't changed anything.

**Acceptance criteria**
- [x] If you have made a change to the content and you haven't saved, alert should happen.
- [x] If you haven't made a change, or you made a change and then save, the alert shouldn't happen. 
- [ ] If you try to create new content, the alert should not appear.

The alert pops up whenever you are editing a page and then click anything outside of the editing functionality, even if you haven't changed anything. 

tori: this pop-up now also happens on the content creation flow, after the uses clicks "create".
n.b. Our Wagtail Bakery install meets acceptance criteria, so this might just be a matter of rolling back what we've done.

**Comment by briaguya** [comment]
Sounds like we're having trouble understanding when a user has edited content in multiple ways (duplicate revisions as well as this)

Also, looks like this is happening in vanilla too:
![Jul-16-2019 18-16-28](https://user-images.githubusercontent.com/6384156/61336173-ec03aa00-a7f5-11e9-808d-ae669345ee13.gif)


so i'm giving it an 8.

**Comment by desigonz** [comment]
@toribr can you clarify the acceptance criteria "If you try to create new content, the alert should not appear"? Is this via the modal?

**Comment by desigonz** [comment]
@briaguya you sure that this behavior is happening on vanilla Wagtail? Because I just tested it out and didn't see it. My video lives here: https://drive.google.com/file/d/1zMGkSUSwQP_1j8aigpHxt5lRk7ww3Zhf/view?usp=sharing

**Comment by briaguya** [comment]
@desigonz The gif I posted is from @easherma's vanilla UI PR app. The fact that it's happening there makes me worry that somehow our *models* are causing an issue instead of just UI tweaks we've made, which makes me think this one could turn into a rabbit hole.

**Comment by desigonz** [comment]
﻿Mine’s from the same UI PR app! Let’s review this at design-dev sync together.

**Comment by desigonz** [comment]
Oh you mean the Joplin-ified one. Either way let's look at it together.

**Comment by briaguya** [comment]
Hey y'all, look at this! https://github.com/wagtail/wagtail/issues/4978

**Comment by easherma** [comment]
Closed via https://github.com/wagtail/wagtail/issues/4978

**Comment by desigonz** [comment]
Un-closing this. Very exciting that Wagtail has a fix, but we want to make sure this aligns with our acceptance criteria and/or rethink acceptance criteria per their changes.

**Comment by briaguya** [comment]
@easherma just tested out your https://joplin-pr-wagtail-26-upgrade.herokuapp.com/admin/pages/106/edit/ branch and found quite a few issues with our templates not liking the upgrade (looks like some css selectors we had before changed) and I still got a leave site alert trying to leave the edit page. Looks like we've got a bit of work on our side to be ready for 2.6.

**Comment by easherma** [comment]
@briaguya yeah I saw some issues https://austininnovation.slack.com/archives/C8T4YD23T/p1564776471048800

**Comment by desigonz** [comment]
Just QA'd against the acceptance criteria above. It's mostly fixed except for in the instance of the "create new content" modal. I made issue #2790 for it; it's on deck and assigned for next sprint.

**Comment by desigonz** [comment]
Okay and I actually found another bug as well—logged as #2791.
