### ISSUE TITLE
Set up APH's content on Sharepoint

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2585]
Working session to get Laura trained up on Sharepoint and get APH content ready for review.

**Comment by annieszot** [comment]
- [ ] research videos
- [ ] create and send agenda
- [ ] develop workflow for APH

**Comment by annieszot** [comment]
Draft agenda for working session
Walkthrough Sharepoint Online, One Drive 
How to create metadata - editorial process
File uploading/sharing
Calendar view

**Comment by annieszot** [comment]
Met Wed. July 24. Closing
