### ISSUE TITLE
Janis guide mock for community gardens

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2586]
Our goal is to see how the guide content type with a different department's content.

**Comment by chasechenevert** [comment]
Here's the draft of [this content](https://docs.google.com/document/d/1qJxOnPWHso7E2RTdtWavCuZmYpzvDgMNdA7AoDcTlEY/edit#) from #2022.

- There are a number of places where I'm unclear on the content, so I have put placeholders until we can sort it out.
- [This page](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZTo5OTI=) seems to be rendering incorrectly, so I'm not sure what it's supposed to look like. 

https://xd.adobe.com/spec/a7bd4d95-b051-4cce-6b46-0a1c3cbfe370-d18c/

**Comment by chasechenevert** [comment]
@desigonz since we'll have a full working demo of the guide soon, do we still need a mockup or will we just start using Joplin going forward? From what I could tell by the content there weren't any new issues we needed to account for in this guide compared to the mobile food vendor permitting guide.

**Comment by desigonz** [comment]
I leave that up to you and @toribr—we can certainly use the content type, and then flag anything that arises during content pin-up.

**Comment by toribr** [comment]
I think we can close this. Mostly I wanted design to conduct a bit of due diligence around different guide subjects, to see if anything new came up. If @chase thinks not, then we can close this and see how things go as they get implemented.

**Comment by chasechenevert** [comment]
Thank y'all, and I agree. If we run into questions down the road I'll just add the mocks we need into the master.
