### ISSUE TITLE
Prepare mobile food vendor guide content for approval

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2587]
Revise the guide to incorporate:
- [ ] feedback from fact check round
- [ ] user research findings

**Comment by LauraTrujillo** [comment]
@srigdon and I are going to meet tomorrow to talk about the feedback. I'll work on this on Monday, July 28th.

**Comment by desigonz** [comment]
@srigdon Per our discussion, de-prioritizing this for sprint 38. If you finish other sprint goals (or are blocked on OPO things), pick this one back up!

**Comment by desigonz** [comment]
- Wrapping up edits during sprint 39
- Beginning of sprint 40: send out for fact checking
- Incorporate any fact check edits and send for review (hopefully sprint 40)
