### ISSUE TITLE
Objectives 2 and 3 scope and timeline

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2591]
Per the OPO statement of work document, it looks like search/filter and data visualizations are slated to happen September-December, while objectives 4 and 5 (reports and "legacy" docs) are slated for August. However, there is momentum for getting to objectives 2 and 3, and we're not feeling ready for objective 4. Let's revisit the timeline and flesh out the scope!

**Comment by desigonz** [comment]
@oliver2g We still need to update the SOW doc, correct?

**Comment by oliver2g** [comment]
@desigonz I just heard from Marni that Farah wants us to pause work on data visualizations until they hire a data viz person. so we're really looking at scoping out obj 2 and possibly looking at 4 and 5. Let's talk on Monday. Marni will probably reach out to you too.

**Comment by desigonz** [comment]
Yes, let's chat today! Tori has been working on the data visualization and we should let her know.

**Comment by desigonz** [comment]
Backlogging this—OPO priorities shifted.
