### ISSUE TITLE
Add "nondeveloper" input to Wagtail conference 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2594]
Here's a resource to "brain dump" 
https://docs.google.com/document/d/1v4UzAdvq0IAQThmdbVKu7VKV1z3pUhIjfytgSAq4uk0/edit

See #2553 and #2589 

FYI @briaguya @easherma

**Comment by srigdon** [comment]
Added a couple thoughts to the doc.

**Comment by annieszot** [comment]
Awesome thanks @srigdon! Will remove assignment :) Should be ready to close this at or before Sprint Review Thurs.

**Comment by LauraTrujillo** [comment]
I also added a thought or two

**Comment by annieszot** [comment]
Thanks, rockstars! @LauraTrujillo unassigning you :)

**Comment by annieszot** [comment]
Closing. Now with Eric at wagtail space
