### ISSUE TITLE
Make a generic guide image

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#2596]
Until we have the capability to add images to pages in wagtail, we'll need a generic image to be used for the guide.

**Comment by desigonz** [comment]
Photographic vs. graphic?

**Comment by easherma** [comment]
We can add images to pages in wagtail, is there something preventing that...?

**Comment by desigonz** [comment]
No, this is a design issue, not a dev issue. Chase is going to come up with a generic image solution.

**Comment by chasechenevert** [comment]
Here's the default for the MVP. I'm going with a simple line-art style that's simple and clean, and I've added in an accent color to start introducing a little variation within the monochromatic palette we have so far. Long-term I'd like to create something more bespoke for Alpha, and working through this gave me some ideas for the future. 

![Guide_default image_draft 1png-24](https://user-images.githubusercontent.com/7027270/66139866-c0a78480-e5c6-11e9-93f5-3c96ad9469fc.png)

In context: 
![Screen Shot 2019-10-03 at 10 04 26 AM](https://user-images.githubusercontent.com/7027270/66139909-d2892780-e5c6-11e9-952f-5361b2ee2e04.png)
