### ISSUE TITLE
Implement guides: Janis

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2599]
### As a resident, I want to be able to easily understand complex processes at the City so that I know where to start and where I am in the process.

**MVP acceptance criteria in progress**
- [x] Style matches mocks: [desktop](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/58cef195-a92f-450c-ba2e-4124f44b9469/Template-Guide-desktop) for intro section and right column, [mobile](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/a5132472-47f7-4fa1-ba90-223af090026f/Template-Guide-mobile-1)
- [x] Intro block include guide title, description, image
  - [x] download links are post MVP
  - [ ] If author doesn't add an image, use generic image (see #2596)
- [x] Guide aggregates content from information and service pages under sections
  - [x] Contact information
    - [x] Border on the contact information, matches design specs
  - [x] Checklist
    - [x] Checklist is an information page (content editors will use `</br>` to create line breaks)
    - [x] For MVP, don't generate PDF size
  - [x] Content sections
    - [x] Section title in blue boxes per mocks
    - [x] Display page content per mocks 
    - [x] Autogenerated section number labels (ex. "Learn and prepare 1 of 6")
    - [x] At the bottom of each page or service block, link to the originating info ("View this page on alpha.austin.gov")  behavior—open in a new tab

**Post MVP—don't implement now**
- [ ] Download checklist 
- [ ] Download application documents
- [ ] Checklists
  - [ ] Bullet style with checkbox
  - [ ] Need to not have to use code to create line breaks
- [ ] Documents section behavior
  - [ ] Lists all the documents that are linked to within the guide. Note that this includes CoA documents that are pointed to within pages, but not documents that are linked to that are not CoA.
  - [ ] Headings correspond to the sections in which the documents originated
  - [ ] ❓Clicking on a document name opens the file in a new tab
  - [ ] ❓(For MVP?? This could be curated by a content editor, so instead include this in style guide/content governance documentation) In the case of duplicate documents (found on one or more pages), the preferred behavior would be to show the document where its first referenced within the guide. We want to avoid duplicating links because that's confusing to users. For example, if an application doc is linked to in Section 1 and then again on a different page in Section 3, then only show that document in Section 1 of Documents, but not again in Section 3.

**Comment by desigonz** [comment]
- [ ] @chasechenevert to deliver mobile designs to @briaguya for Janis implementation

**Comment by desigonz** [comment]
@briaguya 

The URL that opens for "View this page on alpha.austin.gov" should be: 
- [ ] If we have a topic, use the first topic
- [ ] If we don't have a department, use the first department

**Comment by desigonz** [comment]
@briaguya okay if we move this one to QA?

**Comment by desigonz** [comment]
Assigning myself and @chasechenevert to QA this!

**Comment by desigonz** [comment]
- [ ] Description field doesn't style distinct from the rest of the body content (see screenshots 1 and 2 below). @chasechenevert can you provide specs for the description field style in guides?
- [ ] "View this page on alpha.austin.gov" links don't work. Should open page in new tab.
- [ ] Headings are problematic—titles for pages that are dynamically getting pulled in are styling as H2, and so is the next heading level down. (See screenshot 3.) This makes sense on a standalone page, but not within a guide, which has two layers of headings above it—the guide title (H1), and the section title (which seems to be styling as an H1 but semantically doesn't make sense to me) @chasechenevert can you review?


**Screenshot 1**
Left: service page; right: guide
![image](https://user-images.githubusercontent.com/5839508/63302765-982c2b00-c2a3-11e9-9545-93012ac56882.png)

**Screenshot 2**
Left: service page; right: guide
![image](https://user-images.githubusercontent.com/5839508/63302842-ca3d8d00-c2a3-11e9-97f3-fcac1f00e1b3.png)

**Screenshot 3**
Left: service page; right: guide
![image](https://user-images.githubusercontent.com/5839508/63302943-0cff6500-c2a4-11e9-8ae0-36eca2bef740.png)

**Comment by chasechenevert** [comment]
**Page descriptions** should appear similarly to other pages on Janis, with a slight difference in the distance between the page description and main body content (to account for the lack of a heading background when they're displayed in guides). 

```
font-size: 2.4rem;
margin: 3rem 0 0 6rem;
```

### Screenshot
I've added a page description example to the mock, and added this updated mock into the master. 
 
<img width="831" alt="Screen Shot 2019-08-21 at 4 01 38 PM" src="https://user-images.githubusercontent.com/7027270/63468247-ff291b80-c42c-11e9-8932-fa7687b72fc8.png">

**Comment by desigonz** [comment]
Thanks @chasechenevert! Assigned back to @Niicck and placing on deck.
