### ISSUE TITLE
2nd round of Funshops I-III

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#26]
2nd round of Funshops I-III
- [x] Invite Sara Smith (CTM), Sara Parelta, Happiness Kisoso, Aly Van Dyke, Library team, Bloomberg team to Funshop I

- [x] Schedule Funshop I at Faulk for the last week of April (tentatively 4/24?)

- [x] Tell people to bring something to write on

- [x] Figure out parking (will we have passes for them?)

- [x] Forward Funshop 1 at New Central Library (on May 9th) invite to anyone who cannot attend Faulk Funshop. (Max capacity 24 attendees)

- [ ] Include parking directions and phone number (either LT's or Tatiana's)

- [ ] Schedule Funshop I with EMS
- [ ] Schedule Funshop I with DSD

**Comment by LauraTrujillo** [comment]
@amenity we'd like to have Funshop I at the end of April- and there will be two chances for people to come! @ashleecoa and I want to host one session here at Faulk during the last week of April, and the library has offered to host another session of Funshop I on May 9th. In order to keep it fair (and meet the demand... that I don't think I'm imagining) both sessions will be open to all city employees and not just APL peeps. However, the one on the 9th will probably have less space but will serve as a second chance for people who can't make it to the Funshop I in April.

**Comment by courtneyjacinic** [comment]
@LauraTrujillo could you update with Libraries requests and steps to make this happen?

**Comment by LauraTrujillo** [comment]
closing because it's different in practice. more of a rolling Funshop I instead of a Funshop series set.
