### ISSUE TITLE
Implement guides: Joplin

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2600]
### As a content editor, I want to be able to author guides that allow residents to easily understand complex City processes, so that residents know how to start the process and where they are in the process.

See #2599 for Janis acceptance criteria.

**MVP acceptance criteria in progress**
- [ ] The following fields are required:
  - [x] Topic
  - [x] Title
  - [ ] Description
  - [x] Contact 
 - [x] Section title
  - [x] Ability to pick pages within each section
- [x] Ability to change the order of pages within a section

- [ ] The following fields are optional:
 - [ ] Image (default image supplied by @chasechenevert) but author can upload one

### Post-MVP
- [ ] Ability to upload/host files on Joplin for guide MVP (make an issue for this)
- [ ] Minimum required section behavior

**Comment by briaguya** [comment]
@desigonz I think this is something we need to sync on, putting a 13 on it for now but that may change.

From a Joplin stand point, this should include:
* Authors can create new guides
* Authors can associate content from other pages into the guide (what does this look like?)
* The API exposes all the information Janis needs to build a guide page
  * It would be really helpful to have an example guide and all the pages it pulls from here

**Comment by desigonz** [comment]
Thanks @briaguya! Acceptance criteria forthcoming; will have by end of sprint (and hopefully by dev-design sync next Tues, when we'll be reviewing the designs)

**Comment by toribr** [comment]
![1851 Guide](https://user-images.githubusercontent.com/3790067/61463222-96d0b100-a939-11e9-8106-3ff215d0aa96.png)

There are a few question on this comp that have to do with how the backend of Joplin will deal with adding both sections and URLs, but this is a detail that more has to do with the visual implementation than anything. 

@desigonz We need to also decide as to what's required, and how to handle the contact info. Note that as the page templates get more complicated, the style guide becomes more important. Also - we should keep in mind that there should be a clear delineation between how to fill out the form (helper text, which is on page) and what to put in the fields (style guide). See notes on the comp.

**Comment by desigonz** [comment]
Parameters for page picker—limited to service pages, info pages that are LIVE.

**Comment by desigonz** [comment]
What happens if someone unpublishes an info page that is part of a guide?

**Comment by toribr** [comment]
Updated MVP version with out of the box (as I understand it) controls of header/pages functionality. 
![1851 Guide](https://user-images.githubusercontent.com/3790067/62245065-5562eb80-b3a6-11e9-83de-c71f1a9c0858.png)

**Comment by desigonz** [comment]
Assigning myself to QA this!

**Comment by desigonz** [comment]
Did some QA. Here's what needs fixin':
- [ ] Description field should be required
- [ ] Remove colons at the end of each field label throughout content type (see screenshot), including for:
  - [ ] Select a topic (also, please lowercase "topic"!)
  - [ ] Make this page a top link for this topic
  - [ ] Related department
  - [ ] Section heading
  - [ ] Pages
  - [ ] Contact

![image](https://user-images.githubusercontent.com/5839508/63301540-6a91b280-c2a0-11e9-848d-29ecbbaedc2b.png)

**Comment by desigonz** [comment]
Per conversation with @briaguya and @Niicck today, seems like we should backlog these improvements until Joplin 3.0. Is that correct?
