### ISSUE TITLE
Save button when creating a contact

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2605]
**Describe the bug**
When you create a new snippet (location, contact, map), there is no "save" button. (There is, however, a save button on existing pages.)

**Acceptance criteria**
- [x] There is a save button and it saves a new map/contact/location.
- [x] Save button pattern matches existing contact save button

**URL**
https://joplin.herokuapp.com/admin/snippets/base/contact/add/ 
https://joplin.herokuapp.com/admin/snippets/base/location/add/ 
https://joplin.herokuapp.com/admin/snippets/base/map/add/ 

**Screenshots**
New contact—no save button anywhere
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/d761ec64-6741-4e4a-8a49-9e292a1ae1b2)

Existing contact—save button
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/3bfa5dc9-f4c3-4e94-a307-ddf5325b6bdd)

**Comment by easherma** [comment]
This is because we hide the default action bar with css.

**Comment by briaguya** [comment]
@desigonz I think we should get design involved here. I'm happy to do a quick fix and just unhide the bottom action bar for now but I think we should address this in a "what does adding contacts look like" way as well. My 1 is for the "unhide the action bar" solution.

**Comment by desigonz** [comment]
@briaguya yep, we have #2571 for reviewing the contact Joplin experience, and #2364 for rethinking contacts w/r/t maps and locations. For now we def need this quick fix!

**Comment by desigonz** [comment]
@briaguya This looks great, thank you! QA complete.

**Comment by desigonz** [comment]
@briaguya This is still happening in Joplin staging—where/how can we preview this?
