### ISSUE TITLE
Contacts — remove "Copy content from:"

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2606]
**Describe the bug**
"Copy content from:" language shouldn't be on the contact pages.  

**Acceptance criteria**
- [x] "Copy content from:" and buttons doesn't appear when you create a new contact
- [x] "Copy content from:" and buttons doesn't appear when you edit an existing contact

**URL**
adding a new contact: https://joplin.herokuapp.com/admin/snippets/base/contact/add/
existing contact: https://joplin.herokuapp.com/admin/snippets/base/contact/2/

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/85de844d-cc15-4b67-ac10-f691603df9d5)

**Comment by briaguya** [comment]
@desigonz are there places where we *do* want to see this?

If we want to just hide it everywhere full stop that's like a 1, but if there are conditions under which we want it and others where we don't then it may be more of a 3-5.

**Comment by desigonz** [comment]
That's a good question. The "Copy content from" predates me and I don't totally understand it. @LauraTrujillo and @toribr, can y'all weigh in?

**Comment by toribr** [comment]
@desigonz I have no idea where this came from.

**Comment by desigonz** [comment]
@briaguya Looks good! QA complete.
