### ISSUE TITLE
Content review of content type descriptions

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#2608]
Please review the descriptions of page type, and add edits here:
![Select content type a](https://user-images.githubusercontent.com/3790067/61330870-3b41de80-a7e6-11e9-9708-39eb71b48a45.png)

**Comment by easherma** [comment]
@briaguya I'm thinking if we get these nailed down it would be great to stick them in a docstring or other object associated with each model and have them populate dynamically. Same with the list of available models themselves.

**Comment by LauraTrujillo** [comment]
Duplicate-ish of #2610

**Comment by LauraTrujillo** [comment]
@toribr @desigonz I updated the descriptions in the [content model doc](https://docs.google.com/spreadsheets/d/1ZkH93F4tJ0_Zjx4t8k6k6TgwSlOh8u8ejWmegE6WqH0/edit#gid=46035360).
