### ISSUE TITLE
Create content modal screen titles & copy

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#2610]
Verify content of titling screens for all page types, and add language where needed
 
Content team: add necessary below and I'll update the comps.

Service page:
verify it's still ok: @toribr just change the dept. name bullet to "You don't need to include your department's name in the title"
![Screen Shot 2019-07-16 at 5 00 02 PM](https://user-images.githubusercontent.com/3790067/61332945-2d428c80-a7eb-11e9-8c23-ad804f904552.png)

Information page
![Screen Shot 2019-07-16 at 4.52.39 PM.png](https://images.zenhubusercontent.com/5a81e99a4b5806bc2bc6a146/20dd1e98-70a3-4c98-bf00-5d8090efb61b)
Needs new header at min.
header: Write a clear, descriptive title
example: Hepatitis in Austin
bullets: 
- "Use primary + secondary keywords" to the current bullets
- Use simple, accessible language
- Use words you think residents may search to find the service
- You don't need to include your department's name in the title

Department page
![Screen Shot 2019-07-16 at 4.54.50 PM.png](https://images.zenhubusercontent.com/5a81e99a4b5806bc2bc6a146/aeacb121-9f1e-43a2-b282-0e5e59a4d137)
example: Office of Police Oversight
helper bullets: You don't need to include "Austin" in your department name. *Note for ODD- is that going to rock the boat too much?*

Guide page:
none exists - start from scratch
header: (tori: write a name for your guide)
example: (tori: Guide for starting a community garden)
bullets: (tori: • Use the word "guide" in your title, etc.)
- Use the word "guide" in your title
- Use simple, accessible language
- Use words you think residents may search to find the service
- You don't need to include your department's name in the tile

Form:
none exists - start from scratch
header: Write a clear, descriptive title
example: Request a day laborer
bullets: Make it clear what residents can accomplish when they fill out this form
- Don't use jargon or acronyms
- Use simple, accessible language
- Use words you think residents may search to find the service

**Comment by LauraTrujillo** [comment]
We're closing #2608 (duplicate) so here's @easherma's comment: 
@briaguya I'm thinking if we get these nailed down it would be great to stick them in a docstring or other object associated with each model and have them populate dynamically. Same with the list of available models themselves.

**Comment by LauraTrujillo** [comment]
@toribr @desigonz ready for your eyes!

**Comment by desigonz** [comment]
Thanks @LauraTrujillo! Interesting question about dropping "Austin" in office titles. I noticed that, for the Drupal 8 site, CPIO is dropping some of the Austin's but not all of them:
![image](https://user-images.githubusercontent.com/5839508/62483625-c70fb080-b77d-11e9-8691-188c0e0df940.png)

I wonder if some of them are strong brands that would be difficult to remove the "Austin"—example "Austin Energy" or "Austin Animal Center" (although I see they are listed as "Animal Services" !!)

Some things we should maybe do:
- [ ] Get in touch with CPIO and learn about how they made these decisions
- [ ] Discuss at an upcoming content pinup and decide on conventions

**Comment by desigonz** [comment]
@toribr Anything else you need to add? Mocks to update? Otherwise, move into "review" pipeline and assign me—I'll make an issue for devs with acceptance criteria.

**Comment by LauraTrujillo** [comment]
Sent to translators last week, waiting to get it back.
