### ISSUE TITLE
Review character limit UX

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2611]
We have character limits for certain fields, but they're not consistently labeled. Let's review:
- [x] Where we message character limits (in the create content modal? when editing a page?)
- [x] How we do error message for character limits
- [x] Additionally, let's run the character limits by the content team and make sure they're consistent with our google doc templates
- [ ] https://github.com/cityofaustin/techstack/issues/2193 
character limit by language also is effected, as translation fields show up in different places. 

Because shorter writing is essential to readability, character limits should be an integral part of an authoring interface.

**Comment by toribr** [comment]
![Screen Shot 2019-08-01 at 2 11 25 PM](https://user-images.githubusercontent.com/3790067/62320664-65da9b00-b466-11e9-8450-7de179df9ba8.png)
A character count pattern has been used in the content creation modal - it shows both characters left, and then switches to red type and negative number when the count goes over. 
![Screen Shot 2019-08-01 at 2 28 42 PM](https://user-images.githubusercontent.com/3790067/62321636-b7842500-b468-11e9-87a7-0ddf573da06d.png)

This pattern should be duplicated to relevant fields on page templates.

**Comment by LauraTrujillo** [comment]
Reviewed character limits and created parity between content model doc and google doc templates

**Comment by desigonz** [comment]
thanks @LauraTrujillo!

**Comment by desigonz** [comment]
@toribr Anything else you need to add? Otherwise, move into "review" pipeline and assign me—I'll make an issue for devs with acceptance criteria.

**Comment by toribr** [comment]
Not at this time, but do please note that character counts for other languages will be different.

**Comment by desigonz** [comment]
@toribr Great thank you! Acceptance criteria lives in issue #2734. How does this sound for translation character counts? Or have it appear for those but at whatever arbitrary number we increased it to?
> Character limits only appear for English content; in other languages, don't include (this is because translations can be longer than English; I believe we've already set the character count higher for Spanish?)
