### ISSUE TITLE
GlobalNav: Improve leading issue for theme labels 

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#2614]
# Primary nav leading
### Issue
Leading is too wide for theme menu items at the mid breakpoint, and the vertically centered positioning is awkward next to menu items like "Pets" and "Jobs" that doen't break lines.

### To do
- [x] Narrow leading 

### As implemented
<img width="962" alt="Screen Shot 2019-07-16 at 6 34 49 PM" src="https://user-images.githubusercontent.com/7027270/61337020-39cde180-a7f9-11e9-9ec1-46fe719995f8.png">

**Comment by desigonz** [comment]
You might also want to take a look at Spanish, which tends to use more characters than English: 
![image](https://user-images.githubusercontent.com/5839508/61908637-bba6c480-aef5-11e9-9f54-fe809e6953f2.png)

**Comment by desigonz** [comment]
You might also want to look at Spanish: 
![image](https://user-images.githubusercontent.com/5839508/61908670-ceb99480-aef5-11e9-9c67-d8706b34318c.png)

**Comment by chasechenevert** [comment]
## Changes
**Leading**
- add: `line-height: normal;` to `.coa-ThemesNav__link`

<img width="880" alt="Screen Shot 2019-08-07 at 2 34 34 PM" src="https://user-images.githubusercontent.com/7027270/62652538-3d98e380-b921-11e9-94db-b1c06554b7ac.png">

**Breakpoints**
- Still working through this, but given that we have 7 themes in the `ThemeNav`, and keeping in mind that search and translation will put further strain on comfortable spacing here.

**Comment by desigonz** [comment]
@chasechenevert to specify breakpoints

**Comment by chasechenevert** [comment]
Changing the estimate on this one because it's not as simple as reducing the leading/line height. What we have now isn't great, and it's worse in Spanish. The bigger issue is that we need a better way to display navigation when screen width is below the desktop size, and without dropping type size below 16 points to remain accessible. 

We may have need to use the mobile menu for the breakpoints between 1080 and 768. I'll need to mock this up.

**Comment by chasechenevert** [comment]
## Problem statement
In Spanish, themes with long titles are breaking to 3 lines at responsive breakpoints. This stacking causes the theme bar stretch vertically way, looks awkward next to themes with fewer words in the title.

## Solution
- [ ] Line-spacing from 2.8rem to 2rem
- [ ] 768 < 1080 breakpoint: font-size reduced to 1.4rem. This will at least reduce the number of line breaks.
- [ ] align theme text to the top, so that shorter theme titles don't appear vertically centered 

### Screenshots
**Before**
<img width="769" alt="Screen Shot 2019-09-30 at 11 58 55 AM" src="https://user-images.githubusercontent.com/7027270/65899809-28b55b00-e37a-11e9-8920-1f4943d77eb1.png">

**After**showing the design at 768px browser width (this is the mid breakpoint, <768 goes to the mobile version), and line-spacing: 2rem. 
<img width="769" alt="Screen Shot 2019-09-30 at 11 59 04 AM" src="https://user-images.githubusercontent.com/7027270/65899818-2d7a0f00-e37a-11e9-86d3-87e3c41813d7.png">

## Next steps
While this works for now, we’re still holding on to a menu design that predated both my and Tori’s time on the project. We know there will be more issues in the future once we have more content under each theme, get Kristen’s report on tree testing our IA, and (far further in the future) add search into the global nav.

It’s premature to launch into a redesign of the menu right now since we don’t have that enough content or research to inform a solution, but I will start documenting examples out on the interwebs that solve similar challenges we’re dealing with.

**Comment by desigonz** [comment]
Thanks @chasechenevert! Made #3074 with acceptance criteria for dev. Can you give this issue a size and then close it? Just want to make sure we're properly estimating our effort.
