### ISSUE TITLE
Create a new loading icon for Joplin

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#2616]
Right now there's a really hacky looking "LoAdIng" icon in Janis. Let's give the develops something decent to swap it with.

**Comment by easherma** [comment]
@briaguya we have a spinner that we use when the site is originally loading that we could probably just use there as well, no?

**Comment by toribr** [comment]
@briaguya @easherma Let's discuss what we can implement prior to @chasechenevert spending time on this.

**Comment by desigonz** [comment]
This is related to #2354, which @briaguya just fixed in [PR 459](https://github.com/cityofaustin/janis/pull/459) but hasn't been merged to staging yet. Leaving this issue open for the design team's ideal solution but moving it to the short-term backlog.
