### ISSUE TITLE
Calendar icon does not pull up calendar

### ISSUE THREAD

**Issue by oliver2g** [cityofaustin/techstack#2622]
Clicking the calendar icon in the date field "closes" the keyboard and does not pull up a calendar.

**URL tested:** https://opo.austintexas.io/request-day-laborer/2309-day-labor/form

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+6&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fopo.austintexas.io%2Frequest-day-laborer%2F2309-day-labor%2Fform&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://opo.austintexas.io/request-day-laborer/2309-day-labor/form&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 6 |
| Browser | Mobile_safari |
| Operating System | iOS 11.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.3 x 4.1 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/050d9264d6c818e2c2c54e59c827675676113e05/realios_iPhone_6.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/050d9264d6c818e2c2c54e59c827675676113e05/realios_iPhone_6.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+6&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fopo.austintexas.io%2Frequest-day-laborer%2F2309-day-labor%2Fform&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://opo.austintexas.io/request-day-laborer/2309-day-labor/form&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by desigonz** [comment]
Agreed, thanks @Niicck!
