### ISSUE TITLE
In page edit - content tools

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#263]
We have lots of research on the struggles staff face maintaining excellent content with the current CMS. What will their struggles be when they are hand transferring content from there to Austin.gov? How might we address them? 

What would our greenfield-solutions look like? What are stopgap tools/instructions we could use initially?
These features might already exist in a CMS, so this relates to #190, too. 

Ideas
- Reading level info
- Acronym detector
- Grammar
- Character count
- File upload barrier. 
...

**Comment by toribr** [comment]
v1 design done, testing next
