### ISSUE TITLE
Allow production coa-forms deployments for all forms

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#2630]
Scaling this back to manually get "Request a day laborer" form into production
-----

There is a maze of stuff going on in CloudFront that has to get fixed if we want to deploy more than just the OPO form on the production forms.austin.gov url.

**Comment by Niicck** [comment]
"Request Day Laborer" is live in prod.

English: https://forms.austin.gov/request-day-laborer/form
Spanish: https://forms.austin.gov/request-day-laborer-es/form

**Comment by desigonz** [comment]
@Niicck Beautiful! As you pointed out, Spanish URL should be `solicite-un-jornalero`. Sorry for missing that :( Back to you!

**Comment by Niicck** [comment]
voila.
https://forms.austin.gov/solicite-un-jornalero/form

**Comment by desigonz** [comment]
You are great! One last thing: 

- [ ] when you click on "Español," you get taken to https://forms.austin.gov/solicite-un-jornalero/form

(currently it's sending to the old URL which just redirects to alpha)

![image](https://user-images.githubusercontent.com/5839508/64343126-90fa6200-cfb1-11e9-9dbd-3dd2e40ae307.png)
