### ISSUE TITLE
Weird & skinny step with options

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2632]
**Describe the bug**
When filling out a service page, the option fields don't stretch across the whole screen. It becomes awkward to write in such narrow fields.

**URL**
https://joplin.herokuapp.com/admin/pages/91/edit/

**To Reproduce**

1. Go to 'https://joplin.herokuapp.com/admin/pages/91/edit/'
2. Scroll down to steps
3. See error

**Current behavior**
Step with options fields appear at half width
![image](https://user-images.githubusercontent.com/5839508/62064014-9d8cdd00-b1f1-11e9-994b-ee73d321d1ee.png)

**Expected behavior**
Step with options field stretches across full width

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/502a0832-599a-482b-a5df-95ed2bb6c55b)

**Device**

**Browser**

**Additional context**

**Comment by easherma** [comment]
Probably just need to set a max-width thing here.

**Comment by briaguya** [comment]
@desigonz I have a quick fix in https://github.com/cityofaustin/joplin/pull/323 that gets us from:
## BEFORE
<img width="1046" alt="Screen Shot 2019-08-06 at 10 04 09 PM" src="https://user-images.githubusercontent.com/6384156/62591738-3aa4e100-b896-11e9-94a6-da852fa31af5.png">
to

## AFTER
<img width="1035" alt="Screen Shot 2019-08-06 at 10 09 29 PM" src="https://user-images.githubusercontent.com/6384156/62591945-f9610100-b896-11e9-8e62-1c7f8d9a4687.png">

I know it's probably not perfect but I figure we should put off any bigger improvements until we rethink our streamfield strategy with react-streamfield etc.

**Comment by desigonz** [comment]
assigning @toribr to QA

**Comment by toribr** [comment]
Not perfect as mentioned but will suffice for now.
