### ISSUE TITLE
Add OPO anonymous complaint translations to Joplin

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2633]
- [x] Add translations to thank you service page
- [x] Add translations to complaint service page
- [x] @srigdon to QA and confirm when they're looking good

**Comment by desigonz** [comment]
Thank you preview: https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxMDQ0
Complaint preview: https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxMDQx

Assigning @srigdon to QA. Please make sure all of the translations appear where expected, that hyperlinks take you to the correct doc, etc!

**Comment by srigdon** [comment]
🚫 Thank you preview in Spanish was showing these errors: 

1. The office's name isn't translating, which is a known issue, can't find the number right now. 
2. Caught some accents missing on the office's name in the mail option, fixed 'em: 
<img width="627" alt="Screen Shot 2019-08-01 at 4 09 25 PM" src="https://user-images.githubusercontent.com/5445796/62328967-303fad00-b47a-11e9-95a1-e68bcb801304.png">
3. Caught these missing "About this service" and "Remain anonymous or ask to follow up" sections, and I attempted to fix them but let me know if it's reading wrong, @desigonz. 
<img width="698" alt="Screen Shot 2019-08-01 at 4 30 54 PM" src="https://user-images.githubusercontent.com/5445796/62329041-5a916a80-b47a-11e9-8200-b34f5d9111ad.png">
4. Also a known issue, the second sentence in the footer is all title case-y. See #2643. 

🚫 Complaint preview in Spanish was showing these errors: 

1. Same office name translation issue as above. 
2. Same accents issue as above, fixed it. 
3. Same footer issue as above.

**Comment by desigonz** [comment]
Thanks @srigdon!

The following two images are the thanks form in English and Spanish. I'm noticing a discrepancy in content—Spanish doesn't have the "Be aware" part. What's correct?
![image](https://user-images.githubusercontent.com/5839508/62332245-5c602b80-b484-11e9-96c0-c413781b5240.png)

![image](https://user-images.githubusercontent.com/5839508/62332257-61bd7600-b484-11e9-99e4-518103bd00fd.png)

**Comment by srigdon** [comment]
@desigonz Whoops! Good catch. IIRC we decided the copy starting "Be aware" and the bullet points after it don't make enough sense to keep even if technically correct, so I deleted it. I did keep the sentence thanking people for their feedback and added it on the Spanish page.

**Comment by desigonz** [comment]
Great! Closing this issue if that's alright with you.
