### ISSUE TITLE
OPO service pages 404ing

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#2636]
## bug report

**Describe the bug**
The service pages for OPO thanks and complaints are both assigned to the Office of Police Oversight department page, and the URLs below we had for these pages (that reflect how you would navigate via the department) are now 404-ing. 
- https://alpha.austin.gov/en/police-oversight/file-a-complaint-about-an-austin-police-officer
- https://alpha.austin.gov/en/police-oversight/thank-an-austin-police-officer

Also, on the page that does publish, the "Offered by:" department doesn't show—see screenshot.

Could this be related to #2271?

**Screenshots**
![image](https://user-images.githubusercontent.com/5839508/61966291-ed706780-af97-11e9-860a-4fc6c7dfab6b.png)

---
## @srigdon's original bug report; also see below

**Describe the bug**
Here's what I did: 

1. Drafted and published these two service pages without adding them to a topic or topic collection: 
https://alpha.austin.gov/en/police-oversight/file-a-complaint-about-an-austin-police-officer
https://alpha.austin.gov/en/police-oversight/thank-an-austin-police-officer

2. Drafted and published a topic collection page (Police oversight). https://alpha.austin.gov/en/health-safety/police-oversight-2/ 

3. Drafted and published a topic page (Police feedback and records). https://alpha.austin.gov/en/health-safety/police-oversight-2/police-feedback-and-records 

Now, when I click "view live" for each of the following pages, this is what happens: 

Both of these pages are 404ing: 
https://alpha.austin.gov/en/police-oversight/file-a-complaint-about-an-austin-police-officer
https://alpha.austin.gov/en/police-oversight/thank-an-austin-police-officer

The "Police oversight" topic collection page is working: https://alpha.austin.gov/en/health-safety/police-oversight-2/ 

And the "Police feedback and records" topic page was just opening a new tab with the Joplin Content page. But then, I clicked "edit" and that worked. I then saw I hadn't yet added a topic collection to it, so I added the "Police oversight" topic collection page to it. Then I updated it, and viewed live, and now that results in a 404. https://alpha.austin.gov/en/health-safety/police-oversight-2/police-feedback-and-records 

Is this because you can't create pages or end nodes without first creating the topic collection and topic for it? Or something else? 

**To Reproduce**
1. Go to https://joplin.herokuapp.com/admin/pages/3/
2. Search "police" and all of these pages should come up. 
3. View any of the broken ones live. 
4. See 404s

**Device**
Macbook Air

**Browser**
Chrome

**Comment by desigonz** [comment]
@srigdon I think some of the 404s happened for topic/topic collections are because Janis can take up to 6 or 7 minutes after publishing on Joplin to deploy a build—so there's lag between when you publish and when you see the effect take change. (This is a content editing user experience thing we might want to look into, but I'm going to consider it separate from this bug.)

However, it looks like you have OPO assigned as the department for both of those pages, and that's not appearing on Janis. I'm going to rewrite the bug issue to reflect that.

**Comment by briaguya** [comment]
@desigonz @srigdon this is because we are now using the multiple departments instead of the single department field on our pages. I've updated them in Joplin and there are no longer 404s. I also have a PR out (https://github.com/cityofaustin/joplin/pull/306) to remove the confusing double fieldness

**Comment by briaguya** [comment]
Joplin prod no longer has both a "department" and "related departments" field, it just has "related departments"

I don't know why this is marked as blocked because it's fixed now. Closing it.

**Comment by desigonz** [comment]
thank you thank you @briaguya!
