### ISSUE TITLE
"Option" field in information page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2637]
- [ ] Should be centered

With design and content team, we should review options in information pages. We don't use them currently, and with this design, they can only appear above any other body text.

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/7b50e4f9-e8fa-4098-8766-f09e3b9c0d24)

**Comment by briaguya** [comment]
@desigonz this centering issue is definitely the same thing as #2607

**Comment by desigonz** [comment]
We've removed options in info pages for now, so closing this
