### ISSUE TITLE
Update Greenhouse job postings to include salary and benefits info

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2641]
### As someone applying for an ODD job, I want to see salary and benefits information when reviewing a job description on Greenhouse, so that I don't waste my time applying for a job that doesn't offer the salary and benefits I need.

Per sprint retro—we noticed a discrepancy between ODD website and Greenhouse postings.

**Comment by desigonz** [comment]
@oliver2g is this one complete?

**Comment by oliver2g** [comment]
yes
