### ISSUE TITLE
Footer copy changes

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2643]
**Acceptance criteria**
- [ ] In English, lowercase "project site"
- [ ] In English and Spanish, "austintexas.gov" should all be lowercase. (We only capitalize a URL if it begins a sentence.)
- [ ] In Spanish, sentence case for the following sentence: "Encuentre más información en nuestro sitio del proyecto"
- [ ] In Spanish, project site hyperlink should only be applied to "sitio del proyecto," not the full sentence

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/6681b5d7-3b37-4836-a46b-b5e38b578ee7)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/f1d856e0-90f2-4ee0-b45f-009ede431788)

**Comment by desigonz** [comment]
Can't figure out where to update these—when I search on the Janis repo, they appear as expected.

![image](https://user-images.githubusercontent.com/5839508/62061550-058cf480-b1ed-11e9-990c-20ae2a57df6b.png)

**Comment by briaguya** [comment]
in staging now

**Comment by desigonz** [comment]
beautiful, back to you.
