### ISSUE TITLE
Schedule APH funshop

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2646]

**Comment by LauraTrujillo** [comment]
@annieszot I'm going to connect you and @desigonz with Jen S. again and hand this off to you.

**Comment by annieszot** [comment]
Sounds great!

**Comment by annieszot** [comment]
Phone call/Email to Jen Samp for proposed September dates (all 10am-noon)
Tuesday, September 17
Wednesday September 18
Wednesday September 25 
 
Will do a friendly follow-up Tuesday, August 13 if don't hear back.

**Comment by LauraTrujillo** [comment]
Check-in with Ben or Marni for who to contact to reserve the Bull Pen.

**Comment by annieszot** [comment]
Follow-up email sent Friday, August 16,

**Comment by desigonz** [comment]
Let's follow up by 8/28 if we haven't heard back.

**Comment by annieszot** [comment]
Funshop date confirmed with Jen 9/25!
I have the 25th reserved for yall. Dee Dee said she couldn’t segment the APH Drupal editors out of her list. So I’m still waiting to hear back from our employees. I’ll update you this week.
Will create a new issue to reserve the bullpen :)
