### ISSUE TITLE
Share Wagtail Space learnings

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2647]
**Objective** 
Brian and Eric went to Wagtail Space to learn about all of our questions, compiled in #2553. Let's share out!

**Participants**
@briaguya and @easherma will present to the team

**Agenda**

------
- [x] Schedule meeting (8/1 at 11am)
- [x] Meet
- [x] Create resulting issues

**Comment by desigonz** [comment]
Notes from the conference: https://docs.google.com/document/d/1RGWCd66fHoh7qvOvtkk7t69kcqAYwgN0LX7BhpBPu7Q/edit?usp=sharing

**Comment by briaguya** [comment]
investigate available options better selection flows
* https://wagtail-autocomplete.readthedocs.io/en/latest/
