### ISSUE TITLE
Official document style guide

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2648]
### As an OPO content editor uploading official documents, I want to be able to refer to the style guide on how to use this content type so that I can successful and consistently communicate with residents.

We are implementing the official document content type. We need a style guide entry to correspond to it. This will provide guidance to OPO content editors on how to use the content type. We'll also use this when we train the OPO team on using Joplin to add new content using this content type.

**Comment by srigdon** [comment]
[Draft document](https://docs.google.com/document/d/1xxLLPEH3INKf1WvJYWIkSlHfK5jL_Tl2BPFA-1EubvY/edit) in progress.

**Comment by desigonz** [comment]
@srigdon Also de-prioritizing for sprint 37, but keep on jotting down notes as you work on the docs!

**Comment by srigdon** [comment]
I'll be wrapping this up next sprint after a meeting with Mia and Sara this Friday.

**Comment by ablangworthy27** [comment]
I drafted this in the google doc. Throwing it to @srigdon for review.

**Comment by srigdon** [comment]
Looking good, @ablangworthy27! See the draft doc for edits in line. 

Passing to @Jo-Dwyer for review and implementation. Let me know if you have questions or if I can help put it in the style guide.

**Comment by srigdon** [comment]
Per sprint planning meeting 10/17, we're going to publish this section of the style guide and discuss the following question at the [next content pin-up meeting](https://github.com/cityofaustin/techstack/issues/3198): 

> Should we include instructions and screen shots for how to use Joplin? (It'd be more thorough and clear, but not as evergreen.) If so, how will we review the style guide for changes to Joplin?

**Comment by desigonz** [comment]
@srigdon With Joplin in flux so much, I don't think it's valuable to include any screenshots or specific directions about the interface (for example, "use the button at the top of the screen"). I think for now that kind of training will have to be more face-to-face, one-on-one sessions.
