### ISSUE TITLE
Refactor "groupTitleSubPath" and other "subpath" props

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#265]
In https://github.com/cityofaustin/janis/pull/214#discussion_r180275059, @ifsimicoded said:

> The more I see this subpath thing everywhere for topic pages and theme pages, I get bad vibes. Maybe there's a better way to define topic links and theme links... or links in general... in just one place. This type of thing seems like it's a middleware transformation that should be done once wherever the topmost data comes through. Maybe in a clean data step at the page level with all the other clean data steps for RouteData. Or in LanguageWrapper for SiteData things. What do you think?

We had talked about adding awareness in Joplin of longer paths instead of just slugs, but that wouldn't be relevant in this use case navigation. I'm not sure I know a better way at this point so just going to log this as technical debt for now while we think about it.

**Comment by easherma** [comment]
@briaguya is this relevant at all for our current build? Related to re-evaluating the joplin API structure?
