### ISSUE TITLE
404 page copy edit

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2652]
**Acceptance criteria**
- [ ] lowercase "contact us" (per our editorial style guide)

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/2a719c12-7bea-416d-8146-fc80cd83272e)

**Comment by briaguya** [comment]
in staging now

**Comment by desigonz** [comment]
Looks great, back to you.
