### ISSUE TITLE
ODD service offerings one-pager

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#2653]
- Nameir asked for some help with designing one-pager to promote ODD's service offerings. He's going to connect with me next week with the content.
- [Draft 1 content](https://docs.google.com/document/d/1nBdE4PJ52jQi9tFgfxvxZjyeF_DwkP0FvgxnkEncIK8/edit) is now in

**Comment by chasechenevert** [comment]
Status update: waiting for content to be developed.

**Comment by desigonz** [comment]
dupe of #2913
