### ISSUE TITLE
Weird display issue when scrolling 

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#2654]
**Describe the bug**
When scrolling the rich text bar on an active component appears above the header.

![Screen Shot 2019-07-26 at 12 53 19 PM](https://user-images.githubusercontent.com/3790067/61971885-c9b41e00-afa5-11e9-9588-ea331395fb47.png)

**URL**
http://joplin-staging.herokuapp.com/admin/pages/152/edit/

**To Reproduce**

1. Go to 'http://joplin-staging.herokuapp.com/admin/pages/152/edit/'
2. Scroll to one of the step rich text fields (such as where it says "Find a garden site")
3. Click within the rich text field (so that your text cursor is blinking within the edit field)
4. Scroll to the bottom of the page

**Current behavior**
As you scroll, you'll notice that the rich text options bar appears above the header

**Expected behavior**
It shouldn't appear above the behavior. Instead, it should behave as it does when your text cursor isn't focused on the edit field.

**Screenshots**

**Device**

**Browser**

**Additional context**

------

**Comment by desigonz** [comment]
Assigning @toribr to QA

**Comment by toribr** [comment]
Yas.
