### ISSUE TITLE
Line spacing in steps

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#2656]
**Acceptance criteria for dev team**
- [ ] In steps, there is `1em` of margin between paragraphs
-------
### background
Not sure what's happening, but it has no effect from the service steps component.

component
![Screen Shot 2019-07-26 at 1.50.36 PM.png](https://images.zenhubusercontent.com/5a81e99a4b5806bc2bc6a146/58ef50c0-5d27-4e97-a49f-5528d3bae8f9)

renders
![Screen Shot 2019-07-26 at 1.50.49 PM.png](https://images.zenhubusercontent.com/5a81e99a4b5806bc2bc6a146/f71583b3-4d8b-4d14-a282-9d0f1e3aee07)

**Comment by desigonz** [comment]
@toribr Line breaks are working for me (puts each line within its own `<p>`), but it seems like the spacing in the steps hasn't been implemented correctly.

@chasechenevert, can you verify how the line breaks should be styling within steps? See below.

### In a step
*joplin*
![image](https://user-images.githubusercontent.com/5839508/62331428-86641e80-b481-11e9-8c2e-96c8dfcd2886.png)

*janis*
![image](https://user-images.githubusercontent.com/5839508/62331373-5d438e00-b481-11e9-8f6d-4b49e729b53e.png)
![image](https://user-images.githubusercontent.com/5839508/62331489-b0b5dc00-b481-11e9-830e-0474e8a9be94.png)


### Within an option
*joplin*
![image](https://user-images.githubusercontent.com/5839508/62331432-8cf29600-b481-11e9-9170-66dbc681f2c6.png)


*janis*
![image](https://user-images.githubusercontent.com/5839508/62331384-66ccf600-b481-11e9-954d-f29756e4abb7.png)

**Comment by desigonz** [comment]
Assigned @chasechenevert to verify line breaks for steps in Janis.

**Comment by chasechenevert** [comment]
Seems like we can just add in some top and bottom margin within the `.coa-Steps__list>ul>li>p>p` class. Seems like it's overriding the `p` element top and bottom `margins`. 

### Example of margin overrided
![Screen Shot 2019-08-09 at 9 14 23 AM](https://user-images.githubusercontent.com/7027270/62785658-b796ad00-ba86-11e9-8a4f-00eadc4956c5.png)

**Comment by desigonz** [comment]
Thanks @chasechenevert for looking into this! If the acceptance criteria below looks good, we can send it onto the dev team.

**Acceptance criteria for dev team**
- [ ] In steps, there is `1em` of margin between paragraphs

**Comment by chasechenevert** [comment]
No problem! Good to go on the criteria

**Comment by desigonz** [comment]
thanks @chasechenevert! updated the issue with acceptance criteria and cued it up for the dev team.

**Comment by briaguya** [comment]
Current on alpha.austin.gov:
<img width="754" alt="Screen Shot 2019-08-21 at 11 14 06 AM" src="https://user-images.githubusercontent.com/6384156/63449033-da20b280-c404-11e9-92eb-d60c31d68b9c.png">

In https://github.com/cityofaustin/janis/pull/475:
<img width="703" alt="Screen Shot 2019-08-21 at 11 14 15 AM" src="https://user-images.githubusercontent.com/6384156/63449834-75665780-c406-11e9-98a9-9842d2c8ebe4.png">

See PR app: https://deploy-preview-475--janis.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/get-immunized

**Comment by briaguya** [comment]
gave this a 2 because it'll take a bit of QA to make sure we don't break styles in other places with the change I implemented

**Comment by briaguya** [comment]
looks like my fix has some oddities, we really need to look into cleaning up our stylesheets to handle things like this:

![Aug-22-2019 05-45-03](https://user-images.githubusercontent.com/6384156/63508676-063d4180-c4a0-11e9-8b66-a008d06d6679.gif)

**Comment by desigonz** [comment]
@briaguya did some things for the line spacing in steps here: https://deploy-preview-475--janis.netlify.com/en/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup
@chasechenevert, assigning you to review and tell us if we need any tweaks

**Comment by chasechenevert** [comment]
This looks good to me

**Comment by briaguya** [comment]
@desigonz this is in staging now here: https://janis.austintexas.io/en/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup/

**Comment by desigonz** [comment]
QA complete, looks great.
