### ISSUE TITLE
Double active navigation when adding new snippet

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2657]
**Describe the bug**
When you add a new snippet (location, contact, or map), the left navigation shows both the snippet and the content field as active.

**URL**
http://joplin-staging.herokuapp.com/admin/pages/3/

**To Reproduce**

1. Go to http://joplin-staging.herokuapp.com/admin/pages/3/
2. Click on the left nav icon for "Locations" (or "maps" or "contacts"—all of them do this)
3. Click on the "add new" button on the top right

**Current behavior**
On the left nav, two menu items appear as active (a.k.a. have a darker background and have that line on the left): "content" and "locations" (or "maps" or "contacts," depending which one you've navigation from)

**Expected behavior**
Only the "locations" icon to appear as active in the left nav

**Screenshots**
![image](https://user-images.githubusercontent.com/5839508/61980798-5b7b5580-afbd-11e9-8299-d21d927d33ec.png)
![image](https://user-images.githubusercontent.com/5839508/61980808-5f0edc80-afbd-11e9-9d9f-25536011d630.png)
![image](https://user-images.githubusercontent.com/5839508/61980818-63d39080-afbd-11e9-9679-ad7c4cbbebc5.png)

**Device**

**Browser**

**Additional context**

**Comment by briaguya** [comment]
Just checked on prod (and staging/local) and this appears to have been fixed already.

**Comment by toribr** [comment]
Purty.
