### ISSUE TITLE
Follow up Joplin Audit with refactoring into separate apps/packages

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#2659]
Now that we've gone through all the changes that Joplin makes to Wagtail, lets see how we can separate them into separate apps (which is a Django thing) to be packaged as tools that could be used by others and in other projects.

i.e. 
Side by side tabs/preview

**Comment by desigonz** [comment]
Looped into @briaguya's Joplin 3.0 work, closing this.
