### ISSUE TITLE
Review links to top services on department pages

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2660]
We have the ability to add "top services" links on department pages, but the author experience for adding them isn't intuitive.
- Review how translations are added
  - What to do with "Copy content from"?
  - Currently, you choose to add a link in a certain language all on one page (rather than using the language tab at the top of the link)
- Does the order you enter links determine the order in which they appear?
- What else for short term? And what's the ideal long-term solution—using a picker to choose a Joplin page?

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/2b1ecdb3-5eef-4447-8310-e99232ca14f3)

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/f0b0a281-d238-4a44-9888-02f6f1809036)

**Comment by toribr** [comment]
Essentially, whatever is created in English should be duplicated to other languages (matching blank fields) automagically on the backend, and should show under the tab control at the top. Translations should only be managed via one method.

**Comment by desigonz** [comment]
Marginally related to #2691

**Comment by toribr** [comment]
Draft
![2660](https://user-images.githubusercontent.com/3790067/63060190-232daf80-beb7-11e9-910c-c19905aa0703.png)

**Comment by desigonz** [comment]
@toribr This is great. Is it ready to go to dev?

**Comment by desigonz** [comment]
Developed acceptance criteria in #2782. @toribr, there's one question there for you.
