### ISSUE TITLE
Service page step styling

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2662]
# New acceptance criteria
Janis
- [x] Step with options text doesn't style as H1

Joplin
- [x] When creating a step with option, the "options description" field is a rich text field

----------

# old 

**Acceptance criteria**
- Janis
  - [ ] Step heading styled per dev spec
  - [ ] Body text remains the same
- Joplin
  - [ ] Basic steps need field for header
  - [ ] Use default max character limit

Per discussion in #2465, step style is displayed below.

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/d989a130-6907-43ff-b0cd-84170c33faa2)

**Additional resources**
- [link to dev specs](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/ce9e7492-b75b-472c-9dab-98d7bd1843ba/Template-Service-desktop/)

**Comment by robbobfrh84** [comment]
The pull request for both Janis and Joplin are up and ready for review for this issue now...😬👇
Janis: https://github.com/cityofaustin/janis/pull/501
Joplin: https://github.com/cityofaustin/joplin/pull/360
Deployed at: https://joplin-pr-2662-service-step-st.herokuapp.com/admin/login/

**Comment by easherma** [comment]
@desigonz one side effect of switching the description to be rich text is it doesn't have a label anymore (since we've hid those labels per design). Does the design feel intuitive to you? It seems hard to understand what field is for what and how they are nested. Either way, improvements to that might be better in a subsequent issue but I figured I'd mention it.

**Comment by desigonz** [comment]
Ahh I see what you mean. Would it be easy to change the "Write here..." placeholder text to say "Options description"?

![image](https://user-images.githubusercontent.com/5839508/64644584-8dfbd900-d3d8-11e9-9949-dce4e22bcca9.png)

![image](https://user-images.githubusercontent.com/5839508/64644622-a2d86c80-d3d8-11e9-9bba-2d927f3374fd.png)

**Comment by robbobfrh84** [comment]
@desigonz Makes since. I'll change that now.

**Comment by robbobfrh84** [comment]
@desigonz Would we also want to have the *Basic Steps* placeholder text to be "Options Descriptions" as well? 

...Then, I'm wondering about the remaining "Write Here..." placeholder for the "Option Description" I'd assume?

This image show the "Basic Steps", then the "Steps with Options" both as default as it stands.

<img width="805" alt="Screen Shot 2019-09-10 at 3 19 07 PM" src="https://user-images.githubusercontent.com/15821138/64648802-43cb2580-d3e1-11e9-9b61-0cd6fbc7235e.png">

**Comment by briaguya** [comment]
@desigonz I'm hoping you can clarify here:

My understanding was this changed our current implementation of:
* Basic step
  * Rich text with nothing else
* Step with option
  * Options description (plain text)
  * Options
    * Option name (visible when collapsed)
    * Option details (expanded)

to:

* Basic step
  * Basic step header (name?) - ***NEW***
  * Rich text
* Step with option
  * Options description
  * Options
    * Option name (visible when collapsed)
    * Option details (expanded)

I see that options description is now being mentioned as a part of the acceptance criteria here.

I'd suggest breaking this issue up, making it so we have one issue for updating the basic step to have a header, and then another issue for making options description a rich text field instead of a plain text field.

**Comment by desigonz** [comment]
Hey @briaguya—the acceptance criteria changed last week when Eric and Bob brought up some good points about the implications of the original acceptance criteria. I worked with Chase and Annie to nail down the new acceptance criteria, which is simpler that we had originally planned. I'm meeting with Bob today to answer his questions above, with the goal of not adding on any scope.

So what's actually happening in Joplin is we went from:

* Basic step
  * Rich text with nothing else
* Step with option
  * Options description (plain text)
  * Options
    * Option name (visible when collapsed)
    * Option details (expanded)

to:

* Basic step
  * Rich text (stays the same, not new)
* Step with option
  * Options description (changes to rich text) **NEW**
  * Options (all of this stays the same)
    * Option name (visible when collapsed)
    * Option details (expanded)

**Comment by desigonz** [comment]
If you're curious, @briaguya, we can hop on a call and I can explain the reason behind the acceptance criteria change.

**Comment by robbobfrh84** [comment]
I just wanted to update how the "steps with options" are looking now with my PR

<img width="697" alt="Screen Shot 2019-09-13 at 2 45 19 PM" src="https://user-images.githubusercontent.com/15821138/64890448-4cb43500-d635-11e9-9992-4325db3423b6.png">

**Comment by Jo-Dwyer** [comment]
I'm seeing a step style example worth looking at:

When I use a basic step followed by a step with options, the basic step has a text box with no format options while the step with options has an h1 title

![Screen Shot 2019-09-17 at 3.11.56 PM.png](https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/6404e841-1fd8-49af-90f8-a17eed50c35b)

**Comment by desigonz** [comment]
@Jo-Dwyer We're changing this so that step 2 in your screenshot wouldn't be styled as a heading. It's not in production yet but will be soon.
