### ISSUE TITLE
Write Guide section of the style guide 

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#2663]
As an OPO content editor uploading official documents, I want to be able to refer to the style guide on how to use the Guide content type so that I can successfully and consistently communicate with residents.

We are implementing the Guide content type. We need a style guide entry to correspond to it. This will provide guidance to OPO content editors on how to use the content type. We'll also use this when we train the OPO team on using Joplin to add new content using this content type.

**Comment by desigonz** [comment]
Thanks for making this issue! Assigning this to next sprint, but you can use this issue to jot down thoughts you have along the way/as you work on guide content.
