### ISSUE TITLE
Implement guide nav and scrolling

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2664]
- [x] Desktop: left navigation and scrolling behavior
  - [x] As a user scrolls through the body content, the corresponding larger section in left nav is highlighted with blue line, and the title of the particular page is in blue, with arrow pointing?
  - [x] When a user clicks on a heading in the left nav, the body scrolls to the corresponding content

**ignore**
- [ ] Mobile scrolling behavior
  - [ ] When a user opens the mobile nav, display only section headers
  - [ ] When a user opens the mobile nav, the current section on the screen is highlighted with blue line and blue text

**Comment by Niicck** [comment]
Chase Mocks: https://xd.adobe.com/spec/3cd2740c-6a05-45fc-6e6e-e1cf885acaca-4ae3/screen/8cc5044c-856c-46b4-a403-aaf1c94cf534/Guide-MVP-desktop-fixed-left-menu

**Comment by desigonz** [comment]
Has been implemented but not merged into staging. Waiting to merge until we have #2783.
