### ISSUE TITLE
Review microcopy for Joplin guide UI

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2665]
### As a content editor, I want clear labels and helper texts so that I understand what kind of content to add where when authoring a guide.

See #2600. @toribr designed mocks for Joplin UI—per design pin-up today, @LauraTrujillo will review the field labels and helper text for editing a guide in Joplin. (Might need @toribr to upload the latest design.)

**Comment by LauraTrujillo** [comment]
Gave Tori the marked up doc today.
