### ISSUE TITLE
Ability to add trashy/ReCollect apps between steps

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2666]
### As a content editor, I need the ability to add the apps between steps on Joplin, in order to achieve the user goal above.

**Acceptance criteria**
- [ ] When a user uses "code" in a rich text field, they can type `APPBLOCK: App Name` to insert app and have it appear in Janis

**Is your feature request related to a problem? Please describe.**
Currently, on pages like [Get your bulk items collected](https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup/), we ask users to scroll down to the apps below, which is not an ideal user experience—the apps are then out of context.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by briaguya** [comment]
@desigonz this brings up so many things, so I'm just going to braindump some of my ideas here:
## Option 1 (Don't change joplin, do some hacky Janis stuff)
### Author flow
* Add a "code" block to an existing step, use some fancy keyword to mean "hey Janis, we want an app here"
<img width="996" alt="Screen Shot 2019-07-31 at 9 37 25 AM" src="https://user-images.githubusercontent.com/6384156/62221262-00f44780-b377-11e9-9519-c09f67c00149.png">

* Remove app from "maps and apps" so we don't have it on the page twice
![Jul-31-2019 09-26-06](https://user-images.githubusercontent.com/6384156/62221311-16697180-b377-11e9-9840-7dbc93df7513.gif)

### Resident flow
* The app appears in line with the relevant content
<img width="713" alt="Screen Shot 2019-07-31 at 9 39 56 AM" src="https://user-images.githubusercontent.com/6384156/62221371-2e40f580-b377-11e9-8557-d2186fb13579.png">

### Code changes
* Update [HtmlFromAdmin](https://github.com/cityofaustin/janis/blob/c61922ffdc01f998551b2d4ca241c46d886550c2/src/components/HtmlFromAdmin/index.js#L16) to do some extra stuff when parsing "code" blocks
* Example in branch: https://github.com/cityofaustin/janis/tree/2666-hacky-janis-step-apps

### Pros
* No changes to Joplin

### Cons
* Implementation could get messy

### Thoughts / Questions
* Is this an acceptable flow to use for authors?

## Option 2 (Update joplin to support an extra step type)
### Author flow
* Add a fancy new step that supports application blocks in line

<img width="1133" alt="Screen Shot 2019-07-31 at 9 09 13 AM" src="https://user-images.githubusercontent.com/6384156/62223189-233b9480-b37a-11e9-8940-9f5e59ebf881.png">

* Write the step content using a Streamfield (wagtail term) which means:
  * Add a rich text block to the start of the step
  * Add an application block next
  * Add other blocks as desired

* Remove app from "maps and apps" so we don't have it on the page twice
![Jul-31-2019 09-26-06](https://user-images.githubusercontent.com/6384156/62221311-16697180-b377-11e9-9840-7dbc93df7513.gif)

### Resident flow
* The app appears in line with the relevant content
<img width="713" alt="Screen Shot 2019-07-31 at 9 39 56 AM" src="https://user-images.githubusercontent.com/6384156/62221371-2e40f580-b377-11e9-8557-d2186fb13579.png">

### Code changes
* Update Joplin models to change step into a streamfield that supports:
  * Rich text blocks
  * Application blocks
* Update Janis to make sure it correctly handles this in steps

### Pros
* Clean implementation
* Less obtuse author interface

### Cons
* Author interface could get messy

### Thoughts / Questions
* Is this an acceptable flow to use for authors?
* Are there other places (such as the non-step part of the service page body) we want to put application blocks?

## Option 3 (Make a new page type for apps)
### Author flow
* Add a new page for the app
* Add the app and appropriate helpful information about it to a page

### Resident flow
* The service page step content links to a page with the application

### Code changes
* Add app page to Janis/Joplin

### Pros
* Cleanest implementation
* Makes testing easier for future apps
* Keeps load times down for residents by only loading apps when specifically asked

### Cons
* More clicks for residents
* Requires design work to figure out what this looks like

### Thoughts / Questions
* Is this an acceptable flow to use for residents?

**Comment by desigonz** [comment]
Let's go with option 1 as short-term solution. Longer term, we'll think about other kinds of apps and solutions for them (possibly some of them will need to go with option 3).

**Comment by desigonz** [comment]
- [ ] @desigonz to add acceptance criteria for option 1
- [ ] @briaguya  to turn option 1 into PR
- [ ] @desigonz to make issue for next version of this—experience of adding it via rich text field (per @easherma's suggestion)

**Comment by desigonz** [comment]
@briaguya I added acceptance criteria. This one is ready for you!

**Comment by easherma** [comment]
Random thought(s) on this one: at some point we'll probably want to restrict the kinds of apps that could be added depending on the department of the page or other parameters. 

Also see: http://docs.wagtail.io/en/v2.6.1/advanced_topics/customisation/extending_draftail.html#creating-new-entities
And, if/when we want to get fancy, other plugins we could leverage: 
https://www.draftail.org/docs/plugins
https://www.draft-js-plugins.com/plugin/mention

**Comment by briaguya** [comment]
@desigonz moved to QA and assigned you, there is an example of this working in staging now:
Joplin: https://joplin-staging.herokuapp.com/admin/pages/145/edit/
Janis: https://janis.austintexas.io/en/health-safety/health-records-certificates-2/birth-death-certificates/test-all-of-the-appblocks/

**Comment by desigonz** [comment]
What a dream!! This looks amazing and you are amazing. QA complete, back to you.
