### ISSUE TITLE
Add fee table to "Get a birth or death certificate"

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2674]
We now have the ability to add tables via markdown (see #2333 for details on how to do so). We will be developing conventions for how to do so (#2331). Then, we need to replace pricing in step 2 on the [Get a birth or death certificate](https://alpha.austin.gov/en/health-safety/health-records-certificates-2/birth-death-certificates/birth-and-death-certificates-test) service page with a few table.

**Acceptance criteria**
- [x] Author fee table in English
- [x] Send for review (at least one content strategist)
- [x] Translate
- [x] Publish in English
- [x] Publish in Spanish

**Comment by Jo-Dwyer** [comment]
Still waiting on Spanish translation.
