### ISSUE TITLE
SEO tab

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2686]
### As a Joplin admin, I want the ability to update SEO-related data and slugs for a page, so that my page will reach the right audiences.

**Is your feature request related to a problem? Please describe.**
Wagtail has a default SEO tab, but we've currently hidden it. You can view it here: https://joplin-pr-show-extra-panels.herokuapp.com/admin/pages/128/edit/#tab-seo

One thing to note: The dev team noticed that we often page titles and slugs that don't match (#3156). That's because the slug is set when you first title a page; if you change the page title, slug will stay as it was before. 

**Describe the solution you'd like**
Let's make some decisions about what needs to be on the SEO tab.
- **Slug:** we have the ability to add different slugs for different languages. What should that experience be for users? Should it live instead on the content tab?
- **Page title:** Should we remove this field?? This is an optional "search engine friendly" title that appears at top of the browser window, apparently (I guess it's `<title>`). We're using the page title within content for this (and it will change depending on language). 
- **Show in menus:** This seems irrelevant to us. It's for some auto-generated menus. That's not how our IA works.
- **Search description:** This field allows you to add text that will be displayed if the page appears in search results. Would we just want this to pull from the "description" field in the content? @srigdon: Yes, we're writing descriptions so they can be used by humans and search engines. 
- **Rel canonical:** We want to surface related content for users who don't know what they don't know, which has resulted in similar (not duplicate but to a search engine it could be near-duplicate) content across several pages. This is good for humans, and we want to tell Google which one is the most pertinent to a user's search. See [Moz SEO Fundamentals: Duplicate content](https://moz.com/learn/seo/duplicate-content). Examples: 

> - Serve on the CPRC (service page on how to serve that links to a form container page with a Formstack form in it)
> - Apply to serve on the CPRC (form container page/online application form)
> 
> - Hire a day laborer (service page about how you can access this service through various ways, whether on the phone or through a digital form)
> - Request a day laborer (the form is specifically about making a request to hire)

Also, which user groups should have access to this tab? Currently, we have administrators, moderators, and editors. @srigdon: Every role should be able to access it because ideally making pages easy for residents to find part of content creation. 

Also also, we'll want to handle redirects for broken links in case the slug changes:
http://docs.wagtail.io/en/v2.6.2/reference/pages/model_recipes.html#have-redirects-created-automatically-when-changing-page-slug

Another note: these sections are weirdly appearing twice in the PR branch above. We'll want to fix that.

![seo-tab](https://user-images.githubusercontent.com/5839508/66671575-f16c6700-ec21-11e9-8bed-8326e04ebb9a.gif)

**Describe alternatives you've considered**
Our content templates have a "keywords" field. Somewhere to add those?

**Additional context**
[Wagtail info on promote tab](http://docs.wagtail.io/en/v2.0/editor_manual/new_pages/the_promote_tab.html)

**Comment by desigonz** [comment]
Something to consider: in #2827 we made it so that the various content drafts are split up by language under a dropdown. 

Slugs are a non-content field that are not global, i.e. language-specific. They are housed in the SEO tab.
- [ ] decide how we should display other localization info that might be related to something like SEO

gif that shows english slug and then blank for the spanish slug
![language-slug](https://user-images.githubusercontent.com/5839508/65801264-544c0180-e13e-11e9-8f01-96b594a6d4b6.gif)

**Comment by desigonz** [comment]
Note from @toribr:
> the model could still work in that we could tie the page language and seo tab language together. but we would probably want to change the styling of notes and settings to links to make them look different because their behavior will be more universal.

**Comment by Jo-Dwyer** [comment]
@toribr is this whole epic nixed?

**Comment by srigdon** [comment]
Is this OK to close? @toribr

**Comment by toribr** [comment]
No, there are a couple of resulting dev issues, so we won't close this until those are complete.
