### ISSUE TITLE
Add file size on official documents

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2688]
On the dev spec, we have file size after a PDF. Let's make a way for that automatically to appear!

**Acceptance criteria**
- [ ] On Janis, the file size appears per [Dev spec](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/895949b5-49ac-45bc-9114-2f5b3183573e/Official-Document-MVP-web-1/) for official documents

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/da335e86-8e2a-4d17-a491-5fcaeb3a3548)

**Comment by Niicck** [comment]
Here's what we got. If the link is a PDF, then we add a little (PDF) message to it.

<img width="787" alt="Screen Shot 2019-08-07 at 4 05 35 PM" src="https://user-images.githubusercontent.com/14187277/62657967-3f68a400-b92d-11e9-9f6c-aa802f4194bb.png">

However, it will not tell you the size of the PDF. Long story short, Browser security rules prevent Janis from dynamically reading a PDF's file size. 2 options:

1. Get the PDF file size on Joplin when we add/update a link, add it to our database, display that on Janis.
2. Links for Documents are temporary anyway until we let people upload their own documents. We can easily add the PDF Size feature when that happens.

It would be a lot of work for a UI feature that is temporary anyway. If design is okay with it, I'll like to not add PDF size to official documents until we're uploading documents for real.

**Comment by Niicck** [comment]
We (Tori, Chase, Desi, I) decided to push back on this task for now.

**Comment by desigonz** [comment]
Moved to short term backlog for now. This will be post-MVP and when we have document hosting.

**Comment by Niicck** [comment]
nvm I found a way to implement this. https://github.com/cityofaustin/janis/pull/464/commits/744d9c5e8ce75feb84bca13bf847e608e1dd0787
