### ISSUE TITLE
Janis - Department page related info/top services needs some love

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#2691]
## As a resident, I want a department page to direct me to top services and other relevant information, so that I can find the information I need.

**The problem**
Currently, we've got logic set up on the department pages so that any page assigned to a particular department automatically appears on the department page under the "Related information" section. This was a short-term solution for the OPO microsite: We did this so that, on the Office of Police Oversight page, the "How we store and use your data" and "Complaint investigation process" pages are easily navigable from the department page. 

We've outgrown this short-term solution and need something a little more medium- or long-term. Why?
- For OPO, we've made the intro pages of the forms into service pages. This allows them to appear within the IA, which is great! But now we have duplicate links under "Top services" and "Related information." This isn't the end of the world, but it's not the best.
![image](https://user-images.githubusercontent.com/5839508/63601318-d028bc00-c58a-11e9-8d4a-754b737405c7.png)
- For APH, we're about to publish the department page and associate many existing service pages with that department. That's going to be a problem, because the "Related information" section isn't built to display all of the pages under a department.
![image](https://user-images.githubusercontent.com/5839508/63380227-a63d8280-c35b-11e9-8508-5dbad7ee2c12.png)

**By the end of sprint 38**
Let's develop a medium-term solution that will serve both APH and OPO's needs. We can later iterate for the long-term.

**We need a solution for "Related information" that...**
- [ ] Allows us to display OPO information pages that don't really live elsewhere in the IA beyond the department page
- [ ] Won't overload a department page like APH that has a lot of pages under it

**Things to consider**
- [ ] How much control/curatorial power should a content editor have over the "Related information" section? (AKA it's currently automatic, but should it be content manageable instead?)
- [ ] Long-term, what content governance/rules should we consider?

-----

## background

<img width="972" alt="Screen Shot 2019-08-06 at 4 20 38 PM" src="https://user-images.githubusercontent.com/6384156/62578226-395bc000-b866-11e9-91e0-01772c3044d3.png">
Looks like we're getting some duplicate links in here, let's fix that.

**Comment by desigonz** [comment]
This is happening because "Related information" automatically feeds in any pages defined as a department page. Long-term, this solution won't work. I think we should have @toribr and @chasechenevert take a look at this and determine an interim solution.

**Comment by toribr** [comment]
What if the system simply knew not to duplicate links between top and related? Ie, if <link> is top, then <link> is not in related list.

**Comment by desigonz** [comment]
That could be neat. Let's discuss the implications of this at the next dev/design sync.

**Comment by desigonz** [comment]
Also a problem for Austin Public Health

- [ ] @desigonz to flesh out how things are working and what our goals are

![image](https://user-images.githubusercontent.com/5839508/63380227-a63d8280-c35b-11e9-8508-5dbad7ee2c12.png)

**Comment by desigonz** [comment]
Two possible short-term solutions. @briaguya can you weigh in?

### solution 1
**Hide related info on non-OPO pages on the Janis-side of things.**

Pros: would this be a quick fix? Doesn't require changing anything in Joplin.
Cons: Still have the duplication with the top services on OPO, but we could live with that for now.

### solution 2
**Change the logic related information isn't automagically populated; instead, content editor has ability to add the few OPO related links.**
In Joplin, we'd need a new component for departments that basically allows a title and a short list of links (up to 10).

Pros: allows us to clean up OPO to how we really need it. More editor control.
Cons: Sounds like a bigger lift, more changes to Joplin.

**Comment by easherma** [comment]
I remember when we discussed this in person Solution 2 seemed like a stronger bet. It's not an impossible lift and can also help make the queries in janis be easier to manage/maintain.

**Comment by desigonz** [comment]
Per my notes where we landed on this is that the design team will be taking a look at how this would currently work for APH (using staging—and in fact we can already see what's happening here: https://janis.austintexas.io/en/austin-public-health/) and then will come up with a proposed solution. We'll then review with the dev team before y'all take this one on.
