### ISSUE TITLE
Update copy and icons create modal improvements (and delete that screen)

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2692]
### Select content type screen
**Acceptance criteria**
- [ ] Implementation matches mocks below
- [x] "Content pages" and "Topics or topic collections" as two separate tabs 
  - [x] Title for content pages should be "Select a content type"
- [x] Use [these icons](https://github.com/cityofaustin/techstack/issues/2467#issuecomment-511044512)
- [ ] Use the following names and descriptions for each:
  - [x] [name] Service page [description] A step by step guide to a particular city service
  - [x] [name] Information page [description] Provides supplementary information and resources to support service delivery
  - [x] [name] Department page [description] Basic information and contact details for a department
  - [x] [name] Guide [description] A collection of pages for a complicated process, organized into sections
  - [x] [name] Official document list [description] Summaries and links to official documents 
  - [ ] [name] Simple form [description] A way to collect basic information from residents
  - [ ] Copy note: all headings should be sentence case (so only first letter capitalized), and no period at the end of descriptions, since they aren't full sentences

![create w service Collection – 1](https://user-images.githubusercontent.com/3790067/62894925-6c44fe80-bd13-11e9-83c7-16c89b0106e1.png)
![Select content type](https://user-images.githubusercontent.com/3790067/62894927-6cdd9500-bd13-11e9-8df4-181cff4f55b0.png)

See #2467 for more background on this.

### Add title screen
**Acceptance criteria**
- [x] Copy edit: all bullet points on all screens should end in a period
- [x] [Service page](https://xd.adobe.com/spec/6728765d-1f27-4732-4e6d-b3d6726ca4ec-1119/screen/73fb56eb-60a4-4de5-afc7-0926ff27dff0/Service-modal) copy matches mocks
- [x] [Information page](https://xd.adobe.com/spec/6728765d-1f27-4732-4e6d-b3d6726ca4ec-1119/screen/682130aa-f3d8-47a3-b980-9d30775a1815/Information-modal) copy matches mocks
- [x] [Department page](https://xd.adobe.com/spec/6728765d-1f27-4732-4e6d-b3d6726ca4ec-1119/screen/c8cb5e0a-466a-45e4-aa8c-867854c23e6e/Dept-modal) copy matches mocks
- [x] [Guide](https://xd.adobe.com/spec/6728765d-1f27-4732-4e6d-b3d6726ca4ec-1119/screen/6ee4d9c2-06fa-4c81-860b-555e1197f06a/Guide-modal) copy matches mocks
- [ ] [Form](https://xd.adobe.com/spec/6728765d-1f27-4732-4e6d-b3d6726ca4ec-1119/screen/cf0ab30d-031f-46e5-9f53-3bcfb065d281/Basic-form) copy matches mocks
- [x] [Official document](https://xd.adobe.com/spec/6728765d-1f27-4732-4e6d-b3d6726ca4ec-1119/screen/cfaba674-a723-48e8-b104-35efc831def8/Official-document) copy matches mocks

![Service modal](https://user-images.githubusercontent.com/3790067/62894928-6cdd9500-bd13-11e9-9d13-0ef036243a09.png)
![Information modal](https://user-images.githubusercontent.com/3790067/62894929-6cdd9500-bd13-11e9-8d0c-abed2b99b65e.png)
![Dept modal](https://user-images.githubusercontent.com/3790067/62894930-6d762b80-bd13-11e9-8d8a-e6a4951eaac5.png)
![Guide modal](https://user-images.githubusercontent.com/3790067/62894931-6d762b80-bd13-11e9-9758-8c963fb9bf77.png)
![Basic form](https://user-images.githubusercontent.com/3790067/62894932-6d762b80-bd13-11e9-9582-0495c748a771.png)

### Topic or department
- [x] Delete all instances of "Topic or Department?" screen

*delete this!*
![image](https://user-images.githubusercontent.com/5839508/62873588-50c2ff00-bce5-11e9-8164-f9b66622c021.png)

----------

See #2468 for more background on this.

**Comment by easherma** [comment]
This one is a biggie, lets discuss it! @briaguya and I have talked about a desire for refactoring the modal, and I think we could/should explore using the generic chooser library as a more solid foundation to build the thing on.

**Comment by toribr** [comment]
Updated comps:

![create w service Collection – 1](https://user-images.githubusercontent.com/3790067/62894925-6c44fe80-bd13-11e9-83c7-16c89b0106e1.png)
![Select content type](https://user-images.githubusercontent.com/3790067/62894927-6cdd9500-bd13-11e9-8df4-181cff4f55b0.png)
![Service modal](https://user-images.githubusercontent.com/3790067/62894928-6cdd9500-bd13-11e9-9d13-0ef036243a09.png)
![Information modal](https://user-images.githubusercontent.com/3790067/62894929-6cdd9500-bd13-11e9-8d0c-abed2b99b65e.png)
![Dept modal](https://user-images.githubusercontent.com/3790067/62894930-6d762b80-bd13-11e9-8d8a-e6a4951eaac5.png)
![Guide modal](https://user-images.githubusercontent.com/3790067/62894931-6d762b80-bd13-11e9-9758-8c963fb9bf77.png)
![Basic form](https://user-images.githubusercontent.com/3790067/62894932-6d762b80-bd13-11e9-9582-0495c748a771.png)
![Official document](https://user-images.githubusercontent.com/3790067/62894933-6d762b80-bd13-11e9-8179-ed5fb2421cbf.png)

**Comment by desigonz** [comment]
@easherma Let's start with these content and clean up changes for this sprint, and we'll do a bigger refactor later. Trying to get Joplin 2 to a usable place and *later* to an optimal place :)

**Comment by desigonz** [comment]
Thanks @toribr! I updated the mocks in the acceptance criteria.

**Comment by briaguya** [comment]
this is in staging now

**Comment by desigonz** [comment]
@briaguya copy edits for you:

- [ ] Lower all instances of "page" in content type headings (see screenshot 1)
- [ ] Delete period to the end of the description for "Service page" (see screenshot 1)
- [ ] Delete to the end of the description for "Department page" (see screenshot 1)
- [ ] Lowercase "collection" in "Topic collection" content type heading (see screenshot 2)
- [ ] Delete "s" from end of "Topic" content type heading (see screenshot 2)
- [ ] **On all title screens for all content types,** lowercase "title" in page "Title" (see screenshot 3)
- [ ] TBD—we might remove or change the example title for guides.


### Screenshot 1
![image](https://user-images.githubusercontent.com/5839508/63606122-f94e4a00-c594-11e9-82d1-ff9e236fd19f.png)

### Screenshot 2
![image](https://user-images.githubusercontent.com/5839508/63606064-e0de2f80-c594-11e9-822b-68ae4886e831.png)

### Screenshot 3
![image](https://user-images.githubusercontent.com/5839508/63605986-b4c2ae80-c594-11e9-8d9c-e3c2c26c66ab.png)

### Screenshot 4
![image](https://user-images.githubusercontent.com/5839508/63606314-67930c80-c595-11e9-96e2-ea46fd40f0d0.png)
