### ISSUE TITLE
Select a clearer contact icon

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#2693]
Tori mentioned wanting to explore other options for "Contact" icons since the Material version we use isn't very recognizable (especially at smaller sizes). 

-  Consider what's the most universal way to represent this concept. Compare across gov sites and major OS platforms. 
- Different icons for "Contact" vs "Phone" (currently there's only 1 we're using for both purposes)

**Use cases** 
- Janis contact component
- Joplin input field
- Form fields (need to double check if we are using these icons in forms, we did at one time but I can't remember if we still do)

**Material icons**
- [Communication](https://material.io/resources/icons/?search=communication&style=baseline)
- [Contact](https://material.io/resources/icons/?search=contact&style=baseline)

**Comment by chasechenevert** [comment]
## Current implementation

- "Contacts" icon isn't very clear at small sizes. The counter space within the phone shape is too small to notice at-a-glance.
- Since we currently use this icon to represent "contacts" and label phone numbers, we'll need to address that icon as well.

![Janis_contact vs phone_hoplin-09](https://user-images.githubusercontent.com/7027270/63286318-58524d00-c27d-11e9-9930-5520724563d2.png)


# Proposal
Material's icon font is handy for design + devs, helps us maintain consistency, and has a very large pool to choose from so I think we should stick to what's available within the set. The challenge here is to pick something that's more obvious for users, and to create distinction between similar concepts like "users" and "contacts".

- **Contacts**: creating distinction between the concept of "users" vs "contacts" is challenging. Both are about people but "users" refers to content authors on Joplin, and "contacts" refers to the information authors are providing to residents (Janis). We tried out other variations on "contacts" in Material's icon set, but those weren't successful because they felt to similar to the icon we're using for "users". I think that the folder + person outline might get across that it's a collection, or file, of contacts. Will shop this at pin-up tomorrow. 
- **Phone**: This is related since we currently use the same icon for "contacts" as "phone" (the icon is a card with a person's outline next to a phone). At small sizes this is difficult to distinguish and loses meaning. Looking at Mass.gov they use a slightly different representation of a phone icon that includes an illustration of sound waves--I think this detail could make the icon more recognizable than what we're currently using.

![Janis_contact vs phone-08](https://user-images.githubusercontent.com/7027270/63282649-eb3ab980-c274-11e9-9c16-614ca07d0298.png)


## Popular operating systems
### Apple: [Contacts app](https://support.apple.com/guide/contacts/welcome/mac)

![Janis_contact vs phone_apple-06](https://user-images.githubusercontent.com/7027270/63281682-d6f5bd00-c272-11e9-9264-6d97cb41f1e3.png)

### Google: [contacts](https://contacts.google.com/)

![Janis_contact vs phone_google-07](https://user-images.githubusercontent.com/7027270/63281832-305dec00-c273-11e9-8551-228b5fbb9814.png)

## Gov examples
- Mass.gov uses a phone icon that includes a representation of sound waves--that extra detail might help to make it more recognizable at smaller sizes. Google Material has a phone icon with sound waves "phone-in-talk"

![Janis_contact vs phone-04](https://user-images.githubusercontent.com/7027270/63280306-36060280-c270-11e9-81e2-2e18fa7c2edb.png)
![Janis_contact vs phone-05](https://user-images.githubusercontent.com/7027270/63280308-36060280-c270-11e9-8b6c-c687e454cc2c.png)

**Comment by chasechenevert** [comment]
@toribr and @desigonz I leave this for y'all as the deciders. If this doesn't work for you, take a look through the [Material Icon library](https://material.io/resources/icons/?style=baseline) and select what you'd like and we can close this one out.

### After
![Group 3245@2x](https://user-images.githubusercontent.com/7027270/63528420-84154300-c4c8-11e9-8b05-73028d955230.png)
### Before
![Screen Shot 2019-08-22 at 10 31 11 AM@2x](https://user-images.githubusercontent.com/7027270/63528421-84154300-c4c8-11e9-98af-33e875df2af5.png)

**Comment by desigonz** [comment]
I defer to @toribr! Let me know and I'll put it in the queue

**Comment by toribr** [comment]
[baseline-perm_contact_calendar-black-18.zip](https://github.com/cityofaustin/techstack/files/3531466/baseline-perm_contact_calendar-black-18.zip)

I like this one better.

**Comment by chasechenevert** [comment]
agreed! i brought that one to sprint review but it got voted down then, very possible we were looking at too much at once.

so all we need to do is pass the name of this icon to dev, which is: "perm_contact_calendar"
