### ISSUE TITLE
August Funshop

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2694]
**Objective** 

**Participants**

**Agenda**

------
- [x] Schedule meeting
- [x] Meet
- [ ] Create resulting issues

**Comment by LauraTrujillo** [comment]
Here's the How to funshop doc: https://docs.google.com/document/d/1-SxmgP09VjtlLcLR4lE4f23Psg7DC-SBGq1-NxXyE44/edit
It should help with sending the follow up email tomorrow. Great job today!! <3 <3 <3

**Comment by annieszot** [comment]
@srigdon I'll sync with you today for the follow-up to-do list, send the email, then close the issue :)

**Comment by annieszot** [comment]
Follow-up email sent. Here's Sarah's follow-up doc for issue creation. Closing :) 
https://docs.google.com/document/d/12KBfGYh-tMc3v312B9vDCri07nlF4SQo4EgOZQNNNbw/edit
