### ISSUE TITLE
Day labor form copy edits

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2698]
- [x] Add a period at the end of "Describe the job"
- [x] Add the T to "Transportation."
- [x] Change "I'd like a suggestion from First Workers' staff." to "I'd like a suggestion from the Day Labor Center's staff."

![image](https://user-images.githubusercontent.com/5839508/62656262-62915480-b929-11e9-8876-1536b3076366.png)

**Comment by Niicck** [comment]
WIP on https://github.com/cityofaustin/coa-forms/tree/2626-day-labor-content
Deployed to https://opo.austintexas.io/request-day-laborer/2626-day-labor-content/form

**Comment by desigonz** [comment]
Made #2737 for the change for form-service-api and assigned to Eric. Closing this one!
