### ISSUE TITLE
Gather and analyze statistics on foster process

### ISSUE THREAD

**Issue by MireyaGalarza** [cityofaustin/techstack#27]
The purpose of this activity is to obtain the number of  foster applicants through the process in hopes to identify the areas where applicants are dropping off:

- [ ] Call give pulse and get the amount of ppl who signed up for each of the past 12 months
- [ ] Call give pulse and get the amount of ppl who signed up for each of the past 12 months
Get the # of application submissions for past 12 months (monthly totals in Chameleon or Drupal)
Get the # of application approvals for past 12 months (monthly totals in Chameleon or Drupal)
- [ ] Get the # of application submissions for past 12 months (monthly totals in Chameleon or Drupal)
- [ ] Analysis and insight documentation

[Spreadsheet](https://docs.google.com/spreadsheets/d/1-sc4DKg0izC2ulcmfTRg1OFtMqmnuvOLitThb3pa00s)

**Comment by MireyaGalarza** [comment]
I contacted Michael Maddux,  he is the IT manager at the department of Health and provides IT support to Animal Center, to find out more about the status of Chameleon's replacement: Vestify.  He is working on hiring an analyst and he said that the IT PM at CTM working on Vestify is Carla Jobe-Partington

**Comment by MireyaGalarza** [comment]
This information is from research done by Enterprise Architect https://cityofaustin.github.io/austinea/arch/as/report/update091015.html

**Comment by amenity** [comment]
@MireyaGalarza - Can you add the link to the spreadsheet where you recorded this research and write up some key takeaways? Thanks!

**Comment by amenity** [comment]
@MireyaGalarza - Can you add the link to the spreadsheet where you recorded this research and write up some key takeaways? Thanks!

**Comment by amenity** [comment]
Cleaning backlog; designer who picks up AAC form will create necessary issues.
