### ISSUE TITLE
Refactor all components to use PropTypes and DefaultProps

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#270]
https://reactjs.org/docs/typechecking-with-proptypes.html

- [ ] Make sure all existing components have PropTypes & defaultProps defined. 
- [ ] Make sure all new components written do too. If not, we should be calling it out for each other in PRs.

## Why?
- It helps new devs understand a code base, what props they can use, etc.

## What else?
- We should use isRequired.
- defaultProps vs setting default values the es6 way when you deconstruct props in functional components.
  - preference towards defaultProps since it works for both stateful class components & stateless functional components. 

https://github.com/cityofaustin/techstack/issues/264

**Comment by ifsimicoded** [comment]
@mateoclarke, not 100% sure which components would need defaultProp definitions. I'm not sure that defaultProps matches our use case but I may not be thinking about their use correctly. Let me know if you have input.

**Comment by mateoclarke** [comment]
This might be a better for @luqmaan once he's back.

**Comment by ifsimicoded** [comment]
This issue was completed in Sprint 6 via https://github.com/cityofaustin/janis/pull/239
