### ISSUE TITLE
Rethink Joplin Data Model brain dump

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#2700]
I'm just using this issue as a place to braindump at the moment

See comments below for details:

* Official website header text
* Official website header body (rich text?)
* Header external links
* Site title
* Themes
* Homepage banner image
* Homepage banner(welcome) text
* Homepage top services
* Topic collections
* City seal image
* Homepage secondary footer links
* Homepage social media links
* Footer body (rich text?)

**Comment by briaguya** [comment]
I'm going to try coming up with a data model based on Janis from XD, we can figure out more in the future:

Starting with the homepage:
Full image:
![component](https://user-images.githubusercontent.com/6384156/62664131-0259dd00-b940-11e9-9754-4646f65468ca.png)

* Official website header
![component](https://user-images.githubusercontent.com/6384156/62664164-274e5000-b940-11e9-95df-d525818eb6eb.png)

* Header external links
![component](https://user-images.githubusercontent.com/6384156/62664205-4e0c8680-b940-11e9-9efb-44507e38f6e5.png)

* Site title
![component](https://user-images.githubusercontent.com/6384156/62664290-aba0d300-b940-11e9-9a03-dd1d025c07e6.png)

* Themes
![component](https://user-images.githubusercontent.com/6384156/62664344-e4d94300-b940-11e9-8d11-62fcb5718374.png)

* Homepage banner image
![component](https://user-images.githubusercontent.com/6384156/62664415-0fc39700-b941-11e9-9cb3-36479b35afef.png)

* Homepage banner(welcome) text
![component](https://user-images.githubusercontent.com/6384156/62664553-a7c18080-b941-11e9-9558-12b8d04a22d0.png)

* Homepage top services
![component](https://user-images.githubusercontent.com/6384156/62664584-c58ee580-b941-11e9-8c37-6ffe2c0b3819.png)

* Topic collections
![component](https://user-images.githubusercontent.com/6384156/62664679-14d51600-b942-11e9-8cb9-d71ec03b0643.png)

* City seal image
![component](https://user-images.githubusercontent.com/6384156/62664780-6c738180-b942-11e9-9ac3-509008c69f03.png)

* Homepage secondary footer links
![component](https://user-images.githubusercontent.com/6384156/62664807-8dd46d80-b942-11e9-91e2-2cd5ede60236.png)

* Homepage social media links
![component](https://user-images.githubusercontent.com/6384156/62664849-bceadf00-b942-11e9-8623-d8d917ca5070.png)

* Footer body (rich text?)
![component](https://user-images.githubusercontent.com/6384156/62664867-cc6a2800-b942-11e9-96ec-3987fbefe9fb.png)

**Comment by easherma** [comment]
Open question: why not implement these in current Joplin? Seems like the main blocker would be our clunky graphql API, but if grapple is a time-saving option we could should be able to make these models whenever.

**Comment by briaguya** [comment]
@easherma we can consider that after we get to 2c (build a couple implementations of the API against the data model prototypes, see how close we can get to the API we designed) in https://github.com/cityofaustin/techstack/issues/2707.
