### ISSUE TITLE
Reduce size of coa-forms

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#2701]
The bundle size for coa-forms is huge. This is a barrier to viewing it on mobile/3G internet.

We had an issue about this, but I can't find it now. I think it took like 30 seconds to load for some device?

coa-forms needs to be made more mobile/data friendly

**Comment by Niicck** [comment]
Dup of https://github.com/cityofaustin/techstack/issues/1646

**Comment by easherma** [comment]
FWIW the biggest improvement we could make here performance wise is code-splitting, and I don't know that we have the appetite to dive into webpack and us-forms-system to make that happen.

But if we can get forms ported over to janis I expect performance to be better/react-static and its newer versions especially are supposed to be pretty good at splitting stuff up.
