### ISSUE TITLE
Update snippet should trigger build

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#2703]
Contact Snippets (and any other snippet) can be saved in Joplin. But those changes won't publish to Janis unless the pages that they're attached to are published.

So to change a contact snippet, you'd need to re-publish every page that they're attached to. Even if you do that, there is a problem. If those pages are in a draft state that you don't want to publish yet, you won't be able to update contacts separately.

If this isn't possible now, we'd want to design Joplin 3.0 from the ground up to support publishing snippets in isolation from the pages they're attached to.

**Comment by easherma** [comment]
Matt Westcott from Torchbox says: 
@Eric Sherman The standard Django `pre_save` / `post_save` signals should work there, since snippets don't have the save-as-draft/publish workflow that pages do.
