### ISSUE TITLE
MVP user roles and permissions

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#2706]
Think about roles for managing topics, hierarchy stuff from the start.

**Comment by easherma** [comment]
https://github.com/cityofaustin/techstack/issues/472
https://github.com/cityofaustin/techstack/issues/666
https://github.com/cityofaustin/techstack/issues/687

**Comment by desigonz** [comment]
Made this an epic. A lot of the past issues are pretty old and we'll need to review for relevancy. For now putting this in the backlog til we're ready for it!
