### ISSUE TITLE
Joplin 3 - birds (🐦🐧🦜🦆🦅🦉🦢) eye view

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#2707]
### First edit

* come up with a plan for a new data model (https://github.com/cityofaustin/techstack/issues/2700)
* implement it in vanilla wagtail
* implement grapple or other api
* branch from janis and build against it
* implement author changes in a reusable way
  * If we package up our UI/UX changes into wagtail plugins, then we'll be able to ensure cleaner and repeatable implementations, as well as share/collaborate with the greater wagtail community.

## The Plan! (🧠dump right now)
1. Janis Model Audit
1a. Take the janis legos apart #2700 
1b. Figure out names for the legos (look at each component from janis and come to an agreement on an official name)
1c. Make an instruction booklet for the legos (document how the janis components interact with each other to form things, come to a consensus as a team around how the components combine to form things)
1d. Design a new kit (define a pseudo-api schema. This schema will be designed to make managing the data in Janis as straightforward as possible.)
![Untitledlego](https://user-images.githubusercontent.com/6384156/62743371-d6099380-ba07-11e9-9c5b-4b07c29a2068.png)

2. Wagtail model audit
2a. Figure out the best tools for the job to build each lego (best wagtail type for each data component)
2b. Prototype the box set (build out a couple versions of the data model, get a sense of what works and what doesn't)
2c. Try to build the prototype box sets (build a couple implementations of the API against the data model prototypes, see how close we can get to the API we designed.)
2d. Pick a prototype and document the reasoning behind choosing it.

3. Building things with legos!
3a. Implement a version of the data model and API in vanilla wagtail
3b. Build a version of Janis that runs against it

4. Setting the age ranges on the lego boxes (Define a permissions model - stretching the analogy here)
4a. Figure out who can edit what
4b. Implement the permissions model
4c. Test it
4d. Repeat b & c until "test it" is almost completely automated

5. UX improvements
5a. Break down author interface improvements into chunks (take @toribr's designs and other suggestions and see if we can do some clustering to find underlying issues that can be tackled together)
5b. Identify any "quick wins" where adding an existing plugin or settings tweak can get us close to solving one of the above issues
5c. Investigate solutions for above issues in ways that can be reusable
5d. Prioritize/Implement solutions

6. Getting our data in
6a. Figure out a way to consume the Joplin 2.0 API and get all of our old content
6b. Figure out a way to translate all of that into the new data model
6c. Make a "Get 2.0 data, translate it, and populate my DB with it" button

7. Preparing the switch
7a. Come up with a MVP checklist for the author interface
7b. Get a staging environment set up with Joplin 3 + Janis working
7c. Get a prod environment set up for Joplin 3, with *a* Janis pointing to it
7d. Get all content editors set up with correct permissions on Joplin 3
7e. Verify that the data imported works correctly with the permissions model, update the data model and permissions model as needed.
7f. Set a go-live date.

8. Going live
8a. Content freeze day: Clear the Joplin 3.0 prod DB, hit the "Get 2.0 data, translate it, and populate my DB with it" button
8b. Make sure everything looks fine with Janis and Joplin making the move (execute a preparatory test plan)
8c. Update prod Janis to the version that's working with prod Joplin 3.
8d. Make sure everything looks fine with alpha.austin.gov (final test plan)
8e. Celebrate 🎉

### No idea when these will happen but want to try
* Investigate react-streamfield custom logic (if we just make everything a streamfield, we may be able to have a incredibly simplified data model with a very customizable UI)
* Come up with some names, right now when we say Joplin, we mean:
  * The codebase
  * The live admin interface
  * Our data model
  * (it'd be cool to switch it up so we can distinguish between COA specific things (alpha data model) and general UX improvements for wagtail)

**Comment by Niicck** [comment]
### Also
- Translations

**Comment by desigonz** [comment]
@briaguya Do you want to keep this issue open now that Joplin 3.0 refactor is almost here?

**Comment by briaguya** [comment]
we're in prod
