### ISSUE TITLE
Set Janis URL from within Joplin /django-admin

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#2708]
This will make it easier for Joplin to sync to the right Janis frontend for PR builds.

Future Step: Add ability to deploy a Janis (that points to the right Joplin CMS_API) from /django-admin. Because Janis must be pointed to the same Joplin in order for Previews to work.

This would resolve https://github.com/cityofaustin/techstack/issues/2296
And alleviate the pain points of https://github.com/cityofaustin/techstack/issues/2415

**Comment by easherma** [comment]
http://docs.wagtail.io/en/v2.6.1/reference/contrib/settings.html
