### ISSUE TITLE
Guide: mobile nav

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#2709]
Create mockups for mobile nav. 

- Consider very long guides and very short guides and overcome the challenge of navigating very long pages
- Consider Global and Contextual navigational elements and ensure that their functions are clear to users
- Should we include "Back to top"?
- Should the navigation stick at a certain point (Mass.gov)

**Comment by chasechenevert** [comment]
# Pinup 1, Sprint 37

### Sticky bottom "Table of contents" button.

- Lower-third, easier for thumbs to access. There are many mobile patterns that use bottom navigation (bottom nav bar, forms buttons, chrome experiments)
- Opposite global navigation to avoid confusion with navigation types
- Opened menu initially overlays onto the page within the top two-thirds so that a user can see content behind the menu overlay. The intention is to avoid the user being confused by a page-level menu overtaking the screen suddenly, feeling like they've changed pages.

### Page level
1. Button is in-line until it is visible in the viewport 
2. Button sticks to bottom of screen until footer

### Component level

1. User `clicks` on ToC
    a. Menu flies up from bottom

2. User `clicks` on menu item
    a. Section and page indication changes to user's selection
    b. Menu collapses down 
    c. Page scrolls to user's selection

# Screenshots

![Web 1920 – 1@2x](https://user-images.githubusercontent.com/7027270/62962402-796df600-bdc4-11e9-8c3d-b59df36cbfc6.png)
![Web 1920 – 2@2x](https://user-images.githubusercontent.com/7027270/62962403-796df600-bdc4-11e9-9341-3387f519ba9d.png)
![Web 1920 – 3@2x](https://user-images.githubusercontent.com/7027270/62962404-796df600-bdc4-11e9-9aac-f85b8bd4501b.png)

# Next steps
- [ ] Incorporate "back to top" button
- [ ] Change button label to: "Table of contents"
- [ ] Visualize timeline of the interactions specified above 
- [ ] Connect with @kriskristin about how we might go about testing. Just to be clear, we haven't made the determination that we will test. Since this is a new pattern for alpha I'm wondering if we should vet this with users to detect any issues before sending along to dev.
- [ ] Investigate whether we can build that extra layer of interaction within another tool like webflow, axure, or figma that that we can achieve a higher fidelity.

**Comment by desigonz** [comment]
@desigonz to work with Chase to develop acceptance criteria

**Comment by desigonz** [comment]
Acceptance criteria for the mobile nav lives in #2783. Let's meet with the dev on this on Friday to review and see what's missing.

**Comment by chasechenevert** [comment]
Need to come up with a solution for the breakpoint between desktop and mobile. I don't think this will be challenging since the length of page titles are a constraint. I can tell that we'll need to default to the mobile (single column) view pretty quickly as this starts to resize. I'll mockup some solutions to get a rough idea of this.

**Comment by desigonz** [comment]
Thanks @chasechenevert! @Niicck will be the dev on this. 

How does meeting on Friday sound to y'all?

**Comment by chasechenevert** [comment]
Friday works for me. I'll have those mocks ready for then.

**Comment by chasechenevert** [comment]
Closing out: 
- Mobile and tablet specs were handed off to dev
- We had a quick sync meeting to review criteria
