### ISSUE TITLE
Get APH department page approved

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2715]
Draft: https://docs.google.com/document/d/1S7LjUH_K1CdJacZTHAR6YRMOC7tfSLjz0cl-wTb_t6U/edit
Preview:  https://alpha.austin.gov/en/preview/department/UGFnZVJldmlzaW9uTm9kZToxMTY1
Approved via email "Looks good" from Jen Samp on 8.13.19
Remaining to-dos:
- [x] Share preview link
- [x] Answer: Who should people call with general public health questions? Is there a good general contact number and email address? - asked in 9/16 email.

**Comment by annieszot** [comment]
@desigonz Sent you a [test] email to send to Jen for approving the Department page :)

**Comment by annieszot** [comment]
Next steps: 
- [ ] set APH translation goal sprint 37
- [ ] Share preview link
Closing issue
