### ISSUE TITLE
Publish Civic Futures Summit on civiqueso

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2717]
draft lives here: https://docs.google.com/document/d/13m40q3M2GlO7fpMSyq9fkWxywsThgY48O63JAeakGuQ/edit?usp=sharing

- [x] Revise it
- [x] Get images - Ben has them 
- [x] Publish it

**Comment by annieszot** [comment]
8.9.19 Comm channels: Permission to access requested from Ben. Slack. 
Revisions needed: 
-links where words are underlined
-Add alt text to your photos in Medium
--Medium alt text instructions: Click edit story. Select an image in your story and choose alt text
-Please add this after the lineup promotion paragraph:
Civic driven professionals from the City of Austin's Office of Design and Delivery will present on design thinking and writing for residents. Chris Luedtke, Service Design Practices Lead for the Service Design Lab, will co-facilitate design thinking and community driven design for better technology, programs and policies with Mari Nakano, Design Director for New York City's Service Design Studio. Content strategists Sarah Rigdon and Annie Szotkowski will host a Funshop to coach writing resident-friendly content then train professionals to spread the practice of writing for residents.
Will follow-up with requested deadline Monday, August 19 with email/Slack on Mon. August 9 and Wed. August 15

**Comment by annieszot** [comment]
Revisions added 8/13/2019

**Comment by annieszot** [comment]
Slack Medium article communications
August 9, 13, 15.

**Comment by annieszot** [comment]
Published! 
https://medium.com/civiqueso/join-us-for-the-civic-futures-summit-oct-1st-2nd-2019-ab020b62b344

**Comment by annieszot** [comment]
Closing :)
