### ISSUE TITLE
Refine content strategy onboarding docs

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2719]

**Comment by LauraTrujillo** [comment]
Welcome- Onboarding doc: https://docs.google.com/document/d/1ekcuyc0jMEGYqWThLBplbCCduxfCuTU0S1PoZHVqsgI/edit#heading=h.lx5ig3dxkprr
Content team's usage and style, etc... https://docs.google.com/document/d/1yL3afGS_72aFYBoF7ZH90yUCNeqAgYx1RuRxc_JbZAw/edit
