### ISSUE TITLE
Upgrade to Wagtail 2.6

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2729]
Wagtail 2.6 is now available. We need to upgrade!

Some notes from @briaguya [from here](https://github.com/cityofaustin/techstack/issues/2583#issuecomment-518916776):
> @easherma just tested out your https://joplin-pr-wagtail-26-upgrade.herokuapp.com/admin/pages/106/edit/ branch and found quite a few issues with our templates not liking the upgrade (looks like some css selectors we had before changed) and I still got a leave site alert trying to leave the edit page. Looks like we've got a bit of work on our side to be ready for 2.6.

Things to watch for:
- [ ] CSS selectors should be working as before
- [ ] Test out new leave site alert behavior (is it fixed, or same as before?)
- [ ] QA

**Comment by easherma** [comment]
@briaguya @desigonz so I believe some of the issues testing the heroku branch have to do with the way static assets are bundled differently on staging, local, or branch builds. 

I get different behavior locally than on heroku. 

The behavior I get locally is that the leave site error goes away, css outlines for accessibility are working, but the edit page dosen't look right. 

I think this may have more to do with our wonky javascript than even the templates changing, but I haven't ironed that out yet.

**Comment by easherma** [comment]
Bug 1: language fields aren't being hidden because the 'h2' tags were/are missing. Not 100% if this was a wagtail template change or a result of some of our code not being used correctly, but if the former we could ignore until we have a new translation strategy. 
Bug2: styling/overrides don't seem to be applying (mainly headings are pink and all that)

**Comment by easherma** [comment]
https://joplin-pr-wagtail-upgrade.herokuapp.com/admin/images/ Is the one to test
