### ISSUE TITLE
Department page top services & related information (long-term solution)

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2730]
### As a content editor, I want to be able to easily manage top services and related information on a department page so that I can deliver the information a user needs.

In #2691, we're implementing an interim solution for displaying top services and related information. Currently, department pages have a "related information" section that displays any pages associated with that department. However, this solution was implemented to serve the needs of Office of Police Oversight, but is not sustainable as we add more departments. 

We need a long-term solution that will work across multiple departments.

**Comment by desigonz** [comment]
Simplest implementation:
- [ ] Related information section on Joplin in which editors can select pages
  - [ ] Limit to 4

**Comment by toribr** [comment]
![#2730](https://user-images.githubusercontent.com/3790067/64981232-44e8d080-d881-11e9-9610-deb3e68a0574.png)

**Comment by toribr** [comment]
@desigonz @chasechenevert Chase, might be good to attach your dept page comp with only this component, and showing only four links.

Future versions would allow different styles of preview modules.
