### ISSUE TITLE
Linking inline phone numbers

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2731]
### As a resident, I want to be able to click a phone number in the body of a page in order to call that number, so that I have a seamless mobile experience.]

**Is your feature request related to a problem? Please describe.**
On the OPO complaint and thank you service pages, we've added phone numbers within an accordion. However, we have no way to make that phone number into a link! I tried both using the rich text block's link editor *and* using HTML. 

![image](https://user-images.githubusercontent.com/5839508/62874618-325e0300-bce7-11e9-8f77-87f4b0613cf6.png)

**Describe the solution you'd like**
We need a solution for linking phone numbers that is author-friendly. Could Janis automatically recognize phone numbers and create a link?

**Describe alternatives you've considered**

**Additional context**

**Comment by easherma** [comment]
https://github.com/wagtail/wagtail/pull/5478 @desigonz this will be possible in the next version of wagtail!

**Comment by desigonz** [comment]
@easherma you got a sense of timeline on that next version of Wagtail?

**Comment by briaguya** [comment]
deferring to @easherma on this one, what's the wagtail functionality look like?

**Comment by easherma** [comment]
@briaguya  you can see/try it in action on any rich text widget on this build:
https://joplin-pr-wagtail-27-test.herokuapp.com/admin/pages/5/edit/#tab-content

**Comment by easherma** [comment]
@desigonz this should be working via any rich text widgets in Joplin.

**Comment by desigonz** [comment]
Just verified this, looks great!

**Comment by desigonz** [comment]
Added the links to the OPO complaint and thank you service pages.
