### ISSUE TITLE
Publishing a topic collection without a theme

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2732]
**Describe the bug**
I broke Joplin staging when I published a topic collection without assigning it to a theme or another topic collection.

**URL**
http://joplin-staging.herokuapp.com/admin/login/?next=/admin/pages/3/

**To Reproduce**

1. Go to Joplin staging
2. Make a new topic collection by giving it a title
3. When you get to the edit page, publish the page (without adding a theme)

**Current behavior**
Joplin staging breaks.

Either a theme or a published topic collection (assigned to a theme) should be selected for it not to break. 

**Expected behavior**
Joplin staging doesn't break. Should we add required fields? 

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by easherma** [comment]
IIRC the create content model works around requirements by populating defaults in those fields. It's pretty ugly, but we could do that in this case. A better fix would be better. :-D

**Comment by desigonz** [comment]
Assigning @toribr to think about ideal behavior here.

**Comment by toribr** [comment]
It needs to be required before publishing. So the behavior should be that publishing is not allowed unless that selection has been made. Creating a draft is ok. Publishing is not. If it's not published then it won't break anything, right? ;)

**Comment by desigonz** [comment]
Let's look at this at today's dev/design sync, in conjunction with #2180

**Comment by easherma** [comment]
Idea 1:
Make _every_ field `blank=True` so the draft will save. But then on publish (maybe in the `save()` method) do long-hand form validation, and raise exception and add errors to missing fields?

Idea 2:
There’s probably a better way using `base_form_class` http://docs.wagtail.io/en/v2.6.1/advanced_topics/customisation/page_editing_interface.html#customising-generated-forms

Maybe make an intermediary class that stores draft data, and on-page-publish it _actually_ saves the page?

**Comment by desigonz** [comment]
@easherma @briaguya @Niicck Question: would publishing a topic collection without a theme on prod break Joplin prod?

**Comment by easherma** [comment]
@desigonz currently yes. This is a pretty bad bug. We should probably address it ASAP.

**Comment by desigonz** [comment]
okay it's queued up for next sprint, will discuss at dev/design sync

**Comment by easherma** [comment]
https://github.com/cityofaustin/joplin/pull/349/ mitigates this particular issue which should allow us to focus on the root cause(s) mentioned in the related issues
