### ISSUE TITLE
No indication of which kind of page you are editing on the edit page

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#2735]
While you are editing a page, there is no indication of the content type you are editing. 

This seems like this could be confusing, as we have different rules and guidelines for each content type and its hard to keep track of definitions. 

Ideally we'd have the style guide linked directly to the content type, but a) that is in progress and b) you may not think to look there and could browse away

Proposal:
Add the content type to the edit toolbar so it says some variation of: 
Edit ```name of page```, ```content type```

**Comment by desigonz** [comment]
In fact, @toribr is currently working on something like this in her current designs!

**Comment by desigonz** [comment]
Related to #2580
