### ISSUE TITLE
Day Labor Form: Email address cut off on review/submit page 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2739]
**Describe the bug**
Related to #2626. Email address
**URL**
https://opo.austintexas.io/request-day-laborer/2626-day-labor-content/review-and-submit
**To Reproduce**

1. Go to https://opo.austintexas.io/request-day-laborer/2626-day-labor-content/form 
2. QA form and fill out. Click continue
3. Review answers 

**Current behavior**

Email address is cut off on form review-submit page 
**Expected behavior**
User can view full email address. 

**Screenshots**

![Screen Shot 2019-08-14 at 8.53.05 AM.png](https://images.zenhubusercontent.com/5c4b52abd709c56fe9edad32/13df4e18-5b35-436a-9640-af583347ff86)
**Device**

Desktop
**Browser**

Chrome Version 75.0 
**Additional context**

**Comment by desigonz** [comment]
This is a known bug from the OPO form days: #1270. Backlogging this one for now.
