### ISSUE TITLE
Day Labor form: Edit OPO info on Confirmation Email

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2740]
**Describe the bug**
On the Day Labor Form confirmation email, Office of Police Oversight information is at the bottom. Need to correct that information. 

**URL**
Confirmation email 
**To Reproduce**

1. Go to https://opo.austintexas.io/request-day-laborer/2626-day-labor-content/form 
2. Fill out form. Click Continue. 
3. Review form and submit. 
4. Check email. Scroll and see error

**Current behavior**

See screenshot 
**Expected behavior**

Need to check with @desigonz or @LauraTrujillo about whether its Austin Public Health or the First Workers Day Labor Center address and information 
**Screenshots**

![Screen Shot 2019-08-14 at 8.56.33 AM.png](https://images.zenhubusercontent.com/5c4b52abd709c56fe9edad32/e26f6c75-e1f6-4074-9d05-d42b8888ddf3)
**Device**

Desktop
**Browser**

Chrome version 75.0
**Additional context**

**Comment by desigonz** [comment]
Let's use this contact info:

First Workers Day Labor Center
4916 North IH-35 Service Road
Austin, TX 78751
(512) 972-4100

**Comment by easherma** [comment]
@desigonz is there a contact email?

**Comment by desigonz** [comment]
@easherma Nope!

**Comment by desigonz** [comment]
This looks good!
