### ISSUE TITLE
Missing rich text blocks and weird indents

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2742]
**Describe the bug**
Lots of stuff: Weird display and indents throughout Joplin not appearing. Rich text blocks (including additional content on info and service pages, basic steps on service pages, and author notes on all pages) aren't appearing, even though they continue to publish out on alpha.austin.gov

**URL**
Joplin

**To Reproduce**

1. Go to Joplin
2. Click to edit any page
3. Scroll down to a rich text field (see above)

**Current behavior**

**Expected behavior**

**Screenshots**
Service page
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/25917d83-cd8f-4fee-a1bc-40b546aa5ded)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/ede4d7a7-78ea-4441-a465-8f6b785a27e9)

Department page w/ weird indents and author notes not appearing
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/899f60d5-839e-43cb-90d7-a0c9c95e10b1)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/7d456b11-69e3-4adb-92f1-7f3ef62611de)

**Device**

**Browser**

**Additional context**

**Comment by easherma** [comment]
https://github.com/cityofaustin/joplin/commit/f725040fe680edb5b515ad9f73833abfd79b0ca9
alright im gonna patch prod and just take the !important tag off that line of css to be as non-descructive as possible. it dosent seem to be an issue in staging becuase the template for the edit page has changed, i can do more digging to definitely describe the what/why/when but this ought to fix it in the meantime
but the TL;DR is probably something like >
If you write css like
```
label {
    width: auto !important;
}
```
Which puts an important tag on a very broad and general selector (not even a class in this instance), dont be suprised if the width of some labels get modified in some unexpected ways at some point
