### ISSUE TITLE
"External links to services" on topic pages

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2743]
**Acceptance criteria**
- [ ] When editing a topic page: remove the "external links to services" block

------------

### background

@toribr, not totally sure the background for this field and the use case. Can you review? Relates to translation model #2670

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/fdab7c47-2cbf-445b-b33c-3b53c2a61e1e)

**Comment by briaguya** [comment]
@desigonz it was on the whiteboard for this one: https://github.com/cityofaustin/techstack/issues/1641

> From @toribr on slack: "Because link to forms will likely commonly provide a service-like experience, i think we should be able to include links to them (via cards) in the same way that service pages are. So the links (on cards) from the OPO dept page should basically be able to be duplicated on a topic page as well. Make sense?"

**Comment by desigonz** [comment]
@toribr there's our answer!!! ☝️see above

Now we're moving to forms having an intro service page with contextual info. [File a complaint](https://alpha.austin.gov/en/health-safety/police-oversight-2/police-feedback-and-records/file-a-complaint-about-an-austin-police-officer/) and [Thank an officer](https://alpha.austin.gov/en/health-safety/police-oversight-2/police-feedback-and-records/thank-an-austin-police-officer/) are examples. Does that cover it for us?

**Comment by desigonz** [comment]
once @toribr responds, @briaguya can take it on

**Comment by toribr** [comment]
So, we did this to link to forms, and now that we are providing an intro page for every form (or we think) then I think it does make sense to remove it.

**Comment by desigonz** [comment]
Great! Ready for @briaguya to remove. Same acceptance criteria as above.

**Comment by desigonz** [comment]
@easherma to merge in master and run migration test
