### ISSUE TITLE
Clean up Joplin translations

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2744]
### As a content editor, I want translations in Joplin to be consistent so that I'm not confused about how to enter translations.

See #2670 for background.

**Comment by desigonz** [comment]
assigning @toribr to review acceptance criteria

**Comment by desigonz** [comment]
@toribr Can you review how you would expect official document translations to work? Should all fields require translations, etc?

**Comment by desigonz** [comment]
- [ ] @toribr to create a convention for non-translatable fields

**Comment by desigonz** [comment]
- [ ] @desigonz to review acceptance criteria now that Joplin isn't buggy

**Comment by desigonz** [comment]
I just reviewed acceptance criteria "All translations by page, not by field", and found that one of them is now fixed, but two are still outstanding. This is reflected in the acceptance criteria above.

Assigning to @toribr to develop patterns for how non-translatable should work.

**Comment by toribr** [comment]
(duplicating my comment from above to here)
@desigonz Good question. Might there not be legal ramifications with regards to translating an official document? Does it make sense to translate a summary but have the actual document in its original language? I feel like we need a content policy person who makes all decisions regarding how we handle translations.

**Comment by desigonz** [comment]
@toribr Great question, let's consider this one with @srigdon this coming sprint.

**Comment by toribr** [comment]
![Screen Shot 2019-08-29 at 10 29 46 AM](https://user-images.githubusercontent.com/3790067/63954049-162cc680-ca48-11e9-933a-b359b2f8b326.png)

**Comment by toribr** [comment]
![Screen Shot 2019-08-29 at 10 32 43 AM](https://user-images.githubusercontent.com/3790067/63954234-64da6080-ca48-11e9-9cc7-fd775a7c3779.png)
https://material.io/resources/icons/?search=lock&icon=lock&style=baseline

**Comment by easherma** [comment]
We have gone back and forth about whether we want translations to be by page or by field.

**Comment by desigonz** [comment]
@desigonz to split into multiple issues
