### ISSUE TITLE
Style for number ranges

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2748]
We need editorial style conventions for number ranges. Should we always default to using punctuation as opposed to "to"? En dash or hyphen? Spaces or no between numbers and punctuation? 

- [x] Make content governance decisions about this
- [ ] Update the style guide to include it
- [ ] Make issues to correct anything that's auto-generated, like the punctuation within contacts

![image](https://user-images.githubusercontent.com/5839508/63114114-9ee03880-bf59-11e9-9e00-5a5071e9b077.png)
![image](https://user-images.githubusercontent.com/5839508/63114223-e961b500-bf59-11e9-91d9-2497011ea795.png)

**Comment by desigonz** [comment]
Also take a look at "ages 1 to 44" in the [Injury prevent topic page draft](https://docs.google.com/document/d/1ZOyDgCdkniYDcwieivbN4UZXjc46bYEiTMxzx7eRQgA/edit)—would something like that require punctuation?

**Comment by srigdon** [comment]
Good question, @desigonz. 

* I added to the [style guide doc](https://docs.google.com/document/d/1yL3afGS_72aFYBoF7ZH90yUCNeqAgYx1RuRxc_JbZAw/edit#heading=h.v2926m4hzgf3) on that number range in a sentence question. 
* I added en dash rules to that section as well. 

@ablangworthy27 see above. Thoughts?

**Comment by ablangworthy27** [comment]
Thanks @srigdon. I'm going to implement these changes from the google doc into the official Gitbook guide, and then I will go through and make related issues

**Comment by ablangworthy27** [comment]
This is done and the resulting issue can be found here:
https://github.com/cityofaustin/techstack/issues/3219
