### ISSUE TITLE
Write tag style guide entry

### ISSUE THREAD

**Issue by courtneyjacinic** [cityofaustin/techstack#276]
- [x] Create Content @courtneyjacinic 
- [x] Review @ashleecoa @LauraTrujillo 
- [x] Uploaded to style guide @ashleecoa 
- [x] Send link to Tori to put into prototype @courtneyjacinic

**Comment by ashleecoa** [comment]
@courtneyjacinic let me know if this is ready for me to add to the Style Guide site!

**Comment by courtneyjacinic** [comment]
@ashleecoa Good to go!

**Comment by ashleecoa** [comment]
@courtneyjacinic https://cityofaustin.github.io/digital-services-style-guide/write-for-search/

**Comment by courtneyjacinic** [comment]
@toribr For the tagging helper text sections we have a link for the style guide to be added: 
https://cityofaustin.github.io/digital-services-style-guide/write-for-search/
