### ISSUE TITLE
Address and incorporate APH edits

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2770]
Austin Public Health sent back edits on the content sent to them via Sharepoint.
- [x] Incorporate 👍edits straight into Sharepoint docs
- [x] Clarify any questions they have/make our case for style things
- [x] Send email to Jen for second round of review

**Comment by Jo-Dwyer** [comment]
I'm working my way down through the edits documents in the APH Sharepoint folder. As of this message I've incorporated edits in "Basic services..", "Community development...", and "Free child safety seats".

Next steps:
-comb through google docs of each content draft 
-complete feedback for Jen directly in the feedback sheet that she sent to us
-ping you @desigonz when it's all complete for a once over before I send it to Jen

**Comment by desigonz** [comment]
I added some comments to "Basic services" and "Dove Springs" page. 

I'm struggling with the free child safety seat page:
- What is a child safety seat?? Is it the same as a car seat?
- The description field mentions "car seat checks," while the body text mentions "Free child safety seats." Those sound different to me.
- The title of the page is about child safety seats, but the description also mentions tax help, and the body text mentions other services. That is confusing to me.
- Lol Blue Santa. I would include a brief description with a link (so something like "Apply to receive toys for kids 14 and under through the [Operation Blue Santa](https://www.bluesanta.org/apply-solicitar)")

FYI we also have this page on child car seat checks: https://docs.google.com/document/d/1Vx7w4fGwk3ZAO7BQnuZgCcl-HJtfUw8Y1xa6GZn4IpM/edit?usp=sharing

**Comment by Jo-Dwyer** [comment]
- RE: Car seats : Travis County Health says "child safety seats"; everything I'm finding from CoA says "car seats". It's more descriptive so I'm going to change it in all places to "car seats".
- Check vs. free car seats: Yes, they are different, but both services are provided. Per Austin-Travis County EMS: 
"You have the opportunity to bring your car seat in to be inspected and ensure it is the correct type of seat and installed properly in the vehicle. Along with this, we provide families with car seats if they are in need of one."  http://www.austintexas.gov/page/car-seat-checks
- Could seasonal financial and family support be a different page where tax help and Operation Blue Santa lives, and car seat safety checks and free car seats live on their own?
- Yes. That's much better language!

**Comment by desigonz** [comment]
> Could seasonal financial and family support be a different page where tax help and Operation Blue Santa lives, and car seat safety checks and free car seats live on their own?

Yes, that's probably a good solution...I think Laura authored this and I'm not sure of the rationale of why it's split up this way. Maybe @annieszot knows? I think she reviewed the page.

**Comment by Jo-Dwyer** [comment]
Some content is ready to migrate, but others will need new page creation or additional clarification from Jen.

Questions:

- How/when do we encourage APH to create generic email addresses for diabetes testing etc?
- Downloads are sometimes a separate section (as in "Plan a smoke-free event") and are sometimes in-line links. Which is preferred?
- Some information is dependent upon APH to figure out as in the 2020-2021 school year application dates for AYC. How do we ensure that this gets updated? (This part of the Alpha IA, isn't it?)
- Are there links or contacts for next steps available to add to the "Help with child care expenses"?

**Comment by annieszot** [comment]
@Jo-Dwyer When your're free, can we meet up and you point to the content referred in Desi's comment above? Thank you in advance :)

**Comment by Jo-Dwyer** [comment]
- generic emails are being addressed
- downloads should be inline, not a separate section
- use evergreen content, and allow information for a specific year or event to be handled in communication with our SPOC

**Comment by Jo-Dwyer** [comment]
@desigonz  and @annieszot I created issues #2925 and #2926 to pull out financial and free fans info as new information pages. I'd like to send Jen Samp all of the pages to review—including new page drafts—in one request rather than overwhelm her with several.

**Comment by annieszot** [comment]
Superb @Jo-Dwyer ! Always helpful for partners to bundle drafts :)

**Comment by desigonz** [comment]
@Jo-Dwyer I think you meant issue #2927, not 2926?

**Comment by Jo-Dwyer** [comment]
@desigonz I totally did. Thank you!
