### ISSUE TITLE
Content not centering as expected in Day Labor form

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2772]
**Describe the bug**

On the form page, review page, and confirmation page of the Day Labor form, all of the content is off-center (flush to the left), but I expect it to be centered like in the OPO form

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/565e8879-6cbb-4278-8f39-fa2391012fe1)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/0d2ade1d-3c38-426d-9241-70a73592f8da)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/caf8e6c9-0ec0-4a2c-84fb-10e4eb324848)

compare to:
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/652d531f-72d3-4814-b54c-300c20e6f505)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/113b3df2-8f08-4baf-95e8-50b5aaf4dfdb)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/1464b592-edb4-4a4a-be46-1a33a54592c2)

**URL**

**To Reproduce**

**Current behavior**

**Expected behavior**

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by easherma** [comment]
FYI @Niicck 
i think that form not being centered was actually introduced awhile ago and no one noticed
my hunch being maybe when nick removed the progress bar
cause the compost form is not centered either, and I thought it might have been me cleaning up some css but even if i paste back in all the OPO css the form still isnt centered

**Comment by easherma** [comment]
@desigonz I'm not actually seeing this happen at the moment, or at least not consistently.

**Comment by desigonz** [comment]
huh you are so right. Let's close for now.
