### ISSUE TITLE
Translate APH department page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2776]
We've got a department page! Now we need to translate.
Draft: https://docs.google.com/document/d/1S7LjUH_K1CdJacZTHAR6YRMOC7tfSLjz0cl-wTb_t6U/edit
Preview:  https://alpha.austin.gov/en/preview/department/UGFnZVJldmlzaW9uTm9kZToxMTY1
Approved via email "Looks good" from Jen Samp on 8.13.19

- [x] Prepare and send to translators
- [x] Review translation when we get it back

**Comment by annieszot** [comment]
Dept page sent to translations 8.29.19

**Comment by annieszot** [comment]
Translations received 9.3.19
@desigonz Review from email?

**Comment by desigonz** [comment]
@annieszot Can you clarify your request—do you want me to review the translation?

**Comment by desigonz** [comment]
I think @Jo-Dwyer had some small edits. We should review the translation to make sure there is parity between the two.

**Comment by annieszot** [comment]
Reviewed 9.5.19 and incorporated edits into previews (Spanish and English): 
English: https://alpha.austin.gov/en/preview/department/UGFnZVJldmlzaW9uTm9kZToxMzI3
Spanish: https://alpha.austin.gov/es/preview/department/UGFnZVJldmlzaW9uTm9kZToxMzM2
