### ISSUE TITLE
Publish APH department page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2777]
Once we have the translations, let's publish!

**QUESTION: do we need an image to publish it?**

- [x] Publish department page
- [ ] Go through Alpha and assign all published APH info and service pages to this department page.

**Comment by annieszot** [comment]
https://alpha.austin.gov/en/austin-public-health
https://alpha.austin.gov/es/austin-public-health

**Comment by desigonz** [comment]
Awesome! I changed "Director" to "Directora" (matching gender) en español. And that's when I noticed that Farah's title on the OPO department page included her department so I went ahead and did the same for APH, but that's something we should either add to the style guide or in microcopy in Joplin. Or decide to omit it for any department.

![image](https://user-images.githubusercontent.com/5839508/64429826-7f31c100-d07c-11e9-82de-933cdd3b7f8f.png)

I'll also add this note in the style guide issue.
