### ISSUE TITLE
Top services on department pages

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2782]
### As a content editor, I want to be able to choose top services from a list of Joplin pages so that I have a smooth editing experience.

Currently, to add a top service on a department page, Joplin allows you to enter strings for the button content as well as a URL. Now that OPO forms are service pages, we'd like to replace this with a page picker. (This will also make the need to add translated version obsolete—this will automatically pull from the page content.)

For more context, see #2660.

**Acceptance criteria** (and see mock below)
- [x] Instead of using Streamfield, use a page picker (behavior should match what's being used for the guide type)
- [x] Users can select service, info and guide pages *(updated to include info pages, so as not to constrain ourselves unnecessarily, as I can imagine that an info page about a disease outbreak might need to be surfaced to "top". The selection of "top" should be addressed by the STYLE guide for the department page.)*
- [x] Users can add up to (and no more than) 4 top links

![2660](https://user-images.githubusercontent.com/3790067/63060190-232daf80-beb7-11e9-910c-c19905aa0703.png)

post-mvp
- [ ] When a user scrolls to the top services, the first option to add a page should be visible on the page by default

**Comment by briaguya** [comment]
@desigonz I think this and https://github.com/cityofaustin/techstack/issues/2792 will go hand in hand, if we can manage children of a department from the page we should have an easier time setting them as top.

Suggestion:
* In the short term:
  *Really dumb top services, we can add too many, we get a hack into janis to make sure they don't also show up in related information.
* In the long term:
  * Make "top" management a part of our IA refactor, don't just fix it for department pages but all page management

**Comment by desigonz** [comment]
Moved this to Joplin 3.0 for our long-term solution. For short-term solution, made issue #2800 to move different languages out of the Streamfield.

**Comment by desigonz** [comment]
@easherma to review Joplin and Janis PRs

**Comment by easherma** [comment]
I reviewed and left comments. 

Also, I'm wondering if pages should be restricted to pages that are already related to that specific department? As is you can assign any service, info, guide page as a top service for any department and it makes for a long list and probably isn't going to be what a department page owner wants or expects.

**Comment by briaguya** [comment]
@desigonz this is in staging for Janis and Joplin.

looks like the way it's implemented will prevent the top services part of https://github.com/cityofaustin/techstack/issues/2855 from working correctly.

**Comment by briaguya** [comment]
@desigonz official document pages for top services are working in staging now https://janis.austintexas.io/en/police-oversight/

**Comment by desigonz** [comment]
QA complete! looks great.
