### ISSUE TITLE
Implement guide: mobile nav

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2783]
### As a resident, I want to access guides on my mobile device so I can easily understand complex processes at the City.

XD link: [Mobile Guide Nav](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/a5132472-47f7-4fa1-ba90-223af090026f/Template-Guide-mobile-1)
[Tablet specs](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/0c710da7-eff9-4a62-b3bf-8b5adeec771e/Template-Guide-tablet/)

**Screenshots**

![Web 1920 – 1@2x](https://user-images.githubusercontent.com/7027270/62962402-796df600-bdc4-11e9-8c3d-b59df36cbfc6.png)
![Web 1920 – 2@2x](https://user-images.githubusercontent.com/7027270/62962403-796df600-bdc4-11e9-9341-3387f519ba9d.png)
![Web 1920 – 3@2x](https://user-images.githubusercontent.com/7027270/62962404-796df600-bdc4-11e9-9aac-f85b8bd4501b.png)

**Acceptance criteria**
- [x] When user opens guide on mobile, a table of contents (ToC) button appears on bottom of screen, `position: sticky;`.
- [x] When user taps ToC button, menu opens and initially overlays onto the page within the bottom two-thirds so that a user can see content behind the menu overlay.
- [x] When user taps on ToC, menu `eases in` up from bottom (.3 seconds)
- [x] When user taps on menu item:
  - [x] Background color `#ECF1F7` and right-arrow moves to user's selection, 0.3 seconds
  - [x] Menu `eases out` (down), 0.3 seconds
  - [x] Page scrolls to user's selection
- [x] When user selects browser back button when menu is opened, menu collapses
- [ ] User can swipe down to close the menu

**Comment by Niicck** [comment]
Deployed at https://deploy-preview-494--janis.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/
