### ISSUE TITLE
Create standard for input fields and focus in Joplin

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#2784]
Currently text fields and inputs have a number of different ways they display visually, both by default and on hover. Streamfield elements display differently, for example. 

This inconsistency comes into play when designing an element which does not look active to a user then, since different fields already look different from each other.

As a short term solution, a locked icon (with hover text "non-translatable field") will probably work, but long term, the visual consistency of the fields in a template should be redressed.
---
Related:
I just reviewed acceptance criteria "All translations by page, not by field", and found that one of them is now fixed, but two are still outstanding. This is reflected in the acceptance criteria above.

Assigning to @toribr to develop patterns for how non-translatable should work.

_Originally posted by @desigonz in https://github.com/cityofaustin/techstack/issues/2744#issuecomment-523475646_

**Comment by desigonz** [comment]
This will be looped into Joplin UI rehaul.
