### ISSUE TITLE
Remove "Leave page" alert when sharing or previewing a page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2791]
**Describe the bug**
"Leave page" page appears when you click the "share" or "preview" buttons. 

**URL**

**To Reproduce**

1. Go to Joplin and click "edit" under any page
2. Make a copy change on the edit page
3. Click "preview" or "share" buttons

**Current behavior**
Alert appears
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/9cd82585-abf9-477f-993c-5fec09565d4f)

**Expected behavior**
No alert should appear. You're not leaving the page!

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by briaguya** [comment]
@desigonz moving this to QA as it appears to be fixed with the wagtail 2.6 upgrade
