### ISSUE TITLE
Joplin - investigate many-to-many relationships for service page and topic

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#2792]
Using ParentalManyToMany (see http://docs.wagtail.io/en/v2.6.1/releases/1.9.html#many-to-many-relations-on-page-models) we should find out if:
* We can update our service page and topic models to use a different many-to-many relationship where
  * We can update which services pages are under a topic from a topic
  * We can update which topics a service page is under from a service
  * The updates are reflected by both edit pages

**Comment by easherma** [comment]
Early work on this here: 
https://github.com/cityofaustin/joplin/pull/341

**Comment by easherma** [comment]
@Niicck has also starting poking around with this

**Comment by desigonz** [comment]
This will be a part of the requirements I'm outlining in #3522
