### ISSUE TITLE
Remove bullets from meganav

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2794]
**Describe the bug**
Remove bullets from meganav—it was designed to not have bullets

*currently*
![image](https://user-images.githubusercontent.com/5839508/63481287-9d7fa600-c45a-11e9-9ce5-b99d065cda6d.png)

*as designed*
@chasechenevert please add mock here

**Acceptance criteria**
- [ ] No bullet points in meganav
- [ ] Topic collections in meganav styled according to mocks

**URL**
alpha.austin.gov

**To Reproduce**

1. Go to alpha.austin.gov
2. Click on any menu nav item
3. See error

**Current behavior**
Remove bullets from meganav. 

**Expected behavior**

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by briaguya** [comment]
@desigonz moving this to QA as https://github.com/cityofaustin/techstack/issues/1903 looks like it covers it. Since we don't have mocks yet we can move it back if there are missing changes.

**Comment by desigonz** [comment]
k sounds good!
