### ISSUE TITLE
Improve Joplin load times

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2795]
I'm occasionally but not consistently getting this error when I log into Joplin staging:
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/19188750-3a64-4390-8a65-8ea10aba7712)
That's because it sometimes takes longer than 30 seconds for Joplin’s pages page to load. Heroku times out. Taking 30 seconds for a website to load is not good.

Let's improve Joplin's load time.

**Comment by easherma** [comment]
Couple different options here: 

- Enabiling Redis for caching
- Enabling template caching in Wagtail
- Tweaking Heroku Dyno settings, especially using a bigger dyno

**Comment by easherma** [comment]
Load times are also slowing locally, so if we speed that up locally, we should realize some gains in the cloud as well. This is a good first step before resorting to staging/production cloud specific things. 

A good clean step for this would also be better splitting of dev, staging, and production settings for Joplin.

**Comment by easherma** [comment]
It appears that loading the create content modal is def slowing things down/delaying time to first meaningful paint.

**Comment by easherma** [comment]
performance audit on staging ![performance-staging](https://user-images.githubusercontent.com/10539855/63615318-aed7c800-c5aa-11e9-8d3f-c88af69093d6.png)

**Comment by easherma** [comment]
Also, heroku does not keep logs for very long. We should pick a log monitoring thingie.

**Comment by easherma** [comment]
Some performance profiles I ran:
[performanceProfiles.zip](https://github.com/cityofaustin/techstack/files/3535854/performanceProfiles.zip)

**Comment by easherma** [comment]
https://github.com/cityofaustin/joplin/pull/343 now shows significantly better load times:
![better](https://user-images.githubusercontent.com/10539855/63955486-6442c980-ca4a-11e9-8e8c-7fef53e6b9be.png)

Two main sources of improvement:
I simplified the operation required to check if there are author notes or not.
Static files are now gzipped, the biggest source of that being our webpack bundle and the create content modal. They aren't minified, but performance gains from that seem pretty...minimal (no pun intended). 

Other notes/learnings to follow, but it's ready for QA at 
https://joplin-pr-2795-joplin-load-tim.herokuapp.com/

**Comment by desigonz** [comment]
@easherma It's ready for QA or review?

**Comment by easherma** [comment]
https://github.com/cityofaustin/joplin/pull/351/ also improves performance
