### ISSUE TITLE
Document alpha.austin.gov

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#2798]
This should cover https://github.com/cityofaustin/techstack/issues/2700.

this includes getting all of the pieces of alpha documented in https://github.com/cityofaustin/alpha-documentation at the level we have for https://github.com/cityofaustin/alpha-documentation/blob/master/header.md including a table of where each piece of copy lives and any suggestions for improved places for it to live.

**Comment by desigonz** [comment]
@briaguya Do you want to keep this issue open now that Joplin 3.0 refactor is almost here?

**Comment by briaguya** [comment]
a lot of what I was hoping would come from this is now in prod as a part of v3
