### ISSUE TITLE
Implement service or process page for Foster form

### ISSUE THREAD

**Issue by juliazbyron** [cityofaustin/techstack#280]
All: Determine which of the start page text to move the service page, determine which information from the [current AAC service page](http://www.austintexas.gov/fosterpets) will move to the new service page, determine/create any information that is missing.

Courtney: Write/refine copy
Celine: Create/design service page
Julia: Advise

**Comment by juliazbyron** [comment]
I'll schedule a whiteboarding session for us for next week where we can map how the content will fit into the service page template and any changes that need to be made to make it work.

**Comment by juliazbyron** [comment]
Sketches from whiteboarding session with Celine. 

Next steps are @cthibaultatx will mock up a Service Page option and a Process Page option to present at the meeting with AAC on Wed 4/25. @cthibaultatx Can we have a quick review on this upcoming Monday or Tuesday before we present?
@courtneyjacinic I don't think you need to do anything until after the AAC meeting.

![img_0891](https://user-images.githubusercontent.com/13106016/39062878-ade7634a-448e-11e8-9414-1cc41d88d424.JPG)

**Comment by amenity** [comment]
Covered by #789
