### ISSUE TITLE
Triage: Host and manage documents

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2811]
By end of this sprint
- [x] Expose functionality
- [x] Look into different ways we can host and manage documents 
  - [x] Timebox this and propose solutions during next dev and/or design sync
  - [x] Create resulting issues

### As a content editor, I want the ability to upload and manage documents in Joplin.

Some of the things we could do or need to think of: 
- [ ] Expose documents on Joplin
- [ ] Where do the documents actually *go*?
- [ ] Fetching document URLs from API
- [ ] Need to test in prod *a lot*

This will probably take one sprint to develop and another to test.

**Comment by desigonz** [comment]
from @briaguya:
> I figure we can make a branch where we unhide documents and see what works and what doesn't and go from there a bit

**Comment by briaguya** [comment]
What I've learned so far:
* Wagtail hasn't implemented redirects for documents yet, while documents within wagtail do get stored on s3, the URLs within wagtail include a django serve view: https://github.com/wagtail/wagtail/pull/5296

It seems as though this gives us the option of either managing our document url building in Janis by using our Joplin URL (joplin.herokuapp.com/documents/{id}/{document name}) or (kinda hackily) keeping track of our s3 document urls on our own

I'm going to move forward looking into the s3 urls for now and we may be able to implement a cleaner solution once wagtail is updated.

**Comment by briaguya** [comment]
POCs here:
Joplin: http://joplin-pr-2811-play-with-docum.herokuapp.com/admin/pages/118/edit/
Janis: https://deploy-preview-504--janis.netlify.com/en/health-safety/health-records-certificates-2/birth-death-certificates/test-a-hosted-document

**Comment by desigonz** [comment]
@briaguya all of the issues we discussed today are logged in epic #2964. Closing this one!
