### ISSUE TITLE
Fix info and service pages on IE 11

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2830]
**Describe the bug**
Info and service pages are squishy on IE 11. Let's fix that!

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/813e7678-dddc-411c-b281-b0aadb60c329)

**Acceptance criteria**
- [ ] Info and service pages aren't squishy, and match how they look on other browsers

**URL**

**To Reproduce**

**Current behavior**

**Expected behavior**

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by briaguya** [comment]
working in prod now
