### ISSUE TITLE
Swap "contacts" icon on Joplin nav

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2831]
Let's switch the contacts icon to this little guy: ![baseline_perm_contact_calendar_black_18dp](https://user-images.githubusercontent.com/3790067/63540689-2e4d9480-c4e2-11e9-8cb2-c2490ea6f3bd.png)

**Acceptance criteria**
- [x] Joplin nav uses the icon above for "Contacts"

**Additional info**
Use this name in the code `perm_contact_calendar` (according to @chasechenevert here: https://github.com/cityofaustin/techstack/issues/2693#issuecomment-524366231)

**Comment by briaguya** [comment]
@desigonz this is on staging now.

**Comment by desigonz** [comment]
@briaguya looks great, QA complete
