### ISSUE TITLE
Audit existing components and content types

### ISSUE THREAD

**Issue by chase-gumbeau** [cityofaustin/techstack#2838]
# Audit existing components and content types in austintexas.gov

**Goal**
Discover and record what components and content types are needed to reach parity with austintexas.gov. This will help the design team understand what we will need in the near and future term so that as we're working we're thinking more holistically. We have some of this information in various places, I'd just like to gather it in one place.

## To-do
- [ ] Look through austintexas.gov and dev.austintx.gov and document components and content types in this [Janis 2: Visual design audit](https://docs.google.com/spreadsheets/d/1aSeJhXNhECYmyU4NWxGGlE_Z4Ou5OfIM2mpNSPC6IcA/edit#gid=1643602565) sheet. Be sure to note what components and content types we have in Alpha.

**Comment by chase-vert** [comment]
This issue is stale, and no longer needed
