### ISSUE TITLE
Copy edit for create content modal loading message

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2844]
**Acceptance criteria**
- [x] Loading message reads "Creating page" (no period, and "page" is lowercase)

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/1c7ad5c2-1359-4745-9c2f-964e7ed22f45)

**Comment by briaguya** [comment]
@desigonz this is on staging now

**Comment by desigonz** [comment]
@briaguya Looks great, QA complete

**Comment by briaguya** [comment]
this is on prod now
