### ISSUE TITLE
Test out APH department page on Joplin staging

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2854]
The APH department page is approved, and we're getting it translated. Yay!

We'd like to test out what the page will look like when it's published and when we've marked a bunch of service and info pages as "offered by" APH. Will it break anything? How will the "Related information" section work? See #2691 if you want more background on the latter question.

- [x] @annieszot, can you point @Jo-Dwyer to the draft?
- [x] Get @Jo-Dwyer access to Joplin staging (and Joplin prod while we're at it)
- [x] Create and publish the department page on Joplin staging
- [ ] Assign published APH service and info pages to that department page

@Jo-Dwyer, I think this will be a great way to get your feet wet with Joplin. As you use the author interface, we'd love to collect your feedback and capture any bugs. I can fill you in on best practices for writing new issues.

**Comment by annieszot** [comment]
@Jo-Dwyer [APH department](https://docs.google.com/document/d/1S7LjUH_K1CdJacZTHAR6YRMOC7tfSLjz0cl-wTb_t6U/edit) draft :)

**Comment by desigonz** [comment]
@srigdon to set Jo up with access

**Comment by Jo-Dwyer** [comment]
It looks like @annieszot put the APH dept page on staging a little while back https://app.zenhub.com/workspaces/techstack-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2854

I made a small edit (tracked in the google doc as a suggested edit). I'll get the hang of assigning pages this afternoon

**Comment by desigonz** [comment]
@Jo-Dwyer Okay cool, let's get that published on Joplin! (I think its in draft)

**Comment by desigonz** [comment]
Actually I went ahead and published it for guide purposes
