### ISSUE TITLE
Joplin picker page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2855]
### As a content editor I want page pickers to be contextual (show content details that are useful to the task at hand), so that I can easily edit a page.

**Acceptance criteria**
During dev-design sync on 8/29/19, let's review this acceptance criteria and see what makes sense for Joplin 2 and what should wait for Joplin 3.

### Selecting pages for a guide
- [x] Heading: "Select a page for the guide"
- [x] Alert message per mock that says "Only the following page types may be selected: information and service pages. All other types have been excluded from this list."
- [x] User can find a page via a search box
- [ ] Only display live pages
  - [ ] Info
  - [ ] Service pages
- [x] Column headings are accurate (authors has "Author" heading; status has "Status" heading)
- [x] When a user searches for a query, displays "There are x matches." where x is the number of results (and please add period at end of sentence 😇) (see "Search results" mock below)

![guide](https://user-images.githubusercontent.com/3790067/63887627-d52ea680-c9a2-11e9-92e5-bf5f75d8c65e.png)

Search results
![Search results](https://user-images.githubusercontent.com/3790067/63888019-a402a600-c9a3-11e9-9b99-4934ec749e2d.png)

### Top services on a department page
- [ ] Heading: Choose content to feature on the department page
- [ ] Alert message per mock that says "Only the following may be selected: information pages, service pages, official documents, and guides. All other types have been excluded from this list."
- [ ] Only display live pages:
  - [ ] Info
  - [ ] Service
  - [ ] Official docs
  - [ ] Guides
- [ ] Column headings are accurate
- [ ] When a user searches for a query, displays "There are x matches." where x is the number of results 

![Top services- dept](https://user-images.githubusercontent.com/3790067/63888020-a402a600-c9a3-11e9-924d-43fd07814aa9.png)
related department

### Offered by department
- [x] Heading: Add one or more departments that offer this page
- [ ] Only display live department pages
- [x] Column headings are accurate
- [x] When a user searches for a query, displays "There are x matches." where x is the number of results

![department 1](https://user-images.githubusercontent.com/3790067/63888038-aebd3b00-c9a3-11e9-8956-47492a2751f9.png)

### Selecting a topic on an info/service/guide page
- [ ] Heading: "Select a topic" 
- [ ] Only display live topics
- [x] When a user searches for a query, displays "There are x matches." where x is the number of results
![topic 1](https://user-images.githubusercontent.com/3790067/64433929-0f740400-d085-11e9-8a40-9957089b8919.png)

### Selecting a collection on a topic page
- [ ] Heading: "Select a topic collection" 
- [ ] Only display live topic collections
- [x] When a user searches for a query, displays "There are x matches." where x is the number of results
![topic 1](https://user-images.githubusercontent.com/3790067/64433929-0f740400-d085-11e9-8a40-9957089b8919.png)

**Additional info**
#2746, #2747, #2604

**Comment by easherma** [comment]
So it looks like we are looking for a component with very similar and consistent behavior such as:

- [ ] Only select live pages (and sometimes by type)
- [ ] Alert message that lists the limit criteria in effect
- [ ] Search box
- [ ] Correct columns/table listings in the template

We want the ability to differentiate:
- [ ] Headings
- [ ] Search/picker criteria (live, type of page)

**Comment by easherma** [comment]
So search by default is in the header, but we hide the default header for all pages. If possible, it would be great to extend and re-use the header and not hide it, as it has many things we are going to want. I'll still aim for a more short term solution with this picker, though.

**Comment by easherma** [comment]
@desigonz @toribr 
Couple comments/questions on copy for the Headings
The verb here for the page chooser by default is 'Choose'. Here we've got 'Select' as the lion's share, but one that is still 'Choose', and another that is 'Add'. Do we want the verbage to be consistent and/or are we trying to clue the user that there is some different behavior?

Which brings me to behavior: 
As is, you cannot select _multiples_ using this particular part of the view. In this view, you can only select one page, then you have to go back to the page you are editing, 'Add' another page picker, and then pick another page. I think we all agree thats a less than optimal UX flow, but for now this means language like:
"Add one or more departments that offer this page" 
is not going to match the functionality of the page. 

Similarly: "Choose content to feature on the department page" is a bit more vauge but also implies a plural. 

In order for these to be accurate to current functionality, it should probably say something like:
"Choose a page to feature on the department page"
"Choose/add a department that offers this page"

If we do want to be able to select multiple items in a single go, that's something we could totally support as a checkbox widget or something, but we'd probably want a new design for that or further specs.

**Comment by toribr** [comment]
Adding @srigdon since we looked at this together. 

My vote is
• "Add a department that offers this page"
* "Choose content to feature on the department page" ie, no change. I think it's better for them to think about this choice as content, not as a page. The implied plural imo doesn't matter. Neither do I believe there is any benefit to making the word choice exactly the same (select/choose/add) because users don't care and won't notice. We should simply pick the word that we feel works best. 

@srigdon ?

**Comment by easherma** [comment]
Took an initial stab https://github.com/cityofaustin/joplin/pull/355 and got 90% of the way there!

**Comment by srigdon** [comment]
Yep, @toribr I think those work for now. cc @easherma

**Comment by easherma** [comment]
viewable @ https://joplin-pr-2855-joplin-pickers.herokuapp.com/

**Comment by desigonz** [comment]
@easherma There are a number of things to do to meet acceptance criteria:

- [ ] Only display live pages (no drafts) across all pickers
- [ ] When choosing a topic collection on a topic page, heading should read: "Select a topic collection"
- [ ] When choosing a topic on an info, service, or guide page, heading should read: "Select a topic"
- [ ] Top services on department page should be a picker and should fulfill all of the acceptance criteria above

**Comment by desigonz** [comment]
Next steps: 
1. @briaguya to review code and give feedback
2. @easherma to finish acceptance criteria
3. It goes to @desigonz for final QA
4. If changes made, final review

**Comment by easherma** [comment]
Displaying only live pages is going to be trickier than previously estimated.
