### ISSUE TITLE
Revisit/refactor janis url construction in joplin

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#2856]
https://github.com/cityofaustin/joplin/blob/996ff9fda34b24e5ad6c79b33450842035e1379e/joplin/base/models/janis_page.py#L45

This function is currently needed in order to construct proper urls for previewing janis in joplin. 

However it is causing bugs (https://github.com/cityofaustin/techstack/issues/2732 ), may be causing some performance slowdowns ( due to stuff like ```self.topiccollections.all()``` querying the whole model rather than just checking if field exists or retrieving that field) , and is kind of a tangled list of conditionals. 

https://github.com/cityofaustin/joplin/pull/349 adds some simple error handling to log issues and prevent joplin breaking entirely, but it's also probably worth it to revisit this function to clean it up.

**Comment by desigonz** [comment]
@easherma to comment on things to check

**Comment by easherma** [comment]
https://github.com/cityofaustin/joplin/pull/350 this addressed the issue partially, but there is also some song and dance being done on Janis to put together links and URLs in other ways as well that we might be able to improve

**Comment by desigonz** [comment]
QA done, let's merge
