### ISSUE TITLE
Janis/Joplin - URL structure for information pages sans department/topic

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#2862]
### As a Joplin admin, I want the ability to publish a page that's global to the whole site.

**Acceptance criteria**
- [x] URL structure for global pages: alpha.austin.gov/page-title/
- [x] Custom logic to handle "this topic is global" in Janis (for URL)
- [ ] When editing page, an admin can indicate something is a "top-level page"

Post-MVP
"Global" topic or department that you can only access as an admin (user roles!!)

------

### background
This will enable us to publish out links that will be published in the footer (#2950).

We have a few information pages that won't be a part of a topic or department. How do we want their URLs to work?

**Comment by desigonz** [comment]
In the case of the [privacy policy](https://joplin.herokuapp.com/admin/pages/37/edit/), which will be linked to from the footer, I would expect alpha.austin.gov/privacy-policy/. All of our current examples of info pages that aren't related to topics or departments would be footer links.

@briaguya Is this doable with our current data model? We'll be needing this when we publish APH content.

**Comment by briaguya** [comment]
working through this and decided to try making a global topic/tc/theme, ended up running into this:
![Sep-17-2019 21-35-48](https://user-images.githubusercontent.com/6384156/65103197-25da6380-d993-11e9-8e47-834e6621c23f.gif)

so went back on the idea of needing more than just a topic, PR app link to come

I also started thinking about a good simple way to do this and get the ball rolling on permissions, which could look like:
Joplin:
* Create superadmin
* Add a "global' option to our janis pages for global that's only visible to a superuser
* Update the API to allow us to filter by global
Janis:
* Use queries with the filter to get all of the global pages
* Build those pages at the correct urls

**Comment by easherma** [comment]
can_choose_root=True might come in handy:
http://docs.wagtail.io/en/v2.0/reference/pages/panels.html#pagechooserpanel

**Comment by briaguya** [comment]
Current implementation building against staging here, there are a few things about it that are less than ideal/incomplete so it could use some work before it hits prod.

https://deploy-preview-517--janis.netlify.com/privacy-policy-for-alphaaustingov/

**Comment by briaguya** [comment]
Better implementation:
Joplin:
* PR App link to privacy policy: http://joplin-pr-2862-global-pages.herokuapp.com/admin/pages/37/edit/
* Created a new non-admin user (notadmin@austintexas.io, pw: x)
* If you edit a page as an admin and scroll to the bottom, there's a checkbox for global
* If you edit the page as a non-admin, you can't see the checkbox
Janis:
* PR app link to privacy policy: https://deploy-preview-519--janis.netlify.com/privacy-policy-for-alphaaustingov/

**Comment by briaguya** [comment]
Moved this to in review:
Joplin PR: https://github.com/cityofaustin/joplin/pull/372 (still needs confirmation with design/content about microcopy)
Janis PR: https://github.com/cityofaustin/janis/pull/519 (still need to confirm contextualnav behavior with chase)

**Comment by briaguya** [comment]
Branched off the janis PR here and added https://github.com/cityofaustin/techstack/issues/2996 to it.

New link for Janis:
https://deploy-preview-520--janis.netlify.com/privacy-policy/

**Comment by desigonz** [comment]
QA complete, ready to go to prod
