### ISSUE TITLE
Guide QA: Windows 7: Internet Explorer 11

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2873]
### desktop

Test the following features. Use the [bug report template](https://github.com/cityofaustin/techstack/issues/new?template=bug_report.md) to submit any guide bugs. Add the labels "bug" and "content type: guides".

URL to test: https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/

- [ ] UI Implementation matches design. Does the site look like the mocks? https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/58cef195-a92f-450c-ba2e-4124f44b9469/Template-Guide-desktop/
  - [ ] Intro block 
    - [ ] Title
    - [ ] Description
    - [ ] Image
  - [ ] Content
    - [ ] Contact information displays contact name, phone number, and email
    - [ ] Section headings
    - [ ] Content within each section
      - [ ] Clicking "View this page..." opens in a new tab (note: in order for this to work, each individual page needs to be assigned a topic or a department page in Joplin)
- [ ] Navigation and scrolling
  - [ ] Sidebar is sticky. When you scroll down to reach it, it should stay stuck.
  - [ ] As you scroll through the body content, the navigation reflects where you are in the content
  - [ ] When you click on a heading in the left nav, the body scrolls to the corresponding content
- [ ] Breakpoints for responsive design:
  - [ ] over 480px up to 767px is mobile
  - [ ] over 768px up to 1079px is tablet
  - [ ] over 1080px is desktop

**Comment by anukandimalla** [comment]
Bugs Reported for this page are #2892 #2893 #2895 #2897
