### ISSUE TITLE
Create Lambda function to handle Janis build jobs

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#2888]
One lambda function that connects Joplin to Janis. Pass in the Joplin Branch and the Janis Branch to create a new publish.

This would go nicely hand-in-hand with https://github.com/cityofaustin/techstack/issues/2708

We would be able to publish to any Janis from any Joplin (with whatever built-in restrictions we deem necessary, like only prod Joplin can build prod Janis).

**Comment by easherma** [comment]
Have we thought about just fleshing out our use of signals in Joplin to accomplish this?
http://docs.wagtail.io/en/v2.6.2/reference/signals.html
