### ISSUE TITLE
Look into alpha.austin.gov link error

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#289]
@mateoclarke found error in the logs: `RouteData or withRouteData couldn't find any props for path . You are either missing a route.getData function or you are relying on RouteData/withRouteData where you don't need to.`

When typing alpha.austin.gov into Chrome browser page comes up that is only header and footer. Can go to homepage that is ok by clicking alpha.austin.gov 'logo'.

**Comment by ifsimicoded** [comment]
Related to this issue logged on React Static Github -- https://github.com/nozzle/react-static/issues/567
