### ISSUE TITLE
Title max width

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#2897]
**Describe the bug**
Guide Title "Mobile food permitting process guide" is not responsive and didn't set to Max-width

**Acceptance criteria**
- [ ] Max width should be 572 px

**URL**
https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/ 

**To Reproduce**
1. Open  above URL
2. Notice Heading at the top "Mobile food permitting process guide"
3.Resize the browser size

**Current behavior**
Please refer to below screenshot
![Main heading](https://user-images.githubusercontent.com/52670306/64284011-38c65000-cf1e-11e9-8c72-cb0f9f2a7664.png)

**Expected behavior**
- [ ] Max width should be 572 px

**Screenshots**

**Device**
Windows 7-Desktop

**Browser**
 IE 11
**Additional context**

**Comment by desigonz** [comment]
@chasechenevert assigning to you to review how the title displays and specify acceptance criteria (or close the issue if it's not relevant)

**Comment by briaguya** [comment]
@chasechenevert pr app link: https://deploy-preview-518--janis.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide

css change in PR: https://github.com/cityofaustin/janis/pull/518/files

**Comment by desigonz** [comment]
Assigned @chasechenevert to review, do you have time to do this on Friday (9/20)?

**Comment by chasechenevert** [comment]
The expected behavior of 576px wide is correct

**Comment by desigonz** [comment]
@briaguya This looks good, ready to merge.
