### ISSUE TITLE
Translations options for Arabic and Vietnamese  are missing on Android Mobile Devices  

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#2898]
**Describe the bug**
Translations options for Arabic and Vietnam  are missing on Android Mobile  

**URL**
https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/

**To Reproduce**
1. Go to URL 
2. Check Secondary Nav for Arabic and Vietnamese Translation options

**Current behavior**
Please check the screenshot below
<img width="424" alt="Translation" src="https://user-images.githubusercontent.com/52670306/64286773-c48eab00-cf23-11e9-83e5-36d5f8e362c9.png">

**Expected behavior**
https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/a5132472-47f7-4fa1-ba90-223af090026f/Template-Guide-mobile-1/
**Screenshots**

**Device**
Phone: Galaxy s9,Pixel 3XL,Nexus 7,LG G5,Moto x Gen2

**Browser**
Chrome 71.0

**Additional context**

**Comment by chasechenevert** [comment]
We're only displaying languages that we have human-translated content for. We don't yet have human-translated content for Arabic or Vietnamese, so we don't show those language options in primary nav just yet.

**Comment by anukandimalla** [comment]
Wrote  this bug to keep track in future

**Comment by desigonz** [comment]
I'm going to close this issue—Arabic and Vietnamese are placeholders for the future in Chase's mocks.
