### ISSUE TITLE
Search Icon is Missing on the  primary nav Android Mobile device 

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#2901]
**Describe the bug**
Search Icon is Missing on the  primary nav Android Mobile device 

**URL**
https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/

**To Reproduce**
1. Go to  the above URL
2. search Icon is missing the top right corner

**Current behavior**
<img width="396" alt="Search Icon" src="https://user-images.githubusercontent.com/52670306/64288957-f0f8f600-cf28-11e9-8208-7225da1cf2dc.png">

**Expected behavior**
<img width="346" alt="ExpectedIcon" src="https://user-images.githubusercontent.com/52670306/64289103-39b0af00-cf29-11e9-8827-7655fc7f2353.png">
https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/a5132472-47f7-4fa1-ba90-223af090026f/Template-Guide-mobile-1/

**Screenshots**

**Device**
Phone: Galaxy s9,Pixel 3XL,Nexus 7,LG G5,Moto x Gen2 

**Browser**
Chrome 71.0

**Additional context**

**Comment by desigonz** [comment]
We haven't implemented search yet—that's a placeholder in Chase's designs for the future feature :)
