### ISSUE TITLE
Content Information is missing or needs to be updated on the Mobile Food Permit Guide on Android Mobile Devices 

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#2902]
**Describe the bug**
Content Information is missing or needs to be updated on the Mobile Food Permit Guide on Android Mobile Devices 

**URL**
https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/

**To Reproduce**
1. Go to the above URL
2. Scroll down the body content 
3. Notice at top of the body content
4. Missing the contact information

**Current behavior**
<img width="386" alt="ContactInoformation" src="https://user-images.githubusercontent.com/52670306/64290305-81d0d100-cf2b-11e9-9ef7-a2aad69d159b.png">

**Expected behavior**
<img width="335" alt="Expectedcontact Information" src="https://user-images.githubusercontent.com/52670306/64290427-b2b10600-cf2b-11e9-8536-dcdb6bc6a310.png">
https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/a5132472-47f7-4fa1-ba90-223af090026f/Template-Guide-mobile-1/

**Screenshots**

**Device**
Andriod phone:Galaxy s9,Pixel 3XL,Nexus 7,LG G5,Moto x Gen2

**Browser**
Chrome 71.0

**Additional context**

**Comment by desigonz** [comment]
@anukandimalla Don't worry about content parity—we're just testing functionality.
