### ISSUE TITLE
ToC hamburger menu icon

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#2903]
**Describe the bug**
Bottom Sticky Overlay has different Hamburger menu from the design guide 

**URL**
https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/

**To Reproduce**

1. Go to the above URL
2. See the Table of contents Sticky overlay 

**Current behavior**
<img width="418" alt="Table of content" src="https://user-images.githubusercontent.com/52670306/64291915-d4f85300-cf2e-11e9-8266-d3f395401923.png">

**Expected behavior**
![baseline-toc-24px](https://user-images.githubusercontent.com/52670306/64292048-1688fe00-cf2f-11e9-8549-0d0f7a342bca.png)
https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/a5132472-47f7-4fa1-ba90-223af090026f/Template-Guide-mobile-1/

**Screenshots**

**Device**
Andriod phone:Galaxy s9,Pixel 3XL,Nexus 7,LG G5,Moto x Gen2

**Browser**
Chrome 71

**Additional context**

**Comment by desigonz** [comment]
@chasechenevert Can you verify which icon to use? It looks like the icon in your mocks is upside down. Please close this issue if the one in development is correct.

**Comment by chasechenevert** [comment]
Implementation is correct, mock is wrong. Updated the spec, and closing this out.
