### ISSUE TITLE
Bottom sticky ToC button on Android

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#2904]
**Describe the bug**
Bottom Sticky Overlay is not centered on the Mobile page

**URL**
https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/

**To Reproduce**

1. Go to the above URL
2. See the Table of contents Sticky overlay

**Current behavior**
<img width="418" alt="Table of content" src="https://user-images.githubusercontent.com/52670306/64292205-741d4a80-cf2f-11e9-90aa-f7a925f15c04.png">

**Expected behavior**
<img width="419" alt="Expected TOC" src="https://user-images.githubusercontent.com/52670306/64292280-aaf36080-cf2f-11e9-9b1c-5fd89c34e9ac.png">

**Screenshots**

**Device**
Andriod phone:Galaxy s9,Pixel 3XL,Nexus 7,LG G5,Moto x Gen2

**Browser**
Chrome 71

**Additional context**

**Comment by robbobfrh84** [comment]
fixed with this PR: https://github.com/cityofaustin/janis/pull/515
