### ISSUE TITLE
Double scroll bar for Android devices

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#2905]
**Describe the bug**
Main page scroll is on top of the Table of the content overlay and the second scroll for page overlay appears simultaneously 

**URL**
https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/

**To Reproduce**

1. Go to the above URL
2. Click on Table of content sticky bar at the bottom
3. Can see page scroll which is over the overlay

**Current behavior**
<img width="419" alt="Pagescroll" src="https://user-images.githubusercontent.com/52670306/64293032-5b159900-cf31-11e9-9737-ec9b6b95cd91.png">

**Expected behavior**
<img width="315" alt="ExpectedTOC" src="https://user-images.githubusercontent.com/52670306/64293201-bcd60300-cf31-11e9-8d1e-ba6196a0d459.png">
https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/a5132472-47f7-4fa1-ba90-223af090026f/Template-Guide-mobile-1/

**Screenshots**

**Device**
Andriod phone:Galaxy s9,Pixel 3XL,Nexus 7,LG G5,Moto x Gen2

**Browser**
Chrome 71.0

**Additional context**

**Comment by chiaberry** [comment]
I  do not see a double scroll bar on my Pixel using Chrome. Maybe its been addressed with other changes?
