### ISSUE TITLE
ToC overlay horizontal rules

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#2906]
**Describe the bug**
Horizontal rule on table of contents overlay is missing and The line separator after Table of contact heading should not be there 

**Acceptance criteria**
@chasechenevert to define

**URL**
https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/

**To Reproduce**

1. Go to above URL
2. Scroll down to the Table of contact sticky overlay
3. click on the overlay to open

**Current behavior**
<img width="420" alt="Subdiv" src="https://user-images.githubusercontent.com/52670306/64295742-931fda80-cf37-11e9-9fd8-d0b4643a9f14.png">

**Expected behavior**
- [ ] Rules between section headings (bold) run full-width of the component
- [ ] Rules between pages are flush with the Section and Page title and go to the end of the component
<img width="318" alt="Expected subdiv" src="https://user-images.githubusercontent.com/52670306/64295793-ccf0e100-cf37-11e9-9854-e2a6bb75937f.png">

**Screenshots**

**Device**
Andriod Mobile phone 

**Browser**
Chrome 71.0
**Additional context**

**Comment by desigonz** [comment]
assigning @chasechenevert to develop acceptance criteria or close issue if it looks fine

**Comment by chasechenevert** [comment]
added another screenshot and a few bullet details under "Expected behavior" to help out, but otherwise this should just match the mock
