### ISSUE TITLE
Kick off emails to AAC and form user

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#291]
_from #269_

1. Confirmation email to applicant. (dependent on content taht @juliazbyron is working on with @courtneyjacinic)
2. New applicant data email mirroring existing email for copy/paste to Chameleon. see [email image](https://user-images.githubusercontent.com/1463708/38657329-30b7998a-3de5-11e8-9fdb-bc2c96c50460.png) 😞

We could use Matt’s Rails job dispatcher + email micro service in the short term or build our own emailing service.

Aha! Link: https://desi1.aha.io/features/RT-321

**Comment by cthibaultatx** [comment]
Joan from Communications & Public Information asked whether or not department teams will have access to the data from their forms. She works with Drupal forms and departments have to ask her for form data.
