### ISSUE TITLE
New Page: Split "Fall prevention class service page" into two pages

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#2910]
There are two audiences for information on the "Fall prevention class service page". 

Make a page for each audience with similar information and different context:
-[] seniors who want to register for the class
-[] community members who want to host the class

**Comment by desigonz** [comment]
Assigning @annieszot for first review

**Comment by annieszot** [comment]
Graciously handing this off to @ablangworthy27 for first review :)

**Comment by ablangworthy27** [comment]
I did the first pass, and it is ready for the second review!

**Comment by srigdon** [comment]
Looking good except for the fact-checking questions in comments. Per @Jo-Dwyer, we're waiting to hear back from APH friends. Closing for now, as splitting this into two pages is a good idea and has been accomplished. Create a new issue if needed for any future versions needed after review with APH.
