### ISSUE TITLE
Janis: Pagination for Official Documents

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#2912]
### As a resident I want to see a smaller amount of official documents at a time so that I don't have to scroll deep within a page to find an official document.

**Is your feature request related to a problem? Please describe.**
OPO will have up to 40 official documents listed and we need a way to restrict the amount of official documents viewable at a time so that users aren't overwhelmed with a long list of documents.

**Describe the solution you'd like**
A feature that allows us to reduce the amount of official documents displayed on a single page so that it's not overwhelming for the user to parse through a large volume of documents.

- Pagination
- List view

**Describe alternatives you've considered**
We may also need a way to allow residents the ability to sort/filter official documents on the Janis side.

**Additional context**

**Comment by toribr** [comment]
Changed the name from "organize" to include keyword "pagination". I found another page which will require this pattern pretty soon.
![screencapture-joplin-staging-herokuapp-admin-pages-172-edit-2019-10-04-10_36_55](https://user-images.githubusercontent.com/3790067/66221428-902e1c00-e694-11e9-83ba-5b6342139bb1.png)

**Comment by chasechenevert** [comment]
I connected with @toribr about the options I've been considering and we came to some decisions. 

## Options we've considered:
<img width="1042" alt="Screen Shot 2019-10-17 at 12 34 42 PM" src="https://user-images.githubusercontent.com/7027270/67033664-deeba500-f0db-11e9-82d1-4f5bde9aaba0.png">

1. **Number span with “previous” and next “buttons” with truncation** While not as elegant as the next two solutions, this implementation would allow a user to navigate across a set of pages better than simply needing to click "Next page" 8 times to get to the 9th page (as an example); the user would be able to jump across a wider number of pages. In the absence of the ability to tag, search, or filter information in a list, we think this functionality is more valuable than the below solutions. We will need to use truncation to prepare for cases where there are a large number of pages, and especially for mobile. 

2. **“Previous” and “Next” buttons.** Pretty simple solution, but doesn't give the user any further information about how many pages of results are in the list (especially in the absence refining the listing with filters, tags, or search).
3. **“Previous page” and “Next page” buttons that list “Page # of #” below.** Simple solution and provides more information than the version above, but also has the same drawbacks in the absence of filter, tag, or search. 

## Code examples for number span with truncation
- https://codepen.io/allicarn/pen/jPowab
- https://codepen.io/Mobius1/pen/gLdzJg

# Criteria
I'll be adding more to this as I go.
- [ ] Desktop and mobile should truncate, so the above example of "12 Elements" is the one we're going for
**Previous and Next buttons**
- [ ] Default state: tertiary style (gray fill, no border, primary blue text and icon) since these just control moving back and forward and are distinct from the page numbers which represent the pages themselves.
- [ ] Hover: fill goes to primary blue, text and icons go to` #FFFFFF`
- [ ] Click: fill changes to dark blue, text and icon remain the same
- [ ] Desktop: should show "Previous" and "Next" text labels to make things clear
- [ ] Mobile: should only use left and right chevrons to save space
**Page numbers**
- Default state: 

# Need to determine
- [ ] How many results per page?

**Comment by chasechenevert** [comment]
@desigonz This has been vetted with Tori, and I've got a good start on acceptance criteria, but given the complexity with pagination I know I'll be missing something. Maybe we can bring this up at dev/design sync?

**Comment by desigonz** [comment]
@chasechenevert added it to the list!

**Comment by desigonz** [comment]
Pagination component. Develop in storybook, write a test for it.

- [ ] @desigonz and @chasechenevert to create dev issues for this

Library we could maybe use: https://www.npmjs.com/package/react-paginate

**Comment by desigonz** [comment]
Acceptance criteria logged in #3247. We still need a decision on number of results to display per page, started a Slack thread about it.

**Comment by srigdon** [comment]
Re: button copy -- Sounds like we all like the third option because it's the clearest. (I'd edit it to "Previous" instead of "Previous page" and then underneath it in smaller text "Page X of Y" [so no need to repeat the word "page"].) However, per @chasechenevert: "because we don’t have any way to filter or search the list of documents there’s no way to jump through the data set. So say you want to view a record that’s 5 pages away, we don’t want the user to have to: click “next” 4 times (page loads, scroll to bottom, click “next” again) to get to the range of data they’re looking for. this pagination pattern will allow for jumping through large page sets much faster until we get tag/search/filter." 

In the meantime, it's Option 1, and for button copy "Previous" and "Next" is good.
