### ISSUE TITLE
Select contacts for all page types?

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#2914]
From a previous issue, we had this info:

> Are there any any page types that would not have any contacts associated with them?  

I don't see how this matters, but it's unlikely.

_Originally posted by @toribr in https://github.com/cityofaustin/techstack/issues/2702#issuecomment-521239252_

It sounds like all content types should be able to select associated contacts, in that case? According to the content model, Document pages do not. So we should update that.

**Comment by desigonz** [comment]
Per @srigdon, contact section on official document list pages aren't necessary, so closing this issue.
