### ISSUE TITLE
Translate the rest of OPO official docs

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2920]

**Comment by srigdon** [comment]
- [ ] Once we get all of the official docs finalized with OPO, I'll prep them and send to translation. 
- [ ] Get them back from translation (this should take a wild guess of about a week). 
- [ ] Input translated content in Joplin.

**Comment by desigonz** [comment]
OPO to deliver the rest of docs on Wednesday 10/2. Pushing this to sprint 41.

**Comment by srigdon** [comment]
This is finished except for a small batch sent out for translation today. 

- [ ] To do: discuss OPO managing translations directly. Talk to them, the translation firm, and @desigonz.

**Comment by srigdon** [comment]
I think we can call this issue done. Creating a new one, #3266, for OPO translations going forward, post-transition.
