### ISSUE TITLE
Triage: Style guide strategy

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2921]
Our [Digital Service Style Guide](https://cityofaustin.github.io/digital-services-style-guide/introduction/) is a product we offer that guides City of Austin staff in writing for residents. It needs some love. Let's take a look this sprint at existing style guide issues and come up with a  

- [x] Review all [style guide issues](https://github.com/cityofaustin/techstack/issues#workspaces/techstack-5a78b88e1ce69f3510b678ef/board?labels=style%20guide&notFullScreen=false&repos=118780243&showPRs=false)
- [x] Work with @desigonz to prioritize issues and establish a plan of attack
- [x] Share at content pin-up and get feedback

**Some background**
We need to decide on a longer-term platform for the style guide. #2380
We have made a lot of editorial style decisions that haven't been incorporated in the style guide or communicated outside of our team. #2165
We need have a lot of content types that haven't yet been added to the style guide. #2578
We need to practice what we preach by applying our editorial style to our style guide. #2166

**Comment by Jo-Dwyer** [comment]
@desigonz here's the order I see working

- [ ] choose a platform
   - [ ] gather relative benefits and limitations of GitBook vs GitHub
   - [ ] understand how hard is it to migrate between platforms?

- [ ] copy edit style guide using style guide (SG)
- [ ] compile all currently used editorial decisions and style conventions into SG
- [ ] add framework of new content 
   - [ ] content types
     - [ ] information page
     - [ ] guide page
     - [ ] department page
     - [ ] topic page
     - [ ] topic collection page
     - [ ] official documents
   - [ ] number ranges
   - [ ] fee tables

- [ ] submit for review by content team to consider style, language and governance

Long term (beyond MVP): 
- Create a heuristic set/define guiding values to create a test for suggested editorial conventions

**Comment by desigonz** [comment]
@Jo-Dwyer Let's chat about this today and make some new issues together!

**Comment by Jo-Dwyer** [comment]
I spoke with @easherma re: git(book + hub). It is possible to merge GitBook edits to the GitHub repo AND have that be linked to the little scroller iframe in Joplin. Eric scopes that work at 1-2 days. It would make it possible to use GitBook as our editor while also keeping the content up to date in both locations with little dev maintenance. @desigonz should we make some issues?
