### ISSUE TITLE
Apply service access framework to inventories

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2922]
We have done a few content inventories but haven't completed the corresponding service access frameworks. Let's complete those!

**Comment by matthewbarron** [comment]
Estimate at 5. This should be my priority for this sprint I feel. To get all on same page.

**Comment by matthewbarron** [comment]
Currently 9 audits that need S.A.F. applied. Purchasing	
Municipal Court	
Animal Center
311	
Code
Austin- Travis County EMS
Capital Contracting Office
Communications and Public Information Office
Transportation

**Comment by matthewbarron** [comment]
This is ready to be closed. My apologies on not looping back to confirm this with you.
