### ISSUE TITLE
Table of contents style fixes

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2923]
**How to replicate**
1. Use the guide in mobile
2. Open table of contents

**What happened**
Arrow styles as in screenshot below

**What I expected**
Arrows style with the following padding
- [ ] 16px of padding, all sides, for the whole menu
- [ ] 16px of padding between arrow and text labels
- [ ] this should take care of the mismatch between desktop and mobile, where on mobile the arrow pushes the text forward.
- [ ] Once you've implemented this in a PR app, please review with @chasechenevert 
- [ ] Also solve horizontal rule thing to match mocks here: #2906

The pink bars indicate the padding, all are 16px.
<img width="478" alt="Screen Shot 2019-09-11 at 1 28 46 PM" src="https://user-images.githubusercontent.com/7027270/64724462-273df480-d498-11e9-92ea-b4e9acdbdb1f.png">

**URL tested:** https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+6&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fjanis.austintexas.io%2Fen%2Fhealth-safety%2Fhealthcare-prevention%2Fdisease-prevention%2Fmobile-food-permitting-process-guide%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 6 |
| Browser | Mobile_safari |
| Operating System | iOS 11.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.3 x 4.1 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/7926ae311985bc27ac4533eda34e9c123f913010/realios_iPhone_6.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/7926ae311985bc27ac4533eda34e9c123f913010/realios_iPhone_6.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+6&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fjanis.austintexas.io%2Fen%2Fhealth-safety%2Fhealthcare-prevention%2Fdisease-prevention%2Fmobile-food-permitting-process-guide%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by desigonz** [comment]
@chasechenevert assigning to you to review the arrow padding and alignment and specify acceptance criteria

**Comment by chasechenevert** [comment]
- [ ] 16px of padding, all sides, for the whole menu
- [ ] 16px of padding between arrow and text labels
- [ ] this should take care of the mismatch between desktop and mobile, where on mobile the arrow pushes the text forward.

**The pink bars indicate the padding, all are 16px.**
<img width="705" alt="Screen Shot 2019-09-11 at 1 12 43 PM" src="https://user-images.githubusercontent.com/7027270/64723298-e218c300-d495-11e9-9588-3b9259ebf73f.png">
<img width="617" alt="Screen Shot 2019-09-11 at 1 10 43 PM" src="https://user-images.githubusercontent.com/7027270/64723543-53f10c80-d496-11e9-882b-37582c41a59c.png">

**Comment by briaguya** [comment]
@chasechenevert got a start on this here: https://deploy-preview-514--janis.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide

as far as I can tell it's looking good for items with only one line of text, but items with multiple lines are looking odd.

Any chance we could get a multi line design example added in?

**Comment by briaguya** [comment]
there seems to be a lot of styling work to do between this and https://github.com/cityofaustin/techstack/issues/2906, a lot of which is currently undocumented interaction behavior.

Everything in the menu has been pretty fragile so I've given this and 2906 3s so we can get it working smoothly

**Comment by chasechenevert** [comment]
this looks good to me!

**Comment by desigonz** [comment]
thanks @chasechenevert! Removing you from this issue.

**Comment by briaguya** [comment]
@chasechenevert @desigonz moving this to review, if we could get this QA'd here: https://deploy-preview-522--janis.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-vendor-permit-guide that'd be awesome!

dev note: PR here: https://github.com/cityofaustin/janis/pull/522

**Comment by desigonz** [comment]
Assigning @chasechenevert to QA on this one. I believe he's out of town today but will be in the office on Monday.

**Comment by chasechenevert** [comment]
This is looking good @briaguya. One thing I'm seeing: for bolded section labels that have at least 1 page within the section, the rule border value should be 0. This helps to relate the section label with the pages within that section.

<img width="683" alt="Screen Shot 2019-09-30 at 10 06 20 AM" src="https://user-images.githubusercontent.com/7027270/65891397-0adffa00-e36a-11e9-98a3-622c1e5f87ca.png">

**Comment by briaguya** [comment]
@chasechenevert updated it, putting this back in QA:
test guide: https://deploy-preview-522--janis.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/test-a-guide/
food vendor guide: https://deploy-preview-522--janis.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-vendor-permit-guide/

<img width="365" alt="Screen Shot 2019-09-30 at 11 55 55 PM" src="https://user-images.githubusercontent.com/6384156/65935786-f2aac200-e3df-11e9-842d-60792d8479f0.png">

**Comment by desigonz** [comment]
Looks good! I think it's ready to go.
