### ISSUE TITLE
Draft New Page: Free tax and financial assistance

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#2925]
Currently, the "Free car seats..." information page contains financial and seasonal information within information about free car seats. To make each information type easily searchable:

- [x] Create draft page "Free tax and financial assistance"
- [x] Include tax services and holiday gift assistance
- [x] what other information is needed to complete the page re: tax and financial assistance?
- [ ] send to @srigdon for review

**Comment by Jo-Dwyer** [comment]
@annieszot what's your take on this estimate? (2?)

**Comment by annieszot** [comment]
@Jo-Dwyer I've been estimating drafts as (2) but points can range from 2-3. I think (2) or (3) will work here.

**Comment by Jo-Dwyer** [comment]
@annieszot @srigdon Can either of you review this page before I send to Jen Samp at APH for approval?

https://docs.google.com/document/d/1qhqC8o2Ysv2xu0cu8ZxCogOhgVL0Ip5a_EnYSnPdcrs/edit#

**Comment by annieszot** [comment]
On it @Jo-Dwyer !
