### ISSUE TITLE
Draft page: Free clothing and fans at neighborhood centers

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#2927]
Currently, the "Free car seats..." information page contains financial and seasonal information within information about free car seats. To make each information type easily searchable:

- [ ] Create draft page "Free clothing and fans at neighborhood centers"
- [ ] Include free seasonal health and comfort services
- [ ] what other information is needed to complete the page ?
- [ ] send to @srigdon for review

**Comment by Jo-Dwyer** [comment]
@srigdon @annieszot Can either of you take a look and review this page before I send it to Jen at APH?

https://docs.google.com/document/d/1Gd9Tvg1gis0nJEkvRLTNwU0gdDgo7M8Lpi2J4WnrD3U/edit#

**Comment by annieszot** [comment]
On it @Jo-Dwyer !
