### ISSUE TITLE
Remove instances of language labels

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2930]
- [ ] Remove instances of language labels (ex. `[en]` and `[es]`) on edit pages
  - [ ] On info pages, remove from:
    - [ ] Title
    - [ ] Write a description of this page
    - [ ] Add option sections as needed.
    - [ ] Write any additional content describing the service
  - [ ] On service pages, remove from:
    - [ ] Title
  - [ ] On department pages, remove from:
    - [ ] Title
    - [ ] What we do
    - [ ] Mission
  - [ ] On topic pages, remove from: 
    - [ ] Title
    - [ ] Description
  - [ ] On topic collection pages, remove from: 
    - [ ] Title
    - [ ] Description
  - [ ] On guide pages, remove from:
    - [ ] Title
    - [ ] Write a description of the guide

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/38fdd34a-01a9-4dbf-ac80-07fd14d6082e)

**Comment by easherma** [comment]
`[en]` etc are generated automatically by our translation process. 
Those tags are also currently used to make the switching work.

So we'd need to make them invisible but still there or do more hacking with our translations to prevent them from generated (which sounds bad). 

They are distinct enough that some judicious regEx work with Javascript could suffice (and I guess we could trim them from the titles, make them invisible, or add them as an ID instead or something).

**Comment by desigonz** [comment]
Thanks! In that case deprioritizing this.

**Comment by easherma** [comment]
https://joplin-pr-2827-edit-page-heade.herokuapp.com/  should have no language bracket labels anywhere

**Comment by briaguya** [comment]
@easherma even though we covered some of this, we don't know all the acceptance criteria is covered, so we're putting it back in the backlog for now
