### ISSUE TITLE
Contact snippet translations

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2931]
### As a Spanish-speaking resident of Austin, I want to be able to see contact information (including contact title and phone descriptions) in Spanish, so that I can understand how to contact a City department or office.

**Acceptance criteria**
- [ ] Turn on translations for the following fields in Contact snippets:
  - [ ] Office name (Make sure data moves from name -> name_en (should be doable with our translation lib when making migrations))
  - [ ] Phone number labels (**note:** this is breaking something in Joplin. Need to figure out what's wrong and fix it)
- [ ] Run this Joplin implementation by @toribr and @desigonz 
- [ ] Translation fields appear in Janis

**Comment by easherma** [comment]
Should be chill assuming registering snippets with wagtail-modeltranslations doesn't have any problems. It's already registered for themes so that should be ok.

**Comment by desigonz** [comment]
@easherma yes. Also @toribr's taking a look at this one to make sure our acceptance criteria is clear.

**Comment by toribr** [comment]
![#2931](https://user-images.githubusercontent.com/3790067/64550758-3aff2480-d2f9-11e9-9579-ee6ef668f3e4.png)

**Comment by toribr** [comment]
Because Contacts is handled differently within wagtail, in that the content contained within each contact is shown separately from the page template, translation is more complicated than usual because it creates an additional step for the person entering the translations. Further, not all fields within contact require translating.

One presumes that the easiest path for the user is that the fields that require translating are surfaced in the same way as other non-snippet fields. (As opposed to needing to click into a widget, which has no signifier that any translation might be required, even.) In the same vein, displaying only fields that require translation - rather than all fields - simplifies the view for this user.

Lastly, are we assuming that once the relevant fields of a snippet are translated, that the translated version of it will be automatically propagated to the spanish version if the english version utilizes the snippet?

**Comment by easherma** [comment]
https://joplin-staging.herokuapp.com/admin/snippets/base/theme/1/ <--- see for an example of how snippets function currently when registered as a translations

I haven't done this yet, but I'd want to double check:
* how those fields are exposed in GraphQL and can therefore be used in janis
* what a reverse lookup along those model relationships would like like (this is mostly a dev thing, but understanding it means it could be easier to make translated fields visible in more places on the admin but still managed from a single palce)

When the snippet is then used, those fields should be associated as well. That means that translated fields of a snippet should tag along for the ride. The whole point of snippets to cut down the number of places where content that has to be re-used is managed and edited. 

The path of least resistance to me seems to be creating a similar filtered interface that we have for an edit page. But it also sounds like we might be talking about making a view specifically for entering translations. That could be cool, but might be more of a Joplin 3.0 thing.

**Comment by briaguya** [comment]
@desigonz looks like we need to define exit criteria here:
Super basic implementation that is also broken (https://github.com/cityofaustin/joplin/tree/2931-contact-translations) leads to:
<img width="1120" alt="Screen Shot 2019-10-14 at 10 31 24 AM" src="https://user-images.githubusercontent.com/6384156/66763719-fa517880-ee6d-11e9-8296-359aab8cbb2f.png">
^ what we currently have for snippets translation working in the branch.

<img width="1073" alt="Screen Shot 2019-10-14 at 10 31 36 AM" src="https://user-images.githubusercontent.com/6384156/66763793-1b19ce00-ee6e-11e9-9301-0c6c0e04fc84.png">
^ allowing translations for phone numbers breaks things, need to clean this up.

I see this issue as:
MVP:
* Implement name translation as-is
* Make sure data moves from name -> name_en (should be doable with our translation lib when making migrations)
* Fix phone numbers so we can edit them again
Next:
* Figure out a good way to get all the bonus junk from our page edit view into our snippet edit view.

**Comment by desigonz** [comment]
@briaguya Thanks makes sense, I think! Let's chat about it quickly when you're in the office today.

**Comment by desigonz** [comment]
Acceptance criteria updated above, let's go with that.

**Comment by desigonz** [comment]
Eric is recommending rethinking the snippet model (which means going to design). Deprioritizing this issue while we figure it out.

**Comment by easherma** [comment]
There are a couple potential technical issues; which might have mostly to do with wagtail-modeltranslation handling nested panels. We didn't full debug, may have to revisit later.

**Comment by toribr** [comment]
This issue progressed to #4186. Closing.
