### ISSUE TITLE
Game plan for wrapping up OPO content transition

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#2933]
- [ ] I'll do a quick audit OPO content that's still on austintexas.gov, compiling findings and recommendations for archiving and transitioning content. 
- [ ] Peralta and I will then review and determine what needs to get transitioned to alpha.austin.gov and what doesn't. 
- [ ] Review and approve with OPO stakeholders. 
- [ ] Create resulting issues.

**Comment by desigonz** [comment]
Sara Peralta is working on the audit.

**Comment by srigdon** [comment]
Update: Peralta is working on the audit. 

Meanstwhile, I'll be doing #3134.

**Comment by srigdon** [comment]
Peralta started the content audit and has delivered to ODD to finish. See #3526
