### ISSUE TITLE
Translations and style parity Style Guide  

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2935]
@Jo-Dwyer When requesting Austin Public Health's department page Spanish translations, the translations that were returned did not include style conventions on our bulleted lists. Commas are not included in the Spanish version. 
See [English] (https://alpha.austin.gov/en/austin-public-health) and [Spanish] (https://alpha.austin.gov/es/austin-public-health). 

What's your decision on whether language translations should match our comma style?

**Comment by Jo-Dwyer** [comment]
@annie I think for publication, the content is clear and we can go forward. For the near- to long-term I want to check in with digital.gov and other muni and fed guides to benchmark.

**Comment by annieszot** [comment]
SWEET. Love it. Thanks @Jo-Dwyer !

**Comment by Jo-Dwyer** [comment]
@annieszot do we want to leave this open to address translation style guide creation in the future, or do you feel like this has been addressed for the moment?
