### ISSUE TITLE
"Back" doesn't close guide ToC on mobile

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2936]
**Describe the bug**
Our acceptance criteria includes "When user selects browser back button when menu is opened, menu collapses" but I wasn't able to replicate on mobile.

**Acceptance criteria**
  - [ ] When user selects browser back button when menu is opened, menu collapses

**URL**

**To Reproduce**

1. Go to https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/
2. Click on table of contents
3. Try clicking back button

**Current behavior**
goes back to the page I was on BEFORE going to the guide

**Expected behavior**
ToC closes and I see the guide

**Screenshots**

**Device**
iPhone 6

**Browser**
Safari AND chrome

**Additional context**

**Comment by briaguya** [comment]
putting a 5 on this, sounds like we just haven't implemented anything that handles navigating back, and I don't think we have an example of this functionality anywhere else in janis

**Comment by desigonz** [comment]
Thanks @briaguya! @chasechenevert, I'm going to backlog this if you don't have objections.
