### ISSUE TITLE
"View this page on alpha.austin.gov" should open in new tab

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2938]
**Describe the bug**
At the bottom of each page or service block, link to the originating info ("View this page on alpha.austin.gov") behavior should open in a new tab. Currently it's opening in the same tab.

**Acceptance criteria**
- [ ] Clicking "View this page on alpha.austin.gov" opens in new tab

**URL**
https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/

**To Reproduce**

1. Go to https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/
2. Scroll down to content
3. Click "View this page on alpha.austin.gob"

**Current behavior**
opens in tab 

**Expected behavior**
opens in new tab

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by briaguya** [comment]
went ahead and merged this to master because it was a one line fix

**Comment by briaguya** [comment]
@desigonz this is fixed on staging now, assigned you and moved it to QA

https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide

**Comment by desigonz** [comment]
QA complete, works like a dream
