### ISSUE TITLE
Dark nav footer with utility links

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2948]
### Janis
Implementation matches design. All page mockups in XD have been updated with the new footer, and you can see the components in isolation here: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/e38bb76c-3af1-4d9f-8e26-266302647b4e/Component-Menus/
- [x] Dark style applied
  - [x] City seal delineates section below nav
    - [x] "Alpha.austin.gov is a work in progress..." language moved to to left side below the seal
    - [x] Social icons link to:
      - [x] Facebook: https://www.facebook.com/austintexasgov
      - [x] Instagram: https://www.instagram.com/austintexasgov/
      - [x] Linkedin: https://www.linkedin.com/company/city-of-austin/
      - [x] Twitter: https://twitter.com/austintexasgov
      - [x] YouTube: https://www.youtube.com/user/austintexasgov  
- [x] Below dark footer nav is another section with additional utility links. Note: For now; we only need to display [Privacy policy](https://joplin.herokuapp.com/admin/pages/37/edit/)
 to meet acceptance criteria

## Background
#2619

**Comment by briaguya** [comment]
@desigonz just want to confirm, this now just covers:
- [ ] Change styles so it matches XD
- [ ] Hardcode links to socials

**Comment by briaguya** [comment]
@desigonz @chasechenevert adding you to this and moving it to QA.

check it here: https://deploy-preview-532--janis.netlify.com/

**Comment by desigonz** [comment]
@chasechenevert Can you do a quick pass on the visual design, and check for breakpoints?

@briaguya I ran the footer through accessibility tools. For the social icons, thoughts about wrapping them in a `<ul>` and adding `aria-label` for the links?
 
![image](https://user-images.githubusercontent.com/5839508/65966250-7509a500-e425-11e9-8e2e-424da6b5d0e8.png)

**Comment by briaguya** [comment]
updated https://deploy-preview-532--janis.netlify.com/

 I added the aria-labels but didn't wrap the social icons in a list. I know if I do that I'll need to fight against some styling, so if it's good enough without the `<ul>` then I'd like to avoid that.

Questions for @desigonz:
* Is wrapping the social links in a `<ul>` required?
* What should the text for each aria-label be?

**Comment by desigonz** [comment]
Text for aria-labels can be simply: Facebook, Instagram, LinkedIn, Twitter, YouTube.

I'd not 100% on the `<ul>` for social links—I've gotten that feedback in the past when working with an accessibility consultant on a website redesign, but maybe we don't need it. And honestly I'm not sure who we would run it by to determine the best approach—maybe fellow devs or @chasechenevert?

**Comment by chasechenevert** [comment]
Sorry for this last minute catch, but we need to shift two color values for accessibility compliance. 
- Placeholder "Coming soon text should be" `#A3A3A3`
- Link hover color: `#AACDEC`

**Comment by desigonz** [comment]
Since this is already in prod, I made a new issue for this: https://github.com/cityofaustin/techstack/issues/3108

Closing this one
