### ISSUE TITLE
Determine content for form submission to AAC

### ISSUE THREAD

**Issue by juliazbyron** [cityofaustin/techstack#295]
I think that this will just involve determining how the information needs to be organized by speaking with AAC to determine which format of information will make it easiest to copy/paste into the database.

Then mapping the answers collected to that format so dev can create the email service.
https://github.com/cityofaustin/techstack/issues/291

Aha! Link: https://desi1.aha.io/features/RT-319

**Comment by courtneyjacinic** [comment]
@cthibaultatx @mateoclarke Let's make sure we bring this up in our 5/29 meeting with AAC!
