### ISSUE TITLE
Apply Janis to ReCollect and Trashy

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2951]
### Acceptance criteria
ReCollect:
- [ ] Link color: `#0049c7`
- [x] Button primary: background color: `#0049c7`; text: `#ffffff`
- [ ] Button secondary: background color: `#ffffff`; border: `#0049c7`; text: `#212121`
- [x] Application banner: `#162E51`
- [ ] Copy should be set in sentence case (right now it's using ALL CAPS)
  - [ ] What do I do with...
  - [x] Type the name of a waste item and we'll tell you how to recycle or dispose of it.
- [x] Type should be set in IBM Plex Sans.

Trashy:
- [x] Replace "X" close icon with Material Design's "close"; the icon is in the font set we have on Alpha, but if you need a direct link it's here: https://material.io/resources/icons/?search=close&icon=close&style=baseline

### Background
#849

**Comment by desigonz** [comment]
According to @Niicck, we hit some roadblocks here. Assigning back to @chasechenevert to review and see what acceptance criteria we're cool with losing.

**Comment by chasechenevert** [comment]
If we can't do the remaining items, then I guess this is done.

**Comment by desigonz** [comment]
Thanks @chasechenevert! @chiaberry and @Niicck, where is this in the QA and review process? Our flow is generally:
- If we can fully QA acceptance criteria in a PR app, we do that. You can assign the issue to me, and if I'm not the right person to QA I'll assign to the appropriate person.
- Code review usually can happen simultaneously, unless you think QA will really change up the code (am I right on this, @briaguya?)
- Push to staging
  -  If we were able to fully QA against acceptance criteria on the PR app, then the developer just needs to confirm the new feature is working as expected. 
  - If we weren't able to fully QA against acceptance criteria, assign back to me and we'll complete QA. (This usually happens when you have to change something on Joplin to see a result on Janis. Nick's working on a fix to that this sprint!)
- Push to production. Developer should confirm again that the new feature is working as expected.

**Comment by briaguya** [comment]
@desigonz agreed on simultaneous QA/code review, although there are times when it's nice to get QA eyes on something before cleaning up the code enough for it to be ready for review (especially when doing things with css)

**Comment by Niicck** [comment]
Right now, the issue has passed Code Review and QA, so I'll press the button to merge it into staging.

**Comment by desigonz** [comment]
@Niicck excellent thank you!

and +1 @briaguya.

**Comment by Niicck** [comment]
And deployed to Production
