### ISSUE TITLE
Connect OPO official documents to related content

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2953]
- [x] Meet to workshop through this user story and possible design solutions
- [ ] Make resulting issues

### As a resident reading official documents on the OPO's website, I want to understand what the documents are and how they fit in the complaint process. 

**Is your feature request related to a problem? Please describe.**
We need to link to a related page (https://alpha.austin.gov/police-oversight/complaint-investigation-process/) from the Official documents page. The description field does not let you do this.

**Describe the solution you'd like**
possible options:
- hyperlink within description fields? although description fields weren't designed for that.
- an additional rich text field that appears somewhere on the page
- Maybe in the sidebar, where contacts usually go?
- "Related information/pages" cards?

**Describe alternatives you've considered**

**Additional context**

Problem: 

The official documents content type doesn't currently have a way to filter or otherwise understand that there are different types of documents published on that page, or what that means or how the document types function in the complaint process. 

Ways to solve this:  

1. Link to the [complaint investigation process](https://alpha.austin.gov/police-oversight/complaint-investigation-process/) page from somewhere on the "official documents" page (see possible options above). Also, edit the complaint investigation process to include explanations of document types and where they fit in the process. 
2. Create a separate official documents page for each document type, then group them in a topic. 
3. Create a new way to display this info on the Official documents page.

**Comment by desigonz** [comment]
@srigdon I found an old issue that overlaps with this a lot. I'm adding it here and closing the other one.

### As a resident, I want to understand the context around the disciplinary outcomes documents that OPO publishes, so that I:
- understand the difference between what actions OPO took and what actions APD took
- have a clear sense of what actions APD took
- can be better informed about policing

When we display OPO cases that results in disciplinary outcomes, how might we offer some contextual information to make sense of a complicated process? Does this live on an information page?

**Comment by toribr** [comment]
In my view, the complaint investigation process document (linked to above) does not actually satisfy the use case of how the different document types relate to the process. So prior to deciding *how* to provide that information, it would be helpful to have a better understanding of *what* that information actually is. 

Secondly @desigonz the issue you added to this one is pretty different than the one here, and one far more complex, as it steps over the merely factual boundary into the cause>effect zone, which is territory we've been instructed to avoid.

**Comment by desigonz** [comment]
Thanks @toribr— I definitely see what you mean about these issues being different (with the second one as a more complex one). When we workshop together, maybe we should start by aligning on which user stories we're trying to solve now, and what we should backlog (especially based on stakeholder limitations).

**Comment by desigonz** [comment]
Thanks all for meeting! My next steps are to touch base with @oliver2g about contacting OPO with our recommendations for what to work on next. Closing this issue.
