### ISSUE TITLE
Copy edit to Spanish nav

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2961]
**Describe the bug**
We use "usted" when doing second person in Spanish, so we need to update this translation 

**Acceptance criteria**
- [ ] Text circled on the nav image below should read "Visite austintexas.gov..."

![image](https://user-images.githubusercontent.com/5839508/64797901-bfdf7d80-d547-11e9-8b85-422f8b22753a.png)

**Comment by desigonz** [comment]
looks great!

**Comment by briaguya** [comment]
in prod
