### ISSUE TITLE
Guide anchor links needs slowing down MVP

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#2962]
### As a user, I want to be able to understand how the structure of the guide works, by getting visual indications as I use it.

**Acceptance criteria**
When a user clicks on a section in the nav, there's a scrolling animation that takes user from the content they were on to the section they selected   
- [ ] Implement scrolling
- [ ] Back to design to determine scrolling speed.
- [ ] Implement the bonus junk.

Possibly import Material UI animations.

The linking to anchors happens too quickly. We need something like this: https://embed.plnkr.co/plunk/29jeYo There are other mo fancy things that do this too, like scrolly.js which includes a very cool blurring thing at the bottom. But at any rate, we need to do something. Probably you'll have the ability to add some ease in/ out or something to it. I can be more specific later but maybe like 500 swing to start?

**Comment by briaguya** [comment]
found adding `scroll-behavior: smooth` to our base.scss gets us somewhere, but gives us no control.

I'll play with setting up https://www.npmjs.com/package/smooth-scroll next

**Comment by briaguya** [comment]
@desigonz @toribr before putting time into investigating new scrolling packages right away, I'd like to see if what we have implemented here: https://deploy-preview-522--janis.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-vendor-permit-guide is good enough for MVP and we can put off coming up with a more flexible/complete solution til later.

**Comment by desigonz** [comment]
It looks pretty good to be but I want to hear @toribr's opinion. The ease in is oddly slow, could that be made quicker with the existing package.

**Comment by toribr** [comment]
I have the same question. The carburetor needs adjusting. :)

**Comment by desigonz** [comment]
Just messaged with @briaguya who clarified:
> Right now there's a one liner in there that makes it so instead of instantly jumping it scrolls as we see now. This is obviously less than ideal, and there is no way to change the speed/ease in on it. This is using pure CSS and not a library.

> In order to have more control over it, we'll need to do some exploring of different scrolling library options, hence the 5 points on the issue.

> I was just wondering if what we have now is good enough for MVP or if I need to dive into the 5 pointer and get it working, considering there are few things on deck (bugs blocking other issues etc.) that seem pretty pressing

We have a few more pressing dev needs right now (like some of the P3 bugs and the ability to upload documents in Joplin), so let's split these into two issues, with the current CSS implementation as MVP and then the improved library solution (#3065) for next sprint.
