### ISSUE TITLE
Test embed Formstack form in an alpha.austin.gov page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2979]
We're going to use Formstack for content manageable simple forms (see #2820). One idea is to embed simple forms onto a Joplin page, but first we need to:
- [x] see what happens to an alpha.austin.gov page when we embed a Formstack form in a rich text block using `</>`
- [x] look into what kind of dev work would be required to make embedding forms viable, if any
- [ ] create issues for that dev work we discovered

**Comment by Niicck** [comment]
Preview link available here: https://janis.austintexas.io/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxNDI1

**Comment by desigonz** [comment]
@Niicck Wowee you're a wizard! That was fast. I made #3008 for the design team to develop requirements, so closing this now!
