### ISSUE TITLE
Character count when adding an element to page after initial load

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2982]
**Describe the bug**
Character count fields for things like official documents are working—sometimes. The character count for these fields behave as expected per #2734 for fields that were already there when you load the edit page, but if you were to add another document, the character counts don't work.

**URL**
Joplin staging

**To Reproduce**

1. Go to Joplin staging
2. Edit an existing official document page
3. Scroll down to documents section. Character counts are working as expected!
4. Add a new document

**Current behavior**
Character counts don't work as expected in the new document you've added

**Expected behavior**
- [x] Character count behaves like the pre-existing documents:
  - [x] Character limits on edit pages uses the same patterns as on the create content modal
    - [x] Displays characters remaining
    - [x] When user goes over character count, the type becomes red and displays negative number
  - [x] Allows you to add more content than character limit, but with error messaging above

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by easherma** [comment]
@desigonz ready for QA, made a example test doc page here: 
https://joplin-pr-2982-widget-fix.herokuapp.com/admin/pages/118/

**Comment by desigonz** [comment]
QA complete! Looks beautiful.
