### ISSUE TITLE
First review for garden guide

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2983]
Review due by 9/26

- [x] @annieszot to make sure Google docs match austin.gov previews and add the Google doc links
- [ ] Review all of the content linked from here: https://docs.google.com/document/d/1qJxOnPWHso7E2RTdtWavCuZmYpzvDgMNdA7AoDcTlEY/edit#

**Comment by annieszot** [comment]
Assigning @Jo-Dwyer to first-round review (scroll down document to see pages linked to google docs). Requesting edits by Wednesday, September 25.

**Comment by annieszot** [comment]
Reassigning first round review of garden guide to @ablangworthy27.

**Comment by desigonz** [comment]
This issue is a bit stale—we workshopped the guide as a group (#3009). Closing this now, we're open a new issue when it's ready for review.
