### ISSUE TITLE
Send those ARR page edits for translation

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2984]
We need to translate the following into Spanish:
- #2919
- #2918
- #2917
- #2916

[guide to translating](https://docs.google.com/document/d/1vGsq17-a1Ho9gjkVBUiTNnPLsrGPkLfWKP7gPv5kpJ8/edit#heading=h.xbik72h24d7a)

**Comment by ablangworthy27** [comment]
Sent for translation!

**Comment by ablangworthy27** [comment]
Just received these back from translators and requested an invoice

**Comment by desigonz** [comment]
@ablangworthy27 Do you need any help reviewing the translations, or do you feel set to enter them into Joplin?

**Comment by ablangworthy27** [comment]
These translations have been added. They need to be reviewed by another set of eyes. OR we just assume everything is ok, since revisions were minimal. @srigdon @Jo-Dwyer @annieszot

**Comment by desigonz** [comment]
the embedded appblocks look amazing! And the Spanish does too.

**Comment by ablangworthy27** [comment]
these are published
