### ISSUE TITLE
Migrate information and department pages to style guide

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2985]
We have [info](https://cityofaustin.gitbook.io/digital-style-guide/pick-the-perfect-content-type/information-page) and [department](https://cityofaustin.gitbook.io/digital-style-guide/pick-the-perfect-content-type/department-page) pages on Gitbooks. Let's move them over to Github.
- [ ] review & migrate information pages entry
- [ ] review & migrate department pages entry

**Comment by Jo-Dwyer** [comment]
@desigonz if we choose to link the github repo and static site, the merge between gitbook and github will be made.

(correct me if I'm getting that wrong/not quite right @easherma )

**Comment by desigonz** [comment]
Confirmed in my notes [here](https://github.com/cityofaustin/techstack/issues/2254#issuecomment-532890153), so closing this issue.
