### ISSUE TITLE
Share out navigation research findings

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2986]
**Objective** 
We tested the nav. Let's share what we learned!

**Participants**
Required for content and design teams; optional but recommended for others.

**Agenda**

------
- [x] Schedule meeting
- [x] Meet
- [ ] Create resulting issues

**Comment by kriskristin** [comment]
@srigdon Are we good to close this? Are all issues documented?

**Comment by srigdon** [comment]
Documenting notes in the austin.gov > 01 Content > Information Architecture folder and issues as needed.
