### ISSUE TITLE
Start to think about user roles

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2987]
- [x] dig up old documentation

**Comment by toribr** [comment]
https://airtable.com/tbl81sEyDtax6CAqT/viw2xsBCXbdsghhAS?blocks=hide

**Comment by toribr** [comment]
Just some notes:
Content restrictions
-Admin should be able to assign users to dept; this will influence what content they see, and the topics and TC's they can add pages to
- will need to make a decision about business rule about what pages they can edit; all in dept, or only "their" pages? what about shared components (snippets?)

Publishing restrictions
- we need a workflow whereby authors can create a page, save a draft, and then notify an editor. Perhaps a "send to review" action where the recipient is established via settings.
• fields for editors
- email
- department
- name
• fields for moderators
- department
- email
- name
Admin user creation "Add user to department"
• select department
• add name
• email
• editor/moderator (one per dept to start?)
- presumably that editor can then view the page, make any corrections and then publish the page; no method for feedback in this workflow at this time.
