### ISSUE TITLE
ARR transition: What's done? What's missing?

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2989]
We've been writing ARR content and we think we're almost done! Let's double check our work to get a sense of what else needs to be done to fully transition.

- [x] @annieszot to review ARR alpha content drafts against inventory and come up with a list of what still might need to be transitioned
- [ ] Then @annieszot and @desigonz to meet and create issues together

**Comment by annieszot** [comment]
To create issues tomorrow for:
Universal Recycling Ordinance
Special Events Ordinance
Generation Zero Waste Free 
Parse out "documents" 
Polish rest of content

**Comment by annieszot** [comment]
New issues: 
Universal recycling ordinance #2685 
Special events ordinance #3166
Generation zero waste free #3167
Parse out "documents" page - link to zero waste content #2133 
Polish remainder of zero waste content/waste + businesses for transition #2133 #1725
Trash - save money by changing your cart size #3168 
Donate clothes & household items - #3169
Brush - ask ARR if need to include brush content

**Comment by desigonz** [comment]
Thanks @annieszot! Let's review these at backlog grooming.
