### ISSUE TITLE
Mock up new search user flow

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#299]
Mocked this up as part of the permitting process transition. Sketch file shows specific use case moving from Residential Permitting topic page to Residential Permitting Resource: Applications & Forms within search template/function.

There are opportunities for refined interaction design. Looking to @mateoclarke @ifsimicoded and @toribr to elaborate there :)

Sketch file: https://drive.google.com/open?id=1L14iZVx8KrXRDUs8mfa5hz1lZ3DWELXd

![screen shot 2018-05-18 at 2 33 16 pm](https://user-images.githubusercontent.com/20911665/40254292-739148fc-5aa8-11e8-85ec-0b84bda7e549.png)
______
![screen shot 2018-05-18 at 2 33 59 pm](https://user-images.githubusercontent.com/20911665/40254332-943b23fc-5aa8-11e8-8e26-64acd9f089c5.png)
______
![screen shot 2018-05-18 at 2 34 15 pm](https://user-images.githubusercontent.com/20911665/40254333-944f9a12-5aa8-11e8-97c9-135df5de051f.png)

**Comment by cthibaultatx** [comment]
@ifsimicoded @mateoclarke we'll review in 5/22 design-dev review to make any tweaks, break down into smaller chunks, and task build

**Comment by amenity** [comment]
@courtneyjacinic @ashleecoa @LauraTrujillo in your court to review

**Comment by amenity** [comment]
Moving into epic #258
