### ISSUE TITLE
Author name on document

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2991]
### As a content editor, I want to know who uploaded a document, so that I can search for my document without having to remember the file name.

**Acceptance criteria**
- [x] When users views document listing ([sneak peak here](http://joplin-pr-2811-play-with-docum.herokuapp.com/admin/documents/)), there is a column that lists authors
- [x] When selecting a document via a picker ([like on this page](http://joplin-pr-2811-play-with-docum.herokuapp.com/admin/pages/118/edit/)), there's a column that lists authors
- [x] Column is titled "Author"

![image](https://user-images.githubusercontent.com/5839508/64989149-8766d900-d892-11e9-92cb-fba8f30029fc.png)

**Comment by easherma** [comment]
Is this assuming we also are narrowing documents down by collections? 

We'll need to see what metadata is exposed to the document list template. If we're lucky, this is a field that we have easy access to in the template, in which case its just a matter of overriding default in a similar way we do for pages, which wouldn't take much work at all.

**Comment by desigonz** [comment]
Narrowing docs by collection is already happening:

![download-collection-filter](https://user-images.githubusercontent.com/5839508/65921496-04707300-e3a8-11e9-8da2-d04740c40f97.gif)

Let's keep this issue just limited to adding author name.

**Comment by desigonz** [comment]
Wondering @Niicck if you could explain why you size this one an 8?

**Comment by chiaberry** [comment]
@desigonz I'm not sure if you're the right person to ask, but I realized I just assumed the author column would be titled author and go right between "Collection" and "Uploaded". Are those correct assumptions?
<img width="996" alt="Screen Shot 2019-10-09 at 3 55 53 PM" src="https://user-images.githubusercontent.com/12474808/66519788-93b70e00-eaad-11e9-8567-ab86fdae0321.png">

**Comment by desigonz** [comment]
@chiaberry I am the right person to ask! And yes, good assumption and thanks for clarifying. We'll go with the title "Author" to match the column on the content listing page.

![image](https://user-images.githubusercontent.com/5839508/66520254-6d45a280-eaae-11e9-965e-ed2d5d66da70.png)

**Comment by chiaberry** [comment]
@desigonz thank you! I put the author's full name in there, but I can easily change it to the last name so it matches the Content page

**Comment by desigonz** [comment]
Great question. Looping in @toribr to decide on that. Tori, Chia defaulted to added author full name, which strikes me as a good idea. Thoughts? If so, Chia, feel free to share the PR app whenever it's ready for QA, and I'll make a new issue to change the author to first + last name in other places.

**Comment by chiaberry** [comment]
@toribr Here's the app: https://joplin-pr-2991-author-name-on.herokuapp.com/

**Comment by desigonz** [comment]
@chiaberry to add link to where we can test, then assign to @desigonz

**Comment by chiaberry** [comment]
ready for QA: https://joplin-pr-2991-author-name-on.herokuapp.com/

**Comment by desigonz** [comment]
@chiaberry looks great! Ready to go to code review and/or staging. You can just verify that it's working in staging, no need for a second QA.
