### ISSUE TITLE
"Places" and Google maps conversation

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2993]
**Objective** 
We're developing a new content type: Places! We're thinking about integrating Google maps to make info about City services easy-to-find and resident-friendly. We're also interested in a single source of truth. Let's talk about the potential and limitations of this solution.

Before this meeting, review [these notes](https://docs.google.com/document/d/1gHhYiFrPaNYJQf_j9qiSqJGVe7Nks-TurbQkmD8TdNs/edit#).

**Participants**
@toribr 
@chasechenevert 
@desigonz 
@briaguya 
@easherma 
@kriskristin 
@Jo-Dwyer 
@ablangworthy27 

**Agenda**

------
- [x] Schedule meeting
- [x] Meet
- [x] Create resulting issues

**Comment by Jo-Dwyer** [comment]
Hey all! Has this been scheduled yet?

**Comment by desigonz** [comment]
@Jo-Dwyer yes and you are on the invite
![image](https://user-images.githubusercontent.com/5839508/65466413-5e12f380-de24-11e9-9da0-08b8ed3bdbef.png)

**Comment by chasechenevert** [comment]
[Spreadsheet: Places model research](https://docs.google.com/spreadsheets/d/1CX6g504QM1LPhizY8mQ079RLpGr_14qffMOoFjU-TJw/edit#gid=1920159143)
This is the spreadsheet that we've created to develop an overview of the data types present on these pages. Huge shoutout to @ablangworthy27 for taking the baton; feeling good about what we've got!
