### ISSUE TITLE
Hardcoded link to privacy policy

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2996]
once we have #2862 
- [x] Hardcoded link to privacy policy

**Comment by briaguya** [comment]
this is up here: https://deploy-preview-520--janis.netlify.com/

**Comment by desigonz** [comment]
QA complete.

**Comment by desigonz** [comment]
@briaguya 
- [ ] verify in staging
- [ ] merge to prod and verify

**Comment by desigonz** [comment]
@briaguya can this go to staging and then production soon?

**Comment by desigonz** [comment]
QA complete, ready to go to prod
