### ISSUE TITLE
Janis/Joplin - make dept related information links manageable

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#2997]
Let's copy how we're doing Top Service links in departments and do that for related information links

**Acceptance criteria**
- [x] Page pickers for related information on Joplin
- [x] A Joplin user can select up to 4 related information pages
- [x] Related info appears on a department page in Janis

- [ ] Make sure OPO has the right pages on related info

**Comment by desigonz** [comment]
@briaguya I added acceptance criteria so we can test against it later. Please review and see if it makes sense!

**Comment by robbobfrh84** [comment]
I just wanna make sure I didn't miss anything. We don't have any new styles for the Janis side of things. Correct? @desigonz ![Screen Shot 2019-09-27 at 10.30.51 AM.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/79cd5a4c-0815-45fe-8b35-60c30b0b7d29)

**Comment by desigonz** [comment]
@robbobfrh84 No new styles, related info should appear as before!

**Comment by robbobfrh84** [comment]
PR UP:
- Janis: https://github.com/cityofaustin/janis/pull/541
- Joplin: https://github.com/cityofaustin/joplin/pull/383

- Deployed: https://deploy-preview-541--janis.netlify.com/

NOTE: you'll need to create new `Top Services` and `Department Links`
* Use `alpha.austin.gov` to duplicate what's on prod.

**Comment by desigonz** [comment]
@robbobfrh84 this looks great! I just did QA on the above. Once we push to prod, we'll need to make sure to add the following "Related information" to the [Office of Police Oversight](https://janis.austintexas.io/en/police-oversight):
- [ ] [How we store and use your data](https://janis.austintexas.io/police-oversight/how-we-store-and-use-your-data)
- [ ] [Complaint investigation process](https://janis.austintexas.io/police-oversight/complaint-investigation-process)

**Comment by briaguya** [comment]
in prod
