### ISSUE TITLE
"View Live" Links are broken

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#2999]
## **Describe the bug**
Clicking on "View Live" either 404s or doesn't load. Depending on the content type.

### Test pages that are live on the PR app: 
- [x] Service page
- [x] Info page
- [x] Department page
- [ ] Official document
- [ ] Guide
- [x] Topic
- [x] Topic collection

#### info pages
- [x] Information pages with no topics or departments (no valid url) **opens at http://joplin-staging.herokuapp.com/admin/pages/3/#**
- [x] Information pages with no topics, one department (department url) **opens at https://janis.austintexas.io/en/austin-public-health/mobile-food-vendor-permit-types-and-fees/**
- [ ] Information pages with no topics, multiple departments (first department url) ****
- [ ] Information pages with one topic, no department (theme/tc/topic url?) ****
- [x] Information pages with one topic, one department (theme/tc/topic url?) ****
- [x] Information pages with one topic, multiple departments (theme/tc/topic url?) **https://janis.austintexas.io/en/housing-utilities/recycling-trash-and-compost/compost-food-waste/testing-2607/**
- [ ] Information pages with multiple topics, no department (theme/tc/topic url?) ****
- [x] Information pages with multiple topics, one department (theme/tc/topic url?) **https://janis.austintexas.io/en/housing-utilities/recycling-trash-and-compost/compost-food-waste/2999-multiple-topics-one-dept/**
- [x] Information pages with multiple topics, multiple departments (theme/tc/topic url?) **https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/2999-mult-topics-and-depts/**
#### service pages
- [x] pages with no topics or departments (no valid url) **http://joplin-staging.herokuapp.com/admin/pages/3/#**
- [ ] pages with no topics, one department (department url) **This one seems to be 404-ing. Joplin: http://joplin-staging.herokuapp.com/admin/pages/158/edit/. Janis: https://janis.austintexas.io/en/austin-public-health/service-with-embedded-google-map**
- [ ] pages with no topics, multiple departments (first department url) ****
- [x] pages with one topic, no department (theme/tc/topic url?) **https://janis.austintexas.io/en/health-safety/health-records-certificates-2/birth-death-certificates/birth-and-death-certificates-test/**
- [x] pages with one topic, one department (theme/tc/topic url?) **https://janis.austintexas.io/en/health-safety/police-oversight-2/police-feedback-and-records/file-a-complaint-about-an-austin-police-officer/**
- [ ] pages with one topic, multiple departments (theme/tc/topic url?) ****
- [ ] pages with multiple topics, no department (theme/tc/topic url?) ****
- [ ] pages with multiple topics, one department (theme/tc/topic url?) ****
- [ ] pages with multiple topics, multiple departments (theme/tc/topic url?) ****
#### official docs
- [ ] pages with no topics or departments (no valid url) **goes to http://joplin-staging.herokuapp.com/admin/pages/3/#**
- [ ] pages with no topics, one department (department url) ****
- [ ] pages with no topics, multiple departments (first department url) ****
- [ ] pages with one topic, no department (theme/tc/topic url?) ****
- [x] pages with one topic, one department (theme/tc/topic url?) **https://janis.austintexas.io/en/health-safety/police-oversight-2/police-feedback-and-records/official-complaint-and-discipline-documents/**
- [ ] pages with one topic, multiple departments (theme/tc/topic url?) ****
- [ ] pages with multiple topics, no department (theme/tc/topic url?) ****
- [ ] pages with multiple topics, one department (theme/tc/topic url?) ****
- [ ] pages with multiple topics, multiple departments (theme/tc/topic url?) ****
#### guide pages
- [ ] pages with no topics or departments (no valid url) ****
- [ ] pages with no topics, one department (department url) ****
- [ ] pages with no topics, multiple departments (first department url) ****
- [ ] pages with one topic, no department (theme/tc/topic url?) ****
- [x] pages with one topic, one department (theme/tc/topic url?) **https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/**
- [ ] pages with one topic, multiple departments (theme/tc/topic url?) ****
- [ ] pages with multiple topics, no department (theme/tc/topic url?) **Got a 404 for this one. Joplin: http://joplin-staging.herokuapp.com/admin/pages/147/edit/ Janis: https://janis.austintexas.io/en/health-safety/disaster-safety-relief/disaster-preparedness/guide-name**
- [ ] pages with multiple topics, one department (theme/tc/topic url?) ****
- [ ] pages with multiple topics, multiple departments (theme/tc/topic url?) **This one is 404ing. Joplin: http://joplin-staging.herokuapp.com/admin/pages/151/edit/ Janis: https://janis.austintexas.io/en/housing-utilities/recycling-trash-and-compost/recycling-reuse/test-how-does-the-style-guide-show-up-in-joplin**
#### department pages
- [x] live **opens at https://janis.austintexas.io/en/austin-public-health/**
#### topic pages
- [x] live and assigned to an active TC (TC URL) **https://janis.austintexas.io/en/housing-utilities/recycling-trash-and-compost/compost-food-waste/**
- [ ] live and not assigned to an active TC (no valid URL) ****
#### topic collection
- [x] live and assigned to a theme (theme URL) **https://janis.austintexas.io/en/housing-utilities/recycling-trash-and-compost/**
- [ ] live and not assigned to a theme (no valid URL) ****

## **Process**
1. Make sure pages that are already live on the PR app have working links
2. Code review
3. Merge to staging
4. Make sure everything works in staging (including new pages, don't have those for PR apps still)
5. Merge to prod

**Comment by briaguya** [comment]
looks like something wonky is happening here:
https://github.com/cityofaustin/joplin/pull/351/files

**Comment by easherma** [comment]
can be QA'ed at https://joplin-pr-view-live-patch.herokuapp.com/admin/login/

**Comment by desigonz** [comment]
I did first round of QA on the PR build. I was able to verify that it worked for all content types except:
- [ ] guide
- [ ] official document
Both of those content types just link to here: https://joplin-pr-view-live-patch.herokuapp.com/admin/pages/3/#

**Comment by desigonz** [comment]
Removing myself from this issue for now. @easherma please assign me when it's ready for me to take a look again!

**Comment by desigonz** [comment]
This passes acceptance criteria! Woohoo! 

I did notice that it's confusing UX for pages that are published ("live") but not assigned to the IA, so there's no Janis URL for it. I made a new issue #3015 for design to chew on.

**Comment by easherma** [comment]
Didn't want to bury @briaguya 's not about more through QA, so here it is:
https://github.com/cityofaustin/joplin/pull/371#pullrequestreview-290172334

**Comment by desigonz** [comment]
okay then consider QA not complete. I'll get to those and add to the list.

**Comment by desigonz** [comment]
This is ready to go to production, unassigning myself.

**Comment by easherma** [comment]
https://github.com/cityofaustin/joplin/pull/371 merged this to staging, and its in prod now (i believe)
