### ISSUE TITLE
"Leave site" alert when you preview/share more than once

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3003]
**Describe the bug**
"Leave site" alert appears when you edit a page, click "preview" or "share", make some more edits, and then click "preview" or "share" again. It shouldn't.

**URL**

**To Reproduce**

1. Go to Joplin staging
2. Pick a page to edit
3. Make an edit
4. Hit preview (preview will open in new window; no "leave site" alert, which is good)
5. Go back to the Joplin tab and edit page some more.
6. Hit preview again
7. See error

**Current behavior**
"Leave site" alert pops up

**Expected behavior**
It shouldn't pop up, you aren't leaving the page!

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by easherma** [comment]
This bug could use a screencap or video and what Browser was being used. I wasn't able to replicate.

**Comment by desigonz** [comment]
@easherma Me neither. Closing this one.
