### ISSUE TITLE
General page view or empty search query returns author notes bug

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3006]
![joplinerr](https://user-images.githubusercontent.com/10539855/65175063-ba86a500-da17-11e9-863b-432ae97d0b60.png)

# To replicate:
Try an empty search, or visit https://joplin.herokuapp.com/admin/pages/search/?q=
Also happens at https://joplin.herokuapp.com/admin/pages/

Appears to be triggered by root or home page on this code: 
https://github.com/cityofaustin/joplin/blob/f9bd8b1a0b3a3dcaa2393fdd43c84dcbfff06b4a/joplin/base/wagtail_hooks.py#L136

Not urgent, but we'll probably want to fix before we start filtering the page listing or using search.

**Comment by briaguya** [comment]
accidentally fixed this here: https://github.com/cityofaustin/joplin/pull/399

**Comment by easherma** [comment]
https://joplin-pr-2581-pages-listing-s.herokuapp.com/admin/login/

**Comment by robbobfrh84** [comment]
This issue has been pushed to staging. I'm still not totally clear on our QA flow here... @desigonz ? 
- ¿ If i'm the person who merges it to staging, Should I assign a QA person ?

**Comment by briaguya** [comment]
@robbobfrh84 i generally:
* Move the issue to QA
* assign someone
* add a comment explaining where/how to QA

**Comment by robbobfrh84** [comment]
This issue is now in staging and can be tested by ... 
- Run an empty search in janis: now, you'll see a valid return (rather than the error, from ☝️prod above)
- Or, sample link: https://joplin-staging.herokuapp.com/admin/pages/search/?q=

**Comment by desigonz** [comment]
@robbobfrh84 Beautiful! QA complete. This can go to production.
