### ISSUE TITLE
Simple form style requirements

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3008]
@Niicck made a theme in Formstack, then built a form and embedded it on an alpha.austin.gov pag! [Preview the form.](https://janis.austintexas.io/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxNDI1) All it takes is [adding an iframe into a codeblock](https://joplin-staging.herokuapp.com/admin/pages/161/edit/). Nick is also thinking about how to version control Formstack styles. 

https://cityofaustin.formstack.com/forms/ni_request_day_laborer

Your mission: review what the embeds look like and develop design acceptance criteria for form styling and what the embed looks like on a page. Or do we not want to embed at all? Let's think about:
- [x] accessibility
  - [x] We'll want to test iframes with David Ondich
- [x] mobile/responsiveness
- [x] would the iframe embed make it difficult to track analytics and load time?

Not sure how much control we'd have over error messaging, but that's also something to consider.

**Comment by easherma** [comment]
We probably also need to re-test for accessibility and it isn’t very mobile friendly atm

**Comment by Niicck** [comment]
Here's the link to the direct website: https://cityofaustin.formstack.com/forms/ni_request_day_laborer

**Comment by Niicck** [comment]
And yes, we would have more control over error messaging. I just lost my Formstack account before I could get to it. 😬

**Comment by desigonz** [comment]
Thanks @easherma and @Niicck!

Team, let's also get a list from Soolin of forms currently embedded on Drupal and check out what that looks like.

**Comment by toribr** [comment]
We should also consider the behavior of including a form in a guide.

**Comment by desigonz** [comment]
Woah. Form in a guide.

I just asked Soolin for examples of embedded Drupal forms, will share with y'all once I hear from her.

**Comment by desigonz** [comment]
Soolin shared [central preparation facility registration](http://austintexas.gov/page/central-preparation-facility-registration) as an example of a Formstack form embedded in austintexas.gov.

**Comment by toribr** [comment]
Using GA in iframes:
https://support.google.com/analytics/answer/1012049?hl=en

**Comment by desigonz** [comment]
- [ ] @desigonz to get embed code from Formstack so we can play around with it

**Comment by desigonz** [comment]
What happens when a form is in a guide?

**Comment by desigonz** [comment]
@toribr This is the embed code that Formstack gives me:
`<script type="text/javascript" src="https://cityofaustin.formstack.com/forms/js.php/ni_request_day_laborer"></script><noscript><a href="https://cityofaustin.formstack.com/forms/ni_request_day_laborer" title="Online Form">Online Form - NI Request Day Laborer</a></noscript>`

![image](https://user-images.githubusercontent.com/5839508/66168655-637df400-e603-11e9-8858-a7dabb1bd27b.png)

**Comment by desigonz** [comment]
Thanks @toribr! Yes, let's talk in pin-up, I have questions. 

Have you tested what the forms look like in mobile? Also, any thoughts on what embedding the forms means for analytics? And finally, is there any frontend work we need to do accessibility-wise for the forms?

**Comment by toribr** [comment]
We want *somehow* for the form rendered in Janis to match our form guidelines, ie, fields aren't stacked, there aren't labels underneath fields, and so forth.

So we need to find out what can be done in formstack to adhere to the form guidelines.

**Comment by briaguya** [comment]
Issues to come from this:
@Niicck to look into Joplin/Janis form stuff
@toribr to look into formstack styling

**Comment by toribr** [comment]
![Form - 3008](https://user-images.githubusercontent.com/3790067/66946094-d6309b80-f015-11e9-9813-3b9819c0ccac.png)

**Comment by desigonz** [comment]
@toribr and @chasechenevert to pair up over sprint 42 and deliver:
- [ ] CSS specs
- [ ] designs for error message handling

**Comment by chasechenevert** [comment]
Components
- [ ] Heading
- [ ] Label
- [ ] Hint text
- [ ] Field/text area
- [ ] Button
- [ ] Dropdown
- [ ] Checkbox
- [ ] Radio button
- [ ] File input

States
- [ ] Default
- [ ] Focus
- [ ] Active
- [ ] Hover
- [ ] Select
- [ ] Success
- [ ] Error
- [ ] Required

**Comment by chasechenevert** [comment]
@desigonz I think this is ready now, but as usual, I'm sure there's something else I'm not aware of or may need to tweak once seeing it implemented.

**Comment by desigonz** [comment]
Thank you @chasechenevert! I'll make the new issue for dev, and if anything comes up later, y'all can file new issues for that.

**Comment by desigonz** [comment]
Acceptance criteria logged in #3288. Closing this one!
