### ISSUE TITLE
Garden guide workshop

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3009]
**Objective** 
Annie wrote the first draft of the garden guide: https://docs.google.com/document/d/1qJxOnPWHso7E2RTdtWavCuZmYpzvDgMNdA7AoDcTlEY/edit#
Let's workshop it!

**Participants**
@toribr @annieszot @srigdon 

**Agenda**

------
- [x] Schedule meeting
- [x] Meet
- [x] Create resulting issues

**Comment by annieszot** [comment]
Supporting documents 
Strategic Direction 2023
[Community garden resolution ](http://www.austintexas.gov/sites/default/files/files/Parks/communitygardens/resolution.pdf)
[Garden ordinance](http://www.austintexas.gov/sites/default/files/files/Parks/communitygardens/urbanagriculture_ordinance2.pdf) (application and license agreement) 
[Garden ordinance](http://www.austintexas.gov/edims/document.cfm?id=149063) (exemptions)
[Garden ordinance](http://www.austintexas.gov/edims/document.cfm?id=149062) (water meter and tap waivers)

**Comment by annieszot** [comment]
Resulting issues #3125 #3126 
Closing!
