### ISSUE TITLE
Communicate new link to Funshop list

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3013]
- [ ] email Funshop list with the new style guide link

-----

### As a City of Austin staff member, I want to be able to refer to the style guide link I bookmarked and be directed to the most up-to-date style guide, so that I can use the resource when developing content. 

The current Gitbook is *not* the link that we shared around the City a long time ago (so things like Sara P's bookmark and the Forms Style Guide point to something that's broken). Some options:
  - Communicate a new link to folks.
  - Set up a redirect, if possible?
  - Set up our old Gitbook to say "We've moved!" with a link.

See more context here: #2254

**Comment by Jo-Dwyer** [comment]
Excellent! Thanks @desigonz Can you hook me up with access to the GitBook?

**Comment by desigonz** [comment]
Lol I cannot because I don’t have access, but let’s do some sleuthing tomorrow to figure out who does!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jo-Dwyer** [comment]
I wish I could size this at a 4. Trying to figure out how to get access to the old GitBook.

**Comment by Jo-Dwyer** [comment]
@annieszot Would you mind linking to the list of funshop attendees so I can send them a note?

**Comment by annieszot** [comment]
@Jo-Dwyer The Outlook web browser doesn't support sharing the email list. Can you please send me the note then I'll send it to the list/cc you?

**Comment by Jo-Dwyer** [comment]
Sure—thank you @annieszot!

**Comment by Jo-Dwyer** [comment]
IN order to complete this, I need to populate an email list from past funshop attendance lists (that doesn't have email), then send it out.
