### ISSUE TITLE
README for github style guide repo

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3019]
Moving forward, we will:
  * use the GitBook platform for editing and as a public-facing webpage
  * use the GitHub repo to push synced style guide into the nav in joplin

Since this is a one-way sync (GitBook ----> GitHub; GitHub --/--> GitBook), we want to close editing in GitHub.

This could be done by:
- [ ] adding a README in the repo re: sync & info flow
- [x] limiting login access

**Comment by easherma** [comment]
Happy to add a note to the README explaining how it works. The sync is bi-directional; though I don't expect people will edit content on the repo directly, and they would need to be added as a collaborator to the repo anyways.

**Comment by desigonz** [comment]
Jo, assigning you to develop the README that tells people where they should edit and who to ask about permissions.

**Comment by Jo-Dwyer** [comment]
@desi 
Leave briaguya and easherma 

Remove:
ashleecoa
jcbpl
LauraTrujillo
toribr
courtneyjacinic
sknep
sergiogcx
nonprofitable
