### ISSUE TITLE
Replicate formatting between different versions of the same page when drafting

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3021]
### As a content author, I want to easily replicate the format of an original English page so that when I create SP/VI/AR versions the formatting is consistent with less room for user error.

**Is your feature request related to a problem? Please describe.**
When I finish creating a draft page in Joplin and move to create versions in other lanuages, I flip back and forth between versions to be sure I've recreated the steps, options, buttons, etc in the same way. This leaves rooms for user error and can be frustrating. I can use notepad to keep text organized, but this is still another window to jump between.

**Describe the solution you'd like**
I wonder if it's possible to replicate the formatting from the the first page of a draft into subsequent language versions.

**Describe alternatives you've considered**
Could a scratch pad window work?

**Additional context**

**Comment by desigonz** [comment]
duplicate on #3022 (which got consolidated on #2926), closing this one
