### ISSUE TITLE
Replicate features across all language versions of a draft

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3022]
### As a content author I want to replicate features from an English draft into SP/VI/AR version drafts so that the formatting of each language version is consistent, easily updated and user error is limited.

**Is your feature request related to a problem? Please describe.**
When I finish creating a draft in English and begin subsequent drafts in other languages, it can be frustrating to flip back and forth from the EN version to ensure that any steps, options, buttons,etc are recreated consistently across all language versions. Even a seemingly small update to the layout in one version requires flipping between language versions. 

**Describe the solution you'd like**
It could be helpful to automatically replicate any formatting or features into all language versions of a draft so that I know that user error on my part is limited, and that changes can be more simply addressed across all versions.

**Describe alternatives you've considered**
Maybe a scratchpad or embedded box to compare against other versions without switching between windows. 

**Additional context**

**Comment by easherma** [comment]
Does opening the same page in another browser tab help? That way you could more easily compare them side by side.

**Comment by Jo-Dwyer** [comment]
Currently that's what I'm doing. I  am thinking also of a future user in Joplin who may find that clunky and frustrating. Whether or not *this* is the solution, I'm not sure. I wanted to frame a probable issue in a slightly more constructive way. I think it needs more conversation.

**Comment by desigonz** [comment]
Consolidated this on #2926—we've been thinking about these things but it's later in the backlog. Closing this for now but keep adding ideas on #2926!
