### ISSUE TITLE
Introduction to the guide content type

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3024]
**Objective** 
@toribr will introduce our new content strategists to the garden guide. I'll let y'all schedule this one yourselves!

**Participants**
@Jo-Dwyer 
@ablangworthy27 
@toribr 

**Agenda**

------
- [x] Schedule meeting
- [x] Meet
- [ ] Create resulting issues

**Comment by Jo-Dwyer** [comment]
Thanks @toribr for the overview

**Comment by toribr** [comment]
No resulting issues, so closing this.
