### ISSUE TITLE
Standardizing content inventories meeting

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3025]
**Objective** 
Let's meet to discuss feedback from the content team and see how we can incorporate it into content inventories going forward.

**Participants**
@Jo-Dwyer @ablangworthy27 @anukandimalla @matthewbarron 

**Agenda**

------
- [x] Schedule meeting
- [x] Meet
- [x] Create resulting issues

**Comment by anukandimalla** [comment]
[Document to discuss during the meeting ](https://docs.google.com/document/d/1rWgfFp8mtSXeowzhHnyCkxGhDrbzRoAUG3nDvoVLMtY/edit#)

**Comment by anukandimalla** [comment]
[Content Audit standardization Ideation](https://docs.google.com/document/d/1OR7upXbaIwLjuPe46NFbRT1FRjsUHxaTn2agvag7Ywo/edit?usp=sharing) Document and [New Audit Template ](https://docs.google.com/spreadsheets/d/1YR9lxL-RyPquYLCVwuBSjCbf9TIukTd-UTYLpYVX2N4/edit?usp=sharing)

**Comment by anukandimalla** [comment]
2nd Iteration of [Standardized Reference document ](https://docs.google.com/document/d/1OR7upXbaIwLjuPe46NFbRT1FRjsUHxaTn2agvag7Ywo/edit?usp=sharing)
