### ISSUE TITLE
Update Spanish on bulk item pickup page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3027]
https://alpha.austin.gov/es/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup

We're missing Spanish where I've circled. 

**Acceptance criteria**
- [x] The circled part should read "Separe los artículos en tres grupos."

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/fae20641-10fb-4184-89a3-9675e2c80165)

**Comment by ablangworthy27** [comment]
This has been fixed in the latest draft. BUT this draft is not published yet, because I am awaiting review from Content team

**Comment by ablangworthy27** [comment]
This is done and published
