### ISSUE TITLE
Padding on map feature

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#3028]
I have noticed a pretty big space above the map feature on a page that I am working on.  I have tried to remove, but it seems like the space is just built into the feature. Is there a way that it can be made smaller? It is a bit awkward looking. See attached for an example![Screen Shot 2019-09-20 at 12.14.47 PM.png](https://images.zenhubusercontent.com/5d6e8f01caef900001337734/b3bdaab5-4aa2-4235-87c5-f1e84f6e3a9f)

**Comment by desigonz** [comment]
https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/household-waste/hazardous-waste-dropoff

**Comment by chasechenevert** [comment]
Took a quick look at this to see what the margin/padding/border values are and it's looking like there's a total of 180px of spacing between the steps and the map, and we want to get this down to 60px of spacing between the steps and the map. I'm not sure what the best route would be to achieve this (via bottom margin/padding, top and bottom margin/padding, just margin, just padding, idk). 

**Steps**
- Margin: 30px bottom
- Padding: 30px bottom
**Map**
- Margin: 60px top and bottom
- Padding: 60px top and bottom

<img width="1212" alt="Screen Shot 2019-10-01 at 12 38 11 PM" src="https://user-images.githubusercontent.com/7027270/65985925-77312b00-e448-11e9-87b1-8f2d190b1184.png">
<img width="1214" alt="Screen Shot 2019-10-01 at 12 38 23 PM" src="https://user-images.githubusercontent.com/7027270/65985926-77312b00-e448-11e9-944b-194e2428afa9.png">

**Comment by desigonz** [comment]
@briaguya @chasechenevert maybe we should look at this today when we're discussing font style implementation!

**Comment by desigonz** [comment]
Per our meeting today, @chasechenevert should make test pages on staging inserting maps wherever we it's possible and review all of the breakpoints.

**Comment by chasechenevert** [comment]
I'm no longer able to see the map on https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/household-waste/hazardous-waste-dropoff/ and when I've tried to go into Joplin to see the component it doesn't render on Janis.

**Comment by desigonz** [comment]
@chasechenevert Hmmm looks like we have a bug—the map's not rendering! I made #3366 for it and marked it as a blocker for this issue. We can backlog this for now.

**Comment by easherma** [comment]
https://github.com/cityofaustin/janis/commit/668fea91efb4b226baace929cf91752441434bf6

We removed dynamicContent awhile back, tracking down evidence on the exact reasons why. 

In the meantime, https://github.com/cityofaustin/joplin/pull/457 adds it back, but lets do QA and make sure adding it back doesn't break anything

**Comment by toribr** [comment]
Don't use maps anymore since our awesome location page.
