### ISSUE TITLE
Button not surviving "save as draft" in joplin

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3029]
**Describe the bug**
When I create a button on a service page, it will show up perfectly in preview, but once it is saved as draft it no longer appears on the page. 

Seems like "button" styling isn't saving when we click "Save as draft."

**URL**
Joplin

**To Reproduce**

1. Go to Joplin and edit the page "Hire a day laborer"
2. Scroll down to the step option titled "Online." In the rich text editor, highlight "Start" link text.
3. Click on ''Button" to make "Start" a button.
4. Click "preview." Preview opens in a new tab and shows the button (like here: https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxNjAx). 
5. Go back to the Joplin tab and click "Save as draft" to save page.
6. Return to [Joplin page listing page](https://joplin.herokuapp.com/admin/pages/3/) and under "Hire a day laborer," click "view draft."
7. See error: https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxNjAy

**Current behavior**
Button styling hasn't saved. 
![image](https://user-images.githubusercontent.com/5839508/65353106-ec337380-dbb1-11e9-9283-908eba6fd136.png)

**Expected behavior**
I expected the button to stay button-like and functional as a button, just like in the preview.

**Screenshots**
![Screen Shot 2019-09-20 at 1.50.21 PM.png](https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/9dd8519a-55f5-436a-8d7f-2574bc84edab)

Desktop

**Browser**
Chrome

...not currently doing the thing. 

**Additional context**
This is happening for [Thank an Austin police officer](https://alpha.austin.gov/en/health-safety/police-oversight-2/police-feedback-and-records/thank-an-austin-police-officer) which is a live (published) page. No matter how many times we go in Joplin and style as a button, it won't save!
![image](https://user-images.githubusercontent.com/5839508/65353196-26047a00-dbb2-11e9-85e7-2320c7885e4a.png)

Weirdly, the button appears as expected on [File a complaint](https://alpha.austin.gov/en/health-safety/police-oversight-2/police-feedback-and-records/file-a-complaint-about-an-austin-police-officer)

**Comment by easherma** [comment]
I took just a quick look & it seems like the button designation resets when you visit the edit page. So if you highlight and save, it will display correctly. If you save again without re-highlighting the button, it appears to reset.

**Comment by briaguya** [comment]
might be able to mix this in with https://github.com/cityofaustin/techstack/issues/3053

**Comment by easherma** [comment]
Fix is up at https://joplin-pr-3029-persist-button.herokuapp.com/ , with some bonus css magic

**Comment by briaguya** [comment]
@desigonz @easherma this should be in prod now

**Comment by desigonz** [comment]
cc @Jo-Dwyer—the button save should be in production! yay! Closing this one.
