### ISSUE TITLE
Update the content templates to conform with content model 

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#3031]
@toribr updated the content model, but the templates don't match. Let's edit the templates so they match the content model and what authors need to enter in Joplin.

**Comment by desigonz** [comment]
- [ ] Make sure templates explain how to title info vs. service pages


Made a little table with Sarah's brilliant explanation from today
| Content type     | What it does                    | Title convention      |
|------------------|---------------------------------|-----------------------|
| Service page     | Tells you what you need to do   | Action (verb)         |
| Information page | Tells you what you need to know | Subject matter (noun) |

**Comment by ablangworthy27** [comment]
Okie doke, I did this. It is done. I cross-referenced Joplin and the content model spreadsheet. I even updated the topic/topic collection templates to match Joplin even though they don't actually have a tab in the spreadsheet.
