### ISSUE TITLE
Upload a document while editing a page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3032]
### As a content editor, I want to be able to upload and manage documents while editing a page, so that I don't have to toggle back and forth within Joplin to publish my content.

**Is your feature request related to a problem? Please describe.**
We'll soon have document management in Joplin, but to upload a document while editing a page, you have to exit the page and go to the "Documents' section.

**Describe the solution you'd like**
The big issue with wagtail is that images and documents should be able to be added within page templates, and not require first adding them to the image/document library. Let's make it so you can upload a document while editing a page.

**Describe alternatives you've considered**

**Additional context**

**Comment by briaguya** [comment]
@easherma is this something the generic chooser can help with?

**Comment by easherma** [comment]
We exposed this by un-hiding tabs on choosers yay!

**Comment by desigonz** [comment]
It looks like this: ![image](https://user-images.githubusercontent.com/5839508/66346968-ec08d700-e918-11e9-907f-ec2eb52499f2.png)
