### ISSUE TITLE
Janis designs for navigating to guides from pages and topics

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3033]
### As a resident, I want to access a guide from relevant pages (including topics and individual pages) so that I can find all the information I need about a complex City process.

**Is your feature request related to a problem? Please describe.**
We have guides! You can currently navigate to a guide the same way you would find any other service or info page.

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/584a0fbf-696c-4e96-9d12-b608b7398248)

But from an individual page that's part of a guide, there is no indication that it belongs to a guide. And we might also want to distinguish guides from individual pages at the topic level.

**Describe the solution you'd like**
Designs for navigating to guides from topic pages and from individual service or info pages.

**Describe alternatives you've considered**

**Additional context**

**Comment by desigonz** [comment]
@chasechenevert please add an estimate!

**Comment by chasechenevert** [comment]
I need to show this for all page types that can be pulled into a guide: 
- [ ] Service page
- [ ] Information

I need to iterate on: 
- [ ] How the guide tile appears visually at the topic level. 

We've talked about various ways that we can distinguish the tile: icon, fill or border colors, placing the guide tile above others, under a small heading....

**Comment by chasechenevert** [comment]
Mocks for dev: https://xd.adobe.com/spec/e2cdc032-9eba-4140-5274-fc14f7254296-94fc/

**Comment by desigonz** [comment]
- [ ] @desigonz and @chasechenevert to work on a new issue with acceptance criteria. 
- [ ] Content team needs to approve microcopy.

**Comment by desigonz** [comment]
Made issues #3244 and #3245 to cover this. @chasechenevert please take a look at them and make sure they look good; also asked @ablangworthy27 to review the "This page is a part of" microcopy so she might have something for you to update in the mocks. For now, closing this issue!
