### ISSUE TITLE
Draft APH pages in Joplin

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3043]
We have ~20 pages approved to publish. Let's draft them in Joplin to prep for publishing!

**Comment by Jo-Dwyer** [comment]
Ready for review:
- [ ] https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxODQw
- [ ] https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxODUx
- [ ] https://alpha.austin.gov/en/preview/topic/UGFnZVJldmlzaW9uTm9kZToxNjkz
- [ ] https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxODU0
- [ ] https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxODY2
- [ ] https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxODY5
- [ ] https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxODcz
- [ ] https://alpha.austin.gov/en/preview/topic/UGFnZVJldmlzaW9uTm9kZToxODMw
- [ ] https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxODc4

**Comment by desigonz** [comment]
Thanks for meeting today! As we discuss, I'll work on getting multiple contacts on a page (#3079) into the dev pipeline.

[Chronic disease prevention](https://alpha.austin.gov/en/preview/topic/UGFnZVJldmlzaW9uTm9kZToxNjkz) and [injury prevention](https://alpha.austin.gov/en/preview/topic/UGFnZVJldmlzaW9uTm9kZToxODMw) are topic pages so the preview isn't fully working right now. @Jo-Dwyer I'm thinking we wouldn't send those to review to APH?

I'm noticing that the headings on [help with childcare expenses](https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxODUx) are appearing bolder than on other pages—I think you have both `bold` and `H2` selected. Let's remove the bold!
![image](https://user-images.githubusercontent.com/5839508/66327753-f8793980-e8f0-11e9-8ae1-fa19ae8df46c.png)

Also, not sure this should be a heading? 
![image](https://user-images.githubusercontent.com/5839508/66327907-3b3b1180-e8f1-11e9-8801-b88016bfbe94.png)

**Comment by Jo-Dwyer** [comment]
Agreed: topic/ topic collection pages won't be sent to APH until they are functional previews.
Fixed: 
- [x] Header on [Basic services...](https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxODgy)
- [x] Bold on [Help with childcare...] (https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxODgx)
