### ISSUE TITLE
Fit APH pages into the information architecture

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3044]
We have ~20 APH pages ready to publish. We need to fit them into the IA!

- [x] connect with @srigdon to develop a workflow for fitting things into the IA

**Comment by Jo-Dwyer** [comment]
## Topic pages to create
### These are suggested topic pages to create, more or less.
- [ ] Healthcare and prevention
- [ ] Housing and utilities

**Comment by desigonz** [comment]
Per sprint planning, @srigdon and @Jo-Dwyer to meet on 10/7 to talk IA and make some decisions.
