### ISSUE TITLE
Come up with a plan to periodically audit IT costs for ODD

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3046]
I think we don't tend to prioritize cost concerns as a team, which makes sense, but it might also make sense to periodically dedicate a little bit of sprint time to checking on that, maybe every quarter or so.

This could be as simple evaluating what is running and cleaning up stuff that isn't needed or relevant anymore. This would help us stay organized in addition to keeping costs predictable and being able to explain what are costs are for if/when we are asked.

**Comment by oliver2g** [comment]
@easherma Shortly after we talked about this, I had a meeting with CTM Finance in which they asked me to vet our tech tools through CTM IT. During this process, I'll reach out to yall on a case by case basis as necessary. Closing this issue and opening a corresponding one in the odd-ops repo. https://github.com/cityofaustin/odd-ops/issues/120
