### ISSUE TITLE
Move prod data to staging automagically

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3050]
Right now it's not auto and it's not magic, let's make it both.

**Comment by easherma** [comment]
This could vary widely depending on our acceptance criteria. I remember some discussion around concerns of nuking staging data if someone is not aware and was working on a draft. We'll also want to decide what sort of 'magic' we want: will it be time based (on a regular schedule) or condition based (making this up, but say when we merge a PR called ``` Master ----> Prod ``` it runs then.

**Comment by Niicck** [comment]
Also need to sync prod media (images only, I think) into the staging media folder
