### ISSUE TITLE
"Pick up free paint" hyperlink

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3052]
**Describe the bug**
Hyperlink at the bottom of "Pick up free paint" doesn't go anywhere, let's fix it!

![image](https://user-images.githubusercontent.com/5839508/65688626-1319fb80-e031-11e9-8134-0de0093901ab.png)

**URL**
https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/recycling-reuse/pickup-free-paint/

**Comment by briaguya** [comment]
@desigonz looked at this on joplin prod and it seems like the content is right, but for some reason isn't working. I'm on it

**Comment by briaguya** [comment]
looks like the link is coming up as
```
<a id="11" linktype="page">drop off at the Recycle and ReUse Center</a>
```

my guess is that this somehow came about with the move to the new picker, but that's a hunch at best.

I've updated the link manually for now, I'll test it once Janis redeploys

**Comment by briaguya** [comment]
fixed the instance in production, created a new issue to address the underlying bug: https://github.com/cityofaustin/techstack/issues/3053

**Comment by desigonz** [comment]
@briaguya Since this is working in production and you made the new issue, I'm going to close this.
