### ISSUE TITLE
Merge language select + content tab

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3054]
Edit page header redesign specs required us to merge the functions of the language select with the first content tab

Research options
Try a couple approaches
Solicit feedback

**Comment by easherma** [comment]
Live in https://joplin-pr-2827-edit-page-heade.herokuapp.com/

**Comment by briaguya** [comment]
@desigonz are the acceptance criteria for this a part of #2827?

**Comment by desigonz** [comment]
@briaguya yep
