### ISSUE TITLE
New topic page doesn't load preview

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3056]
**Describe the bug**
I created a new topic page as a draft in prod. Clicked preview; doesn't load. Clicked save as draft and preview; doesn't load.

https://alpha.austin.gov/en/preview/topic/UGFnZVJldmlzaW9uTm9kZToxNjQ4

**To Reproduce**

1. Go to joplin prod
2. Click on 'Chronic disease prevention'
3. Select 'preview'
4. See vast nothingness.

**Current behavior**
Page loads as a white blank page.

**Expected behavior**
A preview of the topic page I created in prod

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by desigonz** [comment]
Made a gif to illustrate what's happening:
![image](https://user-images.githubusercontent.com/5839508/65800025-113c5f00-e13b-11e9-803f-078481328861.png)

**Comment by desigonz** [comment]
oops now it works
![topic-preview](https://user-images.githubusercontent.com/5839508/65800056-2618f280-e13b-11e9-9a92-a63709bb22d5.gif)

**Comment by briaguya** [comment]
looks like an error with building topic pages in preview, maybe a cleandata thing

**Comment by briaguya** [comment]
@desigonz this is up [here](https://deploy-preview-535--janis.netlify.com/en/preview/topic/UGFnZVJldmlzaW9uTm9kZToxNjQ4)

To quote [my PR](https://github.com/cityofaustin/janis/pull/535) -
## What this does
* Make it so topic page previews load, and title/description can be previewed

## What this doesn't do
* Make it so we don't use dummy data to populate page links in the preview
