### ISSUE TITLE
Create mapped locations for St Johns and Far South Austin Health Clinics

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3058]
## In order to guide users through choosing a location for picking up records, I want to include maps of both locations: St Johns and Far South Austin Clinics.  

* One option might be to create two new map options and embed them
* We could also embed a map with multiple locations on it.

**Comment by desigonz** [comment]
Eventually the Places content type will allow us to do this, so I'm marking this as "content debt."  For now I think you have a few options:
- Include two contacts (on the right side of the page), one for each clinic
- Include two maps with our existing map component. The map component is currently less than ideal, though, and takes up a lot of real estate on the page. It might suffice just to have the two contacts.

**Comment by Jo-Dwyer** [comment]
@desigonz I'm closing this!
