### ISSUE TITLE
Guide anchor links needs slowing down—better solution

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3065]
In #2962, @briaguya implemented a CSS solution that creates a scrolling animation that takes user from the guide content they were on to the section they selected. It's okay enough for MVP, but the ease in is oddly slow, and we can't fix that with the existing solution.

Let's look into implementing a new library to achieve the ideal effect.

**Acceptance criteria**
- [ ] Ease in is faster—work with @toribr to confirm the ideal animation speed

**Comment by briaguya** [comment]
`scroll-behavior: smooth;` is all we have in there rn

**Comment by robbobfrh84** [comment]
Fixed with this PR: https://github.com/cityofaustin/janis/pull/560

**Comment by Niicck** [comment]
Assigning to Chase to QA. I remember he had an idea of the speed of the scrolling effect, so let's make sure this solution works for him.

**Comment by desigonz** [comment]
Thanks @Niicck!

@robbobfrh84, can you add the links where Chase can test? (I think you posted on Slack but let's keep them on the issue so it's all in one place.) And in general, when something is ready to QA, you can assign the issue to me and I'll assign to whoever needs it.

**Comment by robbobfrh84** [comment]
This fix is deployed and can be tested here: https://deploy-preview-560--janis.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-vendor-permit-guide/#Learn-and-prepare-5

**Comment by desigonz** [comment]
It looks really beautiful on my side of things! Let's wait on design for the final word before pushing to staging.

**Comment by chasechenevert** [comment]
This looks great to me! Good work.

**Comment by desigonz** [comment]
Excellent! This can go to staging for you to verify before it goes to prod; no need to further QA if it all looks good to you in staging.
