### ISSUE TITLE
New feature: Assign Info and Service pages to Topic Pages from within the Topic Page editor

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3067]
*Make sure to add the label "Content debt." If available, add the appropriate "Content type" or "Feature" label.*

https://joplin.herokuapp.com/admin/pages/203/edit/

**Have you documented this via the author notes field in Joplin?**
- [x] Yes!
- [ ] No, but I'll do it now

**Describe the content debt.**
Might be cool to be able to assign relevant service and info pages to the topic page in same way that I select the topic collection and department pages.

**What is the long-term, ideal solution for this content debt?**
Maybe having a similar tool as what we use for dept and topic collection page selection?

**Is this related to a feature request issue? (Add the issue number below and add the issue as a dependency.)**

**What approvals will be needed to publish this content change?**

**Comment by desigonz** [comment]
Yes!! That will be covered in #2223
