### ISSUE TITLE
Phone number not appearing in preview

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3069]
**Describe the bug**
I made a new contact that includes a phone number and added it to a draft page, then previewed it. The contact shows up but not the phone number. 

Not sure if this is an issue with preview (we know there are a lot of preview issues) or with the phone number data model (should I have entered "default" or something for the phone number?)

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/ba0c8c60-2707-47fd-a5d0-ed8d26b2f387)

**URL**
Preview: https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxNzEw
WIC benefits edit page: https://joplin.herokuapp.com/admin/pages/199/edit/
Contact edit page: https://joplin.herokuapp.com/admin/snippets/base/contact/11/

**To Reproduce**

**Current behavior**

**Expected behavior**

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by briaguya** [comment]
probably some weird preview logic with parsing phones, not sure, worth digging around and seeing if there's something scary causing it

**Comment by desigonz** [comment]
Interesting—it's working in staging for me 
![image](https://user-images.githubusercontent.com/5839508/65920831-db4ee300-e3a5-11e9-9cb6-77564c104d12.png)
Janis preview link: https://janis.austintexas.io/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxNjg2
Joplin staging link: http://joplin-staging.herokuapp.com/admin/pages/198/edit/

**Comment by desigonz** [comment]
And actually now the contact name isn't appearing 🤦 Not sure if it's the same thing, I can submit a new bug issue if we need to.

![image](https://user-images.githubusercontent.com/5839508/65920896-0f2a0880-e3a6-11e9-86be-fd888bdc2ed1.png)

contact snippet (Joplin): http://joplin-staging.herokuapp.com/admin/snippets/base/contact/11/

**Comment by briaguya** [comment]
@desigonz the contact name isn't appearing here either https://alpha.austin.gov/en/health-safety/police-oversight-2/police-feedback-and-records/file-a-complaint-about-an-austin-police-officer

There's no contact name in XD either https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/ce9e7492-b75b-472c-9dab-98d7bd1843ba/Template-Service-desktop

**Comment by desigonz** [comment]
Woahhhh you're so right. I'll double check with design and contact on that one.
