### ISSUE TITLE
Make language selection also navigate back to content tab

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3070]
Dropdowns do not typically also navigate to other parts of a page, so this is another piece of functionality needed to implement the new edit page header

Hoping to leverage/replicate the functionality that Wagtail already uses to handle tabs

**Acceptance criteria**
- [x] Interaction with dropdown from a non-content tab is as follows:
  1. Go to a non-content tab (ex. Notes)
  2. Click on drop-down arrow
  3. Select a language (ex. Spanish).
  4. **What I expect to happen:** Spanish content appears on page and is highlighted in the tab title. (What's currently happening is that Spanish will appear in the tab title but Notes persists on page.)

**Comment by easherma** [comment]
Can be QA'ed as part of https://joplin-pr-2827-edit-page-heade.herokuapp.com/

**Comment by briaguya** [comment]
@desigonz are the acceptance criteria for this a part of #2827?

**Comment by desigonz** [comment]
@briaguya yep!
