### ISSUE TITLE
Desi broke Janis staging builds 😬

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3071]
**Describe the bug**
I think I broke Janis staging builds again on a Friday afternoon 😬 I published the "Chronic disease prevention" topic page without giving a topic collection. Joplin staging still worked and I went back in and added a topic collection. But the Janis builds didn't work for these pages:
![image](https://user-images.githubusercontent.com/5839508/65805740-5c12a280-e14c-11e9-84f1-9116f177f444.png)

And when I view live, the page 404s:
![image](https://user-images.githubusercontent.com/5839508/65805757-751b5380-e14c-11e9-8a22-7113ec8ce3d5.png)

Then I made a new [info page](http://joplin-staging.herokuapp.com/admin/pages/196/edit/) and published it. It also wouldn't build.

![image](https://user-images.githubusercontent.com/5839508/65805805-af84f080-e14c-11e9-9c8f-93bfeb00c4ac.png)

**URL**

**To Reproduce**

**Current behavior**

**Expected behavior**

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by briaguya** [comment]
should be fixed by https://github.com/cityofaustin/janis/pull/528

**Comment by briaguya** [comment]
quick rundown on what broke here:
If you add a topic to a topic collection, the topic collection page tries to build a card for it (with the topic title and links to pages under said topic)
We didn't have logic to handle a topic without any pages under it, so it broke.

**Comment by briaguya** [comment]
recklessly merged this all the way into prod, closing it
