### ISSUE TITLE
Improve GlobalNav leading

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3074]
## Problem statement
In Spanish, themes with long titles are breaking to 3 lines at responsive breakpoints. This stacking causes the theme bar stretch too much vertically, and looks awkward next to themes with fewer words in the title.

## Solution
- [x] Line-spacing from 2.8rem to 2rem
- [x] 768 < 1080 breakpoint: font-size reduced to 1.4rem. This will at least reduce the number of line breaks.
- [x] align theme text to the top, so that shorter theme titles don't appear vertically centered 

### Screenshots
**Before**
<img width="769" alt="Screen Shot 2019-09-30 at 11 58 55 AM" src="https://user-images.githubusercontent.com/7027270/65899809-28b55b00-e37a-11e9-8920-1f4943d77eb1.png">

**After**
Showing the design at 768px browser width (this is the mid breakpoint, <768 goes to the mobile version), and line-spacing: 2rem. 
<img width="769" alt="Screen Shot 2019-09-30 at 11 59 04 AM" src="https://user-images.githubusercontent.com/7027270/65899818-2d7a0f00-e37a-11e9-86d3-87e3c41813d7.png">

**Comment by briaguya** [comment]
the styles here might be kinda fragile, so I'm giving it a 3

**Comment by briaguya** [comment]
@desigonz this is up here: https://deploy-preview-534--janis.netlify.com/

adding you and moving to review

**Comment by desigonz** [comment]
Assigning @chasechenevert to review. Can you review against your full acceptance criteria? One thing I noticed: Acceptance criteria mentions top alignment but then the mock doesn't show it (my bad for not catching that earlier).
