### ISSUE TITLE
Neighborhood centers irregular hours

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3075]
*Make sure to add the label "Content debt." If available, add the appropriate "Content type" or "Feature" label.*

**What is the URL?**
https://joplin.herokuapp.com/admin/snippets/base/contact/16/
https://joplin.herokuapp.com/admin/snippets/base/contact/15/
https://joplin.herokuapp.com/admin/snippets/base/contact/18/
https://joplin.herokuapp.com/admin/snippets/base/contact/17/

**Have you documented this via the author notes field in Joplin?**
- [ ] Yes!
- [ ] No, but I'll do it now
- [x] Actually I can't right now because these are snippets, which don't have the author field!

**Describe the content debt.**
Neighborhood centers often have irregular hours, like closed for lunch. Additionally, for some of them, you have to make an appointment to access services during open hours. Our contacts snippet doesn't currently allow us to specify this, but the new Place content type will.

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/bae63f83-2085-47f7-b071-6889eba9459f)

**What is the long-term, ideal solution for this content debt?**

**Is this related to a feature request issue? (Add the issue number below and add the issue as a dependency.)**

**What approvals will be needed to publish this content change?**

**Comment by Jo-Dwyer** [comment]
Fixed by #3763
