### ISSUE TITLE
Feedback Form non-responsive in IE11

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#308]
From the logs, it looks like we need to add a polyfill for the browser Intl API. This seems to be choking the Javascript so features like navigation and feedback form don't work as a result.

<img width="761" alt="screen shot 2018-04-21 at 1 41 51 pm" src="https://user-images.githubusercontent.com/5697474/39087842-b2e80dfc-456c-11e8-9da0-f1b60ed4243f.png">

Aha! Link: https://desi1.aha.io/features/RT-316

**Comment by mateoclarke** [comment]
Very confusing. I installed the npm package `intl` which is a polyfill for browsers that don't have the Intl standard API. Now getting a different error in IE 11: `Unable to get property 'postMessage' of undefined or null reference`.

Navigation menu works fine, so does Recollect. But Feedback Form doesn't.

<img width="716" alt="screen shot 2018-04-21 at 3 53 41 pm" src="https://user-images.githubusercontent.com/5697474/39088707-6af55594-457c-11e8-8bd8-a23aca52f267.png">

**Comment by easherma** [comment]
We did it
