### ISSUE TITLE
Janis/Joplin - Improve previews

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3084]
Thoughts:
* There will be quite a bit of preview refactoring work to do when we move to Joplin 3.
* Getting related info from a page revision involves quite a bit of Joplin API work.
* If we build guide previews we'll probably get a better sense of how we're trying to do all this stuff.

**Comment by desigonz** [comment]
Brian explained a lot of things to me on Slack and I'm adding here for posterity:

> I think it's a "make sure our dummy data looks decent" in J2 and then figure out relationships in previews for J3
> any other bugs can be addressed individually
> For previews:
> - we need to make queries to the DB based on a page revision id
> - then we need to ask the API for specific stuff based on page type
> - then we need to take that in Janis and build a page

> when getting a full page from Joplin we have the relationships in there, and then we do a lot of work at build time in Janis to make sure those relationships work correctly (contextual nav etc.)
> but with previews we're generally missing a lot of stuff
> and need to manually fill it in
> one of the big things is shareable preview links
> those rely on us using a revision id in Joplin
> so basically it's "given this revision id, which doesn't tell us what kind of page it is, generate a preview for the page"
> skipping over the logic we have to put pages at all the right urls
> skipping over a lot of our Janis build time logic
> so really the less work we do in Janis for builds the easier it'll be to make previews
> but getting Joplin to a point where Janis doesn't need to do so much work is kinda a big chunk of J3
> (me: Is this at all related to incremental builds?. brian: yup)
> incremental builds with the amount of logic we have at build time in Janis right now would be really hard
> we'll need to refactor to support them

**Comment by easherma** [comment]
+1 to the above
![](https://giphy.com/gifs/WHByqMWMonVMQ/html5)

**Comment by desigonz** [comment]
@Niicck @robbobfrh84 @briaguya We decided to backlog this for now, and wait til incremental builds, correct?
