### ISSUE TITLE
Constraining visibility/access to content by author's department

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#3085]
### As an author within a particular department, I want to only see content that is relevant to me, so that I can more easily access my content.

- [ ] As a city author, I would only be able to view/edit pages and content (documents/images) that belong to my department.
- [ ] In the case of guides, I need to be able to access pages from other departments via the page picker 

Assumptions:
 - [ ] Each user will have a profile, which includes the department they work in, their name,
and their email
- [ ] When a user logs in, they will see only content on "pages" that has been created by themselves or those within their department. Similarly they will only see documents and images uploaded by themselves or someone from their department.
- Adding pages to a guide from another department is an exception: when users go to add pages by default they will see only pages created by themselves or others in their department. If the user selects the checkbox, however, the page should refresh to show all eligible pages across Alpha.
![#2912](https://user-images.githubusercontent.com/3790067/66419412-b7a12380-e9c9-11e9-81ad-7efc4d1317ee.png)

**Comment by desigonz** [comment]
Per sprint planning, we'll be discussing user roles during pin-up this sprint. We'll also talk to the dev team about what's possible 🚀

**Comment by desigonz** [comment]
Consolidated these into #3378!
