### ISSUE TITLE
Style fixes for edit page header

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3087]
Follow-up to #2827 where we implemented the redesigned edit page header. Let's fix these style issues:

- [x] Center language name within first tab minus the divider/arrow part (I guess it's currently centering across the whole tab; I would expect it to center between the left most edge of the tab and the divider)
- [x] remove radius on first tab {border-radius: 0px 0px 0px 0px;}
- [x] make buttons align/not exceed bar 
![Screen Shot 2019-10-01 at 1 01 18 PM](https://user-images.githubusercontent.com/3790067/65987712-ff64ff80-e44b-11e9-9f9c-800c294cf6a6.png)
- [ ] make divider bar align with hover 
![Screen Shot 2019-10-01 at 1 07 10 PM](https://user-images.githubusercontent.com/3790067/65987913-6f738580-e44c-11e9-9508-2c49fa11405a.png)

**Comment by briaguya** [comment]
@desigonz this is up here: http://joplin-pr-3087-stylish-header.herokuapp.com
it includes:
cityofaustin/techstack#2827
cityofaustin/techstack#3078
cityofaustin/techstack#2930

**Comment by desigonz** [comment]
Hey @briaguya, looks great. The one thing I noticed is that now the arrow section of the language tab doesn't have the hover highlight color. I'm totally cool with that but want to run it by @toribr first.

Tori, let's take a look at it together at the office today.

Here's a GIF comparing the two PR branches:
![3087-button](https://user-images.githubusercontent.com/5839508/66049901-de56ea00-e4f1-11e9-99ea-0c3669a3b8b4.gif)

**Comment by toribr** [comment]
@briaguya I'd rather have a misaligned hover than no hover at all.
