### ISSUE TITLE
"Meet our director" change on department pages

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3090]
**Acceptance criteria**
- [ ] English: Change hardcoded "Meet our director(s)" to "Leadership"
- [ ] Spanish: Change hardcoded "Conozca nuestra directora" to "Liderazgo"

![image](https://user-images.githubusercontent.com/5839508/66064542-351ced80-e50b-11e9-94d7-5bdc95d1e5af.png)

**Comment by briaguya** [comment]
@desigonz this is here: https://deploy-preview-543--janis.netlify.com/en/police-oversight/

**Comment by desigonz** [comment]
Beautiful! QA complete.
