### ISSUE TITLE
Navigation header should match navigation

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#3091]
**Acceptance criteria**
- [ ] [Main content listing page](http://joplin-staging.herokuapp.com/admin/pages/3/) is titled "Pages" (instead of content)

![Screen Shot 2019-10-02 at 12 54 53 PM](https://user-images.githubusercontent.com/3790067/66078374-86d37100-e527-11e9-8de0-06a4fc97b14b.png)
These two titles ("pages" & "content") have gotten out of sync, which is somewhat confusing. Please make "content" say "Pages" so they match.

**Comment by desigonz** [comment]
This will be covered by #2581, yay!
