### ISSUE TITLE
Janis build breaks when publishing a guide with a missing page

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3092]
**Describe the bug**
Guides can be published with unselected pages, when this happens it breaks the janis build.

**To Reproduce**

1. Go to joplin
2. Make a guide page
3. Add a section without a page
4. Hit publish

**Current behavior**
Page publishes, Jans build breaks.

**Expected behavior**
- [x] Page under section is required to publish and save page
- [ ] Test what happens when:
  1. you add a page to a guide
  2. publish the guide
  3. delete that page
  4. Should look like (@robbobfrh84 to add screenshot) and Janis still builds

**Screenshots**
<img width="1129" alt="Screen Shot 2019-10-02 at 8 18 07 PM" src="https://user-images.githubusercontent.com/6384156/66092555-05450880-e552-11e9-89bc-f0eb6b0c54fa.png">

<img width="1047" alt="Screen Shot 2019-10-02 at 8 14 07 PM" src="https://user-images.githubusercontent.com/6384156/66092563-0bd38000-e552-11e9-98c4-463e2a989c68.png">

**Additional context**

**Comment by desigonz** [comment]
@briaguya Can we make adding the first page under a section required (can't save the page without it, with of course error messaging to indicate that)? Would that solve the problem, or no?
![image](https://user-images.githubusercontent.com/5839508/66126650-95fe0180-e5af-11e9-8032-001c3081ee71.png)


Similar to what happens when you try to add an official document without filling out the required fields.
![image](https://user-images.githubusercontent.com/5839508/66126645-90a0b700-e5af-11e9-83a9-eb8295ff2335.png)

**Comment by easherma** [comment]
Gave this a tentative estimate, depending on the underlying cause and acceptance criteria for a fix.

**Comment by robbobfrh84** [comment]
Here's the image of how it should look *without* a page in a section...
![Screen Shot 2019-10-14 at 2.44.40 PM.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/c3931d08-00c7-4790-a4d7-eeb83018b525)

And.... Here's how it currently looks when you attempt to publish *without* adding a page...

![Screen Shot 2019-10-14 at 2.44.07 PM.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/32c2360f-bff2-4a0f-8f54-4d138798a8d1)

**Comment by robbobfrh84** [comment]
This has now been review, and merged into staging for QA @desigonz . 
- Also, here's a direct example: https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/test-a-guide

**Comment by desigonz** [comment]
I'm not 100% sure about the acceptance criteria here, let's get @briaguya to test.

What I did:
1. added pages to the community garden guide in staging ([Joplin](http://joplin-staging.herokuapp.com/admin/pages/130/edit/)) ([Janis](https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/community-garden-permitting-guide/#And-another-1))
2. unpublished one of those pages: Thank a police officer ([Joplin](https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/community-garden-permitting-guide/#And-another-1))
It still appears in the guide—is that what is expected? 

But also it's still appearing here: https://janis.austintexas.io/health-safety/police-oversight-2/police-feedback-and-records/thank-an-austin-police-officer/

**Comment by briaguya** [comment]
@desigonz that's odd with the unpublish thing, it's gone from the topic page https://janis.austintexas.io/en/health-safety/police-oversight-2/police-feedback-and-records

try making a new page and adding it to a guide, then deleting the page you just made. We'll worry about unpublish later as that's not what this issue is addressing.

**Comment by desigonz** [comment]
Thanks @briaguya! I tested according to your steps. 

It still builds! Yay! 

I'm noticing this visual bug happens—basically a blank space for the title. I'll submit a bug issue for this and put it (way back) in the backlog.

![image](https://user-images.githubusercontent.com/5839508/67053307-95647f80-f106-11e9-85c6-9dcd34b77835.png)

**Comment by desigonz** [comment]
@robbobfrh84 So the moral of the story is that QA is complete and this can go to staging and prod.

**Comment by robbobfrh84** [comment]
@desigonz Sounds great!

**Comment by desigonz** [comment]
This is now in production so I'm closing it!
