### ISSUE TITLE
Janis - Guide page TOC breaks when too tall

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3094]
## NOTES FOR QA
PR: https://github.com/cityofaustin/janis/pull/609
App link: https://janis-3094-guide-toc-2.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-vendor-permit-guide/#Get-inspected

### In order to work correctly (noted as sometimes/never/always):
 * when a user scrolls:
   * the current section appears "selected" in the TOC (Brian's testing: **sometimes** - see known issue 2)
   * the current section is on screen in the TOC (Brian's testing: **sometimes** - see known issue 3)
 * when loading the page with an anchor link:
   * the linked section is scrolled to the top (Brian's testing: **always**)
   * the corresponding TOC section is selected and visible (Brian's testing: **sometimes** - see known issue 1)
 * when clicking a link in the TOC
   * the url is updated to reflect the link anchor (Brian's testing: **always**)
   * the clicked section is scrolled to the top (Brian's testing: **sometimes** - see known issue 2)
   * the corresponding TOC section is selected and visible (Brian's testing: **always**)

### Known Issues 
1. if you enter a new anchor link in the url when the page is already loaded, it will scroll to the new section but not update the scrolling on the TOC
2. if we have dynamic content (like recollect that changes height after loading) we don't correctly recalculate the size of the sections, so everything will be off by a little bit (existing bug I'm pretty sure)
3. scrolling down after clicking a section lower down allows the selected TOC item to be offscreen again
 
### Ideally I'd like to get to the point where we feel this is:
* An improvement from what we have now (TOC never scrolls with content)
* A decent jumping off point for any smaller issues that stem from it
  * See known issues above

## original issue stuff

**Describe the bug**
On a guide page, if we have too many sections for the TOC to fit on the screen at one time, we lose track of the highlighted sections.

**Acceptance criteria**
The last TOC menu item that I can see in my browser window is "Prepare your mobile food vendor permit application":
- [ ] as I scroll further down within the body section and roll up to the next TOC menu item, "Apply for mobile food vendor permit in person", the TOC would move up just enough to show the corresponding TOC section
- [ ] this behavior would happen the same way in reverse if the user is at the bottom of a page and scrolling upwards with a TOC that's longer than the viewport can fit

**URL**
https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-vendor-permit-guide

**To Reproduce**
1. Click on link ^
2. Scroll down.

**Current behavior**
selected section goes off screen

**Expected behavior**
not that. @desigonz need details.

**Screenshots**
![Oct-03-2019 08-48-44](https://user-images.githubusercontent.com/6384156/66133053-a61bde00-e5bb-11e9-9bbb-3e829140a708.gif)

**Device**
Desktop

**Browser**
Chrome

**Comment by desigonz** [comment]
Assigned @chasechenevert to flesh out expected behavior/acceptance criteria

**Comment by chasechenevert** [comment]
Are we able to have the lefthand menu scroll with the body content? @toribr does that sound right to you?

**Comment by desigonz** [comment]
I'm able to scroll TOC with my trackpad, but wondering what the experience is like for folks without a trackpad, or using just a keyboard to navigate.

We also haven't done accessibility testing on the guide—making an issue for that!

**Comment by desigonz** [comment]
Here's a video of scrolling with the trackpad
![3094-left-scroll](https://user-images.githubusercontent.com/5839508/66661586-e3f8b200-ec0c-11e9-8eb2-01d9c9128e12.gif)

**Comment by toribr** [comment]
@chasechenevert Yes. 

How I envisioned it was that the left rail and right content section should be responsive to one another. So if i were to scroll down in the content, the left rail would also move to show me where I am.

**Comment by briaguya** [comment]
@toribr made a terrible imovie mockup gif, something like this?

![Oct-11-2019 12-44-29](https://user-images.githubusercontent.com/6384156/66672873-eebf4100-ec24-11e9-8221-4f236ccae0be.gif)

**Comment by toribr** [comment]
I kind of want to see more to confirm, but yes? Namely if i scroll down all the way to the bottom, the left hand nav "shows" where I am... both sides track to one another.

**Comment by briaguya** [comment]
@toribr I think i was trying to demonstrate the TOC heading locking in with the guide heading, and then scrolling up together and both sticking at the top. I'll see if I can find an example of a page with side nav that does something similar.

**Comment by toribr** [comment]
@briaguya I'm looking, too, but it looks like it'd be using a scroll distance detection and then mapping that to active class in the left nav.

**Comment by briaguya** [comment]
@desigonz left a ton of notes in this for QA so we can figure out a way to start pushing it forward.

**Comment by desigonz** [comment]
Hi @briaguya and @Niicck! Okay I've taken a deep dive into Brian's QA notes above. Here's what I'm thinking:
- Known issues 1 and 2 are fine for now—we should create new issues and plan to tackle those when they become a priority. (At the moment I actually don't see too much of a use case for known issue 1, but let me know if you disagree; and for known issue 2, we're not currently planning to add pages with apps in them into a guide, so we can cross that bridge when we get there.)
- @briaguya, wondering if you can clarify known issue 3: when you say "scrolling down after clicking a section lower..." do you mean scrolling down in the TOC, or on the section content? Maybe share a screen grab to illustrate?
- The one thing that's not an improvement (and dare I say the opposite of an improvement) is that now, anytime you scroll through content, the current section jumps to the top of the TOC, which is jarring. Compare the two GIFs below. Based on the acceptance criteria, I would expect the highlighted section in the TOC to continue functioning like it is in staging, but once a user hits the section at the bottom of the on-screen TOC, the TOC nudges up just enough to show the corresponding TOC section.

Happy to talk through this if that's easier!!

### PR 
![3094-scroll](https://user-images.githubusercontent.com/5839508/68966496-dd2d0400-07a3-11ea-958a-aefac7692793.gif)

### Staging
![staging-scroll](https://user-images.githubusercontent.com/5839508/68966609-24b39000-07a4-11ea-8acb-2388d2ab2e37.gif)

**Comment by desigonz** [comment]
This looks 😍 QA passed, this is good to go to staging.

Let's create a new issue for the thing that's happening when your on an anchor, you reload the page, and then expect to see that section highlighted in the nav but it's not.
