### ISSUE TITLE
Janis - Topic pages with lots of children look terrible on desktop

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3095]
**Describe the bug**
They're tiles and go off the screen for larger screen sizes (breakpoints 1080px and up).

**Acceptance criteria**
- [ ] Matches [mocks](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/19c5f0cc-e878-4ff1-946a-7a8a56b5b637/Template-Topic-desktop)
- [ ] Max 3 tiles in a row, which on mocks occupy the first 10 columns (left to right) or 964px

**URL**
https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention

**Screenshots**
<img width="1621" alt="Screen Shot 2019-10-03 at 8 58 51 AM" src="https://user-images.githubusercontent.com/6384156/66133395-322e0580-e5bc-11e9-9d78-e6785a7e273d.png">

**Comment by desigonz** [comment]
We'll need this pretty soon—assigning @chasechenevert to clarify design for topic page tile behavior.

**Comment by chasechenevert** [comment]
This should appear as it does in the mocks for Topics, I'm sure more info is needed, but please let me know: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/19c5f0cc-e878-4ff1-946a-7a8a56b5b637/Template-Topic-desktop

- Max 3 in a row, which on my mock occupies the first 10 columns (left to right) or 964px

**Comment by desigonz** [comment]
Thanks @chasechenevert, removing you. I've updated acceptance criteria above. @briaguya do y'all need further acceptance criteria?

**Comment by briaguya** [comment]
@desigonz I put together a quick fix for this:
Compare [staging](https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/) to [this pr app](https://deploy-preview-551--janis.netlify.com/en/health-safety/healthcare-prevention/disease-prevention)

**Comment by desigonz** [comment]
@briaguya looks beautiful, QA complete.
