### ISSUE TITLE
User research CTA page

### ISSUE THREAD

**Issue by kriskristin** [cityofaustin/techstack#3098]
### As a resident interested in participating in research with ODD I want an easily findable sign up form so that I can participate in research with ODD.

We will likely be promoting sign ups in Spanish for user research with ODD via video. Currently we gather participant via a google form but the URL will not work for a video segment.

**Ideally we would:**
- Create something similar to [Mass.gov](https://www.mass.gov/user-panel?utm_source=chalkmark&utm_campaign=annoucement-demo-test).
- Use content from our medium [article](https://medium.com/civiqueso/help-test-the-city-of-austins-new-website-1d405c660fd4)
- And a button saying something like "Sign up to test alpha.austin.gov" that will send out to our current form. In the future, we could build a form on alpha.austin.gov.

**Current state**
We have a form that we currently link to in [English](https://docs.google.com/forms/d/e/1FAIpQLScEZa1kZM6Agyibq5L3y9JnFsV6hfNOaaSu8hq9FAPUnlmwqQ/viewform?usp=sf_link) and [Spanish](https://docs.google.com/forms/d/e/1FAIpQLSfjG1wxPhaj2tD-2mBk_8UKDMQ4MUW7VPjzLzQQEDC6SpNY7w/viewform?usp=sf_link). 

**Addition steps needed**
- Content from Medium article translated to Spanish

**Comment by kriskristin** [comment]
@srigdon @annieszot Could either of you let me know the process to get a Spanish translation? 
Also, what is the usual turn around for translations?

**Comment by kriskristin** [comment]
We could also embed the html from the form in the page so we aren't sending people away. See it work in [codepen](https://codepen.io/kriskristin/pen/Rwwbpym). Might look hacky though.

**Comment by annieszot** [comment]
@kriskristin we have a "[How to get docs translated](https://docs.google.com/document/d/1vGsq17-a1Ho9gjkVBUiTNnPLsrGPkLfWKP7gPv5kpJ8/edit#heading=h.xbik72h24d7a)" doc! Ask questions that you have anytime :)

**Comment by desigonz** [comment]
Converting this into an epic and will file individual tasks under it!

**Comment by desigonz** [comment]
I'm excited to reported that this page is LIVE in English and Spanish, and we link to it from the nav *and* the footer!
