### ISSUE TITLE
Review content for the user research page

### ISSUE THREAD

**Issue by kriskristin** [cityofaustin/techstack#3101]
We need this page to go through the editorial process. 
[Help test the City of Austin's new website](https://docs.google.com/document/d/1EJYp96A_Taf7A6ncutRIxwcjgDfGNaW6jTaZlOdjVUE/edit?usp=sharing)

Most of this is just copied over from [content I wrote for civiqueso](https://medium.com/civiqueso/help-test-the-city-of-austins-new-website-1d405c660fd4). But as I am looking at it, we might need to make adjustments. 

Have a look at what [Mass.gov](https://medium.com/civiqueso/help-test-the-city-of-austins-new-website-1d405c660fd4) has done.  And [the issue](https://github.com/cityofaustin/techstack/issues/3098) for the page itself.

**Comment by desigonz** [comment]
@ablangworthy27 can you size this issue?

**Comment by ablangworthy27** [comment]
I added my edits to the doc, and Kristin gave approval. I am now sending to @srigdon for review.

**Comment by srigdon** [comment]
Documenting the end goal for posterity: we want to create a user testing pipeline inspired by mass.gov's approach: https://www.mass.gov/guides/user-research-and-product-testing-on-massgov

For now, I did a review pass and everything looks good to go. There might be discrepancy in the form intro copy--if that was already translated before I edited it, feel free to go with the previous version so we can get this published ASAP. @kriskristin @desigonz @ablangworthy27
