### ISSUE TITLE
Drafts for new "place" page designs: single place view, multiple places page, using content from service page and department page. 

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#3103]
Objectives:
- As an resident, I want to be able to easily view where I can obtain a service
- As a resident, I want to be able to see details about a location's accessibility, hours, parking, and other issues which may effect my ability to obtain a service.

Artifacts:
- [ ] Comps using real-world service content for single "places" page
- [ ] Comp using real-world content for mulitple location places page
- [ ] Comp for how contact snippet and places work together
- [ ] Comp for department place page

**Comment by chasechenevert** [comment]
We determined that for MVP we'll just focus on creating the individual Place pages, and link to them where locations are currently listed within service pages (or elsewhere)
- Place page: includes all information that the contact snippet has including: phone numbers, fax, email, hours

**Comment by desigonz** [comment]
@chasechenevert and @toribr: I'm going to make this issue just about the single place page content type (Janis side), and then make a new issue for the Joplin side of the single place page. Later we can make more issues for the multi-view or the view from a service page, etc.

**Comment by desigonz** [comment]
Hey team—I broke these down into the individual tasks (#3194 and #3195), and transferred y'all's notes above to Place content type epic #2966. Once we decide whether we're doing a multi-page for MVP or just changing how multiple locations display on a service or info page, we can create issues for delivering those mocks. Closing this one, but let me know if you have questions!
