### ISSUE TITLE
Consider limiting formatting types in rich text boxes

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3107]
#### Format issues ####
Published pages are showing several layers of formatting which may be holdover formatting from draft pages in other platforms. 
#### Control issues ####
Currently an author can use any header level they want in any order they feel. An author understands headers as aesthetic choice rather than a structural feature and may choose to use headers in an order that is not clear or useful for users of screen readers.
### Possible solutions ###
I'd like to consider ways to control how headers and formatting are used and/or pulled in with a copy-paste. 
Might we:
- strip formatting when text is pasted
- allow only one header type at a time, in order, dependent upon what headers are already in use on the page

**Additional context**

**Comment by desigonz** [comment]
@Jo-Dwyer can you share specific examples of "format issues"? Bold in headings is one of the examples I've seen (in screenshot below, both pages are using H2s but the one on the right uses bold as well).
![image](https://user-images.githubusercontent.com/5839508/66327753-f8793980-e8f0-11e9-8ae1-fa19ae8df46c.png)

**Comment by desigonz** [comment]
Added these thoughts to epic #1422. Closing this one!
