### ISSUE TITLE
Translate user research CTA page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3110]
### As a resident interested in participating in research with ODD I want an easily findable sign up form so that I can participate in research with ODD.

- [x] Send the page out for translation
- [x] Once translations are back, enter into Joplin

Note: translation tends to take around a week.

"[How to get docs translated](https://docs.google.com/document/d/1vGsq17-a1Ho9gjkVBUiTNnPLsrGPkLfWKP7gPv5kpJ8/edit#heading=h.xbik72h24d7a)" doc

**Comment by desigonz** [comment]
Went out for translation 10/10, waiting on them :)

**Comment by ablangworthy27** [comment]
These are done and have been added to the page in Joplin.
