### ISSUE TITLE
User research CTA links on homepage and footer

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3111]
### As a resident interested in participating in research with ODD I want an easily findable sign up form so that I can participate in research with ODD.

**Acceptance criteria**
- [x] let's go ahead and expose SEO tab in edit
- [x] due to #3199, let's manually update these slugs
  - [x] English page slug: `/feedback`
  - [x] ~~Spanish page slug: `/realimentacion`~~ backlogging this for now since we don't have Spanish slugs working yet
- [ ] Change "More about the alpha.austin.gov project." to "**Help us improve our website.**" 
  - [ ] have it link to `https://alpha.austin.gov/en/feedback`
  - [ ] For español, change "Más sobre el proyecto alpha.austin.gov." to "**Ayúdenos mejorar nuestro sitio web.**" 
  - [ ] have it link to `https://alpha.austin.gov/es/feedback/`
  - [ ] Change information icon to Material feedback icon ([here](https://material.io/resources/icons/?icon=feedback&style=baseline))
- [x] Change "Learn more about this project" to "**Help us improve.**" 
  - [ ] have it link to `https://alpha.austin.gov/en/feedback`
  - [x] For español, change sentence "Encuentre más información en nuestro sitio del proyecto." to "**Ayúdenos mejorar.**" 
  - [ ] have it link to `https://alpha.austin.gov/es/feedback/`

![image](https://user-images.githubusercontent.com/5839508/66165780-244ba500-e5fb-11e9-99d8-b68c4473b445.png)
![image](https://user-images.githubusercontent.com/5839508/66165802-2e6da380-e5fb-11e9-8ca5-119f1a1581f5.png)

**Comment by ablangworthy27** [comment]
@desigonz we are going with this for the copy on both:

_Help us improve_

Do you think you can translate since it is so minimal or should I send out? I also question whether the information icon is a little inappropriate since the page is not informational in a larger sense, and really only talks about volunteering for research.

**Comment by desigonz** [comment]
Nice! Maybe add "our website"? *Help us improve our website.*

@kriskristin, would love your editorial eye on my translations:
Help us improve = Ayúdenos mejorar.
Help us improve our website = Ayúdenos mejorar nuestro sitio web.

**Comment by desigonz** [comment]
Also! We need a short slug, memorable for the page. @ablangworthy27 and @kriskristin, can you specify what you'd like it to be in English?

alpha.austin.gov/**slug-name-here**

**Comment by ablangworthy27** [comment]
For the slug, my suggestion is alpha.austin.gov/participate-in-research

I'm not sure that adding "our website" fixes the problem with the icon. Especially since the research isn't just for the site, but also services. But maybe I am overthinking it. 

@kriskristin I know we landed on _help us improve_but let me know what you think of Desi's suggestion.

**Comment by desigonz** [comment]
Oops didn't see your icon comment! Let me touch base with Chase about it.

**Comment by chasechenevert** [comment]
@desigonz Let's go with the Material "feedback" icon. Devs will have access to the icon in Janis, but anyone needs a link it's here: https://material.io/resources/icons/?icon=feedback&style=baseline

**Comment by kriskristin** [comment]
@desigonz Your translation looks great to me. 

To be clear we are talking about:
> slug = alpha.austin.gov/participate-in-research

> text on the mega menu and footer = "help us improve" 

I am not opposed to using "help us improve out website". 

@ablangworthy27 @desigonz 
I'll give a thumbs up to the slug and whichever option ☝️ fits better in the footer and mega menu.

**Comment by desigonz** [comment]
@easherma to merge branch with SEO and settings tabs exposed

**Comment by kriskristin** [comment]
after looking over the slug and getting some feedback, I am thinking that we should change it to "feedback"
@desigonz is it too late to make that change?

**Comment by desigonz** [comment]
@kriskristin Not too late, but we did just find a related bug in #3199

**Comment by easherma** [comment]
@desigonz changing URL page slugs by language isn't currently supported in Janis, do we want to make this happen now, or make it follow the pattern for privacy policy? (content changes, nothing changes in the slug but the language selected

**Comment by easherma** [comment]
another issue, looking for some feedback:
https://austininnovation.slack.com/archives/C0WTQUT2Q/p1571260465031600

**Comment by easherma** [comment]
Preview up here: https://deploy-preview-569--janis.netlify.com/

**Comment by desigonz** [comment]
- [ ] Let's follow what's happening for privacy policy for now. Would you mind opening an issue for the other one?
- [ ] there's a funny double `help us improve`
![image](https://user-images.githubusercontent.com/5839508/66962185-ff612400-f035-11e9-926f-8c4672a4a8f4.png)
- [ ] Need to update the link down here 
![image](https://user-images.githubusercontent.com/5839508/66962300-4818dd00-f036-11e9-919a-844de0726878.png)

**Comment by desigonz** [comment]
@easherma here's the missing acceptance criteria:
- [ ] Copy in nav menu should read:
  - [ ] English: "Help us improve our website."
  - [ ] Spanish: "Ayúdenos mejorar nuestro sitio web."
- [ ] In the nav menu, change information icon to Material feedback icon
- [ ] Resolve #3026 in order to meet the acceptance criteria about routing to the properly localized URLs

**Comment by desigonz** [comment]
@easherma Where can I test this?

**Comment by chasechenevert** [comment]
Agree on removing the icon.
