### ISSUE TITLE
Triage APH blockers

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3113]
**Objective** 
Triage APH blockers including preview bugs that are preventing us from sharing APH pages with stakeholders.

**Participants**
@Jo-Dwyer @desigonz 

**Agenda**

------
- [x] Schedule meeting
- [ ] Meet
- [ ] Create resulting issues

**Comment by Jo-Dwyer** [comment]
- [ ] Can't display multiple contacts #3079 Service pages are allowing only one to be selected; info allows multiple selected. Both only display one.
    - [ ] [Free health services...] (https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxNzYw) 
    - [ ] [Get a copy of your immunization...](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxODYx)
    - [ ] [Neighborhood centers help...] (https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxODYz)
    - [ ] [Job search help...] (https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxODM4)


- [ ] Fact check with APH
    - [ ] Does $20 cover a full panel for all STIs or one at a time? [Get tested...] (https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxNzcy)
    - [ ] What is the new contact for the diabetes coalition/ prevention? [Help prevent...] (https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxODY2)
    - [ ] What is the contact info for smoking prevention? [Plan a smoke-free...] https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxNzI2
