### ISSUE TITLE
ARR approvals next steps

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3114]
**Objective** 
Meet with Marni and develop a strategy for ARR approvals next steps

**Participants**

**Agenda**

------
- [x] Schedule meeting
- [x] Meet
- [ ] ~Create resulting issues~

**Comment by annieszot** [comment]
Met 10.8.19. @wilhitem will ask about ARR engagement with Stephen during 1:1 Friday, Oct. 11
Closing issue!
