### ISSUE TITLE
Navigation research share out

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3115]
**Objective** 
Share out nav research

**Participants**
@kriskristin and the team

**Agenda**

------
- [x] Schedule meeting
- [ ] Meet
- [ ] Create resulting issues

**Comment by kriskristin** [comment]
Final slide deck. [https://docs.google.com/presentation/d/1dREz12U_SNRdUulc75Akg6TAEGLlVjdxcoRiTuL4pe4/edit?usp=sharing]
