### ISSUE TITLE
Publishing before saving draft causes leave site alert

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3119]
If you go to joplin, edit a page, and then click "publish" or "update" before saving a draft a leave site alert pops up.

**Comment by desigonz** [comment]
I'm not able to replicate this per your description above. But I swear I've seen errant "leave site" alerts here and there. Can you add a video?

**Comment by desigonz** [comment]
Can't replicate, closing for now. If we see it again let's file a bug issue with steps to replicate.
