### ISSUE TITLE
Removed ordered list options in steps rich text blocks

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3120]
PR app: http://joplin-pr-3120-step-ols.herokuapp.com/admin/

**Acceptance criteria**
- [x] No ordered list options in basic steps rich text blocks (on service pages)
- [x] No ordered list options in step with options rich text blocks (on service pages)

-------

## background

**Describe the bug**
If you add an ordered list to a step it shows up as an unordered list

**To Reproduce**

1. Go to a service page in joplin
2. add a step with an unordered list and an ordered list
3. check it on Janis
4. see it's only unordered lists

**Comment by desigonz** [comment]
I wonder if there's a content/design question here. Steps are already numbered; do we want to allow for ordered (numbered) lists within them? I'll pose this question on the appropriate slack channels.

**Comment by desigonz** [comment]
From @toribr on Slack:
> To me, ordered lists within ordered lists sound like something needs to be rewritten, as parsing that as a user seem tres confusing.

**Comment by desigonz** [comment]
QA passed!

**Comment by easherma** [comment]
This caused a regression, it appears to break pages that still have ```ol```s in them discovered by 
https://github.com/cityofaustin/techstack/issues/3446

**Comment by desigonz** [comment]
@briaguya I've reviewed all of the service pages and removed one instance of `ol`. This issue is ready to go!
