### ISSUE TITLE
Trashy Schedule - Bulk Item pickup Invalid Date

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#3122]
**Describe the bug**

Some addresses return an `undefined` nextBulkPickupDate which comes out as an Invalid Date. However, i checked some other addresses and they correctly render. I am guessing it's because my next pickup date is in 2020, so far the ones I've seen render are in 2019.

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/4f86659b-b6fd-435a-b775-b058fdf01f7e)

**URL**
https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup/

**To Reproduce**

1. Go to {janis}/en/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup
2. Scroll down to step 3: Look up bulk pickup weeks
3. My address comes up as undefined: 8506 spearman. However 3203 Hollywood comes up as December.

**Current behavior**

Some addresses give back Invalid Date when searching next pickup. 

**Expected behavior**
- [x] When there is a valid date, copy should say: `Next bulk item collection: <date>`
  - [x] Remove hyperlink from "Next bulk item collection"
  - [x] Lowercase "bulk"
- [x] When there is no future date, replace the entire line "Next Bulk item collection: Invalid date" with `Currently, no upcoming bulk item collection date has been scheduled. Please check back soon.`

**Screenshots**
[Screen Shot of Invalid Date](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/95dca589-d5ee-461c-8224-8895bb1f6cbd)

**Additional context**

**Comment by desigonz** [comment]
@briaguya is this something we can control? Also I'd want to fact check. It might not be scheduled, or bulk pickup isn't available at that location.

**Comment by desigonz** [comment]
From Keri in ARR: 

> Our customer calendar needs to be updated in ReCollect annually for the upcoming year and I have been working with the team that creates our routing and mapping to get the 2020 schedule uploaded into the system. I am told this is expected to be completed by 11/22. As a result, customers who have already had two bulk collections this year do not have another one currently scheduled in the system. This should correct itself once that new calendar is uploaded.

We should author placeholder language for when there is no valid date, encouraging them to check back soon.

**Comment by srigdon** [comment]
Instead of this line: 
Next Bulk item collection: Invalid Date

Replace with this line: 
Currently, no upcoming bulk item collection date has been scheduled. Please check back soon.

**Comment by easherma** [comment]
The problem is we don't have any error handling before trying to format the date. Unassigned myself for now, feel free to grab it.

**Comment by chiaberry** [comment]
@desigonz to get official spanish translation

**Comment by desigonz** [comment]
Just sent out for the official translations; I'll create a new issue when they come in.

If this issue is ready to QA, please share a PR app link!

**Comment by chiaberry** [comment]
oops, on the PR but I forgot to put it here too: 

https://janis-3122-trashy-sched.netlify.com/en/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup/

**Comment by desigonz** [comment]
QA passed!!
