### ISSUE TITLE
Automatically assign department to pages according to their user profile

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#3123]
As an author within a particular department, I don't want to fill out fields with information that the system should already know about me:
- [ ] When creating a new page, "offered by" would automatically be assigned to pages, so no department assignment would need to be made manually. 
- [ ] The department selection on page templates remains as is for now. For future versions, we should change the presentation of this selection.

**Comment by desigonz** [comment]
Consolidated these into #3378!
