### ISSUE TITLE
Share insight with the web team

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#3129]
**Acceptance criteria**
- [ ] Talk about this at design pin-up

We've heard from folks in the Funshops that people in older generations tend to be afraid to share their info via the website. How might we meet this user group’s needs on the website? 

From [Civic Futures funshop notes and follow-ups 10.7.19](https://docs.google.com/document/d/1Z-dQsiTR-_zsUgivQxvQvWxZ9FII-2ztmOQWZh7vNF4/edit)

@srigdon Take the lead on when/how to answer this?

**Comment by srigdon** [comment]
Shared with @toribr and @chasechenevert as a consideration. Let's discuss a way to help city teams address this concern in the short term and what we can design for in the long term.
