### ISSUE TITLE
Incorporate/introduce Joplin/Janis in Funshop

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#3132]
Build on[ Civic futures deck joplin/janis intro](https://docs.google.com/presentation/d/1X11qt8jEBAbmI86tvLhzCXau2wcKr4APKWx5m-OYQK0/edit#slide=id.p)
Suggestion out of [Civic Futures funshop notes and follow-up](https://docs.google.com/document/d/1Z-dQsiTR-_zsUgivQxvQvWxZ9FII-2ztmOQWZh7vNF4/edit)

**Comment by desigonz** [comment]
We won't be transitioning EDD anytime soon, so I wonder if introducing Janis/Joplin is too much right now. Let's discuss this.

**Comment by annieszot** [comment]
Discussed at content pin-up Nov. 19.19. Will refer to Jo's goals, objectives, outcomes page, but as a whole, will keep Funshops content focused and not touch on Janis/Joplin. Department-specific Funshops that are transitioning content may differ. Closing!
