### ISSUE TITLE
PDF strategy including Funshop II training 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#3138]
Out of [Civic Futures Funshop pdf questions](https://docs.google.com/document/d/1h0CFV5cX1_kKSYVCxcIoFP2-P0nwOsMHW3hGsnz7nTE/edit?ts=5d97bd4e#)

**Comment by srigdon** [comment]
[Best practices for PDFs](https://www.nngroup.com/articles/avoid-pdf-for-on-screen-reading/) on websites

**Comment by Jo-Dwyer** [comment]
@srigdon do you have access to the Civic Futures pdf questions document that Annie referenced here?

**Comment by Jo-Dwyer** [comment]
@InaraFernandez questions re: PDFs might be of interest to you
