### ISSUE TITLE
Add to style guide  - acronyms and target audience 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#3139]
Context @Jo-Dwyer follow-up @srigdon will do from Civic Futures Funshop [questions](https://docs.google.com/document/d/1h0CFV5cX1_kKSYVCxcIoFP2-P0nwOsMHW3hGsnz7nTE/edit?ts=5d97bd4e#heading=h.vi63d4cmcjvy): 

How to deal with acronyms when writing for specific audience?

**Comment by desigonz** [comment]
For technical docs, spelling out acronym first with parenthetical on first instance, then acronym on second instance.

**Comment by srigdon** [comment]
Added!
