### ISSUE TITLE
Remove email requirement from "contacts"

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3145]
"Email" is currently a required field for the Contacts snippet. But it turns out tons of services/offices don't have a dedicated email. This forces the content editor to add 311's email for everything even for things that don't really apply, like contacting a clinic. Let's remove this requirement.

**Acceptance criteria**
- [x] Email is not required to save a contact snippet.

**Comment by desigonz** [comment]
@chiaberry to add PR link where to test and assign to @desigonz when ready

**Comment by chiaberry** [comment]
link to QA: https://joplin-pr-3145-remove-contacts.herokuapp.com/

**Comment by desigonz** [comment]
Looks great, QA complete! Ready to go to staging, no need for another round of QA.
