### ISSUE TITLE
Implement generic guide image

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3148]
Most of the time, authors will add an image to the guide. But if they don't add one, Janis defaults to a generic guide image.

**Acceptance criteria**
- [x] @chasechenevert to verify visual design implementation
- [x] When a content editor doesn't select an image for a guide, Janis displays this image:
![Guide_default image_draft 1png-24](https://user-images.githubusercontent.com/7027270/66139866-c0a78480-e5c6-11e9-93f5-3c96ad9469fc.png)

In context: 
![Screen Shot 2019-10-03 at 10 04 26 AM](https://user-images.githubusercontent.com/7027270/66139909-d2892780-e5c6-11e9-952f-5361b2ee2e04.png)

**Comment by robbobfrh84** [comment]
PR for this up now: https://github.com/cityofaustin/janis/pull/567

Checkout page without a image(*see the placeholder)

Here's one: https://deploy-preview-567--janis.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/test-a-guide
Checkout a page with and image

Here's one: https://deploy-preview-567--janis.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-vendor-permit-guide

**Comment by desigonz** [comment]
Assigning @chasechenevert to QA this. Chase, I'm noticing white space on the sides of the generic guide graphic but not the page with a non-generic image—thoughts on this?

![image](https://user-images.githubusercontent.com/5839508/66872133-d889eb80-ef6a-11e9-9855-ec7e23f43c81.png)
![image](https://user-images.githubusercontent.com/5839508/66872141-dd4e9f80-ef6a-11e9-8c68-2c60e61014cb.png)

@robbobfrh84, I'd also like to QA the acceptance criteria "When a content editor doesn't select an image for a guide, Janis displays generic image" once this is in staging.

**Comment by robbobfrh84** [comment]
Hey @desigonz This is in staging now! ready for QA!

**Comment by chasechenevert** [comment]
The whitespace issue is because of the max width is set differently between the two images. To make these match, lets have the max width: 100% and that should take care of it.

**Comment by robbobfrh84** [comment]
Here it is at 100% @chasechenevert Is that what you had in mind?

![Screen Shot 2019-10-16 at 6.16.38 PM.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/7ff17713-12ee-4c66-9179-32d8c8b3024d)

@desigonz I'll let you know once it makes it's way to staging for QA

**Comment by desigonz** [comment]
Looks beautiful. This might already be in production?

**Comment by robbobfrh84** [comment]
@desigonz Not with the 100% width change.

**Comment by chasechenevert** [comment]
Yes, the 100% width is what I was looking for so that it matches the other guide image example.

**Comment by desigonz** [comment]
Great, good to go to prod.

**Comment by desigonz** [comment]
This is now in production so I'm closing it!
