### ISSUE TITLE
Collapsible contact/location hours

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3149]
### Janis
XD Prototype: https://xd.adobe.com/spec/f81c5f2d-3350-4720-79ff-cd73881cf143-8e2d/
- [ ] Icon for down-carrot is named "arrow_drop_down" in the Material icon font we have in Janis, or can be found here: https://material.io/resources/icons/?search=down&icon=arrow_drop_down&style=baseline
  - [ ] Default state should have the arrow facing down
  - [ ] Open state should rotate icon 90 degrees so that the arrow is facing up
- [ ] Hours are now collapsed behind a dropdown, and displays the current day and hours. I’m not sure what the right term is, but it should open in the way that an accordion does (where content below moves down, instead of overlaying like dropdowns typically are).

**Comment by easherma** [comment]
Another thing that came up was the need for multiple hours per weekday. We'll need to update the mocks, and flesh out some code here (most likely):
https://github.com/cityofaustin/janis/blob/d44a1b54ea4dc2975e90e605e33ad17e12bc548d/src/components/Contact/Hours.js#L65

**Comment by easherma** [comment]
http://docs.wagtail.io/en/v2.6.3/reference/pages/panels.html#multifieldpanel

**Comment by desigonz** [comment]
This issue is no longer relevant, now that we've moved hours to the location content type.
