### ISSUE TITLE
Privacy Policy Link and Content

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#315]
Currently the Privacy Policy link only shows in the Menu on mobile. One solution to add the link to the footer on all devices. This is up to design's discretion.

- [ ] Design privacy policy page ([here's the content](https://docs.google.com/document/d/17u7LU8YFqqp4t6FkMyKwTjgQtqBKuhaeBsThfTGt5ZM/edit#))
- [ ] Implement privacy policy page
- [ ] Add link accessible on all devices

**Comment by amenity** [comment]
@chasechenevert is going to make sure that the privacy policy link stays in the footer in the Janis 2.0 mocks.
