### ISSUE TITLE
Email alias for user research page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3154]
@ablangworthy27 and @kriskristin have drafted a nifty page to encourage residents to [sign up for user testing](https://joplin.herokuapp.com/admin/pages/241/edit/#tab-content). But we're currently using Kristin's personal email address, which is something we advise against. Let's work with IT to develop a mailbox specifically for user research communications.

[Notes on how to request mailboxes](https://github.com/cityofaustin/techstack/issues/2246#issuecomment-498058065)

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/899927b6-bebd-41d7-90c4-b809ae191d0b)

- [ ] Decide on what we'd like the email address to be
- [ ] Request from IT
- [ ] Once we have a new email address, swap it on that page

**Comment by ablangworthy27** [comment]
@kriskristin do you want to choose an email and request it? Desi suggested user-research@austintexas.gov but it is really up to you. 

Then I can swap it out.

**Comment by kriskristin** [comment]
@ablangworthy27 
either "user-research@austintexas.gov" or "feedback@austintxas.gov" work.
I can go through the process to get one and then let you know when it is set up.

**Comment by desigonz** [comment]
I like feedback@austintexas.gov!

**Comment by srigdon** [comment]
I like feedback@austintexas.gov, too! 

Steps to set one up:
1. @kriskristin, if you're good with that email address, decide who will have access to it. You'll need to put their names in the help ticket to request it. 
2. Submit a ticket through ServiceNow > https://atx.service-now.com/sp

**Comment by desigonz** [comment]
I think the emails about participating in research can go straight to y'all. Thanks!

We might also use this email when the feedback module fails. If that's the case, can y'all forward those emails to me? And if it seems cumbersome, we could add me to the inbox then.

**Comment by kriskristin** [comment]
Requested the email today. Not sure of the turn around, but seems like an easy edit to make to the content of the page. 

As far as the case for a feedback module failure. I think keeping that going to the same email address for the time being (feedback@austintexas.gov) is perfectly fine. If it gets cumbersome, we can make the change further down the road.

**Comment by annieszot** [comment]
@kriskristin, Andrew and Honker will publish a Civiqueso post on the tech selection tool. They'd like feedback on the toolkit, so may I include the feedback@austintexas.gov email address for how to get in touch? I can ping Andrew that you and Anu will have access to the email address.

**Comment by kriskristin** [comment]
feedback@austintexas.gov is live with @anukandimalla and I as email recipients for the emails currently.

@ablangworthy27, can we make that change in the spanish and english user research sign up page?

Side note, this is a distribution list. This means that we cannot respond to emails from the account, it is an inbox that distributes to folks on the list and then we can email from our personal accounts. The distribution can be added to and taken away by contacting folks at IT. My contact has been neil.nelson@austintexas.gov

**Comment by desigonz** [comment]
Awesome, thanks Kristin!!
