### ISSUE TITLE
Slug for page does not update if title is changed

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3156]
This turned out not to be a bug, per se, but it may still need to be thought through or documented. 

**Current behavior**
Page slugs are hidden, and never updated. So when a page title is changed, the slug stays the same. 

**Expected behavior**
The ability to update page slugs
Or have page slugs update from title
Either way, if we do add the ability to change page slugs, we'd want to handle redirects for broken links in case the slug changes:
http://docs.wagtail.io/en/v2.6.2/reference/pages/model_recipes.html#have-redirects-created-automatically-when-changing-page-slug

The solution there may or may not apply to a headless context.

**Comment by easherma** [comment]
http://docs.wagtail.io/en/v2.6.2/reference/pages/model_recipes.html#have-redirects-created-automatically-when-changing-page-slug

**Comment by desigonz** [comment]
Incorporated all these thoughts into the epic #2686. Closing this issue!
