### ISSUE TITLE
Document what needs to change for model changes between janis and joplin, and make this process more nimble, flexible

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3157]
---
name: Feature request
about: Suggest an idea for this project

---

### As a [user type] I want [capability] so that [benefit].

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by desigonz** [comment]
Can you add more detail to this issue? Trying to figure out how this fits into the picture of our incremental builds/Joplin 3 issues.
