### ISSUE TITLE
Lets find some time to squash migrations for Joplin

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3158]
### As a developer I want migrations to be squashed so that build times improve and changes are easier to manage.

**Is your feature request related to a problem? Please describe.**
We have two years worth of database migrations running on Joplin. Django is very good about handling these, but once we're over around 100 it starts to get a little silly, and we have over 200. 

**Describe the solution you'd like**
Pick a strategy:
https://docs.djangoproject.com/en/1.11/topics/migrations/#squashing-migrations
vs
https://cfpb.github.io/cfgov-refresh/migrations/#recreating-migrations

Personally I'm inclined to go with the default approach as we don't have _that_ many manual migrations. The default approach is also more friendly to existing PRs. 

The process would be:
1) Open a branch, squash the migrations, test that everything works as expected. 
2) Merge this into master. Done the default way, old migration files are kept, and new branches will just run the new migration file. 
3) Once all active branches are merged in, we can delete the old migration files. 

**Describe alternatives you've considered**
Letting this fester...
Also I could be missing some complications! Feel free to chime in.

**Comment by briaguya** [comment]
@easherma I'm not too familiar with how migration squashing works. What happens if we have an environment at migration 50 but we squash 25 through 75 and then update the code on that env? Will it break?

**Comment by easherma** [comment]
As long as the old migration files are there, that branch will continue to run those because that is what its pointed to. 

When you squash migrations normally, it consolidated them all into a new file and the new file references what it was squashed from. 

From the django docs:
"These files are marked to say they replace the previously-squashed migrations, so they can coexist with the old migration files, and Django will intelligently switch between them depending where you are in the history. If you’re still part-way through the set of migrations that you squashed, it will keep using them until it hits the end and then switch to the squashed history, while new installs will just use the new squashed migration and skip all the old ones.

This enables you to squash and not mess up systems currently in production that aren’t fully up-to-date yet. The recommended process is to squash, keeping the old files, commit and release, wait until all systems are upgraded with the new release (or if you’re a third-party project, just ensure your users upgrade releases in order without skipping any), and then remove the old files, commit and do a second release."

**Comment by easherma** [comment]
We have a squashed migration in prod now, leaving the old migrations there for now, but new branches should use the squashed migration automatically.
