### ISSUE TITLE
Usability test participant database

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#316]
We've used various Airtable, Google Sheets, docs, etc. to manage participants for individual usability tests. We should put these together to create a master list and streamline our recruiting process.

Last time we discussed this, we pushed it back because we were hoping it would overlap with Inno Office CRM implementation, but we can't wait any longer to get our 🦆s  in order:
- There are legal implications including a minimum time period allowed between giving individual residents cash/equivalent.
- Testing with the same participant multiple times is almost always bad UX practice.

There are simple solutions we can use instead of a full-blown CRM: Airtable, MailChimp, etc. etc.

Ideally, this will turn into our management tool of a civic user testing group, á la [CUT Chicago](http://www.cutgroup.org/).

See also:
- [User Testing Recruitment & Communication Tool](https://docs.google.com/document/d/10J5Di_Ka99TnMiDWZDskrny2-7qA3RKgj4iGimy421c/edit)
- [Recommended Next CRM Steps, Prioritized](https://docs.google.com/document/d/10J5Di_Ka99TnMiDWZDskrny2-7qA3RKgj4iGimy421c/edit#heading=h.sj3wqzbd0ba7)
- [Resources to support ongoing for user research and testing](https://github.com/cityofaustin/techstack/issues?q=is%3Aissue+label%3A%22Resource%3A+Research+%2B+Testing%22+is%3Aclosed).

Aha! Link: https://desi1.aha.io/features/RT-313

**Comment by amenity** [comment]
@toribr @LauraTrujillo @ashleecoa @courtneyjacinic @cthibaultatx - please stick any relevant docs in the description!

**Comment by oliver2g** [comment]
@kriskristin just making sure you're aware of this issue. It's an old one but probably relevant to the work you're doing

**Comment by desigonz** [comment]
@kriskristin I'm going to close this because you've started this, and of course this will ongoing :)
