### ISSUE TITLE
Get search logs or set up search log capture for austintexas.gov

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#3160]
Toward an [evidence-based](https://www.nngroup.com/articles/search-log-analysis/) search strategy and information architecture, the search logs for austintexas.gov before, during, and after the transition from Drupal 7 to 8 would help us build a search strategy that serves residents the information and services they're looking for. 

See also: [nav testing shareout](https://docs.google.com/presentation/d/1dREz12U_SNRdUulc75Akg6TAEGLlVjdxcoRiTuL4pe4/edit)

Steps: 

- [ ] Figure out who or which team at the city handles this area, contact them. 
- [ ] Set up a system for capturing and for our team to view the data.

**Comment by desigonz** [comment]
Julia's set this up in austintexas.gov analytics!! Woohoo!
