### ISSUE TITLE
Guide accessibility testing

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3162]
We have a guide! But we haven't done accessibility testing for it. Let's test the guide with David Ondich.

- [x] Schedule with David. Ask if it's also possible to test in mobile.
- [x] Draft up list of specific questions
  - Heading levels
  - Mobile navigation
  - Desktop navigation
- [x] Run test with David
- [x] Write up resulting bug issues

**Comment by desigonz** [comment]
Related: #3049 heading levels in guides. How does this work on a screenreader? What's best practice?

**Comment by desigonz** [comment]
Let's test this guide: https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-vendor-permit-guide/

**Comment by kriskristin** [comment]
Meeting scheduled but David expressed concern about testing in mobile. I will follow up with him when we are there and see if there is a way we can make it happen some other way to test on mobile.
