### ISSUE TITLE
Guide pages don't load directly onto anchor tag location

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#3164]
**Describe the bug**
When you refresh or load a guide page that has an anchor (eg: http://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-vendor-permit-guide**#Maintain-or-renew-your-permit-2**), the page will not navigate to that exact anchor.

**URL**
https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-vendor-permit-guide/#Maintain-or-renew-your-permit-2

**To Reproduce**
1. Click on that link.
2. Observe that you are not directed to #Maintain-or-renew-your-permit-2

**Device**

Yes.

**Browser**
Chrome. And all other browsers.

**Comment by desigonz** [comment]
Going to backlog for now and review priority once we have a live guide.

**Comment by chiaberry** [comment]
Closed because Nick fixed this when he worked on the table of contents (issue #3094)
