### ISSUE TITLE
Guide page media queries are broken

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#3165]
PR code: https://github.com/cityofaustin/janis/pull/610
PR app: https://janis-3165-guide-page-small-screen.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-vendor-permit-guide

**Describe the bug**
Guide page sections used to be mobile responsive. Now they are not. Sad day.

All the code to make this work should already exist. Something probably changed on the parent classNames of the guide sections or something.

**URL**
https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-vendor-permit-guide/

**To Reproduce**

1. Click on that link.
2. Look at it on a mobile device via Browserstack.
3. Struggle to read contents.

**Current behavior**
It's too long

**Expected behavior**
It should be just right

**Screenshots**
![Screen Shot 2019-10-11 at 3.45.15 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/5e5cbb85-35c5-44ac-91a4-133bc95a2229)

**Device**
Discovered on Browserstack iPhone SE Safari

**Comment by desigonz** [comment]
:( yeah let's fix this

**Comment by desigonz** [comment]
@briaguya beautiful!!! QA passed.
