### ISSUE TITLE
Draft Generation Zero information page 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#3167]
http://austintexas.gov/department/youth-education
Airtable https://airtable.com/tblZogjLILtjQQuaJ/viwEr4exYRsg7mfr0?blocks=hide

**Comment by annieszot** [comment]
- research more to decide whether it's better as a service page or info page 
- [ ] Draft

**Comment by gabrielaperezdelaosa** [comment]
I'd like to work on this next Sprint unless someone else feels strongly about it.

**Comment by gabrielaperezdelaosa** [comment]
This page does not need to be made as it is a copy of https://keepaustinbeautiful.org/education/generation-zero/, instead we need to find a place to link to it. I'm adding that task to #2393.
