### ISSUE TITLE
Remove implied ability to re-order official documents

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3177]
### As a content editor adding official documents, I want an easy and understandable way to manage many document entries within the official document content type.

**Acceptance criteria**
- [ ] Ability to re-order is gone for official document pages (see C in the mock below—remove this!)
- [ ] Previews of official documents pages should show documents in the correct order (most recent at top)
- [ ] Note: steps on service pages should still have the ability to reorder.

![#2668](https://user-images.githubusercontent.com/3790067/64995571-33afbc00-d8a1-11e9-96c5-d5fdb809ff6a.png)

**Comment by toribr** [comment]
Due to the new structure of container/document, this issue is no longer relevant.
