### ISSUE TITLE
Official documents display order

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3179]
### As a content editor adding official documents, I want an easy and understandable way to manage many document entries within the official document content type.

**Acceptance criteria**
- [ ] ~~When user opens an official document edit page that already has entries, there is an empty first instance of the document on the top of the document entries (see A in the mock below)~~
- [ ] Documents already entered into the edit page display in reverse chronological order
- [ ] "Add document" button a the top
- [ ] When a user changes a date, the documents re-order into expected reverse-chronological order
  - This will only happen on a page refresh for MVP, we can look into dynamic updating for the future

**Comment by desigonz** [comment]
@toribr, I'm splitting up the official doc management into multiple issues with acceptance criteria. For this one, I'm looking at the mock and not sure how a user would add a second entry beyond the empty first instance. Can you specify that?

**Comment by toribr** [comment]
Let's see how dev feels about this:

![#3179](https://user-images.githubusercontent.com/3790067/66830359-eb74cf80-ef1a-11e9-99e3-5318041d6922.png)

**Comment by toribr** [comment]
@desigonz updated. let's review during design/dev sync.

**Comment by briaguya** [comment]
As per discussion with @toribr at dev/design sync, we're pushing the empty first document requirement off.

**Comment by desigonz** [comment]
@briaguya love it, thanks y'all for talking through that!

**Comment by toribr** [comment]
@chiaberry This all seems irrelevant to me now. agree?
