### ISSUE TITLE
Implement style guide menu in Joplin (make styleguide iframe TOC match Gitbooks TOC)

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3180]
### As a content editor I want the style guide panel in Joplin to display information relevant to the component/content type I am editing so that I can more efficiently find appropriate guidance.

**Is your feature request related to a problem? Please describe.**
The style guide panel in Joplin allows content editors to reference the style guide, but it's only half-way set up. 

- [Gitbook syncs](https://cityofaustin.gitbook.io/digital-style-guide/make-content-accessible) to the [Github repo](https://github.com/cityofaustin/digital-services-style-guide). Gitbooks should be the source of truth where editors go to update the style guide.
- Joplin pulls from the [Github repo](https://github.com/cityofaustin/digital-services-style-guide). 
- We haven't yet implemented it so that the menu syncs with Gitbooks. That's been confusing because when we navigate the style guide in Joplin, we see old content that doesn't match with Gitbooks.
![image](https://user-images.githubusercontent.com/5839508/65189208-f4ff3a80-da35-11e9-98e8-b85888346368.png)
- Since the Gitbook to Github sync is set up, we don't need to migrate info and department pages (#2985), we just need to fix the menu thing.
- Style guide content in Joplin
  - Currently, you see the correct style guide content on Joplin for information and service pages. 
  - Department page style content isn't appearing in Joplin—it 404s (see screenshot)

**Acceptance criteria**
- [x] For content types that don't have a page in the style guide yet, the default open page should be the [Gitbook intro page](https://github.com/cityofaustin/digital-services-style-guide/blob/master/README.md)
- [x] When a user opens the menu in the Joplin style guide tab, the menu should match the menu on Gitbooks (**note:** currently it's feeding in the old Github content menu, which does not match Gitbooks)
  - [x] TBD interaction for the dropdown menus like "Pick the perfect page type"—dev team, what would be easiest to implement for MVP?  
![image](https://user-images.githubusercontent.com/5839508/66773007-a0f44400-ee83-11e9-949b-8349260339a0.png)
- [ ] Once this is implemented, let's get rid of the [_words folder contents](https://github.com/cityofaustin/digital-services-style-guide/tree/master/_words) in Github. It's been confusing for the content team—in the past we've been updating in both places, but our source of truth from now on will be the Gitbook.

**Comment by briaguya** [comment]
@desigonz are we going to try to rethink our jekyll build process (the way the github.io version of the style guide) is done for this?

From what I've seen the github/gitbooks integration we have going on is kind of messy, and it might be worth thinking through a more manageable solution.

Possible options:
* Try to figure out a way to make gitbooks and iframes play nice (probably asking gitbooks nicely to see if they're willing to help us with cross frame options)
* Update our jekyll theme to display the correct items in the side menu but nothing else
* Rethink our style guild build process/jekyll theme stuff

**Comment by desigonz** [comment]
@briaguya Wasn't planning to work Jekyll build process, and it's much lower priority than other things. Is that a blocker for this issue? We could discuss this at the next dev sync if you'd like.

**Comment by easherma** [comment]
> @desigonz are we going to try to rethink our jekyll build process (the way the github.io version of the style guide) is done for this?
> 
> From what I've seen the github/gitbooks integration we have going on is kind of messy, and it might be worth thinking through a more manageable solution.
> 
> Possible options:
> 
> * Try to figure out a way to make gitbooks and iframes play nice (probably asking gitbooks nicely to see if they're willing to help us with cross frame options)
> * Update our jekyll theme to display the correct items in the side menu but nothing else
> * Rethink our style guild build process/jekyll theme stuff

For the record:
* gitbooks doesn't allow iframes
* i looked into other styleguide management options, including a plugin for Wagtail that exists exactly for that purpose
* however, content team still wants the Gitbook as a standalone version that can be a way to easily share best practices outside of the alpha project. 
* therefore, here we are :-)

**Comment by easherma** [comment]
I've tried a couple things, but Jekyll isn't really set up to be nimble about parsing the data from SUMMARY.md as I'd like. 

I'm tempted to migrate this to a Hugo project, which will follow the directory structure and link everything with relative links no problemo. Generating the Table of Contents is something it can do automatically, but the file structure isn't quite the same as Gitbook's.

I'm going to stew on this. It's not ideal, but hardcoding the table of contents in HTML might not be too bad, since we don't change it terribly often.

**Comment by easherma** [comment]
I made a version with a hard-coded nav for table of contents, its visibile in joplin now, or at https://cityofaustin.github.io/digital-services-style-guide/

**Comment by desigonz** [comment]
Looks great, QA complete! 🎉 I guess we can close the issue?
