### ISSUE TITLE
Lists in Janis

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3183]
Let's make lists style consistently and in ways that work beautifully with the rest of the content on a page. Here's where we'll start.

**Acceptance criteria**
- [ ] For both mobile and desktop, entire `<ol>` or `<ul>` should have the following per @chasechenevert's doc:
  - [ ] `Margin-top: 20px`
  - [ ] `Margin-bottom: 20px`
  - [ ] `Margin-left: 20px`
- [ ] Get rid of margin bottom for all `<li>` (mobile and desktop)

**To test**
@briaguya, can you help flesh out a testing plan here?
When this is ready to QA, we'll assign to @chasechenevert

**Comment by chiaberry** [comment]
@chasechenevert Here is the deployed link

https://janis-3183-lists-in-janis.netlify.com/

Examples
- general list : https://janis-3183-lists-in-janis.netlify.com/en/austin-public-health/
- Department Page related links: https://janis-3183-lists-in-janis.netlify.com/en/police-oversight/
- Steps with Options: https://janis-3183-lists-in-janis.netlify.com/en/health-safety/health-records-certificates-2/birth-death-certificates/birth-and-death-certificates-test/
- Steps: https://janis-3183-lists-in-janis.netlify.com/en/health-safety/disaster-safety-relief/disaster-preparedness/public-health-emergency-prep/

I cannot remember if we settled on me reverting the changes to the steps or not, so I left them matching the acceptance criteria. Let me know if I should put the margin back on  `<li>` or not

**Comment by chiaberry** [comment]
@chasechenevert I updated the steps styling
https://janis-3183-lists-in-janis.netlify.com/en/health-safety/disaster-safety-relief/disaster-preparedness/public-health-emergency-prep/

and removed the special styling that dept pages related links had
https://janis-3183-lists-in-janis.netlify.com/en/police-oversight/

let me know if this looks good, and ill get it merged

**Comment by desigonz** [comment]
These look great to me! @chasechenevert, can you confirm?

**Comment by chasechenevert** [comment]
**Step styling**: good to go!

**Special styling around related links**: much better already, all we need to do is remove the `margin-bottom` that's being applied to the `li`s and we'll be good to go.

**before**
<img width="425" alt="Screen Shot 2019-11-06 at 12 24 42 PM" src="https://user-images.githubusercontent.com/7027270/68326126-76fffd00-0090-11ea-9e18-23d402698f46.png">

**after**
<img width="368" alt="Screen Shot 2019-11-06 at 12 24 56 PM" src="https://user-images.githubusercontent.com/7027270/68326149-7f583800-0090-11ea-853b-c6aed713da40.png">

**Comment by chiaberry** [comment]
@desigonz and @chasechenevert, updated! if its all good to go now, I'll merge

**Comment by desigonz** [comment]
Looks great, QA passed!
