### ISSUE TITLE
H1 font weight

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3184]
**Acceptance criteria**
- [x] All H1s should have the same `font-weight` of `700`
- [x] The one exception is section headings within guides, which should remain at `500`

![image](https://user-images.githubusercontent.com/5839508/66778558-a48ec780-ee91-11e9-8c43-7b120cfc1d1c.png)

**Comment by chiaberry** [comment]
@desigonz  ready for QA, deployed link: https://janis-3184-h1-font-weight.netlify.com/

here is the link for section headings within guides https://janis-3184-h1-font-weight.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-vendor-permit-guide/

**Comment by desigonz** [comment]
@chiaberry QA complete, looks great!
