### ISSUE TITLE
Clean up Error Messages from janis_url function in Joplin

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#3185]
**Describe the bug**
When we navigate to the home page `pages/3` on Joplin there are issues thrown for every page that's queried. They look like this:
```
!janis url error!: Participate in research with the City of Austin list index out of range
Traceback (most recent call last):
  File "/Users/nicholasivons/City/joplin/joplin/base/models/janis_page.py", line 123, in janis_url
    theme_slug = self.topics.first().topic.topiccollections.first().topiccollection.theme.slug or None
AttributeError: 'NoneType' object has no attribute 'topic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nicholasivons/City/joplin/joplin/base/models/janis_page.py", line 127, in janis_url
    theme_slug = self.topiccollections.first().topiccollection.theme.slug or None
AttributeError: 'ServicePage' object has no attribute 'topiccollections'
```

**URL**
http://localhost:8000/admin/pages/3

**To Reproduce**
Go to the page on a local environment. See all the errors.

**Current behavior**
We get many error messages.

**Expected behavior**
We don't want all of those error messages.

**Comment by easherma** [comment]
So these error messages are pretty legit and we should probably talk about the situations they describe and how to handle them. 

These are the steps I'm planning to take:

1.  Make better use of Python logging to have control over where and when these errors print out

1. Trace and document the current errors that are happening and note why they are happening
1. Modify the code to handle them in a more preferred way if applicable, think about unit testing in this context as well

**Comment by easherma** [comment]
During dev sync we talked about a concern here being that these errors pop up when you try to dump data. However, that is a depreciation error that shows up there and should be addressed as part of: https://github.com/cityofaustin/techstack/issues/2883
