### ISSUE TITLE
Translate dates in each official documents content type entry into Spanish 

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#3187]
### As a reader of a given page using the official documents content type in Spanish, I want to read the dates in my preferred language so that I'm not confused by English and Spanish content on the same page.

**Acceptance criteria**
- [ ] In Spanish, each date should appear in this format: `[day] de [month] de [year]`
  - [x] **january:** 9 de enero de 2019 
  - [x] **february:** 9 de febrero de 2019
  - [x] **marzo:** 9 de marzo de 2019
  - [x] **april:** 9 de abril de 2019
  - [x] **may:** 9 de mayo de 2019
  - [x] **june:** 9 de junio de 2019
  - [x] **julio:** 9 de julio de 2019
  - [x] **august:** 9 de agosto de 2019
  - [x] **sept:** 9 de septiembre de 2019
  - [x] **oct:** 9 de octubre de 2019
  - [x] **nov:** 9 de noviembre de 2019
  - [x] **dec:** 9 de diciembre de 2019

**Is your feature request related to a problem? Please describe.**
Right now, the dates for each entry in the official documents content type display in English, and there doesn't seem to be a way to enter the Spanish translation in the date picker. 
![Screen Shot 2019-10-14 at 3.41.06 PM.png](https://images.zenhubusercontent.com/5be0b7bea977220c77bd229b/92f857f0-cd85-4014-aac7-a880ad16b50f)

**Describe the solution you'd like**
Ideally, we'd automatically display each date in the language the user picks on Janis, and not have to enter it manually in Joplin. We'd also save a lot of translation $$ this way. 

**Describe alternatives you've considered**
Alternatively, we could manually enter every date in every language, but the date picker isn't designed to allow for this anyway. 

Assigning to @desigonz to prioritize.

**Comment by chiaberry** [comment]
https://momentjs.com/docs/#/i18n/

**Comment by chiaberry** [comment]
@desigonz  ready for QA: https://janis-3187-translate-dates-docs.netlify.com/en/health-safety/police-oversight-2/police-feedback-and-records/official-complaint-and-discipline-documents

toggling spanish / english will toggle the dates' language

**Comment by chiaberry** [comment]
also, not sure if the size should be dropped down to 3?

**Comment by desigonz** [comment]
@chiaberry just changed it. 

Can you share the Joplin PR app link? To test the rest of the months, I'll need to add a few more documents. Thanks!

**Comment by chiaberry** [comment]
@desigonz  hm, I didn't have to change anything on the Joplin side of things, do I create a separate joplin instance and have this deployed janis point to it? I'll ask the devs

**Comment by desigonz** [comment]
Well there are just certain months that aren't covered by the documents currently entered in Joplin, so I can't verify that they work (see the months I've checked off above). If there's some other way you think I could easily test this, let me know!

**Comment by chiaberry** [comment]
@desigonz  Here is a joplin for you to test on, https://joplin-pr-3187-janis-branch.herokuapp.com/admin/pages/3/, it should be linked to the deployed janis branch now

**Comment by desigonz** [comment]
QA passed! Looks great.

**Comment by desigonz** [comment]
Can this one go to production?
