### ISSUE TITLE
Translate, review, and publish mobile food vendor guide 

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#3190]
Steps left to get this over the finish line: 

Once I receive approval from Marcel and Don, assign to two rounds of review by two of our eagle-eyed content strategists. @annieszot I'd love one of those rounds to be by you, as you've got guide experience. Does doing that some time this sprint (42) work for you? 

- [ ] Send it off for Spanish translation. 
- [ ] Publish the English version, and the Spanish one when we receive it. 
- [ ] Send it to EHSD for enjoying and bug squashing.

**Comment by desigonz** [comment]
This issue is very exciting.

**Comment by annieszot** [comment]
Happy to help and review @srigdon ! Just assign and ping me when you receive approval from Marcel and Don :)

**Comment by srigdon** [comment]
Steps left to do: 

- [ ] Approval (and maybe comments) received. 
- [ ] I'll incorporate any edits or comments I get in the Google docs, Sharepoint docs, and Joplin. - [ ] Assign a content strategist for first review. 
- [ ] Assign a content strategist for second review. 
- [ ] Meanwhile, decide where the guide and each page of the guide goes in the IA. 
- [ ] Put everything into a Word doc and send to Language and Content for Spanish translation. 
- [ ] Discuss with @desigonz: 

- How should we handle the content debt that has already emerged? 
- How will we address requests for edits from EHSD? Do we offer to train someone and create a new account, or hold off for now? 
- How will we return to the topic of making the permit application and mobile food vendor business updates an online form? It's not a simple form, you need to pay a fee, and one part is a notarized form that can't be sent online, it has to be mailed or submitted in person.
