### ISSUE TITLE
Joplin mocks for single place page content type

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3194]
- [ ] Comps for Joplin single place page content type

For MVP we'll be displaying:
- Phone
- Fax
- Email
- Hours
- Physical address

**Comment by desigonz** [comment]
Will discuss at dev-design sync on 10/29

**Comment by toribr** [comment]
@desigonz Your MVP display list above is no longer accurate. Do you want to modify it, or have dev use the comp below?

@desigonz Also - could use @srigdon or other content to review micro-copy.

![Locations_page](https://user-images.githubusercontent.com/3790067/68406906-48455d80-0148-11ea-8b39-89853087cf63.png)

**Comment by desigonz** [comment]
Thanks @toribr! I'll develop acceptance criteria for dev in a new issue, and base it on your mock.

Assigning @ablangworthy27 to review microcopy, since she did it for the Janis side of things. Please review headings, helper text, etc.

**Comment by ablangworthy27** [comment]
**Location name**
This is good.

**Location physical address**
This is good.

**Choose an image for the location page**
Is this a banner image? If so, let's make the copy "Choose a banner image" 
Also, this is a larger discussion that can wait, but is this image meant to be specifically of the exterior of the location? Or can they use a stock image that depicts relevant activity, etc...

**Location mailing address, if any**
Change to  "Location mailing address (if applicable)"

**Location alternate name** 
This is good.

**Use this field if the building has a second name or is within a larger facility**
Change this to "Use this field if the building has a second name or is inside a larger facility".

**Location phone number**
This is good.

**Only if location has dedicated number**
I am trying to come up with something else, but nothing is quite as clear as this.

**Phone description**
@desigonz @toribr I'm confused about what this would be used for, which might mean it should change or have additional context

**Nearest bus**
This is good.

**Add services delivered at this location**
This is good.

**Service buttons "Choose another page" and "Edit hours for this service"**
These are good.

**Hours**
The way hours are displaying isn't in line with our style guide, but I think that is another problem.

**Comment by toribr** [comment]
@ablangworthy27 

**Choose an image for the location page**
Yes, specifically the exterior. There will be a default image (tbd) already in place.

**Phone description**
This might be a bit future proofing, but an example might be "reservations"

**Hours**
yes, whole 'nother issue.

**Comment by ablangworthy27** [comment]
@toribr for the image, let's be specific. Can we add an additional line of text?

"Choose a banner image"
maybe with this underneath: "Use this to show the exterior of the location"

**Comment by toribr** [comment]
@desigonz This should be good to go!
![Locations](https://user-images.githubusercontent.com/3790067/68476519-78e0d200-01f0-11ea-9b35-1e195119e071.png)

https://xd.adobe.com/spec/d3fea86b-184d-4652-48b2-48ce78dcb3ae-a5cf/

**Comment by ablangworthy27** [comment]
Sorry to be nitpicky but "Choose **an banner** image" should be "Choose **a banner** image"

**Comment by toribr** [comment]
Quite all right! Fixed.

**Comment by toribr** [comment]
-[ ] Check what YouTube branding comes along with embedding files: can you control preview image before and after; the "watch next" stuff; compression; accessibility?

**Comment by desigonz** [comment]
Consolidated into #3400
