### ISSUE TITLE
Gather requirements for language translation workflow

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#32]
Currently, we are purchasing translated content and entering it into the CMS ourselves. This is not a sustainable solution and we need to start planning for one that is. 

Meet with CPIO language access and get information on their work: 
- Are we still evaluating vendor tools?
- Will we have a dedicated budget for ongoing translation services like those we've been obtaining so far?

Depending on their strategy, we may need to perform any of the following:
- User research with translators.
- Evaluation of any vendor tools to determine how they might integrate with our CMS
- Research into an in-house translation solution.

Some questions we need to answer if we are building the solution in-house:
1) this seem like it might be a new user role, ie, the translator actor gets permission to work on pages, but only in a narrow capacity, ie, adding a translation to fields, but not changing anything else on the page. 
2) Can it be assumed that the translator works on pages city wide? How many translators for each language will be required? How will the division of pages be achieved in the case of >1 translator per language?
3) How are updates handled? When new content is added, does the system somehow notify the translators that a new translation is required?
4) Are pages not published until all translations are available? If this is the case, then see 3) for managing new content.
5) If translations are *not* required prior to publishing, then what does a non-english reader see if a page is not available in their language?
6) Who is responsible for making sure pages get translated and published, and how is this info communicated to the responsible party?
7) What properties are associated with the translator role: (name, language, email, publish rights, etc)

Notes from workflow meeting: https://docs.google.com/document/d/1kLn7QK3kqMtj6sVGPvf0GhVvugswbLbgO_EGcYERhFw/edit?usp=sharing

- [ ] Meet with @benweatherman, @toribr, and content team to sketch out "translation needed" notification

**Comment by cthibaultatx** [comment]
@toribr please add your questions in the main body of this issue

**Comment by benweatherman** [comment]
In a meeting today with translators, we got consensus for this stop-gap workflow:

1. Develop the English content
2. Send translators a link to the content and the raw HTML (the translators' system can handle importing HTML)
    - We'll optionally include a PDF highlighting just the changes since the last translation
3. Translators load the HTML, do the translation, and review the translations
4. Translators send back the HTML, which we'll load into the CMS/YAML files

**Comment by amenity** [comment]
Third email in to CPIO to figure out where they are with vendor platforms. 🙃

**Comment by amenity** [comment]
@benweatherman that sounds pretty great! No content team copy pasting!

**Comment by amenity** [comment]
Since we will be using local contractors to perform translation for the foreseeable future...We're going to #326 -make it a friendly, accurate, & efficient arrangement. 👭
