### ISSUE TITLE
Prototype linking to place pages

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3200]
### As a resident, I want to see all locations that offer a city service, so that I can find a location that’s most convenient for me.

- [x] MVP designs for how a user navigates from a service/info page to the place page.

**Comment by chasechenevert** [comment]
Designs are covered in the [XD Places MVP spec](https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/): 
- [Desktop](https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/screen/2a5af05a-3afb-4293-a312-96d5d333e375/Template-Service-list-desktop) 
- [Mobile](https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/screen/431f2b3c-5299-483c-adda-ed32d1951136/Template-Service-list-desktop) 

<img width="1403" alt="Screen Shot 2019-11-06 at 11 11 38 AM" src="https://user-images.githubusercontent.com/7027270/68320816-41eead00-0086-11ea-8779-e7f2adbcfb7a.png">

- [ ] Padding: 2rem
- [ ] Border: 1px, `#C6CACE`
- [ ] Location name: 1.6rem, 700, 
- [ ] Address: 1.4rem, 400, `#3D4551` (or `'gray-cool-79'` in USWDS tokens)
- [ ] Max width: 572px
- [ ] Minimum width: 318px
- [ ] Margin between location tiles: margin-bottom: 8px, or 0.8rem
- [ ] Margin for the bottom of a location list `ul` margin-bottom: 2rem

**Comment by chasechenevert** [comment]
Pushed the update here: https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/

**Comment by desigonz** [comment]
Consolidated into #3400, will flesh out further there!
