### ISSUE TITLE
Localization for links to global pages

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3206]
**Describe the bug**
We implemented the privacy policy as a hard-coded link in the footer, but when you're in español, the page only appears in English. 
![privacy-policy-espanol](https://user-images.githubusercontent.com/5839508/66965072-160b7900-f03e-11e9-9ae2-4e8f2f6c8529.gif)

This is also happening with the user research call to action page we're implementing in #3111
![3111-spanish](https://user-images.githubusercontent.com/5839508/66964716-08a1bf00-f03d-11e9-8e15-c8bce3ea8385.gif)

**Acceptance criteria**
- [x] When using the website in Spanish, clicking on the Privacy Policy link takes you to the Spanish version of the page
- [ ] "Privacy policy" in Spanish says "Política de privacidad" 

**URL**

**To Reproduce**

**Current behavior**

**Expected behavior**

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by briaguya** [comment]
line 72 of PageSections/Footer/index.js needs to be:
```
<Link to={`/${intl.locale}/privacy-policy/`}>
```

**Comment by desigonz** [comment]
@easherma Just QA'd this. It's missing one of the acceptance criteria:

- [ ] "Privacy policy" in Spanish says "Política de privacidad" 

![image](https://user-images.githubusercontent.com/5839508/67041768-fdf23300-f0eb-11e9-8d7d-8dca49008011.png)
