### ISSUE TITLE
Error number on content tab

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3207]
**Describe the bug**
See image below—I tried publishing a guide page with a section heading missing. I get a little number telling me how many errors it throws on the content tab, but they're behind the top menu bar. Let's bring the number to the front.
![image](https://user-images.githubusercontent.com/5839508/66965811-a3e86380-f040-11e9-875b-9190c1576e12.png)

**URL**

**To Reproduce**

1. Go to Joplin staging
2. Edit a guide page
3. Add a section to the page, but don't write in a section heading
4. Publish page

**Current behavior**
It doesn't let me publish the page, and what happened above appears

**Expected behavior**
It (still) doesn't let me publish the page, but the number doesn't get cut off

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by robbobfrh84** [comment]
I think this happened when we moved to having `search` page be our *main* page. We had to move the search header up the *z-chain* and it looks to have over-reached on this notificaiton. 

- Hopefully,  just an z-index fix
