### ISSUE TITLE
Form accessibility testing

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3209]
Let's test this form with David Ondich to see how accessible our Formstack theme is out of the box. https://cityofaustin.formstack.com/forms/ni_request_day_laborer

- [x] Schedule with David. Ask if it's also possible to test in mobile.
- [x] Draft up list of specific questions(Started)
  - Error validation
  - Labels
  - Form fields
- [x] Finalize the Questions for Testing
- [x] Testing
- [x] Write up resulting bug issues

**Comment by kriskristin** [comment]
Meeting scheduled but David expressed concern about testing in mobile. I will follow up with him when we are there and see if there is a way we can make it happen some other way to test on mobile.

**Comment by kriskristin** [comment]
@Niicck On sprint day you mentioned that you would embed this form in a page on alpha before testing on 10/24. How is progress going on that?

**Comment by Niicck** [comment]
It's moving along. I'll be ready by Thursday. Tracking my progress in this issue: https://github.com/cityofaustin/techstack/issues/3202

**Comment by kriskristin** [comment]
@Niicck I was searching for that issue, thanks for sharing. 

For some reason I thought that we were just testing out a simple stand-alone form in the context of alpha. Glad I checked in on this.....

**Comment by Niicck** [comment]
A deployed simple form on alpha.

https://alpha-form-test.netlify.com/en/health-safety/health-records-certificates-2/birth-death-certificates/request-a-day-laborer/

**Comment by Niicck** [comment]
Here's a link to the form directly hosted on formstack:
https://cityofaustin.formstack.com/forms/ni_request_day_laborer
