### ISSUE TITLE
Designs and acceptance criteria for homepage/footer management

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3211]

**Comment by chasechenevert** [comment]
Notes from pin-up are here: 
[Design pin-up / Sprint 42 / Utility navigation management exercise](https://docs.google.com/document/d/1fECN-68xbty04_8QWgxXBLYqxXKswV8RTExjM0bGei0/edit?usp=sharing)

**Comment by toribr** [comment]
![#3211 Global links](https://user-images.githubusercontent.com/3790067/68786270-1bd88800-0605-11ea-826f-14c3600f17db.png)

**Comment by desigonz** [comment]
Acceptance criteria in #3408. Added it to the list for the next dev-design sync (#3409)!

**Comment by toribr** [comment]
https://xd.adobe.com/view/14ff4194-7f57-4617-5635-183575ff6d9d-62ce/

**Comment by desigonz** [comment]
Waiting on content strategist to review microcopy, then good to close.

**Comment by Jo-Dwyer** [comment]
I apologize for the delay @toribr. I check out the XD with microcopy re: link names.

**Comment by desigonz** [comment]
@toribr once the microcopy is updated and you've published the changes, you can close this issue. Thanks team!!

**Comment by toribr** [comment]
![#3211 Global links](https://user-images.githubusercontent.com/3790067/69559847-541a8780-0f70-11ea-8aef-7d6ede325e0b.png)
