### ISSUE TITLE
Draft pools and spas outline

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3214]
First draft by end of sprint 42

**Comment by ablangworthy27** [comment]
This can be seen [here](https://docs.google.com/document/d/19xjtvx32XEYuo2B3yTMJ6_Hnd863UMn69Ab-ToeWpEc/edit#)

**Comment by desigonz** [comment]
😍love it! I'm wondering if this is actually three separate guides with a lot of the same pages within them:
- Get a permit for a new pool
- Get a permit for an existing pool with a new owner
- Renew your pool permit

I believe we had this conversation a while back with @srigdon and @toribr—maybe something to discuss at content pin-up?
