### ISSUE TITLE
Draft Municipal Court department page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3221]
https://www.google.com/search?q=municipal+court+austin&oq=munic&aqs=chrome.1.69i57j69i59j0j69i59j69i61l2.2665j0j7&sourceid=chrome&ie=UTF-8

**Comment by annieszot** [comment]
Draft 
https://docs.google.com/document/d/13YwVBDWonaAQ4Rh6l_O1ufv9Vk2AAd9IXty9ZW9luHM/edit
Pinging @Jo-Dwyer for first review. Feel free to toss back with suggested edits by Wednesday, Oct. 29 close of business. I'll polish it before you fact-check/get approval from Amy, then I'll bring Sarah in for final review.

**Comment by Jo-Dwyer** [comment]
This looks excellent! Sent to Amy at municourt for review! Thank you for the lovely, fast work @annieszot!

**Comment by annieszot** [comment]
Great! @desigonz Good to close?

**Comment by desigonz** [comment]
Dream team!! Thanks y'all.

I think this is good to close. Can y'all open a new issue for the approvals and rounds of internal editorial review?

**Comment by annieszot** [comment]
Closing
Made #3289
