### ISSUE TITLE
Draft parking ticket content

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3222]
By end of the sprint 42, @Jo-Dwyer will have outline the process for resolving a parking ticket and a roadmap for what needs to get drafted.

**Comment by desigonz** [comment]
@Jo-Dwyer please add an estimate!

**Comment by Jo-Dwyer** [comment]
This page requires the alternative payments page before publication.

**Comment by desigonz** [comment]
I added the alternative payments page as a dependency.

**Comment by Jo-Dwyer** [comment]
[Draft page lives here](https://cityofaustin.sharepoint.com/:w:/s/CTM/TEAMSITES/ODD/ETkRno1kyhZFloAlt6OsYzUBLtxddHbN1m8EhZQTzg-yZQ?e=nAExPS)

**Comment by Jo-Dwyer** [comment]
sent draft of this and #3221 to Amy at municourt today

**Comment by Jo-Dwyer** [comment]
Content is being fact checked by Amy Schillerstrom at Municourt.
[Resolve a parking ticket page](https://cityofaustin.sharepoint.com/:w:/r/sites/CTM/TEAMSITES/ODD/alphaaustingov%20Content/Workflows/Departments/Municipal%20Court/Resolve%20a%20parking%20ticket%20service%20page.docx?d=w8d9e1139ca644516968025b7a3ac6335&csf=1&e=H04HW3)

**Comment by gabrielaperezdelaosa** [comment]
@ablangworthy27 for review

**Comment by ablangworthy27** [comment]
All the links are not working yet, but I'm assuming that is because the pages are in the works.

I updated/restructured the pay your ticket option. Otherwise, it looks goodl

**Comment by ablangworthy27** [comment]
On the request for dismissal form,

**Suggested changes:** 
License Plate Number change to License plate number

Uploaded image of ParkATX receipt or Pay Station Sticker/Receipt(Required)
 **(does Pay Station Sticker/Receipt need to be capitalized?)**
Any other images/files to be considered by the Hearing Officer
 **(does Hearing Officer need to be capitalized?)**

Any additional statement you would like considered
**change to:**
Provide any additional statement you would like considered.

Also, when I tested this, I never received any confirmation email.

**Comment by ablangworthy27** [comment]
I made a simple update to the description for the Request an online hearing form container.

**Changes that should be made to the form:**

add link to https://zoom.us/test

If they select 'No' for zoom capabilities, should this disqualify them?

Also, when I tested this I never received any confirmation email. We may want to have these properly qa'd
