### ISSUE TITLE
View live links for top-level pages

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3225]
**Describe the bug**
Amanda published "Participate in research with the City of Austin" and checked "Make this a top level page," but the view live links don't open the page at the expected URL. https://joplin.herokuapp.com/admin/pages/241/edit/#tab-content

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/3021cc82-fba6-495b-b4f7-16da8a053f27)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/03378917-b858-42c3-9a04-aaf86c7070eb)

**Acceptance criteria**
- [x] Live pages with no topics or departments, but demarcated as a top-level page, should open from the following:
  - [x] "View live" from the main content listing page
  - [x] "Live" button on the individual edit page 
- [ ] Write unit test to verify that view live button is working as expected

**URL**

**To Reproduce**

**Current behavior**

**Expected behavior**

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by easherma** [comment]
I belive this is fixed in https://joplin-pr-3285-error-messages.herokuapp.com/admin/pages/3/ 
https://github.com/cityofaustin/joplin/pull/422

**Comment by desigonz** [comment]
This passed my product QA, but I'm seeing that one of the acceptance criteria was "Write unit test to verify that view live button is working as expected." I don't think we have started doing that, right?

**Comment by desigonz** [comment]
@easherma, maybe you can just file a new issue for the unit test and then we can proceed with this one?
