### ISSUE TITLE
Implement MVP permissions  

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3227]
### As a Joplin user, I want permissions around what I can and can't do, so that I can effectively edit content within the bounds of our content governance structure.

| Action                                      | Editor | Moderator | Administrator |
| --- | --- | --- | --- |
| View published content                      | ✅             | ✅               | ✅             |
| Draft new content                           | ✅             | ✅               | ✅             |
| Edit published content (draft)              | ✅             | ✅               | ✅             |
| Publish/update content                      |               | ✅               |   ✅             |
| View revision history                       | ✅             | ✅               | ✅             |
| Replace current draft from revision history | ✅             | ✅               | ✅             |
| Update from revision history                |               | ✅               | ✅             |
| Unpublish content                           |               | ✅               | ✅             |
| Delete draft content I authored                              | ✅               | ✅               | ✅             |
| Delete published content I authored                              |                | ✅               | ✅             |
| Delete content others authored                              |               | ✅               | ✅             |
| Content SEO tab                             |               | ✅               | ✅             |
| Content Settings tab                        |               | ✅               | ✅             |
| View snippet (in left nav)                            |              | ✅               | ✅             |
| Add snippet                                 |              | ✅               | ✅             |
| Save/publish snippet                        |              | ✅               | ✅             |
| Delete snippet                              |               |                 | ✅             |
| View users ("users" appears in left nav)                                  |  ✅             | ✅               | ✅             |
| Edit user                                   |               |                 | ✅             |
| Add new user                                |               |                 | ✅             |
| Delete user                                 |               |                 | ✅             |
| Add image                                   | ✅             | ✅               | ✅             |
| Edit image                                  | ✅             | ✅               | ✅             |
| Delete image I authored                                |     **skip**        |  **skip** ✅               | ✅             |
| Delete image others authored                               |        **skip**         |  **skip** ✅               | ✅             |
| Add document                                | ✅             | ✅               | ✅             |
| Edit document                               | ✅             | ✅               | ✅             |
| Delete document I authored                             |       **skip**       |  **skip** ✅               | ✅             |
| Delete document others authored                            |        **skip**       |  **skip** ✅               | ✅             |

- [ ] even though editors won't see snippets in left nav, they should be able to select snippets when drafting a page

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by desigonz** [comment]
Future: 
- see a user's department

**Comment by easherma** [comment]
This issue would actually be a great candidate to set up some tests!

- Start using user roles and permissions
- Set up some test users with these roles
- Break down these tasks by functionality and find the best places in the codebase to control each one, write a test to verify it.
- Since we overall don't have unit tests or end to end tests, for some of these we'll want to make sure that restricting functionality doesn't intentionally break things

I have some questions on acceptance criteria for these, for instance: 
- Snippets cannot be viewed by editors, but should they still be able to be choose from a list of snippets for a page where appropriate, etc?

If the issue seems too big, it might be better to split these permissions into chunks based on functionality (e.g. make sure permissions work as expected and don't break anything for pages first, then snippets, then documents/images, etc.)

**Comment by desigonz** [comment]
Yes, editors should be able to view snippets! I added an acceptance criteria above for that. Keep the questions coming.

Tomorrow at sprint planning we can break this down if need be.

**Comment by chiaberry** [comment]
@desigonz: question about the editors permissions, can they see the seo tab but can't interact with it, or do they not see the seo tab at all? same question for content settings tab

**Comment by desigonz** [comment]
@chiaberry For both: They can't see it at all. Thanks for clarifying!

**Comment by chiaberry** [comment]
https://joplin-pr-3227-permissions-mvp.herokuapp.com/

mod@austintexas.io pw: w
test@austintexas.io pw: q

**Comment by desigonz** [comment]
### Assigning to QA
- @annieszot to review **editor** role (login: test@austintexas.io pw: q)
- @ablangworthy27 to review **moderator** role (login: mod@austintexas.io pw: w)

### Test URL
https://joplin-pr-3227-permissions-mvp.herokuapp.com/

### Testing notes
1. To test, check against your respective column at the table at the top of this issue. 
2. Some of the fields say **skip**—don't worry about those!
3. If behavior is inconsistent with the table above, log it as a comment here.

Thanks y'all!

**Comment by ablangworthy27** [comment]
Ok, I reviewed the moderator permissions and the only thing I had a question about was snippets. Does "save" = "publish"? I only ask because I saw no publish option, and am not sure if I was supposed to. 

Otherwise, everything checks out for the Moderator role!

**Comment by annieszot** [comment]
QA documentation for Editor role. QA'd in Google Chrome 78.0 
Inconsistent behavior summary: 
Delete content others authored- Delete option not available on live content others authored but delete option is available on drafts others authored 


| Action                                      | Editor | Notes | 
| --- | --- | --- | --- |
| View published content                      | ✅             | "View Live" pages load at different speeds
| Draft new content                           | ✅             |
| Edit published content (draft)              | ✅             | Viewed "Flu prevention" draft
| Publish/update content                      |               | "Save as draft" only option 
| View revision history                       | ✅             | Viewed Revisions of "Drop off household waste" 
| Replace current draft from revision history | ✅             | "Compare with previous revision" button
| Update from revision history                |               | Option not available
| Unpublish content                           |               | Option not available 
| Delete draft content I authored                              | ✅               | Delete button available for draft. Delete possible for draft
| Delete published content I authored                              |                | Delete button not available - viewed "Austin Public Health department published page
| Delete content others authored                              |               | Delete option not available on live content others authored but delete option is available on drafts others authored 
| Content SEO tab                             |               | No content SEO tab
| Content Settings tab                        |               | No content settings tab
| View snippet (in left nav)                            |              | No snippet in left nav
| Add snippet                                 |              | No add snippet
| Save/publish snippet                        |              | No Save/publish snippet
| Delete snippet                              |               |   No Delete snippet
| View users ("users" appears in left nav)                                  |  ✅             | Users appears in left nav and can view
| Edit user                                   |               |  No Edit user available
| Add new user                                |               |   No Add new user available
| Delete user                                 |               | No delete user available 
| Add image                                   | ✅             | Add image is available/possible
| Edit image                                  | ✅             | Edit image available/possible
| Delete image I authored                                |     **skip**        |  
| Delete image others authored                               |        **skip**         |            
| Add document                                | ✅             | Add document available/possible
| Edit document                               | ✅             | Edit document available/possible
| Delete document I authored                             |       **skip**       | 
| Delete document others authored                            |        **skip**       |             |

**Comment by desigonz** [comment]
Thanks team for your joint QA effort! @ablangworthy27, yep, for snippets, save = publish.

@annieszot, looking down your list, looks like everything squares, except this one thing:
> "Delete content others authored" —Delete option not available on live content others authored but delete option is available on drafts others authored

Seems like editors can delete any drafts, whether authored by them or by others. @chiaberry, what size estimate would you give for making it so that editors can only delete their drafts and not others' drafts? If it would be a lot of work, let's make it a new issue, and for now not let editors delete any drafts.

**Comment by chiaberry** [comment]
@desigonz  ah. I would give it a 3 I think, I am thinking its also checking who "owns" the page as well as checking if they can delete. I am hoping that checking ownership is straightforward...although now that I'm saying it, there could be a scenario where you write a page, I make a draft, but you are the owner of the page so I can't delete it. Or vice versa, I write a page, you make a draft and i delete your draft....

sounds like I should make it so editors can't delete any draft for now?

**Comment by chiaberry** [comment]
actually I may need some guidance finding how to get the option to delete the draft, I am logged in as an editor and can't find how to delete drafts.

**Comment by annieszot** [comment]
Happy to walk-through @chiaberry ! Here's an example
![Screen Shot 2019-11-27 at 5 16 03 PM](https://user-images.githubusercontent.com/46934140/69765469-af4ba600-1139-11ea-9922-b9a64270ba6b.png)

**Comment by desigonz** [comment]
Also seeing it at this level on a draft:

![image](https://user-images.githubusercontent.com/5839508/69767881-e8891380-1143-11ea-8d83-836d84a3d0c7.png)


But yes, @chiaberry, I'll spin that into a new issue now. This issue is ready to go to staging woohoo!!

**Comment by desigonz** [comment]
New issues as #3510 and #3509. QA passed, let's merge this!
