### ISSUE TITLE
Input format for hours and minutes for daily labour request form is not working

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#3233]
**Describe the bug**

The input for daily labour form hours and minutes is not accepting time format. 

**URL**
https://cityofaustin.formstack.com/forms/ni_request_day_laborer

**To Reproduce**

1. Go to 'above URL'
2. Scroll down to  question 'How many hours do you expect each person to work, per day?'
3. Input the hours.minutes with out using slider
4. Input hours accepts 4.90

**Current behavior**
The hour input field accepts the invalid time format

**Expected behavior**

**Screenshots**
![Screen Shot 2019-10-22 at 12 09 41 PM](https://user-images.githubusercontent.com/52670306/67311407-218af400-f4c5-11e9-97cd-9b9f04341ecf.png)
Error Handling message:
![Screen Shot 2019-10-22 at 12 09 48 PM](https://user-images.githubusercontent.com/52670306/67311437-37001e00-f4c5-11e9-8726-cb1813cbb1dd.png)

**Device**

Desktop

**Browser**

Chrome

**Additional context**

**Comment by desigonz** [comment]
Ahh interesting. That's because the input is a number with a decimal, not hours and minutes. I think in this case, we would just choose to round the number of hours to not allow decimals.

**Comment by Jo-Dwyer** [comment]
Let's just round it. Does it make sense to update the text to reflect that this is an estimate and not a binding document?

**Comment by desigonz** [comment]
Updated to rounding the numbers. We already got copy approved and translated, so I say let's keep as-is and then see if we get any feedback on that later!
