### ISSUE TITLE
Focus indication for forms

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#3234]
**Describe the bug**
Formstack forms dont give any current input field  indication (where you are at) while navigating using keyboard

**URL**
https://cityofaustin.formstack.com/forms/ni_request_day_laborer

**To Reproduce**

1. Go to 'above URL'
2. Navigate the form using keyboard
3. Current input field indication where you are at 

**Current behavior**
Navigate using keyboard with out using mouse to fill the application for input fields blinker cursor gives current input field but for State ,Date time picker, checkbox and input fields there is no current input filed state.

**Expected behavior**
- [ ] Focus indication matches the focus indication we used on the OPO form: 
  - [ ] outline: `2px dotted #aeb0b5`
  - [ ] outline offset: `3px`

![image](https://user-images.githubusercontent.com/5839508/67710190-7f1fb480-f98d-11e9-9ae6-2e73518040a2.png)
![image](https://user-images.githubusercontent.com/5839508/67710267-a4142780-f98d-11e9-97f0-30b8134093ae.png)

**Screenshots**

**Device**

Desktop

**Browser**

Chrome

**Additional context**

**Comment by easherma** [comment]
I put this as a 5 because as a dev/user I'd expect Formstack to pass along focus behavior/styling unless its explicitly hidden rather than something we'd have to explicitly add. Otherwise every time there's a new theme its something we'd have to watch for. However, I haven't touched the theme stuff or styling, so @Niicck might have better insight.

**Comment by Niicck** [comment]
Assigning to @chasechenevert, per our conversation about adding new focus style requirements

**Comment by chasechenevert** [comment]
Requirements were added in the formstack styling issue: https://github.com/cityofaustin/techstack/issues/3288

Let's just reach parity here and mimic what we did on OPO for now.

- [ ] outline: 2px dotted #aeb0b5
- [ ] outline offset: 3px

**Comment by chasechenevert** [comment]
Not sure if I can close this, so just defaulting to tagging you @desigonz

**Comment by Niicck** [comment]
We could also close it out because its done: https://cityofaustin.formstack.com/forms/ni_single_page_test

**Comment by desigonz** [comment]
Beautiful!!! CLosing it.
