### ISSUE TITLE
Need 311 editorial convention

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3241]
**Describe the bug**
In contact snippets and in the header, we write `311`, but on the [measles page](https://janis-3053-test.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/learn-about-measles-in-austin/), it's written as `3-1-1`.

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/c6b74ca5-7a10-43f6-b662-872b1d951045)

- [x] Determine convention
- [x] Update the page accordingly
- [x] Decide if you want to add to style guide

**URL**

**To Reproduce**

**Current behavior**

**Expected behavior**

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by srigdon** [comment]
Got curious, did 10 minutes of research. Tl;dr: there's no consistent format even for 9-1-1, let alone the less well-known 3-1-1. So let's think about what results we want for residents. I think the most important factor is educating the public that this is a number you can call for non-emergency civic services. My vote is for hyphens. 

- AP says no hyphens, but that's 911, everybody understands it with or without hyphens. https://twitter.com/apstylebook/status/913034205625450496
- Wheras the National 9-1-1 association uses hyphens. https://www.nena.org/page/911overviewfacts
- But also! FCC doesn't put hyphens! https://www.fcc.gov/consumers/guides/what-you-need-know-about-text-911
- And then (with hyphens): https://en.wikipedia.org/wiki/3-1-1
- Also (no hyphens from the former Federal CIO): https://obamawhitehouse.archives.gov/blog/2010/03/03/open-311

**Comment by srigdon** [comment]
Very important! 

3-1-1 is a local number, and let's say you want to call Austin's 3-1-1 but you're not in the City of Austin. You'd have to call: 

(512) 974-2000
TTY: (512) 972-9848

<img width="274" alt="Screen Shot 2019-10-24 at 11 49 38 AM" src="https://user-images.githubusercontent.com/5445796/67507386-65f8ca00-f654-11e9-8215-af8ba4cd8647.png">

We need a sentence spelling that out in the contact card for 3-1-1.

**Comment by desigonz** [comment]
Ooh fascinating and thanks for pointing that out, @srigdon. Can you make a new feature issue for that? Seems like bigger than a simple content editorial style decision.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by srigdon** [comment]
@desigonz Sure thing, added #3250.
