### ISSUE TITLE
Write "how to use Joplin" guide for OPO staff

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#3242]
Apart from the organization-wide Official Documents content type style guide entry, OPO staff will need to know how to update all the other content types and need a [quick how-to guide](https://docs.google.com/document/d/1D6VV0B9cM5whkmcyf4SLDzkunPNpQ42WRsQaahoepnM/edit) for using Joplin for ongoing reference, apart from an in-person training. 

Ideally let's use this as a template to adapt and share every time we add a new user.

**Comment by Jo-Dwyer** [comment]
Writing this guide is covered by #4316.
