### ISSUE TITLE
"View live" on PR apps

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3243]
**Describe the bug**
"View live" and "live" links on Joplin PR apps opens Janis staging staging, rather than the associate Janis PR app. This makes it more difficult to QA.

![image](https://user-images.githubusercontent.com/5839508/67575133-829f0b80-f701-11e9-9620-9c3b13732a00.png)

**Acceptance criteria**
- [ ] Clicking "view live" from the content listing page opens a link at the corresponding Janis PR app
- [ ] Clicking "live" from an individual edit page opens a link at the corresponding Janis PR app 

**URL**

**To Reproduce**

**Current behavior**

**Expected behavior**

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by briaguya** [comment]
@desigonz this seems to be working in PR apps now, see: https://joplin-pr-brians-janis-testing.herokuapp.com/

not sure what/who fixed it but I'm moving it to QA for you.

**Comment by desigonz** [comment]
That's great! QA complete on this bug.

But tell me more about the purple background on this...will that get pushed to prod? Because we don't want that 😬

![image](https://user-images.githubusercontent.com/5839508/67862036-64655100-faef-11e9-8b4f-ae8902b0d1c9.png)
