### ISSUE TITLE
Guide icon on tiles/cards

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3244]
### As a resident, I want to differentiate guides from individuals pages when navigating the IA, so that I can understand what is a guide at a glance .

We have guides! You can currently navigate to a guide the same way you would find any other service or info page. We're implementing this change so that a user have a visual cue of what's a guide vs. an individual content page when nagivating the IA.

- [x] Through out the website, tiles/cards for guides use the guide icon rather than an arrow
- [x] Implementation matches mocks
  - [Desktop tile group topic collection view](https://xd.adobe.com/spec/e2cdc032-9eba-4140-5274-fc14f7254296-94fc/)
  - [Desktop tile group on service page](https://xd.adobe.com/spec/e2cdc032-9eba-4140-5274-fc14f7254296-94fc/screen/4ef7ef2a-05ec-468e-ab5d-2abe7e0b5b37/Template-Service-desktop-in-header-rail-1)
  - [Desktop single tile on an info page](https://xd.adobe.com/spec/e2cdc032-9eba-4140-5274-fc14f7254296-94fc/screen/467158b1-9f5d-415b-ab35-f168cb70cc98/Template-Information-desktop-in-header-rail-1)
  - [Mobile single tile on a service page](https://xd.adobe.com/spec/e2cdc032-9eba-4140-5274-fc14f7254296-94fc/screen/229face0-32b4-4e61-8f1f-bead36a282c9/Template-Service-mobile)
  - [Mobile tile group on a service page](https://xd.adobe.com/spec/e2cdc032-9eba-4140-5274-fc14f7254296-94fc/screen/12e84452-83f8-4f04-b93e-bfe5cfcad14c/Template-Service-mobile-1)
  - The icons would function the same on department and topic pages
- [ ] Unit tests: Will we need to write any unit tests for this content type or feature set?

**Comment by robbobfrh84** [comment]
@desigonz Ready for QA!
PR: https://github.com/cityofaustin/janis/pull/598
Deployed: https://janis-3244-guide-icon-tiles.netlify.com/

**Comment by desigonz** [comment]
@robbobfrh84 I want to test out how this displays on all pages—topic collections, topics, service pages, etc. Can you set up a Joplin branch that will work with this Janis branch so I can make those?

**Comment by desigonz** [comment]
Assigning @chasechenevert to verify the implementation of the icon [here](https://janis-3244-guide-icon-tiles.netlify.com/en/health-safety/healthcare-prevention/disease-prevention)

@robbobfrh84 that Joplin branch would still be helpful!

**Comment by chasechenevert** [comment]
Good to go by me. It looked slightly off-center, but I know that's because of the padding, and there's an issue for that here: https://github.com/cityofaustin/techstack/issues/3365

**Comment by robbobfrh84** [comment]
Hey @desigonz , I didn't realize that those other pages hadn't been built out yet. So, I'm adding that now. And, @chasechenevert, I'll look into adding the centering issue into this PR.

**Comment by robbobfrh84** [comment]
Hey @desigonz , here is the updated views of the icons. Let

To see Topic collection View: https://janis-3244-guide-icon-tiles.netlify.com/en/housing-utilities/recycling-trash-and-compost/
To see Top Service View: https://janis-3244-guide-icon-tiles.netlify.com/en/housing-utilities/recycling-trash-and-compost/compost-food-waste

LInk to Joplin link for adding/ testing more data: Joplin deployed link

**Comment by desigonz** [comment]
QA complete! Looks great. And toenail clippings now properly disposed.
