### ISSUE TITLE
"Page is a part of this guide" tiles

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3245]
### As a resident, I want to access a guide from relevant pages (including topics and individual pages) so that I can find all the information I need about a complex City process.

We have guides! You can currently navigate to a guide the same way you would find any other service or info page. From an individual page that's part of a guide, there is no indication that it belongs to a guide. We want to make it so.

(Note: We're covering the icons in #3244.)

- [x] If an information or service page is a part of a published guide, the individual service or information page displays tiles in header rail
- [x] Tile links to the beginning of the guide
- [ ] When a page belongs to only one guide, display as a single tile according to mocks
  - [ ] [Desktop single tile on an info page](https://xd.adobe.com/spec/e2cdc032-9eba-4140-5274-fc14f7254296-94fc/screen/467158b1-9f5d-415b-ab35-f168cb70cc98/Template-Information-desktop-in-header-rail-1)
  - [ ] [Mobile single tile on a service page](https://xd.adobe.com/spec/e2cdc032-9eba-4140-5274-fc14f7254296-94fc/screen/229face0-32b4-4e61-8f1f-bead36a282c9/Template-Service-mobile)
- [ ] Design matches mocks
  - [ ] [Desktop tile group on service page](https://xd.adobe.com/spec/e2cdc032-9eba-4140-5274-fc14f7254296-94fc/screen/4ef7ef2a-05ec-468e-ab5d-2abe7e0b5b37/Template-Service-desktop-in-header-rail-1)
- [ ] When a page belongs to multiple guides, display as a tile group according to mocks
  - [ ] [Mobile tile group on a service page](https://xd.adobe.com/spec/e2cdc032-9eba-4140-5274-fc14f7254296-94fc/screen/12e84452-83f8-4f04-b93e-bfe5cfcad14c/Template-Service-mobile-1)
- [x] Microcopy preceding tile/tile group
  - [x] on info pages:
    - [x] English: `This information is a part of:`
    - [x] Spanish: `Esta información es parte de:`
  - [x] on service pages:
    - [x] English: `This service is a part of:`
    - [x] Spanish: `Este servicio es parte de:`
- [ ] These tile groups appear in information and service page previews?? (dev, thoughts on this acceptance criteria? is this necessary?)
- [ ] ~~Unit tests: Will we need to write any unit tests for this content type or feature set?~~

**Comment by ablangworthy27** [comment]
@desigonz does it need to be one microcopy solution for both information and service pages?

**Comment by ablangworthy27** [comment]
If not, I like the following:

This information is part of:
This service is part of:

OR 

This information is part of a guide
This service is part of a guide

But it does bring up the question of using punctuation in microcopy. Should there be a period? @srigdon @Jo-Dwyer

**Comment by Jo-Dwyer** [comment]
I like 

> This information is part of:
> This service is part of:

Because it allows single or multiple guides to be listed and eliminates the need for punctuation

And then list any relevant guides beneath it. O don't know

**Comment by ablangworthy27** [comment]
Ok great, so no need to broach the subject of microcopy in the style guide just yet. @desigonz I believe this is ready for dev.

**Comment by desigonz** [comment]
great! thanks team.

**Comment by desigonz** [comment]
@chasechenevert We landed on microcopy for the tile groups on info and service pages; see updated acceptance criteria. Can you update the mocks when you have a chance?

**Comment by robbobfrh84** [comment]
Ok @desigonz! We're ready for review. 

Deployed link: cityofaustin/techstack#3245
Shortcut links...

Here is a Service page that is part of multiple guides: https://janis-3245-page-a-part.netlify.com/en/housing-utilities/recycling-trash-and-compost/recycling-reuse/changes-your-clocks-back/

Here is a Information Pages that is part of a single guide: https://janis-3245-page-a-part.netlify.com/en/housing-utilities/recycling-trash-and-compost/recycling-reuse/cool-places-of-interest-to-see-in-austin/

**Comment by desigonz** [comment]
@robbobfrh84 this is super exciting! I QA'd a few things but leaving the rest of the design for @chasechenevert to review. 

Question: can you share how these appear in previews? I think we can split this acceptance criteria into its own issue if need be, but I'm interested to see how it looks!

**Comment by robbobfrh84** [comment]
@desigonz I meant to mention that. Sorry, but I think that'll need to be a separate issue. But, hopefully we can use what we've done on janis here without too much hassle!

**Comment by desigonz** [comment]
Sounds good; we can make a separate issue, but do you have preview links vs live links I could use to write up the issue?

**Comment by robbobfrh84** [comment]
Here it is @desigonz 
-
Current Preview: https://janis.austintexas.io/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyMzY3
![Current Preview.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/bb1a3286-103e-4966-99d9-465040353549)
-
Current Live: https://janis-3245-page-a-part.netlify.com/en/housing-utilities/recycling-trash-and-compost/recycling-reuse/changes-your-clocks-back/
![Current Live.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/1f44a796-de12-4c11-9a2e-60e60afde87c)
- Note☝️: Check staging/prod in future. That's just the PR branch.

**Comment by desigonz** [comment]
Thanks!

(P.S. "If I could turn back time" is one of my favorite karaoke songs.)

**Comment by desigonz** [comment]
Made https://github.com/cityofaustin/techstack/issues/3571 to account for previews!

**Comment by chasechenevert** [comment]
This is good to go for MVP! 

The way our headings are currently set makes for a little awkwardness with responsive sizing, but I can live with it for now and make a new issue to address the H1s across the board.
![Screen Shot 2019-12-13 at 11 22 34 AM](https://user-images.githubusercontent.com/7027270/70819136-0fc61e80-1d9b-11ea-95d4-6dc3b4a3b66f.png)
