### ISSUE TITLE
Janis - set up testing framework

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#3248]
Before we write any unit tests, we need to set up a testing framework to run said tests

Jest Snapshot Testing
https://jestjs.io/docs/en/snapshot-testing

React Testing Tutorial
https://www.robinwieruch.de/react-testing-tutorial

Using React Storybook along with Jest
https://www.robinwieruch.de/visual-regression-testing-react-storybook

**Comment by easherma** [comment]
Do we want to explore/evaluate other alternatives or should we just go with this combo?
