### ISSUE TITLE
Agenda for Content Pin-up - 10-29-19 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#3249]
Last Content Pinup #3198
This meeting will incorporate #3223 Joplin user permissions MVP meeting (30 minutes)
https://austininnovation.slack.com/archives/C5PHTQRPD/p1571752780015500

@desigonz would like to discuss whether the pools and spas guide should actually be 3 guides.
@Jo-Dwyer wants to look at how to clearly display fine/fee information for _hundreds_ of infractions currently listed in a PDF so that residents know how much they need to pay.

🚦Approve agenda

~💻 Content sprint goals~
~Checking in on...anyone need help?~

~🏁 Roadmap~
~What's coming up~

👩‍🏭 Workshop
🤓Review assignments
🏖 OOO
🌵ETC
🏃Next Steps
@desigonz @ablangworthy27 to meet with Marni and break guide into issues

**Comment by Jo-Dwyer** [comment]
[Fines list] (http://www.austintexas.gov/sites/default/files/files/Municipal_Court/active_charge_list_10012019.pdf)
