### ISSUE TITLE
Sentence case on official documents page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3253]
I'm noticing that some of the official document titles for OPO use sentence case (per our style guide) while others are capitalized. Can you review style conventions with OPO publishers and standardized?

https://alpha.austin.gov/en/health-safety/police-oversight-2/police-feedback-and-records/official-complaint-and-discipline-documents

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/67cbaee0-1179-4243-b553-6b5570d2dec3)

**Comment by annieszot** [comment]
Sentence case updated on official documents - only for consistency. Naming conventiosn still being determined.
https://alpha.austin.gov/en/health-safety/police-oversight-2/police-feedback-and-records/official-complaint-and-discipline-documents/#1

Good to close?

**Comment by desigonz** [comment]
Awesome work! Closing this issue.
