### ISSUE TITLE
Form & form container entry for style guide

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3254]
We have a new content type: the form container! #3202 

Let's write a new entry of the style guide that explains how to use it, as well as how to build a form using Formstack.

Additional notes from @toribr on using a form container within a guide (not sure if this info should fit in the entry for the guide or the form container):

> When forms/form containers are linked to within a guide, we should not display the form because that would be unusable.
> 
> Instead, the guide will display the form title and description, if any, and a link to the form in a new tab.

**Comment by desigonz** [comment]
In sprint 49, @toribr spent some time identifying best practices for forms—we should incorporate these into the style guide entry: https://github.com/cityofaustin/techstack/issues/3735#issuecomment-575290184

**Comment by ablangworthy27** [comment]
@srigdon @Jo-Dwyer Can ya'll review this draft and let me know what you think?

https://docs.google.com/document/d/14nPmvuzxmkkTLZIs6andYByEyABMjUroy_bnma4TeAE/edit#

**Comment by srigdon** [comment]
Reviewed, looks good! We just need to figure out the conundrum of titling Service pages and the Form container pages they link to. @desigonz can you weigh in?

**Comment by desigonz** [comment]
I added some thoughts on the doc. I encourage y'all just to pick a direction for now and we'll see how it works, and any SEO things that was technical implications, let's add to the backlog under the epic #2686.

**Comment by desigonz** [comment]
- [ ] @ablangworthy27 when this is done and published, create an issue for dev. Can be modeled off of this: https://github.com/cityofaustin/techstack/issues/3995
