### ISSUE TITLE
document your content process 

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#3255]
Looping in @srigdon @Jo-Dwyer @annieszot to remind them to do some casual documentation/note taking of their experiences with the following:

-kickoff
-using content inventory (this might be too new for anyone to have anything useful)
-SDL engagements
-finding stakeholders
-drafting/reviewing

I will then synthesize the info and make official.

**Comment by Jo-Dwyer** [comment]
[Document for adding to/ reference] (https://docs.google.com/document/d/1TafEQ4mLJrETytrYFur8t7QonvP7cIoAJpqs5pK6_o4/edit)

**Comment by desigonz** [comment]
For now, let's focus on these processes:
- Drafting and reviewing
- Finding the right person with the right information to keep your content moving forward
