### ISSUE TITLE
Make contact with Pools & Spas stakeholders

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#3256]
I need to get the following contacts and schedule meetings with them

- [ ] SME
- [ ] SPOC

By making contact with these people, I'll be able to establish norms for content review.

**Comment by desigonz** [comment]
Did your chat with @ChristopherLuedtke give you insights into who these folks are? And I wonder if your SPOC would be Anna Lassman in Public Health...ccing @Jo-Dwyer in case she has thoughts.

**Comment by desigonz** [comment]
Also tracking all these things could potentially be a coordinator role :)
