### ISSUE TITLE
Write "citizens guide to appeals" as a guide

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3260]
As a defendant in a municipal court criminal case, I want to know the steps and timelines for filing an appeal so that I can potentially have my guilty verdict overturned.

The process for filing an appeal has many steps, documents, and deadlines which might benefit from being assembled as a guide content type.

Currently the [guide is a PDF](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Appeal_Instructions.pdf).

I'll need help scoping this project @desigonz ...maybe @annieszot and @srigdon can lend insights, moral support?

**Comment by annieszot** [comment]
Of course @Jo-Dwyer ! Want this as a goal (scope this guide) as one of the team's sprint goals next sprint (43)?

**Comment by Jo-Dwyer** [comment]
@annieszot I think scoping could happen in 43, but it may need to wait til 44 @desigonz what do you think?

**Comment by desigonz** [comment]
@Jo-Dwyer @annieszot Yeah first let's focus on top-priority content and content that's easiest to churn out (and especially the nexus of the two)!
