### ISSUE TITLE
Departments page: mega list

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3263]
PR app: https://janis-3263-depts-page.netlify.com/en/departments/

<img width="1319" alt="Screen Shot 2019-10-28 at 2 53 57 PM" src="https://user-images.githubusercontent.com/6384156/67712910-dd9b6180-f992-11e9-9400-1b05720b7848.png">

it does wonky stuff like this right now.

we should confirm with design which part of the style guide we're supposed to be following with the departments page

**Acceptance criteria**
- [ ] Match styling of tiles on topic pages for all breakpoints

**Comment by desigonz** [comment]
Assigning to @chasechenevert to add acceptance criteria/mocks.

**Comment by desigonz** [comment]
This will require a new approach (aka not those same tiles). @chasechenevert will be investigating this and developing mocks.

**Comment by chasechenevert** [comment]
_From https://github.com/cityofaustin/techstack/issues/3347 pin-up notes_
 
Presented variations of lists with alphabetical groupings, and SD 2023 groupings, but this level of effort is currently beyond scope, and we don’t yet have a lot of departments to populate this page. 
 
**Future state ideas:**
- Display tags with departments to enable filtering and toggling
- Show relationships between departments, how government works together
- Local search and global search on the same page could be confusing 
 
**Next steps:** 
- [ ] Define the grid layout
- [ ] Add specs and criteria to github issue #3263

**Comment by chasechenevert** [comment]
The way these are laying out here is as I think it should be: https://janis-3244-guide-icon-tiles.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/

**Comment by desigonz** [comment]
@desigonz to update acceptance criteria

**Comment by desigonz** [comment]
I'm going to say QA passed for this one. If design wants to improve/change the design for both topic page card layout and department page going forward, we'll submit new issues.
