### ISSUE TITLE
Ongoing Spanish translation for OPO

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#3266]
Translation needs for OPO are pretty straightforward and inexpensive, as most of what needs updating for the next quarter or two will primarily be entries on the Official Documents page. Those continue to be published one or two at a time, maybe once a week on average. 

Tasks: 

- [ ] Talk to CPIO about policy and budgeting for language translations on austin.gov. 
- [x] Document decisions about how OPO handles translations going forward. Track: what's been sent for translation, what's been translated, what's been published in Spanish on the website.

**Comment by desigonz** [comment]
Per discussions with Marni and OPO, we'll be handling translations for now. Closing this issue, we'll open up new issues for translation budgeting and policies as they arise.
