### ISSUE TITLE
Research municipal court community service documents and forms 

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3270]
Community service can substitute for fines or other penalties in the municiapl court. There are five documents or forms currently in PDF form. To transition this content into a new content type, I need to know:
- [ ] Why are these documents updated so frequently (monthly)? What information changes on them? What stays the same? Who updates the information?
[Community Service (Adult) Austin Locations](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/CommunityService_RosterAdults_10212019.pdf)
[Community Service (Juvenile) Austin Locations](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Community_Service_Roster_for_Juvenile_10_19_17.pdf)
- [ ] Can these forms be broken up into information pages and then a form? Could they be one form that has a pull down for juvenile vs adult? can the roster and timesheet be submitted as a digital form?
[Community Service Time Sheet, Rules & Roster - Adult](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Community_Service_Timesheet__Adult.pdf)
[Community Service Time Sheet, Rules & Roster – Juvenile](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Community_Service_Timesheet_Juvenile.pdf)
- [ ] Can providers submit this form online via formstack? What other information do providers ned to know in order to become a provider site? Is municourt looking for more providers?
[Community Service Provider Application Agreement](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Community_Service_Provider_Application_Agreement.pdf)

**Comment by desigonz** [comment]
We have a forms content type! Do you mean we would transition these to forms?

**Comment by Jo-Dwyer** [comment]
Oh! To be clear I mean a new label for issues called "Content Type: Form".

**Comment by desigonz** [comment]
We have a label "Content type: form container," which refers to the content type in Joplin. Does that work?

**Comment by Jo-Dwyer** [comment]
FYI @ADoAboutThings Here are some of the q's I have for Kim Wingard re: community service.
