### ISSUE TITLE
Research citizen complaints for a new service page

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3271]
Citizen complaints are one way to begun formal court preceedings in civil cases. There are three types of complaints with very similar "requirements" information followed by specific fields per the subject matter. All three require a notary and judge's signature.
- [ ] Are these documents candidates for formstack? Is the presiding judge open to using e-signatures for these documents? 
[Citizen Complaint Form – Noisy Animal](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/AFFAnimalViolations03_2016_F.PDF)
[Citizen Complaint - Code/Ordinance Violation (except noisy animal)](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/AFFNonTrafficOtherViolations03_2016_F.PDF)
[Citizen Complaint - Traffic/Insurance Violations](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/AFFTrafficInsuranceViolations03_2016_F.PDF)

**Comment by desigonz** [comment]
Wondering...why "citizen"?

**Comment by Jo-Dwyer** [comment]
Use of the word citizen here is a policy issue and will be passed on to the Policy Lab. PDFs are being used as-is and are carried forward in issue #3999.
