### ISSUE TITLE
Create an information request service page with form

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3273]
Information requests are handled differently by municipal court than for other departments in the city. All requests (PIRs and JIRs) are handled by the court itself (not by city hall) but only some (PIRs) are reported to city hall.
The form is currently a PDF but is only informational and requires no signatures at all. 

- [x] Could this form be a formstack?
- [x] Can workflows be designated based on the JIR/PIR definitions that send a report of PIRs to city hall?
[Records/Information Request] (http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Fillable_Records_Request_Form_Approved_3_2019.pdf)

**Comment by Jo-Dwyer** [comment]
The answer seems to be "yes": the PIR/JIR forms can be transitioned to Formstack, and we are working with @ADoAboutThings to consider how this might fit into a forms workshop.

**Comment by Jo-Dwyer** [comment]
- [ ] @ADoAboutThings will get formstack info from Soolin
- [ ] @Jo-Dwyer to transition current content to the formstack platform
- [ ] share with Amy Schillerstrom for fact checking
- [ ] share with content for review
- [ ] share with Amy for manager review
- [ ] publish

**Comment by Jo-Dwyer** [comment]
@desigonz can I get formstack access to create the first draft?

**Comment by Jo-Dwyer** [comment]
Integrated edits from Amy.
- [ ] review design/UX by @toribr 
- [ ] content review by @ablangworthy27 

[Request for judicial records form](https://cityofaustin.formstack.com/forms/request_for_judicial_records)

**Comment by Jo-Dwyer** [comment]
@toribr can you look at this form?

**Comment by ablangworthy27** [comment]
@Jo-Dwyer

**Description:**
"in accordance to" I think should be "in accordance with"

**Are you requesting information about a specific case or general information about municipal court cases** 
-needs a question mark.
-when I select first option, the boxes for putting in the defendant's age and relationship to the defendant are a different color from the rest of the boxes.
-the default value of zero for the defendant's age is weird.
-the logic-based questions about the defendant are not required but perhaps they should be?  I'm assuming at the very least they will need a name or case number to find the correct case.

**The Court will contact you about the cost of requested documents within two working days. Copies will only be released after fees are paid.**
-It might be good to indicate how they will be contacting. Is it a phone call or email?

**The City of Austin is committed to compliance with the American with Disabilities Act. Reasonable modifications and equal access to communications will be provided upon request.**
-Is this having to do with the phone call or email followup? Not saying this isn't important but there needs to be more context. Maybe a more detailed submission message about next steps could include this?

**Comment by toribr** [comment]
@Jo-Dwyer @desigonz 

This question: 
Are you requesting information about a specific case or general information about municipal court cases (Required)
<radio>...specific...
<radio> general informaion...

Under the first selection, there are about 10 fields. Am I to understand that all 10 are required?

For this: "defendant's age at time of violation" - the previous two fields ask the date of birth and the date of violation, which means that if those fields are required, the date of violation is redundant, ie, the system can do the math.

Lastly, "Case number or violation type". Is this information going to be easy for me to find? How do I know where it is? If I don't have a case number, how would I know what sort of "violation" type it is? This field seems like it might cause a lot of friction. Do we need to add any instructional text like, "you can find your case number on x document in the top left corner."

Overall, there are some strange styling issues going on, ie, black text and grey text, but I can't tell why they are rendering differently.

**Comment by desigonz** [comment]
A few more notes:

- [ ] Remove the title—we don't use the titles when they're in the form container on alpha.gov, because it creates redundant titles. (@toribr, we might want to create a new issue and work with @chasechenevert/dev team to think this through. The only instance when someone would land on this version of the form is if the form fails due to a privacy blocker.)
- [ ] If you select "information about a specific case": 
  - [ ] Should anything in this section be required?
  - [ ] Having the default birthdate for a defendant be today is weird. We might get a lot of wrong birthdays this way.
  - [ ] For "Date of violation," I can choose a future date. That's a bit weird. Although not sure if Formstack allows you to only limit to past dates from whatever today is. Maybe @ablangworthy27 can help you with that one.
  - [ ] I can't fill out these questions. They also happen to be the questions that are grayed out. @Jo-Dwyer, is that a setting on your side?
![image](https://user-images.githubusercontent.com/5839508/74757549-c16e4980-523b-11ea-9259-735eac1482a7.png)
- [ ] If you select "general information about municipal court cases", is the audio recording for a trial question still relevant? Kind of doesn't make sense to me...
![image](https://user-images.githubusercontent.com/5839508/74758531-152d6280-523d-11ea-8e9b-14d0496d3768.png)
- [ ] Write a custom confirmation message that sets expectations about when they're hear back, is friendly, etc
![image](https://user-images.githubusercontent.com/5839508/74758374-e0211000-523c-11ea-83ef-082433957527.png)

**Comment by Jo-Dwyer** [comment]
@ablangworthy27 
Description:
- [x] "in accordance to" I think should be "in accordance with"

Are you requesting information about a specific case or general information about municipal court cases
- [x] needs a question mark.
- [ ] when I select first option, the boxes for putting in the defendant's age and relationship to the defendant are a different color from the rest of the boxes. __These were "read only"__
- [x] the default value of zero for the defendant's age is weird.
- [x] the logic-based questions about the defendant are not required but perhaps they should be? I'm assuming at the very least they will need a name or case number to find the correct case. ****They aren't but the more information is included, the more easily staff can find your record. I've added text to explain this.**

The Court will contact you about the cost of requested documents within two working days. Copies will only be released after fees are paid.
- [x] It might be good to indicate how they will be contacting. Is it a phone call or email? **Do you know if it's possible to have a logic requiring at least one field to be filled out? The way that court staff contacts the requestor is based on what method of contact they select. There should be at least one way to contact them, but it doesn't matter which.**

The City of Austin is committed to compliance with the American with Disabilities Act. Reasonable modifications and equal access to communications will be provided upon request.
- [x] Is this having to do with the phone call or email followup? Not saying this isn't important but there needs to be more context. Maybe a more detailed submission message about next steps could include this? **II don't have enough information about how modifications are made for this particular document. This text is the standard ADA text that's included on many CoA pages. I'd like to leave it as is and look into the policy around the blurb and how we could rewrite this.**

@toribr 
This question:
- [x] Are you requesting information about a specific case or general information about municipal court cases (Required)
...specific...
general information...

- [x ] Under the first selection, there are about 10 fields. Am I to understand that all 10 are required? **They aren't but the more information is included, the more easily staff can find your record. I've added text to explain this.**

- [x] For this: "defendant's age at time of violation" - the previous two fields ask the date of birth and the date of violation, which means that if those fields are required, the date of violation is redundant, ie, the system can do the math. The fields are already set up to do this math; I have now hidden the "age at time of violation" field so it's only visible to the backend user. 

- [x] Lastly, "Case number or violation type". Is this information going to be easy for me to find? How do I know where it is? If I don't have a case number, how would I know what sort of "violation" type it is? This field seems like it might cause a lot of friction. Do we need to add any instructional text like, "you can find your case number on x document in the top left corner." **I added helper text to clarify this.**

- [x] Overall, there are some strange styling issues going on, ie, black text and grey text, but I can't tell why they are rendering differently. **Yes. This is true and I don't know why. I've made some changes to editable fields. Maybe this has made a differene in what you're seeing.**

@desigonz 
A few more notes:

- [x]  Remove the title—we don't use the titles when they're in the form container on alpha.gov, because it creates redundant titles. (@toribr, we might want to create a new issue and work with @chasechenevert /dev team to think this through. The only instance when someone would land on this version of the form is if the form fails due to a privacy blocker.)
- [x]  If you select "information about a specific case":
 Should anything in this section be required? **The request can be made using as little or as much information as the person has.**
- [x]  Having the default birthdate for a defendant be today is weird. We might get a lot of wrong birthdays this way. **No default date on this or the violation.**
- [x]  For "Date of violation," I can choose a future date. That's a bit weird. Although not sure if Formstack allows you to only limit to past dates from whatever today is. Maybe @ablangworthy27 can help you with that one. **I'm not seeing the capability to limit to past dates only.**
- [x]  I can't fill out these questions. They also happen to be the questions that are grayed out. @Jo-Dwyer, is that a setting on your side? **The only grayed out fields should have been the dates, and I've hidden the age at violation field. I'm not having trouble filling out other fields. It shouldn't be a problem now.**

**Comment by toribr** [comment]
@Jo-Dwyer FYI, I seem to recall we've previously established that formstack isn't smart enough to prevent future dates. Probably Nick could answer for sure. This is a super irritating issue with all date pickers. We had the same issue with the OPO form (but used a different library so it's of no use to us now.)

The instructional text is tiny. That style should be accounted for with our theme, so not sure what's happening there.

What happens if the resident does not provide enough information?

**Comment by Jo-Dwyer** [comment]
@toribr the court staff are currently equipped (and in the habit) to follow up by phone or email if they need more info to look up the court case. 

re: size The style and size of the instructional text is controlled within the formstack text editor, so I bumped it up to size 18 where possible. It is easier to read, but it's not clear at the outset that I need to do this as an editor in formstack. @desigonz  Is this something I should bring up to Soolin?

**Comment by desigonz** [comment]
Made issue #4032 for the text style.

**Comment by desigonz** [comment]
@srigdon will review copy, then ready to go live.

**Comment by srigdon** [comment]
Reviewed, looks good to go! The only edits I have are for the form, not the form container, and I noted those edits in [this page's Notes tab](https://joplin.herokuapp.com/admin/pages/169/edit/#tab-notes). Will edit when I get Formstack access. @InaraFernandez if you want to pick up implementing those edits before I do, go for it, but no worries if not. Putting all Formstack edits for this round of Municourt pages in #4690 so we can close this one.
