### ISSUE TITLE
Research outlier municourt forms and documents

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3278]
After sorting existing forms and documetns by subject, process or content type I am left with these outliers. 

I need to know:
- [ ] what process or situation these forms and documents might be used in
- [ ] who the main user is
- [ ] could the form be made into a digital form
- [ ] could the document be made into its own information or service page

...in order to
- [ ] decide what content type each requires
- [ ] create resulting issues.

[Surety Bond Form](http://austintexas.gov/sites/default/files/files/Municipal_Court/Surety_Bond_Form.pdf)
[Personal Bond Form](http://austintexas.gov/sites/default/files/files/Municipal_Court/Personal_Bond_Form.pdf)
[Affidavit - Camera Red Light Non-Liability](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Affidavit_-_Camera_Red_Light_Non-Liability.pdf)
[Affidavit & Motion to Dismiss – Disabled Parking](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/motionfordismissalparking.pdf)
[Affidavit - Parking Non-Liability](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Affidavit_-_Parking_Non-Liability.pdf)
[Cash Appeal Bond](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Cash_Appeal_Bond.pdf)
[Plea form-English](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Plea_Form_English.pdf)
[Motion Form - Adult](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Motion_Generic_Sharepoint.pdf)
[Expunction Information - Juvenile](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Expunctions_Juveniles_and_Minors.pdf)
[Expunction Information - Adult](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Expunction_Petition.pdf)
[Opt Out Letter](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Opt_Out_Form_03_2019.pdf)
[Attorney Appearance Docket Waiver Request Form](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Attorney_Appearance_Docket_Waiver_Sharepoint.pdf)
[Motion Form - Juvenile](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Motion_Juvenile_Sharepoint.pdf)

**Comment by gabrielaperezdelaosa** [comment]
#4628 was created to address bonds:
Surety Bond Form
Personal Bond Form
Cash Appeal Bond

#4133 addresses forms to prove you were not liable
Affidavit - Camera Red Light Non-Liability
Affidavit & Motion to Dismiss – Disabled Parking
Affidavit - Parking Non-Liability

#4629 is a lawyer filing cabinet page that contains
Plea form-English
Motion Form - Adult
Attorney Appearance Docket Waiver Request Form
Motion Form - Juvenile

#4630 for Get a record expunged
Expunction Information - Juvenile
Expunction Information - Adult

Opt Out Letter addressed in #4567
