### ISSUE TITLE
<FormattedMessage> not working on Samsung Internet browser

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#328]
`<FormattedMessage>` seems not to be doing a good job on old browsers.

I saw this happened somewhere else but I didn't take a screenshot. I thought adding the polyfill for React-Intl would fix this.

![screen shot 2018-04-25 at 11 56 17 pm](https://user-images.githubusercontent.com/5697474/39286801-79682fe0-48e5-11e8-9532-dab14859cb0b.png)

Aha! Link: https://desi1.aha.io/features/RT-311

**Comment by easherma** [comment]
Obsolete
