### ISSUE TITLE
Joplin content keywords

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#3281]
### As a content writer I want to add keywords to content so that people can search for it easier.

**Is your feature request related to a problem? Please describe.**
Joplin content needs keywords. This is a pre-requisite to having meaningful search that actually works.

**Describe the solution you'd like**
I don't know what this looks like. We should get started on it.

**Additional context**
Content team wants this feature too.

**Comment by easherma** [comment]
https://docs.wagtail.io/en/v2.6.3/topics/search/index.html

Setting up the Postgres search backend makes the most sense for us

**Comment by toribr** [comment]
@gabrielaperezdelaosa good find! closing this sucker!
