### ISSUE TITLE
Make issue for Municourt approvals and internal reviews 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#3289]
- [ ] Annie to talk with @Jo-Dwyer  about how she wants to layout approvals and internal review issues

**Comment by Jo-Dwyer** [comment]
@annieszot I made a combined issue #3290  with parking tickets and dept page reviews in it, but I want to chat with you and clean it up as we see fit.

**Comment by desigonz** [comment]
I think this is taken care of with #3326
