### ISSUE TITLE
Iterate on animal center foster process page

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#329]
see issue #280
see issue #80 and related issues around jumping people from atx to alpha

**Comment by cthibaultatx** [comment]
![alpha_l_foster-1](https://user-images.githubusercontent.com/20911665/40189808-ed5eca2e-59c2-11e8-8f73-3b10b4d19998.png)

link to sketch file in google drive: https://drive.google.com/open?id=1nJePAA3EI1APmdFK8zcBjh4OuajyjElG

**Comment by cthibaultatx** [comment]
@ifsimicoded @mateoclarke we'll review in 5/22 design-dev review to make any tweaks, break down into smaller chunks, and task build

**Comment by amenity** [comment]
@courtneyjacinic take a look

**Comment by amenity** [comment]
Covered by #789
