### ISSUE TITLE
Translate labels on Formstack forms

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3293]
**Describe the bug**
I made a Spanish version of a Formstack form and even set the language to Spanish (under "Settings"). But the submit button and "required" still appear in English

**Acceptance criteria**
- [ ] "required" translates
- [x] submit button translates

![image](https://user-images.githubusercontent.com/5839508/67813121-c467e300-fa6e-11e9-8a17-9cc7b6fcea48.png)
![image](https://user-images.githubusercontent.com/5839508/67813172-dea1c100-fa6e-11e9-9941-70644f59ab45.png)

**URL**
https://cityofaustin.formstack.com/forms/solicite_un_jornalero

**To Reproduce**

**Current behavior**

**Expected behavior**

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by desigonz** [comment]
From Soolin:

> I went in and created a new copy of the 'Theme' that was being used on the 'Request a Day laborer ' Spanish form and edited the HTML code in order for the required field to say 'requerido' (double checked that with Mireya who speaks Spanish). It now works!!

Yay so we can change it in the theme! Does that mean we need an English and a Spanish theme? Or just one?

But two things we still need to update:
- [ ] Introduced a regression with a big ol' asterisk (need to remove that)
- [ ] Change "Requerido" to "Obligatoria"—that's the language we got from the translators and have been using it on the OPO form, so let's stay consistent.
![image](https://user-images.githubusercontent.com/5839508/67898647-b24d7980-fb2e-11e9-9c21-c72d3fb53a76.png)

**Comment by Niicck** [comment]
Alright. I got it so that we can use the same theme for both English and Spanish. And it'll magically translate the "Required" label between languages hooray.

PR: https://github.com/cityofaustin/formstack-alpha-theme/pull/1
Deployed Link: https://janis-3288-content-padding.netlify.com/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyMTM5?CMS_API=https://joplin-pr-nick-testing-machine.herokuapp.com/api/graphql

**Comment by desigonz** [comment]
😍 love it! QA complete
