### ISSUE TITLE
Location page - MVP API

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3296]
- When building a dept/service page, the api can returns all relevant location information
   - Bonus (not mvp): only returns link info if we're getting a bunch, return full info if we're getting one
 - When building a location page, the api returns all relevant services/departments

**Comment by desigonz** [comment]
Make Joplin and Janis sides of the content type fit together and work. 
- [ ] Builds at the right URL
- [ ] Previews work

**Comment by Niicck** [comment]
from https://github.com/cityofaustin/techstack/issues/3297
- [ ]  In Joplin, entering phone number labels are supposed to be optional. You might have already done this, but I would expect that if there is no phone number label entered, then on Janis, only the phone number appears, without label
- [ ] Within hours, "Closed" should translate to "Cerrado"
- [ ] Within hours, "Noon" should translate to "mediodía" (I'm noticing this isn't happening currently in [contacts](https://alpha.austin.gov/es/health-safety/healthcare-prevention/disease-prevention/get-immunized) :( Is this something you'd fix across the board, or only fix for this content type, and then we should create a new issue to fix elsewhere?)

**Comment by desigonz** [comment]
made #3535 to replace this
