### ISSUE TITLE
Limit "Make top-level link" to service and info pages

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3313]
We have the ability to make pages top-level links! This enables us to make a "global" page we can add to the footer. Yay!

But we don't need this for all content types. 

**Acceptance criteria**
"Make top level links" appears on these content types:
- [x] service
- [x] info

"Make top level links" DOES NOT appear on these content types:
- [x] department
- [x] official docs
- [x] guide
- [x] topic
- [x] topic collection
- [x] form container

![image](https://user-images.githubusercontent.com/5839508/67878777-e2365600-fb09-11e9-8c66-756b63f75052.png)

**Comment by easherma** [comment]
We should clarify the naming here, easy to mix up these 'top level link' checkbox with 'top links' on a topic page. 

Also there is almost certainly a better way to designate these, but that might be more of a Joplin 3.0 thing.

**Comment by ablangworthy27** [comment]
I can attest to the accuracy of Eric's concern over the checkbox language.  I had trouble with this while publishing the new OPO page.

**Comment by easherma** [comment]
In the long run, doesn't it just make more sense to have a 'global' settings section where you choose pages there rather than have a checkbox on every single/most page models despite the fact that just a very small few will be 'global' pages?

**Comment by chiaberry** [comment]
https://joplin-pr-3313-limit-top-level.herokuapp.com/admin/pages/search/ for QA

**Comment by desigonz** [comment]
Thanks @chiaberry! Per acceptance criteria, the "make top-level page" text and checkbox should appear on info and service pages, but I'm not seeing them fully on either.

Service page—only see the text, not the checkbox:
![image](https://user-images.githubusercontent.com/5839508/71633732-a12af280-2bdb-11ea-8eeb-d299084fbb5e.png)

Info page—not seeing it at all:
![image](https://user-images.githubusercontent.com/5839508/71633741-aab45a80-2bdb-11ea-8cac-47416425ddf4.png)

**Comment by chiaberry** [comment]
@desigonz sorry about that Desi, it should be working now

**Comment by desigonz** [comment]
@chiaberry Looks great—QA done!
