### ISSUE TITLE
Revise and publish Municourt dept page

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3326]
We already have feedback on Municourt! To get this page published I need to:
- [x] make a few changes to wording
- [x] review by content strategist
- [x] review by @srigdon 
- [x] send to Amy at APH for approval
- [x] send to translation
- [x] publish

**Comment by Jo-Dwyer** [comment]
Ready for internal review: [Municipal court department page](https://cityofaustin.sharepoint.com/:w:/r/sites/CTM/TEAMSITES/ODD/alphaaustingov%20Content/Workflows/Departments/Municipal%20Court/Municipal%20Court%20Department%20Page.docx?d=w520b156f697541cfb6a8932bb38f60b6&csf=1&e=SU440D)

Question for @annieszot @srigdon @ablangworthy27: Municipal court has a director (Court Clerk Mary Jane Grubb) and a presiding judge (Sherry Statman). They are both shown on the [current Municipal Court page](http://www.austintexas.gov/department/municipal-court). 

Today I'll learn more about how the roles work together, but for now I want to know if we can put two people on the dept page, if that is as overcomplicated as I think it is, and what criteria we might use to decide who goes on the dept page.

**Comment by ablangworthy27** [comment]
@Jo-Dwyer I don't think it is a problem to include both. Since the title of that section is "Leadership" it doesn't bother me.

**Comment by Jo-Dwyer** [comment]
- [ ] waiting bio for Mary Jane Grubb from Amy Schillerstrom
- [ ] send page to @ablangworthy27 for review

Should have the bio by Mon Nov 4 or Tues Nov 5.

**Comment by Jo-Dwyer** [comment]
Waiting on bio from Municourt for the department page.

**Comment by Jo-Dwyer** [comment]
Bio received; can @ablangworthy27 or @annieszot please review?

[Municipal Court Department Page] (https://cityofaustin.sharepoint.com/:w:/r/sites/CTM/TEAMSITES/ODD/alphaaustingov%20Content/Workflows/Departments/Municipal%20Court/Municipal%20Court%20Department%20Page.docx?d=w520b156f697541cfb6a8932bb38f60b6&csf=1&e=uJisc0)

**Comment by ablangworthy27** [comment]
I can do it.

**Comment by ablangworthy27** [comment]
@Jo-Dwyer I completed my review. You should be able to track the changes in Word (not sharepoint). You probably already knew this, but I just figured it out!  Let me know if you have any questions.

**Comment by Jo-Dwyer** [comment]
Thanks for the editorial @ablangworthy27. I'll propose written-out degrees for the style guide. Accepted most changes and will review with Amy to make the bio on Mary Jane more resident.

Amy has the newest revision.

**Comment by Jo-Dwyer** [comment]
Drafted in Joplin, need:
- [ ] another set of eyes for review by a content person @annieszot or @ablangworthy27 
- [ ] director photos unbroken #3484
- [ ] approval by municourt
- [ ] publish

**Comment by annieszot** [comment]
Copy @Jo-Dwyer ! Will take a look before content retreat tomorrow.

**Comment by Jo-Dwyer** [comment]
Thanks @annieszot! The link might be helpful! [draft of Municourt dept page](https://alpha.austin.gov/en/preview/department/UGFnZVJldmlzaW9uTm9kZToyMzY4) 
Don't mind the broken images, please!

**Comment by annieszot** [comment]
Review completed @Jo-Dwyer Suggested edits added in Sharepoint - apologies for the suggested edits being in the form of "comments." Had trouble "tracking changes" because opening the Word doc was read-only. 

Suggested edits are regarding the bulleted list (last three bullets, sub-bullets), and some minor tweaking of Mary Jane Grubbs bio. Please let me know if you have questions :)

**Comment by Jo-Dwyer** [comment]
@srigdon can I get final approval on the [Municourt dept page](https://alpha.austin.gov/en/preview/department/UGFnZVJldmlzaW9uTm9kZToyNDMy) before I send it for translation?

**Comment by ablangworthy27** [comment]
@Jo-Dwyer below I copy/pasted the bios and my edits are in bold/italics. They are very minimal.

Judge Statman was first appointed to the bench in 2006; she was named presiding judge for the Austin Municipal Court in 2014. Her service includes memberships in the State Bar of Texas' Lawyer Assistance Program Committee, Travis County Women Lawyers' Association, Inns of Court, Austin Young Lawyers Association, **_and the_** Texas Municipal Courts Association. She also provides pro bono help to low-income residents, people in family law, and Social Security disability cases.

Mary Jane Grubb is an East Texas native and has worked in Texas Municipal Courts for almost 25 years with nearly 15 years of court administration and management experience. She joined the City of Austin as the Clerk of the Austin Municipal Court in 2015. She holds a bachelor of science in business administration, is a Level III Certified Municipal Court Clerk, and **_is_** a member of **_the_** Texas Court Clerks Association and **_the_** Texas Municipal Courts Association.

**Comment by srigdon** [comment]
@Jo-Dwyer @ablangworthy27 Good edits, agree on all of them. With those incorporated, it looks good to publish to me.

**Comment by Jo-Dwyer** [comment]
GREAT! I now publish.
