### ISSUE TITLE
Padding for topic card on topic collection page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3328]
**Describe the bug**
Padding seems funny at this breakpoint; larger breakpoints look normal.
![image](https://user-images.githubusercontent.com/5839508/67892167-22093780-fb22-11e9-829f-a98e393bbe52.png)

**URL**
https://alpha.austin.gov/en/health-safety/disaster-safety-relief/

**To Reproduce**

**Current behavior**

**Expected behavior**

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by desigonz** [comment]
Assigning to @chasechenevert to investigate.

**Comment by chasechenevert** [comment]
I think i've figured it out~ Changing left and right margins from `auto` to `0` seems to do the trick.

```
margin-left: 0;
margin-right: 0;
```
## Before
**Row of 2**
<img width="1053" alt="Screen Shot 2019-11-13 at 10 35 08 AM" src="https://user-images.githubusercontent.com/7027270/68784249-e3837a80-0601-11ea-9686-12bed8d31d76.png">
**Vertical list**
<img width="709" alt="Screen Shot 2019-11-13 at 10 43 04 AM" src="https://user-images.githubusercontent.com/7027270/68784588-69072a80-0602-11ea-883e-14421afade58.png">



## After
**Row of 2**
<img width="1013" alt="Screen Shot 2019-11-13 at 10 36 44 AM" src="https://user-images.githubusercontent.com/7027270/68784479-35c49b80-0602-11ea-8080-eec16db57016.png">
**Vertical list**
<img width="746" alt="Screen Shot 2019-11-13 at 10 37 10 AM" src="https://user-images.githubusercontent.com/7027270/68784489-38bf8c00-0602-11ea-8534-8a0a5fa7c8e0.png">

**Comment by chasechenevert** [comment]
Ready for ya, @desigonz

**Comment by desigonz** [comment]
Great! Reassigning this to dev. 

**Acceptance criteria**
- [ ] Change  left and right margins from `auto` to `0`
`margin-left: 0;
margin-right: 0;`
- [ ] To test: At breakpoints between 972pixel width and mobile views, margin is consistent

**Comment by chiaberry** [comment]
deployed link: https://janis-3328-padding-topic-card.netlify.com/en/health-safety/disaster-safety-relief/

**Comment by desigonz** [comment]
Looks great! QA done.
