### ISSUE TITLE
Can't see a related contact on an info page

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3331]
PR: https://github.com/cityofaustin/janis/pull/594

**Describe the bug**
I set an associated contact to the WIC info page and when the page goes live, there is no visible contact on the page.

[WIC benefits information page] (https://alpha.austin.gov/en/health-safety/healthcare-prevention/kids-and-family-resources/wic-benefits/)

**To Reproduce**

1. Go to '[WIC benefits joplin](https://joplin.herokuapp.com/admin/pages/199/edit/#tab-content)
2. Scroll down to 'Contacts'
3. See the assigned 'Women, INfants, and CHildren' contact
4. Go to '[WIC benefits janis] (https://alpha.austin.gov/en/health-safety/healthcare-prevention/kids-and-family-resources/wic-benefits/)
5. See no contacts

**Current behavior**
I see no contacts on the page![Screen Shot 2019-10-30 at 3.17.19 PM.png](https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/60b30be3-94bf-4e8d-bd31-51eaae6e19c8)

**Expected behavior**
I expected to see the contact information for this info page on the right side of the page

**Screenshots**

**Device**
mac

**Browser**
chrome

**Additional context**

**Comment by briaguya** [comment]
Testing contacts show up correctly:
Info page (edit): https://joplin-pr-brians-janis-testing.herokuapp.com/admin/pages/28/edit/#tab-content
Info page (live): https://janis-3331-info-related-contact.netlify.com/en/police-oversight/how-we-store-and-use-your-data/
Info page (preview): https://janis-3331-info-related-contact.netlify.com/en/preview/information/UGFnZVJldmlzaW9uTm9kZToyMTMz?CMS_API=https://joplin-pr-brians-janis-testing.herokuapp.com/api/graphql
Service page (edit): https://joplin-pr-brians-janis-testing.herokuapp.com/admin/pages/94/edit/#tab-content
Service page (live): https://janis-3331-info-related-contact.netlify.com/en/health-safety/police-oversight-2/police-feedback-and-records/thank-an-austin-police-officer/
Service page (preview): https://janis-3331-info-related-contact.netlify.com/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyMTM0?CMS_API=https://joplin-pr-brians-janis-testing.herokuapp.com/api/graphql
Guide page (edit): https://joplin-pr-brians-janis-testing.herokuapp.com/admin/pages/172/edit/#tab-content
Guide page (live): https://janis-3331-info-related-contact.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-vendor-permit-guide/
Guide page (preview): https://janis-3331-info-related-contact.netlify.com/en/preview/guide/UGFnZVJldmlzaW9uTm9kZToyMTM1?CMS_API=https://joplin-pr-brians-janis-testing.herokuapp.com/api/graphql
Department page (edit): https://joplin-pr-brians-janis-testing.herokuapp.com/admin/pages/27/edit/#tab-content
Department page (preview): https://janis-3331-info-related-contact.netlify.com/en/preview/information/UGFnZVJldmlzaW9uTm9kZToyMTM2?CMS_API=https://joplin-pr-brians-janis-testing.herokuapp.com/api/graphql
Department page (live): https://janis-3331-info-related-contact.netlify.com/en/police-oversight/how-we-store-and-use-your-data/
Official Docs/Topic/TC N/A

**Comment by briaguya** [comment]
@desigonz assigned you, see previous comment for testing links

**Comment by desigonz** [comment]
@briaguya Thanks Brian! Your tests all look  great, BUT @Jo-Dwyer and I are going nuts trying to figure out why the WIC contact info won't publish out on prod. This info page draft was started a long time ago—could that be the issue?

**Comment by desigonz** [comment]
@Jo-Dwyer I'm going to try re-making the contact snippet...
