### ISSUE TITLE
Guide Page URLs are inaccurate for PR builds

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#3334]
**Describe the bug**
The urls on page sections within Guide Pages point to the wrong site. The urls in the "Show me this page on alpha" links won't take you to the right page within your PR/local site.

It seems like the graphql query points to the Preview Janis Branch URL, rather than the Publish URL.

**URL**

**To Reproduce**

1. Run Joplin locally with LOAD_STAGING_DATA.
2. Build a Janis off that Joplin and go to the mobile food vendor permitting guide
2. Or just run the graphql query to see the results directly

**Expected behavior**

Guide URLs (and maybe all internal links?) should know which site they're on.

**Screenshots**

Proof:
![Screen Shot 2019-10-30 at 5.20.05 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/589da4e3-f097-448a-881b-c3cae7182ff1)
![Screen Shot 2019-10-30 at 5.19.50 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/3f31e891-e1d3-4ea0-ad7c-a8d75cc8fb85)

**Comment by desigonz** [comment]
What would the size be for "all internal links should know which site they're on" vs. "guide pages know which site they're on"?

**Comment by Niicck** [comment]
3 points for just guide pages. The parenthetical was confusion on my part about whether this bug could be connected to all internal links. I don't know if it is.

**Comment by chiaberry** [comment]
closed because of query out of date after move to v3.
