### ISSUE TITLE
Research translation UX for resident

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3341]
Sometimes we have to publish in English before we have Spanish translations. What does that experience look like for a resident?

**Comment by chasechenevert** [comment]
_From #3347 pin-up notes_

Discussed issues around adding a persistent message on pages that haven’t been translated to a language that appears in the global nav. We’re doing exploratory work so this should still be relatively low-fi with the goal of trying to show different strategies.

**What we discussed**
- Our translation model works field-by-field as opposed to per page, and not all fields are required
- This could get complicated quickly when we support more languages (Arabic and Vietnamese)

**Future state ideas**
- Residents can request translation for a page which could help to prioritize pages which need translation
- Residents can sign-up for user testing (CTA)

**Next steps**
Iterate on a few ways to deliver an alert to the user when the user selects Spanish in the global nav:
- [ ] Tool-tip on mouse-in for spanish
- [ ] One-time modal or toast dialogue upon selecting language
- [ ] Message in right-rail, something else for Guides (no rails)
