### ISSUE TITLE
APH batch of edits

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3343]
Anna Lassman sent us a batch of edits. Let's incorporate her feedback!

**Comment by desigonz** [comment]
@Jo-Dwyer to add checkboxes or split into issues

**Comment by Jo-Dwyer** [comment]
Awaiting fact checking by APH
- [ ] Rent and utility help
- [ ] Free help to quit tobacco
- [ ] Get a copy of immunization records
- [ ] Help with child care
- [ ] Grafitti removal
- [ ] Austin Youth Council
- [ ] Basic services at neighborhood centers
- [ ] Community youth development Dove Springs
- [ ] Free child safety seats
- [ ] Flu
- [ ] Get a flu shot
- [ ] Get free or low-cost HIV testing
- [ ] Attend a fall prevention class
- [ ] Host a fall prevention class
- [ ] free tax and seasonal assistance
- [ ] Get a free child car seat check

Feedback received, edits made and approved 

- [x] WIC benefits
- [x] Smoking in public places
- [x] Find work as a day laborer
- [x] Hire a day laborer
- [x] Breastfeeding support

**Comment by Jo-Dwyer** [comment]
Edits are made, require content review before publishing
- [ ] [Smoking in public places] (https://joplin.herokuapp.com/admin/pages/207/edit/#tab-content)

**Comment by Jo-Dwyer** [comment]
[APH process tracking spreadsheet](https://cityofaustin.sharepoint.com/:x:/r/sites/CTM/TEAMSITES/ODD/alphaaustingov%20Content/Workflows/Departments/Austin%20Public%20Health/Content%20Approvals/APH%20editorial%20tracking.xlsx?d=w89830c282e484cb3b02bed5246de2b36&csf=1&e=496qg5)

**Comment by Jo-Dwyer** [comment]
Can @srigdon, @ablangworthy27 or @annieszot take these reviews or the ones above?

### Need Final Review
- [ ] [WIC benefits] (https://alpha.austin.gov/en/health-safety/healthcare-prevention/kids-and-family-resources/wic-benefits/)
- [ ] [Hire a day laborer](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxODcz)
### Pre-Joplin Review
- [ ] [Breastfeeding support](https://cityofaustin.sharepoint.com/:w:/s/CTM/TEAMSITES/ODD/ERT-Tf2YcypBmAcCB1Vg7RgBuTuIA1gVSNrXqFKkc7Disg?e=zIeeKH0)
- [ ] [Community youth development in Dove Springs](https://cityofaustin.sharepoint.com/:w:/s/CTM/TEAMSITES/ODD/ESG7DAyI_3VJj97h7Ex9rykBpyyq10zU0szwMMeinTAq7Q?e=zUBsdX)

**Comment by srigdon** [comment]
- Smoking in public places --> Changed the lists to conform to the style guide, otherwise looks good. (Saved changes as draft)
- Find work as a day laborer --> Cleaned up punctuation and the list, good to go. (Saved changes as draft)
- WIC benefits --> Deleted an extra space in the title, saved changes, good to go
- Hire a day laborer --> The preview page made the list look fine but in Joplin all the formatting was removed somehow? Fixed, good to go 
- Breastfeeding support --> Looks good
- Community youth development in Dove Springs --> Looks good, left the comment threads there in case you need them but recommend cleaning up before sending to APH

**Comment by Jo-Dwyer** [comment]
More pages ready for approval! @srigdon @annieszot @ablangworthy27 can I get a review on:
- [ ] [Help prevent diabetes in your community](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyMzgy)
- [ ] [Breastfeeding support](https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToyMzg5) Hours at MOm's Place are irregular, so I am leaving the contact off for now. This is logged in #3496.

**Comment by Jo-Dwyer** [comment]
@ablangworthy27

**Comment by ablangworthy27** [comment]
Below are a few things I had notes on for [Breastfeeding Support](https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToyMzg5)

_- why breastfeeding matters_ 
might be better as "Importance of breastfeeding" or maybe something neutral? Breastfeeding matters but we don't want to alienate people who can't or choose not to breastfeed. I just know this is kind of political and sensitive. Perhaps "Benefits of breastfeeding" would work.

_- How partners and grandparents can support breastfeeding mothers_
Maybe this is going too far with gender neutrality. But, on rare occasions, a person who is breastfeeding might not be identifying as a woman/mother. I wonder if there is a way to keep this bullet but remove that aspect. 

_grant funded_ 
should be hyphenated grant-funded

**Comment by Jo-Dwyer** [comment]
@ablangworthy27 
Thank you for the thoughtful feedback I was looking for this kind of subtlety but wasn't quite hitting it myself. I'm taking "Benefits of breastfeeding" and "grant-funded". I brought up "breastfeeding parents" and didn't get a strong response either way. "Nursing parents and caregivers" may work as well.

**Comment by Jo-Dwyer** [comment]
Closing and splitting these into individual issues so we keep momentum.

**Comment by Jo-Dwyer** [comment]
Grafitti removal is being put on hold for transition by Jen Samp.
