### ISSUE TITLE
OPO official doc not showing up

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3348]
**Describe the bug**
When clicked, one of the official docs on the OPO page returns an error.

https://joplin-austin-gov-static.s3.amazonaws.com/production/media/documents/2019-0710.pdf

**To Reproduce**

1. Go to '[OPO Documents} (https://alpha.austin.gov/en/police-oversight/official-complaint-and-discipline-documents/)'
2. Click on '[Formal Complaint: Smoking/Tobacco Use](https://joplin-austin-gov-static.s3.amazonaws.com/production/media/documents/2019-0710.pdf)
3. See error

**Current behavior**

**Expected behavior**
Should load a document.

**Screenshots**
![Screen Shot 2019-10-31 at 2.59.47 PM.png](https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/31142c55-852a-47e5-ab40-7edf662e9146)

**Device**
macbook air

**Browser**
chrome

**Additional context**

**Comment by srigdon** [comment]
Thought I'd quickly fix this one, then checked the other PDF links on the page, and now they're all 404ing. Even the "Formal complaint: Smoking/Tobacco Use" link is displaying this error: 
![Screen Shot 2019-11-04 at 9 16 32 PM](https://user-images.githubusercontent.com/5445796/68175984-bd4a4480-ff48-11e9-8f4f-126a95aa7b6f.png)

Can't find anything wrong in Joplin prod re: official documents. cc @desigonz

**Comment by desigonz** [comment]
Noticing the URLs from the official doc page have `undefined` in them, ex, `https://alpha.austin.gov/en/police-oversight/official-complaint-and-discipline-documents/undefined/Johnson_-_10.08.19_1.pdf`.

**Comment by easherma** [comment]
They seem to working now, but we're not sure why they broke in the first place. It looks to me like an error with the janis_url for that page and not a problem with the document itself. Replicating it might be tough, especially since we don't know when it started breaking.

**Comment by easherma** [comment]
To @Jo-Dwyer 's original issue, I strongly suspect the name of that document was changed, and a new build hadn't been triggered yet. 

To 'undefined' showing up in the janis_url, I'm not sure exactly how to replicate that but I think it's a separate issue.

**Comment by easherma** [comment]
note for devs: we could maybe use this hook for checking if a doc exists?
https://docs.wagtail.io/en/v2.6.3/reference/hooks.html#document-serving

**Comment by srigdon** [comment]
Seeing the same error message now but it's displaying in a different format. 
![Screen Shot 2019-11-05 at 12 36 34 PM](https://user-images.githubusercontent.com/5445796/68239615-e57d8600-ffd0-11e9-99cd-3c19eeb385ce.png)

Steps taken so far:
1. Tried re-uploading the document Formal Complaint: Smoking/Tobacco Use. 
2. Tried deleting the document entry then re-adding it. 
3. Deleted the document, went back to the official documents page and deleted the entry, then re-added the entry. Renamed the document file name and the title. 
4. Still not working! Taking an even longer break than the few minutes it usually takes for a change to publish out and coming back to it.

**Comment by easherma** [comment]
https://github.com/cityofaustin/joplin/tree/3348-signals 

Adds a signal for document upload to trigger a build

**Comment by easherma** [comment]
> Seeing the same error message now but it's displaying in a different format.
> ![Screen Shot 2019-11-05 at 12 36 34 PM](https://user-images.githubusercontent.com/5445796/68239615-e57d8600-ffd0-11e9-99cd-3c19eeb385ce.png)
> 
> Steps taken so far:
> 
> 1. Tried re-uploading the document Formal Complaint: Smoking/Tobacco Use.
> 2. Tried deleting the document entry then re-adding it.
> 3. Deleted the document, went back to the official documents page and deleted the entry, then re-added the entry. Renamed the document file name and the title.
> 4. Still not working! Taking an even longer break than the few minutes it usually takes for a change to publish out and coming back to it.

@srigdon 
1) In staging/prod, re-uploading the doc is not going to trigger a new build unless you modify the Formal Complaint page (the PR I link above is a proposal to change that)
2) Would love to see what you did here, but again if it's just on the docs page it won't trigger a new build
3) This _would_ trigger a new build, so we should verify what you did here and see whats up with that.

**Comment by srigdon** [comment]
It works! What ended up fixing the 7-11-19 instance is I edited the document entry from the official documents edit page, like so: 

1. Ctrl+F "tobacco," then find the 7-11 formal complaint instance. 
2. Click "Choose another document" button
3. Click the Upload tab
4. Add a title, upload the document, make sure it's in the OPO collection, click upload, then click Update in the upper right corner
5. Wait ~5 minutes, then check it on Janis 

For future reference, there are two instances of the same .pdf file in the Documents section of Joplin: 
| Title | File | 
| ---- | ---- | 
| 2019-0710_formal | 2019-0710.pdf | 
| 2019-0710_Notice-of-Formal-Complaint.pdf | 2019-0710.pdf | 

We've decided to leave both in there for now in case we want to troubleshoot this problem later. Hope this note helps someone in the future. (_Puts note in bottle, puts cork in, tosses it._)
