### ISSUE TITLE
"Form container" nomenclature

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3352]
The "form container" content type is called because we want to indicate to authors that this isn't where you make the form itself, it's just a thing that holds the Formstack form.

- [x] change content_type to “form container”,
- [x] For the create new content modal, should say "Form container"
![image](https://user-images.githubusercontent.com/5839508/67703751-f8190f00-f981-11e9-8138-60467606cb33.png)
- [ ] When you edit the form container page, the header says "Edit form container"
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/1c068a13-ee71-4cfd-be6d-e54cb8b28aec)

**Comment by Niicck** [comment]
QA-able here: https://joplin-pr-3352-form-container.herokuapp.com/admin/pages/search/?q=&content_type=base.formcontainer

**Comment by desigonz** [comment]
QA done! beautiful!!
