### ISSUE TITLE
Review best practices and incorporate into the Funshop deck

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#3355]
Guides and checklists to review: 
- [x] https://accessibility.blog.gov.uk/2016/09/02/dos-and-donts-on-designing-for-accessibility/
- [x] http://accessibility.voxmedia.com/

Others?

**Comment by annieszot** [comment]
Excellent @srigdon ! Currently incorporating in the [economic development's deck](https://docs.google.com/presentation/d/1u3u6yz-g2dFfRG_njonG-tSaP9KBxGKo9LMZQq7kZNk/edit#slide=id.g2784417b60_0_12) 
Also compliments #3138

**Comment by annieszot** [comment]
Closing (incorporated into Econ Dev Funshop) but added these best practices into "How to Funshop" doc
