### ISSUE TITLE
Publish from main Joplin page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3358]
**Describe the bug**
Publishing from the main content page in Joplin 404s.

![publish-from-main](https://user-images.githubusercontent.com/5839508/68237581-017f2880-ffcd-11e9-84be-d6434e813d1a.gif)

**URL**
Joplin staging

**To Reproduce**

1. Go to Joplin staging
2. Pick a page that's `draft` or `live + draft`; use the dropdown to select "publish"
3. On "Are you sure?" page, select publish

**Current behavior**
404

**Expected behavior**
- [ ] Page publishes

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by easherma** [comment]
https://joplin-pr-3358-publish-redirec.herokuapp.com/

**Comment by desigonz** [comment]
We're going to QA this one on staging.

**Comment by desigonz** [comment]
QA passed!

**Comment by easherma** [comment]
![publish-janis](https://user-images.githubusercontent.com/10539855/68788010-2b0d0500-0608-11ea-8660-998ab63a84cb.gif)
![publish-joplin](https://user-images.githubusercontent.com/10539855/68788011-2b0d0500-0608-11ea-9691-f184ea939024.gif)
@desigonz I tested publishing triggering a build in staging for you
