### ISSUE TITLE
Main search alert & styling fixes

### ISSUE THREAD

**Issue by robbobfrh84** [cityofaustin/techstack#3363]
When searching, filtering and sorting from our Main search pages. A few issues have popped up. 

* When selecting to filter by page, without entering any text, you'll see a `This field is required` error. 
  See **Image A**. 

* When you start typing in the search box,  and *Don't press enter,  you'll see the search returned. Now, select a page to filter and see the **Alert!* popup. 
  See **Image B**. 

* Search input box needs basic styling. 
  See **Image B** for raw centered styling look.

* some work-flows still end up @ `admin/pages/3/`. Let's find those remaining locations and direct it to `admin/pages/search/`. 

* Just in case there are old links or places we've missed the old redirect. Let's rerout all `admin/pages/3` in the request function to our new search page instead. 

We expect to search, filter and sort without these notification and errors. 

### Acceptance Criteria and testing:
- [x] Auto search works
* Visit: https://joplin-pr-search-fixes.herokuapp.com/admin/pages/search/
* Start typing in a search word (example: police) 
* It should return results automatically

- [x] Auto search + page filter doesn't show alert message 
* Searching for a word, do NOT pressing [enter]
* Now, select a page type to filter
* you should NOT see any alert messages, and search should be filtered

- [x] No search input + page filter doesn't  show error notification 
* Visit: https://joplin-pr-search-fixes.herokuapp.com/admin/pages/search/
* Try to filter by page type
* You should NOT see an error notification and page should filter without a search. 

Image A
<img width="1169" alt="68125451-488af200-fed7-11e9-9ca2-353929c6a970" src="https://user-images.githubusercontent.com/15821138/68322493-13260600-0089-11ea-89d1-cbab9ad0b64e.png">

Image B
![Screen Shot 2019-11-06 at 5.48.21 PM.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/4a491add-8241-4f3d-8883-f4d3c6c7cef1)

Image C
![Screen Shot 2019-11-06 at 11 35 12 AM](https://user-images.githubusercontent.com/15821138/68322752-9d6e6a00-0089-11ea-8e98-c2fdbe52630c.png)

**Comment by robbobfrh84** [comment]
Ready for QA @desigonz 
- PR: https://github.com/cityofaustin/janis/pull/598
- Deployed: https://janis-3244-guide-icon-tiles.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/

**Comment by desigonz** [comment]
@robbobfrh84 Looks great, QA done!
