### ISSUE TITLE
Form confirmation page styling

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3364]
This is what it currently looks like when you submit a Formstack form. We need to style the confirmation page. 
![image](https://user-images.githubusercontent.com/5839508/68323758-b415c080-008b-11ea-9b0a-685073b909c8.png)
![image](https://user-images.githubusercontent.com/5839508/68323577-55504700-008b-11ea-853b-b31759e33e7f.png)

@chasechenevert, can you submit some quick MVP requirements for styling this?

**Comment by chasechenevert** [comment]
- [ ] Use same details from alpha for body copy (1.7rem, 400, #212121)
Not worried about the check mark right now.

**Comment by desigonz** [comment]
Thanks @chasechenevert! @Niicck would you mind incorporating/would it make sense to incorporate this with the other formstack theme updates you're making?

**Comment by Niicck** [comment]
So it looks like we can't control the styles for the Submission message. Pressing "Submit" takes users away from our form and onto a formstack.com page. 

Authors can only edit submit message styles to a limited extent within each form's individual Submission message richtext editor. :/ 

<img width="587" alt="Screen Shot 2019-11-12 at 11 44 15 AM" src="https://user-images.githubusercontent.com/14187277/68696060-e159e700-0541-11ea-86b2-ea247465c154.png">

**Comment by Niicck** [comment]
But we could redirect to our own external URL on Submit. However, that could be a challenging content authoring flow.

**Comment by Niicck** [comment]
According to content team, we can probably icebox/close this requirement.

**Comment by desigonz** [comment]
Can you explain more about the content team reasoning for wanting to icebox/close this requirement?

**Comment by Niicck** [comment]
"Great, one less thing for us to think about." -Chase

It's basically out of our control. Chase can live with us not being able to style the confirmation page.

**Comment by desigonz** [comment]
Love it. Okay I'll backlog it for now. Might be something we could petition Formstack about.

**Comment by Niicck** [comment]
I spoke too soon.

**Comment by Niicck** [comment]
Alright, confirmation page is styled:
https://janis-3288-content-padding.netlify.com/en/health-safety/health-records-certificates-2/birth-death-certificates/spanish-form-test

**Comment by desigonz** [comment]
This is what I'm getting:

![image](https://user-images.githubusercontent.com/5839508/68811177-3aeb1000-062d-11ea-8b58-6c47e7e850c5.png)
