### ISSUE TITLE
Tile padding adjustment

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#3365]
**Describe the bug**
.coa-Tile needs 2rem of padding, and this applies to the default tile (not compact).

https://alpha.austin.gov/en/health-safety/police-oversight-2/police-feedback-and-records/

**To Reproduce**

1. Go to https://alpha.austin.gov/en/health-safety/police-oversight-2/police-feedback-and-records/
2. See that left and right padding is smaller than top and bottom

**Current behavior**
```
.coa-Tile {
padding: 2rem 1rem;
}
```

**Expected behavior**
```
.coa-Tile {
padding: 2rem;
}
```

**Screenshots**
Before
![Screen Shot 2019-11-06 at 12.09.54 PM.png](https://images.zenhubusercontent.com/5b7b6eae2bc79a5e7d4f874c/484eaa9a-0758-454a-82ed-b5d56fd10450)

After
![Screen Shot 2019-11-06 at 12.12.27 PM.png](https://images.zenhubusercontent.com/5b7b6eae2bc79a5e7d4f874c/818a1822-db3f-447d-8c6d-f0923ad54a38)

**Device**

**Browser**

**Additional context**

**Comment by robbobfrh84** [comment]
Ready for QA and review: https://github.com/cityofaustin/janis/pull/635

**Comment by desigonz** [comment]
Assigning @chasechenevert to QA at https://janis-3365-tile-padding-adjustment.netlify.com/.

**Comment by chasechenevert** [comment]
Good to go!
