### ISSUE TITLE
Map not rendering on Janis

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3366]
**Describe the bug**
This page used to have a map in Janis! Joplin still indicates that the map was selected, but the map isn't appearing in Janis.

https://joplin.herokuapp.com/admin/pages/11/edit/#tab-content
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/f170fb4e-ad9d-45a1-a547-783a3335e7fb)

https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/household-waste/hazardous-waste-dropoff/
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/1667b10c-f358-4b58-8815-ce354f4ab523)

**URL**

**To Reproduce**

**Current behavior**

**Expected behavior**

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by easherma** [comment]
Data is there there on the backend:
```
{
  "data": {
    "allServicePages": {
      "edges": [
        {
          "node": {
            "dynamicContent": [
              {
                "id": "0d8879df-6a04-49eb-a32c-e0888af3cb99",
                "type": "map_block",
                "value": {
                  "description": "Recycle & Reuse Drop-Off Center",
                  "location": {
                    "city": "Austin",
                    "country": "United States",
                    "name": "Recycle & Reuse Drop-off Center",
                    "state": "TX",
                    "street": "2514 Business Center Dr",
                    "zip": "78744"
                  }
                }
              }
            ],
            "id": "U2VydmljZVBhZ2VOb2RlOjEx",
            "title": "Drop off household hazardous waste and other recyclables"
          }
        }
      ]
    }
  }
}
```

**Comment by easherma** [comment]
https://github.com/cityofaustin/janis/commit/668fea91efb4b226baace929cf91752441434bf6

We removed dynamicContent awhile back, tracking down evidence on the exact reasons why. 

In the meantime, https://github.com/cityofaustin/joplin/pull/457 adds it back, but lets do QA and make sure adding it back doesn't break anything

**Comment by easherma** [comment]
Can be tested at: https://janis-3366-static-map.netlify.com/en/housing-utilities/recycling-trash-and-compost/household-waste/hazardous-waste-dropoff/

**Comment by desigonz** [comment]
Verified that the map is back!
