### ISSUE TITLE
I can't save 311 as the phone number for 3-1-1

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3369]
**Describe the bug**
Within Austin, the contact phone number for 3-1-1 is 311. Joplin won't let me save the snippet this way. The error is at 311, but it won't tell me what's wrong. (I assume it's that there is a minimum digit requirement on that field.)

**URL**
[3-1-1 Snippet editor](https://joplin.herokuapp.com/admin/snippets/base/contact/4/)

**To Reproduce**

1. Go to 'Editing contact 3-1-1 .'
2. Add a phon number 311 for calls within Austin
3. Scroll down and click 'save'

**Current behavior**

**Expected behavior**
I want it to save the correct contact ![Screen Shot 2019-11-06 at 3.34.23 PM.png](https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/cc7e962c-c7c4-44e6-9f25-c5c9f413dcdb)number 311.

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by desigonz** [comment]
I'm going to consolidate all of our 311 things issues since none of them are urgent, but we'll want to think of them together. This one is now in #3250
