### ISSUE TITLE
Update 311 as the phone number for 3-1-1

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3370]
Calls to 311 are routed locally, so if a resident calls from within Austin, it will automatically forward to Austin 311. Calls made to 311 from outside Austin will route to the nearest 311 call center. 

I want to clarify the ways to contact Austin 3-1-1 from inside (311) and outside Austin (+15129742000).

**Comment by desigonz** [comment]
Duplicate of #3250
