### ISSUE TITLE
Catching */admin/pages/3/* re-routes

### ISSUE THREAD

**Issue by robbobfrh84** [cityofaustin/techstack#3373]
When we first modified our main content page to be our search page, we went away from wagtails default "explore" page, which lived at ... 
-  `/admin/pages/3`

Though we modified all locations within our code base, there were some user-flows that found their way back to the old url. Which is still there, and useful, but we want to direct users back to the main search page.
- `/admin/pages/search/`

### Known re-routes to `/3/`
- [ ] - Select a page to edit. Once in the "Edit" page > Select the dropdown and  publish. 

### Potential fixes
- Ideally we'd find where wagtail sets this default route and change it to our new route. 

- Also, if this is proving more complicated and / or we just need a quick hack. Embedding this in our .js will do an ugly reroute of any page that lands on `/admin/pages/3/`. 

```javascript
window.onload = function() {
  if (window.location.pathname === "/admin/pages/3/") {
    window.location.href = window.location.origin+"/admin/pages/search/"
  }
}
```

- Other thoughts welcome!

**Comment by robbobfrh84** [comment]
Also. If we know the specific places where this happens. We reroute based on the use-case..
.. which is what we've done to the usual use cases so far.

**Comment by easherma** [comment]
There is almost certainly a way to catch this using a redirect or pattern in urls.py which is where I'd prefer to make the change: 
https://docs.djangoproject.com/en/2.2/topics/http/urls/

**Comment by desigonz** [comment]
Closing this since #3401 will cover it—pretty sure we've found all the cases where we're not getting sent back to the main page. If we discover more, we'll make new issues!
