### ISSUE TITLE
Assigning a page to the same department only once

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3377]
# Describe the bug

You can assign a page to a department twice and then it shows up twice on the Janis page.

Let's prevent authors from choosing a department they already chose.

![image](https://user-images.githubusercontent.com/5839508/68414737-5a2dfd00-0156-11ea-9323-9a72b7351a01.png)

![image](https://user-images.githubusercontent.com/5839508/68414746-5d28ed80-0156-11ea-8024-dd299f2ef14b.png)

# URL

# To Reproduce

# Additional context

**Comment by desigonz** [comment]
- [ ] Once a user has selected a department page, if a user goes to add another department, that first department doesn't appear in modal (or if it does appear, indicates it's already been selected)

**Comment by briaguya** [comment]
@desigonz my guess is this isn't an issue now that we have the new dept stuff

**Comment by desigonz** [comment]
True!! Closing this.
