### ISSUE TITLE
MVP custom save/publish requirements

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3379]
## MVP requirements

- [x] The only field required for **save** across all content types is **Title**
- [x] For publishing, only require English
- [x] Don't require any SEO or settings fields (except English slug, which is auto-generated for English)
- [ ] Behavior when publishing from content list page: if not all the required fields are filled out, opens the edit page with the relevant error messaging
- [ ] IA requirement for publishing (so a page will build)
  * For INFO and SERVICE pages:
    * on publish, you need to have at least:
      * 1 TOPIC **OR** 1 DEPARTMENT **OR** TOP LEVEL checked
  * For FORM CONTAINER, GUIDE, or OFFICIAL DOCS pages:
    * on publish, you need to have at least:
      * 1 TOPIC **OR** 1 DEPARTMENT 
  * For TOPIC pages
    * on publish, you need a TOPIC COLLECTION
  * For TOPIC COLLECTION pages
    * on publish, you need a THEME
  - [ ] Need an error message to display at the top for the "1 TOPIC **OR** 1 DEPARTMENT **OR** TOP LEVEL checked" logic (copy TBD)

### Service page
| Field  | Required for publish? |
| ------------- | ------------- |
| Topic  | ❌  |
| Related departments  | ❌  |
| Description  | ✅   |
| Steps  | ✅  |
| Maps/app blocks  |  ❌ |
| Additional content  | ❌  |
| Contact  | ❌  |
| Make top level  | ❌  |

### Info page
| Field  | Required for publish? |
| ------------- | ------------- |
| Topic  | ❌  |
| Related departments  | ❌  |
| Description  | ✅   |
| Content  | ✅  |
| Contact  | ❌  |
| Make top level  | ❌  |

### Department page
| Field  | Required for publish? |
| ------------- | ------------- |
| What we do  | ✅  |
| Image  | ❌ ? what happens when a dept page gets published without an image?  |
| Mission  | ❌   |
| Contact  | ❌  |
| Department directors  | ❌  |
| Job listing URL  | ❌  |
| Top services  | ❌  |
| Related pages  | ❌  |

### Official document list
| Field  | Required for publish? |
| ------------- | ------------- |
| Topic  | ❌  |
| Related departments  | ❌  |
| Description  | ✅   |
| Document entries  | ✅  |

### Guide
| Field  | Required for publish? |
| ------------- | ------------- |
| Topic  | ❌  |
| Related departments  | ❌  |
| Description  | ✅   |
| Image  | ❌  |
| Sections and pages  |  ✅ |
| Contact  | ✅  |

### Form container
| Field  | Required for publish? |
| ------------- | ------------- |
| Topic  | ❌  |
| Related departments  | ❌  |
| Description  | ✅   |
| Formstack URL  | ✅  |

### Topic

| Field  | Required for publish? |
| ------------- | ------------- |
| Description  | ❌ for now, but will want this later    |
| Image  | ❌  |
| Topic collection  | ✅?? Although this could be a weird chicken-egg situation. So maybe ❌ |
| Top link  | ✅  |

### Topic collection
| Field  | Required for publish? |
| ------------- | ------------- |
| Description  | ❌ for now, but will want this later    |
| Theme  | ✅   |
| Image  | ❌  |
| Topic collection  | ❌(topic collections can belong to parent topic collections)  |

**Comment by easherma** [comment]
@desigonz Where do required fields fit into this? Put another way, do we have any fields that are required for saving a draft _or_ for publishing? 

For example, 'title' is usually a required field. It cannot be blank, neither for drafts or for publishing. Can we note that on the content model as well?

**Comment by briaguya** [comment]
### Publish logic re: janis URLs

* For FORM CONTAINER, GUIDE, OFFICIAL DOCS, INFO, and SERVICE pages:
  * on publish, you need to have at least:
    * 1 TOPIC **OR** 1 DEPARTMENT **OR** TOP LEVEL checked
* For TOPIC pages
  * on publish, you need a TOPIC COLLECTION
* For TOPIC COLLECTION pages
  * on publish, you need a THEME

**Comment by desigonz** [comment]
We'll want to come up with a test plan around this.

**Comment by desigonz** [comment]
### Testing ideas 
- When we test, let's sync with the most up-to-date data and test a whole lot of pages across content types. 
- What's the behavior when existing published pages don't data is in fields that we now will be requiring??

**Comment by chiaberry** [comment]
@desigonz here is the app for qa: https://joplin-pr-add-publisher-prefli.herokuapp.com/admin/pages/search/

there was a problem with empty rich text fields not preventing publishing from happening, but @easherma addressed it in  https://github.com/cityofaustin/techstack/issues/3605

**Comment by desigonz** [comment]
@easherma @chiaberry QA notes below. Let's talk about how to break this down.

The following look good:
✔️Rich text fields (excluding the ones within streamfields)
✔️Info pages
✔️Department pages
✔️Form pages
✔️Topic collections

Across the board
- [ ] Required for publish fields should have an asterisk to indicate that it's required

Service page
- [ ] I was able to publish without adding a step, but I shouldn't be able to

Official documents
- [ ] I was able to publish without adding a document entry, but I shouldn't be able to

Guide
- [ ] I was able to publish without adding sections/pages, but I shouldn't be able to

Topic
- [ ] I was able to publish without a topic collection, but I shouldn't be able to

Some funny things happen when you have a published field, delete it, and then try to publish. See GIF.
![3379-save-without-all-fields](https://user-images.githubusercontent.com/5839508/71024073-c1ca5700-20c9-11ea-8767-9b940733ff65.gif)

**Comment by easherma** [comment]
@desigonz re 'Required for publish fields should have an asterisk to indicate that it's required'

The asterisk comes from marking fields as required in the model, but making those fields absolutely required means they can't be missing if you're saving a draft. We could find a hacky way to add asterisk to fields that are not required but just required for publish, but that dosen't sound like a good idea because it would add a maintenance burden and also conflate two different behaviors. 

I don't recall this being part of the MVP acceptance criteria. 

I'll try looking into the other issue you mentioned as well. 

I'd also recommend 'Behavior when publishing from content list page: if not all the required fields are filled out, opens the edit page with the relevant error messaging' and 'IA requirements for publishing' to be their own issues; those are both even more complicated and would require more testing and implementation than what we have so far.

**Comment by easherma** [comment]
I wasn't able to replicate the problem with documents. 

Guide pages and service pages are likely due to some details about validating Streamfields that I'll have to dig into. 

Topics missing topic collections seems...inconsistent. The first time I tried it was able to publish successfully, but subsequent times did not work.

**Comment by easherma** [comment]
I'm currently running into an error while trying to expand this for Streamfields, very similar to: 
https://github.com/wagtail/wagtail/issues/5663

The current behavior for streamfields is that if there are none at all added, you can still publish. However, if you were to try to, for instance, add a step, and that step was blank, that would trigger an error.

**Comment by easherma** [comment]
We might want to consider the UX value of making this work exactly as indicated as part of MVP for this plugin. 

Another option might be to work on: https://github.com/wagtail/wagtail/issues/5175 , setting a min_number on each StreamField would accomplish the same (not sure how this would/could play into the difference between draft vs publish though)

**Comment by desigonz** [comment]
Here's what I still see missing:
- [ ] If I publish a page with all of the required fields, but later delete one of the required-to-publish fields, it still allows me to publish. This is not the behavior I would expect; I would expect it to throw an error. (This might explain some of the things you couldn't replicate or were inconsistent) 
- [ ] Ability to require a whole streamfield block (not just an individual instance within a streamfield)
- [ ] Asterisk to denote required-for-publish fields (you're right that this wasn't originally part of acceptance criteria; that was an oversight on my part)
- [ ] Behavior when publishing from content list page: if not all the required fields are filled out, opens the edit page with the relevant error messaging
- [ ] IA requirements for publishing

I'll set up a time for us to talk through these tomorrow!

**Comment by easherma** [comment]
Estimates:

1. **5**
1. I need more information to duplicate this. I haven't had this problem or been able to replicate it, except maybe for streamfields, which is probably tied to the larger issue with streamfields. In either case, it probably indicates how helpful writing tests for this functionality would be, so...a **5** to take some time to make testing easier?
1. This is a known issue, mostly in progress but not fully addressed yet. I'd say its a **5** in complexity, but I've got a head start on it so I don't think it would take as much time. 
1. **13** 
The current behavior is to display an error message at the top with a link to edit the page. We could adjust the timeout so it doesn't fade away and add a button so the message could be dismissed, thats more like a **2**. 
Forcefully re-routing would probably need to do some testing to implement and not cause negative side affects, not sure about the UX of that if someone is on the list view and then is taken somewhere else. 
I'd be much more comfortable with just the way Wagtail handles it (allowing unpublishing but not publishing from the page listing view). In general, do we really want people publishing content without looking at it first anyways? Maybe we can simplify the acceptance criteria by clarifying why its valuable in the first place. 
1. At least a **13**, maybe more. We're really fighting against both of the frameworks we're developing on top of at this stage, and that feels unsustainable.

**Comment by desigonz** [comment]
To replicate number 2:
1. Create a new guide via the create content modal
2. Fill out required fields (title, description, section, contact)
3. Publish the page
4. Edit the page and delete the contact
5. Update/publish page

**What happens:** it still publishes
**Expected behavior:** it shouldn't allow you to publish without a contact

However, behavior worked as expected when I did this with an official document list:
1. Create a new official doc page via the create content modal
2. Fill out required fields (title, description, document entry)
3. Publish the page
4. Edit the page and delete the description
5. Update/publish page

So maybe text fields are validating correctly but not streamfields and pickers.

**Comment by easherma** [comment]
I'd need to do more digging, but I reckon the issue with the contact is that its a ClusterableModel. Those are designed to allow for creation/deletion on the fly, and so the type of validation that I'm running on the preflight may not trip it until the relation is either saved or not saved. For instance, if you remove a contact and publish, it will work the first time. But if you try to publish again still missing a contact, it will not let you. 

So I think we'd want to keep an eye on it while working on the other issues, and we may be able to address it along the way. If not, it'l be it's own use case to handle (sorta similar to Streamfields in that way) but after that is addressed it won't be a problem moving forward.

**Comment by easherma** [comment]
Note: wagtail react-streamfield might help us with coverage. For one thing, it adds a min & max length to StreamFields which we could leverage for preventing empty Streamfield entries.
