### ISSUE TITLE
Translation costs for departments: round two

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#339]
Building off of #241, we want to add the cost of the Stack Pack team:

### Implementation Cost ###
- Estimate of _Dev Team_ time spent implementing #326 their hourly rate 

### Per-page Costs ###
_We will want to recalculate this for Process Pages once we have an average/estimated word count on those._
- Estimate of _Content Team_ time spent creating 300 words-or-less Service Page * their hourly rate

### To Do ###
**Dev:**
- [x] Estimate of hours for #326 - ***20 hours***
- [ ] Hourly rate for dev resource (@wilhitem?)

**Content:**
- [ ] Estimate of hours spent Per-300-word-page with new workflow
- [ ] Hourly rate for content resource (@wilhitem?)

**Product:** 
_Unless someone else wants to_
- [ ] Spreadsheet of these costs
- [ ] Share w/ CPIO

**Comment by ashleecoa** [comment]
Looks good. @amenity might be helpful to just sit down and calculate all this out with teams, you and Marni.

**Comment by amenity** [comment]
no longer relevant
