### ISSUE TITLE
Prep & meet— records retention meeting with Wayne Whyte

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#3390]
@annieszot and I are meeting with the CTM records manager, Wayne Whyte, for him to walk through the records control schedule with us so we can represent it in plain language, to be used in educational and communications materials for everyone at the city.

Beforehand, we'll: 

- [x] Read through the RCS document and other curiosities on the [CTM Records Management](https://cityofaustin.sharepoint.com/sites/cTM/teAMSITES/rm/SitePages/Home.aspx?CT=1573169442790&CT=1573233590856&OR=OWA-NT&OR=OWA-NT&CID=bc63c7f5-9344-0830-437b-da879f7953c2&CID=5dd5a279-a63e-2cc6-16d1-12d375cc15b5) site. 
- [x] Compile a list of concrete examples we have of content management questions, especially related to putting PDFs or other documents on the website.

**Comment by desigonz** [comment]
This happened, right? Shall we close it?

**Comment by annieszot** [comment]
@srigdon Does this issue relate to our first phone call with Wayne or the follow-up we have scheduled next week?

**Comment by srigdon** [comment]
@desigonz @annieszot This is about our next meeting on 11/20, not the one we had last week, which was more of a preamble or introduction to get on the same page about what we want to do.

**Comment by annieszot** [comment]
Documentation 11/19/2019 AS: 
- [x]  Read through the RCS document and other curiosities on the CTM Records Management site.
- [ ]  Compile a list of concrete examples we have of content management questions, especially related to putting PDFs or other documents on the website.

**Comment by annieszot** [comment]
Meeting w/ Wayne and @srigdon conducted 11/20/2019 1-1:30pm
Agenda: 
What is a record?
How to put communicate records control schedule in plain language.
Concrete examples of "records" City staff ask the Office of Design and Delivery about during Funshops 

*Notes* 
Record definition (simplified) - anything that is used to conduct business transactions 
-Any medium or media – electronic device, email, notepad, receipts, anything that documents business transactions involving the City, correspondence (email)  
Definition (book) – Any document, map, paper, letter, photograph, sound or video recording, magnetic tape, electronic medium, physical form or characteristics, created or received by local government – transaction for public business  

When looking at records control schedule - "AV" in retention period means "administrative value" - hang on to a records (ex. construction project records) for as long as needed 

Insights: 
Things on the internet not always the record but a copy. Copies are not records. If a resident wants a record from ten years ago (ex.) can file a public information request, City sees if still has records or if it's been destroyed (per record retention policy) and send it to that resident

Each department has own record control schedule. Each department should have a records retention manager/analyst

Referred contacts: Eric Stene with the City Clerks office, City's Records Management Officer
Austin Public Health - Kevin Waldrop 

Next steps (need to crosscheck with @srigdon ) 
-Add records retention checklist to ODD's content inventory
-Determine how records retention subject matter experts will assist in deciding what stays up/comes down when departments transition content from austintexas.gov to austin.gov.  
-Meet with Wayne for an hour to go over checklist (?)

**Comment by srigdon** [comment]
Great notes, @annieszot! Just one thing to add for next steps: 

- Let's go through the steps of Wayne Whyte's SOP that's going through review right now. I'll email him to follow up on this meeting and ask for a copy, and schedule the next meeting. 

Not in the meeting, but additional tasks: 
- Let's connect with Daniel Honker and keep him in the loop, as he's meeting with folks who also have insights on this.
