### ISSUE TITLE
Recover permittingatx.com analytics

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3391]
We need to access Google Analytics for permittingatx.com. Per #392, looks like the people who probably had analytics access were:
- Rachel Crist
- Laura 
- Courtney
none of whom are at the City anymore.

We might be able to follow [Google's suggestion](https://support.google.com/analytics/troubleshooter/7264014?hl=en#ts=7271146) to try to retrieve access:

### Prove site ownership
Make sure you follow the format and the wording exactly as provided. Incomplete and/or incorrect wording will prevent us from proceeding with your request.

1. Create an `analytics.txt` file with the following information:
  - `GooGhywoiu9839t543j0s7543uw1 - pls add {INSERT EMAIL ADDRESS} to GA account {INSERT UA-ID} with ‘Manage Users and Edit’ permissions - date {INSERT DATE}.`
2. Add the `analytics.txt` file to the top-level domain, e.g., `example.com/analytics.txt`. If the URL of the site that is sending data to Analytics is a subdomain, then you can upload `analytics.txt` to either the subdomain or the top-level domain, for example: `sales.example.com/analytics.txt or example.com/analytics.txt`. 
3. If there are Google Ads and/or AdSense accounts linked to the Analytics account, you need to prove ownership of those accounts, as well.
4. [Contact us.](https://support.google.com/analytics/contact/adminleft_ga)

If you cannot prove ownership of all the sites identified by Default URLs in the Analytics account, then we cannot grant access.

If your website does not allow uploading files, then add a meta tag with the following information to the page that is identified as the Default URL in Google Analytics:

GooGhywoiu9839t543j0s7543uw1 - pls add {INSERT EMAIL ADDRESS} to GA account {INSERT UA-ID} with ‘Manage Users and Edit’ permissions - date {INSERT DATE}.

**Comment by desigonz** [comment]
This repo: https://github.com/cityofaustin/Residential-Permitting

**Comment by desigonz** [comment]
Also use my email address!

**Comment by chiaberry** [comment]
i found this in the source of permittingatx, UA-106861757-1

**Comment by desigonz** [comment]
Yeah we have the UA code but we don't have access to view the analytics 🙃

**Comment by easherma** [comment]
The site appears to be deployed through cloudcannon, there are credentials in 1Password but they don't work.

**Comment by easherma** [comment]
We got in, creds are updated in 1Passwrod. 
https://permittingatx.com/analytics.txt Is added and live on the site!

**Comment by desigonz** [comment]
Thank you Eric! I just submitted the form to try to gain back access 🤞
