### ISSUE TITLE
Upgrade to wagtail 2.7

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3393]
We have a branch open for this already:
* update to to latest in staging
* check for anything broken/check upgrade considerations
* see if new features also lead to any improvements we'd want to take advantage of (like hooks, etc)
* implement, test any changes in staging
* push to prod

**Comment by desigonz** [comment]
- [ ] Merge master into the branch
- [ ] Assign @desigonz to QA (and she might reassign)

**Comment by easherma** [comment]
https://joplin-pr-wagtail-27-test.herokuapp.com/

**Comment by desigonz** [comment]
## Need to fix before this PR can go to staging
I QA'd all of the things and only found a few things we need to look into further:
- [ ] Let's talk about how we can test documents—I know that Wagtail 2.7 includes [changes to document serving on remote storage](https://docs.wagtail.io/en/v2.7/releases/2.7.html#changes-to-document-serving-on-remote-storage-backends-amazon-s3-etc) and I want to make sure we don't break documents when this goes to production
- [ ] Guide sections streamfields aren't working—see GIF below
![3393-guide-sections](https://user-images.githubusercontent.com/5839508/69999283-e517d280-151d-11ea-9b0d-087e9a7311bc.gif)

## Notes for design/content
The below shouldn't stop us from merging the PR, but will want to demo to them at content pin-up on 12/3 before having it go into production
- New streamfield design
- Ability to add links for phone numbers
  - There's also the ability to add anchor links, but not sure how this actually works or is applicable to us at the moment? Need to look into this further.
- Users can now update their own user names—we'll want to decide if we want to turn this off for editors and moderators

**Comment by desigonz** [comment]
@easherma Can you give an update on the status of this issue? Thanks!

**Comment by easherma** [comment]
@desigonz this should be ready for QA again at 
https://joplin-pr-wagtail-27-test.herokuapp.com/

To test documents, you'll need to upload something(as it'l be pointing to documents in prod that aren't in the staging or review bucket), then test that the doc link works. I set the link behavior to 'direct', so it should use the s3 url of the document. We can discuss that setting during a dev sync.

**Comment by easherma** [comment]
Tech debt for later: construct_page_listing_buttons is now a hook, so we might be able to replace/streamline some of how custom code for those buttons.

**Comment by desigonz** [comment]
QA complete, looks great! When you merge, please let the content and design teams know, since the new streamfield behavior will be unexpected.
