### ISSUE TITLE
Create dummy test case data for Joplin

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#3396]
We need test data that can handle all permutations of use cases that we run into on Joplin. We also need a way to easily update/migrate that data.

**Comment by briaguya** [comment]
I'm going to get a start on this because I plan on using test data for incremental build stuff

**Comment by briaguya** [comment]
@desigonz i turned this into an epic and made a smaller mvp issue under it which has now been merged into staging.

There were some good ideas for future test data stuff in comments on this pr https://github.com/cityofaustin/joplin/pull/465, so I figured this gives us a place to put those all together
