### ISSUE TITLE
Return to Joplin main page after publishing

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3401]
## Describe the bug
After you publish a page, Joplin takes you to https://joplin.herokuapp.com/admin/pages/3/, but it SHOULD be taking you to our new main page: https://joplin.herokuapp.com/admin/pages/search/

## URL
Joplin

## To Reproduce

1. Go to Joplin
2. Edit a page
3. Click "update" to publish the change

## Current behavior
After you publish, Joplin takes you to https://joplin.herokuapp.com/admin/pages/3/

## Expected behavior
Acceptance criteria
- [x] After updating a live page (from the page edit view), you're sent to https://joplin.herokuapp.com/admin/pages/search/
- [x] After publishing a page from draft (from the page edit view), you're sent to https://joplin.herokuapp.com/admin/pages/search/
- [x] After publishing from the content listing view (http://joplin-staging.herokuapp.com/admin/pages/search/), you're sent back to https://joplin.herokuapp.com/admin/pages/search/
- [x] After Deleting a page, you're sent to https://joplin.herokuapp.com/admin/pages/search/

## Additional context
It's mostly just irritating/unexpected/inconsistent, but not currently blocking anything.

**Comment by easherma** [comment]
![publish-janis](https://user-images.githubusercontent.com/10539855/68788010-2b0d0500-0608-11ea-8660-998ab63a84cb.gif)
![publish-joplin](https://user-images.githubusercontent.com/10539855/68788011-2b0d0500-0608-11ea-9691-f184ea939024.gif)
@desigonz I tested publishing triggering a build in staging for you

**Comment by robbobfrh84** [comment]
Yes. that's cleanup from the "Search-is-now-main-page". Shouldn't be too crazy!👍

**Comment by robbobfrh84** [comment]
I'm gonna add this criteria also.
- [ ] After Deleting a page, you're sent to https://joplin.herokuapp.com/admin/pages/search/

**Comment by desigonz** [comment]
Great!

**Comment by robbobfrh84** [comment]
This is PR is up and ready for QA @desigonz. Hopefully, this solved for any unknown cases, as we just ended up catching the `admin/pages/3/` url and redirecting to `admin/pages/search/` 

PR: https://github.com/cityofaustin/joplin/pull/480
Deployed:  https://joplin-pr-3401-return-after-pu.herokuapp.com/

**Comment by desigonz** [comment]
Looks amazing! QA passed.
