### ISSUE TITLE
Render TC and Topic Pages even without Top Service Links

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#3402]
In Joplin, Top Services are ideally required for Topic Collections and Topic pages. However, that isn't the case right now. And as a result our Janis pages are rendering strangely.

Our Janis pages could be written in a less brittle way to still render some information, even if a Top Service isn't selected. At least adding the title and description, if not the topic service links. This would be nice for future-proofing, and present-proofing.

Ex:
https://janis.austintexas.io/en/health-safety/disaster-safety-relief/
![Screen Shot 2019-11-12 at 1.59.22 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/13f79912-60b4-449d-8fc9-ad004cb20839)

https://janis.austintexas.io/en/health-safety/health-records-certificates-2/
![Screen Shot 2019-11-12 at 2.03.42 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/b248a110-3b36-4dd9-8f66-f9107405badb)

**Comment by chiaberry** [comment]
in PageSections/TopicCollectionCards we check for !!tiles && <div etc> but an empty array is true so it renders the div and tile group. But in the TileGroup we check for !!tiles.length && <title etc> which is false so it doesnt render.

**Comment by robbobfrh84** [comment]
Some more notes I had regarding the link @chiaberry caught that shows the bug as well 👇
- https://alpha.austin.gov/en/health-safety/healthcare-prevention/
- The tile container will link to the Topic Page >` Health classes and resources`
- `Health classes and resources` belongs to the "Topic Collection": `Healthcare and prevention`

Here are some of the issues I seeing/wondering about....
- "Topic Collections" does not have a way to select "top services" currently. 
- And, as @Niicck noted above, how do we handle topics without top Services? Wondering how hard it would be to fallback and fill in open *seats* in the top four service tile slots? 

.. things to consider 🙇‍♂️🤔🙇‍♀️

**Comment by desigonz** [comment]
We've implemented publishing requirements to make it so that this doesn't happen. Yay!
