### ISSUE TITLE
Schedule 2020 Funshops

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3410]

**Comment by desigonz** [comment]
- [ ] decide on dates
- [ ] get them in TRAIN
- [ ] look into booking rooms

**Comment by annieszot** [comment]
Calendar hold on dates for Funshop I: Writing for residents: 
March 25, 2020 10am-noon 
June 17, 2020 10am-noon 
September 23, 2020 10am-noon
December 16, 2020 10am-noon

Will request booking City Council chambers for all

**Comment by annieszot** [comment]
Contact (Alex Medina) to book rooms at City Hall notified me that boards/commissions/city council meetings are currently being scheduled for 2020 and to check back with him in mid-December for the City Chambers' availability.

**Comment by annieszot** [comment]
Course descriptions sent to Julie Bollman for TRAIN 11/22. Julie returns from OOO 12/2.

**Comment by annieszot** [comment]
TRAIN courses up. Needed to include an instructor, so Julie designated me but person can change. 
Location still tbd
[Wednesday, March 25, 2020](https://apps.austintexas.gov/training/students/class_details.cfm?class_id=3347005)
[Wednesday, June 17, 2020](https://apps.austintexas.gov/training/students/class_details.cfm?class_id=3347008)
[Wednesday, September 23, 2020](https://apps.austintexas.gov/training/students/class_details.cfm?class_id=3347014)
[Wednesday, December 16, 2020](https://apps.austintexas.gov/training/students/class_details.cfm?class_id=3347015)

**Comment by annieszot** [comment]
Location spots confirmed - City Council Chambers for March, June and December.
