### ISSUE TITLE
Joplin UI inventory

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#3415]
design debt!

Step one of shaping the Joplin UI, and making it more consistent.

**Comment by desigonz** [comment]
Sprint 44 goal:
- [ ] categorize elements in the interface and add to UX artboards

**Comment by chasechenevert** [comment]
Here's the inventory so far https://xd.adobe.com/view/534c38fe-6d68-4732-5d6c-be975887f3c3-257d/

**Comment by desigonz** [comment]
Is this issue ready to close?

**Comment by toribr** [comment]
It's probably not 100% but complete enough to close.
