### ISSUE TITLE
Pushing Joplin UI forward: joplin design, II

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#3416]
Recreate surveyed components in XD for Joplin, and make improvements

**Comment by desigonz** [comment]
By end of sprint 45, will come away with recommendations about the changes we want to make and will start conversations with the content team about the changes we want to make.

**Comment by easherma** [comment]
@toribr in case it comes in handy we do have the wagtail style guide up here if its helpful for grabbing components:
https://joplin-staging.herokuapp.com/admin/styleguide/

(apologies the tabs components are a bit glitchy due to some of the tweaks we made to them for the edit page)

**Comment by chasechenevert** [comment]
Here's my first pass for the service page; this isn't exhaustive and is intended to help steer the conversation and shape a long-term vision. I've added style and position columns to help clarify what's being changed (second screen): 
https://xd.adobe.com/view/2c0a7d2c-8150-4159-703c-e4f2514ce233-5a3b/

Components that were covered in this effort: 
- Site header
- Page heading and tabs
- Lefthand nav
- Panel 
- Form elements

Not covered in this effort: 
- Modals
- Any other pages
