### ISSUE TITLE
Design for pending translation UX

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3418]
- [ ] Design options by end of sprint

_From #3347 pin-up notes_

Discussed issues around adding a persistent message on pages that haven’t been translated to a language that appears in the global nav. We’re doing exploratory work so this should still be relatively low-fi with the goal of trying to show different strategies.

**What we discussed**
- Our translation model works field-by-field as opposed to per page, and not all fields are required
- This could get complicated quickly when we support more languages (Arabic and Vietnamese)

**Future state ideas**
- Residents can request translation for a page which could help to prioritize pages which need translation
- Residents can sign-up for user testing (CTA)

**Next steps**
Iterate on a few ways to deliver an alert to the user when the user selects Spanish in the global nav:
- [x] Tool-tip on mouse-in for spanish
~- [ ] One-time modal or toast dialogue upon selecting language~
~- [ ] Message in right-rail, something else for Guides (no rails)~

**Comment by chasechenevert** [comment]
**Notes from pin-up**
XD Link: [Alpha_Janis_Language alert_drafting](https://xd.adobe.com/view/f345d089-c468-491f-5b68-ef18ad4bcbd9-8574/)

- Chevron next to the language 👍 
- Links 👍. Content would like ability to point users to a page about how Alpha is approaching translation, or to sign up for user testing, etc. No need to fit a tile within this accordion as it might take up too much space.
- When we have more languages to support this solution will have to be revisited as it will be a challenge to expose all human-translated languages within the global nav.

**Next steps**
- [ ] Users with Spanish localization that arrive on Alpha will automatically default to the Spanish version of Alpha, what should that experience look like? We definitely don't want the accordion to open on each page they click, but we also want to communicate at least once that not all information is translated yet.
- [ ] Develop MVP acceptance criteria (interactions, states)
- [ ] Microcopy for message text from Content in Spanish

**Comment by desigonz** [comment]
I made #3442 for a content strategist to develop microcopy for this.

**Comment by desigonz** [comment]
Wrote up acceptance criteria for dev in #3500, please update any criteria there..
