### ISSUE TITLE
Play around with Django hours module

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3420]
- [ ] @easherma to set it up so @toribr and @chasechenevert can play around with it??
- [ ] design team has early wireframe drafts by end of sprint

**Comment by easherma** [comment]
@toribr  I have a working version up, though it's quite rough around the edges:
https://joplin-pr-recurring-dates.herokuapp.com/admin/snippets/base/recurringrules/ <-- this would be to create a set of rules as a single snippet

Just as an example, I added 'Exceptions' to Contact snippets:
https://joplin-pr-recurring-dates.herokuapp.com/admin/snippets/base/contact/
