### ISSUE TITLE
Drupal 8 QA weekly update

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#3422]
**Objective** 
To give the overview of weekly work.

------
- [x] Component based testing(page -Sidebar - components)
- [x] Finish Colony park
- [x] Revisit the EMS to check re-introduced bugs
- [x] Feedback on fixed bugs
- [x] Meet Drupal Team to discuss next steps
- [x] Check-in with Desi  to discuss the updates, nextsteps

**Comment by anukandimalla** [comment]
**Nov 17- Nov 23**

- Updated  COA burn-down document - assists in analyzing the Bug fix success rate 
- Participated in COA internal team to discuss some UX fixes and UI functional fixes(Hero's,Main Nav,Sidebar label links etc.. )
- Gave feedback on the bug fixes
- Reported some New bugs introduced from Bug fixes

**Comment by anukandimalla** [comment]
**Nov 25 - Nov 30**

- Reviewed Micro sites EMS,Colony park and Rundberg
- Gave Feedback on bug fixes
- Reported Microsites new issues

**Comment by anukandimalla** [comment]
**Dec 2 - Dec 6**

- Gave feedback on more than 25 reported issues
- Reported New issues 
- Met Drupal Team in person as general check-in
- Discussed some UX/UI fixes specially Subscribe input fields and side bar cards

**Comment by desigonz** [comment]
Nice work!!!
