### ISSUE TITLE
Draft OPO official doc summaries + titles

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3424]
Mia will deliver this week, we will need to turnaround in about 2 days.

Maybe let's train the whole content team on this!

**Comment by srigdon** [comment]
Batch of two disciplinary memos sent 11/20, titles and descriptions drafted 11/21, posted on [the official documents page](https://alpha.austin.gov/en/health-safety/police-oversight-2/police-feedback-and-records/official-complaint-and-discipline-documents/) 11/22.

**Comment by srigdon** [comment]
Training scheduled for the next batch, see #3463
