### ISSUE TITLE
Meet with Nameir to kick off Writing Lab planning

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3426]
**Objective** 
We're launching Writing Lab! @annieszot and @srigdon will be meeting with @majette8 early during the week of Nov. 18 to flesh out logistics.

**Participants**

**Agenda**

------
- [x] Schedule meeting
- [x] Meet
- [ ] Create resulting issues

**Comment by annieszot** [comment]
Scheduled for Wed. 11/20/2019 at 11:00 a.m.

**Comment by annieszot** [comment]
Next steps
- [ ] Set up Writing Lab email (Service NOW and Help desk) 
- [ ] Set up Calendly (credentials received from Nameir) 
- [ ] Create messaging for Funshop
- [ ] Determine educational messaging on ODD and what Writing Lab offers - share during Writing Lab or posted
- [ ] Study St. Edward University's Writing Lab and incorporate best practices from there and other local universities/community colleges 
- [ ] Create "pre-survey" or questionnaire for folks coming to Writing Lab 
- [ ] Set Writing Lab launch date (early 2020; possibly sprint 48 - Jan 23) 

Proposed structure of Writing Lab from the [Funshop engagement plan](https://docs.google.com/document/d/1jGWdYYquXlK0dXkQbzwXRpfY1zHtqVok7cJl11ofmJg/edit#) 
Pre-survey - how did you hear about us, what problem are you trying to solve, what’s your goal by the end of this office hour (sent before appointment)
