### ISSUE TITLE
Plan for Writing Lab content

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3427]
**Objective** 
@annieszot and @srigdon to meet with @kriskristin during sprint 44 to discuss Writing Lab content/structure

**Participants**

**Agenda**

------
- [x] Schedule meeting
- [ ] Meet
- [ ] Create resulting issues

**Comment by annieszot** [comment]
Proposed scheduled meeting Thursday, Nov. 21.

**Comment by annieszot** [comment]
Content brainstormed planning ideas captured in [Funshop Engagement Guide](https://docs.google.com/document/d/1jGWdYYquXlK0dXkQbzwXRpfY1zHtqVok7cJl11ofmJg/edit#) for #3459 
Copy:

**Comment by annieszot** [comment]
Notes from the great @srigdon [Writing lab research and prep](https://docs.google.com/document/d/16m34hnbno2VoeHI6gqZayaxT2ORNWfRFwoEW7ktv55k/edit)

**Comment by annieszot** [comment]
Next steps/ new issues (details in notes)
@annieszot Create (or find) a spreadsheet: 
@annieszot Schedule whiteboarding session to redesign the intake form and spell out the customer journey 
Draft an overview message of what we do - enveloped in ^ whiteboarding session 
@kriskristin Draft business goals behind intake (Nameir might have this) 
@srigdon Available to help with above tasks if needed

**Comment by kriskristin** [comment]
Added business goals regarding intake form to the notes from the meeting.
