### ISSUE TITLE
Grid adjustment for information page content type

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#3429]
## Describe the bug
The body content on information pages is too narrow due to the grid column span not matching other content types.

## To Reproduce
1. Go to https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToyMjQx
2. See that the main body content is narrower than other page types. 

## Current behavior
Content currently only spans 8 columns, but it should span 10.

## Expected behavior
- [x] Change `.col-md-8 ` to `.col-md-10 `

## Screenshots
**Before**
![Screen Shot 2019-11-15 at 1 28 15 PM](https://user-images.githubusercontent.com/7027270/68970180-4f094b80-07ac-11ea-905b-5ea840cc7439.png)

![Screen Shot 2019-11-15 at 1 22 18 PM](https://user-images.githubusercontent.com/7027270/68970207-57fa1d00-07ac-11ea-8723-509b5b717ccf.png)

**After**

![Screen Shot 2019-11-15 at 1 21 58 PM](https://user-images.githubusercontent.com/7027270/68970220-5e889480-07ac-11ea-987d-e762344cf16e.png)

**Comment by chasechenevert** [comment]
This alignment should match with the header, but in most cases they don't. I'm updating the spec to better reflect this relationship. So far these pages are: 
- Service
- Information
- Official document

Text blocks with rails (which may or may not have any components/content within them) are on these pages: 
- Department
- Service
- Information
- Official document

**Comment by chiaberry** [comment]
@desigonz does this still need more details, or is it ready to go with the current acceptance criteria?

**Comment by desigonz** [comment]
I think it's good to go but let's double check with @chasechenevert

**Comment by desigonz** [comment]
@chasechenevert gave us the go-ahead!

**Comment by chiaberry** [comment]
@chasechenevert , should I change the official document page to also have a width of col-md-10? it is currently set to 8

currently: ![Screen Shot 2019-12-06 at 10.23.28 AM.png](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/e5047fe0-2159-46d4-a01c-b4602633ad40)

with set to 10: ![Screen Shot 2019-12-06 at 10.23.45 AM.png](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/b1b90e44-adce-4688-af70-6ec3ddf7384c)

**Comment by chiaberry** [comment]
@desigonz  here is it for QA: https://janis-3429-grid-adjustment.netlify.com/preview/information/UGFnZVJldmlzaW9uTm9kZToyMzM4

I did not change the official document page as I asked above b/c the specs says the content should match the heading and I think with it set more narrow it matches, but I am not 100% sure if that's what is right.

**Comment by desigonz** [comment]
I believe official documents are good as-is. Assigning @chasechenevert to QA.

**Comment by desigonz** [comment]
Okay I'm going to say QA is complete because it looks good to me. Thanks!

**Comment by chasechenevert** [comment]
Sorry for being so late to seeing this, but yes this is good to go!
