### ISSUE TITLE
Implement feedback component translations

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3431]
The feedback component isn't localized for Spanish :( 
![image](https://user-images.githubusercontent.com/5839508/68972214-e4a6da00-07b0-11ea-8829-c81799f52218.png)

**Acceptance criteria**

- [ ] When using alpha.austin.gov in Spanish, these translations appear:

| English copy        | Spanish copy           |
| ------------- |-------------|
| Did you find what you were looking for on this page?     | ¿Encontró lo que estaba buscando en esta página? |
| Yes     | Sí      |
| Please tell us more about your feedback. We'll use this information to improve the site. | Por favor díganos más sobre su opinión. Usaremos esta información para mejorar el sitio.      |
| Character limit: 0 of 2000 | Límite de caracteres: 0 de 2000      |
| Submit | Enviar      |
| We have received your feedback. | Hemos recibido sus comentarios.      |
| Thank you for helping improve this website! | ¡Muchas gracias por ayudarnos a mejorar este sitio web! |

**Comment by chiaberry** [comment]
@desigonz  Is there a translation for "Sorry, we had trouble receiving your feedback.
                    Please try again or email" the error message?

**Comment by desigonz** [comment]
Sorry about that! Here's the translation. 

> Lo sentimos mucho, tuvimos problemas para recibir sus comentarios. Por favor inténtelo de nuevo o envíe un correo electrónico a feedback@austintexas.gov.

**Comment by chiaberry** [comment]
@desigonz ready for QA https://janis-3431-feedback-spanish.netlify.com/es/

its going to always error since this site isnt in the  list of approved origins. I can add it after you test the error message if you want to check out the successful flow

**Comment by desigonz** [comment]
Great! Let's just verify the other translations on staging/prod before closing this issue. For now QA is complete.
