### ISSUE TITLE
Content team retreat to the library

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3435]
This issue needs more documentation. We will meet to discuss professional development, content roles, and how our team can support each other and the ODD Flock in a sustainable way.
- [x] What are the goals, objectives, outcomes?
- [x] What materials are needed before, during, and after?
- [x] What is the follow up?

**Comment by annieszot** [comment]
I'm in need of friendly reminders <3 Confirmation, please, on room reservation? Where in the library are we meeting? Is our retreat in place of content pin-up Tuesday, November 26 at 1?

**Comment by annieszot** [comment]
Thanks @Jo-Dwyer !
For goals — Start with: I want for content strategists to feel supported in our work, identify opportunities for professional development, feel they can support ODD in a sustainable way.
For objective — Start with: During this experience, content strategists will 
- [ ] decide workflow for accepting work outside of our austin.gov transitions
- [ ] Figure out how to encourage our colleagues to ask for our skills without detracting from our larger goals of transitioning to austin.gov
- [ ] Come to table with professional development opportunities. Look for professional  development opportunities - how to define/communicate what skills want to develop now and further career development. 
- [ ] Communicate how we'll feel supported in our roles.  
For outcomes — Start with: At the end of this experience, content strategists will be able to
- [ ] Share a workflow with ODD flock 
- [ ] Apply for professional development opportunities (ex. conferences, etc) that are interesting and invigorating. 
- [ ] Feel resilient and choose professional development opportunities to walk into new roles

**Comment by annieszot** [comment]
**Suggested** materials for the retreat:
**Snacks**
- [ ] Hummus and pita/veggies 
- [ ] Chocolate
- [ ] Almonds 
- [ ] Grapes 
- [ ] Bread and jam (jam and bread lol Sound of Music ;) ) 
**Whiteboard erase markers**
**Sharpies and stickies?** More eco friendly version? 
**Laptops and chargers**
**Playlist** @srigdon ? ;) 

Shall we come to the retreat prepared with what the goals (outlined above) mean to each of us then share at the retreat? Then the remainder of the retreat is devoted to achieving the objectives?

**Comment by annieszot** [comment]
Follow-up 
Suggested artifacts: 
-Team Charter or Team agreement
-Issues in Github 
-Agenda items in pin-up

**Comment by srigdon** [comment]
A few relevant documents are in [this folder](https://drive.google.com/drive/folders/1LEtQSyD17uyjPZH2ldlmHsq0T4EdlBQF).
