### ISSUE TITLE
Agenda for Content Pin-up - 11-19-19 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#3440]
Last content pin-up #3350 

🚦Approve agenda
-->Approve or add missing agenda items 
Agenda approved
:pushpin: Action items from Design pin-up cc/ @toribr @chasechenevert 
Improve workflow between Content and Design 
Ways to improve: Content team - Turn on Techstack notifications on Github

💼 It's business time - larger discussions
@ablangworthy location microcopy
Slack convo 
@ablangworthy27 Guide titles and character limits 
@desigonz Jurisdictions share-out 
@annieszot #3132 Janis/Joplin intro into Funshops 

💻 Content sprint goals
Checking in on...anyone need help?
Sprint 44

🏁 Roadmap
What's coming up
👩‍🏭 Workshop
Future pin-up: workshop pools and spas guide titles 
🤓Review assignments
🏖 OOO
🌵ETC
10-15 to talk about content cove retreat #3435 
🏃Next Steps
Testing debt GH label
Next few sprints- enforcement on character limits (related to workshopping guide titles)

**Comment by desigonz** [comment]
Can I have a few minutes to talk about jurisdictions?

**Comment by annieszot** [comment]
Of course @desigonz ! Go ahead and add it. No need to ask in the future :)
