### ISSUE TITLE
Microcopy for pending translation UX

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3442]
- [ ] Content strategist to author copy for #3418 (something along the lines of "This website is a work in progress and might be missing some translations"; maybe include a call to action to [participate in user research](https://alpha.austin.gov/es/feedback).)

### As a content editor, I want Spanish-speaking residents to have a positive user experience on austin.gov even when we haven't received translations for a page, so that they can access City services and place trust in the City.

This is a bigger issue that we'll want to break down into incremental changes/features.

**Is your feature request related to a problem? Please describe.**
Sometimes, we have English content for a page and not the translations. This might happen because it's urgent to publish at least in English, or the hand translations take a while to get back to us, or because someone forgot to add the Spanish translations. 

What happens now on Spanish pages is: if a content editor hasn't added a translation to a field, that field will fallback to the English level. 

This isn't a great user experience, and there's a lot of room for error on the content editing side of things.

**Comment by ablangworthy27** [comment]
@desigonz I have drafted and made a comment in the [XD file ](https://xd.adobe.com/view/f345d089-c468-491f-5b68-ef18ad4bcbd9-8574/).

I just need to send for translation.

**Comment by desigonz** [comment]
This is out for translation. I'm going to close the issue for now, but @ablangworthy27, send those translation onto @chasechenevert when you get them.

**Comment by ablangworthy27** [comment]
@chasechenevert please see below for English and Spanish translation. I'll also add to the XD file.

Translations for this website are a work in progress. 

If you would like to help us improve, please sign-up to participate in user research. 
------------------------------------------------------------------------------------
Continuamos trabajando y procesando las traducciones en este sitio web.

Si le gustaría ayudarnos a mejorar, por favor inscríbase para participar en nuestras investigaciones de usuarios.
