### ISSUE TITLE
Review and edit the mobile food vendor permit guide

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#3453]
The guide has been reviewed and approved! Illustrious content folks, your mission is to review it for clarity and consistency. 

- [x] 1st review: @annieszot, please and thank you. Review due Thurs 12/5

- [x] 2nd review: @ablangworthy27, do you have availability? Review due Thurs 12/12

What do you think, all, could we do these reviews concurrently? 

You'll need: 
- [Google docs](https://drive.google.com/drive/folders/12EiRDN5XytRf2ePN41YjkjK7HTIPNo9z) with the most updated version of the copy
- It's the same version in Joplin (Title: Mobile food vendor permit guide, Author: Rigdon), except that the "Get a food manager certificate or food handler training" page is giving me an error every time I try to edit it, see #3446. The updated version of that page is in the Google doc, though. 
- to reach out with any and all questions as you go

**Comment by annieszot** [comment]
Roger @srigdon !

**Comment by ablangworthy27** [comment]
@srigdon @annieszot I can take the second review when you are ready.

**Comment by annieszot** [comment]
Before I dive too deep @srigdon, these review cycles are for sprint 45? 
Concurrent reviews are going to scramble the review process. Best to keep it clean with one review,  @srigdon accepts or rejects edits, then pass on polished copy to the next review. It's really hard to swim through google doc comments/suggested edits when they haven't been accepted/rejected by the author. 

Editing for clarity and consistency-- I've been editing for active/passive voice and grammar as well as clarity and consistency. And keeping our editing checklist and the digital style guide in mind. Am I correct in my approach to this first round of review? 

Reviewed so far (for documentation purposes): 
- [x] Apply for a food vendor operational permit - service page
- [x] Bring your mobile food vendor unit to your inspection appointment - service page
- [x] Businesses required to get a mobile food vendor permit in Austin - information page

**Comment by srigdon** [comment]
> Before I dive too deep @srigdon, these review cycles are for sprint 45?
Yes, next sprint sounds way more achievable than this one, but let's update if it's taking longer.  

> Concurrent reviews are going to scramble the review process. Best to keep it clean with one review, @srigdon accepts or rejects edits, then pass on polished copy to the next review. It's really hard to swim through google doc comments/suggested edits when they haven't been accepted/rejected by the author.
Makes sense to me! Let's do it one at a time. 

> Editing for clarity and consistency-- I've been editing for active/passive voice and grammar as well as clarity and consistency. And keeping our editing checklist and the digital style guide in mind. Am I correct in my approach to this first round of review?
Yes, that sounds great!

**Comment by annieszot** [comment]
- [x] Mobile food vendor permit types and fees - Info page
- [x] Contacts and documents for mobile food vendors - Information page
- [x] Documents for mobile food vendors in Austin - Information page
- [x] Fire safety checklist for mobile food vendors - Information page
- [x] Get a central preparation facility - Service page 
- [ ] **EMPTY** Mobile food unit inspection checklist for vendors - Information page
- [x] Mobile food vendor permit pre-application checklist - Service page
- [x] Prepare your mobile food vendor permit application  - Service page
- [x] Renew your mobile food vendor permit - Service page
- [x] Report changes to your mobile food business for valid permit - Service page
- [ ] **Content debt** Request an exemption to the mobile food vendor permit - Service page
- [x] Requirements to safely operate your mobile food business - Info page

Suggested edits added @srigdon. Ready for @srigdon to accept or reject edits then @ablangworthy27 can review. 

-I did miss some consistency with measurements (ex. ft/feet)

**Comment by srigdon** [comment]
Very good edits incorporated! Thanks, @annieszot. Now on to @ablangworthy27's scrutiny.

**Comment by srigdon** [comment]
Edits incorporated, plus a few by the EHSD team. Closing, onto #3472 and #3607.
