### ISSUE TITLE
Determine educational messaging on ODD and what Writing Lab offers

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#3458]
Out of #3426 
Relates to but different than #3457 
Answer: Is the goal of educational messaging to funnel people to where they can get the best help? Or to just let them know who we are? Ideally, both.

**Comment by annieszot** [comment]
Will discuss during Writing Lab soft launch on Monday, Dec. 16, 2019

**Comment by srigdon** [comment]
[Draft started](https://docs.google.com/document/d/1LcVPtnualL0lomVJO3jAi2ziPxbct7iRx5UAD3enc1o/edit)

**Comment by sammodabber** [comment]
Review in pin up @ablangworthy27
