### ISSUE TITLE
Add location page to the create content modal

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3462]
- [ ] [Create content modal matches mocks—copy and design](https://xd.adobe.com/view/735f227f-ddc9-4438-6724-a9c74c112837-056e/)

**Comment by chiaberry** [comment]
https://joplin-pr-3462-location-modal.herokuapp.com/admin/ for QA

**Comment by desigonz** [comment]
Looks good! I noticed one thing:

- [ ] change "Location Title" to "Location name" (and note the lowercase "n")

![image](https://user-images.githubusercontent.com/5839508/70462462-881d9e80-1a80-11ea-9d38-b8afa1074db3.png)

**Comment by chiaberry** [comment]
@desigonz updated the copy!

**Comment by desigonz** [comment]
great! QA complete. I'm going to message to the content team that while the location content type is set up in Joplin, it's not set up to publish out on Janis yet.
