### ISSUE TITLE
Training: OPO document writing

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3463]
**Objective** 
@srigdon will train the content team in writing OPO official docs. By the end of the meeting, all content strategists will be equipped to write official doc titles and summaries.

**Participants**
@srigdon @ablangworthy27 @annieszot @Jo-Dwyer 

**Agenda**

------
- [x] Schedule meeting (@srigdon to schedule)
- [x] Meet
- [ ] Create resulting issues

**Comment by desigonz** [comment]
FYI next document delivery date is 12/4

**Comment by srigdon** [comment]
Meeting scheduled for 12/5. Let me know if that time doesn't work for anyone.

**Comment by annieszot** [comment]
@ablangworthy27 and I will notify @srigdon if we're running late on 12/5. We have a 1:30-2 pm meeting at City Hall that day, but it's possible we'll make it to the meeting on time.

**Comment by srigdon** [comment]
@annieszot @ablangworthy27 I moved the meeting up half an hour.
