### ISSUE TITLE
H3 padding

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3464]
## Acceptance criteria
- [x] Bottom margin removed from `h3`

## Describe the bug
There's something funny looking about the `h3` paddings here 
![image](https://user-images.githubusercontent.com/5839508/69381842-3f41a980-0c7b-11ea-93e3-7cd3a248f1d2.png)

## URL
https://alpha.austin.gov/en/preview/guide/UGFnZVJldmlzaW9uTm9kZToyMjY2#Learn-and-prepare-1

## To Reproduce
Steps to reproduce the behavior 
example: 

## Current behavior
A clear and concise description of what happened

## Expected behavior
A clear and concise description of what you expected to happen

**Comment by chasechenevert** [comment]
## Solution
- [ ] Remove bottom margin from H3

**Comment by desigonz** [comment]
Thanks @chasechenevert! Reassigning the issue for dev.

**Comment by briaguya** [comment]
made this a 3 not a 1 because we need to make sure we don't introduce other weird stuff

**Comment by chiaberry** [comment]
for QA: https://janis-3464-h3-padding.netlify.com/

**Comment by desigonz** [comment]
Thanks @chiaberry! I want to check that we've not causing regressions with this. Do you have examples of `h3` on non-guide pages?

**Comment by chiaberry** [comment]
@desigonz  Farah's name is an h3: https://janis-3464-h3-padding.netlify.com/en/police-oversight/, and the name under Contact information (Office of Police Oversight) is also an h3

**Comment by desigonz** [comment]
@chiaberry Thanks! Seems like QA passed—did you catch any regressions with the snapshot tests?

**Comment by chiaberry** [comment]
@desigonz no I didnt find any, but the tests dont have the best coverage. if one slips through the cracks it will be a good storybook story to write

**Comment by desigonz** [comment]
@chiaberry Good idea. I've marked this issue as "QA passed."
