### ISSUE TITLE
Add Spanish translation for collection schedule app

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3465]
## Describe the bug
Missing Spanish translation for "Here's the pickup schedule for 800 Guadalupe St, Austin"

![image](https://user-images.githubusercontent.com/5839508/69432461-5fb34780-0cff-11ea-92df-3e0c1edd8559.png)

Also, we have an updated translation for the invalid bulk collection date message at the bottom, so I'm throwing that into this issue
![image](https://user-images.githubusercontent.com/5839508/69432654-bb7dd080-0cff-11ea-8573-b3b8b26b00a1.png)

## URL
https://alpha.austin.gov/es/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to https://alpha.austin.gov/es/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup in Spanish
2. In step three, type in an address and press enter
3. See error

## Current behavior
English text reads `Here's the pickup schedule for [address]`

## Expected behavior
- [x] Spanish text should read: `Horario de recolección para [address]`
- [x] "Currently, no upcoming bulk item collection date has been scheduled. Please check back soon." should translate to `Actualmente no hay una ninguna fecha de recolección de artículos grandes programada. Por favor vuelva a consultar pronto.`

**Comment by chiaberry** [comment]
https://janis-3465-collection-spanish.netlify.com/es/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup

**Comment by desigonz** [comment]
Beautiful! QA complete.
