### ISSUE TITLE
Whiteboard Session (intake form, customer journey, messaging) 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#3467]
- [x] Schedule meeting
- [x] Send agenda
- [x] Meet
- [ ] Create issues 

Related: #3427 
Whiteboarding session w/ @kriskristin @srigdon @annieszot to redesign the intake form and spell out the customer journey (customer: any customer coming to ODD with a need, so we can message holistically) 
Funshop attendees
SDL trainings/workshops
Writing lab
Office hours 
- Draft an overview message of what we do (Funshops, trainings, office hours/writing lab)

**Comment by desigonz** [comment]
Goal by the end of this is to have new messaging on intake form for Writing Lab

**Comment by annieszot** [comment]
Agenda 
-Pull up intake form, choose whiteboard
->What do we know is true? There is an intake form for ODD
->What problem are we trying to solve? Holistically message ODD offerings by redesigning the intake form and spell out the customer journey (customer: any customer coming to ODD with a need). 
What needs when coming to ODD for:
Funshop attendees
SDL trainings/workshops
Writing lab
Office hours

**Comment by annieszot** [comment]
Digitally captured 
https://docs.google.com/spreadsheets/d/1bOKTEfYHNAP7nJS8rjfDJofKnMhoUU3LvA-MdAdqbB4/edit?folder=1T8K1HoUt1-TdKqDjdsbQQ2eC-dioiBKX#gid=0

Next steps
Overlap =combine efforts
Especially within Touchpoint 1,  2- learn about ODD 2, Follow-up 3 
Highlight similarities
Develop goal based personas
Develop writing lab personas, journey (beginning to end, entry points)
