### ISSUE TITLE
Automate phone number and email tags for WYSWYG content

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#347]
WYSWYG content phone numbers and emails are not automatically hyperlinking. See http://alpha.austin.gov/services/hazardous-waste-dropoff

Can we automate phone number and email tags in WYSWYG content so authors and publishers won't have to worry about it?

**Comment by amenity** [comment]
Cleaning out ancient, probably-no-longer-applicable, issues.
