### ISSUE TITLE
Map doesn't open to the correct address

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3470]
- [ ] When a user clicks the map, the Google map that opens in a new window shows a pin at the location indicated on the map

## Describe the bug
Clicking the location map in a service page keeps the address in the top right bar but doesn't display it on the map. The map shows the default (where I am). (Thanks for catching this one @srigdon!)

[Find work as a day laborer](https://alpha.austin.gov/en/jobs/job-resources/help-finding-work/find-work-as-a-day-laborer/)

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to [Find work as a day laborer](https://alpha.austin.gov/en/jobs/job-resources/help-finding-work/find-work-as-a-day-laborer/)
2. Click on location map
3. See the google map open in a new tab
4. See location address in toolbar and the map centered on your own location <--- error

## Current behavior
The map isn't opening to the location but to the users IP location. You can still click 'search' in the address bar and navigate there, but it's not the...

## ...Expected behavior!
I thought clicking the link would bring me to a map centered on the location address with a little pin in that location!

## Device and browser
Chrome!

**Comment by chiaberry** [comment]
@desigonz  here is the app: https://janis-3470-map-address.netlify.com/

the joplin that is connected is https://joplin-pr-3227-permissions-mvp.herokuapp.com/admin/

**Comment by desigonz** [comment]
Hi! Thanks for the awesome work on this. I'm QAing but the thing I published on Joplin isn't pushing out the to Janis app you shared. I'd just like to test the day labor link—do you have a page with that map?

**Comment by desigonz** [comment]
QA passed! thanks!
