### ISSUE TITLE
Where did bullets go when I'm editing a service page?

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3481]
## Acceptance criteria
- [x] When adding a basic step, there is an option for bullets (`ul`) in the rich text block
- [x] When adding on option within a step with options, there is an option for bullets (`ul`) in the rich text block

## Describe the bug
I opened 'Get a birth or death certificate' for editing. The bulleted lists in the last two options are now just a big text block missing the list formatting. It also happened in 'Hire a day laborer' for @srigdon 

>Hire a day laborer --> The preview page made the list look fine but in Joplin all the formatting was removed somehow? Fixed [using markdown], good to go

[The live page as it should appear](https://alpha.austin.gov/en/health-safety/health-records-certificates-2/birth-death-certificates/birth-and-death-certificates-test/)
[The text as it looks in Joplin](https://joplin.herokuapp.com/admin/pages/65/edit/#tab-content)
[Preview mode](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyMzEw)

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to Joplin and open 'Get a birth or death certificate' for editing
2. Click on either '3-5 business days' or '2-3 weeks' 
3. Scroll down to the 'lists' of documents needed 

## Current behavior
I opened the page to edit the times and noticed that the lists documents were no longer showing up as bulleted lists, even though the live page is formatted in that way. I also don't see any way to add that bulleted list formatting at this point.

## Expected behavior
I expected to the see the lists with bullets since that's what's live right now and I opened that same version to update.

### How it should look when published
<kbd> <img src="https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/c555f6e0-3dfe-4885-b256-7f1c32a577bb" /></kbd>

### How it looks now in preview
<kbd> <img src="https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/fd76bf32-4043-4d50-ae4e-6d834f4b00e1" /></kbd>

## Additional context
I need to update the live version with some small edits, but I'm afraid that if I update the page, it will undo the lists and I don't see a way to put them back in with the editor!

**Comment by desigonz** [comment]
This bug fix is now in production.
