### ISSUE TITLE
Add captions to the 'Know your rights' videos

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#3483]
We have [English and Spanish scripts](https://drive.google.com/open?id=10xwixTOER6YYJRV8MGhettGZvPHOrg8p) to start from, but we need to caption the videos on the ["Know your rights" page](https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToyMjk2). 

@desigonz How should we proceed? Start conversations with transcription companies to get estimates? Handle this one in house for now and outline a process for the next video embed?

**Comment by desigonz** [comment]
I'll send out for captioning and make a little doc on how to request captions.

**Comment by desigonz** [comment]
Sent out videos for captioning/subtitling today via Amara.

**Comment by desigonz** [comment]
Started a "how to caption videos" doc here, more soon as all this progresses! https://docs.google.com/document/d/1tPKDcCE7FW0nPZCx_52HgYcDw3xHfUgoxtYE8iPBb4Y/edit#heading=h.gc9wyyhln972

**Comment by desigonz** [comment]
Caption files live [here](https://drive.google.com/drive/folders/1dBC2Fs9QKHFqFoWjc6OjA2Jz_jY9UYy7?usp=sharing) for the following two videos:
- Know Your Rights: The Right to Remain Silent
- Conozca Sus Derechos: El Derecho de Guardar Silencio

@srigdon let's connect about the status on Know Your Rights content—maybe it makes sense for you to prod them about who to connect with to get these caption files uploaded to YouTube?

**Comment by desigonz** [comment]
Sent out the 2 immigrants rights videos out for captioning and cc'd @srigdon

**Comment by desigonz** [comment]
Immigrants video captions are saved here: https://drive.google.com/drive/folders/1dBC2Fs9QKHFqFoWjc6OjA2Jz_jY9UYy7

Assigning @srigdon to send them off to ATXN folks to upload them to YouTube.

**Comment by srigdon** [comment]
Captions sent to ATXN.
