### ISSUE TITLE
Uploaded photos are broken on the draft for Municourt Dept Page

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3484]
## Describe the bug
Uploaded and inserted photos of leadership for the dept page and they are broken in the preview. 

[Preview of Municourt dept page](https://alpha.austin.gov/en/preview/department/UGFnZVJldmlzaW9uTm9kZToyMzI3)

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to Joplin and edit 'Municourt dept page'
2. Click on 'Choose an image' within  department directors
3. Open a preview

## Current behavior
Photos show up in the editor, not in preview

## Expected behavior
I expect to see the page as it will look when I publish it.

## Screenshots
<kbd><img src="https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/fd241b8e-24e5-4e3f-b2ad-e4d8dd119d85" /> </kbd>
<kbd><img src="https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/1d97f631-9b9d-4c5c-ad7e-d9b7fe6ea4db" /> </kbd>

## Additional context
I want to hand over a preview link for Municourt to approve and don't want to end it with broken pics.Hi! It looks like I need to make a folder for it, but I'm not seeing a way to do that.

**Comment by Jo-Dwyer** [comment]
It looks like if I could create a new collection in the images gallery then I could get closer to making it work?
<kbd> <img src= "https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/3d134e0c-fe57-49e4-a64f-4a2aca2c836b" /> </kbd>

**Comment by Jo-Dwyer** [comment]
Tried in staging with photos saved in the root collection and I'm having the same issue. 

[Check it out in staging](https://janis.austintexas.io/en/preview/department/UGFnZVJldmlzaW9uTm9kZToyMzI3)
[Edit in staging](http://joplin-staging.herokuapp.com/admin/pages/278/edit/#tab-content)

**Comment by desigonz** [comment]
And tried publishing in staging, still errors out:
![image](https://user-images.githubusercontent.com/5839508/69645425-c4d2aa00-102b-11ea-90b9-630819e36456.png)

**Comment by Niicck** [comment]
Alright, try looking at your prod preview again.

This was an environment variable config fix, so there is no code that needs to be pushed up.
It was an issue similar to that hotfix OPO saw, where building from a "publish" used different values than building from a github code push.

As far as getting those same images to appear in staging, it can be done. We just need to sync prod images into the staging images folder. It'll be implemented when we do this issue: https://github.com/cityofaustin/techstack/issues/3050

**Comment by desigonz** [comment]
Yayyy fixed in the prod preview! https://alpha.austin.gov/en/preview/department/UGFnZVJldmlzaW9uTm9kZToyMzY4 I'm going to close this issue.
