### ISSUE TITLE
Top-level aggregator pages - content review

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#349]
Finalize content and translations for top level aggregator pages so changes may be passed on to dev to implement and added to CMS.

Currently these pages are templated on janis and can be viewed by (but add pages as they come up)
- [ ] Topics --> http://staging.austin.gov/topics/
- [ ] Themes  --> http://staging.austin.gov/themes/
- [ ] Services --> http://staging.austin.gov/services/
- [ ] Departments --> http://staging.austin.gov/departments/

**Comment by amenity** [comment]
@LauraTrujillo - I'm not clear what this issue is for... 😛 Is it still relevant? Should it be broken into separate issues - design/content/translations or topics/themes/services/departments?

**Comment by LauraTrujillo** [comment]
@amenity I think you're right- it is a Content team review of the pages and it does pair with #352.
