### ISSUE TITLE
Go through records retention standard operating procedure copy 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#3491]
Out of #3390 when receive copy from #3490 
- [ ] schedule meeting
- [ ] meet
- [ ] create issues 
- [x] review copy re: SOP for records retention to be included in docs (style guide, somethign else) for joplin users

**Comment by sammodabber** [comment]
@srigdon to talk to Wayne to see if Stephen has signed off on this yet

**Comment by srigdon** [comment]
Update: 
Stephen has signed off on the SOPs. Upon review, the action there is to recommend and work into our training for new Joplin users as we migrate their content. CTM's RM: "It would be best for the web manager to check with the department’s records manager as often as necessary. In most organizations, records managers have a working relationship with web managers or communications reps in managing the content of web pages. The records managers would consult with them on the ownership, retention, and disposition of the content."
