### ISSUE TITLE
Pagination page transition (design)

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#3497]
Create a visual clue when using pagination so it's evident that a change has happened

Implement a page transition. Something like this would work:

https://codepen.io/novecentonove/pen/abbdjVj

**Comment by desigonz** [comment]
Assigning @chasechenevert to define this behavior

**Comment by chasechenevert** [comment]
Current idea:
- Resident clicks on a page number
- Page quickly scrolls back to top 
- After a very short delay (.3 seconds) documents populate/load

**Comment by desigonz** [comment]
@chasechenevert to add one last acceptance criteria for the transparent/white thing. Let's make a new issue for dev with acceptance criteria.

**Comment by chasechenevert** [comment]
I actually don't think we need to add any kind of wipe animation. If we can allow the header elements to load in with no delay, and only delay the display of the body content (list) it won't need any animation.
