### ISSUE TITLE
Guides workshop planning kick off

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3498]
**Objective** 
We're pairing with the Service Design Lab to develop a workshop model for guides. The goal is to develop a replicable, scalable workshop that can be used whenever we're transitioning content for a complex City process that will ultimately live as a guide. By the end of the workshop, we will have mapped a complex process, and a content strategist will be ready to begin writing a guide. 

Candidates for the next guides are:
- #2954 fixed food establishment permitting
- #2955 Farmer's market permitting
- #2956 Temporary food event

There might be a lot of overlap in the processes for these permits, so we might want to combine these into one workshop (or maybe not!) 

**Participants**
@desigonz just to join for the kick off
@srigdon will be the content strategist on this
Service designer: Kelsey (and with some support from @ChristopherLuedtke)

**Agenda**

------
- [x] Schedule meeting
- [x] Meet
- [ ] Create resulting issues

**Comment by srigdon** [comment]
Questions: 
- Which criteria make a service eligible for a guide content type? (What level of complexity? How do we define this?) 
- What does MVP content look like for each guide? 

Next steps: 
- Desk research on the three guides above (existing content, linked to in the issues)
- Review the draft of the [mobile food vendor permit guide](https://alpha.austin.gov/en/preview/guide/UGFnZVJldmlzaW9uTm9kZToyMjY2)
- Review the content team's editorial workflow process (in the works, gotta consolidate a few documents) 
- Review @kriskristin's [Guide testing synthesis document](https://docs.google.com/document/d/1Pf_s3j__MI9qaqbHGVdiERHonC0d9qcWEYZZJjIgnIs/edit) 
- Reach out to EHSD to ask: who are the teams who manage each of the permitting processes listed above? 
- Schedule time with @ablangworthy27 to ask for her perspective as she's drafted the pools and spas guide
