### ISSUE TITLE
Joplin add user tab menu

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#3499]
## Acceptance criteria
- [ ] Remove tab menu (when adding a user on Joplin, there is no tab menu)

## Describe the bug

Its hard to fill out the fields when adding a user on joplin because the menu tab bar is sticking and doesnt scroll with the window

## URL
https://joplin.herokuapp.com/admin/users/add/

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to https://joplin.herokuapp.com/admin/users/add/
2. Scroll
4. See error. the tab menu covers the fields and is sticky

## Screenshots
![Screen Shot 2019-11-26 at 3.11.39 PM.png](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/64551bbb-3ec7-4113-bc02-abd513c677ce)

## Additional context

joplin/css/pages/edit.scss  is where the tab-nav is being set as fixed, I believe in order for the page editor tabs to not move. But its affecting the users as well. make a new style?

**Comment by briaguya** [comment]
made this a 5 because we need to figure out what's going on with the roles tab itself, just hiding it is probably a 1 but it could have unintended consequences

**Comment by easherma** [comment]
My recommendation; we should probably just add a specific css class for the tabs on the edit page. No need to hide, it just make it not broken.

**Comment by chiaberry** [comment]
agree with Eric, I put the style that's affecting the tabs in additional context above.

**Comment by robbobfrh84** [comment]
@desigonz Ready for QA and Review: 

- PR link: https://github.com/cityofaustin/joplin/pull/522

- Deployed: https://joplin-pr-3499-floating-tab.herokuapp.com/

- Edit User Link: https://joplin-pr-3499-floating-tab.herokuapp.com/admin/users/3/#account

**Comment by desigonz** [comment]
Beautiful! QA passed
