### ISSUE TITLE
Develop UX Version of Funshop/Nerdshop for the UX community of practice

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#350]
<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] Develop curriculum

- [ ] Schedule test-run

- [ ] Refine curriculum

- [ ] Enter it in TRAIN

- [ ] Start sharing the goodness!
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://desi1.aha.io/features/RT-304

**Comment by ashleecoa** [comment]
Designshop!

**Comment by amenity** [comment]
@ashleecoa @cthibaultatx @LauraTrujillo @toribr So excited for this 🌱 to 🎄 ! Please divide into separate issues assigned to individual disciplines. 😏
