### ISSUE TITLE
Pending translation alert implementation

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3500]
- [x] [Design matches mocks](https://xd.adobe.com/view/f345d089-c468-491f-5b68-ef18ad4bcbd9-8574/)—waiting on @chasechenevert to update mock with the microcopy. (Let's include the English as a placeholder for now, and then we'll update the Spanish once @ablangworthy27 gets it back from the translators.)
  - [x] [Desktop](https://xd.adobe.com/view/f345d089-c468-491f-5b68-ef18ad4bcbd9-8574/screen/335a1865-2163-4498-9845-fa64ca3c9452/Translation-alert-MVP-Desktop)
  - [ ] [Mobile](https://xd.adobe.com/view/f345d089-c468-491f-5b68-ef18ad4bcbd9-8574/screen/ad2144f0-fb1e-4791-a567-a9756b749d2c/Translation-alert-MVP-Mobile)
  - [x] Copy is in Spanish and reads:
> Continuamos trabajando y procesando las traducciones en este sitio web.
> 
> Si le gustaría ayudarnos a mejorar, por favor inscríbase para participar en nuestras investigaciones de usuarios. 
- [x] Interaction
  - [x] When a user is on the English version of the site and select `Español`, alert appears and the site switches to Spanish
  - [x] From the Spanish version, user can click `Español` and the chevron to toggle close the alert, and can reopen it by clicking `Español` again
  - [x] From the Spanish version of the site, clicking `English` will take a user back to the English version of the site, no alert
- [ ] Users with Spanish localization that arrive on Alpha will automatically default to the Spanish version of Alpha: alert defaults to open for the first page they land on, but once they navigate to other pages, the alert doesn't appear (clarify this with @chasechenevert)

**Comment by chasechenevert** [comment]
Mocks updated with the English micro-copy.

**Comment by desigonz** [comment]
Spanish microcopy: 

Continuamos trabajando y procesando las traducciones en este sitio web.

Si le gustaría ayudarnos a mejorar, por favor inscríbase para participar en nuestras investigaciones de usuarios.

@chasechenevert can you update the mocks? Thanks!

**Comment by chasechenevert** [comment]
Mocks updated~

**Comment by chiaberry** [comment]
@chasechenevert  https://janis-3500-pending-translation.netlify.com/ is the deployed WIP

I haven't added the functionality for the dropdown to close if you hit esc, and obviously the styling isn't done, but here you go to play around with it

**Comment by chiaberry** [comment]
https://janis-3500-pending-translation.netlify.com/ for QA!

**Comment by desigonz** [comment]
@chiaberry Just one thing:

- [ ] Mobile visual design should match mocks (border across the full width of screen, no rounded corners)
Mock
![image](https://user-images.githubusercontent.com/5839508/70653724-a3bcac80-1c1a-11ea-9d12-dd969fbec7ff.png)
Implementation
![image](https://user-images.githubusercontent.com/5839508/70653689-930c3680-1c1a-11ea-985d-e280d8b34a37.png)

We're backlogging this one, correct?
> - [ ] Users with Spanish localization that arrive on Alpha will automatically default to the Spanish version of Alpha: alert defaults to open for the first page they land on, but once they navigate to other pages, the alert doesn't appear

**Comment by chiaberry** [comment]
@desigonz  thank you for catching the bug on mobile -- I was only testing on a smaller screen and it looked fine on that. I updated the site.

and yes, Chase said we should backlog the automatic opening of the dropdown

**Comment by desigonz** [comment]
Awesome, mobile looks good. Logged the automatic opening in #3569.

One last change:
- [ ] let's hyperlink the text, so it reads:

> Si le gustaría ayudarnos a mejorar, por favor inscríbase para [participar en nuestras investigaciones de usuarios](https://alpha.austin.gov/es/feedback).

per best practices in accessible content! Then good to go to production.
