### ISSUE TITLE
Joplin staging and production are running out of memory

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#3503]
This is pretty bad actually.

![Screen Shot 2019-11-27 at 10.25.31 AM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/73ccfb69-98d4-43cf-9bd8-4eba5a64a046)

I beefed up our dynos from "hobby" to "Standard". But we're still running out of memory.

An incomplete list of what we need to do:
- [ ] Determine what processes are consuming so much memory. (API calls?, the Joplin UI? specific processes in the Joplin UI)
- [ ] Determine if there are memory leaks in Joplin (sure looks like there are) and patch them.
- [ ] See how to reduce memory consumption
- [ ] If we can't reduce memory consumption further, then determine how much memory we need for the normal functioning of our app. Then make sure we're running Joplin on dynos that can support that.

**Comment by desigonz** [comment]
Start with some discovery, implements solution(s) to make it less bad.

**Comment by easherma** [comment]
Some notes on where I'm at with this:

* https://github.com/cityofaustin/joplin/pull/487 has some tweaks that should help a bit and also prevent total failure/app crashing when we run out of memory
* Cause number 1 is that we were running DEBUG on production; this is a big no-no in Django land as it saves copies of each SQL query every time its run, which would lead to an increase in memory usage.
    - I disabled this in prod, and I'd like to move forward with https://github.com/cityofaustin/techstack/issues/3560 to verify that it was causing the majority of our memory problems. The short term way to test this would be to also disable DEBUG on staging and have a bunch of people log in and do stuff. * shrug emoji *

* The ways we customize Wagtail add significantly to the number of queries run on each page, and therefore CPU processing time and memory usage (roughly in that order).

    - With our templates we use about 40% more memory with each request and roughly 50% slower response time. This was tested by just nuking our templates folder, which is obviously imprecise. 
    - Some great tech debt to address would be to split our customizations into logical but separate modules so we can do more testing and have finer grained control. 
- Another example: just removing the 'view live' link from the pages list/search view reduces the number of queries from around 500 to 300, and cuts CPU response time in half. 
    - Some potential solutions to this: 
        - Use/heavily borrow from Wagtail's built-in url construction methods instead of rolling our own
        - Explore using janis_url as a [cached property](https://medium.com/@fdemmer/django-cached-property-on-models-f4673de33990) (or even just a property)
- Wagtail's default dashboard view is still by far the quickest and cheapest view to return when you first login, and can be customized further to remove info we don't like and add other relevant info. It was probably built that way for this reason.

There are some other potential performance improvements. None of them are on their own expected to be a magic bullet, but combined would probably make performance more robust:
* cached template loading
    * This is a Django functionality, it will prevent re-rendering of templates, but means that changes made to templates won't show until the app is rebuilt (so not good for dev). This would mostly affect CPU, not expected to affect memory too much (may even increase it slightly)
https://docs.djangoproject.com/en/2.2/topics/cache/
* Using memcache
    * another thing Django provides, this would be faster than the default in memory cache Django uses, again would affect response time more than anything 
https://docs.djangoproject.com/en/2.2/topics/cache/#memcached

**Comment by easherma** [comment]
Some other notes on memory consumption, things I think we should check before assuming either template caching or memcache would help significantly: 

* Every time you send a request, we are adding to memory for that session. The memory appears to persist across sessions. However, there is a good chance that it may just appear that way to us, and it would be good to test some variables and see how that affects behavior, such as: 
https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-SESSION_EXPIRE_AT_BROWSER_CLOSE
https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-SESSION_COOKIE_AGE

More info on those here: 
https://docs.djangoproject.com/en/3.0/topics/http/sessions/#browser-length-sessions-vs-persistent-sessions

In our settings, we currently set sessions to expire after: 
```SESSION_SECURITY_EXPIRE_AFTER = 14400``` aka 4 hours


Also, there are parts of our code which use querysets in inefficient ways, here is a prime example of something that could specifically be affecting memory usage on the search page: 
https://github.com/cityofaustin/joplin/blob/3f37c2c648fb8cdcd008cc4f6a0cc36391ba46b9/joplin/base/views/joplin_search_views.py#L30

More info related to how that sort of queryset is cached: 
https://docs.djangoproject.com/en/3.0/topics/db/queries/#caching-and-querysets

**Comment by easherma** [comment]
Also there is a PR already that adds memache: 
https://github.com/cityofaustin/joplin/pull/491

I can throw up one that adds template caching, I already tried it on Friday and it didn't affect performance so I didn't even bother pushing it up.

**Comment by desigonz** [comment]
> In our settings, we currently set sessions to expire after:
> `SESSION_SECURITY_EXPIRE_AFTER = 14400` aka 4 hours

Is that contributing the memory issues? How are you suggesting we change that to alleviate the memory things?

**Comment by easherma** [comment]
@desigonz We don't really know, app performance is a complicated thing to measure. I'm suggesting we could modify that value on a branch and change nothing else and see how that affects memory usage. Same with the other variables
