### ISSUE TITLE
Navigating to location pages from services and departments

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3504]
QA notes:
https://joplin-pr-3504-nav-to-location.herokuapp.com/ <- go ahead and test out preview/publish on location pages/service pages/etc.

Janis PR: https://github.com/cityofaustin/janis/pull/648
Joplin PR: https://github.com/cityofaustin/joplin/pull/499

### Janis
- [ ] Design matches mocks for both the **contact** and **location** cards
  - [ ] Service page with one or multiple locations
    - [ ] [Desktop](https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/screen/e1a0c9b8-037c-4f9b-9547-83049699a5e0/Template-Service-list-Desktop)
    - [ ] [Mobile](https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/screen/431f2b3c-5299-483c-adda-ed32d1951136/Template-Service-list-desktop)
    - [ ] Location information does NOT appear in rail
  - [ ] Department pages with only one location
    - [ ] New styling for contact card per [mocks](https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/)
    - [x] Location appears in the contact card per [mocks](https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/)
    - [x] "Location information" link appears at the bottom of the card and links to the full location page
    - [x] Make sure to test this on:
      - [x] desktop
      - [x] tablet
      - [x] mobile

* Note: we won't be doing multiple locations on departments

### Joplin *(TO DISCUSS AT DEV-DESIGN SYNC)*
- [ ] On service pages, user has the ability to add a "step with locations" that includes a rich text block and location picker
- [ ] Ability to add a location page to a contact snippet

**Comment by chasechenevert** [comment]
In the **Contact card** [section of the spec](https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/) there is an example of a single location associated with a page, where the "Location information" + forward arrow at the bottom of the Contact/Location card which takes users to the Location page.

Let me know if I still need to supply mocks for all of the other instances? I'm assuming that since we already have the component implemented, we'd just be adding the "Location information" link.

<img width="983" alt="Screen Shot 2019-12-02 at 1 28 33 PM" src="https://user-images.githubusercontent.com/7027270/69988814-0372d380-1508-11ea-8569-9f10533f3776.png">

**Comment by chasechenevert** [comment]
In the **Contact card** section of the spec there's an example of a contact card with a link to the location page. At the bottom of the card we'd add this "Location information" link + forward arrow icon to link to the associated location page. 

- **Service page**: the only difference with the contact card is the link at the bottom
- **Department page**: we discussed displaying more information for a single location (phone number, email, address, hours, social, and the new location page link), which was what we had before, it would now include the location page link at the bottom.

Would like to get Content's feedback on the link label here, should it be: 
- Location information
- Location details (shorter than previous)
- something else?

**Comment by desigonz** [comment]
@ablangworthy27, since you've been working on the place page microcopy, can you answer @chasechenevert's question about the link label for locations?

![image](https://user-images.githubusercontent.com/5839508/70064226-c7df1480-15ae-11ea-90b0-dc511f1af7b6.png)

**Comment by desigonz** [comment]
I've updated the acceptance criteria above, and I've reassigned this as a dev team issue and put it on deck.

**Comment by briaguya** [comment]
updated this to an 8 because it required:
* Updating queries for service pages and department pages to support new contacts
* Verifying hours work as expected in 3 places
* Verifying contacts without a location work as expected
* Cleaning up render logic on location pages when we only have some info

**Comment by desigonz** [comment]
@briaguya, thanks for the awesome work on this! Love the "Step with locations" 😍 Here's what I noticed; also assigning Chase to take a pass.

- Service page with two locations within a step: https://janis-3504-nav-to-locations.netlify.com/en/health-safety/disaster-safety-relief/disaster-preparedness/testing-locations-on-a-service-page/
- https://janis-3504-nav-to-locations.netlify.com/en/police-oversight/
- Location page: https://janis-3504-nav-to-locations.netlify.com/en/location/ice-cream-world/


### Janis
- [ ] Contact card background should be `#f7f7f7` *(looks like you have it set to RGB `240, 240, 240` which equals `#f0f0f0`)*
- [ ] Need to add padding between location cards for multiple locations on service pages

*currently*
![image](https://user-images.githubusercontent.com/5839508/71629619-18ed2300-2bc4-11ea-81e3-d9a2c4905f9b.png)

*[mock](https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/screen/e1a0c9b8-037c-4f9b-9547-83049699a5e0/Template-Service-list-Desktop)*
![image](https://user-images.githubusercontent.com/5839508/71629648-3e7a2c80-2bc4-11ea-879e-18a8efe8628c.png)


- [ ] Style for times should follow what's currently on alpha.austin.gov, ex. `8 am–5 pm`
  - [ ] en dash (`–`) punctuation (NOT a hyphen). 
  - [ ] space between number and `pm`/`am`

*currently on alpha.austin.gov*
![image](https://user-images.githubusercontent.com/5839508/71629429-13430d80-2bc3-11ea-8b3d-7793da46316f.png)

*compare with PR branch*
![image](https://user-images.githubusercontent.com/5839508/71629512-86e51a80-2bc3-11ea-9af7-2ee5f101af0e.png)

- [ ] Service pages have funny top margin on "Contact information"—should match department pages
![image](https://user-images.githubusercontent.com/5839508/71629742-c2ccaf80-2bc4-11ea-83fb-78a0c27bf841.png)
- [ ] Per acceptance criteria, on **service pages**, address and "location information" link should not appear in rail/contact information card
- [ ] Why is this TTY number appearing on [this page](https://janis-3504-nav-to-locations.netlify.com/en/location/ice-cream-world/)? Seems like it's happening for every service I add.
![image](https://user-images.githubusercontent.com/5839508/71629956-fa882700-2bc5-11ea-935d-5d558d581a77.png)

**Comment by chasechenevert** [comment]
I didn't catch anything beyond what @desigonz found. 

- [ ] Spacing between location tiles on service pages is `8px`

**Comment by briaguya** [comment]
@desigonz addressed all QA comments except the TTY issue, if you look here (https://joplin-pr-3504-nav-to-location.herokuapp.com/admin/pages/5/edit/#tab-content) you'll see those service pages have 311 listed as the contact, which has both the main and tty numbers listed.

Not sure what the best strategy going forward on this one is

**Comment by desigonz** [comment]
Thanks @briaguya, looks great. I'll look into the TTY thing separately.

Two things:
- [ ] Contact block on service page not appearing as expected on mobile—gray should stretch across width and I imagine there should be padding between contact block and "offered by" block. @chasechenevert can you verify?

*what's happening*
![image](https://user-images.githubusercontent.com/5839508/71833417-75dc5380-3072-11ea-8667-e22c1bf87d4d.png)
*[mock](https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/screen/431f2b3c-5299-483c-adda-ed32d1951136/Template-Service-list-desktop)*
![image](https://user-images.githubusercontent.com/5839508/71833776-50037e80-3073-11ea-9140-c4d8cd02b1bb.png)
- [ ] No spaces between en dash and the times (but keep that space between number and `am`/`pm`). Should appear as follows: `8 am–5 pm`
![image](https://user-images.githubusercontent.com/5839508/71833554-c94ea180-3072-11ea-8925-25b9647f8659.png)

**Comment by chasechenevert** [comment]
Updated the `contact information` and `offered by` sections--you can click on them in the preview to see the spacing if needed!
 
Mobile spec for location list on service pages: https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/screen/431f2b3c-5299-483c-adda-ed32d1951136/Template-Service-list-desktop/

 - [ ] spacing between `contact information` and `offered by` blocks is `16px`
<img width="505" alt="Screen Shot 2020-01-06 at 2 38 27 PM" src="https://user-images.githubusercontent.com/7027270/71847635-fc089200-3092-11ea-8c4f-ceabddf1e018.png">
<img width="524" alt="Screen Shot 2020-01-06 at 2 38 35 PM" src="https://user-images.githubusercontent.com/7027270/71847636-fc089200-3092-11ea-83be-cc220487ee0a.png">
<img width="509" alt="Screen Shot 2020-01-06 at 2 38 44 PM" src="https://user-images.githubusercontent.com/7027270/71847637-fc089200-3092-11ea-9197-d3f639ea30df.png">

**Comment by desigonz** [comment]
QA passed!
