### ISSUE TITLE
Schedule Funshop for Directors

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#351]
see #343

**Comment by ashleecoa** [comment]
@wilhitem Please talk to Stephen and Doug about the following:

We’d like to schedule an hour and a half meeting with department director’s to present a special Content Writing Funshop for them. It will cover key points from the series of three Funhops and give directors the information they need to empower their staff as they move through the more in-depth staff trainings.

What are your thoughts on how this meeting should be structured and facilitated to provide the most value to directors? And how can we go about scheduling such a meeting?
