### ISSUE TITLE
Review the workflow template

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3514]
Content team: I have drafted a temaplte re: work requests for content strategists based on our brainstorming. Can @ablangworthy27 @srigdon and @annieszot take a look and make sure I'm not leaving out any important questions, that I'm asking the questions appropriately, and that the questions are in an order that help to triage requests?

[Template workflow draft] (https://docs.google.com/document/d/1mT_c8EZHaFf1flQIO5c-Iz7CnF_dRRvrynhtHprNQjU/edit?usp=sharing)

**Comment by ablangworthy27** [comment]
I’ve reviewed and left comments, so I’m gonna take myself off this issue.

**Comment by srigdon** [comment]
I've also reviewed and left comments, taking myself off, too.

**Comment by annieszot** [comment]
Reviewed and edits suggested.
