### ISSUE TITLE
'Create new content' doesn't work on search page

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3515]
## Describe the bug
I looked up a page, found that there was no draft of it in Joplin yet, then attempted to "create new content'. Button didn't respond.

https://joplin.herokuapp.com/admin/pages/search/?q=youth%20development

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to [Pages](https://joplin.herokuapp.com/admin/pages/search/)
2. Type any search that will yield no result in the search bar ('birds', 'dogs', or 'tea', for example)
3. See no results
4. Click 'Create new content'
5. See error

## Current behavior
A clear and concise description of what happened

## Expected behavior
Pop up with content types should appear

**Comment by desigonz** [comment]
This is indeed a bug!!

**Comment by easherma** [comment]
This appears to be a bug with wagtail; I can replicate it on our wagtail bakery

**Comment by easherma** [comment]
I think the problem is in:
https://github.com/wagtail/wagtail/blob/master/wagtail/admin/static_src/wagtailadmin/js/core.js

Search is being triggered even when you click the dropdown on a page listing, I think.

**Comment by easherma** [comment]
QA @ https://joplin-pr-3515-create-modal-no.herokuapp.com/

**Comment by desigonz** [comment]
QA passed!
