### ISSUE TITLE
Review and copyedit the "Know your rights" page 

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#3519]
The "Know your rights" information page has been drafted and mostly translated. Content cove, can you give it a review to make sure it meets our standards? @Jo-Dwyer @ablangworthy27 @annieszot 

- Draft page in the drive: https://docs.google.com/document/d/12gBR_4lsYts7AX-N0uadCaYDXQNYwtbiQ6vmAmInDjE/edit#heading=h.rjtcu98on0ud
- English preview page in Joplin: https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToyNDE1
- Y Español: https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToyNDE0

Other things that need to happen before publishing: 

- We're waiting for OPO to send us updated ATXN links for the video embeds. 
- Put the page in the IA, see #3487. 
- I've emailed OPO to ask what else, if anything needs to happen before publishing this page.

**Comment by ablangworthy27** [comment]
@srigdon @annieszot @Jo-Dwyer I'll take this on today.

**Comment by annieszot** [comment]
Copied edited @srigdon second round. These rights are generally known as "Miranda rights" after the Supreme Court case _Mirranda v. Arizona_ 
https://www.legalzoom.com/articles/know-your-rights-what-are-miranda-rights
Posed a question on whether we mention "Miranda" or not... 

Suggested edits on simplifying language, too :)
