### ISSUE TITLE
Identify requirements for bidirectional relationships

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3522]
How do we want things to relate in Joplin? What can we manage where?

**Comment by desigonz** [comment]
- [ ] Write user stories (_Why_ do we need bidirectional relationships? How will they help an end user, whether an author or a resident?)
- [ ] Sift through old issues—where have we requested them in the past?
- [ ] Brainstorm all possible places where we want bidirectional relationships

**Comment by desigonz** [comment]
From #2705:
### As I content editor, I want to be able to manage whether a page is a top service both from the individual edit page and the topic/department page, so that I don't have to do a lot of back and forth while editing.

You should be able to manage whether a page is a top service from both the "Page" and the "Topic"/"Department" page.

**Comment by desigonz** [comment]
From #3527. Bolded the section related to bidirectional relationships:

### As a Joplin admin/mod I want to see associated pages and author names for location snippets so that I can safely delete duplicate locations without leaving a service page without a location.

**Is your feature request related to a problem? Please describe.**
APH locations are sometimes called different names depending on who's talking about it or what service they're speaking about. I have found 2 sets of duplicate locations with slightly different names and I can't be certain of where they're linked. 

**Describe the solution you'd like**
I'd like to see the author name for locations on the table of locations as well as **associated pages listed either on the table of locations or in the details of the location.** 

**Describe alternatives you've considered**
It would also be helpful to be able to sort the list by name or search in order to avoid creating a duplicate to begin with.
Very fancy: if a location shares a physical address but not a name existing location, maybe the field can suggest that existing location?

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by desigonz** [comment]
## First things first

A new, more overarching user story:

### As a content author creating associations between different content types, content snippets, and media artifacts (like images and documents), I want to be able to see how pieces of content are linked, so that I can make smarter decisions about that content.

Examples:
- I might decide not to delete a snippet because I see that it's on multiple pages
- I can better understand where a document is linked to across all of austin.gov


## And later...
Here's another general user desire we've seen in the user experience: Not just the ability to **see** the bidirectional relationships, but also to be able to edit them from multiple places.

### As a content author creating associations between different content types, content snippets, and media artifacts (like images and documents), I want to be able to edit linked pieces of content from different places, so that I can edit information where it makes most sense to do so.

Examples:
- I can whether a page is a topic's top service both from the individual edit page and the topic

**Comment by desigonz** [comment]
@Niicck and @briaguya, I'm starting to outline the user stories for bidirectional relationships, so that we can identify all of the requirements for this, so that we can implement it right!

See the user stories in the comment above. This is where I'm starting. But I want to make sure I'm on the right track for defining requirements that will serve y'all. Is the goal to identify all instances of what needs to know what where? How would you recommend we uncover all possible instances?

Could put this on the agenda for dev-design sync tomorrow if it makes sense, or schedule some other time to chat.

**Comment by desigonz** [comment]
Another use case! During content pin-up today, @toribr, @ablangworthy27, @Jo-Dwyer, and @srigdon identified the desire to allow editor-level users to delete images or pages, but **only** if we have bidirectional relationships enabled that allows them to see everywhere the image/doc is used. Ex. "Are you sure you want to delete this? This image appears on 17 pages."

**Comment by easherma** [comment]
another not-fun aspect of this that we'll ideally consider is how adding these relationships and displaying them can each have performance effects on the app itself. There could be potentially many additional lookups to get this extra information, and it could easily slow down the app itself overall for authors without some careful design/measurement. Acceptance criteria for that could look something like 'all of the above happens while maintaining current page load speeds/app performance for content authors)

**Comment by desigonz** [comment]
## Snippets
### As a content publisher, I want to know all of the pages that a snippet appears on, so that I can make informed decisions about how to edit the snippet.
### Requirements
When a user clicks into a contact snippet, 
- [ ] they are able to see every page the snippet is on
- [ ] they are able to see whether those pages are LIVE or DRAFT (status)
### To test
1. Create a contact snippet
2. Add it to a page and publish the page
3. Add it to a draft and save that draft page
4. Return to the contact snippet and see:
  - [ ] The published page in step 2 is listed
  - [ ] The draft page in step 3 is listed
 ### Test data
- [ ] (True on staging as of 3/13) For the `Recycle & Reuse Drop-off Center` snippet, you should be able to see that it is on the following pages:
  - [ ] `Drop off household hazardous waste and other recyclables` + its current status
  - [ ] `Pick up free paint and other household items` + its current status

## Images and documents
### As a content author, I want to know where on the website an image or a document is used, so that I can make smart decisions about editing and deleting that snippet.
### Requirements

### To test

### Test data

## Pages
### As a content author, I want to be able to manage relationships between multiple pages from each side of the relationship, so that I can effectively manage content without having to the page I'm currently editing.

Examples:
- Locations
  - Location pages ⟷ department pages
  - Location ⟷ service pages
- Top pages ⟷ department pages
- Top links ⟷ topics

### To test

### Test data

**Comment by ablangworthy27** [comment]
@desigonz 

**Locations**
When you say "do we want to be able to edit from this page?" do you mean removing or adding pages associated with the location? I don't think we want users to be able to do that unless there are parameters put up that keep them from removing pages that they didn't author.

**Top pages**
I don't think it makes sense to be able to edit this from the page view. Lower priority, and probably unnecessary.

**Top links**
I have the same feeling here. Because there is a finite amount of links that may be added, I don't think you should be able to edit that from the page view. 

**Pages and topics**
I can't think of a time when I have ever wanted this capability, but that doesn't mean it is not useful.

**Comment by desigonz** [comment]
Thanks @ablangworthy27, I appreciate your thoughts! Do the snippets and image/docs requirement seem good?

+1 on your thoughts on locations—I don't think it makes sense to link from the other way.

Re: "pages and topics"—I believe @toribr ultimately wants to be able to edit what's in a topic from the topic side of things, like curating a whole page of stuff. According to @briaguya it's the most difficult thing we'd be asking to implement, so sounds like it's better to keep this for longer-term backlog.

**Comment by toribr** [comment]
Regarding P2, your test plan doesn't include the message or test for deleting an asset used in multiple places, ie, are you sure you want to delete this image? it's used in x places (or) you can't delete that image because it's used in x spots, depending on how we want to go. Can they ever delete an image that's on more than one page at one go? If so, then how do those pages get republished without the image? Is it automatic? Or are we making them delete in image page by page and then republishing page by page?

**Comment by toribr** [comment]
Re P3; makes sense to me and I defer to @ablangworthy27 

I do think my meta topic and topic collection tree will be necessary eventually but certain isn't a priority right now.

**Comment by desigonz** [comment]
Oooh @toribr good call on the "are you sure you want to delete? It's in x spots" use case. Will add that in.

**Comment by desigonz** [comment]
Actually clarifying question for @toribr: do we want a user to see where images on docs are in both of these places, or just the second:
- On the image/doc edit page
- On the delete "are you sure?" page

**Comment by toribr** [comment]
Should probably be both, but it'd be good to see the flow modeled to be sure. 

Also, I'm presuming this is a dept level view, ie, I won't be able to delete images that are used by another department. We haven't really gotten into the shared "assets" realm, so I'm presuming that visibility, adding and deleting of images or documents have department boundaries.

**Comment by desigonz** [comment]
@toribr Yep, those permission requirements will be implemented separately!

**Comment by desigonz** [comment]
Split these into #4186, #4187, and #4188 for dev to pick up in the future.
