### ISSUE TITLE
Let's talk about publisher

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3524]
**Objective** 
Come up with a game plan for building out publisher to support incremental builds.

**Participants**
Can't really have the meeting without @briaguya and @Niicck, but I'd love to hear from @chiaberry @robbobfrh84 @easherma and @desigonz too!

**Agenda**

Not sure yet, this is a WIP meeting issue. I'm commenting some brain dump style stuff after I create it.

------
- [x] Schedule meeting
- [x] Meet
- [ ] Create resulting issues

**Comment by briaguya** [comment]
![IMG_4095](https://user-images.githubusercontent.com/6384156/70152816-7ea4c880-1673-11ea-820a-2ea0d936921e.jpg)
![IMG_4096](https://user-images.githubusercontent.com/6384156/70152844-86646d00-1673-11ea-85d7-9b792f24f689.jpg)
![IMG_4097](https://user-images.githubusercontent.com/6384156/70152930-ad22a380-1673-11ea-9f01-fc77becfff4f.jpg)
![IMG_4098](https://user-images.githubusercontent.com/6384156/70152893-a005b480-1673-11ea-9164-b79e55ce280c.jpg)
![IMG_4099](https://user-images.githubusercontent.com/6384156/70152867-8fedd500-1673-11ea-8ebd-8c77f213f0b7.jpg)

**Comment by desigonz** [comment]
Scheduled for Monday 12/9!

**Comment by Niicck** [comment]
Thoughts:
- [ ] An opportunity for parallelization during builds: Build English and Spanish on separate threads.
