### ISSUE TITLE
Clean up locations, maps, and contacts snippets in Joplin

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3528]
There are duplicate locations, inconsistent names for maps and locations, and fewer contacts than places with services. To get them cleaned up we need to:
- [x] check Locations list for duplicates
- [ ] check Contacts for duplicates, get specific contact info to replace 311 where appropriate
- [x] make a Map for each Location
- [x] create resulting issues, content debt

I'm sure there's others I'm missing. @ablangworthy27 @annieszot @srigdon can you add more to this list?

I'd also like to set some requirements for how snippets get written, maybe as a style guide convention or as a Joplin requirement. Maybe we only allow one location per address to make sure that services and contacts are not confused with locations?

**Comment by annieszot** [comment]
See @chasechenevert 's #3532 "Locations beyond MVP" to add to the list. List items can turn into sprint goals or content debt.

**Comment by desigonz** [comment]
@desigonz to review and see what's actually relevant
