### ISSUE TITLE
Inserting documents in rich text fields

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3537]
**Acceptance criteria**
- [x] Turn on [Wagtail's document insert functionality](https://docs.wagtail.io/en/stable/editor_manual/new_pages/inserting_documents.html) on all rich text fields

### As a Joplin user, I want to be able to insert (within a rich text block) a hyperlink to a document I uploaded to Joplin, so that I can get residents the content they need.

**Is your feature request related to a problem? Please describe.**
There's no way to find the URL to the document from Joplin right now, which makes authors sad :( We've been asking Nick to send us links to the document on the S3 bucket, which probably makes Nick sad.

**Describe the solution you'd like**
Turning on [Wagtail's document insert functionality](https://docs.wagtail.io/en/stable/editor_manual/new_pages/inserting_documents.html), which we'll want to test how it works but might just do the trick.

**Describe alternatives you've considered**
Alternatively, it would be great if, when choosing a link in a rich text field, there's an option for a "Document link" and a picker with all of the documents.

![image](https://user-images.githubusercontent.com/5839508/70282580-d03c7880-1783-11ea-9251-bf34b018774e.png)

**Additional context**

**Comment by desigonz** [comment]
PR branch where dev turns on the feature, then we'll QA it. 

For testing/dev considerations:
- automatic titling (when you insert a document, is it pulling in the right title?)
- make sure it goes to the right link on Janis (building out the rich text parser, because it will probably give you an ID that you gotta fetch)

**Comment by chiaberry** [comment]
@desigonz  here is the joplin https://joplin-pr-3537-docs-rtf.herokuapp.com/

I am trying to link it to a janis site so you can see that the links don't work as is, but I am running into some build issues. I'll add the link to the janis site when its ready, but in case @toribr wants to see how it looks on Joplin, here it is.

**Comment by chiaberry** [comment]
okay, here is the linked janis: https://janis-3387-related-depts.netlify.com/en/housing-utilities/recycling-trash-and-compost/household-waste/compost-pickup/

with a document that i inserted from the rtf. In order for it to work, we need to do work on Janis so the urls can be formed correctly.

**Comment by desigonz** [comment]
Thanks @chiaberry! Here's what we'd need to do so that this branch could go into production:

- [ ] Make it so Janis can format URLs properly
- [ ] Turn on document insert functionality for the following rich text fields: 
  - [ ] Steps
  - [ ] Steps with options
  - [ ] Steps with locations

When can spin out the Janis side of things into another issue if you'd like, or just adjust the size of this issue accordingly. Let me know what you think.
