### ISSUE TITLE
Update design system components in Sketch sticker sheet

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#354]
It’s best practice to build your design documents so that they’re scalable and maintainable. A request to update the brand color should be as easy as a Bob Ross painting lesson is serene. Here are some tips for creating a stylesheet in Sketch where you can centrally maintain visual details like fonts and colors.  - _[https://medium.com/ux-power-tools/making-stylesheets-in-sketch-47ac1f274cdc](Making Stylesheets in Sketch)_.

**Comment by amenity** [comment]
No longer relevant.
