### ISSUE TITLE
Publish batch of official documents for OPO

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#3545]
For this round, we're drafting, sending for review, editing, and publishing: 

- 10 new notices of formal complaints
- 3 written reprimands
- 2 oral reprimands 

To do: 

- [x] Draft titles and descriptions for all of the above. 
- [x] Send to OPO for review. 
- [x] Receive edits. 
- [x] Do another pass to incorporate. 
- [x] Upload all documents. 
- [x] Add all document entries to the page and update it.

**Comment by ablangworthy27** [comment]
@srigdon I can do the rest once the edits are received from OPO

**Comment by desigonz** [comment]
- [ ] One more document to publish
