### ISSUE TITLE
Content person perspective for APL

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3546]
**When is this project due?**
Monday, Dec 16 (1 hour of timeboxed assistance at office hours; no future project)

**What is the project that this work time will be charged to?**
Office Hours - (general operation?)

**Have you already consulted the [ODD Style Guide](https://cityofaustin.gitbook.io/digital-style-guide/) before submitting this request?**
n/a

**Is the project resident-facing?**
- [x] Yes
- [ ] No

**Is this project a blocker for you or your team?**

**If the project isn't resident-facing, who is the end audience? Depending on who this is written for, we may need more information to understand how to meet your needs.**

**What is the medium for this content?**
Web service: a shared resource room booking tool

**What is the problem that a content strategist can help with?**
Content insights on the web tool itself

**What deliverables do you expect from the content team?**

**What approvals will be needed to complete this work?**

**Please provide the link to the Google Documents we'll need to use.**

**Comment by kriskristin** [comment]
Sarah Cronin had a UT design student help them on a project to re-design the shared learning room online reservation process for the Central Library. She has a prototype built out and wants to get another set of eyes on it. This should be a one time consulting Office Hour (will not become a full SDL engagement). 

**LOGIN**
You can log in at https://library.austintexas.gov/user.
User name: ODD.Testing
Password: Travis!!

You can make reservations at https://library.austintexas.gov/slr-request. This is does not impact the live reservation system so you can make as many reservations as you’d like.

**Concerns**

1. Content in the email sent after reservation:
![Screen Shot 2019-12-12 at 12 02 05 PM](https://user-images.githubusercontent.com/12438022/70737078-5ce0bc80-1cd7-11ea-85e8-22ec92f7723c.png)
 


2. At the top of the request page:

![Screen Shot 2019-12-12 at 12 07 30 PM](https://user-images.githubusercontent.com/12438022/70737388-ff993b00-1cd7-11ea-9f74-1b510385e986.png)

3. The submitted page needs some formatting issues fixed, but I’d like feedback on the text.

4. The confirmation page also needs some formatting issues fixed, but again feedback on the text would be welcome.


Will add some of the research files as soon as they are sent over to me.

**Comment by kriskristin** [comment]
@srigdon I forwarded you the email with some artifacts from the project. They may be good to have a peek at before Mondays Office Hours.

**Comment by srigdon** [comment]
Meeting finished (12/16) and follow-up email sent (12/17).
