### ISSUE TITLE
Error when saving a draft in Joplin, lost all changes

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3547]
## Describe the bug
I added several documents (previously uploaded) to the OPO page. Added descriptions and chose to save as draft. When I did, the screen loaded with this message:
<p align="center">
    <kbd>
      <img src= https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/155e3a58-1f91-4b82-89a7-8facb223dbfd> 
     </img>
    </kbd>
</p>

https://joplin.herokuapp.com/admin/pages/128/edit/#tab-content

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to Joplin 'Official complaint and discipline documents'
2. Edit content
3. Save as draft
5. Also, now none of the content I made is there, or if it is I haven't found it yet. 

The preview for drafts returns documents in a different order from the editor.

## Current behavior
Error!

## Expected behavior
Just save a draft, don't lose my content, and remain on the editor page with my new content in place.

**Comment by desigonz** [comment]
@Niicck @easherma Since y'all are working on this in #3503, ok to close this issue?

**Comment by Niicck** [comment]
Ok to close now that it's linked to the other issue, this is good information to have.
