### ISSUE TITLE
Location page - Localizable hours exceptions

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3568]
Updated acceptance criteria
- [ ] Author can add the hours exceptions in different languages
  - [ ] For the location hours
  - [ ] For the service hours at that location
- [ ] When an author saves a page with the translated hours exceptions, these appear in the preview page
- [ ] When an author publishes a page with translated hours exceptions, these appear in the live page

---

As a content author, I would like to be able to enter exceptions for hours in both english and spanish.

**Comment by desigonz** [comment]
@briaguya Can you size this issue?

**Comment by easherma** [comment]
The field should just need to be added to translations.py in joplin.

**Comment by desigonz** [comment]
What's the testing link for this?

**Comment by easherma** [comment]
https://joplin-pr-3568-localize-hours.herokuapp.com/

**Comment by desigonz** [comment]
Updated acceptance criteria above. As soon as you share a Janis link, I'll QA and then create resulting issues.

**Comment by desigonz** [comment]
Discovered that hours exceptions aren't appearing in Janis, made issue #3675 for this and marked it as a blocker.

**Comment by easherma** [comment]
3675 is in, everything should work ok between this one and that one but we'll want to make sure it works.
