### ISSUE TITLE
Hours exceptions not appearing on Service page

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3570]
## Describe the bug
I input normal hours and hours exceptions for my neighborhood center contacts, but the exceptions information isn't displaying on my page

[rent and utility help preview](https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToyNDky)

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to 'Pages'
2. Search for 'Rent and utility help...'
3. Click 'Edit'
4. Scroll down to contacts
5. Click 'edit contact' on any contact
6. see hours information wiht exceptions
7. preview page with those contacts
8. see error

## Current behavior
A clear and concise description of what happened

## Expected behavior
A clear and concise description of what you expected to happen

**Comment by desigonz** [comment]
Closing this one—hours exceptions will be a thing with the new location content type, which we'll be transitioning next week.
