### ISSUE TITLE
Improve image download speed on <PageBanner>

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#358]
These image aren't optimized and should be. Wondering if we should upload preoptimized imgs as a short term fix or check into the Wagtail image upload options.

**Comment by amenity** [comment]
@mateoclarke - can you stick a size on this guy please?

**Comment by amenity** [comment]
Can we size this guy please.

**Comment by briaguya** [comment]
After starting to look into using signals it appears as though there should be a way to use existing wagtail functionality to make this happen. Investigating that path now.

http://docs.wagtail.io/en/v2.0.1/advanced_topics/images/image_serve_view.html

**Comment by briaguya** [comment]
https://github.com/cityofaustin/janis/pull/240
https://github.com/cityofaustin/joplin/pull/118
