### ISSUE TITLE
Draft in Joplin and publish 'Free child safety seats'

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3582]
[Free child safety seats](https://cityofaustin.sharepoint.com/:w:/s/CTM/TEAMSITES/ODD/ERg0ZeLYN3VNksnyU-OTW78BxEBF38SkpKd64ncX3TQCzQ?e=oMTQlW) 

- [ ] Edit text to reflect: What do residents need to provide to receive this service? There are no requirements except that the client brings their child/children and the car they will be using 
- [ ] send to Anna Lassmann for final approval
- [ ] Review by @ablangworthy27 or @srigdon 
- [ ] OK to publish from @srigdon 
- [ ] publish
- [ ] send for translation
- [ ] add translation

**Comment by gabrielaperezdelaosa** [comment]
this was drafted and translated by me, reviewed by @Jo-Dwyer
