### ISSUE TITLE
Implement pagination page transition

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3583]
- [x] Resident clicks on a page number
- [x] Page quickly scrolls back to top 
- [x] After a very short delay (.3 seconds) documents populate/load

**Comment by robbobfrh84** [comment]
@desigonz Ready for QA: 

PR: https://github.com/cityofaustin/janis/pull/658

Deployed Link: https://janis-3583-pagination-transitions.netlify.com/

Deployed Link (direct): https://janis-3583-pagination-transitions.netlify.com/en/health-safety/police-oversight-2/police-feedback-and-records/official-complaint-and-discipline-documents/

----

NOTE: this was just a first pass - and, the time for scroll / fades are easy to change modify.

**Comment by desigonz** [comment]
This looks good to me, but tagging @chasechenevert and @toribr to review.

**Comment by toribr** [comment]
I think we need to slow it down some more - let's double the fade time, and slow the scroll by half. @robbobfrh84

**Comment by robbobfrh84** [comment]
After a Pair-session with Tori, we landed on a good timing for the effect!👍
