### ISSUE TITLE
Implement mobile pagination truncation

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3585]
- [x] Matches mocks: https://xd.adobe.com/spec/aed4d8fc-6ddb-4576-65e2-4125fdb42e8a-d8e5/ was updated before the break started and after dev/design sync. we talked through the issue with the team, but I neglected to post the notes here. The interactive example in the spec shows where the ellipsis should fall and when
- [x] ellipsis shouldn't function as a button, so they shouldn't have a border, hover, or selected state

~- [ ] shift the back and forward buttons to above and below the row of numbers so that we can fit 7 in a row on the smallest phone size we have available (iPhone 5s).~

**Comment by robbobfrh84** [comment]
@desigonz / @chase, I think we can remove the first criteria now, correct? 
"
shift the back and forward buttons to above and below the row of numbers so that we can fit 7 in a row on the smallest phone size we have available (iPhone 5s).
"
Other than that. I have everything i need within the specs provided.

**Comment by robbobfrh84** [comment]
@desigonz Ready for QA 

Deployed: https://janis-3585-mobile-trunc.netlify.com/

Deployed direct to pagination page: https://janis-3585-mobile-trunc.netlify.com/en/health-safety/police-oversight-2/police-feedback-and-records/official-complaint-and-discipline-documents/

UPDATE: 
- I just tested it on Iphone SE and saw this...

![IMG_5308.PNG](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/10a1b20e-9594-4d74-b41b-c286a483ec46)

So, I had to do ONE Minor change to the design (just reverted back to the old one) and set the page number widths slightly smaller WHICH made it fit like so...

![IMG_5307.PNG](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/532356fc-eee8-4631-b8c9-f4163b2a0e83)

NOTE: This change *is* updated in the PR. 
----
Let me know what y'all think - as it's easy to tinker with atm.👍

**Comment by desigonz** [comment]
Looks beautiful to me! Assigning @chasechenevert to QA

**Comment by chasechenevert** [comment]
Nice, Bob! The change is spot-on. Good to go 🚀
