### ISSUE TITLE
Center pagination component

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3586]
- [x] Let's center the component, and allow it to expand up to the width of the body content which is `.col-md-8` and has `flex-basis: 66.66667% max-width: 66.66667%` (in the event that there are a lot of pages)

**Comment by robbobfrh84** [comment]
Is this👇this correct centering we'd like to have?

![Screen Shot 2019-12-26 at 10.34.43 AM.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/c0f4c8db-0702-442c-b4ef-58d9d2bcb914)

**Comment by desigonz** [comment]
Assigning @chasechenevert to QA, but @robbobfrh84, can you also add a testing link?

**Comment by chasechenevert** [comment]
Yep, this looks right to me! I'll be happy to verify the implementation as well if I get a link

**Comment by robbobfrh84** [comment]
Deployed Link for QA: https://janis-3586-center-pagination.netlify.com
Link to exampleL https://janis-3586-center-pagination.netlify.com/en/health-safety/police-oversight-2/police-feedback-and-records/official-complaint-and-discipline-documents/#4

**Comment by chasechenevert** [comment]
Looks good! I checked across these browsers that I have access to at the moment (not that I anticipated any issues with centering, but I want to start making sure to check across browsers and operating systems when reviewing implementations): 
- Safari: desktop
- Firefox: desktop
- Chrome: desktop and mobile

**Comment by desigonz** [comment]
QA complete!
