### ISSUE TITLE
Create before/after type user testing videos for baseline metrics

### ISSUE THREAD

**Issue by ashleecoa** [cityofaustin/techstack#359]
Run a user test with City staff: have them use a different department's service and record the experience. We'll share the video with that department's staff in order to build empathy and help them understand user pain points accessing their services.

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [x] Research mobile capture user testing tools

- [x] Acquire dedicated laptop and install tools and test kit

- [ ] Determine services to test from austintexas.gov and alpha.austin.gov

- [ ] Schedule testing with City staff of a service not in their department

**Comment by ashleecoa** [comment]
Vet.gov inspiration: 

Before: https://youtu.be/l_ErfXWckjI
After: https://youtu.be/mzeNEXudNSI

**Comment by oliver2g** [comment]
@kriskristin FYI

**Comment by kriskristin** [comment]
@Desi I am not sure if we want this issue to live on. We are doing it and will strategically implement it into future usability testing. I'm fine with closing it since its a long-term strategy thing.
