### ISSUE TITLE
Django query sets/performance

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3596]
**Objective** 
During dev sync next Monday, the team will discuss django query sets and the effect on performance. The goal will to produce a tl;dr documentation.

**Participants**
dev team minus @Niicck who is on vacay

**Agenda**

------
- [x] Schedule meeting
- [x] Meet
- [ ] Create resulting issues

**Comment by easherma** [comment]
Some potential ones to look at:
https://github.com/cityofaustin/joplin/blob/6b1a0cb360e0ef34cfd3a99ab0dd806828582126/joplin/base/models/janis_page.py#L131

https://github.com/cityofaustin/joplin/blob/d59d0eed8436207c402654236a97514a72c0c9ec/joplin/api/schema.py#L531

https://github.com/cityofaustin/joplin/blob/d59d0eed8436207c402654236a97514a72c0c9ec/joplin/api/schema.py#L582

**Comment by easherma** [comment]
https://medium.com/better-programming/django-select-related-and-prefetch-related-f23043fd635d
https://medium.com/@ryleysill93/basic-performance-optimization-in-django-ebd19089a33f

**Comment by desigonz** [comment]
@easherma @chiaberry  Besides the homework, what's the next step on this issue?

**Comment by desigonz** [comment]
@chiaberry will be putting together notes and sharing here.

**Comment by chiaberry** [comment]
here are my sparse notes. I will flesh them out. We reviewed the links above and discussed the better parts of the resources

Resources discussed:

https://docs.djangoproject.com/en/3.0/topics/performance/#work-at-the-appropriate-level
"That is, the database can typically do things faster than Python can, which can do them faster than the template language can"

pipenv shell_plus
https://django-extensions.readthedocs.io/en/latest/shell_plus.html

silk clear request log
https://github.com/jazzband/django-silk#clearing-logged-data

good examples of expensive queries and their faster better versions
https://medium.com/@hansonkd/performance-problems-in-the-django-orm-1f62b3d04785

example of profiling queries
https://medium.com/@ryleysill93/basic-performance-optimization-in-django-ebd19089a33f

reducing queries (medium premium post)
https://medium.com/better-programming/django-select-related-and-prefetch-related-f23043fd635d

**Comment by easherma** [comment]
I will also help flesh out an overall guide, I don't want to re-hash existing content out there but perhaps we can come up with a resource guide + things to watch out for and things that are more specfic to our setup

**Comment by easherma** [comment]
https://docs.djangoproject.com/en/3.0/ref/utils/#django.utils.functional.cached_property is another thing to document/experiment with

**Comment by easherma** [comment]
Draft outline for queryset stuff:

* short basics on what Django querysets are and the role they play(ORM mapping, link to docs)
* helpful links, articles, resources

* what is most relevant for our use case? 
    * Load testing performance in joplin admin = this is decent and solid, relevant for admin UI, not for janis
    * Load testing builds/api calls for builds = this is on much shakier ground, relevant for publishing, not for admin UI

* problems with performance in the admin UI?
    * Look at querysets in joplin views
    * Look at templates for the admin interface, what properties are we calling, are those calling functions? Or those functions slow?
* Problems with build query response time?
   * Look at querysets in the api
   * See if you can write better querysets (see resources) or (better) make it a property on the model instead of something the schema has to construct or catch

**Comment by easherma** [comment]
https://github.com/graphql-python/graphene-django/issues/57

**Comment by easherma** [comment]
https://github.com/eamigo86/graphene-django-extras/issues/43

https://docs.graphene-python.org/en/latest/execution/dataloader/
