### ISSUE TITLE
Feedback on homelessness resource access

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3598]
@easherma helped with user research today, yay! Now he'll be following up with the volunteer dev to give feedback on next steps.

**Comment by easherma** [comment]
Debriefed on 12/12 with @mjanchar @stephaniegates 
Sent an email to the github volunteer to set up a time to chat

Our next asks are going to be more focused on reporting on the overall data quality of the existing dataset; most missing fields, potential for de-duplication, etc

**Comment by easherma** [comment]
Going to chat with our volunteer after the holidays

**Comment by easherma** [comment]
Talking this Friday!

**Comment by easherma** [comment]
Met with Justin; I asked him to use his data skills to report statistics on missing fields in the data + duplication of columns in order to suggest a better shape of the data that will be easier to keep updated and accurate.
