### ISSUE TITLE
Events content type design: Joplin

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3603]
Early designs by the end of sprint 47

**Comment by toribr** [comment]
MVP fields:
- [ ] Title *
- [ ] Description *
- [ ] Short description *
- [ ] Start day/end day/all day *
- [ ] Time (start and end) *
- [ ] Location * (method of entry TBD)
- [ ] Related dept *
- [ ] Contact *
- [ ] Registration link
- [ ] Cost (free/add cost and label)
- [ ] Ability to cancel
 

# Agenda
- [x] What qualifies as an event? What is the difference between a service offered between certain hours and an event? Some qualifiers may be: is registration required? is a service delivered, or is it a fun or learning activity? 
   - [x] We've discussed eligibility requirements; other than age, what sort of requirements are we talking about and wouldn't they apply more to services than an event? (if the event requires eligibility, it's probably a service not an event)
- [x] What happens to events listings after the event date? (preserved, but do they need a status badge? Are there things added to them post-event (agendas, notes, etc.)
{Events can be scheduled; after their end date, the event is unpublished either according to the default date or a date which can be specified. Once the event has past, the view of the event is removed from the home page and list page view; only the event detail at it's original URL remains.

- [ ] What if no location exists? Are authors compelled to create one? (Currently the only way to add a location is by selecting one; if not compelled then author would need to add within text.) 
{outstanding question that needs research; how many events at the City of Austin take place at non city locations}
- [ x] Revisit required fields for MVP (see board)
- [ x] Revisit MVP data model (see board)
  - [ x] Topic (Do events show related topics?) {not needed at this time}
  - [x] Registration link (should this be standardized, ie, show as button or receive other specific styling on Janis) yes, we are going to use this
  - [x] Image {Not MVP}
  - [x] Cancel: special display, remove from home (MVP)
  - [ x] Sharing options (Janis only, but includes ics files, not twitter or fb)
