### ISSUE TITLE
custom save/publish doesn't recognize empty rich text

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#3605]
## Describe the bug

Our custom save/publish doesn't recognize empty rich text. 
This affects: Service Page
Info Page
Department Page
and Guides

**Comment by easherma** [comment]
Resolved with https://github.com/cityofaustin/wagtail-publish-preflight/commit/c076afec1b90f2d6b478c3dbc807ff2d2be5a362

Bumped the version and checked that it works in joplin as well

**Comment by desigonz** [comment]
This is fixed on info and department pages. For guides, see my QA notes on #3379. Closing this one!
