### ISSUE TITLE
Publish Spanish mobile food vendor guide

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3608]
Translation lives here: https://drive.google.com/drive/folders/1wOAOGcxzgG89qNv2QbelvQovpawdma8I

**Comment by ablangworthy27** [comment]
I'm just going to go ahead and assign to myself. If I don't get to it this sprint, it will be good to work on remotely next sprint.

**Comment by ablangworthy27** [comment]
This is done

**Comment by desigonz** [comment]
🎉amazing!!
