### ISSUE TITLE
Observe content team using Joplin to assign pages to the IA

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3609]

**Comment by anukandimalla** [comment]
Related issues: 
https://github.com/cityofaustin/techstack/issues/3655

**Comment by anukandimalla** [comment]
Here are the document links for the findings during the observations 
https://docs.google.com/document/d/1AibdtCQzH6ynssLx6jhY5oQEf4eRZxauoVamzuainWo/edit?usp=sharing
https://docs.google.com/document/d/12nHlnTHayioEq6TW6wWIzfjS7EYVxJesS7eertV2IzY/edit?usp=sharing
