### ISSUE TITLE
Draft service page: apply to the Community Police Review Commission

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3614]

**Comment by annieszot** [comment]
Service page draft on how to apply to join the community police review commission 
[Draft](https://docs.google.com/document/d/19Lmw9vvhiq7oJTrskGlsha7act0XH6hLN8j4__7o_Mo/edit?userstoinvite=desi.gonzalez@austintexas.gov&ts=5df78ce4&actionButton=1)
[Preview
](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyNjAw)

**Comment by annieszot** [comment]
Draft complete. Will make new issue for revising/approving info page. Closing
