### ISSUE TITLE
Draft info page: Community Police Review Commission

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3615]

**Comment by annieszot** [comment]
Information page on the community police review commission
[Draft](https://docs.google.com/document/d/17VRhqafKk33_ibaQ5fD94zlLcSxybigWqav-nrXWki4/edit#heading=h.6ty6bq5qxhj7)
[Preview](url)

**Comment by desigonz** [comment]
Thanks @annieszot! The preview link above didn't work; can you share the link again?

**Comment by annieszot** [comment]
Oops! Link fixed :)

**Comment by annieszot** [comment]
Draft complete. Will make new issue for revising/approving info page. Closing
