### ISSUE TITLE
Style guide: how can we use PDFs to fill a gap and plan for content debt to eliminate the PDF?

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3618]
Sometimes an existing PDF is the best way to give important information to residents and get content published quickly. 
- [x] Let's decide when using a PDF *for now* is the right decision and give a guideline for users to refer to
    - [x] Include do's and don'ts of creating accessible PDFs. 
        - Do: When linking to a PDF or any closed file type on a web page, always include the file type and size in parentheses directly after the link. Example: "This is a request for judicial records and will be answered in accordance with [Rule 12](https://www.txcourts.gov/media/524153/rjac-rule-12.pdf) (PDF, 42 KB)." 
- [x] Write a style guide entry on when it's ok to use an existing PDF and how to record content debt for a more accessible future draft
- [ ] Explain what content debt is and how the concept can be adapted to fit less frequent editorial schedules
       Related issue: #1923
- [x] Revision for [Style Guide: PDFs](https://docs.google.com/document/d/19a4N1BiDDZVanGT0e4QAnkRhDckNydbtyuLdC6tfpr0/edit?usp=sharing) entry

[Here is a document with some research on the pros and cons of PDFs, including why departments may resort to using them. ](https://docs.google.com/document/d/1p6HzupKaOglgImS7fjCyHlBQM4OoMKHZiqUQOf4RO5o/edit?usp=sharing)

**Comment by srigdon** [comment]
Supporting information: https://www.nngroup.com/articles/avoid-pdf-for-on-screen-reading/

**Comment by InaraFernandez** [comment]
[Here is a document with some research on the pros and cons of PDFs, including why departments may resort to using them. ](https://docs.google.com/document/d/1p6HzupKaOglgImS7fjCyHlBQM4OoMKHZiqUQOf4RO5o/edit?usp=sharing)

**Comment by InaraFernandez** [comment]
@ablangworthy27, tagging you on this issue since it's related to the Style Guide. 

Can you give this a first pass? There is a section on recording content debt that i'd like your input on, it might be worth bringing to pin up. One question I have is: should departments seek out our content team's help if they're looking to decommission some PDFs outside of their transition to austin.gov? 

[Here's my draft. ](https://docs.google.com/document/d/19a4N1BiDDZVanGT0e4QAnkRhDckNydbtyuLdC6tfpr0/edit?usp=sharing)

**Comment by ablangworthy27** [comment]
@InaraFernandez I made a bunch of suggestions. Let me know what you think, and of course I can publish to the gitbook.

**Comment by InaraFernandez** [comment]
@ablangworthy27 I think it's good to go with your changes!

**Comment by ablangworthy27** [comment]
This is published in the guide. Part of it is under the write content for residents section, and part of it is in the publish content on austin.gov section.
