### ISSUE TITLE
"Location name" in content type title fields

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3622]
**Acceptance criteria**
- [x] Field label for all content types reads "Title" 

## Describe the bug
Changing "title" to "location name" on the location content type got applied across ALL content types :( We really don't want the other content types to say "location name"

**Dev team: can you respond with a size for:**
1. reverting all fields to "title"
2. reverting all fields to "title" except for on the location content type, in which it should read "Location name"?

Thanks! 

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/3bee2849-2618-4925-869e-d3da094f873f)

## URL
Joplin staging

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to Joplin staging
2. Edit a page that's not a location page
3. See error

## Current behavior
Title field says "Location name" instead of "Title"

## Expected behavior
It says "Title"

**Comment by chiaberry** [comment]
@desigonz  size for first option, 1. size for second option, i dont know, 5? 8?

**Comment by desigonz** [comment]
Okay let's go with the size 1. I made an issue to fix option 2 in the future: #3625

**Comment by chiaberry** [comment]
https://joplin-pr-3622-title-fields.herokuapp.com/

**Comment by desigonz** [comment]
QA passed! Thanks @chiaberry
