### ISSUE TITLE
## Translated nested Streamfields broken on wagtail 2.7

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3623]
## Need to fix before this PR can go to staging
- [x] Guide sections streamfields aren't working—see GIF below
![3393-guide-sections](https://user-images.githubusercontent.com/5839508/69999283-e517d280-151d-11ea-9b0d-087e9a7311bc.gif)

_Originally posted by @desigonz in https://github.com/cityofaustin/techstack/issues/3393#issuecomment-560719730_

**Comment by easherma** [comment]
So the Javascript code we have for handling the hiding of fields is pretty brittle, and not happy with the change in html structure for streamfields. This is going to need its own work.

**Comment by easherma** [comment]
Needs QA, but https://github.com/cityofaustin/joplin/pull/503 addresses this

**Comment by desigonz** [comment]
Verified this on https://joplin-pr-wagtail-27-test.herokuapp.com/admin/pages/118/edit/#tab-content
