### ISSUE TITLE
Dev-design sync 12-17-29

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3624]
- [x] #3572 multi-page form design
- [x]  Start conversation on events, probably at least how to initially handle events on home page. (since there's no home page template) (became #3532)
• controls for selecting 1-4 (tbd) services and 1-4 (tbd) events

**Comment by easherma** [comment]
Going to re-cover multi page form stuff when @Niicck is back, opened #3631

**Comment by easherma** [comment]
We also talked about how, in the near future, we might want to coordinate more in terms of having a process pipeline for managing content types, identifying shared functionality or components between content types, etc.
