### ISSUE TITLE
Create content modal headings for topics and topic collections

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3626]
Topics and topic collections are missing headings on the create content modal.

Compare this 👎
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/9e8dd0db-67cc-4bfc-9a62-bc6a78f2d2c9)

with this 👍
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/caec11fc-13b5-4235-919e-6d116066e80e)

**Acceptance criteria**
- [x] Topic heading is: Write a clear, brief title that accurately describes the collection of pages you'll add to this topic. 
- [x] Edit the topic helper text --> Add to the tips below the text box: Think about this title as a label, and you're labeling the box of content that this topic contains. 
- [x] Topic collection heading is: Write a clear, brief title that accurately describes the collection of topics you'll add to this container page. 
- [x] Edit the topic collection helper text --> Add to the tips below the text box: Think about this title as a label, and you're labeling the box of content that this topic collection contains.

**Comment by srigdon** [comment]
My ideal version of the "create topic collection" and "create topic" modals would link to a resource on doing keyword research, as well as the style guide. Later we'll want to think about role-specific content within Joplin/the style guide/training.

**Comment by desigonz** [comment]
Thanks @srigdon! For the ideal version, can you make a "feature idea" issue with a user story? Otherwise we'll go with acceptance criteria above for now.

I'm reopening this issue and making it a dev issue.

**Comment by srigdon** [comment]
See "feature idea" in #4087
