### ISSUE TITLE
Write wagtail factories for service, info, guide, and department content types

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3630]
### As a developer, I want to easily generate quasi-realistic test data at scale so that we can reliably test functionality and also test the scalability of the janis joplin stack

**Is your feature request related to a problem? Please describe.**
Data can be different staging vs production, and our current testing/development process relies on creating/re-creating test data manually, which is prone to errors and time intensive. 

Similarly, there are various relative unknowns about our application that we need to start addressing more; in terms of how content models might operate at scale. It is difficult to test or visualize these problems without having _lots_ of content in joplin, and the best way to answer that question sooner would be to generate test content. 

**Describe the solution you'd like**
We follow a similar process for the location content type; we make factories and then make a process for generating content data. Ideally we'd integrate that generation more tightly with the django admin. 

This will help us design different scenarios of test data for testing specific relationships or specific scaling problems.

**Comment by desigonz** [comment]
Per our refactor meeting yesterday, this will be a second refactor priority, after refactoring content types into Django apps. We'll want to have completed load tests by June. I'm tentatively assigning this to sprint 50 and we'll revisit as we get closer!

**Comment by desigonz** [comment]
1. Eric to work on this, starting with service pages
2. Shareout in two dev syncs (week of 2/18—we'll reschedule it)

**Comment by easherma** [comment]
It would probably be good to flesh out some technical acceptance criteria for this particular issue, and/or break it up depending on that. Such as:

* do we want to just make the factories?
* do we want to integrate them into tests, or write tests using them?
* do we want to use them to generate fixtures, similar to what I did for locations?

**Comment by desigonz** [comment]
Share out on 3/3. Goals for the group:
- [ ] Get the rest of the team up to speed
- [ ] Figure out what it means for this issue to be done (or loop it into the other issue)
- [ ] Queue up next steps issues, if needed

**Comment by Niicck** [comment]
Covered in v3
