### ISSUE TITLE
Future feature: live view and preview for documents and images

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#3637]
### As a Joplin user I want [to be able to either preview or view live version of a document or image so that I can check my work without attaching to a page, reduce repeat uploads of existing documents or images, and in certain situations, link directly to a pdf without having it surfaceable on the website.

**Is your feature request related to a problem? Please describe.**
I am working on a new page for OPO that would house reports and recommendations. OPO wants to link to a pdf that will live on that page in their next press release, but they are not ready for the entire page to be live. 

**Describe the solution you'd like**
I'd like to be able to go to the documents, find the uploaded doc, and get a link to it from there. I don't think the doc should always have to be attached to a page in order to use it. 

**Describe alternatives you've considered**
The go-around now is publishing the page, but not assigning a topic collection, but I could see situations arising where that is too time-consuming.

**Comment by easherma** [comment]
Chatted a little with @ablangworthy27 about this, and to clarify (at least from a dev perspective), what she's looking for is to be able to preview the PDF in the browser without downloading it as a file. 

Looks like this is an open issue in wagtail core, though there are some details on a workaround. We can keep this in mind with current and future wagtail upgrades:
https://github.com/wagtail/wagtail/issues/1158

**Comment by easherma** [comment]
So fun story it looks like the wagtail 2.7 upgrade will get us what we want!

**Comment by desigonz** [comment]
Closing this, because I verified that Wagtail 2.7 will accomplish this!
