### ISSUE TITLE
Set current language to html *lang* attribute tag. 

### ISSUE THREAD

**Issue by robbobfrh84** [cityofaustin/techstack#3641]
We've done a great job handling languages in our UI for both Janis and Joplin when available. 
- But, we're not setting the html *lang* attribute (it's always 'en')
- This would be nice because then we'd always know what language we're in anywhere in the code.
- I also suspect this may effect screen readers, plugins, browsers or other tools.  

Background: I (Bob) realized this recently updating some of our Joplin code to handle different languages, and it would be useful to know and trust that value programmatically, making it easier to set those conditions.

### Important Questions and things to consider...
- Does any functionality of Janis or Joplin look at this value? / Will there be any regression? 
- Will it effect our analytics? 

## Current behavior
It's always set to 👇
```html 
<html lang='en'
```

## Expected behavior
It's always set the current language set👇
```html 
<html lang='en'/'es'/'ar'/'vi'
```

## Screenshots

Janis... 
<img width="715" alt="Screen Shot 2019-12-19 at 11 04 15 AM" src="https://user-images.githubusercontent.com/15821138/71195742-2dd8c680-2254-11ea-9b6e-736bd356a94f.png">

Joplin...
<img width="835" alt="Screen Shot 2019-12-19 at 11 09 13 AM" src="https://user-images.githubusercontent.com/15821138/71195756-33cea780-2254-11ea-8c94-eb7a5d1a912c.png">

**Comment by desigonz** [comment]
Can we include anything that starts with or contains `es`?

**Comment by robbobfrh84** [comment]
@desigonz Do you mean like a custom "subtag"? Like. `es-coa` ? If so, i'm not sure how that would be handled, but i suspect it's possible (and testable).

**Comment by robbobfrh84** [comment]
PR ready for review: https://github.com/cityofaustin/janis/pull/721
- Code Only here...
