### ISSUE TITLE
Homelessness Dashboard

### ISSUE THREAD

**Issue by sarahscottr** [cityofaustin/techstack#3644]
**When is this project due?**
January 5th - 6th (I know it's quick turn around - I wish I had access to a sighing/pained emoji)

**What is the project that this work time will be charged to?**
Homelessness (there's already a funding code established)

**Have you already consulted the [ODD Style Guide](https://cityofaustin.gitbook.io/digital-style-guide/) before submitting this request?**
Yes

**Is the project resident-facing?**
- [x] Yes
- [ ] No

**Is this project a blocker for you or your team?**
Not a blocker per se, but it will be viewed by people like the ACM, so I want to make sure it's misspelling free.

**If the project isn't resident-facing, who is the end audience? Depending on who this is written for, we may need more information to understand how to meet your needs.**

**What is the medium for this content?**
No

**What is the problem that a content strategist can help with?**
Polishing the information

**What deliverables do you expect from the content team?**
Review and recommendations on language

**What approvals will be needed to complete this work?**

N/A

**Please provide the link to the Google Documents we'll need to use.**
Can we have a conversation about this offline?

**Comment by Jo-Dwyer** [comment]
@sarahscottr can you give me access to the content that needs to be reviewed?

**Comment by sarahscottr** [comment]
@Jo-Dwyer I can but unfortunately you first have to have an account with Socrata - the link to that is here - https://data.austintexas.gov/signup. Once that's done I can add you. I also added the content on Google Drive, since it's more collaborative - https://docs.google.com/document/d/1b5cdD3bTGzooIx1FnMbtT5HINGSuC4sq56wInkfM2u4/edit?usp=sharing

Sections haven't been complete. My goal is to have them done be end of next week, but that depends on whether or not I can get content from partners.

Also the date has been update. It's being presented to Council on the 21st, but will most likely have other iterations.

**Comment by Jo-Dwyer** [comment]
I've had a Socrata account from my tree team days. joanna.gammansdwyer@austintexas.gov

Is the due date for this content revision still Jan 5-6?

**Comment by sarahscottr** [comment]
Awesome. Looks like the email went through and you're now a collaborator. The due date has been pushed out, so I was thinking the 17th, since the 20 is a holiday.

I have been thinking about what the best content practices are for Dashboards (and whether the content that I've written matches.) Not sure it fits into the MVP.... would love your thoughts.

**Comment by sarahscottr** [comment]
@annieszot this is the Homelessness Dashboard issue. Thanks!

**Comment by annieszot** [comment]
Socrata account created @sarahscottr !

**Comment by annieszot** [comment]
[Dashboard research ](https://docs.google.com/document/d/1gUmhwByMvVs7gA55m82YcFMs-xD6_N2bYwazwc9JSrw/edit?usp=sharing)compiled

**Comment by desigonz** [comment]
Closing this issue, but @sarahscottr, get in touch if you need anything else.
