### ISSUE TITLE
Warnings/messages in heroku CLI cause CircleCI builds to break 

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3647]
## Describe the bug
check_app_status.py is existing with an error, becuase the heroku cli is flashing an update warning. 
## URL
example of a failed build: 
https://circleci.com/gh/cityofaustin/joplin/4378

## Solution, 
Logging sterr but not existing if there is one. 
It might be nicer to use the heroku3 python library, but that isn't installed at whatever point the CI script is running, so that would be a bigger tweak to the CI pipeline. 

https://github.com/cityofaustin/joplin/pull/505 has the fix, the commit before the last one has how the code might look if we had heroku3 available.

**Comment by desigonz** [comment]
How do you want to test/QA this? Something to discuss at dev sync maybe?
