### ISSUE TITLE
Refine foster form design

### ISSUE THREAD

**Issue by juliazbyron** [cityofaustin/techstack#365]
https://drive.google.com/open?id=1648ltRiihC2G6vVPyfSWiyXP_2qXkuNV

@cthibaultatx to add a checklist of items.

**Comment by amenity** [comment]
@cthibaultatx @toribr size plz

**Comment by cthibaultatx** [comment]
- @toribr designed interaction model for progress bar:
![formprogress](https://user-images.githubusercontent.com/20911665/40806254-8c301de6-64e6-11e8-95c3-558beb7cc8c6.gif)

- Edited field states
-- When in error state, moved "x" inside field
-- When in error state, user sees error help text. I added back the original help text.
- Updated typestyles
- Edited button alignment
- Streamlined components (there were two types of 'Add additional info' elements)
- Edited alert box styling to not be indented

Updated sketch file: https://drive.google.com/file/d/1nJePAA3EI1APmdFK8zcBjh4OuajyjElG/view?usp=sharing
