### ISSUE TITLE
Joplin-Issues with Preview state and Publish/update state

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#3655]
## Describe the bug
When uploading or editing/updating the content using publish/update at top corner navigates to success message but in "live view" 404 page is resulting.Repeat the process using "preview" the page can be seen without 404 error message.

Note: 
1. **Tested in Staging**
2. **The page has to be published and view live since the only required(*) input to create the page is just “page title”**

## To Reproduce
Steps to reproduce the behavior 
Please refer to the word document below for steps to recreate and understand the different states
https://docs.google.com/document/d/12nHlnTHayioEq6TW6wWIzfjS7EYVxJesS7eertV2IzY/edit?usp=sharing

## Device and browser

Mac and Chrome

**Comment by desigonz** [comment]
This is a known bug that we're working on by refactoring and implementing incremental builds (#3001). Thanks for catching it!
