### ISSUE TITLE
Irregularity flow in uploading the content 

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#3657]
## Describe the bug
Can able to upload the content without Department and Topic collection.The page is published and how and where to find the document in the website flow(sitemap)

Note: **Are there any edge cases for web-pages without the Topic collection and Department?**

## To Reproduce
Please refer to the below document to reproduce and to understand
https://docs.google.com/document/d/1bwe4gsJcwoimbJjs8SsZgfUi84gW3HaYvZfOTbVMC20/edit?usp=sharing

**Comment by desigonz** [comment]
We'll be covering this in #2767
