### ISSUE TITLE
Census 2020 Office Hour 1/6/2020

### ISSUE THREAD

**Issue by kriskristin** [cityofaustin/techstack#3658]
Mateo Clarke (transportation) and Tara Olsen (PIO) are working in collaboration with Travis County on a microsite for Census 2020 awareness. They are coming in for an Office Hour on 1/6/2020 at 1:30.

[Current microsite](https://atx-census-2020.netlify.com/en)

We need a content specialist at the meeting, but they also need to do some work to prep for the meeting. See [notes from phone call with Mateo](https://docs.google.com/document/d/1m-hXIYCigLmxY6DCO18HA5tYgWFEysyr7m8Lt60l6VA/edit?usp=sharing)

**Comment by kriskristin** [comment]
@ablangworthy27 Mateo is transitioning some content to the website over the weekend. The content review we do should include that content. Mateo will be sharing a drive with me and I'll share it with you as soon as I get it.

**Comment by kriskristin** [comment]
[Census Drive](https://drive.google.com/drive/folders/1tMB-C1BVNUWWJkJBUUp6dvhnB1v-e1NL?usp=sharing)

[Folder with the content broken down by pages](https://drive.google.com/drive/folders/1ycxysYh4y1mUq2zVyN_2f4dIND-PaOwm?usp=sharing (edited) 
)

**Comment by desigonz** [comment]
@srigdon to add notes and then close
