### ISSUE TITLE
Review foster form error messages content

### ISSUE THREAD

**Issue by juliazbyron** [cityofaustin/techstack#366]
@cthibaultatx will advise

**Comment by amenity** [comment]
@cthibaultatx @LauraTrujillo - is this the same as #367 ?

**Comment by LauraTrujillo** [comment]
@amenity @cthibaultatx I think it is the same as #367 Which one should we close?

**Comment by amenity** [comment]
They look about the same.Your call!

**Comment by LauraTrujillo** [comment]
I closed out #367

**Comment by cthibaultatx** [comment]
@courtneyjacinic @LauraTrujillo @ashleecoa This is a task for one of you to review all foster form error message content. I'm not sure if Julia had the error content documented in drive somewhere. I think the best way is to work through the [prototype](https://cityofaustin.github.io/prototypeform/Contact_info.html) and document any changes to the content.

@toribr do you remember anything else about error messages from our hand-off with Julia that I'm forgetting?

**Comment by toribr** [comment]
Only thing I remember was the styling questions that came up.
