### ISSUE TITLE
Button styling for multi-page forms

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3660]
Font-weight for button text should be 700 to match style on OPO form
- [ ] For all buttons (back, continue, submit form), `font-weight` is `700`

The "continue" buttons should be styled in the primary styling as opposed to secondary since it's a progressive action
- [ ] "Continue" buttons should style with `background-color: #0050D8` and `font-color: #FFF`
- [ ] "Back" and "submit" buttons should remain the same

  

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/0f2a39b5-e202-4168-b343-b698a4bec015)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/c2a5a9ff-7ab0-474e-9415-56613a1199b4)

**Comment by chiaberry** [comment]
@desigonz @chasechenevert what about the hover styles? ![Screen Shot 2020-01-10 at 2.06.38 PM.png](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/48673bec-de03-48c7-b948-7cfa00f553b2) Should I change the text-color to match the hover of the back button?

**Comment by desigonz** [comment]
I defer to @chasechenevert on this one!

**Comment by chasechenevert** [comment]
Here's some updated styling for you @chiaberry!

This applies to these secondary buttons (back and continue), but not the final "Submit" button that's styled as a primary action. 

<img width="570" alt="Screen Shot 2020-01-13 at 1 15 18 PM" src="https://user-images.githubusercontent.com/7027270/72284510-c0c41100-3606-11ea-9dfa-6bcfad2864a9.png">

**Default state**
- [ ] background-color: `#D9E8F6`;
- [ ] font-color: `#0050D8`; 

**Hover state**
- [ ] background-color: `#0050D8` 
- [ ] font-color: `#FFFFFF`

**Comment by chiaberry** [comment]
for QA: https://janis-3537-docs-rtf2.netlify.com/en/police-oversight/multipage-form-and-confirmation/

@chasechenevert and @desigonz

**Comment by chasechenevert** [comment]
Looks great, @chiaberry! Just noticed one thing and good to go by me: 
- [ ] remove that border around the button

**Comment by chiaberry** [comment]
removed! @chasechenevert, reload and it should be gone from the next prev buttons

**Comment by chasechenevert** [comment]
Sweet this is good to go!
