### ISSUE TITLE
"Know your rights" Spanish page 404ing

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#3666]
## Describe the bug
When you click "Español" at the top of the Know your rights page, it shows a 404 error. When you navigate there from the Spanish topic page, it shows up, but if you click English once on that page, the English page 404s as well. 

This page was saved as a draft before I published, and the title page on the Spanish tab in Joplin was blank until I updated it today. Apparently it automatically added this slug:

![Screen Shot 2020-01-02 at 4.51.04 PM.png](https://images.zenhubusercontent.com/5be0b7bea977220c77bd229b/f64ba2f7-f20e-4328-a5f8-affb12a3b04c)

![Screen Shot 2020-01-02 at 4.51.19 PM.png](https://images.zenhubusercontent.com/5be0b7bea977220c77bd229b/cde91695-7174-47aa-88d7-c100849c2d1c)

After documenting, I tried deleting the slug on the Spanish SEO tab. No dice. 

EDIT: apparently that worked! Now neither page is 404ing. Leaving up for now in case it happens again. 

## URL
https://alpha.austin.gov/en/health-safety/police-oversight-2/police-feedback-and-records/know-your-rights-when-interacting-police

https://joplin.herokuapp.com/admin/pages/265/edit/#tab-content

## Screenshots
.mov of the path described above: https://drive.google.com/drive/folders/1zI_-RQA6HTRfjXKP3yp0FIoivXgf58oY

## Device and browser
Firefox 71.0, Macbook Air

**Comment by desigonz** [comment]
Closing this for now but will reopen if we see this again.
