### ISSUE TITLE
Review job description for Policy Lab content strategist

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/techstack#3667]
**When is this project due?**
Would love to post the job by mid-January, so get review and iterate the job description by Jan 10 is ideal.

**What is the project that this work time will be charged to?**
Policy Lab (paperless)

**Have you already consulted the [ODD Style Guide](https://cityofaustin.gitbook.io/digital-style-guide/) before submitting this request?**
Yep

**Is the project resident-facing?**
- [ ] Yes
- [ ] No
N/A -- it's hiring

**Is this project a blocker for you or your team?**
Very much so. 

**If the project isn't resident-facing, who is the end audience? Depending on who this is written for, we may need more information to understand how to meet your needs.**

**What is the medium for this content?**

**What is the problem that a content strategist can help with?**
I have a [draft job description](https://docs.google.com/document/d/1Gad1QUZIK5n9SSjhL6M2rflVbcwnBU11Mevzu_czLSw/edit) for a content strategist that would be dedicated to the policy team. Naturally, that person would need to align closely with content team as well. I'd like a content strategist to review and advise on the job description.

**What deliverables do you expect from the content team?**
Comments and edits on a job description

**What approvals will be needed to complete this work?**

Marni's signoff before we post the position.

**Please provide the link to the Google Documents we'll need to use.**
https://docs.google.com/document/d/1Gad1QUZIK5n9SSjhL6M2rflVbcwnBU11Mevzu_czLSw/edit

**Comment by Jo-Dwyer** [comment]
@danielhonker I checked out the description and left a few notes. It looks great and as a reader, I'm piqued and can't wait to learn more in an interview, so it seems to serve its purpose.
