### ISSUE TITLE
Transition neighborhood center pages to services

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3668]
- [x] Identify the information pages about "services at various neighborhood centers" that should become service pages
- [x] Draft them. 

-------

### background

*Make sure to add the label "Content debt." If available, add the appropriate "Content type" or "Feature" label.*

https://joplin.herokuapp.com/admin/pages/189/edit/#tab-notes

**Have you documented this via the author notes field in Joplin?**
- [x] Yes!
- [ ] No, but I'll do it now

**Describe the content debt.**
In order to utilize the new locations content type and help residents prepare for a visit to a neighborhood center, well transition the current information page to a service page:
Steps:

Find a location
make an appointment
Gather necessary documents

**What is the long-term, ideal solution for this content debt?**

**Is this related to a feature request issue? (Add the issue number below and add the issue as a dependency.)**

**What approvals will be needed to publish this content change?**
All content has already been approved, so this switch doesn't require approval.

**Comment by gabrielaperezdelaosa** [comment]
[Get help with rent and utility payments](https://alpha.austin.gov/en/housing-utilities/pay-utility-bills-and-rent/get-help-paying-bills/get-help-with-rent-and-utility-payments/) this one was already live

[Get help searching for an applying to jobs](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZTo1Njg=)

**Comment by gabrielaperezdelaosa** [comment]
@Jo-Dwyer do you think you can squeeze in a review of these?

**Comment by Jo-Dwyer** [comment]
These look good to me @gabrielaperezdelaosa! Closing this issue.
