### ISSUE TITLE
Unclear input field title when uploading the content

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#3669]
## Describe the bug
**Collection dropdown when uploading the document**-
what is the purpose of the collection and How to create the new collection?How it can be helpful in publishing the documents?Do collections act as filters when searching?
![image.png](https://images.zenhubusercontent.com/5d236a251149c07fcf3f4fbc/f712a86b-8b10-4157-a7ea-3e970ef3bca5)

**Theme dropdown in Topic Collections Page**
What is the purpose and How it is helpful by adding the Theme?Does it effect the page placement in the website?
![image.png](https://images.zenhubusercontent.com/5d236a251149c07fcf3f4fbc/1731c09d-81dc-4e5d-bb73-58a359e115cf)

## Device and browser

MAC and Chrome

**Comment by desigonz** [comment]
Theme adds a topic collection to the IA.

**Comment by desigonz** [comment]
We're using collections to organize documents by department. We have other issues to dive deeper into this.
