### ISSUE TITLE
Select a content Type overlay - Top Toggle Tab affordance is Missing

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#3670]
## Describe the bug
Top Toggle Tab with "Content pages" and "Topic and Topic Collections" affordance like hover, clickable cursor and the tab selected is missing

**Note** "t" in Topic Collection should be "T"

## URL
Joplin Author Interface

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to ' author interface '
2. Click on 'New Content Type' Button
3. Notice the Tabs at the Top

## Current behavior
A clear and concise description of what happened
![image.png](https://images.zenhubusercontent.com/5d236a251149c07fcf3f4fbc/018a9dc4-3cd2-486a-9dd3-63b5c2b85d2c)

## Expected behavior
Affordance of which tab is selected and Hover, clickable cursor should show up

## Device and browser
Mac and Chrome

## Additional context
**Note:**Tested in staging

**Comment by desigonz** [comment]
> "t" in Topic Collection should be "T"
The lowercase `t` matches our style and was approved by content, so we'll keep it that way!

I'm going to close this issue, because these designs have been approved and redesigning the create content modal isn't a priority at the moment.
