### ISSUE TITLE
503 timeouts during Janis builds

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#3672]
## Describe the bug
We are experiencing severe performance issues during Janis builds. /graphql queries on joplin-staging are timing out with 503 errors.

## To Reproduce
I'm going to replicate this by loading staging data onto a PR Joplin site and running MONITOR_PERFORMANCE.

## Current behavior
We get errors like this: https://app.netlify.com/sites/janis-3568-localize-hours-exceptions/deploys/5e0faaeb247a83655fce0c4c

## Expected behavior
No errors. 

## Additional context
@easherma is bumping up our gunicorn timeout to 190 seconds. Which could save us in the short term, but we still need to fix the underlying cause of the slowdown.

Historical Issue: https://github.com/cityofaustin/techstack/issues/3503

**Comment by Niicck** [comment]
Replicated on a PR branch with the same data as staging:

[503 janis build timeout.txt](https://github.com/cityofaustin/techstack/files/4021205/503.janis.build.timeout.txt)

**Comment by easherma** [comment]
This could have to do with the response time of those queries, but also it could be the volume of requests that get fired off for a total site build. 

Do you get the same increase in timeout running locally? The heroku app could be hitting it's performance ceilings and gunicorn is adjusting accordingly.

**Comment by Niicck** [comment]
In conclusion:

- We increased our joplin-staging scaling to 2 dynos instead of one. This should allow us to handle the number of queries Janis throws at it during a site build. If not, we'll increase to another dyno as a short term fix.
- Silk will definitely cause queries to timeout. It's not suitable for use in staging or production.
- Scout APM is a performance monitor that's less of a burden on Joplin. It does increase the response time for queries during Janis builds (up to 10 seconds for the worst ones), but it does not seem to time out (which happens when queries are backlogged to 30 seconds). It's a worthwhile tradeoff because we need a performance monitor beyond Heroku's default (which only preserves the last 10000 log entries and the last 72 hours of performance metrics).
- Here is the /graphql api log output for a Janis build against a warm Joplin running Scout APM.
[scout_apm_janis_build_api_logs.txt](https://github.com/cityofaustin/techstack/files/4037939/scout_apm_janis_build_api_logs.txt)


Longer term potential solutions:
- Throttle/adjust the number of queries Janis sends simultaneously during a build process.
- Implement some sort of autoscaling solution for Joplin to handle load spikes.
