### ISSUE TITLE
Pagination style changes

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3673]
The spec: https://xd.adobe.com/spec/aed4d8fc-6ddb-4576-65e2-4125fdb42e8a-d8e5/ 
- [ ] selected state #0049C7
- [ ] hover #D9E8F6
- [ ] remove spacing between items to fit more on mobile
- [ ] ellipsis shouldn't function as a button, so they shouldn't have a border, hover, or selected state

**Comment by chase-vert** [comment]
Stale/irrelevant
