### ISSUE TITLE
Hours exceptions in locations

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3675]
## Describe the bug
An author can enter hours exceptions into the location content type on Joplin, but it does not appear on Janis. 

## To Reproduce
Steps to reproduce the behavior 
1. Go to Joplin
2. Make a location page
3. Add hours exceptions
4. Publish page

## Current behavior
Hours exception doesn't appear

## Expected behavior
- [ ] On location page
  - [x] Hours exception appears in English https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/
  - [ ] Hours exception appears in Spanish
- [ ] On contact card (department page)
  - [ ] Hours exception appears on contact card per [mock](https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/screen/893b8e98-9759-45ff-b2e9-401996a43e08/Template-Department-Desktop-)
  - [ ]  Hours exception appears on contact card in Spanish

**Comment by chase** [comment]
I think you meant to ping @chasechenevert and not myself 🙂

**Comment by chasechenevert** [comment]
Mocks posted.

**Comment by desigonz** [comment]
Thanks @chasechenevert! (And sorry other Chase 😳) The hours exceptions is actually a string field an author can enter to write something like "Closed on all holidays." This was the solution we came up for the really weird hours that can happen. Sorry I failed to explain that! Would you mind updating the mocks? 

![image](https://user-images.githubusercontent.com/5839508/71827321-99e56800-3065-11ea-9dbe-ac9b47c1b61a.png)

**Comment by chasechenevert** [comment]
Updated!

**Comment by chasechenevert** [comment]
Updated the `Contact Information` card on the department page to include the "hours exceptions". They'll be grouped under the time, and visible (not within the accordion) to make sure that residents don't need to click in to see this important info.

- Department page desktop: https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/screen/893b8e98-9759-45ff-b2e9-401996a43e08/Template-Department-Desktop-

<img width="508" alt="Screen Shot 2020-01-06 at 2 18 58 PM" src="https://user-images.githubusercontent.com/7027270/71846245-bbf3e000-308f-11ea-990a-708cf5359cc2.png">

**Comment by desigonz** [comment]
Thanks a million, Chase! @briaguya, mocks have been updated and this issue is ready for ya.

**Comment by briaguya** [comment]
@desigonz I don't have this in permanent PR app form but I do have a couple links on this for you to look at:
https://janis-3675-hours-exceptions.netlify.com/en/police-oversight/
https://janis-3675-hours-exceptions.netlify.com/en/location/office-of-police-oversight/

**Comment by desigonz** [comment]
@briaguya Thanks for the speedy work on this! I have a copy change for you (sorry about delivering this at the last hour):

- [ ] We're changing the label "Hours exceptions" to "Special hours"
  - [ ] On department page contact card
  - [ ] On location page
- [ ] When viewing page in Spanish, "Special Hours" translates to "Horarios especiales"
  - [ ] On department page contact card
  - [ ] On location page
- [ ] When viewing page in Spanish, localized text for hours exceptions appears

![image](https://user-images.githubusercontent.com/5839508/71986938-ead69700-31f2-11ea-93fd-f6da8c7952be.png)

So we'll test for full localization when we get to step 3?

**Comment by briaguya** [comment]
@desigonz updated the janis copy, the joplin side of localization should be covered by/tested with https://github.com/cityofaustin/techstack/issues/3568
