### ISSUE TITLE
Dummy Data doesn't get synced with migrations

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#3676]
Cool, we have a dummy datadump in Joplin now. That's great.

However.

It does not stay updated with our migrations. This means that when the schema changes in a dramatic way, the dummy data will be completely broken and unusable. Such is the case now. Sad face.

Our production and staging datadumps _do_ always work because we build them from docker images that exactly match the environments where that data is from. That's a big chunk of what the migration-test script does.

This is what we must do with the dummy data. The dummy data has to run on a docker image of Joplin that exactly matches the same point-in-time migration, and then we need to run the additional new migrations on it and save a new dummy data dump.

An easy way to do this is to automatically update the dummy data every time there is a push to master. It'll be easy to know which docker image to use (it'll always be the next-to-latest "master" image, which we always preserve in dockerhub).

We should do this sooner rather than later. We kind of need the dummy data to start doing effective testing.

Thank you for listening.

**Comment by desigonz** [comment]
Size please?
