### ISSUE TITLE
Pools - Meet with stakeholders in person

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#3677]
After getting to a point where the pools and spas guide draft is as close to finished as possible, I will meet with the following people:

- [x] Customer Service Team (Samantha Oldham and Stephanie Gulley)
- [x] EHOs (Dushun Phillips Mark Churilla)
- [x] EHO supervisor (Grisel Saenz)

Meeting scheduled 1/29 1 pm

Agenda TBD:

**Comment by desigonz** [comment]
- [ ] Create resulting issues
