### ISSUE TITLE
Edit the "Look up your trash, recycling, and compost pickup days" page

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#3678]
We got feedback on this page expressing confusion about the instructions in step 2: https://github.com/cityofaustin/alpha-feedback/issues/118

URL: https://alpha.austin.gov/housing-utilities/recycling-trash-and-compost/household-waste/trash-recycling-pickup/ 

As a resident, I need to know how to add my trash pick-up dates to my calendar, if that's an option. (If it's not an option, let's delete it.) 

Per @desigonz, this address look-up tool is an app we made based on recollect data. There was never an icon, so it's just a quick copyedit.

**Comment by desigonz** [comment]
- [ ] Publish out copy in English
- [ ] Publish out copy in Spanish

**Comment by srigdon** [comment]
Edited the page; sending the English copy for Spanish translation. Making a new issue for Spanish translation: #3809
