### ISSUE TITLE
Review label sizes for "blocks" especially on mobile

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#3679]
Seeing a few inconsistencies pop up via the work on `Locations`. I need to take a look at these blocks, especially on mobile to make sure I'm being consistent, and make issues where needed.

**Criteria**
- [ ] Offered by should go to `2rem` at the mobile break point to match Contact information

Example: 
https://janis-3504-nav-to-locations.netlify.com/en/health-safety/disaster-safety-relief/disaster-preparedness/testing-locations-on-a-service-page/
![Screen Shot 2020-01-06 at 2.47.00 PM.png](https://images.zenhubusercontent.com/5b7b6eae2bc79a5e7d4f874c/9d59f85d-2178-41ad-ac1b-2165d2322050)

**Comment by chasechenevert** [comment]
- [ ] `Offered by` should go to `2rem` at the mobile break point to match `Contact information`

**Comment by chasechenevert** [comment]
This is ready for dev.

**Comment by desigonz** [comment]
logged in #3961
