### ISSUE TITLE
Make rich text links in streamfields work on janis

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#3682]
This is the second part of issue 3537, inserting documents in rich text fields. The branch for that issue was prematurely merged to production, this is the second part that needs to happen for the whole feature to work properly. 

**Acceptance criteria**
- [x] Make it so Janis can format URLs properly
- [x] Turn on document insert functionality for the following rich text fields: 
  - [x] Steps
  - [x] Steps with options
  - [x] Steps with locations

**Comment by chiaberry** [comment]
https://joplin-pr-3537-docs-rtf.herokuapp.com/admin/pages/5/edit/#tab-content for QA

**Comment by chiaberry** [comment]
@desigonz  https://janis-3537-docs-rtf2.netlify.com/en/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup/

is now the janis that is connected to that joplin

**Comment by desigonz** [comment]
The documents work in rich text blocks but still not working in steps, steps with locations, and steps with options.

**Comment by desigonz** [comment]
Where are we on this issue?

**Comment by chiaberry** [comment]
links for documents in steps aren't being formatted by wagtail automatically like they are in other rich text fields, I was hoping to circle back to figure out why after i finished incremental builds, but that issues taken me longer than I had hoped. 

The little bit of digging that I've done on this issue makes me think that it would be a 5 to figure out how to format the document links in our steps. maybe a 3. I don't know if its an issue on how we implement steps, what makes the documents there different from other rich text fields.

**Comment by desigonz** [comment]
This is now in production!
