### ISSUE TITLE
Style guide: multimodal forms options

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3684]
**What is the URL?**

**Have you documented this via the author notes field in Joplin?**
- [ ] Yes!
- [x] No, there's no Joplin page,

**Describe the content debt.**
Outline how to offer multimodal forms (ex. [File a complaint](https://alpha.austin.gov/en/police-oversight/file-a-complaint-about-an-austin-police-officer/))

When a form is being offered as both an online form in Formstack and as a PDF, content authors should have guidelines to do this consistently.

**What is the long-term, ideal solution for this content debt?**

**Is this related to a feature request issue? (Add the issue number below and add the issue as a dependency.)**

**What approvals will be needed to publish this content change?**

**Comment by ablangworthy27** [comment]
@Jo-Dwyer will this be satisfied by adding info to the forms content type in the style guide?

**Comment by Jo-Dwyer** [comment]
@ablangworthy27 yes!
