### ISSUE TITLE
Style for Formstack's "save and resume"

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3686]
### As someone using the "save and resume" feature on a form, I want styling to be consistent, so that I have a seamless experience.

- [ ] Need styling specifications and mocks for "save & resume"

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/261a2170-34a4-4bcd-902f-b199487fa234)

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/0b40bb70-1d6b-42f3-a53d-4f102614482b)

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/7e779292-a309-478d-b2da-9fb4db9ecdd8)

**Comment by robbobfrh84** [comment]
This PR 👇, which, @Niicck  and I worked on, will be very relevant to this. And, hopefully prevent potential headaches getting this to work properly. 
- https://github.com/cityofaustin/formstack-alpha-theme/pull/6

**Comment by chasechenevert** [comment]
Collection for save and resume screens/assets are here: https://share.goabstract.com/19525891-3c33-46a7-bd65-035f287c1549?

- changed the title/label: "Save and Resume Later" to > "Save and resume later", but I welcome a content strategists review across this flow
- Email validation, error messaging, success confirmation: these features seemed to be missing from the flow and I can't tell if it's a bug, or oversight in the feature on Formstack's end, so I made this issue: https://github.com/cityofaustin/techstack/issues/4104

**Comment by desigonz** [comment]
Great—sending this to dev
