### ISSUE TITLE
Formstack confirmation page styling

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3687]
We need to style forms confirmation pages within the Janis design system

https://alpha.austin.gov/en/austin-public-health/request-a-day-laborer/

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/7ff4e476-cd30-435e-b0cc-ce0f03d7c72b)

- [ ] `font-family:'IBM Plex Sans',sans-serif`
- [ ] `line-height:2.8rem`
- [x] `font-weight:400`
- [ ] font color: `#212121`

**Comment by chasechenevert** [comment]
Updated the acceptance criteria, should be good to go!

**Comment by desigonz** [comment]
Thank you @chasechenevert! removing your assignment

**Comment by chiaberry** [comment]
@desigonz for QA: 

https://janis-3537-docs-rtf2.netlify.com/en/police-oversight/multipage-form-and-confirmation/
