### ISSUE TITLE
"All services" microcopy on topic pages

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3688]
On a topic page, we group things under "Top services" and "All services." But not all of the pages on this page are services.

https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/food-business-permits/

![image](https://user-images.githubusercontent.com/5839508/71937457-fd5cbc00-3171-11ea-8276-90a16a358c94.png)

Do we want to update that microcopy? "All pages", maybe?

**Comment by Jo-Dwyer** [comment]
@gabrielaperezdelaosa did this get solved after the megamenu meeting?

**Comment by gabrielaperezdelaosa** [comment]
Not really.... I think for now the consensus is that it's ok to call all of these pages services even if on the back end they fall under different content types? What got resolved was making it so that less things surfaced on the All Services page.

**Comment by srigdon** [comment]
Content decided: "All pages" instead of "all services". @toribr what do you think? 

Two pieces of microcopy in English and two in Spanish:

- On topic pages:  All services --> All pages 
- On topic collection pages: See all services --> See all pages

**Comment by gabrielaperezdelaosa** [comment]
Here is [the excel doc where I'm tracking out bilingual microcopy. ](https://docs.google.com/spreadsheets/d/1jx9gdy3NwBvcVmsvk7VoFjUqvQ4EaEgmw93Mp26pnkw/edit#gid=0)

Please note the blue (for English) and yellow (for Spanish) highlighted updates.

**Comment by toribr** [comment]
@srigdon All pages? I don't like it. It's kind of vague, isn't it? What resident would want to see "all pages"? Does that mean every page on the website?

**Comment by srigdon** [comment]
@toribr Rationale is that on a topic page, "All pages" is more accurate than "All services," because many of those pages aren't services, and users don't need to know how we define a service vs. information in order to navigate a topic page. "All pages" on a topic page would mean all pages related to that topic.

**Comment by toribr** [comment]
@srigdon Thanks for that. Yes, "Top services" should stay the same.
