### ISSUE TITLE
Install HotJar or similar

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#369]
- [ ] Choose subscription level and procure
  - [ ] Janis
  - [ ] Joplin

Aha! Link: https://desi1.aha.io/features/RT-300

**Comment by amenity** [comment]
@toribr has experience with these tools - I believe @benweatherman does too...

**Comment by amenity** [comment]
@benweatherman We will need to purchase a HotJar subscription, yes? Also, I assume this is not a priority until we have staff using hte author interface?

**Comment by toribr** [comment]
@amenity Right, and also they have a free version we can check out first.

**Comment by easherma** [comment]
@oliver2g @toribr can we decide if this is a priority for Janis/Joplin 2.0? I'm guessing not since site traffic is still expected to be low.

**Comment by oliver2g** [comment]
Agreed. I think we can keep it where it is in the Medium/Long Term backlog. When we have more content and expect more traffic, we can re-visit.
