### ISSUE TITLE
Missing some topic collection translations

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3695]
We're missing some topic/topic collection translations.

**Acceptance criteria**
Spanish translations published for:
- [ ] Business permits and licenses
- [ ] Food business permits
- [x] Pay utility bills and rent
- [x] Kids and family resources
- [x] Help finding work

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/37e3d84e-e969-454e-b485-4ae8fb5e1416)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/e4b7a594-ffc2-4d93-b983-4522099a498d)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/c4eef755-c187-4fbb-8835-3dde856320e6)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/8387f2f2-2456-4f97-9897-4927248e8d3d)

**Comment by srigdon** [comment]
Added the translations we have. "Business permits and licenses" and "Food business permits" are both part of #3608. Closing this one and including topics and topic collection names in the mobile food vendor permit guide translation batch.
