### ISSUE TITLE
Write service page for reporting smoking in public places

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3696]
### As a resident, I want to be able to report a violation of the smoking in public places ordinance via multiple channels (online and on the phone), so that I can have multi-modal access to a service.

We are developing an online form for residents to report violations of the ordinance, but we also want to offer other ways to report, such as by phone. We'll probably follow the options accordions on the [file a complaint service page](https://alpha.austin.gov/en/police-oversight/file-a-complaint-about-an-austin-police-officer/).

**Comment by ablangworthy27** [comment]
https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyODA4
