### ISSUE TITLE
Location content type style guide entry

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3697]

**Comment by ablangworthy27** [comment]
This has been drafted. I need a second pair of eyes to look it over. @srigdon @Jo-Dwyer

**Comment by Jo-Dwyer** [comment]
@ablangworthy27 this looks good. I have just a few notes. 

- [ ] I added a link to the service page entry 
- [ ] "if your location is co-located with another place, or if it is located inside of a larger facility." I want to get more clarity about what co-locating means. Is it when we're co-locating a CoA service facility with non-CoA facilities in the same location? Some locations will have more than on eCoA office/ dept at it. A user may not be clear on what the difference is.
- [ ] "can be useful if the phone number is ~for~ a hotline or ~is~ a line for making appointments, or any other purpose more specific than general ~contact~ information.
- [ ] "Include the three closest bus lines." Can we specify a distance/walk time of 15-20 min or less? Some facilities are more than a 15 minute walk from a bus stop
- [ ] "must be input" might be clearer written as "must be entered"
- [ ] hours exceptions: "if a location stays open late on the first Friday of each month, the hours exceptions text box ~would be the appropriate~ is the right space to communicate that. This is also where you ~may~ indicate City holiday closures"
- [ ] "In this section, you can add any services that are administered at the location. When you do ~so~ this, you must either ~input~ enter specific hours of operation for the service or choose to default to the location’s hours."

**Comment by ablangworthy27** [comment]
Ok, I incorporated all these except the co-location one. I don't really know how best to clarify this because it hasn't really come up yet.

**Comment by desigonz** [comment]
🙌 When y'all publish this, let me know, so I can make a dev issue to hook it up in Joplin.

**Comment by ablangworthy27** [comment]
@desigonz I published. It may change at some point when we know more, but it is live now.

**Comment by desigonz** [comment]
Thanks @ablangworthy27! I'll make an issue for dev.

FYI it's appearing first in the "pick the perfect page type" nav, not sure if order matters

![image](https://user-images.githubusercontent.com/5839508/74950006-1e950700-53c4-11ea-9485-3b4ed8411173.png)
