### ISSUE TITLE
Draft the pools and spas guide in Joplin

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3701]
Let's get the pools and spas guide drafted in Joplin so that we can demo it to Environmental Health folks!

**Comment by ablangworthy27** [comment]
- [ ] Finish transferring content from google docs to Word. This is necessary for feedback
- [ ] Draft pages in Joplin
- [ ] Generate list of missing info to ask about in meeting
- [ ] Finesse the joplin drafts, making sure that links are working, etc...
- [ ] Create the guide page, and collate all the pages

**Comment by ablangworthy27** [comment]
The [draft](https://alpha.austin.gov/en/preview/guide/UGFnZVJldmlzaW9uTm9kZTozMDcw) is ready to present.
