### ISSUE TITLE
Move information page content type into its own folder

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3709]
We're going to refactor our content models into different Django apps. We tested this with the location content type. Now let's use a similar approach for **information pages**. We'll want to make sure migration works (@briaguya, please add more details!).

**Comment by desigonz** [comment]
Next steps:
- @easherma and @robbobfrh84 to pair
- Let's try 5 story points to do the magic option 📁
- If that doesn't work, we'll do 🍝
Also for documentation's sake, maybe a dev can translate my emoji :)

**Comment by briaguya** [comment]
@desigonz the idea is to do this in one fell swoop for all page types in https://github.com/cityofaustin/techstack/issues/4089

**Comment by desigonz** [comment]
Looped into @briaguya's Joplin 3.0 work, closing this.
