### ISSUE TITLE
Identify use case for self-serve form platform API

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#371]
Need a use case for #247 .

**Comment by NateATXCode** [comment]
Short Term Rental Applications, Austin Code
For current process see: http://www.austintexas.gov/str 
For current form(s) see: http://www.austintexas.gov/page/short-term-rental-types

**Comment by amenity** [comment]
Thanks, @nateATXCode

**Comment by amenity** [comment]
Cleaning out ancient, probably-no-longer-applicable, issues.
