### ISSUE TITLE
Topic collection still live after unpublishing

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3712]
## Describe the bug
In #3689, we noticed that unpublished pages are still live on Janis, and are publishing out on topic pages 😱Luckily, @briaguya fixed it. However, now I'm seeing a similar thing happen for a topic collection—[Health classes and resources](https://alpha.austin.gov/en/health-safety/healthcare-prevention/health-classes-and-resources) should publish out, but it is, and it's appearing blank on the topic collection it was assigned it.

![image](https://user-images.githubusercontent.com/5839508/72081726-97cd1480-32c4-11ea-98f6-6a6150157c6d.png) 
![image](https://user-images.githubusercontent.com/5839508/72081885-e5e21800-32c4-11ea-9eda-fa1200c165a5.png)
![image](https://user-images.githubusercontent.com/5839508/72081939-feeac900-32c4-11ea-9554-5fbea2dc9a8a.png)
*note that it says draft in the top right!*

**Acceptance criteria**
- [ ] If I unpublish a topic, it does not appear on the topic collection it was previously on
- [ ] If I unpublish a topic, it is not live at a Janis URL

## To Reproduce
Steps to reproduce the behavior 
example: 

## Current behavior
A clear and concise description of what happened

## Expected behavior
A clear and concise description of what you expected to happen

**Comment by robbobfrh84** [comment]
Unless this is a hint of something more problematic on the Joplin side, it'll hopefully be...
- Just a condition to add to Janis.
