### ISSUE TITLE
Funny spacing before required

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3718]
It looks funny when "Required" falls to the second line. @chasechenevert, can you develop acceptance criteria for this?

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/f8218c4f-8dc3-4b80-9194-e6c0d01ab6dc)

**Comment by desigonz** [comment]
Let's try to fix this with a three.

Acceptance criteria: 
- [ ] When "Required" is the first thing on it's own line, no space between the margin and the required.

**Comment by desigonz** [comment]
Margin is currently tied to the "Required"
![image](https://user-images.githubusercontent.com/5839508/72841621-59d4d680-3c5c-11ea-825a-70297ab6a499.png)

**Comment by Niicck** [comment]
- Put a right margin on the text inside the "title" span.
- Remove left margin on "Required" span inside the "title" span.

**Comment by chasechenevert** [comment]
Nick's solution sounds right to me. Ultimately we don't want "Required" to appear as though it's indented when it gets shifted to another line.

**Comment by desigonz** [comment]
Preview link with the form: https://alpha.austin.gov/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyOTI2

**Comment by desigonz** [comment]
And here is the non-embedded form: https://cityofaustin.formstack.com/forms/cprc_application_copy

**Comment by briaguya** [comment]
## quick options:
### Keep it as is:
<img width="770" alt="Screen Shot 2020-01-30 at 5 40 54 PM" src="https://user-images.githubusercontent.com/6384156/73500294-e16ec380-4387-11ea-802a-4e254689dbd4.png">

### Just remove the space
<img width="709" alt="Screen Shot 2020-01-30 at 5 42 13 PM" src="https://user-images.githubusercontent.com/6384156/73500317-ef244900-4387-11ea-8b44-5e46fd002131.png">

### Always go to a new line
<img width="737" alt="Screen Shot 2020-01-30 at 5 42 04 PM" src="https://user-images.githubusercontent.com/6384156/73500325-f64b5700-4387-11ea-9ffd-a8e2570d2da5.png">

**Comment by desigonz** [comment]
Thanks @briaguya! Let's go with just remove the space for the CPRC form launch. Then @chasechenevert can review designs and make an issue for the future, if we decide it's a priority later.

**Comment by briaguya** [comment]
https://github.com/cityofaustin/formstack-alpha-theme/pull/4

**Comment by chasechenevert** [comment]
Ouais, thanks @briaguya! Agree with @desigonz, removing the space looks like what we were expecting. 

It's good to go~

**Comment by desigonz** [comment]
Reassigned the issue to @briaguya and put it back "in progress" until this gets implemented on Formstack. Brian, do we need to coordinate with @Niicck or @chiaberry to get this theme update live?

**Comment by desigonz** [comment]
@chiaberry will help push this to Formstack!!

**Comment by chiaberry** [comment]
the style change has been added to formstack!
