### ISSUE TITLE
Update digital services style guide

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#372]
We need to make sure it includes the basic information:
- [x] complete sentences
- [x] every page needs context

General updates:
- [x] rename sections so authors know what they will find in each section
- [x] take out the tacos :(

**Comment by ashleecoa** [comment]
Change Speak to the people, not over them to "What is service-oriented language?"
Change Accessibility for all to "Make content accessible"
Change Make Hemingway proud to "Understand writing principles, voice, and tone"
Change Write with some style, formatting and flair to "Make content easier to read"

Keep same:
Focus on the public and their needs
Write for all languages, please, por favor, xin vui long, رجاء, 請
Create quality content
Put your best photos forward
Write for search engines 

Thoughts @LauraTrujillo

**Comment by LauraTrujillo** [comment]
Yeah I like that!

Moving your Slack comment here: 
Complete Sentences
* Write in complete sentences. This ensures you are communicating a complete and clear statement to residents.
* Avoid writing sentence fragments.
-- Example: Shows no signs of improving after the input session.
* Avoid writing run-on sentences.
-- Example: The City will be requesting resident input on the new master plan residents have asked for meetings to be held after 6 p.m. in multiple locations to have all voices heard.

**Comment by ashleecoa** [comment]
@LauraTrujillo do you have any more background on the "context" section asks?
