### ISSUE TITLE
Review Smoking in Public Places form

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3723]
@ablangworthy27 is developing the form; let's have @toribr do a round of review

**Comment by desigonz** [comment]
@ablangworthy27 Can you share a link to this form?

**Comment by ablangworthy27** [comment]
https://cityofaustin.formstack.com/forms/smoking_in_public_spaces_online_complaint_form_2_

**Comment by ablangworthy27** [comment]
Service page:
https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZTozMDEz

Form:
https://alpha.austin.gov/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyODky

**Comment by toribr** [comment]
This looks good to me @ablangworthy27

**Comment by Jo-Dwyer** [comment]
### Service page ###

Step 1 opens prompts me to learn more about municipal code and then opens code in the same window without a clear sense of what I'm supposed to learn and how to resume the process of filing a complaint. 
 
Possible solution

* Add language to frame step 1 within the context of this service, "Report smoking in public place".
> Before you file a report, learn more about what the ordinance prohibits
*  Direct to the information page
> [Smoking in public places](https://alpha.austin.gov/en/health-safety/health-prevention/disease-prevention/smoking-in-public-places/)

Step 2 looks good

Step 3 has a timeframe expectation of 3 days to process; is there a time expectation for the 3-1-1 submission?

### Form ###

Add helper text for addresses of city parks or facilities within a larger city property. What if it happened in Zilker Park, but I'm not near Stratford Drive? Can I submit an approximate address?

> Tell us about the violation
> Provide the address of the location where the violation occurred. **If the violation happened within a park or larger city property, use the general location address.** (Required)


Add "city park" to the dropdown menu.

Blow the date and time, what does "If other, please describe" refer to? It's required, but I don't know what the otherness is.
