### ISSUE TITLE
MVP specs for events/calendar: Janis

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3724]
Goal: specs and acceptance criteria ready for dev by end of sprint
- [ ] Homepage view of events
- [ ] List view of events
- [ ] Detail view of events

**Comment by chasechenevert** [comment]
Feedback to incorporate into draft 2
Reference: [pin-up Janis-Joplin draft 1 ](https://docs.google.com/document/d/1f5HCJz0UPdujIK1t6RwcZtXBP2Ggg4Qz6jiGGHXyRHM/edit#heading=h.xku6j63ue47n)

**All views (list, detail, home block)**
- [ ] Cost information: include an example with a price range

**List page**
- [ ] Short description: make a version without short description, bring this up at pin-up
- [ ] Add "See past events" link near page heading

**Detail page**
- [ ] Overall: the layout here doesn't feel solid yet, mostly because of the event information block in the page body. I'm going to try to address this with the page heading, and try a version with the block moved to the rail
- [ ] Location vs. directions: create more distinction between this information (icons, links)

**Comment by chasechenevert** [comment]
# Round 3 to-dos
Google doc: [Round 2 pin-up notes](https://docs.google.com/document/d/1ZwjtJrnUm4jn1fNi0NNodT5afzdwThFJks2fXn8HX9c/edit#)

- [ ] Tablet
- [ ] Mobile

**Home**

- [ ] Change label from, “Today’s events”, to “Upcoming events”
- [ ] Add date, day, month, and year back as an overline

**List**

- [ ] Remove “January 2020” label
- [ ] Display fee information
- [ ] Take month from day/date block, add it to the body somewhere
- [ ] Make day/date larger
- [ ] Try adding the homepage block to the first page, subsequent pages in the view (pagination) won’t have this block
- [ ] Remove pin icon from location name
- [ ] Past events: consider adding a badge?

**Detail**

- [ ] Find a spot for “Add to calendar” 
- [ ] Add space for registration link

**Comment by chasechenevert** [comment]
# Handoff checklist
- [ ] Mocks for all breakpoints
  - [ ] [Desktop](paste URL here)
  - [ ] [Tablet](paste URL here)
  - [ ] [Mobile](paste URL here)
- [ ] All interactive states: includes all applicable interactive states (hover, down, focus, keyboard focus, disabled)
- [ ] Defined behaviors: includes guidelines for layout (wrapping, truncation, overflow), animation, interactions, etc.
- [ ] Usage guidelines: includes a list of dos and don'ts that highlight best practices and common mistakes
- [ ] Accessible contrast: follows WCAG 2.0 standards for contrast. Minimum is AA, but we should strive for AAA where possible.
- [ ] Keyboard interactions: follows WCAG 2.0 standards for keyboard accessibility guidelines and includes a description of keyboard interactions.
- [ ] Spec is merged into Master XD file
- [ ] Design tokens: all design attributes (color, typography, layout, animation) are included. We're not using tokens yet, but ensuring that the values are consistent before going to dev is a must.
- [ ] Translations: is there anything hardcoded in Janis that needs to be translated to Spanish? What else do we need to consider?
- [ ] Previews: Will this content type or feature set require previews in Janis? 
- [ ] Unit tests: Will we need to write any unit tests for this content type or feature set?

**Comment by chasechenevert** [comment]
# Draft 3 feedback for final spec
**Home**
- [ ] Price range: include example
- [ ] Multiple locations: remove example

**List**
- [ ] Price range: include example
- [ ] Feedback component: hide
- [ ] Canceled badge: move from date badge to above event name, matching the design on all other views

**Detail**
- [ ] Feedback component: add
- [ ] Price range: include simple fee schedule example with registration link
- [ ] Icon color: decide on gray
- [ ] icon color: make new issue to change this globally in the contact component

**Comment by desigonz** [comment]
Is this issue ready to close?

**Comment by chasechenevert** [comment]
Event spec MVP
- [Overview](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/)
- Home page: [desktop](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/screen/8d5f7c07-f178-473d-91cb-77a50ad353a0/Event-MVP-Home-Desktop)
- Home page: [mobile](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/screen/3d291391-3fdf-4bdd-876a-d0f51aa9fcb0/Event-MVP-Home-Mobile)
- List page: [desktop](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/screen/5a90f9d0-253a-4275-9248-0cdae662b27c/Event-MVP-List-Desktop)
- List page: https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/screen/27ea2637-f07e-45e7-a434-20ff08138c5f/Event-MVP-List-Mobile
- Detail page: [desktop](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/screen/3da19c95-f6c3-4177-9bba-98e36449bdbd/Event-MVP-Detail-Desktop)
- Detail page: [mobile](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/screen/43e6c429-6434-49c1-9bdb-dab5547c8b0d/Event-MVP-Detail-Mobile)

---
# Notes
## Home page
**Number of events listed**
- Max: 3
- If 0: do not display the component

**Fee and registration display**
- If there’s a registration link on Joplin display “Registration required”, this won’t be a link

**Possible combinations**
- Free
- Free • Registration required 
- Registration required 
- $1 
- $1–$5
- $1 • Registration required
- $1–$5 • Registration required

**Location display**
- Display name of location, exclude address
- If no location name, display address
- Don’t display “Get directions”

**Display**
- Mobile: vertical list
- Desktop: minimum width: 277px, below which the component should switch to the list vertical view

## List page
- Max number of events in list: 10

## Detail page
- All icons should match text color: #272727

**Rich text affordances**
- Bold
- Italic
- Link
- Forced line break
- Lists: ordered, unordered

**Fee and registration display**
Possible displays on the detail page view. Arrows denote the outbound icon next to links that take the resident away from the domain.
- Free
- Free • Register ⬈
- Register ⬈
- $1
- $1–$5
- $1 • Register ⬈
- $1–$5 • Register ⬈

**Location display**
Get directions ⬈
