### ISSUE TITLE
MVP specs for events: Joplin

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3725]
MVP fields (*=required)
- [x] Title *
- [x] Description *
- ~~[ ] Short description *~~
- [x] Start day/end day/~~all day~~ *
- [x] Time (start* and end)
- [x] City Location * (use same method of entry as on service page)
  Should have ability to add > 1 location, which displays as "multiple locations"
- [x] Related dept *
- [x] Contact *
- [x] Registration link
- [x] Cost (free/add cost and label)
- [x] Ability to cancel (no rules for MVP)
- [x] ~~Scheduling (date post is published and unpublished. Unpublished date has a default (?) and can also be set manually.)~~
**Multi-day events are manually created 

- [ ] Non-city location added

Janis
- [ ] download ics?
- [ ] no rules around how long events are kept (keep all for now)

 See [design pin-up](#1)(https://github.com/cityofaustin/techstack/issues/3646) for details re discussions during pin-up

New (post Library events mtg):
- [x] Discuss "All events are free" as default
- [x] Is there an affordance for meeting room? (wouldn't be on location, so needs to be added on event: in the body? or what? does that seem too separate from the rest of the location?
- [x] Are events that are cancelled within two weeks (for example) handled differently than events that are cancelled that are more than two weeks away? (No- up to author. Post-poned events are also handled manually)
- [x] Look into ics series (series is MVP - single is MVP)
- [x] Location taxonomy; yes or no? No for now.
- [x] short description - is it really needed? Not at this time.

Link to [library meeting notes](https://docs.google.com/document/d/15PtXZNWr4IZasx1dRVSnX_pc5vGzLHiosufJsNv191g/edit) which contain many ideas for future features
Post MVP conversations:
- [ ] Discuss the advantages/disadvantages of combining start date with time/end date with time. Allows for multi-day events, but not for flexibility in start/end times. What happens if the last day is shorter, for instance? 
- [ ] Complex date & time (mass.gov), Listing info (SEO only), How they cancel, logo or image.

**Comment by toribr** [comment]
![Events - Joplin_final](https://user-images.githubusercontent.com/3790067/72375878-89229b00-36d2-11ea-9926-fcdacb41fda6.png)

**Comment by toribr** [comment]
https://xd.adobe.com/view/13cf6c47-e3bc-4c21-7449-0f4cb312ace0-65fe/

**Comment by desigonz** [comment]
Acceptance criteria in #3814
