### ISSUE TITLE
Implement image gallery for Foster Application

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#373]
Create image gallery components as mocked for Foster Process Page.
This also relates to issue #220 and #260 for an image gallery on a Service Page.
Functionality includes
- lightbox
- responsiveness

Consider how this image gallery data
- will be sourced from Joplin
- will be inserted into Joplin

Aha! Link: https://desi1.aha.io/features/RT-299

**Comment by mateoclarke** [comment]
I think @luqmaan helped get this setup so I know he has some experience with the data from PetHarbor:
https://twitter.com/CutePetsAustin
https://github.com/open-austin/CutePetsAustin

**Comment by cthibaultatx** [comment]
# Mock-ups

## Desktop with 3 images and captions
![screen shot 2018-05-24 at 7 17 39 am](https://user-images.githubusercontent.com/20911665/40484911-a9f3a86c-5f22-11e8-830a-2333e07f5b82.png)

## Mobile with 3 images and captions
![screen shot 2018-05-23 at 8 55 06 pm](https://user-images.githubusercontent.com/20911665/40484936-be17323c-5f22-11e8-92ba-c131daa42c43.png)

Still to come:
## Desktop with more than 3 images
## Mobile with more than 3 images

## Desktop with less than 3 images
## Mobile with less than 3 images

**Comment by cthibaultatx** [comment]
Based on these mocks, we should max out how many images people can add to a gallery module BUT that could change.

Also, @benguhin brought up using variable image heights to allow for portrait and landscape formats simultaneously. These image mocks use a ratio that's almost square so it will crop images down and look consistent. We may decide to go with variable heights in the future.

Available to chat about these notes and mocks if there's confusion or questions!

**Comment by ifsimicoded** [comment]
related to issue #260

**Comment by cthibaultatx** [comment]
Notes from @briaguya "I was wondering if you could put a few more numbers in there (distance between image blocks in vertical/horizontal view mode (should it be adaptive/is there a max width/height we want for images)"

Interaction and formatting reference via AirBnB "Similar listings" component near bottom of page: https://www.airbnb.com/rooms/11950278?location=Santa%20Rosa%20Beach%2C%20FL%2C%20United%20States&s=2idiG2Gy

- [ ] Fixed image box aspect ratio: 
-- desktop width x height: 303 px x 238 px

- [ ] Image padding: 2rem or check mocks :)

- [ ] Crop portrait images to fill width and center vertically

- [ ] Max container width 1200 px

- [ ] In mobile:
-- images stack and all images are shown (vs. in desktop, max 3 are shown)
--container is full width on mobile

- [ ] See if we can't enable swiping for pro users with touchscreens

**Comment by cthibaultatx** [comment]
Sketch file @briaguya https://drive.google.com/file/d/1tX8pTU9cQspYupRHIl4xW-CBQHW_gtT_/view?usp=sharing

Let me know when you run into a question!

**Comment by mateoclarke** [comment]
Relates to https://github.com/cityofaustin/janis/pull/254

So far its implemented in Storybook but not on Process Pages yet.
