### ISSUE TITLE
Information page - Love chickens

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3732]
### As an [member of the odd flock] I want [to better understand the history of the love chicken] so that [I can share it with new team members].

**Is your feature request related to a problem? Please describe.**
Nobody knows the full history of the love chicken.

**Describe the solution you'd like**
An information page about love chickens.

**Describe alternatives you've considered**
Idk, probably just talking to @wilhitem @amenity and @mateoclarke to start and writing down anecdotes from the history of the love chicken and its meteoric rise.

**Additional context**
This is both very sarcastic and entirely sincere at the same time.  I have no expectation of this ever happening but boy would I be tickled if it did.

**Comment by amenity** [comment]
🤗💛🐣

**Comment by easherma** [comment]
You mean 
https://odd.austintexas.io/love-chicken/

Doesn't tell you all you need to know?
