### ISSUE TITLE
Form best practices (formstack)

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#3735]
Gather up best practices for content team to use as basis for style-guide

**Comment by toribr** [comment]
Is every question really required?
Are the questions grouped sensibly?
Think about what the resident may need to answer any questions. Will they need some paperwork, or need to reference some document they already have? It's better to tell them ahead of time what they will need to complete the form so they don't have to stop what they are doing to find something.
Stay away from personal info as much as possible. If it's absolutely required, it's helpful to tell them why it's needed, and what will happen to it.

**Comment by toribr** [comment]
This is about all i can think of at the moment. Hopefully, it's enough for content to get going with.

**Comment by desigonz** [comment]
Awesome, thanks! Passed off to content in #3254.
