### ISSUE TITLE
Joplin logs/analytics

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#3736]
Why? Because numbers. Eventually they may help us. 

We would have accurate quantitative data on platform, screen size, etc.
We could also know things like # of pages edited / mo, what parts of the app were most used, etc.

What about data on *how* it's used. Can we set up the ability to know how many events/mo, or similar sorts of stats?

What sort of quantitative data would we want to know if Joplin had paid subscribers that paid our salary?

I've assigned this to myself so that I can further define the above question.

**Comment by easherma** [comment]
FYI: https://github.com/tomdyson/wagalytics

**Comment by easherma** [comment]
And more tangential: 
https://github.com/torchbox/wagtail-experiments
https://github.com/wagtail/wagtail-personalisation

**Comment by desigonz** [comment]
We could also just start by setting up Google analytics on Joplin and Joplin staging 🙃 Making this into an epic. Let's look at this when we groom next sprint and create a few issues.

**Comment by toribr** [comment]
Draft: 
* how many times a week or month do they use the system? 
* how many hours a week or month do they use the system?
* are they creating new content or editing existing content or both?
* Are they writing in the tool or cutting and pasting from elsewhere? if cutting and pasting, then from where? how does formatting change? 
* Is their work moderated or approved by someone else, and if so, how? (physically how - sent via email, in person, paper, what?)
* how many people in the approval process?
* how many in their office touch drupal?
* what types of content do they usually work with? give list: events, news, information, etc - may need descriptions so they can decide 
* approx age (or do ask about other types of content making apps they use, ie, previous experience with Wordpress, squarespace, etc.)
* what other tools, software or websites do they use in their content-related work
* do they use google analytics? if so, what do they look at?
* what size monitor do you use?
* what dept are they in?
* do they do any translations? if so what language?  META or GAnalytics (all authors)
* How often is content changed on the system? by everyone?  (get files) • Can this be broken down into chunks, ie, 10% changed every week (perhaps logs will show this?)
*  what screen size (%’s)
* browser (%s)
