### ISSUE TITLE
janis performance: Alpha loads slow on slow internet, mobile

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3737]
![slow_guides.png](https://images.zenhubusercontent.com/5c3515e58332e72a247dae38/0701d7f2-c5be-4ef8-a1c4-ccd06c94320e)
![slow_home.png](https://images.zenhubusercontent.com/5c3515e58332e72a247dae38/43dad80d-639e-469f-8d1e-8e8a7e60edae)

**Comment by easherma** [comment]
Some pretty clear low hanging fruit for when we pick this up:

* evaluate how our webpack is set up. react-static is supposed to help alot with code splitting, but it still seems like we're loading a lot for each page
* seems like we dont have gzip setup for compression, which we did do for opo form and for joplin. That alone would be super quick to set up and seems like it would have a big effect.

Maybe keep an eye out for:
* not sure how search mvp is set up, but it could have a performance hit if its loading the entire query of all pages to be searched on the client.

**Comment by Niicck** [comment]
https://gtmetrix.com/reports/alpha.austin.gov/V3hH7NCF
