### ISSUE TITLE
RDS SSL Certificates by February 5th

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#3738]
We have to update the SSL Certificates on all of the databases we're using in AWS. Here's the full email from our AWS account manager:

Hello,

As an Amazon RDS customer, you should have received email from AWS notifying you about rotating your SSL certificates. The SSL certificates for RDS database instances are being updated. The certificates are being updated as part of standard maintenance and security best practices for RDS, and action is required by all RDS customers who use SSL to connect to their database instance in order to maintain connectivity to their database instance after the update. As part of the standard maintenance and security best practices for RDS, the SSL certificates for RDS instances are updated every few years.

 

Please reference the following documentation for certificate rotation.

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html

 

This change can be scheduled to occur during the normal RDS maintenance window or on your own, after hours you can perform it in real-time.

 

We encourage you to test these steps in a development or staging environment before implementing them in your production environments. If not completed, your applications using SSL/TLS will fail to connect to your existing database instances as soon as RDS rotates your certificates on the database side prior to March 5, 2020.

 

Please reply to this email letting me know you received the information and let me know if you need any help, the documentation incudes both screenshot instructions for the UI as well as a CLI script.

 

If you would like more information on the need for rotating the certificate authority, here is a blog with more information on updating your certificates.

https://aws.amazon.com/blogs/database/amazon-rds-customers-update-your-ssl-tls-certificates-by-february-5-2020/

**Comment by easherma** [comment]
Where are we actually using RDS?

**Comment by Niicck** [comment]
In ctxfloods. And they're updated now.
