### ISSUE TITLE
Phone number not appearing on location page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3742]
## Describe the bug
There's a location phone number entered in Joplin but it's not appearing on the location page in Janis.

Janis
![image](https://user-images.githubusercontent.com/5839508/72276328-49d24c80-35f5-11ea-823d-57deef5dbc8c.png)

Joplin
![image](https://user-images.githubusercontent.com/5839508/72276336-4dfe6a00-35f5-11ea-86e2-868e1c32264b.png)

XD mock
![image](https://user-images.githubusercontent.com/5839508/72276346-52c31e00-35f5-11ea-9e92-e65f8dd78bb5.png)

- [x] Location contact block appears on the location page, above the address block, per [Janis mocks](https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/screen/62dce76d-7739-43a1-a958-9c2e122b74f8/Template-Locations-MVP-Desktop/)

## URL
https://alpha.austin.gov/en/location/office-of-vital-records/
https://joplin.herokuapp.com/admin/pages/328/edit/#tab-content

## To Reproduce
Steps to reproduce the behavior 
example: 

## Current behavior
A clear and concise description of what happened

## Expected behavior
A clear and concise description of what you expected to happen

**Comment by chiaberry** [comment]
does that location also have an email address? It looks like 
`    {!!phone.value && !!email.value && (
      <LocationPageContact phone={phone} email={email} />
    )}` is the culprit. no email preventing the contact component from showing. 1?

**Comment by desigonz** [comment]
There is no email address. But we'll want a phone to appear even if there is no email.

**Comment by briaguya** [comment]
@desigonz check https://janis-3742-location-page-phone.netlify.com/en/location/office-of-vital-records/

**Comment by desigonz** [comment]
QA passed, thanks @briaguya!
