### ISSUE TITLE
"View live" for location pages doesn't work

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3743]
## Describe the bug
"View live" links aren't working for the new location content type.
https://github.com/cityofaustin/joplin/pull/527

![image](https://user-images.githubusercontent.com/5839508/72277880-66bc4f00-35f8-11ea-9a5a-99acb0989d46.png)
![image](https://user-images.githubusercontent.com/5839508/72277908-7471d480-35f8-11ea-85ee-6f12ee0f520e.png)

**Acceptance criteria**
All "View live" links open the live page, including:
- [x] On the main search page: `view live` button
- [x] On the main search page: `Live`/`Live + draft` links in the righthand column
- [ ] On an individual edit page:  `Live`/`Live + draft` links within the header

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to Joplin
2. Search for a location page
3. Click "view live"

## Current behavior
The same Joplin page opens in a new window

## Expected behavior
The corresponding Janis page opens

**Comment by easherma** [comment]
location pages don't follow the previously established url structure, so this is falling back to 'no' link
so we'll need logic to parse the janis_url for this content type
this kinda blends into refactoring of the API we need to do, and refactoring on the janis side as well. but if we ignore trying to make this a helpful fix in those aspects as well and just make it work for this function, its not a bad lift, its something like:

* Wagtail gives pages a content_type as a property, so we do a conditional on that as part of janis_url()
* if its a location page, follow the rules of the location type ( i.e. <language slug>/location/<location_name>)

**Comment by desigonz** [comment]
@briaguya Do you have a QA link for this one?

**Comment by briaguya** [comment]
@desigonz 
Go here: https://joplin-pr-3743-location-page-v.herokuapp.com/admin/pages/search/?q=&content_type=locations.locationpage
Click view live

**Comment by desigonz** [comment]
Qa complete!
