### ISSUE TITLE
Service hours exceptions on location pages—design

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3744]
## Describe the bug
We allow hours exceptions for services at a particular location, they aren't appearing on Janis.

![image](https://user-images.githubusercontent.com/5839508/72278454-a6376b00-35f9-11ea-8462-e0c3b5f0fd4a.png)

## URL
Janis: https://alpha.austin.gov/en/preview/location/UGFnZVJldmlzaW9uTm9kZToyNzUy
Joplin: https://joplin.herokuapp.com/admin/pages/330/edit/#tab-content
![image](https://user-images.githubusercontent.com/5839508/72278716-3aa1cd80-35fa-11ea-8344-cdd5c7a722b4.png)

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to Joplin
2. Make a location page
3. Add a related service with hours and hours exception
4. Publish or preview page

## Current behavior
This hours exception doesn't appear

## Expected behavior
will need @chasechenevert to supply a mock for how this appears

**Comment by chasechenevert** [comment]
Spec updated:
<img width="660" alt="Screen Shot 2020-01-15 at 3 28 10 PM" src="https://user-images.githubusercontent.com/7027270/72473183-c0b14600-37ab-11ea-9e09-77d8ae37bcb4.png">
 https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/

**Comment by desigonz** [comment]
Acceptance criteria logged in #3777. @chasechenevert can you size your effort on this and then close the issue, if 3777 looks good to you?
