### ISSUE TITLE
Limit to one contact per page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3745]
With the new location content type, we no longer need multiple contacts on one page—in fact, we want to limit contacts to one per page! Per @toribr: "Where we landed was no, we don’t want multiple contacts for one page. The logic is identical as we used for the guide - multiple contacts is confusing."

Janis side of things
- [x] On service pages, only one contact appears.
- [x] On information pages, only one contact appears.
- [x] On department pages, only one contact appears.

Joplin side of things
- [x] On service pages, authors can only add one contact.
- [x] On information pages, authors can only add one contact.
- [x] On department pages, authors can only add one contact.

**Comment by easherma** [comment]
@briaguya brought up this good point that this would actually allow us to simply some code on the backend.

**Comment by chiaberry** [comment]
Service Page
https://joplin-pr-3745-one-contact.herokuapp.com/admin/pages/94/edit/#tab-content

Information Page
https://joplin-pr-3745-one-contact.herokuapp.com/admin/pages/345/edit/#tab-content

**Comment by desigonz** [comment]
This looks really great, thank you! I would say QA passed but I have one question: did you run across pages with multiple contacts that we need to decide what to do about them? Will pushing this into prod break those pages?

**Comment by desigonz** [comment]
- @chiaberry will try hiding the button, and if it takes a long time, we'll spin that out into a new issue
- @desigonz work with content to make sure we only have one contact per page

**Comment by desigonz** [comment]
- [ ] Events have only one contact, we can follow that pattern
- [ ] Guides should be limited to one contact

**Comment by chiaberry** [comment]
@briaguya ^^^

**Comment by chiaberry** [comment]
@briaguya this is covered in v3, right? I can close this issue?
