### ISSUE TITLE
Renamed topic collection keeps old slug

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3746]
I renamed a topic collection per APH director Hayden. The topic collection is renamed, but the slug remains "healthcare and prevention". Can we get them to match?

[Health and prevention topic collection](https://alpha.austin.gov/en/health-safety/healthcare-prevention/)

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to ' https://alpha.austin.gov/en/health-safety/healthcare-prevention/ '
2. See that topic collection name and slug do not match

## Expected behavior
I expected the slug to update to match the name topic collection name

## Screenshots
![Screen Shot 2020-01-13 at 11.46.51 AM.png](https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/a0ad01c3-df7f-4a4d-93d0-ab953cc393ee)

## Additional context
Since the City of Austin doesn't *do* healthcare, it's important to APH that we not offer it or use the term on our website. Matching slug::titles are also supportive of the IA.

**Comment by desigonz** [comment]
Did you try changing the slug via the SEO tab?

**Comment by Jo-Dwyer** [comment]
@desigonz I hadn't but I now have change dit in SEO tab. When I navigate to the page, the slug is still "healthcare-prevention"

https://alpha.austin.gov/en/health-safety/healthcare-prevention/

but when I click "Live" on the editing page in Joplin, it directs me to "health-prevention" as in the SEO tab

https://alpha.austin.gov/en/health-safety/health-prevention/
