### ISSUE TITLE
Review UX for "Save and review" on OPO form

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3751]
We have enabled the "save and review" functionality for the OPO form, which is built into Formstack. We should review the experience within the context of embedding forms on alpha.austin.gov and test it in a few browsers, then determine if this is an acceptable option for users.

Test the form in:
- [ ] iOS v. 13 iPhone 8 Safari
- [ ] Windows 10 Chrome
- [ ] Android Galaxy 9
- [ ] Mac Mojave, Safari 12.1

Contact @desigonz if you need browserstack credentials

Link to test:
https://alpha.austin.gov/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyNzc1

**Comment by toribr** [comment]
Perusing the [formstack support files](https://help.formstack.com/hc/en-us/articles/360019204632-Allowing-Users-to-Save-Resume-Forms) indicate that this screen should display after clicking the link. I can see it flash (i think) briefly 
![Screen Shot 2020-01-13 at 1 38 04 PM](https://user-images.githubusercontent.com/3790067/72372181-82445a00-36cb-11ea-807c-74379f612d7b.png)
