### ISSUE TITLE
Upgrade postgres in heroku

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3756]
We should upgrade to something beyond the free tier. This would allow more connections, and allow the PG database to have its own cache, which should greatly help response time of multiple requests.

**Comment by easherma** [comment]
This is currently done on staging. 

I followed these instructions:
https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases#upgrading-with-pg-copy

It is working. We are getting a weird error in the logs, though: 
```
2020-01-15T20:17:47+00:00 app[postgres.9907]: [AMBER] [8-1]  sql_error_code = 28000 FATAL:  no pg_hba.conf entry for host "188.178.64.218", user "postgres", database "postgres", SSL off
2020-01-15T20:17:48+00:00 app[postgres.9908]: [AMBER] [8-1]  sql_error_code = 28000 FATAL:  no pg_hba.conf entry for host "188.178.64.218", user "postgres", database "postgres", SSL off
```
Not sure who this host is who is trying to connect this way, this is best info I could find from Heroku:
https://help.heroku.com/DR0TTWWD/seeing-fatal-no-pg_hba-conf-entry-errors-in-postgres

Not sure whether we'd consider this blocking also upgrading prod. 

Testing is not _super_ conclusive but it appears that the following is true:
* staging, using syncronus workers on guinicorn, has roughly the same build time as before with a bigger database
* subsequent builds appear to be faster, implying that the postgres cache is being used
* however, it seems that after a certain period of time this speed gain is lost and it goes back to the old response time, but heroku reports hitting the postgres cache just the same
that could have something to do with connection pooling with the django app or something with graphene-django

Either way, overall the overall affect on performance isn't super huge (response seems to take about a second if cached, about 2-3 seconds if not), so it's not like this is a magic bullet.

**Comment by easherma** [comment]
It appears that host/log is not longer showing up...so...maybe the problem solved itself? 
* grimace emoji *

**Comment by easherma** [comment]
Also, we might want to make sure deploys to staging or prod don't de-upgrade our database, though at the moment I think that would only happen if you explicitly dropped the database on heroku.

**Comment by desigonz** [comment]
- Writing something that makes it not a hobby tier
- Write up read me on "here's how to copy prod data to staging"

@Niicck's going to take a look and offer feedback and next steps.
