### ISSUE TITLE
Fee table: align entries to top

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#3757]
## QA
PR: https://github.com/cityofaustin/janis/pull/703
### Places this css hits
* Tables in info pages: https://janis-3757-table-text-alignment.netlify.com/en/permits-tickets/business-permits-and-licenses/food-business-permits/mobile-food-vendor-permit-types-and-fees/
* Tables in guides: https://janis-3757-table-text-alignment.netlify.com/en/permits-tickets/business-permits-and-licenses/food-business-permits/mobile-food-vendor-permit-guide/#Learn-and-prepare-2
* Tables on location pages https://janis-3757-table-text-alignment.netlify.com/en/location/office-of-police-oversight/ (need to go to ~200px wide to see it)
* Possibly hours in contact information on department pages (@desigonz @chasechenevert  do we have an issue to go from "don't show hours" to [what we have in abstract](https://share.goabstract.com/b9193fc6-3a4e-46b8-8ed8-dc2b644ce72d?commentId=239f463b-8b63-4f53-8d43-705fea465d53&sha=4583c07a61f14ecacaa8f5b867acc46b0df26aa1))

## Issue
Let's make the text in fee tables align to top

![Screen Shot 2020-01-14 at 1.51.54 PM.png](https://images.zenhubusercontent.com/5b7b6eae2bc79a5e7d4f874c/559cc6a3-f5a9-448e-8782-afee4c30e08c)

**Comment by briaguya** [comment]
should just need to add `vertical-align: top;` to our tds in our rich text areas

**Comment by desigonz** [comment]
Looks great to me, but will let @chasechenevert do the final pass.

And for some reason I don't have abstract access right now, so for this question, I defer to @chasechenevert!
> (@desigonz @chasechenevert do we have an issue to go from "don't show hours" to what we have in abstract)

**Comment by chasechenevert** [comment]
@briaguya This looks great! 

Re: contact card, I've got an issue https://github.com/cityofaustin/techstack/issues/4039 to review this and make sure we have parity between them.
