### ISSUE TITLE
Agenda for Content Pin-up 1/21/2020

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3758]
Last content pin-up #3693

🚦Approve agenda
-->Approve or add missing agenda items

📌 Action items from Design pin-up or Desi cc/ @toribr @chasechenevert @desigonz
#3761 City of Austin Holidays list - what's MVP?

💼 It's business time - larger discussions

💻 Content sprint goals
Checking in on...anyone need help?
Sprint 48

🏁 Roadmap

👩‍🏭 Workshop
Service page requirements
#3274 rules of the court: official document page
Department and location names in Spanish (carried over from last week)

🤓Review assignments

🌵ETC

🏃Next Steps

**Comment by desigonz** [comment]
Re: #3761 City of Austin Holidays list—I'm going to keep this in the short-term backlog right now, and might bring it in in the next few sprints if it makes sense re: priorities. Not sure if we need to discuss anything today?
