### ISSUE TITLE
City of Austin Holidays list

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3761]
This will be needed in lots of places that are closed on City of Austin Holidays

**Describe the content debt.**
City of Austin offices and buildings are often closed on holidays. As an author creating hours exceptions I want a simple way to refer residents to dates of holiday closures. For now, an information page may be the simplest way to achieve this. 

**What is the long-term, ideal solution for this content debt?** 
Ideally, editing hours for a service or location would include a button to choose whether to apply holidays and Janis would automatically display those days as "holiday - closed".

**Is this related to a feature request issue? (Add the issue number below and add the issue as a dependency.)**

**What approvals will be needed to publish this content change?**

CPIO/HR? The list is currently kept by HR http://www.austintexas.gov/department/official-city-holidays

**Comment by gabrielaperezdelaosa** [comment]
https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZTo2MTQ=

**Comment by Jo-Dwyer** [comment]
Copy looks good. What dept should offer it?

**Comment by gabrielaperezdelaosa** [comment]
top level page?

**Comment by gabrielaperezdelaosa** [comment]
@ablangworthy27 bad news: this page disappeared from Joplin and needs to be recreated
good news: we now have the ability to link it in the location pages (woohoo!)

**Comment by ablangworthy27** [comment]
I remade the page. @Jo-Dwyer has this been approved to publish by HR?

**Comment by gabrielaperezdelaosa** [comment]
the same page exists on austintexas.gov
https://www.austintexas.gov/department/official-city-holidays

I want to say if that can be published this can be published

**Comment by ablangworthy27** [comment]
This is published, and I have updated the location page links.
