### ISSUE TITLE
Async wokers on gunicorn

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3765]
- this would allow those requests to be concurrent on joplin, but
- during site builds, joplin seems to spend more time with requests waiting in a queue than anything else. this is probably because the site build process files off a bunch of requests at once, and gunicorn is handling them appropriately for how we have it set up but not really appropriate for the kind of app we've actually built. The short answer is that is what the above PG Bouncer is for
- switching to this kind of setup was pretty easy (I have a PR out: cityofaustin/joplin#526), but a naive implementation leads to lots of DB connections being created for every request

**Comment by easherma** [comment]
https://medium.com/@genchilu/brief-introduction-about-the-types-of-worker-in-gunicorn-and-respective-suitable-scenario-67b0c0e7bd62

**Comment by easherma** [comment]
Can be tested at: https://joplin-pr-async-and-pool.herokuapp.com/admin/login/

**Comment by desigonz** [comment]
I'm guessing @briaguya's doing the testing here? Need anything from me or others on the team to move forward on this?

**Comment by easherma** [comment]
I fully tested this in January, Brian has now also tested it using the same method, I don't think there's really anything else to do but merge it to staging and test it there at this point.

This is kind of a separate issue, but what might help is fleshing out general acceptance criteria for measuring build performance, what indicators we are looking for and want to test, and how to note and document those tests so we can measure improvement or regression. The process is very ad-hoc right now which I think causes confusion and miscommunication.

**Comment by easherma** [comment]
I fully tested this in January, Brian has now also tested it using the same method, I don't think there's really anything else to do but merge it to staging and test it there at this point.

This is kind of a separate issue, but what might help is fleshing out general acceptance criteria for measuring build performance, what indicators we are looking for and want to test, and how to note and document those tests so we can measure improvement or regression. The process is very ad-hoc right now which I think causes confusion and miscommunication.

**Comment by desigonz** [comment]
Okay, I've assigned Nick to determine what acceptance criteria/done means here. Happy to work through this with you, but I think you have a better grasp on this than I do.
