### ISSUE TITLE
QA the OPO commission application form & related pages

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3766]
We are launching a new form for the Office of Police Oversight! Let's QA with a fine-toothed comb to make sure it's ready to go.

### Test link
https://alpha.austin.gov/en/police-oversight/serve-on-the-community-police-review-commission/ (and the form that links from the "start" button

### Browsers/devices
- [x] First, @srigdon's device and browser: Macbook Air, Firefox 72.0.1 (64-bit). Then we'll move onto a cross-browser check. 
  - [x] Accuracy
  - [x] Spelling and grammar
  - [x] Any UX/UI things that aren't working as expected
- [x] iOS v. 12 iPhone 8 Safari
  - [x] Any UX/UI things that aren't working as expected
- [x] Windows 10 Chrome
  - [x] Any UX/UI things that aren't working as expected
- [x] Android Galaxy 9
  - [x] Any UX/UI things that aren't working as expected
- [ ] Mac Mojave, Safari 12.1
  - [ ] Any UX/UI things that aren't working as expected

Contact @desigonz if you need browserstack credentials

### For each test, make sure to review the following sections:
- [x] The info/service page
  - [x] About the commission
  - [x] Commission responsibilities
  - [x] Commission's expectations
  - [x] Qualifications/eligibility
  - [x] Steps for applying
  - [x] Link to the form
- [x] Form
  - [x] First page (Disqualifiers)
    - [x] Test conditional logic for boards and commissions. There's a lot of conditional logic—make sure it all works!
    - [x] Boards and commissions follow up question
  - [x] Second page (Applicant information)
    - [x] Test conditional logic, especially around relationship to police officers
  - [x] Third page (Demographic questions)
  - [x] Fourth and fifth pages (More information—essay questions. They span two pages.)
     - [x] Test conditional logic—only on fourth page, I believe
     - [x] Feels like some of the questions are missing. ~~@ablangworthy27, can you review the published form and check before @srigdon dives into QA on this particular page?~~ looks fixed!
  - [x] Submission page ("Your application was submitted successfully.") 
- [x] Confirmation email sent to applicants
- [x] Email sent to application reviewers

**Comment by desigonz** [comment]
@srigdon I've added the test link and a list of browsers to test in the issue description. Use the [bug report template](https://github.com/cityofaustin/techstack/issues/new?template=bug_report.md) to report each bug. Let me know if you want to walk through this together on Tuesday before starting!

**Comment by desigonz** [comment]
Added a note for something for @ablangworthy27 to verify above

**Comment by desigonz** [comment]
@ablangworthy27 fixed it! Thank you!

**Comment by srigdon** [comment]
QA-ed all the things in Firefox and got started on a content review, #3759. [See log here](https://docs.google.com/document/d/1SMCJb-3LGOQCLVJDHUoNKBGx0fG_8BgfqWgYufLoE9I/edit). I wish Google docs had a Markdown feature :/

**Comment by srigdon** [comment]
Bugs: 
- #3893
