### ISSUE TITLE
Design retro #1

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#3769]
# Let's use this time to go deeper on workflow, tools, processes, wants, and needs specific to Design. 

BRAIN DUMP though far more than we can discuss in one retro, but feel free to contribute! We can break this up across retros, too.  

**Alpha-related**
- [x] Regular design retro? **Yes**
- [x] Workflow: questions around comments, archival and documentation of those comments, and "source of truth" **#1**
- [ ] Things are getting more complex, and there's always desire for faster velocity, so how do we make sure that things don't fall off our radar when we're revising previous designs (components) that have dependences? Should we Q/A design specs before they get to developers to make sure we've got everything? 
- [ ] https://github.com/cityofaustin/techstack/issues/3849 What's the journey from idea to implementation of a new content type? We had a few interviews with Nameir, but we haven't really carried those conversations forward. We've naturally iterated on this across time, so what's working and what could we improve on as we start to look across the 2020 roadmap? What takes a lot of time, what saves us time? Can we make this process repeatable? Can we satisfy broader thinking before drilling down into MVP (I think the Thinking Hats method could be really useful at the start of intake for a new content type to help us dream big while uncovering places where we need to be careful, i.e. worst case scenarios). 
- [ ] Health check on documentation: XD specs, and docs about what components and content types we have and how things are supposed to work (thinking about a future QA person and what they'll need). 
- [ ] How might we engage with user research regularly, what do we need? Thinking about Anu's new role, SDL's user research function and how we can work together. Similarly, how might we interface with residents of Austin regularly to learn about how they go through their day-to-day as residents of Austin, and how our work can impact their quality of life?
- [ ] Persona development, macro-micro level. What do we need from personas, and how might they help us make decisions, identify problems and opportunities? We've identified "conditions and identities", how might we put these into play during pin-ups, and decision-making?
- [ ] XD documentation: components, states, colors, typesetting. This could be a good time to discuss tools like ZeroHeight, Gitbooks, Google Docs, etc. How might we address the workload of maintaining documentation (once or twice a sprint?), and get Team Content's help with writing?

**Beyond the Alpha project**
- [ ] Personal and professional goals
- [ ] How we might be inclusive of others who want to contribute to the design function in ODD? Are there tasks that we could outline that would contribute to the project Alpha, or design as a discipline within ODD, and be beneficial to colleagues who want to learn and contribute in this area? Thinking about [Designer Fund's Level Up](https://df1.designerfund.com/levelup/) maturity model and how we might put that into play? Concern about how to make space for this considering resource management and demands on all of our time.
- [ ] Sharing our work: case studies and profiles of our work that everyone can take with them and use for their portfolios
- [ ] If we were able to get interns, what could they help us with?
- [x] How can we engage creatively beyond Alpha? Expand on our lunch hour idea!
- [ ] Are there companies in Austin, or gov-design teams who would be willing to open their tools and processes to help us understand their day-to-day processes and how they've solved similar challenges?
- [ ] Are there people we could tap to come in and present to us, or otherwise give us feedback? Would we be expected to compensate their time?

**References**
- [Service patterns for local government](https://patterns.wearefuturegov.com/) 
- [Better design documentation](https://medium.muz.li/design-docs-6bb34589f7a9) medium article
- [Adobe XD cloud API integrations](https://medium.com/adobetech/adobe-xd-cloud-content-apis-are-here-ca12cf91e2fe)
- [Behavioral archetypes instead of personas](https://medium.com/common-good/behavioural-archetypes-instead-of-personas-c7ccc5b8b998) medium article
- [Organizing brainstorming workshops: a guide for designers](https://www.smashingmagazine.com/2019/03/conducting-brainstorming-workshops/)
- [Atlassian team playbook](https://www.atlassian.com/team-playbook)
- [Significa handbook](https://significa.co/handbook/) design firm's working methodology, guidelines, and useful resources. 
- [Designer Fund's Level Up maturity model](https://df1.designerfund.com/levelup/)
- [Designer Fund's resources](https://www.designerfund.com/resources)
- https://medium.com/indeed-design/creative-activities-to-help-your-design-team-thrive-d1a055cabdf5

**Comment by toribr** [comment]
I'm beginning to think to cover all this, we'll need a retro (what's working and what's not) *and* another ongoing meeting to tackle strategy and implementation issue by issue. I'm not sure any of these issues can be discussed and a process created in an hour's time.

**Comment by chasechenevert** [comment]
Sounds good!

**Comment by toribr** [comment]
Sadly, the other article I had bookmarked is behind the paywall at Medium 
https://spotify.design/articles/2019-12-16/reimagining-design-systems-at-spotify/

**Comment by chasechenevert** [comment]
What we accomplished for our first retro! A good mix of looking back and ideas to improve as we  move forward. We're going to keep this issue live since we have a lot to cover, and track the progress over time. 

![IMG_20200127_133412](https://user-images.githubusercontent.com/7027270/73209545-0d7f1000-410e-11ea-812c-7a4d80a21728.jpg)

**Comment by toribr** [comment]
Follow up, which took place at the following Pin-up:
![IMG_20200128_114052](https://user-images.githubusercontent.com/3790067/73389376-a726f880-4299-11ea-94d9-356cfc8520a2.jpg)
