### ISSUE TITLE
Build failure while creating location and service pages

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#3770]
## When did this happen?
*Rough estimate if fine, but the more precise, the better*
The Janis Builds channel says that the builds went through successfully at  20:18:04 and 20:18:08 today (1/15) 

## Where did this happen?
- [x] Production
- [ ] Staging
- [ ] On a branch: *list the branch here*

## What were you trying to do when this happened?
*Explain the situation!*
I am trying to build both a location page and service page. I am publishing both drafts because I can't connect the two without them being live. I did publish without a topic or dept, so that they won't generate a url while still editing. 

## Screenshots
*Include a screenshot of the error you got when this happened.*

Preview works fine but when I try to view the live version of the service page, this is what I get:
![Screen Shot 2020-01-15 at 2.27.26 PM.png](https://images.zenhubusercontent.com/5d6e8f01caef900001337734/54e13d8e-800f-432b-a244-7e11b9604685)

Preview works fine but when I try to view the live version of the location page, this is what I get:
![Screen Shot 2020-01-15 at 2.30.26 PM.png](https://images.zenhubusercontent.com/5d6e8f01caef900001337734/44a58122-4e21-46e9-bae0-436582a94fbc)

**Comment by desigonz** [comment]
This is right—you won't be able to see the live page, you'll just get a 404. However, you'll be able to add the page to a guide and the content will show up in the guide.

This isn't great long term, we'll want a better authoring experience for all of this.
