### ISSUE TITLE
Save and resume modal

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3771]
## Links
PR: https://github.com/cityofaustin/formstack-alpha-theme/pull/3
Testing link: https://janis.austintexas.io/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyODg3

## Describe the bug
When you use the "save and resume" functionality on a Formstack form that's been embedded into Janis, the modal appears at the top of the iframe. Most users wouldn't know to scroll to find it.

![save-resume-modal](https://user-images.githubusercontent.com/5839508/72472170-b0986700-37a9-11ea-8030-3cb3d4085965.gif)

## URL
https://alpha.austin.gov/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyNzc1

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Fill the form out a bit
2. Scroll down and click "Save and resume"
3.  See error

## Current behavior
Modal is at the top of the iframe, but not in view for the user

## Expected behavior
Modal appears where the viewer is currently scrolled to. Compare to how it works in a non-embedded form: https://cityofaustin.formstack.com/forms/cprc_application

**Comment by briaguya** [comment]
@desigonz https://janis.austintexas.io/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyODg3

this is accomplished by adding
```
    <style type="text/css">
.fs-ngdialog-content { position: absolute !important; left: 0; right: 0; bottom: 100px;}    </style>
```

to our header html in our formstack theme, I'll need to figure out what exactly updating formstack looks like and if there's a better place to put the styles with sass and stuff

**Comment by chiaberry** [comment]
I updated the formstack alpha theme to incorporate your changes @briaguya
