### ISSUE TITLE
Event content Type - Research

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#3772]
**Event content type research basing on the following questions**

1.How often city events taking place at non-city Venues?(Not-needed any more)
2.How often do events take place in multiple locations simultaneously?
3.What % of events charge fee and what are different types of Fee structure and Fee Buckets?
4.Type of Events
5.Events Sponsored by city of Austin

Here is the link for the Research
https://docs.google.com/spreadsheets/d/1TcKkfMZRVjATZYT6hIBM27FvWLR-wsNLf5pIHAIax8w/edit?usp=sharing

**Comment by desigonz** [comment]
I think this is complete—designs for events have been sent to dev. Thanks for your work on this @anukandimalla !
