### ISSUE TITLE
Save and resume confirmation page is missing

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3775]
## Describe the bug
When you use the "save and resume" functionality on a Formstack form such as the [OPO application](https://cityofaustin.formstack.com/forms/cprc_application), the confirmation page is missing for the form that has the alpha.austin.gov theme applied. (But it worked on one with the [default theme](https://cityofaustin.formstack.com/forms/dg_test).)

## URL
https://cityofaustin.formstack.com/forms/cprc_application

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Fill out the form a bit
2. Click on "Save and resume"
3. In the modal, click "save and get link"
4. Enter your email address and click "Send save and resume link"
5. See error

## Current behavior
A blank page

## Expected behavior
This confirmation page: 
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/e3adcef0-0b6b-4c22-b482-9cb9ceb45602)

**Comment by chiaberry** [comment]
@Niicck can this be solved by turning on a confirmation page plugin, or adjusting the current confirmation page plugin? if so, 3?

**Comment by robbobfrh84** [comment]
I can see that https://cityofaustin.formstack.com/forms/dg_test behaves as expected. However, i can't seem to locate this example on the formstack.com side of things?

**Comment by robbobfrh84** [comment]
Ready for QA @desigonz 

PR: 
https://github.com/cityofaustin/formstack-alpha-theme/pull/6

## To Test

Visit test url: https://cityofaustin.formstack.com/forms/bob_s_simple_form

- Click [save and resume later]
- enter email ignore@igore.com
- did you see a confirmation message - small as it may be?

NOTE: this definitely needs to be styles ;) -> font is super small.

**Comment by desigonz** [comment]
It emerges!!!! Looks great, QA passed. 

P.S. @chasechenevert is working on style in #3686 so we'll have that soon too :)
