### ISSUE TITLE
Permissions: restricting what you can edit/view by department

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3780]
### As an editor within a particular department, I want to only see content that is relevant to me, so that I can more easily access my content.

NEED FOR MOVE TO V3:
- [x] Editors and moderators must belong to at least one department
  - [x] **Design team** will need to create designs for how an administrator assigns a user to a department when [adding a new user](https://joplin.herokuapp.com/admin/users/)—maybe on the roles page?
    - department pages ≠ permissions for departments—separate those in the data model
    - *What is the admin flow for creating a new department within this permissions structure?*

CAN WAIT
- [ ] On the main content search page, editors and moderators only see pages that belong to their assigned department 
- [ ] When using a guide page picker, editors and moderators have the ability to search and select all pages, regardless of assigned department
- [ ] When using an internal link page picker, editors and moderators have the ability to search and select all pages, regardless of assigned department

Assumptions:
 - Each user will have a profile, which includes the department they work in, their name,
and their email **Need design mocks for what this looks like**

**Comment by briaguya** [comment]
Assuming https://app.zenhub.com/workspace/o/cityofaustin/techstack/issues/3784 and https://github.com/cityofaustin/techstack/issues/3813 are complete, this should be a quick one.

**Comment by chiaberry** [comment]
Duplicated in other issues? #4097, #4203
