### ISSUE TITLE
Assigning users to a department

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3784]
### As a Joplin administrator, I want to be able to create a new Joplin user and assign them to a department, so that departmental permissions can be a thing.

We have outlined MVP requirements for departmental permissions in #3780. Now we need to design the user flow for how an admin assigns a new user to a department when [adding a new user](https://joplin.herokuapp.com/admin/users/)—maybe on the roles page?

**Comment by toribr** [comment]
@desigonz @easherma Isn't there some affordance already in wagtail for this? I'm not sure if it's turned off, or I don't have permissions to see it.

**Comment by desigonz** [comment]
Additionally:
- [ ] How does a (super)admin add a new department, or edit the name of an existing one?

**Comment by toribr** [comment]
This issue is twofold as discussed during the last dev/design sync.

Super admin which can create/edit users and assign department to that user, as well as creating a new department or editing an existing department name.

Moderator who can add new user to existing department, as well as making current department users "inactive."

**Comment by desigonz** [comment]
That sounds right.

**Comment by toribr** [comment]
Update: Modeling after Drupal means that only admins can add users. Therefore, an affordance for adding department to users is needed, as well as editing/adding new departments.

**Comment by toribr** [comment]
https://xd.adobe.com/view/1b86b869-7cf8-4623-6479-16bc0a8e09e7-6db7/

**Comment by desigonz** [comment]
Acceptance criteria logged in #3919 and #3920
