### ISSUE TITLE
Janis Page Instances in Joplin - create/update/delete on publish

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3786]
### Issue now
When publishing a page in Joplin, we should:
* Create/update page instances for each appropriate instance (url/contextual nav data)
* Delete any page instances that no longer apply (changing a topic etc)

The logic for updating this will be page type specific, and based on different fields per page type

example:
* Department
  * If we change the slug, we need to update
    * all of the page instances that use that slug in the url
    * all of the urls on page instances that link to us
  * If we change the the Title, we need to update
    * all of the titles on page instances that use the title in links

this will need to be much more fleshed out, a lot of the work from https://github.com/cityofaustin/techstack/issues/3692 should be helpful here

### Issue Before
Instead of naively deleting all janis urls when saving a page, make sure we:
* Only update Janis URLs when an IA change is made
* Update all child page URLs when updating slugs of a parent (topic/department/topic collection)
  * This will be needed when we start adding localized slugs.
* Create a manual migration to give existing pages URLs

**Comment by desigonz** [comment]
Hey @briaguya—@Niicck said your current Joplin refactor will lead to a fix for this. Ok to close this one?
