### ISSUE TITLE
Janis/Joplin - Update API/queries to support Instances

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3788]
### As a [Janis] I want [to know all Janis URLs for a page, along with relevant extra information such as parent/grandparent] so that [I can reduce redundancy in URL generation and support localized slugs].

**Is your feature request related to a problem? Please describe.**
https://github.com/cityofaustin/techstack/issues/3787
https://github.com/cityofaustin/janis/pull/675
https://github.com/cityofaustin/techstack/issues/3388

**Describe the solution you'd like**
When querying the Joplin API, I'd like to be able to get all URLs for a given page, along with relevant information.
For example, I'd like to get all URLs for a service page, as well as any information about parent topics, parent departments etc.
```
{url: /language/theme_slug/topic_collection_slug/topic_slug/page_slug, 
       parent: topic_page,
       grandparent: topic_collection,
       great_grandparent: theme,
       language: language}
```
This way I will have the ability to:
* generate a link to the page at the correct url using filtering instead of url construction
* use information from Joplin only to create pages with localized urls

**Additional context**

When making Topic Collection pages, we use this query:
```
  query getTopicCollectionPage($id: ID) {
    allTopicCollections(id: $id) {
      edges {
        node {
          id
          slug
          title
          description
          theme {
            id
            text
            slug
          }
        }
      }
    }
    allTopicPageTopicCollections(topiccollection: $id) {
      edges {
        node {
          page {
            id
            live
            slug
            title
            description
            topPages {
              edges {
                node {
                  title
                  slug
                  pageType
                }
              }
            }
          }
        }
      }
    }
  }
```

I would like to see it become:

```
query getTopicCollectionPage($id: ID) {
    getTopicCollection(id: $id) {
      id
      url  // Localized, since it's TopicCollection there's only one
      title
      description
      topicCardTopics {
        title
        description
        url  // Localized, using the correct url under this topic collection if we have topic under multiple
        topPages {
          title
          description
          url // Localized, using the current url under this topic and tc not under a dept or something
        }
      }
    }
  }
```

**Comment by chiaberry** [comment]
I believe this was solved by v3
