### ISSUE TITLE
Shorten/Combine Funshop presentations for Directors/Managers

### ISSUE THREAD

**Issue by ashleecoa** [cityofaustin/techstack#379]

**Comment by ashleecoa** [comment]
https://docs.google.com/presentation/d/1TJ_Tj4gHgBvDkkv-PFQdlHXB3EDBbzdJomohv7XVWN0/edit

**Comment by LauraTrujillo** [comment]
Per our conversation yesterday, @ashleecoa, I "skipped" the hyperlink section. That's not as important (for executives to see) as the other slides.
