### ISSUE TITLE
Formstack forms don't render on alpha in chrome with Privacy Badger installed using default settings

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#3792]
## Describe the bug
Using chrome with privacy badger installed causes the form to not render in alpha

![image](https://user-images.githubusercontent.com/6384156/72944288-15216c00-3d3e-11ea-8717-568b523e9ee4.png)

## URL
https://alpha.austin.gov/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyNzc1

## To Reproduce
1. Use chrome with privacy badger and above settings.
2. Click that link.

## Current behavior
![Screen Shot 2020-01-18 at 9.36.23 AM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/1aca1930-efa1-44a3-88ad-a2fd3b64aa38)

With errors.

## Expected behavior
If the form fails to load, information is shown to help the user determine what to do.?
@Niicck suggested:
* If the form hasn’t displayed: click here to go to the direct link
* Also disable any extensions that block external content, etc etc
probably a question for content if we move forward on this one.

## Device and browser
Only on Chrome (works on Firefox and Safari) on Nick's Macbook.

## Additional context
In addition to fixing this issue outright, it would be good to offer a fallback.
"You can also fill out this form directly at this address: [Formstack URL]."
That way the page isn't totally broken for someone in the future. We also don't have the feedback button for form pages, so they wouldn't be able to report it.

**Comment by desigonz** [comment]
- [ ] If we fall to load the form, error handling appears. **content team to give us words for the error; This form failed to load. Try disabling ad blockers or privacy things etc etc.**
- [ ] Add a link to the direct form **content words here too**

**Comment by robbobfrh84** [comment]
@Desi, Here's the updated PR with deployed links demonstrating the issue for content and design ( @tory @chasechenevert ) to take a look at ... 

PR: https://github.com/cityofaustin/janis/pull/680

Deployed: https://janis-3792-badger-block.netlify.com/ 
- Direct link to issue: https://janis-3792-badger-block.netlify.com/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyNzc1

When going to the displayed link you may see one of two outcomes ... 

1) The form loads fine (image#1)
2) The form does not load, and a "placeholder" message appears. (image#2)

🚨Note: 
  - The screen shots below so the state of the privacy badger, which blocks the form from loading. And, shows the url. 
  - Here's the link to the privacy badger plugin (if you don't already have it): 
    - https://www.eff.org/privacybadger

### Image#1
![not blocked.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/bec067b0-6a7a-4256-8543-4925058c86cf)

### Image#2
![blocked.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/4984e3d5-8f61-4f60-be22-36b24efd7248)

**Comment by robbobfrh84** [comment]
Also, If you don't have privacy badger installed already, i noticed i had to reboot chrome for it to work properly. So, if you're not getting the page blocked, it maybe because of that.

**Comment by desigonz** [comment]
Thanks @robbobfrh84! Awesome work, I got really excited when the message appeared . Next steps is for a content strategist to tighten the language and for @chasechenevert to mock up a design. I'll make issues for those and inform the various parties :)

The form is due to launch on Monday—I'd love us to push out something by then (so that when CPIO sends out the press release, it's in place), even if it's not perfectly matching mocks, and then we can improve later. Let's check in tomorrow about it!

**Comment by robbobfrh84** [comment]
Sounds Great! I'll make myself available whenever you're free.

**Comment by desigonz** [comment]
@robbobfrh84 

# Copy
### We are still waiting for your form to load ###

[Open the form in a new window](https://cityofaustin.formstack.com/forms/cprc_application)

#### Why hasn't it loaded yet? ####

- A plugin could be blocking the form (for example a privacy app like Privacy Badger)
- It may have failed to load ("404 error")

# Design
https://xd.adobe.com/view/8b74c769-0d5e-45fd-567a-d07de46198dc-fd45/?fullscreen

# Acceptance criteria
- [ ] style follows mocks above
- [ ] Copy matches content above
- [ ] Form link opens in new tab/window

**Comment by robbobfrh84** [comment]
@desigonz Ready for QA!

github: 
- https://github.com/cityofaustin/janis/pull/680

Deployed: 
- https://janis-3792-badger-block.netlify.com/

Direct link to issue: 
- https://janis-3792-badger-block.netlify.com/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyNzc1

**Comment by desigonz** [comment]
QA passed! Let's push this into production!

**Comment by desigonz** [comment]
Can we get this into production? Let me know if there are any blockers to that!
