### ISSUE TITLE
Required/optional best practice for forms

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3794]
Let's determine a best practice, share with content, and then make resulting issues for anything dev would need to implement.

**Comment by toribr** [comment]
This article is recent, and I think the best way for us to go, ie, add (*required) or (optional) to ALL fields.
https://www.nngroup.com/articles/required-fields/

This means we need to change our style sheet to support the additional string of (Optional) after the Field Label within Formstack.
