### ISSUE TITLE
Joplin UI designs for type and color

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3795]
We've scoped down the Joplin UI stuff and will be starting with type (font-face, line-spacing, margins/paddings, states, etc) and color (buttons, type color).

**Comment by chasechenevert** [comment]
@toribr Let's block off maybe 2 hours for this sometime next week, maybe Monday after the open house at the new office?

**Comment by chasechenevert** [comment]
On our second pass, @toribr and I took a thorough look through Joplin and listed out all type and color changes that we want to put into the first phase of enhancements: 
Google Doc: [Joplin UI / Phase 1](https://docs.google.com/document/d/1SdAro51Ppdi3Hirn1XkVviJ6nu89dDXtvvFKIX4T8t8/edit#heading=h.uvw6ggmsdkmc)

Next steps, before Thursday
- [ ] Make decisions for items highlighted in yellow
- [ ] Mock-up these changes (including interactive states) to ensure we've covered everything we're proposing, and to give Bob a spec to work from
- [ ] Create new issue to scope Phase 2 changes, and add the items highlighted in purple to that list

**Comment by desigonz** [comment]
Awesome work team! 🙌Is this ready to review at dev-design sync today?

**Comment by toribr** [comment]
@desigonz We don't have everything worked out, but there's certainly enough to get started.

**Comment by toribr** [comment]
User story: As a city author, I need the authoring experience to have a logical visual hierarchy so that I am better able to understand the interface. @desigonz

**Comment by chasechenevert** [comment]
@toribr @desigonz I'd add to that something about making color and type meet accessibility standards, because during our review we found a lot of instances where type was below 14-16px, and color contrasts that are below AA-AAA ratios.

**Comment by desigonz** [comment]
Thanks team! Sorry, didn't see these notification yesterday

**Comment by chasechenevert** [comment]
@desigonz here's the spec: https://xd.adobe.com/view/c533a077-9314-46a6-5db4-d4a7f8601e8f-b302/
