### ISSUE TITLE
Research and plan for Certificates Expire for COA Feb 19, 2020

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#3800]
Sergio has been getting these emails and he writes
Hello #odd-flock devs, I’ve been getting these emails. Just making sure you are aware :slightly_smiling_face: the certs may need to be re-keyed, or if they generate automatically the new certs will have to be re-installed on AWS. 

![2020-01-21_09-24-33.png](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/0088f1e5-ac08-477b-ae36-4ea15ec01f29)![2020-01-21_09-23-24.png](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/3b64a7a3-0cd2-455f-91ea-6f16a6100226)

We need to investigate this and figure out steps forward

**Comment by briaguya** [comment]
First we'll need to get a new certificate, @wilhitem has been in contact with the DNS team and we should know more on that front.

After that, we'll need to log in to AWS and go to "Certificate Manager," the current certificates for forms.austin.gov and alpha.austin.gov are in there. We can just hit the reimport button for it after that.

**Comment by desigonz** [comment]
Jason's got the info, we will check in with them the week before it expires.
