### ISSUE TITLE
Write and publish Spanish-language content strategist job description

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3802]
- [x] Look at the description in the past and update with what's missing. 
- [ ] Coordinate with @oliver2g to publish

**Comment by desigonz** [comment]
@Jo-Dwyer will take the lead on this

**Comment by desigonz** [comment]
Exciting content strategist job description: https://github.com/cityofaustin/odd/blob/master/_jobs/positions/__content-strategist.md

**Comment by ablangworthy27** [comment]
### Some notes on the existing text
_- Serve on multidisciplinary teams to concept, prototype, and implement content solutions for city services_
Maybe workshop would be a better word than prototype?

_- Pursue continuing engagement with internal and external users, and participate in planning thoughtful and ethical user research_
The first half of this sentence is pretty vague and I think just having "Participate in planning thoughtful and ethical user reserach" would do fine. But honestly this particular duty hasn't really come up for me. Thoughts @srigdon @Jo-Dwyer ?

### The required content audit and in-person exercise
I didn't get the sense that this was used much during my interview process. No one ever asked me about it. If we are going to ask for homework or an example of competency, I think we should choose something else. And maybe that is a Spanish test of some sort?

For the outline of the job hiring experience, an "exercise" is mentioned. I never did one of those. If we decide not to do an in-person exercise, then lets remove that from here.

**Comment by srigdon** [comment]
Great edits, @ablangworthy27, agreed. I made edits and comments here: https://github.com/cityofaustin/odd/pull/21/files
