### ISSUE TITLE
Relationship manager role meeting

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3804]
**Objective** 
Identify coordinator needs so we can begin prototyping what the role will look like.

**Participants**
Sam Modabber
@stephaniegates 
@Jo-Dwyer 
@ablangworthy27 
@srigdon 
@desigonz 

**Agenda**

------
- [x] Schedule meeting
- [x] Meet
- [x] Create resulting issues

**Comment by srigdon** [comment]
Follow up tasks: 
I'll write out and send to Sam the communication flow for official documents and talk to Mia about the change in process.
