### ISSUE TITLE
Joplin - Page Instances

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3805]
### STORY: As a Joplin API consumer (janis build), I want to be able to request a page at any given URL from Joplin and get back the correct data for the instance of that page at that URL (correct contextual nav data, correct URLs for pages linked in our topic cards etc.)

BENEFITS: Reduced complexity in the Janis build process when generating data for pages (easier debugging/easier to add new content types)

Over the course of working on https://github.com/cityofaustin/techstack/issues/3388, one of the main goals became understanding how to build any given page with the correct contextual information at any given url.

By creating a page instance model, we can manage those in joplin and make sure that we have all relevant information available when rebuilding a page at any given url.

TODO: fully flesh this out

![IMG_4422](https://user-images.githubusercontent.com/6384156/72839408-dc0ecc00-3c57-11ea-9405-b2f666c2efbe.jpg)

**Comment by desigonz** [comment]
Can you add a user story here?

**Comment by briaguya** [comment]
@desigonz updated the description

**Comment by desigonz** [comment]
Thanks @briaguya! Also maybe a size on this, if possible?

**Comment by briaguya** [comment]
@desigonz closing this, added a link to it in https://github.com/cityofaustin/techstack/issues/4088 so we can reference it as a braindump
