### ISSUE TITLE
Feedback component tweak 

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#3806]
# Solution
Spec: https://xd.adobe.com/view/a3f55254-1db8-437a-5421-6e1e1d175e35-d5c4/

- [ ]  Background gray: #F7F7F7 (matches other background grays we're using)
- [ ] Component background/container spans 100% width, but the input fields and everything else should all remain where they are, they shouldn't span 100%

## problem
I'm not happy with how the feedback component is appearing in context of other pages (notably the Location page). This isn't an issue with the implementation, just my designs. I think this can be smoothed out by simply making the full-width component stacked on top of the footer. 

- [x] Mock-up the feedback component as a full-width component stacked on top of the footer
- [x] Decide on one gray

<img width="1633" alt="Screen Shot 2020-01-21 at 2 16 10 PM" src="https://user-images.githubusercontent.com/7027270/72839952-dbc30080-3c58-11ea-8ad7-4ef9000d40f6.png">

**Comment by chasechenevert** [comment]
Spec: https://xd.adobe.com/view/a3f55254-1db8-437a-5421-6e1e1d175e35-d5c4/
- [ ] Background gray: `#F7F7F7` (matches other background grays we're using)
- [ ] Component background/container spans 100% width, but the input fields and everything else should all remain where they are, they shouldn't span 100%

**Comment by desigonz** [comment]
Logged this in #3959
