### ISSUE TITLE
Events review/scrubbing

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#3811]
Just making an issue to make sure the review is tracked and estimated to prevent it from falling through the cracks! 

Things to watch for (please add to this if you think of anything):
- [ ] Implementation matches mocks
  - [ ] Spacing
  - [ ] Type sizing
  - [ ] Colors
  - [ ] Feedback component present on detail page, repressed on list page
  - [ ] Responsive behavior/styling
- [ ] Screen reader behavior
- [ ] Labels
---
- [ ] Homepage component
- [ ] List page
- [x] Detail page
- [ ] Joplin

**Comment by chasechenevert** [comment]
@desigonz took a quick look through the browser inspect, and most of the padding values are wrong. The first page of the spec surfaces all of the padding values, so we may need a dev to go through and change the values to match the mocks.

https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/

**Comment by desigonz** [comment]
Thanks @chasechenevert! Made a new issue for this: #3917. I'm going to move this issue back to next sprint candidates so we can scrub listing and homepage view during sprint 50.
