### ISSUE TITLE
Create department groups in the data model

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3813]
In the data model, we're going to allow for an array of departments in case in the future we'll be allowing users to belong to multiple departments. But as outlined in #3920's acceptance criteria, on the Joplin UI we'll only allow admins to pick one department for now.

------
### Previously

If we want to filter pages by department , we need pages to have an associated department (not department page) from the permissions model. https://github.com/cityofaustin/techstack/issues/3780

**Comment by desigonz** [comment]
I'm adding this to the agenda for dev-design sync. Want to make sure the design and product teams understand the implications from a UX perspective.

**Comment by easherma** [comment]
Hmm, if this is needed shouldn’t we be able to generate the list of departments from the department pages? That wouldn’t require any additional work in the admin.

**Comment by briaguya** [comment]
Braindump:

## User types (WIP check [google doc](https://docs.google.com/spreadsheets/d/1O-oTlr4qI3PDamQa9zNQ5Cfdo1_q1LM6laVVRexbAaQ/edit#gid=0)):

  | Create departments? | Create users? | Create pages? | See pages?
-- | -- | -- | -- | --
Super Admin (name?) | Yes | In any department | In any department | ?
Dept Admin (name?) | No | In own department | In own department | ?
Dept editor (name?) | No | No | In own department | ?
??? | No | No | In any department | ?

### Flows in which the user's department will be used 
* Creating a new page
  * Limits around creating multiple department pages for a dept?
    * Customize createcontentmodal?
  * Make sure pages are assigned to the correct department
    * For users that are allowed to create pages in any department, what does this look like?
    * For users that are allowed to create pages in their own department only, this is done automatically.
      * 
* Filtering what pages appear:
  * Default search (https://joplin-staging.herokuapp.com/admin/pages/search/)
    * What do we do with the number on page filter buttons?
      * Edge case: If someone is in a department, and allowed to see but not edit pages from any department, do we show the number of pages in their department of each type or total?
  * Stopping until we have a clearer understanding on what we want to change from user type to user type from a who can see what stand point
* 

### Other stuff
* (tangent) We'll need to do some custom script work to retrofit our old pages
  * Something along the lines of: for each department page, create a department, for every other page, if it has a related department page, assign it to the department page's department
* In our custom publish logic, instead of checking for related department pages, we'll need to check to see if the department the page we're trying to publish belongs to has a department page live
  * How do we handle multiple department pages? We currently support that, do we plan on changing that?

**Comment by easherma** [comment]
@desigonz I'm sure but this might overlap with https://github.com/cityofaustin/techstack/issues/3919 ?

**Comment by briaguya** [comment]
## Acceptance criteria testing I've done
### Pages can be associated with department groups
1. Logged in to https://joplin-pr-3813-department-grou.herokuapp.com/admin/login/ as admin@austintexas.io
2. Navigated to the hidden departments as groups view (https://joplin-pr-3813-department-grou.herokuapp.com/admin/groups/)
3. Clicked on "Austin Public Health" (https://joplin-pr-3813-department-grou.herokuapp.com/admin/groups/7/) and scrolled down to see a bunch of pages with associated edit rights
