### ISSUE TITLE
Events - Joplin model

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3814]
### As an author, I want to be able to publish events so that residents can learn about events the City offers.

Fields
- [x] Title
  - [x] 58 character max
  - [x] This is the only field required for save
  - [x] Localize for `es` 
- [x] Long description
  - [x] Rich text block
  - [x] Localize for `es`
- [x] Event date picker
- [x] Event time
  - [x] Start time
  - [x] End time
- [x] Location—streamfield with two options:
  - [x] City location
    - [x] Opens a location picker (required within streamfield)
    - [x] Field for additional details, such as room number
      - [x] Localize for `es`
  - [x] Remote location
    - [x] Remote location name field
      - [x] Localize for `es`
    - [x] Address field (like in the location content type)
    - [x] Field for additional details, such as room number
      - [x] Localize for `es`
- [ ] Cost ~~radio buttons~~ <--post-mvp
  - [x] This event is free
  - [ ] This event requires a fee
    - [x] Ability to add multiple fees
    - [x] Fee $ field
    - [x] Fee label field
      - [x] Label fields must be localized for `es`
- [x] Registration URL field
- [x] Related departments (can add multiple)
- [x] Contacts
- [x] "Cancel this event" checkbox

XD: https://xd.adobe.com/view/13cf6c47-e3bc-4c21-7449-0f4cb312ace0-65fe/
Design issue: https://github.com/cityofaustin/techstack/issues/3725

In Joplin, create a new model:
* Follow the pattern of Location pages being it's own Django app.
* The model should have
  * Description: `description = models.TextField`
  * Date: `date = models.DateField`
  * Time = `time = models.TimeField`
  * An array of locations
    * This should include the option for a location page or a manually entered location @toribr @desigonz is the non city location mvp for this?
  * Cost (array of fees/fee labels), option to be free
  * Registration URL
  * Related Departments (array of FKs to dept page)
  * Contact (FK to it)
  * Cancelled flag

**Comment by easherma** [comment]
Yes non-city location is mvp

**Comment by desigonz** [comment]
I'm going to add acceptance criteria to the above.

**Comment by briaguya** [comment]
@easherma the calendar lib sounds interesting, but it feels like it's blowing the scope on this. I think to keep it MVP and ship it fast we should just use a date/time for now.

**Comment by desigonz** [comment]
Acceptance criteria updated above

**Comment by easherma** [comment]
@briaguya thats what im saying, we don't need to use the calendar part, we just use the model parts we need. It ought to save time, not blow scope. 

Most of the fields are already covered:
https://github.com/linuxsoftware/ls.joyous/blob/e94026a442764d965bd8a39401fba6d255325245/ls/joyous/models/events.py#L483

So we just make a model that inherits this EventsBase model and then add the extra stuff we need.

**Comment by briaguya** [comment]
Implementation vs. XD

## Event title
### Xd
<img width="770" alt="Screen Shot 2020-01-29 at 3 22 21 AM" src="https://user-images.githubusercontent.com/6384156/73343679-9dc07080-4246-11ea-8739-595dbf771853.png">

### Implementation
<img width="920" alt="Screen Shot 2020-01-29 at 3 21 21 AM" src="https://user-images.githubusercontent.com/6384156/73343688-a1ec8e00-4246-11ea-9a41-fe1214fcfd42.png">

### Differences
* Title instead of "Event title"
  * This is standard across Joplin
* Fonts

## Long description
### Xd
<img width="788" alt="Screen Shot 2020-01-29 at 3 24 23 AM" src="https://user-images.githubusercontent.com/6384156/73343854-e710c000-4246-11ea-84d0-1c01b8d11aa1.png">

### Implementation
<img width="1063" alt="Screen Shot 2020-01-29 at 3 25 09 AM" src="https://user-images.githubusercontent.com/6384156/73343889-f98af980-4246-11ea-99c7-c181574e3eb1.png">

### Differences/Questions
* Missing "Long description" heading
* What rich text options should we allow?
* Missing character counter for rich text (we don't have this anywhere else in Joplin)

## Event date/Event time
### Xd
<img width="410" alt="Screen Shot 2020-01-29 at 3 28 21 AM" src="https://user-images.githubusercontent.com/6384156/73344134-6f8f6080-4247-11ea-9f11-51b309180378.png">

### Implementation
<img width="625" alt="Screen Shot 2020-01-29 at 3 28 12 AM" src="https://user-images.githubusercontent.com/6384156/73344153-75854180-4247-11ea-8526-dd152e7e7276.png">

### Differences
* Date picker is one field instead of 3
* Fonts/spacing

## Location (city)
### Xd
<img width="783" alt="Screen Shot 2020-01-29 at 3 31 02 AM" src="https://user-images.githubusercontent.com/6384156/73344505-1a078380-4248-11ea-8a40-0f8abf2167a4.png">

### Implementation
<img width="1099" alt="Screen Shot 2020-01-29 at 3 30 53 AM" src="https://user-images.githubusercontent.com/6384156/73344537-255aaf00-4248-11ea-8a56-e07c77cc7908.png">

### Differences
* "Choose another location" is "Choose another page"
  * This is standard across Joplin
* Fonts/spacing

## Location (non-city)
### Xd
<img width="446" alt="Screen Shot 2020-01-29 at 3 36 35 AM" src="https://user-images.githubusercontent.com/6384156/73344770-926e4480-4248-11ea-8e88-d2d120a941ae.png">

### Implementation
<img width="661" alt="Screen Shot 2020-01-29 at 3 32 10 AM" src="https://user-images.githubusercontent.com/6384156/73344806-99955280-4248-11ea-9ac4-c6e648900db7.png">

### Differences
* Layout
  * Need to find an example of StructBlocks in streamfields that allow customizing layout so it's not one tall list
* Right now the implementation has "remote location" in as the text, Xd has "Non-city location of event"
  * The picker has "non-city location" in the mocks, TODO @briaguya change remote to non-city

## Location (type chooser)
### Xd
<img width="445" alt="Screen Shot 2020-01-29 at 3 42 02 AM" src="https://user-images.githubusercontent.com/6384156/73345263-6901e880-4249-11ea-9384-8029875f699e.png">

### Implementation
<img width="1092" alt="Screen Shot 2020-01-29 at 3 31 26 AM" src="https://user-images.githubusercontent.com/6384156/73345279-7028f680-4249-11ea-8f3a-0b350c1e9da9.png">

### Differences
* Fonts
* Missing icons TODO: @briaguya fix those
* Can add multiple right now (will be fixed with https://github.com/cityofaustin/techstack/issues/3851 and https://github.com/cityofaustin/techstack/issues/3858)

## Cost
### Xd
<img width="582" alt="Screen Shot 2020-01-29 at 3 46 29 AM" src="https://user-images.githubusercontent.com/6384156/73345606-f8a79700-4249-11ea-927b-bd2b80d61b28.png">

### Implementation
<img width="927" alt="Screen Shot 2020-01-29 at 3 47 18 AM" src="https://user-images.githubusercontent.com/6384156/73345664-14ab3880-424a-11ea-8966-4c9a4750d1f9.png">

### Differences
* Free is a checkbox instead of a radio button
  * Radio button plans?
  * We discussed conditionally hiding fees based on free/not free events
* Fonts
* Missing '$'

## Registration url
### Xd
<img width="732" alt="Screen Shot 2020-01-29 at 3 50 32 AM" src="https://user-images.githubusercontent.com/6384156/73345930-956a3480-424a-11ea-8020-3d9d1111341b.png">

### Implementation
<img width="1056" alt="Screen Shot 2020-01-29 at 3 50 48 AM" src="https://user-images.githubusercontent.com/6384156/73345987-af0b7c00-424a-11ea-9741-0f2380a241a6.png">

### Differences
* Missing "registration" heading
* Fonts

## Related departments
### Xd
<img width="332" alt="Screen Shot 2020-01-29 at 3 53 43 AM" src="https://user-images.githubusercontent.com/6384156/73346195-13c6d680-424b-11ea-8993-d44d03bca4e3.png">

### Implementation
<img width="318" alt="Screen Shot 2020-01-29 at 3 53 37 AM" src="https://user-images.githubusercontent.com/6384156/73346229-1f1a0200-424b-11ea-9c1f-5846170d3981.png">

### Differences
* Fonts

## Contact
### Xd
<img width="288" alt="Screen Shot 2020-01-29 at 3 56 09 AM" src="https://user-images.githubusercontent.com/6384156/73346334-4ec90a00-424b-11ea-8985-97299fd6b826.png">

### Implementation
<img width="246" alt="Screen Shot 2020-01-29 at 3 56 34 AM" src="https://user-images.githubusercontent.com/6384156/73346362-5be5f900-424b-11ea-9e07-3d0334c491ba.png">

### Differences
* We decided on only one contact for events, Xd shows the UI for multiple

## Cancel
### Xd
<img width="683" alt="Screen Shot 2020-01-29 at 3 58 01 AM" src="https://user-images.githubusercontent.com/6384156/73346503-964f9600-424b-11ea-9ce9-101bc0b88360.png">

### Implementation
<img width="153" alt="Screen Shot 2020-01-29 at 3 57 54 AM" src="https://user-images.githubusercontent.com/6384156/73346522-9cde0d80-424b-11ea-90a9-d3074cb5c3c2.png">

### Differences
* Missing "will not unpublish" helper text
* Fonts

**Comment by desigonz** [comment]
@briaguya I've put together 6 events that cover various combinations we'll want to test, including:
- Canceled/not canceled
- CoA location/Remote location
  - Within this, I've included examples of each that have/don't have additional location details
- Free/one fee/multiple fees
- Registration link/no registration link
- End time/no end time

The test data lives in the last tab in [this spreadsheet](https://docs.google.com/spreadsheets/d/1TcKkfMZRVjATZYT6hIBM27FvWLR-wsNLf5pIHAIax8w/edit#gid=1474893340). 

I'm also going to review your notes above of re: Implementation vs. XD.

**Comment by briaguya** [comment]
Things left for MVP:
* Cancel
  * Missing "will not unpublish" helper text
* Registration url
  * Missing "registration" heading
* Location (non-city)
  * Remove country
* Long description
  * Missing "Long description" heading

**Comment by desigonz** [comment]
QA passed!
