### ISSUE TITLE
Events detail view: Janis

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3815]
### As a resident, I want to learn about events the City offers that are relevant to me, so that I can find one to attend.

- [ ] Design matches mocks
  -  [ ] Janis [spec overview](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/)
  - [ ] [Desktop](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/screen/3da19c95-f6c3-4177-9bba-98e36449bdbd/Event-MVP-Detail-Desktop-2)
  - [ ] [Mobile](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/screen/43e6c429-6434-49c1-9bdb-dab5547c8b0d/Event-MVP-Detail-Mobile-2)
- [x] Preview works for this content type
- [ ] Interactive states (hover, down, focus, keyboard focus, disabled)—Janis [spec overview](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/)
- [ ] Defined behaviors: includes guidelines for layout (wrapping, truncation, overflow), animation, interactions, etc.—Janis [spec overview](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/)
- [ ] Accessibility behaviors—@chasechenevert to add
- [ ] Feedback form appears on page

#### Test that the following content appears:
- [x] Title
    - [x] `en`
    - [x] `es`
    - [x] Stretches across the full width **@chasechenevert can you confirm?**
- [x] Long description
    - [x] `en`
    - [x] `es`
- [x] Event date
  - [x] Day of the week
  - [x] Date `January 17, 2020`
  - [x] If event is canceled, `CANCELED` badge appears before date per mock
     - [x] `en`
     - [x] `es` translate to `CANCELADO`
  - [x] Date localizes; use the same translations we use for OPO. For days of the week, use [these translations](https://www.spanishdict.com/guide/days-of-the-week-in-spanish) and let's capitalize the first letter in each weekday 
    - [x] `en`
    - [x] `es`
- [x] Event time
  - [x] Start time only
  - [x] Start and end time
- [ ] Location
  - [ ] For both types of locations: "Get directions" link opens Google maps in new window
    - [x] `en`
    - [x] `es`: `Obtener direcciones`
  - [x] City location
    - [x] Display street address (no Austin, TX 78777) **@chasechenevert and @srigdon please confirm this**
      - [x] Without additional details—nothing appears beyond address
      - [x] With additional details, such as room number, appears on its own line
        - [x] `en`
        - [x] `es`
    - [x] "Location information ->" appears on Janis
  - [x] Remote location
    - [x] Location name
      - [x] `en`
      - [x] `es`
    - [x] Display street address (no Austin, TX 78777) **@chasechenevert and @srigdon please confirm this**
      - [x] Without additional details—nothing appears beyond address
      - [x] With additional details, such as room number, appears on its own line
        - [x] `en`
        - [x] `es`
- [ ] Cost
  - [x] If event is free, display `Free`
    - [x] `en`
    - [x] `es`: translate to `Gratis`
  - [x] If only one cost is entered into Joplin, display cost (ex. `$20`)
  - [x] If a multiple costs are entered into Joplin, ~~display range (ex. `$1–$10),~~ list fee schedule
      - [x] Labels appear in `en`
      - [x] Labels appear in `es`
- [x] Register/free
  - [x] If there is a registration link in Joplin, display `Register` and link to that link
      - [x] `en`
      - [x] `es`: translate to `Regístrese`
  - [x] If there is no registration link in Joplin, display `Open to the public`
      - [x] `en`
      - [x] `es`: translate to `Abierto al público`
- [x] Long description
  - [ ] Affordances
    - [ ] Lists: ul/ol
    - [ ] Bold
    - [ ] Italic
    - [ ] Link
    - [ ] Forced line break
  - [ ] Let's test that the various rich text things format correctly
    - [x] `en`
    - [x] `es`
  - [x] Header "Details"
    - [x] `en`
    - [x] `es`: translate to `Detalles`
- [x] Contact block in the right rail
- [x] Contextual nav
  - [x] The left side links to `All events`
      - [x] Localize for `es`: use `Todos eventos`
  - [x] The right side displays `Offered by: Department name`
    - [x] `en`
    - [x] `es`

More detail page stuff
## Detail page
- All icons should match text color: #272727

**Rich text affordances**
- Bold
- Italic
- Link
- Forced line break
- Lists: ordered, unordered

**Fee and registration display**
Possible displays on the detail page view. Arrows denote the outbound icon next to links that take the resident away from the domain.
- Free
- Free • Register ⬈
- Register ⬈
- $1
- $1–$5
- $1 • Register ⬈
- $1–$5 • Register ⬈

**Location display**
Get directions ⬈

**Comment by desigonz** [comment]
@chasechenevert Can you add mobile and tablet specs, as well as defining the rest of the things from the [dev handoff checklist](https://github.com/cityofaustin/techstack/issues/new?template=handoff_checklist.md)?

**Comment by chiaberry** [comment]
we estimated the location janis side as 8, i am making this a 13 so we can make sure *everything* on the checklist is triple checked

**Comment by desigonz** [comment]
@briaguya Updated specs
- [Overview](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/)
- Detail page: [desktop](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/screen/3da19c95-f6c3-4177-9bba-98e36449bdbd/Event-MVP-Detail-Desktop)
- Detail page: [mobile](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/screen/43e6c429-6434-49c1-9bdb-dab5547c8b0d/Event-MVP-Detail-Mobile)

**Comment by desigonz** [comment]
Hey @chiaberry— @briaguya's been working on this: https://github.com/cityofaustin/janis/pull/678
I think that is the data side needed to get you started on this issue??

**Comment by desigonz** [comment]
@chiaberry oops scratch that, meant to put the comment on #3817, will do that now

**Comment by briaguya** [comment]
@chiaberry left a comment about "Todos eventos" vs "Todos los eventos" (https://github.com/cityofaustin/janis/pull/678#discussion_r373217863), @desigonz should I make the change?

**Comment by desigonz** [comment]
Starting to QA—will keep updating here. I'll let you know when I'm done with my first pass, then send on to @chasechenevert!

- [ ] Need to localized "Location information" bar. **content or @desigonz to fill in translation**
![image](https://user-images.githubusercontent.com/5839508/73501455-98207300-438b-11ea-9dec-07fa9de67dbb.png)

But noticing we also missed this when implementing the new location content type:
![image](https://user-images.githubusercontent.com/5839508/73501526-cb630200-438b-11ea-8dab-fb0b55daac9c.png)

@briaguya should this spin out into its own issue?

**Comment by desigonz** [comment]
@briaguya Yes, let's go with "Todos los eventos." I'm going to ask MY mom and sister about "Location info" now, lol

**Comment by desigonz** [comment]
Time style things:
- [ ] use an en dash `–` between the times
- [ ] lowercase `am` and `pm`
This should be the same thing across the board on our site—I wonder if we want to abstract this out at some point, so it's all centrally managed? We could make a new issue for that.

![image](https://user-images.githubusercontent.com/5839508/73502821-e20b5800-438f-11ea-8ad7-ac8816427dff.png)

**Comment by desigonz** [comment]
@chiaberry or content folks (@Jo-Dwyer @srigdon @ablangworthy27) can y'all weigh in on this?

Days of the week aren't capitalized en español, but I think one would capitalize it at the beginning of a sentence. See screenshot below—we're inconsistent. Which way should we go?

![image](https://user-images.githubusercontent.com/5839508/73502911-2991e400-4390-11ea-9e21-0ec08d1e3a61.png)

**Comment by desigonz** [comment]
Also for content team:

Time localization en español. 24-hour clock or AM/PM? We might just want to pick a consistent thing for MVP, then do a deeper dive once we have a Spanish language strategist.

![image](https://user-images.githubusercontent.com/5839508/73502984-5d6d0980-4390-11ea-9013-02e3b6fe8f52.png)

![image](https://user-images.githubusercontent.com/5839508/73502975-5514ce80-4390-11ea-82cc-eb0febd86f50.png)

**Comment by desigonz** [comment]
Dang @briaguya this is looking good. Caught these things:

- [ ] Feedback form not appearing on this page
- [ ] "Get directions" and "Obtener direcciones" should open in new tab

Passing off to @chasechenevert for a design review. Also going to get a content strategist to review tomorrow.

**Comment by Jo-Dwyer** [comment]
@desigonz Let's capitalize days of the week as that seems to be the usual on all the calendars en español I have found.

Re: time. Let's got 24 hr since the Joplin side is 24 hr and it will be consistent for both languages and users for now.

**Comment by briaguya** [comment]
@desigonz re: time - made an issue to make sure it's unified correctly across Janis https://github.com/cityofaustin/techstack/issues/3897

**Comment by briaguya** [comment]
alright @desigonz I have the times unified and using existing logic but I also made an issue for it so we can come up with a clean solution to use everywhere and figure out full criteria for localization eventually https://github.com/cityofaustin/techstack/issues/3897

I also made an issue for location information links https://github.com/cityofaustin/techstack/issues/3896, other than that it should be updated with all the changes from the QA notes

**Comment by desigonz** [comment]
QA passed!! Awesome work!
