### ISSUE TITLE
Janis/Joplin - Get Events pages publishing and previewing

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3816]
We need to get it so events correctly publish out/preview. This means:

Prerequisite for both:
* Make sure the Events page model is exposed properly in the Joplin API

Publishing:
* Update site structure in Joplin to include event pages.
  * The event page urls should be in the structure of /YYYY/MM/DD/event-slug
* Update the Janis build process to create event pages at the correct URLs

Previewing:
* Update Joplin preview links to generate urls for event pages
* Update PageRevisionNode in schema.py in the api folder to support event page
* Update Janis preview page to support event preview urls

So far this query is working
```
{
allEventPages {
    edges {
      node {
        title
        description
        locations {
          additionalDetails
          locationType
          cityLocation {
	    id
            title 
          }
          remoteLocation {
            name
            street
            city
            state
            zip
          }
        }
      }
    }
  }
}
```

**Comment by desigonz** [comment]
I'm going to say QA passed on this one :)
