### ISSUE TITLE
Research roadmap meeting prep

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3820]
In #3767, we're going to be scoping research priorities that support the delivery of our roadmap. Your homework is to come with a sense of opportunities for research from your discipline's perspective.

**Comment by desigonz** [comment]
- research ahead of content type dev
- quantitative dev from City authors re: how they use the author interface

**Comment by toribr** [comment]
Let's get some quantitative data on city authors to guide Joplin.
Some things I'd like to know are:
_Content & moderation_ 
* how many times a week or month do they use the system? 
* how many hours a week or month do they use the system?
* are they creating new content or editing existing content or both?
* Are they writing in the tool or cutting and pasting from elsewhere? if cutting and pasting, then from where? how does formatting change? 
* Is their work moderated or approved by someone else, and if so, how? (physically how - sent via email, in person, paper, what?)
* how many people in the approval process?
* how many in their office touch drupal?
* what types of content do they usually work with? give list: events, news, information, etc - may need descriptions so they can decide 
* approx age (or do ask about other types of content making apps they use, ie, previous experience with Wordpress, squarespace, etc.)
* what other tools, software or websites do they use in their content-related work
* do they use google analytics? if so, what do they look at?
* what size monitor do you use?
* what dept are they in?
* do they do any translations? if so what language?

@chasechenevert Can you think of any others?

**Comment by toribr** [comment]
Ideas from lunch:

Research on screen readers as components are launched.

Formalizing evaluation accessibility of buildings
- how is accessibility not true?
- how might we teach people how to really evaluate accessibility and improve it?

**Comment by desigonz** [comment]
Re: buildings, are you referring to physical accessibility? (Not web accessibility of our site, right?)

**Comment by toribr** [comment]
Also for future: alerts
existing: locations

**Comment by desigonz** [comment]
Thanks @toribr!
