### ISSUE TITLE
IA requirements for publishing a page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3823]
### As a Joplin user, I want the above to apply to IA rules, so that I ensure that a page I publish will build and live somewhere on Janis.

- [ ] IA requirement for publishing (so a page will build)
  * For INFO and SERVICE pages:
    * on publish, you need to have at least:
      * 1 TOPIC **OR** 1 DEPARTMENT **OR** TOP LEVEL checked
  * For FORM CONTAINER, GUIDE, or OFFICIAL DOCS pages:
    * on publish, you need to have at least:
      * 1 TOPIC **OR** 1 DEPARTMENT 
  * For TOPIC pages
    * on publish, you need a TOPIC COLLECTION
  * For TOPIC COLLECTION pages
    * on publish, you need a THEME
  - [ ] Need an error message to display at the top for the "1 TOPIC **OR** 1 DEPARTMENT **OR** TOP LEVEL checked" logic **(copy TBD)**

**Comment by Niicck** [comment]
Requirements: https://github.com/cityofaustin/techstack/issues/3379

**Comment by desigonz** [comment]
@Niicck's working on this and writing unit tests

**Comment by Niicck** [comment]
https://joplin-pr-3823-preflight-ia.herokuapp.com/admin

**Comment by desigonz** [comment]
### Test cases

Info page
- [ ] Select neither 1 TOPIC nor 1 DEPARTMENT nor TOP LEVEL; shouldn't publish
- [ ] Select 1 TOPIC and nothing else; should publish
- [ ] Select 1 DEPARTMENT and nothing else; should publish
- [ ] Select 1 TOP LEVEL and nothing else; should publish
- [ ] Select two of the above; should publish

Service page
- [ ] Select neither 1 TOPIC nor 1 DEPARTMENT nor TOP LEVEL; shouldn't publish
- [ ] Select 1 TOPIC and nothing else; should publish
- [ ] Select 1 DEPARTMENT and nothing else; should publish
- [ ] Select 1 TOP LEVEL and nothing else; should publish
- [ ] Select two of the above; should publish

Form container
- [ ] Select neither 1 TOPIC nor 1 DEPARTMENT; shouldn't publish
- [ ] Select 1 TOPIC and nothing else; should publish
- [ ] Select 1 DEPARTMENT and nothing else; should publish
- [ ] Select both of the above; should publish

Guide
- [ ] Select neither 1 TOPIC nor 1 DEPARTMENT; shouldn't publish
- [ ] Select 1 TOPIC and nothing else; should publish
- [ ] Select 1 DEPARTMENT and nothing else; should publish
- [ ] Select both of the above; should publish

Official document
- [ ] Select neither 1 TOPIC nor 1 DEPARTMENT; shouldn't publish
- [ ] Select 1 TOPIC and nothing else; should publish
- [ ] Select 1 DEPARTMENT and nothing else; should publish
- [ ] Select both of the above; should publish

Topic
- [ ] Don't select TOPIC COLLECTION; shouldn't publish
- [ ] Select TOPIC COLLECTION; should publish

Topic
- [ ] Don't select THEME; shouldn't publish
- [ ] Select THEME; should publish

**Comment by desigonz** [comment]
This is a bug that's probably unrelated but posting here in case it is a related regression:
1. Go to Joplin content listing page
2. Click on a page type filter (for example, "Service page")
3. See error: "This field is required" appears under the search box
![image](https://user-images.githubusercontent.com/5839508/73897453-bd115c00-484b-11ea-8bbc-0831fbc054a4.png)

And also perhaps relatedly:
1. Go to Joplin content listing page
2. Click on the page type filter "Form container"
3. Get error screen
![image](https://user-images.githubusercontent.com/5839508/73897474-d31f1c80-484b-11ea-8682-54f9c280eadf.png)

**Comment by desigonz** [comment]
Hi @Niicck—your work looks amazing!! Acceptance criteria passes but found the bug above, can you check to size if it's a regression and then size what fixing it might be?

I made issue #3913 to log a question—last spring we built the affordance to assign topic collections to topic collections. We're not currently using this on any page. And in this issue, we made it so you have to assign a topic collection to a theme, which seems to contradict the nesting topic collections. We'll want to decide what to do here. (Totally my oversight for not catching this!)

Nick, if we later decide we want the permission to be that, on topic collections, you have to select either a theme or a topic, will that be a big lift? Because I don't want this to stop us from pushing this to production.

**Comment by Niicck** [comment]
If we decide to do it, it will be very easily switch out the theme requirement for an IA requirement of either a theme or a topic collection. No worries.

**Comment by desigonz** [comment]
Awesome, that's great! In that case, can you take a look at the bug(s) reported above and let me know if it's a regression related to this issue?
- If it's unrelated we can spin it out into it's own issue
- If it is related, can you size it?

**Comment by Niicck** [comment]
- Fixed the Form Container error page. That was a bug with our test data. Fixed now. https://joplin-pr-3823-preflight-ia.herokuapp.com/admin/pages/search/?q=&content_type=base.formcontainer
- "This field is required" is weird. That is a new bug. I'll make an issue.
