### ISSUE TITLE
Deleting required fields bug

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3824]
## Describe the bug
As we're working on #3379: If I publish a page with all of the required fields, but later delete one of the required-to-publish fields, it still allows me to publish. This is not the behavior I would expect; I would expect it to throw an error. (This might explain some of the things you couldn't replicate or were inconsistent)

## To Reproduce
Steps to reproduce the behavior 
example: 

## Current behavior
A clear and concise description of what happened

## Expected behavior
A clear and concise description of what you expected to happen

**Comment by desigonz** [comment]
empty arrays versus null
AND/OR is it related to the streamfield thing

More documentation is in #3379, @desigonz to copy/pasta into here

**Comment by easherma** [comment]
This only happens on streamfields, it should be addressed once we have a good solution for preventing publish with no streamfields.

**Comment by desigonz** [comment]
Might be moot with #3827

**Comment by desigonz** [comment]
@Niicck and @chiaberry, I believe this is fixed from what I QA'd—would y'all agree?

**Comment by chiaberry** [comment]
yes!
