### ISSUE TITLE
Require a whole streamfield block

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3827]
### As a Joplin user, I want to be able to save a page without filling out the required fields but not be able to publish it without the required fields, so that I can confidently publish my content.

- [ ] Ability to require a whole streamfield block (not just an individual instance within a streamfield)

@desigonz to flesh out test cases based on #3379

**Comment by chiaberry** [comment]
@desigonz is error messaging / labeling the streamfield block part of the acceptance criteria?

**Comment by chiaberry** [comment]
test cases to try: 
Guide Page: 
- never add a page in the section
- open the sections, only add a header
- open the sections, only add a page
- add both header and page

Service Page
- dont add any steps

**Comment by desigonz** [comment]
@chiaberry Oooh good question on error messaging. I think we should include it as part of acceptance criteria, but it can be really basic. What would you size error messaging at?

I fleshed out test cases a bit—did I go overboard? Does this make sense?

### Guide Page
- [ ] When user doesn't add any sections/streamfields, don't publish (because at least one section is required)
- [ ] When a user adds a section but adds neither heading nor page, don't publish (because heading and page are required within the streamfield)
- [ ] When a user adds sections, and within section only adds a header but no page, don't publish  (because **both** heading and page are required within the streamfield)
- [ ] When a user adds sections, and within section only adds a page but no header, don't publish  (because **both** heading and page are required within the streamfield)
- [ ] When user adds at least one section, and each section has a header and one page, publish!!

### Service Page
- [ ] When user doesn't add any steps, don't publish 
- [ ] When user adds at one `step` without content, don't publish (because content is required within the streamfield)
- [ ] When user adds at one `step` with content, publish!
- [ ] When user adds at one `step with location` without content or a location, don't publish (because content is required within the streamfield)
- [ ] When user adds at one `step with location` with content, publish!
- [ ] When user adds at one `step with options` without content or option info field out, don't publish (because content is required within the streamfield)
- [ ] When user adds at one `step with options` with content, publish!
- [ ] When user adds multiple steps all with content, publish!

**Comment by desigonz** [comment]
@chiaberry is working on error messages popping up. Will also document the weird add/delete bug.

**Comment by desigonz** [comment]
Tested this in @Niicck's PR app for #3823 and it looks gorgeous! Awesome work @chiaberry!
