### ISSUE TITLE
Behavior when publishing from content list page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3828]
### As a Joplin user, I want to be able to save a page without filling out the required fields but not be able to publish it without the required fields, so that I can confidently publish my content.

- [ ] if not all the required fields are filled out, Joplin opens the edit page with the relevant error messaging

See #3379 for more info

**Comment by desigonz** [comment]
Note from @easherma:

> The current behavior is to display an error message at the top with a link to edit the page. We could adjust the timeout so it doesn't fade away and add a button so the message could be dismissed, thats more like a 2.
> Forcefully re-routing would probably need to do some testing to implement and not cause negative side affects, not sure about the UX of that if someone is on the list view and then is taken somewhere else.
> I'd be much more comfortable with just the way Wagtail handles it (allowing unpublishing but not publishing from the page listing view). In general, do we really want people publishing content without looking at it first anyways? Maybe we can simplify the acceptance criteria by clarifying why its valuable in the first place.

**Comment by easherma** [comment]
Per @Niicck we removed this functionality, so we don't need to solve for this scenario anymore.
