### ISSUE TITLE
Draft Rules of the Court as an information page

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3832]
Rules of the Court is a PDF: create an information page to hold the contents and see how it works to reference the info page from the service that pertains to it.

**Comment by ablangworthy27** [comment]
@Jo-Dwyer can you confirm that this is the pdf to work off of?
https://www.austintexas.gov/sites/default/files/files/Municipal_Court/Rules_of_the_Court_06-2014.pdf

**Comment by ablangworthy27** [comment]
@Jo-Dwyer I went ahead and drafted in Joplin, so we could see what the formatting looks like.
https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZTozNTkw

**Comment by srigdon** [comment]
Looks good, ready to publish.
