### ISSUE TITLE
Draft out of custody jail credit form

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3834]
- [ ] draft form content in formstack
 - [ ] share with design @chasechenevert @toribr
 - [ ] review by content @srigdon @ablangworthy27
 - [ ] send to Amy Schillerstrom for review by Mary Jane Grubb and Judge Statman

**Comment by Jo-Dwyer** [comment]
You can plead “no contest” and submit proof to the court of your incarceration.  Jail credit is determined by a judge and if granted, will result in a conviction.

**Comment by InaraFernandez** [comment]
@gabrielaperezdelaosa found this on formstack: 

https://cityofaustin.formstack.com/forms/out_of_custody_jail_credit_request_form

I will work on the Spanish version

**Comment by gabrielaperezdelaosa** [comment]
@InaraFernandez awesome!

**Comment by gabrielaperezdelaosa** [comment]
@InaraFernandez it's not quite this issue, but this is the other form we need made into a formstack:
http://www.austintexas.gov/sites/default/files/files/Municipal_Court/SPANISH_Opt_Out_Form_03_2019.pdf

**Comment by InaraFernandez** [comment]
Update on this issue: Amy is working on getting the ES form up. Not sure if we should close this issue.

**Comment by gabrielaperezdelaosa** [comment]
create a form container for the English version and move to review (ping me when you do this please)

**Comment by gabrielaperezdelaosa** [comment]
https://alpha.austin.gov/municipal-court/request-credit-for-time-incarcerated/

@InaraFernandez I did a quick form container so I could get another page working. Since we won't be able to do Spanish formstacks, no need to worry about this one anymore.

**Comment by gabrielaperezdelaosa** [comment]
@ablangworthy27 for review
