### ISSUE TITLE
Publish and send for translate smoking form

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3836]
- [x] Test email receipt with our stakeholders
- [ ] Publish 
- [ ] Send for translation

**Comment by ablangworthy27** [comment]
going to combine this with the other issue [#3703 ](https://github.com/cityofaustin/techstack/projects#workspaces/techstack-5a78b88e1ce69f3510b678ef/board?assignees=ablangworthy27&filterLogic=any&repos=118780243)
