### ISSUE TITLE
Locations hours display

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3840]
### As a resident, I want the hours for a location and the hours for a service within a location to display consistently, so I can have a consistent user experience. 

- [ ] For location hours 
  - [ ] Hours are now able to run the width of the component, so we don't have two columns
  - [ ] Special hours/hours exceptions display below hours
  - [ ] mobile view: force a line break after the comma to stack these vertically
- [ ] For service hours
  - [ ] Hours are now able to run the width of the component, so we don't have two columns
  - [ ] Special hours/hours exceptions display below hours
  - [ ] mobile view: force a line break after the comma to stack these vertically

<img width="923" alt="Screen Shot 2020-01-15 at 3 28 24 PM" src="https://user-images.githubusercontent.com/7027270/72473434-4df49a80-37ac-11ea-89af-47ec0e5afe72.png">
<img width="332" alt="Screen Shot 2020-01-16 at 2 59 36 PM" src="https://user-images.githubusercontent.com/7027270/72562374-e2283580-3870-11ea-899e-adb7784642f2.png">

**Comment by robbobfrh84** [comment]
@desigonz this is ready for QA!

PR: https://github.com/cityofaustin/janis/pull/682

Deployed: https://janis-3840-location-hours.netlify.com/

Mixed Example: https://janis-3840-location-hours.netlify.com/en/location/st-john-neighborhood-center/
Simple Example: https://janis-3840-location-hours.netlify.com/en/location/recycle-reuse-drop-off-center/

**Comment by desigonz** [comment]
Assigning @chasechenevert to QA this one!

**Comment by chasechenevert** [comment]
Looks good to me! 🚀

**Comment by desigonz** [comment]
Awesome, thanks @chasechenevert!

@robbobfrh84 I slapped on the "QA passed" label. Beautiful stuff!

**Comment by robbobfrh84** [comment]
Thanks y'all! 👏✅
