### ISSUE TITLE
Load prod datadump; get exception

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3843]
## Describe the bug
Exception at /admin/pages/search/
can't currently handle on_delete types other than CASCADE, SET_NULL and DO_NOTHING

This may simply be related to the other bug(sanitizing revisions), but it may also be at least partially caused by discrepancies in users/user permission checks between the test app set up for migrations and staging or prod users/permissions.

**Comment by desigonz** [comment]
Can you add more details/a user story so that I understand what the outcome of this would be?

**Comment by easherma** [comment]
I believe this was fixed by https://github.com/cityofaustin/techstack/issues/3842

But the outcome of the bug was that you couldn't view any pages.
