### ISSUE TITLE
"Create New Content" modal doesn't work on empty database

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#3845]
## Describe the bug
The "Create New Content" modal doesn't work on empty database.
Unless you enter something into the search bar first, then it'll work.

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Load a Joplin with an empty database
2. Click on the "Create Content Modal"

## Current behavior
A clear and concise description of what happened

## Expected behavior
A clear and concise description of what you expected to happen

## Screenshots

![Screen Shot 2020-01-25 at 3.14.51 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/25981a8d-f86a-44c5-8934-09da6c027263)

**Comment by chiaberry** [comment]
Hopefully this was fixed by https://github.com/cityofaustin/techstack/issues/3515.

**Comment by desigonz** [comment]
This seems really low-priority to me, since a Joplin user will never have an empty database and a dev probably has other options. Can you explain the use case/user value of this to me?

**Comment by Niicck** [comment]
It is reasonable for this to be really low priority. I reported it because it's a bug, and I think it's good to be aware of what's going on in our app. And it could be a side effect of some other deficiency in Joplin.

**Comment by desigonz** [comment]
Okay makes sense! I am going to close this issue, but we will have it documented and searchable in closed issues if we need to revisit it in the future.
