### ISSUE TITLE
Connecting the dots: feedback and page editing

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#3848]
Authors should be able to read comments from residents to find out what pages are missing content or need more detail, without needing to leave Joplin.

Can we add get the comments from the feedback, and post them into the notes section per page? How would that work? What about some sort of alert, too, from the pages list that showed which pages had comments?

What would be the MVP of this feature?

**Comment by desigonz** [comment]
Consolidated this in #807, closing this one.
