### ISSUE TITLE
Limit blocks on streamfields

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3851]
### As a [Joplin developer] I want [to be able to create streamfields with a max number of blocks] so that [we can use the flexibility of streamfields (choosing different types of content) for non list data].

**Is your feature request related to a problem? Please describe.**
We need to have either a location page selected or an address manually entered for event pages. We will eventually want to support multiple. The streamfield UI by default will allow us to enter multiple blocks, we only want to allow one.

**Describe the solution you'd like**
A pattern using streamfields (or an updated version of them) that supports limiting the number of items a use can *enter* (not just limit/error on save/publish)

**Describe alternatives you've considered**
* Not using streamfields, adding a dropdown and custom JS to hide fields
* Using StreamBlocks with a max_num (this just throws an error when too many are entered)

**Additional context**
* Dropping in react-streamfield may be a magic fix (https://github.com/wagtail/react-streamfield/blob/653197c844fca9343095ee7d9bfea769d91092e1/src/StreamField.js#L94) - (but also beware of magic, as it is powerful and requires much testing)
  * more react streamfield https://github.com/wagtail/wagtail/issues/4770#issuecomment-425963675
* This has been discussed in the wagtailverse (https://github.com/wagtail/wagtail/issues/5175)
* Streamblock stuff
```
    location_blocks = StreamField(StreamBlock(
        [
            ('city_location', StructBlock(
                [
                    ('location_page', PageChooserBlock(label="Location", page_type=[LocationPage], classname='do-not-hide')),
                    ('additional_details_en', TextBlock(label='Any other necessary location details, such as room number [en]', required=False)),
                    ('additional_details_es', TextBlock(label='Any other necessary location details, such as room number [es]', required=False)),
                    ('additional_details_ar', TextBlock(label='Any other necessary location details, such as room number [ar]', required=False)),
                    ('additional_details_vi', TextBlock(label='Any other necessary location details, such as room number [vi]', required=False)),
                ]
            )),
            ('remote_location', StructBlock(
                [
                    ('name_en', TextBlock(label='Name of venue [en]')),
                    ('name_es', TextBlock(label='Name of venue [es]', required=False)),
                    ('name_ar', TextBlock(label='Name of venue [ar]', required=False)),
                    ('name_vi', TextBlock(label='Name of venue [vi]', required=False)),
                    ('street', TextBlock(label='Street', required=False)),
                    ('unit', TextBlock(label='Unit', required=False)),
                    ('city', TextBlock(label='City', required=False)),
                    ('state', TextBlock(label='State', required=False)),
                    ('country', TextBlock(label='Country', required=False)),
                    ('zip', TextBlock(label='ZIP', required=False)),
                    ('additional_details_en', TextBlock(label='Any other necessary location details, such as room number [en]', required=False)),
                    ('additional_details_es', TextBlock(label='Any other necessary location details, such as room number [es]', required=False)),
                    ('additional_details_ar', TextBlock(label='Any other necessary location details, such as room number [ar]', required=False)),
                    ('additional_details_vi', TextBlock(label='Any other necessary location details, such as room number [vi]', required=False)),
                ],
                # label="Step With Options"
            )),
        ], max_num=1),
        verbose_name='Add location of event',
        # this gets called in the help panel
        # help_text='A step may have a basic text step or an options accordion which reveals two or more options',
        blank=True
    )
```

**Comment by desigonz** [comment]
@chiaberry to get @robbobfrh84's help on hiding fields

**Comment by chiaberry** [comment]
@desigonz  http://joplin-pr-3851-limit-blocks.herokuapp.com/

I changed the streamfields to react-streamfields.
It should be no different from the streamfields we already have. What took longest was hiding the translated fields. Bob got it over the finish line. The way to test is to go to the guide page and add sections, toggling the languages in the dropdown at the top. The expected fields should be the ones showing.

**Comment by desigonz** [comment]
### Test cases
- [ ] Service page **basic step**
  - [ ] Looks like its counterpart on staging
  - [ ] can edit in English and in Spanish
- [ ] Service page **step with options**
  - [ ] Looks like its counterpart on staging
  - [ ] can edit in English and in Spanish
- [ ] Service page **step with locations**
  - [ ] Looks like its counterpart on staging
  - [ ] can edit in English and in Spanish
- [ ] Guide
  - [ ] Looks like its counterpart on staging
  - [ ] can edit in English and in Spanish

**Comment by desigonz** [comment]
- [ ] Missing the insert document functionality on all step types on service pages
![image](https://user-images.githubusercontent.com/5839508/74365300-6a77f880-4d93-11ea-8843-a5feefe3384c.png)
  - [ ] basic step
  - [ ] step with options
  - [ ] step with locations

**Comment by chiaberry** [comment]
@desigonz I updated to match staging, the document links are visible now

**Comment by desigonz** [comment]
Looks great! QA passed.
