### ISSUE TITLE
Drupal 8 User Manual Documentation validation 

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#3856]
This is for testing the user Manual Documentation Validation created by Tim to improve the documentation

Out of scope: Document any author-side interfaces issues for future reference

**Comment by anukandimalla** [comment]
Related document :https://docs.google.com/document/d/1XBxg6eRg_L_Zip1H8uCK7zRFYsqGNO-Gspu1vFq2VMQ/edit?usp=sharing

**Comment by desigonz** [comment]
Is this done? Can we close it?

**Comment by anukandimalla** [comment]
This is Drupal 8 Manual Documentation validation for Drupal 8 authors. We didn't get a chance to do it because of other priority issues during the transition.
