### ISSUE TITLE
City council district question on OPO application

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3857]
## Describe the bug
In the council district question, it says both optional and required: City Council District (Optional)(Required)
That is confusing.
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/f058fb02-ff6f-484a-89aa-f35f802256d3)

- [x] Figure out if it's optional or required
- [x] Sentence case—don't capitalize the things?

## URL
https://alpha.austin.gov/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyOTI2

**Comment by ablangworthy27** [comment]
These edits  have been incorporated
