### ISSUE TITLE
Events - a user can only add one location

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3858]
### As a [content author] I want [to only be able to enter a location in Joplin if it will publish out to Janis] so that [I don't get confused about why only 1 of my 3 locations is showing up on alpha].

**Describe the solution you'd like**
* Give the location streamfield a maximum of 1 entry (https://github.com/cityofaustin/techstack/issues/3851)

### Acceptance criteria
- [ ] A user can only add one event location to the event content type.

**Comment by easherma** [comment]
QA @ https://joplin-pr-3858-one-place-one-t.herokuapp.com/

**Comment by desigonz** [comment]
That's pretty cool. Thanks for the great work @easherma! QA passed.
