### ISSUE TITLE
OPO contact snippet is repeating itself

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#3864]
## Describe the bug
The OPO's contact snippet shows the information twice. 

## URL
https://alpha.austin.gov/en/police-oversight/serve-on-the-community-police-review-commission/

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to https://alpha.austin.gov/en/police-oversight/serve-on-the-community-police-review-commission/
2. Scroll down to the contact snippet 
3. See error

## Screenshots
![Screen Shot 2020-01-29 at 11 57 05 AM](https://user-images.githubusercontent.com/5445796/73384373-c79e8500-4290-11ea-934c-de1b44a0b6f5.png)

## Device and browser
Macbook Air, Firefox 72.0.1 (64-bit)

**Comment by desigonz** [comment]
Looks like there were two contacts added to that page. Eventually we're going to limit to one contact per page (#3745) but for now I've deleted the second contact.
