### ISSUE TITLE
Complex fees brain/picture dump

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3871]
so, i think we have:
"This event is free" checked/"This event is free" unchecked, only one fee entered, that fee is zero, we have no label for it (should prevent the second one in joplin though)
<img width="129" alt="Screen Shot 2020-01-29 at 3 55 43 PM" src="https://user-images.githubusercontent.com/6384156/73401057-07289980-42b0-11ea-93a2-4e67a0d8c2e2.png">

"This event is free" unchecked, only one fee entered, that fee is not zero, no label for it
<img width="120" alt="Screen Shot 2020-01-29 at 3 58 28 PM" src="https://user-images.githubusercontent.com/6384156/73401380-a8175480-42b0-11ea-9d2b-e5a833137e49.png">

"This event is free" unchecked, only one fee entered, that fee is not zero, there is a label for it
<img width="152" alt="Screen Shot 2020-01-29 at 4 02 49 PM" src="https://user-images.githubusercontent.com/6384156/73401498-deed6a80-42b0-11ea-8dc3-697aeca398fe.png">

"This event is free" unchecked, multiple fees entered
<img width="291" alt="Screen Shot 2020-01-29 at 4 01 13 PM" src="https://user-images.githubusercontent.com/6384156/73401348-98980b80-42b0-11ea-9397-5476358f2fc9.png">

**Comment by desigonz** [comment]
This is done I believe!
