### ISSUE TITLE
Privacy plugin fallback message

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3872]
### The situation
When people have a privacy browser plugin like[Privacy Badger](https://chrome.google.com/webstore/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp?hl=en-US) on, Formstack forms don't load.
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/97bd6971-e0b5-409c-a006-5c1435631a0e)
@robbobfrh84 has been working on a brilliant solution to show fallback messaging when this happens. This message will also appear when the page is a really long time to load, such as in the case of a really bad internet connection.

### Your mission
- [x] **Content team**: Draft the content for this message.
@robbobfrh84's added placeholder text that gives the gist of what we want to communicate. (Question for @robbobfrh84: do we have to write out the URL of the form, or could it be [a hyperlink like so](https://cityofaustin.formstack.com/forms/cprc_application)?)
- [x] @chasechenevert: Mock up the design for this error message https://xd.adobe.com/view/8b74c769-0d5e-45fd-567a-d07de46198dc-fd45/?fullscreen

### How to replicate
1. Install a browser plugin like [Privacy Badger](https://chrome.google.com/webstore/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp?hl=en-US)
2. Navigate to the [CPRC form](https://janis-3792-badger-block.netlify.com/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyNzc1)
3. You might have to adjust the privacy slider to block the Formstack iFrame
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/2795079c-0824-418c-890a-cbe8f89480d8)
4. Then, try loading the [CPRC form](https://janis-3792-badger-block.netlify.com/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyNzc1) again, and you'll see this
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/7d0178e2-1264-49bf-b9fd-43e9ee0216f9)

**Comment by chasechenevert** [comment]
Got a quick sketch up to start the conversation sooner: https://xd.adobe.com/view/8b74c769-0d5e-45fd-567a-d07de46198dc-fd45/?fullscreen

I don't have a way to repeat the wheel animation for a set period of time, so go ahead and click on the wheel, or press the forward key on your keyboard to advance to the message block

**Thoughts**
- should we animate the entrance of the message?
- in terms of the type, i'm just using the basic typesetting pattern that we have (H2 for the heading, then H3s for the sections below to make tabbing possible)
- does the order of the info feel right? want to make sure that we don't inadvertently serve the form link below the viewport (especially on mobile). 
  - one option is to list the form link below the heading to make sure that it's optimally visible

**Comment by chasechenevert** [comment]
Capturing some quick feedback from @toribr 
- Can we make it look/feel more "alerty"?
- Type sizes could maybe come down
- Change the title from a statement to a question to draw the user in

**Comment by Jo-Dwyer** [comment]
### We are still waiting for your form to load ###

[Open the form in a new window](https://cityofaustin.formstack.com/forms/cprc_application)

#### Why hasn't it loaded yet? ####

- A plugin could be blocking the form (for example a privacy app like Privacy Badger)
- It may have failed to load ("404 error")

**Comment by Jo-Dwyer** [comment]
@desigonz et al., does the copy I wrote give you enough to move forward and close the issue?

**Comment by desigonz** [comment]
@chasechenevert Can you close this one you've updated the mocks?

**Comment by chasechenevert** [comment]
Update incorporating feedback:
https://xd.adobe.com/view/76025448-36e1-49b0-7dfc-cbbbb6e92c38-0033/screen/b8627cb5-6ae8-4ba9-90ea-0d464680b336/Form-fallback-Message-Desktop

- added an additional page of a few iterations of the message styling
- changed a few things to help the message be more easily identified: blue left border, info icon, subtle drop-shadow
- open in new window icon for the form link. in the material icon font it's titled "open_in_new"

![image](https://user-images.githubusercontent.com/7027270/73577039-87323900-4441-11ea-92d2-a0b68c3752cf.png)

![Screen Shot 2020-01-31 at 3 46 27 PM](https://user-images.githubusercontent.com/7027270/73576978-5e11a880-4441-11ea-8f75-53c6e5b67c4f.png)

**Comment by desigonz** [comment]
Okay, thanks @chasechenevert! We're going to push this version into prod for the immediate need, but I've assigned myself to turn this into acceptance criteria for the future.

![image](https://user-images.githubusercontent.com/5839508/73580519-77b7ed80-444b-11ea-9465-7c7be002ccf8.png)

**Comment by desigonz** [comment]
Logged this in #3967
