### ISSUE TITLE
Create content modal for events—designs

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3873]
We missed this when sending over acceptance criteria and mocks to dev.

- [ ] Need an icon
- [ ] Where does it go within the create content modal hierarchy?
- [ ] Need content for the following (numbers correspond to screenshots)
1. Content type title
2. Content type short description
3. Need a title for the write a title screen
4. Bullet points on the write a title screen

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/79d59bbc-47f6-46e7-9b2f-e5d4716127b4)
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/e055ad50-ef64-45e6-9b4f-1bb758b5e7aa)

**Comment by toribr** [comment]
@ablangworthy27 If you could review these two screens for microcopy changes, please, as soon as possible, thanks.
https://xd.adobe.com/view/adbc711d-5f10-4adc-6aa5-f72c08ee5572-db8d/screen/cd50e991-1175-491d-a78c-92d194b32f0f/create-event
@desigonz

**Comment by desigonz** [comment]
I know @ablangworthy27 is swamped with the OPO stuff right now, so assigning Jo and Sarah as well. Can y'all determine who can review this? Early next week would be great, so we can send to dev for sprint 50.

**Comment by Jo-Dwyer** [comment]
@toribr I left minor changes in the XD comments.

**Comment by toribr** [comment]
Updated: https://xd.adobe.com/view/adbc711d-5f10-4adc-6aa5-f72c08ee5572-db8d/
![event graphic](https://user-images.githubusercontent.com/3790067/73565393-10884200-4427-11ea-9bba-49362127d811.png)

**Comment by briaguya** [comment]
deploying update to https://joplin-pr-3814-events-non-joyo.herokuapp.com/admin/ right now

**Comment by desigonz** [comment]
Thanks! Looks like @briaguya's changes made it into prod. But one thing I want to verify with @toribr before closing this issue: where in the hierarchy should "event" go? In the mocks, it looks like it replaces department. Should we drop department lower down?

We can also post-MVP all of this and wait for analytics/research to help inform.

![image](https://user-images.githubusercontent.com/5839508/73664444-09e70e00-4665-11ea-9fce-42b85a09b63c.png)

**Comment by toribr** [comment]
Re: order. In my head, this would be smart and sort according to most used in this department. Eventually, we might need a 'search' field at the top as well. Also, eventually, this list could be constrained per department, or per user, even. For now it makes sense for least used to fall to the bottom, so department and official document list might be good candidates for this. 

We also could explore a different view, where the tiling is more compact. Frankly, I didn't think we'd get to this problem so quickly. :)

**Comment by desigonz** [comment]
Let's set up analytics on Joplin (#3736) and use that to inform decisions (in tandem with things like author's mental model on D8).
