### ISSUE TITLE
Event fees on Joplin

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3874]
### QA notes
1. Go here: http://joplin-pr-3874-hide-fees.herokuapp.com/admin/pages/362/edit/#tab-content
2. See fees are hidden
3. Play with event is free checkbox and watch fees show/hide

PR: https://github.com/cityofaustin/joplin/pull/569

### As a event author, I want to have to either enter fees or mark an event as "free", so that residents get the right information about fees for an event.

Adding a fee on an event page looks like this
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/be69f048-bf1e-4427-9f54-ea6be94f6139)

But what happens when both "free" and "fees" are entered? Or neither? 

Generally seems like a weird user experience.

An alternative is using streamfields similarly to how we used them for City vs. remote locations.

**Comment by easherma** [comment]
Sounds to me like a good case for the conditional validation I tested out on #3740 

As far as 'what happens', that would be up to design, but there are plenty of options. We could trigger validation and ask the author to _either_ check the box _or_ enter fees. We could also use Javascript to hide the fees section if they check the free box. Either way, there are lots of ways to handle this without moving it into a Streamfield, though that could be an option too.

**Comment by desigonz** [comment]
@briaguya @desigonz and @toribr to chat about this next sprint!

**Comment by briaguya** [comment]
@desigonz doing this with streamfields probably doesn't get us what we want here, as we'd still need to write out custom logic to only allow for one or the other.


My preference for course of action on this one is:
1. Add some custom JS to hide the fees when "free" is checked (probably a 2 or 3)
2. Eventually update from checkboxes to be a toggle/switch https://github.com/cityofaustin/techstack/issues/3790

**Comment by desigonz** [comment]
Awesome, thanks @briaguya! cc @toribr on the above

**Comment by desigonz** [comment]
Want to make sure the JS isn't too jumpy

Next steps:
- Implement step 1 above
- Review with @toribr re: user experience for MVP

**Comment by briaguya** [comment]
@desigonz giving this a 3, it might end up being smaller than that but I'm not sure.

**Comment by easherma** [comment]
Stuff to use/steal/be inspired by: https://github.com/davidcondenl/wagtailuiplus#usage

**Comment by desigonz** [comment]
Thanks @briaguya! This looks great to me for MVP. @toribr, assigning you to take a look. 

@briaguya Any chance any regressions might be introduced? Do we need/want to test what this means for Janis?

**Comment by toribr** [comment]
I think that's workable for now. <soapbox>I'm still going to advocate for a radio button as this method obscures content and choices, which is bad for usability. Users understand things better when they have a comparison, so hiding the fee table is not ideal. </soapbox>

**Comment by desigonz** [comment]
Sounds good. We have the radio button in the backlog, so for MVP, QA has passed.

**Comment by briaguya** [comment]
@desigonz this doesn't change anything that's exposed to Janis, it's just hiding things in the Joplin UI.

 The logic in Janis (https://github.com/cityofaustin/janis/blob/e9aa0b5a8efce97be40f900fed3b13e80ecd85e9/src/components/Pages/Event/EventDetailCard/EventDetailFees.js#L22) is to **only** show fees if we do **not** have "event is free" checked, so even if there are fees still saved on the event, if it's marked as free it will show up as free

**Comment by desigonz** [comment]
Sounds good!

**Comment by briaguya** [comment]
@desigonz this is working on staging now
