### ISSUE TITLE
Not able to preview a form container from the content page.

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3879]
## Describe the bug
Formstack form works, published the form container without topic or topic collection—clicking "Live" yields a 404. Only opening edit, then previewing there allows me to see the preview.

https://alpha.austin.gov/en/request-judicial-information
vs
https://alpha.austin.gov/en/preview/form/UGFnZVJldmlzaW9uTm9kZTozMTU0

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to content list
2. Click on "Live" at the right side
3. See error

## Current behavior
A clear and concise description of what happened

## Expected behavior
I expect to see a preview, or at least be able to preview a page without having to create a new draft (which seems like it's the only way to see a page)

**Comment by desigonz** [comment]
The page won't build if it's not assigned to either a topic or a department. 

I'm able to see the form in the preview page.
