### ISSUE TITLE
Build fail for OPO reports and recommendations page

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#3880]
### When did this happen?
At 11:31am (austin time)

### Where did this happen?
- [x] Production
- [ ] Staging
- [ ] On a branch: *list the branch here*

### What were you trying to do when this happened?
I was trying to publish changes on the OPO official reports and recommendations page.  I had uploaded a new document with a summary and wanted it to go live. 

It is worth noting that the preview of this update did not look right. 
-The new document showing up below the older document
-The feedback pop-up is below each document, so it is showing up twice

### Screenshots
![Screen Shot 2020-01-30 at 11.44.48 AM.png](https://images.zenhubusercontent.com/5d6e8f01caef900001337734/cb55c5fa-482c-4893-b5c6-4658ae560a1c)

**Comment by easherma** [comment]
( just an fyi It would be super helpful to paste the URL of the log thats in the notification above in addition to a screenshot)
