### ISSUE TITLE
Incorporate edits from stakeholders

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#3882]
Now that we've had a meeting, untangled some confusing bits of information, and set up a plan of action for moving forward, I can reasonably expect to be able to start incorporating edits on February 13th. The goal is to have everything incorporated by February 20.

**Comment by desigonz** [comment]
Is this the same as #3830?

**Comment by ablangworthy27** [comment]
- [ ] Follow up with missing perspectives
- [ ] Follow up on any remaining confusion
- [ ] Incorporate edits into word doc
- [ ] Incorporate edits into Joplin

**Comment by ablangworthy27** [comment]
I'm going to wait on Joplin edits because I have new feedback coming down the pipe.
