### ISSUE TITLE
Investigate our AWS build logs and their public access

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#3886]
## Describe the bug
Some of the links in the janis-builds Slack channel do not open for me (chia)
https://s3.amazonaws.com/janis-austin-gov-production/_reserved/logs/669c2698f9a23475d1a0d6914c1715c35f7ee90c686354e4774479d637562590.txt
https://s3.amazonaws.com/janis-austin-gov-production/_reserved/logs/8f871d1dfebe0f8afdadbc1e1b6d8361451fe896cba3ceabd655e7c8288e4939.txt
I get an access denied response. However, a subsequent link worked
https://s3.amazonaws.com/janis-austin-gov-production/_reserved/logs/29e52f9ae50d2dcc24e1f930eff21eed6e208297305110a3ccf571be9df37bcd.txt

Original thought was that I had to be logged in to AWS to see the links. Logging in did not fix the first two links. 

Also, is there a way to to prevent non-logged in people from seeing the logs? What are the pros/cons if we can. 

## To Reproduce
Steps to reproduce the behavior 
example: 

## Current behavior
a build failed, I tried to see the logs and it says access denied. 

## Expected behavior
I expect to be able to read our logs. Especially when a build fails, id like to see why. 

## Additional context

```
janis-buildsAPP  11:31 AM
PRODUCTION -- Thu Jan 30 17:31:59 UTC 2020 8f871d -- <class 'base.models.official_documents_page.OfficialDocumentPage'> 'Police oversight reports and recommendations' was edited by user: amanda.langworthy@austintexas.gov

11:31
PRODUCTION -- Thu Jan 30 17:31:59 UTC 2020 8f871d -- :coffee: We've received a request to build janis. Take a cup of coffee, you will be notified whenever it's done.

janis-buildsAPP  11:38 AM
PRODUCTION -- Thu Jan 30 17:38:29 UTC 2020 8f871d -- :x: There was a problem building janis. Check the logs for details. https://s3.amazonaws.com/janis-austin-gov-production/_reserved/logs/8f871d1dfebe0f8afdadbc1e1b6d8361451fe896cba3ceabd655e7c8288e4939.txt
```

**Comment by easherma** [comment]
@chiaberry feel free to re-open, but IIRC you just needed to re log in to AWS

**Comment by chiaberry** [comment]
@easherma except @Jo-Dwyer can view logs and doesnt have an AWS login
