### ISSUE TITLE
Conditional logic in CPRC form

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3887]
## Describe the bug
When filling out the CPRC application, if you answer `Yes` to "Do you or have you served on any City of Austin boards and commissions?" and `Yes` to "If you are currently serving on a commission, are you willing to resign?", you will be allowed to go to the "Applicant information page," but then cannot continue to the demographic and essay questions—instead, the "continue" button on this page says "submit form."

## URL
https://alpha.austin.gov/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyOTI2

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to the [CPRC form](https://alpha.austin.gov/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyOTI2)
2. Answer the first page exactly as outlined in this screenshot
![image](https://user-images.githubusercontent.com/5839508/73499504-e3378780-4385-11ea-89b7-19f53b6aab3b.png)
3. Click "continue" to start the application page
![image](https://user-images.githubusercontent.com/5839508/73499520-eb8fc280-4385-11ea-9556-790a321a07b8.png)

## Current behavior
You see the "Submit form" button on this page and end the application process page after filling this page out.

## Expected behavior
- [ ] You see the "Continue" button and continue onto the following pages:
  - Demographics
  - More information I
  - More information II

I believe what's happening here is related to conditional logic. On the "Applicant information" page, all the fields appear if you previously said `No` to serving on commissions OR if you said `Yes` to willingness to resign from a commission:

![image](https://user-images.githubusercontent.com/5839508/73499799-afa92d00-4386-11ea-85b8-d73b32f39e96.png)

However, doesn't look like that distinction was applied to the other pages:
![image](https://user-images.githubusercontent.com/5839508/73499834-ca7ba180-4386-11ea-9c72-c894e5e0aaa2.png)

## Screenshots
See above

**Comment by desigonz** [comment]
@ablangworthy27 I think I figured it out. I made a [copy of the form](https://cityofaustin.formstack.com/forms/cprc_application_desis_copy) to test out the logic. 

For all of the following pages:
- Demographics
- More information I
- More information II

I deleted the conditional logic question for "Do you or have you served on any City of Austin boards and commissions?" 

![image](https://user-images.githubusercontent.com/5839508/73500460-5215e000-4388-11ea-81d9-fc63188f9a8c.png)

Can you gut check this by testing in on that copy form link above? And then if that looks good I'm going to let you edit this in the actual form because I don't want to break anything 🙃

**Comment by ablangworthy27** [comment]
Yes! This works.
