### ISSUE TITLE
Service page loads forever

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3888]
## Describe the bug
I clicked a preview link for a service page draft and the page "loaded" forever. No 404. No time out. Just "loading".

[Get tested...](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxODY1)

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to content list in Joplin.
2. Search for 'Get tested for sexually transmitted diseases'
3. Click on 'Draft' to see the preview

## Current behavior
A clear and concise description of what happened: clicked the link, said it was loading. never loaded, never timed out.

## Expected behavior
Load successfully or timeout and give me an error. 

## Screenshots
![Screen Shot 2020-01-30 at 5.47.48 PM.png](https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/a1650d41-99af-4a87-919e-fcedd81c7d1c)

**Comment by easherma** [comment]
With this issue, the page didn't have a topic and had a map block added but not selected. I corrected both of those errors and it now previews correctly.
