### ISSUE TITLE
Error message when submitting the OPO commission form

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3893]
I attached a .txt file to the resume uploader and got this error message: 

ERROR: Please return and fill out the following required fields: 
- Resume

I didn't get a confirmation email, either. 

|Property | Value|
|------------ | -------------|
| Browser | Chrome 79.0 |
| Operating System | Windows 10 |
| Resolution | 1920x960 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/44c1fa1c5f43536d37cd83a75d01f03508899ccc/win10_chrome_79.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/44c1fa1c5f43536d37cd83a75d01f03508899ccc/win10_chrome_79.0.jpg)

**Comment by srigdon** [comment]
I also clicked the back button to see if it would save and it kicked me back to the first page of the form. The first question I answered was saved but no other answers were.

**Comment by desigonz** [comment]
Wasn't able to replicate this. I was able to submit a .txt file, but was not able to submit an .rtf file.
