### ISSUE TITLE
Draft the community service timesheet form

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3895]
This form must be printable due to current usage by defendants and community service supervisors. Formstack does not support printed forms. This must be drafted as a PDF. 
- [ ] get design template for PDFs from @chasechenevert  or maybe @desigonz 
- [ ] using feedback from form workshop draft the form
- [ ] submit to @toribr for design review
- [ ] submit to @ablangworthy27 or @srigdon for content review
- [ ] submit to Amy Schillerstrom for approval
- [ ] create resulting issues

**Comment by sammodabber** [comment]
@Jo-Dwyer Does this need to go into formstack if the process primarily involves a printed PDF?
