### ISSUE TITLE
Localize location information links

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3896]
From this comment: https://github.com/cityofaustin/techstack/issues/3815#issuecomment-580521342

- [x] Need to translate "Location information" bar: Localización
  - [x] Department pages
  - [x] Event pages

**Comment by desigonz** [comment]
![image](https://user-images.githubusercontent.com/5839508/74570686-6f2edf00-4f42-11ea-8de9-43e46cc4faa4.png)

**Comment by chiaberry** [comment]
for QA: https://janis-3896-localizacion.netlify.com/es/municipal-court
https://janis-3896-localizacion.netlify.com/es/event/2020/3/2/create-an-event-in-staging/

**Comment by desigonz** [comment]
Looks great! qa passed.
