### ISSUE TITLE
Broken builds with top level pages

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3899]
## Describe the bug
ContexualNav errors with top level service pages

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go Joplin
2. Make a service page a top page `serve-on-the-community-police-review-commission` is a good example
3. Make it a top level page (check the box at the bottom)
4. Watch a build break!

## Current behavior
A clear and concise description of what happened

## Expected behavior
A clear and concise description of what you expected to happen

**Comment by desigonz** [comment]
Do you think it broke because that page was already assigned to elsewhere in the IA—in this case, a department?

**Comment by briaguya** [comment]
I think it broke because we only ever set up information pages to work as top level pages, as our test case was privacy policy.

**Comment by desigonz** [comment]
I'm interested to know the size on various possible solutions for this (setting up top-level for service pages, or just removing top-level as an option on service pages). In #3313, we limited top-level pages to service and info pages, but so far have only used info pages for top-level things.

**Comment by briaguya** [comment]
@desigonz 

options:
* Remove top level for service pages: probably a 3
* Fix contextualnav on service pages to support top level service pages: probably a 1 or a 2

**Comment by chiaberry** [comment]
@desigonz & @briaguya I can't get the build to fail running locally, but I have a question about the options. 
- remove top level for service pages -- if its like what I did on issue 3313, then I'd give it a 2
- fix contextual nav, I dont understand what this is describing 😳

**Comment by briaguya** [comment]
@chiaberry I think it's because we're trying to use the contextualNav object [here](https://github.com/cityofaustin/janis/blob/5967fdfc57d5acd7c25bd10ea5c6113a9debc27e/src/components/Pages/Service.js#L112) but it doesn't exist so we need to check for coaGlobal there like we do [up here](https://github.com/cityofaustin/janis/blob/5967fdfc57d5acd7c25bd10ea5c6113a9debc27e/src/components/Pages/Service.js#L47)

**Comment by chiaberry** [comment]
@desigonz  ready for testing, https://joplin-pr-3899-broken-build.herokuapp.com/
which is linked to the janis https://janis-3899-broken-build.netlify.com/

(https://janis-3899-broken-build.netlify.com/en/serve-on-the-community-police-review-commission/ is the service page that is now a top page)

Here are the logs in netlify. https://app.netlify.com/sites/janis-3899-broken-build/deploys 

The way I tested it was by trying to make builds and then seeing if they worked with what changes I made. Checking the logs you can see it kept failing until my last change. If you'd like, we can QA together (alone together, hello sherry turkle), or you can make changes in joplin and we can see that the site updates?

**Comment by desigonz** [comment]
Okay, I made [Look up your trash, recycling, and compost pickup days](https://joplin-pr-3899-broken-build.herokuapp.com/admin/pages/14/edit/) a top-level page. 

(Also: I love a good Shturkle reference!)

**Comment by chiaberry** [comment]
https://janis-3899-broken-build.netlify.com/en/trash-recycling-pickup/ there it is! top page

**Comment by desigonz** [comment]
Woohoo!! QA passed.
