### ISSUE TITLE
Conditional next steps do not display on pixel 3/chrome

### ISSUE THREAD

**Issue by wilhitem** [cityofaustin/techstack#3900]
## Describe the bug
Happening on my pixel 3 in chrome browser. 
When utilizing the form to apply for the  community police commission, the conditional logic is not causing the page objects to display. (click no on first required question, should have a pop up of next question/etc. 

This appears to work fine on the iPhone w/ chrome and my desktop.

## URL
https://alpha.austin.gov/en/police-oversight/apply-to-the-community-police-review-commission/

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to https://alpha.austin.gov/en/police-oversight/apply-to-the-community-police-review-commission/
2. Click on 'no' under 'Do you currently hold public office?'

Alt:
2. Click on 'yes' under 'Do you currently hold public office?'

## Current behavior
click 'no' or 'yes' or 'save and submit later'

## Expected behavior
With each of the buttons, the page should react
Click no -> next qualifying question should appear
Click yes-> message 'Sorry. This disqualifies you from applying.' appears
Click 'save and submit later'->Save pop up starts the process

## Screenshots
![Screenshot_20200202-090233.png](https://images.zenhubusercontent.com/5a971d9c4b5806bc2bc8db22/d526e21c-da49-44cc-aa3b-653a4438c6c9)

## Device and browser
Andriod 9; Pixel 3
Chrome v79.0.345.136

## Additional context
The user is unable to apply for the commission from an android device

**Comment by desigonz** [comment]
This is fixed, closing the issue!
