### ISSUE TITLE
Future Feature: More user-friendly fee tables

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#3905]
### As a content author I want the ability to add fee tables more seamlessly so that creating new tables and updating them on a regular basis is easy.

****This is sort of related to [issue #3275](https://github.com/cityofaustin/techstack/issues/3275)****

**Is your feature request related to a problem? Please describe.**
For the pools guide, there are multiple points where a resident will need to pay a fee. The fee amount will be different for each resident and is dependent upon multiple factors (their particular pool setup and their location, for example). 

Currently, I am copy/pasting a </> fee table from another page and that is not ideal. If I have these fee tables in several places within a guide, that means there is a not so user-friendly process that a future APH author will have to go through to update the fees multiple times. 

**Describe the solution you'd like**
There are a couple of ideas that have been discussed in content cove, and I actually think they both have their value. The first is to develop a content type that can be linked to from a service page or pulled into the service page directly (like a snippet?). This would be really cool because then the author would only have to update in one place.

the second, and probably MVP solution, is to create a functionality with service pages on Joplin, that allows a user to add and customize a fee table inside a step. Kind of like the map or recollect blocks, but it would need to be something that we could add in the step itself.

**Comment by desigonz** [comment]
We actually have a backlog issue for this! #2333. Will copy/paste your thoughts over there, and close this one.
