### ISSUE TITLE
Upgrade Wagtail 2.8

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3912]
2.8 gives us lots of goodies, including a fix for: #3561

Release notes here:
https://docs.wagtail.io/en/latest/releases/2.8.html

The general drill:

- [ ] Make a branch, update the wagtail dependency
- [ ] See if generally everything runs ok, run tests if we got them
- [ ] Go through the release notes and note upgrade considerations, things we might need to modify
- [ ] Once these are done, make sure everything works, run migrations if needed, do a new datadump
- [ ] Merge to staging, prod

**Comment by desigonz** [comment]
Starting a list here for new features we want to make sure to test:
- [ ] (add items here)

Starting a list here for things we'll want to review with the content and design teams (more like a heads up, not necessarily a test):
- [ ] Improve diffing behavior for text fields (Aliosha Padovani)
- [ ] etc

**Comment by easherma** [comment]
Can be QA'ed at: https://joplin-pr-3912-wagtail-28.herokuapp.com/

Didn't need a migration.

**Comment by desigonz** [comment]
QA passed. 

Compiling a list of things to review at Tuesday's dev-design sync:
- #3561
- Improve diffing behavior for text fields in revision history ([link](https://joplin-pr-3912-wagtail-28.herokuapp.com/admin/pages/6/revisions/compare/1523...1567/))
- Add ability to filter image index by a tag ([link](https://joplin-pr-3912-wagtail-28.herokuapp.com/admin/images/))
