### ISSUE TITLE
UX for managing expectations with the "View live"/publish delay

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3916]
### As a content publisher, I want to [_have one of the following options below_], so that I can verify that my content has published correctly and I understand what users are seeing on the website right now.
- **Ideally**: be able to view my changes on a live page immediately after publishing
  - As a content publisher, my mental model from using other author interfaces is that changes publish out immediately
- **MVP**: have something that manages my expectations about how long it will take for a page to publish
  - For example, and this is only an idea: where `view live` button is in Joplin, if a page was published less than X minutes ago, have some sort of notification that says "It takes up to X minutes for your changes to appear. Check back later."
  - Context: Near-instantaneous builds are going to take a while to get to. Let’s design an interim solution.

**Acceptance criteria**
- [ ] Designs for how to manage user expectations within Joplin

-------
### Background
- [Original bug report](https://github.com/cityofaustin/techstack/issues/2872)
- [Notes from dev-design sync from 1/28/2020](https://github.com/cityofaustin/techstack/issues/3819#issuecomment-578960294)
- [Notes from design pin-up from 2/25/2020](https://docs.google.com/document/d/1eE0e4PbuXM0iXxJkGAe7BBw89kwA7pNNPU1_Dnn8avE/edit#)

**Comment by desigonz** [comment]
Nick is building out a queueing system for publisher. 

`View draft` `View live` `This page is still publishing` `This page is done publishing`
Publishing queue: see what's being published. Put a UI on the queueing system.
If page was published less than 5 minutes ago, link to that.
Link to the latest preview
What happens to the list view? Should be from everywhere in Joplin.

Four states when published a page:
- just updated (queue)
- confirmed in progress (building)
- finished (in UI, return to normal state—`View live`)
- build failed

**Comment by desigonz** [comment]
Might want to do usability testing on this one. Thoughts from @toribr:
- Probably not a ton of risk
- On the fence about it

**Comment by desigonz** [comment]
For sprint 50:
- [ ] Work out some designs
- [ ] Decide if we want to test it—but we'll need to be testing something that can actually be implemented. Will need to do a really thorough review with dev before we test.

**Comment by chasechenevert** [comment]
I made a collection for the (master) screens and components related to the issue in Abstract: 
https://share.goabstract.com/10a9e4fa-4f77-4119-aa18-662d69e07aa2?

**Comment by desigonz** [comment]
@chasechenevert @toribr is this issue OK to close? Or move to sprint 52?

**Comment by chasechenevert** [comment]
Since the specs were handed over I think we can close this one. When we have updates from user testing we'll just generate a new issue.
