### ISSUE TITLE
Adding, editing, and deleting departments

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3919]
Mocks: https://xd.adobe.com/view/1b86b869-7cf8-4623-6479-16bc0a8e09e7-6db7/

### Acceptance criteria
- [x] Only administrators see and have access to this
- [x] "Departments" appears as an option in the left nav
- [x] "Add department" button in the top right follows patterns for other snippets
- [ ] All departments appear in listing view, follows patterns for other snippets
- [ ] For each listing:
  - [ ] Indicate number of users assigned to a department
  - [ ] Last login includes username with login timestamp
- [ ] A user can only delete if there are 0 users in the department
  - [ ] If an administrator clicks the "delete" button and there are 1 or more users in that department, need error validation (@Niicck, is there a pattern for this that already exists?)

**Comment by easherma** [comment]
All of these could be fairly easily covered by adding a snippet (did we nuke our departments snippet already? zombie model...)

*except*
>For each listing:
    Indicate number of users assigned to a department
    Last login includes username with login timestamp

That would require a custom list view, which would make the model best served by a ModelAdmin. 

So for everything else this is like a **1**, adding the custom interface listing would be a **5**. 

However, we could make this as a snippet first, then later convert it's admin interface to a ModelAdmin later by dropping the snippet decorator and then building out the modelAdmin interface (which Wagtail has lots of tools for), so that criteria could get moved into it's own subsequent issue.

**Comment by desigonz** [comment]
We will split some of this acceptance criteria in a separate issue— @briaguya and @desigonz to touch base when he sends MVP stuff to @desigonz to QA.

**Comment by briaguya** [comment]
## Acceptance criteria testing I've done
### Only administrators see and have access to this
1. Logged in to https://joplin-pr-3813-department-grou.herokuapp.com/admin/login/ as admin@austintexas.io
2. Navigated to my personal (brian.smith@austintexas.gov) user (https://joplin-pr-3813-department-grou.herokuapp.com/admin/users/10/) and unchecked administrator on the roles tab
3. Saved and logged out, logged in as brian.smith@austintexas.gov
4. Didn't see departments in the left nav

### "Departments" appears as an option in the left nav
1. Logged in to https://joplin-pr-3813-department-grou.herokuapp.com/admin/login/ as admin@austintexas.io
2. Saw departments in the left nav

@desigonz I put a 2 on this so far, would it be possible to split out the rest of the exit criteria into a couple issues for list/edit view UX? If so I can keep the 2 on here and make another 2 or 3 for list view and another 2 or 3 for deletion criteria (I figure the default behavior might be alright but we should figure out the edge cases by playing around with it)

**Comment by desigonz** [comment]
Split out the rest of the requirements as post-MVP (#4045). The rest is looped into the PR branch associated with #3813. More notes in this document: https://docs.google.com/document/d/1FY-enbU7mTFXR8vX2rG7FqnySRqsAFoB8Op1f_--v14/edit# Closing this issue!
