### ISSUE TITLE
Get Permittingatx analytics

### ISSUE THREAD

**Issue by courtneyjacinic** [cityofaustin/techstack#392]
Reach out to Rachel Crist to get access to the analytics for permittingatx to better inform the IA on alpha as we transition.

**Comment by LauraTrujillo** [comment]
![permittingatx analytics](https://user-images.githubusercontent.com/30263897/48568389-e2235300-e8c4-11e8-85da-5d444d234fbd.png)
![permittingatx analytics2](https://user-images.githubusercontent.com/30263897/48568594-607ff500-e8c5-11e8-8f1c-75102b1b04da.png)
