### ISSUE TITLE
Adding users to department—functionality

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3920]
Mocks: https://xd.adobe.com/view/1b86b869-7cf8-4623-6479-16bc0a8e09e7-6db7/

### Acceptance criteria
- [x] Only administrators see and have access to this
- [x] On the "roles" page under "users", an administrator can select a department from the department permissions model
  - [ ] For MVP, on the Joplin UI side of things, only allow an administrator to select 1 department per user

I think ultimately the logic we'd like is:
- If the user being added is **not** assigned the administrator role (in other words, is a moderator or editor), they **must** belong to a department. @Niicck I'd be interested to get your thoughts on how to break this down into different issues based on how we described the breakdown of issues on Tuesday! We could also take baby steps where we don't have this requirement yet, but want to make sure it doesn't break things.

**Comment by easherma** [comment]
@desigonz would love to flesh out the first criteria:
Does access mean visibility? Or would we want users to see what department they belong to but not edit the field?

**Comment by desigonz** [comment]
We will split some of this acceptance criteria in a separate issue— @briaguya and @desigonz to touch base when he sends MVP stuff to @desigonz to QA.

**Comment by briaguya** [comment]
## Acceptance criteria testing I've done
### Only administrators see and have access to this
1. Logged in to https://joplin-pr-3813-department-grou.herokuapp.com/admin/login/ as admin@austintexas.io
2. Navigated to my personal (brian.smith@austintexas.gov) user (https://joplin-pr-3813-department-grou.herokuapp.com/admin/users/10/) and unchecked administrator on the roles tab
3. Saved and logged out, logged in as brian.smith@austintexas.gov
4. Saw the users list page is read only

### On the "roles" page under "users", an administrator can select a department from the department permissions model
1. Logged in to https://joplin-pr-3813-department-grou.herokuapp.com/admin/login/ as admin@austintexas.io
2. Navigated to my personal (brian.smith@austintexas.gov) user (https://joplin-pr-3813-department-grou.herokuapp.com/admin/users/10/)
3. Saw checkboxes for each department

@desigonz I'd like to discuss the "only allow an administrator to select 1 department per user" requirement, as that will definitely add complexity.

**Comment by desigonz** [comment]
For now, we've decided _not_ to limit to one department for user. We want to revisit that experience as we start to onboard more editors and moderators.

The rest of the acceptance criteria is looped into the PR branch associated with #3813. More notes in this document: https://docs.google.com/document/d/1FY-enbU7mTFXR8vX2rG7FqnySRqsAFoB8Op1f_--v14/edit# Closing this issue!
