### ISSUE TITLE
make entire "Start" button clickable

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3921]
## QA
PR: https://github.com/cityofaustin/janis/pull/707
PR app: https://janis-3921-clickable-buttons.netlify.com/

### To test
1. Go here: https://janis-3921-clickable-buttons.netlify.com//en/government-business/business-resources-3/workforce-development-and-hiring/hire-a-day-laborer/
2. Expand "online" option in step 3
3. Notice entire "start" button is an 'a' element

## Issue
The start button on service page steps only has the text as clickable instead of the whole button

# Previous description
"Start" button to access form container not immediately responsive

## Describe the bug
Tried out the link on service page "hire a day laborer" to access the live "request a day laborer" form container. The button was not responsive on first click, but second click.

[Hire a day laborer](https://alpha.austin.gov/en/government-business/business-resources-3/workforce-development-and-hiring/hire-a-day-laborer/)

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to 'Hire a day laborer'
2. Click on 'Online' and then 'Start'
3. See error

## Current behavior
Responds after two clicks

## Expected behavior
I expected it to respond on the first click

**Comment by desigonz** [comment]
I feel like this has happened to me too, but I can't currently replicate.

**Comment by chiaberry** [comment]
The link is only the word, so if you click the button but not exactly on the word, it does nothing. 
Do you think on the first click it was outside of the text, but the second click was on the text? If i keep clicking outside of the text (but on the button) it does nothing until I click the text. 

The fix is to make the link go the width of the whole button.

**Comment by desigonz** [comment]
Thanks @chiaberry! Putting this one on deck.

**Comment by desigonz** [comment]
Looks great @briaguya! QA passed.
