### ISSUE TITLE
Joplin UI: type and color strategy

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3922]
## As a city author, I need the authoring experience to have a logical visual hierarchy so that I am better able to understand the interface.

@chasechenevert's Google doc: https://docs.google.com/document/d/1SdAro51Ppdi3Hirn1XkVviJ6nu89dDXtvvFKIX4T8t8/edit#heading=h.ff2tre8z4na1
and the prototype: https://xd.adobe.com/view/196b8e14-f966-4033-7a7d-53b9c188ca17-6f5a/?fullscreen

0. Refactor style things—to match Janis (a lot of housekeeping)
1. Work through the Google doc check list
2. Pair with design team as we're implementing to adjust accordingly

Sprint 50 goal:
- Work on step 0—start reorganizing, using the designs to work from there.
- Get feedback from the team
- By end of sprint, we'll have decided a direction to go

Related PR: https://github.com/cityofaustin/joplin/pull/561

**Comment by robbobfrh84** [comment]
I think a big part of this could be a *discovery* of implementing how we can best override wagtail styles.
 - Which would includes some investigation, research and testing. 

Doing that and documenting well will give us a "road map" of how we handle Joplin UI changes going forward. 

That could be added as part of this issue, or a separate issue all-together. Wrapping it up in this issue and scaling it up makes sense to me. 

Thoughts?

**Comment by easherma** [comment]
@robbobfrh84 I think that is a good point and should be part of this issue! I did estimate with that in mind, but we could increase the estimate too if you'd like. I've done a pretty good chunk of that research already, but it could definitely stand to be formalized more and we can make sure all that knowledge is shared between whoever is working on it.

**Comment by robbobfrh84** [comment]
As I've started to work through this, I've discovered that breaking the work down section-by-section has been an easier way to keep it all organized (At least in my head). 

I've with three static sections
- [ ] **Side** Nav 
- [ ] **Top** Nav 
- [ ] **Pages** Top Nav 

Then, there will inevitable be regressions (for example, changing one style can mess up another).
- [ ] Clean up regression (gonna need to be a thorough manual search I'm afraid)

<img width="484" alt="Screen Shot 2020-02-13 at 5 24 12 PM" src="https://user-images.githubusercontent.com/15821138/74487697-c9b63580-4e85-11ea-820c-30a4db1beedd.png">

... Sorry for the bad handwriting, BUT, it's really clear it isn't part of the actual design.

**Comment by desigonz** [comment]
🙌 This is amazing. Let us know if you need support in spotting those regressions.

**Comment by desigonz** [comment]
@robbobfrh84 to create an issue for what he's working on right now and assign to sprint 51, then close this issue

**Comment by robbobfrh84** [comment]
@desi, After sprint planning, i think we said this was close-able? ? -> Due to my current work is related to https://github.com/cityofaustin/techstack/issues/4016

**Comment by desigonz** [comment]
yep! closing now
