### ISSUE TITLE
Error states for save/publish requirements

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3926]
We now have some pretty cool logic for what's required for saving and what's required for publishing! Now let's improve those error states.

- [ ] Define everywhere we need the error messaging
- [ ] Review error messaging
- [ ] Review asterisks—when should they happen? Currently just for required for save, #3829 said we wanted to do it for required for publish
- [ ] Propose designs

**Comment by toribr** [comment]
- [ ] Add required asterisk to all fields required for publishing
- [ ] Get error message (from content) per required field for all components
- [ ] Design: error styling per component
- [ ] Design: page-level error messaging

Behavior: Requirements for any required fields for publishing are shown on page. 
• If user clicks "save as draft", then no error messaging is returned. 
• If user clicks "publish" and some required fields are missing, then page with error message and error message/design for each required component is returned. 
• In the rare case that user attempt to save as draft without a title, then behavior remains the same as current implementation, ie, the field shows error, but if user backs out without change, then previous title is used.

**Comment by toribr** [comment]
For my component reference
<img width="227" alt="Screen Shot 2020-02-10 at 11 06 57 AM" src="https://user-images.githubusercontent.com/3790067/74176102-a7f64d80-4bfc-11ea-89de-6a7083218b3a.png">

**Comment by toribr** [comment]
![IMG_0401](https://user-images.githubusercontent.com/3790067/74275031-c5004e80-4cd8-11ea-94c1-a9a4baeb5bb4.jpg)

**Comment by desigonz** [comment]
Hey @toribr—if you need a content strategist to work on the error copy, @ablangworthy27's available this sprint.

**Comment by toribr** [comment]
@desigonz Do we feel good about the model that outlines which fields are required? And can you help me find it? :)

**Comment by desigonz** [comment]
The requirements are here: https://github.com/cityofaustin/techstack/issues/3379
We haven't yet heard about any need to change it, so let's stick with it!

**Comment by toribr** [comment]
@desigonz 
Actually what I meant was that if @ablangworthy27 is going to write error copy, then she's going to know what fields are required, per template. So we need to refer her to the data model doc which contains that info, and which I believe you last updated.

**Comment by chasechenevert** [comment]
https://share.goabstract.com/2217505d-e313-49b5-a420-2e889036bf8f?

**Comment by desigonz** [comment]
- [ ] Will need entrance animation for the error message
- [ ] Message should NOT fade out

**Comment by desigonz** [comment]
Assigned @ablangworthy27 to review the microcopy for publish error messaging. We need microcopy to message the fields an author needs to fill out in order for a page to publish. Full mocks live [here](https://share.goabstract.com/2217505d-e313-49b5-a420-2e889036bf8f).

- [ ] Page-level error messages
![image](https://user-images.githubusercontent.com/5839508/74786306-fac1ac00-5271-11ea-9049-b7ce9f476253.png)
- [ ] Component-level messaging—see all of the below.
### Service page
![screencapture-joplin-staging-herokuapp-admin-pages-368-edit-2020-02-18-17_05_06](https://user-images.githubusercontent.com/5839508/74785860-f8ab1d80-5270-11ea-8d38-b3617b78b7bf.png)

### Info page
![screencapture-joplin-staging-herokuapp-admin-pages-369-edit-2020-02-18-17_05_33](https://user-images.githubusercontent.com/5839508/74785874-ffd22b80-5270-11ea-9622-7f6a5dcc690c.png)

### Department
![screencapture-joplin-staging-herokuapp-admin-pages-370-edit-2020-02-18-17_07_51](https://user-images.githubusercontent.com/5839508/74785960-36a84180-5271-11ea-85a5-6ea1a902d738.png)

### Guide
![screencapture-joplin-staging-herokuapp-admin-pages-371-edit-2020-02-18-17_08_22](https://user-images.githubusercontent.com/5839508/74785984-4a53a800-5271-11ea-846e-9e2cfe48b3cb.png)

### Official documents
![screencapture-joplin-staging-herokuapp-admin-pages-373-edit-2020-02-18-17_10_10](https://user-images.githubusercontent.com/5839508/74786123-8ab32600-5271-11ea-8850-ce179fa1f4f9.png)

### Form container
![screencapture-joplin-staging-herokuapp-admin-pages-374-edit-2020-02-18-17_11_17](https://user-images.githubusercontent.com/5839508/74786193-b209f300-5271-11ea-8726-8192366bbb2e.png)

### Topics
![screencapture-joplin-staging-herokuapp-admin-pages-375-edit-2020-02-18-17_19_45](https://user-images.githubusercontent.com/5839508/74786660-e16d2f80-5272-11ea-8bf0-2b49ee856a0f.png)


### Topic collections
** note: per today's content pin-up, we're going to make it so either a THEME or a TOPIC COLLECTION is required, so write your microcopy for that use case (#3913)
![screencapture-joplin-staging-herokuapp-admin-pages-376-edit-2020-02-18-17_16_28](https://user-images.githubusercontent.com/5839508/74786472-6b68c880-5272-11ea-82b7-d0d7cafa466f.png)

**Comment by ablangworthy27** [comment]
@chasechenevert @toribr @desigonz I added notes to Abstract, but below is everything that wasn't featured there. Let me know if I missed anything!

**Info page**
A minimum of 1 topic, 1 related department, or a top-level page selection is required.
Page description is required.
Additional content is required.

**Department page**
Department description is required. 

**Guide**
Guide description is required.
A minimum of 1 topic or 1 related department is required.
A minimum of 1 section header and page is required.
A minimum of 1 contact is required.

**Official documents**
Page description is required. 
A minimum of 1 topic or 1 related department is required.
A minimum of 1 document must be selected.
	-Document date is required.
	-Document title is required.
	-Authoring office is required.
	-Document summary is required.
	-Document name is required.

**Form**
A minimum of 1 topic or 1 related department is required.
Form title is required.
Form description is required.
Formstack url is required. 

**Topics**
Topic name is required.
Topic collection is required.
A minimum of 1 top page is required

**Topic collection**
A selection of either a theme or topic collection is required. 
(Put this in both places, since these selections aren't together)

**Comment by desigonz** [comment]
Logged in issue #4000 and wow that's a big number. Closing this one
