### ISSUE TITLE
Define scope for CPRC commissions web presence 

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3927]
Let's have a meeting to hone in on the requirements for the scope of the OPO commissions work.

**Comment by desigonz** [comment]
@toribr and @srigdon, I've compiled my understand of OPO's requirements for the April deadline of the CPRC website. Let me know what I'm missing! 

---

## As a resident concerned about police oversight, I want to be able to know about what the commission is, who its members are, and what the commission is working on, so that I have a sense of what the City and civilians are doing to address policing in Austin.

- [ ] Scope of commission (pull from the Meet and Confer agreement)
- [ ] Commission by-laws
- [ ] List of commissioners and contact information
- [ ] Public commission meetings/community forums (events)
  - [ ] Enter via events content type (include agenda in the event description)
  - [ ] List all upcoming meeting dates on some part of the commission site
- [ ] Link to [Serve on the Community Police Review Commission](https://alpha.austin.gov/en/police-oversight/serve-on-the-community-police-review-commission/)
-------------
### Additional notes
- Don't need to comply with TOMA
- Won't be using the website to share secure documents to commissioners
- Website will be primarily public-facing
- Will meet with consultants the first week of March to further hone into content recommendations
- What can we do with existing content types? What's the minimal design/dev work needed to achieve our goals?
  - Maybe use a topic page to compile all of the commission-related links?
  - Information page on general scope/mission
  - Pull in all upcoming commission public meetings (events)—maybe on the topic page? Can we design this in a way that can be reused for other departments?
- Other potential **post-MVP** things:
  - [ ] Recommendations made by the commission—could probably use official doc type
  - [ ] Chief of Police responses
  - [ ] Press releases
  - [ ] Commissioner headshots and bios

**Comment by srigdon** [comment]
I added a few more [notes on content](https://docs.google.com/document/d/1GCEpQNQflrcbpizBZzzRQ5BII1S9kKDkJhvkFnlOGnc/edit#), but I'm not noticing anything big that's missing. My main question right now is where residents expect to find this information. We might need to follow up with OPO on that.

**Comment by desigonz** [comment]
Cool, thanks @srigdon! We'll continue to have the vanity URL atxpolicecommission.org. And then otherwise we'll need to determine

Per our meeting, they're okay with the "Offered by: Office of Police Oversight," at least in the near term. But we might want to give the CPRC its own landing page of sorts (maybe a topic page?).

**Comment by toribr** [comment]
@srigdon @desigonz 
My recommendation would be to gather the content or improvise content that's need for this presence, ie, content-first design. I can't really think about how to shape it until I see the actual (or nearly actual) content and volume of it. @srigdon Can you sketch a structure (happy to help), so that the board has something to look at in terms of filling in the gaps?

**Comment by srigdon** [comment]
@toribr Can do!

**Comment by desigonz** [comment]
Okay I made an epic with the requirements above: https://github.com/cityofaustin/techstack/issues/3979

And an issue for content sketching: #3980

Does this goal for sprint 51 seem reasonable?
- @srigdon to sketch content
- @desigonz and @toribr to review/give feedback
- By end of sprint, we'll have identified any design or dev work that might need to happen (let's try to keep it small, because we'll only have sprints 52 and 53 to design and implement)
