### ISSUE TITLE
New homepage vision: research and ideate

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3930]
- [x] Schedule meeting for Tuesday to review our sketches together at the new office!
- [x] 5-10 super rough sketches each, taking different points of view and including notes 
- [x] Meet to discuss our sketches and plan for the deliverables we'll work on during sprint 51

**Comment by chasechenevert** [comment]
We discussed our sketches, and we'll likely discuss next steps in grooming and tomorrow.
