### ISSUE TITLE
Don't keep datadumps in github anymore

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#3932]
### As a [developer] I want [to stop committing datadumps to github] so that [github doesn't evict us for having datadumps that are too big].

**Is your feature request related to a problem? Please describe.**
Our github repos are over 50MB. This is larger than their recommended size. There could be problems.

**Describe the solution you'd like**
We can start storing datadumps in an S3 bucket. This would also help a lot with our docker image sizes. And speed up our incremental build process.

**Describe alternatives you've considered**

**Additional context**
Make sure local development and PR builds can access S3 buckets to load datadumps. The migration-test.sh process needs to upload new datadumps to production.

**Comment by easherma** [comment]
I don't think this much of a concern.

Github has a _repo_ size limit of 100GB, with 1GB being a recommended maximum. We aren't anywhere close to even 1GB.

So I'm assuming you may have meant an individual _file_ size limit. 

For one, the 50MB limited can actually be increased on our repo settings. 

That being said, Github does have a 100MB hard limit on an individual file size, but we would run into other problems before that with even using such a large datadump. Solutions could be using Git Large File Storage, or even better we could split data dumps out by content type, which is as simple as specifying the content type model on a datadump. 

We already store backups of data in S3, and Heroku also has a process for storing backups of the database.

However, what could/probably will make sense at some point is for the datadumps in the repo to be merely representative of data in prod and not comprehensive. That way we can still use real-world data for testing and PR apps but not be bogged down by the full amount of content.

**Comment by Niicck** [comment]
Done, I think.
