### ISSUE TITLE
Unit tests for departmental permissions

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3935]
### As a Joplin developer, I want unit tests around the ability in #3780, so that I can ensure that our features don’t break when we add things in the future.

We want to make sure a departmental user can only see/publish/edit pages in their department. Let's write some unit tests.

**Comment by chiaberry** [comment]
https://github.com/wagtail/wagtail/blob/982b1d60a4b3d5b4e841f2b39e2244bcb421b091/wagtail/core/tests/test_page_permissions.py

**Comment by Niicck** [comment]
Every issue is going to do its own unit tests.
