### ISSUE TITLE
Janis URL structure

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#394]
Our current url structure on Janis is heavily determined by react-static routing needs instead of user needs.  
- Explore which url structure is best for a user. 
- Explore technical requirements for updating url structure.

Ex.
/Topics/adopt-a-pet
vs 
/Themes/pets/Topics/adopt-a-pet
vs
/pets/adopt-a-pet

**Comment by amenity** [comment]
duplicate
