### ISSUE TITLE
Design process task: Create a list of new content tasks, in order

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#3944]
Step one of a more robust documentation, generate a list of all possible steps design takes in the creation of new content (based on the sticky board created).

**Comment by toribr** [comment]
https://docs.google.com/document/d/1gadkzI3Gqs9xdR8mG1smfNs3V7OTIMkxhOJL3clbjt4/edit

**Comment by chasechenevert** [comment]
- [Process / [Template] / Overview](https://docs.google.com/document/d/1yLPo8nQeQR8NZBkm4S7FOfb6KGfmdFuK3MPqZd4kV08/edit#heading=h.85y9kyo6v9om)
- [Process / [Template] / User experience and visual design research](https://docs.google.com/document/d/1_9yQd0knx8ERY1v4ix6l_BWoQmz6BPVl5ctX7Y1nwh4/edit#heading=h.n0lykgr25cof)
