### ISSUE TITLE
Updates ThemesNav.js to use siteData for themes

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3947]
PR: https://github.com/cityofaustin/janis/pull/698
PR App: https://janis-3947-no-hardcoded-themes.netlify.com/

We pass our theme info to our FullSiteMenu correctly, but for some reason ThemesNav.js has hardcoded theme data in it.

We should make sure we aren't using hardcoded themes in there.

**Comment by desigonz** [comment]
One positive side effect I'm already seeing is that the global nav order matches that of the meganav!!! 
![image](https://user-images.githubusercontent.com/5839508/75283245-111eb900-57d8-11ea-96a7-98ec81c91147.png)

@briaguya How else should we QA or test for regressions?

**Comment by briaguya** [comment]
@desigonz live on staging (we can tell because the order matches!)

**Comment by desigonz** [comment]
yay!!! can we get it in prod?
