### ISSUE TITLE
Link not working in step

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#3948]
## Describe the bug
I am trying update the [Hire a day laborer service pag](https://alpha.austin.gov/en/government-business/business-resources-3/workforce-development-and-hiring/hire-a-day-laborer/)e to include a link in step 3 to the new location page that I just built. It seems to work when I am in Joplin, but after publishing it doesn't. It appears to be highlighted like a link but is not clickable.

## URL
https://alpha.austin.gov/en/government-business/business-resources-3/workforce-development-and-hiring/hire-a-day-laborer/

## To Reproduce
Steps to reproduce the behavior 
example: 
You can see this on the live page currently. 

## Screenshots
You can see below that there is another link for holiday schedules and that link is working just fine, but it was in the step before I began editing.
![Screen Shot 2020-02-10 at 1.38.35 PM.png](https://images.zenhubusercontent.com/5d6e8f01caef900001337734/0cbf3dc6-8e5c-4552-8bb7-dc2300033d54) 

## Device and browser
Macbook Air
Chrome and Safari

**Comment by ablangworthy27** [comment]
This is also happening here:
https://alpha.austin.gov/en/austin-public-health/report-smoking-in-a-public-place/

The link in step 1 isn't working, and neither is the button in step 3

**Comment by ablangworthy27** [comment]
This is also happening here:
https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/food-business-permits/renew-your-mobile-food-vendor-permit/

none of the links are working

**Comment by chiaberry** [comment]
Fixed by https://github.com/cityofaustin/techstack/issues/3852, right?

**Comment by desigonz** [comment]
This is fixed, thanks team!
