### ISSUE TITLE
Copy edit review: new service page for neighborhood centers

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#3949]
I am transitioning neighborhood centers to the new location content type, and a need has come up to create a service page that can replace [this info page](https://alpha.austin.gov/en/housing-utilities/pay-utility-bills-and-rent/get-help-paying-bills/neighborhood-centers-help-you-pay-rent-and-utilities-2/).

Please make suggestions in the[ _Get help with rent and utility payments_ draft.](https://docs.google.com/document/d/1lVOHyDcs_Crrp8U0bfiAwnWyqhU33pa5fT1fo1PPP40/edit)

**Comment by Jo-Dwyer** [comment]
looks good to me!
