### ISSUE TITLE
Review: Copy changes for mobile food vendor guide 

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#3951]
As I transition EHSD to the new location content type, there are steps within the mobile food vendor guide that can be simplified by adding a step with a location. I have proposed changes on the following pages

- Apply for a mobile food vendor operational permit
- Prepare your mobile food vendor permit application 
- Report changes to your mobile food business
- Bring your mobile food unit to your inspection appointment
- Get food handler training and a food manager certificate 

I need a content review of these [copy changes](https://docs.google.com/document/d/1bpGcLJ76W1woVzkHaK_W4XD0iHAHXvjuhimEV47nB80/edit).

**Comment by Jo-Dwyer** [comment]
This looks good. Changes approved!
