### ISSUE TITLE
Design + implementation for graphql schema

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3953]
See https://github.com/cityofaustin/joplin/pull/555

### As a developer, I want a structured technical design for our api schema to support the above goals and implement it in a testable way so that I know what I am affecting when I wrote new code for the api and know when something breaks, changes, or needs to be purposefully changed.

**Comment by desigonz** [comment]
Can you at least add a user story, so that we have a documentation of the value of this?
