### ISSUE TITLE
AWS Lambda logs are painful for humans to parse

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3955]
Our publisher logs are here:
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logStream:group=/aws/lambda/coa-publisher-mvp-pr;streamFilter=typeLogStreamPrefix

They are hard to read. It's hard to know which log is for which branch or build. There is lots of noise in the log itself. Also, the messages from this log don't go anywhere ( such as Slack or Github ) to easier trace and notice if there is an error or problem with the publish process.

**Comment by Niicck** [comment]
This will be fixed by MVP publisher.
