### ISSUE TITLE
Feedback component style changes

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3959]
# QA
PR: https://github.com/cityofaustin/janis/pull/702

Homepage (with feedback component): https://janis-3959-feedback-width.netlify.com/
OPO page (without feedback component): https://janis-3959-feedback-width.netlify.com/en/police-oversight/

### Places the margin-bottom css hits
* Department pages (https://janis-3959-feedback-width.netlify.com/en/police-oversight/)
* Event pages (https://janis-3959-feedback-width.netlify.com/event/2020/3/2/create-an-event-in-staging/)
* Form pages (?)
* Information pages (https://janis-3959-feedback-width.netlify.com/en/permits-tickets/business-permits-and-licenses/food-business-permits/businesses-required-to-get-a-mobile-food-vendor-permit-2/)
* Service pages (https://janis-3959-feedback-width.netlify.com/en/permits-tickets/business-permits-and-licenses/food-business-permits/get-a-central-preparation-facility/)

# Solution
Spec: https://xd.adobe.com/view/a3f55254-1db8-437a-5421-6e1e1d175e35-d5c4/

- [ ]  Background gray: #F7F7F7 (matches other background grays we're using)
- [ ] Component background/container spans 100% width, but the input fields and everything else should all remain where they are, they shouldn't span 100%

**Comment by briaguya** [comment]
## Before
### Collapsed Desktop
<img width="1205" alt="Screen Shot 2020-02-25 at 4 36 32 PM" src="https://user-images.githubusercontent.com/6384156/75294269-93fe3e80-57ed-11ea-9a6b-454896d7815b.png">

### Expanded Desktop
<img width="1210" alt="Screen Shot 2020-02-25 at 4 36 45 PM" src="https://user-images.githubusercontent.com/6384156/75294281-9a8cb600-57ed-11ea-8bd1-9e7f39791579.png">

### Collapsed Mobile
<img width="367" alt="Screen Shot 2020-02-25 at 4 37 03 PM" src="https://user-images.githubusercontent.com/6384156/75294302-a4161e00-57ed-11ea-9370-21eb3cc3ccf9.png">

### Expanded Mobile
<img width="383" alt="Screen Shot 2020-02-25 at 4 37 45 PM" src="https://user-images.githubusercontent.com/6384156/75294752-d1af9700-57ee-11ea-9597-e799018a0cd5.png">

### Footer padding on page without feedback component
<img width="780" alt="Screen Shot 2020-02-25 at 4 40 23 PM" src="https://user-images.githubusercontent.com/6384156/75294323-ae381c80-57ed-11ea-9f38-06c605d4b198.png">

## After
### Desktop collapsed
<img width="1211" alt="Screen Shot 2020-02-25 at 4 47 23 PM" src="https://user-images.githubusercontent.com/6384156/75294647-9745fa00-57ee-11ea-9442-e342b1e0387e.png">

### Desktop expanded
<img width="1211" alt="Screen Shot 2020-02-25 at 4 47 33 PM" src="https://user-images.githubusercontent.com/6384156/75294654-9f059e80-57ee-11ea-89a5-cd797c7a4750.png">

### Mobile collapsed
<img width="396" alt="Screen Shot 2020-02-25 at 4 38 01 PM" src="https://user-images.githubusercontent.com/6384156/75294690-b04eab00-57ee-11ea-883b-63d4dc4f81e7.png">

### Mobile expanded
<img width="463" alt="Screen Shot 2020-02-25 at 4 38 11 PM" src="https://user-images.githubusercontent.com/6384156/75294703-b6dd2280-57ee-11ea-9c66-936615220dcd.png">

### (lack of) footer padding on page without feedback component
<img width="717" alt="Screen Shot 2020-02-25 at 4 39 43 PM" src="https://user-images.githubusercontent.com/6384156/75294929-3539c480-57ef-11ea-97b0-0ee1513b6e9c.png">

**Comment by briaguya** [comment]
@desigonz @chasechenevert I was hoping to get some feedback on if it's ok to clear off the footer padding for pages without feedback components (getting rid of it was the quickest way to remove some odd looking whitespace between the feedback component and the footer)

examples above, links:
Homepage (with feedback component): https://janis-3959-feedback-width.netlify.com/
OPO page (without feedback component): https://janis-3959-feedback-width.netlify.com/en/police-oversight/

**Comment by desigonz** [comment]
I defer to @chasechenevert on this!

**Comment by chasechenevert** [comment]
@briaguya This looks good! For pages without the feedback component, I do want a little padding so that there is some rhythm to the spacing (similar to how there's padding between the header and body content, and the spacing between paragraphs and sections). Let me know if this is tricky though!

**Comment by chasechenevert** [comment]
All good from me.
