### ISSUE TITLE
Process Page: Build Joplin Content Model

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#396]
This is a first stab at model definition for the process pages but feel free to update as you see fit.

### Process Page Model (ProcessPage)
- [x] slug
- [x] title
- [x] topic
- [x] description 
- [x] banner image {url, text}
- [x] steps [array] of step objects defined below
- [ ] images [array] of image objects defined as:
  - [ ] url
  - [ ] text

### Process Page - Step Model (ProcessStepPage) (overlaps with step object above)
- [x] slug - autogenerated via `<process page slug>/<step number>`
- [x] step number autogenerated via streamfield order
- [x] title (for overview page)
- [ ] long title (for step page)
- [x] short title (for badge)
- [x] link title (for link on overview page)
- [x] description
- [x] banner image {url, text}
- [x] overview (array of strings to show as bullets on overview page)
- [ ] Streamfield to order content generated via 
  - [x] WYSIWYG content
  - [ ] Table
  - [ ] Accordion
  - [ ] Map
  - [ ] App (needs more definition)
  - [ ] Image Gallery
  - [x] quote

maybe get with content and @cthibaultatx to see if we need so many different titles/labels for each step -- overview title, long title, short title, link title -- seems like a lot.

**Comment by cthibaultatx** [comment]
@ifsimicoded let's simplify it as much as possible. Would love to work through this next week.

**Comment by ifsimicoded** [comment]
For the process page step:
- let's utilize the title to serve purpose of long title too.
- The step number will be determined by the order the model is created
- The slug is set by the parent process page

**Comment by ifsimicoded** [comment]
Reopening issue and updating requirements above based on requirements outlined in [content modeling meeting](https://docs.google.com/document/d/1v0SWKBJJU7hkAQ9sJ-KsaRrDOTcgM-t9vWC6FpxQa80/edit) with all disciplines

**Comment by amenity** [comment]
[Putting Process Page back in the ol' backlog](https://github.com/cityofaustin/techstack/issues/821).
