### ISSUE TITLE
Label size for mobile "blocks"

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3961]
@chase noticed an inconsistency in heading sizes on mobile. 
![image](https://user-images.githubusercontent.com/5839508/74479505-e39b4c80-4e74-11ea-86c7-360b7486552f.png)

**Acceptance criteria**
- [ ] On mobile, `Offered by` should go to `2rem` at the mobile break point to match Contact information

**Comment by briaguya** [comment]
@chasechenevert I have this implemented here: https://janis-3961-label-size.netlify.com/en/health-safety/health-prevention/disease-prevention/find-free-condoms/ (as well as https://github.com/cityofaustin/techstack/issues/3959)

I couldn't find an example of the full mobile footer on abstract so I was hoping to use this as a chance to figure out what exactly we're going for with it

**Comment by desigonz** [comment]
Assigning @chasechenevert to review. Do you have a mock of the full mobile footer (with contact block and departments) on Abstract?

**Comment by chasechenevert** [comment]
Sorry for the delay here! The space is fine to me for now, so this is good to go!
