### ISSUE TITLE
Unable to preview a service page in progress

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3964]
## Describe the bug
I'm making changes to a draft of a service page and want to see how my bulleted list looks. I hit preview and none of the content on my page appears. 

[Request court records](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZTozMDk4)

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to https://joplin.herokuapp.com/admin/pages/359/edit/#tab-content
2. Click on 'Preview'
3. See the preview page open
4. See no content

## Current behavior
I'm making changes to a draft of a service page and want to see how my bulleted list looks. I hit preview and none of the content on my page appears. When I go back to Joplin to see what I can do about it, there's a new red "1" on the editing tab. I click it and it's unresponsive, so I don't know what it trying to tell me.

## Expected behavior
I expect that "Preview" will take the content I currently have in the editor and create a preview page with it so I can see it before I save the draft or publish. 
I expect also that when there's a red warning-looking icon, it will lead me to more information so I can resolve it and make it disappear.

## Screenshots
![Screen Shot 2020-02-14 at 11.53.11 AM.png](https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/376bf601-bbf0-4279-976b-b8ccd804f4e8)
![Screen Shot 2020-02-14 at 11.53.48 AM.png](https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/e2b28217-5c04-4854-80a7-b921515ea1e8)

**Comment by desigonz** [comment]
I was able to preview:
https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZTozMzQx

The little red 1 means that you tried saving the page but hadn't fully filled out requirements for a field, so it didn't save. And that's why the preview didn't work.

Closing this issue. We have issues out for improving the error messaging.
