### ISSUE TITLE
Styling/localization for privacy fallback message

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3967]
### Testing notes
1. Go here: https://janis-3967-form-fallback-styles.netlify.com/en/police-oversight/apply-to-the-community-police-review-commission
2. Make sure privacy badger (or whatever content blocker you'd like to use) is blocking formstack
3. See styled/localized fallback message

PR: https://github.com/cityofaustin/janis/pull/696

## Issue
- [ ] Implementation matches [mocks](https://share.goabstract.com/70b0c639-82c9-48a4-9095-2998bb623b01?sha=7b03d6540e22969acfb12c4f11035f87ed2487a4)
- [x] Blue left border
- [x] Info icon 
- [x] Copy for link: "Open the form in a new window"
  - [x] followed by the material icon font, it's titled "open_in_new"
  - [x] When clicked, link opens in new window

**Comment by briaguya** [comment]
@chasechenevert @desigonz This is implemented here (https://janis-3967-form-fallback-styles.netlify.com/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyNzc1) now.
* It's only desktop (is mobile MVP? I didn't see specs for it)
* It hasn't been localized

**Comment by desigonz** [comment]
Good catch. I made #4041 for localization.

@chasechenevert, assigning you to QA. Thanks!

**Comment by desigonz** [comment]
@briaguya The translators were speedy with this one. Here's the copy for `es`:

**Aún estamos esperando que cargue su formulario**
Abra el formulario en una nueva pantalla.
¿Por qué no ha cargado aún?
- Es posible que un plugin esté bloqueando el formulario (por ejemplo: "Privacy Badger")
- Puede haber ocurrido un error al cargarlo ("error 404")

Thanks for catching this and looping it in!

**Comment by chasechenevert** [comment]
Mobile has been added: https://share.goabstract.com/70b0c639-82c9-48a4-9095-2998bb623b01?sha=7b03d6540e22969acfb12c4f11035f87ed2487a4

**Comment by desigonz** [comment]
Assigning @chasechenevert to QA this

**Comment by chasechenevert** [comment]
@briaguya @desigonz This is good to go.
