### ISSUE TITLE
Pasting markdown tables into codeblocks creates multiple codeblocks

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3969]
When pasting a syntactically valid markdown table into a codeblock in Joplin, it appears as multiple lines separated by a block ending endline character. (we see big spaces in between instead of small spaces)

This means our logic in janis parses each line individually as markdown, making it so our tables are not parsed as tables.

If pasting within a code block kept it as one big code block, that would make the experience of pasting markdown tables much less painful.

This could possibly be something to discuss with wagtail too, not sure how the paste behavior in rich text fields was designed.

**Comment by desigonz** [comment]
Looped this into #2333
