### ISSUE TITLE
Display pages in order of most recently edited

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3974]
## QA
PR: https://github.com/cityofaustin/joplin/pull/579
1. Go to https://joplin-pr-3974-list-order.herokuapp.com/admin/pages/search/
2. See that it's sorting by last updated
3. Try playing with page filters and searching and see if the pages are ordered as expected

### As a content author, I want to be able to easily access pages I've edited most recently, so I can efficiently edit content.

Before we implemented the search page as the main Joplin page, we used to order pages in reverse chronological order, with the page that's been most recently edited at the top. Now it's just in order of creation. That's unhelpful when you update a page but then want to go back to it—you have to go searching for it.

- [ ] On main content page, the pages appear in reverse chronological order (what has been edited/saved most recently at the top)

**Comment by briaguya** [comment]
@desigonz @toribr want to clarify here, do we want:
* Sorting by date/time of last draft saved?
  * May be annoying with the current "need to save to preview" flow

OR
* Sorting by date/time of last publish?

**Comment by desigonz** [comment]
Last saved is what we used to have, I believe. @toribr can you confirm?

**Comment by toribr** [comment]
@desigonz Not sure what you mean by "used to have" but between 'last saved' and 'last published' I think 'last saved' makes more sense.

**Comment by desigonz** [comment]
Agreed with "last saved." This was the behavior before we switched to the search home page.

**Comment by desigonz** [comment]
QA passed. This looks great!
