### ISSUE TITLE
Step with multiple locations display

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3975]
## QA Notes
PR App: https://janis-3975-location-steps.netlify.com/en/housing-utilities/pay-utility-bills-and-rent/get-help-paying-bills/get-help-with-rent-and-utility-payments/
PR: https://github.com/cityofaustin/janis/pull/699

@chasechenevert I made some changes to the spacing on mobile, I didn't see anything in abstract for steps with locations.

Comparison:
https://alpha.austin.gov/en/housing-utilities/pay-utility-bills-and-rent/get-help-paying-bills/get-help-with-rent-and-utility-payments/
vs.
https://janis-3975-location-steps.netlify.com/en/housing-utilities/pay-utility-bills-and-rent/get-help-paying-bills/get-help-with-rent-and-utility-payments/

## Describe the bug
See step one in the screenshot below. Content is breaking to the line below the step number and is all the way left justified. 

![image](https://user-images.githubusercontent.com/5839508/74753380-ab5d8a80-5235-11ea-8225-382bef4a2bc4.png)

## URL
https://alpha.austin.gov/en/housing-utilities/pay-utility-bills-and-rent/get-help-paying-bills/get-help-with-rent-and-utility-payments/

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to https://alpha.austin.gov/en/housing-utilities/pay-utility-bills-and-rent/get-help-paying-bills/get-help-with-rent-and-utility-payments/
2. See error

## Current behavior
![image](https://user-images.githubusercontent.com/5839508/74753380-ab5d8a80-5235-11ea-8225-382bef4a2bc4.png)

## Expected behavior
- [ ] layout/padding matches the second step.

**Comment by chasechenevert** [comment]
Good catch! The layout should match the second step.

**Comment by briaguya** [comment]
@chasechenevert @desigonz just verifying we want the description **and** the location buttons in the step to be the same width as the second step

**Comment by chasechenevert** [comment]
> @chasechenevert @desigonz just verifying we want the description **and** the location buttons in the step to be the same width as the second step

Yep, that's right

**Comment by desigonz** [comment]
Looks great, but let's wait for @chasechenevert's sign off.

**Comment by chasechenevert** [comment]
Looks good to me! 🚀

**Comment by desigonz** [comment]
@chasechenevert to specify `line-spacing`, then we'll implement, then QA will be complete

**Comment by briaguya** [comment]
@desigonz split out spacing into https://github.com/cityofaustin/techstack/issues/4044
