### ISSUE TITLE
Labels on snippets

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3977]
## Describe the bug
This seems to be a regression but not sure when it happened—on snippets, the titles are formatting funny, with the arrow icon overlapping the beginning of the label

![image](https://user-images.githubusercontent.com/5839508/74772975-98a77d80-5256-11ea-8a5c-e919efd0798e.png)

**Acceptance criteria**
- [x] Titles don't overlap/return to how they used to be for:
  - [x] Contacts
  - [x] Maps

## To Reproduce
Steps to reproduce the behavior 
example: 

## Current behavior
A clear and concise description of what happened

## Expected behavior
A clear and concise description of what you expected to happen

**Comment by chiaberry** [comment]
for QA https://joplin-pr-3977-snippet-labels.herokuapp.com/admin/snippets/base/contact/1/ for

**Comment by desigonz** [comment]
What a dream! QA passed
