### ISSUE TITLE
Sketch CPRC content

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3980]
### As a resident concerned about police oversight, I want to be able to know about what the commission is, who its members are, and what the commission is working on, so that I have a sense of what the City and civilians are doing to address policing in Austin.

For more notes and specific requirements, see #3979.

We need to gather the content or improvise content that's need for this presence, ie, content-first design. 
- [x] Content strategist to sketch a structure based on requirements in #3979. Quick IA with:
  - [x] What are the pages
  - [x] What's on each page
  - [x] How they relate to each other (what's a parent, what's a child, etc)
- [x] Then we'll bounce around draft with @toribr and @desigonz 
- [x] By end of sprint, have identified any design or dev work that might need to happen (let's try to keep it small, because we'll only have sprints 52 and 53 to design and implement)

**Comment by desigonz** [comment]
@srigdon How does having a content sketch by content pin-up on 2/25 sound? And can you size this?

**Comment by srigdon** [comment]
@desigonz Can do, let's get this hammered out early in the sprint.
