### ISSUE TITLE
Janis/Joplin API for department groups

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3983]
### As a [Joplin API consumer (Janis)] I want [to be able to build pages at the correct URLs and display the correct  based on department groups instead of department pages] so that [we don't need to manage multiple types of associations between departments/department pages/other pages in any given department].

**Is your feature request related to a problem? Please describe.**
When adding a page to a department group, we need that page to also publish under the department and have the correct information in contextualnav.

**Describe the solution you'd like**
The Joplin API exposes the appropriate department information for any given page based on department group associations

**Comment by desigonz** [comment]
This is looped into the PR branch associated with #3813. More notes in this document: https://docs.google.com/document/d/1FY-enbU7mTFXR8vX2rG7FqnySRqsAFoB8Op1f_--v14/edit# Closing this issue!
