### ISSUE TITLE
UX for assigning "Top-level page"

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#3984]
### As a content author I want the ability to select top-level page while also selecting topics and related departments, so that there is less confusion about publishing requirements.

**Is your feature request related to a problem? Please describe.**
I am writing the microcopy for error messaging, and I have realized that for info pages you are required to select a minimum of 1 topic, 1 related department, or make the page a top-level page. If you don't select any of these things, you will get an error message. That error message would be much clearer if all of these selections were together. Currently the selection to make your page a top-level page is at the very bottom of the page and it is not clear that there is logic-based criteria involving all three options.

**Describe the solution you'd like**
I'd like the checkbox moved up.

**Comment by easherma** [comment]
( This is sorta tangential, but its also come up several times before that 'top-level' pages are so rare that it probably makes more sense to have a single spot in the admin where they are managed vs having this checkbox on every info page and would clear up this issue as well. )

**Comment by desigonz** [comment]
Yeah I think this issue should be "rethink UX of assigning top-level pages" and I'm going to file it in the long-term backlog. We might want to rewrite the user story too.

**Comment by toribr** [comment]
Moving relevant parts to #3051 and closing this as dupe.
