### ISSUE TITLE
Integrate content type factories into our testing, CI

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3987]
With https://github.com/cityofaustin/techstack/issues/3630 , we have more and more factories to generate data. 

But we don't use them in many (if any) tests at the moment. 

Acceptance criteria for this:
The framework is set up and documentation and some example tests are committed. This issue isn't meant to cover adding all the tests needed to joplin, as that'l be a longer process.

**Comment by easherma** [comment]
https://github.com/cityofaustin/techstack/issues/3986 would make this simpler/easier/faster

**Comment by desigonz** [comment]
Next steps are the shareout on 3/3, see #3630 for more details on the shareout.

**Comment by Niicck** [comment]
Covered in v3
