### ISSUE TITLE
"This page is a part of this guide" button not consistently appearing

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3993]
# QA
PR: https://github.com/cityofaustin/janis/pull/706

## What was broken
The pattern of brokenness on alpha.austin.gov is:
* If [the page](https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/food-business-permits/businesses-required-to-get-a-mobile-food-vendor-permit-2) is the [first within it's section of the guide](https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/food-business-permits/mobile-food-vendor-permit-guide/#Learn-and-prepare-1), it will have a "page is part of" guide link
* If [the page](https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/food-business-permits/mobile-food-vendor-permit-types-and-fees/) is [**not** the first within it's section](https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/food-business-permits/mobile-food-vendor-permit-guide/#Learn-and-prepare-2), it will **not** have a "part of a guide link"

## Testing
* Go to [a guide](https://janis-3993-part-of-guide.netlify.com/en/permits-tickets/business-permits-and-licenses/food-business-permits/mobile-food-vendor-permit-guide)
* Click the links to open pages
* See the "page is a part of" links there

### Also all these links should work
https://janis-3993-part-of-guide.netlify.com/en/health-safety/health-prevention/disease-prevention/documents-for-mobile-food-vendors-in-austin/ 
https://janis-3993-part-of-guide.netlify.com/en/permits-tickets/business-permits-and-licenses/food-business-permits/businesses-required-to-get-a-mobile-food-vendor-permit-2/ 
https://janis-3993-part-of-guide.netlify.com/en/permits-tickets/business-permits-and-licenses/food-business-permits/prepare-your-mobile-food-vendor-permit-application/ 
https://janis-3993-part-of-guide.netlify.com/en/permits-tickets/business-permits-and-licenses/food-business-permits/fire-inspections-for-mobile-food-vendors/
https://janis-3993-part-of-guide.netlify.com/en/permits-tickets/business-permits-and-licenses/food-business-permits/requirements-to-safely-operate-your-mobile-food-business/ 
https://janis-3993-part-of-guide.netlify.com/en/permits-tickets/business-permits-and-licenses/food-business-permits/mobile-food-vendor-permit-types-and-fees/
https://janis-3993-part-of-guide.netlify.com/en/permits-tickets/business-permits-and-licenses/food-business-permits/get-a-central-preparation-facility/
https://janis-3993-part-of-guide.netlify.com/en/permits-tickets/business-permits-and-licenses/food-business-permits/get-food-handler-training-and-food-manager-certificate/ 
https://janis-3993-part-of-guide.netlify.com/en/permits-tickets/business-permits-and-licenses/food-business-permits/mobile-food-vendor-pre-application-checklist/
https://janis-3993-part-of-guide.netlify.com/en/permits-tickets/business-permits-and-licenses/food-business-permits/apply-for-mobile-food-vendor-permit-in-person/ 
https://janis-3993-part-of-guide.netlify.com/en/permits-tickets/business-permits-and-licenses/food-business-permits/bring-your-mobile-food-unit-to-your-inspection-appointment/ 
https://janis-3993-part-of-guide.netlify.com/en/permits-tickets/business-permits-and-licenses/food-business-permits/renew-your-mobile-food-vendor-permit/ 
https://janis-3993-part-of-guide.netlify.com/en/health-safety/health-prevention/disease-prevention/report-changes-to-your-mobile-food-business/ 

# Issue
## Describe the bug
A while ago, we implemented functionality so that pages that are a part of a guide have a link to that guide via the "This page is a part of this guide" button. We're noticing it's not working everywhere.

## URL
https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/food-business-permits/mobile-food-vendor-permit-guide/

### It's working for these
- [x] https://alpha.austin.gov/en/health-safety/health-prevention/disease-prevention/documents-for-mobile-food-vendors-in-austin/ **info page**
- [x] https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/food-business-permits/businesses-required-to-get-a-mobile-food-vendor-permit-2/ **info page**
- [x] https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/food-business-permits/prepare-your-mobile-food-vendor-permit-application/ **service page**
- [x] https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/food-business-permits/fire-inspections-for-mobile-food-vendors/ **info page**
- [x] https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/food-business-permits/requirements-to-safely-operate-your-mobile-food-business/ **info page**

### It's **not** working for these
- [x] https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/food-business-permits/mobile-food-vendor-permit-types-and-fees/ **info page**
- [x] https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/food-business-permits/get-a-central-preparation-facility/ **service page**
- [x] https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/food-business-permits/get-food-handler-training-and-food-manager-certificate/ **service page**
- [x] https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/food-business-permits/mobile-food-vendor-pre-application-checklist/ **info page**
- [x] https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/food-business-permits/apply-for-mobile-food-vendor-permit-in-person/ **service page**
- [x] https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/food-business-permits/bring-your-mobile-food-unit-to-your-inspection-appointment/ **service page**
- [x] https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/food-business-permits/renew-your-mobile-food-vendor-permit/ **service page**
- [x] https://alpha.austin.gov/en/health-safety/health-prevention/disease-prevention/report-changes-to-your-mobile-food-business/ **service page**

## To Reproduce
Steps to reproduce the behavior 
example: 

## Current behavior
A clear and concise description of what happened

## Expected behavior
A clear and concise description of what you expected to happen

**Comment by easherma** [comment]
![](https://media.giphy.com/media/vp122eOzO0Hxm/giphy.gif)

**Comment by briaguya** [comment]
gut feeling is something is happening with `getPagesOfGuidesData` in our static.config.js, lots of places to look/test with this so I'm giving it a 5

**Comment by desigonz** [comment]
Looks great! QA passed. 

I tested it by navigating to the pages from the ["Food business permits" topic](https://janis-3993-part-of-guide.netlify.com/en/permits-tickets/business-permits-and-licenses/food-business-permits), because the links from the guide lead to alpha.austin.gov.

cc-ing @srigdon—we have a fix for this and it will be going into production soon!
