### ISSUE TITLE
Update custom publish requirements for department groups

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3994]
Since we no longer have related departments on pages, we should update our publish requirements so pages must have any of the following:
* An associated department group with an associated department page
* An associated topic
* Top level checked (for applicable page types)

This should be doable by creating a new custom requirement in publish_preflight/requirements.py, that looks at the GroupPagePermissions for a page, finds the associated department record for the group, and checks to ensure there's an associated department page for that department.

**Comment by desigonz** [comment]
This is looped into the PR branch associated with #3813. More notes in this document: https://docs.google.com/document/d/1FY-enbU7mTFXR8vX2rG7FqnySRqsAFoB8Op1f_--v14/edit# Closing this issue!
