### ISSUE TITLE
Add location pages to the style guide tab

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3995]
### As a content editor I want the style guide panel in Joplin to display information relevant to the component/content type I am editing so that I can more efficiently find appropriate guidance.

- [x] When a user edits a location page, the style guide tab is open to [location page style guide content](https://cityofaustin.gitbook.io/digital-style-guide/pick-the-perfect-content-type/location-page)

**Comment by easherma** [comment]
QA me at 
https://joplin-pr-3995-location-styleg.herokuapp.com/admin/login/

**Comment by desigonz** [comment]
@easherma awesome work, looks great—QA passed!

**Comment by desigonz** [comment]
This is in production, closing the issue.
