### ISSUE TITLE
Get rid of deprecated location snippet stuff

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3996]
We have fully transitioned locations to the new location content type! Let's get rid of the old location snippet.

**Acceptance criteria**
- [x] User cannot access locations snippet from the left nav
- [x] When editing a contact, user does not see the option to select a **location snippet**
- [x] When editing a contact, user is still able to select a **location page**

![image](https://user-images.githubusercontent.com/5839508/74950647-05408a80-53c5-11ea-8245-c18e2b8eda30.png)

![image](https://user-images.githubusercontent.com/5839508/74950723-230def80-53c5-11ea-828b-af6152362a72.png)

**Comment by desigonz** [comment]
Technical acceptance criteria:
- [ ] Just get rid of all the location snippet stuff

**Comment by desigonz** [comment]
Location QA is complete, so this issue is ready to go!!

**Comment by easherma** [comment]
@desigonz 
Do all of these maps have an appropriate location page that they can link to instead?
https://joplin.herokuapp.com/admin/snippets/base/map/

**Comment by easherma** [comment]
Can be QA'ed at:
https://joplin-pr-3996-remove-location.herokuapp.com/admin/login/

If we want to truly delete the other fields, thats going to require some dancing around dev wise, but that doesn't impact QA/criteria for content author-facing stuff

**Comment by desigonz** [comment]
Great! QA passed for user acceptance criteria, but I'll let @Niicck evaluate the technical acceptance criteria above.

**Comment by Niicck** [comment]
Technical Acceptance Criteria:
- [ ] Truly delete the old location snippet
- [ ] Make sure that the migration will work when applied to an existing database

Here's the issue Eric ran into:
> Initially, I ran into a foreign key constraint when just dropping the snippet and replacing it with the location page. I'm thinking this is probably because loading the fixture was including the 'old' snippet relations as well. There may also be an issue with trying to load a datadump that contains references to models that no longer exist on the target.
> I also ran into this error running migration test in general, and so I opted for pushing up a solution that still meets acceptance criteria while giving us time to follow through with removing the old stuff from the models.

- [ ] The solution needs to account for that error. 
  + Loading (an existing datadump) with (old location snippets) might not work. 
  + But loading (an existing datadump) that once had (old location snippets) but now has (new location migrations that deleted those old snippets) must work. You might have to run migration-test against a PR branch that has (new location migrations) applied.

**Comment by desigonz** [comment]
- [ ] @briaguya to confirm that the technical acceptance criteria is met in Joplin 3.0

**Comment by Niicck** [comment]
Will be covered in v3
