### ISSUE TITLE
Draft a service page for the Driver safety request

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3998]
When a defendant pleads "no contest" to a traffic violation, they may waive their right to a trial and  request a driver safety course to dismiss the charges. Currently information about this is embedded in a [pdf form](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/DeferredDisposition_Driver_Safety_Course.pdf) to be printed and filled out and then submitted by mail, in person or email. 

This service page should outline the steps and fee information that are currently embedded in the form and link to the existing PDF as a document hosted on Janis.

- [x] Is it true? **The information on this document is up to date as of 12/330/19 and is therefore true.** 
- [x] Is it readable? **The PDF reads at a grade 10 level**
- [ ] Is it actionable? **The PDF provides all information needed to connect a resident with the service, this information needs to be surfaced in a service page.**

- [ ] Send for review by @srigdon, @ablangworthy27 or @Jo-Dwyer

**Comment by ablangworthy27** [comment]
I have a [google docs draft](https://docs.google.com/document/d/1Gw2y-AcKmRsANZM4xN18Y1MneBuJ56JefHqx2f7rKhI/edit) done. There are a couple of holes in information that @Jo-Dwyer is looking into with her SME.  But, I think a review could be done without that info.

**Comment by desigonz** [comment]
Waiting for:
- Follow up from Amy
- then review by a content strategist
