### ISSUE TITLE
Draft a service page for filing a citizen complaint

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3999]
When a resident wants to file a complanit against another person, it must be delivered in person and signed by a court clerk *or* notarized and submitted by mail. There are three kinds of compaints with similar requiremnts and separate forms. 

The service page should outline the complaint process then break out the forms in a step with options. Link to the original PDFs as documents hosted on Janis. 

[Citizen Complaint Form – Noisy Animal](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/AFFAnimalViolations03_2016_F.PDF)
[Citizen Complaint - Code/Ordinance Violation (except noisy animal)](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/AFFNonTrafficOtherViolations03_2016_F.PDF)
[Citizen Complaint - Traffic/Insurance Violations](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/AFFTrafficInsuranceViolations03_2016_F.PDF)

- [x] Is it true? **Yes. According to Amy Schillerstrom, these documents are up tot date despite a 2016 publish date.**
- [x] Is it readable? **The PDF is at a grade 8-9 level. Tone change is necessary, but not vocabulary.**
- [x] Is it actionable. **Yes, the necessary information to fill out and submit this document is in the PDF.**

- [x] Send for review by @srigdon, @ablangworthy27 or @Jo-Dwyer

**Comment by ablangworthy27** [comment]
I have a [draft ](https://docs.google.com/document/d/1GcKzXLl7D2H6nWSTVy1QQQfmhMSyZsHslk8eEX04OWc/edit)ready for review. @srigdon @Jo-Dwyer 

I also created a contact snippet and location page for Downtown Austin Community Court, because it was the only location option that wasn't already set up. 

Once I get a review, I will draft in Joplin.

**Comment by Jo-Dwyer** [comment]
- citizens complaints must be notarized or filled out in the court (no email or phone)
- this form must be notarized (printed) or in person sworn by clerk


Might be good to include info redirecting to OPO form since people sometimes confuse them.

"were you looking for OPO/ complaint against officer?"

**Comment by Jo-Dwyer** [comment]
This looks awesome. Draft away.

**Comment by ablangworthy27** [comment]
@Jo-Dwyer here is a joplin draft:
https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZTozMzg1

**Comment by srigdon** [comment]
Reviewed; it looks good to publish. Got it down to a grade 7 reading level. Preview page: https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZTozMzkz 

Great work, @ablangworthy27!

**Comment by desigonz** [comment]
@Jo-Dwyer to review and take it to the next step!

**Comment by gabrielaperezdelaosa** [comment]
New preview link: https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZTo2MTY=

**Comment by srigdon** [comment]
Reviewed, edits made in the Joplin draft. Looks good to publish.
