### ISSUE TITLE
Implement Process Page component: Callout/Quote

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#400]
Related to #397 #398
Component, PropTypes and Storybook

**Comment by cthibaultatx** [comment]
## Mobile quotes
![screen shot 2018-05-25 at 9 39 20 am](https://user-images.githubusercontent.com/20911665/40550383-8eff9cae-5fff-11e8-8c90-644608a8e389.png)

## Desktop quotes
![screen shot 2018-05-25 at 9 37 02 am](https://user-images.githubusercontent.com/20911665/40550403-9808e22e-5fff-11e8-8231-f8152a840ad1.png)

**Comment by amenity** [comment]
@ifsimicoded - it is likely that the design specs for this component will change during #671 . Shall I mark that as a dependency, or is it irrelevant to this part of the implementation?

**Comment by amenity** [comment]
[Putting Process Page back in the ol' backlog](https://github.com/cityofaustin/techstack/issues/821).
