### ISSUE TITLE
Joplin Smol label fix on event page - "Long description" to "Description"

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4001]
At one time we had two description fields for events and then we got rid of one, but the label didn't get changed. Blame me! 

Change "Long description" to just "Description".

**Comment by chiaberry** [comment]
https://joplin-pr-4001-description-lab.herokuapp.com/admin/pages/362/edit/#tab-content

@desigonz @toribr no longer says long description!

It does say "full description of the event" below, let me know if that copy needs to be changed as well.

**Comment by desigonz** [comment]
QA passed!
