### ISSUE TITLE
Review content strategist applications and schedule phone screens

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#4013]
At content sync, discuss applications and select who to move forward and who will interview.

**Comment by ablangworthy27** [comment]
As discussed yesterday in sync, these are the candidates that I like so far.  New ones are being submitted still, so I turned on notifications. Mary Ellen is a new candidate that I am adding to my list of possible phone screens.

Mary Ellen McCarthy
Monica Rojas 
Gabriela Perez
Inara Fernandez
Marcela Reyes Ayala
and possibly Michelle Hulme-Lippert
