### ISSUE TITLE
Joplin UI: Application Banner & Primary Navigation

### ISSUE THREAD

**Issue by robbobfrh84** [cityofaustin/techstack#4016]
"As a city author, I need the authoring experience to have a logical visual hierarchy so that I am better able to understand the **Application Banner & Primary Navigation** interface." - A City Author

This is a broken out section of the Joplin UI re-design.
 
#### Acceptance Criteria
- [ ] Matches styles from XD Design 👇
  - https://xd.adobe.com/view/c533a077-9314-46a6-5db4-d4a7f8601e8f-b302/
- [ ] Matches CSS for Themes and Colors from Google doc 👇 "Phase 1 acceptance criteria"
  - https://docs.google.com/document/d/1SdAro51Ppdi3Hirn1XkVviJ6nu89dDXtvvFKIX4T8t8/edit#heading=h.ff2tre8z4na1

#### Technical Acceptance Criteria
- [ ] Matches any new structural patterns implemented into the new Joplin UI
- [ ] Checks for and removes any dead-css no longer being used.

**Comment by robbobfrh84** [comment]
OK, this is ready for QA. Please Don't hessitate to reach out with any questions as this is a bit a new test flow we haven't done.

PR: https://github.com/cityofaustin/joplin/pull/586
Deployed: https://joplin-pr-4016-navs.herokuapp.com/

click the lamp in the center of the city seal. It's small, so you may have to click around a bit (10x10px)
This PR only covers TWO sections of the new design.
The Primary Navigation ("Side Nav")
The Application Banner, including User Account dropdown and menu.
See "Design Specs" above.
Does it match the Design?

**Comment by desigonz** [comment]
I wasn't able to verify this in production—can you verify and then close the issue?
