### ISSUE TITLE
Hack for Change Prep

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#402]
- [x] Finalize list of projects
  - I think we've decided to divide and conquer. Ben will lead the crowdsourced content editing workflow UI. Brian will lead the open source recycling schedule. Mateo will lead the analytics.austin.gov fork.
- [x] Forward email with pitch instructions
- [ ] 😿 Create pitch slide
- [x] [Onboarding for volunteers](https://gist.github.com/benweatherman/f62f655014b16aa7357da3db1130a8fc)
- [ ] Create backlog issues for our list of mini projects. Create a new Milestone for ATXH4C and assign the projects to that milestone.

**Comment by briaguya** [comment]
Don't know if there's already an issue for this so I'm going to go ahead and put my notes about the recollect API here.

I sent an email to api@recollect.net asking for the docs, still haven't gotten a response, so I've been working on reverse engineering it via inspecting the widget.

### What do I do with:
```https://recollect.net/api/areas/Austin/services/waste/pages?suggest={SEARCH TEXT HERE}&type=material&include_links=true&locale=en-US&accept_list=true&_=1527843546836```
I'm not sure what the magic number at the end does, it seems to function just fine without it.

### Recycling schedule:
When typing in the address for autocomplete:
```https://recollect.net/api/areas/Austin/services/323/address-suggest?q=1702&locale=en-US&_=1527882407286```
When selecting an address, it appears to do a formatted address search to get an ID
```https://recollect.net/api/places?formatted_address=1702+Taylor+Gaines+St+Unit+B%2C+Austin&parcel_id=39514805&area_id=323&area_name=Austin&place_id=0&svc_id=323&locale=en-US&args=```
when hitting that endpoint, it redirects to:
```https://recollect.net/api/places/9155CF5C-65D4-11E8-891D-DF22E1657EA1/services/323?```
then we get a calendar search endpoint hit:
```https://recollect.net/api/areas/Austin/services/waste/pages/en-US/calendar_search:%7B%22tabbed%22:true%7D.json?widget_config=%7B%22area%22%3A%22Austin%22%2C%22container%22%3A%22%23rCw%22%2C%22page%22%3A%22tabbed_widget%22%2C%22name%22%3A%22wizard%22%7D&_=1527882494973```
^ this one doesn't seem to actually get any specific info
We also get a hit on this endpoint:
```https://recollect.net/api/places/9155CF5C-65D4-11E8-891D-DF22E1657EA1/services/323/events?nomerge=1&hide=reminder_only&after=2018-05-27&before=2018-07-09&locale=en-US&include_message=email&_=1527882518```

**Comment by briaguya** [comment]
![img_2294 2](https://user-images.githubusercontent.com/6384156/40863916-3f60f310-65b7-11e8-8352-04d0d4658a02.JPG)
![img_2293](https://user-images.githubusercontent.com/6384156/40863923-430d1c0a-65b7-11e8-9c7b-70b61b7425db.JPG)

**Comment by benweatherman** [comment]
Nice workflowing!

@mateoclarke has mentioned that the info from the ReCollect widget is in the open data portal. That way we could get completely away from ReCollect. Might be another avenue to pursue.

> I'm not sure what the magic number at the end does, it seems to function just fine without it.

Many request libraries add something like that for cache-busting

**Comment by benweatherman** [comment]
I've been putting some notes at [tiny.cc/hackforchange](https://tiny.cc/hackforchange)

**Comment by mateoclarke** [comment]
@briaguya https://data.austintexas.gov/Utilities-and-City-Services/Recycling-Schedules/rfif-mmvg

**Comment by mateoclarke** [comment]
https://devpost.com/software/alpha-austin-gov
