### ISSUE TITLE
what content type has a link to my location for a service?

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4022]
## Describe the bug
As a resident accessing a service, I expect to find an address that links to a map at some point while I'm figuring out how to access a service. 

## To Reproduce
Steps to reproduce the behavior 
example: 

## Current behavior
A clear and concise description of what happened

## Expected behavior
A clear and concise description of what you expected to happen

**Comment by desigonz** [comment]
Looped this into #4059
