### ISSUE TITLE
Revision history isn't opening or responding

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4026]
I searched for a page, tried to view revision history. The link in the "more" dropdown changes color on hover but doesn't open the revisions page.

https://joplin.herokuapp.com/admin/pages/search/?q=get%20rent

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to ['Pages'](https://joplin.herokuapp.com/admin/pages/search/)
2. Search for "get rent" (that's what I searched)
3. Click on 'more' to see more options
4. Click on 'revisions'
5. See error—watch the address bar too... it looks like an address flickers through there, but there's no change on the page

## Current behavior
I searched "get rent" to pull up the 'Get help with rent and utilities' page, pressed enter wiht my keyboard, then clicked on the more option tab to open revisions. Aside from a color change when I hover with the mouse and a _very_ brief flicker in the address bar, there is no response.

## Expected behavior
I expect the revision history to open even when there's no history.

**Comment by easherma** [comment]
I was able to replicate this, it only happens specifically if you type from scratch and then try to select revisions. You can get it to work by pressing enter after you're done typing (not saying thats ideal, just a fact)

**Comment by desigonz** [comment]
I wasn't able to replicate, and I tested both by pressing enter and not. Closing this for now.
