### ISSUE TITLE
'Privacy policy' opens to weird parts of the page

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4040]
## Describe the bug
When I scroll to the bottom of the ausitn.gov homepage (or any page on it) and click the link for the privacy policy it opens to the middle or bottom of the page with no apparent reason.

https://alpha.austin.gov/en/privacy-policy/

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to 'https://alpha.austin.gov/'
2. Scroll to the bottom
3. Click on 'privacy policy'
4. See error: the page opens in around the midpoint

1. go to another page like ['Get immunized'](https://alpha.austin.gov/en/health-safety/health-prevention/disease-prevention/get-immunized)
2. scroll down to the bottom
3. click on 'privacy policy
4. see error: opens at the bottom and doesn't look like there's any change at all

## Current behavior
The privacy page opens to parts of the page that aren't the top and don't seem to be linked to the referring page content.

## Expected behavior
Either open to the top of the page or open to the privacy content that's most related to the referring page.

**Comment by desigonz** [comment]
Folded this in #4053
