### ISSUE TITLE
Unpublished page still appears on topic

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#4042]
## Describe the bug
While troubleshooting #3818, @chiaberry fixed it so unpublished pages don't slip through the site structure. I tested unpublishing the "Get bulk items collection" page. The page is now unpublished (it [404s](https://janis-3818-event-home.netlify.com/en/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup/)), but it's still appearing on the topic page.

![image](https://user-images.githubusercontent.com/5839508/75397957-e575fe80-58bd-11ea-9e83-9fce3528f8f0.png)

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to a Joplin PR branch
2. Unpublish a page that lives within a topic
3. Wait for the site to build with the unpublish
4. Go to the topic that that page used to live on

## Current behavior
Unpublished page is still listed on topic. When you click the link, it takes you to a 404 page.

## Expected behavior
Unpublished page no longer listed on topic

**Comment by chiaberry** [comment]
the janis is: https://janis-4042-unpub-page.netlify.com/

the joplin is: https://joplin-pr-4042-unpub-page.herokuapp.com/

ways to test: 
https://alpha.austin.gov/en/parks-and-recreation/ is in draft form, but you can see it
https://janis-4042-unpub-page.netlify.com/en/parks-and-recreation/ 404s

**Comment by chiaberry** [comment]
@desigonz you QA'd this, right? just double checking b/c there is no label

**Comment by desigonz** [comment]
Ahhh sorry, I published on Joplin and forgot to come back after the build. QA passed!
