### ISSUE TITLE
Design: events on info, service pages, and location pages

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#4043]
### As a resident, I want to see events related to some information or a City service, so that I can make plans to attend a relevant event.

We can split this issue into the Janis/Joplin sides if that makes sense.
- [ ] What does this look like for the resident side of things?
- [ ] What does it look like for an author to add these?

**Is your feature request related to a problem? Please describe.**
For the Community Police Review Commission content (see @srigdon's [doc](https://docs.google.com/document/d/1GCEpQNQflrcbpizBZzzRQ5BII1S9kKDkJhvkFnlOGnc/edit#)), we plan to have an information page about the commission, and want residents learning about the commission to be able to see all upcoming public meetings. This will be useful for many other use cases in the future!

**Describe the solution you'd like**
- [x] A way for events to appear on information pages: block component inserted below `body `content, and before `footer` content
- [x] A way for events to appear on service pages: `page picker` component

**Describe alternatives you've considered**

**Additional context**
- Abstract branch: https://share.goabstract.com/bf090de4-48ad-4c3e-80bc-2e3b17a62e60
- Abstract collection within that branch: https://share.goabstract.com/a215a3e1-a703-48f5-9bbe-9d22bdf60db1

**Comment by desigonz** [comment]
More examples where we might want events:
- https://alpha.austin.gov/en/health-safety/health-prevention/disease-prevention/help-prevent-diabetes-in-your-community-2
- @Jo-Dwyer's writing a service page on resolving parking tickets. She'd want to pull in amnesty days

**Comment by desigonz** [comment]
### Considerations

Joplin
- Use page picker pattern
- Business requirements like how many events on a page
- What happens once an event is over?
- Consider where the connection is made: service/info ---> event vs event ---> service/info

Janis
- What happens once an event is over? Probably consistent with home and list views—drop off once the date has past

Content
- Copy on that page that refers to that event (probably want to discourage non-evergreen event content outside of the event content type)

**Comment by chase-vert** [comment]
Janis options to try
- [ ] Rail
- [ ] Body
  - [ ] Block below body content. Consider the case of pages with a lot of content
  - [ ] Block above body content
  - [ ] Inserted within body content

**Comment by chasechenevert** [comment]
# Pin-up notes
- go with the option that matches the implementation we currently have for tiles and locations on service pages. 
- we’ll place them below body content, above the footer for now and see how that feels
- if there are no events to display, the component won’t display (heading)
- I’ll replace the dummy info with real content from @Jo Dwyer, and mockup the tablet and mobile views with an XD prototype link so that we can get a truer representation
- follow-up will be Thursday, for a mini pin-up

**Comment by chase-vert** [comment]
# Dev/design sync notes
- Brian is breaking this out into issues
- `Locations` and `Events` are already associated (you have to include a `location` for an event), and the consensus is that this should be easier to do than adding them to `service` and `information pages`
- `location` page with `events`: https://share.goabstract.com/852ed7b8-f2da-427c-bcf6-e3c3a5055156?mode=design&sha=b366e13abf2185f3493797bc6ac7eeafc8e34ee2

## Follow-up
- include edge cases for the number of events listed, and finalize the logic around that
- include tablet and mobile breakpoints in the next round for all page types: `info`, `service`, `location`. Tablet is usually almost exactly the same as desktop, so this shouldn't take too much time
- `search` mvp specs should be finalized and delivered to dev Thursday

**Comment by chase-vert** [comment]
MVP designs are complete. Created https://github.com/cityofaustin/techstack/issues/4235 for dev hand-off.
