### ISSUE TITLE
Line height on locations in steps on mobile

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#4044]
### As a [mobile user] I want [locations in buttons on steps to be easy to read and understand] so that [I can read and understand the locations and addresses being presented to me].

**Is your feature request related to a problem? Please describe.**
Comment in here: https://github.com/cityofaustin/techstack/issues/3975

view [this](https://alpha.austin.gov/en/housing-utilities/pay-utility-bills-and-rent/get-help-paying-bills/get-help-with-rent-and-utility-payments/) on mobile to see

**Describe the solution you'd like**
Todo

**Describe alternatives you've considered**
Keeping it as is

**Comment by desigonz** [comment]
@chasechenevert Can you define the line spacing?

**Comment by chasechenevert** [comment]
try `1.8 rem` for both `location name` and `address`

**Comment by desigonz** [comment]
Thanks @chasechenevert!
