### ISSUE TITLE
Editors/moderators MUST belong to a department

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#4046]
### As an administrator, I want to make sure that an editor/moderator belongs to at least one department, so that they can see content in the list view.

In #3920, we made it so an admin can assign a user to a department. And in #3780, we're going to make it so that an editor and moderator can only see and edit their department's content. We need to make it so that an admin MUST assign an editor to at least one department, so that that new user will actually see something when they login to Joplin.

**Acceptance criteria**
- [ ] Admin can't save a new user if they don't belong to a department.

More context in [this document](https://docs.google.com/document/d/1FY-enbU7mTFXR8vX2rG7FqnySRqsAFoB8Op1f_--v14/edit#)

**Comment by Niicck** [comment]
Link for QA:
https://joplin-pr-4047-separate-groups.herokuapp.com/admin/users/

**Comment by toribr** [comment]
- [ ] design passed!
