### ISSUE TITLE
Create new user: Separate editor/moderator from departments 

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#4047]
### As an administrator adding a new user, I want to be able to easily distinguish between editing/publishing permissions and department permissions, so that I can understand the difference.

**Is your feature request related to a problem? Please describe.**
In #3813, we have department permissions. Yay! But editors/moderators are lumped together with all the departments. That doesn't fit an admin user's mental model.

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/44ba0d07-d.2d2-4585-b6da-d75a745aa911)

For MVP, we'll want to separate these.
- [x] @desigonz to draft permissions table with departments now included
- [ ] Run by @briaguya, content, and design. We'll need to hone in on an MVP solution for this that separates them out. Might include changing how we display roles—maybe it's:
  - "is part of department"
  - "is part of department" + "has publish permissions"
  - "is part of department" + "has admin permissions"

**Comment by desigonz** [comment]
Permissions model, now with departments: https://docs.google.com/spreadsheets/d/1zE_Y806MlCli1aSkzIbXTzCTA01KWSReLGrJ7b5sUYU/edit#gid=0
Vetted this with content team and @toribr, so we've defined our ideal steps.

Scheduled time to review with @briaguya tomorrow.

**Comment by Niicck** [comment]
Link for QA:
https://joplin-pr-4047-separate-groups.herokuapp.com/admin/users/

When creating or editing a user, "groups" are now split up into "role" and "department" sections.

**Comment by toribr** [comment]
- [ ] design passed!
