### ISSUE TITLE
Privacy Badger - recollect

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#4051]
If you have privacy badger blocking recollect.net, then you just end up with a constant loading wheel.
(example here: https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/compost-food-waste/set-out-your-leaves-grass-and-branches-for-pickup/)

Maybe we can build out something like what we have for when forms don't load?

**Comment by desigonz** [comment]
Duplicate of #3988 :)
