### ISSUE TITLE
Don't maintain scroll position when opening a new Link on Janis

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#4053]
## Describe the bug

Links to other pages on Janis (that are in a `react-router` Link component) will open the next page at the same scroll position as the previous one. Not at the top of the new page which is how I, Chia, expect it to be. 

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to alpha.austin.gov
2. Scroll down to different positions within the page and click the links
3. See that the resulting page is at different positions as well. Check out these screen shots

## Current behavior
 ![Screen Shot 2020-02-28 at 10.09.25 AM.png](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/0887d1c2-3bcd-4bd2-899f-bbaae663e7c9)![Screen Shot 2020-02-28 at 10.09.33 AM.png](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/49924e33-6b95-4411-9ca1-6ab1d2b25b38)
![Screen Shot 2020-02-28 at 10.09.46 AM.png](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/51f504e6-7bd4-4b6e-a9f4-3156aaeda5b8)
![Screen Shot 2020-02-28 at 10.09.53 AM.png](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/9fdd54ea-cabf-4365-8703-d55c7d17d635)

## Expected behavior

Start at the top of the next page? 

https://medium.com/@nasir/reset-scroll-position-on-change-of-routes-react-a0bd23093dfe
https://stackoverflow.com/questions/45583358/open-link-at-top-of-page

## Device and browser

Chrome

**Comment by desigonz** [comment]
Also reported in #4040. 

## Test cases
For each of these cases, scroll to where it is, and test that it opens at the top of the page, not scroll position
- [ ] `Privacy policy` in footer
- [ ] "Check out City of Austin services" on homepage—scroll down to a service and click the service card `Get immunizations for you and your family`
- [ ] On the [Get help with paying rent and utility payments](https://alpha.austin.gov/en/housing-utilities/pay-utility-bills-and-rent/get-help-paying-bills/get-help-with-rent-and-utility-payments/) page, click `St John Community Center` card

**Comment by chiaberry** [comment]
@desigonz  for QA: https://janis-4053-scroll-position.netlify.com/

**Comment by desigonz** [comment]
@chiaberry Fantastic—QA passed! Looks beautiful.
