### ISSUE TITLE
Strategy for City web SPOC survey

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#4056]
@anukandimalla and @desigonz to:
- [ ] see what data we can pull from Drupal already
- [ ] review @toribr's [research questions](https://github.com/cityofaustin/techstack/issues/3736#issuecomment-585961484) for content authors
- [ ] identify steps to move forward on this survey

Meeting scheduled for 3/2.

**Comment by desigonz** [comment]
potential questions for survey

Draft: 
* how many times a week or month do they use the system? 
* how many hours a week or month do they use the system?
* are they creating new content or editing existing content or both?
* Are they writing in the tool or cutting and pasting from elsewhere? if cutting and pasting, then from where? how does formatting change? 
* Is their work moderated or approved by someone else, and if so, how? (physically how - sent via email, in person, paper, what?)
* how many people in the approval process?
* how many in their office touch drupal?
* what types of content do they usually work with? give list: events, news, information, etc - may need descriptions so they can decide 
* approx age (or do ask about other types of content making apps they use, ie, previous experience with Wordpress, squarespace, etc.)
* what other tools, software or websites do they use in their content-related work
* do they use google analytics? if so, what do they look at?
* what size monitor do you use?
* what dept are they in?
* do they do any translations? if so what language?  META or GAnalytics (all authors)
* How often is content changed on the system? by everyone?  (get files) • Can this be broken down into chunks, ie, 10% changed every week (perhaps logs will show this?)
*  what screen size (%’s)
* browser (%s)

**Comment by anukandimalla** [comment]
Here is the document for the Web Spoc Survey questions strategy
https://docs.google.com/document/d/1AxWPcu9kSaBBMJCAJK045tuBs-4Kf0dAoMRnCAvD4Jo/edit?usp=sharing
