### ISSUE TITLE
Homepage v2 design drafting

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#4070]
Some links for breakout
- [ ] https://docs.google.com/presentation/d/1YUNrIyufmE9xaa44D_Tl6na8gJjg3PuyiF09PCPJ_L4/edit#slide=id.g80ec3012a1_1_140

- [ ] https://oneaddress.fortworthtexas.gov/

**Comment by toribr** [comment]
Closing this; pickup at #4406
