### ISSUE TITLE
Localize documents in official documents

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#4076]
## Acceptance criteria 
- [ ] On Joplin, a user can add a Spanish version of a document (without it swapping out the `en` one)
- [ ] If on Joplin there is a Spanish doc in the previous acceptance criteria: On Janis, when a user toggles to `Español`, a user clicks the link for the doc and the Spanish version of the doc opens.

----- 

## Describe the bug
Janis shows the English version of document, and Joplin doesn't allow for localized Spanish doc

## To Reproduce
Go to https://alpha.austin.gov/en/police-oversight/office-of-police-oversight-official-reports#1
Switch to Spanish
Click a document link
Observe english document

## Current behavior
A clear and concise description of what happened

## Expected behavior
A clear and concise description of what you expected to happen

**Comment by desigonz** [comment]
Documents aren't localized for Spanish and English in the data model on the Joplin side. That makes sense for OPO's disciplinary documents, which are official documents with things like redactions and signatures that make it difficult to translate, so we just include the translated description, but link to the document. cc @srigdon and @toribr.

However, @ablangworthy27 was trying to publish the translated full racial profiling report. Amanda, did that come from OPO directly, or was that something we did?

Would love to hear y'all's thoughts. We'll need to decide if we _want_ localized document uploads for official document entries before moving forward.

**Comment by ablangworthy27** [comment]
@desigonz the translated report came from OPO.

**Comment by desigonz** [comment]
Okay good to know! Sounds like that's a user need, then. @srigdon/@toribr, any additional thoughts?

**Comment by toribr** [comment]
So, in the SP version, the link would be in Spanish and link to the Spanish doc? In that case, then it seems like the 1-1 relationship we hope to have with translations would work, ie, user enters Spanish version, and links to the Spanish document. Is that what we're thinking?

**Comment by desigonz** [comment]
Yep, that's spot on! And for disciplinary docs that we don't translate, the link to the English doc will still appear. I'll update acceptance criteria above.

**Comment by toribr** [comment]
Sounds good. If no Spanish doc is linked, then system will show the English version.

**Comment by briaguya** [comment]
I tried just adding `document` to our `OfficialDocumentPageOfficialDocumentTranslationOptions` in `translation.py` and making/running migrations. It did not work as expected (docs gone, translated version of docs field not showing up in editor -- not just a js issue, definitely deeper than that) I spent a couple hours poking around/googling wagtail-modeltranslation foreign key issues but didn't really get anywhere. I'm going to up this one to a 5 and unassign myself from it.

**Comment by easherma** [comment]
Can you at least note the issue with the exact errors you ran into and what you tired so whoever picks it up has somewhere to start from?

Also at that point if it really isn’t going to work couldn’t we just manually make the field for Spanish document similar to what we do for Streamfields?

**Comment by briaguya** [comment]
@easherma that was going to be the next thing I tried if I stayed on the issue after getting out of the wagtail-modeltranslation rabbit hole

**Comment by chiaberry** [comment]
@ablangworthy27 for testing
https://janis-4076-local-docs.netlify.com/es/health-safety/policing-in-austin/police-feedback-and-records/official-complaint-and-discipline-documents/#1
is the janis

and https://joplin-pr-4076-local-docs.herokuapp.com/admin/pages/search/ is the linked joplin. 

I replaced the first entry on janis (the last one on joplin) with a fake spanish pdf, you can see it by clicking the first document on janis. other documents that were not replaced with a spanish one still have the english document.

**Comment by ablangworthy27** [comment]
This looks good!
