### ISSUE TITLE
Draft service page: Get information about a traffic or criminal violation and pay online

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4078]
### You can find information about your criminal or traffic violation case online. You can use this online case search to pay a ticket or to find out a judge's decision.

This online tool will only find cases handled by the City of Austin Municipal Court. If you got a ticket outside of Austin or if it was written by anyone other than a City of Austin enforcement officer, you can't lookup your case or pay a ticket using this tool. 

To look up a criminal case or a traffic violation you'll need:
-  your last name and date of birth
- your driver's license number
- case number 
    - case number can be found by calling the municipal court or by looking it up using one of the other pieces of information.

https://www.austintexas.gov/AmcPublicInquiry/search/psnsearch.aspx

**Comment by gabrielaperezdelaosa** [comment]
See here: https://docs.google.com/document/d/1Nmhrts1_J-8zoi99C9egoKZ2rkfC_RDWIOhGgoQtXFI/edit?usp=sharing

**Comment by srigdon** [comment]
Reviewed, edits made in Joplin. Several links on the page go to pages that aren't published, yet, so those need to be published before this one is. A list of those is in the Notes tab.
