### ISSUE TITLE
Draft service page: Get information about a court appearance online

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4079]
You can find out when you need to go to court online.

If you have received a ticket that is handled by City of Austin Municipal Court, you can lookup the date and time  of your scheduled court appearance, as well as the charges against you. This online tool will only find cases handled by the City of Austin Municipal Court. If your case is being handled by any other court, your scheduled appearance will not be listed on this schedule.

To look up your scheduled court appearance, search by your last name. There may be more than one person with your last name, so look for your first name and middle name well. 

https://www.austintexas.gov/AmcPublicInquiry/search/vclsearch.aspx

**Comment by Jo-Dwyer** [comment]
Edit to include information about online dockets. Link to form: https://cityofaustin.formstack.com/forms/questionnaire_for_virtual_hearing

**Comment by Jo-Dwyer** [comment]
This can stay backlogged, since there are no in person dockets currently.

**Comment by gabrielaperezdelaosa** [comment]
this morphed into a "Lost Ticket" page.
@ablangworthy27 for review

**Comment by ablangworthy27** [comment]
@gabrielaperezdelaosa Can you provide a link? Not sure if your draft is in Joplin or Google docs, but either way I can't seem to find it.

**Comment by ablangworthy27** [comment]
For the [Lost ticket page](https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxMzA3), I added headers to break it up and make more scannable.
