### ISSUE TITLE
Write text for "Why the delay?" link from publishing banner

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4081]
Include information about:
- build time
- what else?

@srigdon @desigonz

**Comment by desigonz** [comment]
@toribr, by when do you need this copy?

**Comment by toribr** [comment]
@desigonz End of week would be great, but EOD mon would also work. Sooner is always better.

**Comment by desigonz** [comment]
Thanks @toribr! @srigdon, what seems doable to you?

**Comment by srigdon** [comment]
@toribr @desigonz I can do end of week.

**Comment by desigonz** [comment]
Excellent!

**Comment by srigdon** [comment]
@toribr [See copy here](https://docs.google.com/document/d/1R7cAKk61LQ7QxYHitmZJqrd9o4t3FcxaVCYDOpZuD3k/edit#), come at me with questions.

**Comment by toribr** [comment]
What would you think about moving the "how long it takes" up to the first sentence? And instead of saying publishing, say something like, it takes 5-10 minutes before your updates will go live on the website.

**Comment by srigdon** [comment]
@toribr Good call, I can make that change.
