### ISSUE TITLE
Interview work for Content Strategist (Spanish)

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#4084]
We need a good list of interview questions to vet with Language Access and potentially our content friends at CDS. We also need a Spanish test or equivalent work assessment. 

- [x] Compile a [list of questions](https://docs.google.com/document/d/13hT4C8S89oKy259nioxQduPsFaqdoyeX_BHapfihnzo/edit#) we have for the person in this role. To be done by: @srigdon @ablangworthy27 @Jo-Dwyer 
- [x] Share with Language Access and ask for their feedback and sample work assessments they've seen. 
- [x] Ask LA to help with interviews. @Jo-Dwyer 
- [x] Share with CDS and ask for their feedback and sample work assessments they've seen.

**Comment by Jo-Dwyer** [comment]
Notes from Houmma Garba

Fluency is someone who can navigate between the target language and English. They should complete a fluency test that indicates that they can work at a professional level. A test that could indicate this: there are companies that provide this and CoA also offers a test. 

Bilingual speakers may or may not have ‘fluency’—simply means that they speak two languages. Bilingual speakers can fail fluency.

- What is the person’s experience in translation? Not just ‘bilingual’ or majored in Spanish or a native speaker. 
- Have the person provide us with material that they have translated
- We can also choose a text and give it to the candidate to translate in person. 
    - Talk to CTM HR about how to develop the questions. The questions must be the same for all candidates being interviewed. After translation, we can use the translation vendor to read the translation, and ask the vendor for fluency level of the translation by the candidate.

Whitney Sklar is CTM’s Language Access Plan point of contact. 

At this time there is no focus on content creation within the Language Access community of practice, but Houmma encourages that this person could help to develop that!
