### ISSUE TITLE
Assigning departments to topics and topic collections?

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#4085]
We're implemented department permissions that make it so that a user selects a department when creating a page, so that it has departmental permissions. But we're thinking of limiting the creation of topic and topic collections to admins, who will decide the direction of the IA. Does this mean we don't need this section here?
 

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/ddb088ad-3d5c-4757-860c-410a46332857)

**Comment by toribr** [comment]
This issue no longer relevant, as it was fixed when departments and authors were correlated.
