### ISSUE TITLE
non-abstract JanisBasePage, move pages into Django apps

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#4089]
this exists in v3: https://github.com/cityofaustin/joplin/pull/606

### for this, we need to have
* /joplin/pages/
* /joplin/pages/base/ (JanisPage (instances come later))
* /joplin/pages/department/ 
* /joplin/pages/location/
etc...

so instead of importing from joplin.base.models for our pages we can import from joplin.pages.page_type, with every page inherit from a non abstract base page

### after this we will need to
* see what options we have for migrating data
* use the new structure to better understand how to implement PageInstances

**Comment by easherma** [comment]
Dumping all my notes/links on doing this:
https://medium.com/@sh.hooshyari/how-to-correctly-refactor-django-project-moving-models-cb634c57e0
https://stackoverflow.com/questions/30601107/move-models-between-django-1-8-apps-with-required-foreignkey-references/30613732#30613732

One helpful cheat can be to set your model's database name to the name in its old location. I did this a few times on a project that kept getting refactored but we were not in production so the data I was preserving wasn't super valuable.

My thought was 1) tell everyone they can't edit  2) move the code where you want it to be - but with the table name explicitly the old table name.

if that works, then drop your migrations, rename your tables (in the database itself), and recreate initial migrations as if things had always been where they are now
