### ISSUE TITLE
Guide preview not working

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#4090]
## Describe the bug
Preview is not working for the mobile food vendor guide in either language. 

## URL
https://alpha.austin.gov/en/preview/guide/UGFnZVJldmlzaW9uTm9kZTozNDQy

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to edit the mobile food vendor guide in Joplin
2. Toggle to Spanish and add some translations to the title, description and headings
3. Push preview
4. See error in new window

## Current behavior
The preview window says "loading", but it never actually loads.

## Expected behavior
The expected behavior is that I can see the edits

## Screenshots
![Screen Shot 2020-03-04 at 12.34.32 PM.png](https://images.zenhubusercontent.com/5d6e8f01caef900001337734/70bc7fae-303c-4bd6-b8f0-09a503970c50)

## Device and browser
Chrome

## Additional context
I can't continue updating the guide with Spanish translations because it is impossible for me to check my work. This is blocking [#3608](https://github.com/cityofaustin/techstack/issues/3608)

**Comment by easherma** [comment]
https://alpha.austin.gov/en/preview/guide/UGFnZVJldmlzaW9uTm9kZTozNDQy

Looks like we fixed it!

**Comment by ablangworthy27** [comment]
@easherma The preview is not working for Spanish is not working. Is this a different issue? 

https://alpha.austin.gov/es/preview/information/UGFnZVJldmlzaW9uTm9kZTozNDY3
