### ISSUE TITLE
Turn permissions spreadsheet into issues

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#4091]
we want to take the rows in https://docs.google.com/spreadsheets/d/1zE_Y806MlCli1aSkzIbXTzCTA01KWSReLGrJ7b5sUYU/edit#gid=0 and turn them into issues with exit criteria that can be used to write unit tests etc.

Let's make some issues!

**Comment by desigonz** [comment]
You started this last sprint—closing this issue.
