### ISSUE TITLE
Permissions - view content on list page

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#4097]
from https://docs.google.com/spreadsheets/d/1zE_Y806MlCli1aSkzIbXTzCTA01KWSReLGrJ7b5sUYU/edit#gid=0

Exit criteria:
* On the page list/search page
  * As an editor/publisher in a department
    * I can see/search for the pages in my department
    * I cannot see/search for pages that are not in my department
  * As an admin
    * I can see/search for all pages

Unknowns:
* What kind of automated testing can we do here?

**Comment by briaguya** [comment]
I think this is anywhere from a 2 to a 5, I think the functionality and testing it manually would be a 2, but figuring out how to write unit tests for what we can see would make it into a 5

**Comment by chiaberry** [comment]
https://github.com/wagtail/wagtail/blob/982b1d60a4b3d5b4e841f2b39e2244bcb421b091/wagtail/core/models.py#L1853

https://github.com/wagtail/wagtail/blob/master/wagtail/admin/views/pages.py#L63

https://github.com/wagtail/wagtail/blob/982b1d60a4b3d5b4e841f2b39e2244bcb421b091/wagtail/core/tests/test_page_permissions.py

**Comment by Niicck** [comment]
Acceptance Criteria:
- [ ] limit what pages authors see on content_list view based on their departments (unless they are superadmins).
- [ ] limit what pages authors can search for in the content_list view based on their department (unless they are superadmins).
  - [ ] Question: Is this the flow we want? Or should we allow user to search (and view) any pages.

**Comment by toribr** [comment]
Answer: Authors can see only content based on their department, and that content is the exact same content that is used for search.

Users can not search all content or pages outside their department.
