### ISSUE TITLE
CMS - Landing/Index of Pages Table

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#410]
Pages Index Table
-  [x] sortable by `updated_at`, `type`, `status`

- [ ] Make sure actions work: 
  - [x] edit
  - view: https://github.com/cityofaustin/techstack/issues/578
  - [ ] share - need design input. Does is copy a link for live pages? Does it share a preview link for drafted pages?
  - [ ] more - what actions do we want in the dropdown? Right now it has, move copy delete unpublish and revisions. Move seems irrelevant for us

"More" Button on each row in Index of Pages Table
- [ ] short URL - dev not sure what this means, is this the same a Share?
- unpublish (based on authorization)
- archive

- [ ] Search Component
- search by `title`, maybe `name`

- [ ] Page Index Table Filters
- filter by:
  - All (default)
  - Published
  - Draft
  - In Review
- also make Achieved toggleable. Default to hiding Archived

- [x] Pagination
- paginate and change how many rows at a time, 10, 25, 50

**Comment by mateoclarke** [comment]
@toribr Can you share any screenshots or mockups for this?

**Comment by toribr** [comment]
![page list](https://user-images.githubusercontent.com/3790067/41121719-e03f46b4-6a5e-11e8-8ed5-73bdc6aa0d6c.png)

Please note: not final visual
I am currently working on a version which will include tech specs for functionality.

**Comment by toribr** [comment]
Removed "dashboard" from issue title as it's not really a dashboard, and I don't want us getting confused.

**Comment by toribr** [comment]
![pearl content list](https://user-images.githubusercontent.com/3790067/41242889-66f4a33e-6d66-11e8-8e78-42c5bb7c31f2.png)

Updated "view" specs.

**Comment by toribr** [comment]
![pearl content list specs](https://user-images.githubusercontent.com/3790067/41539756-38bb8e88-72d4-11e8-8794-63570148474e.png)
Includes some notes for archived view, which does not offer "more" button.

**Comment by toribr** [comment]
![content map of roles permissions and status](https://user-images.githubusercontent.com/3790067/41539831-61a82a90-72d4-11e8-985e-dc7891aed0f6.png)

Map of how authors and publishers can access content of each status type, what they can do with it, and the resulting status of that content.

**Comment by mateoclarke** [comment]
Closing this out since these requirements came from the decouple strategy. Much of this comes out of the box in Wagtail and we've broken out remaining customizations in there issues:

https://github.com/cityofaustin/techstack/issues/582
https://github.com/cityofaustin/techstack/issues/583
https://github.com/cityofaustin/techstack/issues/584
