### ISSUE TITLE
Publish queue usability tests

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#4121]

**Comment by toribr** [comment]
Testing complete.

**Comment by anukandimalla** [comment]
[Usability Test synthesis and findings documentation(1st design iteration)](https://docs.google.com/document/d/1z2LrKm6AmGrleUNBT3X86DNtaBwDf_IMLPADxSnO1Gc/edit?usp=sharing)
[Usability test synthesis and findings documentation(2nd design iteration)](https://docs.google.com/document/d/1rGFsnG_TWS83mSPDCeD7QQNG6P13iY8h86Hg85RLJzk/edit?usp=sharing)
