### ISSUE TITLE
Web SPOC research

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#4123]
- [x] Touch base with Nikhilesh and CPIO re: web SPOC data
- [x] Begin tracking user data

**Comment by anukandimalla** [comment]
Reached out to Nikhilesh but couldn't get hold of him but as one last try planning to reach Divya Rathanlal to find any available information on Database

**Comment by anukandimalla** [comment]
Here is the [document link for research](https://docs.google.com/document/d/1AxWPcu9kSaBBMJCAJK045tuBs-4Kf0dAoMRnCAvD4Jo/edit?usp=sharing)

**Comment by anukandimalla** [comment]
https://docs.google.com/document/d/1AxWPcu9kSaBBMJCAJK045tuBs-4Kf0dAoMRnCAvD4Jo/edit?usp=sharing
