### ISSUE TITLE
Implementation: Save and resume styling

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#4124]
### As someone using the "save and resume" feature on a form, I want styling to be consistent, so that I have a seamless experience.

Mocks on abstract: https://app.abstract.com/projects/065fcabf-a46a-4688-a858-83ce2117b16c/branches/master/collections/c901f0ef-71f4-4fe3-89ba-c2596b7e6e2a
- changed the title/label: "Save and Resume Later" to > "Save and resume later", but I welcome a content strategists review across this flow.
- Email validation, error messaging, success confirmation: these features seemed to be missing from the flow and I can't tell if it's a bug, or oversight in the feature on Formstack's end, so I made this issue: #4104

**Comment by Niicck** [comment]
- [ ] Style Modal
- [ ] Style Confirmation Page
- [ ] Change Copy

**Comment by desigonz** [comment]
🤦‍♀️ turns out I made this issue twice. Copying acceptance criteria from #4127

### Acceptance criteria
Mocks [home](https://share.goabstract.com/19525891-3c33-46a7-bd65-035f287c1549)
- [ ] Save and resume "are you sure" modal [matches mocks](https://app.abstract.com/projects/065fcabf-a46a-4688-a858-83ce2117b16c/branches/master/commits/2310b885a9d99d76dc1e114f4780ac97c2d82801/files/7b463232-16b3-4f77-b85f-0ada2d42ecb6/layers/807b46b5-ad9e-444d-9fbf-d8240bcb9d3a?collectionId=c901f0ef-71f4-4fe3-89ba-c2596b7e6e2a&collectionLayerId=f40bf69e-f528-46c5-8b0f-1990b483fbb3)
- [ ] Save and resume later email input screen matches mocks
  - [ ] [Desktop mocks](https://app.abstract.com/projects/065fcabf-a46a-4688-a858-83ce2117b16c/branches/master/commits/fd76d84074444d4e685932d38c585dddd3c5f42e/files/1f02fe06-f565-4099-9ea1-0ff092933fb5/layers/1a1fd5d7-6908-4b19-86b1-13655f6751ff?collectionId=c901f0ef-71f4-4fe3-89ba-c2596b7e6e2a&collectionLayerId=15441e4b-9521-4b21-af4c-eb2f446270b6)
  - [ ] [Tablet mocks](https://app.abstract.com/projects/065fcabf-a46a-4688-a858-83ce2117b16c/branches/master/commits/fd76d84074444d4e685932d38c585dddd3c5f42e/files/1f02fe06-f565-4099-9ea1-0ff092933fb5/layers/977406a8-b12f-4c5f-84a7-a8f9463f34ea?collectionId=c901f0ef-71f4-4fe3-89ba-c2596b7e6e2a&collectionLayerId=61d13deb-656d-4cd9-bfb6-ab8d3f16442d)
  - [ ] [Mobile mocks](https://app.abstract.com/projects/065fcabf-a46a-4688-a858-83ce2117b16c/branches/master/commits/fd76d84074444d4e685932d38c585dddd3c5f42e/files/1f02fe06-f565-4099-9ea1-0ff092933fb5/layers/e3eb69e9-3c2c-405a-83aa-850bc2c0c270?collectionId=c901f0ef-71f4-4fe3-89ba-c2596b7e6e2a&collectionLayerId=8522dd30-cef6-4d10-a6e5-e724b181320d)
- [ ] Error validation [matches mocks](https://app.abstract.com/projects/065fcabf-a46a-4688-a858-83ce2117b16c/branches/master/commits/b755fb302fd72e8caa75fe7b67ab0e3d46288140/files/1f02fe06-f565-4099-9ea1-0ff092933fb5/layers/7cc40cdf-7c33-42b0-b003-60870fd14230?collectionId=c901f0ef-71f4-4fe3-89ba-c2596b7e6e2a&collectionLayerId=ea5626f0-a809-4cd6-864b-4b757351231e) (we might need to spin this out into its own issue)

Additional notes from @chasechenevert:
- changed the title/label: "Save and Resume Later" to > "Save and resume later", but I welcome a content strategists review across this flow. 
- Email validation, error messaging, success confirmation: these features seemed to be missing from the flow and I can't tell if it's a bug, or oversight in the feature on Formstack's end, so I made this issue: https://github.com/cityofaustin/techstack/issues/4104

### QA notes
- [ ] Send to @chasechenevert to QA

**Comment by Niicck** [comment]
We're ready for QA:

A long example:
https://cityofaustin.formstack.com/forms/4124_save_and_resume_long
A short example:
https://cityofaustin.formstack.com/forms/4124_save_and_resume_styling

**Comment by desigonz** [comment]
Thanks @Niicck! I'll leave it up to @chasechenevert to QA.

**Comment by chasechenevert** [comment]
A few small things--mostly oversights on my part--then we're ready to go 🚀  

- [ ] Button label on the `save and resume screen`, and on the `success screen` seems to be falling back to browser default instead of `font-family: IBM Plex Sans` 
- [ ] `Save and resume` gray button 
  - [ ] Hover: `background-color: #e6e6e6` 
  - [ ] Label color: `#0050d8`
- [ ] Input field text size: currently at `12px`, let's bump this up to `16px` 

<iframe
  src="https://app.abstract.com/embed/19525891-3c33-46a7-bd65-035f287c1549"
  width="784"
  height="360"
  frameborder="0"
></iframe>

**Comment by desigonz** [comment]
Awesome, thanks @chasechenevert! And one tiny thing: is it possible to lowercase the R and the L here? Or is that Formstack?

![image](https://user-images.githubusercontent.com/5839508/76543433-e5006a80-645c-11ea-9bcf-41334d2ff74a.png)

**Comment by Niicck** [comment]
Yep, its possible. It's a formstack thing, but we can change the copy anywhere with the power of javascript. However, one thing I did not think about was handling translation for our custom copy on "Save and resume later".

**Comment by desigonz** [comment]
Ahh. Me neither!! I'll make a backlog issue for that. It's not a high priority for the CPRC form since commissioners need to be able to read English if they are accepted to the commission.

**Comment by desigonz** [comment]
Hmmm Formstack actually translates out of the box:
![image](https://user-images.githubusercontent.com/5839508/76623490-f5baea00-6509-11ea-9237-d30fb8875b91.png)
![image](https://user-images.githubusercontent.com/5839508/76623514-03706f80-650a-11ea-9fa7-3e9db3188f2e.png)
Is it easy to maintain those? Does changing the capitalization mean we don't maintain those?

**Comment by Niicck** [comment]
Changing capitalization is effectively the same as changing copy entirely. So we'll lose Formstack's automatic translation. But we have the ability to add our own Spanish translation manually, like we do for "Required" and "Obligatoria".

**Comment by desigonz** [comment]
Okay let's ditch capitalization and write backlog issues for doing those later.

**Comment by Niicck** [comment]
I went ahead and did all the translation stuff for our "Save and Resume" changes. There was actually a lot of custom stuff we added that broke out of the box translation, so I fixed it.

You can do a side by side to see a "Spanish" form with the new styling, vs. the old styling. There should be no language copy regressions.

https://cityofaustin.formstack.com/forms/4124_es_with_old_style
https://cityofaustin.formstack.com/forms/4124_es_new_style

I fixed the "Save and resume later" capitalization everyone we wanted it for the English form as well. And @chasechenevert's change requests have been applied. Those can be QA'd at the same English links:
A long example:
https://cityofaustin.formstack.com/forms/4124_save_and_resume_long
A short example:
https://cityofaustin.formstack.com/forms/4124_save_and_resume_styling

**Comment by chasechenevert** [comment]
Thanks for making those changes, @Niicck! Good to go on my end.
