### ISSUE TITLE
Draft a Request a deferral for a moving violation service page

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4132]
Defendants can ask for a deferral in judgement depending on what kind of crime that they've been charged with. If they can successfully complete the terms of their deferral, the case will be dismissed.

- [ ] Is it true? Yes.
- [ ] Is it readable? The current page is at a grade 9-10 level and uses unusual terms and jargon.
- [ ]  Is it actionable. Yes, the necessary information to fill out and submit this document is in the PDF and supporting information is on the current page.
 
Send for review by @srigdon, @ablangworthy27 or @Jo-Dwyer
### Disqualifiers:
You are not eligible for a deferred disposition on a moving violation if you:

- Are charged with:

    - Leaving the scene of a collision.
    - Passing a School Bus.
    - Received your citation while driving in a Construction Zone when workers were present.
    - Have a commercial driver license even if the violation occurred while you were driving a private vehicle.

If you request a deferral via email or mail and are not eligible, you will be notified, in writing, to select another option to handle your case.

### Payment
Organize as a step with options with an option for each offense type.
Fee differs by offense, information about this is in each pdf.

### Understand the terms of your deferral
Organize as steps with options.

### Submission methods
Organize as step with options.

Mail or in person. Payment must be made by check or money order. Defendants may contact the court if they can't pay immediately.

You must appear at court to request a deferred disposition if:

You are a juvenile (under the age of 17). As a juvenile, you must appear in person at the date and time assigned by the court prior to requesting a deferred disposition. Keep your address updated with the Court because notices will be mailed.

You are charged with a code violation (violation other than traffic, parking, red light camera, “no insurance”, no driver license or driving with license invalid, seat belt). You may contact the court to determine if you are required to attend an appearance docket.

The deferral form will not be transitioned yet. Upload it to Joplin and link to the PDF.
Moving violations deferral

**Comment by ablangworthy27** [comment]
@Jo-Dwyer Is this process already covered with #4066 ?

**Comment by gabrielaperezdelaosa** [comment]
covered in #4066
