### ISSUE TITLE
Create a "Prove you no longer own a vehicle" page

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4133]
If a defendant chooses to plead non-guilty because they were no longer in possession of the vehicle that was in violation, they can prove this to the court to clear the charges. The affadavit to declare non-liability gathers the necessary information for the judge to make a decision.

Information

[Declare non-liability form](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Affidavit-Declaration_of_Non-Liability.pdf)

This form will not yet be transitioned. Upload it to Joplin and link to the PDF.

**Comment by ablangworthy27** [comment]
@Jo-Dwyer on [this page](http://www.austintexas.gov/page/parking-tickets), the pdf link is different from what you have attached. Can you just confirm that the one here in the issue is the correct one?

**Comment by Jo-Dwyer** [comment]
There are actually two different affidavits, and the one written above is now out of date:
- [one for parking offenses](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Affidavit_-_Parking_Non-Liability01_2020_Revised.pdf)
- [one for red light offenses](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/Affidavit_-_Camera_Red_Light_Non-Liability.pdf)

**Comment by InaraFernandez** [comment]
Is this content available in Spanish?

**Comment by srigdon** [comment]
Content debt: digitize the affidavit form --> #4705

**Comment by srigdon** [comment]
[Prove you weren't responsible for a disabled parking offense](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxMjY4) is ready to publish, but the topic page picker isn't surfacing the [Handle a ticket](https://alpha.austin.gov/en/permits-tickets/handle-a-ticket/) topic page at the moment.
