### ISSUE TITLE
Prep for March 25 Funshop 1: Writing for residents

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#4134]
- [x] Review the deck for ideas on what needs to be updated and what can be improved quickly.

**Comment by desigonz** [comment]
- [ ] Rework the deck for a remote presentation.

**Comment by srigdon** [comment]
- [ ] Make sure the post-workshop survey still makes sense. 
- [ ] Write and send follow-up email to participants. Include: slide deck, resources for working remotely, best examples of COVID-19 outbreak communications
