### ISSUE TITLE
Dev Team  - Authentication Ownership Inventory

### ISSUE THREAD

**Issue by robbobfrh84** [cityofaustin/techstack#4138]
We have several platforms with different owners and avenues to get added and removed. With @desigonz  transitioning, I thought it might be a nice time to have this stuff documented. 
- I see this as a rolling issue until it's complete and the documentation finds a home.

Why? 
- It'll make it easy to find out who has the ownership when needing access for future devs,
- Make modifying access for future teams easier
- Shows us where we're missing actual authentication powers!

### Platform Inventory List (Please add anything I've missed...) 
- Huroku 
- AWS 
- Github (Who adds/removed contributors) 
- Formstack 
- Netlify 
- CircleCI
- Google Analytics 
- ....
- *example platformz

# Questions?...

- Where should we keep this list? 
- Would it be worth creating a COA-dev in some cases to be the owner so that transitions of the dev team are less tangled...?
- Should we address keys/passwords and such, where could those live?
- ...

# Details 

### Example Platformz 
- Owner: Janis Joplin 
- Owner Username: JanisJoplin43
- Owner Email: Janis.Joplin@austintexas.gov
- ...

**Comment by easherma** [comment]
This is a great idea!

Most of this is stored under 1Password, there is a 'Developers' vault under our organization's 1Password

There may be other additional places where this either was documented but fell out of date or where it could be documented. @oliver2g might have some ideas there. 

I'd suggest that we migrate whatever isn't there to be there and have that be the source of truth. It has the advantage of being more secure and centralized in a pragmatic way.

**Comment by oliver2g** [comment]
when Sergio was on the team, we transitioned all the logins we knew about from a google doc to 1password. Everything that I know about is there. Other things might still be in other places, especially dev tools which i generally didn't touch.

**Comment by robbobfrh84** [comment]
So, I feel silly. I was about to say "I haven't set up an account with 1password yet"
-
But... tried to log in and it said It was created on sept 3! that was my first day...🙃 
-
So, looks like i need to be helped back in as it's asking me for a secret key, and then says to...
`Ask your administrator to help you recover your account.`

**Comment by robbobfrh84** [comment]
Either way I'll update here with what we have and see if it can just all be consolidated there.

**Comment by robbobfrh84** [comment]
Thanks for gettin' me plugged back into 1password. I'll go through what we have hear and report back to this issue.

@easherma I see a ton of platforms we use in the "All Vaults" but no "Developers" vault? Hmm... Is that something I'd have to be added to in addition within 1password?

**Comment by robbobfrh84** [comment]
I'm closing this because everything looks to be handled in 1password now.
