### ISSUE TITLE
Search: UI design iterations

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4145]
# Goal
Come up with a few different approaches to the visual design of the search experience from performing a search in the `primary nav` to getting a result on the `search page`.
- Results should be easy to scan and read, so the user can make an informed decision about what they want to click
- Starting a search from the `primary nav` must be easy to find; don't rely on an icon alone.

## **Dev/Design sync**  3-27
- Collection: https://share.goabstract.com/0f3dad6e-7205-4df5-9d66-ab52406b2d79
- XD prototype: https://xd.adobe.com/view/45de5a8d-bfc3-46b8-6ce7-1490703f9750-33ef/?fullscreen

### Primary nav button/component
- [ ] Lockup: label + icon (figure out the best order)
- [ ] Button states
  - [x] Default
  - [x] Hover
    - [x] input field is populated: background-color: ; search icon goes away, label slides left, right arrow (trailing) appears on the right side, indicating a page change
    - [x] input field is not populated: only background color changes 
  - [ ] Active/selected
- [ ] Responsive sizes 
  - [ ] desktop
  - [ ] tablet
  - [ ] mobile

### Input field
 _surfaces when the search button is clicked_
- [ ] States
  - [ ] Default
  - [ ] Hover
  - [ ] Active/selected, and populated
- [ ] Responsive sizes 
  - [x] desktop
  - [ ] tablet
  - [ ] mobile

### Nav interactions
- [ ] close affordance
  - [ ] clicking away (outside) container
  - [x] selecting [ X ]
  - [ ] keyboard:  `escape` key
- [x] submit affordance
  - [x] tap `search`
  - [x] tap `enter` on keyboard
- [ ] pressing `search` button when there's no input: 
 
### Search page
- [ ] `Text field` with `search button`
- [x] Result summary: "1–10 of 1,655 results"
- [x] "Showing results for [search query]"
- [ ] Max per page: 20 as a starting place
- [ ] Responsive sizes 
  - [x] desktop
  - [ ] tablet
  - [ ] mobile
- [x] Pagination component
- [x] Null state
  - [x] 0 results
  - [x] Title: "There are no matching results." Content Strategy team can finesse this

### Entry
- [x] Title
- [ ] Description
  - [x] with description
  - [ ]  without description
- [ ] Offered by, related to, department
- [ ] Labels: PDF documents, locations, services
- [ ] Responsive sizes 
  - [x] desktop
  - [ ] tablet
  - [ ] mobile

### Out of scope for MVP, but it wouldn't hurt to consider:
- [x] Filters (Topic, Department, Contacts, Events, Media (photos, images), Services, Locations)
- [x] Labels
- [ ] Suggested searches

---
**Background**
- Research [google doc](https://docs.google.com/document/d/1C2I2Sery8GbBkeIdgBHxIAAqT344Laqc5dM1Y0q5g74/edit)
- https://github.com/cityofaustin/techstack/issues/4111 requirements brainstorming meeting

**Comment by chasechenevert** [comment]
## Pin-up follow-up
- [ ] Nav footer: match implementation
- [ ] Input field: use the secondary option
- [ ] Result list: add topic and offered by, static and not link
  - [ ] no department to display?
  - [ ] multiple departments to display?
- [ ] Links: title add underline
- [ ] List: use the second list style where the attributes are below the title
- [ ] List / descriptions  take some descriptions from Janis for min/max values
- [ ] Null state

**Comment by chasechenevert** [comment]
# Round 2
### Options
- Basic: lists topic and department beneath the description
- Basic - no underline: removes underline from link titles
- Basic - overline: moves topic above link title to break out the topic for scanning
- Labels: treats topic and department as static visual labels
- Labels - in-line dept: places department ahead of description, styled with a lighter shade of gray to help with scanning the list

### Questions
- are there any options here that feel comfortable for scanning?
- while this result list is hypothetical, it illustrates how many different content types could end up in one result. which list type helps you scan through the results to understand what the list item is?
- these are real descriptions taken from Alpha. is there enough information for you to understand what the page is about?
- what could make this better?

**Comment by chase-vert** [comment]
Closing this out since the UI iteration portion of this issue are complete.
