### ISSUE TITLE
Homepage: COVID-19 alert

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#4149]
Let's get a scrappy `alert` that links to City of Austin COVID-19 page over to dev by noon!

https://share.goabstract.com/bd4e4a4e-8334-468e-84d8-242c5d826b48

- Yellow background and black foreground meet AAA standard
- Utilized the labels we’re developing on the Joplin side to give this an alert type (could come in handy in the near future)
- External link icon so that users are aware they’ll be taken away from this domain

Requirements
- [x] Desktop
- [x] Tablet
- [x] Mobile

**Comment by Jo-Dwyer** [comment]
> "Get current information about coronavirus (COVID-19) in Austin"
> "Obtenga informácion actual sobre el coronavirus (COVID-19) en Austin"

@desigonz can you do a quick translation verification on that Spanish text?

**Comment by desigonz** [comment]
@Jo-Dwyer Looks good to me!! I can run it by my parents too.
