### ISSUE TITLE
CMS - Create Content Modal Flow

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#415]
- Modal experience will lead user to existing edit <content-type> page -- will will utilize existing bootstrap and jqueryUI utilities on page rather than attempting to build with an independent js build process.
- Themes/Topics selection will be hard-coded to the depts/content we’re currently working with (for now)

_from https://docs.google.com/document/d/1znAEqCRBMJhBuyHJ3KGYUWtqFRTbtub5jMgCcg5qf1k/edit#_

### workflow 

- "create new content" Button that triggers modal

Step 1:
- list of page types
- select topic type
- search not yet necessary

Step 2: 
- give page a title

Step 3: 
- Information Architecture task, related back to what they have access to
- Topic selection
- only show one theme open at a time
- have a default theme expanded

Step 3b:
- repeat for a secondary topic selection in chosen
* _how we tackle this might still be in the air_

Step 4: 
- loading page
* _is the necessary?_

- deserialize data on Service Page

**Comment by toribr** [comment]
![create content modals](https://user-images.githubusercontent.com/3790067/42944435-3cd68012-8b2b-11e8-8efa-1f675ee956b6.png)
This image represents functionality, but not necessarily styling which can be amended to be more wagtail friendly. 

Keep in mind we have a character limit restriction on page title.

Ben and I had discussed making selection of a secondary topic NOT critical to MVP and that perhaps it could be done manually on the backend if necessary.

**Comment by mateoclarke** [comment]
merged in the first related branch. currently working on a second branch with styling and refactoring.

**Comment by amenity** [comment]
@toribr @mateoclarke - once the workflow is implemented, any necessary design updates can go into https://github.com/cityofaustin/techstack/issues/551.
