### ISSUE TITLE
Implement covid-19 alert

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#4154]
https://share.goabstract.com/bfe746d7-0f25-42de-b6e3-f8c81826eb84
janis only

couldn't find spanish copy in abstract, todo: find that

**Comment by desigonz** [comment]
### Acceptance criteria 
- [ ] Designs implemented for:
  - [ ] Mobile
  - [ ] Tablet
  - [ ] Desktop
- [ ] Link opens to http://www.austintexas.gov/COVID19 in a **new tab/window**
- [ ] Link copy:
  - [ ] `en`: Get current information about coronavirus (COVID-19) in Austin
  - [ ] `es`: Obtenga informácion actual sobre el coronavirus (COVID-19) en Austin
- [ ] Only the underline text is hyperlinked (not the entire block)

**Comment by chiaberry** [comment]
https://janis-4154-covid-alert.netlify.com/

@desigonz and @chasechenevert 

Some of the padding on the label may be off, let me know what I need to tweak. 

Big shout out to @robbobfrh84 who helped me with some style questions

**Comment by chasechenevert** [comment]
My only changes!
```
/* styles.5a893d3f.css | https://janis-4154-covid-alert.netlify.com/styles.5a893d3f.css */
@media screen and (min-width: 768px) {
  body {
    /* line-height: 3.4rem; */
    line-height: 2rem;
  }
}
.coa-HomepageAlert__link {
  /* width: 238px; */
  width: 100%;
}
/* Element | https://janis-4154-covid-alert.netlify.com/ */
.coa-HomepageAlert__link {
  padding-left: 16px;
  padding-right: 16px;
}
```

**Comment by chiaberry** [comment]
updated at the same link

**Comment by chasechenevert** [comment]
Sweet! Great work--good to go from me! 🚀

**Comment by desigonz** [comment]
Looks amazing! Let's get it into production.
