### ISSUE TITLE
Global alert: responsive CSS tweak

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4156]
@desigonz noticed some unexpected extra space at certain breakpoints. I took a look with inspect and tried to see if I could get there with a few tweaks.

**Fixes the height issue**
```
/* styles.59b99011.css | https://alpha.austin.gov/styles.59b99011.css */

.coa-HomepageAlert__container {
  /* height: 159px; */
  height: auto;
}
```

**Needed to add in some top padding so it looks good on `desktop`**
```
/* Element | https://alpha.austin.gov/ */

.coa-HomepageAlert__link {
  padding-bottom: 24px;
  padding-top: 16px;
}

```

## Before
![Screen Shot 2020-03-17 at 1 44 16 PM](https://user-images.githubusercontent.com/7027270/76891037-56259080-6856-11ea-8647-5a6673e67333.png)

## After
![Screen Shot 2020-03-17 at 1 49 31 PM](https://user-images.githubusercontent.com/7027270/76891053-5b82db00-6856-11ea-8100-3f50b1db7c03.png)

**Comment by robbobfrh84** [comment]
This was fixed in https://app.zenhub.com/workspaces/techstack-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/4392

**Comment by jairPineros** [comment]
QA tested
