### ISSUE TITLE
Implement COVID-19 hours alert on location pages

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#4158]
Collection with files: https://share.goabstract.com/a951f879-c99c-48ce-be76-a635f7d27b1b

### Acceptance criteria
- [x] Appears below "Facility hours" heading on every location page
- [x] Designs implemented for:
  - [x] Mobile
  - [x] Tablet
  - [x] Desktop
- [x] Copy
  - [x] `en`: "City of Austin offices and facilities may be closed or have temporary emergency hours that are not up to date on this website. Call 3-1-1 for updated hours information or get current information about coronavirus (COVID-19) in Austin."
  - [ ] `es`: "Es posible que oficinas y servicios de la Ciudad de Austin estén cerrados o tengan horarios de emergencia temporales que no están actualizados en este sitio. Llame al 3-1-1 para obtener horarios actualizados u obtenga información actual sobre el coronavirus (COVID-19) en Austin."
- [x] "Call 3-1-1" links to `tel:(512) 974-2000` (or "Llame al 3-1-1" for `es`)
- [ ] "get current...in Austin"  links to http://www.austintexas.gov/COVID19 (or "obtenga información...en Austin" for `es`) in a new window

**Comment by robbobfrh84** [comment]
Ok, this is ready for QA and review

PR: https://github.com/cityofaustin/janis/pull/724

Deployed: https://janis-hard-coded-hours-alert.netlify.com/
- Direct Example: https://janis-hard-coded-hours-alert.netlify.com/en/location/recycle-reuse-drop-off-center/

Use 👇 below links and check for ...
- styles and
- external links to https://www.austintexas.gov/COVID19
- 311 calls > (512) 974-2000.

**Comment by desigonz** [comment]
Hey @robbobfrh84, can you replace the copy with @Jo-Dwyer's new translation? 


> Las oficinas e instalaciones de la Ciudad de Austin quizás estén cerradas o tengan horario de emergencia temporal que no se ha actualizado en este sitio web. Llame al 3-1-1 para información actualizada sobre horarios o obtenga información actual sobre el coronavirus (COVID-19) en Austin.

**Comment by desigonz** [comment]
- [ ] "Llame al 3-1-1" is the phone link
- [ ] "obtenga...en Austin" is the link link

**Comment by robbobfrh84** [comment]
Got it. Should be updated to the new translation.
