### ISSUE TITLE
CMS - Edit Service Page

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#416]
- image select
- steps (up to 8 or 10)
- add form, map, app, etc
- SEO description
- keywords
- short url
- help text for some fields
- visual language split in styling b/t fields that render vs meta
- sticky menu at top:
  - breadcrumb
  - draft url (public link with copy/paste)
  - share a draft btn
  - save draft
  - carat dropdown for seeing revision history (need to create API to get this out of Wagtail)
  - send to review
- if a page is under status: `in review`, then it should be locked for author

**Comment by toribr** [comment]
![edit page style guide](https://user-images.githubusercontent.com/3790067/41429640-4afe9684-6fd3-11e8-94eb-5d862c49fb27.png)

I'll be updating this as I get the states all made, specs defined and called out.

**Comment by benweatherman** [comment]
we're using the built-in wagtail editor so yay!
