### ISSUE TITLE
Edit Page Sidebar

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#417]
Fixed Menu Bar to toggle active:

- Mobile | Performance | Style Guide

Mobile Preview
- as they type, live update (or button available to trigger rerender)
- this will be a lot of work in Janis abstracting components to be reusable via npm?

Style Guide
- iframe of Jekyll site
- https://cityofaustin.github.io/digital-services-style-guide/introduction/

Performance
- Satisfaction
  - emoji percentages
  - scrollable feed of comments
- Content Review
  - reading level
  - acronyms
  - broken links
  - misspellings
  - word count
- Analytics
  - views
  - origins

**Comment by amenity** [comment]
Mobile Preview
- https://github.com/cityofaustin/techstack/issues/464

Style Guide
- https://github.com/cityofaustin/techstack/issues/467

Performance Tab
- https://github.com/cityofaustin/techstack/issues/465
- https://github.com/cityofaustin/techstack/issues/466
