### ISSUE TITLE
Synthesis document for publish queue usability tests

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#4176]

**Comment by anukandimalla** [comment]
1st Iteration Findings and Usability Test Report:
https://docs.google.com/document/d/1z2LrKm6AmGrleUNBT3X86DNtaBwDf_IMLPADxSnO1Gc/edit?usp=sharing

**Comment by anukandimalla** [comment]
2nd Iteration Findings and Usability test report:
https://docs.google.com/document/d/1rGFsnG_TWS83mSPDCeD7QQNG6P13iY8h86Hg85RLJzk/edit?usp=sharing
