### ISSUE TITLE
Look into Drupal 8 alerts

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#4177]
Let's get an understanding of the affordances of alerts for Drupal 8 authors.
- How many alerts at once?
- Do they show up everywhere? How does an author control where it shows up?
- Can an author set a time frame?
- How customizable are the alerts? What can you add to an alert?
- Microsites can have alerts. How does this work?

**Comment by anukandimalla** [comment]
Drupal  Alerts research:
https://docs.google.com/document/d/1FPYCAtc7Lfi_bYm999E_pYYCZecnfYu48rivtde3y-0/edit?usp=sharing
