### ISSUE TITLE
Connect with Julia and Tim re: alerts

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#4178]

**Comment by srigdon** [comment]
Questions: 
- Who can create and edit alerts? What are those permissions? 
- How far-reaching are alerts? Can you make them site-wide, or just specific to a particular section of the IA (I'm guessing 'department' is the divider)? 
- I'd want to see the user path for creating an alert, with a screen shot for each step. 
- Do they have Google Analytics set up for alert clicks? If so what's the data saying so far?

**Comment by toribr** [comment]
Also:
Are there affordances for multiple alerts?
What about severity? Or are all alerts the same?

**Comment by chase-vert** [comment]
Rough, i.e. not very curated notes:
https://docs.google.com/document/d/1cW5-lurTq25E-OENREEPPPNz8IpfloiVWIaYNct_TS4/edit

@Jo-Dwyer I believe you have notes as well?
