### ISSUE TITLE
Alerts: UI iterations

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#4179]
Some things to think about:
- How do alerts affect different content types?
- Local vs. global? 
- What do multiple alerts look like?

---
**Background**
- Alerts MVP [desk research](https://docs.google.com/document/d/1cYigwpSBlL4bqDr1tqLKea5rUnQVyVRaLh27Tr_iRRo/edit#heading=h.odkykz16diw0)

**Comment by chase-vert** [comment]
I think we've settled on the styling and positioning on the Janis side. Just need to generate the `dev hand-off` collection and link to it within the criteria issue.
