### ISSUE TITLE
joplin - add related service/info pages to events

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#4214]
from https://github.com/cityofaustin/techstack/issues/4043

page picker a la department top pages
service and info page only

**Comment by chiaberry** [comment]
@briaguya is there a limit to how many related services / info pages can be on an event?

**Comment by chiaberry** [comment]
https://joplin-pr-4214-add-to-events.herokuapp.com/admin/pages/27/edit/#tab-content
