### ISSUE TITLE
Search results: assign on-the-fly topics to a sample D8 search result list

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4222]
**When is this project due?**
Before the end of sprint 23, if possible (Thursday, April 2).

**What is the project that this work time will be charged to?**
Alpha

**Have you already consulted the [ODD Style Guide](https://cityofaustin.gitbook.io/digital-style-guide/) before submitting this request?**
No

**Is the project resident-facing?**
- [X] Yes
- [ ] No

**Is this project a blocker for you or your team?**
Somewhat

**If the project isn't resident-facing, who is the end audience? Depending on who this is written for, we may need more information to understand how to meet your needs.**

**What is the medium for this content?**

**What is the problem that a content strategist can help with?**
We're trying to finalize the MVP search result behavior and criteria, and we need a real sample result to evaluate which contextual information to go with. It would be great if we could have a content strategist take maybe 10 results from this result list, and suggest a `topic` that the page would fall under in Alpha.

Sample result list: http://austintexas.gov/search-pages?search_api_fulltext=permitting&department=&sort_order=DESC&sort_by=search_api_relevance

**Context**
Slack link: https://austininnovation.slack.com/archives/CPZ16AY07/p1585337313012400?thread_ts=1585327863.010200&cid=CPZ16AY07
>And from a content standpoint we need a realistic results list to evaluate and determine what gets populated into that Label section of a result, and that’s hard to vet without looking at a real list. I like your permitting example--what about taking a sample page of results from a D8 “permit” search, and have a content strategist create some on-the-fly topics that those would be associated with, and I can update the mocks?

**What deliverables do you expect from the content team?**
Spreadsheet probably

**What approvals will be needed to complete this work?**

**Please provide the link to the Google Documents we'll need to use.**
I've been working within this sheet: https://docs.google.com/spreadsheets/d/1mF2ncOk2QgdpMZ8LuR6Ot9MZKx7FR3aZj8IDnwSRWN8/edit#gid=0

**Comment by toribr** [comment]
Improvised copy:
Multifamily Recycling Requirements Household Waste  Commerical Recycling Requirements Business Waste  Residential Recycling Collection
Household Waste

Clothing and Housewares Recycling Recycling and Reuse

Christmas Tree Recycling Compost and food waste

Apartment/Condominium Recycling
Residential Trash Collection

Construction & Demolition Recycling Ordinance
Construction Debris

Business Trainings on Recycling and Organics Diversion
(event)
Business recycling trainings

Downtown Austin Recycling, Trash & Litter-Control Services Business recycling trainings
