### ISSUE TITLE
News/press: Research and discovery, features, ideas

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4233]
Let's research News and press releases and figure out what we need for our first mocks.

## Cover
- [ ] Government and private industry examples
- [ ] D8 workflow, feature list
- [ ] User behavior related to press and news
- [ ] Features: Janis and Joplin
- [ ] Gather real-content from D8 for use in mocks
- [ ] Design requirements

**Comment by anukandimalla** [comment]
Here is the [Drupal research document link on New/Press Release](https://docs.google.com/document/d/1FYgSjk0-FZozB3QfL3fT_CiJF9A4OgaHdoKOETOK9XU/edit?usp=sharing)

**Comment by toribr** [comment]
Closing this and splitting this work into two parts moving forward, starting with media releases and then news/articles.
