### ISSUE TITLE
Events on info, service, and locations: Dev criteria

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4235]
## Janis
- Abstract collection: [dev hand-off](https://share.goabstract.com/a215a3e1-a703-48f5-9bbe-9d22bdf60db1) 

## Joplin
- Abstract collection: [dev hand-off](https://share.goabstract.com/f55b6fc4-b618-4382-a589-b8560ab5ce4d) 

---
Acceptance criteria, functional Joplin
- [ ] Page types that may be selected are info, service and location
- [ ] There is no limit to the pages that an event can be added to

Acceptance criteria, functional Janis
- [ ] For pages that are selected, display that event on that info, service or location page. 
- [ ] Up to 3 events may be displayed per page
- [ ] Display style is same except small exception on location, which does not include leading icon (see mocks)
- [ ] Past events should not display

Acceptance criteria, visual
- [ ]  Implementation matches mocks, including spacing, type sizing, colors
- [ ] Responsive behavior conforms to mocks
- [ ] Screen reader behavior 

---
**Background**
- Design issue: https://github.com/cityofaustin/techstack/issues/4043

**Comment by chiaberry** [comment]
@chase-vert ready for some review
Service: 
https://janis-v3-4235-janis-rel-events.netlify.app/en/kitchen-sink-department/pick-up-boxes-of-produce
Information page:
https://janis-v3-4235-janis-rel-events.netlify.app/en/kitchen-sink-department/recipes/
Location page:
https://janis-v3-4235-janis-rel-events.netlify.app/en/location/faulk-library/

I need to do some work around an undefined link showing up on the service & information pages, but this is ready for you to look at the design

the linked joplin is: 
https://joplin-pr-4215-events-api.herokuapp.com/admin/pages/search

**Comment by chase-vert** [comment]
Good work @chiaberry ! I've checked between all responsive views, and there's just a few small things: 

```
/* Element | https://janis-v3-4235-janis-rel-events.netlify.app/en/kitchen-sink-department/pick-up-boxes-of-produce/ */

.coa-RelatedEvents__container {
  padding-left: 20px;
  padding-top: 40px;
}

/* Element | https://janis-v3-4235-janis-rel-events.netlify.app/en/kitchen-sink-department/pick-up-boxes-of-produce/ */

.coa-EventListPage__Entry {
  margin-left: 0px;
}

/* Element | https://janis-v3-4235-janis-rel-events.netlify.app/en/kitchen-sink-department/pick-up-boxes-of-produce/ */

.coa-RelatedEvents__heading {
  margin-left: 0px;
  margin-bottom: 16px;
}

/* styles.b2b2e2fb.css | https://janis-v3-4235-janis-rel-events.netlify.app/styles.b2b2e2fb.css */

.coa-EventListPage__Entry--relatedPage:last-of-type {
  /* border-radius: 0 0 4px 4px; */
  border-radius: 4px;
}
```
