### ISSUE TITLE
Joplin: Add entry for ICMS# on Official Docs content type

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#4238]
### As an OPO content author I want to be prompted to add an ICMS# for official documents (specifically for complaint and discipline documents, and I want that entry and the date to automatically generate when I toggle to Spanish in Joplin. This will make it will be easier to confirm that I am working on the right entry when I toggle to Spanish.

**Is your feature request related to a problem? Please describe.**
Since we implemented document localization for Spanish/English, I am no longer able to easily confirm that I am adding translations to the correct entry. As of now, the only thing that is carried over when I toggle to Spanish is the date. Date isn't enough to confirm that I am working on the correct entry because there is often many entries for the same date.

**Describe the solution you'd like**
There would be an additional text box or other entry box to add the ICMS #, and whatever the author entered there in English would be carried over in Spanish.

I don't think this should be a required field, because reports and recommendations use the official doc content type and they do not have ICMS #s.

I also don't think the ICMS # needs to show up on Janis. It is mainly helpful for organizational purposes for the authors

**Comment by toribr** [comment]
We think that the new official document collection/official document page division will make this issue irrelevant. Closing until we learn otherwise.
