### ISSUE TITLE
Location page style update: background color swapping

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4242]
PR: https://github.com/cityofaustin/janis/pull/773
PR App: https://janis-v3-4242-location-page-style.netlify.app/en/location/faulk-library/

Small quality of life change that switches the page body background color and the card color. 

**Rationale**
Emphasis should be on the card to better focus the user--where we want more contrast with foreground and background. 

## Acceptance criteria
- [ ] Page body changes to gray `#F3F3F3`
- [ ] Card background color changes to `#ffffff`

**Comment by briaguya** [comment]
closing this as it has been rolled into #4241
