### ISSUE TITLE
News: the content formerly known as Media release: Joplin MVP 

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4243]
Research [#4233](url)
Split from news/article [#4277](url)

**Data model**
MVP Media release content
- [ ] System generated city seal
- [ ] Headline (90 char count ok?)*
- [ ] System generated repeating first sentence (how do we communicate this isn't a system error?)
- [ ] Body copy with ul/ol and links only (any char limit for body text?)
- [ ] System generated time stamp (date of first publish)
- [ ] System generated updated stamp (date of last update, any user)
- [ ] System generated end ###
- [ ] Image (y/n)
- [ ] Contact * (one only)

Joplin:
- [ ] Is ability to schedule necessary? (N)
Will also need media release create content icon and description.

- Joplin [Abstract collection](https://share.goabstract.com/79e328d4-48e6-4311-9fe4-ce07311125f7)
- Janis [Abstract collection](https://share.goabstract.com/e937ef92-e3d0-4eac-9838-3e2cdc61ca2f)

Acceptance criteria of NEWS
- [ ] Headline (required) has a character limit of 90 characters
- [ ] Body (required) has no character limit at this time
- [ ] System generated time stamp (date of first publish)
- [ ] System generated updated stamp (date of last update, any user)
- [ ] Authors have the ability to select any existing department page (optional). This will associate this media release with that department, which means it will exist within that department's other media releases as if it were authored by someone within that department.
- [ ] Only one department may be selected
- [ ] A contact is required

**Comment by toribr** [comment]
Making this issue media release only, and creating new issue for news/article.

**Comment by Niicck** [comment]
Dev functionality that we decided on 4/28/2020 dev/design sync.

As a CPIO user, I want to be able to publish a media release on behalf of Austin Public Health.

- The media release page created by a CPIO user will belong to the CPIO department group.
- The Austin Public Health department group will be selected in the "From" department selector on the edit page.
- The Janis Instance/Url/Contextual Nav creation will be determined by the selected "From" department, not the content author's department. The media release content type will have a custom "janis_instances()" method on its model to support this.
- MVP according to Jo: a user belonging to the Austin Public Health department will not need to see this media release on their own Content List View in Joplin. We don't need to add additional department ownership groups for media releases.

**Comment by toribr** [comment]
I made a few edits above, to infer that the ability to select the APH is not specifically what's required, but rather we want the CPIO to be able to select any other dept. APH is merely the one that will likely be used most.

**Comment by toribr** [comment]
Link for content to review
https://share.goabstract.com/7c479733-c791-49b4-998f-8491fc0fd25b?sha=a092bc5c103b2527fcf22133587dc823e33a169d

**Comment by toribr** [comment]
@Niicck I'm not sure why this is still in review?

**Comment by Jo-Dwyer** [comment]
@toribr microcopy looks good... sorry this has been chilling in the pipeline for ages.
