### ISSUE TITLE
Establish short URL standards

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#426]
Author interface component that enables one to get a shortened URL to share a page.

Considerations:
- *organizational governance* - e.g people wanting the same URL, inconsistent URL patterns
- *longevity of URL*  - may be used on evergreen print materials so if the page is deleted or moved, needs to redirect
- *human readability* - with so much content, will be harder to do without lengthening the URL
- ...

**Comment by mateoclarke** [comment]
Here's a good thread: https://github.com/government/best-practices/issues/160

But it might 404 on you if you haven't set up your github account with a .gov email:
https://github.com/government/welcome#how-to-join

And if you're lazy, read this PDF:
[URL conventions · Issue #160 · government:best-practices.pdf](https://github.com/cityofaustin/techstack/files/2095806/URL.conventions.Issue.160.government.best-practices.pdf)

**Comment by ashleecoa** [comment]
yeah, happy to share the info I know from how it's worked so far on austintexas.gov

**Comment by LauraTrujillo** [comment]
@srigdon can you link to your url doc?

**Comment by oliver2g** [comment]
related to #1178

**Comment by srigdon** [comment]
I don't think it's a duplicate, it's still a to-do. Here's the draft URL standards doc: https://docs.google.com/document/d/1pI2vdbAC4gpupVU02GLo6qGr6nsEJGuEORnVHJqs6JM/edit

**Comment by oliver2g** [comment]
hey @srigdon where are we on this issue? do i need to adjust the milestone?

**Comment by srigdon** [comment]
@oliver2g In progress, just updated it to Sprint 28.
