### ISSUE TITLE
Draft about page for austin.gov 

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#4262]
### User story
As a resident who lands on an alpha.austin.gov page, I want to know where to find any city service I might need from there. 

### Background
We've been talking about creating an austin.gov version of [sf.gov's "A new website for San Francisco" page](https://sf.gov/about-this-website) for a minute, and some of the page feedback we've been getting recently speaks to some confusion about where the whole website is. For a treat check out cityofaustin/alpha-feedback. 

A very bare bones to-do list (please add and edit): 

- [x] draft interim message for now (start with existing copy about values, update, add) 
- [ ] content 🔃 design 
- [ ] publish interim page 

https://docs.google.com/document/d/1iAzY-9cAkFxkuPnFiRO0exFKtqrwdtJJnwl1Pyu7CpM/edit#

**Comment by srigdon** [comment]
@ablangworthy27 is writing the first draft. Woo!

**Comment by srigdon** [comment]
Another way to reduce confusion for users here is adding something like this to the search results page: 

> 
Uh oh, no results found. You can try your search on austintexas.gov (link to austintexas.gov search? Or just the homepage?)

**Comment by toribr** [comment]
If possible a pre-populated search (based on the alpha search term) on austintexas.gov might be interesting.

**Comment by ablangworthy27** [comment]
@toribr [The draft](https://docs.google.com/document/d/1iAzY-9cAkFxkuPnFiRO0exFKtqrwdtJJnwl1Pyu7CpM/edit#) has been written and reviewed by the content team.

**Comment by ablangworthy27** [comment]
@toribr I can't publish because I don't have a topic/department, but I have a draft in Joplin that you can [preview.](https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToyMTA=)

**Comment by toribr** [comment]
In the end, this is really two issues. 1) Making the links to austintexas.gov more visible and 2) adding the about page. I'm not sure it makes sense to separate them now, though.

**Comment by ablangworthy27** [comment]
I now have a [live link,](https://alpha.austin.gov/a-new-website-for-the-city-of-austin/) but I'm not seeing it in the nav.
