### ISSUE TITLE
Clean up API Tests

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#4268]
Maybe there's a better, cleaner way to test the importer than querying a deployed "pytest" environment.

Problems with the deployed test environment:
- It doesn't get automatically updated.
- It's awkwardly hosted as its own branch in the Joplin repo.
- Anyone who runs the tests will need to have access to API_TEST_USER_PASSWORD.
- Updates can potentially break tests on PR branches.

Potential Solution:
- Run API tests entirely locally, getting rid of the need for a "pytest" environment.
- Load fixtures into a test site/HomePage.
- Then try importing those fixtures into another site/HomePage.
- You could still go through the whole PageImporter process, just querying your own local database.

Or if we just want to improve the current deployed "pytest" environment:
- Make fixtures for all of the test data we want to query from "pytest". Otherwise that data has to be manually imported into "pytest" environment.

**Comment by chiaberry** [comment]
Closed because we are removing importer tests.
