### ISSUE TITLE
Janis Search: Navigation Icon

### ISSUE THREAD

**Issue by robbobfrh84** [cityofaustin/techstack#4283]
Add "search" icon functionality and designs. 

![search on navbar.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/78b4ed6c-c9fd-459b-988b-bcfc5877ebb0)

Abstract Search Page Designs 
- https://app.abstract.com/projects/065fcabf-a46a-4688-a858-83ce2117b16c/branches/27aa4fc8-3c8e-4c7f-969c-164a870c68df/collections/c7f56f4c-4217-4a78-a3af-ddc90330aa13

**Comment by robbobfrh84** [comment]
Here's the PR for both this addition as well as pagination @chase-vert and @toribr 
- https://github.com/cityofaustin/janis/pull/778

Really the only UI addition is the search nav icon.

**Comment by chase-vert** [comment]
Confirming here as well that this is good to go by me 🚀
