### ISSUE TITLE
Janis Search: Search Page

### ISSUE THREAD

**Issue by robbobfrh84** [cityofaustin/techstack#4285]
Create New `/search` page and designs. 
- Filter query by title only (MVP for now)
- Trigger search on [search] button press.
- ~Ignore individual official docs for now(MVP)~ They have been included
- Set translations I18n for en/es - title etc...
Note: they're included in the design.

Abstract Search Page Designs
- https://app.abstract.com/projects/065fcabf-a46a-4688-a858-83ce2117b16c/branches/27aa4fc8-3c8e-4c7f-969c-164a870c68df/collections/c7f56f4c-4217-4a78-a3af-ddc90330aa13![Screen Shot 2020-04-15 at 7.50.31 PM.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/bb3cf765-0d85-4b9f-ae19-3404e8cb3069)

![Screen Shot 2020-04-15 at 7.50.31 PM.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/01a77322-0b41-4553-a206-507b6e7bfb6c)

**Comment by robbobfrh84** [comment]
Ok @chase-vert and @toribr the PR is up for this here: 
- https://github.com/cityofaustin/janis/pull/768

NOTE: the search in navbar and pagination will follow up with the next PR(s).

Deployed: https://janis-v3-4285-search-page.netlify.com/search

**Comment by chase-vert** [comment]
The only thing I can see is the `search` button hover color, and let's set that to: `#2672DE`, or blue-warm-50v (in USWDS token)
