### ISSUE TITLE
Search: Add individual official documents into search

### ISSUE THREAD

**Issue by robbobfrh84** [cityofaustin/techstack#4287]
So far with search we've only crated index for Pages. 
- However, we want to add individual `.pdf` entries into the search results. 

The Site Index API will need to be modified to allow this. 
- We'll need to query all Official Document pages and and ALL their official documents into the search Index.

Questions...
- We'll need to decide on a page type name... "Individual Official Document" ... ?
- And, link result to the pdf?

**Comment by toribr** [comment]
@robbobfrh84 In our future world, each official document entry will have it's own page, the title of which would appear in search. Won't that make this issue outdated?

**Comment by toribr** [comment]
superceded by #4655
