### ISSUE TITLE
Research IA for press releases and news 

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#4293]
User story: 
As a resident, I want to easily find what's going on in Austin that affects me and the City services I access or might want to access. 

Tasks: 
- [ ] review other gov sites for how they do IA for press releases, news, blog posts, articles, etc. 
- [ ] make a spreadsheet of research findings

**Comment by gabrielaperezdelaosa** [comment]
hey @srigdon just want to mention that there is already some information documented on [this doc](https://docs.google.com/spreadsheets/d/1Xmw4M8-Jw3Xk_hYTAkyKl3mwZ3LCJbmE4vZFL8r0BI4/edit#gid=1345408276) that you might find helpful--the IA tab and News tabs in particular

**Comment by srigdon** [comment]
Not needed anymore.
