### ISSUE TITLE
Implement All Pages View components in Storybook

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#430]
![](https://user-images.githubusercontent.com/3790067/41242889-66f4a33e-6d66-11e8-8e78-42c5bb7c31f2.png)

## Rough List of Components:

- [x] `<DashboardHeader/>` 
  - [x] `<UserSettings/>` (1) - username dropdown menu w/ profile settings & Logoff
- [ ] `<PageHeader/>`
  - [ ] `<ButtonWithModal/>` (2) - opens create content modal in this instance
  - [ ] `<Search/>` (3) 
- [ ] `<LeftSidebarNavigation/>` (4) 
   - current location has active state
   - authors only see "content"
   - publisher has "manage users", "performance", others
- [ ] `<PageHeader/>` "Content" title
- [ ] `<Table/>` - manages state of sorting and filtering
- [ ] `<TableFilters/>` (5) - by status, archived toggle
- [ ] `<ColumnHeaders/>` - some can sort
- [ ] `<TableRow/>`
  - [ ] `<RowActionsButtons/>` - Edit, View, More
- [ ] `<Pagination/>` (8)

**Comment by ifsimicoded** [comment]
Closing as we've opted to use Wagtail CMS and not decouple our Author Interface at this time.
