### ISSUE TITLE
Review basic traffic deferrals form

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4300]
This form is a quick response to a two-day lead tiem on digitizing forms for courtroom use via remote dockets on Zoom. The primary user is a prosecutor who will save and send the unique resume link to the defendant who will sign, save and send the link to the judge who will sign and submit the form. Issues in user experience are expected. It is a legal document.

In this circumstance please review for:
- [x] glaring errors in the copy
- [x] consistency of style and use of microcopy
- [x] logic

Bugs in the signature field and save/submit buttons will be addressed.

[Basic traffic deferral](https://alpha.austin.gov/en/municipal-court/basic-traffic-deferral/)

**Comment by srigdon** [comment]
[Editing pass complete](https://docs.google.com/document/d/1LZWRqjakjkRakbC9PE8ey68L_6LUrsUO1R37qxu69ZA/edit#). I just got Formstack access so I can edit the form directly, but let me know if these edits make sense, @Jo-Dwyer.

**Comment by srigdon** [comment]
Closing because I finished the review, and this form went elsewhere.
