### ISSUE TITLE
Kitchen Sink Official Document Link doesn't work

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#4310]
Maybe this is just a test data problem.

Go here:
https://janis-v3-v3.netlify.app/en/kitchen-sink-theme/kitchen-sink-topic-collection-page/kitchen-sink-topic-page/kitchen-sink-official-documents-page#1

Try to click on the official document link. Nothing happens.

**Comment by chiaberry** [comment]
obsolete issue b/c of official document page refactor
