### ISSUE TITLE
Develop MVP curriculum for new content authors in Joplin

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#4316]
To draft: 

- [x] [learning objectives and outline](https://docs.google.com/document/d/1UVBnQZgPMZGG0igYs8-qVrjVCsQKXCwmel7h9zFAhfw/edit#)
- [x] [slide deck](https://docs.google.com/presentation/d/1BEUGBTgKfdZLV6x9jH57nn0gOQLwnQ_bac9wY2O56kY/edit#slide=id.g81c91e7466_0_124)
- [x] create a how to use Joplin doc ([draft started](https://docs.google.com/document/d/1D6VV0B9cM5whkmcyf4SLDzkunPNpQ42WRsQaahoepnM/edit), incorporated into the training outline) 
- [x] prepare activities, practice materials (by 8/14)
- [x] accessible content checklist (#4534 or [this cheat sheet](https://docs.google.com/document/d/1FAYaGRYtUfXeYJ2aQQJ5kOMaOjcKl6J0ScqhNp9niWI/edit#)) (by 8/14)
- [x] determine people and send out invitations (by 8/7)
- [x] present content team on 8/10
- [x] run the pilot (before 8/31)

**Comment by Jo-Dwyer** [comment]
From Gabi's issue:

Re-organize funshops in a way that clearly defines and measures learning outcomes.

 schedule a content team meeting to get the ball rolling on this
Goal: make trainings more modular and topic-specific, so Funshop participants can focus on the training they need now and dig into less time-sensitive topics later.
