### ISSUE TITLE
Change hard-coded content in Trashy App

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#4327]
ARR has not scheduled bulk trash pickup dates, and the user experience in step 3 on the [Alpha page](https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup/) is not ideal. 

To improve, I need a Dev to move the hard-coded text that reads : "Currently, no upcoming bulk item collection date has been scheduled. Please check back soon." 

It is currently at the bottom of the dropdown, and it should be at the top, right above the list of dates. 

I will also update the text in step 3 to be more specific.

**Comment by toribr** [comment]
Also, there's no action available on Step 2. I thought we had an issue to put the print calendar back in, but i can't find it.

**Comment by toribr** [comment]
Alpha Site Feedback (#413)

**Comment by toribr** [comment]
@briaguya Do you know anything about the print calendar?

**Comment by jairPineros** [comment]
Tested on July 20 2020 on Chrome and Safari
