### ISSUE TITLE
Events: virtual/digital label [JANIS]

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4348]
## Background
Due to COVID-19, lots of events have been canceled or switched to virtual options. It could be helpful for residents to indicate virtual events where the `Location` data normally displays. 

## Asks
- [x] Team content to determine the label that communicates "online" that they like best
  - [x] English
  - [x] Spanish
- [x] Add microcopy to spreadsheet and/or data model if necessary
- [x] Add "online" selection to streamfield
- [x] Get content to approve new "remote" language

## Resources
- Dev criteria collection: https://share.goabstract.com/6c110358-d5be-439a-bafb-6a5a0ae38183

## Criteria
- [ ] Icon: use the `screen` icon in the Material Icon font pack we have in Janis
- [ ] Label: this label should replace where the `address` information normally populates anywhere on the instance view (home page, search result list, event list (all), service pages, and information pages (I think events can be added on info pages, but I'm not remembering?)
  - [ ] EN: "`Virtual event`"
  - [ ] ES:"``"
- [ ] Remove the "Location information" tile that sits below the component
- [ ] Border: `border-radius: 4px`

**Comment by sammodabber** [comment]
@chase-vert What does content need to do on this?

**Comment by chase-vert** [comment]
@sammodabber yes `asks` checklist has the tasks outlined

**Comment by sammodabber** [comment]
Duh, thank you!

**Comment by toribr** [comment]
@Jo-Dwyer If we can get someone to pick this small issue next sprint, we might be able to get it into devs hands soon after.

**Comment by toribr** [comment]
![screencapture-austintexas-gov-department-ann-and-roy-butler-hike-and-bike-trail-and-boardwalk-lady-bird-lake-2020-09-01-09_27_51](https://user-images.githubusercontent.com/3790067/91883761-85845a00-ec4a-11ea-885c-97f035a22073.png)

@chase-vert Currently, an author has to choose between *only* city of austin location or a remote location which requires and address. the address, even if faked, as I did it, creates a link. 

I'd like for us to come up with an "online" icon, which then just adds and Online label. Authors can use existing link to registration for the online location.

**Comment by gabrielaperezdelaosa** [comment]
Virtual event
Evento virtual

@toribr @chase-vert let me know if you need anything else from content.

**Comment by chase-vert** [comment]
## Update
Tori and I chatted about this, and there will be some tweaks on the Joplin side to enable sharing other digital event info (meeting #, link to where meeting is hosted). More to come.

**Comment by chase-vert** [comment]
Dev issue ported to: https://github.com/cityofaustin/techstack/issues/4951
