### ISSUE TITLE
Create/Update `allPageQuery` for Pearl/Joplin

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#435]
1. make allPagesQuery filterable/sortable based on requirements in #410. We should filter on the backend in Joplin, not in the client javascript. The query should also return unique IDs for each page.

2. Make a page that hits this new/updated endpoint and puts pages data on a page.

3. (captured in #430) bring in proper components according to Tori's mocks

**Comment by ifsimicoded** [comment]
Closing as we've opted to use Wagtail CMS and not decouple our Author Interface at this time.
