### ISSUE TITLE
Formstack forms are not saving and resuming

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4350]
On forms made in the Formstack folder Municipal Court, some are not allowing use of the 'save and resume' function. The button is not responsive on any of the forms within Prosecutor subfolder, but are working in the Judiciary subfolder.

For example:
https://cityofaustin.formstack.com/forms/misdemeanor_deferral_prosecutors

Full folder:
https://cityofaustin.formstack.com/admin/form/dashboard/folder/206922

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to https://cityofaustin.formstack.com/forms/misdemeanor_deferral_prosecutors
2. Click on save and resume
3. See error

## Current behavior
No response, not even an error

## Expected behavior
I expect it to save and give me a link to return to the form or email myself the link as it is on other forms

**Comment by Niicck** [comment]
Copy of Traffic Deferral (original has broken save + resume)
https://cityofaustin.formstack.com/admin/form/builder/3862505/build
https://cityofaustin.formstack.com/forms/basic_traffic_deferral_copy_1

**Comment by Niicck** [comment]
Fixed by formstack support. We have a negative number in one of our fields.

![](https://files.slack.com/files-pri/T04KZA1MB-F012PRU084E/screen_shot_2020-05-01_at_8.24.32_am.png)
