### ISSUE TITLE
create individual `servicePageQuery` for Pearl/Joplin

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#436]
- [x] adapt allServices query to make sure we can get 1 page at a time based on a UID. 
    - _see caveat about UIDs below: https://github.com/cityofaustin/techstack/issues/436#issuecomment-398224605_
- [ ] make a page based on slug (ex: pearl.gov/edit/:uid) thats spits out data on the the page
- [ ] (captured in #431) Style it according to mocks

**Comment by mateoclarke** [comment]
@briaguya @ifsimicoded, I started poking into this issue but didn't want to change too much about Joplin while you experiment with graphcool. 

What I did learn (after a bunch of trial & error) is that in order to pull out a single service page, you **can not** query by ID. I think this has to do with some configuration but I was stumped by this line: https://github.com/cityofaustin/joplin/blob/0eb8d493b88bd24a4e78799702b9951bdbedc24f/joplin/api/schema.py#L111

Instead you can query `pk` or `slug`. Examples below:

![screen shot 2018-06-18 at 6 11 01 pm](https://user-images.githubusercontent.com/5697474/41566891-45debd70-7323-11e8-8f03-032177a37c99.png)

![screen shot 2018-06-18 at 6 14 37 pm](https://user-images.githubusercontent.com/5697474/41566944-80860712-7323-11e8-9380-1fda2ee3b96a.png)

**Comment by ifsimicoded** [comment]
You should be able to query by Id too. Not sure where you left out, but I just used the allServicePages query and filtered by ID like below:
![screen shot 2018-06-18 at 10 34 20 pm](https://user-images.githubusercontent.com/3039125/41575445-1ecf7876-7348-11e8-8928-0f16f6edce78.png)

I putzed some with your branch to get the Query HOC working to deliver content via id, but got stuck there. maybe we can put the two together ... or maybe that's where you got stuck too?
