### ISSUE TITLE
Images and Documents need Collections on v3

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#4366]
- [ ] Image collections no longer exist on v3. Fix this.
- [ ] Manually set all images to their proper collections to match v2 prod.

**Comment by briaguya** [comment]
Might be a chance for a better docs UX overall here if we think about this with https://github.com/cityofaustin/techstack/issues/4368

We have monster load times on https://joplin.herokuapp.com/admin/pages/203/edit/, but maybe we could just say "hey docs page, this tag means i'm on you" for all the docs, and then extend the document model to have some of the additional info we currently store on the docs page
