### ISSUE TITLE
contextual nav is broken on pages at urls with department parents

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#4367]
PR https://github.com/cityofaustin/janis/pull/770

example https://alpha.austin.gov/austin-public-health/find-work-as-a-day-laborer/

from https://austininnovation.slack.com/archives/C011LSUTQ4T/p1588285329030800

so in there (https://github.com/cityofaustin/janis/blob/f8175489490e2ea0393a6b230d2c0f70ca7709af/static.config.js#L726-L739), we send in the same pageAtUrlInfo.node for every instance, so if we’re somehow updating that node, whatever the last state it’s in will show up everywhere if I recall the build process correctly

https://github.com/cityofaustin/janis/blob/f8175489490e2ea0393a6b230d2c0f70ca7709af/static.config.js#L490-L502

then we’re passing the servicePageData object into there and updating the contextualNavData on it. https://github.com/cityofaustin/janis/blob/f8175489490e2ea0393a6b230d2c0f70ca7709af/static.config.js#L206-L210

i think we just need to make this line https://github.com/cityofaustin/janis/blob/f8175489490e2ea0393a6b230d2c0f70ca7709af/static.config.js#L216 return a copy of the servicePageData instead of the original object

**Comment by Niicck** [comment]
> so! apparently the events were being cleaned, (formatting the eventUrl) but then that same event was trying to be cleaned again, and the eventUrl couldnt be made again the slug wasnt in the cleaned Event object. but an eventurl was there.
> 
> Which I think may be a similar issue to our contextual nav bug?

https://github.com/cityofaustin/janis/pull/754#issuecomment-626091777
