### ISSUE TITLE
Official document improvements, sketchy draft of ideas.

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4372]
The current implementation of official documents has received a lot of use, and is now trying to load hundreds of documents in a single user interface, creating a poor user experience.

As an author, I want to be able to view, access and edit large amounts of documents without absurdly long wait times so that I can perform my job more quickly.

**Comment by easherma** [comment]
FYI we got this one in the backlog that might still be relevant/has a paper trail to some other related issues: 
https://github.com/cityofaustin/techstack/issues/2668

**Comment by toribr** [comment]
Reviewed sketches with content and dev, and moving forward with a bi-directional implementation that allows authors to add official documents to an official document collection, or add a collection from an official document. This efforts separates the document meta-data and file from the collection page, thus making this document type quicker and easier to work with.
