### ISSUE TITLE
Deploy Janis PR to production

### ISSUE THREAD

**Issue by robbobfrh84** [cityofaustin/techstack#4373]
Currently, a shiny new Janis v3 PR will default to *staging* as expected. 

However, we're still getting a build fail when attempting to deploy the PR to *production* data. 

---- 
### Some notes from Bob's journey....

To tell Publisher I *don't* want the default PR to staging...

- Modify `branchConfig.js` by adding the specific branch name to point to production like so.

```javascript
  'build-search': {
    joplin_appname: 'production'
  }
```

Push the branch up to github like usual and you'll quickly see all green checks.

However visit the netlify url: `http://janis-v3-<Your PR>.netlify.com` and you see nothing fun ☹️.

On to AWS🏇!
- Visit our publisher DB: https://console.aws.amazon.com/dynamodb/home?region=us-east-1#tables:selected=coa_publisher_test;tab=items
- select `coa_publisher_test`
- Click {+ Add filter}
- For *Enter Attribute* add pk (primary key)
- For *Enter Value* add `BLD#<Your PR>`

Find the *status* column where the failed notification was discovered. 
- Back to the *pk* column, click the link to show the json data of the build. 
- click: *logs* > *Map* > Url > follow that link to build logs.

... This is where Bob's journey ended and why this issue was created ...

**Comment by robbobfrh84** [comment]
Here are a few questions I'd need to figure out before headed toward making progress on fixing this issue.
- I'm not sure the best way to get started to debug from here. 
- I have the *publisher* repo pulled down. But have yet to replicated any of this dev process.
- What are all the cli tools / commands / configurations / order of operations needed to replicate and test building a branch against a live branch?

Probably making this more complicated than it is... but I've yet completed the dev cycle of publisher, and still need to discover what I'd need to do to fix something like this.

**Comment by Niicck** [comment]
@robbobfrh84 Let's take some time to walk through this and see how to fix it. We'll add documentation to answer those questions along the way.
