### ISSUE TITLE
Publish not happening for some users

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#4379]
>>> After several tries, at 40:25, I thought Mia had published her first official document, because it looked like the new entry had saved in Joplin. I told her to wait a few minutes, we said good-bye, and then Janis didn't build.

>> That's strange. On production? Which page? I don't see any build failures. I'd like to look into this.
Yes, on production. This page. Yeah, is the #janis-builds channel getting re-connected? No big if it's not a high priority.

>Also, after I sent this email I tried publishing the same doc, and it worked. What could it be? I don't know where to start looking. I see Mia hasn't logged in since yesterday. I could log in as her and see if I'm able to publish anything?

Let's make sure that all users who should be able to publish can publish. When our publish visibility and permissions get more sorted by the end of this sprint, it should be clearer how to find and fix this problem.

**Comment by chiaberry** [comment]
Should be resolved by the fix that fixed being able to save drafts. I'm going to close it.
