### ISSUE TITLE
Publishing an info page yielded internal server error

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4380]
## Describe the bug
When I tried to publish an information page it came back with an internal server error and then returned to the editor with all my content gone.

joplin.herokuapp.com/admin/pages/217/edit

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to [joplin.herokuapp.com/admin/pages/217/edit](joplin.herokuapp.com/admin/pages/217/edit)
2. Click on 'publish'
3. See error

## Current behavior
A clear and concise description of what happened

## Expected behavior
A clear and concise description of what you expected to happen

## Screenshots
![Screen Shot 2020-05-08 at 3.14.40 PM.png](https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/9aef2de3-da61-45a4-9104-e0e8a6d4b142)

Also [a video of the event](https://web.microsoftstream.com/video/0f3d070b-a4d9-446e-9215-fa3d59ca6efa). FF to 17:10ish

**Comment by easherma** [comment]
And log: 
https://logentries.com/app/eba00fce#/search/log/0640e5ec?log_q=where(500)&last=Last%203%20Hours

**Comment by briaguya** [comment]
@Jo-Dwyer after watching the video I see that you selected ARR as the department, which is a draft page only, and didn't pick any topics.

My gut feeling is that may have something to do with it

**Comment by chiaberry** [comment]
The error happened because the Topic panel was opened but nothing was entered. Que loco.
