### ISSUE TITLE
Add Group Permission Fixture to our "fixtures" LOAD_DATA flow

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#4383]
Please.

and themes

**Comment by chiaberry** [comment]
do we know what permissions we want to add to the fixtures?

**Comment by Niicck** [comment]
Yes, sorry! In `joplin/base/db/fixtures/group_permissions_settings.json`

**Comment by Niicck** [comment]
Current these settings are managed manually on
https://joplin-staging.herokuapp.com/admin/groups/1/
https://joplin-staging.herokuapp.com/admin/groups/2/

**Comment by chiaberry** [comment]
They used to be loaded here: https://github.com/cityofaustin/joplin/blob/master/joplin/base/management/commands/load_joplin_data.py#L117
