### ISSUE TITLE
MVP News: get microcopy out of the 🤠 wild west 🌵

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#4386]
Hey content team! When working on news I used some **🤠placeholder copy 🌵**, I was hoping to swap it out with some approved copy!

#### news description
<img width="252" alt="Screen Shot 2020-05-11 at 2 17 54 PM" src="https://user-images.githubusercontent.com/6384156/81602919-116c3080-9393-11ea-8d33-8bfc27c4f914.png">

#### can't publish without a body
<img width="285" alt="Screen Shot 2020-05-11 at 2 27 20 PM" src="https://user-images.githubusercontent.com/6384156/81603322-c1419e00-9393-11ea-9871-97e1ec1e8bb8.png">

#### can't publish without a contact
<img width="292" alt="Screen Shot 2020-05-11 at 2 27 33 PM" src="https://user-images.githubusercontent.com/6384156/81603327-c6065200-9393-11ea-9b93-53ac2277593f.png">

**Comment by Jo-Dwyer** [comment]
News - Provides a time-sensitive report about an announcement or occurrence 
Body text is required to publish
A contact is required to publish

I'm specifically not using the word event so it's not confused with an 'event' content type.

@srigdon or @ablangworthy27 can give feedback, but it should work for our current users so we can move ahead.

Once it's approved let smerge.
