### ISSUE TITLE
Joplin: page picker inventory

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4390]
We need to get a handle on how certain UI elements are being used and reused, within Joplin.    

#4203 List of places where picking happens

- Abstract Joplin branch: https://share.goabstract.com/c8d1f405-5433-418c-b091-3a3b65f34b4a
- Joplin microcopy [spreadsheet](https://docs.google.com/spreadsheets/d/1ZwQmQFPh-YK0tXbc5oFoTz0IM_jAOZNrA_z6XpyrdaE/edit?ouid=117580441351251740719&usp=sheets_home&ths=true)

**Comment by chase-vert** [comment]
### Updates
- We've got a pretty solid draft for the page pickers, and know the ui changes we want to make
- Need to iron out microcopy with content
