### ISSUE TITLE
🤝 4392 nav2: Header and Themes Buttons dev criteria

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4392]
Janis Abstract collection: https://share.goabstract.com/d47259b9-2bb4-4c90-b8a9-71f9cc3b08d5

**Additional related issues**
- [ ] Contextual nav background color change: https://github.com/cityofaustin/techstack/issues/4393

# Changes
### General
- Balanced font weights and sizes
- `Search` is now at the global layer, matching the mobile implementation (it's currently at the same level as themes on desktop)
- Label has changed from `City of Austin` to the shorter `Austin.gov`

### Contextual nav
- [ ] background: `#EDF5FF`, blue-warm-5v

NOTE: 
- The Mega Nav of this issue was spit out to it's own issue here: https://app.zenhub.com/workspaces/techstack-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/4648

**Comment by chase-vert** [comment]
@robbobfrh84 this is pretty much ready to go. It's only lacking the mobile search, which I'm not able to add back into Abstract at the moment, but I can link to it here.

**Comment by robbobfrh84** [comment]
@chase-vert Looks good. Any considerations for hover effect (sorry if i missed the directions somewhere)?

**Comment by chase-vert** [comment]
@robbobfrh84 oversight on my end! So let's retain the same rounded corners as in the `active` state, but lets go with this gray: #F3F3F3, or 'gray-4' in the [scale](https://designsystem.digital.gov/design-tokens/color/system-tokens/#gray).

**Comment by robbobfrh84** [comment]
no problem! looks great. How you feelin' about the 0.3 second transitions we've added a few other places. That's kinda been my default. But, i didn't wanna assume it didn't create conflicts with design/expectations. 

I'll get a PR up soon so we can test it if you're curious to see how it feels.

**Comment by chase-vert** [comment]
Yeah, let's go with that transition for sure!

**Comment by robbobfrh84** [comment]
- [ ] - Make sure Spanish `theme nav` doesn't breakdown to an other line.

**Comment by robbobfrh84** [comment]
Ok, this issue has been broken into (see: edits and links above) two. 

BUT, this 1st part is ready for QA: @jairPineros ! @chase-vert !

There was quite a lot code changes here. So lots to test/qa

**Comment by jairPineros** [comment]
I was reading the previous comments and it looks like you guys were talking about a different color for the boxes when the user hoovers over the links (y'all talk about a gay color and in the site it is a darker blue). The boxes and are working fine with the round corner and in the Spanish version they aren't breaking on a new line. Once I have clarification on the color I'll add the pass QA tag

**Comment by robbobfrh84** [comment]
@jairPineros my bad. I missed moving this part of the "active" button state into part of the "New Mega Nav#4648". 
  - https://app.zenhub.com/workspaces/techstack-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/4648. 

I'll be updating that button state in that issue. I also moved that comment from here to there as well so i don't forget!

Good catch though! Let me know if you have anymore questions?
