### ISSUE TITLE
Feedback link in Joplin

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4396]
# Original issue
### As an new user of Joplin, I want a way to send feedback about bugs, issues, or problems I'm having with Joplin.

Integration with service now in progress, so probably this just means an outbound link in the UI.

---

# Design
Abstract collection: https://share.goabstract.com/8582f743-acc6-4402-bad8-d379ff262145
- Position: link lives in the bottom left corner of the application shell (global navigation)

Styling
- Leading `announcement` icon, styled in primary blue
- Trailing `open_in_new` icon

# Content
Currently "Feedback", but content wants to take some time to suggest something more accurate.
- [ ] Finalize label micro-copy @Jo-Dwyer 

# Dev
Issue here: https://github.com/cityofaustin/techstack/issues/4494

**Comment by chase-vert** [comment]
We're squared-away with the visual design, and it has been merged into master in Abstract here: https://app.abstract.com/projects/bbe34f6b-7080-4dcd-9fa9-d8e30d8f6128/branches/master/files/022dc15a-ae1d-43f6-baf2-2016d64749f8. 

Haven't gotten an answer from content on the micro-copy, but I think "Feedback" is good enough to roll with for MVP?
