### ISSUE TITLE
Cleanup Docker & Heroku Config

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#440]
- [x] set up environment variables in heroku (not in DockerFile)
- [x] copy only necessary files to Docker container (currently we're copy . to app/.)
not sure what other devops-y stuff needs washing.
- [x] node_modules probably shouldn't be a mounted volume to prevent local modification of these.
- [ ] update ENV variables [like this](https://github.com/cityofaustin/pearl/blob/75cf41c94303547a43d7c16ae998fce46ad59b8a/Dockerfile#L15) to be overwrittable defaults instead of statically defined.

**Comment by mateoclarke** [comment]
Pearl is on hiatus
