### ISSUE TITLE
News list page/links from other pages

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#4404]
https://github.com/cityofaustin/joplin/pull/736
https://github.com/cityofaustin/janis/pull/783

good to go https://austininnovation.slack.com/archives/C9EH0LSSD/p1590597516189300?thread_ts=1590592881.186900&cid=C9EH0LSSD

https://github.com/cityofaustin/techstack/issues/4355 covers making the content type and rendering the news page in Janis.

This should cover the list page and links from other pages

## copied from 4355
https://github.com/cityofaustin/joplin/pull/724
https://github.com/cityofaustin/janis/pull/766

Make a media release.
Acceptance Criteria

 Janis https://app.zenhub.com/workspaces/techstack-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/4234
 Joplin https://app.zenhub.com/workspaces/techstack-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/4243

**Comment by chiaberry** [comment]
@jairPineros  ready for QA

https://janis-v3-4404-news-pag.netlify.app/en/mvp-news-aph/
the linked Joplin is https://joplin-pr-4404-news-api-only.herokuapp.com/

News pages are written by departments, but are able to be written for other departments. 

Cupcake news is written by aph for aph
Cupcake court is written by muni court for aph
Bacon court is written by muni court for muni court

- [ ] Confirm no more than 3 news items appear on the department page: https://janis-v3-4404-news-pag.netlify.app/en/austin-public-health/

- [ ] Check the news list page (that appears per dept): https://janis-v3-4404-news-pag.netlify.app/en/austin-public-health/news/#page=1, https://janis-v3-4404-news-pag.netlify.app/en/municipal-court/news/#page=1

- [ ] News pages have link to news list page in right rail:
https://janis-v3-4404-news-pag.netlify.app/en/austin-public-health/court-cupcakes/

**Comment by chiaberry** [comment]
seems to be an issue with the latest 3 news items appearing, ill investigate.

**Comment by chiaberry** [comment]
This is ready for QA again @jairPineros , it was returning the *oldest* three news stories but now its fixed to be the *newest* three news stories.

**Comment by jairPineros** [comment]
Hey @chiaberry I tested it using https://janis-v3-4404-news-pag.netlify.app/en/ and I'm still getting the oldest news instead of the latests news

**Comment by chiaberry** [comment]
@jairPineros the link should show the latest from today, one of the news pages was failing which was preventing the build from updating correctly. It was due to this bug: #4588. I am not 100% what the error so I'm going to keep looking at it over the weekend.

**Comment by jairPineros** [comment]
ok tested it again now it looks like it is working.
