### ISSUE TITLE
joplin news tweaks

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#4405]
- [ ] news icon for create content modal
  * from Brian - we are using the event page icon at the moment, we should update this
  * from Tori - "We may be moving away from using these icons .... Standby"

**Comment by toribr** [comment]
We may be moving away from using these icons, as we need to update this modal. It's getting too unwieldy. Standby.

**Comment by briaguya** [comment]
@toribr updated this item to be a bucket for any joplin news tweaks we need to make while I'm developing the janis page for the news list view and updated the description.
