### ISSUE TITLE
Decide on permissions for new content types

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4407]
Content has outlined permissions for each role for each content type and the actions in each. We now have added two more content types:
- [ ] news
- [ ] events

Add permissions for each role for each option on the [permissions spreadsheet](https://docs.google.com/spreadsheets/d/1zE_Y806MlCli1aSkzIbXTzCTA01KWSReLGrJ7b5sUYU/edit#gid=7019049570).

**Comment by ablangworthy27** [comment]
It looks like Events has already been done, but I can do News

**Comment by Jo-Dwyer** [comment]
Related to #4399
