### ISSUE TITLE
Better fixture organization (including user fixtures)

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#4413]
We need to handle users in a way that makes sense.

I'm not sure if our current strategy of copying users over from production and or making users manually is a good plan for users on test apps/staging going forward. Especially as we start doing permission ux testing.

When doing permissions testing, we should have sample users that reflect different departments/roles. Then when we spin up a new instance of joplin locally/pr app/staging we will have a way to test out those ux things.

Throughout this process, it should be clear to any user of staging who they can log in as, what permissions that user will have, and what password they should use.

**Comment by chiaberry** [comment]
closed because we do have some test user fixtures, and some test user accounts. not perfect, but they are there.
