### ISSUE TITLE
Dev Design sync 5/19/20

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#4415]
- [ ] From devs:
  - [x] What's our handoff flow? Answer: Chase will assign issue to "Team:dev", remove "Team:design", Move into "On deck" lane, when handoff issue is ready for devs. 

From design:
- [ ] topics/topic collection flow from create modal
- [ ] OPO joplin container and topic collection container

**Comment by toribr** [comment]
topics/topic collection from content modal postponed until after official documents work.
