### ISSUE TITLE
Spanish translation for "0" search results page

### ISSUE THREAD

**Issue by robbobfrh84** [cityofaustin/techstack#4423]
Here's what we've got in english...
- - - 
~https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/6535a94f-0526-4445-a83c-6e02bed71ca5~

⚠️ Image updated since original post.
<img width="712" alt="Screen Shot 2020-06-03 at 2 11 36 PM" src="https://user-images.githubusercontent.com/15821138/83758716-1b9ee900-a638-11ea-8df1-92325a500a1d.png">

**Comment by InaraFernandez** [comment]
@robbobfrh84 , Is this issue still open? If so, I can help w/translation.
_______
0 resultados
No hay resultados para su selección. Para mejorar los resultados de la búsqueda:
	- Revise la ortografía  
	- Use menos palabras claves 
	- busque algo menos especifico

**Comment by robbobfrh84** [comment]
Awesome @InaraFernandez ! 

I'll pick this up and start workin' on it. 

Once i have it updated I'll add a temporary Deployment link, so you can review it as it would look live and give a final ✅ ok before we update it to the live site.

Thanks again!

**Comment by robbobfrh84** [comment]
Hey @InaraFernandez,

I just realized the first line will include the searched term. For example, 

`0 results for "something unexpected"`

And, here's the updated screenshot in English...👇

<img width="712" alt="Screen Shot 2020-06-03 at 2 11 36 PM" src="https://user-images.githubusercontent.com/15821138/83758541-dda1c500-a637-11ea-8272-8e1f8ad14b8f.png">

So, just need that top line looked at again. 

Thank you so much! Sorry I didn't have it correct the first time through!

**Comment by InaraFernandez** [comment]
NEW: 
0 resultados para " " 

No se encontraron coincidencias. Para mejorar los resultados de la búsqueda:
- revise la ortografía
- use menos palabras claves
- busque algo menos especifico

**Comment by robbobfrh84** [comment]
Hey @InaraFernandez, this update has been added to a testing link: https://janis-v3-es-no-results.netlify.app/

Just wanted to give you a chance to double-check it looks correct on the site. 

To test, you'll have to 
- Make sure the page is in Español
- Then search for something that doesn't return any results. 

Here's a screenshot of how it should look. Please let me know if you have and questions or want to make any changes. 

![Screen Shot 2020-06-09 at 7.28.19 PM.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/c9a85afa-1fd2-4467-a5a5-cd9a9b028008)

**Comment by robbobfrh84** [comment]
PR: https://github.com/cityofaustin/janis/pull/790
