### ISSUE TITLE
Spanish formstack forms are not showing up consistently

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4424]
## Describe the bug
Amy is using formstack forms in form containers to do remote dockets. The Spanish language version of the [Financial Affidavit](https://alpha.austin.gov/es/municipal-court/financial-affidavit-form/) is returning a mix of pages: sometimes it's 404, sometimes it's th eprovacy blocker text, and sometimes it's just loading only a partial form. This issue is written to the best of my ability as an intermediary for Amy.

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to [Financial Affidavit](https://alpha.austin.gov/es/municipal-court/financial-affidavit-form/)
2. ???
3. See error

## Current behavior
She is trying to use the Spanish form and it's giving her inconsistent responses including partial load, totally 404, or the privacy blocker text w/ link to formstack form pop out.

## Expected behavior
As in English, the Spanish form should open with our styling and include the whole form. 

## Device and browser
Chrome on a Dell laptop

## From Amy:

> Schillerstrom, Amy
    So, folks aren't even getting the link every time - sometimes they just get the partial image...  I looked at my privacy settings and nothing looks abnormal.  How would I tell a citizen to fix it?

**Comment by briaguya** [comment]
```
vendors~main.c000db32.js:1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://cityofaustin.formstack.com') does not match the recipient window's origin ('https://alpha.austin.gov').
C @ vendors~main.c000db32.js:1
(anonymous) @ vendors~main.c000db32.js:1
q @ vendors~main.c000db32.js:1
e @ vendors~main.c000db32.js:1
(anonymous) @ vendors~main.c000db32.js:1
(anonymous) @ vendors~main.c000db32.js:1
vc @ vendors~main.c000db32.js:1
js @ vendors~main.c000db32.js:1
t.unstable_runWithPriority @ vendors~main.c000db32.js:1
Jo @ vendors~main.c000db32.js:1
Ws @ vendors~main.c000db32.js:1
(anonymous) @ vendors~main.c000db32.js:1
R @ vendors~main.c000db32.js:1
T.port1.onmessage @ vendors~main.c000db32.js:1
analytics_0e96c0d8a9.js:1 GET https://cityofaustin.formstack.com/forms/analytics.php?f=3879555&a=v&m=hosted net::ERR_BLOCKED_BY_CLIENT
```

**Comment by chiaberry** [comment]
Is this error still happening, @Jo-Dwyer ?

**Comment by Jo-Dwyer** [comment]
Nope @chiaberry!
