### ISSUE TITLE
Write Joplin copy for build notification, general errors

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#4426]
Per #4425: 

> As a user of Joplin, I need to have a place to check when things don't go as expected, so I can see if it's something I'm doing wrong, or if it's a build failure, so I know what next steps to take.

This will need some copy. [Here is a draft](https://docs.google.com/document/d/1LPl_wME_uz6n4m1I8DDRyivcNq25q7RCxkTVn2EGnCM/edit#). cc @toribr @Niicck @Jo-Dwyer @ablangworthy27

**Comment by ablangworthy27** [comment]
I reviewed copy and it looks good. 

FYI @toribr @Niicck
