### ISSUE TITLE
Move hardcoded links to joplin

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#443]
We should move any hardcoded links to service pages out of Janis and use Joplin to deliver them dynamically instead.

from @ifsimicoded's PR comments on the [Recycling Schedule PR](https://github.com/cityofaustin/janis/pull/251/files):

> We may want to consider having the CMS, Joplin deliver this link instead of hard-coding it here in case this page is moved or the slug is updated.

> OH, now that I see this use case, it would make a lot of sense for Joplin to deliver a list of related services and their corresponding service page links. This way translations and links as well would be handled by Joplin and not hard-coded in case service names, slugs needed to be added, updated or dropped.

**Comment by easherma** [comment]
@briaguya is this still a relevant issue? I see a merged PR so maybe its stale. I don't have a good sense of what is hard-coded in janis off the top of my head.

**Comment by briaguya** [comment]
I feel like this issue is a bucket we keep trying to empty but end up filling up again, I'm going to close it, if there are specific instances we need to fix we should make specific issues for it, or just fix them.
