### ISSUE TITLE
Email confirmation to new users on Joplin

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4433]
As an onboarding user in Joplin, I'd like to receive confirmation when my user account has been created in Joplin so that I have a receipt for the account and a link to login in easily for my reference.

As a superadmin in Joplin, I'd like for Joplin to send an email to new users when their account has been created so they can confirm that I've made the account using the correct email address and there is a trustworthy communication for login, not an ad hoc personal note.

**Comment by briaguya** [comment]
probably related https://github.com/cityofaustin/techstack/issues/4402

**Comment by chiaberry** [comment]
also similar to issue #4397

**Comment by Jo-Dwyer** [comment]
This is all true. I think Tori's capture it. Will close this issue.
