### ISSUE TITLE
Fix Spanish translation errors across austin.gov

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4437]
*Make sure to add the label "Content debt." If available, add the appropriate "Content type" or "Feature" label.*
- [x] delete duplicative pages on 
        [X] "breastfeeding suport" and "get breastfeeding support"
- [ ] Merge
         [ ] "smoking in public places" and "Report Smoking in Public Places" 
- [ ] Translate the following topic lines
        - [x] Business permits and licenses
        - [x] Food business permits
        - [ ] Policing in Austin- _let's table this for now (IF)__
        - [x] Municipal Court
        - [x] Smoking in public places

- [x] Decide on whether it should be _"policia"_ or "oficial de la policia" and make uniform
- [x] Decide on a translation for oversight
- [x] Decide on a translation for "checklist" and update across couple of places (sorry!) 
- [x] Look for and fix "fracturas de servicios publicos" if I didn't already

- [x] [WIC](https://alpha.austin.gov/es/health-safety/health-prevention/kids-and-family-resources/wic-benefits/)
- [x] This page has quite a bit of redundancy
- [x] "Solicite beneficios de WIC" should be a headline or deleted. 

- [x] [Get immunized](https://alpha.austin.gov/es/health-safety/health-prevention/disease-prevention/get-immunized/)
- [x] This page in Spanish has redundancy at the top and the bottom that the English version doesn’t. 
- [x] el sec sabado
- [x]  a third bullet point  
- [x] the PDF can easily be incorporated into the website

- [x] [Find free condoms](https://alpha.austin.gov/es/health-safety/health-prevention/disease-prevention/find-free-condoms/)
- [x] The link given about Prep should link to the Spanish version of the site.

- [x] [Pickup free paint](https://alpha.austin.gov/es/housing-utilities/recycling-trash-and-compost/recycling-reuse/pickup-free-paint/)
- [x] The two lines at the bottom should be one. 
- [x] English copy has an extra line: “Need to drop off items to be recycled? See how to drop off at the Recycle and ReUse Center.”

- [x] [Find work as a day laborer](https://alpha.austin.gov/es/jobs/job-resources/help-finding-work/find-work-as-a-day-laborer/)
- [x] commas in the bullet points
- [x] ConstrucciónJardineríaCarpinteríaPinturaPlomería
- [x] We've used both the words "compostaje" and "compost" in the [recycling, trash and compost section](https://alpha.austin.gov/es/housing-utilities/recycling-trash-and-compost/), let's go with one. I believe they are both OK to use. 

**Have you documented this via the author notes field in Joplin?**
- [ ] Yes!
- [x] No, 

**What is the long-term, ideal solution for this content debt?**
Having an in-house translator or someone in-house who will proof the webpage or an arrangement with the translator that part of the contract is to proof the web copy (in that order of preference) 

**Is this related to a feature request issue? (Add the issue number below and add the issue as a dependency.)**

**Comment by InaraFernandez** [comment]
I am adding a few things to this task. Let me know if you'd rather I create a new task.
