### ISSUE TITLE
Joplin micro copy for Official documents and Official document collections

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4448]
Please review copy on these screens (https://xd.adobe.com/view/11e325e5-933c-40d5-654a-52b3e44b0864-67d2/) and update here (https://docs.google.com/spreadsheets/d/1ZwQmQFPh-YK0tXbc5oFoTz0IM_jAOZNrA_z6XpyrdaE/edit#gid=1885029904)

If you make an addition, (like adding secondary copy to a field), maybe think about a way to indicate that by changing the color or something. This isn't a very refined document in terms of structure. If you can think of a better way to do this, I'm all ears. Because there is a lot of overlap between page templates, I think it's useful to show all the templates on a single tab, but also it's not so great also for that reason. Maybe we could use a way to indicate component labels and secondary copy, or something. Feel free to improve. :)

**Comment by ablangworthy27** [comment]
@toribr I made additions to the spreadsheet and addressed all your responses in the mocks. I do think that the spreadsheet would be better if each type had its own tab. I am happy to take on the task of reorganizing but I don't want to step on any toes. Let me know.
