### ISSUE TITLE
Spanish Guide Page is broken

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#4449]
https://github.com/cityofaustin/joplin/pull/737

https://alpha.austin.gov/es/permits-tickets/business-permits-and-licenses/food-business-permits/gu%C3%ADa-de-permisos-para-los-vendedores-ambulantes-de-comida/

Clicking on link results in a 404

:(

Update:
Spanish slug is not getting set for this guide page. 
https://alpha.austin.gov/es/permits-tickets/business-permits-and-licenses/food-business-permits/mobile-food-vendor-permit-guide

**Comment by briaguya** [comment]
@Niicck we don't have spanish slugs yet. Just /es/slug-en/

Where are we seeing that first URL?

**Comment by briaguya** [comment]
definitely happening on topic pages, looking for more places
