### ISSUE TITLE
Joplin: account for all UI in Abstract

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4451]
Let's make sure we have all elements accounted for and organized in Joplin.

**Comment by toribr** [comment]
@chase This effort is now five sprints old. Let's break it out into separate issues if it's going to extend beyond Sprint 63. We don't want to have efforts that extend multiple sprints. Moving forward, pick a chunk that's sized for that Sprint given other efforts, and address that chunk only.

**Comment by chase-vert** [comment]
All UI is accounted for.
