### ISSUE TITLE
Content pin-up

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#4453]
### 1. Approve agenda
Priority is Larger discussion items, followed by workshopping.

### 3. Workshopping (style issues, etc...)

- [x] Gender inclusive Spanish-language content
- [ ] discussion around learn more button 
- [ ] Topic/collection discussion re: kids+family

### 4. Larger Discussions (roadmap, sprint goals, big projects)

- [x] Plan for OPO docs/onboarding.
- [x] Community gardens grooming
https://docs.google.com/document/d/1t8T4lZjp1k8yMwsW0RN-swBeN4AySVF2zWQlDkxwCfU/edit#
- [x] Content drafting checklist shareout from @srigdon 
https://docs.google.com/document/d/1X1BOn0_8-TLKqStKvVZZDGC0XOz12X8uiyt4yNVbabU/edit#heading=h.jzndgsrpwbmw

**Comment by srigdon** [comment]
1. Community gardens process - next steps and what we might needs in terms of agreements for Parks n' Rec so she can tee it up with the BRMs. 
2. Quick share of the accessible content checklist. 
3. Jo will share a presentation she'll give on Wednesday for feedback. 
4. If time: Gabi - global edits on "Learn more" within topic cards on topic collections and making changes to the information architecture.
