### ISSUE TITLE
Joplin new user email notification 

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4457]
Write email content to be used in new user email notification  #4397

What content should this email contain?

**Comment by ablangworthy27** [comment]
I started [a draft ](https://docs.google.com/document/d/16RwWBRphpPaab9yQl__DHO1VvMLIGVOIFpao7VKCMnI/edit#)for the new user email. Perhaps we can keep drafts of future notifications here as well?

@Jo-Dwyer @srigdon I thought it best to keep this email fairly simple, but let me know if there is anything else you think should be included.

**Comment by Jo-Dwyer** [comment]
That sounds good @ablangworthy27 
@Niicck can we generate an email that merges the user's first name in the greeting? The draft has an example.

**Comment by Niicck** [comment]
Yes, we have the technology.
