### ISSUE TITLE
Readdress structure of style guide index

### ISSUE THREAD

**Issue by courtneyjacinic** [cityofaustin/techstack#447]
Review the current structure of the style guide to ensure the most support for the CMS while standing alone.

@LauraTrujillo we probably need to recap this idea with @ashleecoa

**Comment by courtneyjacinic** [comment]
Working from this doc: 
https://docs.google.com/document/d/1TjJ3mJlgtChtUYZyKSuDk0mOqCisAIFbMUGRgoyb_wY/edit?usp=sharing

**Comment by courtneyjacinic** [comment]
- [ ] @LauraTrujillo
- [ ] @ashleecoa 
Please review purposed structure. Feel free to edit/make suggestions!

https://docs.google.com/document/d/1TjJ3mJlgtChtUYZyKSuDk0mOqCisAIFbMUGRgoyb_wY/edit#

**Comment by ashleecoa** [comment]
Looks great!
