### ISSUE TITLE
Fact check the community garden permit guide with SMEs

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#4472]
To do: 

- [x] Review the [guide outline](https://docs.google.com/document/d/1t8T4lZjp1k8yMwsW0RN-swBeN4AySVF2zWQlDkxwCfU/edit) and linked pages
- [x] Reformat the guide outline into one document with all guide content (information and service pages) included (@gabrielaperezdelaosa to do)
- [ ] Prep for work session by making a list of all fact checking questions. 
- [x] Schedule a work session with Jennifer to fact check all guide pages and cut the ones no longer necessary. 
- [ ] Do the work session. 
- [ ] Make an issue for each page. Each issue should include these steps: 
> - [ ] Rewrite the page, save draft in Joplin
> - [ ] Send to Jennifer for fact check review
> - [ ] Content team does 2 rounds of edits
> - [ ] Send for approval
> - [ ] Publish
- [x] Ask CPIO Language Access about translating the guide into Burmese.

**Comment by gabrielaperezdelaosa** [comment]
- [ ] Reach out to [Burmese translators](https://library.austintexas.libguides.com/ld.php?content_id=51824861)

**Comment by srigdon** [comment]
The parts checked above are done, so closing this and making the rest #4684
