### ISSUE TITLE
MVP translations flow

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4479]
Use requirements to sketch flow or design screens if necessary

Document flows

**Comment by gabrielaperezdelaosa** [comment]
Adding a link to the [workflow map](https://miro.com/app/board/o9J_krWx8QY=) here too

**Comment by gabrielaperezdelaosa** [comment]
I'm closing issue #682 since it is redundant with this effort, but does have useful info.

**Comment by toribr** [comment]
Closing this as MVP for report has no design needs.
