### ISSUE TITLE
Prioritize next round of departments for content transition

### ISSUE THREAD

**Issue by sammodabber** [cityofaustin/techstack#4487]
- [ ] Set kick off meeting with Ashley Parsons (BRM)
- [ ] Determine list of departments ready/available for content transitions based on next round:

- Austin Public Library
- Austin Police Department
- Austin Fire
- Austin Resource Recovery
- Animal Services
- Parks and Recreation
- Office of Sustainability

**Comment by ablangworthy27** [comment]
@Jo-Dwyer @sammodabber Not sure, If I or anyone else already communicated this, but the Design team expressed concern over starting a department that needed new features/content types. They would prefer we pick a department that is an easy win, straight forward transition.

**Comment by sammodabber** [comment]
Set up prioritization meeting

**Comment by sammodabber** [comment]
@Jo-Dwyer How does this fit into our new pivot plan?

**Comment by sammodabber** [comment]
Don't meet with Ashley parsons
