### ISSUE TITLE
MVP New Official Documents Container

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#4504]
Related Issues:
https://github.com/cityofaustin/techstack/issues/4374
https://github.com/cityofaustin/techstack/issues/4395

**Comment by chiaberry** [comment]
https://miro.com/app/board/o9J_kq2Gpvo=/
Things to keep in mind
- [ ] janis urls bypass?
- [ ] disable preview?
- [ ] view live takes you where?
- [ ] topic collections : topics :: official documents list : official document page
