### ISSUE TITLE
Creating a current translation style guide

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4506]
[x] finalize translation workflow
[x] read and archive existing translation guides
[x] draft a [new guide](https://docs.google.com/document/d/1g-RO_pVNZHbArmwXPnrOtFfM1GWTudJiVZgx-A5jnIY/edit?usp=sharing)
[x] have conversations to learn about and maybe revise previously made decisions about what shouldn't be translated
[ ] add translation guide to our style guide

**Comment by gabrielaperezdelaosa** [comment]
@ablangworthy27 I think this is ready to be added to the Style Guide in its own section. Page 3 which is on our translation workflow probably does not need to be added.

**Comment by ablangworthy27** [comment]
@gabrielaperezdelaosa wondering what you think about swapping out the philosophy section for this:

Content should meet residents' needs, no matter what language it is in. Throughout this style guide, there are suggestions for writing resident-friendly English language content. Keep these same suggestions in mind when tackling translations. Start by using plain language and writing with brevity. Both of these suggestions: 

- Save money for the City by making web page translations quicker 
- Save time for residents by making in-person translations easier.
