### ISSUE TITLE
Search enhancement: enter (keypress) to submit search query

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4510]
Functional oversight on my part, so I apologize for that. This isn't a high priority issue.

# Criteria
- [ ] When search input field is populated with >1 character, the resident should be able to hit the `enter` key to submit their search

**Comment by robbobfrh84** [comment]
PR ready for QA: https://github.com/cityofaustin/janis/pull/813 !

**Comment by jairPineros** [comment]
QA Test comment
