### ISSUE TITLE
Revise "Participate in User Research" page

### ISSUE THREAD

**Issue by InaraFernandez** [cityofaustin/techstack#4515]
Proposal to revise: https://alpha.austin.gov/es/feedback and https://alpha.austin.gov/en/feedback/

**Comment by gabrielaperezdelaosa** [comment]
Let me know if you need anything from me here, otherwise I'm happy to serve as proofreader/idea bouncer and let you take the lead on this.

**Comment by InaraFernandez** [comment]
[https://app.zenhub.com/files/118780243/699563d2-f1e0-4ddc-8884-d45fb0c34b14/download](https://app.zenhub.com/files/118780243/699563d2-f1e0-4ddc-8884-d45fb0c34b14/download)

Suggested Edits (turn track changes on)- @gabrielaperezdelaosa let me know your thoughts.
