### ISSUE TITLE
Add hyperlink best practices to Style Guide

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#4518]
Funshop content on hyperlinks is not in the Style Guide. Let's add it! 

Hyperlink best practices

Do:
Be descriptive.
Give a preview of what will be found by clicking.
Include file size on links to download a file (e.g., PDF, spreadsheet). 

Example:
Diabetes can be managed with diet and exercise. Read more about diabetes prevention. 
Download the care manual (96 kb) for more information 

Don’t:
Use “click here” 
Be vague
Navigate away from the website (have external sites open in a new tab)

Example:
Click here for Diabetes info.

Here is more info.

**Comment by ablangworthy27** [comment]
this is done
