### ISSUE TITLE
Dashboard UI/UX review of (COVID)

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4524]
At the request of web services, Chase and I will review and write up a list of issues/improvements to the COVID dashboard, and submit to GIS for possible further design work.

Abstract branch / Office hours: https://share.goabstract.com/9dfa7afe-b16c-47bb-a5b9-424bfcbf0fda

Acceptance criteria:
- [x] Document which outlines a phase I suggestion of improvements

**Comment by chase-vert** [comment]
Here's the doc: https://docs.google.com/document/d/1EOQNII8Wa0xKXCagWQ-UAB-qQKIw8y5g8coUPbeABAs/edit#

Feel free to edit and send along!
