### ISSUE TITLE
Create a drop-down menu for "Authoring Office of Document" 

### ISSUE THREAD

**Issue by InaraFernandez** [cityofaustin/techstack#4528]
### As a content author entering numerous documents into Joplin, I am asked to manually enter the "authoring office of document" field. This might present a problem if there are department name changes and it also leaves more room for error. For instance, we are looking to change the OPO department translation and doing so means we have to retroactively change the name in every entry (there are many!). 

![image.png](https://images.zenhubusercontent.com/5ecd8a286f3d7a1e1c2fa134/9a9d5c25-fb9b-4e7e-aa2c-aa6b42af3354)

**Is your feature request related to a problem? Please describe.**
We are going to be changing the translated name of the Office of Police Oversight and will have to manually change the "authoring field" hundreds of times. 

**Describe the solution you'd like**
A dropdown menu where the Joplin user can enter the authoring department.

**Comment by toribr** [comment]
Wondering if this might be handled on the back-end only, with no UI changes. Putting it on the dev/design sync agend for 7/1.

**Comment by Niicck** [comment]
Hi @InaraFernandez ! Here are the dev/design thoughts on this:

- The "authoring office" dropdown does not relate to departments. In some cases, the "authoring office" is a department, but in other cases it is not. So we don't have a single source of truth for every possible "office" the same way we do for "departments".
- When the time come to change the translation for OPO's name, you can talk to dev and we'll make a script to automatically change all the office names.

**Comment by toribr** [comment]
Thanks for writing this follow up, @Niicck ! @InaraFernandez I'm closing this issue - when the time arrives for translation, write a new issue for the script request.
