### ISSUE TITLE
Identify language access expectations to bring up in kickoff with newly transitioning departments

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4529]
When we kickoff content transition with a department, language access should be a part of the conversation.

**Comment by gabrielaperezdelaosa** [comment]
I added the following line to our [MVP Department Transition Goals:](https://docs.google.com/document/d/1plMhCSm6NbA3wXdbFVrXE6OVnx0CC72gWF5nVVOMMYQ/edit)

Goals: 1) Department staff will understand that language accessibility needs to be part of the content-creation process and that quality translations require groundwork. 
2) Identify key language stakeholders and decision-makers (a translation vendor? A staff member? SPOC?)

Objectives: 1) Document who the stakeholders are, what the artifacts exist, what research might need to be done, how will translations be carried out, how will translation decisions be made. 
2) The department will have a terminology list of preferred translations. 

Outcomes: The department will have a translation workflow process in place for alpha.

------

Totally open to suggestions here, this is only a draft. But if there are none, does this meet exit criteria for this issue? Or what is exit criteria? @Jo-Dwyer @InaraFernandez

**Comment by gabrielaperezdelaosa** [comment]
Given the fact that:
- we discussed this in a content team meeting documented [here](https://miro.com/app/board/o9J_kpbRTN0=/)
- [MVP Department Transition Goals](https://docs.google.com/document/d/1plMhCSm6NbA3wXdbFVrXE6OVnx0CC72gWF5nVVOMMYQ/edit) was updated
- and we are shifting to a different transition model where kickoff meetings are as of yet undefined 
I am going to close this issue. 

Under our new transition model the steps we are taking to consider language access up front include: 
- gathering and recording terminology (in Monstro) from pages transitioned
- working towards having Google translation API integrated
