### ISSUE TITLE
Add 'how to add a button' to style guide service page/form container instructions

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4535]

**Comment by gabrielaperezdelaosa** [comment]
@ablangworthy27 I think this is your ballpark now but let me know if I can help in any way

**Comment by ablangworthy27** [comment]
This is done.
https://app.gitbook.com/@cityofaustin/s/digital-style-guide/publish-content-on-austin.gov/pick-the-perfect-content-type/service-page
