### ISSUE TITLE
Translation Capability for Contact Snippets

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4542]
![image.png](https://images.zenhubusercontent.com/5ecd5c4a1cb98b2a16b27154/7ea5e42f-6093-473e-aaf1-73660f89c280)

### As a content strategist and/or author I want to be able to translate contact information so that 
1) Limited English Proficiency users have access to all of the same meaningful information 
2) Our Spanish language site (and in the future other languages) looks cohesive and professional (i.e. doesn't have OPO translated in one place and not translated in another place)

**Describe the solution you'd like**
A multilingual tab, parallel to the tabs we have in other areas of Joplin.

**Describe alternatives you've considered**
Lines for each language on one page instead of a tab would be fine too. 

**Additional context**

**Comment by toribr** [comment]
@gabrielaperezdelaosa This is actually designed and covered under #4186!
