### ISSUE TITLE
Decide MVP SEO requirements

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#4543]
[Did some research](https://docs.google.com/document/d/14SLDqzXuITosgr-p8lgGb-deC8pdvkrF0KbUQame368/edit#), plus drafted requirements and started a question list. 

Tasks: 

- [ ] Decide what changes, if any, need to be made to the UI. 
   - [x] @toribr can you review the questions under MVP in the document above? 
   ~- [ ] @Jo-Dwyer @ablangworthy27 @InaraFernandez @gabrielaperezdelaosa can you review content questions in the doc?~ Added #4562 and #4563 for content cove to-dos. 
- [x] Make an issue for dev team to implement the decisions below. 

Decisions: 

- Move the slug field from the SEO tab to the Content tab. Retain the slug field for all languages. 
- Add a keyword research field in the Notes tab. User story: As a content author, I need to do keyword research and store those keywords in Joplin so that my content team and I don't forget which ones we should incorporate into the title, description, first couple of paragraphs, and/or H1s and H2s. 
- Nix the SEO tab. 
- Auto-generate a sitemap. 
- Include a robots.txt. 
- Create a custom 500 page. 

Decision still needed:

- Which meta tags, if any, are important to include? See research doc above for info sources.

**Comment by toribr** [comment]
See issues #4581, #4582, #4583 and #4584
