### ISSUE TITLE
Create a form container page for opt out letter

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4547]
When a defendant cannot or will not complete the terms of a deferral and chooses not to explain the reason to a judge, they can "opt out" of a deferral and choose to plead guilty with no contest. 

https://cityofaustin.formstack.com/forms/opt_out_letter

**Comment by Jo-Dwyer** [comment]
@toribr

**Comment by gabrielaperezdelaosa** [comment]
https://alpha.austin.gov/municipal-court/opt-out-of-deferral-process/

**Comment by gabrielaperezdelaosa** [comment]
@InaraFernandez is creating the Spanish form stack based on this language: http://www.austintexas.gov/sites/default/files/files/Municipal_Court/SPANISH_Opt_Out_Form_03_2019.pdf

**Comment by gabrielaperezdelaosa** [comment]
@InaraFernandez please review based on google doc

**Comment by gabrielaperezdelaosa** [comment]
@srigdon we couldn't do a Spanish formstack but please review the existing form container based on the google doc
https://docs.google.com/document/d/1Nmhrts1_J-8zoi99C9egoKZ2rkfC_RDWIOhGgoQtXFI/edit
