### ISSUE TITLE
Create a service page for Request a deferral for driving without proof of valid insurance

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4552]
https://cityofaustin.formstack.com/forms/deferred_disposition_request_no_insurance_violation

### Currently, instructions for how to access this service is buried within the form itself. Let's put these steps in to a service page.

1. The payment must be made immediately in the amount of $125.00 plus collection and/or warrant fees, if applicable. The amount due may be obtained by calling 512-974-4800. Please confirm that this request has been processed before submitting payment online. You may also pay in person at both of the court's locations, by mail, or by calling 512-974-4800. Contact the court if you cannot pay immediately; and

2. Maintain the minimum liability insurance coverage as required by law without lapse during the deferral period (attach copy of insurance or binder with this form); and

3. Possess and maintain a valid driver license or permit during the deferral period (attach copy with this request); and

4. Notify the Court in writing of any change of name or address; and

5. At the end of the deferral period, submit a letter (Letter of Experience) from your insurance company or agent showing that the above mentioned insurance has been in effect from the date this form is postmarked for a period of 180 days to the Court.

**Comment by InaraFernandez** [comment]
@Jo-Dwyer , is this meant to be a form container? If not, do you have the text for the service page?

**Comment by InaraFernandez** [comment]
hey @Jo-Dwyer I am not 100% I did this right: https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZTo1NjU=

Let me know what changes need to be made, I am happy to have a quick call to learn more :).

**Comment by gabrielaperezdelaosa** [comment]
The first step of this makes no sense to me:

> The payment must be made immediately in the amount of $125.00 plus collection and/or warrant fees, if applicable. The amount due may be obtained by calling 512-974-4800. Please confirm that this request has been processed before submitting payment online. You may also pay in person at both of the court's locations, by mail, or by calling 512-974-4800. Contact the court if you cannot pay immediately; and

Also, step 5 refers to the date this form is postmarked. I think we gotta update that to "the date the form is submitted"

**Comment by gabrielaperezdelaosa** [comment]
covered under #4066
