### ISSUE TITLE
Create a form container for Request a deferral for a traffic violation 

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4554]
https://cityofaustin.formstack.com/forms/deferred_disposition_request_moving_violation

**Comment by InaraFernandez** [comment]
See here: https://alpha.austin.gov/en/preview/form/UGFnZVJldmlzaW9uTm9kZTo1NTQ=

**Comment by gabrielaperezdelaosa** [comment]
@srigdon this is one of the pages that was already on the google doc list for your review just under #4567

**Comment by srigdon** [comment]
Reviewed and [left edits in Notes](https://joplin.herokuapp.com/admin/pages/260/edit/#tab-content) for someone with a Formstack license. 

- [ ] Edits made in Formstack.
