### ISSUE TITLE
Work on new Drupal 8 survey questions sent by CPIO 

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#4560]
CPIO suggested adding new survey questions to Drupal 8 survey:

- Do you add images to your posts?

(If yes:)
    - [ ] Where do you typically get your images from?
    - [ ] Do you resize or crop images before uploading them? Do you wish Drupal had better tools for doing this, or is your process working fine with tools you already have?

(If no:)
    - [ ] Do you want to upload images, but don’t have a good source for finding usable images?
    - [ ] Do you want to upload images but the process in Drupal is too difficult?

**Comment by Jo-Dwyer** [comment]
@anukandimalla this seems no longer relevant... should we close it?

**Comment by anukandimalla** [comment]
Thanks, @Jo-Dwyer.will close this issue.
