### ISSUE TITLE
Add SEO content to the style guide

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#4562]
Once we [decide which information to include](https://docs.google.com/document/d/14SLDqzXuITosgr-p8lgGb-deC8pdvkrF0KbUQame368/edit#), add it to the style guide. 

Use content from #4563.

**Comment by srigdon** [comment]
Add to the Information page entry: 

**Research keywords.** 
Start by thinking about words and phrases you would use to find this page. What problem is the searcher intending to solve? Try searching one of those phrases in Google, then scroll to the bottom of the first page and check the suggestions under “Searches related to (your search term).” Which of these most closely matches the searcher’s intent? Pick 2-3 keywords to incorporate into the title, description, the first 1-2 headers, and the first 1-2 paragraphs or steps. 

Add to the Service page entry: 

**Research keywords.** 
Start by thinking about words and phrases you would use to find this page. What problem is the searcher intending to solve? Try searching one of those phrases in Google, then scroll to the bottom of the first page and check the suggestions under “Searches related to (your search term).” Which of these most closely matches the searcher’s intent? Pick 2-3 keywords to incorporate into the title, description, the first 1-2 headers, and the first 1-2 steps or to "Related information" after the steps.

**Comment by ablangworthy27** [comment]
Done!
