### ISSUE TITLE
Content Sync 6/30

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#4564]
Content cove needs to get together and redistribute the collective workload. It seems like these might be good places to start in preparation for Tuesday:

- Make a list of things you are interested in learning more about or exploring further (Gabi & Inara & Amanda)

- Make a list of everything on your plate, prioritizing highest to lowest, and give it a number. (Sarah & Jo)

This is just an idea, if anyone has suggestions of better places to start, let me know.

**Comment by srigdon** [comment]
Brainstorm board: https://miro.com/app/board/o9J_kpnlul8=/
