### ISSUE TITLE
Micro-copy planning

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#4565]
**Objective** 

- Establish a workflow for micro-copy 
- Dig into Amanda's proposed spreadsheet changes ([Amanda's copy of page templates](https://docs.google.com/spreadsheets/d/1g99yNEBKo8dyBuRp0X62xrokRAbl_h8d2Zk_nunOJbc/edit#gid=1885029904) to review, working off [Chase's original](https://docs.google.com/spreadsheets/d/1ZwQmQFPh-YK0tXbc5oFoTz0IM_jAOZNrA_z6XpyrdaE/edit#gid=1885029904))
-start the conversation about folding in the Spanish copy.

**Participants**
@ablangworthy27 
@toribr and/or @chase-vert 
@gabrielaperezdelaosa 

*Let me know if next week or week of 7/6 is better to schedule time.
------
- [ ] Schedule meeting
- [ ] Meet
- [ ] Create resulting issues

**Comment by gabrielaperezdelaosa** [comment]
Either week works for me.

**Comment by toribr** [comment]
Either is fine, but I am taking th/f off next week.
