### ISSUE TITLE
Please review these form containers I created

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4567]
https://alpha.austin.gov/municipal-court/opt-out-of-deferral-process/

https://alpha.austin.gov/municipal-court/request-to-take-a-driving-safety-course/

https://alpha.austin.gov/municipal-court/request-a-deferral-for-a-water-safety-violation/

https://alpha.austin.gov/municipal-court/request-a-deferral-for-criminal-disabled-parking-violation/

**Comment by gabrielaperezdelaosa** [comment]
Had to create an info page called "Request a deferral for a moving violation"  to parse out the difference between:
(F) Request a deferral for a moving violation
(F) Request to take a driving safety course

**Comment by Jo-Dwyer** [comment]
@gabrielaperezdelaosa containers look good, but I want to QA the forms. They're live so it'll require more coordination. Closing this issue.
