### ISSUE TITLE
Services offered are lacking visibility in the location page type

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4579]
When I go to[ a location page such as this one](https://alpha.austin.gov/en/location/rosewood-zaragosa-neighborhood-center) I have to scroll way down to see other services offered at that location. And then when I do get to services offered there is duplicative time information. If the user clicks in and gets the phone number, it is not very likely that they'd scroll down to see what else they can do there. There seems to be a lot of empty space on the page that maybe we could utilize at least for a desktop version? 

![image.png](https://images.zenhubusercontent.com/5ecd5c4a1cb98b2a16b27154/39190cbb-3038-4d4f-ab79-50ff8a03ecb9)
I don't think we need anything except "Get help with rent and utilities" hyperlinked.

**Comment by toribr** [comment]
@gabrielaperezdelaosa Actually, the hours there are necessary, as the hours for the location and the hours for the service may be different. 

The primary purpose of location pages is to provide location information. The services offered there are secondary. Therefore, they're fine where they are, as we want to 1st support the primary use case.
