### ISSUE TITLE
SEO tab and page template changes

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4581]
See originating issue: https://github.com/cityofaustin/techstack/issues/4543

As an author, I want it to be easy to keep the page title and page slug in sync, and also be translatable.

- [ ] The slug field, now found on the SEO tab, should be moved to below the title on all page templates.
- [ ] Hide the SEO tab on all page templates

Having them on two different tabs has resulted in the slug getting out of sync - additionally, we don't need any of the other stuff on this tab.

Acceptance criteria
- [ ] The page slug field set is to display below the title field set on every type of page template
- [ ] The SEO tab is no longer displayed resulting in language tab, notes and settings tabs only

**Comment by chiaberry** [comment]
SEO tab removed on all pages, and slug field under title on the following pages:

- [ ] Department page
- [ ] Topic collection page 
- [ ] Topic page
- [ ] Official document collection
- [ ] Official document page
- [ ] Service page
- [ ] Information page
- [ ] Guide page
- [ ] Form container
- [ ] Location page
- [ ] Event page
- [ ] News page
