### ISSUE TITLE
Official docs: Janis enhancements

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4591]
## Overview
This update creates the new view of a single official document
- Displays the collections that an official document belongs to
- Lists all document attachments within the single document view
- Gain the ability to link to a single official document

### Resources
- Abstract branch: https://share.goabstract.com/2ed5b7fe-57d6-47f8-afa1-9a805630ab4e
- Original design issue: #4435

## Acceptance criteria
- [ ] Implementation matches mocks

### Official document page
Overall this page is very similar in structure to `Information pages`. The only exception is that there's a `Documents` H2 heading within the body section, and beneath that is where the attached documents are listed.
- [ ] `Documents` H2 heading in page body
  - [ ] Attached documents populate under this heading as a list
  - [ ] Attached document includes trailing metadata (the same as what's implemented elsewhere) `file type` and `file size`
- [ ] `Part of` indicator lives in the right rail of the header section (the 1/3 chunk to the right of the description area), and lets a user know that this document is part of another collection. If the document is part of more than 1 collection, the tiles should stack per the normal pattern. This pretty much the same as the `Guide` indicator.

**Contextual nav**
- [ ] `Parent topic` goes in the far left
- [ ] Remove `related to`
- [ ] `Offered by` parent department in the far right

### Search presence
~~Feel free to break this out into a separate issue!~~
now in issue #4618

**Comment by chiaberry** [comment]
@chase-vert, I'm ready for a visual inspection. 
https://janis-v3-4591-janis-docs.netlify.app/police-oversight/report-2018-officer-involved-shooting-june-2020/

I pointed out during dev-design sync that the official document page doesn't include "Authoring Office" which is visible in the official document collection. Do you want me to add it back in?

**Comment by chase-vert** [comment]
Great job, @chiaberry ! This looks good, I only had a few small tweaks.

**Desktop**
- [ ] h1 (page title) width: we use the full-width for news only, and I was trying it out here but I prefer reverting this back to the 2/3 proportion that we use everywhere else

**Tablet**
- [ ] Small bug between 724px-767px where the layout sets the `part of` container and the `page body/link list` side-by-side, and we just wanna have those stack vertically as they do on mobile

**Mobile**
- [ ] Subhead text: from 24px to 18px (this is looking a little too big for an iPhone 5/SE). 
- [ ] h2: from 20px to 24px

All
- [ ] Spacing between h2 ("Documents") and `list items`: let's just make this 16px across the board for desktop, mobile, and tablet.

**Comment by chase-vert** [comment]
Good to go 🚀
