### ISSUE TITLE
microcopy for Official Documents Collection

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#4598]
As a result of splitting Official Documents into Official Document Collections and Pages, we have some new microcopy. 

https://joplin-pr-4504-doc-migration.herokuapp.com/admin/pages/search/
Note: it says Official Document Page New in  some places on this test branch, that will not be the case when its in production. Its just leftover from me _trying new things_

- [x] Create Content Modal: description for what an Official Document Page is
- [x] Create Content Modal, Choose Title Step for Official Document Collection
- [x] Create Content Modal, Choose Title Step for Official Document Page
- [x] Official Document Page, field to choose which Collection it belongs to

![Screen Shot 2020-07-08 at 9.55.49 AM.png](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/6b56b782-8d32-462a-8e0a-4e8d1fde1057)
![Screen Shot 2020-07-08 at 10.12.15 AM.png](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/61f23daa-5e71-4167-accf-bf9e2eb6b7dc)
![Screen Shot 2020-07-08 at 10.12.32 AM.png](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/65c9cd10-c94b-44fa-9845-3ca1acc2a563)
![Screen Shot 2020-07-08 at 10.04.04 AM.png](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/e4bbe00b-a310-407c-bdfb-b7b51577851f)

**Comment by ablangworthy27** [comment]
@chiaberry I will also document this in the microcopy spreadsheet. It is a bit of a mess right now, so see below for my edits. 

**Create Content Modal: description for what an Official Document Page is**
A single official document
**Create Content Modal, Choose Title Step for Official Document Collection**
Write the name for this list of documents
Is it possible to change "Page title" to "List title"?
**Create Content Modal, Choose Title Step for Official Document Page**
Write the name for this document
And change "Page title" here to "Document title"
**Official Document Page, field to choose which Collection it belongs to**
This is fine as is, but need to change the capitalization. Should be:
Official documents collections this document belongs to
Select and official document collection
