### ISSUE TITLE
Integrate or link project tracker tool into alpha.austin.gov

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#46]
https://grackle.austintexas.io/

Team that created this tool:
@mateoclarke – developer
Tori Breitling – UX designer
Daniel Honker – product owner

Need to work out position within information architecture and resolve styling variations.

**Comment by amenity** [comment]
How is this related to https://github.com/cityofaustin/joplin/issues/45? Can these issues be combined or clarified?

**Comment by mateoclarke** [comment]
@amenity There would be work in both Janis and Joplin for this feature. Updating models in wagtail + layout and frontend work in Janis. Separate tasks in the system.

**Comment by amenity** [comment]
@mateoclarke - that makes sense, but this one is in /techstack. And cityofaustin/joplin#45 assumes that we won't be going the "link to" route, right?

**Comment by mateoclarke** [comment]
That was the assumption. That we would use the existing prototype to update the CMS models. But if it needs more requirements defined be we start work...

**Comment by amenity** [comment]
Picking this guy back up! 🐜I want to learn about the costs/benefits of integrating the project tracker into alpha instead of linking to the site so I can prioritize accordingly.

**Comment by mateoclarke** [comment]
Seems like you'd want to talk to @danielhonker if you haven't yet.
