### ISSUE TITLE
Website notifications

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#460]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1463708/45661733-6bd0c300-bac4-11e8-8dc7-216aabbbc8d8.gif)
Example from NC.gov where bell/alert icon displays in upper right.

Aha! Link: https://desi1.aha.io/features/RT-282

**Comment by amenity** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1463708/45661733-6bd0c300-bac4-11e8-8dc7-216aabbbc8d8.gif)
Example from NC.gov where bell/alert icon displays in upper right.

**Comment by chase-vert** [comment]
This issue is being worked out in the alerts epic: https://github.com/cityofaustin/techstack/issues/1807
