### ISSUE TITLE
Primary Nav overlay is missing on the Alpha research participation web page in Mobile version

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#4604]
## Describe the bug
The primary navigation overlay(Hamburger menu) is not showing on the Alpha research participation page(https://alpha.austin.gov/en/feedback/) is missing.

## URL
https://alpha.austin.gov/en/feedback/

## To Reproduce
Steps to reproduce the behavior 
1. Go to https://alpha.austin.gov/feedback/ on mobile
2. Click on Primary Nav(Hamburger Menu) top left corner
3. Notice the overlay

## Current behavior
The primary Nav overlay is missing and but the Nav content is available in-page by pushing the page content.

## Expected behavior
A clear and concise description of what you expected to happen

## Screenshots
[Video link for error](https://drive.google.com/file/d/168Q93BqXs2nICwIdTpSKxgsZhXxxGecY/view?usp=sharing)

## Device and browser
Chrome and iPhone 11

**Comment by chiaberry** [comment]
Has been corrected in another issue

**Comment by jairPineros** [comment]
looking into this
