### ISSUE TITLE
Navigation to Alpha research participation is missing from home page in mobile version

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#4605]
Description:
The Main navigation overlay is missing the Main Nav - Footer links. **This is the only place the link is available to Austin Residents to navigate to https://alpha.austin.gov/feedback/**

For understanding, here is the reference screenshot from desktop and mobile versions
![image.png](https://images.zenhubusercontent.com/5d236a251149c07fcf3f4fbc/b1b050ed-d735-41ea-aed7-7d485c18b976)

Mobile Versions:
![image.png](https://images.zenhubusercontent.com/5d236a251149c07fcf3f4fbc/493785ec-869f-4e26-903c-6e9b26ea15c3)

Tagging @toribr for refernce

**Comment by toribr** [comment]
@chase-vert Additionally, I don't think the new WIP banner includes any link to feedback sign up, does it? 
@anukandimalla Please remind me how many people have signed up since this link was put into place.

**Comment by anukandimalla** [comment]
**This is the information from Google Analytics, @toribr** 

1. No. of page views from Feb 1 - June 12th,2020 | 23 pageviews | 18 sign-ups(none from the alpha.austin.gov)
2. No. pageviews before Feb 1, 2020 | 0 | (Analytics didn't set up before Feb)

When tabling or social media promotions, I usually navigate users via this https://alpha.austin.gov/en/feedback because Austin residents have an idea of what to expect from research, the process of research and it helps in gaining trust.

**Comment by toribr** [comment]
@anukandimalla Can you clarify this - you state above "none from the alpha.austin.gov". So the 18 sign-up you received did NOT originate from alpha? (I'm assuming they originated from social media promotions, then, is that right?)

**Comment by anukandimalla** [comment]
@toribr Thats correct. None of the Sign-up from the user-path of Home page> open Nav bar> click the link "Help us to improve the website" > navigate to Austin participant research sign up web page > click on the google form to sign-up

All sign-up's are from other channels Social media promotions,in-person emailing(Post research thank you email).

**Comment by toribr** [comment]
Taken care of another issue by adding a link in feedback module. See #4494
