### ISSUE TITLE
Implement gzip compression for Janis

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#4611]
Modify react-static's webpack to use gzip compression. This is an easy, single thing we can do to improve performance. After we get this working, it'll be easier to add incremental additional webpack improvements.

Modifying react-static's webpack is harder than I'd hope.

I've submitted a support question here: https://github.com/react-static/react-static/discussions/1470

**Comment by Niicck** [comment]
Compression isn't working on prod I guess. https://gtmetrix.com/reports/alpha.austin.gov/RSAO2ovE

**Comment by Niicck** [comment]
### QA
Alright, so, we wanted to compress Janis. Turns out this plugin I added did nothing. What I really needed to do was tweak a couple of settings in AWS S3 and Cloudfront to get it to automatically compress our site for us. Those changes can be seen in this Publisher PR: https://github.com/cityofaustin/publisher/pull/16

- [ ] Check that it still loads: https://janis-v3-4611-gzip-2.netlify.app/
- [ ] Check that compression works even after removing compression-webpack-plugin
  - [ ] Proof: https://gtmetrix.com/reports/janis-v3-4611-gzip-2.netlify.app/BCPPifoM

I already did the AWS config changes in staging and production. So you can see for yourself that Production is fixed.
Check it out, we're not longer failing (64%). :)
https://gtmetrix.com/reports/alpha.austin.gov/hRqibkcK

**Comment by jairPineros** [comment]
Compression is not failing anymore ![Screen Shot 2020-07-21 at 2.34.35 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/fb995cce-86d6-402e-87de-394e2e58c884)
