### ISSUE TITLE
Need help with Spanish translation for Library social media research sign-up promoting post

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#4612]
Document:
https://docs.google.com/document/d/1hU_1ic3IL4GL93elD-yyvKXad3qP0uiC6zyjQTnTaQI/edit?usp=sharing

**Comment by InaraFernandez** [comment]
I checked the Sign-up forms and it looks like email is a mandatory field for both the English and Spanish forms.

**Comment by anukandimalla** [comment]
Will make sure to change it to either/or, Inara before Monday

**Comment by InaraFernandez** [comment]
@anukandimalla Are we OK to close this issue?
