### ISSUE TITLE
Clean data - Official Document Pages in search results

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#4618]
Note: this issue the first part of adding Official Document Pages to search. The 2nd part, which focuses on the styling part of adding Document Pages to search results, is here...
- https://app.zenhub.com/workspaces/techstack-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/4861

The first part focuses soly on the searchBuilder and making sure it ends up in the search results component with all data points needed and without any unused code.

### Resources
- Abstract branch: https://share.goabstract.com/2ed5b7fe-57d6-47f8-afa1-9a805630ab4e
- Original design issue: #4435

## Acceptance criteria
- [ ] Implementation matches mocks

### Search presence
~~Feel free to break this out into a separate issue!~~ done!
- [ ] Document titles are now hyperlinks that go to the single document view
- [ ] `Date` removed
- [ ] `Theme` removed
- [ ] `Part of`: if the document is part of a larger collection, list that collection page name here as a hyperlink. If the document is part of multiple collections, list them inline and separated by a comma
- [ ] `From`: list this as a static string and not a hyperlink

**Comment by robbobfrh84** [comment]
@jairPineros ready for QA: https://github.com/cityofaustin/janis/pull/844
- Deployed: Deployed: https://janis-v3-search-docs-styles.netlify.com/
