### ISSUE TITLE
Add language to the style guide about how to use options

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4625]
I have been misusing the "options" feature to provide information rather than actionable steps. For example here:
[Get a juvenile criminal record expunged](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZTo3MTc=)

I didn't know that it could not/should not be used this way but Sarah says that Tori has a very clear explanation about why users' mental model requires the drop down to have an actionable item. 

That information needs to be added to the style guide.

**Comment by gabrielaperezdelaosa** [comment]
@toribr

**Comment by gabrielaperezdelaosa** [comment]
Here's another example of me using it wrong but I'm not sure what the right fix would be: https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZTo2NDQ=

**Comment by ablangworthy27** [comment]
Need review:
https://docs.google.com/document/d/1x_8FWsXkkeMQrwKeVQA09Bj9IalJdfyu56hjJemTBcc/edit#

**Comment by ablangworthy27** [comment]
Ran this by content team in slack, and it seems to be fine. I published and this issue is closed!
