### ISSUE TITLE
Create a lawyer filing cabinet page

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4629]
There are 3 forms that someone (mostly a lawyer) would use to interact with the court during a hearing. I think they’ll always exist at least partially as PDFs because they are used in the physical courtroom. 

- [ ] decide on a title  “Manage your court appearance” “Navigate your court appearance” or “Interact with the court” 
- [ ] upload and link to the following PDFs
Motion Form - Adult
Motion Form - Juvenile
Enter a plea
Plea form-English 
Attorney Appearance Docket Waiver Request Form
- [ ] decide if we need an additional service page for entering a plea

**Comment by gabrielaperezdelaosa** [comment]
turns out file a motion with the court is the only thing we really needed here.

**Comment by Jo-Dwyer** [comment]
@gabrielaperezdelaosa can we close this then?

**Comment by gabrielaperezdelaosa** [comment]
Yes, Inara reviewed the form container for file a motion.
