### ISSUE TITLE
Create a formstack for orgs to apply to be a community service provider for the court

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4635]
This is the form:
https://joplin3-austin-gov-static.s3.amazonaws.com/production/media/documents/Community_Service_Provider_Application_Agreement.pdf

- [x] create form in formstack
- [x] create form container around it: 
Title: Apply to be a community service provider for the court
Description: If you represent a government agency, educational institution, non-profit, or other organization that provides services to the general public that enhance social welfare and the general well-being of the community you can apply to appear on the Municipal Court's list of community service sites. 
- [ ] send to Amy for first-check
- [x] send to first content-team reviewer
- [ ] send to second content-team reviewer

@InaraFernandez the form creation is the most important part, obviously, and I'm happy to take it from there, or if you want to run with it go for it

**Comment by InaraFernandez** [comment]
See form here: https://cityofaustin.formstack.com/forms/community_service_provider_application_agreement

Some notes: 
- I wasn't able to replicate the structure on weekday/time availability on Formstack, I left it as an open response question. This may be a problem if you're looking to filter by date. 
- I marked all questions as required (excluding questions triggered by logic), be sure to double-check this 
- I left off the submission instructions on the PDF
- "Internal use only" section was also left out

**Comment by Jo-Dwyer** [comment]
@gabrielaperezdelaosa and @InaraFernandez has Amy looked at this one?

**Comment by gabrielaperezdelaosa** [comment]
Yep, this is good to go: https://alpha.austin.gov/en/preview/form/UGFnZVJldmlzaW9uTm9kZToxMDgw
