### ISSUE TITLE
Add link to research pipeline from Feedback module

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4636]
Currently we have a link on the "in progress" banner in order to try to capture any residents who want to help us improve the website. Sadly, no one has ever completed this path.

Instead, let's add a link to the end of the feedback module. The hypothesis is that since a resident has already filled out the feedback module, they are predisposed to help. We need to craft copy and style a sentence with a link to the form from the last step of the module.

## Work
- [ ] Ready for review: https://share.goabstract.com/2ae0f4ee-f25b-4e6d-8e67-9510cd3c567f?collectionLayerId=203a06b9-9ffd-4e25-9156-e66f0b0f06f5&mode=design

**Comment by sammodabber** [comment]
@toribr Do you need anything from content on this?

**Comment by toribr** [comment]
@sammodabber Yes. We need microcopy for this:
![Screen Shot 2020-07-20 at 11 54 34 AM](https://user-images.githubusercontent.com/3790067/87964437-d9165c00-ca7f-11ea-8974-ecea3e92b2b9.png)

Something like: Thank your for help. This website is a work in progress. You can further help us by signing up for a [paid user feedback session](https://alpha.austin.gov/en/feedback/).

Content: please run your microcopy by @anukandimalla as well.

**Comment by InaraFernandez** [comment]
@anukandimalla - Found this issue while going through techstack and am not sure if the feedback module still needs copy, here is some just in case: 

Thank you for your feedback!

To further help us make this website better, [sign up for a paid user feedback session with our team](https://alpha.austin.gov/feedback/)!

Spanish: 

¡Gracias por sus comentarios!

Para seguir ayudándonos a mejorar este sitio web, [inscríbase para participar en una sesión pagada de investigación de usuarios](https://alpha.austin.gov/es/feedback/).

**Comment by anukandimalla** [comment]
@InaraFernandez from my understanding @chase-vert is wrapping-up on the design for Feedback Module in this sprint, please correct me if i assumed wrong.

@InaraFernandez Is it possible to message in a different way, When the user clicked on this "sign up for a paid user feedback session with our team!" expected to find the Sign-up form than the information page to sign-up. Is there a way to set the expectations navigating to the research sign-up page?

**Comment by toribr** [comment]
@anukandimalla I think that landing page offers a lot of important information to a curious resident. Are you asking that the language be changed or that the flow be changed?

**Comment by anukandimalla** [comment]
@toribr I agree, the page has more valuable information than directly linking to the sign-up form. "sign up for a paid user feedback session with our team!" --> When a user sees the word "Sign-up", they expected to see the form to sign-up. can we change the microcopy to meet that expectation?

 I am thinking more about Microcopy change than user-flow.

**Comment by chase-vert** [comment]
## Draft for review 
This just places the sentence at the end of the feedback flow. Any and all feedback welcome:
https://share.goabstract.com/2ae0f4ee-f25b-4e6d-8e67-9510cd3c567f?collectionLayerId=203a06b9-9ffd-4e25-9156-e66f0b0f06f5&mode=design

**Comment by toribr** [comment]
@anukandimalla If you want this language changed, get on content to give us a new version!

**Comment by chiaberry** [comment]
https://github.com/cityofaustin/janis/pull/900

deployed: https://janis-v3-4636-feedback-link.netlify.app/
I set it so the feedback module always shows the success message for purposes of testing. Let me know if you want me to take it off.

**Comment by chiaberry** [comment]
@jairPineros & @toribr let me know when this is good to go

**Comment by toribr** [comment]
@chiaberry looks good to me.

**Comment by jairPineros** [comment]
QApassed
