### ISSUE TITLE
Add body text field to official document template

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4641]
As a resident, I want to be able to search the content of formal complaints and other official documents. To do so, the text of the pdf must be in a text format on the page.

Acceptance critieria:
- [ ] New field set: body text on official document page
Rich text tools tbd

**Comment by Niicck** [comment]
# QA

https://joplin-pr-4641-body.herokuapp.com/admin/pages/31/edit/?next=/admin/pages/31/edit/#tab-content
Go here. See if you can add body text to the document. Nothing will show up on Janis yet, this is just the backend part.
