### ISSUE TITLE
Joplin Preview | Mobile preview on Joplin is not fully translated in spanish

### ISSUE THREAD

**Issue by jairPineros** [cityofaustin/techstack#4643]
## Describe the bug
The title for the "Official complaint and discipline documents" doesn't translate to Spanish when I select the mobile preview on Joplin and select Spanish.
*Issue also present on "Police oversight reports and recommendations"
## URL
https://joplin-pr-4621-preview.herokuapp.com/admin/pages/319/edit/#tab-content
## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to to joplin select official document collection
2. Click on mobile preview 
3. Click on Spanish to translate the page 
4. Everything is translated but the titles remain in English

## Current behavior
A clear and concise description of what happened

## Expected behavior
Everything in the page should be translated in S![Screen Shot 2020-07-16 at 10.47.46 AM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/20d0877b-d95a-4ab8-af1e-6397094d3195)panish 
## Device and browser

Tested on Chrome

**Comment by Niicck** [comment]
The title isn’t translated because there isn’t a Spanish title entered. Joplin/Janis falls back to the English value for a field if there isn’t a Spanish value available.

**Comment by gabrielaperezdelaosa** [comment]
Fixed this, closing.
