### ISSUE TITLE
Nav2 Dropdown

### ISSUE THREAD

**Issue by robbobfrh84** [cityofaustin/techstack#4648]
### Nav2 Dropdown
- Themes have separate views now, and the desktop and tablet versions will display an image
- Design fits a max of 12 links, but this can easily expand if we should _need_ to grow it
- "About alpha..." messaging is moved from its footer position, to above the theme container
- Retain the same rounded corners as in the active state, but let's go with this gray: #F3F3F3, or 'gray-4' in the scale.

Theme "tabs"
- [ ] hover: #F3F3F3

### Mobile
- Utilizes the current mobile footer implementation, placing `topics` into accordions
- Features the "About alpha..." messaging

### Followup Issue(s):
https://app.zenhub.com/workspaces/techstack-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/4766

**Comment by robbobfrh84** [comment]
Comment moved from https://app.zenhub.com/workspaces/techstack-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/4392

@chase-vert  - "@robbobfrh84 oversight on my end! So let's retain the same rounded corners as in the `active` state, but lets go with this gray: `#F3F3F3`, or 'gray-4' in the [scale](https://designsystem.digital.gov/design-tokens/color/system-tokens/#gray)."

<img width="602" alt="Screen Shot 2020-06-03 at 2 10 50 PM" src="https://user-images.githubusercontent.com/7027270/83678880-109a7900-a5a4-11ea-9069-53340fe357b8.png">

**Comment by jairPineros** [comment]
hey @robbobfrh84  where is the Janis instance for this issue?

**Comment by jairPineros** [comment]
never mind I think I found it is it https://janis-v3-mega-nav.netlify.app right?

**Comment by jairPineros** [comment]
@robbobfrh84 The links in the nav and the 311 link overlap when you make the window small or when you are looking at the app in a vertical view in a tablet

Small window in a computer:
![Screen Shot 2020-08-12 at 2.13.53 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/861cee94-86ed-40bb-8906-a2aafa983dfd)

View in an 12.9 inch ipad:
![IMG_0032.jpg](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/79e668af-3f6b-48ec-a779-e4681ffe12e9)

**Comment by jairPineros** [comment]
issue was fix we are ready to deploy
