### ISSUE TITLE
Provide CoA seal at 100%

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4658]
The image we are using for the seal is way bigger than it needs to be. Reduce the image to 100% and notify dev.

https://alpha.austin.gov/static/coa_seal_color.ebf9b04d.png

**Comment by chase-vert** [comment]
I reduced the resolution from 300 PPI to 72 PPI, which takes the filesize down from 2.86mb to 51kb.
![city-of-Austin-seal_240x240px](https://user-images.githubusercontent.com/7027270/88069247-d6c30900-cb36-11ea-8fd3-8666fe5a8c87.png)
