### ISSUE TITLE
3-1-1 inventory assessment

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4661]
This issue is taken on by the transition owner @gabrielaperezdelaosa 

- [x] assess the current content inventory
    - [ ] has CPIO assessed the department's content for archiving? Note this in the inventory.
- [x] which pages are moving forward to Joplin?
- [x] what kind of pages will be made to account for all content that's moving over?
Close this issue when 
- [x] all content is accounted for w/ archive or page/snippet type

**Comment by gabrielaperezdelaosa** [comment]
proposed steps 
- [ ] update the audit as necessary
- [ ] identify who the WebSPOC is
