### ISSUE TITLE
3-1-1 DNS forwarding

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4665]
Identify pages that should redirect from current Drupal 8 to Joplin.
- [x] identify pages to address from Drupal 8 to Joplin (CPIO could be part of this conversation about what current D8 pages go to newly created pages on Joplin)
- [x] document addressing on spreadsheet
- [ ] set up forwarding through DNS
- [ ] close this issue when the dept web spoc is informed with two weeks advance notice (CPIO can support this)

**Comment by gabrielaperezdelaosa** [comment]
I'm going to close this. Once we have a working DNS plan, here is the documentation for what needs to go where: https://docs.google.com/document/d/1UIKbPJ4l3ssuIdWQ08VH82xAviICRrP-GREqjUNYDB0/edit
