### ISSUE TITLE
3-1-1 go live

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4668]
Publish pages once they've been assigned themes and topics.
Close this issue when
- [x] pages are published
- [x] an email is sent to the webspoc including
   - [ ] read receipt
   - [x] locations of content on D8 --> Joplin
   - [ ] two weeks notice of DNS changes
Are any actions needed from the webspoc here?
- [ ] send an email to CPIO to archive content when DNS forwarding occurs

**target date: 8/5**

**Comment by gabrielaperezdelaosa** [comment]
this is starting to overlap with the user transition epic

**Comment by gabrielaperezdelaosa** [comment]
DNS hasn't been set up, but since this overlaps with documentation handoff and I'm going to close it
