### ISSUE TITLE
3-1-1 Content review

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4670]
Before publication, have content reviewed. Include documentation of any small fact check edits that have been implemented so that they might be reviewed.
- [x] proofreading the content
- [ ] if applicable, check implementation of fact checking
- [x] hit publish
- [x] copy URLs into the inventory

**target dates 
received by: 7/30
reviewed by: 8/5**

**Comment by Jo-Dwyer** [comment]
@srigdon can you link the review process doc in this issue?

**Comment by Jo-Dwyer** [comment]
@ablangworthy27 this was what we documented re: reviewing guidelines

**Comment by gabrielaperezdelaosa** [comment]
https://docs.google.com/spreadsheets/d/1-XYSYXQwMEGq7AqaVXINlYBXplhrqemI3rxw46-FKQc/edit#gid=1635575941
