### ISSUE TITLE
Send "Know your rights" videos for transcription 

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#4674]
The English and Spanish videos on the page have already been submitted to ATXN for captioning. The [videos in other languages](https://docs.google.com/document/d/1rUXyfMuyQgXl1Jzlz7wEDUZpceisreozCZEBx3Vh-54/edit) need transcriptions, too. 

Follow the steps in the [how-to doc](https://docs.google.com/document/d/1tPKDcCE7FW0nPZCx_52HgYcDw3xHfUgoxtYE8iPBb4Y/edit#heading=h.2q1ptr6n5g43) under Sending videos out for transcription.

**Comment by InaraFernandez** [comment]
In addition to asking for transcription in other languages (through Amara), I have submitted a request to ATXN to check on the status of the English and Spanish captions because the videos have not been updated.
