### ISSUE TITLE
3-1-1 Funshop 1: writing for residents

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4676]
Active D8 users who will maintain web access on Joplin should attend a funshop in writing for residents
Close this issue when
- [ ] all 3-1-1 users who will have login access on Joplin have attended a funshop

**Comment by sammodabber** [comment]
@Jo-Dwyer Add this to an epic

**Comment by sammodabber** [comment]
This will be included in the meeting for department-based walkthrough of Joplin (#4713)
