### ISSUE TITLE
3-1-1 identify users

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4677]
Who are the people who will use Joplin?
- [x] get the names/contact info for current users on the list from D8
- [x] we will onboard the users who have published in Drupal in the past year; other user IDs will be 'archived' (not migrated to Joplin)
    - [ ] if available, confirm with CPIO

**Comment by gabrielaperezdelaosa** [comment]
Matilda, Marissa and Shawna
