### ISSUE TITLE
Draft 3 pages related to "About the 3-1-1 app" 

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4681]
This page will combine an existing webpage and 2 PDFs. 
http://www.austintexas.gov/department/311/smart-phone-app
http://www.austintexas.gov/sites/default/files/files/311/19-1_Austin_311_Mobile_App_Fact_Sheet.pdf
http://www.austintexas.gov/page/austin-3-1-1-smart-phone-app-faq
embedded video: https://www.youtube.com/watch?reload=9&v=gwG8CyYV-OM

- [x] Step 1: Copy and paste "[Terms of Service](http://www.austintexas.gov/page/terms-service-austin-3-1-1-smartphone-application)" over into its own info page
  - [ ] publish that so you can link to it
- [x] Step 2: create a monstrous long ugly info page that has the overview, followed by the fact sheet (copy and paste out of the PDF), followed by the FAQ
  - [x] link to the terms of service 
  - [x] link to alpha's version of the privacy policy (it's the same) 
- [x] Step 3: take 30 minutes to create a better version, just working with the information you have in there
- [x] log content debt  
  - [x] note common term usage in the word bank 'Monstro'
  - [x] create user research debt/service design debt
  - [x] create policy debt
  - [x] flag future feature development (specify functionality, not just feature)
- [x] move over to review, tag Amanda 
**target date: Thursday 7/30**

  - [x] Amanda proofreads
  - [ ] Amanda hits publish
  - [ ] Amanda copies the URL into the [inventory ](https://docs.google.com/spreadsheets/d/1-XYSYXQwMEGq7AqaVXINlYBXplhrqemI3rxw46-FKQc/edit#gid=0) column E
**target date: Tuesday 8/4**

**Comment by gabrielaperezdelaosa** [comment]
These 3 pages are what emerged from this. @ablangworthy27, please review.

[Troubleshoot problems with the 3-1-1 app](https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxMjIy)

[About the 3-1-1 mobile app](https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxMjIz)

[3-1-1 Mobile App Terms of Service](https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxMjE1)

**Comment by ablangworthy27** [comment]
These are reviewed! I can't publish yet because we need to determine some IA stuff.

**Comment by gabrielaperezdelaosa** [comment]
Thanks Amanda! closing this since publishing and URL recording is also covered under #4670
