### ISSUE TITLE
Draft 2 "3-1-1 Public Records" pages

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4682]
This page will combine http://www.austintexas.gov/department/311/socrata and http://www.austintexas.gov/sites/default/files/images/Communications/Web_Content/Austin_311_Socrata_Fact_Sheet.pdf (copy and paste out of the PDF). Make sure you get the FAQ's in the drop-down. 

- [x] Step 1: make a long info page just copying and pasting all the content into 1 place
- [ ] Step 2: take 30 minutes to create a better version only with the information you have
- [x] log content debt  
  - [ ] note common term usage in the word bank 'Monstro'
  - [ ] create user research debt/service design debt
  - [ ] create policy debt
  - [ ] flag future feature development (specify functionality, not just feature)
**target date: Thursday 7/30**

- [x] move over to review, tag Amanda 
  - [x] Amanda proofreads
  - [x] Amanda hits publish
  - [x] Amanda copies the URL into the [inventory ](https://docs.google.com/spreadsheets/d/1-XYSYXQwMEGq7AqaVXINlYBXplhrqemI3rxw46-FKQc/edit#gid=0) column E
**target date: Tuesday 8/4**

**Comment by gabrielaperezdelaosa** [comment]
target date: Thursday 7/30

**Comment by gabrielaperezdelaosa** [comment]
https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxMTQ1

tagging @ablangworthy27 for review

**Comment by gabrielaperezdelaosa** [comment]
here's the 2.0 version which I'll present to them: https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxMTQ3

Don't proof this one until/unless they agree to use it.

**Comment by ablangworthy27** [comment]
I updated capitalization and lists based on our style guide. I assigned public records as the topic, and published.
