### ISSUE TITLE
Draft info page: "Check the status of a 3-1-1 service request"

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4683]
There are 2 ways to do this depending on how you submitted the request. 

Requests submitted via the app (either on the app or on 311.austintexas.gov) can be found here: http://311.austintexas.gov/

If you have a service number and an associated e-mail address you can check the status of your request here: https://austin-csrprodcwi.motorolasolutions.com/ServiceRequest.mvc/SRIntake

- [x] create page using current content types, make no additions to the text
- [x] log content debt  
  - [x] note common term usage in the word bank 'Monstro'
  - [x] create user research debt/service design debt
  - [x] create policy debt
  - [x] flag future feature development (specify functionality, not just feature)
- [x] move over to review, tag Amanda 
**target date: Thursday 7/30**

  - [x] Amanda proofreads
  - [x] Amanda hits publish
  - [x] Amanda copies the URL into the [inventory ](https://docs.google.com/spreadsheets/d/1-XYSYXQwMEGq7AqaVXINlYBXplhrqemI3rxw46-FKQc/edit#gid=0) column E
**target date: Tuesday 8/4**

**Comment by Jo-Dwyer** [comment]
@ablangworthy27 donezo.

**Comment by ablangworthy27** [comment]
-We need to add the link to the app when possible. 

-Reviewed but not published (no topic)

**Comment by ablangworthy27** [comment]
This still needs the link to the app @Jo-Dwyer @gabrielaperezdelaosa
