### ISSUE TITLE
Automate Translation Report Email

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#4695]
- [ ] Make sure links and html formatting look right.
- [ ] Send it to Gaby, Inara, Jair.
- [ ] Use heroku scheduler to send it every Monday and Wednesday

**Comment by Niicck** [comment]
# QA 
Alright, this will be a fun one to QA.
![Screen Shot 2020-08-13 at 6 35 15 PM](https://user-images.githubusercontent.com/14187277/90197253-c3046e80-dd93-11ea-9288-66e33f782865.png)

Any user who has "Translations" enabled should receive the translation report email on Monday at 6AM. This functionality is currently only enabled on this PR app, for pages published on this PR, for users enabled on this PR. But if it works, then we can merge it into production and expect it to work the same.

So to QA that functionality, all you have to do it wait. Maybe publish a couple pages. And if your user is enabled, then you should get an email on Monday.

**Comment by jairPineros** [comment]
ok I'm having some issue login as me in that site...

**Comment by jairPineros** [comment]
ok I updated the kitchen sink page and now we are waiting for the email

**Comment by jairPineros** [comment]
I got the email today Monday 17th at 6:05 am
