### ISSUE TITLE
Search: numbers aren't being interpreted as strings

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4698]
## Describe the bug
When entering a numeral [only] into the text field and submitting, I get this error.

![Screen Shot 2020-07-27 at 2.01.08 PM.png](https://images.zenhubusercontent.com/5b7b6eae2bc79a5e7d4f874c/15d14d50-299b-490e-abf3-0c5b90757ac3)

## URL
https://alpha.austin.gov/en/search/#?=8&page=1

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to apha.austin.gov
2. Input a number, press "enter" on keyboard, or click "Search"
3. See error

## Current behavior
Error screen

## Expected behavior
Search screen with results

**Comment by chiaberry** [comment]
https://janis-v3-4698-search-num.netlify.app/

to test: try to search just a number, like 88 in the search bar. should return no results

compare to its behavior on alpha.

**Comment by jairPineros** [comment]
it is working well now
