### ISSUE TITLE
Header background color update (service, search)

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4703]
Now that the new `global nav` is implemented we should update the header background color on service and search pages to match the contextual navigation background color. Background: USWDS updated their color palettes many months ago, and these are some lingering holdovers that haven't been addressed yet.

- [ ] Update background color from `#f3f7fc ` to `#EDF5FF` or `blue-warm-5v` 
  - [x] Service page header background
  - [x] Search page
  - [x] Event list page
  - [x] Guide section header background color

**Comment by chiaberry** [comment]
https://janis-v3-4703-header-color.netlify.app/en/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup/

compared to:
https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup/

it's a subtle change.
