### ISSUE TITLE
Search bar input doesn't clear after user press the back button in the browser

### ISSUE THREAD

**Issue by jairPineros** [cityofaustin/techstack#4704]
## Describe the bug
After a user executes a search from the home page and presses the back button in the browser there user is taking to the home page with the search input in black font overlay on the blue bar
## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to 'https://alpha.austin.gov/"
2. Type something in the search bar 
3. Press return to execute the search
4. Press the back button in the browser 
5. User is back to the home page with the issue described above (see 3rd screen shot)

## Current behavior
A clear and concise description of what happened

## Expected behavior
A clear and concise description of what you expected to happen
user is returned back to the home page with either the home screen without any search input or the home screen with the search bar open and the input in it 
## Screenshots

**Type search**
![Screen Shot 2020-07-28 at 12.25.21 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/790bfab3-f253-4dc3-a9dd-959060d5f02d)

**search**
![Screen Shot 2020-07-28 at 12.25.32 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/d594817d-9ad7-4268-8b1b-4b2070aa7b95)

**Press the back button** 
![Screen Shot 2020-07-28 at 12.25.45 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/a216015e-5049-43f9-a2e6-e608f1aa9957)

## Device and browser

Macbook pro
Chrome 
## Additional context

This issue seem to be present only on chrome

**Comment by jairPineros** [comment]
@robbobfrh84 I think the issue is that the search bar is closed when you press the back button in Chrome. In Safari when the user presses the back button, the user is taken to the home screen with the search bar open and the previous search input still in it.

**Comment by toribr** [comment]
@chase-vert Define the behavior.

**Comment by robbobfrh84** [comment]
Ready for QA: https://github.com/cityofaustin/janis/pull/846

Deployed: https://janis-v3-clear-search.netlify.com/

**Comment by jairPineros** [comment]
Tested and pass on 08/28
