### ISSUE TITLE
Digitize affidavit for disabled parking violation form

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#4705]
**What is the URL?**
Service page: Prove you weren't responsible for a disabled parking offense 

**Have you documented this via the author notes field in Joplin?**
- [x] Yes!
- [ ] No, but I'll do it now

**Describe the content debt.**
This is currently a PDF form with a few versions floating around the web. It should be a Formstack form. See #4133 for background. 

**What is the long-term, ideal solution for this content debt?**
A digital form with an easy print option. This is so the information is updated in one place, but it can be formatted for printing when residents need that.

**Is this related to a feature request issue? (Add the issue number below and add the issue as a dependency.)**
Nope. 

**What approvals will be needed to publish this content change?**
Municipal Court

**Comment by gabrielaperezdelaosa** [comment]
Unfortunately we can't digitize notarized forms
