### ISSUE TITLE
3-1-1 hand off documentation on content migration

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4712]
Users will need to have a record of what migration means and how we made decisions in their dept's transition.

Close this issue when the web spoc has received:
- [x] an external version of the addressing for Drupal -> Joplin transition accounting for all original links and a summary of choices to split, omit, combine information.
- [x] a list of current Joplin users in their dept and their user role
- [x] a quick start guide (even if it's just how to login and change a password)
- [x] information about how to follow up with ODD for writing labs, advanced funshops, service design support, or guidance with policy issues

**Comment by gabrielaperezdelaosa** [comment]
an invitation to a Joplin onboarding session?
