### ISSUE TITLE
3-1-1 department content-based walkthrough of Joplin

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4713]
New users will need to know:
- [x] where their dept's content is on austin.gov 
- [x] how they can edit and publish content on austin.gov
- [x] how to write for residents/according to the style guide
- [x] where to get more help

Close this issue when
- [x] Joplin training is scheduled
- [x] Joplin training is complete

**Comment by gabrielaperezdelaosa** [comment]
- [ ] set a calendar reminder for follow up?

**Comment by sammodabber** [comment]
Potentially put in Sprint 64

**Comment by gabrielaperezdelaosa** [comment]
done, learned things
