### ISSUE TITLE
Alpha Feedback will stop working on October 1st

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#4717]
Github is getting rid of the API that we're using to automatically create github issues from the feedback form:

>Hi @cityofaustin Admin,
We're contacting you regarding upcoming changes to GitHub Apps owned by your organization:
/- CoA GitHub Issue Creator
We no longer support two events which your GitHub Apps may rely on, "integration_installation" and "integration_installation_repositories".
These events can be replaced with the "installation" and "installation_repositories" events respectively.
The "integration_installation" and "integration_installation_repositories" events will be removed after October 1st, 2020.

**Comment by chiaberry** [comment]
https://github.com/cityofaustin/form-to-github-issue/blob/e13b91e3afdcfecc907c61e71d553f44df14e625/app/controllers/submissions_controller.rb

This is where we are using GithubApps (https://octokit.github.io/octokit.rb/Octokit/Client.html) for alpha feedback. I've searched the repo and opened the files to see if we use "integration_installation" and "integration_installation_repositories" anywhere, and it appears that we do not.
