### ISSUE TITLE
CMS - roles/permissions UI controls - stage 1

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#472]
Figure out how view blocks can be adjusted based on user roles/permissions as defined here:
![CONTENT- map of roles, permissions and status.png](https://images.zenhubusercontent.com/5aac26dd4b5806bc2bcb3106/bba46bc0-a296-43ab-b775-d957213cbe95)

Stage 1 will include:

- [ ] dashboard / all pages view

- [ ] the sidebar

**Comment by easherma** [comment]
The time for this seems pretty nigh, based on chats with content folks. It'l be easier to start answering questions about UI/UX stuff if we can have different levels of permission correspond to more or less access to certain features in joplin.

**Comment by briaguya** [comment]
not sure how up to date that table is, probably worth doing a quick inventory of actions currently available in Joplin.
