### ISSUE TITLE
News page template: copy change

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4720]
Updated copy on Assign Department component (News template)

Acceptance criteria:
- [ ] Assign department description text reads as here: https://share.goabstract.com/2e2b9fad-9275-4649-b413-2196d4e54578?mode=design&sha=f0e5bce3292a64fa8d74ea68619f664d29588a11

**Comment by toribr** [comment]
Updated copy on Assign Department component (News template)

Acceptance criteria:
- [ ] Assign department description text reads as here: https://share.goabstract.com/2e2b9fad-9275-4649-b413-2196d4e54578?mode=design&sha=f0e5bce3292a64fa8d74ea68619f664d29588a11

**Comment by chiaberry** [comment]
Is this the right abstract link @chase-vert @toribr ?

**Comment by toribr** [comment]
Apparently, not. Try this: https://share.goabstract.com/04da24c5-5a3b-411e-a454-d4014dc0f193?mode=design&sha=1eadf1dddb9f8a65df02f6e83218fbc4e2561e42

**Comment by chiaberry** [comment]
https://joplin-pr-4720-news-copy.herokuapp.com/admin/pages/27/edit/#tab-content

**Comment by toribr** [comment]
Looks good to me. Will be glad when we can get the display fixed, though.
