### ISSUE TITLE
Airport and 311 links are gone on the website 

### ISSUE THREAD

**Issue by jairPineros** [cityofaustin/techstack#4737]
## Describe the bug
A clear and concise description of what the bug is
The airport link is gone on the website view but it is still present in the mobile view. The 311 link is gone but I'm not still sure if this should be the case for 311 since there is a department 
## URL
https://alpha.austin.gov/
## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to 'https://alpha.austin.gov/'
2.  Inspect the home page and verify the 311 and airport link are gone

## Current behavior
Links disappeared 
## Expected behavior
A clear and concise description of what you expected to happen
Links for 311 and airport should be present in the home page
## Screenshots

Missing Links
![Screen Shot 2020-08-03 at 1.17.15 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/248d9f05-5469-4a6c-8a62-6a3c7db87657)

Links in mobile view
![Screen Shot 2020-08-03 at 1.18.19 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/7765f0a0-a63c-4c01-85c6-72486110200e)
## Device and browser

Chrome|macbook pro
## Additional context

Can we clarify if the 311 link should be gone now?

**Comment by jairPineros** [comment]
Hey @robbobfrh84 this is the issue we talked about in dev sync

**Comment by robbobfrh84** [comment]
Looks like our  `display: none;` <-> `display:  block;` for mobile are backward. 
- Also, there's a line-hight issue when the <a> tag breaks around mobile view... 

![311 and airport bug.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/ff0eab7f-48f4-4f8e-b4fa-4fcda139d242)

**Comment by jairPineros** [comment]
Tested on https://janis-v3-mega-nav.netlify.app and the bug was resolved! great job @robbobfrh84
