### ISSUE TITLE
Revisit content elements of the new and improved official documents

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#4739]
Topics to workshop, discuss: 
1. Flesh out the IA of "Policing in Austin" - workshop this topic collection page amongst ourselves. 
    - Which topics make sense as a grouping? Topics under this topic collection can grow and change. 
    - What is the label that makes the most sense for this grouping? 
DONE: https://miro.com/app/board/o9J_knpAAP4=/

2. We need to contextualize what a document collection means. We could do this a couple of ways: 
- Description field might need the ability to create a link
- Have a "related page" or "part of" way to surface the complaint process page(s)
**Suggested Solution**: - Description field might need the ability to create a link

3. A document is authored by APD but the page or service is offered by OPO. This is probably confusing. We could:
- Remove author from the document entry display
- In contextual nav, we have a middle space that's "related to" - we already have this functionality
**Suggested solution:** - Let's clarify who the authoring office is in the doc collection description

cc: @toribr

**Comment by InaraFernandez** [comment]
@srigdon- this is my stab at #1: https://miro.com/app/board/o9J_knpAAP4=/

**Comment by InaraFernandez** [comment]
@srigdon not sure what the next steps/exit criteria is for closing this issue but I think we've thought through each point.

**Comment by toribr** [comment]
@srigdon So we already implemented the ability to have a link in the description. Is there any other functionality from this issue that needs to be planned for? If not, then please close this issue, thanks!
