### ISSUE TITLE
DCC Department Page

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4741]
- [x] download and upload locally these two PDFs
  - [ ] https://www.austintexas.gov/sites/default/files/files/Community_Court/downtown-austin-community-court-3-1-11.pdf
  - [ ] https://www.austintexas.gov/sites/default/files/files/Community_Court/DACC_Organizational_Chart_8_12_19.pdf
- [x] combine these pages into a department page
  - [ ]  https://www.austintexas.gov/department/community-court
  - [ ] https://www.austintexas.gov/department/community-court/about
  - [ ] https://www.austintexas.gov/department/community-court/biographies
     and all subsequent bios, provide e-mails instead of reproducing webform
  - [x] incorporate this link: https://www.austintexas.gov/gis/JurisdictionsWebMap/
  - [ ] link to austintexas.gov for the board stuff for now

> - [x] create a page that migrates [URL(s)] using current content types
> - [x] make no additions to the text, you may delete redundant text
> - [ ] log content debt
>    - [x] note common term usage in the word bank 'Monstro'
>    - [ ] create Github issues (tag as content debt)
>    - [ ] also record content debt in Joplin notes
> content debt includes: fact checking, reading level, length, accessibility, questions about the user or the necessity of this page, user research debt, service design debt, policy lab work, and new features to dev.
**target date: 8/13**
> - [x] move to review and tag [reviewer]
>    - [ ] Reviewer proofreads the content
>    - [ ] If applicable, check implementation of fact checking
>    - [ ] Hit publish and copy URLs into the inventory
If you can’t publish yet because you are waiting on the IA, you can still close the issue after the review is complete.
**target date: 8/18**

**Comment by gabrielaperezdelaosa** [comment]
https://alpha.austin.gov/en/preview/department/UGFnZVJldmlzaW9uTm9kZToxNTcz

**Comment by srigdon** [comment]
Reviewed, got it down to Grade 12. If I have time to rework the bios I can get it lower, but for the sake of approvals this might be a good place to stop for now: https://alpha.austin.gov/en/preview/department/UGFnZVJldmlzaW9uTm9kZToxNzM3

**Comment by gabrielaperezdelaosa** [comment]
not doing the bios is smart - I think someone from DACC is reworking all of those anyway. I'm meeting with her Tuesday.
