### ISSUE TITLE
Create an info page about DCC intensive case management

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4744]
> - [x] create a page that migrates https://www.austintexas.gov/department/intensive-case-management using current content types
> - [x] make no additions to the text, you may delete redundant text
> - [x] log content debt
>    - [x] note common term usage in the word bank 'Monstro'
>    - [x] create Github issues (tag as content debt)
>    - [x] also record content debt in Joplin notes
> content debt includes: fact checking, reading level, length, accessibility, questions about the user or the necessity of this page, user research debt, service design debt, policy lab work, and new features to dev.
**target date: 8/13**
> - [x] move to review and tag [reviewer]
>    - [ ] Reviewer proofreads the content
>    - [ ] If applicable, check implementation of fact checking
>    - [ ] Hit publish and copy URLs into the inventory
> If you can’t publish yet because you are waiting on the IA, you can still close the issue after the review is complete. 
**target date: 8/18**

**Comment by InaraFernandez** [comment]
@gabrielaperezdelaosa ready for review, see my notes on Joplin.

**Comment by gabrielaperezdelaosa** [comment]
done, changed some capitalization
