### ISSUE TITLE
Create a service page for DCC virtual services

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4745]
> - [x] create a page that migrates https://www.austintexas.gov/article/dacc-virtual-court-services-guidelines using current content types
> - [x] make no additions to the text, you may delete redundant text
> - [ ] log content debt
>    - [ ] note common term usage in the word bank 'Monstro'
>    - [ ] create Github issues (tag as content debt)
>    - [x] also record content debt in Joplin notes
> content debt includes: fact checking, reading level, length, accessibility, questions about the user or the necessity of this page, user research debt, service design debt, policy lab work, and new features to dev.
**target date: 8/13**
> - [x] move to review and tag [reviewer]
>    - [x] Reviewer proofreads the content
>    - [ ] If applicable, check implementation of fact checking
>    - [ ] Hit publish and copy URLs into the inventory
> If you can’t publish yet because you are waiting on the IA, you can still close the issue after the review is complete. 
**target date: 8/18**

**Comment by gabrielaperezdelaosa** [comment]
https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxNzA3

**Comment by ablangworthy27** [comment]
I reviewed and made some basic structural and punctuation changes, but could not publish.
