### ISSUE TITLE
Process Page Content

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#475]
Finalize Process Page Content that I believe is close to done so it can be added to the Alpha site. (still being added via yaml files). Let me know if you need the structure of the Process data model to do this.
- [ ] Foster Content
- [ ] EMS Content

**Comment by amenity** [comment]
FWIW, we can't put up the Foster page until we have a form.

**Comment by ashleecoa** [comment]
I recommend content around Food Manager
http://austintexas.gov/department/food-personnel-requirements
http://austintexas.gov/online-form/food-manager-certificates

**Comment by amenity** [comment]
Duplicate of #773
