### ISSUE TITLE
Redacted content notification

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4751]
As a resident, i might be confused by the formatting of redacted content. A message that indicates redacted content may be helpful.

For instance some sort of notification on Janis that says “This is copy from a redacted document. To see it in it’s original redacted state, please view the attached pdf.”

On the Joplin side, a checkbox: This document has been redacted.

Janis mock: #4787

**Comment by toribr** [comment]
Language on this need content review

**Comment by toribr** [comment]
@chase-vert Let's review this with content at next pin-up, so we can assign to dev.

**Comment by InaraFernandez** [comment]
@toribr This is the copy for the text, has been reviewed by Sarah as well: 

The following text was extracted from the PDF file to make this document more accessible. This machine-generated content may contain styling errors due to redactions. In some instances, text may not load if the original file is a scanned image or has not been made searchable. For the full version of the document, please view the PDF.

**Comment by toribr** [comment]
@chase-vert Can you update your abstract mock and then re-assign to dev?

**Comment by chase-vert** [comment]
@toribr done! 

Here's the collection for dev criteria: https://share.goabstract.com/d753d0f0-61c1-435f-ad45-33e58f7d8400

**Comment by toribr** [comment]
- [ ] We need a ES translation for the above text
– [ ] Should the header "PDF content" also be translated?
https://github.com/cityofaustin/techstack/issues/4751

**Comment by InaraFernandez** [comment]
@toribr Spanish translation: 

El siguiente texto fue extraído de un documento PDF para hacerlo más accesible. Este contenido generado por máquina puede contener errores de formato. El texto se mostrará en el idioma original del documento. En algunos casos, el texto no se cargará si el documento original es una imagen escaneada o si el texto no tiene capacidad de búsqueda. Para mirar la versión completa, favor de ver el documento PDF.

**Comment by chiaberry** [comment]
Joplin checkbox no longer needed, copy pasted onto issue #4787
