### ISSUE TITLE
Change links from React-Router Link to a

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#4755]
From Brian's PR

"If we use react-router-dom links in the way the documentation for react-static and other static site generators recommend (use plain a tags for external links, router <Link> tags for internal links) we get hit with a giant "LOADING" screen by the react suspense component.

I propose we go ahead and just use plain a tags everywhere for now (I know we've gone back and forth on this) and revisit react-router-dom links if we find a way to use them for performance gains in the future."

Opening this Issue to keep track of status of branch

**Comment by chiaberry** [comment]
Ready for QA: 

https://janis-v3-4404-react-router-dom-link-tangent.netlify.app/ 

We should no longer see LOADING in the upper left hand corner of the browser when clicking internal links, such as contextual nav, the privacy policy in the very very bottom of the page. 

I've tested this by going to alpha.austin.gov, clicking the privacy policy and then testing it on the PR branch and seeing there is no "loading"

**Comment by jairPineros** [comment]
QA 
Tested in multiple pages in alpha vs testing environment and where Alpha had a loading screen the testing environment didn't have one.
