### ISSUE TITLE
Being able to hyperlink in location pages

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4758]
As a resident, I should be able to easily find out what city holidays are, when they are referred to on a page.

We need to add the ability to add a link to the "Hours exceptions" component, on the location template.

@toribr 

Acceptance criteria
- [ ] Author has the ability to create a link within the Hours exception text box
- [ ] Link renders correctly on Janis

**Comment by toribr** [comment]
Long term, I'm going to add that I think there might have been a more robust "hours" design that addressed this. However, this short term fix might be good to get into place, considering.

**Comment by toribr** [comment]
Dev, since this is just the addition of rich text to this field with only linking capability, I'm going to assume no design is needed.

**Comment by Niicck** [comment]
# QA

We had to turn a couple of fields into RichTextFields to allow content to post links.
- [ ] OfficialDocumentCollections now can post links in the description
- [ ] Location "hours exceptions" can now include links

Janis:
- [ ] Location Page: https://janis-v3-4758-hyperlink.netlify.app/en/location/city-hall/
- [ ] Official Document Collection: https://janis-v3-4758-hyperlink.netlify.app/en/pets/kitchen-sink-topic-collection-page/kitchen-sink-topic-page/link-in-the-desciption#page=1

Joplin:
- [ ] Location: https://joplin-pr-4758-hyperlink.herokuapp.com/admin/pages/17/edit/#tab-content
- [ ] OfficialDocumentCollection: https://joplin-pr-4758-hyperlink.herokuapp.com/admin/pages/31/edit/#tab-content
