### ISSUE TITLE
Wagtail Translations - Streamfields

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#476]
Currently we're using django_modeltranslations which doesn't support Wagtail StreamField translations. This is forcing us to use rich text fields, where we could create a better experience by using StreamFields (For example, on a ServicePage Steps field).

Wagtail_modeltranslations v0.9 would facilitate translations on Wagtail StreamFields, but it is not yet compatible with Wagtail > v2.0.

When this PR is merged https://github.com/infoportugal/wagtail-modeltranslation/issues/191, we'll be able to use Wagtail_modeltranslations for StreamFields.

To prevent a nightmare:
Please do not try to use an older version of Wagtail_modeltranslations (v0.8) or do any kind of tomfoolery by using an older version of django_modeltranslations, that is the dependency of Wagtail_modeltranslations that is throwing the current the url_resolver error. None of these are compatible with Wagtail 2.0 or greater.  Just be patient and wait for the above PR to be merged.

**Comment by amenity** [comment]
🚫 Tomfoolery!

**Comment by amenity** [comment]
Cleaning out ancient, probably-no-longer-applicable, issues.

**Comment by easherma** [comment]
This looks very close to done/done already: 
https://github.com/infoportugal/wagtail-modeltranslation/issues/191

**Comment by easherma** [comment]
fyi @briaguya  since you've been doing a bunch of translations stuff lately

**Comment by easherma** [comment]
https://github.com/infoportugal/wagtail-modeltranslation/issues/191#event-2197910913

**Comment by briaguya** [comment]
seems to be working now with steps
