### ISSUE TITLE
Create descriptions for OPO document types

### ISSUE THREAD

**Issue by InaraFernandez** [cityofaustin/techstack#4761]
Draft copy for each document type: 
- [x] Formal complaints filed
- [x] Written reprimands
- [x] OPO reports and recommendations
- [x] Disciplinary memos 
~- [ ] Chief of Police Response~ (let's hold off on this until we have them to publish)
~- [ ] CPRC recommendations~ (let's hold off on this until we have them to publish)
- [x] Fact check and revision with OPO
- [x] Send to Tori/staging for implementation

**Comment by InaraFernandez** [comment]
@srigdon-[ Can you please fact check this](https://docs.google.com/document/d/1IlWHV8GDlHFRKE91TcoE62o0CCe8NFC4rpZ7riBS1vc/edit?usp=sharing)?

**Comment by srigdon** [comment]
@InaraFernandez I did a pass through the text. Looks good to share with OPO for fact checking.

**Comment by InaraFernandez** [comment]
This was assigned to OPO via teams group on 8/26
