### ISSUE TITLE
Work session no. 2: fact check the community garden permit guide

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#4764]
- [x] Do work session 2
- [x] Clean up notes and incorporate info in the draft. 
- [x] Create resulting issues. Make an issue for each page. Each page issue should include these steps:

> 1. Rewrite the page, save draft in Joplin. Ask Jennifer any questions in Teams as they come up. 
> 2. Once all pages are drafted, send to Jennifer for a quick review to make sure we didn't change the meaning of anything. 
> 3. Content team does 2 rounds of edits
> 4. Send the whole guide to Jennifer and Cindy for approval
> 5. Publish
> 6. Translate into Spanish and Burmese (Reach out to [Burmese translators](https://library.austintexas.libguides.com/ld.php?content_id=51824861)). What other languages?

**Comment by gabrielaperezdelaosa** [comment]
This is done, a mockup was created, it is with Jennifer and Cindy for fact-checking. When it comes back we will proceed to incorporate edits and set up for content review.
