### ISSUE TITLE
Part of "Obtenga un asiento de seguridad para niños gratis" page is not translated 

### ISSUE THREAD

**Issue by jairPineros** [cityofaustin/techstack#4765]
## Describe the bug
part of the page is not translated 
## URL
https://alpha.austin.gov/es/health-safety/health-prevention/kids-and-family-resources/free-car-seat
## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to '.https://alpha.austin.gov/es/health-safety/health-prevention/kids-and-family-resources/free-car-seat.'
2. Scroll down to the bottom half of the page.
3. See error

## Current behavior
A clear and concise description of what happened

## Expected behavior
A clear and concise description of what you expected to happen

## Screenshots

![Screen Shot 2020-08-06 at 2.26.05 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/0d0338b6-92d3-4476-ae3d-3360daa4fbc6)
## Device and browser

Macbook pro | Chrome

**Comment by gabrielaperezdelaosa** [comment]
![image.png](https://images.zenhubusercontent.com/5ecd5c4a1cb98b2a16b27154/604bd7f5-67e9-45a7-94d9-efebae9668e1)
