### ISSUE TITLE
The majority of the 311 page is not translated when the user choses Spanish (only one title is translated)

### ISSUE THREAD

**Issue by jairPineros** [cityofaustin/techstack#4768]
## Describe the bug
The majority of the 311 page is not translated when the user choses Spanish (only one title is translated)
## URL
https://alpha.austin.gov/es/3-1-1/
## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to https://alpha.austin.gov/es/3-1-1/
2. Click on Spanish 
3. Inspect the page
4. See error.

## Current behavior
page is not fully translated 
## Expected behavior
page should be fully in Spanish and not partially in spanish
## Screenshots

![Screen Shot 2020-08-06 at 2.52.44 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/387f440f-6bc8-46a6-9dc0-8a944e7a44fe)
## Device and browser

Macbook pro | Chrome

**Comment by jairPineros** [comment]
This also applies to submit and check on a 3-1-1 service request.

**Comment by gabrielaperezdelaosa** [comment]
chatted with Jair about the fact that in our new transition model we won't be doing human translation for most of the pages we put up, we will instead be working on getting the Google API in place and a workflow around that
