### ISSUE TITLE
Implement a new search Service

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#4776]
Choose between 
- [ ] Google Search API
- [ ] Algolia
- [ ] Solr

Notes here:
https://github.com/cityofaustin/techstack/issues/4762

**Update 9/9/2020**: I chose Elasticsearch. This issue will create a searchIndex that is compatible with Elasticsearch. Automating the creation of elasticsearch services and querying from elasticsearch will be future issues.

**Comment by Niicck** [comment]
## QA

https://janis-v3-4776-elastic.netlify.app/en/search/#page=1
This search should work the same as it did before. 
- [ ] Make sure all the page results we'd expect to see show up.
- [ ] And that those links work.
- [ ] And that the right summary/data below the link shows up for correctly for each content_type.

**Comment by jairPineros** [comment]
@Niicck 
There is a discrepancy in the number of results for the search term Policía between the PR and Alpha (police in spanish)
![Screen Shot 2020-09-10 at 4.09.41 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/a4064a13-5c8e-44fb-9ce7-eeb41b524d9b)![Screen Shot 2020-09-10 at 4.11.00 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/8f7e4823-9780-40bf-9c50-5951d199c43a)

Also there is a discrepancy of the number of results for the term police between the PR and Alpha 
![Screen Shot 2020-09-10 at 3.59.04 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/9ae32d8f-83fb-4bf5-a65d-2dc924f10a5f) ![Screen Shot 2020-09-10 at 3.58.39 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/c7df9ba2-68cd-4390-a3b1-c5fc7e472c98)

**Comment by Niicck** [comment]
@jairPineros The PR pages aren't 100% synced up with production. If new pages were published on production recently, then they wouldn't show up in the PR. This isn't a problem unless the PR's search isn't displaying results that actually do live on the PR site.

**Comment by jairPineros** [comment]
@Niicck , so I check the pages that appeared in alpha that did not appeared in the PR search results and I found that:

"Solicite para servir en la Comisión Comunitaria de Evaluación de la Policía" is not part of the search results of the PR, but the page is available in the PR

Page in the PR:
![Screen Shot 2020-09-11 at 2.56.48 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/623c8ebd-8435-4c51-8478-0a98f17cc54d)

Page in Alpha:
![Screen Shot 2020-09-11 at 2.58.10 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/2a505364-5c64-4e4a-906f-47366533f268)

Search results in PR:
![Screen Shot 2020-09-11 at 2.59.24 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/72e7dac3-49d6-4cfa-8222-8a7c5e11b170)
![Screen Shot 2020-09-11 at 2.59.41 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/0d701897-a214-4ad5-b68f-a243fb86d040)

Search results in Alpha:
![Screen Shot 2020-09-11 at 3.01.20 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/c98fad3f-6be8-45aa-8943-a4f15dc0a1ff)

**Comment by Niicck** [comment]
Yep, that's a real bug. I'm looking into it.

**Comment by Niicck** [comment]
Fixed. "Form Containers" were not being added to the searchIndex. https://janis-v3-4776-elastic.netlify.app/es/search/#?=servir&page=1

**Comment by jairPineros** [comment]
Tested and passed on 09/14
