### ISSUE TITLE
3-1-1 admin onboarding

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4781]
As a dept admin on Joplin, I want to understand what I am able to govern for my dept vs other roles.
- [x] create a reference guide for what an admin for a dept is uniquely responsible for
- [x] include a contact info if I ave questions or want further training
- [ ] send it to the admin for 3-1-1

**Comment by gabrielaperezdelaosa** [comment]
language drafted:


Hello [USER],
Welcome to the content management system for alpha.austin.gov (called Joplin). You can access it here: https://joplin.herokuapp.com/
Log-in: 
Password: 
When you log in for the first time, at the top right hand corner, under “Account Settings” you will be able to change your password. 
As an admin for your department, you have the ability to manage how your department’s web content interacts with other departments’ web content. You can select contacts, images, and documents from other departments when building web pages, where your department’s publishers can only select from department content. Furthermore, you can create and organize information architecture across departments where, again, department publishers can only handle the content for their department. Lastly, you can update the contact information for your department when needed. If you have any questions or would like training on using Joplin, please reach out to us. 
We’re excited to work together,

**Comment by gabrielaperezdelaosa** [comment]
things learned from drafting that e-mail...we probably won't onboard department admins unless someone has a specific interest in having an admin account. Closing this since that has not happened for 311, but I incorporated the language into the migraiton epic google doc. @Jo-Dwyer
