### ISSUE TITLE
Alternative sanctions offered by DACC page improvement

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#4786]
*Make sure to add the label "Content debt." If available, add the appropriate "Content type" or "Feature" label.*

**What is the URL?**
TBD, not published yet but preview is [here](https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxNjk2) and can be found in Joplin as "Alternative sanctions offered by Downtown Austin Community Court"

**Have you documented this via the author notes field in Joplin?**
- [x ] Yes!
- [ ] No, but I'll do it now

**Describe the content debt.**

- Revisit the language. Is it set in stone for legal reasons or can it be made more accessible?

- Consider making this actionable and turning into a service page. How does someone see out an alternative sanction?  Another option would be shortening this content and adding it to another service page. 

**What is the long-term, ideal solution for this content debt?**

- It needs to be actionable. Not sure many people are going to find this page useful.

**Is this related to a feature request issue? (Add the issue number below and add the issue as a dependency.)**
No

**What approvals will be needed to publish this content change?**
DACC

**Comment by gabrielaperezdelaosa** [comment]
#4827
