### ISSUE TITLE
User is having problems submitting feedback on pr 4375

### ISSUE THREAD

**Issue by jairPineros** [cityofaustin/techstack#4795]
## Describe the bug
A clear and concise description of what the bug is
User is getting an error after submitting the feedback.
## URL
https://janis-v3-4375-dependabot.netlify.app/en/health-safety/health-prevention/disease-prevention/get-immunized/
## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to the bottom of any page to the feedback field
2. Type feedback
3. submit feedback

## Current behavior
A clear and concise description of what happened

## Expected behavior
A clear and concise description of what you expected to happen
User should be able to submit feedbacks
## Screenshots

![Screen Shot 2020-08-13 at 6.05.18 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/65837d3a-af67-4706-8772-7f55c00ff8ef)
## Device and browser

Macbook pro | Chrome

**Comment by chiaberry** [comment]
I dont think any of the netlify.app urls are accepted by the feedback form. if they are whitelisted then i think it should fix it.
