### ISSUE TITLE
User navigating alpha in spanish encounter multiple 404 pages.

### ISSUE THREAD

**Issue by jairPineros** [cityofaustin/techstack#4796]
## Describe the bug
A clear and concise description of what the bug is
When the user is navigating the page in Spanish the pages "Financial help" and "Get help searching for and applying to jobs"  give a 404

I believe this is because the user is being redirected to a the Spanish slug. Once the user is the the 404 page the slug wont change even if the user switches to english or refreshes the page. This is concerning because to an only Spanish-user this pages will look as if they don't exists. 

## URL
https://alpha.austin.gov/es/jobs/job-resources/help-finding-work/obtenga-ayuda-buscando-y-aplicando-trabajos

https://alpha.austin.gov/es/housing-utilities/ayuda-financiera

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to alpha and switch the page to Spanish.
2. From the home page navigate to "Ayuda financiera" see the 404 page
3. Then navigate to recursos laborales 
4. Then click on "vea todos los servicios" under "Ayuda para encontrar empleo"
5. Click on "Obtenga ayuda buscando y aplicando a trabajos" under "todos los servicios "
6. See the 404 page.

## Current behavior
A clear and concise description of what happened
user navigating in Spanish is encountering 404 for pages that are available both in Spanish and English

## Expected behavior
A clear and concise description of what you expected to happen
All services currently offer for users navigating the site in English should be available to user navigating in Spanish specially if translations for this services are available.

## Screenshots

![Screen Shot 2020-08-13 at 9.42.26 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/a02129af-8305-4de3-90d9-158b9ecbe196)

![Screen Shot 2020-08-13 at 10.03.09 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/95a991cd-fbbe-47a5-b902-365d7c27668a)

**Comment by InaraFernandez** [comment]
@jairPineros I think I fixed it, feel free to close the issue after double-checking if it works for you.

**Comment by chiaberry** [comment]
@InaraFernandez , how did you fix it? was it by deleting a spanish slug?

**Comment by InaraFernandez** [comment]
@chiaberry Yes, Spanish slugs have been a constant issue for us

**Comment by chiaberry** [comment]
Frustrating, I worried that the spanish slugs would create 404s. I want to investigate.

**Comment by jairPineros** [comment]
@chiaberry after you are done could you drop this in the QA column and tag Team QA?
