### ISSUE TITLE
Automate Janis rebuilds from Joplin

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#480]
We need to initiate a rebuild of Janis/React-Static upon changes to the Joplin API.

There should be some method hooks upon saving new data where we could trigger this. 

We also need to consider how long this process will take and think about how we message to authors that their site revisions aren't yet live but will be shortly.

**Comment by benweatherman** [comment]
Here's something Heroku suggested for kicking off a build

> If you use the [create build api endpoint](https://devcenter.heroku.com/articles/platform-api-reference#build-create) you can use the GitHub API endpoint to get the source blob. Assuming your GitHub repo is private the URL would be something like:
```
https://api.github.com/repos/<repo-owner-or-org>/<repo>/tarball/<branch>?login=<github-user-name>&access_token=<personal-access-token>
```
> The <github-user-name> would need to be a user with access to the GitHub repo, and they would need to generate a personal access token in GitHub to use for <personal-access-token>.
