### ISSUE TITLE
Convert future official doc PDFs into text 

### ISSUE THREAD

**Issue by InaraFernandez** [cityofaustin/techstack#4801]
Run automation script that will pull text from PDFs and create new pages. 

Exit Criteria: 
- [ ] Create a new page in Joplin that saves as draft 
- [ ] Have a way to flag PDFs that are not searchable and unable to display text 

To do for content: 
- [ ] Disclaimer copy for text unable to be extracted

**Comment by toribr** [comment]
@InaraFernandez We don't have the capability to create new pages, those will have to be done manually. The script can be run only for existing pages. Content will need to continue to create pages, and then notify dev that the script should be run.

In light of that, I'm closing this issue.
