### ISSUE TITLE
Identify Office of Sustainability users

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4806]
Who are the people who will use Joplin?
WebSPOCs http://coaspweb1.coacd.org/sites/CTM/Apps/WebServices/Internet-intranet/Lists/CONTENT%20TEAM/AllItems.aspx?View=%7b7a91470f-c102-4e78-99c2-bffd2546029b%7d&SortField=LinkTitle&SortDir=Asc (you need to be on VPN)
Any users who have published in Drupal in the past year
if available, confirm with CPIO

**Comment by ablangworthy27** [comment]
@gabrielaperezdelaosa, who in CPIO did you confirm with?

**Comment by gabrielaperezdelaosa** [comment]
no one...that part was written by Jo but when I asked Tim he just sent me the webspoc link
