### ISSUE TITLE
Opening official documents and clicking "back" does not return you to where you were.

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4816]
As a resident, I want to be able to navigate to pages and back and land where I clicked from, thus supporting the common mental model of the web.

The behavior of clicking into an official document from the collection page should return you to the page where you were. Currently, it returns you to page 1, even if you clicked from page 20. This means the user has to start over, and is very confusing.

Behavior
- [ ] Navigate to any other page except page 1 in an official document collection. Make note of which page you are on. Click on an official document. Click the back button. Are you on the same page from which you clicked? If yes, then behavior is as expected.

**Comment by robbobfrh84** [comment]
NOTE: This may be solved by @Niicck incoming additions to pagination / official docs / search stuff. I'll check back in and double check if the changes have been applied.
