### ISSUE TITLE
Phase 2 for community gardens

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4821]
Bonus: Come up with a good name for phase 2
[Letters of support for a community garden](https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxNzUw) --> Changed to [Get a nonprofit sponsor and support for a community garden](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyNzQ2)
[Draft documentation for a community garden](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxNzYw) --> Changed to [Start documents for a community garden](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyNzU2)
[Phase 2 check-in page](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxOTk1) -- See notes in Joplin. About the on-site meeting, where will they meet? During the pandemic, will they be meeting remotely? Let's update it with that info.

**Comment by gabrielaperezdelaosa** [comment]
@srigdon reviewing :)

**Comment by srigdon** [comment]
Reviewed! See notes in the first comment above. 

Options for phase names: 

1. Start the permit application process
2. Gather the paperwork
3. Get ready to build 

/
1. Permit application kickoff
2. Paperwork mountain
3. Home stretch

/
1. Get this garden started
2. Organize for community support
3. Build it and they will come
