### ISSUE TITLE
Downtown Austin Community Court Department page glitching

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4829]
## Describe the bug
The department page is 404ing and when you click "view live" from Joplin it doesn't work, just opens a new Joplin search window. 

## URL
https://alpha.austin.gov/en/downtown-austin-community-court-department/

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to Joplin and search downtown austin community court
2. click view live (on the dept page, not location)

**Comment by Niicck** [comment]
@chiaberry fixed this. The Department Page did not have a Department Group assigned. Made a new issue here: https://github.com/cityofaustin/techstack/issues/4836
