### ISSUE TITLE
Global nav: remaining styling

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4830]
## Overview
Now that we have Q/A, I think I might've missed the opportunity to do a visual pass over the implementation and that's my bad. There are just a few small lingering issues that I'll outline here. 

## Summary
- [x] Screen under mega nav in the open state
- [x] Nav item hover color
- [x] WIP banner visibility on department pages

### Screen under mega nav in the open state
For `desktop` and `tablet`, when the mega-nav is open, we want visually separate the background from the foreground with a div layer over the page body (from the `contextual nav` down), but beneath the mega nav. Some issues crop up when opening the mega nav on pages that have white backgrounds, where the separation between the page body and the mega nav container get lost. 

- Referenced mock: https://share.goabstract.com/d47259b9-2bb4-4c90-b8a9-71f9cc3b08d5?collectionLayerId=0adf8183-1450-4fe1-a100-ff4ba6b6b158&mode=design

**Criteria**
- [x] Fill color: `#1b1b1b`
- [ ] Transparency: 25%
- [x] `WIP banner` should sit at the same level with the mega nav drawer/container so that it's also above/over the div background
- [x] Applies to
  - [x] Desktop
  - [x] Tablet

### Nav item hover color
This one is on me! The primary blue here makes the hover effect look as though it's a primary action (i.e. submits something like a button, or takes elsewhere in the site), but the interaction only opens a drawer, so I'd like to knock this back in the hierarchy. 

**Criteria**
- [x] Hover color from: `#0050D8` or USWDS `blue-warm-06v`, to: `#EDF5FF` or USWDS `blue-warm-5v`

### WIP banner on department pages
- [x] Let's raise the WIP banner above the department banner so that it's visible

**Comment by robbobfrh84** [comment]
I'm not sure if this would be automatically included in this issue by happenstance here, but chia noticed that the WIP banner isn't displayed in the department pages. Here are some examples. 
- https://alpha.austin.gov/en/downtown-austin-community-court-department/
- https://alpha.austin.gov/en/3-1-1/

Maybe this is a different issue. But we actually have two cases here, dept. pages with banners & without.

**Comment by chase-vert** [comment]
Ah, yeah we'd include that here. I know it's overkill to have it blasted everywhere, but Tori wants this redundancy as we start to import a lot more content (and potentially traffic). I'll add it above!

**Comment by robbobfrh84** [comment]
Ready for QA & Review. 

github Issue: https://github.com/cityofaustin/janis/pull/852

Deployed: https://janis-v3-nav-cleanup.netlify.com/
Dept page link: https://janis-v3-nav-cleanup.netlify.app/en/austin-public-health/

**Comment by jairPineros** [comment]
### QA
This fix the issues with the WIP message in 311, community court department and Austin public health
