### ISSUE TITLE
Add alt text field for media

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#4833]
### 2. As a screen reader user I need alt text for all media so I know what it is and why it matters to me. 

**Is your feature request related to a problem? Please describe.**
We don't have a place to put alt text for images we upload, and we're starting to onboard new Joplin users who've participated in a funshop. 

Acceptance criteria
- [ ] mock of page with approved microcopy
- [ ] necessary updates to doc model
- [ ] necessary updates to microcopy document
- [ ] Janis label translations (where does this live?)

**Comment by toribr** [comment]
Design will look at this first so dev can do this sprint.

**Comment by gabrielaperezdelaosa** [comment]
@toribr and @chase-vert this may or may not be the right place to say/consider this, but designing a place to give photo credit would also be dope. Just putting it out there.

**Comment by toribr** [comment]
@gabrielaperezdelaosa There's an issue for that, thanks to @srigdon. We're going to do alt text first, though.

**Comment by toribr** [comment]
Additional details here (for design): https://miro.com/app/board/o9J_kmqnYgU=/

**Comment by toribr** [comment]
We're going with Wagtail default implementation, so closing this until we have fresh considerations.
