### ISSUE TITLE
Department Page creation is buggy

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#4836]
- [ ] If a Department Page does not have a Department Group assigned, then the department page will 404 and not be built. However, a link will still be created from the /departments list page, it will just be a broken link.
- [ ] The workflow around Department Groups/Department Pages is not intuitive. Authors frequently forget to connect Groups to Pages. Perhaps there is a way that we can automate the creation and connection of Department Groups and pages.

Acceptance criteria:
- [ ]

**Comment by toribr** [comment]
![newDeptFlow](https://user-images.githubusercontent.com/3790067/92734299-096ece00-f33e-11ea-8791-f82f56ee854f.png)

**Comment by toribr** [comment]
See details here:
https://share.goabstract.com/352b6b34-8526-451e-bfcb-638a53b97d59
