### ISSUE TITLE
Sustainability info page - Climate change

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#4844]
### Page or pages that needs to be migrated:
http://austintexas.gov/climate
http://austintexas.gov/department/climate-change
http://austintexas.gov/page/learn-about-climate-change

- [x]  Create pages using current content types. [Climate change at the local level](https://joplin.herokuapp.com/admin/pages/674/edit/?next=/admin/pages/674/edit/#tab-content) and [how to cut down on your carbon footprint](https://joplin.herokuapp.com/admin/pages/676/edit/?next=/admin/pages/676/edit/#tab-content)
- [x]  Make no additions to the text, you may delete redundant text.
- [x]  Log content debt.
    - [x] Note common term usage in the [word bank 'Monstro'](https://docs.google.com/spreadsheets/d/1gEyX6ayn1TW7CQxngsMT9pej-egMWxCtxAzRWXAeLfM/edit#gid=0).
    - [x] Create Github issues (tag as content debt).
    - [x] Record content debt in Joplin notes content debt includes: fact-checking, reading level, length, accessibility, questions about the user or the necessity of this page, user research debt, service design debt, policy lab work, and new features to dev.
- [x]  Move to review and tag another content strategist for review.
- [ ]  Reviewer uses [checklist] (https://docs.google.com/document/d/1FVP_ZiQyT2P5F6GUNET327L6hyyexrkA-IzKXQjjzXw/edit#heading=h.7aga879dvzu9) for guidance.
- [ ]  Reviewer hits publish.
- [ ]  Reviewer documents new alpha URL in the department's inventory spreadsheet.
- [ ]  Reviewer documents all newly created Contacts, Locations, documents and other snippets, if applicable

**target date: 9/2**

**Comment by sammodabber** [comment]
@Jo-Dwyer Vibe check

**Comment by ablangworthy27** [comment]
@InaraFernandez I originally wanted to see if I could combine [this page](http://www.austintexas.gov/page/climate-projections-austin) with the page on climate resilience, but now I am thinking it could easily be folded into this page?

**Comment by InaraFernandez** [comment]
@ablangworthy27 I think that's a good idea- the first two links in the description are dupes btw. I think having a section on climate change, especially relating to our local community, is a good idea and a great way to cut down on all these pages with similar information.

**Comment by gabrielaperezdelaosa** [comment]
changed the reducing your carbon footprint page into an info page
re: #4883, I think that so long as we are ok archiving the netzero hero content (which is old anyway) then there is nothing left to migrate on http://austintexas.gov/department/climate-change
