### ISSUE TITLE
Sustainability service page - participate in the community climate plan

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#4845]
### Page or pages that needs to be migrated:
http://austintexas.gov/page/austin-community-climate-plan

- [x] [ Create pages using current content types](https://joplin.herokuapp.com/admin/pages/672/edit/#tab-content).
- [x]  Make no additions to the text, you may delete redundant text.
- [x]  Log content debt.
    - [x] Note common term usage in the [word bank 'Monstro'](https://docs.google.com/spreadsheets/d/1gEyX6ayn1TW7CQxngsMT9pej-egMWxCtxAzRWXAeLfM/edit#gid=0).
    - [x] Create Github issues (tag as content debt).
    - [x] Record content debt in Joplin notes content debt includes: fact-checking, reading level, length, accessibility, questions about the user or the necessity of this page, user research debt, service design debt, policy lab work, and new features to dev.
- [x]  Move to review and tag another content strategist for review.
- [ ]  Reviewer uses [checklist] (https://docs.google.com/document/d/1FVP_ZiQyT2P5F6GUNET327L6hyyexrkA-IzKXQjjzXw/edit#heading=h.7aga879dvzu9) for guidance.
- [ ]  Reviewer hits publish.
- [ ]  Reviewer documents new alpha URL in the department's inventory spreadsheet.
- [ ]  Reviewer documents all newly created Contacts, Locations, documents and other snippets, if applicable

**target date: **

**Comment by InaraFernandez** [comment]
This page is a pandora's box of PDF and a link to a google drive, spoke with Jo this morning and will continue the conversation on how to handle some of the content types.

**Comment by gabrielaperezdelaosa** [comment]
https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyMTQ4

**Comment by gabrielaperezdelaosa** [comment]
this now includes the Ambassadors page content. @ablangworthy27 you may want to update that in the inventory?
