### ISSUE TITLE
Sustainability info page - City strategies for resilience and adaptation

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#4846]
### Page or pages that needs to be migrated:
http://www.austintexas.gov/page/climate-projections-austin
http://austintexas.gov/page/climate-change-resilience-and-adaptation
http://austintexas.gov/sites/default/files/files/Sustainability/Climate_Resilience_Action_Plan.compressed.pdf

- [x]  Create pages using current content types.
- [x]  Make no additions to the text, you may delete redundant text.
- [x]  Log content debt.
    - [x] Note common term usage in the [word bank 'Monstro'](https://docs.google.com/spreadsheets/d/1gEyX6ayn1TW7CQxngsMT9pej-egMWxCtxAzRWXAeLfM/edit#gid=0).
    - [x] Create Github issues (tag as content debt).
    - [x] Record content debt in Joplin notes content debt includes: fact-checking, reading level, length, accessibility, questions about the user or the necessity of this page, user research debt, service design debt, policy lab work, and new features to dev.
- [x]  Move to review and tag another content strategist for review.
- [ ]  Reviewer uses [checklist] (https://docs.google.com/document/d/1FVP_ZiQyT2P5F6GUNET327L6hyyexrkA-IzKXQjjzXw/edit#heading=h.7aga879dvzu9) for guidance.
- [ ]  Reviewer hits publish.
- [ ]  Reviewer documents new alpha URL in the department's inventory spreadsheet.
- [ ]  Reviewer documents all newly created Contacts, Locations, documents and other snippets, if applicable

**target date: 9/2**

**Comment by ablangworthy27** [comment]
Drafted and ready: 
https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToyMDE1

This does not include the table from: http://www.austintexas.gov/page/climate-projections-austin 
-I think this may be better suited for the Learn about climate change page, and there is already a link to similar information included in the text.

[Content debt is also logged. ](https://github.com/cityofaustin/techstack/issues/4870)

**Comment by gabrielaperezdelaosa** [comment]
done :)
