### ISSUE TITLE
Official doc collection: display total number of documents

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4847]
## Background
Original design issue: #4803

Tori had a hard time navigating the `Official document collection`, and one of those reasons was because she couldn't see the total number of official documents in the list (which we display for search results).

## Solution
Display the `total number` of results on the first page of the official document collection

## Links
- Abstract collection: [🏗 Doc collection: display total # of docs ∙ Dev criteria](https://share.goabstract.com/809fa3b6-f0d0-4df7-9a78-323462d57613)
 
## Acceptance criteria
- [ ] Implementation matches mocks
- [ ] Display the total number of documents within a document collection just below the header, and above the page body content
  - [ ] Desktop
  - [ ] Tablet 
  - [ ] Mobile
- [ ] Only display this on the first page of results

**Comment by chase-vert** [comment]
@jairPineros tagging you here since this is ready for dev. It's a pretty simple addition, and mirrors an existing pattern we have.

**Comment by jairPineros** [comment]
Thanks Chase!

**Comment by jairPineros** [comment]
@robbobfrh84 where is the PR?

**Comment by jairPineros** [comment]
oh never mind I see it in Slack
