### ISSUE TITLE
Meet with Health Director on Content Transition

### ISSUE THREAD

**Issue by courtneyjacinic** [cityofaustin/techstack#485]
We have inventoried all of Public Health with Linda Cox's go-ahead. We would like Director go-ahead to begin transforming and transitioning all Public Health service pages.

- [ ] @wilhitem and SE set meeting with Director
- [ ] MW receives written permission from Director to begin and forwards to Product Owner @amenity  + Content Team

**Comment by wilhitem** [comment]
I emailed Stephen with a reminder to set up a meeting! Our calendars don't line up for this week, I'm hoping I can meet with her early next week.

**Comment by wilhitem** [comment]
Stephen talked to stephanie before she went on vacation and got a thumbs up to proceed. I have a follow up email drafted to send today as she returned from vacation yesterday to take her our learnings, next steps!
