### ISSUE TITLE
Sustainability service page/form container - Become an Austin green business leader

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#4851]
### Page or pages that needs to be migrated:
http://austintexas.gov/department/austin-green-business-leaders
http://austintexas.gov/page/top-7-reasons-join-austin-green-business-leaders
http://www.austintexas.gov/online-form/become-austin-green-business-leader
http://www.austintexas.gov/sites/default/files/files/Sustainability/AGBL/resource_page_fixed4.pdf

- [x]  Create pages using current content types.
- [x]  Make no additions to the text, you may delete redundant text.
- [ ]  Log content debt.
    - [ ] Note common term usage in the [word bank 'Monstro'](https://docs.google.com/spreadsheets/d/1gEyX6ayn1TW7CQxngsMT9pej-egMWxCtxAzRWXAeLfM/edit#gid=0).
    - [ ] Create Github issues (tag as content debt).
    - [ ] Record content debt in Joplin notes content debt includes: fact-checking, reading level, length, accessibility, questions about the user or the necessity of this page, user research debt, service design debt, policy lab work, and new features to dev.
- [ ]  Move to review and tag another content strategist for review.
- [ ]  Reviewer uses [checklist] (https://docs.google.com/document/d/1FVP_ZiQyT2P5F6GUNET327L6hyyexrkA-IzKXQjjzXw/edit#heading=h.7aga879dvzu9) for guidance.
- [ ]  Reviewer hits publish.
- [ ]  Reviewer documents new alpha URL in the department's inventory spreadsheet.
- [ ]  Reviewer documents all newly created Contacts, Locations, documents and other snippets, if applicable

**target date: 9/2**

**Comment by ablangworthy27** [comment]
Service page is called [Become an Austin green business leader](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyMDc5) and the form is called [Apply for a green business leader scorecard. ](https://alpha.austin.gov/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyMTMz)

**Comment by gabrielaperezdelaosa** [comment]
done, moved some information from the first step to steps 2 and 3. Let's make sure to remember to link the page to the submission message on formstack.
