### ISSUE TITLE
Sustainability service page - donate food

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#4853]
### Page or pages that needs to be migrated:
http://austintexas.gov/page/how-donate-food

- [x]  Create pages using current content types.
- [x]  Make no additions to the text, you may delete redundant text.
- [x]  Log content debt.
    - [x] Note common term usage in the [word bank 'Monstro'](https://docs.google.com/spreadsheets/d/1gEyX6ayn1TW7CQxngsMT9pej-egMWxCtxAzRWXAeLfM/edit#gid=0).
    - [ ] Create Github issues (tag as content debt).
    - [x] Record content debt in Joplin notes content debt includes: fact-checking, reading level, length, accessibility, questions about the user or the necessity of this page, user research debt, service design debt, policy lab work, and new features to dev.
- [x]  Move to review and tag another content strategist for review.
- [ ]  Reviewer uses [checklist] (https://docs.google.com/document/d/1FVP_ZiQyT2P5F6GUNET327L6hyyexrkA-IzKXQjjzXw/edit#heading=h.7aga879dvzu9) for guidance.
- [ ]  Reviewer hits publish.
- [ ]  Reviewer documents new alpha URL in the department's inventory spreadsheet.
- [ ]  Reviewer documents all newly created Contacts, Locations, documents and other snippets, if applicable

**target date: 9/2**

**Comment by InaraFernandez** [comment]
@ablangworthy27 @Jo-Dwyer- Are we also transitioning the [Universal Recycling Ordinate](http://www.austintexas.gov/department/universal-recycling-ordinance-uro) as well each service page for commercial businesses, multi-family properties and food-permitted businesses? 

If so, I can create an issue and work on it. I did not see any of these in the content inventory sheet.

**Comment by ablangworthy27** [comment]
Looks like that is part of ARR

**Comment by InaraFernandez** [comment]
@gabrielaperezdelaosa ready 4 review

**Comment by gabrielaperezdelaosa** [comment]
changed it to a service format, took away question headings: https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyMTY4
