### ISSUE TITLE
Sustainability service page - Get involved with the food policy board

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#4858]
### Page or pages that needs to be migrated:
http://www.austintexas.gov/page/food-policy-board-join-working-group
http://austintexas.gov/page/austin-travis-county-food-policy-board

- [x]  Create pages using current content types.
- [x]  Make no additions to the text, you may delete redundant text.
- [x]  Log content debt.
    - [x] Note common term usage in the [word bank 'Monstro'](https://docs.google.com/spreadsheets/d/1gEyX6ayn1TW7CQxngsMT9pej-egMWxCtxAzRWXAeLfM/edit#gid=0).
    - [x] Create Github issues (tag as content debt).
    - [x] Record content debt in Joplin notes content debt includes: fact-checking, reading level, length, accessibility, questions about the user or the necessity of this page, user research debt, service design debt, policy lab work, and new features to dev.
- [x]  Move to review and tag another content strategist for review.
- [ ]  Reviewer uses [checklist] (https://docs.google.com/document/d/1FVP_ZiQyT2P5F6GUNET327L6hyyexrkA-IzKXQjjzXw/edit#heading=h.7aga879dvzu9) for guidance.
- [ ]  Reviewer hits publish.
- [ ]  Reviewer documents new alpha URL in the department's inventory spreadsheet.
- [ ]  Reviewer documents all newly created Contacts, Locations, documents and other snippets, if applicable

**target date: 9/2 **

**Comment by ablangworthy27** [comment]
[Here is the preview for the service page ](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyMzMz)

**Comment by ablangworthy27** [comment]
Content debt: 
https://github.com/cityofaustin/techstack/issues/4898

**Comment by gabrielaperezdelaosa** [comment]
location page says it's closed every day of the week currently, I image we need to reach out and ask whether they've gone online with these?

**Comment by gabrielaperezdelaosa** [comment]
@ablangworthy27 what happened to the food policy board recommendations? this looks like another official doc collection? I'm not sure what happened here.
