### ISSUE TITLE
Sustainability info page - Eco Districts

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#4860]
### Page or pages that needs to be migrated:
http://austintexas.gov/department/ecodistricts-0
http://austintexas.gov/page/seaholm-ecodistrict
http://austintexas.gov/page/tour-seaholm-ecodistrict

- [x]  Create pages using current content types.
- [x]  Make no additions to the text, you may delete redundant text.
- [x]  Log content debt.
    - [x] Note common term usage in the [word bank 'Monstro'](https://docs.google.com/spreadsheets/d/1gEyX6ayn1TW7CQxngsMT9pej-egMWxCtxAzRWXAeLfM/edit#gid=0).
    - [x] Create Github issues (tag as content debt).
    - [x] Record content debt in Joplin notes content debt includes: fact-checking, reading level, length, accessibility, questions about the user or the necessity of this page, user research debt, service design debt, policy lab work, and new features to dev.
- [x]  Move to review and tag another content strategist for review.
- [x]  Reviewer uses [checklist] (https://docs.google.com/document/d/1FVP_ZiQyT2P5F6GUNET327L6hyyexrkA-IzKXQjjzXw/edit#heading=h.7aga879dvzu9) for guidance.
- [ ]  Reviewer hits publish.
- [x]  Reviewer documents new alpha URL in the department's inventory spreadsheet.
- [x]  Reviewer documents all newly created Contacts, Locations, documents and other snippets, if applicable

**target date: 9/2**

**Comment by ablangworthy27** [comment]
Here is the preview: https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToyNTA3

I eliminated some repetitive content. If there ever is multiple eco-district pages, we can rethink the strategy in the IA and content.

Content debt:
https://github.com/cityofaustin/techstack/issues/4903

**Comment by gabrielaperezdelaosa** [comment]
done, I've not hit publish
