### ISSUE TITLE
Style - Official Document Pages in search results

### ISSUE THREAD

**Issue by robbobfrh84** [cityofaustin/techstack#4861]
Related to issue #4591

### Resources
- Abstract branch: https://share.goabstract.com/2ed5b7fe-57d6-47f8-afa1-9a805630ab4e
- Original design issue: #4435

## Acceptance criteria
- [ ] Implementation matches mocks

### Search presence
- [ ] Document titles are now hyperlinks that go to the single document view
- [ ] `Date` removed
- [ ] `Theme` removed
- [ ] `Part of`: if the document is part of a larger collection, list that collection page name here as a hyperlink. If the document is part of multiple collections, list them inline and separated by a comma
- [ ] `From`: list this as a static string and not a hyperlink

**Comment by jairPineros** [comment]
## QA

**Comment by jairPineros** [comment]
@robbobfrh84 so we are having that issue where we the user get returned to page number 1 regardless of where he/she/they are... but this is nothing we will be introducing since it is already on Production.
