### ISSUE TITLE
Put a notice on bulk pickup

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4864]
Bulk pickup is one of our most visited pages, and also, we get a lot of negative feedback now that the city isn't providing bulk pickup services.

Can we 1) add a notice on this page, or 2) link to somewhere on austintexas.gov that discusses the deal with bulk pick up, or 3) some other solution that notifies the residents that this service has been suspended, and any alternative there might be.

https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup/

**Comment by gabrielaperezdelaosa** [comment]
done, in both languages
