### ISSUE TITLE
All external (outbound links) need a trailing icon

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4874]
The steps on this page have outbound links, and there should be the external link icon (called `open_in_new`) https://alpha.austin.gov/en/health-safety/disaster-safety-relief/disaster-preparedness/public-health-emergency-prep/ so that a user knows what will happen when they click the link.

This is important for residence when searching through Office of Police Oversight related Official Documents can navigate to a new page without losing their work getting to that point 🎉

**Comment by robbobfrh84** [comment]
@jairPineros All ready for you eyes!

Zenhub: https://app.zenhub.com/workspaces/techstack-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/4874

Deployed: https://janis-v3-out-link.netlify.com/

Deployed Example Page for change: https://janis-v3-out-link.netlify.com/en/health-safety/disaster-safety-relief/disaster-preparedness/public-health-emergency-prep/

**Comment by jairPineros** [comment]
we are all good now
