### ISSUE TITLE
Turn on alt-text field in the last version of Wagtail

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4877]
Images need alt text fields to be accessible. 

#4833 is the design issue for doing this, but let's see the default before we tweak.

**Comment by chiaberry** [comment]
https://github.com/wagtail/wagtail/blob/dc2b4a587777f996690c7106d28b53ba4adf3b5c/wagtail/images/rich_text/contentstate.py#L12-L23

https://docs.wagtail.io/en/v2.10/advanced_topics/images/custom_image_model.html

**Comment by chiaberry** [comment]
wagtail doesnt have out of the box alt text. 
alt text can be added when inserting in a rich text field. see issues #4947, #4948
