### ISSUE TITLE
Put up Municourt translations

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4880]

**Comment by sammodabber** [comment]
@gabrielaperezdelaosa Add list of pages to description with checkboxes to break up work

**Comment by gabrielaperezdelaosa** [comment]
list: https://docs.google.com/document/d/1Nmhrts1_J-8zoi99C9egoKZ2rkfC_RDWIOhGgoQtXFI/edit
@jairPineros feel free to close this bad boy once you QA it
