### ISSUE TITLE
Net-zero page for the Office of Sustainability 

### ISSUE THREAD

**Issue by InaraFernandez** [cityofaustin/techstack#4883]
## Page or pages that needs to be migrated:
Need to find home for "climate change heroes" and the 3 principles content on http://austintexas.gov/department/climate-change. 
https://www.austintexas.gov/page/net-zero-level-1-ten-ways-reduce-your-carbon-footprint
http://austintexas.gov/page/net-zero-level-2-intermediate-actions
http://austintexas.gov/page/net-zero-level-3-advanced-actions

- [x]  Create pages using current content types.
- [x]  Make no additions to the text, you may delete redundant text.
- [ ]  Log content debt.
    - [x] Note common term usage in the [word bank 'Monstro'](https://docs.google.com/spreadsheets/d/1gEyX6ayn1TW7CQxngsMT9pej-egMWxCtxAzRWXAeLfM/edit#gid=0).
    - [ ] Create Github issues (tag as content debt).
    - [x] Record content debt in Joplin notes content debt includes: fact-checking, reading level, length, accessibility, questions about the user or the necessity of this page, user research debt, service design debt, policy lab work, and new features to dev.
- [ ]  Move to review and tag another content strategist for review.
- [ ]  Reviewer uses [checklist] (https://docs.google.com/document/d/1FVP_ZiQyT2P5F6GUNET327L6hyyexrkA-IzKXQjjzXw/edit#heading=h.7aga879dvzu9) for guidance.
- [ ]  Reviewer documents new alpha URL in the department's inventory spreadsheet.
- [ ]  Reviewer documents all newly created Contacts, Locations, documents and other snippets, if applicable

**target date: **

**Comment by ablangworthy27** [comment]
Here is the preview link and it is a doozy. Not sure if it can be improved. Its just not a good page. I'll see what I can convince her of. We actually didn't end up talking about this. She did say that Net Zero Heroes could live on the blog, so that is not included.
https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToyNjE0
