### ISSUE TITLE
Alt text for media [Janis]

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4887]
## Behavior
- [ ] Display `alt text` when image doesn't load

## Decisions to make
- [x] On `hover` do we want to display the alt text? By default, Chrome, Firefox and other browsers do not display the text used in the alt attribute when hovering over an image; the alt text is only displayed when an image doesn't load. Also, there are no hover effects on mobile. [Source](https://www.computerhope.com/issues/ch001076.html)
- [ ] How will the text appear when the image doesn't load?

**Comment by chiaberry** [comment]
@chase-vert, is the workflow that after you finish this issue you will open an issue for dev? or should i open that issue, for dev to add the alt text on images in janis?

**Comment by chase-vert** [comment]
@chiaberry Feel free to generate the dev issue! I think there's some simple styling stuff I need to outline here when an image doesn't load, but I don't want to slow down the dev work to turn the feature on.

**Comment by chase-vert** [comment]
I have some outstanding questions about the default styling: 
- padding that comes with images (because this could be an issue if the padding is too large, making the image appear further away from the paragraph it relates to)
- alt text that's displayed in place of the image if the image breaks on Janis

I asked these questions in dev/design sync, and no one seemed to think this would be an issue, so I'll close this issue.
