### ISSUE TITLE
Update homepage banner image

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4893]
# Background
The background image on the homepage has been there for too long at this point, and there are some issues with it that don't make it a great choice in our new reality. 

## To-do
- [x] Swap the existing banner image for this one. Dimensions on this one are 1440px wide by 440px tall, but let me know if it looks weird?

![mj-tangonan-unsplash_Downtown austin](https://user-images.githubusercontent.com/7027270/91760579-36322100-eb99-11ea-9f4f-bc3fdeb91f98.png)

## Acceptance criteria
- [x] Images swapped

**Comment by jairPineros** [comment]
Image is swapped
