### ISSUE TITLE
work in progress message is behind the picture in https://alpha.austin.gov/en/austin-public-health/

### ISSUE THREAD

**Issue by jairPineros** [cityofaustin/techstack#4896]
## Describe the bug
A clear and concise description of what the bug is
Work in progress message is hidden by the picture 
## URL
work in progress message is behind the picture in https://alpha.austin.gov/en/austin-public-health/
## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to https://alpha.austin.gov/en/austin-public-health/
2 see error 

## Current behavior
A clear and concise description of what happened

## Expected behavior
WIP message should be present in all pages 
## Screenshots

![Screen Shot 2020-09-01 at 1.59.55 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/01a89e1e-ddc2-4742-8674-607898c4b77b)

**Comment by robbobfrh84** [comment]
Ready for QA & Review: This issue is a part of https://app.zenhub.com/workspaces/techstack-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/4830

**Comment by jairPineros** [comment]
this issue can be close now
