### ISSUE TITLE
Stop displaying tags on the Images UI

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#4897]
Wagtail has tags, which is cool, but you can't delete them, which is not cool. For now, hide the tag functionality within Images so people don't use them and don't get confused.

Acceptance criteria:
- [ ] Go to the Images section on the left
- [x] No tags are displayed on the list view
- [ ] Go to an image
- [x] No tag field below "Collections" exists on the image detail view

**Comment by chiaberry** [comment]
https://joplin-pr-4897-no-image-tags.herokuapp.com/admin/pages/search/

This is the deployed branch. 

A few times when I first deployed it, I got an internal server error. However when I test it locally over and over again, I can't reproduce it. I can't get it to happen again deployed either, but let me know if you get it.

**Comment by jairPineros** [comment]
no tags are displayed in the list view and there are not any tag fields under the collections
