### ISSUE TITLE
Aligning existing designs to wagtail

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#491]
There is alignment that needs to happen to make the wagtail MVP implementation match existing designs (insofar as possible), both functionally and visually. This is a placeholder for that work as it becomes apparent.

**Comment by amenity** [comment]
Broke into smaller issues:
Content listing: https://github.com/cityofaustin/techstack/issues/548
Service page template: https://github.com/cityofaustin/techstack/issues/549
Preview & share: 
_Create content_ modal: https://github.com/cityofaustin/techstack/issues/551
In-page Images: 
https://github.com/cityofaustin/techstack/issues/549
