### ISSUE TITLE
Don't duplicate data fetching for '/en' and '/' builds

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#4917]
We could really cut down our Janis build times if we didn't run a whole build for both '/en' and '/' routes in static.config.js.

I made an attempt to just copy the translatedRoutes object from '/en' into '/'. It did not work. I tried to `_.deepClone()` the '/en' object, change the path to '/' and then add it to our translatedRoutes array. And superficially it looked like all the child pages were there (the correct length was there). But when the site was actually built, many pages were missing for the '/' root routes. For example: "/police-oversight" only had 68 pages, but "/en/police-oversight" had 274 pages in my test. So something isn't copying over correctly. 

I was just experimenting while tried to do another issue, so there is more digging that could be done.

**Comment by chiaberry** [comment]
done during turbo work.
