### ISSUE TITLE
Draft Service Page for Food Handler Resources

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#493]
Current: http://austintexas.gov/department/food-personnel-requirements
Drive: https://docs.google.com/document/d/153zaCfYHDbeYSTJw-FnoHXUMPiaH3ezaE2x17BjQ5Ww/edit#

Reviewed by:
- [ ] Ashlee
- [x] Courtney

**Comment by ashleecoa** [comment]
Reviewed!

**Comment by courtneyjacinic** [comment]
Reviewed!
