### ISSUE TITLE
Draft service page for Inspection scores

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#494]
Current: http://austintexas.gov/department/restaurant-inspection-scores
Drive: https://docs.google.com/document/d/1BwqYerXXWkcXTaUchsS25KaFS6OCD6K_Kc_qrS-Od30/edit#

Reviewed by:
- [ ] Ashlee
- [x] Courtney

**Comment by ashleecoa** [comment]
Reviewed

**Comment by courtneyjacinic** [comment]
It should be noted that the dataset is difficult to search. We cannot at this time control the quality of the datasets or their interfaces.
