### ISSUE TITLE
Joplin - Add images to Info pages

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#4947]
Add ability to add images via rich text fields on information pages
Check that alt text fields get sent over in schema

**Comment by jairPineros** [comment]
Hey @chiaberry so I'm not too sure about passing this one since the left align and right align picture has no difference... I'm not sure if this is going to be an issue for the content team maybe @Jo-Dwyer could comment whether or not that is a show stopper?

**Comment by jairPineros** [comment]
Images can't be added thru rich text ![Screen Shot 2020-09-25 at 2.32.36 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/0974d0d7-9bfe-4697-bd23-16281e001726)
