### ISSUE TITLE
Draft service page for Tuberculosis (TB)

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#495]
Current: http://austintexas.gov/department/tuberculosis
Drive: https://docs.google.com/document/d/1Fi0AumyVMuGhnLB_9_vtnOcTJJK74NjezgbROohGu70/edit#
Reviewed by:
- [ ] Ashlee
- [x] Courtney

**Comment by courtneyjacinic** [comment]
Reviewed!
