### ISSUE TITLE
Virtual event support ∙ Janis dev criteria

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4951]
Original Janis [design] issue: https://github.com/cityofaustin/techstack/issues/4348
Joplin issue: https://github.com/cityofaustin/techstack/issues/4940

## Background
Due to COVID-19, lots of events have been canceled or switched to virtual options. It could be helpful for residents to indicate virtual events where the `Location` data normally displays. 

## Resources
- Dev criteria collection: https://share.goabstract.com/6c110358-d5be-439a-bafb-6a5a0ae38183

## Criteria
- [x] Icon: use the `screen` icon in the Material Icon font pack we have in Janis
- [ ] Label: this label should replace where the `address` information normally populates anywhere on the instance view (home page, search result list, event list (all), service pages, and information pages (I think events can be added on info pages, but I'm not remembering?)
  - [x] EN: "`Virtual event`"
  - [x] ES: "`Evento virtual`"
- [x] Remove the "Location information" tile that sits below the component
- [x] Border: `border-radius: 4px`

**Comment by chiaberry** [comment]
Label: this label should replace where the address information normally populates anywhere on the instance view 
 - [ ] home page
 - [ ] search result list
 - [ ] event list (all),
 - [ ] service pages 
 - [ ] information pages
 - [ ] location pages

Events can have virtual, city of austin, non city locations or a combo of virtual/city  or virtual/non-city
