### ISSUE TITLE
🚧  Global alert style tweaks ∙ dev criteria

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4954]
# Overview

This update removes some styling to streamline the design and adjusts the yellow hue so that it's more harmonious with the primary blue, making the component more balanced in the interface.

# Criteria

Original design issue: https://github.com/cityofaustin/techstack/issues/4936
Abstract collection: https://share.goabstract.com/4035d2f0-6e37-431c-9da7-4832eb5109a1

**Before** [desktop]
![image](https://user-images.githubusercontent.com/7027270/93622349-9949f300-f9a2-11ea-9d66-7494f934060d.png)

**After** [desktop]
![image](https://user-images.githubusercontent.com/7027270/93622381-a830a580-f9a2-11ea-8465-336bc4952c46.png)

## Global alert
- [ ] Background color: `#face2f` or USWDS: `yellow-20v`
- [x] Text color: `#1b1b1b` or USWDS: `gray-90`

**Alert label**
- [x] We don't need the container around the label anymore, so this can just be inline with the description text
- [ ] font-weight: `medium` or `500`

**Description**
- [x] Description text is now static, and no longer a link

**Links**
- [ ] Add a new "Read more" link after the description
  - [ ] EN: "Read me"
  - [ ] ES: " "
- [x] The distance between the `description text` and `read more link` is `8px`
- [x] Add the trailing icon after the "Read me" string, the distance between those two elements are `4px`
- [ ] Links to pages on alpha.austin.gov should display the `arrow_forward` icon from the Material icon font within our codebase
- [x] Outbound links hosted outside of alpha.austin.gov should display the `open_in_new` icon from the Material icon font within our codebase

**Conditional styling**
- [x] If >1 alert, add border-bottom: 1px, `#fee685` or USWDS `yellow-20v` to all except the final alert in the list
- [ ] Mobile: don't display `description`

**Responsive behavior**
- [x] Since the alert is now restyled to be all in-line, with no pill shaped label, lets let the text use the `overflow-wrap`. (I could be wrong on the property, but ultimately I'm wanting the text to flow normally, breaking into however many lines it needs to as the viewport contracts.)
  - [ ] Notice the tablet view, where the line break is flush left with the alert label but not the leading icon
- [x] Entire banner becomes the `tap-target`
- [x] Hide `leading icon`
- [x] Hide `link`
- [x] Place `trailing icons` to the right of the container

## Location alert
This may need to be broken off into a separate issue. Location alerts are similar but have some important distinctions since they are displayed in the body of a page instead of inline at the global level.
- [ ] Alert label is treated as a header for the component/object
- [ ] There are two descriptions, each within its own block (thinking in terms of grids or tables)
  - [ ] a description that's specific to `location content types`
  - [ ] the description that comes from the global/parent alert, and this entire row is a clickable link
- [ ] "Read more" doesn't appear here, and instead the description row is the tap/click target.

**Comment by chiaberry** [comment]
@jairPineros  https://janis-v3-4954-global-alert.netlify.app/en/location/first-workers-day-labor-center/ for review

**Comment by jairPineros** [comment]
@chiaberry hi Chia it looks good execpt for the issue of not wrapping up well in big IOS devices. I think you saw that on iPads and also it is present in big screen phones like Iphone 11pro max
<img width="719" alt="Screen Shot 2020-12-08 at 1 25 09 PM" src="https://user-images.githubusercontent.com/67925539/101544192-1fe6ee80-395a-11eb-824d-7f54fd463968.png">
<img width="798" alt="Screen Shot 2020-12-08 at 1 28 35 PM" src="https://user-images.githubusercontent.com/67925539/101544208-237a7580-395a-11eb-8c18-359a50a1898d.png">

**Comment by jairPineros** [comment]
![Uploading Screen Shot 2020-12-08 at 1.42.19 PM.png…]()
