### ISSUE TITLE
Draft service page for Diabetes Education and Prevention Classes

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#496]
Current: http://austintexas.gov/department/diabetes-education
Drive: https://docs.google.com/document/d/1trSHZt3qXFT9VFVPny1CTT-T_yfSJXjMIFGFjDmLBQc/edit#

Reviewed by:
- [ ] Ashlee
- [x] Courtney

**Comment by courtneyjacinic** [comment]
@LauraTrujillo question in comments
