### ISSUE TITLE
Draft service page for Click here for more diabetes resources.

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#498]
Current: http://www.austintexas.gov/department/central-texas-diabetes-coalition
Drive: https://docs.google.com/document/d/1llvtWtb2JSuAA6D8GDdBOsZW5JfZeq01C1XtpF3dVxI/edit#heading=h.e4san3fgxsj5

Reviewed by:
- [ ] Ashlee
- [x] Courtney

**Comment by ashleecoa** [comment]
Reviewed!

**Comment by courtneyjacinic** [comment]
@LauraTrujillo one question in there!
