### ISSUE TITLE
Foster Prototype 0.2: Iterate prototype based on AAC feedback

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#50]
[Prototype](https://github.com/cityofaustin/prototypeform)

Note that the size estimate is dependent on choice made during #48.

**Comment by juliazbyron** [comment]
@courtneyjacinic is taking first pass by creating a branch then I'll review

**Comment by courtneyjacinic** [comment]
@juliazbyron pull request sent with first pass. Some more complex edits need to be made and are noted in this feedback document: https://docs.google.com/document/d/1PRMP93pCLEc0JcdUlzXI7EZ7ppmOspPWS_teeqHns3E/edit
