### ISSUE TITLE
Translations for Search Filters

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#5010]
Hi! We need a few words translated for Spanish. This is for our Official Document Page Search Filters. The context for these words can be found in the design mocks: 
- https://app.abstract.com/projects/065fcabf-a46a-4688-a858-83ce2117b16c/branches/3a2b0cf9-c911-4f50-a55f-51192d591bc2/collections/6942dcd9-cbff-47ad-8469-3f74bd202806
- https://app.abstract.com/projects/065fcabf-a46a-4688-a858-83ce2117b16c/branches/3a2b0cf9-c911-4f50-a55f-51192d591bc2/commits/latest/files/5f438f7c-5610-4e53-bb46-96c489d88052/layers/2739911c-0232-412c-9545-63baf8cbd812?collectionId=6942dcd9-cbff-47ad-8469-3f74bd202806&collectionLayerId=88072142-047f-4203-b22c-81dd6e609a6f
- PR build so far: https://janis-v3-4849-filter.netlify.app/en/health-safety/policing-in-austin/police-feedback-and-records/nicks-small-collection/#page=1

Words/Statements to translate:
- [ ] Filter
- [ ] Date
- [ ] From
- [ ] To
- [ ] Month
- [ ] Day
- [ ] Year
- [ ] Clear filters
- [ ] Apply filters
- [ ] Filter by date
- [ ] {x} filtered results
- [ ] 1 filtered result

**Comment by InaraFernandez** [comment]
Date- Fecha
 From- Desde
 To- Hasta
 Month- Mes 
 Day- Día 
 Year- Año
 Clear filters-  Borrar filtros
 Apply filters- Aplicar filtros 
 Filter by date- Filtrar por fecha
 {x} filtered results- (x) resultados filtrados
 1 filtered result- 1 resultado filtrado 
@Niicck
