### ISSUE TITLE
Contacts on Janis crash if Facebook links don't include trailing slashes

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#5012]
## Describe the bug
If on joplin you set the facebook url as facebook.com/AustinFireDepartment, the component will crash in Janis. it is looking for facebook.com/AustinFireDepartment/

## To Reproduce
Steps to reproduce the behavior 
example: 

We need to adjust the regex, add a error boundary? have it choose the correct match group instead of going for one that is undefined.

**Comment by chiaberry** [comment]
https://janis-v3-5012-contact-slash.netlify.app/ is the janis

is the linked joplin https://joplin-pr-4907-remove-importer.herokuapp.com/admin/snippets/contact/contact/1/

**Comment by jairPineros** [comment]
issue was resolved by dev:

![Screen Shot 2020-10-30 at 1.52.37 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/210a6efc-3c1e-47e4-9eea-e7a25fd5c9e2)
