### ISSUE TITLE
Topic collection translation stuck on Spanish when English is selected: TurboJanis

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#5027]
## Describe the bug
![Screen Shot 2020-10-02 at 11.54.06 AM.png](https://images.zenhubusercontent.com/5be0b7bea977220c77bd229b/20821627-9415-42b6-99af-4e172facadf3)
![Screen Shot 2020-10-02 at 11.54.23 AM.png](https://images.zenhubusercontent.com/5be0b7bea977220c77bd229b/3e97127f-ea77-448a-b566-35966ba78efb)

The topic collection page is also 404ing when you click Spanish: https://janis-v3-demo.netlify.app/es/permits-tickets/building-and-development-permits

## URL
https://janis-v3-demo.netlify.app/en/permits-tickets/building-and-development-permits/

## To Reproduce
Steps to reproduce the behavior 
example: 

## Current behavior
A clear and concise description of what happened

## Expected behavior
A clear and concise description of what you expected to happen

**Comment by gabrielaperezdelaosa** [comment]
I think this was maybe user (me) error and is now fixed.
