### ISSUE TITLE
Turbo 404s / Missing Pages

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#5029]
Add missing 404s that you encounter. Some might be related to builds failing in general, some might not. We'll checkbox them if they end up working later. **Please add the id for the page you list**

- [ ] From @srigdon 
  - Page Id = 1003
>  park day pass is 404ing, i haven’t looked at why - https://janis-v3-demo.netlify.app/en/explore-visit/public-parks-and-greenways/get-outside/get-a-day-pass-for-a-park-in-austin

- [ ] https://app.zenhub.com/workspaces/techstack-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/5030

- [ ] Get funding for cultural arts programs
    Page ID =  850
    https://janis-v3-demo.netlify.app/en/housing-utilities/financial-help/grants-and-funding/funding-for-cultural-arts-programs/ 

- [ ] Permisos de construcción (Building permits in Spanish)
    Page ID = 823
    https://janis-v3-demo.netlify.app/es/permits-tickets/permisos-de-construccion

**Comment by gabrielaperezdelaosa** [comment]
Economic Development Department Page is 404ing: https://janis-v3-demo.netlify.app/en/economic-development/
