### ISSUE TITLE
Bug with event not appearing on a department page

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#5030]
## Describe the bug
This [Roots and Wings Event](https://janis-v3-demo.netlify.com/event/2020/10/24/roots-wings-festival) should be appearing on the [PARD Department page](https://janis-v3-demo.netlify.app/en/parks-and-recreation/). [The event does appear to be associated with the department. ](https://joplin-pr-demo.herokuapp.com/admin/groups/9/). I don't know why it's not appearing. 

## Device and browser
PC Chrome

**Comment by chiaberry** [comment]
I looked at the code and events arent written to show up on department pages as of now. So this isnt so much a bug as a feature that doesnt exist.

**Comment by gabrielaperezdelaosa** [comment]
well woops, thanks for looking at it Chia, I'll create a feature request issue
