### ISSUE TITLE
Spanish translations for the Office of Design and Delivery research sign-up questions

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#5033]
- [ ] Spanish translations needed for research sign-up questions([Reference document for translations from the page 5](https://docs.google.com/document/d/1D4wCsZ3siuQegEA-SHBJfIloC7jq4d2LH8LgrkAVeX0/edit?usp=sharing))
- [ ] Attach the Formstack sign-up links(English and Spanish versions) in the [research sign-up webpage](https://alpha.austin.gov/en/feedback/)
- [x] For reference, [here](https://cityofaustin.formstack.com/forms/office_of_design_and_delivery_research_signup_form) is the re-iterated and Formstack transitioned form 

Adding @toribr here to put this issue on her radar

**Comment by InaraFernandez** [comment]
@anukandimalla , I think this has already been done?

**Comment by anukandimalla** [comment]
Yes, it's done and sorry I forgot to close the issue.
