### ISSUE TITLE
Draft process page for How to Start a Mobile Food Business

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#504]
Current:chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/http://austintexas.gov/sites/default/files/files/Health/Environmental/RevisedSite/How_to_Start_a_Mobile_Food_Business_EN_4-16.pdf
Drive:

Reviewed by:
- [ ] Ashlee
- [ ] Courtney

**Comment by ashleecoa** [comment]
Draft: https://docs.google.com/document/d/1VCL-BZKzL9axkZtQVqrMAdmkkUSt2SYppjFulOkIEcE/edit?usp=sharing
