### ISSUE TITLE
OPO document collections

### ISSUE THREAD

**Issue by InaraFernandez** [cityofaustin/techstack#5042]
Each of these document collections were created published for document type: 

All documents housed under the "[Official complaint and discipline documents](https://alpha.austin.gov/en/health-safety/policing-in-austin/police-feedback-and-records/official-complaint-and-discipline-documents/#page=1)" need to be broken down into: 
[Formal complaints](https://joplin.herokuapp.com/admin/pages/826/edit/#tab-content)
[Disciplinary memos](https://joplin.herokuapp.com/admin/pages/829/edit/#tab-content)
[Written reprimands](https://joplin.herokuapp.com/admin/pages/828/edit/?next=/admin/pages/828/edit/#tab-content)
[Oral reprimands](https://joplin.herokuapp.com/admin/pages/827/edit/#tab-content)
[Protest complaints](https://joplin.herokuapp.com/admin/pages/666/edit/#tab-content)

[Police oversight reports and recommendations ](https://alpha.austin.gov/en/health-safety/policing-in-austin/police-feedback-and-records/office-of-police-oversight-official-reports/#page=1)

currently unpublished- [Memos from Austin Police Chief Brian Manley](https://joplin.herokuapp.com/admin/pages/731/edit/#tab-content)
[OPO reports and recommendations ](https://joplin.herokuapp.com/admin/pages/830/edit/#tab-content)

Content side: 
- [x] Draft descriptions for each document type
- [x] Get feedback from OPO on descriptions
- [x] Create topic where all of these document collections will live
- [x] Figure out IA to get rid of the topic collection "policing in Austin" 

cc: @toribr

**Comment by InaraFernandez** [comment]
@chiaberry 
Document conventions in [Official complaint and discipline documents](https://alpha.austin.gov/en/health-safety/policing-in-austin/police-feedback-and-records/official-complaint-and-discipline-documents/#page=1)
temporary suspension of [officer/detective]
written reprimand
oral reprimand 
all complaint docs should start with "formal complaint" 
Batches: 
[Formal complaints OPO processed on June 1: Purpose and scope—community policing and other policy violations](https://alpha.austin.gov/police-oversight/formal-complaints-opo-processed-on-june-1-purpose-and-scopecommunity-policing-and-other-policy-violations/)
[Formal complaints OPO processed on June 2: Purpose and scope—community policing and other policy violations](https://alpha.austin.gov/police-oversight/formal-complaints-opo-processed-on-june-2-purpose-and-scopecommunity-policing-and-other-policy-violations/)
[Formal complaints OPO processed on June 3: Purpose and scope—community policing and other policy violations](https://alpha.austin.gov/police-oversight/formal-complaints-opo-processed-on-june-3-purpose-and-scopecommunity-policing-and-other-policy-violations/)
[Formal complaints OPO processed on June 4: Purpose and scope—community policing and other policy violations](https://alpha.austin.gov/police-oversight/formal-complaints-opo-processed-on-june-4-purpose-and-scopecommunity-policing-and-other-policy-violations/)
[Formal complaints OPO processed on June 5: Purpose and scope—community policing and other policy violations](https://alpha.austin.gov/police-oversight/formal-complaints-opo-processed-on-june-5-purpose-and-scopecommunity-policing-and-other-policy-violations/)
[Formal complaints OPO processed on June 8: Purpose and scope—community policing and other policy violations
](https://alpha.austin.gov/police-oversight/formal-complaints-opo-processed-on-june-8-purpose-and-scopecommunity-policing-and-other-policy-violations/)
[Formal complaints OPO processed on June 9: Purpose and scope—community policing and other policy violations](https://alpha.austin.gov/police-oversight/formal-complaints-opo-processed-on-june-9-purpose-and-scopecommunity-policing-and-other-policy-violations/)
[Formal complaints OPO processed on June 10: Purpose and scope—community policing and other policy violations](https://alpha.austin.gov/police-oversight/formal-complaints-opo-processed-on-june-10-purpose-and-scopecommunity-policing-and-other-policy-violations/)
[Formal complaints OPO processed on June 11-30](https://alpha.austin.gov/police-oversight/formal-complaints-opo-processed-on-june-11-30/)- it looks like this may duplicated, I am going to look into it.

**Comment by chiaberry** [comment]
@InaraFernandez  can I close this, now that they are moved over?
