### ISSUE TITLE
QA Community Garden Permit Guide

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#5044]
[The community garden permit guide](https://alpha.austin.gov/en/explore-visit/neighborhoods/gardens/community-garden-permit-guide/)
[and all its constituent pages](https://alpha.austin.gov/en/health-safety/sustainability-and-environment/gardens/)
[Program page](https://alpha.austin.gov/en/health-safety/sustainability-and-environment/gardens/community-gardens-program/)
[Interest form](https://alpha.austin.gov/parks-and-recreation/community-garden-interest-form/)

Acceptance criteria
There are 2 formstacks in there, please test both and that you get a confirmation email
That the links work in each page
That the guide is loading properly and the table of contents on it works
Pages are assigned a topic and a contact (this won't show up within the guide)
(there is no translation at this time)

**Comment by jairPineros** [comment]
Hey @gabrielaperezdelaosa  This link to the CDC doesn't link to the right place ![Screen Shot 2020-10-09 at 3.22.52 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/03bc9682-a6ae-495b-945e-bb951c4db28d)

This is what I get:
![Screen Shot 2020-10-09 at 3.28.10 PM.png](https://images.zenhubusercontent.com/5f05cb2ac67f7f6ab3c0b762/af3466b9-397b-4897-9a3c-6abf89210859)

This is the link:
https://alpha.austin.gov/en/health-safety/sustainability-and-environment/gardens/community-gardens-program/

**Comment by jairPineros** [comment]
Form works fine I got the email.

**Comment by jairPineros** [comment]
Form works fine I got the email.
