### ISSUE TITLE
Add Virtual Events to EventPage search_output

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#5054]
When Virtual Events become a real feature, the EventPage's search_output must be modified to include them.

**Comment by chiaberry** [comment]
Note, since the only events that are being added are CPRC events, this directly affects OPO

**Comment by chiaberry** [comment]
https://joplin-pr-5054-events-search.herokuapp.com/admin/pages/search/
https://janis-v3-5054-events-search.netlify.app/
