### ISSUE TITLE
Draft service page for STD (Sexually transmitted diseases) clinic

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#506]
Current: http://austintexas.gov/department/sexually-transmitted-diseases-stds
Drive: https://docs.google.com/document/d/1IGhEBxFOXxWam7ghcmcP9bTvn-YXZF-mVyCEnwAr6gQ/edit?usp=sharing

**Comment by LauraTrujillo** [comment]
reviewed!

**Comment by courtneyjacinic** [comment]
reviewed!
