### ISSUE TITLE
Joplin deletes and won't publish my Spanish OPO entries. 

### ISSUE THREAD

**Issue by InaraFernandez** [cityofaustin/techstack#5067]
## Describe the bug
Joplin isn't saving any of the changes I've made in Spanish. It's likely been doing this for a few weeks in the topic collection titled "Police oversight reports and recommendations", this is a page I've tried to publish twice and save as a draft on my last attempt: 
https://joplin.herokuapp.com/admin/pages/833/edit/#tab-content
This problem only seems to be happening on this document collection: https://alpha.austin.gov/es/health-safety/accountability-and-transparency-in-policing/police-feedback-and-records/office-of-police-oversight-official-reports/

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to https://joplin.herokuapp.com/admin/pages/833/edit/#tab-content
2. Click on the Spanish tab
3. Input the following translation: 
**Title**: Recomendación: Las Órdenes Generales (General Orders) del Departamento de Policía de Austin, cortesía de actitud imparcial y conducta personal 
**Authoring office**: Oficina de Fiscalización de la Policía
**Document summary**: La Oficina de Fiscalización de la Policía recomienda cambios a las Órdenes Generales (General Orders) del Departamento de Policía de Austin. Estas políticas informan al proceso operativo policial, la respuesta, y la conducta. Las recomendaciones incluyen actualizar el lenguaje para refinar las Órdenes Generales 301.2 cortesía de actitud imparcial, 900.3.4 conducta personal, y la matriz de disciplina relacionadas con estas políticas. 
Estos cambios alinearán al Departamento de Policía de Austin con las mejores prácticas nacionales, sostendrán las normas equitativas de ley, y establecerán la responsabilidad para los oficiales de la policía. 
**Name of document**: Recomendación: Las Órdenes Generales (General Orders) del Departamento de Policía de Austin, cortesía de actitud imparcial y conducta personal (en inglés)
**Doc name**: Recommendation: Impartial Attitude Courtesy and Personal Conduct
4. Hit "publish" and try to go back to the entry.... on my screen it just returns all fields to blank. 

## Expected behavior
It should save and publish my entries 

## Device and browser
Chrome on mac
CC: @chiaberry @robbobfrh84

**Comment by chiaberry** [comment]
@jairPineros

**Comment by chiaberry** [comment]
I wasn't able to reproduce @InaraFernandez and @jairPineros, I will take myself off the issue but leave it open in case it happens again

**Comment by InaraFernandez** [comment]
Cleared my cache, solved the problem.
