### ISSUE TITLE
Draft service page for Where to get tested

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#507]
Current: http://austintexas.gov/department/where-get-tested
Drive: https://docs.google.com/document/d/1WYxl7K2xZoDHc52a1olKIPWJpP5d_mFgH39TS1nuCuo/edit?usp=sharing

**Comment by LauraTrujillo** [comment]
reviewed!

**Comment by courtneyjacinic** [comment]
reviewed!
