### ISSUE TITLE
pdf size on search results

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#5075]
## Describe the bug

The pdf size on documents are coming across as I think just the bytes and not KB? But the numbers dont match when you click into the page all the time. 

## URL

https://alpha.austin.gov/en/police-oversight/official-complaint-and-discipline-documents/

## To Reproduce
Steps to reproduce the behavior 
example: 

## Current behavior
A clear and concise description of what happened

## Expected behavior
A clear and concise description of what you expected to happen

## Screenshots

![Screen Shot 2020-12-01 at 11.59.57 AM.png](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/3a493e37-855c-4e6e-b59c-255698881aff)

**Comment by chiaberry** [comment]
compare: https://alpha.austin.gov/en/police-oversight/official-complaint-and-discipline-documents/

to: https://janis-v3-5075-pdf-size.netlify.app/en/police-oversight/official-complaint-and-discipline-documents/

**Comment by jairPineros** [comment]
Tested and passed
