### ISSUE TITLE
official document collection preview is crashing

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#5084]
https://alpha.austin.gov/en/preview/official_document_collection/UGFnZVJldmlzaW9uTm9kZTo0MDk1

**Comment by chiaberry** [comment]
https://janis-v3-5084-crash.netlify.app/en/preview/official_document_collection/UGFnZVJldmlzaW9uTm9kZTo0MDk1

Last week Inara found a bug where you can't preview OfficialDocumentCollections from joplin, here is a PR that fixes that: https://github.com/cityofaustin/janis/pull/911
to test: try to preview an official document collection from joplin, change the preview url from alpha.austin.gov to janis-v3-5084-crash.netlify.app and :fingers_crossed: it should preview

**Comment by jairPineros** [comment]
Tested and passed
