### ISSUE TITLE
Information page contact snippets missing information

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#5087]
We don't query the social media handles for the information pages. We should. ![Screen Shot 2021-01-22 at 1.46.38 PM.png](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/88bcf8e9-a196-4f8a-b948-0479798504a4)![Screen Shot 2021-01-22 at 1.46.26 PM.png](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/bf0e4338-0bbc-4358-8135-146145562af7)

**Comment by chiaberry** [comment]
@jairPineros  Information pages didn't request the social media handles: https://janis-v3-5087-info-contact.netlify.app/police-oversight/complaint-investigation-process/

But now they do!

**Comment by jairPineros** [comment]
Tested and passed!
