### ISSUE TITLE
Get AAC feedback on prototype

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#51]
[Prototype](https://github.com/cityofaustin/prototypeform)

**Comment by juliazbyron** [comment]
I sent an email to Erin and Lorian yesterday and received an OOO message in return saying Lorian is out until 3/3, so I'm guessing we'll do it next week. I'll still try to coordinate for that with Erin.

**Comment by juliazbyron** [comment]
Scheduled for Tues 3/6 from 12-1 at AAC
