### ISSUE TITLE
Draft service page for Graffiti Removal

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#510]
Current: http://austintexas.gov/graffiti
Drive: https://docs.google.com/document/d/1cEVTp3JCeWiCLYnHxqoZA-MAwb2kB_fd04bCLnyVZcI/edit

**Comment by ashleecoa** [comment]
On hold due to political decisions being made around entire graffiti program

**Comment by LauraTrujillo** [comment]
@JeffCopy please work your magic! :)

**Comment by JeffCopy** [comment]
My suggested edits added; onward!

**Comment by LauraTrujillo** [comment]
@annieszot your turn, please!

**Comment by LauraTrujillo** [comment]
@annieszot Ready for youuuuuu

**Comment by annieszot** [comment]
@LauraTrujillo Marked up with suggested edits!
