### ISSUE TITLE
Draft service page for Fresh for Less Healthy Food Access Project

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#511]
Current: http://www.austintexas.gov/freshforless
Drive: https://docs.google.com/document/d/1ZQQiwrr5ahcwJqx1fMzpkvxiT-NtHuavuHoEJNJ6Its/edit?usp=sharing

**Comment by LauraTrujillo** [comment]
reviewed!

**Comment by courtneyjacinic** [comment]
Reviewed!
