### ISSUE TITLE
Draft service page for Immunizations Program

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#512]
Current: http://www.austintexas.gov/immunizations
Drive: https://docs.google.com/document/d/1gC5eOWnzxeL_Kwi7FGFFoiQGBE2myShO1QbKam-NPk8/edit?usp=sharing

https://docs.google.com/document/d/1CdHeFbMTTUabOuf7qeg6wZh_Zaw8YK52ACuPn-B0M8M/edit?usp=sharing

**Comment by LauraTrujillo** [comment]
reviewed both docs!

**Comment by courtneyjacinic** [comment]
Reviewed both docs. One question on getting records. @ashleecoa can you only get your own records or can you also get your child's? Should we make space for that?

**Comment by ashleecoa** [comment]
@courtneyjacinic I don't know. Could you put a note in the doc so Health can answer that for us
