### ISSUE TITLE
Draft service page for car seat checks

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#515]
Current: chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/http://austintexas.gov/sites/default/files/files/Health/Chronic_Disease/2018_car_safety_seat_schedule.pdf
Drive:

**Comment by ashleecoa** [comment]
https://docs.google.com/document/d/1Vx7w4fGwk3ZAO7BQnuZgCcl-HJtfUw8Y1xa6GZn4IpM/edit?usp=sharing

**Comment by LauraTrujillo** [comment]
reviewed!

**Comment by courtneyjacinic** [comment]
reviewed!
