### ISSUE TITLE
Draft process page for How to Start a Farmers Market Business

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#517]
Current: chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/http://austintexas.gov/sites/default/files/files/Health/Environmental/Food/How_to_Start_a_Farmers_Market_Booth_Business_2018.pdf
Drive:

**Comment by amenity** [comment]
[Putting Process Page back in the ol' backlog](https://github.com/cityofaustin/techstack/issues/821). Will recreate tasks when necessary.
