### ISSUE TITLE
Draft service page for ordering a certificate

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#518]
Current: http://austintexas.gov/department/obtaining-birth-or-death-certificate
Drive: 

** This will be the service page. Pull info from birth certificate's page (http://austintexas.gov/birthcertificates) for additional information Each option for ordering a birth certificate could be a service page, or all 4 ways could be a how-to page. Curious why they have this language "To request vital records from other states, visit the National Center for Health Statistics website for more information." under a button instead of just linking to National Center for Health Statistics. The button looks like a link.

******
Additional Information/Content comes from: http://austintexas.gov/birthcertificates

**Comment by courtneyjacinic** [comment]
Google doc: https://docs.google.com/document/d/1zTCZdgrlDyVbxVKKZl57DglwCqCK1fx7LuEgiiyjp1g/edit#
