### ISSUE TITLE
Foster Prototype 0.2: Create Usability Test Plan

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#52]

**Comment by juliazbyron** [comment]
[Foster App Prototype 0.2 Test Plan](https://docs.google.com/document/d/171_JFZLMyNTs5zQT-5kUxprQo70Zk1W8uAkvsahFRk4/edit?usp=sharing)

**Comment by juliazbyron** [comment]
@amenity @MireyaGalarza Check out the plan, let me know your feedback.

**Comment by amenity** [comment]
@MireyaGalarza note that we need to review ASAP.

**Comment by amenity** [comment]
@juliazbyron This looks good. My only concern is that the tests will be long, so let's plan to time the practice tests and adjust discussion length if necessary. Max 20 minutes per person? 

We also need to let them know how long it will take before they start.

**Comment by juliazbyron** [comment]
@amenity Sorry if I didn't make it clear in there, but I was thinking different people would be doing task 1 and task 2 to cut the time down. Also aiming for 20 mins per person. Agreed about letting them know how long it'll take.

**Comment by amenity** [comment]
@juliazbyron - aha, sorry I missed that. Sounds 👌!

**Comment by juliazbyron** [comment]
Just waiting on @MireyaGalarza 's feedback and testing the test to wrap up

**Comment by juliazbyron** [comment]
Finalized.
