### ISSUE TITLE
Draft informational or process page for Public and semi-public pools and spas

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#520]
Current: http://austintexas.gov/department/pools-spas-interactive-water-features-and-fountains
Drive:

**Comment by LauraTrujillo** [comment]
Is this more of a process page or informational page?

**Comment by amenity** [comment]
@wilhitem - what's the plan for this intro?

**Comment by amenity** [comment]
[Putting Process Page back in the ol' backlog](https://github.com/cityofaustin/techstack/issues/821).
