### ISSUE TITLE
Draft informational page for Austin Youth Council

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#522]
Current: http://austintexas.gov/page/austin-youth-council
Drive: https://docs.google.com/document/d/10ic2yS3jTxRoiBAGc_40lcFSY3bLB98tv-QMoPAqZb8/edit#

**Comment by desigonz** [comment]
@LauraTrujillo Found this one still assigned to Jeff, rolling over to sprint 35 and assigning to you instead. Let me know if that's unreasonable/if you've got way too much on your plate!

**Comment by LauraTrujillo** [comment]
@annieszot first review to you! If you can complete it by Tuesday, July 23rd I'd appreciate it.

**Comment by annieszot** [comment]
Great work @LauraTrujillo ! Suggested edits added and just needs content debt documented for related alpha pages :)

**Comment by LauraTrujillo** [comment]
Documented content debt. Thanks, @annieszot!
