### ISSUE TITLE
Draft service page for Shots for tots and Big Shots clinic schedule in English

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#524]
Current: http://www.austintexas.gov/sites/default/files/files/Health/Immunizations/Imm_Consent_Form_1_page.pdf
Drive:

**Comment by ashleecoa** [comment]
https://docs.google.com/document/d/1CdHeFbMTTUabOuf7qeg6wZh_Zaw8YK52ACuPn-B0M8M/edit?usp=sharing

**Comment by LauraTrujillo** [comment]
reviewed!

**Comment by courtneyjacinic** [comment]
Reviewed!
