### ISSUE TITLE
Draft process page for Plan Review Checklist

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#526]
Current: chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/http://austintexas.gov/sites/default/files/files/Health/Environmental/FeeChanges/Plan_Review_Checklist_PS_100117.pdf
Drive:

**Comment by amenity** [comment]
[Putting Process Page back in the ol' backlog](https://github.com/cityofaustin/techstack/issues/821). Will recreate tasks when necessary.
