### ISSUE TITLE
Foster Prototype 0.3: Iterate form design based on usability testing and AAC feedback

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#53]
Testing results located in https://github.com/cityofaustin/techstack/issues/151
AAC feedback located in https://github.com/cityofaustin/techstack/issues/279

~- [ ] copy (text) edits changed in the prototype~ Now to be done by @courtneyjacinic 

- [x] UX and visual design updates in Sketch

**Comment by juliazbyron** [comment]
[Sketch file](https://drive.google.com/open?id=1648ltRiihC2G6vVPyfSWiyXP_2qXkuNV)

**Comment by juliazbyron** [comment]
I'll be pursuing the new help text layout on the last image on this sketch
![doc_05012018171835](https://user-images.githubusercontent.com/13106016/39594149-769ffa62-4ed1-11e8-93eb-ebd6dce06f43.jpg)

I'll be pursuing a progress bar like the image in the 3rd column, 2nd row in this sketch.
![doc_05012018171835-0005](https://user-images.githubusercontent.com/13106016/39594189-90575612-4ed1-11e8-98de-e03aa0cbc71f.jpg)

**Comment by juliazbyron** [comment]
Sketch file ready for review by design. Showed to Mateo already, but needs redlining for devs.

**Comment by juliazbyron** [comment]
Wrapping up improvements today.

**Comment by juliazbyron** [comment]
Wrapping up improvements today.
