### ISSUE TITLE
Research improving build time

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#534]
- review previous discussion: https://github.com/cityofaustin/janis/issues/132
- how much we can improve within the current dockerized React-Static
- other options like Server Rendered React 
- Create issue for Tori if we won't be able to improve it for MVP

**Comment by briaguya** [comment]
In my research, I found improvements in react-static version 6 (currently in beta) compared to 5.9.7 (currently in janis).

I ran 3 builds using react-static 6 and recorded the output: https://gist.github.com/briaguya/413a5d3962d1fb0d63ada8659c0e8c84

Results:
```
=> [✓] Dist cleaned (0.1s)
=> [✓] Routes Built (12.4s)
=> [✓] Templates Built (0s)
=> [✓] Public directory copied (0s)
=> [✓] App Bundled (26.4s)
=> [✓] Site Data Downloaded (3.5s)
=> [✓] Route Data Downloaded (0.7s)
=> [✓] Route Data Exported (0s)
=> Exporting HTML across 4 threads...
=> [✓] HTML Exported (197s)

=> [✓] Dist cleaned (0.4s)
=> [✓] Routes Built (14.2s)
=> [✓] Templates Built (0s)
=> [✓] Public directory copied (0s)
=> [✓] App Bundled (31s)
=> [✓] Site Data Downloaded (3s)
=> [✓] Route Data Downloaded (0.5s)
=> [✓] Route Data Exported (0s)
=> [✓] HTML Exported (225.3s)

=> [✓] Dist cleaned (0.3s)
=> [✓] Routes Built (11.8s)
=> [✓] Templates Built (0s)
=> [✓] Public directory copied (0s)
=> [✓] App Bundled (33.5s)
=> [✓] Site Data Downloaded (2.1s)
=> [✓] Route Data Downloaded (0.5s)
=> [✓] Route Data Exported (0s)
=> Exporting HTML across 4 threads...
=> [✓] HTML Exported (199.6s)
```

One of the most interesting things I found was the exporting across x threads line, it seems like we could throw more CPU power at this to speed it up.

This is in comparison to our current builds: https://gist.github.com/briaguya/a8f63c9c718ae1b0ed909cb022af921f

Results:
```
=> [✓] Public directory copied: 3.884ms (0s)
=> [✓] Routes Built: 13966.764ms (14s)
=> [✓] App Bundled: 53099.151ms (53s)
=> [✓] Site Data Downloaded: 2359.677ms (2s)
=> [✓] Route Data Downloaded: 434.939ms (.4s)
=> [✓] Route Data Exported: 17.901ms (0s)
=> [✓] HTML Exported: 11609.663ms (11s)
=> Site is ready for production!: 259818.697ms (259s)

=> [✓] Public directory copied: 1.702ms (0s)
=> [✓] Routes Built: 16147.314ms (16s)
=> [✓] App Bundled: 43387.951ms (43s)
=> [✓] Site Data Downloaded: 2142.653ms (2s)
=> [✓] Route Data Downloaded: 480.596ms (.4s)
=> [✓] Route Data Exported: 16.899ms (0s)
=> [✓] HTML Exported: 16745.250ms (16s)
=> Site is ready for production!: 251126.798ms (251s)
```

It seems as though the improvements aren't too gigantic, but it's worth investigating what throwing more threads at it might bring us. I think we should put a pin in this specific portion of the investigation until react-static 6 launches, at which point we should try super absurd thread numbers against it.

**Comment by briaguya** [comment]
Another idea for a short-term win would be to publish a base janis image to dockerhub, and then instead of:
* pulling the node image
* running yarn to install all dependencies
* building the site
we could simply:
* pull the janis image with all dependencies installed
* build the site
This should also shave a bit of time off the build.

**Comment by briaguya** [comment]
Tried adding 1000 service pages and running a build,
* Joplin timed out (doesn't allow queries against graphQL that take more than 30s by default)
  * Increased timeout to 3000s to allow query to run, still failed
  * Updated query and removed related pages, worked within new giant timeout
* Janis build: https://gist.github.com/briaguya/300c2c1816d93d9ff994a2ea6762eed0
```
=> [✓] Public directory copied: 2.033ms (0 seconds)
=> [✓] Routes Built: 384044.694ms (6.4 minutes)
=> [✓] App Bundled: 42016.778ms (42 seconds)
=> [✓] Site Data Downloaded: 3482.087ms (3.4 seconds)
=> [✓] Route Data Downloaded: 1193.942ms (1.2 seconds)
=> [✓] Route Data Exported: 290.197ms (0.3 seconds)
=> [✓] HTML Exported: 270539.460ms (4.5 minutes)
=> Site is ready for production!: 863482.920ms (14.4 minutes)
```

Learnings:
* Joplin
  * Work to improve query response times
* Janis
  * Move away from querying all pages at once
    * Pagination?
    * Page by page (get all ids and run a query for each)

**Comment by briaguya** [comment]
More ideas about build time improvements:

### Benefits of Static Site Generation:
* If the DB goes down the site is still up
* Very easy to scale (more users isn't a problem)
* Fast load times

### Issues we're facing with react-static:
* Slow build times
  * Incremental builds haven't been figured out

### Ideas:
Move to a nightly build of the static site, find a way to dynamically generate non-static routes, this would allow us to change the process for updating a page to:
* Content editor updates and publishes a page
* That page is moved to a dynamic route until the next build, making time to go-live very fast
* Once the next scheduled static build happens, the page is moved back to being static

I'm not sure how much effort this would take compared to implementing incremental builds, but I'd like to investigate this path.
