### ISSUE TITLE
CMS - Filter home / index of pages by dept/user

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#537]
- Content model based on permissions model
- Actual permissions
- http://docs.wagtail.io/en/v2.1.1/topics/permissions.html

Aha! Link: https://desi1.aha.io/features/RT-270

**Comment by ifsimicoded** [comment]
Filters are available on listing pages using django's modeladmin class prop list_filter --> http://docs.wagtail.io/en/v2.0/reference/contrib/modeladmin/indexview.html

maybe related to #584
