### ISSUE TITLE
CMS - Draft, (Un)Publish, Delete buttons 

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#542]
We should use the same button options as wagtail (since other functions like unpublish/delete will also be needed). Save draft button should be the default with other actions in pull down

In moving these buttons to the top of the page, they aren't there. use the wagtail model (s) for now.

**Comment by toribr** [comment]
The "they" in "they aren't there" is the additional functionality found in wagtail, as seen in this graphic. Submit for moderation will not be necessary until we have actual user roles.
![screen shot 2018-07-19 at 11 21 28 am](https://user-images.githubusercontent.com/3790067/42956584-f3165770-8b45-11e8-8582-3a19518b3932.png)

**Comment by toribr** [comment]
To summarize, there will be three buttons at the top initially: Share | Preview | Save Draft v 

After we get preview into the panel, then only two: Share and Save Draft v

**Comment by briaguya** [comment]
@toribr what about Publish?

**Comment by briaguya** [comment]
@toribr or did you mean the Save Draft button should have a dropdown with:
* Unpublish
* Delete
* Publish
* Save Draft

**Comment by toribr** [comment]
I thought that's what I said. :)

**Comment by toribr** [comment]
Actually, since the menu drops _down_ not _up_ as in wagtail, the order should be 
* Save Draft
* Publish
* Delete
* Unpublish
