### ISSUE TITLE
Use clipboard.js for share link copying

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#544]
Testing in browserstack we found that the current copy text implementation for the share links on the edit page isn't working as well as it should be. @mateoclarke recommended using clipboard.js to mitigate this.

Aha! Link: https://desi1.aha.io/features/RT-268

**Comment by briaguya** [comment]
I'm not sure if clipboard.js works for this. In order to generate the link we need to submit the form and refresh the page. This means that we need to programmatically populate the clipboard without using a click event which is not supported by clipboard.js (https://stackoverflow.com/questions/43235239/copy-text-to-clipboard-using-clipboard-js-without-button)

**Comment by mateoclarke** [comment]
I see, maybe we should change the name of this issue to "Fix copy to share link to clipboard for IE browsers".

**Comment by mateoclarke** [comment]
We don't think this is a priority right now bc we don't have many expected IE users right now. And there is a work around by clicking Previewing copying the url there. Let's backlog until we have more users in departments.
