### ISSUE TITLE
Translation workflow research & design 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#546]
Review the [current translation process](https://docs.google.com/document/d/1kLn7QK3kqMtj6sVGPvf0GhVvugswbLbgO_EGcYERhFw/edit) and determine must/wants/nice to haves for Joplin alpha solution.

**Comment by wilhitem** [comment]
@amenity we probably want to schedule time to talk about this during sprint 12 so that we can start breaking down the work into must/wants/nice to haves.

**Comment by amenity** [comment]
@toribr - would you size this, por favor?

**Comment by toribr** [comment]
I can't until the requirements are more known.

**Comment by amenity** [comment]
Requirements needed that account for translators' workflow/pricing and content team's needs.
