### ISSUE TITLE
Expand and polish Digital Forms for Gov Guide

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#55]
[Digital Forms for Government Guide](https://docs.google.com/document/d/1yPibYRchIriRMNmAmTx4rcfsDyu2vBOHV8J8WPS93fY/edit#) doc

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] Refine outline

- [ ] Summarize key points from web articles

- [ ] Writing
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://desi1.aha.io/features/RT-350

**Comment by ashleecoa** [comment]
Here's my first draft of the Forms Guide: https://docs.google.com/document/d/18u1j8iZj-PFJnrWKYThBUSwK2tOaF0Tnd-BjXI7RGcw/edit?usp=sharing

The last three sections will need staff with certain expertise to expand. Particularly a UX staff person and a Security staff person. Thanks! @amenity @juliazbyron 

Let me know next steps Amenity
