### ISSUE TITLE
Create a Strategic Priority component

### ISSUE THREAD

**Issue by ashleecoa** [cityofaustin/techstack#555]
Add ability for authors to assign a related Strategic Priority to a piece of content

https://austinstrategicplan.bloomfire.com/posts/2760135-city-of-austin-strategic-direction

Aha! Link: https://desi1.aha.io/features/RT-267

**Comment by LauraTrujillo** [comment]
Create issues out of this meeting

**Comment by easherma** [comment]
@oliver2g I don't have a great sense of if this is relevant/important/worth keeping in our medium term backlog?

**Comment by oliver2g** [comment]
@easherma I did some joplin backlog grooming with content today. they'e going to continue discussing potential features and then prioritize them into must-haves for the Janis 2.0 release, must-haves for later, etc. i'll make sure this is part of their discussion. @LauraTrujillo can you make sure this issue gets covered in yall's discussion of the Joplin features you need. If it's not relevant anymore, we can move it to the icebox.

**Comment by LauraTrujillo** [comment]
@oliver2g @easherma 10-4!! Thanks!

**Comment by LauraTrujillo** [comment]
@oliver2g @easherma I'm going to move this to icebox- I don't see a need for this in the future
