### ISSUE TITLE
Draft service page for Reporting Diseases- for healthcare providers and others

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#559]
Current: http://austintexas.gov/department/epidemiology-and-disease-surveillance
Drive: https://docs.google.com/document/d/1Wnlkk88TREr3Ir3CYk_jFd-EeGmGItJgITmu9EBcx7M/edit

**Comment by courtneyjacinic** [comment]
@LauraTrujillo changes suggested!
