### ISSUE TITLE
Draft new service page for "what do to when encountering bats" 

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#563]
Why don't I have access: http://www.austintexas.gov/news/city-reminds-public-what-do-when-encountering-bats
- http://www.austintexas.gov/page/bats
Drive: https://docs.google.com/document/d/1wqyvjkzWeKr6wQFntpk3nvdvk-tskHxjIS175J4fIZo/edit#

**Comment by courtneyjacinic** [comment]
@LauraTrujillo changes suggested!
