### ISSUE TITLE
Draft new service page for Neighborhood Centers

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#565]
Current: http://austintexas.gov/department/neighborhood-centers
Drive: https://docs.google.com/document/d/1zY3seU2FAuZ5deFqZZtQh6_C14GQXWndyOwSgLOV6VE/edit#heading=h.e4san3fgxsj5

**Comment by courtneyjacinic** [comment]
@LauraTrujillo changes suggested!
