### ISSUE TITLE
Draft service page for Tobacco/Smoking Cessation and Prevention

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#566]
Current: http://austintexas.gov/department/tobaccosmoking-cessation-and-prevention
Drive: https://docs.google.com/document/d/1TIZi3sZW_Wee9wHdcZS6b_gOFdGEdnVmjdUTkj9djgU/edit#

**Comment by courtneyjacinic** [comment]
@LauraTrujillo edited!
