### ISSUE TITLE
Draft service page for Walk Texas! Active Austin 10-Week Challenge

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#567]
Combine: chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/http://austintexas.gov/sites/default/files/files/Health/Chronic_Disease/Walk_Texas_-_Benefits.pdf
and
http://austintexas.gov/department/walk-texas-active-austin-10-week-challenge

Drive: https://docs.google.com/document/d/1_7GiFicELWsiEAt8P8ug8NIV_bOAXND2P-sd89uUYgQ/edit

**Comment by courtneyjacinic** [comment]
@LauraTrujillo changes suggested!
