### ISSUE TITLE
Draft event page for WIC cooking classes

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#569]
Current: chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/http://austintexas.gov/sites/default/files/files/Health/MCAH/WIC/WIC_Cooking_Classes__3-17_.pdf

**Comment by desigonz** [comment]
How to deal with this for the transition, since we won't have the event content type yet? Continue to link out to PDF and document the content debt?

**Comment by LauraTrujillo** [comment]
@desigonz Yes, or put it in backlog with an "event" content type label.  And revisit as we develop said content type? That would minimize the content debt.
