### ISSUE TITLE
Update presentations page on project site

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#573]
Let's add these shorter topical decks to [the presentations page](http://projects.austintexas.io/projects/austin-digital-services-discovery/about/presentations/): 
 -   [Iterative Website Rebuild](https://drive.google.com/open?id=1zF74JRkJmwf6wbRjM92-_z-cm8bjTwcqlVgF1Ynelzg)
 -   [Resident-first Content](https://drive.google.com/open?id=16jhYlkjlkl-F_iMDnIrq2_C9f9GNCdhmHXeuY76FRgQ)
 -   [Modular Architecture](https://drive.google.com/open?id=131EYFlpJ08dFzbphwY6S5iA4wWRvKGBhqU7xYfJ4oxA)
 -   [Digital Forms](https://drive.google.com/open?id=1qvIjK3hbQeHo3POiwQAr4vPZUXgGyjlq2AaOuK4I5JM)
 -   [Digital Service Values](https://drive.google.com/open?id=1tXySIrXi0b1PQrbasxUh1Cz_L9EPC1H1_dfWSf1TP0c)
 -  [Open Source City CMS](https://docs.google.com/presentation/d/1CE5dReO81MvKfpje1tH1rsTXf9Y2GgmooyExI1DtVmM/edit#slide=id.g3bb04f3fc3_0_0)

@wilhitem - do you think we should keep all those others up?

**Comment by amenity** [comment]
@mateoclarke - Mind if I add your Linux Fest deck, too? https://docs.google.com/presentation/d/1CE5dReO81MvKfpje1tH1rsTXf9Y2GgmooyExI1DtVmM/edit#slide=id.g3bca1dce1f_1_4402

**Comment by mateoclarke** [comment]
@amenity, just do it!
