### ISSUE TITLE
CMS: Character limits and counting (SEO and elsewhere)

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#575]
**Character limits and counting (SEO and elsewhere)**
While we know the SEO component won't come into play for a while, we do know from previous usability testing that we'll probably need to encourage the user to write more. The arbitrary minimum we have set for now is 150 characters.

Additionally, due to design constraints on the front end, we may have need to limit characters of certain fields. For instance, we may need to limit service page titles.

1) Can we create the pattern now for min and/or max for fields?
2) Ideally, in some instances this should manifest as a active character count (see attached image for example.)
![charcount](https://user-images.githubusercontent.com/3790067/42943668-0680b138-8b29-11e8-9a69-9d1e990833ac.png)

cc/ @toribr

Aha! Link: https://desi1.aha.io/features/RT-262

**Comment by easherma** [comment]
Think this is covered by https://github.com/cityofaustin/techstack/issues/2734
