### ISSUE TITLE
Adjust Style Guide CSS for Mobile/Wagtail Preview

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#576]
- [ ] The style guide embed should use a css file which provide better readability from the panel and is specific to the use of the panel. 

https://github.com/cityofaustin/digital-services-style-guide/blob/master/assets/stylesheets/zilker/variables.scss#L1

**Comment by toribr** [comment]
Closing this as changing the style for Zilker overly complex, and moving towards other options.

**Comment by amenity** [comment]
Met with developers to discuss options and decided that Zilker theme is too complex to be worth restyling. Instead, Chase made a Google Sites version of the guide: https://sites.google.com/view/digital-services-style-guide/introduction
