### ISSUE TITLE
Fix links to published pages

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#578]
There are a few places in Joplin where we have broken links to published pages.

* The message bar when a user hits the publish button
  * This link will be difficult to make work technically, and for MVP it will not be a live link (we need to improve build speeds for this to make sense)
    * In the interim I propose we just remove the link from this message (@toribr I'm hoping you're cool with this as an MVP solution. I also think moving forward it's worth having a discussion around how we want to handle the message bar at the top of wagtail and see if that's something that fits within our overall vision)
* On the list of pages
  * I propose we make these links work

**Comment by briaguya** [comment]
![message bar](https://user-images.githubusercontent.com/6384156/43738750-5523eeca-998b-11e8-9095-25aedce9ed7c.png)
@toribr in regards to what the message bar is, the green thing up at the top here

**Comment by ifsimicoded** [comment]
@briaguya @mateoclarke -- Just an FYI, maybe instead of changing urls everywhere, it would be simpler to extend the Page class and update the url methods -- http://docs.wagtail.io/en/v0.7/core_components/pages/creating_pages.html
```
url
Return the ‘most appropriate’ URL for referring to this page from the pages we serve, within the Wagtail backend and actual website templates; this is the local URL (starting with ‘/’) if we’re only running a single site (i.e. we know that whatever the current page is being served from, this link will be on the same domain), and the full URL (with domain) if not. Return None if the page is not routable.

full_url
Return the full URL (including protocol / domain) to this page, or None if it is not routable
```

**Comment by briaguya** [comment]
@ifsimicoded definitely a good point, we might also look into extending revisions and adding a url to them instead of generating them all over the place
