### ISSUE TITLE
Joplin Alpha: Add a short description component to Service Page

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#580]
The Service Page should have a short description field prior to the steps.

It would be called "Write a description of this service."
 - 250 character limit
 - Optional/required TBD

![service page do-all v 1 switch description](https://user-images.githubusercontent.com/1463708/48722199-13fc2880-ebe9-11e8-95ad-6e032e7ea85f.png)

Mass.gov example:
![screenshot 2018-11-15 12 27 50](https://user-images.githubusercontent.com/1463708/48573754-d76fba80-e8d2-11e8-831d-121caec4ea83.png)

Aha! Link: https://desi1.aha.io/features/RT-259

**Comment by amenity** [comment]
@briaguya @ifsimicoded - size plz. 🙏

**Comment by oliver2g** [comment]
@briaguya this issue has been languishing in the backlog for a while. it appears small, so I'd like to get your thoughts on including it this sprint or next. Moving to the short term backlog for now, but let me know if it fits in the scope of yall's current work or not.
