### ISSUE TITLE
Design specs for URL redirects and deleted/unpublished content

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#581]
When pages are unpublished, the url for that content will no longer exist. We need to determine if users should then be directed to another page or a 404 page

**Comment by mateoclarke** [comment]
Ex: Seasonal pages

If an author changes the slug, do we have the expectation that redirect

**Comment by amenity** [comment]
@toribr @chasechenevert - would like your input on this, but my initial thoughts:

 - In the case of a slug change, e.g. https://austin.gov/articles/ir-request gets changed to https://austin.gov/articles/get-a-copy-of-your-immunizations-record, the former URL should redirect to the new URL. 

 - If a page is deleted or unpublished, the user gets a 404.

**Comment by amenity** [comment]
See https://github.com/cityofaustin/techstack/issues/649.
