### ISSUE TITLE
Content Pages Table Filters - `/admin/pages/`

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#584]
- filter by:
  - All (default)
  - Published
  - Draft
  - In Review
- also make Achieved toggleable. Default to hiding Archived

@toribr, this was a feature for Pearl but we should talk about how/when we prioritize this for Wagtail.

_Originally from https://github.com/cityofaustin/techstack/issues/410_

Aha! Link: https://desi1.aha.io/features/RT-258

**Comment by toribr** [comment]
![screen shot 2018-08-08 at 9 20 55 am](https://user-images.githubusercontent.com/3790067/43843163-7fcb4e54-9aec-11e8-9996-684929df73ee.png)

Updated design

**Comment by ifsimicoded** [comment]
Filters are available on listing pages using django's modeladmin class prop list_filter --> http://docs.wagtail.io/en/v2.0/reference/contrib/modeladmin/indexview.html

**Comment by desigonz** [comment]
old/dupe of #2269
