### ISSUE TITLE
Enable Table Editing Widget in Wagtail

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#595]
Use case is around schedules in APH content.

@toribr might have more ideas around how this plugs in to specific edit pages

https://docs.wagtail.io/en/v2.2/reference/contrib/table_block.html

**Comment by toribr** [comment]
Best I recall it was going to be added via the same "add" function that adds steps. At least at first. It'd be good to at least get it enabled within Wagtail, so I can see how it works. Currently I've only been able to see parts of it via Wagtail documentation.
