### ISSUE TITLE
Update joplin Dockerfile to use base Dockerfile

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#604]
There is currently some copypasta between the local and deployment dockerfiles in Joplin, it'd be great to find a way to use `FROM joplin-base` in our heroku Dockerfile

Aha! Link: https://desi1.aha.io/features/RT-249

**Comment by amenity** [comment]
@briaguya - is this holding anything up? What's your recommendation on when it should be done relative to other issues?

**Comment by briaguya** [comment]
@amenity this isn't holding anything up, it's just a matter of reducing duplicated code
