### ISSUE TITLE
Update 311 services on alpha

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#61]
User Story: A resident has a question about a service, but doesn't know who to contact. They are familiar with 311 and call them.

- Finalize 311 content and UX

- Translate services

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [x] get list of prioritized services from Paul B. and team

- [x] decide between calling it 'Austin 311' or '311'

- [x] work with Paul B. on communicating to other departments that their 311 services will be on alpha site

- [ ] Spanish

- [ ] Vietnamese

- [ ] Arabic
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://desi1.aha.io/features/RT-346

**Comment by amenity** [comment]
@cthibaultatx @ashleecoa - I created a feature for this work called "311 integration" - UX and content to support resident navigation between alpha & 311. This is based on what I read in the description above, but I'm not sure it matches the user story in the issue title.

**Comment by amenity** [comment]
@cthibaultatx @ashleecoa - I believe this is in progress, no?

**Comment by LauraTrujillo** [comment]
311 prioritized services: https://docs.google.com/document/d/1ms8iDsrm28gSFK8B0n1KgxrwJRKastkx80zwMJNQm4E/edit?usp=sharing

**Comment by cthibaultatx** [comment]
@LauraTrujillo probably don't need to have me on this task anymore since the mocks have been implemented

**Comment by LauraTrujillo** [comment]
Translated services: 
[311 prioritized services_Arabic.docx](https://github.com/cityofaustin/techstack/files/1894791/311.prioritized.services_Arabic.docx)
[311 prioritized services_spanish.docx](https://github.com/cityofaustin/techstack/files/1894792/311.prioritized.services_spanish.docx)
[311 prioritized services_Vietnamese.docx](https://github.com/cityofaustin/techstack/files/1894793/311.prioritized.services_Vietnamese.docx)

**Comment by LauraTrujillo** [comment]
"All 311 Services" : 
[All 311 Services.docx](https://github.com/cityofaustin/techstack/files/1928361/All.311.Services.docx)

**Comment by ifsimicoded** [comment]
@LauraTrujillo, based on our slack chat -- 
for the 311 section heading, I need 'Call 311' 'Or' and 'Submit an Online Request' broken up in to 3 separate parts to accommodate links.

**Comment by LauraTrujillo** [comment]
I'm going to work through Simi's instructions to highlight the content and send HTML to translators.
