### ISSUE TITLE
Draft Public Health Presentation for 9/7/18

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#610]
## Proposed deck structure
- Write a complaint about the website
- Explain our solution
- Include any testing results reaffirming choice
https://docs.google.com/presentation/d/1Wx0a-NsCvpCWNrgkU5wRHVsqv9ZHjTBkG6aPDSU7dgk/edit#slide=id.g3c8f7135bf_2_942

**Comment by courtneyjacinic** [comment]
Reviewed! Slide 30 is empty though.
