### ISSUE TITLE
Joplin MVP: Header and Nav design updates

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#613]
Sketch file: https://drive.google.com/open?id=1S5Ida1oIhDDf9R0RGe_sXbdDllkr8Pju

![headernav](https://user-images.githubusercontent.com/1463708/44283616-33676c00-a21c-11e8-82a9-bab53a0fec70.png)

- [ ] Left navigation icons and styling
- [ ] User name styling (#ffffff for now)

**Comment by mateoclarke** [comment]
@amenity @toribr, As I'm reviewing the color choices for buttons and links, I'm afraid our color contrast won't meet accessibility requirements.

Currently Wagtail uses `#43b1b0` for its links and buttons. This also has a contrast ratio of 2.58:1. https://webaim.org/resources/contrastchecker/?fcolor=43B1B0&bcolor=FFFFFF

The two colors I find the the mocks are `#00B6CC` which is worse at 2.45:1 and `#5AC6D3` which is the worst at 2.01:1.
https://webaim.org/resources/contrastchecker/?fcolor=00B6CC&bcolor=FFFFFF
https://webaim.org/resources/contrastchecker/?fcolor=5AC6D3&bcolor=FFFFFF

If we are going to make a deliberate change to the base Wagtail colors, I would like to advocate for doing so in a manner that would improve readability/accessibility and adhere to WCAG AA as a minimal requirement.

This is an example of a color that meets the requirements:
https://webaim.org/resources/contrastchecker/?fcolor=00818F&bcolor=FFFFFF

**Comment by amenity** [comment]
Thanks, @mateoclarke. Agreed that we should adhere to WCAG AA.

**Comment by toribr** [comment]
Yep, you’re right, I’ll get that adjusted.
