### ISSUE TITLE
Joplin MVP: Content Index design updates

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#614]
Sketch file: https://drive.google.com/open?id=1S5Ida1oIhDDf9R0RGe_sXbdDllkr8Pju

![content index](https://user-images.githubusercontent.com/3790067/43917967-4e046d42-9bd7-11e8-8fa9-fe59f5759e93.png)

- [ ] Can remove "move" from "more" button dropdown
- [ ] The "author" column should show the name of the person that authored the page. Currently it's "unknown". (I'm assuming we're not giving everyone a single log-in?)
- [ ] Fix or don't display search until it works -- search will be fixed via issue #583

**Comment by mateoclarke** [comment]
The author column is "unknown" because right now all our data comes from YAML files. That should change soon. No action needed yet.

Search is in progress in #583.

**Comment by ifsimicoded** [comment]
@toribr Effectively the [move permission is the same as the delete permission](https://github.com/wagtail/wagtail/blob/88d5a8cfee653e654a6a86b55ea0a365f3733ed0/wagtail/core/models.py#L1791) -- should both move and delete be removed?

**Comment by toribr** [comment]
@ifsimicoded 

That's weird. Move and delete are the same? I don't see any need for the "move" functionality (at least short-term), but I think it's safe to assume we'll need to delete. Is it easier to keep both then?

Note that delete only should work on pages in an "unpublished" state. 
Please advise if this provides enough clarity.
