### ISSUE TITLE
Joplin Alpha: Share button design updates

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#618]
<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] Share should show short URL

- [ ] Share notification should be styled as below
![screen shot 2018-08-13 at 10 02 31 am](https://user-images.githubusercontent.com/3790067/44040015-07fb8b12-9ee0-11e8-817c-423913d8fb29.png)

- [ ] Though sharing requires the system to save, it would be preferred that sharing NOT invoke the "draft updated" notification, as it is secondary to the action.  (Also, the button shows saving, which is good enough)
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

**Comment by toribr** [comment]
[check.svg.zip](https://github.com/cityofaustin/techstack/files/2416159/check.svg.zip)
