### ISSUE TITLE
Usable URLs for uploaded documents

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#622]
- [ ] Make it so we have nice-looking document URLs

------

This ticket is to serve as a reminder to create usable URLS for uploaded documents. For instance, in the case of a pdf that has been linked, the URL of that pdf should be parsable and readable. Ideally, if it were shortened, it would also lead to a page, not to a 404.

**Comment by desigonz** [comment]
@briaguya reviving this issue!

**Comment by srigdon** [comment]
Hi @toribr! What's still relevant here?

**Comment by toribr** [comment]
@srigdon I don't know! Where is it coming into play? Official documents? Is there a user story we are solving for?

**Comment by Niicck** [comment]
I think this has been fixed within the past 2 years?

**Comment by toribr** [comment]
Closing it.
