### ISSUE TITLE
Get data in joplin prod persisting

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#623]
In order for our content team to add new service pages, we'd like to persist the production Postgres DB so that we don't have to import fixture data each time we deploy.

This will allow the content team to test our production CMS instead of creating YML fixture (aka seed data) files.

@sergiogcx has an idea to move the db in a separate container than the Joplin code.

**Comment by mateoclarke** [comment]
- [ ] replacing our current load data from YML files with just a db snapshot or something similar that allows us to spin up local dev with base data.

**Comment by sergiogcx** [comment]
Data is now persisted in preview, staging and production environments. Closing issue.
