### ISSUE TITLE
Reproduce the Digital Services Guide on Google sites

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#626]
The digital services guide in Github is too limited and complicated to change for use now that the style guide will primarily be seen in the Style Guide panel of the CMS.

This issue will be assigned to Chase.

**Comment by chasechenevert** [comment]
- Design Services Google Site [working file](https://sites.google.com/view/digital-services-style-guide/introduction)
- Design Services Style Guide [notes document](https://docs.google.com/document/d/1QNG2Q6H64gQyHyN_9WDX7Dtj7vcHQFrjude2XoEk4Qs/edit?usp=sharing)
