### ISSUE TITLE
Lo fi design: Joplin Beta sign in page

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#629]
We should customize this background to something appropriate for Austin so City staff are 😄 about signing in. 

![Screen Shot 2018-08-22 at 12.18.32 PM.png](https://images.zenhubusercontent.com/5a81e99a4b5806bc2bc6a146/9e03b6f5-036e-49ac-b0ce-891ea3e7caa2)

- [ ] Name
- [ ] Background image
- [ ] Fields/layout
- [ ] Button...

**Comment by chasechenevert** [comment]
### Sprint 18 plan:
- [ ] Collect CMS login examples
- [ ] Sketch: hand sketch some options
- [ ] Mockup: mockup best options, offer at least 3

**Comment by chasechenevert** [comment]
https://gallery.io/projects/MCHbtQVoQ2HCZcMUWtlNkMhJ/files/MCFp71KCyGHjv-u9E3sJBMn-
