### ISSUE TITLE
Find a stock photo for public health service pages

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#630]
Photos should be free (no copyright) and size large

Should be related to content and give context for the following services:
- [ ] Prepare for public health emergencies: https://docs.google.com/document/d/19CIvm_PpQ06baWnF3BtNLBawLIEZ27ZviAjaFCjEIMg/edit
- [ ] Keep yourself safe around bats in Austin: https://docs.google.com/document/d/1wqyvjkzWeKr6wQFntpk3nvdvk-tskHxjIS175J4fIZo/edit
- [ ] Get immunizations for you and your family: https://docs.google.com/document/d/1CdHeFbMTTUabOuf7qeg6wZh_Zaw8YK52ACuPn-B0M8M/edit
- [ ] Get a copy of your or your child’s immunization record: https://docs.google.com/document/d/1gC5eOWnzxeL_Kwi7FGFFoiQGBE2myShO1QbKam-NPk8/edit
- [ ] Find free condoms and learn other ways to prevent HIV: https://docs.google.com/document/d/1IIAYtVBt9KvMMeAn_VbjvnplZRvtlu7sJbtRLY243Iw/edit
- [ ] Get a birth or death certificate: https://docs.google.com/document/d/1zTCZdgrlDyVbxVKKZl57DglwCqCK1fx7LuEgiiyjp1g/edit?usp=sharing

**Comment by chasechenevert** [comment]
Here's a start with a wide variety of images within a flexible structure: 
- Drive folder: [photo batches_summer 2018
](https://drive.google.com/drive/folders/1IOMwkZxgWPpT6Sr5p4quuJB-2qkS5aoo)

I've made several subfolders within that structure to help drill into specific topics. Feel free to add to this structure. I'll continue to take a little time each day to source new photos. 

cc: @LauraTrujillo
