### ISSUE TITLE
Design CMS "logo"

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#632]
The city seal... can we do better than this? It's illegible.

Add specs to https://github.com/cityofaustin/techstack/issues/764.

**Comment by chasechenevert** [comment]
### Sprint 18 plan:
- [ ] Collect a few CMS logos in the field
- [ ] Collect Austin cultural elements, bootstrapping into Celine’s research 
- [ ] Sketch: hand sketch (crazy 8s)
- [ ] Mockup top 3

**Comment by amenity** [comment]
@chasechenevert - moving to the backlog for this upcoming sprint.
