### ISSUE TITLE
Create COA Base Page Model

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#634]
We're duplicating functionality for each content type. If we created a coa base page model (that inherits from page) from which we inherited our content types from, this duplication can be removed.
This would also facilitate a [custom index/page listing view](http://docs.wagtail.io/en/v2.0/reference/contrib/modeladmin/indexview.html) that we could customize headers, filters and search fields on, instead of overriding the existing templates (which could simplify upgrading wagtail later)

From #418:
  - mainly for testing
  - also with our array of statuses:
    - `drafted`, `in review`, `archived`, `published`, `unpublished`

**Comment by mateoclarke** [comment]
🤷‍♂️
