### ISSUE TITLE
Draft Food Handler Process Page Content

### ISSUE THREAD

**Issue by courtneyjacinic** [cityofaustin/techstack#640]
- [x] select a to-be process page to begin drafting
- [x] create first draft: https://docs.google.com/document/d/1eDUPEAOrlsgLDs8L2cSOMHAwCSbzyyIo2m7fpeKD7Eg/edit

**Comment by ashleecoa** [comment]
I recommend content around Food Manager
http://austintexas.gov/department/food-personnel-requirements
http://austintexas.gov/online-form/food-manager-certificates
