### ISSUE TITLE
Design author interface for Department Page MVP

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#642]
Design: #669 

### MVP 
1. Department Page Title
2. Banner Image
3. Dept name
4. Director's block (added to MVP on 9/11/18)
5. Contact Information
6. What we do here
7. Mission block
8. Popular services (auto-generated)
9. Social media links

### Future releases
10. Places - any locations associated with that dept
11. Highlight block - time-boxed content
Based on discussion on 9/6 with @LauraTrujillo, we're thinking this is a selection of a previously existing content type which gets a particular display, ie, any article, press release, or event could be selected to receive additional attention. Essentially, the highlight widget allows author to select existing content to have a preview display on the page for selected period of time.
  
12. News blocks
This component will have (probably) a one sentence description, link to news (always offsite), and an index page of all instances. 
13. Article 
14. Gallery
15. News/press release

Ben G brought up the issue of reports, and documents that will need to be linked. This should be explored further, but one of the existing component types may suffice, like article, or press release.

Secondary navigation will be required in the case of articles, departments, and press releases, plus an index page for each, as well as a detail page. See draft flow below:
![deptflow](https://user-images.githubusercontent.com/3790067/45426014-93f19980-b660-11e8-8f1e-ef2bfa2582c7.png)

**Comment by amenity** [comment]
@toribr - putting this back in the backlog so you can focus on #551, #675, and #624  in Sprint 14.

**Comment by toribr** [comment]
Forgot: needs wordsmithing for instructional text
- [ ] send to content and revise

**Comment by toribr** [comment]
![edit department page](https://user-images.githubusercontent.com/3790067/45425360-b2ef2c00-b65e-11e8-90e6-8e091506f390.png)
Department page MVP

**Comment by LauraTrujillo** [comment]
@toribr @courtneyjacinic @ashleecoa First round of instructional text:
**Department name**
Don't include Austin in the department title

**What we do**
Give a brief summary of the types of services available to the public. Don't just list them, write for your audience.

**Choose an image for the department banner**
Ensure that it's related to the services you provide

**Mission**
Share your department's mission with the public.

**Mission**
It's recommended that the contact is a resource account that is checked daily.

**Director's photo**
Make sure photo is high resolution and consistent with all other director photos.

**About the director**
Write a brief summary of the director's accomplishments, bio, etc...

**Comment by toribr** [comment]
The department page MVP is done until needed. Marking this issue closed.
