### ISSUE TITLE
Janis shows varied content depending on nav path

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#646]
Progress:
Janis is rendering different content depending on how a user navigates to a particular page.
For example, navigating to http://staging.austin.gov/services/get-immunized directly shows limited content, but navigating via links from http://staging.austin.gov/topics/healthcare-prevention, will show the full content. Utilizing the back arrow will also show full content. Refreshing the page shows limited content.
Screen share below:
![servicepageweird](https://user-images.githubusercontent.com/3039125/44606569-65d81280-a7a2-11e8-9114-12982f7ff47b.gif)

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [x] Reproduce locally

- [ ] Diagnose issue

- [ ] Code up fix

- [ ] Verify fix

- [ ] Clean up code
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://desi1.aha.io/features/RT-237

**Comment by ifsimicoded** [comment]
To add to the mystery -- it seems like the data is passed into the steps component prop -- but is not rendered.
![screen shot 2018-09-23 at 3 18 14 pm](https://user-images.githubusercontent.com/3039125/45933540-fa6d9600-bf43-11e8-9a45-b36b48098375.png)

**Comment by ifsimicoded** [comment]
Props are the same according to the inspector in both missing and rendered states???

![screen shot 2018-09-23 at 3 36 10 pm](https://user-images.githubusercontent.com/3039125/45933691-7f59af00-bf46-11e8-8708-affa5d563eb9.png)

**Comment by ifsimicoded** [comment]
routeinfo also shows correct props.
![screen shot 2018-09-23 at 3 56 18 pm](https://user-images.githubusercontent.com/3039125/45934292-36f3be80-bf51-11e8-99dd-780ccf8e01f9.png)

**Comment by briaguya** [comment]
I think I figured this out!

It happens with "dangerouslySetInnerHTML" so using a parser makes a huge difference.
