### ISSUE TITLE
Design Process Page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#661]
Refine existing designs utilizing [Permittingatx.com](https://permittingatx.com/) (sans overview page) for content. @toribr can explain further.

### Existing research and designs
- [Drive](https://drive.google.com/drive/u/1/folders/11TFsoMi4FgsJMGqscQ4pr-TZxRjYnoch)
- [V1 PDF](https://github.com/cityofaustin/techstack/files/2353944/alpha.austin.gov-processpage-v1.pdf)
- [V2 PDF](https://github.com/cityofaustin/techstack/files/2353944/alpha.austin.gov-processpage-v1.pdf)

### Examples from other gov sites
- [FOIA.gov information request](https://www.foia.gov/request/agency-component/d42a8692-bf5a-4d97-aeee-1389a96a9fba/)
- [WENYC How-To Guides](https://we.nyc/how-to-guides/)

**Comment by amenity** [comment]
Duplicate of #808
