### ISSUE TITLE
Update Service Page Model

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#663]
* needs more than one topic
* should it be an array? or primary & secondary?

**Comment by amenity** [comment]
@briaguya size please? 🙏

**Comment by briaguya** [comment]
Giving this an 8 because we need to update quite a few things in the UI to accommodate for this (especially the new content modal)

**Comment by amenity** [comment]
Cleaning out ancient, probably-no-longer-applicable, issues.
