### ISSUE TITLE
Simplify Department Page mockup for MVP

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#669]
Pare down design from #636 to the MVP elements listed below. Attach to #642 when complete. 
### MVP 
1. Department Page Title
2. Banner Image
3. Dept name
4. Contact Information
6. What we do here
8. Mission block
10. Popular services
11. Social media links

### Future releases
7. Places - any locations associated with that dept
9. Highlight block - seasonal
12. News blocks
13. Director block
14. Article/blog
15. Gallery
16. News/press release

**Comment by amenity** [comment]
@chasechenevert - please attach/link to the simplified mock to #585 #664 #642 when it's complete!

**Comment by chasechenevert** [comment]
Mockup 2.5 for presentation today. It contains the original sketch, MVP, and future release (just look in the nav, top left to switch between drafts)
https://xd.adobe.com/view/0bd95529-38e5-4b65-51f0-413e21e68486-7de8/
