### ISSUE TITLE
Refine design of author interface Steps component

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#675]
Once #650 is complete, the author interface for the steps component will be up for some design love.

**Comment by amenity** [comment]
@toribr - just making sure: You do not think we need this for MVP, correct? What about Alpha?

**Comment by toribr** [comment]
We do need it for MVP. the steps page won't render usable copy in most cases. @chasechenevert made a new design from which I am working.

**Comment by toribr** [comment]
Some visual design tweaks will be needed, but overall this is done.

**Comment by amenity** [comment]
Sweet, @toribr. Would you add a link or upload an image/file here?

**Comment by toribr** [comment]
![edit service page w options](https://user-images.githubusercontent.com/3790067/45960333-a2856c80-bfe1-11e8-9aa7-97788fb94f84.png)

NOTES IN MAGENTA are critical to understanding. Please read them.

**Comment by ifsimicoded** [comment]
@toribr is there an updated design coming from @chasechenevert?
The current Janis [design](https://xd.adobe.com/view/cfb1ac5a-4640-4832-4d44-ad95b6fac902-b980/screen/78cd1913-6f0f-4b44-adaf-36d0964bea5c/Service-death-certificate-mobile-expanded-v1), linked to in our meeting invite, still shows steps nested under options which are nested under top level steps. This structure isn't reflected in the Joplin design (steps aren't nested under options) and multiple levels of step nesting feels really complex. I know we chatted about this, but wanted to verify that the design needs to be updated and that the content team feels like one level of steps is ok for displaying this type of information.

**Comment by toribr** [comment]
His issue for that update is still in progress. 

However, CONTENT AND DESIGN have all viewed this version and agreed that this will work. https://preview.webflow.com/preview/tori-project?utm_source=tori-project&preview=131f616770c538243ea51f57bec6aed4

The notable difference (and i'll have him update ASAP) is that the body copy will all be the same font size, and the word "step" will be removed, and instead use an ordered list.

Please note that options allow both ordered and unordered lists, whereas the basic step only allows unordered, so the rich html menu within the CMS will vary slightly in this regard.

Also, as you and I discussed, any willy-nilly tabbing within a list in either type will not get displayed in Janis, ie, only one level of indenting no matter what.
