### ISSUE TITLE
Sidebar Preview - default states

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#679]
related to https://github.com/cityofaustin/techstack/issues/662

- For edit pages we should let Mobile Preview be the default
- For create pages we should have the Style Guide be the default

Unknowns:
- what do we do for the Mobile Preview on the create page? Until a revision is saved, there is no preview available to display.
https://github.com/cityofaustin/joplin/blob/a48dbc4cccda4f7ac2e1fa0899418ef90cf261c3/joplin/templates/wagtailadmin/shared/sidebar-preview.html#L13
- what is the feasibility/priority of having preview with dynamic updates? @briaguya

**Comment by toribr** [comment]
updated in #784
