### ISSUE TITLE
Promote Joplin staging to Production

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#681]
Once we merge in all the current open PRs, we should go ahead promote what is in staging to prod.

Currently, the `master` branch automatically rebuilds on joplin-staging.
Previously, we were having issues promoting the `master` branch to joplin.

We'll want this to be done for MVP so we can tell users to go to http://joplin.herokuapp.com/

**Comment by amenity** [comment]
@sergiogcx will size/modify/close this issue after decision on deployment process

**Comment by sergiogcx** [comment]
Staging has now been deployed to production. Closing issue.
