### ISSUE TITLE
Joplin Beta: translation workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#682]
Our translation workflow is currently:
1. After English content is finalized, it is emailed to translators.
2. Translators use software — [MemoQ](https://www.memoq.com/en/) or [Trados](https://www.sdltrados.com/) — to translate the content. They can begin by loading a library of existing translations specific to a topic or client.
3. The content team adds the content to Alpha.austin.gov by [_editing YAML files in Github? using Joplin?_].

When we launch Joplin Alpha to City staff, we need to have a strategy in place to ensure that new content will be translated in a timely manner. This strategy might include new policies, procedures, and/or Joplin functionality — or a decision to continue handling translation as we are now for the time being.

Let's do a work session to share knowledge and discuss possible options.

### Notes:
 - [Translation cost per 300 word service page is $53](https://github.com/cityofaustin/techstack/issues/241#issuecomment-377964353).
- @ifsimicoded [investigated sending a full webpage issue](https://github.com/cityofaustin/techstack/issues/326) - resulting in [Translation Workflow](https://github.com/cityofaustin/janis/blob/master/docs/TranslationWorkflow.md).
 - MemoQ can import a number file formats. HTML and XML imports preserve tags which makes translation faster and less error-prone than other formats such as JSON. See also [the API](https://help.memoq.com/8-5/api-docs/wsapi/index.html).
 - When a previously-translated file is imported, MemoQ can detect changes. E.g. if a translator only needs to add a few sentences, that can be done quickly.

**Comment by amenity** [comment]
@ifsimicoded can you add your screenshot of acceptable file types here?

**Comment by ifsimicoded** [comment]
![screen shot 2018-08-30 at 10 08 09 am](https://user-images.githubusercontent.com/3039125/45449497-3114f800-b68a-11e8-9d9b-30fbfabfaabc.png)
![screen shot 2018-08-30 at 10 08 03 am](https://user-images.githubusercontent.com/3039125/45449498-31ad8e80-b68a-11e8-8618-0ef1ab8e9f53.png)

**Comment by gabrielaperezdelaosa** [comment]
I'm carrying over useful data from, but closing, this issue since it has been addressed in issue #4479

See current [translation workflow maps](https://miro.com/app/board/o9J_krWx8QY=)
