### ISSUE TITLE
Joplin MVP: Global elements

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#685]
😃 📖  As a member of the content team, I want a clean and consistent user interface so that I can do my work efficiently.
---

The following issues relate to the Joplin header, sidebar, footer, fonts, colors, global icons...

_[Create a new issue using the bug report template](https://github.com/cityofaustin/techstack/issues/new?template=bug_report.md) and add it to this epic._

**Comment by briaguya** [comment]
Overall this looks good, I think I might add a question:
* Does this prevent a user from completing a task? If so, what task?

This should help with prioritization (make sure everything is functional, then make sure nothing is confusing, then make sure everything looks perfect)
