### ISSUE TITLE
Redesign Wagtail CMS to better support CoA goals

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#69]
Starts with revising/adding/moving functional core to reflect needs of CoA authors/publishers/translators

**Comment by amenity** [comment]
Here are some example ideas for individual issues you could create to breaking this guy down, @toribr :
- **Topic Page Editor** Interface with subtasks like **_Reorder title and theme fields, Make help text a bigger font, Link to Digital Style Guide in sidebar, etc._** 
- **Editor View of Content Dashboard** with subtasks like **_Filter by author dropdown, increase visibility of 'Page Visits' column, etc._**

**Comment by amenity** [comment]
Also,
