### ISSUE TITLE
Create Content Modal: Data in fields and radio buttons don't clear on "close"

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#696]
**Describe the bug**
If a user enters data or makes any selection but closes the modal prior to completing the process, then the next time the user opens the modal the previous selections are shown.

All fields should be cleared upon "Close".

**Details**
  - URL:
  - Device: _E.g. desktop/laptop, tablet, or phone_
  - Browser: _Use [browser info](https://www.whatismybrowser.com/) if you are unsure_ 

**Current behavior**
If user begins to create new content but closes the window before finishing, the next time the user opens the create content modal the previous selections and states will show.

**Expected behavior**
If user closes the modal before finishing, the modal should reset to the beginning.

**To Reproduce**

**Screenshots**
If applicable, add screenshots or a gif to help explain your problem.

**Additional context**
Add any other context about the problem here. Does this prevent a user from completing a task? If so, what task?

**Comment by amenity** [comment]
QA at https://joplin-staging-pr-168.herokuapp.com/
