### ISSUE TITLE
Thumbnails don't preview

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#697]
**Describe the bug**
Thumbnails within edit mode and within image gallery are not previewing correctly but show broken link. However, newly uploaded images do upload and preview.
![screen shot 2018-09-12 at 11 52 17 am](https://user-images.githubusercontent.com/3790067/45502906-dbeceb00-b74a-11e8-8d44-12d4300b22eb.png)

**Comment by amenity** [comment]
Might be addressed by @sergiogcx changes in #471 .

**Comment by amenity** [comment]
Duplicate of #598
