### ISSUE TITLE
Mobile preview render: repress language picker bar

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#698]
**Describe the bug**
Repress the language picker on mobile preview, as it's not needed in this context
![screen shot 2018-09-13 at 11 57 48 am](https://user-images.githubusercontent.com/3790067/45503473-887b9c80-b74c-11e8-80f1-71fb1d58f20b.png)

Aha! Link: https://desi1.aha.io/features/RT-226

**Comment by amenity** [comment]
Going to use hacky CSS to hide element.
