### ISSUE TITLE
Character limit micro-copy changes

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#701]
**Describe the bug**
On the page title screen, prior to typing the character limit label reads: character limit. After a user begins to type it changes to " characters remaining".

All instances should read: "characters remaining"

![screen shot 2018-09-14 at 7 31 58 am](https://user-images.githubusercontent.com/3790067/45550482-908d1800-b7f0-11e8-8d50-b177e950029e.png)
![screen shot 2018-09-14 at 7 34 13 am](https://user-images.githubusercontent.com/3790067/45550496-9aaf1680-b7f0-11e8-8e79-332b8082ea81.png)

**Details**
  - URL:
  - Device: _E.g. desktop/laptop, tablet, or phone_
  - Browser: _Use [browser info](https://www.whatismybrowser.com/) if you are unsure_ 

**Current behavior**
A clear and concise description of what happened.

**Expected behavior**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or a gif to help explain your problem.

**Additional context**
Add any other context about the problem here. Does this prevent a user from completing a task? If so, what task?

**Comment by toribr** [comment]
This looks right for the service page selection but the same bug exists for the process page. Seems like it would make sense to fix both? @briaguya

**Comment by amenity** [comment]
QA at https://joplin-staging-pr-168.herokuapp.com/
