### ISSUE TITLE
Medium post | Part II of Mateo's Part I Open Source City CMS

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#712]
Assigning the whole dev team. Y'all talk amongst yourselves about who wants to write it and let me know.

**Comment by sergiogcx** [comment]
I can't think of amore indicated person to write about the CMS than @briaguya. He would know the lessons learned and the entire context behind Django/Wagtail.

I am also happy to write it if needed be :)

**Comment by easherma** [comment]
We could write about our experience going to the Wagtail conference
