### ISSUE TITLE
Medium post | Alerts 

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#718]
Thinking about how governments are alerting their residents using Hurrican Florence as an example. This came out of a conversation between Chase and I about a suicide prevention/design challenge article: https://uxdesign.cc/preventing-suicide-the-modern-way-86a816e2bf07

Survey of cities on coast: what systems are they using
Designing:
- text
- error page
- alert

- How atxfloods, etc... are communicating

Aha! Link: https://desi1.aha.io/features/RT-211

**Comment by chasechenevert** [comment]
Just cleaning up a little bit. We can revisit after we've implemented if we have anything of value to add to the dialogue.
