### ISSUE TITLE
Create specs for Service Page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#724]

**Comment by chasechenevert** [comment]
I'd like to sit with Devs to look at this and see if it meets their needs, but I know we're a ways off from them getting to this.

https://xd.adobe.com/spec/9223bc26-57ed-4053-68bc-5496c5232e14-e412/#access_token=eyJ4NXUiOiJpbXNfbmExLWtleS0xLmNlciIsImFsZyI6IlJTMjU2In0.eyJpZCI6IjE1Mzg2NjE2NzgyMjNfZjg0ZmI0OWYtYzRlMS00YTdiLWE2MjktOTYwYjA4NTMyNDAwX3VlMSIsImNsaWVudF9pZCI6IkNvbWV0V2ViMSIsInVzZXJfaWQiOiIxNzM5NEYzMDRFODNGMDdCMEE0OTBENDVAQWRvYmVJRCIsInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJhcyI6Imltcy1uYTEiLCJmZyI6IlMyRjdRQTQyWFBOMzdIRzZTNEFBQUFBQTNVPT09PT09Iiwic2lkIjoiMTUzNjk1MDkyODAxOV82ZTM5MTI1ZS03ZjRkLTQ4MTctYjg1My05Zjc0MjMwZmUwN2ZfdWUxIiwibW9pIjoiZTQ5MWZkMGEiLCJjIjoiQzJoNmN5R2piYnRRd3hvK1ZhcFdSQT09IiwiZXhwaXJlc19pbiI6Ijg2NDAwMDAwIiwic2NvcGUiOiIiLCJjcmVhdGVkX2F0IjoiMTUzODY2MTY3ODIyMyJ9.E2ktUNw44L5qM6uOEyLOn1Jk0m4zJgu33JNITBwrwgOApuzrLmENhdXmxp4ylxfexIY-IbAlTBhtqzcxU0s3kFaHsar4qN6wEdGy3KmGxZHZHF54uThqOL1HwRZHhthWx1tVlIlM1PY_aucWRollH089o_AweqE-Q6L_JRsbeeLMe-pNQwhlv5qVd4ORr2dbPDKc-lsvbcj227amK4716z6epjKcCHO6v4SF1ehGeap6-h6kPOBw6UKX8csz9R-Ipf0jSt73EKNflV6TGYYt9OHnB3EtBbNNy5F-aGHMYPtp02Y86ZPY8v1NKKgHJh881QDYbgaOhbgHMBwFg_iM_g&token_type=bearer&expires_in=86399991

**Comment by amenity** [comment]
So rad, @chasechenevert! Excited to see how this supports & expedites the dev<-->design workflow.👩🏾‍💻⬅️ ❤️ ➡️👨🏽‍💻 **design** 👨🏻‍💻👨🏻‍💻👨🏻‍💻
