### ISSUE TITLE
Solve steps component for author interface

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#728]
We don't want authors to create indents in the steps component. We can't keep them from hitting the tab key on their keyboard, but how can we prevent that action from from showing in the WYSIWYG?

Current Janis Mockup: https://xd.adobe.com/view/0bd95529-38e5-4b65-51f0-413e21e68486-7de8/

**Comment by ifsimicoded** [comment]
A steps component contains two possible modules to use: basic steps or options. (the UI for switching may change - this version  uses radio buttons.)
Steps have a single text component which allows bullets or lists, and links. (tabbing within this component and the display issues it creates still needs to be resolved). The options module requires a title, which serves as a link, and a text module which works the same as the basic steps module, and is the part that is hidden/revealed.
![screen shot 2018-09-19 at 11 11 08 am](https://user-images.githubusercontent.com/3039125/45833050-810e4300-bcb8-11e8-9227-8f93a451af37.png)

**Comment by ifsimicoded** [comment]
preventing indents from rendering on janis would suffice
number the steps for the user in the author interface

**Comment by amenity** [comment]
Duplicate of #676
