### ISSUE TITLE
Create Production branch for Travis Deployments

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#730]
Master deploys to staging
Prod deploys to prod

**Comment by sergiogcx** [comment]
These are the notes we have from our meeting:

![board_1](https://user-images.githubusercontent.com/5282430/45833525-7197f580-bcca-11e8-8bc4-69e3ab77971e.jpg)

![board_2](https://user-images.githubusercontent.com/5282430/45833549-807ea800-bcca-11e8-9729-b68a2124da0d.jpg)

As discussed, we already have the production branch. The Travis pipeline has been coded in a way that it is ready to handle these deployments, we simply have to run the first couple deployments on staging and make sure nothing breaks there. Once everything runs smoothly on staging and we have enough observations, we can make the deployment for production.

**Comment by sergiogcx** [comment]
The production branch has been adapted in our Travis deployments. Closing issue.
