### ISSUE TITLE
Document all the devops things

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#734]
Get as much stuff into the readme as possible. 

- [x] deploy pipeline / TravisCI processes and Heroku processes - https://github.com/cityofaustin/joplin#deployments-with-travis-ci
- [ ] branching strategy for staging and production environments
- [ ] Review app URL structure for Janis and Joplin
- [ ] Create docs file in repo and add ☝️

**Comment by amenity** [comment]
Closed, per Slack convo with Sergio.
