### ISSUE TITLE
Typos in topics

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#746]
**Describe the bug**
Typo's
1. Lots and found (should be: Lost and found)
2. Health Records and Certificates (should be: Health records & certificates)

**Screenshots**
![screen shot 2018-09-21 at 1 43 07 pm](https://user-images.githubusercontent.com/3790067/45900092-51d50000-bda4-11e8-95be-1b55fd46ef1e.png)
![screen shot 2018-09-21 at 1 43 55 pm](https://user-images.githubusercontent.com/3790067/45900109-687b5700-bda4-11e8-8303-b8a8a58c4640.png)

Aha! Link: https://desi1.aha.io/features/RT-201

**Comment by amenity** [comment]
@briaguya - I'm putting this in the backlog for now.
