### ISSUE TITLE
Improve look of drop down button

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#747]
**Describe the bug**
Button displays weirdly

**To Reproduce**
1. Go to 'save draft
2. view pulldown
3. See error

**Current behavior**
![screen shot 2018-09-25 at 11 38 59 am](https://user-images.githubusercontent.com/3790067/46029001-c1eec900-c0b7-11e8-83ab-26811e1a08a4.png)

When selecting publish the button should display full width.

**Expected behavior**
Button should display full length of button width of save draft.

**Screenshots**
If applicable, add screenshots or a gif to help explain your problem.

**Details**
  - URL: any edit page
  - Device: _E.g. desktop/laptop, tablet, or phone_
  - Browser:  chrome

**Additional context**
Add any other context about the problem here. Does this prevent a user from completing a task? If so, what task?

Aha! Link: https://desi1.aha.io/features/RT-200

**Comment by desigonz** [comment]
@chasechenevert I found issue #834 ... may or may not be relevant to you. If it's no longer relevant, close the issue!
