### ISSUE TITLE
update recruitment postcard for bilingual testing

### ISSUE THREAD

**Issue by aineeathar** [cityofaustin/techstack#76]

**Comment by aineeathar** [comment]
suggested:

Do you speak Spanish, Vietnamese, or Arabic?

The City of Austin is looking for bilingual residents to give feedback on new online services! All participants get HEB gift cards.

Sign up: tinyurl.com/marchwebtest

**Comment by LCTrujillo** [comment]
https://drive.google.com/drive/folders/1w6PAEDRQCyswYNACBQwNsTNIXn5xkVIt
![translation recruiting flyer](https://user-images.githubusercontent.com/30263897/36600331-8f22e954-1877-11e8-8846-1742d115b54b.png)
