### ISSUE TITLE
Determine strategy for Alpha forms 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#770]
Alpha-forms.austin.gov
 - Do we have an index page, redirect to the project site/alpha, or...?
 - What is the path by which a user goes to and from a form on Alpha-forms? 

Scope of implementing Knack ATD RPP prototype on Alpha
 - Service/Process Page - content team
 - Basic style specs - design
 - Implementation - dev
 - ...

Next up?
 - Police Monitor
 - Foster Application
 - Food Handler

Prioritization & staff time

**Comment by amenity** [comment]
Alpha-forms.austin.gov
 - Do we have an index page, redirect to the project site/alpha, or...? 
_Standalone._
 - What is the path by which a user goes to and from a form on Alpha-forms? 
_Will bring forms over to Alpha site when they are ready.

Scope of implementing Knack ATD RPP prototype on Alpha
~Service/Process Page - content team~
 - Basic style specs - design
 - Implementation: 
    - Mateo 
 - ...

Next up:
 - Police Monitor - A

Considerations:
 - Review RPP prototype with content and design
 - 

Prioritization & staff time
Design: Chase, 1 hour 
     - [Knack prototype](https://atd.knack.com/parking#home/)
     - Basic header with City of Austin and links to other ATD services, beta disclaimer; like [Permittingatx.com](https://permittingatx.com/)*
     - Styles on Knack components
     - Page layout, background color, etc.

**Comment by benguhin** [comment]
🎉

**Comment by amenity** [comment]
Opting to embed the form in Alpha.austin.gov. This means Mateo will make a branch of Janis to build the form in, then pull in Chase in a future sprint for design love. 

**Benefits**

- We don't have to create a new repo and make technical decisions, e.g. "What framework should we use, `create-react-app`, Jekyll, something else?"
- We don't have to wait on CTM to implement a new DNS configurations
- Gets a second department on Alpha, and sets the precedent for lots more ATD things there
- Most importantly: We'll learn quickly how the Knack JS plays with React static Austin.gov
