### ISSUE TITLE
Produce specs for Department Page MVP

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#775]
Mobile + Desktop

Add to https://github.com/cityofaustin/techstack/issues/815 when complete.

**Comment by chasechenevert** [comment]
As a supplement to the XD specs for Devs, I'm pulling out specific changes to components to help clarify where changes have been made (especially to the CSS).

Doc: [Spec supplement for Department and Service pages](https://docs.google.com/document/d/1TtX4fJoQfvwdJnPmUpYI1Fzyqf2rmC6CJsEKnfqCYhE/edit#)
