### ISSUE TITLE
Discovery for Process Page design

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#776]

**Comment by chasechenevert** [comment]
##Debrief
Design met with Content to learn from their process and discoveries. Content flagged a number of design issues to think through. I better understand the scope of Process pages and that this is a big deal in the way users will be able to navigate complex city processes. 

**Process document**: [Process Page Template_V1](https://docs.google.com/document/d/1h6uRCwyGN8IiavZn8k32a52BOrmvLwfHh7moOgWz6mA/edit?usp=sharing)

##Inspiration
- [NYTimes Four Square Blocks](http://archive.nytimes.com/www.nytimes.com/interactive/2013/10/10/garden/philadelphia-design.html) for the way the left-hand nav snaps as you scroll, and contains anchor tags. No mobile experience
- [Polygon PS4 Review](https://www.polygon.com/a/ps4-review/video_review) slides out on mouse-in. No mobile experience.
- [Dropbox Guide](https://www.dropbox.com/guide) multi-pane experience  with a fixed left-hand page and right scroll; stacks on mobile. Feels like a workbook, which could be suitable for this context.
- [FOIA](https://www.foia.gov/request/agency-component/d42a8692-bf5a-4d97-aeee-1389a96a9fba/) lefthand nav along with anchor links and other helpful information. The glossary is a nice feature.
