### ISSUE TITLE
Mobile preview within CMS does not render images

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#785]
![screen shot 2018-10-03 at 12 44 51 pm](https://user-images.githubusercontent.com/3790067/46428942-dd3a8380-c70a-11e8-9efb-5e0e9eb87643.png)

The user should be able to see the images that have been added to their page in mobile preview panel so that they can author confidently.

**Comment by sergiogcx** [comment]
Simi and I were discussing this issue during design-dev/sync yesterday, it appears it is an environment variable that needs to be changed. 

Current URL:
https://joplin-staging.herokuapp.com/media/
Needs to change to:
https://joplin-austin-gov.s3.amazonaws.com/media/

Once changed, the result should be something like this:
https://joplin-austin-gov.s3.amazonaws.com/media/images/lady-bird-lake.width-640.jpg

<img width="1243" alt="janis-staging_ _settings___heroku" src="https://user-images.githubusercontent.com/5282430/46433959-d2d2b680-c717-11e8-8dfb-0f4b67a77c46.png">

The instance may need to be rebooted for the changes to take effect, I can do it but I would prefer if someone is looking over my shoulders in case it breaks. 

@briaguya @ifsimicoded
