### ISSUE TITLE
Initial planning for Janis v2 release

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#788]
To be kept in separate branch  - v2 release

https://xd.adobe.com/view/f858965b-0df2-44fc-54ee-324d8ce6d342-8e69/
- Make a list of all components/component groups, e.g. _map_, _menu_, _footer_
- Make issues for implementing each ☝️ 
- Work with Chase and create design issues for any outstanding specs

**Comment by ifsimicoded** [comment]
Meeting 10/23
### Service Page
- Recollect Third Party App - needs design work
- Map - needs design work (currently a placeholder in the mock)
- Multiple Contacts? - still up for conversation, but one at the moment
- No images at the moment to keep content focused - but up for conversation in the future

### General Styling
- USWDS integration 
	- [ ] Chase will review the following USWDS2.0 packages for parity with mocks
	- [ ] Simi will use USWDS2.0 and remove 1.0
	- spacing 
	- typography
	- color 

- Revisit Breakpoints
	- [ ] Chase will review breakpoints to determine pixel max or min widths as needed with uswds constraints in mind
	- Considering adding tablet width

### Other components

#### Main navigation needs design
- general nav experience on mobile and desktop
- Mobile nav expanded and closed states?
- subnav Pop-out state on desktop?

#### Translation bar needs design
- @amenity Are we still considering translations as an MVP feature?
(If so, we’ve been neglecting it on the Joplin-side)
- Needs to fit 4 main languages, I think, if so?
- Consider for both mobile and desktop

**Comment by ifsimicoded** [comment]
I'll also review components as they're made and have @chasechenevert QA them in storybook for 1 round of revisions.

**Comment by mateoclarke** [comment]
Hey friends, I was talking today about how we might want to use some CoA design standard approved components for our work at ATD. Don't want to blow the scope but would y'all be open to the idea of packaging the v2 components as an npm module? I could probably contribute to that effort.

**Comment by briaguya** [comment]
@mateoclarke I really like that idea! Speaking of blowing the scope, that could be a perfect opportunity to move to importing styles into components instead of building one giant stylesheet.

**Comment by amenity** [comment]
@ifsimicoded Re:translations: We want site content fully translated before moving to beta.austin.gov, e.g. when we expose the site to search engine indexing and invite/redirect Austintexas.gov visitors. That's post Janis v2, and Process Page MVP. It's looking like Process Pages are complicated enough that we won't want to expose them to non-admin/author/staff roles. So instead of designing and building a beautiful Joplin Process Page template, @toribr & a backend dev can dig into translation during those sprints.

**Comment by ifsimicoded** [comment]
@briaguya we went with a manifest approach for base styles for several reasons (one of which is our styles are setting a holistic brand for the whole page with components shared across pages -- so there won't be many situations where we have only component specific styles). I think a more blended approach with base styles in a manifest and more component specific styles could work.  Happy to work down a path you think makes sense, but I'll be following the pattern we've already set for now.

**Comment by ifsimicoded** [comment]
@mateoclarke definitely up for doing research for this, but I'll be working simply on rebuilding our storybook components for the short term.

**Comment by amenity** [comment]
@ifsimicoded - is this completed to your satisfaction? 💁

**Comment by briaguya** [comment]
@ifsimicoded I was definitely thinking about a blended approach. I just know our current strategy could lead to the steps component styling being included in a giant bundle when it'd be nicer to include the base styles for headings/text etc. in our steps bundle.
