### ISSUE TITLE
ATX.gov to Alpha.austin.gov -- Create Content

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#79]
create text content for ATX.gov to Alpha.austin.gov UI component/banner link
- [ ] Create any transition notifications for ACC/Alpha

**Comment by LauraTrujillo** [comment]
- [ ]  Discuss options with Ashlee
- [ ]  Style with Celine
- [ ] Deployed by Ben

Deployed by Ben

**Comment by amenity** [comment]
Closing for now, see https://github.com/cityofaustin/techstack/issues/82.
