### ISSUE TITLE
Janis builds fail when an unpublished page doesn't fit requirements

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#791]
I tried unpublishing a page that was causing the janis build to fail and it ended up failing on the same error as it did before unpublishing it. Deleting the page solved the issue. We should implement logic to make sure we don't try to build pages that aren't live, especially considering we are going to have logic that allows content editors to save drafts of pages that don't meet all of the requirements for going live.

**Comment by amenity** [comment]
@briaguya Does this mean an unpublished page that is missing required fields will break _all_ Janis builds? In #759 I was able to mess with up-to-par pages and, it seemed, successfully rebuild — despite the presence of a non-compliant page in the database.

**Comment by amenity** [comment]
Need this for MVP - breaks _all_ builds.

**Comment by briaguya** [comment]
@amenity I wasn't able to reproduce this issue with any of the pages in master after removing absolutely every piece of data from pages.

What I did find was that we aren't respecting the "unpublished" flag, and are building the site with unpublished pages.

I think the best course of action is to update this on the joplin side so we can choose if we want to get unpublished pages when querying the API. However, unless we find that this is still breaking the build post whatever changes exist in master that we don't have on staging at the moment, I don't think it needs to be MVP.

**Comment by amenity** [comment]
@briaguya - cool, thanks! I'll leave this here & labeled MVP until we've got the PRs merged and deployed on staging.

**Comment by briaguya** [comment]
Tested on staging, seems to be fine. (unfinished and unpublished page still appears, but it doesn't break the build)
