### ISSUE TITLE
Write content for government and business theme page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#798]
Aha! Link: https://desi1.aha.io/features/RT-181

**Comment by LauraTrujillo** [comment]
@JeffCopy here's an example: https://alpha.austin.gov/themes/housing-utilities

**Comment by JeffCopy** [comment]
Ready for review.
Given brevity, maybe just one reviewer @LauraTrujillo ?
https://docs.google.com/document/d/1O3X-9bbutgB6cGgPSGytYCuoRmWQA0KJaZbsyhIZ5vM/edit

**Comment by LauraTrujillo** [comment]
looks great!
