### ISSUE TITLE
Restyle storybook components

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#800]
Comb through the [Storybook](http://staging.austin.gov/storybook/?selectedKind=Trashy&selectedStory=Schedule%20component&full=0&addons=1&stories=1&panelRight=0&addonPanel=intl%2Fpanel) and restyle components.

Reference [USWDS](https://v2.designsystem.digital.gov/components/).

**Comment by amenity** [comment]
Covered by [Janis 2.0 label](https://github.com/cityofaustin/techstack/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Janis+2.0%22+).
