### ISSUE TITLE
Process Page work session

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#812]
@toribr began working on @ashleecoa's process page, _[Start a food truck or mobile food business](https://docs.google.com/document/d/1VCL-BZKzL9axkZtQVqrMAdmkkUSt2SYppjFulOkIEcE/edit)_ and found it exceedingly complicated. She compiled a [table of the paper documentation](https://docs.google.com/document/d/1lK-67reUVzRIkb2A6xr-49eTbSyHan4Swy88tIBBEI8/edit) required to open a mobile food business based on business type and City/County restrictions. 

How might we provide residents with this information? How might we further simplify the process?

**Comment by amenity** [comment]
Remapping what's on the Ashee's current pages to break out into components and see how we can use a decision tree like workflow for the user. 

Should also choose a simpler use case to design with in parallel.

**Comment by chasechenevert** [comment]
### ODD Flock Winter Wonderland edition 
![img_20181016_143937](https://user-images.githubusercontent.com/7027270/47101507-e265fb00-d1ff-11e8-9b19-4975b2c6cc9b.jpg)
![img_20181016_143941](https://user-images.githubusercontent.com/7027270/47101508-e265fb00-d1ff-11e8-9665-8f6cbc6fbfbd.jpg)
![img_20181016_145706](https://user-images.githubusercontent.com/7027270/47101509-e265fb00-d1ff-11e8-9e75-90ea803333e1.jpg)
![img_20181016_145711](https://user-images.githubusercontent.com/7027270/47101510-e2fe9180-d1ff-11e8-9e77-0ce6baac8e5d.jpg)
![img_20181016_145712](https://user-images.githubusercontent.com/7027270/47101511-e2fe9180-d1ff-11e8-9122-70f2caebbee4.jpg)
![img_20181016_145719](https://user-images.githubusercontent.com/7027270/47101513-e2fe9180-d1ff-11e8-9ed7-772b21ae6615.jpg)
