### ISSUE TITLE
Process Page content type

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#821]
During Sprints 16 and 17, the team attempted to define the Process Page content type using [mobile food permit content](https://github.com/cityofaustin/techstack/issues/827). We determined that processes that complex would be best-served by a wizard-like interface; a la Turbo Tax or [GOV.UK's Step-by-step](https://www.gov.uk/learn-to-drive-a-car). We do not currently have the engineering resources necessary to building out that content model and functionality, nor the service design resources we would need to ensure they're executed effectively.

So the Process Page content type is going back in the backlog for the time being. When it's picked back up, check out:
- [Early content model](https://github.com/cityofaustin/techstack/issues/396)
- [Notes on GOV.UK's Step-by-step](https://github.com/cityofaustin/techstack/issues/833)
- [Work session with mobile food content](https://github.com/cityofaustin/techstack/issues/812)
- [Refine process page for How to Start a Mobile Food Business](https://github.com/cityofaustin/techstack/issues/827)
- [@chasechenevert's initial designs](https://github.com/cityofaustin/techstack/issues/774#issuecomment-430666976)
- [Callout/Quote component](https://github.com/cityofaustin/techstack/issues/400)

**Comment by desigonz** [comment]
Closing this; guides (#1736) are replacing process pages
