### ISSUE TITLE
Refine process page for How to Start a Mobile Food Business #504 

### ISSUE THREAD

**Issue by ashleecoa** [cityofaustin/techstack#827]
https://docs.google.com/document/d/1VCL-BZKzL9axkZtQVqrMAdmkkUSt2SYppjFulOkIEcE/edit?usp=sharing

**Comment by LauraTrujillo** [comment]
![img_4882](https://user-images.githubusercontent.com/30263897/47298697-0d749400-d5de-11e8-8857-32794873d446.jpeg)
![img_4883](https://user-images.githubusercontent.com/30263897/47298699-0e0d2a80-d5de-11e8-9e69-6dd2bc532323.jpeg)
![img_4884](https://user-images.githubusercontent.com/30263897/47298700-0e0d2a80-d5de-11e8-9d3e-e2958532c1e9.jpeg)
![img_4885](https://user-images.githubusercontent.com/30263897/47298701-0ea5c100-d5de-11e8-89e9-aac20b5bcafc.jpeg)
![img_4886](https://user-images.githubusercontent.com/30263897/47298703-0fd6ee00-d5de-11e8-8079-b69f9761c7dd.jpeg)
![img_4887](https://user-images.githubusercontent.com/30263897/47298704-106f8480-d5de-11e8-9aeb-4a17fa1080e1.jpeg)
![img_4888](https://user-images.githubusercontent.com/30263897/47298705-11081b00-d5de-11e8-810c-f9551fa7eae5.jpeg)
![img_4889](https://user-images.githubusercontent.com/30263897/47298708-11a0b180-d5de-11e8-8439-bff1ecd39574.jpeg)
![img_4890](https://user-images.githubusercontent.com/30263897/47298711-12d1de80-d5de-11e8-899d-1aa0677c005d.jpeg)

**Comment by amenity** [comment]
[Putting Process Page back in the ol' backlog](https://github.com/cityofaustin/techstack/issues/821).
