### ISSUE TITLE
Define process that documents functional Janis+Joplin versions

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#832]
* How do we want to handle versions?
* What versions of Joplin work with what DB backups?
  * What does our naming structure for backups look like?
  * Can we make Joplin "backwards compatable" with old backups?
  * Any extra automation opportunities here?
* What versions of Janis work with what versions of Joplin?

**Comment by oliver2g** [comment]
@easherma assigning this to you for now and adding it to the upcoming sprint backlog. lemme know if you think otherwise

**Comment by easherma** [comment]
@oliver2g this is most closely related to what @Niicck has been working on. I'd be happy to collab with him on it + documenting
@briaguya was the one who originally wrote the bullet list above

**Comment by oliver2g** [comment]
@easherma sounds good. Can you reference the issue @Niicck  is working on? Feel free to close this one if it's redundant.

**Comment by easherma** [comment]
adding sergio since this is basically all doc writing
