### ISSUE TITLE
Clicking "create" page button while waiting for server response creates duplicate pages

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#835]
**Describe the bug**
When creating a page, and the create button is clicked, nothing visually happens on the page (for a second or so, which is WAY too long) to indicate the system is working. If the user again clicks the create button, then an additional instance of the page is created. Since there is no affordance for deleting the pages in this build, then additional pages with the same name may create a lot of confusion.

**Comment by briaguya** [comment]
Will be resolved via #743
