### ISSUE TITLE
Production Janis builds against staging Joplin

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#839]
**Describe the bug**
Production Janis builds against staging Joplin DB when a page in production Joplin is published.

**To Reproduce**
1. Publish a page in joplin.herokuapp.com
2. A new alpha.austin.gov build is triggered using the staging DB

We have a few issues causing this:
* Janis master uses environment variables in Dockerfile.build which we cannot set/override using config vars in heroku, so they're only pointing to one place.
  * I tried addressing this with a quick workaround by making a "prod" branch of Janis, and it worked when I manually deployed with the new env vars, but.....
* Joplin uses a hardcoded value to deploy a new build to heroku ([JANIS_SLUG_URL](https://github.com/cityofaustin/joplin/blob/ff7ceacffb901b7d848dc79f0e470096f2202ce6/joplin/base/signals.py#L23)), which is always pointing to master. Which means that we are always going to deploy master when this trigger is hit.

Possible solutions:
* Update the trigger in Joplin to deploy prod for prod and staging for staging
  * This would leave us in a position of needing to manage a different branch for prod janis than staging Janis (maybe not the worst thing)
* Update Janis to correctly deploy master with different vars for prod/staging

Other side effects:
* Google Analytics vars not getting set properly

**Comment by amenity** [comment]
Per Slack discussion, going with a quick fix: Update Joplin trigger so prod Joplin deploys prod Janis.

**Comment by briaguya** [comment]
I have a pull out to fix this: https://github.com/cityofaustin/joplin/pull/185
