### ISSUE TITLE
Janis v2 Design: Service Page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#851]
Aha! Link: https://desi1.aha.io/features/RT-164

**Comment by chasechenevert** [comment]
## Visual design: Service pages

<img width="1334" alt="Screen Shot 2019-04-04 at 10 14 51 AM" src="https://user-images.githubusercontent.com/7027270/55567063-94b45080-56c2-11e9-9b2d-0cfdda54a0ba.png">

### Dev specs
- [Desktop](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/ce9e7492-b75b-472c-9dab-98d7bd1843ba/Service-MVP-Web/)
- [Tablet](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/340b1739-563b-406f-8ea6-6abdc54e855f/Service-MVP-Tablet/)
- [Mobile](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/51aa2fb9-cba8-4f59-a726-f8be07fb39ff/Service-MVP-Mobile/)

### Notes
- These comps include the sub-navigational elements (light blue horizontal bar that sits below the global navigation, and above the page title
- Sub-nav elements "offered by" and "related to" appear within the bar on desktop, but move to the bottom of the page just before the footer on tablet and mobile
