### ISSUE TITLE
Janis v2 Design: breakpoint exploration

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#852]
Work on meeting USWDS 2.0 [break point criteria](https://v2.designsystem.digital.gov/utilities/layout-grid/): 

- [ ] Mobile large ≥480px
- [ ] Tablet ≥640px
- [ ] Desktop ≥ 1024px

**Comment by chasechenevert** [comment]
### Sprint 18 plan:
- [ ] Knowledge refresh on designing for grids
- [ ] Codecademy grids lesson
- [ ] Modify mockups accordingly, especially tablet size

**Comment by ifsimicoded** [comment]
@chasechenevert Are we leaning on only mobile and desktop views for now? mobile layout/styles carry through to 1024? or will there be layout mocks for tablet coming -- if so when?

**Comment by amenity** [comment]
@chasechenevert, no need to do tablet mocks for the time being. I'd prefer we apply [breakpoints to specific components](https://medium.com/simple-human/stop-using-device-breakpoints-b11a87e2625c) when necessary rather than produce and maintain more than two sets of mocks. @toribr - thoughts?

**Comment by amenity** [comment]
@chasechenevert did research on breakpoints, specifically focusing on global navigation. Lots learned; will incorporate into future mocks.
