### ISSUE TITLE
Janis v2 lo-fi design: Global navigation 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#853]
Make extremely ordinary. 
 
- Main navigation needs design
- General nav experience on mobile and desktop
- Mobile nav expanded and closed states?
- Subnav Pop-out state on desktop?

**Comment by chasechenevert** [comment]
### Sprint 18 plan:
- [ ] Research different navigation models considering mobile and desktop
- [ ] Sketch: hand sketch some options
- [ ] Mockup: mockup best options, offer at least 3

**Comment by chasechenevert** [comment]
I've drafted up a few different versions to consider with Tori and the team. Going to pause on this until Tori comes back so we can review: 
- [Draft 4](https://gallery.io/projects/MCHbtQVoQ2HCZcMUWtlNkMhJ/files/MCHbtQVoQ2HCZV1UZmxn3m5g)
- [Draft 4 - blue variation](https://gallery.io/projects/MCHbtQVoQ2HCZcMUWtlNkMhJ/files/MCHbtQVoQ2HCZXo0Ie6vjpIX)
