### ISSUE TITLE
Meet to discuss moving permitting content into smaller content types

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#855]
Can we put off Process Pages and start with a "service collection" content type composed of smaller content types a la https://massgovdigital.gitbook.io/knowledge-base/content-types

![IA.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/4aa0e62d-d540-4c17-90ba-9e1def62857a)

**Comment by LauraTrujillo** [comment]
Yes!

**Comment by amenity** [comment]
@LauraTrujillo - can you add @chasechenevert and me to the invite?

**Comment by LauraTrujillo** [comment]
@amenity @chasechenevert done and done!

**Comment by amenity** [comment]
We decided that we are going to use something closer to the Mass.gov content model. This involves:
- New content type: #867
- Transition existing PermittingATX content #353
- Specs for Service Collection #868

![img_7730](https://user-images.githubusercontent.com/1463708/48033739-1e66ee80-e122-11e8-9a2b-cd58ad651cda.JPG)
