### ISSUE TITLE
Create Docker image for worker process

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#859]
- Get Travis to build worker images
- Push them to Heroku

Aha! Link: https://desi1.aha.io/features/RT-161

**Comment by sergiogcx** [comment]
I ran into an issue when trying to deploy my PR to get it ready for master, when I did I noticed a build error and missing pages. For context, the test script will gather all the routes (in all languages) from the graphql api, and try to ping each route. If the route returns an HTTP error code other than 200, it is considered an error. (https://github.com/cityofaustin/janis/pull/276)

This is the build error, notice the URI:

```
TypeError: Failed exporting HTML for URL services/this-is-a-test-page (src/com  ponents/Pages/Service): Cannot read property 'phone' of null
  
  - static.adb39964.js:5258 ContactMap
    /app/dist/static.adb39964.js:5258:28
  
  - react-dom-server.node.development.js:2135 processChild
    [app]/[react-dom]/cjs/react-dom-server.node.development.js:2135:14
  
  - react-dom-server.node.development.js:2061 resolve
    [app]/[react-dom]/cjs/react-dom-server.node.development.js:2061:5
  
  - react-dom-server.node.development.js:2380 ReactDOMServerRenderer.render
    [app]/[react-dom]/cjs/react-dom-server.node.development.js:2380:22
  
  - react-dom-server.node.development.js:2354 ReactDOMServerRenderer.read
    [app]/[react-dom]/cjs/react-dom-server.node.development.js:2354:19
  
  - react-dom-server.node.development.js:2726 renderToString
    [app]/[react-dom]/cjs/react-dom-server.node.development.js:2726:25
  
  - index.js:519 renderToStringAndExtract
    [app]/[react-static]/lib/static/index.js:519:68
  
  - getConfig.js:278 Object.renderToHtml
    [app]/[react-static]/lib/static/getConfig.js:278:14
  
  - index.js:556 _callee8$
    [app]/[react-static]/lib/static/index.js:556:39
  
  - runtime.js:62 tryCatch
    [app]/[babel-runtime]/[regenerator-runtime]/runtime.js:62:40

```

The Test I wrote also shows those very links being a problem:

```
  Basic Availability
    ✓ Should return data from API (1306ms)
    ✓ Main Site Should work (559ms)

  All Routes
    ✓ Routes Should be loaded in memory
    Single Pages
      ✓ Tested all single pages
We are done, clearing routes.


  4 passing (4s)

ERROR: http://janis-austin-gov-preview.s3-website-us-east-1.amazonaws.com/janis-staging-pr-276/services/set-out-your-leaves-grass-and-branches-for-pickup
Response Status Code: 404
ERROR: http://janis-austin-gov-preview.s3-website-us-east-1.amazonaws.com/janis-staging-pr-276/services/this-is-a-test-page
Response Status Code: 404
```

I am thinking I recently pulled the production database into staging, and wonder if this could have affected the routes. Will check again as soon as we are finished with the current sprint.

**Comment by sergiogcx** [comment]
Perhaps if these two routes are not needed, we could remove them and re-build the site.

**Comment by oliver2g** [comment]
@sergio pls estimate this

**Comment by sergiogcx** [comment]
Personal Notes:

- Heroku Worker:
	- Open Branch
	- Checkout code from GitHub repo.
	- Add Heroku helper shell file
	- Put Dockerfile together
	- Put dependencies together
	- Check: Janis workers have AWS credentials
	- Test: Build of container on Heroku
	- Test: Build of Janis

**Comment by sergiogcx** [comment]
This has been done in PR:
https://github.com/cityofaustin/janis/pull/382

And for rotations, in PR:
https://github.com/cityofaustin/janis/pull/383

**Comment by sergiogcx** [comment]
Closing this issue, the deployment pipeline will be handled through issue #858
