### ISSUE TITLE
Trigger worker processes from Joplin on content update

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#860]
Aha! Link: https://desi1.aha.io/features/RT-160

**Comment by sergiogcx** [comment]
This is one in PR:
https://github.com/cityofaustin/joplin/pull/226

Can be tested here:
http://joplin-staging-pr-226.herokuapp.com/admin

When merged to Staging, changes will be built on staging bucket. When on Production, Joplin will deploy to the production bucket.

**Comment by sergiogcx** [comment]
This has been merged to master, it can be tested.

You can trigger a build on master:
http://joplin-staging.herokuapp.com/

See the new build in a test bucket:
http://janis-lab-staging.s3-website-us-east-1.amazonaws.com/
