### ISSUE TITLE
Janis 2.0: Design Information Page MVP

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#864]
- [OPO content for the mock](https://docs.google.com/document/d/1UFLOvMU75FIhLdHdu2qJl4n7QqaFnQb5-lVj1S0AJHM/edit)
 - [Tori's draft of the  Information Page author interface](https://github.com/cityofaustin/techstack/issues/892#issuecomment-440008368).
 - [Content model spec](https://docs.google.com/spreadsheets/d/1ZkH93F4tJ0_Zjx4t8k6k6TgwSlOh8u8ejWmegE6WqH0/edit?ts=5c3e0a70#gid=1232003425).

**Comment by amenity** [comment]
@chasechenevert - sized as a medium assuming that this is basically plugging in the OPO content to the current Service Page template. Sound right?

**Comment by chasechenevert** [comment]
Placing the direct link to the MVP within the stickersheet: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/6cb0a2ed-679d-489c-b6c1-bf8b2022d3bb/Information-MVP-web/
