### ISSUE TITLE
Low-fi design for Service Collection

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#868]
This is an aggregated view of Service Pages and Information Pages.

Mass.gov example:
![screencapture-mass-gov-nursing-licenses-2018-11-15-12_39_29 1](https://user-images.githubusercontent.com/1463708/48575434-8c0bdb00-e8d7-11e8-8fc4-639909e189c6.png)

Aha! Link: https://desi1.aha.io/features/RT-155

**Comment by chasechenevert** [comment]
See this issue #1202 to see how service collections are styled and displayed on topic and sub-topic pages
