### ISSUE TITLE
Janis v2 Design: Global Components Storybook

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#870]
All General components need to be revisited in terms of styles / mark up to adhere to the new Janis 2.0 skin
1. Recreate markup and styles as needed to develop new storybook component. Be considerate of mobile, tablet, desktop versions. Be considerate of right to left text requirements.
2. Review final storybook component with @chasechenevert for revisions/approval.

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] theme level navigation [ mock link here ]

- [ ] topic level navigation [ mock link here ]

- [ ] breadcrumbs [ mock link here ]

- [ ] translation and outbound links [ mock link here ]

- [ ] homepage banner [ mock link here ]

- [ ] homepage notification banner [ mock link here ]

- [ ] page header (based on developer judgement)

- [ ] section headers (based on developer judgement)

- [ ] feedback form [ mock link here ]

- [ ] footer / list links  [ mock link here ]

- [ ] tile groups and tile group set [ mock link here ]
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://desi1.aha.io/features/RT-154

**Comment by ifsimicoded** [comment]
@chasechenevert @amenity please add mock up links as you have them

**Comment by amenity** [comment]
@chasechenevert - do you have mocks for these, or should I create issues for each mock?

**Comment by oliver2g** [comment]
@chasechenevert and @pibemillo this is an old issue that sounds like it's being worked on now. Is it still current (i.e. are there newer issues that make this redundant)? If these items are in progress, can you estimate this issue and move it to the appropriate pipeline? For now, I'm putting it in the Short term backlog.

**Comment by pibemillo** [comment]
This issue is still relevant, although we may want to do an inventory of current/existing components and what will be needed for the Janis 2.0 release. I can connect with @chasechenevert to better identify this.

A good chunk of these items/components are available, but are not in storybook yet.  

http://janis-staging.herokuapp.com/storybook/
alpha.austin.gov/storybook/

I'll need to cleanup and remove legacy stuff from what's currently there...

**Comment by easherma** [comment]
@pibemillo can you update us on the status of this issue when you have a moment? 
It would be great to know how far along you got, and what you see as what the steps would be.

**Comment by easherma** [comment]
related: https://github.com/cityofaustin/techstack/issues/1628

**Comment by easherma** [comment]
This could also be useful for joplin for the author interface.
