### ISSUE TITLE
Janis v2 Design: Service Page Components Storybook

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#871]
All Service Page components need to be revisited in terms of styles / mark up to adhere to the new Janis 2.0 skin
1. Recreate markup and styles as needed to develop new storybook component. Be considerate of mobile, tablet, desktop versions. Be considerate of right to left text requirements.
2. Review final storybook component with @chasechenevert for revisions/approval.

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] steps [mock](https://xd.adobe.com/view/f858965b-0df2-44fc-54ee-324d8ce6d342-8e69/)

- [ ] contact details and contact sub components [mock](https://xd.adobe.com/view/f858965b-0df2-44fc-54ee-324d8ce6d342-8e69/)

- [ ] html from admin / body content from joplin WYSIWYG editor [ mock link here ]

- [ ] tiles [mock](https://xd.adobe.com/view/f858965b-0df2-44fc-54ee-324d8ce6d342-8e69/)

- [ ] recollect / trashy [ mock link here ]
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://desi1.aha.io/features/RT-153

**Comment by ifsimicoded** [comment]
@chasechenevert @amenity add mock links above as you have them

**Comment by oliver2g** [comment]
@chasechenevert and @pibemillo has this already been done (i.e. is this issue still needed)?
