### ISSUE TITLE
Janis v2 Design: footer

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#875]
Footer maybe needs to be reskinned -- the bolded font of the Call 311 section heading and the differing shade of blue in the footer (doesn't match the header) in the [mock here](https://xd.adobe.com/view/f858965b-0df2-44fc-54ee-324d8ce6d342-8e69/) leads me to believe it hasn't really been skinned to match the Janis 2.0 style

**Comment by chasechenevert** [comment]
I've done some consideration around the mobile footer, but I still need to explore: 
- [ ] Super footer idea (mobile, tablet, desktop)
- [ ] Desktop footer

**Comment by amenity** [comment]
See also #315
