### ISSUE TITLE
Janis v2 Design: Implement Service Page phase 1

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#876]
Currently: https://alpha.austin.gov/es/services/bulk-item-pickup

Should look like: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/ce9e7492-b75b-472c-9dab-98d7bd1843ba/Service-MVP-Web/

https://github.com/cityofaustin/janis

If we change this to point to joplin.herokuapp.com then it will grab prod data
https://github.com/cityofaustin/janis/blob/db904e59bed52fa729bb6456a3331c563145740e/scripts/serve-local.sh#L25

**Comment by pibemillo** [comment]
Merged into master thanks to @briaguya merge party
