### ISSUE TITLE
404 page for Set out your leaves, grass, and branches for pickup

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#878]
**Describe the bug**
<I see a 404 page when I tried to view 'Set out your leaves, grass, and branches for pickup' live.>

**https://janis-staging.herokuapp.com/en/services/set-out-your-leaves-grass-and-branches-for-pickup**

**To Reproduce**

1. Go to Wagtail admin dashboard
2. Click on 'view' live underneath Set out your leaves, grass, and branches for pickup

**Current behavior**
<404 page. No tile on theme page for Set out your leaves, grass, and branches for pickup either.>

**Expected behavior**
<Be taken to a live version or published page for Set out your leaves, grass, and branches for pickup>

**Screenshots**

**Device**
<! Mac desktop>

**Browser**
<!Chrome
<img width="1118" alt="screen shot 2018-11-06 at 12 09 39 pm" src="https://user-images.githubusercontent.com/30263897/48084295-ee205e00-e1bc-11e8-9924-0ad0d2d4d0b4.png">
<img width="1184" alt="screen shot 2018-11-06 at 12 09 50 pm" src="https://user-images.githubusercontent.com/30263897/48084296-ee205e00-e1bc-11e8-9a8e-9328737ba8f9.png">

>

**Additional context**

**Comment by LauraTrujillo** [comment]
Related to issue #796

**Comment by amenity** [comment]
Should be fixed by #886.

**Comment by LauraTrujillo** [comment]
Yep, that did it!
