### ISSUE TITLE
Review first draft residential toolkit service pages

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#884]

**Comment by srigdon** [comment]
Steps: 

1. Clean up draft documents, reach out to Susan Barr in DSD to request technical review. 
2. Set a timeline for her review and @LauraTrujillo's. 
3. Incorporate edits as needed. 
4. Create and format pages in Joplin.

**Comment by LauraTrujillo** [comment]
https://drive.google.com/drive/folders/1iDo25QbSkXWuwKtLteIKVHnSefEsmvE9?hl=en
