### ISSUE TITLE
Correct spelling of "accordion"

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#887]
**Acceptance criteria**
- [ ] on service page template in step block, it's spelled "accordion"

**Describe the bug**
On the Service Page template in the steps block, it says "A step may have a basic text step or an options accordian which reveals two or more options"

"Accordian" should be spelled "accordion."

Example URL: https://joplin.herokuapp.com/admin/pages/19/edit/

**Comment by briaguya** [comment]
Low hanging fruit but it'll fall to the ground after @Niicck's migration changes

**Comment by desigonz** [comment]
Submitted [PR 290](https://github.com/cityofaustin/joplin/pull/290) with this fix.

**Comment by amenity** [comment]
![](https://thumbs.gfycat.com/MixedOilyIcelandichorse-size_restricted.gif)
