### ISSUE TITLE
Joplin Alpha: Design Information Page MVP template

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#892]

**Comment by toribr** [comment]
![information page draft](https://user-images.githubusercontent.com/3790067/48729208-abb74200-ebfc-11e8-8c3d-0df8b697bcba.png)
This is a draft, but should be close enough to  facilitate discussions! 

Presumptions:
• description is optional
• Options are stand-alone 
(not a numbered step)
• May require the ability to add another
“additional” content module?
• Content modules & options should allow
repositioning (order).

**Comment by amenity** [comment]
This may be complete, but we need to wait for #863
