### ISSUE TITLE
Fix Joplin staging

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#895]
Right now, Joplin staging looks very broken - styles, missing labels, etc.
<img width="1559" alt="screenshot 2018-11-20 15 19 05" src="https://user-images.githubusercontent.com/1463708/48803552-e4781980-ecd7-11e8-99e3-f4e0c08fc54e.png">

We also want the new users from the production site migrated over. 

Please do a fresh rebuild/deploy and a database migration.

**Comment by sergiogcx** [comment]
It looks like it was missing a javascript file: `createContentModal-b38ab0272c89e7b4d54e.js`

It was present in the server, but not present in s3:
https://joplin-staging.herokuapp.com/static/webpack_bundles/createContentModal-b38ab0272c89e7b4d54e.js

To fix, I used the command (to upload all static files to s3):
`heroku run --app joplin-staging -- python ./joplin/manage.py collectstatic --noinput`

After that, the visuals went back to normal.

**Comment by sergiogcx** [comment]
The database was copied using the following command:

```
heroku pg:backups restore $(heroku pg:backups public-url --app joplin) --app joplin-staging
```

Ideally, if using during a busy day, you may want to turn on maintenance mode on staging:

```
heroku maintenance:on --app joplin-staging
heroku maintenance:off --app joplin-staging
```

This way no new data will be lost in staging.
