### ISSUE TITLE
DevOps docs update

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#897]
Follow up to https://github.com/cityofaustin/techstack/issues/734, add I have a few notes into a PR for joplin after #895.

Aha! Link: https://desi1.aha.io/features/RT-143

**Comment by sergiogcx** [comment]
This has been done in PR:
https://github.com/cityofaustin/janis/pull/382

And for rotations, in PR:
https://github.com/cityofaustin/janis/pull/383

**Comment by sergiogcx** [comment]
Closing this issue, the documentation is available in the worker folder. New documentation will be available as the PR is tested and elaborated.
