### ISSUE TITLE
Police Oversight form: Design form

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#901]
Mocks for dev of the next iteration of the OPM complaint/compliment form. Won't diverge much from out of the box US Forms System, but will need specs for anywhere it does. 

- [Prototype](https://projects.invisionapp.com/share/FZNP0LRHYV4#/screens/315840227)
- [Service Blueprint](https://drive.google.com/drive/u/1/folders/1LSJaoRSdLiIiSjXp8NcqzMM7lJExUI4I)
- [Police Advisory Working Group Recommendations](https://drive.google.com/file/d/1qi2g1Yz3D52FLdQlcmYN9sE8LcRSn82H/view?usp=sharing) - Further Together team's "What we learned about the complain process: final report" begins on page 44
- [ODD promo video](https://drive.google.com/file/d/1aHsSWo_BDBFg4kGpzEk-SOPgNvb1aKdg/view) 
- [Google Drive](https://drive.google.com/drive/u/1/folders/1LSJaoRSdLiIiSjXp8NcqzMM7lJExUI4I)

Design
- USWDS form [controls](https://designsystem.digital.gov/components/form-controls/) & [templates](https://designsystem.digital.gov/components/form-templates/)
- [Resources on digital form UX & best practices](https://docs.google.com/spreadsheets/d/1ov27dpfaFW9nk0mVIpshj5Sj5mxoKaQafk8W4oyvqws/edit#gid=895936753)
- [Sketch file](https://drive.google.com/open?id=1KEvdDmIH_H1BZVduDVVMWXG3ecsosjR7)

See also
 - Chicago's [Civilian Office of Police Accountability](https://www.chicagocopa.org/) has an [online complaint form](https://www.chicagocopa.org/complaints/intake-form/)

**Comment by chasechenevert** [comment]
## Draft 4
- Gallery screens for collecting feedback: https://gallery.io/projects/MCHbtQVoQ2HCZcMUWtlNkMhJ/files/MCHbtQVoQ2HCZRe74CRes39P
- XD Prototype (clickable): https://xd.adobe.com/view/be641505-4589-4777-51c8-d574d9bb4a7d-c855/
- XD Spec: https://xd.adobe.com/spec/9731b7d7-51fe-4531-69da-efa93b483be5-e100/

**Comment by chasechenevert** [comment]
## OoPO Draft 5—Tweaked landing design

* Gallery screens: https://gallery.io/projects/MCHbtQVoQ2HCZcMUWtlNkMhJ/files/MCHbtQVoQ2HCZSVtVxIyKAQ5
* XD Prototype (clickable): https://xd.adobe.com/view/e351865d-cda7-4965-78af-364266c04e26-9560/
* XD Spec: https://xd.adobe.com/spec/3d3b6e88-bfe0-4e44-49e1-e34e08220d55-4b0a/

**Comment by chasechenevert** [comment]
## OoPO Form feedback, December 17, 2018

**Draft 6—DEMO 1**
- XD Demo: https://xd.adobe.com/view/72f51fc9-14d8-4edd-6166-ee76770643ae-04c4/
- Gallery: https://gallery.io/projects/MCHbtQVoQ2HCZcMUWtlNkMhJ/files/MCHbtQVoQ2HCZdz7to4chejz
- Screenshots (Drive): https://drive.google.com/drive/u/0/folders/1mwQYp45nm9ypVU82h8k3FxTuaFkmKD4j

**Overall**

- Farah’s team underscored that they their priority is: incident description, time range, general location. Anything else is nice to have, but not necessary.
- The ability for users to anonymously fill out the form is critical. How might we allow someone to be both anonymous, but also want to be contacted/have a way to contact OoPO about their complaint?
- Considering the anonymity and the minimum viable content (MVC?), how might we streamline the flow even more?

**Tell us about you**

- Consider adding the 'How did you get to this form" to the end of this screen

**Compliment: Review**

- Comment on the "next" button should now read "File My Complaint" or "Submit Complaint" to signify the end of the process.
- Perhaps the "how you found us" could be removed from this screen as it seems unlikely anyone would want to return to that page.

**Complaint: Success**

- email this case number to me (maybe they changed their mind)
- Additional content that says something like: if you think of other remarks you'd like to add to this complaint, please call # and have this case number ready. (we'll need to validate with OoPO that's do-able)

**About officer(s):**

- Are there really non-binary cops? Seems like this might be confusing to most of the public.

**Comment by toribr** [comment]
![oopo_landing_tori](https://user-images.githubusercontent.com/3790067/50105118-697c2300-01f1-11e9-9254-d95813e466f9.png)
Here's an alternative landing to discuss.
