### ISSUE TITLE
Determine bucket deployment standards/rules

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#906]
- Bucket naming conventions
- Bucket locations
- Bucket plans - e.g. different regions

Aha! Link: https://desi1.aha.io/features/RT-139

**Comment by sergiogcx** [comment]
![Janis Production Architecture (1).png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/70ffca0f-6bf5-44b9-9ca3-088074a69576)

The README is located here:
https://github.com/cityofaustin/janis/tree/859-sg-janis-worker/worker
