### ISSUE TITLE
Joplin Alpha: Add 'top service' checkbox to Service Page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#908]
The Service Page should have a short description field prior to the steps.

![service page do-all v 1 switch description](https://user-images.githubusercontent.com/1463708/48722199-13fc2880-ebe9-11e8-95ad-6e032e7ea85f.png)

Aha! Link: https://desi1.aha.io/features/RT-138

**Comment by amenity** [comment]
@toribr - removing this from Joplin Alpha since @briaguya explained that we don't yet have the logic implemented that forces a page into service collections. (We only have “related links,” and that logic isn’t the cleanest.) So including this in the Joplin UI would be putting the cart before the horse.

**Comment by briaguya** [comment]
obsolete as of new data model
