### ISSUE TITLE
Choose content for Information Page mocks

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#909]
Pick two pieces of permitting content for @chasechenevert to use in #864.

**Comment by srigdon** [comment]
@chasechenevert Both of the sample pages below are blended, information (what do I need to know) and service (what do I need to do). They're undergoing edits and fact checking, so final content will be different than what you see here. 

Permitting content type 1: https://docs.google.com/document/d/1lSAyYDeWZHf2Y5gXZ3bPJI459yTnTIRnxw03EceAxr4/edit

Permitting content piece 2: 
https://docs.google.com/document/d/1PU5sMWelzPJUI2nrGlVzbwj2j8cNEw5axNf-p_PnId4/edit
