### ISSUE TITLE
Police Oversight form: Review content and workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#911]
Re-size as needed. 

See the [Police Oversight and Accountability Form epic](https://github.com/cityofaustin/techstack/issues/913) for more info.

**Comment by amenity** [comment]
@LauraTrujillo - I think this turned out to be a duplicate of #916, yeah?

**Comment by LauraTrujillo** [comment]
@amenity essentially- but #916 seemed to be focused on landing page content and this issue seems bigger picture.

**Comment by srigdon** [comment]
See comments here: https://docs.google.com/document/d/1CK7zYEN6O_2aMVJ5DiT80r2BhZ5frRAxHUpbsBo5Uhw/edit#
