### ISSUE TITLE
Review notes from GOV.UK call

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#920]
I cleaned up [the doc](https://docs.google.com/document/d/1gr4Cly5Cn8wN2W0K9CdTiVhYyi7l9LGn_4fi5ZDfwGY/edit#)...Ready for your 2i review. 🤓 Just a quick scan for anything I missed or messed up would be great. 

I left your original notes about the publishing workflow at the bottom of the doc b/c didn't want to mis-incorporate them.

**Comment by srigdon** [comment]
Looks great! @briaguya, can you take a quick look and update the doc with your recording when it's available? Thanks!

**Comment by amenity** [comment]
Thanks, @srigdon ! & Brian's 2i is covered here: https://github.com/cityofaustin/techstack/issues/921
