### ISSUE TITLE
Police Oversight form: User testing and research

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#923]
Once the prototype of the form is up, @toribr will guide user testing to inform improvements.

We've discussed testing:
- Whether the "I agree..." checkbox at the beginning of the form encourages more accurate/comprehensive/comfortable reporting
- The demographic information questions, see #925
- How do we reassure them that their complaint can be anonymous?

Aha! Link: https://desi1.aha.io/features/RT-133

**Comment by amenity** [comment]
@ChristopherLuedtke - @chasechenevert mentioned that you have recommendations for additional points to test.

**Comment by oliver2g** [comment]
removed #1369 from this epic since it is an ongoing task for OPO user testing
