### ISSUE TITLE
Medium Post | A Tale of Three CMSs

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#927]
What approaches are different gov teams taking to create and manage their digital content?
 - GOV.UK: Homegrown (API-based RoR)
 - Boston.gov and/or Mass.gov: Major open source CMS (Drupal)
 - Orlando.gov: Vendor CMS (OpenCities)

## To do

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] Get ☝️ teams on board - GOV.UK ✔️ | Boston.gov, Mass.gov, Orlando.gov ✉️ sent

- [ ] Compose questions

- [ ] Draft

- [ ] Share for feedback

- [ ] Publish
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://desi1.aha.io/features/RT-131

**Comment by LauraTrujillo** [comment]
Close... for now.
