### ISSUE TITLE
Police Oversight Form: Investigate versioning options 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#931]
https://support.knack.com/hc/en-us/articles/231630567-Create-a-Version-History-for-Records

**Comment by sergiogcx** [comment]
We do have a few options,

1. Create two identical tables in knack for complaints and compliments: 
- This would mean that the backend would have to create two records per entry. 
- While field names remain the same, field numbers are different. To insert data, we use field numbers as per Knack documentation. This creates exponentially large complexity in mapping form data to two knack tables.
- While giving read-only access to other users is possible. Data protection is an issue, anyone with admin access will have full access and compromise the integrity of the complaint. Ideally these records should be separate from knack.

2. Upgrade to Pro plan in Knack.
- The Pro plan has versioning included, at a higher cost.
- From the website we can read:

[Full Article Here](https://support.knack.com/hc/en-us/articles/226589228-Working-with-Records#view-record-change-history)
https://support.knack.com/hc/en-us/articles/226589228-Working-with-Records#view-record-change-history

```
4.3. View Record Change History
A "Record History" feature is available on Pro plans and above, which allows you to access a complete history of every record change.

To view a record's change history, first click on the edit icon to the left of that record:
```

3. Dump JSON objects into another database. 
- We can only keep the original version of the form.
- Easiest to implement at almost no cost.
- Easy to move from one technology or provider to another.

**Comment by amenity** [comment]
Awesome research, @sergiogcx 🤓 🙌
