### ISSUE TITLE
Police Oversight Form: Implement file upload UI

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#936]

**Comment by briaguya** [comment]
I've moved to using [filepond](https://github.com/pqina/filepond) to do this. In order to implement this correctly we need to configure our file upload endpoint to work well with that, there's an example here: https://github.com/pqina/filepond-boilerplate-php.

**Comment by amenity** [comment]
No longer relevant; see https://github.com/cityofaustin/techstack/issues/1003.
