### ISSUE TITLE
Police Oversight Form: Implement file upload endpoint in Forms API

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#937]

**Comment by sergiogcx** [comment]
Hello @amenity @briaguya 

The endpoint should be ready, I forgot to document it here yesterday, but it should be ready for uploads to knack:

Endpoint:




Response Structure:

```
response = {
        "status": "error",
        "status_code": 403,
        "knack-file-id": "",
        "message": "Failed to upload file."
}
```


Success Example Response:

```
{
	"knack-file-id": "5c0f8a58c544b1085cef5766",
	"message": "https://api.knack.com/v1/applications/5c09c4327d39ba110484db92/download/asset/5c0f8a58c544b1085cef5766/12112018_83e2198aa7f81c4c51f5f2aa992ae0f6d2e41bcdbc7d67cd97fa63b231cbe6b7.jpg",
	"status": "success",
	"status_code": 200
}
```

Error Example:

```
{
	"knack-file-id": "",
	"message": "No file part",
	"status": "error",
	"status_code": 403
}
```

    Sample Knack File Ids:
    5c0f889017084610430cf964
    5c0f86708515b80857c9cf59
    5c0f8a58c544b1085cef5766

**Comment by sergiogcx** [comment]
**Update** @briaguya 

I didn't previously mention it, but the endpoint looks for the `file` form key:

![Fullscreen_12_12_18__8_19_PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/e2f958ab-426e-42d1-80a9-9ec23038cee7)

**Comment by amenity** [comment]
@sergiogcx @briaguya - what do you want to do with this issue now that we're moving away from Knack for this form?
