### ISSUE TITLE
Police Oversight Form: Quick fix "placeholder" accordion labels for witnesses

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#938]
Delete officer and witness placeholder text. Can be blank for now.

**Comment by amenity** [comment]
@chasechenevert @toribr - talking this over with Eric and since doing #1094 (Office 1, Officer 2...) is a big lift, Eric suggested we put an icon there? Other option is leave it blank.

**Comment by toribr** [comment]
I think it's fine to leave blank for now.

**Comment by amenity** [comment]
Thanks! @easherma ☝️

**Comment by amenity** [comment]
@easherma looks like you fixed this?

**Comment by easherma** [comment]
si
