### ISSUE TITLE
Police Oversight form: Desktop design for each form component

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#951]
Add to sticker sheet.

**Comment by chasechenevert** [comment]
Our latest thinking is to see how it performs out-of-the-box, then adjust where there are issues. The existing US Forms handles responsive design well from what I can see, but we'll need to pay attention to our custom components in particular.

**Comment by amenity** [comment]
@chasechenevert - let's just close this guy and open any necessary issues when they surface.
