### ISSUE TITLE
Police Oversight form: Design uploaded file review page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#958]
![Screenshot 2018-12-12 11.19.14.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/080591f1-0bed-40e8-bdfb-d13805765650)

**Comment by chasechenevert** [comment]
## Review page: file uploads

- Image preview size here is 48 x 48 px

**Direct links:**
- Gallery screenshot: https://gallery.io/projects/MCHbtQVoQ2HCZcMUWtlNkMhJ/files/MCHtA7U1iMGr699UsuJV1xjLQHaQ2CFjSAI
- XD Spec: https://xd.adobe.com/spec/d6588794-d589-429e-469e-188680224204-a069/screen/9c2dc10e-ebd4-40c4-94e0-ae296b07f6c9/7-Review/
- XD Prototype
![screen shot 2019-01-15 at 3 36 22 pm](https://user-images.githubusercontent.com/7027270/51211525-6604b600-18db-11e9-89fc-f950d28ad6f5.png)

**Comment by amenity** [comment]
Looks good!
