### ISSUE TITLE
Police Oversight form: Forms.austin.gov domain

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#964]
Hosted in a bucket.

**Comment by sergiogcx** [comment]
I'm not yet familiar with the process to add a subdomain to `austin.gov`, it appears to me the domain DNS records are not being handled by AWS Route 53. It would seem to me the city handles their own DNS records:

```
id 14496
opcode QUERY
rcode NOERROR
flags QR RD RA
;QUESTION
austin.gov. IN NS
;ANSWER
austin.gov. 21599 IN NS coadns2.austintexas.gov.
austin.gov. 21599 IN NS coadns1.austintexas.gov.
;AUTHORITY
;ADDITIONAL
```

Anyway, I am looking to add a CNAME for a bucket:

`police-monitor-website-production.s3-website-us-east-1.amazonaws.com`

Could anyone direct me to any documentation on where to do this?

**Comment by amenity** [comment]
@wilhitem - will you contact someone in CTM to determine who/how we can get this domain?

**Comment by sergiogcx** [comment]
A CloudFront distribution has been created, this allows us to switch between buckets without switching DNS records:

	https://d1tox4tz6kpvtt.cloudfront.net/


A ticket has been crated, requested attention to Jim Roberts whom is the point of contact for adding a subdomain to austin.gov.

I have not been given (*yet) a ticket reference number, but the request has been made to map `alpha-forms.austin.gov` to `d1tox4tz6kpvtt.cloudfront.net`

**Comment by sergiogcx** [comment]
Also, in preparation for the request I have created a "coming soon" page that we can use to troubleshoot any DNS, SSL settings or bucket configuration.

**Comment by sergiogcx** [comment]
There is a ticket number that has been issued: #1901453

**Comment by sergiogcx** [comment]
I have a reply from CTM:

```
Nice meeting you Sergio, got a few questions - 
Are we looking at forms.alpha.gov as the production URL once alpha-forms.austin.gov is production ready ?
I would like to understand the strategy once you have multiple forms in this environment. Keep in mind forms is a generic name so forms from other tech stacks might also need to use it.
Would it make more sense to have something more specific as forms.alpha.gov/unique_name ? Is that what you were ultimately leaning to ?

I have no issues approving forms.alpha.gov or alpha-forms.austin.gov once we have looked at the bigger picture. We are also reviewing policies on how to handle subdomains and emails that are associated with it. Would you like to be a part of the discussion ? Unfortunately it might need to be after the holidays as most of the team is out the next two weeks.
```

@amenity I don't think we have spoken about the future of the `alpha-forms` domain, is it going to be changed later? If not we can tell him that alpha-forms is going to be production for the next foreseeable future and there will not be any need for change.

Different forms can be contained:

```
https://alpha-forms.austin.gov/ (list of forms)
https://alpha-forms.austin.gov/form_a/
https://alpha-forms.austin.gov/form_b/
https://alpha-forms.austin.gov/form_c/
```
