### ISSUE TITLE
Police Oversight form: Implement frontend mobile design

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#972]
Overrides: https://github.com/cityofaustin/officer-complaint-form/blob/master/css/overrides.css
Specs: https://gallery.io/projects/MCHbtQVoQ2HCZcMUWtlNkMhJ/files/MCEBhHoi0-4v0W_8cA55HNdz

Aha! Link: https://desi1.aha.io/features/RT-126

**Comment by amenity** [comment]
Rumors that @benguhin has volunteered for this... 😏 👨‍🎨

**Comment by benguhin** [comment]
This is true.
