### ISSUE TITLE
Police Oversight form: Implement desktop styles

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#974]
Even though we anticipate that our end users will be overwhelmingly using mobile devices, we want everything pretty for the media and people that find the form that way.

**Comment by benguhin** [comment]
Pull request here: https://github.com/cityofaustin/officer-complaint-form/pull/47

**Comment by sergiogcx** [comment]
Okay, so we are going to work this a little differently. 

I've created two pull requests:

This one implements the changes from PR #47
https://github.com/cityofaustin/officer-complaint-form/pull/48


This one accommodates for using those changes without other media overrides:
https://github.com/cityofaustin/us-forms-system/pull/5

I need a few minutes to test this and I will request your review shortly,

**Comment by sergiogcx** [comment]
This has been tested and approved by @easherma and has been merged to master. It can be closed.
