### ISSUE TITLE
Police Oversight form: Review ordinance, memo, and contract with OPO

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#978]

**Comment by LauraTrujillo** [comment]
@srigdon We have room 3003 reserved on 1/2/19 from 11-2. Will you update the invite and invite Mia Demers and Sara Peralta (as optional), pretty please? And maybe make a note that our meeting should only last an hour so no one stresses out, but Farah will have that time blocked off to work from City Hall.

**Comment by srigdon** [comment]
@LauraTrujillo Absolutely, done!
