### ISSUE TITLE
Police Oversight form: Design confirmation emails

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#987]
Text: https://docs.google.com/document/d/1DjLdEfk8Lq5BnSRjbitoUC3DlADH3x57fXZ2Tzrnaok/edit#

**Comment by sergiogcx** [comment]
Currently the submissions have almost no styling, it was meant as a placeholder.

The background is light-gray, header is dark blue, and black for the rest of the text:

<img width="596" alt="screen shot 2018-12-18 at 1 31 48 pm" src="https://user-images.githubusercontent.com/5282430/50178154-5b013a80-02c9-11e9-9d4f-b10844470e5f.png">

** I haven't implemented the case number, only submission type and the data is shown as a json document without any formatting.

That's more or less where I am at currently,

**Comment by sergiogcx** [comment]
I also forgot to mention, both the user and police oversight receive the same style.

**Comment by amenity** [comment]
Mocks: https://github.com/cityofaustin/techstack/issues/989#issuecomment-459862607
