### ISSUE TITLE
Police Oversight form: Message for resident's complaint confirmation email

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#988]
If a resident supplies an email address, they will receive a confirmation email. 

It will include:
- All information that was submitted by resident
- Case #
- Links to uploaded files

What text should be included in the _**complaint**_ confirmation the resident receives?

**Comment by LauraTrujillo** [comment]
https://docs.google.com/document/d/1DjLdEfk8Lq5BnSRjbitoUC3DlADH3x57fXZ2Tzrnaok/edit#

**Comment by amenity** [comment]
@LauraTrujillo - is this finalized or should it go back in progress?

**Comment by LauraTrujillo** [comment]
Next steps: Getting this into a word doc and sending to Farah and Mia for review.

**Comment by amenity** [comment]
Let's put this in Review/QA and close it when it's ready for @sergiogcx !
