### ISSUE TITLE
Police Oversight form: Form confirmation emails

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#989]
Three emails:
- OPO resource email account (policeoversight@austintexas.gov)
- Resident email address, if supplied
- Internal Affairs resource account, if compliment (internal.affairs@austintexas.gov)

Both emails include:
  - All information that was submitted by resident
  - Case #
  - Links to uploaded files
  - ...?

We'll want different messages in each email.

Aha! Link: https://desi1.aha.io/features/RT-121

**Comment by chasechenevert** [comment]
Here's what I've got: https://xd.adobe.com/spec/6a786d16-7606-4b9d-7c98-0202c57a13eb-1c49/
- Feel free to comment within the Dev Spec if you need to (you don't need an Adobe account to do so, but it is free to sign up and use XD if you want to)
- Let me know if you have any questions as you implement this!

<img width="1538" alt="screen shot 2019-02-01 at 2 46 16 pm" src="https://user-images.githubusercontent.com/7027270/52148744-3fab7e00-2630-11e9-9a5c-898ccbcde9b1.png">

## Notes
I've annotated these notes within the Dev Spec as well.
- You can pull the styles out of the info panel by clicking into a page, then selecting the info icon right side panel
- This is intended to be identical to the form review page with the "Edit" and "Add" buttons, and accordion toggles buttons removed. There's a light gray container behind the answers.
- Minimum width: 350 px (iPhone 5s)
- Max width: 600 px

**Comment by amenity** [comment]
@sergiogcx - is there anything else we need on these?

**Comment by sergiogcx** [comment]
Unless there are any new requests, we should be all done.

I could spend more time if you want me to, if you could point out any specifics.
